### ISSUE TITLE
Hyphy command line error

### ISSUE THREAD

**Issue by va89fa** [veg/hyphy#1000]
Hello,
Actually I had used hyphy selection analysis on windows/desktop previously. but now I have decided to clone hyphy from github, and use command line prompt.
I have read the instructions on command line issues on hyphy website, is it referred to command prompt on Mac system?
Sorry if my issue is simple. I haven't used command line much before, so I couldn't run hyphy yet. in fact, after opening the command prompt from github desktop, no directory which I use is accepted.
the present directory on command prompt is :

C:\Users\Vafa\Documents\GitHub\hyphy>

what should be written after ">" sign to execute the analyses?
is there something wrong with installation, that my commands could not be executed?

**Comment by stevenweaver** [comment]
Dear @va89fa, 

HyPhy > 2.2.4 is not officially supported on Windows. We hope to reintroduce support in the future.

Best,
Steven
