### ISSUE TITLE
Fialed to pass custom parameters to FUBAR.

### ISSUE THREAD

**Issue by Zjianglin** [veg/hyphy#1003]
Dear developers,
      I'm tring to use the `hyphy fubar` to perform the positive selection of some genes.  I used the CMD `hyphy fubar --code Universal --grid 21 --chains 12 --concentration_parameter 0.1 --samples 1000 --chain-
length 5000000 --burn-in 2500000  --alignment nals/OG0001920.fasta --tree Gene_Trees/OG0001920_tree.txt`. However, some parameters weren't been passed in.

After checking result("OG0001920.fasta.FUBAR.json"), I can see that the `grid` and `concentration_parameter` were passed in but the others were not. How could I solve this problem? thank you.

Below is the settings from `OG0001920.fasta.FUBAR.json`:
```
"settings":{
   "burn-in":1000000,
   "chain-length":2000000,
   "chains":1,
   "concentration":0.1,
   "grid size":21,
   "method":"Variational-Bayes",
   "posterior":0.9,
   "samples":100
  },

```

**Comment by spond** [comment]
Dear @Zjianglin,

In _Variational-Bayes_ mode most of the options you supplied are not applicable. Specifically, `burn-in`, `chain-length`, `chains` only apply to the other two methods: `Metropolis-Hastings` or `Collapsed-Gibbs`

Best,
Sergei

**Comment by Zjianglin** [comment]
Thank you for timely response. 

However, I don't find any method choice on FUBAR at [DataMonkey](http://www.datamonkey.org/fubar) , but the `burn-in`, `chain-length`, `chains` options could be adjusted customly. Why is this?

By the way, is there any documents of `Hyphy` for these options explanation. Since I don't find similar docs at offical website and github wiki. The tutorial at website seems focused on interactive mode usage.  Thank you.

**Comment by spond** [comment]
Dear @Zjianglin,

This seems like a bug with the Datamonkey interface. @stephenshank : can you look into fixing the issue in the next release? For Datamonkey, `Variational-Bayes` should be the default and no other options shown.

Only the command line version of HyPhy should support other methods.

Best,
Sergei

**Comment by Zjianglin** [comment]
Okay, thank you very much. @spond
