### ISSUE TITLE
Meme error - no results

### ISSUE THREAD

**Issue by brori-pei** [veg/hyphy#1004]
Hi. I attempted to analyze patterns of diversitying selection in 2 datasets: HCV genomes (257 sequences: 3016 codons) and YFV genomes (147 genomes: 3412 codons). The analyses ran for several days but, upon completion (no longer visable on the job list) no e-mail links to the results were sent. Checked the spam folder and not there either. Repeated to process using a different e-mail address. Same problem. Any suggestions? Thanks!

**Comment by spond** [comment]
Dear @brori-pei,

Last week, we were upgrading our server infrastructure. It is possible that the jobs you had running were killed during master node migration. 

I don't see any results that may be HCV (please rerun it), but I think this could be your YFV analysis (unzip and view in vision.hyphy.org/meme)

Best,
Sergei

[5d53de4ab5ec7b436fd349ed.MEME.json.zip](https://github.com/veg/hyphy/files/3516040/5d53de4ab5ec7b436fd349ed.MEME.json.zip)

**Comment by brori-pei** [comment]
Hi. This is not my YFV data. I will attempt both analyses again and see what happens.
Thanks. Richard

**Comment by spond** [comment]
Dear @brori-pei,

OK, let me know how that goes. 

Best,
Sergei

**Comment by brori-pei** [comment]
Hi Sergei. The YFV genome analysis has finished. But I did not receieve an email link to the results. The ticket number was 257993. The HCV analysis is still running. Here the ticket number is 257996.
Best. Richard

**Comment by stevenweaver** [comment]
@brori-pei - Thank you for pointing out that you did not receive an email. During the migration, I had forgotten to start and configure the mail server on datamonkey's new head node. I will do that shortly.
