### ISSUE TITLE
Datamonkey tree upload

### ISSUE THREAD

**Issue by vladstevan** [veg/hyphy#1013]
Dear all,
I am sorry if my question is trivial, I am new with hyphy.
I am trying to analyze 553 taxons with 876 nt each. I have generated ML tree already and now trying to check for selection.
Every time when I upload fasta alignment I am asked to upload tree. I have copied tree at the end of fasta in newick format but it is not recognized. I even tried typing BEGIN TREES; TREE= and ;END; but again not working. 
How to upload alignement and tree to the Datamonkey?

**Comment by spond** [comment]
Dear @vladstevan,

The format you describe is `NEXUS` not `FASTA`. For FASTA, the expected format is 

```

>a
ATGATTCAACCTCAGACCCTTTTAAATGTAGCAGATAACAGTGGAGCTCG
AAAATTGATGTGTATTCGAGTCATAGGAGCTAGTAATCAGCGATATGCTC
>b
ATGATTCAACCTCAGACCCATTTAAATGTAGCGGATAACAGCGGGGCTCG
AGAATTGATGTGTATTCGAATCATAGGAGCTAGCAATCGTCGATATGCTC
>og
ATGATTCAACCTCAAACTTATTTAAATGTTGCAGATAATAGTGGAGCTCG
AAAACTAATGTGCATTCGAGTTATAGGAACGAGTAATCGAAAATATGCAA


((a,b),og);

```

**Comment by vladstevan** [comment]
Dear Sergei,
Thank you for a fast response!
That was first format I tried, then I tried nexus as shown in HIV example.
I have uploaded tree with substitution values, as I am used to do in paml,
but should I upload just a structure tree like in your example?
Many thanks Vlad
