### ISSUE TITLE
BUSTED analysis table 

### ISSUE THREAD

**Issue by hayli-g** [veg/hyphy#1014]
To whom it may concern 
I have recently used BUSTED implemented in the datamonkey web server and have the CSV analysis table. However, I am unsure to what the different column labels are referring such as unconstrained likelihood, constrained likelihood, optimised null likelihood, constrained statistic and optimised null statistics. 
I would appreciate any help regarding the interpretation of these columns. 
Kind regards

**Comment by spond** [comment]
Der @hayli-g,

See https://github.com/veg/hyphy/issues/487

Best,
Sergei

**Comment by hayli-g** [comment]
Thank you so much for the swift response
