### ISSUE TITLE
one codon sequence can not be detected when it was inputted together with other 28 sequences

### ISSUE THREAD

**Issue by ybdong919** [veg/hyphy#1015]
one codon sequence can not be detected when it was inputted together with other 28 sequences. 
The sequence is :
>QY6AD9.2
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ATGGGGAGCAAGGATAGAATATCATTGCACCCGCCA
TATGTGAGGGGTTCTCCCCCTTCAGGTCCTGGT---TTGTTGCATTCTGAGCCA------
CTCACTATGCAC------------CATCCGCCTGTTCGGCATGCGCCATATGATATGTTG
CCACACTCCGAAGTTATGGAGCGGAGGCTTGCTGACCAGCAGCTGCAGATGCAGAGGTTA
GACTATGGAAACCGGAGGCTCTCTGACCAGCACACGGAGATGCAAAGGCTGGACTATGAA
AACCAAAGGCTTGCAGCTTCCCATGGGACATTGAGGCAGGAGCTCATTGCAGCACAGCGT
GAACTGCAAGTGTTGCAATCGCAAATTGGCACTGCAGAGGCCAAGAGGGAGCAGCAGATT
CGGGGTGTCGTAGATGAAATTGCTAGGATGGAGGCTGAGCTGCAGGCTGCAGAGCCTCTC
AAGCATGAACTGCAACGAGCGCAGGGTGAGGCTCAGAGCCTGGTTGTTTCTAGGGAGGAG
CTTGTTTCTAATGCGCAGAAGCTGTCTCAAGAACTTCAGAGAACCTTCGCAGATGTGCAG
CAGATTCCAGCTCTGATGTCGGAATTTGAGGGCCTCAGACAA---------GAATATCAG
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------CATTGC
AGGGCCACTTTTGAATGTGAAAAAAAATTATACAATGACCATCTTAAGTCACTTCAAGAG
ATGGAAAATAACTATGCTTCTATGTCTAAAGAAGTGGAAAAACTCCGAGCAGAGCTTACG
AACACTGTTAATGTTAATCAAAGA------AGTAGTGGTTCTTACGGAGGCTCCTCTACT
ACTATGGACAATGAGGCTTATGGCCTTTCTAAGAGACAAAATGCACATGAAGATGGTTAT
GTTGTTTCCCAGGGATATGGTACCCTCCTCACAGCCAGT---------------------
------------------------------------------------------------
---GTTGGTGGCACTACTGCAACTACTACTGGAGCTCAACCTGGTCCGGCTTCTGCAAAC
AATGGGTTTAATGCTCCCAGCTGG------------------------------------
------------------------------------TCAAATTATGATTCATCTGCTGGT
CCTGCTTATGATCCACAGAGGTCTGTTGCTTACGATGCACAGAGGGTGACTGGTGTTGAT
TCGGTTACACAA---TCTGGCTATGATTCACAGAGAGAAGCAAATTTGAATGCT------
------CAATATGATCCACATAGAGGT---ACAGGTTATGGCATGCAGGGAGGTCCAGGT
TATGATGCC------------AGTCGAGACCAAGGTTATGATATGCAGAGACGGCCTGCT
TATAATGCATCC---GGAGCTATTGGCTATGAACCGCAGTCAATAGCTGCTGGTGGTCCT
CATGGACATGCTCTGCCAGTGGAGACT------ATGCTGCCTTATGGATCTACAACACCG
CCGGCTCATAATAGT------GGTGGATATGAGAATTTGCATCAAGCGGTAAACCGA---
---------

I don't know the reason why this sequence can no be found when I input all aligned sequences into Datamonkey website.

**Comment by spond** [comment]
Please provide the entire alignment file. There is insufficient information in your post to determine what went wrong. 

Best,
Sergei

**Comment by ybdong919** [comment]
[29CDS_codon_align.txt](https://github.com/veg/hyphy/files/3616766/29CDS_codon_align.txt)

**Comment by spond** [comment]
Dear @ybdong919,

You have 2 identical sequences in your alignment. Datamonkey will strip identical sequences out because they don't contribute any signal to selection analyses other than to make them run a bit slower.

Best.
Sergei

**Comment by ybdong919** [comment]
No, they are all different. Please see below all names,

>Aduranensis\|XP_015946425.1
>Aduranensis\|XP_015962559.1
>Ahypogaea\|5590XE.1 |  
>Ahypogaea\|KBYC2D.1 |  
>Ahypogaea\|QY6AD9.2 |  
>Ahypogaea\|VC1ZWY.1 |  
>Aipaensis\|XP_016181508.1 |  
>Aipaensis\|XP_016194491.1 |  
>Athaliana\|AT1G67170.1 |  
>Carietinum\|Ca_06001.1 |  
>Ccajan\|KYP76498.1 |   |  
>Gmax\|18G279600.1.p |  
>Gsoja\|KHN13801.1 |   |  
>Gsoja\|KHN14477.1 |   |  
>Langustifolius\|Lup001626.1 |  
>Langustifolius\|Lup026705.2 |  
>Langustifolius\|Lup032436.1 |  
>Ljaponicus\|Lj1g3v3105130.2 |  
>Msativa\|MSAD_269180.t1 |  
>Msativa\|MSAD_314545.t1 |  
>Mtruncatula\|Medtr7g019180.1
>Ptrichocarpa\|017G109700.1.p |  
>Pvulgaris\|008G021400.1.p |  
>Tsubterraneum\|GAU14086.1 |  
>Tsubterraneum\|GAU14087.1 |  
>Vangularis\|vigan.Vang04g02460.1
>Vradiata\|Vradi04g09970.1 |  
>Vunguiculata\|Vigun01g238700.1.p
>Vunguiculata\|Vigun05g023000.1.p

**Comment by spond** [comment]
Dear @ybdong919,

The names don't matter. The sequences themselves are **not** all different.

Best,
Sergei

**Comment by ybdong919** [comment]
Aipaensis|XP_016181508.1  and Ahypogaea|QY6AD9.2 are two genes in different species, although their sequences are same. 
So is there any method or setting to keep both of them?

**Comment by ybdong919** [comment]
Thanks, I think you are right. keeping one seq is OK.
Thanks again!
