### ISSUE TITLE
How can I know the location of a analyzed(dn, ds) site in the alignment ? 

### ISSUE THREAD

**Issue by ybdong919** [veg/hyphy#1017]
How can I know the location of a analyzed(dn, ds) site in the alignment ? 
for example, I have a alignment with 3000 nc char. Using FEL analysis, 735 sites were selectecd and analyzed. As result, the site 340 was found to have significantly positive selection. So  how can I know this site's real location in the alignment ?

**Comment by spond** [comment]
Dear @ybdong919,

It is the same as codon **340** in your alignment. Datamonkey will reject any alignments with stop codons, so if you uploaded 3000 bp long alignments (1000 codons), 1000 codons should have been analyzed. 

Best,
Sergei
