### ISSUE TITLE
question on codon sites with w=NaN, alpha=0, beta=0. 

### ISSUE THREAD

**Issue by ybdong919** [veg/hyphy#1019]
Site | Partition | alpha | beta | omega | alpha=beta | LRT | p-value | Total branch length
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | 1 | 0 | 0 | NaN | 0 | 0 | 1 | 0
2 | 1 | 0 | 0 | NaN | 0 | 0 | 1 | 0
3 | 1 | 0 | 0 | NaN | 0 | 0 | 1 | 0
4 | 1 | 0 | 0 | NaN | 0 | 0 | 1 | 0
5 | 1 | 0 | 0 | NaN | 0 | 0 | 1 | 0
6 | 1 | 0 | 0 | NaN | 0 | 0 | 1 | 0
7 | 1 | 0 | 0 | NaN | 0 | 0 | 1 | 0
8 | 1 | 0 | 0 | NaN | 0 | 0 | 1 | 0

FEL result shows that some codon sites with w=NaN, alpha=0, beta=0. Is this means that there are less three codon to calculate on these codon sites, so that these sites can not be calculated for w, alpha, beta values . Right?

**Comment by spond** [comment]
Dear @ybdong919,

These are invariable sites. All the rate estimates are 0. There is no information for comparative analysis (`p-value = 1`)

Best,
Sergei
