### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by gubrins** [veg/hyphy#1020]
Heys,
I was running some analysis with your website last year. Once I got the .json file, I remember I was able to reuploaded it again into datamonkey and check it again. I'm not finding that option anymore, how could I recheck my analysis?

Regards,
Gabriel

**Comment by stephenshank** [comment]
Dear @gubrins,

You can load the JSON output into our companion site, [HyPhy Vision](http://vision.hyphy.org/). Select the appropriate method and use the "Load" button at the top right portion of the screen.

Please let me know if you encounter any issues.

Best,
Stephen

**Comment by gubrins** [comment]
That's exactly what I was looking for, thanks!
