### ISSUE TITLE
path problems with HYPHYMPI

### ISSUE THREAD

**Issue by susanchacko** [veg/hyphy#1021]
Hi, I recently built hyphy (OpenMP) and HYPHYMPI (OpenMPI) v2.5.1 on a Centos7 system. The hyphy test runs are successful, but HYPHYMPI fails with path issues: e.g. 
---------------------
$ mpirun -np 1 HYPHYMPI /usr/local/apps/hyphy/2.5.1/lib/hyphy/TemplateBatchFiles/GARD.bf
Error:

Master node received an error:Could not read command file from 'libv3/UtilityFunctions.bf' (expanded to '/usr/local/apps/hyphy/2.5.1/lib/hyphy/TemplateBatchFiles/libv3/convenience/libv3/UtilityFunctions.bf') in call to LoadFunctionLibrary("libv3/UtilityFunctions.bf", /usr/local/apps/hyphy/2.5.1/lib/hyphy/TemplateBatchFiles/libv3/convenience/);

---------------------

While all the .bf files exist, the paths being searched are incorrect. 

I've tried setting LIBPATH (as referenced in one of the other issues), but still get the same error. 

All suggestions appreciated!

**Comment by stevenweaver** [comment]
Dear @susanchacko, 

I was able to reproduce your issue. While the issue is being resolved, you may be able to work around the issue by doing the following -

```
cd /usr/local/apps/hyphy/2.5.1/lib/
mpirun -np 1 HYPHYMPI ./hyphy/TemplateBatchFiles/GARD.bf
```

Best,
Steven

**Comment by susanchacko** [comment]
Thank you, this worked. I'll watch the updates for a permanent fix. 

Best wishes.
