### ISSUE TITLE
not getting emails for completed jobs

### ISSUE THREAD

**Issue by jayoung** [veg/hyphy#1023]
hi there,

I've submitted quite a few jobs on the website over the last few days, and have been including my email address to be notified for jobs completing, but am not getting any emails. In fact, I'm not sure I've been receiving emails since I switched to using the new website (which I love, by the way!).

I've checked my spam folder, but don't see anything.  Is it possible the server is not sending the emails?   or, could you tell me what address they would be sent from?   Our institution has another layer of spam filter, and I can ask the IT people if datamonkey emails might be getting blocked upstream of a place I can access.

thanks very much,

Janet

**Comment by stevenweaver** [comment]
Dear @jayoung, 

Thank you for pointing this out. It appears that our institution has blocked outgoing mail from our servers. I will contact our IT division to remedy the issue.

Best,
Steven

**Comment by jayoung** [comment]
Thanks, Steven - that explains it!

**Comment by stevenweaver** [comment]
Dear @jayoung , 

email notifications should now be functional once again. 

Best,
Steven

**Comment by jayoung** [comment]
thanks for the fix, Steven - submitted some jobs today, and got emails for all.  nice!
