### ISSUE TITLE
Branch labels read as node labels?

### ISSUE THREAD

**Issue by AAElbassiouny** [veg/hyphy#1024]
Hi there,

I have been using the command-line HYPHY (current version), and I am trying to test one internal branch for Branch-site test (Yang and Nielsen test). I used Phylotree to label the branch, and I can see the {Foreground} label where it is supposed to be. However, when I run the branch-site .bf, I get this error: 

"Model is not associated with the node:Node15

Function call stack
1 :  LikelihoodFunction test_lf = (filteredData, givenTree);"

I tried running without branch label, and the program runs fine, so I assume that the issue is with the labelling of the branch, and that it is being read as a node label. My question is, does HYPHY need a special character to denote a branch? 

Thanks for your help!

Ahmed

**Comment by spond** [comment]
Dear Ahmed,

Nielsen Yang is a legacy analysis that does not support branch labeling. In our 2011 paper describing Branch site REL, we explain why these older analyses should be retired. We recommend either BUSTED or aBSREL for these types of tests

Best,
Sergei

**Comment by AAElbassiouny** [comment]
Dear Sergei,

Thank you for the response, I appreciate it. I was mainly interested in that analysis because of a fairly recent paper (doi: 10.1038/s41559-018-0584-5) that incorporated a multi-nucleotide mutation correction in that model, and I was curious to try it out. I will give BUSTED and aBSREL a try.

Regards,
Ahmed

**Comment by spond** [comment]
Dear Ahmed,

Ah - that's an interesting paper. I think the authors provide a HyPhy script implementing their model.

You may also want to try https://github.com/veg/hyphy-analyses/tree/master/BUSTED-MH which extends BUSTED to allow synonymous rate variation and multi-hit substitutions (@srwis and @aglucaci  are working on this model extension).

Best,
Sergei
