### ISSUE TITLE
BUSTED doesnt report constrained model statistics

### ISSUE THREAD

**Issue by nahidshokribousjein** [veg/hyphy#1026]
Dear Sergie, 

I have used BUSTED to infer positive selection on my foreground branches which are 4 bees. In the output file, BUSTED found no evidence of positive selection in the selected test branches. By looking at the model statistic, I found that just unconstrained model statistics were reported and accordingly the model statistics per site was also not provided. Could you please explain how this can happen? 

Please note that examined gene is CO1. 

Thank in advance
Nahid

**Comment by srwis** [comment]
Hi Nahid,

This is expected behavior for BUSTED. It only fits the constrained model if it finds evidence of positive selection (ω3 > 1) in the unconstrained model. See Sergei's answer to #424 as well.

Best,
Sadie

**Comment by nahidshokribousjein** [comment]
That makes sense now. Thank you so much for clarification.

**Comment by nahidshokribousjein** [comment]
Hi again, 

In BUSTED paper, authors found the number of sites is the best proxy for sample size for independent sites methods such as BUSTED. I was wondering if this is also correct for RELAX test (which I think is also an independent sites method)? 

Actually both reviewers of our paper criticized that our sample size (which are 4 bee species) are small to infer for relaxation or intensification trend of selection while the genes we tested for, were almost in their entire form? 


Thanks in advance
Nahid

**Comment by spond** [comment]
Dear @nahidshokribousjein,

Sample size (which in this case is probably more like the product of the # species in the test group and the # of sites), and the effect size (differences in selective pressures) contribute to power. If your **entire** alignment is only 4 sequences, then the reviewers are probably quite right. If your **test** set includes 4 species (in a larger tree), then you could have reasonable power.

Best,
Sergei

**Comment by nahidshokribousjein** [comment]
Dear @Sergei, 

Thank you so much for your reply. Following my previous questions, I also aim to compare selection intensity between one host bee species and its specific parasite bee which exhibits effective population size that is an order of magnitude smaller than its host.  For this comparison, my alignment includes 11 bee species in which 2 species are my focal host and parasite and the rest are almost from different bee genera (I have attached my alignments here in which Exoneura robusta is focal host and Inquilina schwarzi is its parasite). I selected host species as reference branch and parasite species as test one. Now I have got three questions:

1)	I was wondering if RELAX method is sharp enough to say anything definitive from such a small set of test branch?

2)	I want to know whether including more bees (from different genera) can solve the problem regarding small test set while those species are selected as unclassified branches during RELAX analyses (as you pointed out in your last reply)?

 3) If the answer of question 2 is yes, are those unclassified branches can bias the selection inferences because they belong to different genera?

Thanks in advance
Nahid

[CO1_aligned by translation_MAFFT.nex.txt](https://github.com/veg/hyphy/files/3701868/CO1_aligned.by.translation_MAFFT.nex.txt)

**Comment by spond** [comment]
Dear @nahidshokribousjein,

1. In principle, RELAX might be able to find a difference but only **if the difference is very pronounced** (the effect size is large). You are effectively comparing &omega; distributions inferred individually from branches. I would recommend that you run RELAX (v3 in Hyphy 2.5) with only **2** &omega; classes. That might increase power and reduce over-parameterization.

2. Not really, unless you can **add** some of them to the test and the reference dataset.

Best,
Sergei

P.S. Your NEXUS example file was not formatted correctly; because you have spaces in sequence names, you need to enclose those in quotes, otherwise they won't be parsed correctly. Sequences also contained premature stop codons, so I could not analyze them to test what's going on.

**Comment by nahidshokribousjein** [comment]
>   Dear @Sergei,
>
> Thank you so much for your time and  clarification. In my previous email,
> I asked you if RELAX is sharp enough to say anything definitive when I
>  want to compare selection intensity between one test branch and one
> reference branch? I have attached my data file here where sequence names
> were enclosed with quotes as you suggested.  Please note that E. robusta is
> a host bee species and I. schwarzi is its parasite one. Sequences belong to
> bees CO1 gene and have been checked in Geneious for any premature stop
> codons.
>
> Github page dose not support the format of my data file so I sent it
> trough this email. I pasted my previous query below in case if you want to
> review it (in blue).
>


> I would be so grateful if you could have a look at them and let me know if
> you have any advice.
>
> Thanks in advance
> Nahid
>

Dear @sergei <https://github.com/sergei>,

Thank you so much for your reply. Following my previous questions, I also
aim to compare selection intensity between one host bee species and its
specific parasite bee which exhibits effective population size that is an
order of magnitude smaller than its host. For this comparison, my alignment
includes 11 bee species in which 2 species are my focal host and parasite
and the rest are almost from different bee genera (I have attached my
alignments here in which Exoneura robusta is focal host and Inquilina
schwarzi is its parasite). I selected host species as reference branch and
parasite species as test one. Now I have got three questions:

   1.

   I was wondering if RELAX method is sharp enough to say anything
   definitive from such a small set of test branch?
   2.

   I want to know whether including more bees (from different genera) can
   solve the problem regarding small test set while those species are selected
   as unclassified branches during RELAX analyses (as you pointed out in your
   last reply)?
   3.

   If the answer of question 2 is yes, are those unclassified branches can
   bias the selection inferences because they belong to different genera?

Thanks in advance
Nahid

**Comment by nahidshokribousjein** [comment]
Dear @Sergie,

Thank you so much for your clarification. In my previous email, I asked you if RELAX is sharp enough to say anything definitive when I  want to compare selection intensity between one test branch and one reference branch? I have attached my data file here where sequence names were enclosed with quotes as you suggested.  Please note that E.robusta is a host bee species and I. schwarzi is its parasite one. Sequences belong to bees CO1 gene and have been checked in Geneious for any premature stop codons.
I would be so grateful if you could have a look at them and let me know if you have any advice.  

Thanks in advance
Nahid

**Comment by nahidshokribousjein** [comment]
Dear @Sergei, 

Thank you so much for your clarification. In my previous email, I asked you if RELAX is sharp enough to say anything definitive when I  want to compare selection intensity between one test branch and one reference branch? I have attached my data file here where sequence names were enclosed with quotes as you suggested.  Please note that E. robusta is a host bee species and I. schwarzi is its parasite one. Sequences belong to bees CO1 gene and have been checked in Geneious for any premature stop codons.
I would be so grateful if you could have a look at them and let me know if you have any advice.  

Thanks in advance
Nahid
[CO1_aligned by translation1_MAFFT (1).txt](https://github.com/veg/hyphy/files/3724366/CO1_aligned.by.translation1_MAFFT.1.txt)

**Comment by nahidshokribousjein** [comment]
Dear Sergei, 

I used standard **invertebrate** mtDNA  because my focal organisms are bees. 

Kind regards
Nahid

**Comment by spond** [comment]
Dear @nahidshokribousjein,

In which case Geneious did not correctly report the presence of stop codons it seems.

Best,
Sergei

**Comment by nahidshokribousjein** [comment]
Dear Sergei, 

Thanks for your swift follow up. Choosing frame 1 will arrange nucleotides in a way that there are no stop codons within sequences. 

Cheers
Nahid

**Comment by spond** [comment]
Dear @nahidshokribousjein,

Frame 1 should mean that you start translation at character 1 and go 5' to 3' (left to right). The sequences you provide are **not** in frame. For example, here''s the diagnostic output from BUSTED.

```
PROBLEM WITH SEQUENCE ' MELIPONA_SCUTELLARIS_CO1' (1539 nt long, stop codons shown in capital letters)

attaataaatgattaatatcaacaaatcataaaaatattggaattctttatataatttttgctttatgatcaggaataattggatcatcatttAGAatattaattcgaatagaacttaatAGAccaggaatatgaattaataatgatcaaatttataattcaattgttactagtcatgcatttttaataattttttttatagttataccatttttaattggaggatttggaaattttttaattccattaatattaggatctccagatatagcatttccacgaataaataatattAGGttttgattattaccaccatcattaatattattattattaAGAaatatattttttccaagttctggaactggttgaactatttatcctccattatctttatatttatatcattcttctccatctgttgattttacaattttttcaattcatataactggaatttcatcaattcttggatcattaaattttattgtaacaatttttataataaaaaatttttcattaaattatgatcaaattaatttattttcatgatcaatttctattactgtaattttattaattttatctttacctgtattagcaggagcaattactatattattatttgatcgaaacttaaatacatcattttttgatccaataggaggaggagatccaattttatatcaacatttattttgattttttggacatcctgaagtttatattttaattttaccaggatttggacttatttcccaaattatcataaatgaaAGAggaaaaaaagaaatttttggaaatttaAGAataatttatgcaatattaggaattggattcttaggatttattgtatgagcccatcatatatttacagtcggattagatattgatacacgagcatattttacatcagcaacaataattatcgcaattcctacaggaattaaagtttttAGAtgattagcaacatatcatggatcaaaatta---------aattttaatatttcatttatatgatcaattggattcattttaatatttacaattggaggattaactggaattatattatcaaattcatcaattgatattattttacatgattcttattatgttgttggtcattttcattatgttttatcaataggagctgtattttcaattattgctAGAtttattcattgatttccattaatttcaggattattaataaatcaaaaatgattaaaatttcaattttattttatatttataggagttaatttaacattttttccccaacattttttaggattaataggaataccacgacgatactcagattatcctgattcatattattgttgaaatttaatttcatcattaggatctataatttcaataaatAGAttattatttataatatttattatttttgaaAGAttaatatcaaaacgatttattttatttaaattttatcaatcatcattagaatgattaaataattatccaccatttaaccatatatgtaatgaaattcccttattaattaaa
```

Best,
Sergei

**Comment by spond** [comment]
Dear @nahidshokribousjein,

Unfortunately, there are still stop codons in the second alignment 

---
>code –> Vertebrate-mtDNA
*** PROBLEM WITH SEQUENCE ' MELIPONA_SCUTELLARIS_CO1' (1539 nt long, stop codons shown in capital letters)

attaataaatgattaatatcaacaaatcataaaaatattggaattctttatataatttttgctttatgatcaggaataattggatcatcatttAGAatattaattcgaatagaacttaatAGAccaggaatatgaattaataatgatcaaatttataattcaattgttactagtcatgcatttttaataattttttttatagttataccatttttaattggaggatttggaaattttttaattccattaatattaggatctccagatatagcatttccacgaataaataatattAGGttttgattattaccaccatcattaatattattattattaAGAaatatattttttccaagttctggaactggttgaactatttatcctccattatctttatatttatatcattcttctccatctgttgattttacaattttttcaattcatataactggaatttcatcaattcttggatcattaaattttattgtaacaatttttataataaaaaatttttcattaaattatgatcaaattaatttattttcatgatcaatttctattactgtaattttattaattttatctttacctgtattagcaggagcaattactatattattatttgatcgaaacttaaatacatcattttttgatccaataggaggaggagatccaattttatatcaacatttattttgattttttggacatcctgaagtttatattttaattttaccaggatttggacttatttcccaaattatcataaatgaaAGAggaaaaaaagaaatttttggaaatttaAGAataatttatgcaatattaggaattggattcttaggatttattgtatgagcccatcatatatttacagtcggattagatattgatacacgagcatattttacatcagcaacaataattatcgcaattcctacaggaattaaagtttttAGAtgattagcaacatatcatggatcaaaatta---------aattttaatatttcatttatatgatcaattggattcattttaatatttacaattggaggattaactggaattatattatcaaattcatcaattgatattattttacatgattcttattatgttgttggtcattttcattatgttttatcaataggagctgtattttcaattattgctAGAtttattcattgatttccattaatttcaggattattaataaatcaaaaatgattaaaatttcaattttattttatatttataggagttaatttaacattttttccccaacattttttaggattaataggaataccacgacgatactcagattatcctgattcatattattgttgaaatttaatttcatcattaggatctataatttcaataaatAGAttattatttataatatttattatttttgaaAGAttaatatcaaaacgatttattttatttaaattttatcaatcatcattagaatgattaaataattatccaccatttaaccatatatgtaatgaaattcccttattaattaaa
---

Best,
Sergei

**Comment by nahidshokribousjein** [comment]
Dear @Sergei,

Thank you so much for your reply. I am so sorry  for any inconvenience. I am working on my data to see why there are some stop codons there and will redo Relax analyses when I fix the problem. 

Thanks again
Nahid
