### ISSUE TITLE
MEME error in Hyphy 

### ISSUE THREAD

**Issue by zz7356** [veg/hyphy#1027]
Hi, when I used MEME in Hyphy, I meet error in the last step "Internal error in _LikelihoodFunction::GradientLocateTheBump: in the Brent loop iteration 1. -39.20595168386889 / -39.20595168386703."
Could you give me some suggestions to solve the problem?
Thank you！

**Comment by stevenweaver** [comment]
Dear @zz7356,

Which environment are you running hyphy in? I ask because this is known to happen if hyphy is compiled on one machine and then executed on another with a different architecture.

Best,
Steven

**Comment by zz7356** [comment]
Thank you very much. I reinstall hyphy, the problem still exists. But when I change branches to All , it can run well. And when I use other problem ,such as FEL, it can run well. So, Is it because of my codon sequence not suitable for MEME calculation?

**Comment by zz7356** [comment]
Thank you @stevenweaver
I reinstall hyphy, the problem still exists. But when I change branches to All , it can run well. And when I use other problem ,such as FEL, it can run well. So, Is it because of my codon sequence not suitable for MEME calculation?

**Comment by spond** [comment]
Dear @zz7356,

There is nothing wrong with your data; the error you see is due to numerical instability (internal checks that HyPhy performs). They should be exceedingly rare.

1). Do you run `hyphy` or `HYPHYMPI` for MEME?
2). If you run `hyphy`, you can try changing the # of CPUs allocated to the job (via the `CPU=1` or `CPU=2` and so on command line flags.

If you don't mind sharing the data and the analysis settings that lead to the error being displayed, I could look into it further.

Best,
Sergei

**Comment by zz7356** [comment]
Thank you for your reply. 



1) I run hyphy "HYPHY 2.5.1(MP) for Linux on x86_64".
2) I change CPU=1 or CPU=2，the error is still.

3) Whether I run my data on Datamonkey, it provides a result. But maybe it not use the foreground information. 
4)Attachments are my data used for hyphy and Datamonkey MEME results.


Thank you for your help！

Best wishes
 

------------------ 原始邮件 ------------------
发件人: "Sergei Pond"<notifications@github.com>;
发送时间: 2019年10月4日(星期五) 晚上8:46
收件人: "veg/hyphy"<hyphy@noreply.github.com>;
抄送: "周怡"<929430130@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [veg/hyphy] MEME error in Hyphy  (#1027)




Dear @zz7356,
 
There is nothing wrong with your data; the error you see is due to numerical instability (internal checks that HyPhy performs). They should be exceedingly rare.
 
1). Do you run hyphy or HYPHYMPI for MEME?
 2). If you run hyphy, you can try changing the # of CPUs allocated to the job (via the CPU=1 or CPU=2 and so on command line flags.
 
If you don't mind sharing the data and the analysis settings that lead to the error being displayed, I could look into it further.
 
Best,
 Sergei

**Comment by spond** [comment]
Dear @zz7356,

GitHub strips e-mail attachments. Can you please place post them directly here?

Best,
Sergei

**Comment by zz7356** [comment]
[hyphy.meme.zip](https://github.com/veg/hyphy/files/3712772/hyphy.meme.zip)
[datamonky.meme.result.zip](https://github.com/veg/hyphy/files/3712778/datamonky.meme.result.zip)

**Comment by zz7356** [comment]
OK.  @spond 
[datamonky.meme.result.zip](https://github.com/veg/hyphy/files/3712786/datamonky.meme.result.zip)
[hyphy.meme.zip](https://github.com/veg/hyphy/files/3712788/hyphy.meme.zip)

**Comment by spond** [comment]
Dear @zz7356,

I was able to replicate the error. I am working on a solution; these types of errors are rare and, unfortunately time consuming to fix.

Best,
Sergei

**Comment by zz7356** [comment]
OK. Thank you！



---Original---
