### ISSUE TITLE
Differring results Relax test on Datamonkey server

### ISSUE THREAD

**Issue by MarliesMonnens** [veg/hyphy#1029]
Hi there! I am currently using the RELAX tests implemented on the Datamonkey server.
I really like the ready-to-go interface and the user-friendliness of the website! However, I am a bit confused by some of my results. When I performed the test for the first time, I got a significant relax test, but when I tried to repeat it a couple of months later I keep getting non-significant results. Calculated p values are miles apart too (0 in my first attempt and 1 in the second one). However, I am using the same alignment and input tree, of course with the same genetic code and branch selection. I even tried redownloading the original inputfile from the (significant) results page and reusing that as input, but it still gives non-significant results. I keep staring at my files but I don't see a difference in input at all.. Do you have any advice on what might be causing this?  I will attach my log files to this message. Best regards and thanks in advance!
[log.txt](https://github.com/veg/hyphy/files/3693078/log.txt)
[log-6.txt](https://github.com/veg/hyphy/files/3693079/log-6.txt)

**Comment by spond** [comment]
Dear @MarliesMonnens,

Sometimes, especially for small test sets (your has 2 branches) and low divergence alignments, RELAX experiences conference problems. If you look at the log file, you will see that the program printed a warning about convergence issues. RELAX 3.0 (which is in HyPhy v2.5, but not yet on datamonkey.org) has more convergence diagnostics and more robust behavior. As always, you can determine which result is *better* by looking at Log likelihood values. 

Best,
Sergei

**Comment by MarliesMonnens** [comment]
Dear Sergei

Thank you for the quick follow-up. I have been trying to run RELAX 3.1 locally. The test for relaxation (or intensification) seems non-significant, but I am running into the same warning. I assume then that this implies my results aren't reliable? Is there anything else I might try to work around this convergence issue? I'm a bit confused by all the different log(L) values in the file, do you have any advice on how to interpret them?

Best regards and thanks again,

Marlies
[Output local run.txt](https://github.com/veg/hyphy/files/3704935/Output.local.run.txt)

**Comment by spond** [comment]
Dear @MarliesMonnens,

Sometimes the method simply fails to converge on some datasets. This often indicates that there is simply too little signal in the data for reliable inference. Two other things you can try locally

1). Run RELAX using the 'minimal' model set. This could yield a different result (possibly with a better logL) because it will start the optimization at a different value. 

2). Run RELAX using **fewer** rate classes; this helps when the model seems overparameterized.

```
hyphy relax --models Minimal --rates --alignment /path/to/file
```

Best,
Sergei

**Comment by stevenweaver** [comment]
Datamonkey has been updated to use HyPhy 2.5.1
