### ISSUE TITLE
hyphy installation

### ISSUE THREAD

**Issue by va89fa** [veg/hyphy#1030]
Hello, 

I have tried to install hyphy as the manual guideline, but it did not work. would it be related to the fact that I am not the administrator in linux?
the only commands I could work with were 

sudo apt install hyphy-pt
sudo apt install cmake

which were suggested by the command prompt. is this installation correct? does it need any more steps?

Best,
Vafa

**Comment by stevenweaver** [comment]
Dear @va89fa, 

The packaging for Ubuntu was graciously contributed by @tillea. It should work. If you would like to compile from source, you may follow the instructions provided [here](http://hyphy.org/installation/)

Please read the [CLI tutorial](http://hyphy.org/tutorials/CL-prompt-tutorial/), kindly contributed by @sjspielman, for use instructions.

Best,
Steven
