### ISSUE TITLE
Batch File Error

### ISSUE THREAD

**Issue by va89fa** [veg/hyphy#1032]
Hi Dear HyPhy Team,

I have installed hyphy via conda on Linux. Trying to run batch files everything works fine, yet when I try to run nonCodingSelection.bf which I have downloaded from: https://github.com/ofedrigo/TestForPositiveSelection , I get the following error:

Error:Must have an even number of arguments for explicitly enumerated choice - description pairs in void _ExecutionList::BuildChoiceList(_List*, long int). Had '{neutralProxy, "Neutral proxy", 1, SKIP_NONE, "Synonymous sites", "Use synonymous substitution from a coding alignment", "Intronic sites", "Use intronic sequences", }'

could you help me get through this error?

Best,
Vafa

**Comment by spond** [comment]
Dear @va89fa,

HyPhy 2.5.1 is not perfectly backwards compatible. In particular, older versions of HyPhy would accept files with syntax errors (like the one you see here). One solution is to run the analysis using an older version of HyPhy (2.3.x); another is to "upgrade" the batch file to run on newer version of the program, see https://github.com/spond/TestForPositiveSelection
Best,
Sergei

**Comment by va89fa** [comment]
Dear @spond 

Thanks for your help. I did use the upgraded batch file which you uploaded. and it worked !
