### ISSUE TITLE
RELAX problem with tree

### ISSUE THREAD

**Issue by laristide** [veg/hyphy#1034]
Hi,
I'm running a RELAX analysis on a 326 species tree. The analysis runs ok, but in the results there's one branch missing (one at the base of the tree, see attached plot), both in the estimated parameters and in the "input" tree. Is this a bug or an expected behavior? 
![Rplot](https://user-images.githubusercontent.com/20465715/66830569-0c0e4b00-ef56-11e9-86be-930d670ccaaf.jpeg)

upper tree is the original, the lower is the output with the missing branch (actually missing, not of zero length).

Thanks for your help.

**Comment by spond** [comment]
Dear @laristide,

This is expected behavior. Please see #623, #961, #480, 

Best,
Sergei

**Comment by laristide** [comment]
Thanks, I see.
I'm interested in the general descriptive model, I would like to generate a figure similar to Fig. 6 in Werthein et al 2014. The tree in the figure apparently is the original tree (the one in the Supplementary data has, as expected, one branch missing). How were the K values mapped into the original tree if there's one value "missing" in the output?
Thanks for your help.

**Comment by spond** [comment]
Dear @laristide,

If you have create a root by placing it onto a particular branch, thereby creating two branches, you could just assign the same `k` value to both of them.

Best,
Sergei

**Comment by laristide** [comment]
Thank you very much for help.
