### ISSUE TITLE
BUSTED: Receive unspecified error using HIV-1 pol data

### ISSUE THREAD

**Issue by shelbyLanda** [veg/hyphy#1036]
Hello,

I am trying to run the HIV-1 pol (recombinant) example data provided on the datamonkey website through BUSTED in order to get an idea of the analysis output. However, after I select branches in the tree and choose "save branches" the Job Progress page appears, but I receive an email with a link that does not specify an error and instead reads "We're sorry, there was an error processing your job."

I have inspected the pol.nex file and all formatting seems to be correct which is consistent with BUSTED being able to load the tree so that I can choose foreground branches. Is this data not compatible with BUSTED?

Any suggestions are appreciated--thank you!

**Comment by spond** [comment]
Dear @shelbyLanda,

There appears to be a bug with how Datamonkey transmits branch selection to the server backend for BUSTED.  We'll look into it right away.

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @shelbyLanda, 

Datamonkey does not currently support partition data in NEXUS files. 

```
BEGIN ASSUMPTIONS;
        CHARSET span_1 = 1-459;
        CHARSET span_2 = 460-1005;
        CHARSET span_3 = 1006-1137;
        CHARSET span_4 = 1138-1560;

END;
```

The next release of Datamonkey will support partition data, which will be released towards the end of the month. 

Best,
Steven
