### ISSUE TITLE
Error: Expression appears to be incomplete/sytax error

### ISSUE THREAD

**Issue by JasonAnthonyHill** [veg/hyphy#1037]
Using HYPHYMPI v2.5.0 I am running a BGM analysis. Things seem to be running fine until an error stops the run.

```
### Performing initial model fit to obtain branch lengths and rate parameters
Fitting nucleotide GTR to obtain branch length estimates
>Fitted an alignment-wide GTR model. Log(L) = -215912.87, AIC-c = 440903.39 (4513 estimated parameters)
>Fitted an alignment-wide model. Log(L) = -199934.04, AIC-c = 408959.89 (4520 estimated parameters)

Total tree lengths by partition

Partition 1. 73.994 subs/site.

### Performing joint ancestral state reconstruction and mapping substitutions

### Inferring a BGM on 303 nodes [sites]
HYPHYMPI terminated.
Error:
Expression appears to be incomplete/syntax error. {} scope: 0, () depth 0, matrix scope: 0. In a '' literal. 
nodes + add_discrete_node(13,
```
I'm unable to figure out what is causing the error, and whether the input is to blame or not.

**Comment by spond** [comment]
Dear @JasonAnthonyHill,

That's not good. Let me take a closer look. I presume this issue occurs with different input files?

Best,
Sergei

**Comment by JasonAnthonyHill** [comment]
Dear Sergei,

I did try this again with a different alignment and phylogeny and got a similar error.

End of stdout:
`### Performing joint ancestral state reconstruction and mapping substitutions

### Inferring a BGM on 231 nodes [sites]
HYPHYMPI terminated.
Error:
Expression appears to be incomplete/syntax error. {} scope: 0, () depth 0, matrix scope: 0. In a '' literal. 
nodes + add_discrete_node(13^A,

`
End of messages log:
`SetParameter(BnveQATf.gen_bgm,BGM_DATA_MATRIX,BGM_DATA_MATRIX);

Successful mode switch to Bgm MPI confirmed from node 1
Successful mode switch to Bgm MPI confirmed from node 2
Successful mode switch to Bgm MPI confirmed from node 3
Successful mode switch to Bgm MPI confirmed from node 4
Successful mode switch to Bgm MPI confirmed from node 5
Successful mode switch to Bgm MPI confirmed from node 6
Successful mode switch to Bgm MPI confirmed from node 7
Successful mode switch to Bgm MPI confirmed from node 8
Successful mode switch to Bgm MPI confirmed from node 9
Successful mode switch to Bgm MPI confirmed from node 10
Successful mode switch to Bgm MPI confirmed from node 11
Successful mode switch to Bgm MPI confirmed from node 12
Successful mode switch to Bgm MPI confirmed from node 13
Successful mode switch to Bgm MPI confirmed from node 14
Successful mode switch to Bgm MPI confirmed from node 15
Successful mode switch to Bgm MPI confirmed from node 16
Successful mode switch to Bgm MPI confirmed from node 17
Successful mode switch to Bgm MPI confirmed from node 18
Successful mode switch to Bgm MPI confirmed from node 19
Sent child 0 to node 1
Sent child 1 to node 2
Sent child 2 to node 3
Sent child 3 to node 4
Sent child 4 to node 5
Sent child 5 to node 6
Sent child 6 to node 7
Sent child 7 to node 8
Sent child 8 to node 9
Sent child 9 to node 10
Sent child 10 to node 11
Sent child 11 to node 12
Sent child 12 to node 13
Sent child 13 to node 14
Sent child 14 to node 15
Sent child 15 to node 16
Sent child 16 to node 17
Sent child 17 to node 18
Sent child 18 to node 19
`

Both of this and the previous dataset analyses completed successfully with a single-thread non-mpi run of hyphy BGM. Thanks for taking a look but it's not critical for me at all since the single thread runs finish successfully in a reasonable amount of time. Also, thanks for a great set of tools.

Best,
Jason
