### ISSUE TITLE
Hyphy Desktop Can't run on macOS 10.15

### ISSUE THREAD

**Issue by liu-wq** [veg/hyphy#1039]
Dear manager,
October 24 mac OS updated 10.15, banned running 32-bit programs, led to the current Hyphy desktop macOS 2.2.4 can not be used. When can you update Hyphy Desktop on Mac OS?
Thank you!

**Comment by spond** [comment]
Dear @liu-wq,

The legacy GUI version of HyPhy is no longer being maintained, sorry. Version 2.5.x is entirely command line, but it has visualization components that run in the browser.

See http://hyphy.org/getting-started/

Best,
Sergei
