### ISSUE TITLE
newbie question regarding simulate and characters var

### ISSUE THREAD

**Issue by EHC2019** [veg/hyphy#1043]
Hi,
I am new, just had our IT installed hyphy on the cluster for me :-)
I hope it is the right place to ask questions.

I am trying to use a previously published hyphy script appear here:
https://github.com/JoeThorntonLab/MNM_SelectionTests/blob/master/BranchSites_MNMSimulations_null.bf

I get this Error:Variable characters has not been defined in Simulate.
referred to this line: 
        DataSet simulatedData = Simulate (givenTree,codonFreqs,characters,5000);
Indeed characters var does not appear elsewhere in their script. I saw someone previously complained about that issue (https://github.com/JoeThorntonLab/MNM_SelectionTests/issues/1) and was referred to a missing hyphy simulate.bf file but I was not been able to locate it.

I also went through old hyphy disscussions trying to understand how Simulate goes and found this but I am not sure what is says and if that is the thing I am looking for. 
characters = { {"A","C","G","T" }
{"3","TAA,TAG,TGA","",""} };

Many thanks for the time and effort,
EC

**Comment by spond** [comment]
Dear @EHC2019,

Take a look at https://github.com/spond/MNM_SelectionTests 

Best,
Sergei

**Comment by EHC2019** [comment]
> Dear @EHC2019,
> 
> Take a look at https://github.com/spond/MNM_SelectionTests
> 
> Best,
> Sergei

Thanks!!!
