### ISSUE TITLE
BUSTED also detects non-episodic/constant selection, right?

### ISSUE THREAD

**Issue by greatsantini** [veg/hyphy#1045]
Hi, we received a review on a paper where we present negative results from a BUSTED analysis. One reviewer would like us to change the title so that it reflects that we searched only for episodic selection. However if I understand the BUSTED method correctly, it should also detect positive selection that is constantly different between the foreground and background, right? Maybe even with greater power?!?

Kind regards,
Fabian

**Comment by spond** [comment]
Dear @greatsantini,

BUSTED does **not** compare foreground and background. What is does is to test for selection in the foreground (&omega; > 1), while accounting for the background. That said, if you have pervasive positive selection on foreground branches, BUSTED should be able to detect it. 

Best,
Sergei

**Comment by greatsantini** [comment]
Thank you very much for clarifying!
