### ISSUE TITLE
Blank results page

### ISSUE THREAD

**Issue by KWollenbergPhylo** [veg/hyphy#1046]
Hello:

I had a MEME job finish overnight. When I followed the link for the results I got a page with only the minimal content and no results at all. Here is a screen shot of where the link took me.
<img width="1203" alt="Datamonkey_blankMEMEresults" src="https://user-images.githubusercontent.com/56597475/69248819-f4406d00-0b7a-11ea-8f8a-1ea0a02c2ded.png">

The analysis was chugging away when I left it last night, so no indication that anything was awry. Help?

**Comment by stevenweaver** [comment]
Dear @KWollenbergPhylo, 

There must be something specific to the results that has caused an exception when rendering the results page. Could you email me at sweaver@temple.edu with the link? 

Also, you can access the raw results by appending `/results` to the url. For example, if the url is http://datamonkey.org/fel/5dcc24bca0f4ce7f60c1bf9f, then accessing the raw results would be http://datamonkey.org/fel/5dcc24bca0f4ce7f60c1bf9f/results.

Best,
Steven

**Comment by KWollenbergPhylo** [comment]
Hi Steven:

Thanks for the prompt reply. Here’s the url for my job:

http://datamonkey.org/meme/5dd40a4e16455325f316800a


--
Cheers,
Kurt Wollenberg, Ph.D.
Contractor - MSC, Inc.
Phylogenetics Specialist
Scientific Support Section
Bioinformatics and Computational Biosciences Branch (BCBB)
OCICB/OSMO/OD/NIAID/NIH

31 Center Drive, Room 3B62
Bethesda, MD 20892-0485
Office 240-627-3684


Disclaimer:
The information in this e-mail and any of its attachments is confidential
and may contain sensitive information. It should not be used by anyone who
is not the original intended recipient. If you have received this e-mail in
error please inform the sender and delete it from your mailbox or any other
storage devices. National Institute of Allergy and Infectious Diseases shall
not accept liability for any statements made that are sender's own and not
expressly made on behalf of the NIAID by one of its representatives.
