### ISSUE TITLE
error when running the aBSREL method of hyphy in datamonkey

### ISSUE THREAD

**Issue by Pedicularis** [veg/hyphy#1047]
Dear manager,
Today I use aBSREL in the datamonkey, the analysis can not completed and the results page will not automatically open displaying the results of the analysis.  Can you help me?

Thanks in advance!
Li xin

**Comment by spond** [comment]
Dear @Pedicularis,

Can you please provide the URL (link) to your Datamonkey job?

Best,
Sergei

**Comment by Pedicularis** [comment]
Dear, Sergei
These are the link of no complete results and&nbsp;&nbsp;result sumary&nbsp;jobs in Datamonkey. But when choose the select all, there have complete result and result sumary.
select only internal nodes: https://www.datamonkey.org/absrel/5dd72c7016455325f316d9e7
select only leaf nodes: https://www.datamonkey.org/absrel/5dd72c9f16455325f316da19
select my test nodes:&nbsp;https://www.datamonkey.org/absrel/5dd72c8516455325f316da00
Thankyou!


Best,
Lixin




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sergei Pond"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月22日(星期五) 凌晨4:38
收件人:&nbsp;"veg/hyphy"<hyphy@noreply.github.com&gt;;
抄送:&nbsp;"lixin"<1006975071@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [veg/hyphy] error when running the aBSREL method of hyphy in datamonkey (#1047)




Dear @Pedicularis,
 
Can you please provide the URL (link) to your Datamonkey job?
 
Best,
 Sergei
