### ISSUE TITLE
testing two groups with busted and relax in version hyphy/2.4.0a2

### ISSUE THREAD

**Issue by kmeusemann** [veg/hyphy#1048]
Dear HYPHY developers, 

For a revised study, I need to run analyses with several branches grouped in one group against all others (so 2 groups):

1) BUSTED
------------
In the tree I labeled all branches to test (one group) with {FG}
and will use the command: 
**hyphy busted --alignment BLA.fas --tree BLUBB.tre  --branches FG**
This is correct, isn't it?

2) RELAX
----------
I not get from the manual and help merssages for RELAX (same purpose as above):
Several branches of this group are labeled with  FG ( -> {FG}
a) do I then have to label all remaining ones in the tree as well? (e.g. with BG -> background)? and is this identical to my  --branches FG in the BUSTED analyses? (is the reference option is only valid when having three groups?)
first I thought its simple and with this command (having only FG labeled in the tree):
**hyphy relax --alignment BLA.fas --tree BLUBB.tre --test FG --models Minimal** 
Reading the hyphy relaxed --help and the website I am unsure:  do I have to label in the tree FG (group of interest) and BG (all others) and must the command be then 

hyphy relax --alignment BLA.fas --tree BLUBBE.tre --test FG **--reference-group BG --mode Group test mode** --models Minimal
-> do I have to provide a run mode? 
-> what is the difference between --refference and --reference-group?
= > sorry, I do not get the correct syntax
_(from the --help):
	applies to: Please select a tree file for the data:
mode
	Run mode
	defaut value: Classic mode
	applies to: Group test mode
reference-group [conditionally required]
	The set of branches to use as reference
	applies to: Select the set of branches to use as reference
test [conditionally required]
	Branches to use as the test set
	applies to: Choose the set of branches to use as the _test_ set
reference [conditionally required]
	Branches to use as the reference test
	applies to: Choose the set of branches to use as the _reference_ set_

3) BUSTED
We recognized that for our dataset the p value was never > 0.5. Is three any li9mit and if so, why / what is the rationale? Or is this just chance (and caused by our dataset?

All the best and many thanks in advance :)!
Karen

**Comment by spond** [comment]
Dear @kmeusemann,

1. The BUSTED invocation command is correct for the use case you describe.

2. For two groups in RELAX you should use 

```
hyphy relax --alignment BLA.fas --tree BLUBB.tre --test FG --models Minimal
```

It is not necessary to label the background branches; by default all unlabeled branches will become "background". The other options (`--reference-group BG` etc) are relevant if you have **more** than two groups and want to determine if **any** of them experience relaxed/intensified selection.

3. The p-value does not exceed 0.5 because BUSTED performs a one-sided test (&omega; > 1 vs &omega; = 1). This is a statistical artifact. 

Best,
Sergei

**Comment by kmeusemann** [comment]
Dear Sergei,

thanks for the quick and clar reply, absolutely perfect!! (maybe you could ad these as notes in the manual/tutorial)

Many many thanks and best
Karen

**Comment by spond** [comment]
Dear @kmeusemann,

Glad it was helpful. You should also run the analyses with the current version (2.5 or 2.5.2 which is in the dev branch), as we are continuously working on improving computational performance and convergence. 

Best,
Sergei

P.S. Perhaps adding `examples` to analysis help pages would be useful, like you have in `man` pages?

**Comment by kmeusemann** [comment]
Dear Sergei,

I will for sure use 2.5 for the next analyses - afraid that I will now change version I have to repeat > 65000 analyses (since i would change the version in one big analysis setup, but thanks for the hint!!

adding examples would be cool, but it would be also to add a note in the --help messages and maybe also on the website i.o from HYPHY!

Many thanks again
Karen
