### ISSUE TITLE
dN/dS value 0

### ISSUE THREAD

**Issue by kavithamallayaa** [veg/hyphy#1049]
Hi Hyphy team,

I have obtained Hyphy results where omega 1 is 0. How can I interpret this? 

Does it imply that there is no non-synonymous substitutions in that proportion of sites. 

I have attached the JSON file for reference.

Thanks
Kavitha  

[plastid_ptips.RELAX.zip](https://github.com/veg/hyphy/files/3884329/plastid_ptips.RELAX.zip)

**Comment by spond** [comment]
Dear @kavithamallayaa,

Your interpretation is correct : at a proportion of sites/branches, there are no non-synonymous substitutions. 

Best,
Sergei
