### ISSUE TITLE
trouble wit MEME and abSREL

### ISSUE THREAD

**Issue by MPRIYAM** [veg/hyphy#1050]
I am getting this message anytime I am setting up this analysis. I tried this with different dataset, yet got the same message.

We're sorry, there was an error processing your job. Please try again, or visit our GitHub issues and create an issue if the issue persists.
http://datamonkey.org/meme/5ddcaf843b682c361e77b34e

**Comment by stephenshank** [comment]
Dear @MPRIYAM,

Thanks for reporting this issue. This seems to be an issue with hyphy, as I consistently get the following error when trying to run your dataset with hyphy 2.5.1 and the settings used by datamonkey:
```
Error:
Internal error 
Constrained optimization failed, since a starting point within the domain specified for the variables couldn't be found.
Set it by hand, or check your constraints for compatibility.
Failed constraint:meme.site_tree_bsrel.ATTLR1.beta_2:=492.5035056067326*4389.681353305541 must be in [0,10000]. Current value = 0.6718920626958368.
```

Tagging @spond as he will have more valuable insight on what could be causing this behavior.

Best,
Stephen

**Comment by MPRIYAM** [comment]
@spond - Hello Sergei,
What is this issue ad how can I resolve it?

**Comment by spond** [comment]
Dear @MPRIYAM,

Some of the issues you have experienced may be related to a service interruption which occurred over the Thanksgiving break here. Please re-submit your analyses and see if the problems persist. 

The analysis in question (at the link you provided) errored because the sequences in the original file were not aligned. This in turn created a situation where model parameters, such as branch lengths and substitution rates became very large (essentially infinite) and triggered error conditions.

How do you prepare your sequences for submission to Datamonkey?

Best,
Sergei

**Comment by MPRIYAM** [comment]
@spond I use MAFFT to align the sequences, clean it for stop codon on HypHy and edit it, if needed on Bio-edit.

**Comment by spond** [comment]
Dear @MPRIYAM,

The procedure seems sound. However, the sequences in this issue are not properly aligned. Here are the first 50 amino-acids of all the sequences: clearly there are some issues here.

```
MKPTTALWTAAMLVGLQLIASSSDNIVDRSSSNLSSVPSDLPQKVEFLDL
MKAQGLPCLSVMVFLLFLPHSFMLDMKTFILDYSSSNLSAVPPDLPPSTQ
MKPDWVAGRKDERGFKLCVTSLQSMKDLSHQNLTTVPLNLPKDTEYLDIS
MSPVTAALWAAAMWVGLQLSASSSDIYVDRSSKNLSSVPRDLPQSVECLD
MSPTIALWAAVLFLGLQLSASFSDSIVDRSSQNLSSVPSDLPHTTESLDL
MSVMNAALWVAVMMVVLQQINSSPDGIEDRSSQNLSSVPSDLPQTVKFLD
MSPVTAVLWAAAMLVGLQPSASSLDSIVDRSSKNLSSVPGDLPQTVEFLD
MSVTAAVLWTAAVLVGLQKSASSPDNFVDRSSQNLSSVPTDLPQTTEFLD
MSPVNAALWAAAMLMGLQLSSSSPNFVDLSSKNLSSVPSDLPETVEFLDL
MMGSTIAIFCAAAMLMPQLSVSYLRNYIDLSSSNLSSVPGDLPKEAEYID
MSPTTAALWAAVMLVGLQQLASLAASPDSSVDCSSKNLSSVPSDLPQEVE
MSPMTATLWAAMMFVGLKLITASPNISIVDRSSQNLSSVPSDLPQTVEFL
MSPVYAAIWAAAMLVSLQLSASSSETNVNRSSQNLSSVPGDLPETVEVLD
MKPSCWWLMSVYVTCLHPSLVLAIKSIMVNYSSQNLSSVPPGLKPSTEDL
MKPLGWWLLFVYVTCFHTSPILAIKSIMVNYSSQNLSSVPPGLKPSTEDL
MKPSCWWLVFVYVTCLHPSLILAIKSIMVNYSSQNLSSVPPGLKPSTEDL
MKPSSGWWLVSVYLTCFHPSLIPAIQSIMVNYSSQNLSSVPDDLKPSTED
MLHLNNMSCATVNPHHPLSSTFSKQMTQNSSLMMLALMKAQGLPWLSVVA
MSCATVSHCRPFCSTFSGTDNAGFFPMMLALMQAQELPWLSVVVLLVSLP
MKAQGLPSCLSLVVLLMSLPPSFLLDMEMLILDYSSSNLSAVPTDIPPFT
```

Best,
Sergei

**Comment by MPRIYAM** [comment]
@spond 
These are sequences from a conserved from various fish species, (though from closely related families). I tried using MUSCLE and Hyphy for alignment. How do you suggest I could resolve this? If I edit the sequence, it would be massive.
Regards
Manisha

**Comment by spond** [comment]
Dear @MPRIYAM,

That's a good question. I would suggest you align sequences in the amino-acid space using MAFFT, then map the nucleotides back onto them. You can use HyPhy to help with some of these steps (see https://github.com/veg/hyphy-analyses/tree/master/codon-msa)

Best,
Sergei
