### ISSUE TITLE
issue with aBSREL

### ISSUE THREAD

**Issue by MPRIYAM** [veg/hyphy#1052]
@spond I am getting and error message with my datatset while executing aBSREL. I tried changing the dataset, yet the result remains same. Kindly help.
https://www.datamonkey.org/absrel/5ddf889f3b682c361e783a81

**Comment by spond** [comment]
Dear @MPRIYAM,

There was a service outage during the Thanksgiving break. It has now been resolved. `aBSREL` results on your data can be found at https://www.datamonkey.org/absrel/5de412a6f3787e3dd0f435d8

Best,
Sergei

**Comment by MPRIYAM** [comment]
Thank you
