### ISSUE TITLE
Your job is aborted

### ISSUE THREAD

**Issue by muktaik** [veg/hyphy#1053]
I am trying to run MEME. But job gets aborted 2-3 seconds after I have submitted my alignment file. It also says "We're sorry, there was an error processing your job. Please try again, or visit our GitHub issues and create an issue if the issue persists."

**Comment by spond** [comment]
Dear @muktaik,

Datamonkey experienced a service interruption during the Thanksgiving break. This issue has been resolved. You should be able to run MEME now. Please let us know if the problems persist.

Best,
Sergei

**Comment by muktaik** [comment]
Dear Sergei,
Thank you so much! I also wanted to know where should I post queries which are about running MEME and FEL. 
Thanks again.

Best,
Muktai

**Comment by spond** [comment]
Dear @muktaik,

This forum is where you should be posting such queries.

Best,
Sergei

**Comment by muktaik** [comment]
Dear Sergei,
Thanks for your response. I am trying to do selection analysis on one particular gene and I have sequences of that gene from about 130 species. Out of these 130, about 30 are from one group and 100 from another group. Let us call them group A (30 species) and group B (100). I want to compare dN/dS values and sites which have undergone episodic selection between these two groups. My question is whether I should align these two groups separately and run analysis separately or would it be better if I have one alignment file which I should give FEL and choose A as foreground and B as background? (and vice versa) I am new to this and I am confused as to which is a better approach. 
Thanks for your help in advance.

**Comment by muktaik** [comment]
Also, it would be great if you could suggest a tutorial or a source to understand what do these tools do step by step. I would like to understand these tools better. Thanks.

Best,
Muktai

**Comment by spond** [comment]
Dear @muktaik,

Take a look at http://hyphy.org/tutorials/CL-prompt-tutorial/ and my slide deck for selection methods https://www.dropbox.com/s/eha82kazupkm5pb/Molecular%20adaptation%20.pdf?dl=0

For your specific question, I would suggest you use a method that I am writing up right now, called [Contrast-FEL](http://hyphy.org/methods/other/fel-contrast/#fel-contrast) [note that the current version of Contrast-FEL has more and slightly different options than the one described in the tutorial, for example you can test more than 2 groups of branches).

Best,
Sergei
