### ISSUE TITLE
Labeling of foreground branches is ignored

### ISSUE THREAD

**Issue by Conny8** [veg/hyphy#1054]
Hi Hyphy team,

I installed hyphy 2.5.1 and was trying to run BUSTED as described in the current release tutorial. Instead of running a full tree analysis, I wanted to test a subset of branches. I noticed that steps 1.5, 1.6 and 1.7 do not appear. I was asked to provide the path to the coding sequence file and the tree and then the analysis immdiately started running.
As an alternative option, I labeled the foreground branches using the phylotree widget, but the selection was ignored and again, a full tree analysis started.
I then tried to run aBSREL, but I had exactly the same issues.

What causes these problems and how could I solve them?
Thank you for help!

**Comment by stephenshank** [comment]
Dear @Conny8,

Did you try using the `--branches` flag? I did as you described but included this flag as follows:

```
hyphy busted --alignment CD2.fasta --tree CD2-annotated.new --branches Foreground
```

(note `Foreground` is the default label included by phylotree) and definitely saw a subset selection in the output:

```
### Branches to test for selection in the BUSTED analysis
* Selected 5 branches to test in the BUSTED analysis: `Pig, Cow, Node3, Horse, Cat`
```

You can run `hyphy busted --help` to see a list of all key/value pairs that BUSTED accepts.

Best,
Stephen

**Comment by spond** [comment]
Dear @Conny8,

With 2.5.1 the default behavior is to run the analysis on **all** branches. If you wish to override this behavior, specify the set of branches via the `--foreground` command line argument as suggested by @stephenshank 

Best,
Sergei
