### ISSUE TITLE
GARD: there was an error processing job

### ISSUE THREAD

**Issue by pengyy339** [veg/hyphy#1055]
I submitted my DNA sequence on the DataMonkey, ready to do the GARD calculation, but after about a minute running, prompted me: 
We're sorry, there was an error processing your job. Please try again, or visit our GitHub issues and create an issue if the issue persists.
then I downloaded sequence from http://www.hyphy.org/pubs/GARD/PosadaMBE.tgz , use the file Actine. Nex do the GARD calculation, still appear the same error message.

**Comment by Weihuang0325** [comment]
I also have the same problem. The log file was empty so I actually have no idea what is going wrong.

**Comment by stephenshank** [comment]
Dear @pengyy339 and @Weihuang0325,

Thanks for calling our attention to this issue. There seems to be an issue with GARD in the latest release. We're investigating now and hope to have a fix out soon.

Best,
Stephen

**Comment by pengyy339** [comment]
Thank you for your answer. 
I have another question，I don't know if Rate classes should be set to 2 or 3, the default is 2, but I see a lot of literature using 3.

**Comment by dxter-zz** [comment]
Same.  Failed 3 times so far on same alignment.  Here is last log.

[log (17).txt](https://github.com/veg/hyphy/files/3935199/log.17.txt)

**Comment by spond** [comment]
Dear @dxter-zz,

In your case the error (even though it is not reported) is that there are too few sites for the number of sequences to run the inference. This is an inherent method limitation. You can prune some sequences out and try again with a smaller dataset.

```The alignment is too short to permit c-AIC based model comparison. Need at least 1788 sites for 445 sequences to fit a two-partiton model.```

Best,
Sergei

**Comment by dxter-zz** [comment]
My alignment had 40 sequences and 1008 nucleotide sites.  Attached.

**Comment by spond** [comment]
Dear @dxter-zz,

Github strips attachments from e-mails. Can you please include the full URL for the failed Datamonkey run?

Best,
Sergei

**Comment by spond** [comment]
Dear @pengyy339,

Please select `Nucleotide` data type on the job submission page, and the analysis should complete (http://datamonkey.org/gard/5debfc88f3787e3dd0f52b85). The option to run this as `codon` data is currently not working, and will be fixed. 

Best,
Sergei

**Comment by dxter-zz** [comment]
> Dear @dxter-zz,
> 
> Github strips attachments from e-mails. Can you please include the full URL for the failed Datamonkey run?
> 
> Best,
> Sergei

I didn't save the previous URLs, but I just tried it again both with nucleotide and codon specified and they both seemed to fail right away without any output.  Here is the URL with codon specified: http://datamonkey.org/gard/5ded8a49f3787e3dd0f5414c

**Comment by stephenshank** [comment]
Dear @pengyy339, @Weihuang0325, and @dxter-zz,

We've done a Datamonkey release that rolled back to a previous version of GARD, so hopefully things will work for you as they did before. Could you please try again, and let us know if you encounter any issues?

Best,
Stephen
