### ISSUE TITLE
Branch length of input tree for "absrel"

### ISSUE THREAD

**Issue by Shunsuke-Kanamori** [veg/hyphy#1056]
Dear Hyphy developers,

Does "absrel" use the branch length of the input tree?
Or is "absrel" using only the topology of the input tree and calculating the branch length by itself?

And, should I use a tree with branch length?

Thanks in advance
Shunsuke Kanamori

**Comment by spond** [comment]
Dear @Shunsuke-Kanamori,

`aBSREL` will take branch lengths of the input tree as initial guesses, and re-estimate them using ML.

It is not *necessary* to provide branch lengths in the input tree.

Best,
Sergei

**Comment by Shunsuke-Kanamori** [comment]
Dear @spond ,

Thank you for your quick reply :)
For now, I will try to run the software using the tree without the branch length.

Sincerely yours,
Shunsuke Kanamori

**Comment by Shunsuke-Kanamori** [comment]
Dear @spond,

Now, I have another question.
If I use a tree without branch length, how does aBSREL's initial guess work?
Does it start from the initial branch length search?
Or, are all the initial branch lengths given appropriate values such as 1?

Thanks in advance
Shunsuke Kanamori

**Comment by stevenweaver** [comment]
Dear @Shunsuke-Kanamori, 

If no branch length is provided, then HyPhy will set the branch length with a "small value"(e.g. `1e-10`), then optimizes initial branch lengths using ML and the baseline model `MG94xREV`. 

Best,
Steven

**Comment by Shunsuke-Kanamori** [comment]
Dear @stevenweaver,

Thank you for telling me the details :)
I understood well.

Sincerely yours,
Shunsuke Kanamori

**Comment by stevenweaver** [comment]
Dear @Shunsuke-Kanamori, 

どういたしまして。HyPhyソフトを使用してありがとう。

Best,
スティーブン

**Comment by spond** [comment]
Dear @Shunsuke-Kanamori,

The default behavior in HyPhy is to obtain initial branch length estimates by performing a least squares regression on pairwise distances estimated using simple models (e.g K2P, or JC69). You can override this behavior by setting environment variables, e.g., to instruct HyPhy to use a fixed value as an initial guess, or a fixed value + random noise.

Best,
Sergei

**Comment by Shunsuke-Kanamori** [comment]
Dear @spond,


Hearing that, I thought it would be no problem to use a phylogeny without branch length as an input.

And, I found this page now.
http://www.hyphy.org/w/index.php/Environment_Variables
If I want to try it out, I'll set the environment variable and run it.


Thank you again,
Shunsuke Kanamori
