### ISSUE TITLE
Absrel aborting run

### ISSUE THREAD

**Issue by andreaniml** [veg/hyphy#1057]
Hello, 
I've been trying to run Absrel on datamonkey server, but keep getting 
"We're sorry, there was an error processing your job. Please try again, or visit our GitHub issues and create an issue if the issue persists."
http://datamonkey.org/absrel/5de69310f3787e3dd0f48790
Other programs in datamonkey seem to run just fine

**Comment by stephenshank** [comment]
Dear @andreaniml,

Thanks for making us aware of this issue. There appears to be a bug in the last release, and we're working on a fix now that should be pushed out later this week. I'll be sure to let you know when it is.

Best,
Stephen

**Comment by stephenshank** [comment]
Dear @andreaniml,

Could you please try again? Here is a successful run of aBSREL (completed today) where a subset of branches were selected (this was causing a bug in the prior release):
http://datamonkey.org/absrel/5dee89876b16541651d1b170

Best,
Stephen
