### ISSUE TITLE
Build issues for latest HyPhy and gcc9

### ISSUE THREAD

**Issue by tillea** [veg/hyphy#1058]
Hi,
I tried to upgrade the Debian package for HyPhy but unfortunately I was running into build issues that most probably seem to be in connection with gcc-9 which is the default gcc for future   Debian releases.
This [patch](https://salsa.debian.org/med-team/hyphy/blob/master/debian/patches/gcc9.patch) deals with some of the issues of the form

    /build/hyphy-2.5.1+dfsg/tests/gtests/ut_avllists.cpp:370:68: error: 'class _String' has no member named 'getStr'; did you mean 'get_str'?
      370 |     EXPECT_STREQ("(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)", return_str->getStr());
          |                                                                    ^~~~~~

, but there are more like:

    /usr/bin/c++  -D_HYPHY_LIBDIRECTORY_=\"/usr/lib/hyphy\" -D_SLKP_LFENGINE_REWRITE_ -D_SLKP_USE_AVX_INTRINSICS -D_SLKP_USE_FMA3_INTRINSICS -D__AFYP_REWRITE_BGM__ -                          D__HYPHYCURL__ -            D__HYPHYDEBUG__ -D__UNITTEST__ -D__UNIX__ -I/build/hyphy-2.5.1+dfsg/src/core/include -I/build/hyphy-2.5.1+dfsg/src/contrib -I/build/hyphy-2.5.1+dfsg/src/lib/Link -I/build/hyphy-2.5.1+dfsg/ src/new/include -I/build/hyphy-2.5.1+dfsg/contrib/gtest-1.7.0/include -I/build/hyphy-2.5.1+dfsg/tests/gtests -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -I/ usr/lib/x86_64-linux-gnu/openmpi/include  -g -O2 -fdebug-prefix-map=/build/hyphy-2.5.1+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -    fsigned-char -O3 -std=c++  14 -march=native -mtune=native -mavx  -mfma   -Wall -Wno-int-to-pointer-cast -Wno-conversion-null -Wno-sign-compare -Wno-maybe-uninitialized -msse3 -o CMakeFiles/  HYPHYGTEST.dir/tests/      gtests/ut_simplelists.cpp.o -c /build/hyphy-2.5.1+dfsg/tests/gtests/ut_simplelists.cpp
    /build/hyphy-2.5.1+dfsg/tests/gtests/ut_list.cpp: In member function 'virtual void {anonymous}::ListTest_FindStringTest_Test::TestBody()':
    /build/hyphy-2.5.1+dfsg/tests/gtests/ut_list.cpp:347:26: error: 'class _List' has no member named 'FindString'; did you mean 'FindStepping'?
      347 |     int index = str_list.FindString((BaseRef)needle, 0, false, upTo);
          |                          ^~~~~~~~~~
          |                          FindStepping
    /build/hyphy-2.5.1+dfsg/tests/gtests/ut_list.cpp:350:22: error: 'class _List' has no member named 'FindString'; did you mean 'FindStepping'?
      350 |     index = str_list.FindString((BaseRef)needle, 0, true, upTo);
          |                      ^~~~~~~~~~
          |                      FindStepping
    /build/hyphy-2.5.1+dfsg/tests/gtests/ut_list.cpp:354:22: error: 'class _List' has no member named 'FindString'; did you mean 'FindStepping'?
      354 |     index = str_list.FindString((BaseRef)needle2, 0, true, upTo);
          |                      ^~~~~~~~~~

where I'm hesitating to simply take over the suggestion given by the compiler.  Do you have any clue how to fix this?
Kind regards, Andreas.

**Comment by spond** [comment]
Dear @tillea,

The gtest target (`gtest`) has grown out of sync with the latest code-base (which went through a significant revision in version 2.5.x). The issue you see is not specific to `gcc-9`, because some of the code in `ut_xx.xx` files is no longer correct. For the next release, I'll look over the `gtest` target. 

In the meantime, we have moved much of the testing to higher level scripts, and this is a part of our continuous integration process. @stevenweaver can elaborate.

Do you see any compilation issues with the `MP` and `MPI` targets?

Best,
Sergei

**Comment by tillea** [comment]
Hi Sergei,
thanks a lot for your fast response.

On Fri, Dec 06, 2019 at 09:09:17AM -0800, Sergei Pond wrote:
> The gtest target (`gtest`) has grown out of sync with the latest code-base (which went through a significant revision in version 2.5.x). The issue you see is not specific to `gcc-9`, because some of the code in `ut_xx.xx` files is no longer correct. For the next release, I'll look over the `gtest` target. 
As far as I understand it makes sense to skip the GTEST target for the moment.
 
> In the meantime, we have moved much of the testing to higher level scripts, and this is a part of our continuous integration process. @stevenweaver can elaborate.
I'm really happy to support this in the Debian package.
 
> Do you see any compilation issues with the `MP` and `MPI` targets?
They are building an I uploaded the new version now.  I admit I'm not really happy with my packaging work and I'm absolutely unsure whether it works like expected.  I'd be super happy if you could give it some tests - may be in some VM that could be easily installed.  Your input as upstream is more than welcome and the packaging could heavily profit from your criticism.

Kind regards, Andreas.

**Comment by stevenweaver** [comment]
Dear @spond, 

The HYPHYGTEST target has been updated to work with >=2.5. Before I place `HYPHYGTEST` back into our integration system, I'd like to confirm with you that is desirable.

Dear @tillea, 
Our integration script has become quite complicated. At the very least, we may want to build and run `bash ./run_unit_tests.sh` to ensure that HyPhy is executing as expected.

Best,
Steven
