### ISSUE TITLE
dNdSDistributionComparison.bf  error

### ISSUE THREAD

**Issue by mstagliamonte** [veg/hyphy#1060]
Dear Hyphyers,

Thank you for making available this great set of tools!
I am trying to run dNdSDistributionComparison.bf via command line using Hyphy v2.51. When I do, I get the following error message:

```
Internal error in  _LikelihoodFunction::GradientLocateTheBump: in the Brent loop iteration 1. -1346785.984284581 / -1346716.669566525.

Function call stack
1 :  Optimize(res, lf);
```

This happens during "`Running simpler distribution approximations to ensure good convergence...`"

Can you please advice?

Thank you for your kind attention,
Max

**Comment by spond** [comment]
Dear @mstagliamonte,

Can you share the data set and analysis options that generate the error? I can take a look if I am able to replicate the error.

Best,
Sergei

**Comment by mstagliamonte** [comment]
Hi @spond ,

Thank you for answering so quickly. Please find the attached files:


[errors.log](https://github.com/veg/hyphy/files/3979055/errors.log)
[file1.40689.fasta.txt](https://github.com/veg/hyphy/files/3979056/file1.40689.fasta.txt)
[file1.nwk.txt](https://github.com/veg/hyphy/files/3979057/file1.nwk.txt)
[file2.5415.fasta.txt](https://github.com/veg/hyphy/files/3979058/file2.5415.fasta.txt)
[file2.nwk.txt](https://github.com/veg/hyphy/files/3979059/file2.nwk.txt)
[messages.log](https://github.com/veg/hyphy/files/3979060/messages.log)
[Report.comparednds.45296442.log](https://github.com/veg/hyphy/files/3979061/Report.comparednds.45296442.log)
[compare.dnds.script.txt](https://github.com/veg/hyphy/files/3979062/compare.dnds.script.txt)


Looking forward to hearing from you,
Max

**Comment by spond** [comment]
Dear @mstagliamonte,

I was able to replicate the error. I am not immediately sure what the problem is, but I'll investigate. Thanks for bringing this to my attention 

Best,
Sergei

**Comment by mstagliamonte** [comment]
Dear @spond ,

Thank you for the follow up, I appreciate your time and consideration, and look forward to see what comes out of it. In the meantime, do you have any suggestion on other bf scripts I could use for the purpose? Or should I just wait for the    dNdSDistributionComparison.bf to be amended?

Best,
Max

**Comment by mstagliamonte** [comment]
Dear @spond ,

I have re-run the analysis with hyphy v 2.5.4; this time it looks like the analysis proceeded for a while, but eventually terminated with the same error.
I am attaching the new error files and script.

Thank you for your kind help,

Max


[compare.dnds.script.txt](https://github.com/veg/hyphy/files/4307094/compare.dnds.script.txt)
[errors.log](https://github.com/veg/hyphy/files/4307095/errors.log)
[messages.log](https://github.com/veg/hyphy/files/4307096/messages.log)
[Report.comparednds.bis.48282102.txt](https://github.com/veg/hyphy/files/4307097/Report.comparednds.bis.48282102.txt)

**Comment by spond** [comment]
Dear @mstagliamonte,

Can you please try with 2.5.7?

Best,
Sergei

**Comment by mstagliamonte** [comment]
I will, thank you.

Best,
Max

**Comment by mstagliamonte** [comment]
Dear @spond ,

The script with HyPhy v 2.5.7 run for 5 days, then unfortunately  run out of time on the cluster I am using. 
I have re-submitted the script and allocated more time, we shall see. Last time the error appeared within a few hours, so I am hoping the new version will not incur into it. I will post an update when I can.

Thank you again for your kind help,
Best,
Max

**Comment by spond** [comment]
Dear @mstagliamonte,

Unfortunately for large datasets these analyses will be slow. As a first approximation I would suggest you run FUBAR on each one of them separately and compare the dN/dS density plots like what we did in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5391457/figure/F2/. It'll finish in 10 minutes:)

Best,
Sergei

**Comment by mstagliamonte** [comment]
Great, thank you for the advice, I will 👍 

Have a nice day,
Max

**Comment by spond** [comment]
Dear @mstagliamonte,

Get HyPhy version 2.5.8 and use the call 

```
hyphy fubar ENV="USE_MEMORY_SAVING_DATA_STRUCTURES=1000000;" --alignment file1.40689.fasta.txt --tree file1.nwk.txt --grid 40
```

otherwise you are gonna run into an error because the alignment is too long for my default settings:)

Best,
Sergei

**Comment by mstagliamonte** [comment]
I will, thank you.

Best,
Max

**Comment by mstagliamonte** [comment]
Dear @spond ,

I am sorry to reopen this ticket after so long. I have run fubar on Hyphy/2.5.8, and I need some clarification. I was trying to replicate the plots as in the paper you cited, but I have noticed that fubar only outputs the info regarding site found under positive selection with posterior probability >= 0.9. I am not sure I can find the info regarding all codons in the json file.

I also tried the new datamonkey, and I get the same behavior. Interestingly, when I use a different, smaller alignment (2,115 nt) on datamonkey, I get a table for all the sites; when I run that same alignment on hyphy on my cluster, again, I only get data for the sites under positive selection. 
Can you please advice? 

Thank you for your kind attention; please let me know if you need additional details.

Kind Regards,
Max
