### ISSUE TITLE
Multiple test adjustment based on predetermined order

### ISSUE THREAD

**Issue by dxter-zz** [veg/hyphy#1062]
I was wondering if it would be valid to adjust the ABSREL p-values based on an ordering that should be independent of outliers of the null distribution, say branch length.  So say you look at the longest branch first and do no adjustment, the second you multiply by 2, etc.  Do you have any information regarding the validity of doing something like this and if so what the proper adjustments would be?  Thanks.

**Comment by spond** [comment]
Dear @dxter-zz,

That doesn't sound like an adjustment that will control family wise error rates. All the standard sequentially rejective procedures, like the Bonferroni-Holm correction that aBSREL uses, all work with ordered p-value sequences. You are welcome to apply less restrictive and more permissive schemes, like Benjamini-Hochberg with the understanding that the resulting lists control false discovery rates (i.e. the fraction of positive results that are expected to be false positives). 

Best,
Sergei

**Comment by dxter-zz** [comment]
Yes you are right that it doesn't effectively control FWER.  I simulated
this with 10000 families of 100 fair coins where each was flipped 100
times.  At alpha=0.05 this gave FWER of around 18%.  To get the FWER below
5% (~4.4% and very similar to the simulated Holm FWER in this simulation
~4.4%) you can multiply each p-value by k * 4.  So the first p-value is
multiplied by 4, the second by 8 etc. This is without accepting all null
hypotheses after the first is accepted as in the Holm.  If you accept the
nulls like in the Holm and multiply p-value by k, the FWER is very low ~
0.07%.

The motivation for this with regard to ABSREL is that, although longer
branches are not necessarily more likely to be under positive selection, if
they are, it is more likely for their p-values to be significant than for
shorter branches.  I suppose that just not testing branches under a certain
length and using Holm may possibly give more power.

One thing about ABSREL and other methods on datamonkey that I wanted to
mention is that it is often very difficult to map the node IDs in the
results table to those on the tree.  Many of the branches on the tree seem
to be collapsed to near zero and there is no way to find a particular node
ID.  If the exported newick tree had internal node labels it would solve
the problem.  Also if the tree shown on the results page had an option to
show as a cladogram that would work.  I'm not sure why these branches
become so collapsed because when I calculate branch lengths with, say,
raxml or codeml they don't look like that.

**Comment by spond** [comment]
Dear @dxter-zz,

If the standard Holm-Bonferroni is too conservative, I would suggest using an established less conservative method, like Benjamini-Hochberg FDR or its' derivatives. They mostly work by mapping and filtering single-test p-values , so should be easy to implement. 

The relationship between length and power is something we report in the original paper (https://www.researchgate.net/publication/272517872_Less_Is_More_An_Adaptive_Branch-Site_Random_Effects_Model_for_Efficient_Detection_of_Episodic_Diversifying_Selection/figures?lo=1), but you also need to consider than power is a function of effect size in addition to length. I have a concern that applying an `ad hoc` procedure based on branch length can be misleading and hard to justify. 

@stephenshank : can you please prioritize the internal node labeling feature release for the next Datamonkey version release?

Best,
Sergei
