### ISSUE TITLE
polymorphic sites

### ISSUE THREAD

**Issue by yanzhu-ji** [veg/hyphy#1064]
Dear Hyphy developers,

Thank you first for making this fantastic tool available!

I am trying to detect relaxed selection in a few bird species using RELAX.  Since my data includes within-species data, there are a bunch of polymorphic sites in a given protein.  I am not sure if my understanding is correct, but would you suggest to remove the polymorphic sites before feeding the data to RELAX?  

Thank you in advance for your help!

Best wishes,
Yanzhu

**Comment by spond** [comment]
Dear @yanzhu-ji,

It's rarely a good idea to remove any data, since doing so is apt to introduce unanticipated biases and dilute statistical power. 

Can you tell me more about what data you have exactly and what hypothesis you wish to test with RELAX?

Best,
Sergei

**Comment by yanzhu-ji** [comment]
Dear Dr. Kosakovsky Pond,

Thank you for your prompt reply and suggestion!

To answer your question: we have genome resequencing data for 2-10 individuals per species for about 10 bird species from the same family, and a genome assembly for one of the species.  The species include a few high-altitude ones.  I would like to identify the genes that are under relaxed selection in the high-altitude species.  So after mapping the reads to the reference genome, I called variants and got the consensus for each species.  

If I uderstand correctly, for polymorphic sites, vcftools outputs either the ancestral or alternative allele depending on the frequency that users set.  The segregating sites thus behave as "fixed" sites.  Would this somehow introduce other bias to the analysis, like over-estimating or under-estimating dN/dS?  Addtionally, the information in polymorphic sites is lost.

Anyway, I used to think RELAX is designed to detect relaxed selection using fixed sites only.  Perhaps the segregating sites would not have such a great impact on the overall dN/dS.  I am really new to the field of detecting selection, and still learning about the methods.

I'd appreciate very much if you have other suggestions.

Best,
Yanzhu

**Comment by spond** [comment]
Dear @yanzhu-ji,

The canonical use of dN/dS is to compare **fixed** differences between species, although other uses, e.g. intra-species estimation for pathogens (HIV-1, flu, etc) are just as prominent.

In your application, I would suggest that you apply RELAX to inter-species trees (one sequence per species) using fixed differences, possibly at different allele call thresholds.

There is a [nice review](https://www.sciencedirect.com/science/article/abs/pii/S0168952519302690) by Adam Siepel's group on more recent developments in genomic/population selection detection analyses, but they are not really focused on single genes.

Best,
Sergei

**Comment by yanzhu-ji** [comment]
Dear @spond , 

Thank you very much for your kind suggestion and recommended review!  

Best,
Yanzhu
