### ISSUE TITLE
errors in running MEME method

### ISSUE THREAD

**Issue by hongzhonglu** [veg/hyphy#1065]
Dear Sergei @spond 
Does anyone meet the followed error information when using MEME of hyphy?

Error:
Internal error in  _LikelihoodFunction::GradientLocateTheBump: in the Brent loop iteration 1. -30.10659904426133 / -30.10659904425981.

**Comment by srwis** [comment]
Hi,

This looks like it is the same error from issue #1060 and it looks like Sergei's already working on a fix. But if you'd like to provide that data set and analysis options that caused the error it would be useful. 

Thanks,
Sadie

**Comment by hongzhonglu** [comment]
@srwis Thanks for your help! I will upload the data later.

**Comment by spond** [comment]
Dear @hongzhonglu,

Because the values of the two likelihoods reported in the message are so similar, this error could be due to numerical instability (e.g. saturation on some of the sites). Does the error occur reliably if you rerun the analysis?

Best,
Sergei

**Comment by hongzhonglu** [comment]
@spond Thanks for your help. I will try it and share with you the result later.

**Comment by hongzhonglu** [comment]
@srwis @spond Please find the data in the MEME calculation where I could find the error. The error occurs many times when I used MEME to do analysis of my data. Could you help to find the reason? Great thanks!
[example_data_for_MEME_error.zip](https://github.com/veg/hyphy/files/4226333/example_data_for_MEME_error.zip)

**Comment by spond** [comment]
Dear @hongzhonglu,

Could you please confirm that the error occurs with v2.5.4 (the current release)? I ran your example through the `meme` and was not able to replicate it.

```
 mpirun -np 6 HYPHYMPI meme --alignment /Users/sergei/Downloads/example_for_MEME_error/OG1352_code.fasta  --tree /Users/sergei/Downloads/example_for_MEME_error/OG1352_aa_unroot.tre 
```

Results follow at the bottom.

Best,
Sergei

----

Analysis Description
--------------------
MEME (Mixed Effects Model of Evolution) estimates a site-wise synonymous
(&alpha;) and a two-category mixture of non-synonymous (&beta;-, with
proportion p-, and &beta;+ with proportion [1-p-]) rates, and uses a
likelihood ratio test to determine if &beta;+ > &alpha; at a site. The
estimates aggregate information over a proportion of branches at a site,
so the signal is derived from episodic diversification, which is a
combination of strength of selection [effect size] and the proportion of
the tree affected. A subset of branches can be selected for testing as
well, in which case an additional (nuisance) parameter will be inferred
-- the non-synonymous rate on branches NOT selected for testing.
Multiple partitions within a NEXUS file are also supported for
recombination - aware analysis. 

- __Requirements__: in-frame codon alignment and a phylogenetic tree

- __Citation__: Detecting Individual Sites Subject to Episodic Diversifying Selection.
_PLoS Genet_ 8(7): e1002764.

- __Written by__: Sergei L. Kosakovsky Pond, Steven Weaver

- __Contact Information__: spond@temple.edu

- __Analysis Version__: 2.1.1


>code –> Universal

>Loaded a multiple sequence alignment with **107** sequences, **4300** codons, and **1** partitions from `/Users/sergei/Downloads/example_for_MEME_error/OG1352_code.fasta`

>branches –> All

>Select the p-value threshold to use when testing for selection (permissible range = [0,1], default value = 0.1): 
>pvalue –> 0.1


### Branches to include in the MEME analysis
Selected 211 branches to include in the MEME analysis: `Kazachstania_africana_Seq_82, yHAB155_Kazachstania_spencerorum_Seq_699, yHAB158_Kazachstania_viticola_Seq_14, Node3, Node1, yHAB134_Kazachstania_turicensis_Seq_1631, yHAB160_Kazachstania_kunashirensis_Seq_2846, Node7, yHAB132_Kazachstania_martiniae_Seq_84, yHAB148_Kazachstania_intestinalis_Seq_289, Node10, Node6, yHMPu5000034876_Tetrapisispora_iriomotensis_Seq_910, Tetrapisispora_phaffii_Seq_5114, yHMPu5000034875_Tetrapisispora_fleetii_Seq_1533, yHMPu5000034877_Tetrapisispora_namnaonensis_Seq_386, Node18, Node16, Node14, Candida_glabrata_Seq_3402, Nakaseomyces_bracarensis_Seq_499, Nakaseomyces_nivariensis_Seq_397, Nakaseomyces_delphensis_Seq_4978, Node27, Node25, Node23, Nakaseomyces_castellii_Seq_2837, Nakaseomyces_bacillisporus_Seq_1097, Node30, Node22, Zygosaccharomyces_rouxii_Seq_2212, yHMPu5000034865_Zygosaccharomyces_kombuchaensis_Seq_1038, Zygosaccharomyces_bailii_Seq_2551, Node36, Node34, Lachancea_kluyveri_Seq_1577, yHMPu5000034709_Kluyveromyces_aestuarii_Seq_1309, Kluyveromyces_marxianus_Seq_727, yHMPu5000034710_Kluyveromyces_dobzhanskii_Seq_3192, Kluyveromyces_lactis_Seq_2869, Node50, Node48, Node46, Eremothecium_gossypii_Seq_2192, Ashbya_aceri_Seq_1897, Node54, Eremothecium_cymbalariae_Seq_3590, Eremothecium_sinecaudum_Seq_1479, Eremothecium_coryli_Seq_1827, Node59, Node57, Node53, Node45, Node43, Lachancea_cidri_Seq_4075, Lachancea_fermentati_Seq_778, Node63, Lachancea_mirantina_Seq_2242, Lachancea_nothofagi_Seq_340, Lachancea_dasiensis_Seq_634, Lachancea_meyersii_Seq_4920, Lachancea_fantastica_Seq_672, Lachancea_lanzarotensis_Seq_2198, Node75, Node73, Node71, Node69, Lachancea_quebecensis_Seq_2770, Lachancea_thermotolerans_Seq_4512, Node79, Lachancea_waltii_Seq_4414, Node78, Node68, Node66, Node62, Node42, yHMPu5000035037_Candida_montana_Seq_4180, yHMPu5000035673_Candida_orba_Seq_4076, yHMPu5000035672_Phaffomyces_thermotolerans_Seq_2855, Node89, yHMPu5000035670_Phaffomyces_opuntiae_Seq_3401, yHMPu5000035671_Phaffomyces_antillensis_Seq_3400, Node92, Node88, Node86, yHMPu5000035047_Barnettozyma_pratensis_Seq_3764, yHMPu5000035048_Barnettozyma_salicaria_Seq_589, yHMPu5000035044_Barnettozyma_californica_Seq_4560, yHMPu5000035046_Barnettozyma_populi_Seq_2506, Node99, Node97, Node95, Node85, yHMPu5000034967_Candida_freyschussii_Seq_5409, yHMPu5000035268_Wickerhamomyces_hampshirensis_Seq_2487, Node107, Cyberlindnera_fabianii_JCM3601_Seq_5344, yHMPu5000035688_Cyberlindnera_xylosilytica_Seq_4469, Node111, yHMPu5000035325_Cyberlindnera_petersonii_Seq_4721, yHMPu5000035689_Candida_mycetangii_Seq_2489, yHMPu5000035703_Cyberlindnera_americana_Seq_4895, Node116, Node114, Node110, Node106, Cyberlindnera_jadinii_Seq_4837, yHMPu5000034978_Cyberlindnera_mrakii_Seq_3730, yHMPu5000035687_Cyberlindnera_suaveolens_Seq_958, yHMPu5000035686_Cyberlindnera_saturnus_Seq_1893, Node124, Node122, Node120, yHMPu5000035690_Candida_vartiovaarae_Seq_2566, yHMPu5000034979_Cyberlindnera_misumaiensis_Seq_2713, yHMPu5000035699_Cyberlindnera_maclurae_Seq_2983, Node129, Node127, Node119, Node105, yHMPu5000035271_Wickerhamomyces_bovis_Seq_4516, Wickerhamomyces_anomalus_Seq_4939, Wickerhamomyces_ciferrii_Seq_3276, Node134, Node132, Node104, yHMPu5000035261_Candida_ponderosae_Seq_6857, yHMPu5000034594_Starmera_quercuum_Seq_1581, yHMPu5000034597_Candida_stellimalicola_Seq_1110, yHMPu5000035658_Starmera_amethionina_Seq_1158, Node141, Node139, Node137, Node103, yHMPu5000035274_Wickerhamomyces_alni_Seq_5581, yHMPu5000035286_Candida_azyma_Seq_1068, yHMPu5000035639_Wickerhamomyces_canadensis_Seq_5621, Node146, Node144, Node102, Node84, yHMPu5000034957_Hanseniaspora_osmophila_Seq_1017, Hanseniaspora_vinae_Seq_2526, Node150, yHMPu5000035684_Kloeckera_hatyaiensis_Seq_2262, yHMPu5000035695_Hanseniaspora_pseudoguilliermondii_Seq_3820, Hanseniaspora_uvarum_Seq_3054, yHMPu5000034963_Hanseniaspora_clermontiae_Seq_2175, Node158, Node156, Node154, Hanseniaspora_valbyensis_Seq_912, yHMPu5000035696_Hanseniaspora_singularis_Seq_1090, Node161, Node153, Node149, Node83, Node41, Saccharomyces_uvarum_Seq_504, Saccharomyces_eubayanus_Seq_3281, Node166, Saccharomyces_arboricola_Seq_3812, Saccharomyces_kudriavzevii_Seq_2399, Saccharomyces_mikatae_Seq_2437, Saccharomyces_paradoxus_Seq_4266, Saccharomyces_cerevisiae_YOR161C, Node175, Node173, Node171, Node169, Node165, yHMPu5000035652_Torulaspora_maleeae_Seq_2426, Torulaspora_delbrueckii_Seq_1800, yHMPu5000026152_Torulaspora_franciscae_Seq_247, yHMPu5000034881_Torulaspora_pretoriensis_Seq_4614, Node183, Node181, Node179, yHMPu5000035651_Torulaspora_microellipsoides_Seq_702, yHMPu5000026256_Zygotorulaspora_mrakii_Seq_2868, yHMPu5000034862_Zygotorulaspora_florentina_Seq_237, Node188, Node186, Node178, Node164, Node40, Naumovozyma_dairenensis_Seq_3027, Naumovozyma_castellii_Seq_1519, Node192, yHAB166_Kazachstania_yakushimaensis_Seq_2347, yHAB154_Kazachstania_transvaalensis_Seq_4620, Node196, yHAB143_Kazachstania_siamensis_Seq_1037, yHAB159_Kazachstania_solicola_Seq_495, yHAB164_Kazachstania_aerobia_Seq_2164, Node203, yHAB133_Kazachstania_unispora_Seq_1332, Node202, Node200, yHAB147_Kazachstania_taianensis_Seq_4482, Kazachstania_naganishii_Seq_3571, yHAB136_Kazachstania_bromeliacearum_Seq_863, Node209, Node207, Node199, Node195, Node191, Node39, Node33, Node21, Node13`


### Obtaining branch lengths and nucleotide substitution biases under the nucleotide GTR model
* Log(L) = -125215.61, AIC-c = 250869.28 (219 estimated parameters)

### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
* Log(L) = -110956.02, AIC-c = 222364.27 (226 estimated parameters)
* non-synonymous/synonymous rate ratio for *test* =   0.1105

### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
* Log(L) = -109632.55
* non-synonymous/synonymous rate ratio for *test* =   0.0773

### ** Found _0_ sites under episodic diversifying positive selection at p <= 0.1**

**Comment by hongzhonglu** [comment]
@spond Great thanks for your help! I will test it.
