### ISSUE TITLE
Very high omega values

### ISSUE THREAD

**Issue by kavithamallayaa** [veg/hyphy#1066]
Hi Sergei,

I have been doing Hyphy-RELAX on several alignments. Currently I have started with a new dataset and on running Hyphy-RELAX, I found some unusually high values of Omega 3. I have attached the json file for your reference. Can you tell why I get such high values.

with regards
Kavitha

[R_HOMCHL000773.fasta.RELAX.zip](https://github.com/veg/hyphy/files/4085082/R_HOMCHL000773.fasta.RELAX.zip)

**Comment by stevenweaver** [comment]
Dear @kavithamallayaa, 

High values of ω should be interpreted as infinite. 

Please see @murrellb's succinct explanation at [#393 (comment)](https://github.com/veg/hyphy/issues/393#issuecomment-185842213).

They can be treated as _large values_, greater than 1 given that the LRT is significant.

Best,
Steven

**Comment by spond** [comment]
Dear @kavithamallayaa,

You may also wish to consider running RELAX with more than three rate classes by utilizing the `--rates` command line argument when you invoke the analysis. There is evidence in your analysis that the standard RELAX model, where one distribution is a power transform of the other, does not describe the data well. 

If you take a look `RELAX partitioned descriptive` or `General descriptive` model, you will notice that either of those models has `AIC-c` that is notably lower (better) than the `RELAX Alternative` model. In the `RELAX partitioned descriptive` model, &omega;<sub>3</sub> values are high, but not infinite. You can also see that the major difference between the `Test` and the `Reference` distributions in that model is in the &omega;<sub>2</sub> ("neutral") rate category: on the `Reference` set of branches this category is neutral, whilst on the `Test` set of branches it is subject to strong purifying selection (&omega;<sub>2</sub>  = 0.19).

You could either use one of these more general models, or explore the fits with higher numbers of rate classes.

Best,
Sergei

**Comment by Xiaojun928** [comment]
Dear Sergei,

I ran RELAX with three rate classes for a concatenated alignment (120 orthologs of 148 strains), and got infinite omega values in Partition descriptive model. In my [result](https://github.com/veg/hyphy/files/10378830/RELAX.json.txt) , AIC-c values of `RELAX partitioned descriptive` or `General descriptive` model are higher than `RELAX Alternative` model. In this case, should I try to run RELAX with more than three rate classes? How to determine the number of rate classes? or I could try 4, 5, and 6 repsectively and choose the one showing lower AIC-c in `RELAX Alternative` model?

I also have two questions.
1. Base on the K = 0.4 and P value (0), I can conclude that selection is relaxed. When considering omega distribution of `RELAX Alternative` model, I guess I can only say positive selection is relaxed while puryfing selection is not, as the proportion and value of omega1 does not differ between test and ref branches.  Is it right?
2. In my input `nex` file, the alignment are nucleotide sequences, while the phylogenetic tree was constructed based on amino acid (aa) alignment (As the tree topology based on nucleotide sequqnces differs a lot from aa based species tree, and the aa based tree is more reliable). I was wondering if the tree must be constructed based on the nucleotide alignment. I plan to run RELAX for each orthologs, and the gene tree topology may differ from that of species tree (i.e., tree based on concatenated aa alignment) in some cases, which may affect the tree labelling (I plan to lable both leaves and internal nodes). As a result, two orthologs with different tree topologies may have different internal nodes labeled. Would this affect the result? Could I use one species tree for all orthologs?

Thank you very much!

Best regards,
Xiaojun
