### ISSUE TITLE
problem with GARD

### ISSUE THREAD

**Issue by ig624** [veg/hyphy#1069]
Dear HyPhy developers,
I tried to run GARD from a High-Performance Computing Linux environment.
the command line was:
`hyphy GARD --alignment alignment.phy --type Codon --rate-classes 3`
and the following lines were reported:
```
type: Codon
code: Universal
rv: None
>Loaded a Codon multiple sequence alignment with **258** sequences, **2069** sites (912 of which are variable) from `/mnt/lustre/users/ig624/ATPase_mapping/Screened_Putative_ATPase_pruned_2_alignment_BT.phy`
>Minimum size of a partition is set to be 513 sites


### Fitting the baseline (single-partition; no breakpoints) model
* Log(L) = -175250.02, AIC-c = 351918.79 (528 estimated parameters)

### Performing an exhaustive single breakpoint analysis
Done with single breakpoint analysis.
   Best sinlge break point location: 0
   c-AIC  = 1e+26

### Performing multi breakpoint analysis using a genetic algorithm
```
after two days it ended without concluding (time limit of my slurm job). A messages.log file was generated (that you can find attached): during the first hour, some messages were printed then it remained unchanged during the 2 days. I am not really sure if the messages.log file is reporting any problem or if the analysis requires more than two days. ( also empty GARD.json and gard-best files were generated)

I would also ask if it is possible to check the 978422.localhost ticket on http://datamonkey.org/ (also GARD): it seems to be running, but it is not progressing, and the ticket number is not reported in the  "Job Queue" section.
Thank You very much.
Regards,
IG 
[messages.log](https://github.com/veg/hyphy/files/4119329/messages.log)

**Comment by stevenweaver** [comment]
Dear @veg,

I was able to look up 978422 and confirm this dataset is *failing* without mention warning after approximately 1 hour and 30 minutes. Rerunning the job directly on cluster now.

Best,
Steven

**Comment by spond** [comment]
Dear @ig624,


This behavior (infinite c-AIC) is anomalous. 
```
### Performing an exhaustive single breakpoint analysis
Done with single breakpoint analysis.
   Best sinlge break point location: 0
   c-AIC  = 1e+26
```

We will investigate further. Thanks for reporting.

Best,
Sergei

**Comment by ig624** [comment]
Dear Both,
Thank you very much for your reply. I think the strange c-AIC is due to the alignment. I had a closer look, and there were some very short sequences with a low breadth of coverage.
I repeated the analysis with another alignment, and it worked detecting two BPs. Hence, my question. I was thinking of building ML trees from these three partitions and intertwining them into a consensus network for visual purposes, does this sound feasible (and also to use them for downstream hyphy analysis/tests)? Related to that, in order to split the alignment into the three partitions, can GARD do that, or it must be done manually?
Best regards,
IG
