### ISSUE TITLE
dN/dS with identical sequences

### ISSUE THREAD

**Issue by Cantalapiedra** [veg/hyphy#1070]
Hello,

we are computing dN/dS for a large number of clusters. Some of the clusters have only identical sequences (there are some indels, but no nucleotide variants at all).

We were expecting a dN/dS = 0/0, and therefore maybe a "NA" or similar value reported by hyphy.

However, we obtain a value of "0.8581" for a dataset, and similar values (always around 0.85) for other datasets. Also, with fubar, in the json file, we have a similar issue: for example, alpha = 5.63... and beta = 5.63... are reported for all the residues, when we would expect 0 and 0, since there are no changes at all.

We understand that we should be responsible of pre-filtering out those clusters with identical sequences. However, we still would like to understand where does the "0.8581" come from, since the input tree has all branches with distances = 0.0

Thank you.

**Comment by spond** [comment]
Dear @Cantalapiedra,

What you are seeing is a classic statistical identifiably problem. What `HyPhy` (and other likelihood based tools) infers is the product of evolutionary rates and times, `r` &times; `t`. For identical sequences (up to indels), `t` will be estimated at `0`, which means that `r` (&alpha; and &beta;) can be anything, and the product is still 0. This means, that the rates are not identifiable for identical sequences. This is subtly different from saying that the rates are `0`, although the MLE for rates (assuming `t` &ne; 0) is also 0. The values you see reported are initial guesses for rate parameters that don't get changed. 

As always, what you should look at for inference, are p-values for tests, which will be insignificant for identical sequences.

Which tool are you using for `dN/dS` estimation?

Best,
Sergei

**Comment by Cantalapiedra** [comment]
Dear Sergei,

we are using busted and fubar mainly, although for some tests I had the same results with slac, fel, meme, etc. 

Also, for those alignments with sequences which are different, results for dN/dS are very similar between busted and codeml, whereas for those clusters with only identical sequences busted returns those values close to 0.85, whereas codeml usually reports very large omega values (using model M0).

At the end, in practice, I guess that we just should avoid computing dN/dS with those clusters?

Thank you for your answers

Best,
Carlos

**Comment by spond** [comment]
Dear Carlos,

The "correct" answer for cluster with **only** identical sequences is `dN/dS = n.a`, i.e. can't be estimated. Hence I would suggest that you remove them from your analysis. Check to see if the total tree length reported by any of the `HyPhy` analyses is `0`, and if so, skip the dataset.

Best,
Sergei

**Comment by Cantalapiedra** [comment]
Thank you very much. I am not sure where is it reported the total tree length, but I will try to find out and will skip those.

For the "good" clusters, we are keeping the dN/dS computed under full codon model reported by busted. 

"### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model"

Would that be ok?
