### ISSUE TITLE
cmake -DINSTALL_PREFIX does not work

### ISSUE THREAD

**Issue by smoretti** [veg/hyphy#1071]
Hi

I use cmake 3.12.0 and HyPhy 2.5.1.
For me cmake -DINSTALL_PREFIX=my_path does not work

I have to change it to
`cmake ./ -DCMAKE_INSTALL_PREFIX:PATH=my_path`
to make it work

**Comment by stevenweaver** [comment]
Thank you @smoretti, 

Did you want to submit a pull request to update the README to get credit as a contributor or we can go ahead do that. It's up to you. 

Best,
Steven

**Comment by smoretti** [comment]
You can do it, no need of pull request for this.
Best
