### ISSUE TITLE
"No rule" error building current master branch on Fedora

### ISSUE THREAD

**Issue by ArtPoon** [veg/hyphy#1076]
I was working on installing HYPHY on my teaching server running Fedora, and cloned from the master branch:
```
From http://github.com/veg/hyphy
 * branch              master     -> FETCH_HEAD
   e1420457..fac1356d  master     -> origin/master
Updating e1420457..fac1356d
```

Running `make` after `make clean` and `cmake` raised the following error:
```
make[3]: *** No rule to make target '/usr/lib/gcc/x86_64-redhat-linux/8/libgomp.so', needed by 'hyphy'.  Stop.
make[2]: *** [CMakeFiles/Makefile2:233: CMakeFiles/hyphy.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:144: CMakeFiles/MP.dir/rule] Error 2
make: *** [Makefile:190: MP] Error 2
```

This directory doesn't exist, although `/usr/lib/gcc/x86_64-redhat-linux/9/libgomp.so` does (note 8->9)

I checked out an older release `2.3.14` and was able to compile and install without any problems.

* cmake `3.14.5`
* gcc `9.2.1`
* libgomp `9.2.1`
* Fedora release 30 (Thirty)

**Comment by spond** [comment]
Dear @ArtPoon,

Thanks for reporting this issue. @stevenweaver or @stephenshank : can you please add this configuration to the TravisCI build (if possible) so we can confirm what is going on?

My suspicion is that `CMake` doesn't auto-detect the right OpenMP path (especially if you have multiple gcc toolchains on your system).

Can you look inside `CMakeFiles/Makefile2:233` and see what command is actually triggering the barf?

Best,
Sergei

**Comment by spond** [comment]
Dear @ArtPoon,

Are you building from a clean `cloned` directory or updated in an existing directory? If the latter, try 

```
rm -rf CMakeFiles CMakeCache.txt
cmake ./
make all
```

Best,
Sergei

**Comment by ArtPoon** [comment]
> Dear @ArtPoon,
> 
> Thanks for reporting this issue. @stevenweaver or @stephenshank : can you please add this configuration to the TravisCI build (if possible) so we can confirm what is going on?
> 
> My suspicion is that `CMake` doesn't auto-detect the right OpenMP path (especially if you have multiple gcc toolchains on your system).
> 
> Can you look inside `CMakeFiles/Makefile2:233` and see what command is actually triggering the barf?
> 
> Best,
> Sergei

```
# Target rules for target CMakeFiles/hyphy.dir

# All Build rule for target.
CMakeFiles/hyphy.dir/all:
        $(MAKE) -f CMakeFiles/hyphy.dir/build.make CMakeFiles/hyphy.dir/depend
        $(MAKE) -f CMakeFiles/hyphy.dir/build.make CMakeFiles/hyphy.dir/build
        @$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --progress-dir=/home/apoon42/git/hyphy/CMakeFiles --progress-num=81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100 "Built target hyphy"
.PHONY : CMakeFiles/hyphy.dir/all
```

**Comment by ArtPoon** [comment]
> Dear @ArtPoon,
> 
> Are you building from a clean `cloned` directory or updated in an existing directory? If the latter, try
> 
> ```
> rm -rf CMakeFiles CMakeCache.txt
> cmake ./
> make all
> ```
> 
> Best,
> Sergei

That worked!  Sorry, I thought `make clean` would have cleared out the old configuration.

**Comment by spond** [comment]
Dear @ArtPoon,

No worries. `CMake` has its own cache files (separate from `make`).

Best,
Sergei
