### ISSUE TITLE
How to find source code for some HBL command？

### ISSUE THREAD

**Issue by liu-wq** [veg/hyphy#1080]
Hello,
I think Hyphy is a very powerful tool, but I still need to learn HBL commands if I want to make a little personality model. I can find the source code and description of commands such as estimators.FitLF and utility.Map in the res folder. I still can't find the source code of some commands, although HBL build-in function, HBL command and library reference are described in detail, there are some commands which are not described, such as GetDataInfo, or even listed such as KeywordArgument. I want to learn more about HBL. I hope you can provide a little direction for learning. Where is the source code of these HBL commands? I did not find a function definition in the src folder.
I look forward to getting your answer!

Thank you!
Weiqiang Liu

**Comment by spond** [comment]
Dear @liu-wq,

Unfortunately, there is not a current list of HyPhy batch language commands in one place. I started one a while ago at http://hyphy.org/w/index.php/HyPhy_Batch_Language, but never completed it. Perhaps, I can take your request as a motivation to start documenting some on the current hyphy.org site. Can you respond with a list of specific commands you would like information on?

You can look inside the `C++` source files if you are brave as well. There is some inline documentation there as well.

Best,
Sergei

**Comment by liu-wq** [comment]
Dear Sergei
Most functions are not explained in detail, e.g. functions of estimator class. I think that although it takes big determination to improve HBL, the return is very high. I think you can refer to some programming language books. From data structure to special function of HBL.


Best,
Weiqiang


 原始邮件 
发件人: Sergei Pond<notifications@github.com>
收件人: veg/hyphy<hyphy@noreply.github.com>
抄送: Liu Weiqiang<weiqiang_liu2015@outlook.com>; Mention<mention@noreply.github.com>
发送时间: 2020年2月19日(周三) 06:02
主题: Re: [veg/hyphy] How to find source code for some HBL command？ (#1080)


Dear @liu-wq,
Unfortunately, there is not a current list of HyPhy batch language commands in one place. I started one a while ago at http://hyphy.org/w/index.php/HyPhy_Batch_Language, but never completed it. Perhaps, I can take your request as a motivation to start documenting some on the current hyphy.org site. Can you respond with a list of specific commands you would like information on?
You can look inside the C++ source files if you are brave as well. There is some inline documentation there as well.
Best,
 Sergei

**Comment by spond** [comment]
Dear @liu-wq,

I think you are referring to the library (not built-in) functions, namely the ones in http://hyphy.org/hbl-reference/libv3/ ?

I agree that this documentation is very sketchy. We'll try to improve it. In the meantime, if you have a specific task / change you would like to accomplish, I will be happy to direct you and provide guidance.

Best,
Sergei
