### ISSUE TITLE
GARD terminates with error

### ISSUE THREAD

**Issue by skyungyong** [veg/hyphy#1082]
Dear developers, 

I am running GARD on alignment files, and GARD terminates with error messages for some of the alignments. 

Here is the some part of the error message. How would  this be happening?

Thank you for your help! 

> - __Analysis Version__: 0.1
> 
> type: nucleotide
> rv: GDD
> >How many site rate classes to use (permissible range = [2,10], default value = 4, integer): rate-classes: 3
> >Loaded a nucleotide multiple sequence alignment with **13** sequences, **4119** sites (330 of which are variable) from `OG013.cds.msa.fa`
> >Minimum size of a partition is set to be 23 sites
> 
> 
> ### Fitting the baseline (single-partition; no breakpoints) model
> * Log(L) = -8464.43, AIC-c = 17001.52 (36 estimated parameters)
> 
> ### Performing an exhaustive single breakpoint analysis
> Best sinlge break point location: 1029
>    c-AIC  = 16599.34261043844
> 
> ### Performing multi breakpoint analysis using a genetic algorithm
>  Best break point locations: 1386, 2874
>     c-AIC = 16389.29919469103
> 
> Done with 3 breakpoint analysis.
>     Best break point locations: 982, 1513, 2874
>     c-AIC = 16313.70766359857
> 
> Done with 4 breakpoint analysis.
>     Best break point locations: 812, 1434, 3097, 3556
>     c-AIC = 16228.65249652059
> 
> Done with 5 breakpoint analysis.
>     Best break point locations: 123, 812, 1434, 3097, 3556
>     c-AIC = 16194.05418586989
> 
>     Best break point locations: 123, 812, 1436, 2874, 3313, 3655
>     c-AIC = 16155.52421103128
> Error:
> 
> Master node received an error:Internal error in GARD -- c-AIC INCREASED between two consecutive generations in call to assert(gard.previousBest_cAIC>=gard.currentBest_cAIC, error_msg);
> 
> Function call stack
> 1 :  assert(gard.previousBest_cAIC>=gard.currentBest_cAIC, error_msg);
> 
> -------
> 2 :  ExecuteCommands("assert (`statement`, error_msg)", /usr/local/lib/hyphy/TemplateBatchFiles/libv3/);
> 
> 3 :  [namespace = gard] io.CheckAssertion("gard.previousBest_cAIC >= gard.currentBest_cAIC","Internal error in GARD -- c-AIC INCREASED between two consecutive generations");
> -------
> 4 :  namespace
> 
> Step 0.populationSize=32;
> 
> Step 1.Branch under condition 'populationSize<mpi.NodeCount()-1'
>         to
>                 populationSize=mpi.NodeCount()+1;
>         else
>                 mutationRate=0.8;
> 
> Step 2.populationSize=mpi.NodeCount()+1;
> 
> Step 3.mutationRate=0.8;
> 
> Step 4.rateOfMutationsTharAreSmallShifts=0.5;
> 
> Step 5.maxFailedAttemptsToMakeNewModel=7;
> 
> Step 6.cAIC_diversityThreshold=0.001;
> 
> Step 7.cAIC_improvementThreshold=0.01;
> 
> Step 8.maxGenerationsAllowedWithNoNewModelsAdded=5;
> 
> Step 9.maxGenerationsAllowedAtStagnant_cAIC=100;
> 
> Step 10.addingBreakPointsImproves_cAIC=TRUE;
> 
> Step 11.numberOfBreakPointsBeingEvaluated=1;
> 
> Step 12.Branch under condition 'addingBreakPointsImproves_cAIC'
>         to
>                 numberOfBreakPointsBeingEvaluated+=1;
>         else
>                 <END EXECUTION>
> 
> Step 13.numberOfBreakPointsBeingEvaluated+=1;
> 
> Step 14.generationsAtCurrentBest_cAIC=0;
> 
> Step 15.generationsNoNewModelsAdded=0;
> 
> Step 16.parentModels=gard.GA.initializeModels(numberOfBreakPointsBeingEvaluated,populationSize,numberOfPotentialBreakPoints,bestOverallModelSoFar);
> 
> Step 17.terminationCondition=FALSE;
> 
> Step 18.generation=0;
> 
> Step 19.Branch under condition 'terminationCondition==FALSE'
>         to
>                 childModels=gard.GA.recombineModels(parentModels,populationSize);
>         else
>                 io.ClearProgressBar();
> 
> Step 20.childModels=gard.GA.recombineModels(parentModels,populationSize);
> 
> Step 21.interGenerationalModels=parentModels;
> 
> Step 22.interGenerationalModels*childModels;
> 
> Step 23.gard.GA.evaluateModels(interGenerationalModels);
> 
> Step 24.selectedModels=gard.GA.selectModels(interGenerationalModels,populationSize);
> 
> Step 25.Branch under condition 'gard.GA.modelSetsAreTheSame(selectedModels,parentModels)'
>         to
>                 generationsNoNewModelsAdded+=1;
>         else
>                 generationsNoNewModelsAdded=0;

**Comment by spond** [comment]
Dear @skyungyong,

Thank you for reporting this issue. I will issue a fix shortly and post an update here.

Best,
Sergei

**Comment by spond** [comment]
Dear @skyungyong,

I updated the 2.5.4 release to correct this error which was caused by an oversight on my part. Please update your HyPhy distribution and try again.

Thanks,
Sergei

**Comment by skyungyong** [comment]
Dear @spond,

Thank you for the quick update! GARD works now perfectly. 

best wishes.
