### ISSUE TITLE
Different results for Hyphy BUSTED and MEME

### ISSUE THREAD

**Issue by atha1724** [veg/hyphy#1087]
Hello,
I am a student and was trying to learn how to use and analyze HyPhy BUSTED and MEME. 
I provided the same sequence file to both HyPhy BUSTED and MEME. The results show that -
BUSTED with synonymous rate variation found evidence, while I didn't get any sites showing episodic positive/diversifying selection with MEME. 
Is this because of the algorithm difference or am I doing anything wrong?
Please Help!!

**Comment by spond** [comment]
Dear @atha1724,

This result is not unexpected, especially if you have an alignment with few sequences. BUSTED is a gene-level test, meaning it is able to **combine** information from multiple "weak" site signals to obtain a positive result. MEME uses information from each site individually and, if the alignment is small, often won't reach significant levels. 

Do you have Datamonkey links to your analysis results?

Best,
Sergei

**Comment by atha1724** [comment]
Respected sir,
Thank You for your reply.
I do have the links to my analysis. I will paste them here.
For BUSTED - http://www.datamonkey.org/busted/5e36602c4a93d3783c9ea04b
For MEME - http://www.datamonkey.org/meme/5e37f82a4a93d3783c9ec78c
Please do guide me.
Thank You.

**Comment by spond** [comment]
Dear @atha1724,

You have a very interesting example here, where BUSTED and site-level methods (MEME, FUBAR, FEL) return discordant results with significant confidence. I am still not 100% sure what the root cause of that is, but I'll post a resolution when I have it.

Best,
Sergei

**Comment by atha1724** [comment]
Hello Sir,
Thank You for looking into this. Please do inform me whenever you get to know why the results differ for the same sequence. I would surely like to know more.
Thank You.

**Comment by atha1724** [comment]
Hello @spond,
I had one more sequence file consisting of 37 sequences and in that aBSREL didn't show any selection on any branch. But the other type of tests that I ran upon that sequence file (MEME, BUSTED) did show evidence of selection. Is this also because the number of sequences is less or because of some other reason.
Thank You.

**Comment by spond** [comment]
Dear @atha1724,

Thank you again for bringing this to my attention. You have a very interesting dataset, with curious selection patterns. Examining it led me to discover that for some cases, namely when selected sites also had higher than genome average synonymous rates, MEME might converge to suboptimal rate estimates for such sites, ie. fail to detect selection. I have adjusted MEME settings (and will release them soon) to better handle such scenarios, and there are now positively selected sites reported (see below for text and JSON).

Interestingly, for most of the selected sites in your alignment, there are several tree branches where there are multiple nucleotide substitutions occurring at once (see the attached figure). This is quite unusual and might warrant further investigation.

This, for example, is codon 29:

![slac-ancestral-phylo-3](https://user-images.githubusercontent.com/1018513/75208621-42e93e80-574a-11ea-918a-1b9a746c8092.png)

You can also use https://observablehq.com/@spond/plotting-meme-ebf-on-branches-at-individual-sites to visualize which branches might show evidence of selection with MEME.

Here is a depiction of which branches she support for positive selection at codon 29 under MEME

<img width="640" alt="Screen Shot 2020-02-25 at 6 45 53 AM" src="https://user-images.githubusercontent.com/1018513/75244893-a602c180-579a-11ea-9370-b755632bf438.png">

Best,
Sergei

[1087.MEME.json.zip](https://github.com/veg/hyphy/files/4249802/1087.MEME.json.zip)
---

|   Codon    | Partition  |   alpha    |   beta+    |     p+     |    LRT     |Episodic selection detected?| # branches |
|:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|:--------------------------:|:----------:|
|     29     |     1      |    0.689   |   11.468   |    0.084   |   13.023   |      Yes, p =  0.0006      |     4      |
|    177     |     1      |    0.569   |  179.127   |    0.013   |    3.937   |      Yes, p =  0.0654      |     1      |
|    192     |     1      |    0.073   |   42.875   |    0.012   |   14.684   |      Yes, p =  0.0003      |     1      |
|    194     |     1      |    1.610   |   30.861   |    0.027   |    5.571   |      Yes, p =  0.0281      |     2      |
|    197     |     1      |    0.825   |   28.321   |    0.028   |    3.450   |      Yes, p =  0.0843      |     2      |
|    205     |     1      |    0.929   |   96.811   |    0.012   |    5.591   |      Yes, p =  0.0278      |     1      |
|    211     |     1      |    0.808   |   42.980   |    0.013   |    6.902   |      Yes, p =  0.0142      |     1      |
|    260     |     1      |    1.109   |   50.107   |    0.013   |    6.346   |      Yes, p =  0.0189      |     1      |
|    262     |     1      |    1.496   |   97.042   |    0.012   |    4.405   |      Yes, p =  0.0513      |     1      |
|    266     |     1      |    1.362   |  192.688   |    0.012   |    4.113   |      Yes, p =  0.0597      |     1      |
|    268     |     1      |    0.671   |   44.352   |    0.017   |    4.371   |      Yes, p =  0.0522      |     1      |
|    276     |     1      |    1.453   |   91.078   |    0.028   |    3.627   |      Yes, p =  0.0769      |     2      |
|    309     |     1      |    0.428   |    5.678   |    0.104   |    3.919   |      Yes, p =  0.0660      |     4      |
|    311     |     1      |    0.646   |    7.451   |    0.014   |    3.756   |      Yes, p =  0.0719      |     1      |
|    312     |     1      |    1.098   |  159.362   |    0.013   |    4.323   |      Yes, p =  0.0535      |     1      |
|    342     |     1      |    1.203   |    9.430   |    0.041   |    3.231   |      Yes, p =  0.0946      |     2      |
|    366     |     1      |    0.485   |    6.069   |    0.015   |    3.458   |      Yes, p =  0.0840      |     1      |
|    393     |     1      |    1.555   |   34.829   |    0.076   |    4.728   |      Yes, p =  0.0434      |     3      |
|    411     |     1      |    1.883   |   15.882   |    0.032   |    3.261   |      Yes, p =  0.0931      |     2      |

### ** Found _19_ sites under episodic diversifying positive selection at p <= 0.1**

**Comment by spond** [comment]
Dear @atha1724,

> I had one more sequence file consisting of 37 sequences and in that aBSREL didn't show any selection on any branch. But the other type of tests that I ran upon that sequence file (MEME, BUSTED) did show evidence of selection. Is this also because the number of sequences is less or because of some other reason.

That's a bit different because `aBSREL` does multiple hypothesis testing correction and, unless you do targeted screening, i.e. select a subset of branches a priori, it may lose too much power. 

If you look at the **uncorrected** p-values, do any of them show evidence of selection?

Best,
Sergei
