### ISSUE TITLE
GARD terminates with error

### ISSUE THREAD

**Issue by skyungyong** [veg/hyphy#1089]
Dear @spond,

I have encountered another problem while running GARD. Here is the part of the error messge. 

> - __Analysis Version__: 0.1
> 
> type: nucleotide
> rv: GDD
> How many site rate classes to use (permissible range = [2,10], default value = 4, integer): rate-classes: 3
> Loaded a nucleotide multiple sequence alignment with **13** sequences, **3804** sites (166 of which are variable) from `OG266.cds.msa.fa`
> Minimum size of a partition is set to be 23 sites
> 
> 
> ### Fitting the baseline (single-partition; no breakpoints) model
> * Log(L) = -6684.35, AIC-c = 13441.41 (36 estimated parameters)
> 
> ### Performing an exhaustive single breakpoint analysis
> Done with single breakpoint analysis.
>    Best sinlge break point location: 2627
>    c-AIC  = 13321.0561810831
> 
> ### Performing multi breakpoint analysis using a genetic algorithm
> Done with 2 breakpoint analysis.
>     Best break point locations: 1607, 2868
>     c-AIC = 13276.85624460605
> Done with 3 breakpoint analysis.
>     Best break point locations: 441, 1417, 2868
>     c-AIC = 13218.9037700252
> Done with 4 breakpoint analysis.
>     Best break point locations: 441, 1417, 2868, 3178
>     c-AIC = 13205.59962267284
> [GARD]   5 breakpoints [ generation      1, total models     5988,    0% converged]. Min (c-AIC) =   13201.7938 [ delta =     3.81], breakpoints at 219, 441, 1417, 2868, 31
> [GARD]   5 breakpoints [ generation      2, total models     6019,    1% converged]. Min (c-AIC) =   13201.7938 [ delta =     3.81], breakpoints at 219, 441, 1417, 2868, 3178
> HYPHYMPI terminated.
> Error:
> Internal error
> Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-1006515.591962724] does not match the last recorded LF maximum [-1006446.277244668]

Thank you for your help again!

**Comment by spond** [comment]
Dear @skyungyong,

Could you send me your input data? These internal errors are rare and difficult to debug:(  

Best,
Sergei

**Comment by spond** [comment]
Dear @skyungyong,

This was a subtle bug due to internal node naming in output trees: one was named `Node19` and the other `NODE19` and some of the ancestral reconstruction code was not taking case into account. 

This has been fixed in the `develop` branch with commit 48091351

I am attaching MEME results as well.

Best,
Sergei

[OG271.cds.msa.fa.best-gard.txt.MEME.json.zip](https://github.com/veg/hyphy/files/4238238/OG271.cds.msa.fa.best-gard.txt.MEME.json.zip)

**Comment by spond** [comment]
Dear @skyungyong,

I have worked quite a bit on optimizing the implementation of GARD and your dataset completes using the `develop` branch. The results are attached (view using http://vision.hyphy.org/gard).

Best,
Sergei

[OG266.txt.GARD.json.zip](https://github.com/veg/hyphy/files/4253117/OG266.txt.GARD.json.zip)


Analysis Description
--------------------
GARD : Genetic Algorithms for Recombination Detection. Implements a
heuristic approach to screening alignments of sequences for
recombination, by using the CHC genetic algorithm to search for
phylogenetic incongruence among different partitions of the data. The
number of partitions is determined using a step-up procedure, while the
placement of breakpoints is searched for with the GA. The best fitting
model (based on c-AIC) is returned; and additional post-hoc tests run to
distinguish topological incongruence from rate-variation.

- __Requirements__: A sequence alignment.

- __Citation__: **Automated Phylogenetic Detection of Recombination Using a Genetic
Algorithm**, _Mol Biol Evol 23(10), 1891–1901

- __Written by__: Sergei L Kosakovsky Pond

- __Contact Information__: spond@temple.edu

- __Analysis Version__: 0.1

type: nucleotide
rv: None
>Loaded a nucleotide multiple sequence alignment with **13** sequences, **3804** sites (166 of which are variable) from `/home/sergei/Projects/test/OG266.txt`
>Minimum size of a partition is set to be 23 sites


### Fitting the baseline (single-partition; no breakpoints) model
* Log(L) = -6797.60, AIC-c = 13657.73 (31 estimated parameters)

### Performing an exhaustive single breakpoint analysis
Done with single breakpoint analysis.
   Best sinlge break point location: 2627
   c-AIC  = 13467.83455256095

### Performing multi breakpoint analysis using a genetic algorithm
Done with 2 breakpoint analysis.
    Best break point locations: 1417, 2627
    c-AIC = 13373.70740365584
Done with 3 breakpoint analysis.
    Best break point locations: 441, 1417, 2627
    c-AIC = 13269.35054436436
Done with 4 breakpoint analysis.
    Best break point locations: 367, 629, 1417, 2627
    c-AIC = 13202.7322411751
Done with 5 breakpoint analysis.
    Best break point locations: 367, 629, 1417, 2868, 3178
    c-AIC = 13166.9380267925
Done with 6 breakpoint analysis.
    Best break point locations: 367, 629, 1607, 2189, 2487, 3178
    c-AIC = 13131.67238237345
Done with 7 breakpoint analysis.
    Best break point locations: 367, 629, 1417, 1710, 2147, 2487, 3178
    c-AIC = 13116.45933886882
Done with 8 breakpoint analysis.
    Best break point locations: 367, 629, 1417, 1752, 2113, 2374, 2939, 3178
    c-AIC = 13110.50278190426
Done with 9 breakpoint analysis.
    Best break point locations: 367, 441, 629, 1417, 1710, 2113, 2374, 2939, 3178
    c-AIC = 13113.23102897245
