### ISSUE TITLE
MEME terminates with error when running with GARD output

### ISSUE THREAD

**Issue by skyungyong** [veg/hyphy#1090]
Dear @spond,

I ran GARD with the following command line to obtain the nexus file with predicted multiple tree topology: HYPHYMPI gard --rv GDD --rate-classes 3 --alignment OG271.cds.msa.fa

I ran MEME with the GARD output: HYPHYMPI meme --alignment OG271.cds.msa.fa.best-gard > MEME.out. MEME prints out error messages while running although I got outputs for some sites. 

Below is what is written in the MEME.out file

> - __Analysis Version__: 2.1.1
> 
> 
> code ▒~@~S> Universal
> Loaded a multiple sequence alignment with **12** sequences, **1529** codons, and **2** partitions from `/Users/StaskawiczLab/Desktop/Kyungyong/Tomato-Data-Collection/4-Orthogroups/Orthogroups/New-analysis-output/DONE/OG271/OG271.cds.msa.fa.best-gard`
> 
> branches ▒~@~S> All
> 
> Select the p-value threshold to use when testing for selection (permissible range = [0,1], default value = 0.1):
> pvalue ▒~@~S> 0.1
> 
> 
> ### Branches to include in the MEME analysis
> Selected 21 branches to include in the MEME analysis: `0722_007_N_2_C_CNL_G6, 1269_254_N_2_C_CNL_G6, NODE6, 1316_013_N_1_C_CNL_G6, 1330_243_N_1_C_CNL_G6, NODE10, 2133_012_N_3_C_CNL_G6, 1716_001_N_3_C_CNL_G6, NODE13, NODE9, NODE5, 0411_260_N_1_C_CNL_G6, NODE4, 0422_003_N_2_C_CNL_G6, NODE3, 1039_238_N_2_C_CNL_G6, NODE2, 1401_198_N_1_C_CNL_G6, NODE1, 1404_007_N_2_C_CNL_G6, 1136_062_N_1_C_CNL_G6`
> Selected 21 branches to include in the MEME analysis: `0722_007_N_2_C_CNL_G6, 1401_198_N_1_C_CNL_G6, 1136_062_N_1_C_CNL_G6, NODE4, NODE2, 0411_260_N_1_C_CNL_G6, NODE1, 1269_254_N_2_C_CNL_G6, 0422_003_N_2_C_CNL_G6, 1039_238_N_2_C_CNL_G6, NODE12, 1404_007_N_2_C_CNL_G6, NODE11, NODE9, 1316_013_N_1_C_CNL_G6, 1330_243_N_1_C_CNL_G6, NODE16, NODE8, 2133_012_N_3_C_CNL_G6, 1716_001_N_3_C_CNL_G6, NODE19`
> 
> 
> ### Obtaining branch lengths and nucleotide substitution biases under the nucleotide GTR model
> * Log(L) = -7527.10, AIC-c = 15154.30 (50 estimated parameters)
> 
> ### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
> * Log(L) = -7356.85, AIC-c = 14828.06 (57 estimated parameters)
> * non-synonymous/synonymous rate ratio for *test* =   0.7807
> 
> ### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
> * Log(L) = -7356.65
> * non-synonymous/synonymous rate ratio for *test* =   0.7597
> 
> ### For partition 1 these sites are significant at p <=0.1
> 
> |   Codon    | Partition  |   alpha    |   beta+    |     p+     |    LRT     |Episodic selection detected?| # branches |
> |:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|:--------------------------:|:----------:|
> |     60     |     1      |    0.000   |  1655.646  |    0.080   |    4.355   |      Yes, p =  0.0526      |     1      |
> |    207     |     1      |    0.000   |  545.677   |    0.111   |    3.304   |      Yes, p =  0.0910      |     1      |
> |    521     |     1      |    0.000   |  1019.457  |    0.086   |    3.974   |      Yes, p =  0.0641      |     1      |
> |    775     |     1      |    0.000   |  347.068   |    0.134   |    3.153   |      Yes, p =  0.0985      |     1      |
> |    1074    |     1      |    0.000   |  269.019   |    0.250   |    5.204   |      Yes, p =  0.0339      |     2      |
> |    1077    |     1      |    0.000   |  105.949   |    0.219   |    4.140   |      Yes, p =  0.0588      |     1      |
> |    1146    |     1      |    0.000   |  585.461   |    0.098   |    3.173   |      Yes, p =  0.0975      |     1      |
> Error:
> 
> Master node received an error:HyPhy killed by signal 15
> 
> Function call stack
> 1 :  [namespace = mpi.aux.albjyyLf] MPIReceive(-1, from, result);
> 
> -------
> 2 :  [namespace = mpi.TcSLYavK] node=aux._handle_receieve(queue);
> -------
> 3 :  mpi.QueueJob(meme.queue,"meme.handle_a_site",{"0":"meme.site_likelihood","1":"meme.site_likelihood_bsrel","2":alignments.serialize_site_filter((meme.filter_specification[meme.partition_index])[utility.getGlobalValue("terms.data.name")],(_pattern_info_[utility.getGlobalValue("terms.data.sites")])[0]),"3":meme.partition_index,"4":_pattern_info_,"5":meme.site_model_mapping},"meme.store_results");
> -------
> 4 :  Call("utility.ForEachPair.CB",utility.ForEachPair.key,object[utility.ForEachPair.key]);
> -------
> 5 :  utility.ForEachPair(meme.site_patterns,"_pattern_","_pattern_info_",'
>             if (_pattern_info_[utility.getGlobalValue("terms.data.is_constant")]) {
>                 meme.store_results (-1,None,{"0" : "meme.site_likelihood",
> 

This is a part of what was printed in the terminal. 

> HYPHYMPI terminated.
> Error:
> Attempting to operate on an undefined value; this is probably the result of an earlier 'soft' error condition
> 
> Function call stack
> 1 :  [namespace = woVXodVL] (branch_info[utility.getGlobalValue("terms.synonymous_sub_count")])[s]=(pairwise_counts[utility.getGlobalValue("terms.genetic_code.OPS")])[parent_code][code];
> 
> -------
> 2 :  [namespace = XOZdZGMi] branch_substitution_information=selection.substitution_mapper(ancestral_info["MATRIX"],ancestral_info["TREE_AVL"],ancestral_info["AMBIGS"],^"meme.pairwise_counts",ancestral_info["MAPPING"],(^"meme.codon_data_info")[utility.getGlobalValue("terms.code")]);
> -------
> 3 :  return meme.handle_a_site("meme.site_likelihood","meme.site_likelihood_bsrel","\n        lfunction __make_filter (name) {\n            DataSet hidden = ReadFromString (\"#NEXUS\n\nBEGIN TAXA;\n\tDIMENSIONS NTAX = 12;\n\tTAXLABELS\n\t\t'0722_007_N_2_C_CNL_G6' '1269_254_N_2_C_CNL_G6' '1316_013_N_1_C_CNL_G6' '2133_012_N_3_C_CNL_G6' '1716_001_N_3_C_CNL_G6' '1330_243_N_1_C_CNL_G6' '0411_260_N_1_C_CNL_G6' '0422_003_N_2_C_CNL_G6' '1039_238_N_2_C_CNL_G6' '1404_007_N_2_C_CNL_G6' '1401_198_N_1_C_CNL_G6' '1136_062_N_1_C_CNL_G6' ;\nEND;\n\nBEGIN CHARACTERS;\n\tDIMENSIONS NCHAR = 3;\n\tFORMAT\n\t\tDATATYPE = DNA\n\t\tGAP=-\n\t\tMISSING=?\n\t\tNOLABELS\n\t;\n\nMATRIX\n ---\n ---\n TAC\n ---\n ---\n TTC\n ---\n ---\n ---\n ---\n ---\n ---;\nEND;\");\n            DataSetFilter ^name = CreateFilter (hidden, 3,,,\"TAA,TAG,TGA\");\n        };\n    ",1,{"is_constant":0,"sites":{"0":2}},{"meme.background_fel":{"EFV":{{0.03584791341718316}{0.01544327430326528}{0.02957014835750515}{0.03945605007045674}{0.01439468255821189}{0.006201226516808591}{0.01187385424228031}{0.0158435250932317}{0.01396051905103731}{0.006014188960236306}{0.01151572239875679}{0.01536566249413174}{0.02982354992374527}{0.01284797965252716}{0.02460078458485369}{0.03282532696884994}{0.0210763344887804}{0.009079680901638994}{0.0173854006623131}{0.02319769352300444}{0.008463174437128129}{0.003645933942875007}{0.006981084805939273}{0.009315003371612582}{0.008207913407189149}{0.003535967539575447}{0.006770525646265363}{0.009034050004505835}{0.01753438495905317}{0.007553809715795306}{0.01446372508666785}{0.01929924240911169}{0.03158306836380825}{0.01360597986289704}{0.02605217230454978}{0.03476194310778927}{0.01268213962750215}{0.005463463346961408}{0.01046121557792195}{0.01395861260654003}{0.01229962878039681}{0.005298677746553475}{0.01014569086758168}{0.01353760157138598}{0.02627542655360244}{0.01131944877740301}{0.0216740163452394}{0.02892008060989704}{0.01443815722856837}{0.03688807459795429}{0.01345781250462219}{0.005797623075355135}{0.01110105092304801}{0.01481235791444053}{0.005622758756014067}{0.01076622789499001}{0.01436559674164969}{0.02788250046313353}{0.01201177591292363}{0.02299965595425306}{0.03068890848848116}},"Equilibrium frequency estimator":"Corrected 3x4 frequency estimator","ID":"meme.background_fel","Q":{{"","meme.background_fel.theta_AC*beta*0.1283544697706128","meme.background_fel.theta_AG*alpha*0.2457678753179583","meme.background_fel.theta_AT*beta*0.3279330721313052","meme.background_fel.theta_AC*beta*0.1530914934166736","","",""

Thank you so much!

**Comment by spond** [comment]
Dear @skyungyong,

Could you send me the file `OG271.cds.msa.fa.best-gard` for debugging, please?

Thanks for reporting these issues. I rely on users like you to improve the code and the experience for all involved!

Best,
Sergei

**Comment by spond** [comment]
Dear @skyungyong,

This was a subtle bug due to internal node naming in output trees: one was named Node19 and the other NODE19 and some of the ancestral reconstruction code was not taking case into account.

This has been fixed in the develop branch with commit 4809135

I am attaching MEME results as well.

Best,
Sergei

OG271.cds.msa.fa.best-gard.txt.MEME.json.zip

**Comment by skyungyong** [comment]
Dear @spond,

Thank you for resolving the issue! 

best wishes.
