### ISSUE TITLE
Effects of different tree labelling methods on the output of absrel and busted?

### ISSUE THREAD

**Issue by hongzhonglu** [veg/hyphy#1092]
Dear @spond,
Recently, I am testing branch site model using absrel and busted. I found two main tree labelling methods, like,
(((a #, b#)#, c#)#,d) method1
(((a , b), c)#,d) method2

"#" is as the sign for the "foreground".

I think the method2 is usually used in PAML4.7. I am wondering how the tree labelling methods affect the calculation efficiency and output of absrel and busted. Initially, I found it will take more time if the method1 is used in absrel and busted as it need conduct the calculation for each node.

Thanks for your help!

Best regards,
Hongzhong

**Comment by spond** [comment]
Dear @hongzhonglu,

PAML uses a non-standard Newick format extension which makes no sense for us to support. Please see http://hyphy.org/tutorials/CL-prompt-tutorial/#preparing-labeled-phylogenies 

The format we use is like so:

```
(((a , b), c){Foreground},d)
```

You don't have to use the term "Foreground", any other set name will do for example

```
(((a{Set1}, b{Set1}){Set2}, c{Set2}){Set2},d)
```

Best,
Sergei

**Comment by hongzhonglu** [comment]
Dear Sergei @spond ,
Thanks for your comments! Sometimes the results from the two labelling methods (in the followed) can be different, so how we decide which method is better? Do you have any comment about how to choose the tree labelling method as i found the method2 need more time in the calculation?
(((a , b), c){set1},d)  --------------------------------method1
(((a{Set1}, b{Set1}){Set1}, c{Set1}){Set1},d)----------method2

**Comment by spond** [comment]
Dear @hongzhonglu,

The method is the same, I juts gave two examples. You need to define which group of branches belong to the 'foreground' set. Computational time should not be significantly affected. 

Best,
Sergei

**Comment by hongzhonglu** [comment]
Dear Sergei  @spond,
Thanks very much for your comments.

Best,
Hongzhong
