### ISSUE TITLE
not an issue, but a question about GUI vs command line

### ISSUE THREAD

**Issue by oeco28** [veg/hyphy#1093]
I was checking busted using the GUI interface and I realized that it estimates a tree from the data, and you can immediately select branches and run an analysis. Yet, when I try to run the command line version of it without specifying a tree, it requests a tree. Is there any way to indicate in the command line to estimate a tree and run on all branches?  It is not a big deal to estimate the tree first for each gene and then load it, but I was wondering if there was a way to indicate to hyphy (command line version) that the tree could be estimated from the data (like in the GUI).

your suggestion is much appreciated,
Omar

 This is my command line vs of the invocation:

hyphy busted --alignment OG0000775_macse_NT.fasta --srv No --starting-points 20 --grid-size 500 --save-fit fit.lf

I get the following message:

Analysis Description
--------------------
BUSTED (branch-site unrestricted statistical test of episodic
diversification) uses a random effects branch-site model fitted jointly
to all or a subset of tree branches in order to test for alignment-wide
evidence of episodic diversifying selection. Assuming there is evidence
of positive selection (i.e. there is an omega > 1), BUSTED will also
perform a quick evidence-ratio style analysis to explore which
individual sites may have been subject to selection. v2.0 adds support
for synonymous rate variation, and relaxes the test statistic to 0.5
(chi^2_0 + chi^2_2). Version 2.1 adds a grid search for the initial
starting point. Version 2.2 changes the grid search to LHC, and adds an
initial search phase to use adaptive Nedler-Mead. Version 3.0 implements
the option for branch-site variation in synonymous substitution rates 

- __Requirements__: in-frame codon alignment and a phylogenetic tree (optionally annotated
with {})

- __Citation__: *Gene-wide identification of episodic selection*, Mol Biol Evol.
32(5):1365-71

- __Written by__: Sergei L Kosakovsky Pond

- __Contact Information__: spond@temple.edu

- __Analysis Version__: 3.0

>code –> Universal

>Please select a tree file for the data: (`/path_to_data/`)

At this point I press enter and get the error:

Error:
Illegal right hand side in call to Topology id = ...; it must be a string, a Newick tree spec or a topology

Function call stack
1 :  [namespace = HhlNcT_p] Topology T = (tree_string);

	Keyword arguments:
		{
		 "grid-size":"500",
		 "save-fit":"fit.lf",
		 "srv":"No",
		 "starting-points":"20"
		}
-------
2 :  [namespace = oWHXrwFD] result=trees.ExtractTreeInfo(trees.GetTreeString(look_for_newick_tree));
-------
3 :  [namespace = CbfoEwFm] tree_info=trees.LoadAnnotatedTopologyAndMap(TRUE,mapping);
-------
4 :  [namespace = busted] partitions_and_trees=trees.LoadAnnotatedTreeTopology.match_partitions(codon_data_info[utility.getGlobalValue("terms.data.partitions")],name_mapping);
-------
5 :  [namespace = busted] load_file("busted");
-------
6 :  namespace 

Step 0.LoadFunctionLibrary("modules/shared-load-file.bf", /usr/local/lib/hyphy/TemplateBatchFiles/SelectionAnalyses/);

Step 1.load_file("busted");;
-------

Check errors.log for execution error details.

Check messages.log for diagnostic messages.

**Comment by spond** [comment]
Dear @oeco28,

If I understand correctly, you'd like the option to automatically estimate a (**crude**) tree using neighbor joining and perform the test on it?

Best,
Sergei

**Comment by oeco28** [comment]
Correct. These are strains of bacteria from the same species and I don't
expect the ML gene trees to be too different from a NJ tree.
 Is there an option in the command line for that?
 If you think it is better to estimate the ML tree and run the analyses on
this, then I would go with that

**Comment by spond** [comment]
Dear @oeco28,

There's currently not an option, but I can add one in the next commit to the `develop` branch. 

Best,
Sergei

**Comment by oeco28** [comment]
Thank you Sergei!
  Out of curiosity. The tree estimated in the GUI is a NJ or UPGMA?

**Comment by spond** [comment]
Dear @oeco28,

NJ using the TN93 distances.

Best,
Sergei

**Comment by spond** [comment]
Dear @oeco28,

NJ using the TN93 distances.

Best,
Sergei

**Comment by oeco28** [comment]
thanks!



On Tue, Feb 25, 2020 at 9:24 AM Sergei Pond <notifications@github.com>
wrote:

> Dear @oeco28
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_oeco28&d=DwMCaQ&c=C3yme8gMkxg_ihJNXS06ZyWk4EJm8LdrrvxQb-Je7sw&r=1YnLN6ptmFumCtKMs62AHQdWF0mxKnIbu0uh8D6U1rE&m=5corsl_H6PyC-7q7zvGRmkOPS9lRLqu7G9jpHriGrdo&s=sg51LDoZHJxrwAUeChmKjFPwdu1YIKbKxQIKft5qf54&e=>
> ,
>
> NJ using the TN93 distances.
>
> Best,
> Sergei
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_veg_hyphy_issues_1093-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DADNNQ2ZDBWPSSPOIB7FFVIDREVH4VA5CNFSM4K26IEXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEM4W67A-23issuecomment-2D590966652&d=DwMCaQ&c=C3yme8gMkxg_ihJNXS06ZyWk4EJm8LdrrvxQb-Je7sw&r=1YnLN6ptmFumCtKMs62AHQdWF0mxKnIbu0uh8D6U1rE&m=5corsl_H6PyC-7q7zvGRmkOPS9lRLqu7G9jpHriGrdo&s=Wrma9-TPM8vrubOLUgketJ2Igzkt6PsyXxt2q-R667c&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNNQ267PN75CMUYME6DVFLREVH4VANCNFSM4K26IEXA&d=DwMCaQ&c=C3yme8gMkxg_ihJNXS06ZyWk4EJm8LdrrvxQb-Je7sw&r=1YnLN6ptmFumCtKMs62AHQdWF0mxKnIbu0uh8D6U1rE&m=5corsl_H6PyC-7q7zvGRmkOPS9lRLqu7G9jpHriGrdo&s=lh4W11w7o3Xn9PxK4OEXfLzB4MZdlytwrFDVo2Q6JEs&e=>
> .
>


-- 
Omar E. Cornejo, PhD
Assistant Professor,
School of Biological Sciences
Washington State University
Heald 429.  PO Box 644236
Pullman, WA. 99164-4236

**Comment by spond** [comment]
Dear @oeco28,

In the 2.5.6 release of HyPhy (releasing today), you now have the option to ask HyPhy to automatically build NJ trees for most analyses. You do so by calling

```
hyphy busted --alignment file --tree neighbor-joining 
```

The rules for which tree will be used is as follows

1. If the alignment file includes a tree string, it will be used
2. If there is a file titled `neighbor-joining` in the current directory, it will be used (this is a bit of a kludge)
3. Otherwise (no tree in the alignment, no file named `neighbor-joining` (which is the case you asked for), build a TN93-distance based NJ tree.

Best,
Sergei

**Comment by oeco28** [comment]
Cool!
  thank you Sergei. Your comment made me reconsider a bit what I was doing.
I am going to compare the results with the NJ.  I had run it by estimating
a ML tree and then the BUSTED model See code below:

for i in `cat list`; do
        raxml -m GTRGAMMAI -p 1231211 -# 2 -s ''$i''_macse_NT.fasta -n rax01
        hyphy busted --alignment ''$i''_macse_NT.fasta --tree
RAxML_bestTree.rax01 --srv No --starting-points 20 --grid-size 500
--save-fit hyphy_out/$i.lf > hyphy_out/$i.hyphy.out
        mv ''$i''_macse_NT.fasta.BUSTED.json hyphy_out/
        rm RAxML_*
done

thank you so much for the update!! I will certainly help with future
analyses!

Omar

On Sat, Feb 29, 2020 at 6:37 AM Sergei Pond <notifications@github.com>
wrote:

> Dear @oeco28
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_oeco28&d=DwMCaQ&c=C3yme8gMkxg_ihJNXS06ZyWk4EJm8LdrrvxQb-Je7sw&r=1YnLN6ptmFumCtKMs62AHQdWF0mxKnIbu0uh8D6U1rE&m=LGFQi9AeECnXCjCP6TnYPnXbq-HgUggTZ7bGN1Tdwuc&s=8GVQdj6gYWVyaqcQ8rPUuwU516GbkqGAKiwtw75lrQM&e=>
> ,
>
> In the 2.5.6 release of HyPhy (releasing today), you now have the option
> to ask HyPhy to automatically build NJ trees for most analyses. You do so
> by calling
>
> hyphy busted --alignment file --tree neighbor-joining
>
> The rules for which tree will be used is as follows
>
>    1. If the alignment file includes a tree string, it will be used
>    2. If there is a file titled neighbor-joining in the current
>    directory, it will be used (this is a bit of a kludge)
>    3. Otherwise (no tree in the alignment, no file named neighbor-joining
>    (which is the case you asked for), build a TN93-distance based NJ tree.
>
> Best,
> Sergei
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_veg_hyphy_issues_1093-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DADNNQ24ZUO2KWRAGKZGU43LRFEOS3A5CNFSM4K26IEXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENL3TWA-23issuecomment-2D592951768&d=DwMCaQ&c=C3yme8gMkxg_ihJNXS06ZyWk4EJm8LdrrvxQb-Je7sw&r=1YnLN6ptmFumCtKMs62AHQdWF0mxKnIbu0uh8D6U1rE&m=LGFQi9AeECnXCjCP6TnYPnXbq-HgUggTZ7bGN1Tdwuc&s=S-bQDdAYZ0mY3SfXK6OIphdiR1gAFrGkiHYReLg4f7o&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNNQ2ZNDCXVTIRINPYUSJ3RFEOS3ANCNFSM4K26IEXA&d=DwMCaQ&c=C3yme8gMkxg_ihJNXS06ZyWk4EJm8LdrrvxQb-Je7sw&r=1YnLN6ptmFumCtKMs62AHQdWF0mxKnIbu0uh8D6U1rE&m=LGFQi9AeECnXCjCP6TnYPnXbq-HgUggTZ7bGN1Tdwuc&s=zXbja6hUittiZJKVT9ZTPCrudeeQmQGzIwN1h0ttvug&e=>
> .
>


-- 
Omar E. Cornejo, PhD
Assistant Professor,
School of Biological Sciences
Washington State University
Heald 429.  PO Box 644236
Pullman, WA. 99164-4236
