### ISSUE TITLE
Using HYPHY MEME

### ISSUE THREAD

**Issue by atha1724** [veg/hyphy#1095]
Hello Sir @spond,
Very Sorry to bother you again. I have multiple files that I want to run MEME on to detect for selection. In our last conversation thread, you mentioned my sequence file was peculiar and hence brought to your attention a situation were MEME fails to detect selection. While the original showed 0 sites, the result file you sent back after making changes to MEME show 19 sites under selection. 
I have other sequence files that I ran through MEME show selection at 2 to 3 sites. I think that there may be more sites that MEME failed to detect. You mentioned that you made some changes to MEME which gave better results for my sequences. I want to rerun my files on MEME with the changes you made. I wanted to know if there's any way that I can get the MEME with changes. If this is not possible,  when will you be updating MEME as you had mentioned that you will in our last conversation thread? 
Thank You.

**Comment by spond** [comment]
Dear @atha1724,

These changes have been released to the `develop` branch. It will take a bit of time for them to make their way to datamonkey.org, but in the meantime you can use the new version of the analysis on your local computer.

You need to:

1. Download and build development HyPhy branch (see the README file at https://github.com/veg/hyphy-analyses/)

2. Run 

```./hyphy meme --alignment yourfile``` 

3. Visualize the resulting JSON file in http://vision.hyphy.org/meme

Best,
Sergei
