### ISSUE TITLE
Very high w1 values

### ISSUE THREAD

**Issue by GlennDC03** [veg/hyphy#1103]
Hi,
I've been running aBSREL for a dataset of one gene from 58 species. I'm a little confused by some of the output. For a few leaf branches and also internal nodes I'm getting a really high w1 value (ω1 = 10000000000 (100%)). I'm not quite sure how to interperet this value and I don't know if it's something I've done wrong or not. 
I saw the comments from #393 and #1066, the LRT test for the high w1 values is non-significant

Any advice would be much appreciated.
Thank you.

**Comment by stevenweaver** [comment]
Dear @GlennDC03, 

Would it be possible to clarify a little more on what wasn't addressed in the previous comments to better help? If the values are deemed non-significant, then there is not enough statistical support to report on the ω values for those branches. 

Best,
Steven

**Comment by spond** [comment]
Dear @GlennDC03,

To add to what @stevenweaver wrote, the very high &omega; usually arise when the estimate of dN/dS is imprecise and infinity, i.e. when a branch one has non-synonymous substitutions. The statistically principled way to interpret this value might be: 

> This branch has an unreliable point estimate that is not significantly different from neutrality, &omega; = 1. Unreliable estimates usually stem from lack of signal, i.e. small effective sample sizes, e.g. short branches (few substitutions) especially coupled with short alignments.

Best,
Sergei

**Comment by GlennDC03** [comment]
Firstly, thank you both for replying. 
@stevenweaver I'm fairly new to these kind of tests and these high w-values were on one of the branches of interest of mine, so even though they were non-significant I was just wanting to try and understand what would cause such high values. 
@spond my results make more sense now that I've read what you responded, as all the branches with the high w-values are very short branches, of either species from the same genera or very closely related species. 
Once again thank you both for replying, I really appreciate it.
Cheers,
Glenn
