### ISSUE TITLE
Non-coding sequences positive selection analysis ERROR

### ISSUE THREAD

**Issue by va89fa** [veg/hyphy#1104]
Dear @spond

I have tried to analyze non-coding sequences positive selection using testforpositiveselection.bf
all the positive selection analyses of groups under study have been calculated successfully, yet there remains two groups with 618 number of sequences and 6615 bp for the length of coding alignment, which encounter the following error:

Error:
Internal error
Likelihood function evaluation encountered a NaN (probably due to a parameterization error or a bug).

Function call stack
1 :  Optimize(MLEs, L);

-------
2 :  res_null=fitNullModel(0);
-------

p.s. I am using the software for positive selection analysis under the following instructions: 

HyPhy 2.5.1 (MP) for Linux on x86_64
nonCodingSelection.bf (https://github.com/spond/TestForPositiveSelection)

Synonymous sites>Universal>coding alignment>tree file> Wong and Nielsen test> query alignment (non-coding alignment)> [Null-Alternative 2] ALTERNATE= class 1: Negative, class 2: neutral evolution and class 3: positive selection> [Both] Bayes Empirical Bayes and Naive Empirical Bayes

**Comment by spond** [comment]
Dear @va89fa,

Can you please provide the entire set of inputs (including the alignments) for me to debug this issue?

Best,
Sergei

**Comment by va89fa** [comment]
Dear @spond 

I emailed you the inputs via spond@temple.edu

Best,
Vafa

**Comment by va89fa** [comment]
Dear @spond 

I just want to make sure if there is a way to resolve this issue?

Best,
Vafa

**Comment by va89fa** [comment]
hello dear hyphy team,

is there a way to debug the mentioned issue above?

best,
Vafa

**Comment by spond** [comment]
Dear @va89fa,

Sorry for dropping the ball on this; looking into the cause of the issue.

Best,
Sergei

**Comment by va89fa** [comment]
Dear @spond 

thanks for your precious time and effort.

**Comment by spond** [comment]
Dear @va89fa,

Still looking into it, a non-trivial issue.

Best,
Sergei

**Comment by va89fa** [comment]
dear @spond 

I appreciate your effort

**Comment by spond** [comment]
Dear @va89fa,

Please download the `develop` branch of HyPhy **and** an update to the scripts from https://github.com/spond/TestForPositiveSelection

Let me know if that works for you.

Best,
Sergei

**Comment by va89fa** [comment]
Dear @spond 

thanks so much. it worked and the issue is solved !
