### ISSUE TITLE
aBSREL not taking .nex file but taking .fasta

### ISSUE THREAD

**Issue by Ciznetwork** [veg/hyphy#1106]
I have been trying to run aBSREL with a partitioned file I saved from GARD analysis, but it keeps throwing an error. When I tried with initial .fasta files it worked. Please kindly help with this as I intend to use the partitioned file from GARD for this downstream selection analysis. Or is there a means to save the partitioned file from GARD as .fasta?

Thanks!

**Comment by Ciznetwork** [comment]
I was doing this on the datamonkey server.

Thanks

**Comment by stevenweaver** [comment]
Dear @Ciznetwork, 

Support for GARD files with multiple partitions have been slated for release by datamonkey for some time, but is still in development. Until then, only one partition can be used for each aBSREL analysis.

Apologies,
Steven
