### ISSUE TITLE
aBSREL: High omega values (clarification)

### ISSUE THREAD

**Issue by joannabaker** [veg/hyphy#1110]
Dear all, 

I have read posts [#393](https://github.com/veg/hyphy/issues/393), #1066 and #1103 and I understand the implication and interpretation of high omega values. However, I just had a couple of other minor queries - I hope that this is okay.

Firstly, is it true that I should interpret **any** high value of omega as simply "large" (i.e. any value >1)? That is, my instinct tells me that differences between omega = 1.5 vs 2 vs 100 vs 10000 are important. Perhaps they are not; but if so, what definition would you suggest is reasonable to identify "high values"?

Secondly, what if many omega values in my results are very high ? At what point do I get worried about not seeming to have enough synonymous substitutions! For example, I have recently run an aBSREL analysis over a dataset of 475 branches, identifying 37 instances of episodic diversifying selection. All but 7 of these omega > 1 as one of the rate classes. In total, >100 branches in the tree (~25%) have at least one rate class  where omega > 1. Is this problematic?

For your reference, I attach the jSON output for the example I mention here. 

[Ma_abs.zip](https://github.com/veg/hyphy/files/4324331/Ma_abs.zip)

Thanks in advance and best wishes,

Jo

**Comment by spond** [comment]
Dear @joannabaker,

By definition, any branch that is detected to subject to episodic selection, **must** have at least one &omega; > 1 (i.e. for all 37 of your branches).

>Firstly, is it true that I should interpret any high value of omega as simply "large" (i.e. any value >1)?  That is, my instinct tells me that differences between omega = 1.5 vs 2 vs 100 vs 10000 are important.

**Large** here should be synonymous with infinite, i.e. something **quite** different from 1, especially if the p-value yields a significant result. I would not interpret any &omega; > 1 as large.

You need to consider the entire distribution of &omega; along a branch. For example here,

<img width="920" alt="Screen Shot 2020-03-13 at 11 26 13 PM" src="https://user-images.githubusercontent.com/1018513/76674097-158df480-6582-11ea-84e0-529f431681d7.png">

most of the sequence (96%) along this branch is happily evolving with very low &omega; indicating conservation and synonymous changes aplenty. It's just that a small fraction (4%) of sites have high rates of non-synonymous change. 

Hopefully this helps.

Best,
Sergei

**Comment by joannabaker** [comment]
Hi @spond, 

Apologies for the delay in the response - lots of other things going on as you might expect. 

This is useful, though I'm still a little bit unclear on what is "quite" different. As someone with limited experience, is there some sort of rule-of-thumb threshold you might consider large enough to be considered 'infinite'?

Best wishes,

Jo

**Comment by spond** [comment]
Dear @joannabaker,

As a rule of thumb, &omega; over 50 could be considered infinite.

Best,
Sergei

**Comment by joannabaker** [comment]
@spond Thank you very much for your advice and information.
