### ISSUE TITLE
FUBAR find more sites than MEME consistently

### ISSUE THREAD

**Issue by fagire** [veg/hyphy#1111]
Hi,

I'm analizying multiples phylogenies (for two genes) using FUBAR and MEME and consistently FUBAR is finding more selected sites than MEME. Since pervasive selections is a particular case of episodic selection I was expecting the opposite. Is this normal ?

I'm locally running hyphy (2.5.1) but I'm getting the same results using datamonkey. 

thank you!

Facundo

**Comment by spond** [comment]
Dear @fagire,

Can you provide me with one example (Datamonkey links for FUBAR and MEME on the same dataset)? There was an issue with MEME (resolved in 2.5.4) that sometimes could lead it to fail to converge, causing false negative results to occur.

Best,
Sergei

**Comment by fagire** [comment]
Dear spond,

MEME link: http://www.datamonkey.org/meme/5e6a9ce2f2d22859c6419ff0
FUBAR link: http://www.datamonkey.org/fubar/5e6a9ce9f2d22859c6419ffc

thank you,

Facundo

**Comment by spond** [comment]
Dear @fagire,

Ah -- your alignments are small and have low divergence. Site-level tests will generally have lower power there. 

You can also see that the site that were marked as positively selected by FUBAR (`83`) is also showing some weak evidence for selection with MEME (p-value ~ 0.23)

Best,
Sergei
