### ISSUE TITLE
Error  about running RELAX in datamonkey

### ISSUE THREAD

**Issue by syl570870922** [veg/hyphy#1115]
Good morning,

I'm trying to run RELAX on datamonkey and keep getting an email that “We're sorry, there was an error processing your job. Please try again, or visitour GitHub issues and create an issue if the issue persists”.

/var /spool/ torque/mom priv/jobs/1138293. localhost. SC: line 25: [: missing ]'
Check errors.log for execution error details.

Even if I reuse the previous successful file , It still shows errors like this. 
Please tell me how to solve it. Thank you very much !

**Comment by spond** [comment]
Dear @syl570870922,

It appears that a recent update to Datamonkey caused this error to occur.
We will investigate.

Best,
Sergei

**Comment by stevenweaver** [comment]
Issue should be resolved.

**Comment by syl570870922** [comment]
Dear @spond @stevenweaver 
Thank you for telling me this bug .
I just learned that it had been solved.
