### ISSUE TITLE
multi-nucleotide mutation consideration in aBSREL?

### ISSUE THREAD

**Issue by kingcohn1** [veg/hyphy#1119]
Hello:

Thank you for maintaining this useful program! I was able to to use aBSREL quite effectively to identify positive selection in particular species from thousands of shared orthologs- yay! But I recently came upon a [publication](https://www.nature.com/articles/s41559-018-0584-5) explaining the high possibility of false positives with branch site tests like BUSTED. So, I'm wondering how mnm's might affect aBSREL, and if this something I should consider when running this test specifically or are these mutations more impactful on site specific branch-site tests? Thanks and hope you're well. 

Zach

**Comment by spond** [comment]
Dear @kingcohn1,

That's a good paper you cite (I reviewed it:)

We have a paper out for review which is basically arguing the same thing in a broader context (http://hyphy.org/resources/fmm.pdf). We have a model out (http://hyphy.org/methods/other/FitMultiModel/#fitmultimodel) which you can try out to see how much multi-base hits might affect your data.

We also have a version of BUSTED that allows you to include MH at https://github.com/veg/hyphy-analyses/tree/master/BUSTED-MH 

Please let me know if it works for you.

Best,
Sergei

**Comment by kingcohn1** [comment]
Awesome! This is exactly what I'm looking for, thanks for sharing Sergei!

**Comment by kingcohn1** [comment]
Hello again Sergei,

Thanks again for your insight and sharing that batchfile with me to test my data. I still have a couple questions and value your expertise. I ran this on a subset (500 alignments) of my data. 80% did not have any sites showing preference for a mh model. I then compared the remainder, 100 alignments with mh preference, with the output from aBSREL which I ran on the complete data set of >20,000, and found 70% of these suggested positive selection on at least one branch. Of the 400 that did not show mh model preference only 18% suggested positive selection on at least one branch. I'm not entirely sure how to reconcile/interpret these data...my goal was to compare the proportion of shared genes under selection among these species, which is why I didn't use the BUSTED procedure, do you think I should now rerun these data using the updated BUSTED-MH as ~20% necessitate a mh model? Apologies if this isn't super clear and thanks for any advice you can offer. 

Best,
Zach

**Comment by spond** [comment]
Dear @kingcohn1,

I would look at LRT p-values as the evidence of preference (it is not necessary to have individual sites show up), but that won't make a huge difference in fractions. 

It is really difficult to interpret your aBSREL findings: a positive aBSREL finding could be a function of many things, including branch lengths, selection strength, etc. For example if you your 80% are of systematically lower diversity (total tree length), then **all** tests will have lower power. 

The only reliable way to test is to directly incorporate MH into a specific model. Can you tell me **how** you are using aBSREL? I don't quite understand your setup.

Best,
Sergei

**Comment by kingcohn1** [comment]
good evening Sergei,

Thanks for the quick reply. A quick gander at the p-values and they're below significance threshold indeed. So, I used aBSREL to identify genes under selection among 10 closely related insect species of the same genus (less diverse than Drosophila but more than human). I curated the significant results by species then used gene ontology to associate shared and unique genes among the species with phenotypes, like detoxification and chemosensation. Some of these shared sites from the aBSREL were further scrutinized using the Bayes emperical Bayes test for codon selection via paml, these results supported one another but I wish I had known about MH bias before I had done all this...I'm reluctant to redo this primary step but obviously don't want to be making bad interpretations from false positives. Thanks again for your consideration. 

Sincerely,
Zach

**Comment by spond** [comment]
Dear @kingcohn1,

BEB analysis in PAML and `aBSREL` don't really confirm each other; it is not necessary for BEB to find individual sites under selection if `aBSREL` finds evidence of episodic selection on the branch. One big difference here is that `aBSREL` makes no assumptions about the selective regime on branches that you are **not** testing (background), and PAML's models do -- and those assumptions are very strong (e.g. no selection on background). We showed in our [2011 paper](https://www.ncbi.nlm.nih.gov/pubmed/21670087) (see Fig 1 and Figs S1-S3) that this can lead to very bad statistical artifacts that don't even involve MH.

When you say `used aBSREL to identify genes under selection`, do you mean to identify specific branches under selection in individual genes? So for each pair of (gene, insect species) you could then assign a 1/0 attribute (selected or not)?

That's sensible, but I don't see why you need to run additional tests afterwards. If you use PAML's BEB to test branches that `aBSREL` found using the same data, this is statistically speaking, invalid (a form of [HARKing, Hypothesizing after results are known](https://www.ncbi.nlm.nih.gov/pubmed/15647155)). Your BEB tests, if set up this way, will be likely biased to confirm your initial findings, for example.

If you are concerned about MH, then you should consider fitting aBSREL models where there is an additional component dealing with multiple hits. 

Best,
Sergei

**Comment by kingcohn1** [comment]
Hello Sergei,

Thank you again for the helpful and thorough reply, yes for those reasons I decided on aBSREL as opposed to other branch-site tests and that is how I coded the results, more or less. BEB was used to identify specific sites...this step might be redone using BUSTED-MH now, although we don't want to keep HARKing. Anyway, your last statement is more or less what I'm getting at. 
Best,
Zach

**Comment by spond** [comment]
Dear @kingcohn1,

In v2.5.9 (released today), you can specify the `--multiple-hits Double` or `--multiple-hits Double+Triple` command line option for aBSREL to allow **branch-level** MH rates. I have not formally evaluated this test on simulated data; it may be quite statistically underpowered, but you are welcome to try it on your data.

Best,
Sergei

**Comment by spond** [comment]
Dear @kingcohn1,

Would you mind reporting back here on some comparative results with and without MH? My expectations are 

1). Generally lower power for MH tests (more parameters).
2). Strong effect on short branches (significant without MH, not-significant with MH).
3). For branches where MH rates (&delta;) are >0, you should see a reduction in &omega; estimates compared to the standard (no MH) model.

Best,
Sergei

**Comment by kingcohn1** [comment]
Hello Sergei,

Apologies for not replying sooner-I quickly ran this and then neglected to
follow up with you. On a set of ~500 loci, 137 of these showed evidence of
selection (on at least one branch) in the single-model test whereas five
suggested selection for the MH test. Of five that had evidence, two were
significant in the basal taxon (longest branch) and three were on
intermediate and short branches.


*Zachary Cohen*
*Wisconsin Distinguished Graduate Fellow *
*University of Wisconsin Madison*
*Russell Laboratories Entomology*
*1630 Linden Dr #637*
<https://maps.google.com/?q=1630+Linden+Dr+%23637+Madison+Wisconsin+53706&entry=gmail&source=g>
*Madison Wisconsin 53706*
<https://maps.google.com/?q=1630+Linden+Dr+%23637+Madison+Wisconsin+53706&entry=gmail&source=g>

**Comment by eroycroft** [comment]
Hi Sergei @spond 

I have recently tested out the `--multiple-hits Double` and `--multiple-hits Double+Triple` options in aBSREL, and was wondering about possible options to address the power issue. 
Would it make sense use a likelihood ratio test to compare the likelihood from a standard aBSREL model, to that of the model that accounts for Double/Triple hits?

If so - which values could be used from the output to do this? I wondered whether I could compare the likelihood and no. of parameters that are output under 'Full adaptive model"? In one example I have run on my data, the standard aBSREL model has 194 parameters, but when I add the Double+Triple option, it increases to 308 parameters, and only a very small likelihood increase. So I wonder if it really makes sense to add these additional parameters. (If it is relevant, I am testing two foreground branches for positive selection in these analyses).

Any suggestions you have would be much appreciated.

Best wishes,
Emily

**Comment by spond** [comment]
Dear @eroycroft,

aBSREL will output `c-AIC` scores for each models (those are corrected Akaike Information Scores), which reward models for better fit (higher logL) and penalize the for each parameter. If you wish to determine which model fits the data better, run standard aBSREL, aBSREL with Double rates, and aBSREL with Double/Triple hits and compare the `c-AIC` scores. The one with the lowest score provides the best fit to the data, and the magnitude of `c-AIC` difference is indicative of the relative support for each model. 

Roughly speaking, `exp (0.5 &Delta; c-AIC)` (Akaike weights), are the support values for each model, e.g., if one model has a lower score by 10 points, it is about 150x more likely that the other.

Best,
Sergei

**Comment by eroycroft** [comment]
Dear @spond 

That's really helpful, thank you very much for getting back to me. I'm also wondering about interpreting the rate value of 2x and 3x MNMs in the output. If I understand, this value is the rate of double-nucleotide (or triple) substitutions relative to single-nucleotide substitutions? 

If so, I am wondering how I should interpret larger values of this rate among my results. The majority are mostly zero (or very close to zero), but then a range of higher values occasionally appear, up to a max of 10,000. 
Is a very high value meaningful, or maybe a calculation issue? If so, is there an upper limit at which you would interpret these are meaningful?

Thanks again,
Emily

**Comment by spond** [comment]
Dear @eroycroft,

Such large values are effectively infinite. That's pretty much all you can say about them; that might mean that **all** substitutions along a branch (at least at a fraction of sites) involve multiple hits.

Best,
Sergei
