### ISSUE TITLE
Skip batch file option in command line?

### ISSUE THREAD

**Issue by juliayork** [veg/hyphy#1121]
Hello, I installed HyPhy but I am running into a problem when trying to run the program either interactively or directly, I enter:
>hyphy -i
or
>hyphy relax --alignment file.txt
and it says:
Batch file to run: ('path/to/hyphy')

I don't have a batch file, I'm just trying to run analyses individually. Is this possible? Thanks!

**Comment by spond** [comment]
Dear @juliayork,

HyPhy is not finding its libraries. Two questions

1. How did you install HyPhy?

2. What HyPhy is looking for is `res/TemplateBatchFiles`. It should be in the install directory. So you if you go the source directory of HyPhy, and call `./hyphy` you should be able to run the analysis.

Best,
Sergei

**Comment by juliayork** [comment]
Oh okay, that makes sense. I installed hyphy into my bin under the hyphy directory but then I moved the actual program to the bin (one directory up) because the program can't be found when it is in the hyphy directory. When I move it to the bin, then I can access it, but it asked for the batch file. I moved it back. I can get it to work now by entering the hyphy directory within the bin directory and then running it. This is a little inconvenient though, shouldn't I be able to run the program from any directory? Do you have suggestions for fixing this issue? Thank you for the help.

**Comment by spond** [comment]
Dear @juliayork,

You can run it from anywhere you'd like, you just need to specify where the library directory is. Use

```
hyphy LIBPATH=/path/to/hyphy/res ...
```

Best,
Sergei

**Comment by juliayork** [comment]
This works! Thanks much
