### ISSUE TITLE
why some nodes show "test not run"  when using aBSREL

### ISSUE THREAD

**Issue by hongzhonglu** [veg/hyphy#1125]
Dear Dear Sergei @spond ,
When i check the result from aBSREL, i found some nodes show "test not run" under the item of "LRT"  when visualising the result by hyphy vision. Do you know the reason?
[OG4312.ABSREL.json.zip](https://github.com/veg/hyphy/files/4445028/OG4312.ABSREL.json.zip)

Best regards,
Hongzhong

**Comment by spond** [comment]
Dear @hongzhonglu,

Did you select all branches for testing? `test not run` will appear when some branches are explicitly excluded by the user (e.g. if you elect to test only Internal branches).

Best,
Sergei

**Comment by hongzhonglu** [comment]
Dear Dear Sergei @spond ,
Great thanks for your help.
I only choose the Foreground branches for the testing. This is my script:
mpirun -np 20 HYPHYMPI LIBPATH=/cephyr/users/luho/Hebbe/hyphy/res/ /cephyr/users/luho/Hebbe/hyphy/res/TemplateBatchFiles/SelectionAnalyses/aBSREL.bf --alignment /cephyr/users/luho/Hebbe/cds_align_guidance_new/OG5609_code.fasta --tree /cephyr/users/luho/Hebbe/cds_align_guidance_new_tree_unroot_label/OG5609_aa_unroot_LABEL.tre --branches Foreground --output /cephyr/users/luho/Hebbe/absrel_result/OG5609.ABSREL.json

Best,
Hongzhong

**Comment by spond** [comment]
Dear @hongzhonglu,

In this case you would expect there to be some branches that are not tested (anything that's not labeled `Foreground`)

Best,
Sergei

**Comment by hongzhonglu** [comment]
Thanks a lot!
