### ISSUE TITLE
Does hyphy have tools to do convergent evolution analysis?

### ISSUE THREAD

**Issue by hongzhonglu** [veg/hyphy#1126]
Dear Sergei @spond,
I have a new question about the convergent evolution analysis. So I put a new issue here.
As reported there are some tools to detect the sites which have the convergent evolution in specific interesting branches, like toolbox PCOC (https://github.com/CarineRey/pcoc).
I am not sure whether FADE (FUBAR Aproach to Directional Evolution) could do the same work: to estimate which sites from different tested branches belong to the convergent evolution. 
Looking forward to your comment. Thanks very much!

Best,
Hongzhong

**Comment by spond** [comment]
Dear @hongzhonglu,

Looks like PCOC has phenotype information.

HyPhy has methods for detecting co-evolution / epistasis (BGM), but no formal tests for convergent evolution. If your definition of convergent evolution is repeated substitutions at the same sites, then BGM can detect those. However it will not take the target amino-acid/codon into account.

Best,
Sergei

**Comment by hongzhonglu** [comment]
Dear Sergei
Thanks for the information!

Best,
Hongzhong
