### ISSUE TITLE
Ancestral State Reconstruction Likelihoods in SLAC?

### ISSUE THREAD

**Issue by jteisher** [veg/hyphy#1127]
Hello,

I apologize if this information is recorded somewhere, but I have been looking through the documentation and cannot find whether the ML values from the ancestral state reconstruction done in SLAC are recorded anywhere. The ML codons and amino acids are recorded for each node of the tree, but I have a few sites of interest and would like to know how well-supported that particular reconstruction is for that node. For example, if a particular amino acid/codon in the tree is identified as being under selection, but another possible reconstruction that is almost as well supported has a different amino acid/codon at that node, I would like to be able to express that uncertainty in the discussion of the results.

Thank you!

-Jordan

**Comment by spond** [comment]
Dear @jteisher,

If you stay within the SLAC framework, you can perform ancestral state resampling to assess exactly that. For example you can use the command line flag to generate `N` samples from the posterior probability (under the ML model) for the ancestral states across the entire tree to estimate the degree of variability:

```
hyphy slac --alignment tests/hbltests/libv3/data/CD2.nex --samples 1000
```

----

Results using the ML joint reconstruction

### For partition 1 these sites are significant at p <=0.1

|     Codon      |   Partition    |       S        |       N        |       dS       |       dN       |Selection detected?|
|:--------------:|:--------------:|:--------------:|:--------------:|:--------------:|:--------------:|:-----------------:|
|       47       |       1        |     2.500      |     1.500      |     5.330      |     0.595      |  Neg. p = 0.066   |
|       65       |       1        |     2.000      |     0.000      |     3.832      |     0.000      |  Neg. p = 0.030   |
|       78       |       1        |     2.000      |     1.000      |     4.023      |     0.400      |  Neg. p = 0.073   |
|       82       |       1        |     2.000      |     0.000      |     4.488      |     0.000      |  Neg. p = 0.033   |
|       87       |       1        |     3.000      |     0.000      |     5.826      |     0.000      |  Neg. p = 0.009   |
|      110       |       1        |     3.000      |     0.000      |     3.000      |     0.000      |  Neg. p = 0.037   |
|      116       |       1        |     2.000      |     0.000      |     4.008      |     0.000      |  Neg. p = 0.034   |
|      123       |       1        |     2.000      |     0.000      |     3.906      |     0.000      |  Neg. p = 0.035   |
|      130       |       1        |     2.000      |     1.000      |     4.488      |     0.391      |  Neg. p = 0.060   |
|      164       |       1        |     2.000      |     0.000      |     4.691      |     0.000      |  Neg. p = 0.026   |
|      166       |       1        |     4.000      |     0.000      |     4.000      |     0.000      |  Neg. p = 0.012   |

---- 

Results with ancestral uncertainty included; you can see that at some sites (`47, 130`) there was a lot variation based on ancestral state reconstructions, and at some (`166`) there was little. 

|     Codon      |   Partition    |    S [median, IQR]    |    N [median, IQR]    |    dS [median, IQR]    |    dN [median, IQR]    |  p-value [median, IQR]  |
|:--------------:|:--------------:|:---------------------:|:---------------------:|:----------------------:|:----------------------:|:-----------------------:|
|       47       |       1        |   2.50 [1.00-3.50]    |   1.50 [1.50-3.00]    |    5.33 [1.80-7.24]    |    0.60 [0.60-1.27]    |    0.07 [0.02-0.57]     |
|       65       |       1        |   2.00 [2.00-3.00]    |   0.00 [0.00-0.00]    |    3.83 [3.83-5.92]    |    0.00 [0.00-0.00]    |    0.03 [0.00-0.03]     |
|       78       |       1        |   2.00 [2.00-3.00]    |   1.00 [1.00-1.00]    |    4.02 [4.02-6.22]    |    0.40 [0.40-0.40]    |    0.07 [0.01-0.07]     |
|       82       |       1        |   2.00 [2.00-3.00]    |   0.00 [0.00-0.00]    |    4.49 [4.49-6.97]    |    0.00 [0.00-0.00]    |    0.03 [0.01-0.03]     |
|       87       |       1        |   3.00 [3.00-5.00]    |   0.00 [0.00-0.00]    |   5.83 [5.83-10.31]    |    0.00 [0.00-0.00]    |    0.01 [0.00-0.01]     |
|      110       |       1        |   3.00 [3.00-4.00]    |   0.00 [0.00-0.00]    |    3.00 [3.00-4.00]    |    0.00 [0.00-0.00]    |    0.04 [0.01-0.04]     |
|      116       |       1        |   2.00 [2.00-3.00]    |   0.00 [0.00-0.00]    |    4.01 [4.01-6.19]    |    0.00 [0.00-0.00]    |    0.03 [0.01-0.03]     |
|      123       |       1        |   2.00 [2.00-3.00]    |   0.00 [0.00-0.00]    |    3.91 [3.91-6.33]    |    0.00 [0.00-0.00]    |    0.04 [0.01-0.04]     |
|      130       |       1        |   2.00 [2.00-3.00]    |   1.00 [1.00-2.00]    |    4.49 [4.49-6.97]    |    0.39 [0.39-0.78]    |    0.06 [0.01-0.11]     |
|      164       |       1        |   2.00 [2.00-3.00]    |   0.00 [0.00-0.00]    |    4.69 [4.69-6.80]    |    0.00 [0.00-0.00]    |    0.03 [0.00-0.03]     |
|      166       |       1        |   4.00 [4.00-5.00]    |   0.00 [0.00-0.00]    |    4.00 [4.00-5.00]    |    0.00 [0.00-0.00]    |    0.01 [0.00-0.01]     |

Best,
Sergei

**Comment by jteisher** [comment]
Dear @spond, 

Thank you very much for the response, and that approach does indeed solve one of my problems. However, for other reasons, I would still like to be able to look at the actual values for the ML ancestral state reconstructions for each site at each node of the tree (i.e. the support for one amino acid/codon over an alternative reconstruction at a particular site). Is this something that SLAC saves, and if so, is there a way that they can be accessed? Thank you again!

Best,
Jordan

**Comment by spond** [comment]
Dear @jteisher,

SLAC performs a **joint** ancestral state reconstruction, i.e. the assignment of values to all internal nodes at once that maximize the likelihood. You are looking for marginal ancestral state reconstruction, i.e. the one that maximizes the conditional likelihood for a given node (marginalizing over others). You can do it with HyPhy, just not with SLAC.

Best,
Sergei
