### ISSUE TITLE
Issues trying to run GARD

### ISSUE THREAD

**Issue by Frances-Ratcliffe** [veg/hyphy#1129]
Hi, I am having persistent issues trying to run GARD, any help would be greatly appreciated. My data is a clustalW multiple alignment in fasta format, it is DNA nucleotides. I have checked that the sequence translates to protein and is in the correct reading frame. The error I get doesn't give any clues as to how to solve the problem: 
"We're sorry, there was an error processing your job. Please try again, or visit
our GitHub issues and create an issue if the issue persists"
Many thanks,
Frances

**Comment by stevenweaver** [comment]
Dear @Frances-Ratcliffe, 

Thank you for reporting this issue. It appears two of our nodes is having trouble allocating enough memory. We will remove them from the available nodes to submit GARD jobs to.

Best,
Steven

**Comment by stevenweaver** [comment]
Dear @Frances-Ratcliffe, 

A remedy has been put in place, and we will actively monitor to ensure the issue has been resolved in full throughout the day. 

Best,
Steven

**Comment by Frances-Ratcliffe** [comment]
Brilliant, thank you very much. I will try to run it again now and let you know if there are any continuing problems. Is there a maximum number of sequences I can run? I have 230pm fragment and 131 different variants. 
Best,
Frances

**Comment by Frances-Ratcliffe** [comment]
Dear @stevenweaver 
It works when I submit 20 sequences but when I try 50, 100 or my whole data set (131 seqs) I still get the same "_We're sorry, there was an error processing your job. Please try again, or visit
our GitHub issues and create an issue if the issue persists_" error message. 

Is there a limit to the number of sequences that can be submitted or am I missing an option/setting?

Thanks,
Frances

**Comment by stevenweaver** [comment]
Dear @Frances-Ratcliffe, 

The error you are seeing is typically only seen once a dataset has passed validation and has been sent to the cluster for processing. Unfortunately, all GARD jobs, besides one that was rightfully terminated, has completed successfully since I've posted the last comment. Do you have an `id` that is associated with these failing errors? (It is the datamonkey url at the time of failure). 

If so, can you email it to me at sweaver@temple.edu?

Best,
Steven

**Comment by stevenweaver** [comment]
Issue remedied and further correspondence via email. Related to #726 and veg/datamonkey-js#197.
