### ISSUE TITLE
How to perform a batch analysis in Hyphy?

### ISSUE THREAD

**Issue by astridlee** [veg/hyphy#1130]
Hi Dear HyPhy Team,

I’d like to use YangNielsenBranchSite2005.bf testing for positive selection in a large set of genes. When I launched YangNielsenBranchSite2005.bf in the command-line, I got a series of questions that I have to answer in the interactive form, such as choosing the model, tree and foreground branches. Is there any way to perform a batch analysis in a large set of genes?

 Hope to get your reply and guidance as soon as possible. 

Best,
Astrid

**Comment by spond** [comment]
Dear @astridlee,

You can specify arguments on the command line 

```
hyphy batchfile.bf arg1 arg2 arg3 ...
```

We strongly recommend that you do not use YangNielsenBranchSite2005 because 

1. It can have very poor statistical properties due to the restrictive nature of background / foreground models (see our [2011 paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3247808/))

2. It does not allow for site-to-site synonymous rate variation, which could [also be a problem](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3247808/)

If you are interested in specific sites along specific sets of branches, use FEL/MEME on that branch set. If you are just interested in fractions of selected sites and other gene-level features, use BUSTED[S] on the designated set of branches.

Best,
Sergei

**Comment by astridlee** [comment]
Dear Sergei,

I’m glad to hear from you soon. Thank you so much for your kind reply and advice.

YES, now there are several recent studies have call into question any evidence from codon-based models that do not take into account site-to-site synonymous rate variation as you said just now. 

Recently, I have been reading the paper about the BUSTED[S], which is based on BUSTED. But I am still in a stage of understanding this model. Thanks for your recommend and I will try to use it to test for the positive selection in a large set of genes.

Finally,  May I ask for some advices on how to understand a new modified model better? It's still so hard for me to tell if the model I used is really suitable and accurate for my test.  

Best,
Astrid

**Comment by spond** [comment]
Dear @astridlee,

For branch site testing, I would say having inflexible models for background lineages is worse that syn-rate misspecification.

What biological hypotheses are you trying to test?

Best,
Sergei

**Comment by astridlee** [comment]
Dear Sergei,

Thanks for your reply again!

I’d like to test if some certain foreground branches underwent the positive selection, and it’s better to use branch-site model, right? 

Besides, I'd like to consider some special circumstances like multiple hits. But some models can’t hit the spot. So I was confused about how to choose a suitable model to test. 

Best, 
Astrid

**Comment by spond** [comment]
Dear @astridlee,

If all you care about is characterizing branches as selected/non-selected **one at a time**, the most relevant HyPhy method is `aBSREL`. 

If you want to test if selection occurred on **any** from the foreground branches, use `BUSTED[S]`.

I am adding support for Multiple Hits to `aBSREL` in the next release, and there already is support for MH in BUSTED (see https://github.com/veg/hyphy-analyses/tree/master/BUSTED-MH)

Best,
Sergei

**Comment by astridlee** [comment]
Dear Sergei，

Sorry for bothering you again. 

One question occurred to me: I remember that I have seen another model for test multiple hits (Joe’s MNM analysis) before. And I’d like to know that is there any difference between BUSTED[S] and MNM analysis?  

Best, 
Astrid

**Comment by spond** [comment]
Dear @astridlee,

Take a look at the manuscript we have under review. The MH model we have is more general than the MNM analysis (e.g. it allows for 3x hits). For most intents and purposes, the models are very similar. 

http://hyphy.org/resources/fmm.pdf

Best,
Sergei

**Comment by spond** [comment]
Dear @astridlee,

I added support for MH in aBSREL in the 2.5.9 release; use the `--multiple-hits Double` or `--multiple-hits Double+Triple` command line option (see #1119)

Best,
Sergei

**Comment by astridlee** [comment]
Dear Sergei,

Thanks a lot for your update and I'll see to it right away. 

Recenly, I've been understanding BUSTED[S] from the code, but it's still kind a bit hard for me to understand it thoroughly. 

I always think Hyphy is a useful tool to solve the problem of molecular evolution and I am trying to learn HBL language so that I could try to revise some models to meet my own requirements of analysis in the future. 

May I ask for your some suggestions to how to learn the HBL language better? 

Best, 
Astrid
