### ISSUE TITLE
RELAX - error processing job

### ISSUE THREAD

**Issue by egr1g17** [veg/hyphy#1132]
"We're sorry, there was an error processing your job. Please try again, or visit our GitHub issues and create an issue if the issue persists."

Hi,

I'm using the RELAX tool through the Datamonkey website to compare orthologues. I have a multiple sequence alignment directly from MEGA (In .fas format). I can upload it and select the reference and test branches fine but after running the tool for about 15 minutes I get the above error message. 

I'm using Hox gene cDNA sequences. The alignments are good locally in the DNA binding domain (which is well conserved throughout animals) however gloabally the rest of the alignment is poorer with many taxa specific insertions/deletions and much lower sequence similarity. For context the sequences probably divered in the order of 100's of millions of years ago. 

Is the poor global alignment the reason for the processing error? Should RELAX even be used for sequneces that divereged that long ago? Apologies if this is written somewhere and I haven't found the documentation. 

Kind regards,

Ethan

**Comment by spond** [comment]
Dear @egr1g17,

What's the job URL? `We're sorry, there was an error processing your job` describes any error that could be encountered during analysis execution. Let me see what the logs show (but I need the URL).

Best,
Sergei

**Comment by egr1g17** [comment]
Hi Sergi,

https://www.datamonkey.org/relax/5e9c6bb717bf5e2e9ffcce7a

<img width="746" alt="error screenshot" src="https://user-images.githubusercontent.com/63964671/79692005-89df4600-825a-11ea-93c0-ec816e58c9d3.png">

Thanks,
Ethan

**Comment by rfva** [comment]
Dear Sergei,

I have been having the same problems with RELAX (same error message). Could you tell us how could we solve this problem?

Kind regards,

Raul

**Comment by spond** [comment]
Dear @rfva,

Sorry you are having issues. Can you post your job ID to confirm that I am looking at the right job?

Best,
Sergei

**Comment by rfva** [comment]
Dear Sergei,

Thank you very much for your help. 

http://datamonkey.org/relax/5ea1597500ee46232dff1f37
http://datamonkey.org/relax/5ea152b700ee46232dff1dc4
(Those are the links of several attempts)

Looking forward to hear from you soon.

Kind regards,

Raul

**Comment by chrisbalakrishnan** [comment]
Error message for me too. Alignment runs fine in absrel.
job: http://www.datamonkey.org/relax/5ea58c29d10c000700369553
error: 
: LC_ALL: cannot change locale ("en_US.UTF-8")
manpath: can't set the locale; make sure $LC_* and $LANG are correct
/bin/bash: warning: setlocale: LC_ALL: cannot change locale ("en_US.UTF-8")
sh: warning: setlocale: LC_ALL: cannot change locale ("en_US.UTF-8")

Check errors.log for execution error details.
