### ISSUE TITLE
BUSTED - error processing job

### ISSUE THREAD

**Issue by HSecaira** [veg/hyphy#1135]
Hi all, 

I am trying to run a selection analysis using busted, but I keep getting the following error: 
"We're sorry, there was an error processing your job. Please try again, or visit our GitHub issues and create an issue if the issue persists."
 
Ps: My sequences do not contain stop codons.

Thanks

**Comment by stevenweaver** [comment]
Dear @HSecaira, 

There was an unforeseen compatibility issue with Datamonkey and the latest version of HyPhy. We've rolled back to HyPhy 2.5.8 and things should be operational now. We will update Datamonkey for interoperability with 2.5.9 ASAP. 

Best,
Steven

**Comment by HSecaira** [comment]
Thanks much!

Best.
