### ISSUE TITLE
BUSTED - error processing job

### ISSUE THREAD

**Issue by HSecaira** [veg/hyphy#1136]
Hi, 

I keep getting an error processing my job in BUSTED. I reported this error yesterday, and it was fixed. However, it appeared again. 

Thanks for your help.

**Comment by stevenweaver** [comment]
Dear @HSecaira, 

Yes, there were two rapid releases of HyPhy that caused the error to be reintroduced. I've disabled a feature to rapidly deploy patch releases of HyPhy to Datamonkey until the underlying compatibility issues are resolved. 

Best,
Steven

**Comment by kagningemma** [comment]
I keep having an error with BUSTED. 

**Error message:** We're sorry, there was an error processing your job. Please try again, or visit
our GitHub issues and create an issue if the issue persists."

http://datamonkey.org/busted/5f3f4a54503f2f234816652f
