### ISSUE TITLE
MEME - standard error message

### ISSUE THREAD

**Issue by HSecaira** [veg/hyphy#1137]
Hi all, 

I am running an analysis of a gene with 219 bases and 5 sequences on MEME. I keep getting a "Standard Error Message" (see log_gerpf.txt). Can anyone help me with this error?

Thanks. 

Ps: See attached the gene file. 
[gerPF.txt](https://github.com/veg/hyphy/files/4519609/gerPF.txt)
[log_gerpf.txt](https://github.com/veg/hyphy/files/4519610/log_gerpf.txt)

**Comment by spond** [comment]
Dear @HSecaira,

Which version of HyPhy are you using? The issue you report (failing to find initial starting point for "saturated" sites) was fixed a few releases ago. I just tried with 2.5.9 (current release), and obtained the following results.

Best,
Sergei

>code –> Universal
>Loaded a multiple sequence alignment with **5** sequences, **74** codons, and **1** partitions from `/Users/sergei/Downloads/gerPF.txt`

>branches –> All

>Select the p-value threshold to use when testing for selection (permissible range = [0,1], default value = 0.1): 
>pvalue –> 0.1


### Branches to include in the MEME analysis
Selected 7 branches to include in the MEME analysis: `B_smithii1_gerPF, B_thermoamylovorans1_gerPF, Node1, B_coagulans_gerPF, B_freudenreichii1_gerPF, B_lentus1_gerPF, Node5`


### Obtaining branch lengths and nucleotide substitution biases under the nucleotide GTR model

>kill-zero-lengths –> Yes
* Log(L) = -1151.71, AIC-c =  2333.85 (15 estimated parameters)

### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
* Log(L) = -1059.79, AIC-c =  2166.49 (22 estimated parameters)
* non-synonymous/synonymous rate ratio for *test* =   0.0312

### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
* Log(L) = -1049.00
* non-synonymous/synonymous rate ratio for *test* =   0.0152

### For partition 1 these sites are significant at p <=0.1

|   Codon    | Partition  |   alpha    |   beta+    |     p+     |    LRT     |Episodic selection detected?| # branches |
|:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|:--------------------------:|:----------:|
|     7      |     1      |    0.000   |    2.286   |    0.148   |    4.675   |      Yes, p =  0.0446      |     1      |
|     51     |     1      |    0.000   |    6.180   |    0.304   |    3.600   |      Yes, p =  0.0779      |     0      |

### ** Found _2_ sites under episodic diversifying positive selection at p <= 0.1**

**Comment by HSecaira** [comment]
Dear @spond,

I am using the online server (http://datamonkey.org/meme). 

Best.

**Comment by spond** [comment]
Dear @HSecaira,

Hmm, let's see if this issue goes away with the next software update. It typically occurs when some of the sequences are divergent.

Best,
Sergei

**Comment by HSecaira** [comment]
Dear @spond, 

thanks for your help. I will use the local version of Hyphy.

Best.
