### ISSUE TITLE
Cannot run any SLAC analysis

### ISSUE THREAD

**Issue by tfconnell** [veg/hyphy#1139]
Hi, I keep getting this error when I try to run the program.

We're sorry, there was an error processing your job. Please try again, or visit
our GitHub issues
and create an issue if the issue persists.
Standard Error Message
-bash: warning: setlocale: LC_ALL: cannot change locale ("en_US.UTF-8")
manpath: can't set the locale; make sure $LC_* and $LANG are correct
/bin/bash: warning: setlocale: LC_ALL: cannot change locale ("en_US.UTF-8")

Check errors.log for execution error details.

**Comment by stevenweaver** [comment]
Dear @tfconnell, 

We have an issue where HyPhy >2.5.8 is not compatible with Datamonkey. We've pinned Datamonkey to HyPhy 2.5.8 until the issue is resolved. 

SLAC should be operational again.

Best,
Steven

**Comment by Alshu007** [comment]
Dear Stevenweaver,

As indicated by @tfconnell , datamonkey server is not running when using tools such as SLAC or FEL. could please let me know if the issue is already resolved in order to make sure that it is not a problem from my side.

Thanks.

**Comment by stevenweaver** [comment]
Dear @Alshu007, 

An unrelated issue that caused our cluster to stop accepting jobs on 2020-04-25 at approximately 3:15am EDT has been resolved. Operations should be normal now.

Best,
Steven
