### ISSUE TITLE
Method to remove redundant paralog genes in the gene selection analysis 

### ISSUE THREAD

**Issue by hongzhonglu** [veg/hyphy#1141]
Dear Sergei @spond,
I have a question about how to handle the paralog gene analysis.
In the previous issues, it said that the paralog gene does not affect aBSREL analysis. Is that still right now?
As in lot's reported evolution analysis, only single copy genes were analysed. I am wondering are there good tools to remove redundant paralog genes before the normal analysis?

Looking forward to your comment. Thanks very much!

Best,
Hongzhong

**Comment by spond** [comment]
Dear @hongzhonglu,

Datamonkey will do it for you automatically. 

Best,
Sergei

**Comment by hongzhonglu** [comment]
Dear Sergei @spond,
Great thanks for your help. Can it be used in batch mode, like processing over 1000 ortholog groups in batch?

Best,
Hongzhong

**Comment by spond** [comment]
Dear @hongzhonglu,

No, you can't do that in batch using Datamonkey. Removing duplicate sequences in batch can be done using HyPhy or Python (https://biopython.org/wiki/Sequence_Cleaner)

Best,
Sergei

**Comment by hongzhonglu** [comment]
Thanks a lot!


Best,
Hongzhong

**Comment by spond** [comment]
Dear @hongzhonglu,

Also see  https://github.com/veg/hyphy-analyses/tree/master/remove-duplicates

Best,
Sergei

**Comment by hongzhonglu** [comment]
Dear Sergei @spond,
Great thanks for your help! What is the principle to remove the duplicates here?

Best regards,
Hongzhong

**Comment by spond** [comment]
Dear @hongzhonglu,

Not sure I understand your question. If there are N > 1 identical sequences, only 1 of them will be retained (it is chosen effectively at random).

Best,
Sergei

**Comment by hongzhonglu** [comment]
Dear Sergei @spond,
Thanks for your help. I can take an example here, for one ortholog group, it could have multiple sequences from on species, that is:
species A, seq1;
species A, seq2;
speciesA, seq3;
speciesB, seq4;
speciesC, seq5;

Here, seq1, seq2 and seq3 are not identical , but belong to the paralog genes. Does your recommended method could choose one from seq1, seq2 and seq3?

Best regards,
Hongzhong

**Comment by spond** [comment]
Dear @hongzhonglu,

I think we are talking about different problems (outgroup selection vs collapsing identical sequences). 

Outgroup and paralog vs ortholog selection should be done **prior** to running analyses in HyPhy. Conceptually, there's nothing preventing you from performing analyses where there are multiple paralogs per species.

Best,
Sergei

**Comment by hongzhonglu** [comment]
Dear Sergei @spond,
Great thanks for your comment. Now it is more clear to me.

Best regards,
Hongzhong
