### ISSUE TITLE
Problem downloading CSV file from web interface

### ISSUE THREAD

**Issue by jamanumass** [veg/hyphy#1148]
Hello,
I have been unable to download the CSV from datamonkey results pages (was working a couple days ago). I have confirmed this to be true across multiple runs, tools, browsers, and others have confirmed from different machines. Maybe a bug in the web interface?
Here's an example results page:  
http://datamonkey.org/fubar/5eab63aa2ba956274a3779ca
Any help is appreciated, 
Thanks!
-J

**Comment by stevenweaver** [comment]
Dear @jamanumass, 

Yes, I've confirmed the issue. We will fix asap and will notify here when deployed.

Best,
Steven

**Comment by jamanumass** [comment]
Great! Thanks for such quick attention :) The web server is much appreciated.
-J
