### ISSUE TITLE
[minor] File organization regarding File Hierarchy Standar (FHS)

### ISSUE THREAD

**Issue by bioinfornatics** [veg/hyphy#1149]
Dear,

Thanks for your tools. Moreover the build system and installation follow almost all rules from [FHS](https://refspecs.linuxfoundation.org/FHS_2.3/fhs-2.3.html#THEUSRHIERARCHY) at **Chapter 4. The /usr Hierarchy**.
Which do not happen often in our field :-)

I have a little request to be fully compliant with FHS. Currently installation mechanism put
these directories: `data`,  `GeneticCodes` , `SubstitutionClasses`,  `SubstitutionModels`, `TemplateBatchFiles` into `<prefix>/ lib/hyphy/`

But these directories should be put into `<prefix>/ share/hyphy/`

Thanks for your works

Have a nice day

**Comment by spond** [comment]
Dear @bioinfornatics,

Thanks for the suggestion; we will adjust the default library path in our next release. 

Best,
Sergei

@stevenweaver : should be a simple matter of adjusting `_HYPHY_LIBDIRECTORY_` in the `CMakeLists` file

**Comment by spond** [comment]
Dear @bioinfornatics,

I made the fix in the current `develop` branch; once it's tested and released, library files will go into `share`. Should be version `2.5.14`.

Best,
Sergei

**Comment by bioinfornatics** [comment]
Thanks @spond 
Have a nice day
