### ISSUE TITLE
Visualize MEME output from DataMonkey

### ISSUE THREAD

**Issue by MickAmest** [veg/hyphy#1151]
Hello!
I'm running MEME on a set of gene sequences. Although I'm able to visualize the output on the DataMonkey website, I'm wondering if there is a way to do the same using the output file, which seems to be a .json file. Is  there a software that can read this file? Can I visualize this output on some program? Is it possible to visualize the tree and the branches in which a site was under positive selection using this json file? Or is this only possible using the DataMonkey website?

Regards!!

**Comment by spond** [comment]
Dear @MickAmest,

You can read JSON with pretty much anything (Python, R, etc) and extract what you need. Documentation (a bit of of date, but close enough) on what is in the JSON file is in http://www.hyphy.org/resources/json-fields.pdf

Here's an example of visualization entirely in JavaScript: https://observablehq.com/@spond/plotting-meme-ebf-on-branches-at-individual-sites

You can also extract pieces from `JSON` using tools like `jq` to text (e.g. if you want to pull out a tree string or something like that).

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @MickAmest, 

Additionally, the same view as the datamonkey site can be found at http://vision.hyphy.org/, where you can select to load your JSON result. 

Best,
Steven

**Comment by MickAmest** [comment]
Thank you very much to both of you!! Those option work fine for me!!
Regards!!
