### ISSUE TITLE
compartmentalization detection and permutation

### ISSUE THREAD

**Issue by Xiaojun928** [veg/hyphy#1152]
Dear All,

I've just installed the Hyphy using conda and I am trying to do compartmentalization analysis using tree-based method (Slatkin-Maddison test).  It provided me with the number of groups after I input the tree filename.
like this
>How many branch classes are there (permissible range = [2,214], default value = 2, integer): groups: 2
I have four groups, is there a way to change the group number?

Another thing is the permutation. If I follow the instruction of hyphy, that is, using two groups, then I got a json file, and the hyphy was done. This file provides two p-values:

 "p-value":{
   "panmictic":0.000999000999000999,
   "structured":0.000999000999000999
  },

but I did not find results like #314 mentioned
> Prob{as many or fewer migration events by chance} = 0"

May I know how to perform the significant test?  I attached the input and the JSON file. 
I appreciate so much that you can reply.
[genome_tree.txt](https://github.com/veg/hyphy/files/4613029/genome_tree.txt)
[output.txt](https://github.com/veg/hyphy/files/4613031/output.txt)

**Comment by Xiaojun928** [comment]
I found how to perform multiple compartmentalization and permutations. Thanks.
>hyphy sm --help 
is very helpful.  
The permutation results can be found in the terminal output.

When I look at the terminal output, two p-values were found, may I know which one is 
> Prob{as many or fewer migration events by chance} ?

**Comment by spond** [comment]
Dear @Xiaojun928,

The current version of the SM test implements the standard test (full panmixia), and a structured test (https://github.com/veg/hyphy-analyses/tree/master/SlatkinMaddison), which is less sensitive to small clade effects in larger samples. We developed the structured version specifically for compartmentalization testing in HIV datasets, but it should be more broadly applicable (see https://www.ncbi.nlm.nih.gov/pubmed/32269129).

The **standard** p-value is found in the paragraph ```the standard (full panmixia) p-value for compartmentalization test was ``` or in the JSON as `['p-value']['panmictic']`

Best,
Sergei

**Comment by Xiaojun928** [comment]
Dear Sergei,

Many thanks for your reply!

Best,
Xiaojun

**Comment by Xiaojun928** [comment]
Hi Sergei,

For my dataset1, the standard SM test shows p-value<0.000, whereas the structured SM test shows p-value<0.084. 
For dataset2, standard p-value< 0.001 and the structured p-value<0.208

I found that you defined this as equilibrated or minor-compartmentalization [here](https://www.ncbi.nlm.nih.gov/pubmed/32269129). But I am not sure how to distinguish between them.
May I know how to determine the degree of compartmentalization in my cases?
Thanks a lot!

best regards,
Xiaojun
