### ISSUE TITLE
result interpretation of MEME

### ISSUE THREAD

**Issue by datou99** [veg/hyphy#1154]
Hi,

I want to detecte sites those under selection on any branch of my 7-species tree. 
I used MEME model with the command line "hyphy meme --alignment input.phy --tree input.tree" .

The standard output showed that "Found _2_ sites under episodic diversifying positive selection at p <= 0.1**", one is condon 735 and the other is condon 996.  Both sites had the "# branches" as 1. 
But in the json file, two branches have the EBF value larger than 1 at condon 735, that are 119 and 66  respectively. thus I am wondering how can I konw which branch was the one indicated in the standard output. 

and I also found that for a particular site, the EBF value was different when the paramter "--branches" changes. That means,  when I using default setting "--branches = All" , for the same branch, EBF value for one site is different from that when I using "--branches=test" . "{test}" was add on the input.tree after the branch tested. So is that normal? and result of "--branches=test" is not an subset of result of "--branches=All" ?

Best,
Fang

**Comment by spond** [comment]
Dear @datou99.

1. The branch count includes branches with `EBF >= 100`.
2. When you change the set of the branches that are being tested, the model you are fitting to the data changes as well, which means that EBF of individual branches can change. If you see **dramatic** changes, there may be statistical anomalies, especially for smaller dataset/test sets. Can you provide a more detailed example?

Best,
Sergei

**Comment by datou99** [comment]
Thanks for that Sergei!

1. Do you mean that if the table in standard output told us "# branches" for one codon is x, then sites on branches with the top x EBF values should be under selection?

2. In the flowing example, EBF value for branch HAM and LOP is both 1 when only test these two branches.  When test all braches, EBF for HAM is 119 and for LOP is 66. While I have no ideal if this is a dramatic change. 

input.fasta and input.tree were placed on:
[https://drive.google.com/open?id=1Rd5KVF0TZzNmft5fiWnWxT14aT6BsH4u](url)

Best,
Fang

**Comment by spond** [comment]
Dear @datou99,

1. EBF for MEME is **exploratory**; you should **not** interpret the report that _branch X has EBF > 100 for site Y_ as `branch X at site Y is selected`. A significant p-value for MEME implies that there is evidence of episodic selection at a given site, and EBF is a way to suggest where in the tree these may occur, but in our MEME paper we show that the statistical accuracy to identify specific branches at specific sites is not great on simulated data.

2. I presume you are talking about site **735**? The reason for this behavior, is that when you focus on the two branches, MEME estimates that 100% of distributional weight is allocated to dN/dS  > 1, so EBF is essentially infinite or undefined (no prior weight on dN/dS < 1). The model don't disagree, however, that there is selection at that site.

Best,
Sergei

**Comment by datou99** [comment]
Thanks Sergei !

I understand now. 
So how should I know which branches at that site have undergone selection if we cannot infer that directly from EBF?

**Comment by spond** [comment]
Dear @datou99,

You simply have no power to detect the effect of selection on a single branch at a simple site (that's like using a sample size of 1). You can run `aBSREL` to identify branches subject to episodic selection, but you'll lose site-level resolution. See the discussion in our MEME paper (https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1002764) 

> The ability of MEME, or similar substitution model-based methods, to accurately infer the identity of individual branches subject to diversifying selection at a given site seems unavoidably limited. Most of the information that such inference might be based on is limited to character substitutions along a single branch at a single site, i.e. one realization of the Markov substitution process. Selection along terminal branches in the context of negatively selected background can be detected more reliably than selection along interior branches among neutrally evolving background lineages. However, we caution that despite obvious interest in identifying specific branch-site combinations subject to diversifying selection, such inference is based on very limited data (the evolution of one codon along one branch), and cannot be recommended for purposes other than data exploration and result visualization. This observation could be codified as the “selection inference uncertainty principle” – one cannot simultaneously infer both the site and the branch subject to diversifying selection. In this manuscript, we describe how to infer the location of sites, pooling information over branches; previously we have outlined a complementary approach to find selected branches by pooling information over sites.

Best,
Sergei

**Comment by datou99** [comment]
Thanks Sergei and I get that now !

While I am still wondering, if we can fist running MEME model to find sites under selection and then running aBSREL to find which branches on those sites were under seletion. Because when we do this kind of selection analysis, we really want to know which branches have undergone selection on particular sites for a gene.

Thanks again for your patience and detailed answers.

Best,
Fang

**Comment by spond** [comment]
Dear @datou99,

Unless you have other information, you can't know for sure (based on **sequence variation alone**) that branch X at site Y experienced selection. You can use MEME EBF to **generate hypotheses** or **annotate branches**, but that's it. No other method that I know of can give you that information. 

Best,
Sergei
