### ISSUE TITLE
Contrast-FEL error

### ISSUE THREAD

**Issue by Enrique-SC** [veg/hyphy#1155]
Dear HyPhy Team,

I'm trying to use your new method Constrast-FEL in Datamonkey, but I get the next error message:

"-bash: warning: setlocale: LC_ALL: cannot change locale ("en_US.UTF-8")
manpath: can't set the locale; make sure $LC_* and $LANG are correct
/bin/bash: warning: setlocale: LC_ALL: cannot change locale ("en_US.UTF-8")
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15"

I create two sets of branches in "Tag", select the corresponding branches and this comes after saving them. Maybe I'm doing something wrong.

Also, what does the "Foreground" Tag means?

Thanks for your help,

Enrique

**Comment by spond** [comment]
Dear @Enrique-SC,

Thanks for reporting this; we will check into it. Can you include the URL where the failed job is?

Best,
Sergei

**Comment by Enrique-SC** [comment]
Dear @spond,

This is the URL link:
https://www.datamonkey.org/contrast_fel/5ec3e5ce299cb9159cf28422

Regards, 

Enrique

**Comment by spond** [comment]
Dear @Enrique-SC,

We'll look into this issue, thanks!

Best,
Sergei

**Comment by jzehr** [comment]
Dear @Enrique-SC,

Can you send along your data, and the settings on the command you were using? That way we can try to re-create the problem on our end. 

Best,
Jordan

**Comment by Enrique-SC** [comment]
Dear @jzehr, 

Apologies for the late reply. I just tried again and it worked perfectly. It seems that the bug has been fixed.
Thank you very much! Exited to use this method! 

Best, 
Enrique
