### ISSUE TITLE
Retrieving site under selective pressure on MIME

### ISSUE THREAD

**Issue by emiliomastriani** [veg/hyphy#1157]
Hi guys, I am new using MEME and I have some troubles to understand the results. For example, I obtained the site 9628 results under selection. Now I wish to "see" who this site is .... Is it enough to get the nucleotide at position 9628 into my MSA? For further analysis on this site, should I consider only that nucleotide (9628) or the codon starting at this position? Furthermore, the mentioned site looks to be under selective pressure both into other datasets with different geo-localization: should I repeat the analysis using a different method (SLAC) to confirm that the results is significant?
![Screen Shot 2020-05-20 at 5 03 39 PM](https://user-images.githubusercontent.com/65239532/82649977-9802f680-9c4c-11ea-8a85-1346e91b4140.png)

Thank you very much

**Comment by aglucaci** [comment]
Dear @emiliomastriani 

1. The MEME analysis will be operating on sequences within codon "windows". So Site 9628 would correspond to a triplet of nucleotides in the original sequence.

2. SLAC may provide additional meaningful or interpretable results however to give you a more holistic answer could you clarify what research question you are interested in?

Best,
Alexander

**Comment by spond** [comment]
Dear @emiliomastriani,

To add to what @aglucaci

* The numbers you see are already in terms of codons (e.g. 9628 is **codon** 9628, not **nucleotide** 9628) 

* You don't need to "confirm" one analysis with another. SLAC, for example, is **less** sensitive than MEME, and may miss episodic selection. 

* In MEME, you could use the tree widget to explore which branches in the tree provide support for the selection signal, using the EBF value (EBF = empirical Bayes factor) [see image below]

<img width="591" alt="Screen Shot 2020-05-22 at 4 16 02 PM" src="https://user-images.githubusercontent.com/1018513/82706473-a995cf80-9c47-11ea-8663-cf9e0f58794a.png">

* You can run SLAC on the same dataset, and then use the widget at the bottom to map substitutions to the tree 

<img width="813" alt="Screen Shot 2020-05-22 at 4 22 48 PM" src="https://user-images.githubusercontent.com/1018513/82706765-8586be00-9c48-11ea-9533-e8231654ee9a.png">


Best,
Sergei

**Comment by emiliomastriani** [comment]
Thank you guys very much for your support. To add some details to the research I am conducting: after the preliminary rearrangement test with GARR, I used MEME to verify the different dn/ds between datasets of SARS-COV2 from different countries. And I see that the number of sites under selective pressure is different (as expected), but interestingly the mentioned site is shared from all the countries as "under selection". Since, I wish :

- be sure that it's not a false results (from here the question whether use or not another model)

- understand "who" is this codon to understand "why" we observed this phenomena

Of course, any hits will be very welcome!

PS.: Can someone suggest me a good forum specialized on viral bioinformatics?

Thank you very much

**Comment by aglucaci** [comment]
Dear @emiliomastriani

1. You don't need to "confirm" results by running SLAC.

2. However, the SLAC Phylogenetic Alignment visualization may be useful for you to "see" the interesting codons.

3. Virological.org is a good resource.

Best,
Alexander

P.S. You may be interesting in running our Contrast-FEL method. It will allow you to partition branches by country of origin and see if selection on sites is different between these groups.
