### ISSUE TITLE
Issue running GARD

### ISSUE THREAD

**Issue by rfleischer93** [veg/hyphy#1158]
Hi, 
I am new using GARD and have some trouble. When I try to run GARD on Datamonkey with my fasta-file the job is aborted but I can't figure out why..log file attached. I am sure there are no stop codons or shorter sequences in the file and it ran fine with SLAC, FEL and FUBAR. 
Thanks for your help!
[log.txt](https://github.com/veg/hyphy/files/4676562/log.txt)

**Comment by stephenshank** [comment]
Dear @rfleischer93,

Would you be willing to post the associated job URL (something like http://datamonkey.org/gard/5ec4720a45a540731ae46b05, but with the ID for your specific job), so that I can investigate how things look on Datamonkey's side?

Best,
Stephen

**Comment by rfleischer93** [comment]
Dear Stephen, sure here's the URL:

http://datamonkey.org/gard/5b9a4a2da913185b60116395

Best,
Ramona

**Comment by stephenshank** [comment]
Dear @rfleischer93,

Just wanted to give you an update. I'm rerunning your job here:
http://datamonkey.org/gard/5ecd936981949e0be7d949d6

and will keep an eye on it over the next few days. My suspicion is that it may be timing out. We allocate 24 processors for GARD jobs for a period of 3 days. Your job is on the large side (323 sequences, 4260 sites, 2267 of which are variable) of runs that have successfully completed... see the GARD section of our [usage statistics](http://datamonkey.org/stats) page. Only 6 other jobs with more sequences and sites than this have ever ran to completion.

I'll follow up later in the week after seeing the results of this run and some internal discussion.

Best,
Stephen

**Comment by spond** [comment]
Dear @rfleischer93,

@stephenshank is correct (this is a large dataset). Moreover, GARD is not going to perform well for large data sets, for 323 sequences you have ~650 branch parameters per partition, so now you are talking about ~1-2 sites per parameter. 

I would suggest trimming **sequences** from your dataset, by replacing similar sequences (clades) with one. For 4260 sites, you should aim to have no more than 30-40 sequences.

Best,
Sergei

**Comment by rfleischer93** [comment]
Thanks @stephenshank and also @spond for your suggestion to reduce the number of sequences when running GARD!

Best,
Ramona
