### ISSUE TITLE
RELAX(omega values)

### ISSUE THREAD

**Issue by kavithamallayaa** [veg/hyphy#1159]
Hi Hyphy team,

I have done some relax analysis[alternative and null] and obtained evidence of relaxation. The omega values of test were more closer to one than the reference values. This shows relaxation.

I am interested in purifying selection also. As the omega1 and omega2 values of the test are still less than 1, I think purifying selection is still efficient but reduced compared to reference.
Can I cite this as evidence for purifying selection on the test branches? 

regards
Kavitha

**Comment by spond** [comment]
Dear @kavithamallayaa,

In order to find statistical evidence of purifying selection, you need to run a test that will compare &omega; to 1. Finding a point estimate less than one is suggestive but not sufficient. HyPhy doesn't include a whole lot of tests for this (mostly because the vast genes will be under some degree of purifying selection), but you could try https://github.com/veg/hyphy-analyses/tree/master/BUSTED-conservation which will also allow you to select a subset of branches for testing.

Best,
Sergei

**Comment by kavithamallayaa** [comment]
Dear Sergei,

My argument : relaxation( evident from Hyphy:RELAX) is a relative value and
it is a decrease in selection intensity of the test compared to reference.
It is not necessary for genes under relaxation to lose function as
selection can still be efficient on test branches. Like for instance
endosymbiont genes, the genes show relaxation compared free living
relatives but yet tend to retained for a longer period of time.

I am not trying to show purifying selection, but want to insist that
selection can still be acting during relaxation based on the data we are
given and its biological background.

regards
Kavitha.

**Comment by spond** [comment]
Dear @kavithamallayaa,

I think your interpretation is perfectly fine. You don't need to formally test for &omega; ≠ 1 to make this statement, but you could if you wanted to make it stronger: i.e. despite relaxed selection, there is still statistically significant result on the `test` clade. 

Best,
Sergei

**Comment by kavithamallayaa** [comment]
Dear Sergei,

I will try BUSTED-conversation.

I have been working with Hyphy for the past one year and had reported few
issues in the past. Amazingly, for each issue I have got instant sincere
responses.

Thank you for the support and time.

Kavitha

**Comment by spond** [comment]
Dear @kavithamallayaa,

Users like you help us develop a better product! Keep the issues coming:)

Best,
Sergei

**Comment by kavithamallayaa** [comment]
Dear Sergei,

I have already done the BUSTEC conservative analysis.
As we discussed I can find that unconstrained model has lower AIC. I hope
that provides evidence for purifying selection and we interpret despite
relaxation there is evidence for purifying selection.

I have attached my files for both RELAX and BUSTEC for your reference.

I would also like to ask, in the RELAX output(in my attached file) if p
value is zero, then is it <0.00001.

regards
Kavitha

**Comment by spond** [comment]
Dear @kavithamallayaa,

1. GitHub strips e-mail attachments, so I can't see them. 
2. Sounds like you do have evidence of purifying selection in addition to relaxation
3. I suggest that you report very low p-values p < 0.001 -- the actual precision is meaningless after some point (eg JAMA and other journals actually have p-values reporting requirements that require this). The full precision p-value can be found in the JSON output, but if you see zero reported to the console, then `p<1e-4`

Best,
Sergei

**Comment by kavithamallayaa** [comment]
Dear Sergei,

In the BUSTEC output, there is rate distribution for site-to-site
"synonymous" variation under constrained and unconstrained model.
what does that signify?  Does that provide information about the test
branches.

Thank you
Kavitha

**Comment by spond** [comment]
Dear @kavithamallayaa,

This is the distribution of synonymous substitution rates among sites (https://academic.oup.com/mbe/advance-article/doi/10.1093/molbev/msaa037/5739973). It does not provide information about selection on test branches directly, but it does influence &omega; estimates.

Best,
Sergei

**Comment by kavithamallayaa** [comment]
Dear Sergei,

I will read through that paper.
Thank you once again for the time and support.
Kavitha

**Comment by kavithamallayaa** [comment]
Dear Sergei,

I need some clarification on BUSTEC:

1. Does the AIC scores for unconstrained and constrained is for fitting
these models on test branches only.

2. Unconstrained omega values for background branches is given in screen
output , but json files includes background branches omega values for both
unconstrained and constrained model. BUSTED output has no background omega
values, so I am confused in understanding the output, as I used BUSTED to
follow BUSTEC.

3.Site-to-site synonymous rate variation: Is the Rate provided based on
test branches only or for all branches.

with regards
Kavitha

**Comment by srwis** [comment]
Hi Kavitha,

1) The AICc scores for each model apply to the test branches, correct.

2)Can you post the results files here? Did you pick the same background branches for BUSTED as well as BUSTEC? BUSTED will only fit the constrained model if it finds evidence of positive selection using the unconstrained model first (omega_3 > 1) see issue #424 about this as well. 

3)SRV is a site-level parameter meaning it does not vary from branch to branch currently. 

Best,
Sadie
