### ISSUE TITLE
GARD Error: Invalid matrix index

### ISSUE THREAD

**Issue by szimmerman92** [veg/hyphy#1160]
HI,

When I run GARD on the command line I am getting an error

> Invalid matrix index [-1][0] in an 13 by 1 matrix.

However, when I use the same alignment file, but on the datamonkey website, it runs to completion. The link to the datamonkey job is [here](http://www.datamonkey.org/gard/5ecf1c51d49cd511eec77498).

The line of code I am running on the command line is 

`hyphy gard --alignment 19340281_filtered.protein.fasta_filtered.fasta --type Codon`

I have also attached the multiple sequence alignment file below, (I changed the suffix from fasta to txt so it would attach). Also attached are the error and message files that hyphy outputs.

Thank you very much.

Best,
Sam

[19340281_filtered.protein.fasta_filtered.txt](https://github.com/veg/hyphy/files/4692828/19340281_filtered.protein.fasta_filtered.txt)

[errors.log](https://github.com/veg/hyphy/files/4692832/errors.log)

[messages.log](https://github.com/veg/hyphy/files/4692834/messages.log)

**Comment by spond** [comment]
Dear @szimmerman92,

Which version of HyPhy are you using (can you also provide the `stdout` of your run, not just the log files)? 

I ran 

```
hyphy gard --alignment 19340281_filtered.protein.fasta_filtered.txt --type codon 
```

using the current `develop` branch code (the latest release should do fine as well), without issues. 

```
Analysis Description
--------------------
GARD : Genetic Algorithms for Recombination Detection. Implements a
heuristic approach to screening alignments of sequences for
recombination, by using the CHC genetic algorithm to search for
phylogenetic incongruence among different partitions of the data. The
number of partitions is determined using a step-up procedure, while the
placement of breakpoints is searched for with the GA. The best fitting
model (based on c-AIC) is returned; and additional post-hoc tests run to
distinguish topological incongruence from rate-variation. v0.2 adds and
spooling results to JSON after each breakpoint search conclusion

- __Requirements__: A sequence alignment.

- __Citation__: **Automated Phylogenetic Detection of Recombination Using a Genetic
Algorithm**, _Mol Biol Evol 23(10), 1891–1901

- __Written by__: Sergei L Kosakovsky Pond

- __Contact Information__: spond@temple.edu

- __Analysis Version__: 0.2

type: codon
code: Universal
rv: None
>Loaded a codon multiple sequence alignment with **4** sequences, **199** sites (13 of which are variable) from `/Users/sergei/Downloads/19340281_filtered.protein.fasta_filtered.txt`
>Minimum size of a partition is set to be 5 sites


### Fitting the baseline (single-partition; no breakpoints) model
* Log(L) =  -886.55, AIC-c =  1817.82 (20 estimated parameters)

### Performing an exhaustive single breakpoint analysis
Done with single breakpoint analysis.
   Best sinlge break point location: 140
   c-AIC  = 1812.809183676026

### Performing multi breakpoint analysis using a genetic algorithm
Done with 2 breakpoint analysis.
    Best break point locations: 125, 140
    c-AIC = 1794.982959464081
Done with 3 breakpoint analysis.
    Best break point locations: 35, 125, 140
    c-AIC = 1805.509248241499
```

Best,
Sergei

**Comment by szimmerman92** [comment]
Hi Sergei,

Thank you so much for the advice. I was running an old version of hyphy 2.5.1 I think. Now that I upgraded to 2.5.14 it works perfectly. You can also find the log fie attached below. 

One more question, sorry. I noticed even though hyphy may find evidence of recombination, the difference in AIC between models may be very small. Is there a recommended change in AIC threshold, over which, you would consider there to be a high probability of recombination? In the datamonkey website, they mention an evidence ratio of 100 or greater, but I don't see that measurement in the website or JSON output.

Thanks again!

Best,
Sam 

[hyphy_gard_19340281_stdout.txt](https://github.com/veg/hyphy/files/4713309/hyphy_gard_19340281_stdout.txt)

**Comment by spond** [comment]
Dear Sam,

It's up to you really. Evidence ratio of `100` maps to a &Delta;c-AIC of about `10.5`. 

Best,
Sergei
