### ISSUE TITLE
RELAX: inconsistent results

### ISSUE THREAD

**Issue by crs344** [veg/hyphy#1161]
Hi,
(Archive.zip is 4 Relax json outputs-these tests were run on identical alignments/trees, but 2 different test/reference branches: Apocynaceae_dhshss_relax.json + Apocynaceae_dhshss_relax2.json, and Apocynaceae_dhshss_relax_itov.json + Apocynaceae_dhshss_relax_itov2.json)

We have been using RELAX to test hypotheses on signatures of relaxed selection in a 275 sequence/~1000 bp dataset made up of 2 paralogs. There are a few test branches in one paralog hypothesized to be under relaxed purifying selection or intensification of selection, which we are comparing to a few surrounding branches that are not hypothesized to undergo the same selection changes. In running RELAX multiple times using the same or very similar alignments and trees, we noticed that the general descriptive model was assigning often very different, and uncorrelated, k-values to the same sequences (for example: k and k2 columns, attached spreadsheet).

In addition, for one set of replicate tests run (Apocynaceae_dhshss_relax_itov and itov2), the respective k-values are correlated, but the result of the test is not the same.

1. Test for selection relaxation (K = 0.86) was significant (p = 0.000, LR = 17.94).
2. Test for selection relaxation (K = 0.88) was not significant (p = 0.257, LR = 1.28).

Is there an issue with the dataset or with the chosen test/reference branches that is producing these inconsistent results?

Thank you

[Apocynaceae_dhshss_kvalues.xlsx](https://github.com/veg/hyphy/files/4711672/Apocynaceae_dhshss_kvalues.xlsx)
[Archive.zip](https://github.com/veg/hyphy/files/4711640/Archive.zip)

**Comment by spond** [comment]
Dear @crs344,

Before I look into this, can you confirm which version of HyPhy and RELAX generated the results?
In some situations, RELAX can suffer from convergence issues, but I've been adding safeguards against those in subsequent versions.

Best,
Sergei

**Comment by crs344** [comment]
Hi Sergei,

Thank you for responding so quickly. The log file says that it is RELAX v3.1, if that makes sense. I know that Hyphy was installed on our server in July 2019 so my guess would be version 2.5.0

Best,

Chelsea

**Comment by spond** [comment]
Dear @crs344,

Reposting PS, since edits to messages do not trigger e-mails...

1.  I also need the alignments and partitioned trees in order to replicate the analysis and see what is going on.

2. I see you are running version 3.1 of the analysis (which is recent). I also see that your Test and Reference sets of branches are small (4 and 2) and short (~0.01 subs/site). Unfortunately this is exactly the type of setting that convergence issues may arise. I would suggest you run the minimal set of models and reduce the the number of rate classes to 2
```
hyphy relax --rates 2 --models Minimal --alignment file.fas
```

Best,
Sergei

**Comment by crs344** [comment]
Hi Sergei,

Attached are the alignment, and the labelled trees used for RELAX runs.

Thank you for the advice, I will run these data using the minimal set of models and 2 rate classes.

Best, Chelsea
[Archive 2.zip](https://github.com/veg/hyphy/files/4717286/Archive.2.zip)

**Comment by crs344** [comment]
Hi Sergei,

With the minimal set of models and 2 rate classes, I am still getting messages about convergence issues (attached). Does this mean it is an unfixable problem, at least with our current set of test and reference branches?
[hyphy_relax_desc_staging.sh.o536914.zip](https://github.com/veg/hyphy/files/4879316/hyphy_relax_desc_staging.sh.o536914.zip)

One more question: I mentioned in the first post that k values for branches were uncorrelated between replicate tests-is this also due to convergence issues?

Best,

Chelsea

**Comment by spond** [comment]
Dear @crs344,

In this specific example it seems like there is fairly good consistency between different starting points and no evidence of relaxation/intensification, so the results are most likely OK. If you had big changes in **K** estimates of **logL** values, I'd be concerned.

As far as **k** goes, in your example one of the dN/dS rates in the general exploratory models was exactly 0. This creates an identifiability problem for **k**

Best,
Sergei
