### ISSUE TITLE
Every k value is 1

### ISSUE THREAD

**Issue by juliayork** [veg/hyphy#1162]
Hello, I've been running RELAX on my university's cluster and for a while things seemed like they were functioning okay, but now every single time I run RELAX, on many different data sets, the k value is exactly 1 even if sometimes the p-value is significant and the LRT is sometimes very high. 

Is there some sort of cache I need to clear? Or should I reinstall HyPhy? 

I'm working on running some of the tests again using datamonkey, but this is not ideal for me because 1) I'd like to use my own tree but the datamonkey server can't read my files with the trees at the bottom, even though these are read by HyPhy via command line, and 2) even if I use the tree generated by datamonkey, I find it difficult to select the branches I want because I can't expand the tree horizontally (like is possible on phylotree)

Please let me know if you want some of my data files or other information. Thanks!

**Comment by aglucaci** [comment]
Dear @juliayork,

Can you please provide a sample set of inputs (including the alignments, trees, command line arguments) for me to debug/replicate this issue?

Also, which version of HyPhy are you running?

Best,
Alexander

**Comment by juliayork** [comment]
I am running version 3.1. 

Yes, here are a few starting with a simpler one and then the other two are more complicated. 

`hyphy relax --alignment /path/TRPA1_selectiontest_allbranches_alldata.txt --test Test --reference Reference
`
[TRPA1_selectiontest_allbranches_alldata.txt](https://github.com/veg/hyphy/files/4731908/TRPA1_selectiontest_allbranches_alldata.txt)
For this one I got p=1.42e-09, k=1, LRT=36.6, dN/dS test=0.267

`hyphy relax --alignment /path/Painless_selectiontest_allbranches.txt --test Test --reference Reference
`
[Painless_selectiontest_allbranches.txt](https://github.com/veg/hyphy/files/4731968/Painless_selectiontest_allbranches.txt)
For this one I got p=0.0027, k=1, LRT=9.0, dN/dS test=0.175

`hyphy relax --alignment /path/TRPM1b_selectiontest_alldata_allbranches.txt --test Test --reference Reference
`
[TRPM1b_selectiontest_alldata_allbranches.txt](https://github.com/veg/hyphy/files/4731965/TRPM1b_selectiontest_alldata_allbranches.txt)
For this one I got p=8.49e-14, k=1, LRT=55.7, dN/dS test=0.0445

**Comment by aglucaci** [comment]
Dear @juliayork,

Thank you for providing the alignment files. I am still working on identifying the problem. However, when I ran your data through the most recent stable release (HyPhy 2.5.8) I get different results:

TRPA1_selectiontest_allbranches_alldata.txt, Test for selection intensification (K = 1.85) was significant (p = 0.026, LR = 4.96).

Painless_selectiontest_allbranches.txt, Test for selection relaxation (K = 0.42) was significant (p = 0.000, LR = 111.39).

TRPM1b_selectiontest_alldata_allbranches.txt, Test for selection intensification (K = 1.17) was not significant (p = 0.208, LR = 1.59).

I have also attached the json output to this message.
[RELAX_juliayork.zip](https://github.com/veg/hyphy/files/4746622/RELAX_juliayork.zip)

Version 3.1 is in reference to the version of the RELAX model. Could you report the version of the hyphy core program you are running? It should be found by navigating to the folder which hyphy is installed in, and executing the hyphy binary without any command-line arguments.

Best,
Alexander

**Comment by juliayork** [comment]
Interesting, thank you for running those tests. The HyPhy version I have been running is 2.5.2, should I update?

**Comment by spond** [comment]
Dear @juliayork,

Yes, please. There have been many revisions and improvements to the code base since 2.5.2, including those that affect RELAX optimization stability. You should note that if you receive warning messages on the console regarding convergence or stability, you should interpret results with caution.

Best,
Sergei
