### ISSUE TITLE
Branch selection widget for RELAX clears selection

### ISSUE THREAD

**Issue by iwinkler** [veg/hyphy#1166]
The last few days my student & I ran into a problem in datamonkey selecting branches for RELAX. We can select either the Test Branches or Reference Branches, but clicking on the other category to select different branches clears the initial selection. We used it last week without this problem, but now it seems to happen with any file.

**Comment by stephenshank** [comment]
Dear @iwinkler,

Thanks for reporting this. I was able to confirm the behavior. I am investigating now and will follow up shortly.

Best,
Stephen

**Comment by iwinkler** [comment]
Thanks!

**Comment by stephenshank** [comment]
Dear @iwinkler,

You're welcome, thanks to you for reporting! Here is an example with both test and reference branches: http://datamonkey.org/relax/5eeb7d7b64d1164953f089a5

Please let me know if you experience any further issues, I am happy to take a look.

Best,
Stephen
