### ISSUE TITLE
Upload more than 500 sequences

### ISSUE THREAD

**Issue by Marianasousa7** [veg/hyphy#1167]
Hello,

I am a student currently finishing my thesis. I woul appreciate if you could teach me how to submit more than 500 sequences at FEL and other tools.
I know I have to submit the file with a prebuilt tree but I don't know how to do it.

Thank you

**Comment by spond** [comment]
Dear @Marianasousa7,

We limit the number of sequences on `datamonkey.org` to avoid long running jobs that will "clog up" the queue. FUBAR accepts much larger alignments, and it should return results very similar to FEL.

You can analyze as many sequences as you want if you download and install `hyphy` locally. You can also run larger jobs on http://usegalaxy.org, but it may take a while.

Best,
Sergei

**Comment by jzehr** [comment]
Dear @Marianasousa7,

We have a [YouTube channel](https://www.youtube.com/channel/UCIgRnbJjbOWhshe5ThhaWGw) where we are currently in the process of uploading a tutorial, demonstrating how to install hyphy locally and run any tool. 

Be on the lookout for that coming out in the next few days! That should help guide you on how to run your data locally with hyphy. 

Best,
Jordan

**Comment by jzehr** [comment]
Dear @Marianasousa7,

There is now a [YouTube video](https://www.youtube.com/watch?v=fgNrPbOTpxE&t=2s) where you can see how to run Hyphy locally, which should alleviate your troubles of running so many sequences on DataMonkey. 

Best,
Jordan
