### ISSUE TITLE
No prompts in the interactive command line (BUSTED, aBSREL,...)

### ISSUE THREAD

**Issue by PatriciaPI** [veg/hyphy#1172]
Dear All,
Analyses like BUSTED, aBSREL, etc. (either in HYPHY 2.5.14 or 2.5.15) only ask for the coding sequence alignment file in the interactive command line. No prompt appears asking to choose the genetic code, the set of branches, etc. Do I have to use the typical command line?
Best,

Patricia

**Comment by jzehr** [comment]
Dear @PatriciaPI,

When you use interactive mode, the default code is ```universal```, however, you are correct, there is neither a prompt for ```--branches``` in aBSREL, nor ```--branches```, ```rates```,  ```srv``` or ```syn-rates``` in the interactive mode. The command line tools allow you to customize your run, which can be very handy. If you need to manipulate those options, I would suggest using the command line. and we have a tutorial video for that right here: [YouTube](https://www.youtube.com/watch?v=fgNrPbOTpxE&t=2s).

@stevenweaver, are there plans to add these options in to the interactive mode?

Best,
Jordan

**Comment by stevenweaver** [comment]
Dear @jzehr and @PatriciaPI , 

If you supply `-i` as a parameter to HyPhy (e.g. `hyphy -i busted`, it will start HyPhy in interactive mode. 

Best,
Steven

**Comment by PatriciaPI** [comment]
Thanks for your help, @jzehr and @stevenweaver!
