### ISSUE TITLE
Minimum size of a partition in GARD

### ISSUE THREAD

**Issue by wodanaz** [veg/hyphy#1173]
Hi there,
Can you please explain what does this output from GARD method mean?

_Minimum size of a partition is set to be 11 sites__

If this is the size of the partition in base-pairs can I increase it to 500 bp? 

I hope to get GARD to run a long alignment of 30000 bp and 7 species faster

Thanks so much and best regards,

Alejo

**Comment by aglucaci** [comment]
Dear @wodanaz 

The minimum partition size is calculated in such a way to make sure that the cAIC makes sense for individual partitions. 
You could manipulate this value by increasing the number of species in your alignment. 

However, by placing a restriction on the recombination size, the results may fail to return any evidence for recombination.

Best,
Alexander

**Comment by wodanaz** [comment]
Thanks Alex,
This explanation makes sense.
All the best
