### ISSUE TITLE
MEME problem

### ISSUE THREAD

**Issue by vdvornyk1** [veg/hyphy#1175]
Hello,

When trying to run MEME, get the error:
http://datamonkey.org/meme/5ef33f053b1d506dc6b88a81 (((

**Comment by spond** [comment]
Dear @vdvornyk1,

Thanks for reporting. I will take a look and respond with a solution.

Best,
Sergei

**Comment by spond** [comment]
Dear @vdvornyk1,

It appears that several of the sequences in your alignment are on "infinite length" branches. When this happens, you can run into numerical issues like the one that you encountered. Infinite branch lengths are abiological and indicate either an alignment issue or general lack of homology. I would suggest you remove the three problematic sequences and run the alignment through MEME again.

Best,
Sergei

<img width="600" alt="Screen Shot 2020-06-25 at 10 18 20 AM" src="https://user-images.githubusercontent.com/1018513/85737552-7d012780-b6cd-11ea-8f66-c17119d96752.png">
