### ISSUE TITLE
MEME problem

### ISSUE THREAD

**Issue by raquelsvcardoso** [veg/hyphy#1176]
Hello,

I had no problems loading other files and I had no problem loading this exact file with FEL, FUBAR or SLAC, but MEME is just not loading and eventually ends up showing a message like 'cannot connect server'. Is there something I can do or can you help me somehow?

Thank you in advance

**Comment by stephenshank** [comment]
Dear @raquelsvcardoso,

Are you able to try again and share the URL of a MEME job that is failing to run? Something like this:
http://datamonkey.org/meme/5ef4a35429e6dd17c5fabed9

but with an identifier that is specific to your job. The above was just submitted and ran to completion. If you encounter further errors, the URL will help us to troubleshoot.

Best,
Stephen

**Comment by raquelsvcardoso** [comment]
Hello,

These are the URLs, as I'm running triplicates for my work. 

http://www.datamonkey.org/meme/5ef4ac8b29e6dd17c5fac013
http://www.datamonkey.org/meme/5ef4ac9129e6dd17c5fac1f0
http://www.datamonkey.org/meme/5ef4ac9629e6dd17c5fac3cd

Information like Ticket Number and for how long the work is running don't appear. It may be because the file has a lot of sequences but then again I could complete it with other 3 methods.

Thank you!

Best,
Raquel

**Comment by stephenshank** [comment]
Dear @raquelsvcardoso,

Thank you for bringing this issue to our attention. It appears that the MEME job pages are not receiving output from HyPhy as the jobs run, and are not updating with the ID assigned by the job scheduler.

However, I am able to confirm that your jobs are indeed running. You can see them on the job queue page, if you look for MEME jobs with the number of sites and sequences that you submitted:
http://www.datamonkey.org/jobqueue

A few hundred sequences may take some time for MEME to complete, so I will keep an eye on this. I will also investigate why this information is not being transmitted to the frontend.

Additionally, you may find the email feature useful for notifying you when long running jobs have completed.

I'll be sure to post updates here as I have them.

Best,
Stephen
