### ISSUE TITLE
_LikelihoodFunction::GradientLocateTheBump: 

### ISSUE THREAD

**Issue by AishaYousaf** [veg/hyphy#1177]
Hi,

I am running HYPHY on local server and faced following error. This error prompts for some of the input files. Can you plz tell why this is happening and how to fix this?

Thanks for your time!  

Error:
   
    Master node received an error:Internal error 
     _LikelihoodFunction::GradientLocateTheBump: in the Brent loop iteration 1. -11096.48685194589 / -11062.89471805549.
    Optimization direction: 
    {
    {-10000} 
    {-10000} 
    {0} 
    {0} 
    {0} 
    {0} 
    {-10000} 
    {-10000} 
    {-10000} 
    {-10000} 
    }
    
    Function call stack
    1 :  Optimize(MLEs, L);

Best wishes,
Aisha

**Comment by spond** [comment]
Dear @AishaYousaf,

This error indicates a numerical optimization problem with your analysis. Without any further details (what analysis, input data, run options), I can not provide any meaningful help. Generally, these errors occur in ill-conditioned data, e.g. those that are too divergent, or because there's a previously undiagnosed "edge" condition which breaks HyPhy optimization.

Best,
Sergei

**Comment by AishaYousaf** [comment]
Hi Sergei,

This error appears when I run the following command.  The command runs successfully on all files except few.
         hyphy chr.coordinates.null.bf > HYPHY/chr.coordinates.null.out

_Input File: chr.coordinates.bf_
 random_seed=449;
 quer_seq_file= "/Query_Align/chr.coordinates.fa.prunned";
 ref_seq_file = "/REF/chr.co-ordinates.ref.fa";
 fit_repl_count = 20;
 tree= "(sp1,(sp2,sp3),sp4)";
 fgrnd_branch_name = "sp1";
 res_file = "res/chr2.coordinates.null.res";
 #include "null4-fgrnd_spec.bf";

[null4-fgrnd_spec.bf](https://github.com/wodanaz/adaptiPhy/blob/master/null4-fgrnd_spec.bf)

Thanks for your time!

Best wishes,
Aisha

**Comment by spond** [comment]
Dear @AishaYousaf,

Thanks for providing this additional info. In order to debug it, I also need to have `/REF/chr.co-ordinates.ref.fa` and `/Query_Align/chr.coordinates.fa.prunned`, so that I can fully recreate the analysis. Also, which version of HyPhy are you using? (run `hyphy --version` to see what it is; if you get an error running this command, it means that the version you have is *very* old).

Best,
Sergei

**Comment by AishaYousaf** [comment]
Hi Sergei,

I am using HYPHY 2.5.15.

I have attached the required files.
[chr.coordinates.ref.fa.txt](https://github.com/veg/hyphy/files/4842402/chr.coordinates.ref.fa.txt)


[chr.coordinates.fa.prunned.txt](https://github.com/veg/hyphy/files/4842401/chr.coordinates.fa.prunned.txt)

Best wishes,
Aisha

**Comment by spond** [comment]
Dear @AishaYousaf,

I committed a fix to the `develop` branch (will be in the next release too). There was an "edge" case with optimization not behaving properly.

I also made a minor tweak to 
[null4-fgrnd_spec.bf.txt](https://github.com/veg/hyphy/files/4847811/null4-fgrnd_spec.bf.txt) to avoid recreating the likelihood function.

Best,
Sergei

**Comment by AishaYousaf** [comment]
Hi @spond 

Can I continue the analysis using updated null4-fgrnd_spec.bf.txt file. Moreover, is there any need to update my hyphy installation?

Thanks for your time.

Best,
Aisha

**Comment by spond** [comment]
Dear @AishaYousaf,

Yes, you need to update HyPhy to what's on the `develop` branch (see README at https://github.com/veg/hyphy-analyses/). 
It also seems like you are using old code from the Fedrigo Haygood 2007 paper which performs optimizations from different starting conditions. With more recent versions of HyPhy that may be unnecessary, you can simply request that HyPhy consider different initial values and start optimizing from the best one (see code starting at https://github.com/spond/TestForPositiveSelection/blob/faaef803d2e68fa6a12a87c3ae6144d0516ec678/nonCodingSelection.bf#L326 for an example).

Best,
Sergei

**Comment by AishaYousaf** [comment]
Hi @spond 

I updated hyphy to that on the develop branch.. But now every time I run hyphy, it gives an error:
segmentation fault (core dumped)

**Comment by spond** [comment]
Dear @AishaYousaf,

Do you see this behavior for the test datasets you provided?

Best,
Sergei

**Comment by AishaYousaf** [comment]
Hi @spond 

Yes. I see this behavior for test dataset as well as every run.

Can you tell me what might be causing this or how to fix it?

Thanks!!

Best wishes,
Aisha

**Comment by spond** [comment]
Dear Aisha,

I can't replicate this behavior on my system, but let's try this.

1. Make the DEBUG version of HyPhy (`make DEBUG`) in the HyPhy directory (what you checked out from GitHub)
2. Run `gdb ./HYPHYDEBUG` (or `lldb` depending on what your system has). 
3. `run /path/to/wrapper.bf`

Let me know what the output looks like.

Best,
Sergei

**Comment by AishaYousaf** [comment]
Hi @spond,

Make DEBUG had errors. Here is the make DEBUG log file. 
[make_debug_log.txt](https://github.com/veg/hyphy/files/4908053/make_debug_log.txt)

An excerpt from log file.

/usr/bin/ld: cannot find libasan_preinit.o: No such file or directory
/usr/bin/ld: cannot find -lasan
collect2: error: ld returned 1 exit status
make[3]: *** [HYPHYDEBUG] Error 1
make[2]: *** [CMakeFiles/HYPHYDEBUG.dir/all] Error 2
make[1]: *** [CMakeFiles/DEBUG.dir/rule] Error 2
make: *** [DEBUG] Error 2
