### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by raquelsvcardoso** [veg/hyphy#1178]
Hello, I'm sorry for bothering you in here but I tried to but I have a question that maybe you'd be so kind to answer.

I'm using 4 methods of Datamonkey on my Master thesis so I made 4 scripts to recover the PSS and DSS from the excels. My scripts to SLAC and FUBAR work fine but sometimes I miss one PSS or MSS on MEME or FEL. On MEME, when values from column p-value that are under 0.05, I recover the value from column 'Site' in the same row. On FEL, when the values from column p-value are under or equal to 0.05 I get the value from column 'Site' in the same row. Then I intersect that with the values from column 'Site' in the same row as 'Infinity' or above 1 in the column omega.

Is there some criterion that I'm missing?

Attached I have a screenshot. My scripts recover 139 and 266 because I don't understand the condition I'm missing.

Thanks in advance,
Raquel

**Comment by srwis** [comment]
Hi Raquel,

Could you try attaching your screenshots again? I'm not seeing them. Also to make sure we're on the same page, you want to extract which sites are positively selected according to those 4 methods, correct?

Thanks,
Sadie

**Comment by raquelsvcardoso** [comment]
Hello,

Yes, I'm sorry, it's attached now! Yes I do. I also extracted the NSS but I had no problem with those.

I only took a screenshot at MEME but this also happened with FEL.

![duvida_meme](https://user-images.githubusercontent.com/62177203/86010851-e063c000-ba13-11ea-9da1-f013bb46dfa2.png)

Thanks,
Raquel

**Comment by spond** [comment]
Dear @raquelsvcardoso,

MEME only detects positively selected sites; all you need to check is whether or not the p-value is below a cutoff. Also, we generally **do not** recommend that you intersect the results from many methods -- that way you will simply recover the sites found by the least powerful method (SLAC). MEME detects episodic selection, while SLAC/FEL/FUBAR detect only pervasive selection, so it is expected that some sites found by MEME will not be found by other methods.

Best,
Sergei

**Comment by raquelsvcardoso** [comment]
Hello,

Thank you for your clarification about pervasive and episodic selection,
that was really helpful. Maybe I didn't explain myself right but what I was
trying to figure out is why MEME detected 8 as a positive selected site and
not 139 and 226, given that all of them are below the cutoff value.

Thanks,
Raquel

Sergei Pond <notifications@github.com> escreveu no dia segunda, 29/06/2020
à(s) 14:34:

**Comment by spond** [comment]
Dear @raquelsvcardoso,

139 and 226 have p-values **above** 0.05. The table you see displays rounds p-values to 2 digits of precision, so 0.048 and 0.052 will both appear as 0.05. You need to look at the JSON files to see full precision p-values.

Best,
Sergei

**Comment by raquelsvcardoso** [comment]
Dear Sergei,

I get it now, thank you!

Best,
Raquel

Sergei Pond <notifications@github.com> escreveu no dia segunda, 29/06/2020
à(s) 14:56:
