### ISSUE TITLE
MEME: beta changing with change in test branches

### ISSUE THREAD

**Issue by crs344** [veg/hyphy#1180]
Hi,

When using the same data in MEME, but different test branches (about half of the tree vs. 4 branches), beta (but not alpha) is uncorrelated between the same amino acid positions. Is this because beta is calculated for test branches first, or is there an issue?

Attached are 1) the alignment, tree, and json and log outputs for 2 tests with different test branches, as well as 2) correlations for a and b- between test replicates and test with different branches.

[Archive.zip](https://github.com/veg/hyphy/files/4879619/Archive.zip)
[MEME_correlations.xlsx](https://github.com/veg/hyphy/files/4879638/MEME_correlations.xlsx)

Thank you for you help,

Chelsea

**Comment by spond** [comment]
Dear @crs344,

If you use different test sets (especially if they are quite different), there is not reason to expect that &beta; values will be strongly correlated, unless there is no evolutionary heterogeneity in the tree. This behavior is expected. The should be a much clearer correlation between &alpha; rates (since they are supposed to be measuring the "baseline" rate at the site), but they also will be influenced somewhat by the test set.

Best,
Sergei

**Comment by Suirotras** [comment]
Dear @spond

I have a quick question, which this github issue is somewhat related to. I am unsure what selecting a test branch actually does. If I select a single branch as the test set, thus setting all the other branches as background, hoe does this change the estimation of the α or β substitution rates? 

1) Are the α and β rates for an individual site solely based on the test set, or are they based on all the information from that specific site (that site across all the branches). By looking at the results, it at least looks like the _mixture distribution weights_ are only based on the test set.
2) If these values are based on the complete site information, for what purpose am I specifying the test set.

Thanks for the help and for all the work on these usefull tools!

Best,
Jari

**Comment by spond** [comment]
Dear @Suirotras,

_Techincally_, &alpha; and &beta; (and `p`) values are inferred from the entire site. By specifiying a foreground set of branches, one places a FEL (single &beta;, different from the foregound &beta;s) model on the backgound. So to the first order of approximation, it is useful to think thus

1). &alpha; is informed by the entire site
2). &beta; (and weights) are informed by the foreground.

For example:

```
 hyphy meme --alignment tests/data/adh.nex --branches Internal
...

|    170     |     1      |    0.781   |   45.678   |    0.127   |    9.526   |      Yes, p =  0.0037      |     2      |[2]ccC>ccT|[1]AGt>CAt,Agt>Ggt,Cct>Act,CCt...|
|    197     |     1      |    0.000   |    5.519   |    0.295   |    4.173   |      Yes, p =  0.0578      |     0      |   [2]aGt>aAt|[1]aAt>aGt,Agt>Ggt,Gat>Aat    |
```
...

```
 hyphy meme --alignment tests/data/adh.nex --branches Leaves
...

|    170     |     1      |    0.780   |   17.929   |    0.144   |    6.142   |      Yes, p =  0.0210      |     2      |[2]ccC>ccT|[1]CAt>AGt,CAt>GGt,Cct>Act,cCt...|
|    197     |     1      |    0.000   |    9.507   |    0.096   |    5.685   |      Yes, p =  0.0265      |     1      |     [1]aAt>aGt,AAt>GGt,aGt>aAt,Gat>Aat     |
...
```

Best,
Sergei

**Comment by Suirotras** [comment]
Dear @spond,

Thanks for the quick and clear reply. 

I think I understand. So every site in the background will be described by just one β value, and the β values used in the diversifying selection will be the foreground β values.

With this in mind, am I right that selecting the single branch I am interested in as foreground is not a very good approach? I think this because of the following:

1) The two foreground β values will just be estimated by a single foreground branch-site, and that probably gives a bad estimation of the foreground β values.
2) The whole advantage of MEME (a site can be assigned to β- or β+, allowing detection of episodic selection) disappears, as practically all sites in the background branches will be described by a single β. 

I guess if I am interested in diversifying selection in a single branch, it is better to select all branches as foreground and just be very careful in my interpretation? I know that MEME does not tell me anything about which branches are under the effect of diversifying selection, only the sites. I know that aBSREL is better for detecting branch-level information, but I already ran aBSREL and I wanted to investigate some of the sites that were evolutionary important.

Best,
Jari

**Comment by spond** [comment]
Dear @Suirotras,

Your points (1) and (2) are spot on.  The estimates of &beta; from a single branch will be noisy, and when the foreground is set to a single branch, there is essentially no difference between FEL and MEME. A subtle difference is that FEL uses a less conservative LRT test (MEME has to account for more "boundary" conditions), so it will generally find MORE sites under selection, and corresponding p-values will be smaller.

For instance, here's the output on an example one-branch-foreground case (data from https://github.com/veg/selection-tutorial/blob/main/data/HIV-sets.fas branch set `TRANSMISSION`). Note how `p+` is always 1 for MEME, and that site-level estimates are indeed quite noisy.

#### MEME

```
### For partition 1 these sites are significant at p <=0.1

|   Codon    | Partition  |   alpha    |   beta+    |     p+     |    LRT     |Episodic selection detected?| # branches |Most common codon substitutions at this site|
|:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|:--------------------------:|:----------:|:------------------------------------------:|
|     11     |     1      |    0.000   |  269.732   |    1.000   |    5.928   |      Yes, p =  0.0234      |     1      |         [1]Act>Cct,aGt>aAt,aGt>aCt         |
|     48     |     1      |    0.000   |   74.291   |    1.000   |    5.483   |      Yes, p =  0.0294      |     1      |                 [2]Atg>Ctg                 |
|     59     |     1      |    0.007   |  372.583   |    1.000   |    5.838   |      Yes, p =  0.0245      |     1      |             [1]aAt>aTt,Att>Gtt             |
|    153     |     1      |    0.000   |  149.453   |    1.000   |    6.160   |      Yes, p =  0.0208      |     1      |                 [1]aTc>aCc                 |
|    189     |     1      |    0.000   |  155.135   |    1.000   |    4.099   |      Yes, p =  0.0601      |     1      |             [1]aAa>aGa,Caa>Aaa             |
|    205     |     1      |    0.000   |   57.121   |    1.000   |    3.373   |      Yes, p =  0.0878      |     1      |                 [1]gaC>gaA                 |
|    208     |     1      |    0.000   |  170.604   |    1.000   |    4.384   |      Yes, p =  0.0518      |     0      |                 [2]aCa>aAa                 |
|    214     |     1      |    0.000   |   99.956   |    1.000   |    4.427   |      Yes, p =  0.0507      |     1      |             [1]Gct>Act,Tct>Gct             |
|    264     |     1      |    0.000   |  782.802   |    1.000   |   11.285   |      Yes, p =  0.0015      |     1      |                 [1]TGG>AAT                 |
|    265     |     1      |    0.000   |  354.918   |    1.000   |    3.631   |      Yes, p =  0.0767      |     0      |             [1]GgG>AgT,gGg>gAg             |
|    266     |     1      |    0.237   |10000.000...|    1.000   |    9.793   |      Yes, p =  0.0033      |     1      |             [1]aAT>aCA,aAt>aGt             |
|    267     |     1      |   13.129   |  772.555   |    1.000   |    3.540   |      Yes, p =  0.0804      |     1      |         [1]Ggt>Agt,ggT>ggC,GgT>TgG         |
|    268     |     1      |    7.269   |  1037.967  |    1.000   |    7.647   |      Yes, p =  0.0097      |     1      |             [1]aCT>aAC,ACT>GAG             |
|    270     |     1      |   13.707   |10000.000...|    1.000   |    6.435   |      Yes, p =  0.0180      |     0      |         [1]aGt>aAt,TTA>AGT,TTA>GAG         |
|    276     |     1      |    0.000   |  238.904   |    1.000   |    4.905   |      Yes, p =  0.0396      |     0      |             [1]aCt>aAt,aCt>aTt             |

### ** Found _15_ sites under episodic diversifying positive selection at p <= 0.1**
```

#### FEL

```
|     Codon      |   Partition    |     alpha      |      beta      |      LRT       |Selection detected?|
|:--------------:|:--------------:|:--------------:|:--------------:|:--------------:|:-----------------:|
|       11       |       1        |        0.843   |      282.172   |        5.811   |  Pos. p = 0.0159  |
|       48       |       1        |        0.000   |       72.969   |        4.855   |  Pos. p = 0.0276  |
|       59       |       1        |        0.791   |      364.766   |        5.746   |  Pos. p = 0.0165  |
|      153       |       1        |        0.000   |      149.916   |        6.159   |  Pos. p = 0.0131  |
|      165       |       1        |        0.000   |      195.872   |        2.947   |  Pos. p = 0.0860  |
|      189       |       1        |        0.000   |      148.134   |        4.100   |  Pos. p = 0.0429  |
|      203       |       1        |        0.783   |      134.277   |        2.735   |  Pos. p = 0.0982  |
|      205       |       1        |        0.000   |       58.650   |        3.370   |  Pos. p = 0.0664  |
|      208       |       1        |        0.000   |      174.024   |        4.075   |  Pos. p = 0.0435  |
|      214       |       1        |        0.000   |       97.260   |        4.428   |  Pos. p = 0.0354  |
|      264       |       1        |        2.379   |      783.970   |        5.373   |  Pos. p = 0.0204  |
|      265       |       1        |        0.733   |      329.408   |        3.249   |  Pos. p = 0.0715  |
|      266       |       1        |        1.080   |    10000.000   |        9.653   |  Pos. p = 0.0019  |
|      267       |       1        |       12.857   |      770.387   |        3.540   |  Pos. p = 0.0599  |
|      268       |       1        |        7.286   |      935.482   |        7.649   |  Pos. p = 0.0057  |
|      270       |       1        |        0.000   |    10000.000   |        2.869   |  Pos. p = 0.0903  |
|      276       |       1        |        0.831   |      235.748   |        3.909   |  Pos. p = 0.0480  |

### ** Found _17_ sites under pervasive positive diversifying and _0_ sites under negative selection at p <= 0.1**

````

MEME does compute the extent of support for &beta;>&alpha; for each individual branch, with empirical Bayes Factors. It is defined as 

```
Pr (beta = beta+ | site)                 p+
-------------------------   : ----------------
1 - Pr (beta = beta+ | site)           1 - p+
````

Here, `Pr (beta = beta+ | site) ` is estimated using the empirical Bayes procedure, i.e. 

```
Pr (beta = beta+ | site)   = (Pr (site | beta = beta+) * p+) / Pr (site)  
```

These values are recorded in the `.json` file, and can be visualized using https://observablehq.com/@spond/meme

For example...

```
$hyphy meme --alignment tests/data/bglobin.nex


|   Codon    | Partition  |   alpha    |   beta+    |     p+     |    LRT     |Episodic selection detected?| # branches |Most common codon substitutions at this site|
|:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|:--------------------------:|:----------:|:------------------------------------------:|
|     10     |     1      |    0.456   |   10.455   |    0.149   |    6.102   |      Yes, p =  0.0214      |     2      |[2]acT>acC|[1]ACc>CTc,aCt>aAt,Act>Gct,Act...|
|     11     |     1      |    0.000   |   13.310   |    0.285   |    6.566   |      Yes, p =  0.0169      |     2      |[3]gGc>gCc|[1]GGc>ACc,GGc>TCc,GGC>TCT,Ggc...|
|     14     |     1      |    0.706   |    5.195   |    0.155   |    3.502   |      Yes, p =  0.0820      |     3      |[1]gGa>gCa,ggC>ggA,ggC>ggG,GGC>TCT,GGg>CA...|
|     21     |     1      |    0.000   |    1.644   |    0.349   |    4.998   |      Yes, p =  0.0377      |     0      |         [1]GTt>ACt,gTt>gAt,GTt>TGt         |
|     27     |     1      |    0.000   |    2.532   |    0.140   |    5.510   |      Yes, p =  0.0290      |     2      |             [1]gGc>gCc,GGc>TCc             |
|     37     |     1      |    0.000   |   17.986   |    0.037   |    7.626   |      Yes, p =  0.0098      |     1      |                 [1]CAG>ACC                 |
|     42     |     1      |    0.286   |   16.041   |    0.179   |    9.961   |      Yes, p =  0.0030      |     1      |[2]AGc>TCc|[1]aGc>aAc,agC>agT,AGc>CAc,TCc...|
|     48     |     1      |    0.000   |   32.401   |    0.248   |   16.862   |      Yes, p =  0.0001      |     3      |[2]TCt>AAt,Tct>Act|[1]aAt>aCt,aAT>aGC,TCT...|
|     50     |     1      |    0.343   |   39.941   |    0.271   |    8.216   |      Yes, p =  0.0073      |     1      |[2]TCt>GAt|[1]Gat>Aat,gAT>gCC,TCt>AAt,Tct...|
|     54     |     1      |    0.458   |    4.586   |    0.330   |    6.541   |      Yes, p =  0.0171      |     3      |[2]GGc>AAc,Ggc>Agc|[1]ggC>ggA,ggC>ggT,GGC...|
|    110     |     1      |    1.134   |   39.098   |    0.142   |    9.158   |      Yes, p =  0.0045      |     0      |  [3]atT>atC|[2]TGt>GTt|[1]ATt>TGt,TGt>ATt  |
|    116     |     1      |    1.094   |   29.864   |    0.060   |    3.318   |      Yes, p =  0.0904      |     1      |[2]Ttt>Ctt|[1]ctT>ctG,TTt>CAt,TtT>CtG,ttT...|
|    123     |     1      |    0.289   |   41.711   |    0.257   |    7.741   |      Yes, p =  0.0093      |     0      |[1]Aaa>Caa,CaG>AaT,cAG>cCA,CaG>GaA,CAg>GT...|
|    133     |     1      |    0.207   |   85.190   |    0.035   |    5.925   |      Yes, p =  0.0234      |     1      |             [1]GCT>CGC,gcT>gcA             |

### ** Found _14_ sites under episodic diversifying positive selection at p <= 0.1**

```

In the JSON file you will find, for each tested branch, an Nx2 (N=number of codons) matrix of posterior probabilities for `beta` like so (key `Posterior prob omega class by site`)

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/1018513/214077906-03fb7f60-9bde-42ee-81fd-02fb5a3239d5.png">

Viewing a couple of sites in the notebook shows you the "intensity" of selection by branch

<img width="851" alt="image" src="https://user-images.githubusercontent.com/1018513/214078386-f86751b2-7bf9-4e22-941c-df432a9f16e7.png">


<img width="843" alt="image" src="https://user-images.githubusercontent.com/1018513/214078695-a1020992-f105-4e39-8876-792db8679364.png">


Best,
Sergei

**Comment by Suirotras** [comment]
Dear @spond,

Thanks again for the detailed response. I think I understand it quite clearly now.

Interestingly, I also did have the question how to empirical bayes factor was calculated from the JSON files, as I maybe wanted to do that myself. But I see that you already answered that question in your previous reply before I had asked it.

Best,
Jari
