### ISSUE TITLE
Interpretation of the RELAX model

### ISSUE THREAD

**Issue by ndrubins** [veg/hyphy#1181]
Hi,

I'm trying to understand how to interpret the RELAX model results for my data.

I'm getting K = 3.24 with a p-value = 0.007 and LR = 7.22. From the [documentation](http://hyphy.org/methods/selection-methods/#relax) this is regarded as evidence that selection strength has been intensified along the test branches.

However, in the RELAX alternative, I see these values:
reference: w1: 0 (61.84%); w2: 1 (37.18%); w3: 84.69 (0.98%)
test: w1: 0 (61.84%); w2: 1 (37.18%); w3: 1727448.12 (0.98%)

If this means that the test branches have a much higher w3 (which is also what I'm seeing in the omega plot of RELAX alternative) then isn't it actually indicative of relaxation of purifying selection along the test branches rather than intensification? Or does the [documentation](http://hyphy.org/methods/selection-methods/#relax) mean that if K > 1 positive selection strength has been intensified along the test branches?

Another related question is regarding the non-synonymous/synonymous rate ratio for the reference, test, and unclassified groups which appears both in the standard output and in the json file.

In my case it is in the stabndard output:
* non-synonymous/synonymous rate ratio for *Reference* =   0.2112
* non-synonymous/synonymous rate ratio for *Test* =   0.4326
* non-synonymous/synonymous rate ratio for *Unclassified* =   0.5757

Are these the omega values of the General Descriptive model? If so, again - given the higher omega for the test group I would conclude that purifying selection has been relaxed.

Thanks for your help

**Comment by spond** [comment]
Dear @ndrubins,

>non-synonymous/synonymous rate ratio for Reference = 0.2112
non-synonymous/synonymous rate ratio for Test = 0.4326
non-synonymous/synonymous rate ratio for Unclassified = 0.5757

These are **average** values (no site to site or branch to branch variation) estimated using the MG94 model. General descriptive models estimates a distribution of rates. 

>If this means that the test branches have a much higher w3 (which is also what I'm seeing in the omega plot of RELAX alternative) then isn't it actually indicative of relaxation of purifying selection along the test branches rather than intensification? Or does the documentation mean that if K > 1 positive selection strength has been intensified along the test branches?

Any &omega; > 1 is interpreted as evidence of positive selection. Increased &omega;>1 therefore implies **stronger** positive selective pressure. In your case it seems like ~62% of your alignment is perfectly conserved at the aa. level (&omega; = 0), about 37% are evolving neutrally, and 1% is under strong positive selection, with selection being stronger along the **test** branches.

Best,
Sergei
