### ISSUE TITLE
Inconsistent RELAX results

### ISSUE THREAD

**Issue by ksummers26** [veg/hyphy#1182]
Hello - I have been running some analyses with RELAX to look at patterns of selection or relaxation of selection across domesticated species and their wild relatives, but have been getting what appear to be inconsistent results with the current alignment of the gene BAZ1B. Different runs have indicated intensified positive selection, or significant relaxation of selection. I'm not sure if I am doing something wrong or the program is converging on different results in different runs?
[BAZ1B.codon.short.txt](https://github.com/veg/hyphy/files/4907353/BAZ1B.codon.short.txt)

**Comment by spond** [comment]
Dear @ksummers26,

1. Can you provide the partitioned tree (Newick) with Test and Reference branches?
2. Are you running RELAX locally or on Datamonkey?
3. Which version of the analysis are you running and are you using any non-default settings?

Best,
Sergei

**Comment by ksummers26** [comment]
Dear Sergei,
Thank you for your rapid reply. I ran the analyses in Datamonkey using the default settings (latest version, I assume). I am sending a screenshot of the tree with the test branches selected (the domesticated species - note the bonobo is thought to be self-domesticated). The tree topology was created by the program, I assume on the basis of sequence similarity but I don't know what algorithm (maximum likelihood?). The tree doesn't appear to be an accurate representation of the species tree in a few places - I wasn't sure if this was of concern. I'm also uploading a pdf printout of the results of one run.
Thanks again, Kyle
[RELAX-BAZ1B-ResultsSum.pdf](https://github.com/veg/hyphy/files/4907428/RELAX-BAZ1B-ResultsSum.pdf)
<img width="1440" alt="Screen Shot 2020-07-11 at 2 05 48 PM" src="https://user-images.githubusercontent.com/16978802/87230912-ed23d480-c380-11ea-9661-cf77b8dcff59.png">

**Comment by spond** [comment]
Dear @ksummers26,

Thanks! Could you include the URL to your Datamonkey job, so that I don't make data entry errors in trying to recreate branch partitions and can look at job logs?

The tree is built using neighbor-joining, so it is "rough". Gene trees may not agree with species trees for a variety of reasons including biological (gene family evolution that does not mirror species evolution due to gene conversion, duplication etc), or artifactual (inference errors or lack of phylogenetic signal in some genes).

Best,
Sergei

**Comment by ksummers26** [comment]
I'm not sure if this is what you meant but I started another run to get the URL: https://datamonkey.org/relax/5f0a03f43c24de72bb716dc2
Is that what you needed?

**Comment by spond** [comment]
Dear @ksummers26,

Yes, thanks. I'll see what I can find out.

Best,
Sergei

**Comment by spond** [comment]
Dear @ksummers26,

Upon closer inspection, it does seem like this dataset causes RELAX to generate unreliable estimates. One way to check which one is preferred is to compare two (or more runs) and select the one where the `Alternative` model has the best (lowest) AIC-c score. RELAX **should** report some diagnostics on convergence issues, but it doesn't in the case of your dataset. I will add this example as a test case to improve RELAX diagnostic reporting.

Best,
Sergei

**Comment by ksummers26** [comment]
OK, thanks for looking into this. We are running a bunch of neural crest genes – if just this one gene is inconclusive it’s no big deal, but if they all turn out this way I’ll have to use a different method. I’ve run three others which all seemed fine, but I didn’t run them multiple times so I’m not sure. I guess I’ll go back and run them a few more times just to check.

Best, Kyle

**Comment by spond** [comment]
Dear @ksummers26,

FWIW, convergence issues usually arise with "weird" distributions (like having extreme values of &omega; i.e. one near 0 and one **much** higher than one).

Best,
Sergei
