### ISSUE TITLE
Invalid Id

### ISSUE THREAD

**Issue by NeverseenAgain** [veg/hyphy#1183]
Hello,

I am getting an Invalid Id error from my results and I cannot figure out what to change.
it Reads
{"error":"Invalid ID : 5f0f4a2d3c24de72bb7243b2."}

**Comment by stevenweaver** [comment]
Dear @NeverseenAgain, 

Was this from a job run recently or one that you were returning to from some time ago?

Best,
Steven

**Comment by NeverseenAgain** [comment]
It was a job that was ran recently I started it about an Hour ago

**Comment by stevenweaver** [comment]
Dear @NeverseenAgain, 

I'm not sure where things must have gone wrong, but the url to your results is here:
http://datamonkey.org/absrel/5f0f4a2d3c24de72bb7243b2

Best,
Steven

**Comment by NeverseenAgain** [comment]
Thank you.
