### ISSUE TITLE
processing GARD results

### ISSUE THREAD

**Issue by jbloom** [veg/hyphy#1184]
I'm curious if there is still functionality to process GARD results?

Running `hyphy --help` lists `grdr` as one of the options (to process GARD results). But trying to run this gives an error as `GARDProcessor.bf` has been removed from the TemplateBatchFiles.

I may not understand how to run GARD correctly, but my understanding is that after doing the run of `gard` to get the AIC differences between models +/- breakpoints, there should be some downstream test for topological incongruence between the trees for the different partitions. How is this supposed to be run?

**Comment by spond** [comment]
Dear @jbloom,

Oops! I'll remove the `grdr` option. The current version of `GARD` includes result processing in the script itself and outputs a `json` file that contains all the pertinent information (e.g. http://vision.hyphy.org/gard). It no longer performs the KH test in the script; I can add it back in as an option if you'd like :)

Best,
Sergei

**Comment by jbloom** [comment]
@spond, thanks so much. It would be great to have some guidance for how (or if) to perform the KH test. 

My understanding is that the KH test for whether the partitions have different topologies is important to make sure breakpoints found by GARD are really recombination, and not just rate variation. Is that correct?

I do know that `hyphy` has the KH test installed, so just knowing how to take the GARD results into that test would be great.

**Comment by spond** [comment]
Dear @jbloom,

The current implementation of GARD does include a check for overall rate-variation vs topology difference: it compares AIC-c score between the models where (1) partitions are allowed to have their own trees, (2) partitions have the same topology but different branch lengths. The KH-test gives you the added bonus of identifying specific breakpoints that delineate topologically different partitions. 

If all you care is to check whether or not rate variation alone is sufficient to explain the improvement in fit, the AIC-c test is probably sufficient. 

I need to write a little glue script to extract pieces from the GARD output file to feed into the KH test. I'll post it here in a day or two...

Best,
Sergei
