### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NeverseenAgain** [veg/hyphy#1186]
Hello

I am getting an error code on my link to the job i sent its code is 5f176d6a60a5151234e9fd62

**Comment by stevenweaver** [comment]
Dear @NeverseenAgain, 

What is the error you see and which browser are you using?
The job renders fine here http://datamonkey.org/absrel/5f176d6a60a5151234e9fd62

Best,
Steven

**Comment by NeverseenAgain** [comment]
I use google chrome and this is a recurring error whenever i do a job it gives Me an ID error and i cannot view this

**Comment by stevenweaver** [comment]
Dear @NeverseenAgain, 

I checked our logs, and it looks like you are (or your browser) adding an extra period at the end of the link. Please make sure there is no ending period in the url. 

Best,
Steven
