### ISSUE TITLE
Can HYPHY use the beast MCC tree as an input tree for selection pressure analysis?

### ISSUE THREAD

**Issue by virologist** [veg/hyphy#1189]
Hi, HYPHY programmer

Most papers look like prefer to use ML tree as the input tree for HYPHY analysis.
I am wondering can I use a beast MCC tree topology as the input tree for selection pressure analysis?

Thanks
Yang

**Comment by spond** [comment]
Dear @virologist,

You can use whatever tree you choose, so long as it matches the sequences in your data (same # of tips, same labels). MCC tree is just fine. You can even supply partially unresolved trees. Of course if you think that the tree you use may have a significant effect on inference, you should try several (ML and MCC etc), but typically selection analyses (site level at least) are quite **in**sensitive to the topology.

Best,
Sergei

**Comment by virologist** [comment]
Wonderful! 
Thank you for your reply.
