### ISSUE TITLE
GARD result file makes aBSREL analysis

### ISSUE THREAD

**Issue by cuzzlisa** [veg/hyphy#1191]
I have a 19-sequences codon alignment  to make aBSREL analysis, someone advised me I had to take GARD as pre-processing. when I used GARD, I  choose the "data type" codon, and the "Site-to-site rate variation" None, the "rate-classes"  3. the result file .best-gard contains more than 1 trees. but aBSREL can only run with one tree. What should I do that could  run absrel?

**Comment by jzehr** [comment]
Dear @cuzzlisa,

Are you running on datamonkey.org or are you using the command line tools? 

One possible solution to this is to open up your .best-gard file and you should see a section that says ``` BEGIN ASSUMPTIONS``` (for example:  ```CHARSET span_1 = 1-654;```). Here is where the method suggests to partition your alignment. There are corresponding trees in the ```BEGIN TREES``` section (for example: ```TREE tree_1 =```, thus you can partition your alignment file based on the partitions the method suggests, and pair it with the tree that that individual partition produced. 

At this point you can run as many aBSREL jobs as partitions. 

If you have any other questions feel free to reach out!

Best,
Jordan

**Comment by cuzzlisa** [comment]
Dear @Jordan,

        Thank you for your quick reply.

        I have runned my data on datamonkey.org at first. I chose the "data type" as **codon,** and  the "Site-to-site rate variation" GDD/Gamma, the "rate-classes" 3. but when I checked the analysis log ,it displayed the data type is "**Nucleotide**" **,">Loaded** a nucleotide multiple sequence alignment** . I don't understand why it showed this. so I choose the command line tools finally. it showed codon data type.
        
       here's a par of my best-gard file:
BEGIN ASSUMPTIONS;
	CHARSET span_1 = 1-66;
	CHARSET span_2 = 67-1215;
END;
BEGIN TREES;
	TREE tree_1 = 
        TREE tree_2 = 
         As you suggested, I can choose the tree1 representing the whole alignment to run the aBSREL.
         you can see CHARSET span_1 is longer than CHARSET span_2.  Does the  CHARSET span_1 or tree 1 is  still more representative than  CHARSET span_2 or tree 2 ?   should I run the tree1 and also the tree 2 or just run the tree 1 that can represent the whole alignment on aBSREL?

Best,
cuzzlisa

**Comment by cuzzlisa** [comment]
Dear @jordan,

    Thank you for your quick reply.

    I have runned my data on datamonkey.org at first. I chose the "data type" as codon,and  the "Site-to-site rate variation" GDD/Gamma, the "rate-classes" 3. but when I checked the analysis log ,it displayed the data type is "Nucleotide" ">Loaded a nucleotide multiple sequence alignment . I don't understand why it showed this. so I choose the command line tools finally. it showed codon data type.
    
   here's a par of my best-gard file:
BEGIN ASSUMPTIONS;
CHARSET span_1 = 1-66;
CHARSET span_2 = 67-1215;
END;
BEGIN TREES;
TREE tree_1 =
TREE tree_2 =
As you suggested, I can choose the tree1 representing the whole alignment to run the aBSREL.
you can see CHARSET span_1 is longer than CHARSET span_2. Does the CHARSET span_1 or tree 1 is still more representative than CHARSET span_2 or tree 2 ? should I run the tree1 and also the tree 2 or just run the tree 1 that can represent the whole alignment on aBSREL?

Best,
cuzzlisa

**Comment by jzehr** [comment]
Dear @cuzzlisa,

Based on the results you provided, it looks like the ```CHARSET span_1``` is SHORTER than ```CHARSET span_2```, as it includes fewer positions. 

At this point you can take your original alignment and separate it into two alignments; one that starts at position 1 and ends at position 66, and one that begins at position 67 and ends at position 1215. The first partition corresponds to ```TREE tree_1``` and the second partition corresponds to ```TREE tree_2```, so take the first partition and first tree and run that through ```aBSREL```, and then do the same for the second partition and second tree.

Best,
Jordan

**Comment by cuzzlisa** [comment]
Dear @Jordan,

You explained very thoroughly. I completely understand.  Thank you again for your generous help.(smile,smile)

Best,
cuzzlisa
