### ISSUE TITLE
MEME: testing for positive selection in a subset of species

### ISSUE THREAD

**Issue by lyy005** [veg/hyphy#1195]
Dear developers,
I'm using MEME to identify genes that are under episodic positive or diversifying selection, then use the identified genes for functional enrichment analysis later. 

I have about 50 species of interest. A subset (30 species) of the 50 species has a slightly different trait than the rest of the species. I'm interested in the genes that are under positive selection in both 50 species dataset and 30 species dataset. 

I was wondering if the best way is to run MEME on both datasets and then compare the functions enriched in both sets of species? 

Thank you for any suggestions! 

YY

**Comment by stevenweaver** [comment]
Dear @lyy005, 

Have you considered taking a look at Contrast-FEL, or are you specifically testing for episodic selection as opposed to pervasive? Using this method to determine whether a set of genes are undergoing different selective pressure from another may be appropriate.

Please take a look at the *What are the recommended applications?* section and see if it may suit you.
http://hyphy.org/methods/other/contrast-fel/

Best,
Steven

**Comment by spond** [comment]
Dear @lyy005,

We **do not recommend** that you use `MEME` for **gene-level** inference. To quote from the [BUSTED paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4408417/), the method we designed to look for gene-level episodic selection,

> Regrettably, they chose to use a method designed to detect selection at the level of individual sites (MEME; Murrell, Wertheim, et al. 2012) to infer selection on the entire gene—an approach that we cannot recommend. Combining a set of results from individual sites to draw conclusions about a whole gene while controlling the false discovery rate leads to an unavoidable drop in power to detect gene-wide selection, especially when the number of taxa (which drive signal at individual sites) is limited.

Unless you are interested in specific **sites**, you should use `BUSTED` (which now includes [synonymous rate variation](https://academic.oup.com/mbe/article/37/8/2430/5739973) by default, and is it turns out, not including it can increase false positive rates). When you run `BUSTED`, you can also select a subset of branches to include in your analysis, which should address your original question about subsetting the alignment. 

Best,
Sergei

**Comment by lyy005** [comment]
Hi Steven and Sergei,
Thank you for the suggestions from both of you. I'll use BUSTED instead as I'm more interested in the positive selection on the whole gene level. 

Best
YY

**Comment by lyy005** [comment]
Dear Steven and Sergei,
Thank you for the suggestions. I was able to run BUSTED on a small set of genes. And I was using phylotree.js for branch selection for each gene tree. The website is really useful.  

Now I'm expanding the analysis on the bigger data set with 2000 genes. I was wondering what would be the best way to label branches/clades of interest. 

1. Right now I'm replacing the "species names" to "species names{Foreground}" in the nwk file. However, the internal nodes are not labeled. 

2. Alternatively, I'm thinking to just pick the sequences of species of interest and run BUSTED (without background species). 

I was wondering if you think either approach sounds like a solution? Thank you for any suggestions! 

YY

**Comment by spond** [comment]
Dear @lyy005,

You do not want to do this manually for 2,000 genes. Are you designating a **clade** for testing? If your tree can be labeled using regular expressions to find leaves, and then (optionally) internal branches that lead to those leaves, then I have some scripts that do this automatically. Can you provide a few example trees and how you want them labeled?

Best,
Sergei

**Comment by lyy005** [comment]
Dear Sergei,
Thank you so much for your help with this issue. I attached three tree files and a list of the species of interest. The trees are single-copy gene trees. Each species should have no more than one copy of the genes and genes can be missing in several species. The species of interest may not be a monophyletic clade in the gene trees. File 3 would be the ideal labeling for BUSTED analysis, where all the tips and related internal nodes labeled. 

File 1: Original unlabeled gene tree
File 2: Labeled gene tree using regex, where internal nodes are not labeled. 
File 3: Labeled gene tree using phylotree, where internal nodes are also labeled.
File 4: The list of species of interest. 

Thank you! 

YY

[1_GBlocks.aa.fas.treefile.txt](https://github.com/veg/hyphy/files/5082207/1_GBlocks.aa.fas.treefile.txt)
[2_GBlocks.aa.fas.treefile_integripalpia_Auto.txt](https://github.com/veg/hyphy/files/5082208/2_GBlocks.aa.fas.treefile_integripalpia_Auto.txt)
[3_GBlocks.aa.fas.treefile_integripalpia_Manual.txt](https://github.com/veg/hyphy/files/5082209/3_GBlocks.aa.fas.treefile_integripalpia_Manual.txt)
[4_integripalpia.spp.list.txt](https://github.com/veg/hyphy/files/5082210/4_integripalpia.spp.list.txt)

**Comment by spond** [comment]
Dear @lyy005,

Take a look at https://github.com/veg/hyphy-analyses/tree/master/LabelTrees 

Best,
Sergei

**Comment by lyy005** [comment]
Dear Sergei,
Thank you for sharing the program. It works great!  

YY
