### ISSUE TITLE
Relax page error

### ISSUE THREAD

**Issue by iwamaraf** [veg/hyphy#1196]
Hi, I am trying to run relax on datamonkey but I get an error page.

this is the message:

error | "/home/node/datamonkey-js/app/templates/relax/upload_msa.ejs:16\n    14\|             <input id=\"seq-file\" type=\"file\" name=\"files\">\n    15\|             <div id=\"file-progress\" class=\"progress progress-striped active hidden\">\n >> 16\|                 <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"0\" aria-valuemin=\"1\" aria-valuemax=\"100\" style=\"width: <%= hivtrace.percentage_complete %>\">\n    17\|                   <span class=\"sr-only\">0% Complete</span>\n    18\|                 </div>\n    19\|             </div>  \n\nhivtrace is not defined"
-- | --

Thanks,
Rafael

**Comment by stevenweaver** [comment]
Dear @iwamaraf, 

Thank you, I'm resolving now. 

Best,
Steven

**Comment by stevenweaver** [comment]
Dear @iwamaraf, 

The issue should now be resolved. Thank you for bringing this to our attention. 

Best,
Steven

**Comment by iwamaraf** [comment]
Hi,
Sorry to bother again. I am trying to download the log file of my RELAX analysis and I get no response. I can download all other files, the log is the only one that I get an error.

Thanks,

**Comment by stevenweaver** [comment]
Dear @iwamaraf, 

I've reopened the ticket and will look at this shortly. 

Best,
Steven

**Comment by stevenweaver** [comment]
Dear @iwamaraf, 

The issue should now be resolved. Thank you for reporting.

Best,
Steven
