### ISSUE TITLE
Different BUSTED results between two datasets

### ISSUE THREAD

**Issue by lyy005** [veg/hyphy#1202]
Dear hyphy developers, 
I ran BUSTED on two datasets: 
(1) For the first dataset, I ran BUSTED to test for selection on one gene of 10 species. 
(2) For the second dataset, I ran BUSTED on the same gene, but from 64 different species. And I labeled the same 10 species as the first dataset. 

For the first dataset, BUSTED found no evidence of episodic diversifying positive selection with p-value = 0.5000. For the second dataset, BUSTED found evidence of episodic diversifying positive selection with p-value = 0.0064. 

My understanding is that BUSTED does not compare the foreground and background species. It just tests for selection in the foreground (ω > 1), while accounting for the background. So I was wondering if the different BUSTED results between the first dataset and the second dataset are due to the number of species? With more species, BUSTED has more power to detect positive selection? 

Thank you! 

YY

**Comment by spond** [comment]
Dear @lyy005,

>My understanding is that BUSTED does not compare the foreground and background species. It just tests for selection in the foreground (ω > 1), while accounting for the background

That is correct.

>With more species, BUSTED has more power to detect positive selection?

Yes, generally. 

If I understand your example correctly, in (1) you have a **single** foreground branch. How long is the branch? aBSREL might be a better model if you have a **single** specific branch you wish to test for. You can loosely think of the total sum of branch lengths in the "foreground" set (assuming they all have similar selective pressures) as a proxy for power, subject to saturation constraints (i.e. one very long branch is not going to be very informative). If in example (2) you have 10 foreground branches, then the power to detect selection on those will be increased. 

Best,
Sergei

**Comment by lyy005** [comment]
Dear Sergei, 
Thank you so much for your help on this! It's very helpful. I'll check the branch length for sure. 

And sorry about the confusion about my examples. Let me explain the examples again. 

For my example (1), I have 10 species, and I set all of them as the foreground branches. I'm interested in if this gene is under positive selection among all 10 species. And BUSTED found no evidence of episodic diversifying positive selection with p-value = 0.5000.

For my example (2), I have the same 10 species as foreground branches and other 54 species as background branches. BUSTED found evidence of episodic diversifying positive selection with p-value = 0.0064. 

The difference between example (1) and (2) is just without or with the background branches.

**Comment by spond** [comment]
Dear @lyy005,

Thanks for clarifying the example. Your finding **is** interesting, and I am not entirely sure what is going on. Ideally, BUSTED, should return somewhat consistent results. Can you share the JSON result files of both analyses, so I can look into it more?

Best,
Sergei

**Comment by lyy005** [comment]
Dear Sergei,
Please find the two json files from example 1 and 2. I attached .txt to the .json files as GitHub does not allow .json files as attachement. 

Thank you and please feel free to let me know if I can provide any other information. 

YY

[example1_EOG757QBM.lepidoptera.fas.BUSTED.json.txt](https://github.com/veg/hyphy/files/5121682/example1_EOG757QBM.lepidoptera.fas.BUSTED.json.txt)
[example2_EOG757QBM.lepidoptera.json.txt](https://github.com/veg/hyphy/files/5121683/example2_EOG757QBM.lepidoptera.json.txt)

**Comment by spond** [comment]
Dear @lyy005,

Can you repeat the run for the smaller dataset adding `--starting-points 20 --grid-size 500` options to your `HyPhy` command line? The dataset is small (140 sites), and the signal for selection in the larger dataset is driven by 2 sites (if you look at the evidence ratio plots), so I wonder if this might be a convergence issue.

Best,
Sergei

**Comment by lyy005** [comment]
Dear Sergei,
I reran the analysis using --starting-points 20 --grid-size 500 on example 1. I got the same result with p = 0.5000. Here's the json output: 
[EOG757QBM.lepidoptera_run2.json.txt](https://github.com/veg/hyphy/files/5134178/EOG757QBM.lepidoptera_run2.json.txt)

I attached the sequence file here in case it would be useful: 

[example1_EOG757QBM.lepidoptera.aa.fas.nwk.txt](https://github.com/veg/hyphy/files/5134194/example1_EOG757QBM.lepidoptera.aa.fas.nwk.txt)
[example1_EOG757QBM.lepidoptera.fas.txt](https://github.com/veg/hyphy/files/5134195/example1_EOG757QBM.lepidoptera.fas.txt)
[example2_EOG757QBM.GBlocks.fas.txt](https://github.com/veg/hyphy/files/5134196/example2_EOG757QBM.GBlocks.fas.txt)
[example2_EOG757QBM.lepidoptera.nwk.txt](https://github.com/veg/hyphy/files/5134197/example2_EOG757QBM.lepidoptera.nwk.txt)

YY
