### ISSUE TITLE
Unable to run RELAX

### ISSUE THREAD

**Issue by Isabel-ql** [veg/hyphy#1205]
Hi! I cannot run RELAX from yesterday. I've tried several times with different browsers but with the same problem.

The message says "We're sorry, there was an error processing your job. Please try again, or visit our GitHub issues and create an issue if the issue persists".

Is there any way to solve this problem? Thanks!

**Comment by stevenweaver** [comment]
Dear @Isabel-ql, 

Do you have an example url?

Best,
Steven

**Comment by Isabel-ql** [comment]
Hi Steven,

Please see the attached capture of the screen showing such problem. Thanks!

Best,
Qun
[cid:ED713BFF-90FC-43F4-84B6-39628054E4F7]

在 2020年8月25日，14:19，Steven Weaver <notifications@github.com<mailto:notifications@github.com>> 写道：



Dear @Isabel-ql<https://github.com/Isabel-ql>,

Do you have an example url?

Best,
Steven

**Comment by stevenweaver** [comment]
Dear @Isabel-ql, 

The error is here (we currently have a fix in the works to accurately display this to the user when this happens). 

```
Error:
RELAX requires at least one designated set of branches in the tree. in call to assert(XxqUoCMG.option_count>=2, error_msg);
```

Please choose both **TEST** and **REFERENCE** branches. RELAX requires this to infer whether the **TEST** set is under relaxed selection when compared to the **REFERENCE** set.

Best,
Steven

**Comment by Isabel-ql** [comment]
Hi Steven,

Yes! I forgot to set Reference branch. I will rerun the program. Thanks!

Best,
Qun

在 2020年8月25日，15:01，Steven Weaver <notifications@github.com<mailto:notifications@github.com>> 写道：



Dear @Isabel-ql<https://github.com/Isabel-ql>,

The error is here (we currently have a fix in the works to accurately display this to the user when this happens).

Error:
RELAX requires at least one designated set of branches in the tree. in call to assert(XxqUoCMG.option_count>=2, error_msg);


Please choose both TEST and REFERENCE branches. RELAX requires this to infer whether the TEST set is under relaxed selection when compared to the REFERENCE set.

Best,
Steven
