### ISSUE TITLE
Problems for BUSTED

### ISSUE THREAD

**Issue by Isabel-ql** [veg/hyphy#1206]
Hi! I've tried to run BUSTED these days, encountering the sample problem. It happened frequently that the interface disappeared suddenly during the process. Then I checked the Job queue and can't find it. I did receive an email saying it has been completed. But when I clicked the link, I found nothing. I tried with another browser, but the problem continues.

Please see the link: http://datamonkey.org/busted/5f44dc7e34c53e423ae66cf7. 

Does anyone know how to solve this problem?

**Comment by stevenweaver** [comment]
Dear @Isabel-ql, 

This appears to be an issue with the latest hyphy-vision push.

I've rolled back hyphy-vision to version 2.8.6 on the main site, and will notify our developers. You should be able to access results on that page now. 

Best,
Steven

**Comment by Isabel-ql** [comment]
Hi Steven,

Great! I can see the result now. Thanks very much!

Best,
Qun

在 2020年8月25日，14:16，Steven Weaver <notifications@github.com<mailto:notifications@github.com>> 写道：



Dear @Isabel-ql<https://github.com/Isabel-ql>,

This appears to be an issue with the latest hyphy-vision push.

I've rolled back hyphy-vision to version 2.8.6 on the main site, and will notify our developers. You should be able to access results on that page now.

Best,
Steven
