### ISSUE TITLE
SLAC Analysis Log Download Problem

### ISSUE THREAD

**Issue by rzlara** [veg/hyphy#1212]
I keep getting a Bad Gateway 502 error. This had not happened to me before. I tried clearing my cookies/cache, but it did not work. I even tried accessing from another browser/device and it gave me the same error.

**Comment by stevenweaver** [comment]
Dear @rzlara, 

Can you please email me the url you are having trouble with? sweaver@temple.edu.

Best,
Steven

**Comment by stevenweaver** [comment]
Dear @rzlara, 

The issue should now be resolved. 

Thank you,
Steven
