### ISSUE TITLE
FUBAR, not able to dereference

### ISSUE THREAD

**Issue by noahaus** [veg/hyphy#1213]
Hello, I'm trying to get an analysis of 700 bacterial isolates (around 3 Mbp alignment) running to detect positive selection within the alignment. FUBAR seems to be the thing I need to do this task efficiently. I however have an issue that is similar to this one that has already been resolved on the github:

https://github.com/veg/hyphy/issues/898

Is there anyway to adapt this advice to get FUBAR to run well? I need to have specific instructions to tell the office that manages my campus cluster to alleviate this problem

**Comment by spond** [comment]
Dear @noahaus,

Try running 

```
hyphy fubar ENV="USE_MEMORY_SAVING_DATA_STRUCTURES=1e8;" --alignment /path/to/alignment --tree /path/to/tree
```

Best,
Sergei

**Comment by noahaus** [comment]
Sergei, thank you, it seems to now stop whining in my terminal. I will close this after some time passes however, I need to make sure that it is getting passed the error.

**Comment by spond** [comment]
Dear @noahaus,

Sounds good. Also, I presume most of your 3Mb sites are conserved (since these are bacterial isolates)?

Best,
Sergei

**Comment by noahaus** [comment]
Yes, they are _Mycobacterium bovis_ isolates. They should be highly clonal, but I could not reduce the alignment to only the segregating sites since this would make the hyphy fubar say it isn't in a format it expects.

**Comment by noahaus** [comment]
@spond Also, your solution did work, but now I am facing a new issue in that hyphy fubar expects the alignment to be in a particular codon format. So I will close the issue, but if you have any advice on how to fix this error I would be greatly appreciative.

**Comment by spond** [comment]
Dear @noahaus,

Can you clarify what the new issue is?

Best,
Sergei

**Comment by noahaus** [comment]
So I'm using concatenated genes found through pangenome analysis for a core gene alignment (output from Roary). When I use it as input, the new error is this: 

Error:The input alignment must have the number of sites that is divisible by 3 and must not contain stop codons in call to assert(fubar.codon_filter.sites*3==fubar.codon_data.sites, error_msg);

So for this, I just don't know how to solve this easily. 

Thank you in advance for the help.

**Comment by spond** [comment]
Dear @noahaus,

I am not familiar with `Roary`. My first guess would be that each gene has a stop codon at the end of its corresponding alignment; these need to be stripped out prior to `HyPhy` analyses.

Best,
Sergei

**Comment by noahaus** [comment]
I see, thank you greatly!
