### ISSUE TITLE
datamonkey.org web browser having issues displaying trees and further downstream analysis for the last two days! 

### ISSUE THREAD

**Issue by maharanakrish** [veg/hyphy#1217]
Since yesterday BUSTED and other pipelines having issue displaying the initial tree for branch selection and further downstream analysis once you upload the data file. 

It worked perfectly allright earlier with the same data file.

![Screen Shot 2020-09-06 at 2 44 08 PM](https://user-images.githubusercontent.com/70858913/92333026-2068a400-f050-11ea-89e0-b1d98ea819a1.png)
![Screen Shot 2020-09-06 at 2 43 31 PM](https://user-images.githubusercontent.com/70858913/92333027-22326780-f050-11ea-8346-c4e378d8c7eb.png)

**Comment by stevenweaver** [comment]
Dear @maharanakrish, 

Thank you for reporting, will review issue shortly. 

Best,
Steven

**Comment by stevenweaver** [comment]
Dear @maharanakrish, 

After restarting the web process, it seems to be working now. Can you give another try?

Best,
Steven

**Comment by maharanakrish** [comment]
Yayyyyy!

 It works! 

Thank you and have a great labor day weekend!

**Comment by stevenweaver** [comment]
You're welcome and to you as well. 

Best,
Steven
