### ISSUE TITLE
GARD datamonkey stalled job-part of issue #1214

### ISSUE THREAD

**Issue by No-drama-llama** [veg/hyphy#1218]
Hi,

I am running one analysis on the datamonkey server-GARD, with 60 protein sequences and 341 sites (http://www.datamonkey.org/gard/5f501b5a611379489328f114) that has been running for the past few days and it is always in the same step: "Performing multi breakpoint analysis using a genetic algorithm". Now the job has been removed from the job queue. GARD stops at "Performing multi breakpoint analysis using a genetic algorithm" with this alignment file when run locally too. I have no idea what the problem is.

The other analysis has 68 sequences and 3087 sites but it always gives me an error on the server (http://datamonkey.org/gard/5f574f3cdc5d1378a56076eb). When I tried running it locally I get this error:
"### Performing an exhaustive single breakpoint analysis
Error:
Invalid distance matrix passed to NeighborJoin.". 
I am not sure what the problem is since I specify "--type amino-acid" and it reads it correctly. I have used the same alignment for various other phylogenetic analyses and it hasn't been giving me any problems.

I am kinda stuck, so any help is welcome. Thank you in advance!

Best,
Anamarija

**Comment by spond** [comment]
Dear @No-drama-llama,

Let me take a look...

Best,
Sergei

**Comment by No-drama-llama** [comment]
Thank you!

**Comment by stevenweaver** [comment]
Dear @No-drama-llama, 

Datamonkey suffered a service outage this past weekend, so jobs that were running was not able to be marked as complete. 

The results for the first job are here : http://data.hyphy.org/web/datamonkey/5f501b5a611379489328f114/

Please let me know when you receive them so I can delete from this temporary location.

Best,
Steven

**Comment by No-drama-llama** [comment]
Dear Steven,

I got the results, you can delete them. Thanks again! 

Did you have any luck with the other job?

Best,
Anamarija

**Comment by stevenweaver** [comment]
Dear @No-drama-llama,

If you click `Download Log` (http://datamonkey.org/gard/5f574f3cdc5d1378a56076eb/log.txt), you can see what happened. 
I'm rerunning the job now to see if this was an environment issue with our cluster. 

Best,
Steven

**Comment by No-drama-llama** [comment]
Dear Steven,

Yea I kept getting the same message on a local GARD run. Thank you for the effort :) 

Best,
Anamarija

**Comment by stevenweaver** [comment]
Dear @No-drama-llama, 

I was able to replicate the error outside of datamonkey, so it is an issue with Likelihood optimization in HyPhy. I will investigate the dataset shortly. 

Best,
Steven

**Comment by No-drama-llama** [comment]
Dear Steven,

Did you manage to resolve anything about this Likelihood optimization problem in HyPhy? 

Thank you for trying, I know you must be really busy!

Best,
Anamarija

**Comment by spond** [comment]
Dear @No-drama-llama,

Stay tuned; I was able to replicate the error, trying to understand what's causing it.

Best,
Sergei

**Comment by No-drama-llama** [comment]
Dear Sergei,

OK, thank you for letting me know. Hope it doesn't give you too much trouble.

Best,
Anamarija

**Comment by spond** [comment]
Dear @No-drama-llama,

The resolution is in the `develop` branch.

Best,
Sergei

**Comment by No-drama-llama** [comment]
Dear  Sergei,

Thank you so much. I will give it a try now.

Best,
Anamarija

**Comment by No-drama-llama** [comment]
Dear Sergei and Steven,

I managed to analyse my sequences and get results without a problem. Thank you so much for your help and keep up the good work!

Best,
Anamarija
