### ISSUE TITLE
REL analysis

### ISSUE THREAD

**Issue by mdbohorqueza** [veg/hyphy#1220]
Hello:
I would like to run REL analysis. This was available on classic datamonkey, where I used to run all FEL, IFEL, SLAC, FUBAR, MEME, REL and others. I suppose classic server is being left without support or something like that, but there are some features not available on the new server, such as Integrative analysis and that SLAC FEL IFEL or FUBAR are completely unable to be run now (months before they were available). Well I could manage to go through this with the new server, but REL and other anaysis are not available but in the classic. Is there any solution to this, or why some analysis were left from the new server. Are they obsolete at present?
Thank you so much.

**Comment by spond** [comment]
Dear @mdbohorqueza,

REL has been deprecated. Use FUBAR or MEME instead for site level selection, and BUSTED to infer rate distributions. 
IFEL is now a part of FEL (just select internal branches when you start the analysis).

Take a look at http://www.hyphy.org/resources/tutorial-2017.pdf for our recent recommendations.

Best,
Sergei
