### ISSUE TITLE
Confusing error

### ISSUE THREAD

**Issue by vinjlynch** [veg/hyphy#1221]
Hi All, 

I am teaching myself how to use HyPhy (2.5.18) from the command line. I can set up an aBSREL run using the ./hyphy asbrel command, however, when I try to get more specific and use 

/hyphy absrel - Universal -alignment p53.fasta -tree tree.nwk - Foreground - Double+Triple - y

I get this error message:

- __Analysis Version__: 2.2

Universal

-------
>[WARNING] This dataset contains 14 duplicate sequences. Identical
sequences do not contribute any information to the analysis and only
slow down computation. Please consider removing duplicate or 'nearly'
duplicate sequences, e.g. using
https://github.com/veg/hyphy-analyses/tree/master/remove-duplicates
prior to running selection analyses
-------

>Loaded a multiple sequence alignment with **261** sequences, **294** codons, and **1** partitions from `/Users/Vinny/Downloads/hyphy-2.5.18.hf1/p53.fasta`
Foreground
Double+Triple

### Obtaining branch lengths and nucleotide substitution biases under the nucleotide GTR model
Error:
Ran out of input in buffer during a redirected standard input read. in call to ChoiceList(selection, description, 1, NO_SKIP, option_set);

Function call stack
1 :  [namespace = _EqYqPhb] ChoiceList(selection, description, 1, NO_SKIP, option_set);
	Standard input redirect:
		Empty Associative List
-------
2 :  [namespace = absrel] kill0=io.SelectAnOption({"Yes":"Automatically delete internal zero-length branches for computational efficiency (will not affect results otherwise)","No":"Keep all branches"},"The set of properties to use in the model")=="Yes";
-------
3 :  [namespace = absrel] doGTR("absrel");
-------
4 :  namespace 

Step 0.doGTR("absrel");;
-------

I can interpret this as the alignment and tree are loaded, the universal genetic code selected, and the Double+Triple hit model selected. I can make the error go away if I add a - Yes.

Question 1: What exactly have I done, new data on the screen suggests I have either told asbrel to obtain branch lengths with nucleotide GTR or told asbrel to delete zero-length internal branches???

Question 2: I would like to run aBSREL on many genes using a single phylogeny with the same {Foreground}. Following the "Automating analyses" suggestion from the tutorial I have made this loop (I suspect there are better ways to do this, but I am new at writing scripts):

# Path to files of interest
FILEPATH=/Users/Vinny/Desktop/MammalianAlignments/test/

# Run aBSREL on all files $FILEPATH/*.fasta
for FILE in `ls $FILEPATH/*.fasta`; do
    echo "Running aBSREL on $FILE"
    echo `(echo "1"; echo "6"; echo $FILE; echo /Users/Vinny/Desktop/MammalianAlignments/test/tree.nwk; echo Foreground; echo Double+Triple; echo Yes) |./hyphy`
done

This should work right?

Thanks!
Vinny

**Comment by spond** [comment]
Dear @vinjlynch,

Include keyword style arguments.

```
$hyphy absrel --help

Available analysis command line options
---------------------------------------
Use --option VALUE syntax to invoke
If a [reqired] option is not provided on the command line, the analysis will prompt for its value
[conditionally required] options may or not be required based on the values of other options

code
	Which genetic code should be used
	default value: Universal

alignment [required]
	An in-frame codon alignment in one of the formats supported by HyPhy

tree [conditionally required]
	A phylogenetic tree (optionally annotated with {})
	applies to: Please select a tree file for the data:

branches
	Branches to test
	default value: All

multiple-hits
	Include support for multiple nucleotide substitutions
	default value: None

output
	Write the resulting JSON to this file (default is to save to the same path as the alignment file + 'ABSREL.json')
	default value: absrel.codon_data_info[terms.json.json] [computed at run time]

```


```
/hyphy absrel --code Universal --alignment p53.fasta --tree tree.nwk --branches Foreground --multiple-hits Double+Triple 
```

Best,
Sergei

**Comment by vinjlynch** [comment]
Ah, thanks! This makes sense. Now to simplify my loop :-)

**Comment by vinjlynch** [comment]
Ah, thanks! This makes sense. Now to simplify my loop :-)

**Comment by vinjlynch** [comment]
Ah, thanks! This makes sense. Now to figure out how to simplify my loop. Learning new skills is fun :-)

Vinny
