### ISSUE TITLE
aBSREL: Question regarding genes belong to node under episodic diversifying selection 

### ISSUE THREAD

**Issue by venuraherath** [veg/hyphy#1224]
Hi Dr. Pond and the Team,

Thank you for making these awesome tools accessible to the scientific community via the Datamonkey server.
I have a question regarding the output received for 5f46c7ee34c53e423ae6c264.
I wonder why the node 48 is showing evidence of episodic diversifying selection while genes belonging to the node are not showing the same. When a branch is found to be positive for the test shouldn't genes belonging to it also be positive?
I appreciate if you can shed some light on this  

Thank you.
Venura

**Comment by spond** [comment]
Dear @venuraherath,

There is no expectation that if an internal branch is found to be under selection, then its descendants will also be found under selection. For example, you can have episodic selection occurring at an internal branch followed by neutral evolution or negative selection. This is actually quite common.

Also, your sequences are either too divergent or aligned improperly, it seems. Infinite branch lengths are a good indicator of this, and looking at the alignment reveals very low homology. I would check that before proceeding.

Best,
Sergei

![alignment](https://user-images.githubusercontent.com/1018513/94011598-9faae700-fd75-11ea-9b01-ba1365893347.png)

**Comment by venuraherath** [comment]
Thank you for the Clarification Dr. Pond.
Prob this is a stupid question (about the low homology), is there a workaround (like using TrimAl or Guidence) so I still can get meaningful data out from the analysis? 
About the dataset - This dataset represents the bZIP gene family in potato. 
Thank you,
Venura
