### ISSUE TITLE
aBSREL: no output for some calculation

### ISSUE THREAD

**Issue by hongzhonglu** [veg/hyphy#1227]
Dear  Sergei @spond,
Recently I am trying to use aBSREL to do the positive selection in large scale. I found in some cases I get nothing from aBSREL. This is the data I used as input.
[absrel_need_check.zip](https://github.com/veg/hyphy/files/5304209/absrel_need_check.zip)

This is the script I used for the calculation:
mpirun -np 20 HYPHYMPI LIBPATH=/cephyr/users/luho/Hebbe/hyphy/res/ /cephyr/users/luho/Hebbe/hyphy/res/TemplateBatchFiles/SelectionAnalyses/aBSREL.bf --alignment /cephyr/users/luho/Hebbe/cds_align_guidance_new/OG5595_code.fasta --tree /cephyr/users/luho/Hebbe/cds_align_guidance_new_tree_unroot_label/OG5595_aa_unroot_LABEL.tre --branches Foreground --output /cephyr/users/luho/Hebbe/absrel_result/OG5595.ABSREL.json

Could you help to check it? Thanks very much.

**Comment by hongzhonglu** [comment]
It seems that hyphy v2.52 could give the right output while the hyphy v2.58 can't get any result. I will further check it.

**Comment by hongzhonglu** [comment]
However until now only v2.5.8 could be installed in the cluster of our school. So it is a pity that i can't test the latest version now.

**Comment by spond** [comment]
Dear @hongzhonglu,

The current development version (will be released as 2.5.19 today) runs the analysis without any issues. Result file attached.

Best,
Sergei

[OG5595_code.fasta.ABSREL.json.zip](https://github.com/veg/hyphy/files/5334253/OG5595_code.fasta.ABSREL.json.zip)

**Comment by hongzhonglu** [comment]
Dear Sergei,
Thanks lot! Will try the new version.


Best regards,
Hongzhong
