### ISSUE TITLE
ASRs?

### ISSUE THREAD

**Issue by vinjlynch** [veg/hyphy#1228]
Hi All,

In the past I have used the "classic" datamonkey website to do ancestral state reconstructions, but it is no longer an option and the new website doesn't have an ASR option. Is there a tutorial on how to do ASRs in HyPhy 2.5.18? 

Thanks
Vinny

**Comment by spond** [comment]
Dear @vinjlynch,

Take a look at https://github.com/veg/hyphy-analyses/tree/master/AncestralSequences

Many analyses (e.g BUSTED, aBSREL) have the option to save a `fit` file, which you can then feed to the ancestral sequence tool. Let me know if that works for you. Do you want to reconstruct **all** sequences or estimate a particular one?

Best,
Sergei

**Comment by vinjlynch** [comment]
Will give it a try, is there an option for protein alignments? We’re not interested in all ASRs but a subset > 1.


Best,
Vinny


Vincent J. Lynch, Ph.D.
Assistant Professor
Department of Biological Sciences
University at Buffalo, SUNY
551 Cooke Hall
Buffalo NY, 14260

vjlynch@buffalo.edu<mailto:vjlynch@buffalo.edu>

“... the most useful thing we can do is to repudiate, and so we repudiate” – I. Turgenev, Fathers and Sons (1862)

"There is a grandeur in this view of life, with its several powers,
having been originally breathed into a few forms or into one; and that
whilst this planet has gone on cycling according to the fixed laws of
gravity, from so simple a beginning endless forms most beautiful and most
wonderful have been, and are being, evolved.” – C. Darwin, On The Origin of Species (1859)

On Oct 1, 2020, at 1:35 PM, Sergei Pond <notifications@github.com<mailto:notifications@github.com>> wrote:



Dear @vinjlynch<https://github.com/vinjlynch>,

Take a look at https://github.com/veg/hyphy-analyses/tree/master/AncestralSequences

Many analyses (e.g BUSTED, aBSREL) have the option to save a fit file, which you can then feed to the ancestral sequence tool. Let me know if that works for you. Do you want to reconstruct all sequences or estimate a particular one?

Best,
Sergei

**Comment by spond** [comment]
Dear @vinjlynch,

What does your workflow look like? I can point you to the right analysis settings.

Best,
Sergei

**Comment by vinjlynch** [comment]
We actually haven’t established one yet, other than working on AA alignments so suggestions would be welcome.


Best,
Vinny


Vincent J. Lynch, Ph.D.
Assistant Professor
Department of Biological Sciences
University at Buffalo, SUNY
551 Cooke Hall
Buffalo NY, 14260

vjlynch@buffalo.edu<mailto:vjlynch@buffalo.edu>

“... the most useful thing we can do is to repudiate, and so we repudiate” – I. Turgenev, Fathers and Sons (1862)

"There is a grandeur in this view of life, with its several powers,
having been originally breathed into a few forms or into one; and that
whilst this planet has gone on cycling according to the fixed laws of
gravity, from so simple a beginning endless forms most beautiful and most
wonderful have been, and are being, evolved.” – C. Darwin, On The Origin of Species (1859)

On Oct 1, 2020, at 4:16 PM, Sergei Pond <notifications@github.com<mailto:notifications@github.com>> wrote:



Dear @vinjlynch<https://github.com/vinjlynch>,

What does your workflow look like? I can point you to the right analysis settings.

Best,
Sergei
