### ISSUE TITLE
GARD/FUBAR issues mid-analysis

### ISSUE THREAD

**Issue by samimmunology** [veg/hyphy#1229]
I've been trying to analyze a nucleotide alignment here and it works on the classic server, but when I upload and try to analyze with FUBAR, it keeps bringing up an issue. Is there some bug with the program?

**Comment by spond** [comment]
Dear @samimmunology,

If I understand you correctly, you have an alignment that runs through [classic.datamonkey.org](classic.datamonkey.org) but fails on [www.datamonkey.org](www.datamonkey.org)?

There's always a possibility that a new bug exists in `www.datamonkey.org`, but a more likely scenario is a change in analysis settings/requirements.

In order for us to help you diagnose the issue, we need some details about what happened, for example, the link to the datamonkey error page.

Best,
Sergei
