### ISSUE TITLE
HYPHY 2.5.17 : Discordant results of SLAC and FEL

### ISSUE THREAD

**Issue by lokdeep1993** [veg/hyphy#1232]
Hi,
I am using HYPHY 2.5.17 on my local system to run SLAC and FEL. I ran the program using config file by providing a codon alignment file and a tree. Upon checking the results, I found that there are no common positively selected sites between the programs i.e. the sites reported as positively selected by SLAC are not reported in FEL output and vice versa. I used cut off of P < 0.05 for my analysis. Furthermore, in few occasions, site detected as significantly positive by FEL is reported as under purifying selection by SLAC. The number of sites common between the programs are also very less. Please suggest me something to fix this.
Thank You!

**Comment by spond** [comment]
Dear @lokdeep1993,

Can you provide details of the analysis? It is impossible for me to provide meaningful feedback without seeing what the discordances are like. `.json` files from SLAC and FEL would be very useful here.

Best,
Sergei

**Comment by lokdeep1993** [comment]
Hello Sergei,
Thank you for a quick reply.
Please find the attached json files in the compressed folder.
I want to mention that codon site 4 is detected as under negative selection by SLAC but under positive selection by FEL.
[jsonfiles.zip](https://github.com/veg/hyphy/files/5371625/jsonfiles.zip)

**Comment by spond** [comment]
Dear @lokdeep1993,

SLAC results look very suspect. It seems that the branch lengths in the tree were not optimized correctly (if you look at the tree in SLAC, it has infinite branch lengths). Can you try running the same file through HyPhy v 2.5.20 (current release) to see if the issue persists? 

Best,
Sergei

**Comment by lokdeep1993** [comment]
Sure,
I will run the programs using HyPhy v 2.5.20 and inform accordingly. Once again, thank you for a quick reply!

**Comment by spond** [comment]
Dear @lokdeep1993,

Thanks for reporting this issue. I've spent the last few weeks implementing major updates to some of the key function in HyPhy to make it run considerably faster. While these updates passed our internal tests, it seems that some issues were not caught in testing.

Would you be willing to share the alignment and analysis options with me so that I can debug the issue and provide a fix?

Best,
Sergei

**Comment by lokdeep1993** [comment]
Hello @spond 
Yes, I can share the files. Can you please provide a private link to share the files? I cannot put the files here as this work is still in progress. I hope you understand.
Thank you!
P.S.
The command used was:
`hyphy absrel --alignment "$file" --tree "$tree" --branches fore --output absrel_json_files/"$file"_absrel.json > hyphy/absrel/"$file"_absrel.txt`

I also want to mention that I encountered the same issue while running other programs like MEME, SLAC, FEL also.

**Comment by spond** [comment]
Dear @lokdeep1993,

Please use https://www.dropbox.com/request/AThxqVCKvltTDDgqMbdK (the link will expire in 3 hours and the files will only be viewable by me).

Best,
Sergei

**Comment by lokdeep1993** [comment]
Dear @spond 
I have uploaded the files. I also want to mention that in initial versions of HyPhy, we were able to provide a config file as input to the program by labelling foreground species with "{Foreground}", but now, this is working only in RELAX. In other programs like SLAC, FEL, aBSREL and MEME, newer versions start the test on "branch -> All"  even if the branches are labelled and if we provide through a config file. We have to mention in the command line using:
`hyphy absrel --alignment "$file" --tree "$tree" --branches Foreground`

**Comment by spond** [comment]
Dear @lokdeep1993,

Thank for sending the files! I'm looking at them now, but can't replicate the issue locally. Can you tell me what OS and CPU you are running HyPhy on, and which compiler you used to build the executable (`gcc --version`)?

Best,
Sergei

**Comment by spond** [comment]
Dear @lokdeep1993,

> I have uploaded the files. I also want to mention that in initial versions of HyPhy, we were able to provide a config file as input to the program by labelling foreground species with "{Foreground}", but now, this is working only in RELAX. In other programs like SLAC, FEL, aBSREL and MEME, newer versions start the test on "branch -> All" even if the branches are labelled and if we provide through a config file. We have to mention in the command line using:
> `hyphy absrel --alignment "$file" --tree "$tree" --branches Foreground`

This is the new behavior (going back to version 2.4.xx): arguments are supplied explicitly on the command line as keywords. You should be able to use old config files if you supply the `-i` (force interactive) flag on the command line (`hyphy -I`); let me know if that works.

Best,
Sergei

**Comment by lokdeep1993** [comment]
Dear @spond 
OS: **UBUNTU 18.04.3 LTS (Bionic Beaver)**
GCC: **gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0**
CPU: model name      : **Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz**
I want to mention that now I am running aBSREL with HyPhy v 2.5.17 and I am not getting the error anymore.

P.S.
Thank you for informing me about `-i` argument. I generally used to pass the config file like:
`echo -e ""1\n1" > meme_conffiles/"$file"_meme_conf`
`echo "$dir/$file" >> meme_conffiles/"$file"_meme_conf`
`echo "$dir/$gene".tree >> meme_conffiles/"$file"_meme_conf`

and the passing it to HyPhy using:
`hyphy < "$file"_meme_conf > output.txt`

**Comment by lokdeep1993** [comment]
Dear @spond 
That indeed is strange. In every program (MEME, SLAC, FEL, aBSREL), I got around 8-10 such files from each program out of 280 files for each program for HyPHY v 2.5.19. The error is same as I mentioned above and the JSON files for these outputs are completely empty (0Bytes). I want to mention that I was running multiple hyphy jobs parallelly. Can that effect it in any possible way? I am not sure, just a wild guess.

**Comment by spond** [comment]
Dear @lokdeep1993,

I don't think that running the jobs in parallel is what is causing the issue.

Best,
Sergei

**Comment by spond** [comment]
Dear @lokdeep1993,

Would you please try your analysis with `2.5.20` (released yesterday)?

Best,
Sergei
