### ISSUE TITLE
FUBAR: Internal Error 

### ISSUE THREAD

**Issue by jzehr** [veg/hyphy#1233]
Using hyphy ```2.5.19```, I have attached error message to this issue.

![Screen Shot 2020-10-13 at 12 08 56 PM](https://user-images.githubusercontent.com/38324371/95888865-a5319680-0d4f-11eb-88c0-9706b1c5c189.png)

**Comment by spond** [comment]
Dear @jzehr,

Could you please attach the source data files and analysis settings to complete this issue report?

Best,
Sergei

**Comment by jzehr** [comment]
Dear @spond,

I am running on the server in this dir: ```/data/shares/veg/SARS-CoV-2/coronavirus-comparative``` 

Command: ```mpirun -np 16 hyphy-develop/HYPHYMPI LIBPATH=/data/shares/veg/SARS-CoV-2/coronavirus-comparative/hyphy-develop/res hyphy-develop/res/TemplateBatchFiles/SelectionAnalyses/FUBAR.bf --alignment /data/shares/veg/SARS-CoV-2/coronavirus-comparative-data/data/catted/SARS2_ORF1a.catted.qa.fasta_protein.aligned.compressed.codon.fas --tree /data/shares/veg/SARS-CoV-2/coronavirus-comparative-data/data/catted/SARS2_ORF1a.catted.qa.fasta_protein.aligned.compressed.codon.fas.tree --grid 50 --chains 10 --chain-length 10000000 --burn-in 1000000 --output /data/shares/veg/SARS-CoV-2/coronavirus-comparative data/data/catted/SARS2_ORF1a.catted.qa.fasta_protein.aligned.compressed.codon.fas.FUBAR.json``` 

I have attached a zip file with the codon aware MSA along with the tree file
[SARS2_ORF1a_data.zip](https://github.com/veg/hyphy/files/5373528/SARS2_ORF1a_data.zip)
