### ISSUE TITLE
datamonkey.org aBSREL error

### ISSUE THREAD

**Issue by Praeda** [veg/hyphy#1234]
Hi,

I've repeatedly received the error message "Primary job  terminated normally, but 1 process returned a non-zero exit code. Per user-direction, the job has been aborted." when trying to run aBSREL at datamonkey.org today using a variety of input files. Branch selection works fine, and the job is listed in the queue for a few minutes. Other methods don't have the same problem - both BUSTED and RELAX work properly with the same input files.

If you think it's likely that the files I'm using are relevant to the error, I can provide them.

**Comment by spond** [comment]
Dear @Praeda,

We will look into this. Could you include the URL for one of the failed job runs?

Best,
Sergei

**Comment by jzehr** [comment]
Dear @spond,

I can replicate this error on [Datamonkey.org](http://www.datamonkey.org/absrel) using: [test_data.zip](https://github.com/veg/hyphy/files/5378429/test_data.zip). 

I ran using ```Universal code```, selected a few random branches and then received the error message above.

Here is the job [url](http://www.datamonkey.org/absrel/5f86faac9adf224520fa4920).

Best,
Jordan

**Comment by stephenshank** [comment]
Dear @Praeda,

I believe I've traced this down to a system administration issue on our end, which should now be resolved. Can you please try again? If you're able to provide a URL to the job page, I'll be able to track the progress of your job.

Best,
Stephen

**Comment by Praeda** [comment]
Yes, that's done the trick. The URL is [here](http://datamonkey.org/absrel/5f8776359adf224520fa5cb4), if you'd still like to check anything. Sorry for the delay in responding, and thanks for everyone's help!

**Comment by stephenshank** [comment]
You're quite welcome! And thanks for reporting the issue, it's very helpful to us.
