### ISSUE TITLE
Interpreting RELAX results 

### ISSUE THREAD

**Issue by skaul31** [veg/hyphy#1237]
Hello, 

I recently ran RELAX for a gene of interest that I have been working with. I have a set of 27 sequences in the alignment (I am working with Caenorhabditis species). One of the branches was set as the test and the rest were reference. When I look at the results in the json file I get the following in the test results section: 

"test results": {
    "LRT": 25.48288556428452,
    "p-value": 4.463245889541056e-7,
    "relaxation or intensification parameter": 1

I am unsure about interpreting a K value equal to 1 as I am still new to these analyses. The K value inferred from the general descriptive model is 4.84624663643133. Does a K value equal to 1 indicate no evidence of selection relaxation or intensification? What would K=1 mean in terms of the small p-value I have here? 

Thank you for your help!

**Comment by spond** [comment]
Dear @skaul31,

This does not look normal. `"relaxation or intensification parameter" : 1` cannot result in a significant p-value. Can you paste in the output of the RELAX run for this dataset? That might be more informative for diagnosing what went wrong. 

Best,
Sergei

**Comment by spond** [comment]
Dear @skaul31,

It definitely appears like the previous result is due to a bug. The log you sent makes more sense; can you attach the complete `json` from the Datamonkey run for comparsion?

Best,
Sergei

**Comment by skaul31** [comment]
Sure! I am attaching the two json files zipped since GitHub will not allow me to upload them as json. The one named par2RELAX10.21 is the rerun that gave a k-value of 0.814. Thank you for your help!

[par2RELAX9.21.zip](https://github.com/veg/hyphy/files/5418119/par2RELAX9.21.zip)
[par2RELAX10.21.zip](https://github.com/veg/hyphy/files/5418120/par2RELAX10.21.zip)

**Comment by spond** [comment]
Dear @skaul31,

The 9/21 run seems to have experienced a convergence issues (the &omega; distribution and many branch lengths had near infinite values). This sometimes happens with RELAX; which version of HyPhy did you use to run the 10/21 analysis?

Best,
Sergei

**Comment by skaul31** [comment]
The analysis version is 3.1.1 in the 10/21 log and json file. I used Datamonkey for the 10/21 analysis as well.

**Comment by spond** [comment]
Dear @skaul31,

Got it thanks. Datamonkey moved up a few versions of HyPhy (which is different from the analysis version), so some differences are expected. Would you be comfortable with sharing the datamonkey job link so that I can take a look at the data a bit more?

Best,
Sergei

**Comment by skaul31** [comment]
Ahh I see. I don't mind sharing the datamonkey job link at all. Would the link to the summary tab for the most recent RELAX run work? (https://www.datamonkey.org/relax/5f906e49ca624b1a8ce302cd#summary-tab) If there is a different way to share the job link please let me know and I will send the link as you need. Thank you!

**Comment by spond** [comment]
Dear @skaul31,

I noted that in your analysis the `Test` set has a single branch. This is one of the "canonical" situations when RELAX can have convergence problems, since the sample size is effectively *1* there. We generally **do not** recommend using a test (or reference) sets that contain one branch. The sequences also appear fairly divergent (lots of gaps as well); this makes inference even harder.

If you download the analysis log (under the `Export` button), there is a  warning to that effect 

```
### * Potential convergence issues due to flat likelihood surfaces; checking to see whether K > 1 or K < 1 is robustly inferred
```

Hopefully this is helpful,
Sergei

**Comment by skaul31** [comment]
I see. That does make sense, thank you! What would be an appropriate sample size to use for the test or reference branches? We were initially hoping to focus on one branch but if that is not appropriate then I was wondering how many branches should be included in the test set.

**Comment by spond** [comment]
Dear @skaul31,

There's no hard cutoff, but fitting a 3-rate distribution to a single branch may be a stretch. I would say 3-5 branches is probably a good lower bound, but of course that depends on your application.

Best,
Sergei

**Comment by skaul31** [comment]
That makes sense. Thank you for your help!
