### ISSUE TITLE
datamonkey.org job submit error: [object Object]

### ISSUE THREAD

**Issue by nmathers** [veg/hyphy#1238]
I received a pop up error reading: [object Object] when attempting to submit both BUSTED and aBSREL jobs on the datamonkey.org server. I tried an old input file I have run on the server before without an issue and the error was reproduced.

Thanks for any help.

Nick @ University of Wisconsin

**Comment by spond** [comment]
Dear @nmathers,

Did you receive a job ID, i.e. at what stage did the error occur?

Best,
Sergei

**Comment by nmathers** [comment]
The error occurred when attempting to submit the job (tried both Chrome and Firefox) and no job ID was initiated.

**Comment by stevenweaver** [comment]
Dear @nmathers, 

The issue is resolved. 

Best,
Steven

**Comment by nmathers** [comment]
Great, thank you!
