### ISSUE TITLE
Question: How the dN/dS value is estimated. 

### ISSUE THREAD

**Issue by Isaac1293** [veg/hyphy#1244]
Dear HyPhy community, I'm trying to perform a selection test in a sequence-set of an argonaute protein, comparing parasites and free-living organisms. I wondering if this argonaute is under diversifying selection.
I'm a complete noob in selection tests, so before trying any test such as aBSREL or BUSTED I need to figure out how dN/dS is estimated in-branch selection tests. In my knowledge when pairwise dN/dS is estimated, this value belongs to the comparison, not for an individual sequence. However in a multiple alignment context, I do not have any clue how dN/dS is estimated, is it a mean value of the dN/dS of one sequence vs all?

I’ll really appreciate your support regarding this.

Regards

**Comment by spond** [comment]
Dear @Isaac1293,

In a multiple sequence alignment, most methods implemented in HyPhy/Datamonkey will estimate dN/dS directly as a model parameter in the substitution process model. This will use information from **all** sequences and properly account for their relatedness in the tree. It is **not** estimated from pairwise comparisons of sequences.

Take a look at the first 10-15 pages of http://www.hyphy.org/resources/hyphybook2007.pdf for an introduction. 

Best,
Sergei
