### ISSUE TITLE
aBRSEL error command line 

### ISSUE THREAD

**Issue by dianamosa** [veg/hyphy#1245]
Hello,

I am performing several hyphy analysis with aBRSEL in multiple alignments. For some of them I got the following error:

Error:
UhSiqviG.tree_0.SSCR.omega2 evaluated to a NaN; this can cause all kinds of odd behavior downstream, therefore it is safer to quit now

Function call stack
1 :  Optimize(absrel.null.mles, ^absrel.likelihood_function_id);

-------
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[744,1],4]
  Exit code:    1
--------------------------------------------------------------------------

The analysis are being performed via command line, many of them terminated succesfully but for some I got similar errors. However, I cannot understand which is the issue. Could you please guide me trough this?

Thank you, 

Diana M.

**Comment by spond** [comment]
Dear @dianamosa,

Could you provide an example (alignment + run settings) for me to replicate the issue, please? There's something abnormal occurring with those alignments.

Best.
Sergei

**Comment by dianamosa** [comment]
Dear @spond 
Thank you for your quick response, I am attaching my files. Files are in phylip and newick format, but I had to change it to txt to upload them. 
The command I am using is:

mpiexec -n 5 hyphy absrel --alignment OG0010014_codeml_aln.phy --tree OG0010014'_tree_hyphy.newick --output OG0010014_output.absrel

[OG0010014_codeml_aln.txt](https://github.com/veg/hyphy/files/5518668/OG0010014_codeml_aln.txt)

[OG0010014_tree_hyphy.txt](https://github.com/veg/hyphy/files/5518674/OG0010014_tree_hyphy.txt)

**Comment by spond** [comment]
Dear @spond,

Let me check. One quick note: if you are using `MPI` make sure you call `HYPHYMPI` not `hyphy` -- the latter is **not** MPI-enabled.

Best,
Sergei

**Comment by spond** [comment]
Dear @dianamosa,

I am not able to recreate the error with the current version (2.5.21). The analysis runs to completion, both with and without MPI. Can you confirm which HyPhy version you are using (`hyphy --version`)?

Best,
Sergei

```
### Adaptive branch site random effects likelihood test 
Likelihood ratio test for episodic diversifying positive selection at Holm-Bonferroni corrected _p =   0.0500_ found **2** branches under selection among **73** tested.

* TBRA, p-value =  0.00000
* LYER, p-value =  0.01288
```

Best,
Sergei

**Comment by dianamosa** [comment]
I am using version 2.5.14, I will update it then.
Thank you for your support

**Comment by dianamosa** [comment]
Just to update, the new version ran properly. Thank you for your assitance.
