### ISSUE TITLE
Error when running CleanStopCodons.bf: syntax error near unexpected token `{'

### ISSUE THREAD

**Issue by mbarkdull** [veg/hyphy#1246]
Hi all, 

I am attempting to run Busted on my dataset; however, my sequences all end with a stop codon. I'd like to use `CleanStopCodons.bf ` to remove those stop codons. When I attempt to run `CleanStopCodons.bf` on my data, I get the error message:

```
/workdir/mb2337/FormicidaeMolecularEvolution/hyphy/res/TemplateBatchFiles/CleanStopCodons.bf: line 1: syntax error near unexpected token `{'
/workdir/mb2337/FormicidaeMolecularEvolution/hyphy/res/TemplateBatchFiles/CleanStopCodons.bf: line 1: `if (onlyFilterSequenceNames != 1) {'
```

So far, I've tried using `dos2unix` and `mac2unix` on `CleanStopCodons.bf`, in case this is an issue with end of line characters. This did not resolve the problem. 

I'm working on a machine running CentOS Linux release 7.6.1810. 

Thank you so much for the help!

**Comment by stevenweaver** [comment]
Dear @mbarkdull, 

How are you calling CleanStopCodons.bf?

Something like
```
(echo 1; echo /Users/sweaver/Programming/hyphy/HIV_RT.nex; echo 1) | ./hyphy res/TemplateBatchFiles/CleanStopCodons.bf 
```

Best,
Steven

**Comment by mbarkdull** [comment]
Ah- I'm not used to the syntax for running commands in HyPhy. Your command worked for me as well- thank you so much!

Megan

**Comment by spond** [comment]
Dear @mbarkdull,

I might suggest that instead of removing stop codons (which can mask alignment issues), you confirm that the alignment you made is codon-aware (e.g. see https://github.com/veg/hyphy-analyses/tree/master/codon-msa).

@stevenweaver made a good suggestion; you can further simplify the syntax by using something like 

```
./hyphy cln Universal /Users/sweaver/Programming/hyphy/HIV_RT.nex "No/No"
```

`cln` is a shorthand for calling the codon cleaner, try `hyphy --help` to see all such options

Best,
Sergei

**Comment by mbarkdull** [comment]
@spond- Yep, my alignments should be codon-aware (generated with PAL2NAL), but still contain terminal stop codons. 

Thank you for the additional suggestion! 

One last quick question: when I run the codon cleaner as @stevenweaver suggested, changing only the path to my input file, I cannot find the output file. The script finishes and says `Save cleaned data to: ('/local/workdir/mb2337/FormicidaeMolecularEvolution/')`, but there is no output file in that directory. Any thoughts on what is going on?

Thank you both again!
Megan

**Comment by spond** [comment]
Dear @mbarkdull,

Right, add one more argument like so, using the appropriate file path of course.

```
hyphy cln Universal /Users/sweaver/Programming/hyphy/HIV_RT.nex "No/No" /Users/sweaver/Programming/hyphy/HIV_RT_cleaned.nex
```

Best,
Sergei

**Comment by mbarkdull** [comment]
@spond That did the trick, thank you!
Megan
