### ISSUE TITLE
ERROR: [_LikelihoodFunction::LocateTheBump (index 211) 

### ISSUE THREAD

**Issue by emlee413** [veg/hyphy#1254]
Hello,

I've already run hyphy-aBSREL more than 700 times so far, but no errors have occurred.
Finally, I put the supermatrix file and tried to run it, but an error occurred, and hyphy was killed.
Any help on how to fix this error would be greatly appreciated.

hyphy version : HYPHY 2.5.8(MP) for Linux on x86_64
my command :  HYPHYMPI absrel CPU=45  --align supermatrix.phy  --tree supermatrix.treefile > out.log.txt

The error message is as follows.

### Rate class analyses summary
*  40 branches with **3** rate classes
*  15 branches with **4** rate classes
*  32 branches with **2** rate classes

### Improving parameter estimates of the adaptive rate class model
Error:

Master node received an error:Internal error

        ERROR: [_LikelihoodFunction::LocateTheBump (index 211) current value   -9214425.235745452 (parameter =   0.9993184406333853), best value    -9214425.23574545 (parameter =   0.9993184406333853)); delta = 1.862645149230957e-09 ]

Parameter name emnChoy_.tree_0.hyad.omega5

Function call stack
1 :  [namespace = aFAUvpQS] Optimize(mles, ^lf_id);

-------
2 :  absrel.full_model.fit=estimators.FitExistingLF(absrel.likelihood_function_id,absrel.model_object_map);
-------

**Comment by spond** [comment]
Dear @emlee413,

HyPhy is up to version 2.5.23. May I suggest you try the analysis with a later version and report if the error persists? Also, you are invoking `HYPHYMPI` (an MPI-enabled version), but are using command line arguments for `hyphy` (multi-threaded version). See below for suggested CLI commands:

```
hyphy CPU=45 absrel ...

mpirun -np 45 HYPHYMPI absrel ...
```
Best,
Sergei

**Comment by emlee413** [comment]
Thanks for the very quick reply. As you advise, I am working again with the latest version of hyphy. It takes about 5 days for the error to occur, so I will notify you at that time. Thanks again~!

**Comment by spond** [comment]
Dear @emlee413,

Should be faster with the new version.

Best,
Sergei

**Comment by emlee413** [comment]
Dear @spond 

There was an error again in the work I tried again. An error occurred in the same location, and the contents are almost the same.
Command used    "mpirun -np 20 HYPHYMPI absrel  --alignment  A.phy --tree B.treefile > A.log.txt" (hyphy_v2.5.23)
error message is below 

### Rate class analyses summary
*  46 branches with **3** rate classes
*  37 branches with **2** rate classes
*  4 branches with **4** rate classes

### Improving parameter estimates of the adaptive rate class model
Error:

Master node received an error:Internal error

        ERROR: [_LikelihoodFunction::LocateTheBump (index 185) current value   -9213807.233297681 (parameter =   0.9993584395344067), best value    -9213807.23329768 (parameter =   0.9993584395344067)); delta = 1.862645149230957e-09 ]



Parameter name SAPtw_XW.tree_0.hyad.omega3

Function call stack
1 :  [namespace = faajkttO] Optimize(mles, ^lf_id);

-------
2 :  absrel.full_model.fit=estimators.FitExistingLF(absrel.likelihood_function_id,absrel.model_object_map);
-------

**Comment by spond** [comment]
Dear @emlee413,

How many sites does your alignment have? 

Best,
Sergei

**Comment by emlee413** [comment]
Dear @spond

My alignment have 1320606 sites. 
The alignment is a bit long, but I would really appreciate it if you could make it so I can analyze it.
Thanks.

**Comment by spond** [comment]
Dear @emlee413,

I'll keep this open and try to provide a fix in the next release (next week probably).

Best,
Sergei

**Comment by spond** [comment]
Dear @emlee413,

Please try with version 2.5.24 (released today).

Best,
Sergei

**Comment by emlee413** [comment]
Thanks a lot, I will try today.

**Comment by emlee413** [comment]
Dear @spond, 

A different error occurred at the location where the previous error occurred. And  It took longer than hyphy 2.5.23. I wonder if it is a problem with my server or if the new version is slower.

error message is below.


### Rate class analyses summary
*  48 branches with **3** rate classes
*  4 branches with **4** rate classes
*  35 branches with **2** rate classes

### Improving parameter estimates of the adaptive rate class model
Error:

Master node received an error:Internal error
Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-9213760.427412655] does not match the last recorded LF maximum [1.952236128231523e-312]

Function call stack
1 :  [namespace = zpcTio_R] Optimize(mles, ^lf_id);

-------
2 :  absrel.full_model.fit=estimators.FitExistingLF(absrel.likelihood_function_id,absrel.model_object_map);
-------

**Comment by spond** [comment]
Dear @emlee413,

I fixed related issues in 2.5.25 and later releases. Can you please try again?

Best,
Sergei
