### ISSUE TITLE
Interpreting MEME results

### ISSUE THREAD

**Issue by gsecci** [veg/hyphy#1257]
Dear HyPhy team,
I am currently using MEME on datamonkey for my analyses.
I have a couple questions about the results:
1)	In the table with the EBF values, there are 2333 sites reported for each sample or node. This is not the number of sites under selection (which are 34). I though it could be the number of polymorphic sites, but when I calculate it in DNAsp it says these are 2600. Which site are represented in the table?
2)	If i understand correctly, I can use values of EBF<=100 to make an hypothesis of the branches that are under selection at a given sites. In my table I am obtaining quite big ebf values like 963592539.19. Is it an anomaly or this is supposed to happen? 
Thank you very much for your attention.
My best regards,
Giulia

**Comment by spond** [comment]
Dear @gsecci,

Can you please include a link to your data monkey results page so I can help you with (1)?

For (2), you want to use **EBF≥100** as evidence (exploratory) for positive selection operating on a specific branch at a specific site. We showed in our MEME paper that the accuracy of this inference is pretty low -- you can't expect to reliably identify a single branch at a single site (sample size ~ 1).

Best,
Sergei

**Comment by gsecci** [comment]
Thank you for your quick answer!
Here is the link do MEME results: http://datamonkey.org/meme/5fbf942e7067c12d0e218d29

**Comment by spond** [comment]
Dear @gsecci,

You should see EBF reported for all sites that have **some** variation, i.e. not invariable sites (gaps don't count as polymorphic characters). Any site with MEME or FEL LogL of **0** is an invariable site for which there will be no EBF computed.

You can also view EBF branch values within the app.

1. Turn on EBF display.

<img width="1093" alt="Screen Shot 2020-12-07 at 7 53 57 AM" src="https://user-images.githubusercontent.com/1018513/101365970-a8ce2f00-3861-11eb-9a2a-0572ecc6c757.png">

2. View any particular site (569 in this case)

<img width="948" alt="Screen Shot 2020-12-07 at 7 54 53 AM" src="https://user-images.githubusercontent.com/1018513/101366055-b8e60e80-3861-11eb-814c-8d03072211f9.png">

Best,
Sergei

**Comment by gsecci** [comment]
Thank you very much! I would like to ask you just few more questions, if possible:
1) In the tree visualization that you just showed, why the ebf treshold wouldn't get till 100 (considering that this is the treshold I would use for the exploratory analyses of the branches under selection) but only to 10?
2) When the value of EBF >=100 is identified on a node (and not at an individual sample) is it correct to assume that it is referred not only to node but everything coming after (e.g. all individuals after that node are from the same species, then the species would have that site under selection)?
3) is there any other program you would suggest to reliably investigate selection on a group of branches (even if I may lose the information of the specific site which is under selection)?

**Comment by spond** [comment]
Dear @gsecci,

1. The visualization can allow you to explore "weaker" signal as well (smaller EBF).
2. No, the EBF applies **only** to a single branch. All other branches are modeled as being independent of it. Often you will actually see a "burst" of selection on a given branch, followed by conservation on subsequent branches. 
3. If you are interested in testing **branches**, try aBSREL (http://datamonkey.org/absrel)

Best,
Sergei

**Comment by gsecci** [comment]
I will try it for sure. Thank you again for all your help!
All the best,
Giulia
