### ISSUE TITLE
reconstructing phylogeny generated from datamonkey

### ISSUE THREAD

**Issue by jojoman55** [veg/hyphy#1258]
Hi,

I have recently transitioned from using the Datamonkey to using HyPhy on the command-line. To remain consistent with previous work, I would like to know exactly how the phylogenies are generated when the MSA are imported into the datamonkey server. Can this be performed using the HyPhy package?

Cheers!

**Comment by spond** [comment]
Dear @jojoman55,

Yes, you can use the following command line option

```
./hyphy slac --alignment /path/to/file --tree neighbor-joining (other analysis arguments)
```

Other analyses (`fel`, `meme` etc) also support this argument. Please make sure that the alignment file does not already include a tree: if it does, the included tree takes precedence.

Best,
Sergei

**Comment by jojoman55** [comment]
Great thanks so much, I ran hyphy (fubar specifically) locally with the flag "--tree neighbor-joining" and uploaded the JSON file to hyphy vision. I then compared my results to FUBAR on datamonkey and the trees look different. Is it possible to generate the same trees, are there additional flags I am missing?

Cheers!

**Comment by spond** [comment]
Dear @jojoman55,

Do FUBAR results look different? The analyses should be relatively insensitive to some changes in tree topology. Datamonkey uses a slightly older version of NJ to build trees (it is server specific), but whatever differences you see should be minor. One possibility is that the trees are rooted differently.

Best,
Sergei

**Comment by jojoman55** [comment]
Actually they do look quite different. I am using the influenza a H5N1 example file (https://www.datamonkey.org/help). Datamonkey returns 14 sites under diversifying selection, whereas hyphy returns 8. The trees look differnt beyond just differnt roots. 

hyphy:
"(MALLARD_VIETNAM_16_2003:0.003556812804625227,(((((TREESPARROW_HENAN_1_2004:0.009229536014588648,TREESPARROW_HENAN_2_2004:0.01058758804167685):0.003482422927686155,CHICKEN_HEBEI_326_2005:0.02299042404800914):0.002525448697263577,(((DUCK_GUANGZHOU_20_2005:0.00823567983950661,GOOSE_SHANTOU_2216_2005:0.007638974445913597,PEREGRINEFALCON_HK_D0028_2004:0.004259542357896406):0.004647386722309406,CK_HK_WF157_2003:0.006129977119110483):0.006835473890884011,SWINE_ANHUI_2004:0.01644035527172941):0.00244318137980759):0.001465615800321126,((TREESPARROW_HENAN_4_2004:0.003336777865921734,(DUCK_HONGKONG_Y283_97:0,(CHICKEN_HONGKONG_915_97:0.0005883117273693053,(HONGKONG_97_98:0.004253380803313797,HONGKONG_538_97:0):0.001214310987862246):0.001179619059899629,GOOSE_HONGKONG_W355_97:0):0.02813386601228404):0.002282093350317563,TREESPARROW_HENAN_3_2004:0.0077077655383959):0.002606501748657523):0.01758396169027198,CHICKEN_THAILAND_KANCHANABURI_CK_160_2005:0.007186322866401052):0.000512157400394421,(HUMAN_VIETNAM_CL105_2005:0.005984486479122413,DUCK_VIETNAM_376_2005:0.008348684047829805):0.002355529452744274,VIETNAM_3062_2004:0.001778756294595345,DUCK_VIETNAM_272_2005:0.01013559991427251):0"

datamonkey
"(((((((TREESPARROW_HENAN_1_2004:0.0106547466772628,TREESPARROW_HENAN_3_2004:0.006654269408015559):0.001394262836364561,TREESPARROW_HENAN_4_2004:0.004616443970893027):0.003034437777009581,(CHICKEN_HEBEI_326_2005:0.0191576941641176,(SWINE_ANHUI_2004:0.01028049171202873,TREESPARROW_HENAN_2_2004:0.006427345973732472):0.004081770280002976):0.006251485561606248):0.003496959605326152,(HONGKONG_538_97:0,(CHICKEN_HONGKONG_915_97:0.0005884936346654511,(GOOSE_HONGKONG_W355_97:0,DUCK_HONGKONG_Y283_97:0):0.001179383287307293):0.001209585989492388,HONGKONG_97_98:0.004254267162324838):0.02334949109896385):0.003146728890862514,(((DUCK_GUANGZHOU_20_2005:0.006538315855791489,GOOSE_SHANTOU_2216_2005:0.005947966648618241):0.002349918815879235,PEREGRINEFALCON_HK_D0028_2004:0.003604684194276984):0.003557383394296988,CK_HK_WF157_2003:0.006573301624473312):0.004105784988433468):0.0130614859540947,MALLARD_VIETNAM_16_2003:0.003553881496681842,(HUMAN_VIETNAM_CL105_2005:0.005983744542626166,DUCK_VIETNAM_376_2005:0.008347942703611406):0.002354411423488119,VIETNAM_3062_2004:0.001779623622185972):0.001135813803314362,CHICKEN_THAILAND_KANCHANABURI_CK_160_2005:0.006561902863495422,DUCK_VIETNAM_272_2005:0.008990038923705037):0"

**Comment by spond** [comment]
Dear @jojoman55,

Do you see situations where one site is strongly supported by tree 1 (e.g. posterior probability > 0.9) and the not at all supported by tree 2 (e.g. posterior probability < 0.5)? You could see some sites drift up or down around detection cutoff (0.9) between trees; this is expected and normal. If a site "flips", this is not expected. 

Generally, we recommend using an ML program (e.g. IQ-Tree or RaXML) to infer the tree, especially if your dataset is small. 

Best,
Sergei

**Comment by jojoman55** [comment]
Yes you are right. Thank you so much for your help. I will follow your advice and generate trees using ML program when using both datamonkey and HyPhy
