### ISSUE TITLE
datamonkey MEME

### ISSUE THREAD

**Issue by doresannie** [veg/hyphy#1259]
i use Datamonkey for MEME but i am not locating my job queue also there is no option for email address. at main home page there is option classic, from classic i go to analyze your data option from there i run MEME. plz guide me

**Comment by jzehr** [comment]
Dear @doresannie,

When you are using the classic version of datamonkey.org there is a ```JOB QUEUE``` tab on the top of the page, which should look like this when you click on it: 
![Screen Shot 2020-12-16 at 5 33 38 AM](https://user-images.githubusercontent.com/38324371/102337356-5d520a00-3f60-11eb-8419-af0270e41c92.png)

However, I would suggest using the updated version of [datamonkey.org](http://www.datamonkey.org/). From the main page you can navigate to the ```Methods and Tools``` tab, and select ```MEME```: 
![Screen Shot 2020-12-16 at 5 37 05 AM](https://user-images.githubusercontent.com/38324371/102337727-d81b2500-3f60-11eb-8f79-9b74a5108ccc.png)

This page will appear, giving you the opportunity to provide an email when you run the analysis: 
![Screen Shot 2020-12-16 at 5 38 17 AM](https://user-images.githubusercontent.com/38324371/102337792-eff2a900-3f60-11eb-9ef2-58f94ee8c967.png)

If you want to check the status of your job you can look under the ```Job Queue``` tab, which will look something like this: 
![Screen Shot 2020-12-16 at 5 39 46 AM](https://user-images.githubusercontent.com/38324371/102337959-2a5c4600-3f61-11eb-918b-adab0bbe2f8b.png)

Best,
Jordan

**Comment by doresannie** [comment]
thankyou jorden. it will help me alot

**Comment by doresannie** [comment]
I got this problem after giving sequence file to data monkey server (Alignments with more than 500 sequences must include prebuilt trees Puzzled? Take a look at the file which was uploaded and make sure it is what you expected). I have 779 sequences.

**Comment by jzehr** [comment]
Dear @doresannie 

We limit the number of sequences on `datamonkey.org` to avoid long running jobs that will "clog up" the queue.

You can analyze as many sequences as you want if you download and install `hyphy` locally. You can also run larger jobs on http://usegalaxy.org, but it may take a while. Here is a tutorial you can use to install `hyphy` locally: https://www.youtube.com/watch?v=fgNrPbOTpxE&t=2s

Best,
Jordan

**Comment by doresannie** [comment]
![Screenshot (234)](https://user-images.githubusercontent.com/76098206/108615405-8fcb2800-7425-11eb-92ea-d9925dd9ec3e.png)
340 sites are negative selected. its sound so high, I am analysing selection pressure for virus using SLAC, FEL and MEME. I got larger number of codons selected as negative. one of my colleague told me that you have to only look for positive selection not for negative that evidence of negative selection determined by SLAC and IFEL is bias. kindly guide m. I am completely stuck in the interpretation

**Comment by spond** [comment]
Dear @doresannie,

1. Everything depends on the dataset you are analyzing. For many genes (including yours, where gene average dN/dS ~ 0.05 according to SLAC), extensive negative selection is **exactly** what you will expect to find. For example, site 282 in your alignment contains only amino-acid `D`, but there are **17** synonymous substitutions at that site (and **0** non-synonymous). Under neutral evolution you would expect to find ~**40** non-synonymous substitutions. That you see 0 is very strong evidence of negative selection. What you see is quite normal. 
2. There's no reason to suspect that SLAC or FEL are biased towards detecting **negative** selection. I don't know where your colleague may be getting this information. There's always some error in statistical inference, but for SLAC/FEL these errors are what you'd call nominal (as expected).
3. If you want the most sensitive method for positive selection detection, I suggest you use MEME. On your data there are 14 sites with episodic selection evidence at p≤0.05 (http://datamonkey.org/meme/60326144328ea41e07ffcb28). An interesting feature of your dataset is the fact that this selection is strongly episodic (small p+): it affects a small fraction of branches in the tree, while the rest of the tree is evolving under **negative** selection. For example, you can see where these episodes may be taking place at site 224

![tree](https://user-images.githubusercontent.com/1018513/108629037-108d2280-742c-11eb-8bf0-837a8671f578.png)

Best,
Sergei

**Comment by doresannie** [comment]
Thanks now I understand the concept .
