### ISSUE TITLE
error when using FEL, MEME in HyPhy command line

### ISSUE THREAD

**Issue by williamorsi** [veg/hyphy#1260]
I have been able to successfully use absrel with my in frame codon alignment and phylogenetic tree, and am now trying to identify site-specific dN/dS ratio hotspots using FEL and MEME.  However, when I try to run FEL and MEME using the same alignment and tree that work for absrel, I get the following error message.  Can you provide any insights into why this may be not working?  Is there an extra package that needs to be installed perhaps?  I copied my terminal screen below for you to see the error.  Thank you!

williamorsi1@a165 Hyphy % ./hyphy LIBPATH=/Users/williamorsi1/Projects/Manuscripts/Thalassospira_manuscript/hybrid_assemblies/core_genome_analysis/Phylogenetic_analysis/Hyphy/res fel --tree PhyML_tree.tre --alignment alignment.fasta --output FEL_test.json

Analysis Description
--------------------
FEL (Fixed Effects Likelihood) estimates site-wise synonymous (&alpha;)
and non-synonymous (&beta;) rates, and uses a likelihood ratio test to
determine if beta &neq; alpha at a site. The estimates aggregate
information over all branches, so the signal is derived from pervasive
diversification or conservation. A subset of branches can be selected
for testing as well, in which case an additional (nuisance) parameter
will be inferred -- the non-synonymous rate on branches NOT selected for
testing. Multiple partitions within a NEXUS file are also supported for
recombination - aware analysis.

- __Requirements__: in-frame codon alignment and a phylogenetic tree

- __Citation__: Not So Different After All: A Comparison of Methods for Detecting Amino
Acid Sites Under Selection (2005). _Mol Biol Evol_ 22 (5): 1208-1222

- __Written by__: Sergei L Kosakovsky Pond and Simon DW Frost

- __Contact Information__: spond@temple.edu

- __Analysis Version__: 2.1

>code –> Universal

>Loaded a multiple sequence alignment with **11** sequences, **147298** codons, and **1** partitions from `/Users/williamorsi1/Projects/Manuscripts/Thalassospira_manuscript/hybrid_assemblies/core_genome_analysis/Phylogenetic_analysis/Hyphy/0-800_nodups_v9.fasta`

>branches –> All
Error:
Failed to dereference 'fel.filter.default.site_map'

Function call stack
1 :  [namespace = SZcmxFDN] this_filter[utility.getGlobalValue("terms.data.coverage")]=utility.DictToArray(utility.Map(utility.Filter(^(this_filter[utility.getGlobalValue("terms.data.name")]+".site_map"),"_value_","_value_%3==0"),"_value_","_value_$3"));

    Keyword arguments:
        {
         "output":"FEL_test.json",
         "srv":"Yes"
        }
-------
2 :  [namespace = fel] filter_specification=alignments.DefineFiltersForPartitions(partitions_and_trees,"`prefix`.codon_data","`prefix`.filter.",codon_data_info);
-------
3 :  [namespace = fel] load_file("fel");
-------
4 :  namespace

Step 0.LoadFunctionLibrary("modules/shared-load-file.bf", /Users/williamorsi1/Projects/Manuscripts/Thalassospira_manuscript/hybrid_assemblies/core_genome_analysis/Phylogenetic_analysis/Hyphy/res/TemplateBatchFiles/SelectionAnalyses/);

Step 1.load_file("fel");;
-------

Check errors.log for execution error details.

**Comment by spond** [comment]
Dear @williamorsi,

Because your alignment is very long (by selection analysis standards, anyway, where a gene is typically the unit of analysis), you need to set an environment variable to tell HyPhy to override the default behavior for storing information about datasets. This can be accomplished by adding an `ENV` command line argument as follows:

```
/hyphy LIBPATH=/Users/williamorsi1/Projects/Manuscripts/Thalassospira_manuscript/hybrid_assemblies/core_genome_analysis/Phylogenetic_analysis/Hyphy/res fel --tree PhyML_tree.tre --alignment alignment.fasta --output FEL_test.json ENV="USE_MEMORY_SAVING_DATA_STRUCTURES=1e8;"
```

The number you supply (e.g. 1e8 here) should be greater than the number of sites in your alignment

Best,
Sergei

**Comment by williamorsi** [comment]
Thanks very much!  This solved the issue.
