### ISSUE TITLE
Error when using FUBAR and MEME

### ISSUE THREAD

**Issue by kes550** [veg/hyphy#1261]
Both algorithms have an error when trying to run the programs. Errors persist on datasets that were previously successful. No explanation as to what is causing the problem. There are no stop codons in the alignments and the codons are aligned to ensure proper ORF translation.

**Comment by stevenweaver** [comment]
Dear @kes550, 

Thank you for using HyPhy. Do you happen to have access to the error produced by HyPhy when the program exits? Additionally, would it be possible to provide which version of hyphy you are using? That information can be attained by using the command:

`hyphy --version`

Best,
Steven

**Comment by kes550** [comment]
Hi Stephen,

I am not using a command line to run the analysis. I am not much of a coder so I am running the analysis on the Datamonkey platform. The analyses I am running are to test individual sites for selection using the Bayesian (FUBAR) approach and MEME for episodic selection. When I upload my alignment file that was successful in the past for either analysis, the following error reads: “We’re sorry, there was an error processing your job. Please try again, or visit our GitHub issues and create an issue if the issue persists.”

Kathryn Secrist, B.S.
Ph.D. Candidate, Dr. Ali Virology Lab
Graduate Assistant, Center for Student Academic Success
The University of Tulsa
email: kathryn-secrist@utulsa.edu<mailto:kathryn-secrist@utulsa.edu>

**Comment by stevenweaver** [comment]
Dear @kes550, 

Thank you for reporting. There was an issue with our job runner on our cluster. The issue should be resolved and you should be able to submit analyses again. 

Thanks again,
Steven
