### ISSUE TITLE
aBSREL

### ISSUE THREAD

**Issue by williamorsi** [veg/hyphy#1263]
Hello

I am trying to run aBSREL on an alignment of ca. 30 protein coding sequences, the sequences are in frame codon aligned, and I have confirmed this via BLAST for the individual sequences against NCBI where one can see the CDS and amino acids encoded under the codons of the query and subject.  

However, when I run the multiple sequence alignment of all 30 sequences in aBSREL, I get an error message saying that there are stop codons in the sequences.  However, this seems to be an artefact of the alignment since if I introduce gaps into some of the sequences in the multiple sequence alignment the  (incorrect) stop codons are no longer found by aBSREL.

Is there a way to prevent aBSREL from detecting these incorrect stop codons, or is there a recommened multiple sequence alignment method for in frame codon aligned sequences?  Until now I have been using MUSCLE and CLUSTAL.

Thank you!

Bill

**Comment by spond** [comment]
Dear @williamorsi,

If HyPhy reports stop codons, then they are found in the sequences present in the alignment. Can you clarify what you mean by the following?

> this seems to be an artefact of the alignment since if I introduce gaps into some of the sequences in the multiple sequence alignment the (incorrect) stop codons are no longer found by aBSREL.

A common alignment approach to take would be to 

1. Translate your in-frame sequences into amino-acids
2. Align those protein sequences using `MUSCLE` or `MAFFT` etc.
3. Map nucleotide sequences back onto aligned protein sequences using something like `PAL2NAL` (http://www.bork.embl.de/pal2nal/)

Best,
Sergei

**Comment by williamorsi** [comment]
This works perfectly now , thank you for the tip on preparing the in frame codon alignment!
