### ISSUE TITLE
Error when reading .nwk file

### ISSUE THREAD

**Issue by SinTan1729** [veg/hyphy#1266]
I'm trying to analyze a `.nwk` file with Hyphy. I created this using Mega X. But I'm receiving the follwing error.
```
errors.log

Error:The format of the sequence file has not been recognized and may be invalid
The format of the sequence file has not been recognized and may be invalid
```
What might be causing this? [Here](https://pastebin.com/NGijDChG) are the contents of the file.

**Comment by spond** [comment]
Dear @SinTan1729,

Sorry I can't help you with just the information you provided. Please include

1. **What** were you trying to do with HyPhy, i.e. what analysis were you conducting?
2. HyPhy needs both an (alignment, tree) pair for most analyses. Did you provide an alignment?
3. What was printed to screen? (not just the `error.log` file)

Best,
Sergei

**Comment by SinTan1729** [comment]
I'm entirely new to HyPhy, so I didn't realise that I had to provide the alignment file first. Now, it's opening. It's giving another error, but I think that's due to a mistake I made. Anyway, thanks for the quick response.

**Comment by spond** [comment]
Dear @SinTan1729,

No problem. Please take a look at http://www.hyphy.org/tutorials/CL-prompt-tutorial/ for some instructions.

Best,
Sergei
