### ISSUE TITLE
aBSREL tree internal branch/node not resolved

### ISSUE THREAD

**Issue by josephbenito** [veg/hyphy#1267]
aBSREL tool/method (which is used to test if positive selection has occurred on a proportion of branches) outputs the phylogenetic tree by color coding the leaf and internal branches with evidence of positive selection (P <0.05). Color coded leaf branches are easily identifiable but color coded internal branches are not well resolved (meaning the branches are overlaid on top of one other) and the options/settings provided to display the tree in different views doesn't help. The leaf branches are named with the corresponding species names whereas the internal branches/nodes are numbered (node 1 thru 63). Any help is appreciated!

One of my recent run results can be found at
http://datamonkey.org/absrel/5fea72d670baba7af141c189

**Comment by spond** [comment]
Dear @josephbenito,

It seems that the alignment you analyzed has several **very** divergent sequences, which makes one branch much longer than the others, and "squishes" the display. Normally you can mouse over internal branches to have a popover with the name and analysis info

At the moment, data monkey visualization does not handle this particular case well, but you may want to look at **why** those sequences appear so divergent (perhaps there's an issue with the alignment)?

In the meantime, please take a look at https://observablehq.com/@spond/displaying-absrel-results-using-branch-censoring?id=5fea72d670baba7af141c189 which allows you to "censor" branch lengths and view node names.

Best,
Sergei

![tree](https://user-images.githubusercontent.com/1018513/103688274-94b04700-4f5f-11eb-8a22-2e7700e00f9f.png)
