### ISSUE TITLE
Contrast-Fel - tree issue

### ISSUE THREAD

**Issue by ksummers26** [veg/hyphy#1269]
Hello - I'm trying to run Contrast-Fel with a specified tree, but when the tree comes up on the screen (for labeling) it is missing some branches. Oddly, when I change the order of the sequences in the alignment file, it changes which taxa are missing from the tree(?).  
Thanks for the help, Kyle Summers

**Comment by spond** [comment]
Dear @ksummers26,

Do you have duplicate sequences in your alignment? Datamonkey will filter those prior to displaying anything, and also remove corresponding branches in the tree.

You can use https://github.com/veg/hyphy-analyses/tree/master/remove-duplicates to preprocess your alignment locally and check.

Best,
Sergei

**Comment by ksummers26** [comment]
Ahh - that makes sense - will check that. Thanks, Kyle
