### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by chrisbalakrishnan** [veg/hyphy#1270]
Hi there -

I am currently recieving this error when I try to run absrel or relax. I found a similar post on twitter from March 2020. Was any resolution reached? In my case I'm working with files I have run successfully before.

**Comment by stevenweaver** [comment]
Dear @chrisbalakrishnan, 

This usually occurs when there is a timeout on upload. One moment while I verify. 

Best,
Steven

**Comment by stevenweaver** [comment]
Dear @chrisbalakrishnan, 

There was indeed an issue with our system. I've restarted the datamonkey web process and things seem to be operational as normal. Thank you for reporting this issue, I'm going to mark it as closed but please feel free to reopen should there be further abnormalities. 

Best,
Steven

**Comment by chrisbalakrishnan** [comment]
Thanks!
