### ISSUE TITLE
GARD not working on datamoneky server

### ISSUE THREAD

**Issue by marrrkyyy** [veg/hyphy#1279]
Hello guys,

New user here. I can't get GARD to run on the server. Attached my .fasta alignment, left everything else as default and keyed in my email.

My alignment contains 75 sequences, each sequence is about 27500 nucleotides. 

Please help guys, i cleared cookies, new browser etc. Whenever i  press run, a black grey bar appears where the file attachment box is, doesnt seem to be running when i check job queue 

Thank you

**Comment by jzehr** [comment]
Dear @marrrkyyy,

Could you please provide the job ID number associated with your run? That number should be in subject line from the email sent from ```no-reply@datamonkey.org```, and should be a 24 character ID.

With the job ID we should be able to better assess what issues came up.

Best,
Jordan

**Comment by marrrkyyy** [comment]
Hello Jordan,

Thank you for the reply. I dont think my job started though.
Here is a screenshot of what it looks like on datamonkey. Refresh browser and tried restarting etc. 
 
![Screenshot 2021-02-05 at 11 38 49 AM](https://user-images.githubusercontent.com/78577967/106986699-dd4d6100-67a6-11eb-8d55-597cdb07c190.png)

**Comment by marrrkyyy** [comment]
Actually, I'm running coroanviruses sequences which are like 27k-30k long, there are multiple ORFs where each has its own stop codon, wondering if this is causing the issue?

**Comment by spond** [comment]
Dear @marrrkyyy,

You should run these as `nucleotide` data. The `codon` option will use **codon models**, require things to be in-frame and run 100x slower :)

Best,
Sergei

**Comment by marrrkyyy** [comment]
> Dear @marrrkyyy,
> 
> You should run these as `nucleotide` data. The `codon` option will use **codon models**, require things to be in-frame and run 100x slower :)
> 
> Best,
> Sergei
> 
> PS If you have CoV data, I would also suggest removing sequences that are very similar to others (if you have them). Including sequences that are nearly identical will **worsen** the performance of the method, both computationally, and in terms of being able to detect recombination. You can, for example, run them through `tn93-cluster` (a part of GitHub.com/veg/tn93) to identify tight clusters of sequences at a given threshold (set it low).

Hi Sergei,
Yes i did select and try the nucleotide option too, the analysis doesnt seem to begin. I will try your suggestion and remove identical, not sure if these could be the reason why the analysis on DM is not starting.

**Comment by jzehr** [comment]
Dear @marrrkyyy,

Looks like there might have been an issue on our end last night, go ahead and re-try your analysis with Sergei's suggestions. 

Let us know if you continue to run into issues. 

Best,
Jordan

**Comment by stephenshank** [comment]
Dear @marrrkyyy,

Also, please note from our [usage statistics](http://datamonkey.org/stats#) that a GARD job the size of which you originally described has never ran to completion, due to either sequence limitations set by use or exhausting computational limits for datamonkey. Here is what has ran:

![image](https://user-images.githubusercontent.com/8673708/107047909-57291e80-6796-11eb-8d40-06294c85c265.png)

Best,
Stephen

**Comment by marrrkyyy** [comment]
Thanks for the suggestions guys. So if sites = to nucleotides, a CoV alignment with 70-100 sequences is going to fail. 
I will trim away similar sequences and try again.

will update in due course

**Comment by spond** [comment]
Dear @marrrkyyy,

I am actually working on adding an auto-trim option to GARD; should roll out in the next couple of weeks. You can also turn off rate variation to speed things up.

Best,
Sergei

**Comment by marrrkyyy** [comment]
@spond 

Auto trim would be fantastic. Any further suggestions for CoV analysis? I do not trim the 5' non coding and 3' non coding though.

**Comment by spond** [comment]
Dear @marrrkyyy,

Nothing further at this point.

Best,
Sergei

**Comment by Keiragibson3** [comment]
Hi,

I have the same issue. The job doesn't seem to be starting. I have 15 viral sequences and have tried uploading in all available formats (Phylip, fasta, nexus, etc,). 

Can this be reviewed please?

I am trying to look into recombinations of coronaviruses for my dissertation. Are there other methods of detecting recombination without using GARD?

Thank you,
Keira Gibson.

**Comment by Keiragibson3** [comment]
![Image 17-02-2021 at 12 02](https://user-images.githubusercontent.com/78923814/108201733-1e833080-7118-11eb-9001-371baec5d1aa.jpeg)

**Comment by spond** [comment]
Dear @Keiragibson3,

GARD seems to be running normally (http://datamonkey.org/jobqueue). Where exactly does the analysis fail for you? Are you able to click "Run Analysis" to proceed to the next stage?

Best,
Sergei

**Comment by Keiragibson3** [comment]
Hi Sergei,

I uploaded a screenshot of how it appears on my screen when I click the run analysis.
When I click run analysis, the top area where you would upload the file greys out, and it doesn't go any further. I don't receive an email either. 

Keira Gibson

**Comment by spond** [comment]
Dear @Keiragibson3,

I have not seen this behavior before. What browser are you using? Can you [open the browser console](https://balsamiq.com/support/faqs/browserconsole/) and see if any errors messages are logged there?

Best,
Sergei

**Comment by Keiragibson3** [comment]
Dear Sergei,

I am using safari, and cannot see any error messages.
Would it be possible to email you the alignment I am trying to upload to see if it works for you?

Thank you,
Keira

**Comment by spond** [comment]
Dear @Keiragibson3,

Yes, that would be great. Thanks (spond at temple dot edu).

Best,
Sergei

**Comment by Keiragibson3** [comment]
spond@temple.edu    ?

**Comment by spond** [comment]
Dear @Keiragibson3,

Yes. The at and dot are to make it a little harder for e-mail harvesters to collect the address for spam.

Best,
Sergei

**Comment by Keiragibson3** [comment]
I see, my apologies I have hidden the previous comment with your email.
I have emailed you the file in various formats, have you received it?

Thank you,
Keira

**Comment by spond** [comment]
Dear @Keiragibson3,

Looks like your alignment is too long for Datamonkey (45kb). There is no warning about it -- the server just rejects the upload (@stephenshank @stevenweaver @jzehr : we should put this on the list of things to fix). I'll run the job for you on the cluster and see where it is in a couple of days.

Best,
Sergei

**Comment by Keiragibson3** [comment]
Hi Sergei,

Thank you so much!
Do I wait for you to contact me back?

I really appreciate your help. 
Best wishes,
Keira Gibson.

**Comment by spond** [comment]
Dear @Keiragibson3,

I'll post an update here.

Best,
Sergei

**Comment by marrrkyyy** [comment]
Dear @Keiragibson3 

Yes i have exactly the same problem as you when i started this thread. Still not getting anywhere with my data set. I think CoVs are generally 28-32kb. So cutting them down is not an option if recombination is to be thoroughly accessed. 

I am hoping to use GARD to verify some break points etc. For recombination, i have been exprimenting with 3SEQ (mac terminal) or using RDP (windows)

@spond could i please get some help with my data set, not sure how 75 sequences of 27kb sequences will fair on your back end cluster?

**Comment by spond** [comment]
Dear @marrrkyyy,

For the time-being, just send me your sequences and I will run them.

Best,
Sergei

**Comment by Keiragibson3** [comment]
Hi! 
I hope you are well!
I am just wondering if there is an update with the sequences?

Thank you,
Keira

**Comment by Keiragibson3** [comment]
Hi, 
Sorry to pester I am just really keen on getting this work done.
Any update at all?

Thank you,
Keira

**Comment by spond** [comment]
Dear @Keiragibson3,

I took some time to tune GARD and add some bug fixes. A new release will contain these fixes. Your analysis is running at the moment. Because the alignments are long, it is a relatively slow process. Your alignment definitely contains extensive recombination; once the analysis progresses a bit further, I'll post partial results. One other thing I was going to ask you: how did you generate the alignments? There seem to be a lot of out of frame insertions. It may be better to align the coding part of the genome in protein space. 

Best,
Sergei

**Comment by Keiragibson3** [comment]
Dear Sergei,

Thank you so much for your help it is really appreciated! 

I used MEGAX to generate these alignments.

Thank you,
Keira Gibson

**Comment by spond** [comment]
Dear @Keiragibson3,

Please see the results of your analysis attached. 

Please use https://observablehq.com/@spond/plotting-gard-breakpoint-support to visualize these results (download the result file from here, decompress it, and load it into the notebook).

Best,
Sergei

[cov.fas.GARD.json.zip](https://github.com/veg/hyphy/files/6062822/cov.fas.GARD.json.zip)

**Comment by Keiragibson3** [comment]
Dear Sergei,

Thank you so much! I am honestly so grateful.

Thank you,
Keira Gibson.

**Comment by Keiragibson3** [comment]
Dear Sergei,

I hope you are well!

My recombination analysis didn’t go to plan, and I am thinking this could be due to how many varying sequences I used. Sadly, the GARD online tool is still not allowing me to run sequences.

Could I please request you to run this file for me? It has the RATG13 CoV, pangolin CoV and SARS-CoV-2 sequences.

No worries if not, I just thought it would be worth the ask!

Thank you,
Keira Gibson.

**Comment by spond** [comment]
Dear @Keiragibson3,

Sure. GitHub does not forward e-mail attachments, however, so I didn't receive anything.

Best,
Sergei
