### ISSUE TITLE
GARD with General Discrete Error

### ISSUE THREAD

**Issue by praman5** [veg/hyphy#1281]
Hi!

I tried to run GARD with site-to-site rate variation set as general discrete and rate classes at 3 for a few different alignments and got the same error message in all cases (pasted below). I am now trying GARD on the same alignments with the site-to-site variation set as none and it appears to be working. 

Can you please tell me what my error might be and how to prevent getting an error when I run these alignments with the general discrete settings ? The job ID numbers associated with my runs that didn't work are 602183a227e5ee138cbb21ea, 602181fa27e5ee138cbb2193 and 602181b027e5ee138cbb215c.

Thank you!!

Standard Error Message
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

**Comment by stevenweaver** [comment]
Dear @praman5, 

You are selecting "codon" type instead of "nucleotide". Are you supplying an in-frame codon alignment?

Best,
Steven

**Comment by praman5** [comment]
Hi Steven,

Thank you for replying so quickly. I am supplying an in frame alignment which is why I selected codon but I can try nucleotide instead and see if that helps.

Best,
Pravrutha
