### ISSUE TITLE
FEL-contrast and FEL: choosing alignments

### ISSUE THREAD

**Issue by muktaik** [veg/hyphy#1282]
Hi. This is more of a question and not an issue. I have two cases 1. I have two groups A and B and I have one alignment for them which I am using in FEL-contrast to choose A and B as foreground and background respectively (and also vice versa). 2. I am using separate alignments of A and B in FEL. 
I get drastically different results for both the cases.. Which is a better way to go about this?

**Comment by jzehr** [comment]
Dear @muktaik,

Firstly, I looked at an older comment of yours [#1053](https://github.com/veg/hyphy/issues/1053) and I wanted to point you to our [YouTube channel](https://www.youtube.com/channel/UCIgRnbJjbOWhshe5ThhaWGw), as this might help to better understand how to use some of our tools. 

Secondly, regarding your question, can you provide a little more context as to:
- what biological question you are trying answer
- what data are you using for data A and data B (homologous sequence, codon-aware alignments are preferred when running through our tools).

The FEL method assumes that the selection pressure for each site is constant along the entire phylogeny. If you *just* want to estimate nonsynonymous and synonymous substitution rates at each site within each separate alignment (A individually and B individually), then FEL will be useful. In this approach you will make a codon-aware-alignment for A and a codon-aware-alignment for B, build separate trees, and run FEL on both trees and alignments. 

If your question is to *compare* sites between A and B that are subjected to different selective regimes then Contrast-FEL will be more conducive. In this approach you will need to make a codon-aware-alignment that contains BOTH A and B, build your tree, then run Contrast-FEL accordingly. 

Best,
Jordan

**Comment by muktaik** [comment]
Hi,
Thank you for your elaborate reply. 
Let me give you some context. A and B are very closely related groups of insects and I have gene sequences of a gene that is involved in sensory system. I want to compare evolutionary rates of this gene in these two groups. Broader question is to see if one has higher evolutionary rate than the other. I used gene sequences to build codon-aware alignments. When I performed FEL for individual alignments and used dN/dS values to compare with each other, I found that A has higher dN/dS than B. When I use alignment with both A and B together, FEL-contrast gives me higher dN/dS in B. 
I hope this clarifies my question better.

**Comment by jzehr** [comment]
Dear @muktaik,

Interesting, thanks for the context. 

The short answer: there are several reasons why comparing results of separate datasets in a *post-hoc* fashion are statistically suboptimal; in this case contrast-FEL makes more sense. 

To provide more context check out the [contrast-FEL](https://www.biorxiv.org/content/10.1101/2020.05.13.091363v1.abstract) preprint, under the **Empirical Data** section. This section uses drug resistance in HIV-1 reverse transcriptase to do this exact test, where selection is tested in separate alignments to tease apart selective pressure patterns, and then contrast-FEL is used on the whole alignment to identify selection patterns. The section concludes by discussing why comparing all sites together in one alignment makes the most sense statistically.

Best,
Jordan

**Comment by muktaik** [comment]
Dear @jzehr,

Thanks again. What you have mentioned makes sense. I think I will go with contrast-fel. If I want to do such a contrasting comparison using MEME, as in see if on site-level do I have more episodic positive selection compared to the other group, is there a specific way to do this? Because if I use separate alignments in MEME, the same issue will persist. 

Best,
Muktai

**Comment by spond** [comment]
Can you provide the results of the analyses? Will be helpful to see what’s going on.

**Comment by muktaik** [comment]
Here are the data monkey links for FEL when separate alignments were used. 
A: https://www.datamonkey.org/fel/6025804a27e5ee138cbbcec6#summary-tab
B: https://www.datamonkey.org/fel/60257ece27e5ee138cbbce8e
Here quite a few values with high omega in B compared to A.

Here are the links when they are used as foreground in FEL contrast
A as foreground: https://www.datamonkey.org/contrast_fel/6025737727e5ee138cbbc93b
^ here most of the significant sites have higher omega in A.

Here are the links for MEME for separate alignments.
A: https://www.datamonkey.org/meme/6026a471328ea41e07fe50db
B: https://www.datamonkey.org/meme/6026a47e328ea41e07fe5146

Let me know if I am doing something incorrect here. Thank you so much for your help!
Best,
Muktai

**Comment by spond** [comment]
Dear @muktaik,

Just to make sure: can you tell me specifically what are you comparing when you mention omega estimates? For site level analyses, our recommendation is to only go by pvalues, and qualitative dS and dN characteristics. Point estimates are quite imprecise. You also have quite an odd pattern in the B FEL alignment. Look at the alpha rates in the first 50 bases or so: it is very high. Could indicate some alignment issues. In the joint alignment there is no alpha rate elevation in the same region of the alignment. If you look at the separate and the joint alignments, how different are they?

Best,
Sergei
