### ISSUE TITLE
Plotting k (general descriptive) from RELAX onto tree

### ISSUE THREAD

**Issue by juliayork** [veg/hyphy#1283]
I am so frustrated trying to plot the values of k from my json file onto the tree. I want to plot them as colors. I've tried so many things (phyphy, phytools, ggtree, etc, etc). Can someone please, please help me?

**Comment by spond** [comment]
Dear @juliayork,

Are you doing it from Datamonkey or standalone HyPhy `.json` results?

Best,
Sergei

**Comment by juliayork** [comment]
I'm using standalone HyPhy on my cluster.

**Comment by spond** [comment]
Dear @juliayork,

Try https://observablehq.com/@spond/plotting-relax-k-values-on-branches-of-the-tree

Best,
Sergei

![plotting-relax-k-values-on-branches-of-the-tree](https://user-images.githubusercontent.com/1018513/107992281-62eebf00-6fa6-11eb-8189-d4eaf5ffc8fa.png)

**Comment by juliayork** [comment]
Thank you so much, that is really nice of you!
