### ISSUE TITLE
Hyphy Vision Not Working for ABSREL

### ISSUE THREAD

**Issue by cahende** [veg/hyphy#1286]
Hello, 

Hyphy Vision (the interactive online .json viewer) is not working for ABSREL output, please see sample output that produces the error (note I added the extension .txt to allow for attaching the file in github's messaging system but the file is still the .json output from ABSREL).

In addition, might I ask for a solution to extract relevant information from the .json from the command line for batch processing of output for large numbers of samples for this and MEME analysis (MEME works fine in hyPhy vision)?

Thank you,
Cory Henderson
[Q7QJ32-absrel.json.txt](https://github.com/veg/hyphy/files/5997545/Q7QJ32-absrel.json.txt)

**Comment by spond** [comment]
Dear @cahende,

Regarding your `aBSREL` issue. Would it be possible to obtain the source data and the analysis settings which generated the `.json`? It contains some irregular branch records, and I am not entirely sure why.

As for batch `json` processing, you can go a variety of routes.

1. Use python's `json` module.
2. Use a command line utility `jq` to extract information from JSON (it's very powerful for this purpose)
3. Pretty much any modern language (R, Julia, Perl, Ruby) will support reading JSON files.

Best,
Sergei

**Comment by cahende** [comment]
Thanks for the response Sergei!

The command I use for running hyPhy absrel is as follows (I run iteratively
on a collection of MSA for some orthologs I have identified).

hyphy absrel  --alignment MSA/alignedStopCodonRemoved/${field1}*.fa --tree
iqTreeRuns/concord.cf.tree.nex --output
hyphyRuns/ABSREL/${field1}-absrel.json

Attached is the MSA corresponding to the .json provided previously and my
tree in nexus format.

Best,

Cory Henderson, Ph.D. Candidate
NSF Graduate Research Fellow
The Pennsylvania State University
Rasgon Lab: Vector Genetics and Control <https://rasgonlab.com/>
Dept. of Molecular Cellular and Integrative Biosciences
<https://www.huck.psu.edu/content/research/center-for-infectious-disease-dynamics>
Center for Infectious Disease Dynamics
<https://www.huck.psu.edu/content/research/center-for-infectious-disease-dynamics>

W-119 Millennium Science Complex
Email: cah422@psu.edu
Phone: (336)362-0549

**Comment by spond** [comment]
Dear @cahende,

GitHub strips out e-mail attachments. Can you please re-attach here or send to me by e-mail directly?

Best,
Sergei

**Comment by cahende** [comment]
Hi Sergei,

What email address would reach you directly?

Cory

**Comment by spond** [comment]
Dear @cahende,

spond at temple dot edu

Best,
Sergei

**Comment by spond** [comment]
Resolved with da4ab4c3200a0db6f8d3a7f9b8cbd234fe5d47fe

As a workaround to view already existing ABSREL files, use https://observablehq.com/@spond/displaying-absrel-results-using-branch-censoring/2
