### ISSUE TITLE
Question about GARD output

### ISSUE THREAD

**Issue by dforni5** [veg/hyphy#1288]
Dear hyphy developers,
I have a question regarding GARD  results (hyphy v 2.5.27)
when I run a GARD analysis using codon as a sequence type, the breakpoint positions that I get  refer to codon numbers, I am right? e.g If I get "Best break point locations: 242, 440", those are codon 242 and 440, right?
I am puzzled because hyphy vision reports those as breakpoint positions, and the last position in the recombination segment is 473 (as said here "Loaded a codon multiple sequence alignment with **13** sequences, **473** sites", and in agreement with my alignment length divided by 3). But if I looked at the "alignment.best-gard" file, it reports:

BEGIN ASSUMPTIONS;
	CHARSET span_1 = 1-243;
	CHARSET span_2 = 244-441;
	CHARSET span_3 = 442-1419;

where 1419 is 473*3, suggesting that it is considering these positions as nucleotides. I am using this file as input for the others hyphy analyses (e.g. MEME, FUBAR), so I am wondering how they handle this discrepancy.
Thank you for your time
Diego

**Comment by spond** [comment]
Dear @dforni5,

Partitions are always specified as nucleotides (because the underlying alignment is composed of nucleotides). You can feed the NEXUS file into MEME/FUBAR directly. In fact you should even use GARD in nucleotide mode for speed, because downstream analyses will adjust partitions so that they fall on codon boundaries.

Best,
Sergei

**Comment by dforni5** [comment]
Dear @spond,
thank you for your reply. Sorry, but I am missing something.
same GARD run (my alignment is 1419 nucleotides/ 473 codons)
hyphy vision output:
3 partitions: 1-242, 243-440, 441-473

nexus file partitions:
3 partitions: 1-242, 243-440, 441-1419

the third partition is quite different...
thank you for patience 
Best
Diego

**Comment by spond** [comment]
Dear @dforni5,

It looks like there's an error with the vision output for the last partition. @stephenshank : can you take a look to see if we are simply not back-converting to 3x?

Best,
Sergei

**Comment by dforni5** [comment]
dear @spond 
if I may add something, I have investigated at it in the past few days, and it seems to me that it always consider positions as codons. For example, if I look at the various GARD output files, I never found a position higher than 473 tested as a possible breakpoint. That's why at the beginning I thought that  the nexus file positions were codons.

best
Diego

**Comment by spond** [comment]
Dear @dforni5,

You could be right; I'll check what GARD does in `codon` run mode. In the meantime, I suggest you run it with the `nucleotide` mode.

Best,
Sergei

**Comment by dforni5** [comment]
Dear @spond 
thanks and thanks for all your great work!
Diego
