### ISSUE TITLE
GARD setting on Datamonkey

### ISSUE THREAD

**Issue by Oceanleehy** [veg/hyphy#1291]
Hi there,

I am a beginner at evolutionary analysis. I am trying to use GARD on the datamonkey server. My input data is a CDS alignment that has no stop codon and is divisible by 3. However, when I choose the "codon" and "nucleotide" for the "data type" option, the result is completely different. 

I read the [paper ](https://doi.org/10.1093/molbev/msl051) and for my understanding, the "nucleotide" mode could deal with the sequences that are not in multiples of 3, but I don't understand for my case, why the result is different. Can someone tell me the reason and right parameters, or where I can find the relevant instruction (of those options, like rate class, data type)? Many thanks for any advice you could provide me.

Regards,
Tao

**Comment by spond** [comment]
Dear @Oceanleehy,

The `codon` option actually fits a codon model and uses a different distance for NJ tree building. You should use the `nucleotide` option, even if you have coding data.

Best,
Sergei

**Comment by Oceanleehy** [comment]
Thank you very much for your reply. Then what kind of situation/data is the "codon" option suitable for?

**Comment by spond** [comment]
Dear @Oceanleehy,

If you wanted to use codon substitution models during recombination analyses. That makes the analysis **very** slow, however.

Best,
Sergei

**Comment by Oceanleehy** [comment]
Thanks for your reply.
Best regards,
Tao
