### ISSUE TITLE
Maximum Limitations issues

### ISSUE THREAD

**Issue by SticaC** [veg/hyphy#1294]
I am new to datamonkey, but I saw that recently the maximum limitations have increased. However, I am still having issues with my datasets uploading for jobs. The green bar at the top goes across, but then nothing happens. It works for smaller datasets, but not for my larger ones.

The large data sets are 298 - 590 sequences with less than 500 sites. Both well below all of the increased limitations, as far as I can tell. I am trying to run MEME, FEL, SLAC, FUBAR and potentially a few others.

Thanks

**Comment by spond** [comment]
Dear @SticaC,

This is unlikely to be a data size limitation, but rather could reflect some other issue. Can you share one of the problem data sets for debugging?

Best,
Sergei

**Comment by SticaC** [comment]
Here is the fasta alignment file as a txt file.

[All_D2_E alingment.txt](https://github.com/veg/hyphy/files/6058516/All_D2_E.alingment.txt)

**Comment by SticaC** [comment]
Here are the two datasets in fasta format.

Thanks
Caleb Stica

**Comment by chbabin** [comment]
Hello,
I am also having this issue, however it just started for me today.  I have been working with the same dataset for several weeks now and have never had this problem until today.  Any help is greatly appreciated.

**Comment by SticaC** [comment]
Mine ended up being gaps in my alignments. But I can still only get 500 sequences max to run. Each with about 3,388 sites. So still unsure what the issue is with that, as these are well below the new limits.

**Comment by chbabin** [comment]
Thanks for the response SticaC.  I have 115 sequences in my MSA with a total of 2004 sites.  Datamonkey was working perfectly for me until today so hopefully whatever the issue is will be resolved soon.

**Comment by SticaC** [comment]
Actually I just tried, and I cant run my sequences anymore either. So hopefully just a temporary issue that will be resolved.

**Comment by stevenweaver** [comment]
Dear @chbabin and @SticaC, 

Yes, there were performance issues with datamonkey today that should now be resolved. 

Thanks for your patience,
Steven
