### ISSUE TITLE
Computing ER in BUSTED?

### ISSUE THREAD

**Issue by ctob2** [veg/hyphy#1295]
hello 
I am not sure how to get the ER (as show in graph in the DataMonkey output for BUSTED) from the table below showing likelihoods and statistics- could you kindly advise?
I assume the ER is the best value to report in terms of a descriptive evidence for supporting that that site is under + selection?
many thanks

**Comment by aglucaci** [comment]
Hello ctob2,

The ER values you are looking for are available in the JSON file output from the BUSTED run. If you are interacting with the results on DataMonkey you should be able to download the file via Export -> Save JSON. Site-wise evidence ratios would provide some descriptive evidence that that site might be selected. However, it may be useful to run another model (FEL/MEME) to further interrogate your data. 

Best,
Alexander

**Comment by ctob2** [comment]
hello Alexander and many thanks for your helpful reply.
Found the ER numbers, but still can't see how these relate to the numbers in the table or the graph in the DataMonkey output? 
also which number/(s) would be best to report as descriptive evidence of selection for a site? (Optimized Null Statistic?/ one of the ERs?/their ratio?)
bw
Camilla

**Comment by aglucaci** [comment]
Camilla,

The ER values you find will relate to the graph presented on DataMonkey. When you retrieve the list of ER values, for example "constrained" , they will corresponded to the sites in your alignment from 1 ... N. What is "best" to plot may depend on your biological question of interest. However, you may be interested in plotting the "contrained" ER values and looking at sites with values above a threshold as potentially informative.

Best,
Alexander
