### ISSUE TITLE
MEME significant pos. sel. at invariant sites

### ISSUE THREAD

**Issue by ndwhite** [veg/hyphy#1296]
Hello,

How can I interpret MEME results that detect significant positive variation at invariate sites? This has occurred at many sites in multiple different alignments. Thanks in advance.

**Comment by spond** [comment]
Dear @ndwhite,

MEME does not even test invariable sites (at the nucleotide level) for computational speed-up; the p-values for those should all be 0.67. Can you provide an example?

Best,
Sergei

**Comment by ndwhite** [comment]
Sure, can I email you an example rather than post here?

**Comment by spond** [comment]
Dear @ndwhite,

Yes, spond at temple edu

Please send the alignment file and the `MEME.json` result. Also indicate which are the invariable sites that are flagged by MEME.

Best,
Sergei

**Comment by spond** [comment]
Closing since the issue was tracked down to an odd behavior in version 2.5.27.
