### ISSUE TITLE
MEME Input Data

### ISSUE THREAD

**Issue by juliayork** [veg/hyphy#1297]
Hello! I am using MEME to look for sites under selection in some genes of interest. My tree has quite a few reference/background species included, and I am interested in what sites seem to be under positive selection in only a certain clade of my tree. Additionally, the quality of the sequencing for my clade of interest is inconsistent (I have only partial genes for several species). I am wondering:

1) How many reference or background sequences is it best to include? I imagine more information increases power (as Sergei says in #441 ). 

2) How to best identify the sites specific to my clade of interest? For example, if I label the nodes in the clade of interest "Test" and then tell MEME to test only those branches, does it use the other branches as background or does it just ignore them? Should I run it with all the branches and then look at each site to identify the branches? I'm not entirely sure how to do this but #669 seems to suggest it should be possible.

3) Is it better to remove the incomplete sequences or include them in my clade of interest? It seems like MEME makes some decisions about which sites to test. Is it better to be super stringent and include only sites that are well-aligned or to include as much information as possible? 

Thanks so much!

**Comment by spond** [comment]
Dear @juliayork,

1. MEME does not directly make use of reference/background information. In your case, assuming the clade of interest in monophyletic, the only additional information you would get by including reference/out-group sequences would be about the evolution along the ancestral branch to the clade of interest. If you want to have this (i.e. to "polarize" substitutions), then I would include a couple of reference.
2. If you ask MEME to test selection on a subset of branches, it will treat the rest of the branches as "nuisance" -- there will be some parameters estimated for them (one needs to do that to compute the likelihood function), but they will not have a significant impact on the clade-level inference. Depending on your answer to (1), you could choose to include **only** the clade of interest.
3. Generally it is better to include everything. MEME performs test on any site that is variable -- the only sites it skips are those that are perfectly conserved in the codon space; this includes sites like 

```
ACC
ACC
---
ACC
---
ACC
ACC
....
```

but not like 

```
ACC
ACG
---
---
---
ACC
ACC
...
```

Best,
Sergei

**Comment by juliayork** [comment]
Okay, thank you. I will include some reference species then because I am interested in what occurred in the common ancestor of my clade. 

How can I determine which branches were significant for which sites? I can see in the print out the number of branches that were significant, but not which branches.

**Comment by spond** [comment]
Dear @juliayork,

MEME does not formally test for which branches are significant, but you can use empirical Bayes factors to explore which ones are contributing to the signal. 

You can load your MEME `.json` files into https://observablehq.com/@spond/plotting-meme-ebf-on-branches-at-individual-sites to view plots for individual sites.

If you are comfortable dealing with `JSON`, then all you need to do is pull out branch attributes (see below) and look for branches where this value is >>1 (e.g. > 100)

Best,
Sergei

<img width="722" alt="image" src="https://user-images.githubusercontent.com/1018513/110170149-beeb7d00-7dc7-11eb-8113-5344543e070e.png">

**Comment by juliayork** [comment]
Okay! Thank you so much for your help.

**Comment by juliayork** [comment]
Just a note that I tested out adding more or fewer reference species and how strict to be in the alignment, and checked all the significant sites by hand. I found the more data I gave MEME the more interesting sites it found. Fewer data yielded a few novel sites, but nothing that stood out in my clade of interest and there were several interesting sites it missed.

**Comment by spond** [comment]
Dear @juliayork,

Are you finding more signal **in your clade** when you add more reference sequences, or just in those reference sequences? I'd be very curious to see some examples, if you don't mind. One of the graduate students in our lab (@aglucaci) is working on a project that tries to quantify the effects of sequence sampling on selection analyses, so this may provide an interesting example to explore.

Best,
Sergei

**Comment by juliayork** [comment]
Just sent you the data for more information.
