### ISSUE TITLE
Error while running input file 

### ISSUE THREAD

**Issue by krushnach80** [veg/hyphy#1299]
```
Error:
Could not read batch file '/home/punit/Downloads/pre-msa.bf'.
Path stack:
	/home/punit/anaconda3/envs/codona_alin/share/hyphy/
	/home/punit/Downloads/

```

**Comment by spond** [comment]
Dear @krushnach80,

Please provide the entire command. Based on what you report, `HyPhy` is not finding `pre-msa.bf`. Try giving it the absolute path like in 

```
hyphy /home/punit/path/to/pre-msa.bf
```

Best,
Sergei

**Comment by krushnach80** [comment]
i m running inside a conda environment still it needs the full path?

**Comment by spond** [comment]
Dear @krushnach80,

`HyPhy` does not have a lot of sophistication when looking for files. Being in a `conda` environment does not change it. When you call the program with something other than a standard library analysis (like `busted` or `fubar`), HyPhy will only be able to find the file by 

1. Local path (`pre-msa.bf`, `../scripts/pre-msa.bf` etc)
2. Global path (eg `/home/users/hyphy-analyses/codon-aligment/pre-msa.bf`)

Best,
Sergei
