### ISSUE TITLE
Issue with BUSTED-compare.bf file order LRT test differences

### ISSUE THREAD

**Issue by lcwheeler** [veg/hyphy#1300]
Hello, 

Thanks again @spond for your help getting these pairwise tests going. I ran BUSTED for a set of samples and then used BUSTED-compare.bf to test for differences between them. While doing this, I discovered an interesting issue. The order of the supplied files changes the output. 

In the following example, the order that F1 and F2 are supplied to --fit1 and --fit2 changes the output of the statistical test. In most cases the p values are very close, but in a few cases they are orders of magnitude different. 

```
hyphy BUSTED-compare.bf --fit1 F1 --fit2 F2 --output F1_VS_F2.json
```
is different from

```
hyphy BUSTED-compare.bf --fit1 F2 --fit2 F1 --output F2_VS_F1.json
```
Is there a known explanation for this effect? I would have expected that the test would return identical results regardless of the input order of the two files being compared and I'm not sure how to interpret this output. 

Thanks, 

Luke

**Comment by spond** [comment]
Dear @lcwheeler,

Your expectation is correct : this should be commutative. 

Would you mind sharing the examples where you see big differences? I suspect this has to do with strong sensitivity to initial conditions (which will be different depending on the loading order, for some parameters). I may add a step to get around this sensitivity, so having an example would be very helpful.

Best,
Sergei

**Comment by lcwheeler** [comment]
Dear @spond, 

Thanks for checking this out! I just sent you an email with a couple of files that you can use for the test. They are the two fit files that resulted in the most extreme difference depending on input order. 

Best, 

Luke

**Comment by spond** [comment]
Dear @lcwheeler,

Issue recreated. It is due to initial starting conditions. Will update `BUSTED-compare.bf` to explore a few starting conditions, and post a note here.

Best,
Sergei

**Comment by lcwheeler** [comment]
Dear @spond, 

Awesome, thank you! 

Best, 

Luke

**Comment by spond** [comment]
Dear @lcwheeler,

I made some changes to `BUSTED-compare.bf`. Please pull down the new version and try again. I was able to obtain the same result regardless of ordering with the changed. Thanks for your useful feedback!

Best,
Sergei

**Comment by lcwheeler** [comment]
Dear @spond, 

Thank you for taking the time to figure this out! I will pull down the new version and make sure I can get it to work. I'll post here to let you know the result. 

Best, 

Luke

**Comment by lcwheeler** [comment]
Dear @spond, 

I just tested the updated BUSTED-compare.bf analysis with those same files and it is working for me too. 

Thanks! 

Luke
