### ISSUE TITLE
Labels on the tree

### ISSUE THREAD

**Issue by bsb2014** [veg/hyphy#1301]
Dear Sergei

There are four groups with different colors on my tree and I want to test for selection along the ancestral branches (Foreground) leading to each group. Could you help to have a look if my labels are correct for the purpose? 

Thanks
Eric

![36sp](https://user-images.githubusercontent.com/73562686/111121593-b9fda900-85d1-11eb-9023-1089a45d98ac.jpg)

**Comment by spond** [comment]
Dear @bsb2014,

Looks correct to me.

Best,
Sergei

**Comment by bsb2014** [comment]
Thanks:)
