### ISSUE TITLE
Not being able to use datamonkey server

### ISSUE THREAD

**Issue by tushar-ahmed** [veg/hyphy#1302]
Hello dear,

I am not being able to use the Datamonkey SLAC server. when I click Run Analysis after selecting the file, nothing happens. 
![Screenshot from 2021-03-16 02-11-10](https://user-images.githubusercontent.com/42414322/111215209-14f8c580-85fd-11eb-9ce9-4628ad98544e.png)
the webpage stays as attached picture hours after hours. I could not run the analysis on my Machine because it got killed due to computational resource shortage. 

what I am missing here? Is it a problem with the server or what? 

Thank you.

**Comment by stevenweaver** [comment]
Dear @tushar-ahmed, 

Thank you for reporting this issue. It was a problem with our web server process and should now be working as expected after restarting. 

Best,
Steven
