### ISSUE TITLE
Results not being emailed

### ISSUE THREAD

**Issue by SticaC** [veg/hyphy#1303]
I have submitted a few jobs yesterday and today, and they show up on the job queue, then finish, but results are not emailed.  The latest was ticket number 1513807.

**Comment by stephenshank** [comment]
Dear @SticaC,

I submitted http://datamonkey.org/slac/605218a34ff53378faecaadd and received an email (image attached). Are you sure they are not going to spam? If you don't find anything in your spam folder, can you send me some URLs like the one I shared of jobs that completed but did not send an email?

![image](https://user-images.githubusercontent.com/8673708/111493932-68116c00-8714-11eb-88ce-71d16d2b71f0.png)


Best,
Stephen

**Comment by SticaC** [comment]
Hello Stephen,

It is not going to spam. I am keeping track of the urls, and some get emailed upon completion, some do not, and some disappear from the job queue but are still running.

This one finished but I did not get an email:
http://datamonkey.org/fel/60529ebf4ff53378faecd09f

This one seems to still be running, but is no longer listed on the job queue:
http://datamonkey.org/fubar/60529ee74ff53378faecd12c

If I just keep a list of the submission urls, I should be able to get my results, I am just unsure why some are being emailed and some not.

Thanks

**Comment by SticaC** [comment]
Solved it. It was on my end.

Thanks
