### ISSUE TITLE
An error with RELAX

### ISSUE THREAD

**Issue by 1398206876** [veg/hyphy#1304]
Dear @spond
While I was doing a RELAX analyse. I got this error:
```
### Fitting the general descriptive (separate k per branch) model
Error:
Internal error

        ERROR: [_LikelihoodFunction::LocateTheBump (index 95) current value   -296533.2533553552 (parameter =   0.9992685062681751), best value   -296533.2533553552 (parameter =   0.9992685062681751)); delta = 5.820766091346741e-11, tolerance = 9.9999999999999

Parameter name BzvqFeVJ.tree_id_0.Node64.t

Function call stack
1 :  [namespace = txaRiMAO] Optimize(mles, ^lf_id);

-------
2 :  relax.general_descriptive.fit=estimators.FitExistingLF(relax.general_descriptive.fit[terms.likelihood_function],relax.model_object_map);
-------


Check errors.log for execution error details.
```

```
hyphy relax --alignment OG0000001.cds.txt --tree OG0000001.tree.txt
```
The file is attatched behind.

I did not align my sequence, because I found that the result after alignment was not a multiple of 3, so I deleted the termination codon  and then used it as the input.Is the alignment a problem?

Thank you for your attention！

[OG0000001.tree.txt](https://github.com/veg/hyphy/files/6164588/OG0000001.tree.txt)
[OG0000001.cds.txt](https://github.com/veg/hyphy/files/6164589/OG0000001.cds.txt)
[errors.log](https://github.com/veg/hyphy/files/6164590/errors.log)

**Comment by spond** [comment]
Dear @1398206876,

Looking into it... 

Best,
Sergei
