### ISSUE TITLE
MEME segfaults when specifying a foreground branch

### ISSUE THREAD

**Issue by a-lud** [veg/hyphy#1305]
Hi, 

I'm running some preliminary analyses using MEME on a set of genes for 4 species. I've encountered a subset of 19 genes in my total dataset (a few thousand genes) that result in a segfault when I specify a foreground branch. When no foreground branch is specified, MEME runs for all genes to completion. I've tested a couple of versions of HyPhy and it occurs regardless of version.

HyPhy versions tested: 
`HYPHY 2.5.25(MP) for Linux on x86_64` - installed using conda in a Nextflow pipeline
`HYPHY 2.5.29(MP) for Linux on x86_64` - installed using conda as a standalone environment

Terminal command
```
hyphy meme \
    --alignment OG19611_translated.fasta \
    --tree foregroundMarked.nwk \
    --output MEME-OG19611.json \
    --branches Foreground \
    --pvalue 0.05
```

The `stdout` from the above call
```
Analysis Description
--------------------
MEME (Mixed Effects Model of Evolution) estimates a site-wise synonymous
(&alpha;) and a two-category mixture of non-synonymous (&beta;-, with
proportion p-, and &beta;+ with proportion [1-p-]) rates, and uses a
likelihood ratio test to determine if &beta;+ > &alpha; at a site. The
estimates aggregate information over a proportion of branches at a site,
so the signal is derived from episodic diversification, which is a
combination of strength of selection [effect size] and the proportion of
the tree affected. A subset of branches can be selected for testing as
well, in which case an additional (nuisance) parameter will be inferred
-- the non-synonymous rate on branches NOT selected for testing.
Multiple partitions within a NEXUS file are also supported for
recombination - aware analysis.

- __Requirements__: in-frame codon alignment and a phylogenetic tree

- __Citation__: Detecting Individual Sites Subject to Episodic Diversifying Selection.
_PLoS Genet_ 8(7): e1002764.

- __Written by__: Sergei L. Kosakovsky Pond, Steven Weaver

- __Contact Information__: spond@temple.edu

- __Analysis Version__: 2.1.2


>code –> Universal

>Loaded a multiple sequence alignment with **4** sequences, **340** codons, and **1** partitions from `OG19611_translated.fasta`

>branches –> Foreground

>Select the p-value threshold to use when testing for selection (permissible range = [0,1], default value = 0.1):
>pvalue –> 0.05


### Branches to include in the MEME analysis
Selected 1 branches to include in the MEME analysis: `aipysurusLaevis`


### Obtaining branch lengths and nucleotide substitution biases under the nucleotide GTR model

>kill-zero-lengths –> Yes

### Deleted 1 zero-length internal branches: `Node2`
* Log(L) = -2489.28, AIC-c =  5004.65 (13 estimated parameters)

### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
* Log(L) = -2386.78, AIC-c =  4814.19 (20 estimated parameters)
* non-synonymous/synonymous rate ratio for *background* =   0.0373
* non-synonymous/synonymous rate ratio for *test* =   0.1632

### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
* Log(L) = -2382.85
* non-synonymous/synonymous rate ratio for *background* =   0.0468
* non-synonymous/synonymous rate ratio for *test* =   0.0686
Working on site pattern 227/276 in partition 1Segmentation fault
```

The `errors.log` file is empty, and the cluster simply reports that the job has failed. The issue is at codon 227, however I'm not sure which sites from the original 340 are being removed so I haven't been able to check the offending culprit. Again, this only happens when a foreground branch is specified. 

I've attached this example alignment file, along with the two trees (marked and unmarked) if you want to try and replicate the issue. If you've got any insights it'd be greatly appreciated.

Cheers
Al

Foreground nwk: [foregroundMarked.txt](https://github.com/veg/hyphy/files/6167625/foregroundMarked.txt)
Default nwk:[default.txt](https://github.com/veg/hyphy/files/6167626/default.txt)
Fasta: [OG19611_translated.txt](https://github.com/veg/hyphy/files/6167627/OG19611_translated.txt)

**Comment by spond** [comment]
Dear @a-lud,

Thanks for an excellent bug report. The issue seems to occur because one of the sites is "saturated" (infinite branch lengths) and there's a strange error condition being triggered. I'll look into it some more and provide a resolution.

Best,
Sergei

```
Error:
Internal error 
Constrained optimization failed, since a starting point within the domain specified for the variables couldn't be found.
Set it by hand, or check your constraints for compatibility.
Failed constraint:meme.site_tree_bsrel.aipysurusLaevis.beta_2:=557.3314128935526*19.28270375930667 must be in [0,10000]. Current value = 0.7780120915175132.
```

**Comment by spond** [comment]
Dear @a-lud,

This has been resolved in the `develop` branch and will be included in the next release. I would like to suggest that MEME should not be used to test for site-specific selection on alignments with 4 sequences (especially if the test set is a single branch). There's no power to detect selection in these settings. BUSTED/aBSREL aggregate information across sites and branches, and are much more powerful.

Best,
Sergei

**Comment by a-lud** [comment]
Hi @spond,

Thanks for the details on what's going on, I'll be sure to update the pipeline at the next release.

> I would like to suggest that MEME should not be used to test for site-specific selection on alignments with 4 sequences

Noted. This was a test run of the Nextflow pipeline (regardless of data + model suitability) but will be sure to keep this in mind.

I am going to be using this pipeline for some analyses  with this data, and did have a (potentially very ignorant) clarification about running BUSTED and aBSREL. If the same test branch is specified to both BUSTED and aBSREL, are they essentially testing a similar hypothesis? e.g.

* BUSTED is testing whether there is a non-zero number of sites experienced positive, diversifying selection along the test branch. 
* aBSREL is testing whether some proportion of sites is subject to positive selection along the test branch.

Is that somewhat in the ballpark?
Would you have a recommended approach to using BUSTED/aBSREL for a dataset like this?

Thanks for the help
Al

**Comment by spond** [comment]
Dear @a-lud,

When the foreground is a single branch, BUSTED and aSBREL perform the same test but with slightly different models.
The test is : is there evidence of dN>dS on some non-zero fraction of sites along the foreground branch, i.e. is there evidence of episodic diversifying selection on this branch.

The differences in models are as follows.

1. For BUSTED, the foreground branch and background branches will receive separate distributions of &omega; each with `K` bins. `K=3` by default but can be specified as a CLI argument.
2. For aBSREL, HyPhy will automatically determine the appropriate `K` for each branch, including the foreground. This can take longer to run, especially for larger alignments, but will generally be better if your goal is to identify selection at branch level.

BUSTED is best thought of a `gene-level` test.

Best,
Sergei

**Comment by a-lud** [comment]
Thanks for the info and help @spond, its been a huge help. 

Cheers
Al
