### ISSUE TITLE
Gene tree includes gene duplications in some taxa

### ISSUE THREAD

**Issue by mlosilla** [veg/hyphy#1306]
Hi,

Thank you for making HyPhy available.

I want to study selection on a gene and clade. After a certain node, there are gene duplications and losses along the gene tree, resulting in some taxa with one gene copy, other taxa with 2 paralogs, and still other taxa with 3 paralogs. I want to confirm that the correct way to analyze this is to align all paralogs and taxa in one single alignment and use this to run the tests of selection. 

Any advice is welcome

Thanks
Mau

**Comment by spond** [comment]
Dear @mlosilla,

Gene family evolution analyses, unfortunately, do not follow standardized rules. The short answer: yes, you can align parlors and do a joint analysis.

There are two concerns to keep in mind.

1. Do you suspect any evidence of recombination / gene conversion? If so, you should pre-screen your alignment for possible evidence of recombination and proceed accordingly (you can look at our very old paper on this [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2174272/))

2. What happened to gene copies? Are they performing the same function, are some being pseudogenized, are some undergoing neo-functionalization? Depending on your answer to this, the interpretation of analysis results may differ somewhat. 

Best,
Sergei

**Comment by mlosilla** [comment]
Hi Sergei,

thank you for your reply and for that paper. There is not much I can say conclusively about your concerns: 

1) I do not suspect there has been recombination/ gene conversion, but I am planning to run GARD on my alignment to test for it. 
2) As far as I can tell, all the gene copies I amplified and sequenced are functional (based on size, intron-exon boundaries, start and stop codons). I cannot say anything about their function at this point. It is likely that I didn't amplify all the paralogs though, I am studying a clade with few genomic resources available. 

My data consists of ~40 sequences, the protein produced has ~215 amino acids. Since I am interested in learning all I can about how selection has acted on this gene, my plan is to run the following tests:

- GARD
- BUSTED (If GARD finds no evidence of recombination)
- aBSREL (If GARD finds no evidence of recombination) [I still don't know if I should select any test branch or branches a priori]. 
- MEME 
- FUBAR or FEL (I don't know which one is best suited for the size of my dataset, but I am leaning towards FUBAR, based on resources I found on your website)
- RELAX 

Does this make sense? Again, suggestions and comments are most welcome.

Thanks!
Mau

**Comment by spond** [comment]
Dear @mlosilla,

You can run BUSED/MEME/FEL/FUBAR on data with recombination (just feed in the partitioned file produced by GARD). What you propose make sense. Depending on your tree structure and gene history, you may also find it informative to run selection analyses on **subsets** of branches which define only orthologs, or species-level paralogs for example (RELAX, Contrast-FEL etc).

With `40` sequences you should have decent power  to detect selection on the gene as a whole and on individual sites.

Best,
Sergei

**Comment by mlosilla** [comment]
Thanks Segei, I will definitely keep those suggestions in mind.

The following are not related to the title of this issue. 

1) I have failed to upload a topology to datamonkey, along with my alignment. Based on what I have read, I am under the impression that all I need to do is to paste the tree in newick format at the end of the fasta file with my alignment; or inside a nexus file that also has the alignment. I have failed at both approaches. The alignment in the fasta file is properly recognized, but the tree is ignored, as best as I can tell (the selected method only offers me the tree it infers). 

Noteworthy, There are a few identical sequences in my data. I know these are removed from the alignment, but I don't know if these affect the supplied tree. In any case, I made a fasta file with the alignment and the tree, both without duplicated sequences, and it still failed. 

2) Regarding duplicated sequences, I have a layman's methodological question: I understand they are removed to speed up the analyses, but wouldn't their presence matter for some results? For example, for the estimation of p+ (site-specific weight assigned for the positive selection category) in MEME

**Comment by spond** [comment]
Dear @mlosilla,

1. Can you attach the FASTA file with the tree? What you describe should work.
2. Datamonkey should remove duplicates sequences **and** trim the tree accordingly. 
3. Duplicate sequences do not contribute any information other than slightly changing overall nucleotide frequencies of the alignment. `p+` is better thought of the fraction of total tree length (not the # of sequences) that is subject to selection, rather than a fraction of the number of sequences.

Best,
Sergei

**Comment by mlosilla** [comment]
Hi Sergei,

Thanks for your reply. I insisting a bit more and found the problem: there was a very small difference in some taxon names between the alignment and the tree. 

As a suggestion, I would find it useful if the file check procedure could flag these types of errors. Along these lines, I have noticed that when an alignment is provided in .phy format, datamonkey accepts it but doesn't read it correctly. The selected method starts running, but it interprets each character in the sequence name as a character to analyze. 

Thanks
Mau

**Comment by spond** [comment]
Dear @mlosilla,

>there was a very small difference in some taxon names between the alignment and the tree.

Can you elaborate? HyPhy will sometimes rename sequences to convert them into identifiers (e.g. "sequence 1" => "sequence_1").

> .phy format, datamonkey accepts it but doesn't read it correctly

The original Phylip format only allowed 10 characters for the name of the sequence (e.g. http://scikit-bio.org/docs/0.2.3/generated/skbio.io.phylip.html). Anything past that will be viewed as a part of the sequence. HyPhy assumes that Phylip files are in this strict format.

Best,
Sergei

**Comment by mlosilla** [comment]
I don't have the uncorrected sequences anymore, but broadly there were differences like these:

taxon_and_gene_name_2.1    vs    taxon_and_gene_name_2_1
taxon_and_gene_name_2.1    vs    taxon_and_gene_name_2.1_

I understand what you say about the Phylip format. As a suggestion, I think a warning would be useful for the user-- since the analysis starts and runs, one could easily think there is nothing wrong with the file.

Thanks!
Mau
