### ISSUE TITLE
Contrast-FEL >[WARNING] The cumulative branch length in the _Lab_ class is 0.

### ISSUE THREAD

**Issue by joanmarticarreras** [veg/hyphy#1307]
Hi! I've been recently interested in comparing the dN/dS and identify possible aa changes between genes of 2 groups of viral strains (MCMV): wild-type and lab-attenuatted used in some animal studies. I've decided to use Contrast-FEL for the comparison of the 2 groups (+ some extra sequences to provide background).

For most of the genes  I receive following warning:

```>[WARNING] The cumulative branch length in the _Lab_ class is 0. Rates                                                                                                                                 along these branches are not identifiable; testing will not be formally                                                                                                                                conducted (all p-values set to 1).```

Is there any way to lower the threshold for cumulative branch length (they are in fact not 0 but at the order of 0.0000023698) and allow the calculations to happen? In case it is not possible, what alternative would you recommend? I was thinking to use SNPGenie to calculate the dN/dS (all vs all within each group) and then do a Fisher's Exact Test to compare the dN/dS between the 2 groups.

If needed, I attach the relevant files below

[MuHV1_gp158_iqtree_annotated.contree.txt](https://github.com/veg/hyphy/files/6190366/MuHV1_gp158_iqtree_annotated.contree.txt)
[MuHV1_gp001.json.txt](https://github.com/veg/hyphy/files/6190367/MuHV1_gp001.json.txt)
[MuHV1_gp001_analysis_set_nonSTOP.fa.txt](https://github.com/veg/hyphy/files/6190368/MuHV1_gp001_analysis_set_nonSTOP.fa.txt)
[MuHV1_gp001_report.txt](https://github.com/veg/hyphy/files/6190369/MuHV1_gp001_report.txt)

Thanks a lot!

Joan

**Comment by spond** [comment]
Dear @joanmarticarreras,

You have designated three branches as `Lab`. In your alignment the three sequences corresponding to those branches (all in the same clade) are exactly identical. Because of this, the cumulative inferred branch length on the `Lab` group is exactly 0 (no variation) and **no inference is possible**. It does not matter what method you use, because you cannot estimate dN/dS for the `Lab` group (0/0 effectively).

Best,
Sergei

**Comment by joanmarticarreras** [comment]
Dear Sergei,

Under that premise, make sense that the inference is not possible. Still is it possible that all `Lab` sequences are identical and the `WT` may have variation that may explain the two observed phenotypes? If so, are there in HyPhy or other programs, a way to test it?

Thanks!

Joan

**Comment by joanmarticarreras** [comment]
Dear @spond 

I start checking manually the alignments of those genes that the `Lab` sequences may be identical (`cumulative branch length in the _Lab_ class is 0`). 

I found that not all of them are identical (albeit very similar). An example can be found attach with gp30 (see attachments). In that group, 2 sequences are identical (KY348373 and GU305914) and 1 (AM886412) has 1 NSyn and 1 Syn change with respect to the other 2. In the phylogenetic tree, they appear as closely related at the base of the tree. 

The group is non-identical but the `cumulative branch length` is flagged as 0. Is it because there are only 2 differences in AM886412 with respect to the rest? Still, 2/3 of the possible combinations between KY348373, GU305914 and AM886412 should render a dN/dS, right?

I know it might be out of the scope of the tool, but based on the most common application I can think for `Contrast-FEL` (comparing treatment groups, trials, compartments, etc), even if it's not possible to calculate the dN/dS, it would be interesting to print as secondary output file, the positions in which a NSyn change is conserved within group but divergent between group. That type of change might be relevant for the comparison between the groups, yet no dN/dS can be calculated. Is there maybe an accessory script in HyPhy-analysis? 

[MuHV1_gp030_report.txt](https://github.com/veg/hyphy/files/6196416/MuHV1_gp030_report.txt)
[MuHV1_gp030_analysis_set_nonSTOP.fa.txt](https://github.com/veg/hyphy/files/6196417/MuHV1_gp030_analysis_set_nonSTOP.fa.txt)
[MuHV1_gp030_iqtree_annotated.contree.txt](https://github.com/veg/hyphy/files/6196418/MuHV1_gp030_iqtree_annotated.contree.txt)
[MuHV1_gp030.json.txt](https://github.com/veg/hyphy/files/6196419/MuHV1_gp030.json.txt)

**Comment by spond** [comment]
Dear @joanmarticarreras,

Your `lab` set (blue in the image below) does **not** include any internal branches. All of the variation occurs on the internal branch (shown with the red arrow). You should consider defining the entire clade as a branch set.

Regarding your question about finding differences. While there is no script to do exactly what you are interested in, there is a way to do it with existing scripts. If your groups are reciprocally monophyletic, then any fixed differences between them will occur on the branch separating the two groups (shown with the blue arrow).

You can use two existing scripts

1. [FitMG94](https://github.com/veg/hyphy-analyses/tree/master/FitMG94) to perform a model fit
2. [AncestralSequences](https://github.com/veg/hyphy-analyses/tree/master/AncestralSequences) to map substitutions to specific branches. 

First, give the branch which separates the groups a descriptive name in the Newick file, e.g. `SEPARATOR` as shown below 

```
(MuHV1_gp030_-__AM886412{Lab}:0.0000020044....,MuHV1_gp030_-__MCMV_HaNa1_231348{WT}:0.0021379025)SEPARATOR:0.0010581446)
```

Then, run

```
$hyphy ~/Development/hyphy-analyses/FitMG94/FitMG94.bf --alignment  MuHV1_gp030_analysis_set_nonSTOP.fa.txt --tree MuHV1_gp030_iqtree_annotated.contree.txt --save-fit MuHV1_gp030.fit
$hyphy ~/Development/hyphy-analyses/AncestralSequences/AncestralSequences.bf --fit MuHV1_gp030.fit --output MuHV1_gp030.ancestors.json
```

The second analysis will print out the list of all substitutions like so.

|        Site        | Substitution  |                     Branches                     |
|--------------------|---------------|--------------------------------------------------|
|         5          |   GCC->GTC    |            (1) MuHV1_gp030___HE610451            |
...
|         16         |   GAG->GGG    |            (1) MuHV1_gp030___MG957497            |
|         17         |   ACG->ATG    |                  (1) SEPARATOR                   |
|         19         |   ACG->GCG    |            (1) MuHV1_gp030___MG957497            |
...

It will also create a `JSON` file (`MuHV1_gp030.ancestors.json`), documented at [AncestralSequences](https://github.com/veg/hyphy-analyses/tree/master/AncestralSequences) that you can parse and process programmatically.

Best,
Sergei

![image](https://user-images.githubusercontent.com/1018513/112317731-baa5d780-8c82-11eb-9c69-07874ec09ddb.png)
