### ISSUE TITLE
FUBAR crashing / unable to read file

### ISSUE THREAD

**Issue by andreaniml** [veg/hyphy#1309]
Good evening, 
I've been running into a problem while trying to run FUBAR in the command line

Running fubar with --alignment and --tree options starts the analysis, but it crashes shortly after claiming that fscanf could not read the tree file.

```
Error:'/home/juliana/Malu/Tamires/refazendo_final/ybab_final/macse/selecao/fubar/2021_ybab_cds_final_sequences_nodup_mafftAA_alignment.fasta.treefile' could not be opened for reading by fscanf. Path stack:
        /home/juliana/anaconda3/envs/selection/lib/hyphy/
        /home/juliana/anaconda3/envs/selection/lib/hyphy/TemplateBatchFiles/SelectionAnalyses/ in call to fscanf(PROMPT_FOR_FILE,"RawREWIND, ",treeString, );
'/home/juliana/Malu/Tamires/refazendo_final/ybab_final/macse/selecao/fubar/2021_ybab_cds_final_sequences_nodup_mafftAA_alignment.fasta.treefile' could not be opened for reading by fscanf. Path stack:
        /home/juliana/anaconda3/envs/selection/lib/hyphy/
        /home/juliana/anaconda3/envs/selection/lib/hyphy/TemplateBatchFiles/SelectionAnalyses/ in call to fscanf(PROMPT_FOR_FILE,"RawREWIND, ",treeString, );
```

I use conda to manage hyphy in a server, maybe it is an installation/path problem? I've tried to include "~/the path/to/file" on the command line, but the error persists

Thanks,
Maria

**Comment by stevenweaver** [comment]
Dear @andreaniml, 

This is strange, and I believe it might be due to using a pre-compiled binary from conda on an incompatible system. 
Which distribution of linux are you using?

Best,
Steven

**Comment by andreaniml** [comment]
Dear Steven,

The server runs on SUSE Linux Enterprise Server 12 SP1

I don't know if this helps to troubleshoot, but I've run absrel on the same dataset (although I selected foreground branches for the analysis) and as far as I can tell it didn't run into any problems (no errors.log file, json file created).

Thanks for the fast reply!
Maria

**Comment by spond** [comment]
Dear @andreaniml,

Are there any other error messages, specifically a more detailed trace-back of where the error occurs in the `FUBAR` analysis?

Does the file `/home/juliana/Malu/Tamires/refazendo_final/ybab_final/macse/selecao/fubar/2021_ybab_cds_final_sequences_nodup_mafftAA_alignment.fasta.treefile` exst?

If not, where **does** the `2021_ybab_cds_final_sequences_nodup_mafftAA_alignment.fasta.treefile` exist?

Best,
Sergei

**Comment by andreaniml** [comment]
Dear Sergei,
The file should exist within the folder where FUBAR is being called, however, I just noticed that there is a typo on the name file.
Fixing the typo solved the problem

Thank you!
Maria

**Comment by spond** [comment]
Dear @andreaniml,

Glad it was an easy fix :)

Best,
Sergei
