### ISSUE TITLE
Contrast-FEL result display on datamonkey

### ISSUE THREAD

**Issue by mlosilla** [veg/hyphy#1310]
Hi,

I noticed a strange output in the Contrast-FEL results page on datamonkey (http://datamonkey.org/contrast_fel/605d308cf0fa7819ac2ce8f7). 

It reads: 
"ContrastFEL found evidence of
 Found 38 sites with different Overall dN/dS
with p-value threshold of 0.1"    (see attached screenshot)

But the text I get when I click on the clipboard at the top right is:
"Contrast-FEL found evidence of pervasive positive/diversifying selection at 0 sites in your alignment. In addition, Contrast-FEL found evidence with p-value 0.1 of pervasive negative/purifying selection at 0 sites in your alignment. Contrast-FEL did not find evidence for either positive or negative selection in the remaining 227 sites in your alignment."

How should I interpret these results?

thank you

![Screenshot from 2021-03-25 21-43-17](https://user-images.githubusercontent.com/9287478/112565826-381d3500-8db4-11eb-8fe8-1dfbfbed4449.png)

**Comment by spond** [comment]
Dear @mlosilla,

Thanks for bringing this to our attention, looks like there is an issue in the code that generates the clipboard snippet. @stephenshank or @stevenweaver : can you please take a look?

Best,
Sergei

**Comment by mlosilla** [comment]
Thank you. In the meantime, which of the two is the correct text?

**Comment by spond** [comment]
Dear @mlosilla,

The test displayed on the page (38 sites).

Best,
Sergei

**Comment by mlosilla** [comment]
Potentially related issue: FUBAR results say:

FUBAR found evidence of:
 episodic positive/diversifying selection at 6 sites
 episodic negative/purifying selection at 44 sites
with posterior probability of 0.9

is the word "episodic" correct? shouldn't it be "pervasive" instead? 

I thought MEME was the site-test to detect episodic selection, whereas FEL and FUBAR detect pervasive selection (positive and negative). Congruent with this, FEL's output says "pervasive" instead of "episodic", and MEME's says "episodic".

**Comment by spond** [comment]
Dear @mlosilla,

You are correct. `Episodic` should instead be `pervasive`. @stephenshank @jzehr  : please fix ASAP.

Best,
Sergei

**Comment by jzehr** [comment]
PR created to address the FUBAR results page verbiage.
