### ISSUE TITLE
RELAX group mode #2

### ISSUE THREAD

**Issue by mlosilla** [veg/hyphy#1311]
Hi,

This is related to this closed issue: https://github.com/veg/hyphy/issues/1285

I was wondering if:

1. can group test mode be executed through datamonkey? how?

2. If relax group mode detects significant differences, is it possible to run a posteriori tests between the groups? what tests would these be and what parameters should be tested?
 
3. if instead of group mode, pairwise tests are performed one pair at a time, is there a need for multiple test correction?

4. what is the minimum number of sequences that must be included in the reference group?

Thanks
Mau

**Comment by spond** [comment]
Dear @mlosilla,

1. Not at the moment. @jzehr -- can you put this on the list of feature requests.
2. The group test is an omnibus test -- it does not tell you **which** groups are different. One way to delve deeper is to run pairwise comparisons as separate analyses (you'll need to correct for multiple testing). For example if you have 4 groups with a significant group-level result, you can then perform 6 pair tests (G1 vs G2, G1 vs G3 etc) as separate analyses.
3. Yes
4. Technically there is no minimum, but as a rule of thumb, I recommend no fewer than 3.

Best,
Sergei

PS You can also try https://github.com/veg/hyphy-analyses/tree/master/RELAX-scan

**Comment by mlosilla** [comment]
Hi Sergei,

thank you for the info. I am very interested in RELAX-scan, but I failed to install/run it. Here is what I have:

1) Other than datamonkey, I can use a computer cluster (CentOS 7) to run hyphy. I figured I need the latter to use RELAX-scan

2) I don't have sudo privileges on this cluster. I was able to install hyphy with conda install hyphy as in https://github.com/veg/hyphy I did it in a dedicated conda environment. 
          hyphy --version outputs: HYPHY 2.5.30(MP) for Linux on x86_64
          However, I don't think I RELAX-scan is included here is it?
          
3) I tried to install Hyphy Standalone Analyses (https://github.com/veg/hyphy-analyses) but it didn't work. Is this a standalone installation or must it be installed after hyphy 2.5.30?

Thanks
Mau

**Comment by spond** [comment]
Dear @mlosilla,

You should just check out the https://github.com/veg/hyphy-analyses repo, and then run the corresponding `.bf` with the `2.5.30` installation.

Best,
Sergei

Best,
Sergei

**Comment by mlosilla** [comment]
Hi Sergei,

I have checked out the repo, but it is unclear to me what I must do. I tried the following:
Downloaded the file: Relax_scan/RELAX.bf
Saved it as RELAX_scan.bf in the folder: hyphy/share/hyphy/TemplateBatchFiles/SelectionAnalyses/ (this is the folder where HyPhy 2.5.30 stored RELAX.bf and the other Selection Analyses .bf files)
Ran it as: hyphy <path to Relax_scan>/RELAX_scan.bf   --alignment <path to my alignment>/alignment.fasta  (this file includes a newick tree)

The execution failed shortly, attached is the file errors.log

Thanks
[errors.log](https://github.com/veg/hyphy/files/6246235/errors.log)
