### ISSUE TITLE
How to choose test and reference branches

### ISSUE THREAD

**Issue by mlosilla** [veg/hyphy#1312]
Hi, 

I am not 100% sure about how to choose test and reference branches for methods like aBSREL, BUSTED, FEL, RELAX, Contrast-FEL, FADE. To be clear, I am not asking about the procedures, commands, flags, options, etc that one must use to select test and reference branches. I am inquiring about how to choose the correct branches in order to match the desired biological question, or to make an adequate selection for the desired method. 

My question is similar to specific cases discussed in these two closed issues, but I would like to make sure how to generalize:
https://github.com/veg/hyphy/issues/1301  
https://github.com/veg/hyphy/issues/1100  (I will use a modified gene tree from this thread for my questions [attached])

Scenario 1: 
I want to study patterns of selection on the gene in samples 0-15 (blue branches). What does it mean to choose as test branches:
	case A): the purple branch labeled with A 
	case B): all the blue branches
	case C): only the terminal blue branches

Scenario 2:
Let's pretend blue, green, and red clades live on land, and the orange clade lives in water. Furthermore, most of the orange taxa live in saltwater, but samples 20-23 live in freshwater, and sample 28 lives in both salt and freshwater (euryhaline). I am interested in patterns of selection correlated with each of these environments. What branches must I choose as test and reference to compare:
	case A): land vs water 
	case B): saltwater vs freshwater vs euryhaline
	
I hope this is helpful for other users, and if it is OK, I may add more scenarios later

Thanks
Mau

![75934525-bb3ab880-5e4a-11ea-97cb-712ba4fd5976](https://user-images.githubusercontent.com/9287478/112732688-d83ca080-8f11-11eb-9721-3c29bf92a4ef.png)

**Comment by spond** [comment]
Dear @mlosilla,

1. Different choices of test branches imply different hypotheses. 
       1. If you choose all blue branches that would most closely align with "evolution within the sample group".
       2. If you choose the purple branch 'A', that would be "evolution on the lineage leading to the emergence of the sample group" (ancestral selection).
       3. Terminal branches in the blue clade are somewhat harder to interpret: probably most closely corresponding to "recent evolution" (assuming branch = species, rather than branch = isolate).

2. Both of those partitions make sense. "Water" vs "Land" is presumably a more dramatic difference, and this grouping will result in both "Test" and "Reference" groups having many branches (better power). Include all (internal and leaf branches) in the partitions, except the B branch (which is between the two groups, so it's unclear where to assign it). The 3-way partitioning is also interesting because you are testing for finer difference within group. They answer different questions.

HTH,
Sergei

**Comment by mlosilla** [comment]
Hi Sergei, 

Thank you very much, this is very useful. 

Regarding scenario 2B, what would be the best way to select the branches? is it the following?:
Saltwater: all branches with a grey star
Freshwater: all branches inside the wine circle, but not branch E
Euryhaline: F 
What about the branches with the question mark?  Those are ancestral to species that live in different environments. I think the most parsimonious explanation is that all these ancestors lived in saltwater, but I wonder if they should be selected in the saltwater group.

Thanks
Mau
![75934525-bb3ab880-5e4a-11ea-97cb-712ba4fd5976](https://user-images.githubusercontent.com/9287478/113199576-47c5cf00-9235-11eb-9c00-2e208840b11d.png)

**Comment by spond** [comment]
Dear @mlosilla,

Up to you. The unobserved "phenotype" states of internal branches can be inferred using a variety of approaches and then used for labeling. Parsimony is a sensible way to go, in which case you would include `E` with the saltwater branches. If you are uncertain about the placement of `?` branches, I would suggest excluding them from the analysis. Another option is to perform a sensitivity analysis: one with and one without including the `?` branches.

Best,
Sergei

**Comment by mlosilla** [comment]
That sounds good Sergei, thank you very much!
