### ISSUE TITLE
How to specify branches to test for selection in BUSTED?

### ISSUE THREAD

**Issue by williamorsi** [veg/hyphy#1313]
Hello,

I am running BUSTED (in HyPhy) through the command line, and want to test specific branches in the phylogeny for selection.  I see that there is an option --branches, but if I enter the names of the branches in " " then I get an error saying:

>branches –> 3_3 6_9 6_J 6_2 3_1
Error:
'3_3 6_9 6_J 6_2 3_1' is not a valid choice passed to 'Choose the set of branches to test for selection' ChoiceList using redirected stdin input or keyword arguments. Valid choices are
	All, Internal, Leaves, Unlabeled branches

Is there a way to enter the names of specific branches to test for selection in BUSTED?  

If I run the --branches default (All), and look at the output in HyPhy Vision, I dont see any branch omega values, but rather only a single omega value for the entire alignment, followed by a site specific plot of log likelihoods.  

Can you please advice how to visualize the dS and omega values for each branch using BUSTED?

Thank you!

Bill Orsi

**Comment by spond** [comment]
Dear @williamorsi,

1. You need to designate a set of branches in the tree -- providing a list of individual branches is not supported. See http://www.hyphy.org/tutorials/phylotree/ for one way to do that. A labeled tree looks like 
```
((a,b), (c,d), (e{Test},f{Test}){Test})
```

2. BUSTED uses the same distribution of &omega; for **all** branches in the test set by design. This allows to boost detection power and perform hypothesis testing. If you are interested in branch level inference, aBSREL is the better test. Very few analyses compute `dS`, however. `aBSREL` will give you branch level &omega; and branch lengths. You can extract `dS` from the resulting model fit, if you are interested. Requires a custom script. 

3. Another option is to simply use the MG94 model (https://github.com/veg/hyphy-analyses/tree/master/FitMG94). You can run something like

```
hyphy FitMG94.bf --alignment CD2.nex --type local
```

This will fit a model with separate dN/dS for each branch. In the resulting `JSON` file, each branch will contain a record like

```
"CAT":{
       "Confidence Intervals":{
         "LB":1.238162565357825,
         "MLE":1.598677873541763,
         "UB":2.0344664979999
        },
       "Nucleotide GTR":0.2660909949437275,
       "Standard MG94":0.2763729698024666,
       "dN":0.2877168117085363,
       "dS":0.233974234617924,
       "nonsynonymous":0.2269863033773656,
       "original name":"CAT",
       "synonymous":0.04938666642510114
      },
```
`"Confidence Intervals"` refers to the branch level dN/dS estimate (point estimate 1.5987 confidence interval [1.238, 2.034])

Best,
Sergei

**Comment by williamorsi** [comment]
Dear Sergei

Thank you so much for the fast and detailed response!   Since we already have run aBRSEL on all the data already, and we have those result files, it would probably be easiest for us to use the "custom script" approach for calculating dS.  Since, our whole reason for using BUSTED was to try to calculate dS.    Do you have such a custom script that you would be able to share with me, or if not are you able to provide some information on what needs to be extracted from the .json output files of aBRSEL to obtain the dS?    

Thanks again very much

Bill

**Comment by spond** [comment]
Dear @williamorsi,

The custom script approach requires that you saved complete model fits (via `--save-fit` flag in BUSTED for example). May I ask why you are primarily interested in `dS`? Essentially all those are are synonymous branch lengths normalized by the crudely estimated fraction of synonymous sites in the alignment (page 14 of http://www.hyphy.org/resources/hyphybook2007.pdf). 

Best,
Sergei

**Comment by williamorsi** [comment]
Dear Sergei,

We are trying to calculate dS in response to a reviewer comment that we received on our manuscript , where we used aBRSEL to calculate dN/dS (omega) for a bacterial core genome alignment.  Here is a link to the pre print:

https://www.biorxiv.org/content/10.1101/2020.12.19.423498v2

The reviewer comment, is that they think if dS is too small that the dN/dS ratio is not reliable.  

Reviewer comment:

". I do have two major issues that the authors should address, though. The first is related to details of the dN/dS calculations (there is not enough detail). I don't understand the calculation of dN/dS. Please extend the materials and methods (maybe a supplemental table would be good) so that readers can clearly see which genomes were compared to calculate genome-wide dN/dS in each case. Also, please report values for dN and dS separately, I am a bit concerned about dS being too small for reliable ratios. Sometimes the models underlying the calculation can behave poorly if dN or (especially) dS is too small. "

Therefore, we are trying to calcluate the dS to provide that in our revision.


If you have any suggestions on how to respond to the comment that would be great.  I have a feeling that the reviewer is not familiar with the aBRSEL method that we used.   I have now run the FitMG94.bf approach in hyphy (thanks for the tip, it works great!), which works and provides the dS and dN values.  They appear to be 'normal' in the sense they are all in the range ca. 0.01-0.001 ...

Thank you again for your helpful assistance!

**Comment by spond** [comment]
Dear @williamorsi,

That's a curious request. `aBSREL` does **not** estimate dN and dS separately, but rather their **ratio** directly. The magnitude of `dS` should not matter. Our standard recommendation here is as follows

1. Do not use point estimates of dN/dS (&omega;) directly to make inference. 
2. Instead either use a test where &omega; is compared against one (or some other value) and a p-value is generated. This takes care of uncertainty in estimate.
3. Another approach is to provide a confidence interval or error bounds on parameter estimates. FitMG94 will do that for you.

In your case you have very low dN/dS estimates, which generally are not subject to very high absolute estimation errors, but it doesn't hurt to check.

Cool preprint by the way. Thanks for sharing.

Best,
Sergei

**Comment by williamorsi** [comment]
Thanks for this info!

Could you please provide a reference for the FitMG94 code?  I would like to cite in the manuscript.

Best 

Bill
