### ISSUE TITLE
aBRSEL or FitMG94 for most accurate dN/dS values?

### ISSUE THREAD

**Issue by williamorsi** [veg/hyphy#1316]
Dear Sergei,

I have now run our dataset (34 core genomes of bacteria) through aBRSEL and FitMG94 in hyphy, in order to estimate dN/dS.  

Most of the values are similar between the methods, but some values are rather different for some of the genomes, depending on the method used.  For example, some genomes with very low dN/dS in aBRSEL have much higher dN/dS in FitMG94.

Could you give your opinion, on which method is 'more correct' ? aBRSEL appears to model the dN/dS for different regions of the alignment independently so this seems maybe like it should be more accurate, as opposed to one single dN/dS for the whole alignment?

Thanks again!

Bill

**Comment by spond** [comment]
Dear @williamorsi,

Can you please provide an example? `FitMG94` with the `--model local` option is the baseline aBSREL model, so they should not be too divergent.

Best,
Sergei
