### ISSUE TITLE
aBSREL error with no results reporting

### ISSUE THREAD

**Issue by chbabin** [veg/hyphy#1323]
Hello,
I have been trying to run aBSREL (selecting all branches) on an multiple sequence alignment with 114 sequences and a newick tree added to the fasta file.  I keep receiving this error before any results are reported.: 
![image](https://user-images.githubusercontent.com/80733903/115816085-d7d2e080-a3bd-11eb-9ff3-ce6f00753ec1.png)
This is the log file created up until the error:
[log.txt](https://github.com/veg/hyphy/files/6362641/log.txt)
I've run aBSREL previously with other MSAs and combined newick tree fasta files and have not had any issues.  I'm unable to identify the problem.  Any assistance is greatly appreciated.

**Comment by spond** [comment]
Dear @chbabin,

This error is due to a numerical instability (the error is cryptic, sorry). That, in turn, is usually caused by data with long branches (saturation). It looks like this dataset has several highly divergent sequencing

```
### Determining the optimal number of rate classes per branch using a step up procedure

|              Branch               |  Length  |  Rates   |     Max. dN/dS     |    Log(L)     |     AIC-c     |Best AIC-c so far|
|-----------------------------------|----------|----------|--------------------|---------------|---------------|-----------------|
|              PR_7064              |1291.08...|    2     |    0.11 (91.73%)   |  -133037.35   |   267001.41   |    267001.41    |
|              PR_7064              |1291.08...|    3     |    2.06 (37.31%)   |  -133037.32   |   267005.37   |    267001.41    |
|              CI_8263              |1290.34...|    2     |    1.13 (58.84%)   |  -132991.32   |   266913.37   |    266913.37    |
|              CI_8263              |1290.34...|    3     |    1.20 (33.44%)   |  -132991.32   |   266917.40   |    266913.37    |
```

Would you mind looking at your alignment to ensure that the 4 sequences are properly aligned?

Best,
Sergei

**Comment by chbabin** [comment]
Hi Jordan and Sergei,
Thank you for your responses.  I used a translation alignment and backtranslated for these NT sequences.  One of those sequences is an outgroup (CI_8263) used to make the tree in RAxML.  I thought perhaps the alignment or tree is the problem, but the data run n well in BUSTED, MEME, and FUBAR so I was not sure.  Here is the data file if it is useful.  I am using the full sequences for the translation alignment/backtranslation.  Thank you for your assistance!
[NEW_HyPhy_NEW_AllHIF_NT.txt](https://github.com/veg/hyphy/files/6366245/NEW_HyPhy_NEW_AllHIF_NT.txt)
