### ISSUE TITLE
Using hypht with seqs in different length

### ISSUE THREAD

**Issue by biozhangzhou** [veg/hyphy#1324]
Hello, Sergei:
There are many genes with pre-stop codon or frame-shift variants. They are actually have different length and gene structure but still have good consenses. But this may bring some Input errors for Hyphy.
What should I do to detect selection on this kind of genes particularly when I using hyphy.

Thanks.
JXAU Zhangzhou

**Comment by jzehr** [comment]
Dear @biozhangzhou,

Do you have an example of a codon-aware alignment for the genes you are mentioning? An alignment should create sequences of the same length (even if some genes are longer than others unaligned).

If sites in the alignment are extremely gappy, the tools might not have enough power to detect signal at that location. 

Best,
Jordan

**Comment by biozhangzhou** [comment]
Thank you for you reply. Here is a example. Could you tell me some others tools or ways to analysis this kind of alignment files.
![Screen Shot 2021-04-23 at 9 14 37 PM](https://user-images.githubusercontent.com/42492970/115876454-eaf6b680-a478-11eb-95dc-8cadcd73ce09.png)

**Comment by biozhangzhou** [comment]
Thank you for you reply. Here is a example. Could you tell me some others tools or ways to analysis this kind of alignment files.
![Screen Shot 2021-04-23 at 9 14 37 PM](https://user-images.githubusercontent.com/42492970/115876454-eaf6b680-a478-11eb-95dc-8cadcd73ce09.png)

**Comment by jzehr** [comment]
Dear @biozhangzhou, 

If this file is  a codon-aware alignment *and* you have a hypothesis you want to test about selection using an inferred phylogenetic tree, HyPhy is a great option. But ultimately selecting a tool for analyses comes down to what question you want to ask, what hypothesis you want to test. 

Best,
Jordan

**Comment by biozhangzhou** [comment]
Dear Jordan:

This alignment are extract from  a more wide level alignment(genome alignment). One of the ref seq are codon aware( extracted using the gff file). 
Seqs without a frame-shift missing or variants meets the Hyphy input file format. So I can using absrel to detect
the selection. The seqs with indels may under great selection pressure too but they don't meet the format.
All in all , I just wanna know is a indel inside a alignment impact the seq and make it  under selection?
