### ISSUE TITLE
This job appears to have expired 

### ISSUE THREAD

**Issue by phoeberobinson** [veg/hyphy#1325]
I'm trying to run an alignment using MEME yet the error 'This job appears to have expired' is coming up every time, using different browsers and through different internet connections.

**Comment by stevenweaver** [comment]
Dear @phoeberobinson, 

This appears to be code from classic.datamonkey.org. Have you tried using datamonkey.org for MEME results? In the meantime, I'll reset classic.datamonkey.org processes and attempt resolving this issue. 

Best,
Steven
