### ISSUE TITLE
Help with inconsistent Absrel results

### ISSUE THREAD

**Issue by andreaniml** [veg/hyphy#1326]
Hello,

I have a dataset of 302  sequences of a regulatory gene in bacteria. I wanted to test if two subsets of these 302 sequences had experienced selection, in order to do that I generated two files for the same ML tree, one has my tree with subset A labeled as foreground and the other has subset B labeled as foreground. 
I ran absrel with this command line in hyphy version HYPHY 2.5.2(MP), changing the labeled tree accordingly:

`hyphy absrel --alignment Myalignment.fasta --tree SubsetA_labeledtree.txt  --branches Foreground` 

and got a small set of nodes under selection for each subset

In this dataset of 302 sequences, 6 had stop codons, so I decided to remove them. I ran the analysis again (new alignment, new tree, same labels) and now absrel did not find any node or branch under selection. As neither the alignment nor the tree changed radically I'm thinking this is odd. 

I'm trying to understand why it changed and got some ideas, but I don't know if they make sense:

1) The signal was so small that even a slight change in branch lengths/alignment made it disappear
2) The result I had before was based on some poorly aligned region (false-positive) that tricked absrel 
3) I've run absrel wrong both times and should take another approach/program on hyphy suite 

Is there a way to see the "health" of my absrel run? (some red flag on the log file I may have overlooked) 
Am I just being paranoid and this is normal behavior? 

Thank you,
Maria Luiza

**Comment by spond** [comment]
Dear @andreaniml,

Can you provide result files for both runs? My guess is (2). Also, version 2.5.2 is about 2 years old, and some the improvements made since then were specifically to improve consistency and warn users about various issues that the program may detect.

Best,
Sergei

**Comment by andreaniml** [comment]
Hello, sorry for the delay
Here are the results files for each run (these are the .json files, I had to change them to .txt or github would not let me upload):
[SubsetA_296.txt](https://github.com/veg/hyphy/files/6386474/SubsetA_296.txt)
[SubsetB_296.txt](https://github.com/veg/hyphy/files/6386475/SubsetB_296.txt)
[Subset_A_302seq.txt](https://github.com/veg/hyphy/files/6385893/Subset_A_302seq.txt)
[Subset_B_302seq.txt](https://github.com/veg/hyphy/files/6385895/Subset_B_302seq.txt)

Also, maybe I should update hyphy and re-run the analysis?

Thank you,

Maria Luiza

**Comment by andreaniml** [comment]
Dear @spond 
Thank you for the answer, I will try to address the problem in the alignment file and update hyphy to get a more reliable analysis.
Sequences that might be responsible for these infinite branch lengths can also be spotted by max dN/dS values of >1000 on the log files, right?

Thank you for all the help,

Maria Luiza Andreani

**Comment by spond** [comment]
Dear @andreaniml,

You should look for the high branch length (>1000) in the log files (the `Length` column, see below). aBSREL starts with longest branches first, so they will appear 1st. High dN/dS could arise from very short branches (imprecise estimates).

Best,
Sergei

```
### Determining the optimal number of rate classes per branch using a step up procedure

|              Branch               |  Length  |  Rates   |     Max. dN/dS     |    Log(L)     |     AIC-c     |Best AIC-c so far|
|-----------------------------------|----------|----------|--------------------|---------------|---------------|-----------------|
|               Node1               |   0.29   |    2     |    2.54 (22.22%)   |   -3447.10    |    6992.79    |     6992.79     |
|               Node1               |   0.29   |    3     |    2.55 (22.11%)   |   -3447.10    |    6997.01    |     6992.79     |
|                CAT                |   0.28   |    2     |    5.55 (45.46%)   |   -3441.24    |    6985.29    |     6985.29     |
|                CAT                |   0.28   |    3     |    5.76 (42.96%)   |   -3441.24    |    6989.52    |     6985.29     |
|                COW                |   0.25   |    2     |    8.07 (47.20%)   |   -3433.30    |    6973.63    |     6973.63     |
|                COW                |   0.25   |    3     |    8.13 (47.12%)   |   -3433.30    |    6977.87    |     6973.63     |
|               HORSE               |   0.21   |    2     |    4.09 (45.38%)   |   -3427.91    |    6967.10    |     6967.10     |
|               HORSE               |   0.21   |    3     |    4.11 (45.41%)   |   -3427.91    |    6971.35    |     6967.10     |
|                PIG                |   0.19   |    2     |    2.51 (60.07%)   |   -3426.79    |    6969.10    |     6967.10     |
|               MOUSE               |   0.12   |    2     |   16.15 ( 4.64%)   |   -3426.56    |    6968.65    |     6967.10     |
|               Node8               |   0.11   |    2     |   27.08 ( 9.73%)   |   -3424.54    |    6964.60    |     6964.60     |
|               Node8               |   0.11   |    3     |   27.29 ( 9.69%)   |   -3424.54    |    6968.86    |     6964.60     |
|               Node3               |   0.10   |    2     |    8.49 (28.27%)   |   -3421.27    |    6962.33    |     6962.33     |
|               Node3               |   0.10   |    3     |    8.42 (28.48%)   |   -3421.27    |    6966.60    |     6962.33     |
|               Node2               |   0.07   |    2     |   26.07 ( 9.81%)   |   -3417.28    |    6958.61    |     6958.61     |
|               Node2               |   0.07   |    3     |   25.86 ( 9.88%)   |   -3417.28    |    6962.89    |     6958.61     |
|                RAT                |   0.07   |    2     |    4.64 (31.76%)   |   -3416.49    |    6961.31    |     6958.61     |
```
