### ISSUE TITLE
MEME Analysis Error

### ISSUE THREAD

**Issue by Louisbbbbb** [veg/hyphy#1327]
I am trying to run a MEME analysis but get this message every time: We're sorry, there was an error processing your job. Please try again, or visit our GitHub issues and create an issue if the issue persists.

Could you please help me with this?

Thanks

**Comment by aglucaci** [comment]
Please resubmit the job(s). We performed some maintenance on the system this morning. Operations should be back to normal. If the problem persists or something else arises, you can report that here.
