### ISSUE TITLE
MEME error message

### ISSUE THREAD

**Issue by chamberlain-trevor** [veg/hyphy#1329]
I am trying to run some MEME analyses this morning, and I get a standard error message each time. It says there is an MPI_ABORT invoked, and then there's a bunch of this output:

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

I'm hoping this is not due to my data inputs, but I'm guessing I can try later?

Thanks,
Trevor

**Comment by spond** [comment]
Dear @chamberlain-trevor,

Are you running HyPhy locally or on Datamonkey? There should be more output that just this prior to `signal 15` lines.

Best,
Sergei

**Comment by stephenshank** [comment]
Dear @chamberlain-trevor,

Are you able to share some of the URLs for jobs that failed? This will give us some IDs that will help us to troubleshoot the issue.

Best,
Stephen

**Comment by chamberlain-trevor** [comment]
I am running HyPhy on the DataMonkey server. I've tried 3 runs with the following URLs:

http://datamonkey.org/meme/60901b009e9f70521111dc1d
http://datamonkey.org/meme/60901d0a9e9f70521111dc4a
http://datamonkey.org/meme/60901d3d9e9f70521111dc5e

Thanks so much!
Trevor

**Comment by chamberlain-trevor** [comment]
Also, the beginning of the error message is

MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

Best,
Trevor

**Comment by chamberlain-trevor** [comment]
Update: I'm not sure what the issue was, but I had my files in unlabeled Nexus format with TAXA, CHARACTERS, and TREES blocks, and that prompted errors. I just reformatted everything to fasta format with a Newick tree at the bottom, and the run worked fine. I'll proceed with these files for my current analysis.

Best,
Trevor

**Comment by spond** [comment]
Dear @chamberlain-trevor,

I think there may have been a change in the latest version of HyPhy (2.5.31) that introduced an error when reading unlabeled NEXUS files. As you've discovered, using a different format solves the issue. I'll keep this open while I track down the source of the problem.

Best,
Sergei

**Comment by spond** [comment]
Dear @chamberlain-trevor,

Upon examining your NEXUS file, I noticed that the number of species names in the `TAXA` block was `15` while there were 16 sequences and `NTAX = 16` was declared. HyPhy will take the list of sequence names as the truth (so assume 15), which means that the last two entries in the `MATRIX` block will be "combined" into one sequence which is 2x as long; this was the root of the crashes. Can you tell me how this NEXUS was generated?

Best,
Sergei

```
BEGIN TAXA;
	DIMENSIONS NTAX = 16;
	TAXLABELS
		'ND2_DANIO_RERIO' 'ND2_DANIO_AESCULAPII' 'ND2_DANIO_KYATHIT' 'ND2_DANIO_NIGROFASCIATUS' 'ND2_DANIO_TINWINI' 'ND2_DANIO_ALBOLINEATUS' 'ND2_DANIO_MARGARITATUS' 'ND2_DANIO_ERYTHROMICRON' 'ND2_DANIO_CHOPRAE' 'ND2_DEVARIO_SONDHII' 'ND2_DEVARIO_AEQUIPINNATUS' 'ND2_DANIONELLA_DRACULA' 'ND2_SUNDADANIO_AXELRODI' 'ND2_BORORAS_MACULATUS' 'ND2_TRIGONOSTIGMA_ESPEI' ;
END;
```

**Comment by chamberlain-trevor** [comment]
Hi Sergei,

The mistake was mine. There are 16 tax’s in the alignment, but in the taxa block I left one out (Microdevario kubotai). The Nexus file was generated by myself using fasts alignments, then manually inputting the other information. Sorry to cause you extra work after making this error, but thank you for looking it over.

Best,
Trevor



________________________________

**Comment by spond** [comment]
Dear @chamberlain-trevor,

Not a problem. One issue this reveals on my end is that error reporting on Datamonkey is not informative in this case. The console version of the analysis outputs the following (this at least points you in the right direction).

@stephenshank : can you take a quick look to identify why the logs are empty?

Best,
Sergei

```

### Obtaining branch lengths and nucleotide substitution biases under the nucleotide GTR model
Error:
The number of tree tips in 'fLbSejOQ.tree_0'(16) is not equal to the number of sequences in the data filter associated with the tree (15).

Function call stack
1 :  LikelihoodFunction fLbSejOQ.likelihoodFunction = (sfXqnKtM.lf_components);

-------
2 :  ExecuteCommands(commands, /Users/sergei/Development/hyphy/res/TemplateBatchFiles/libv3/);
-------
3 :  [namespace = sfXqnKtM] utility.ExecuteInGlobalNamespace("LikelihoodFunction `lfid` = (`&lf_components`)");
-------
4 :  [namespace = fLbSejOQ] df=estimators.CreateLFObject(this_namespace,data_filter,tree,model_template,initial_values,run_options,None);
-------
5 :  [namespace = raMdZWKd] return estimators.FitSingleModel_Ext(data_filter,tree,"models.DNA.GTR.ModelDescription",initial_values,run_options);
-------
6 :  [namespace = YUOfiRop] return estimators.FitGTR_Ext(data_filter,tree,initial_values,{});
-------
7 :  [namespace = meme] gtr_results=estimators.FitGTR(filter_names,trees,gtr_results);
-------
8 :  [namespace = meme] doGTR("meme");
-------
9 :  namespace 

Step 0.doGTR("meme");;
-------

```

**Comment by stephenshank** [comment]
Dear @spond,

I think I've identified the cause. Pushing out a fix ASAP.

Best,
Stephen
