### ISSUE TITLE
RELAX JSON error

### ISSUE THREAD

**Issue by benitow21** [veg/hyphy#1330]
Hi there,

I am trying to load the attached JSON file (converted into .txt) from a RELAX analysis into Hyphy Vision and I get "Something went wrong when rendering the results page." Any help with this would be greatly appreciated.

Best,

Benito
[RELAX_itho_UV_output.txt](https://github.com/veg/hyphy/files/6451472/RELAX_itho_UV_output.txt)

@francicco

**Comment by jzehr** [comment]
Dear @benitow21,

It looks like your RELAX output is malformed. 

Can you tell me what version of `HyPhy` you ran? and if you ran it locally or on `Datamonkey.org`?

Best,
Jordan

**Comment by benitow21** [comment]
Hi Jordan,

Thanks for responding so quickly. I ran RELAX locally on HYPHY version 2.5.30. Hopefully this helps you!

Many thanks,

Benito

**Comment by benitow21** [comment]
Hi Jordan,

The output file was a .json, I just made it a .txt. file so I could send it on here just now (Github doesn't accept .json files by the looks of things).

Many thanks,

Benito

**Comment by jzehr** [comment]
Dear @benitow21,

What is the exact command you used to run RELAX? 

Best,
Jordan

**Comment by benitow21** [comment]
Hi Jordan,

I used HYPHY's interactive command line server. Here is a list of the options I chose (sorry if a lot of this is unnecessary. Only just getting to grips with this so thought it was best to state everything I did just incase):

-After selecting RELAX and choosing my alignment and sequence files, I select my test and reference sets, After that, I specify the path of the output JSON file as 'XXXX.json'. 

-The number of points in the initial distribution for likelihood fitting is set to 250, the number of initial random guesses (to 'seed' rate value optimisation?) is set to 1, the number of omega rate classes is set to 3.

- I then run the default RELAX analysis type (for fitting descriptive models too) and I allow synonymous substitution rates to vary from site-to-site.  

-I then set the number of omega rate classes to 3 again (not sure why this needs to be done twice?) and specify the path for the parameter estimates. I choose to Zero-length the branches

The model then runs. Let me know if you need anything else! Many thanks for your help/

All the best,

Benito

**Comment by stephenshank** [comment]
Dear @benitow21,

Thank you for calling our attention to this issue. The hyphy-vision module needs a minor update to accommodate visualizing RELAX results that were ran with variable site-to-site synonymous substitution rates. I've identified the source of the error and will notify you once I've pushed out a fix.

Best,
Stephen

**Comment by benitow21** [comment]
Many thanks Stephen, that would be great! Much appreciated.

All the best,

Benito

**Comment by benitow21** [comment]
Hi Stephen,

I hope all's well. I was just wondering whether there has been any update on the above? 

All the best,

Benito

**Comment by stephenshank** [comment]
Dear @benitow21,

Sorry for the delayed response. I have a fix that I will try to push out today.

Best,
Stephen
