### ISSUE TITLE
FADE output

### ISSUE THREAD

**Issue by Abhishek7Nayak** [veg/hyphy#1334]
I have a protein multiple sequence alignment with 25 sequences which consists of 3 proteins concatenated. 
I would like to do selection analysis.  

[datamonkey-table.csv](https://github.com/veg/hyphy/files/6507979/datamonkey-table.csv)

Please see the CVS file attached.
As i am new to this, I could not figure out the results and infer the selected proteins.
So please help me in analyzing the results.

Thank you

**Comment by stevenweaver** [comment]
Hi @Abhishek7Nayak, 

Have you read information regarding FADE on hyphy.org? https://hyphy.org/methods/selection-methods/#fade

A tutorial describing how to interpret results can be found [here](https://hyphy.org/tutorials/CL-prompt-tutorial/#use-fade-to-test-for-directional-selection-at-individual-sites-in-a-protein-alignment).

Best,
Steven
