### ISSUE TITLE
internal node missing

### ISSUE THREAD

**Issue by dengyuan7** [veg/hyphy#1337]
Hello,

I've got an output of the hyphy ABSREL model from 147 sequences. But I found some internal nodes were missing and the input binary tree became a multi-way tree. Do you have any clues as to why do these internal nodes disappear and how to interpret the nodes that have multiple child nodes?

Any assistance is greatly appreciated.

Best,
Yuan

**Comment by spond** [comment]
Dear @dengyuan7,

HyPhy removes all 0-length internal branches. This is done to speed-up estimation and because the evolutionary process is not identifiable along 0-length branches. Inferences at other branches will be unaffected.

Best,
Sergei

**Comment by dengyuan7** [comment]
Thank you Sergei, that makes sense to me.
