### ISSUE TITLE
hyphy closes unexpectedly

### ISSUE THREAD

**Issue by fagire** [veg/hyphy#1338]
Dear Pond,

I'm running AnalyzeCodonData.bf (following [this issue](https://github.com/veg/hyphy/issues/773)). However, when hyphy asks me, "Continue with result processing (y/n)?" (and I answer "y"), hyphy terminates abruptly and without errors.

I am using HYPHY 2.5.31.

Thank you,

Facundo

**Comment by spond** [comment]
Dear @fagire,

Thanks for reporting. I was able to replicate the issue. Investigating.

Best,
Sergei

**Comment by fagire** [comment]
Dear Pond,

thank you for your clarification.

Best,

Facundo
