### ISSUE TITLE
Empty or missing error.log files.

### ISSUE THREAD

**Issue by RijanDhakal2055** [veg/hyphy#1340]
Hello, 

I am currently trying to run a phylogeny analysis on 21 proteome files from 21 species. So, I got hyphy from github and was able to go through the cmake process and properly add hyphy to my path environment. Now, when I type Hyphy on cli, I am prompted with the  first 17 options from hyphy. Does this mean I have hyphy configured properly? 

I am asking the last question because I can navigate through the options but when I get to the specific part that I need hyphy just sort of idles and if I terminate the process, it says it has made a error.log file but I can't find it in the directory that I called hyphy to. 

And what I currently need for my analysis are as follows:-

Step 1:- option 12: Phylogeny Reconstruction

Step 2:- Option 1: Apply clustering methods for phylogeny reconstruction (UPGMA,WPGMA,complete or minimal linkage) to nucleotide, protein and codon data, using MLE of pairwise distances with user-selectable models. These methods produce trees with global molecular clock.

Step 3:- option 1 :[Distance formulae] Use one of the predefined distance measures based on data comparisons. Fast.

step 4:- option 1 :[Nucleotide/Protein] Nucleotide or amino-acid (protein).

Step 5:- Give the name of the required files in the directory. (Which I do)

Step 5 is where I am a bit confused, when I give it the name of the first species' proteome fasta file, Hyphy just idles and I think starts work in the background. But should it not ask for at least one more species for it to start a phylogeny analysis? Am I doing something completely wrong by using these options for a species tree reconstruction?

And sometimes it will make an empty error.log immediately on start up, so if I go to a directory and start terminal and type hyphy, an empty error.log file will be made in the said directory? Is making an empty error.log file automatically on startup  expected behavior?

**Comment by spond** [comment]
Dear @RijanDhakal2055,

In step 5 you should supply a multiple sequence alignment of the 21 sequences in one of the formats that HyPhy understands (FASTA, PHYLIP, MEGA, NEXUS). Then you will see something like the following console transcript. 

Best,
Sergei

```***************** FILES IN 'Phylogeny Reconstruction' ***************** 


	(1) Apply clustering methods for phylogeny reconstruction (UPGMA,WPGMA,complete or minimal linkage) to nucleotide, protein and codon data, using MLE of pairwise distances with user-selectable models. These methods produce trees with global molecular clock.
	(2) Generate a pairwise sequence distance matrix in PHYLIP format.
	(3) Perform a phylogeny reconstuction for nucleotide, protein or codon data with user-selectable models using the method of neighbor joining.
	(4) Perform a phylogeny reconstuction for nucleotide, protein or codon data with user-selectable models using the method of sequential addition.
	(5) Perform an exhaustive tree space search for nucleotide or protein data with user-selectable models. Should only be used for data sets with less than 10 taxa!

 Please select the analysis you would like to perform (or press ENTER to return to the list of analysis types):1


			+--------------------+
			|Distance Computation|
			+--------------------+


	(1):[Distance formulae] Use one of the predefined distance measures based on data comparisons. Fast.
	(2):[Full likelihood] Estimate distances using pairwise MLE. More choices but slow.

Please choose an option (or press q to cancel selection):1


			+---------+
			|Data type|
			+---------+


	(1):[Nucleotide/Protein] Nucleotide or amino-acid (protein).
	(2):[Codon] Codon (several available genetic codes).

Please choose an option (or press q to cancel selection):1

Please choose a nucleotide or amino-acid data file: (`/Users/sergei/Development/hyphy/`) res/data/p51.aa


			+-----------------+
			|Clustering Method|
			+-----------------+


	(1):[UPGMA] Unweighted Pair Group Method using Arithmetic Averages. (new distance)=1/2(sum of old distances).
	(2):[WPGMA] Weighted Pair Group Method using Arithmetic Averages. (new distance)=((Taxa in clade 1)dist1+(Taxa in clade 2)dist2)/(Taxa in clade 1+Taxa in clade 2).
	(3):[Complete Linkage] Complete Linkage Method. (new distance)=max(old distances).
	(4):[Single Linkage] Single Linkage Method. (new distance)=min(old distances).

Please choose an option (or press q to cancel selection):1


			+----------------------------------+
			|Amino-acid based distance formula.|
			+----------------------------------+


	(1):[PC] Poisson corrected distance (equal character frequencies, all rates equal).
	(2):[PC_RV] Poisson corrected distance with rate variation (equal character frequencies, all rates equal, gamma distributed rate variation from site to site)).
	(3):[PC_MH] Distance corrected for mulitple hits used in Clustal-W.
	(4):[p_Distance_aa] Number of observed substituions per site.
	(5):[Unaligned_LZ] Distance measure for unaligned sequences based on Lempel Ziv measure of information content.
	(6):[Unaligned_LZ_FR] Distance measure for unaligned sequences based on Lempel Ziv measure of information content using the best choice forward and reverse string orientations.

Please choose an option (or press q to cancel selection):1


 --------------------- INFERRED TREE --------------------- 

((((((B_FR_83_HXB2:0.01265890399214495,B_US_90_WEAU160:0.01265890399214495):0.01101471108474892,B_US_86_JRFL:0.02367361507689386):0.008754143212331686,D_CD_83_NDK:0.03242775828922555):0.006900689911002254,B_US_83_RF:0.03932844820022781):0.02868501809925827,(D_CD_83_ELI:0.02804473332552179,D_CD_84_84ZR085:0.02804473332552179):0.03996873297396429):0.009686230570743873,D_UG_94_94UG114:0.07769969687022993)
```
