### ISSUE TITLE
Some GARD analysis are active more that 90 hours

### ISSUE THREAD

**Issue by MauriAndresMU1313** [veg/hyphy#1341]
Hi!

This week I ran a GARD analysis for 33 sequences, in the same time I noticed that some other users ran the same method. Now, this analysis takes more than 90 hours (in some cases), including my analysis. 
![imagen](https://user-images.githubusercontent.com/68199472/121740403-09694d80-cacb-11eb-9f4a-7fa6358372aa.png)

Does is it normal? 
My analysis keeps running; however, it looks like going to never stop.
This is more a comment than a problem. 
Always I welcome any comment to discuss a topic like this. 

Thank!

**Comment by stevenweaver** [comment]
Hi @MauriAndresMU1313, 

No, it is not normal. There was an abrupt system failure Tuesday, which resulted in improper cleanup of failed jobs at time of failure. Unfortunately, these jobs will need to be run again. 

Best,
Steven
