### ISSUE TITLE
MEME doesn't result

### ISSUE THREAD

**Issue by SticaC** [veg/hyphy#1343]
I am attempting to run MEME on whole genome datasets for dengue. The jobs appear in the queue and process for a couple of minutes but then disappear. They don't generate anything in a log file and still appear to be initializing when I go to the URL.

Here are a few:
http://datamonkey.org/meme/60c6ba1cd0841316fd5da730
http://datamonkey.org/meme/60c69f76d0841316fd5d9099
http://datamonkey.org/meme/60c6a088d0841316fd5d912d

I have also attached my alignment files that I am using.

Thanks

[DENV4_WG_alignement_complete.txt](https://github.com/veg/hyphy/files/6645931/DENV4_WG_alignement_complete.txt)
[DENV1_WG_alignement_complete.txt](https://github.com/veg/hyphy/files/6645932/DENV1_WG_alignement_complete.txt)

**Comment by stevenweaver** [comment]
Dear @SticaC, 

While the site itself appears to be functional for me, I do see that there was a communication error with these specific jobs. Investigating now and will report back shortly. 

Best,
Steven

**Comment by stevenweaver** [comment]
Dear @SticaC, 

There were indeed communication issues between our cluster and the front-end site. I believe I've worked to resolve these issues, but I've included results for your previous runs here:

http://data.hyphy.org/web/sticac/

You can use http://vision.hyphy.org/MEME to visualize results. 

Please let me know when you have received them. 


Best,
Steven

**Comment by SticaC** [comment]
Dear Steven,

Amazing. Thank you for resolving this so quickly. I have am now able to visualize the results.

Thanks
Caleb
