### ISSUE TITLE
Jobs aren't completing (FUBAR, SLAC, MEME)

### ISSUE THREAD

**Issue by SticaC** [veg/hyphy#1345]
Hello,

It seems as if the following jobs are still processing, but they no longer appear on the queue. A few have been processing for over 27 hours and all seem to have stopped at the same point in the log files. The datasets themselves have resulted for other methods, so I dont believe it is an issue with the files.

FUBAR
http://datamonkey.org/fubar/60c7fc6b1735c43bacd20a57
http://datamonkey.org/fubar/60c816811735c43bacd21936

SLAC
http://datamonkey.org/slac/60c7fc8c1735c43bacd20ca1
http://datamonkey.org/slac/60c816c81735c43bacd21d09
http://datamonkey.org/slac/60c95d411735c43bacd251eb

MEME
http://datamonkey.org/meme/60c815a81735c43bacd2118c

Thanks
Caleb

**Comment by stephenshank** [comment]
Dear @SticaC,

Thanks for reporting this issue. It appears as though the jobs ran to completion, but the system failed to act accordingly.

I've shuffled some files around and updated some entries in our database, and your results should now be viewable at the above URLs.

Best,
Stephen

**Comment by SticaC** [comment]
Hi Stephen,

Amazing. Thanks for this.

Caleb
