### ISSUE TITLE
website integration

### ISSUE THREAD

**Issue by ZemarQazi** [veg/hyphy#1351]
Hi DataMonkey, 

This is Zemar Qazi. I'm a student at Temple University currently working on a project using DataMonkey. My issue is finding out the best way to integrate the data that DataMonkey gives me to another site (FlyDivas). I have a couple of ideas on how to do this (using API), but I was wondering if someone would know the most effective route in tackling this issue. 

It would be great if someone could get back to me as soon as possible, 

Zemar Qazi 
06/30/21

**Comment by stevenweaver** [comment]
Dear @ZemarQazi, 

There are a couple different routes you go. If you just need to run a few jobs and need access to the raw results file, you can access the JSON by appending `results` to the end of the URL, such as http://datamonkey.org/fel/60d9d04b7c8781112a3c78c7/results. 

If several jobs need to be spawned periodically and/or programmatically, you can use the Datamonkey API. https://github.com/veg/datamonkey-js/wiki/API. Please let me know if this answers your question. 

Best,
Steven
