### ISSUE TITLE
SLAC error

### ISSUE THREAD

**Issue by bella-xia** [veg/hyphy#1353]
Dear DataMonkey, I am currently studying a Coursera course which requires the use of datamonkey SLAC analysis. However, I've been trying for several attempts and repeatedly got the notification that there's error processing the job. Here is the link to the error page: http://datamonkey.org/slac/60e8d6de53d4f07f693c20f7. Thank you very much!

<img width="1321" alt="Screen Shot 2021-07-10 at 6 49 33 AM" src="https://user-images.githubusercontent.com/87211890/125143486-7b29cb00-e14d-11eb-8f04-b816623c2808.png">

**Comment by stevenweaver** [comment]
Dear @bella-xia, 

A patch release of Datamonkey was released earlier that has been causing some performance issues. I've reverted back to the older version. Operations should be normal now. 

Best,
Steven

**Comment by bella-xia** [comment]
Hi Steven, thank you very much! It is working now!
