### ISSUE TITLE
HyPhy killed by Error 15?

### ISSUE THREAD

**Issue by llebynnej** [veg/hyphy#1354]
Hi,

I keep receiving the error message "HyPhy killed by Error 15". 

Here's a link to my latest run:
http://datamonkey.org/absrel/60efd67841074e140f3cd254 

Would you please be able to assist?

Thanks!

**Comment by spond** [comment]
Dear @llebynnej,

Your job was terminated due an internal numerical error -- this occurs occasionally, especially when the input data set has very long branches (see #1323). Sorry about poor error reporting. 

There seem to be such long branches in your dataset -- I would check alignment and homology to ensure that the sequences are not saturated. You can also remove the "long branch" sequences and try running the analysis again.

Best,
Sergei

### Determining the optimal number of rate classes per branch using a step up procedure

|              Branch               |  Length  |  Rates   |     Max. dN/dS     |    Log(L)     |     AIC-c     |Best AIC-c so far|
|-----------------------------------|----------|----------|--------------------|---------------|---------------|-----------------|
|              Node17               |1237.69...|    2     |    0.20 (29.21%)   |   -72172.46   |   146741.01   |    146741.01    |
|              Node17               |1237.69...|    3     |    0.35 ( 0.00%)   |   -72172.46   |   146745.06   |    146741.01    |
|NM_213070_1_DANIO_RERIO_KARYOPHE...|1237.64...|    2     |    0.53 (32.76%)   |   -72142.13   |   146684.41   |    146684.41    |
|NM_213070_1_DANIO_RERIO_KARYOPHE...|1237.64...|    3     |  101.83 (13.47%)   |   -72140.18   |   146684.56   |    146684.41    |
|              Node18               |1237.62...|    2     |    0.10 (26.56%)   |   -72114.35   |   146632.89   |    146632.89    |
|              Node18               |1237.62...|    3     |    0.81 (17.89%)   |   -72112.18   |   146632.62   |    146632.62    |
|              Node18               |1237.62...|    4     |    0.86 (17.89%)   |   -72112.18   |   146636.67   |    146632.62    |
|              Node83               |1237.55...|    2     |    0.24 (13.40%)   |   -72087.79   |   146587.88   |    146587.88    |
|              Node83               |1237.55...|    3     |   81.31 ( 7.12%)   |   -72087.18   |   146590.72   |    146587.88    |
|NM_201305_1_DANIO_RERIO_KARYOPHE...|1237.51...|    2     |    8.27 ( 2.99%)   |   -72057.68   |   146531.72   |    146531.72    |
|NM_201305_1_DANIO_RERIO_KARYOPHE...|1237.51...|    3     |   12.31 ( 2.97%)   |   -72057.68   |   146535.77   |    146531.72    |
