### ISSUE TITLE
RELAX results

### ISSUE THREAD

**Issue by SPark-botanist** [veg/hyphy#1355]
Hi there,

I have a question about the interpretation of result from the RELAX. 
I've tested for selection using aBSREL (total 19 branches, ingroup: 13 branches, outgroup: 6 branches). Within ingroup, seven branches showed dN/dS >1, and LRTs detected that only three branches had significantly higher than the others.  To test for relaxed purifying selection or intensified positive selection, I used RELAX (set test: ingroup, reference: outgroup).
I found that the test for selection intensification (k=3.54) was significant (LR = 13.15, P=0.0000).
The k values of three branches are 1.94 (w=2.13, p=0.00274), 1.77 (w=1.52, p=0.0000360), and 4.27(w=4.02, p=0.00000000198), respectively. I understood that three branches are under strong positive selection.
However, the k values of the four branches that had dN/dS >1, but rejected by LRTs are 2.23 (w=3.35, p=0.0631), 1.48 (w=1.01, p=1), 1.71 (w=1.17, p=0.0665), and 3.67 (w=18.1189, p=0.6). Could I ignore this result? Or does it mean something else?

Thanks, 

Seongjun

**Comment by spond** [comment]
Dear @SPark-botanist,

Can you please provide further clarification? It is the case that branch-level &omega; estimates are different under aBSREL and RELAX. Specifically, I don't understand the last result bit:

>However, the k values of the four branches that had dN/dS >1, but rejected by LRTs are 2.23 (w=3.35, p=0.0631), 1.48 (w=1.01, p=1), 1.71 (w=1.17, p=0.0665), and 3.67 (w=18.1189, p=0.6).

Best,
Sergei

**Comment by SPark-botanist** [comment]
Dear Pond, 

I am sorry for the late reply. 
Each analysis was done independently. The ω values from aBSREL analysis. 
![그림1](https://user-images.githubusercontent.com/66659784/126856581-4954d147-a2b8-4b73-8a38-fb8395d2d9a4.png)
I have attached a file that was generated by aBSREL. As you can see, three branches are significantly under positive selection, although there are four branches that have showed dN/dS >1. 
RELAX revealed that three branches had significant K>1, indicating intensified selection. But, four branches also had K>1. 
I would like to know what does mean. 

Thanks, 

Seongjun
