### ISSUE TITLE
Interpreting contradicting results: significant aBSREL but non-significant BUSTED

### ISSUE THREAD

**Issue by mufernando** [veg/hyphy#1358]
Hi,

How would one interpret a positive aBSREL result but negative BUSTED result? Both applied on the same branch of a single-gene alignment. I'm thinking it has to do with lower power in BUSTED when the number of foreground branches is small (just one branch in this case), but why would aBSREL on the same branch produce positive results? Another thought that came to mind has to do with divergence: does power differ between these two methods with high-ish divergence?

Thank you!

**Comment by spond** [comment]
Dear @mufernando,

Can you share result files? I'll be able to provide better feedback with actual data.

Best,
Sergei

**Comment by mufernando** [comment]
Here goes the JSON for both analysis: [https://gist.github.com/mufernando/cf5534b014aac17555752b117c176622](https://gist.github.com/mufernando/cf5534b014aac17555752b117c176622). Thanks for the quick reply, Sergei!

**Comment by spond** [comment]
Dear @mufernando,

Interesting use case for sure. The big difference between the methods is that BUSTED includes site-to-site synonymous rate variation, and aBSREL does **not**. 

As we showed in https://pubmed.ncbi.nlm.nih.gov/32068869/, this can have a big effect. In your dataset there's pretty extensive synonymous rate variation:

```
"Synonymous site-to-site rates": {
          "0": {
            "proportion": 0.1022839962753578,
            "rate": 0.08854341962091937
          },
          "1": {
            "proportion": 0.6020914071169067,
            "rate": 0.4148763120212026
          },
          "2": {
            "proportion": 0.2956245966077355,
            "rate": 2.507064605643759
          }
        },
```

If you compare the goodness of fit for BUSTED and aBSREL, you will also see that BUSTED has AIC-c of 31097.7 while aBSREL has AIC-c of 31246.68, hence BUSTED is a much better fit to the data.

As a check, you can run BUSTED with the `--srv No` command line option and see what the returned result is.

Best,
Sergei

**Comment by mufernando** [comment]
Ah, that makes sense! I think a lot of the variation in synonymous rate is due to misalignment. Some of the sequences I had in my MSA are really divergent from my branch of interest and the alignments don't look good. I tried realigning just a few of the more related sequenced and synonymous rate variation is reduced, and the signal of positive selection appears both in BUSTED and aBSREL. 

Thanks for the quick clarification, Sergei!
