### ISSUE TITLE
RELAX with mnm and srv 

### ISSUE THREAD

**Issue by vinjlynch** [veg/hyphy#1361]
Hi all,

I’m setting up a RELAX run on a large dataset (~12k genes) and would like to include multinucleotide mutations and synonymous rate variation. When I include these options in the commands as --multiple-hits Double+Triple and -- snv yes RELAX runs, but without acknowledgment of these commands. Are these options not implemented or am I using the commands wrong?

Thanks 
Vinny

**Comment by vinjlynch** [comment]
Forgot to mention that I'm using HYPHY 2.5.1(MP) for Darwin on x86_64 and RELAX  3.1....

**Comment by spond** [comment]
Dear @vinjlynch,

With version 2.5.32 (current version) you can include synonymous rate variation by

```
--srv Yes
```

You should definitely update to the newer version as it will be much faster and more stable.

There is currently no support for `--multiple-hits` in this analysis, but I can add it to the next release if you'd like. In return, I'd like to ask you to tell me what happens to the results with and without the inclusion of `multiple-hits`:)

Best,
Sergei

**Comment by vinjlynch** [comment]
Deal! We will upgrade HyPhy to 2.5.32 for srv and compare and contrast with multiple hits when it's available. Related, do you think the issues of not accounting for multiple hits is the same for positive selection tests and RELAX?

Best,
Vinny


Vincent J. Lynch, Ph.D.
Assistant Professor
Department of Biological Sciences
University at Buffalo, SUNY
551 Cooke Hall
Buffalo NY, 14260

***@***.******@***.***>

"There is a grandeur in this view of life, with its several powers,
having been originally breathed into a few forms or into one; and that
whilst this planet has gone on cycling according to the fixed laws of
gravity, from so simple a beginning endless forms most beautiful and most
wonderful have been, and are being, evolved." -C. Darwin, 1859

________________________________

**Comment by spond** [comment]
Dear @vinjlynch,

Well, multiple hits models tend to reduce &omega; estimates on shorter branches on average (i.e. if you need to explain multiple nucleotide changes with only single position changes, you benefit from higher &omega;). The effect of this on RELAX is not intuitively clear, which is why I'd be curious to see a large scale comparison...

I'll post a couple of examples here when I have the code running.

Best,
Sergei

**Comment by vinjlynch** [comment]
Great! Will keep an eye out for code 🙂

Best,
Vinny


Vincent J. Lynch, Ph.D.
Assistant Professor
Department of Biological Sciences
University at Buffalo, SUNY
551 Cooke Hall
Buffalo NY, 14260

***@***.******@***.***>

"There is a grandeur in this view of life, with its several powers,
having been originally breathed into a few forms or into one; and that
whilst this planet has gone on cycling according to the fixed laws of
gravity, from so simple a beginning endless forms most beautiful and most
wonderful have been, and are being, evolved." -C. Darwin, 1859

________________________________

**Comment by spond** [comment]
Dear @vinjlynch,

You should be able to use the `--multiple-hits` option  in the latest 2.5.32 release. It works for SRV options **except** the branch-site option.

Best,
Sergei

**Comment by vinjlynch** [comment]
Thanks for the quick turnaround! Just to be clear, what branch-site option do you mean in RELAX?

Thanks
Vinny

**Comment by spond** [comment]
Dear @vinjlynch,

If you specify `--srv Branch-site` then the multiple hit option has no effect.

Best,
Sergei

**Comment by vinjlynch** [comment]
Ah! Thanks.

Sent from my iPhone

On Aug 16, 2021, at 3:39 PM, Sergei Pond ***@***.***> wrote:

﻿

Dear @vinjlynch<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvinjlynch&data=04%7C01%7Cvjlynch%40buffalo.edu%7C2da6064a8a544508a6da08d960ed882a%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637647395587077927%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=h9XP8smvnhdVVnNNYqFZIx7dheHZznbTaeB%2Ftb%2F8Kl0%3D&reserved=0>,

If you specify --srv Branch-site then the multiple hit option has no effect.

Best,
Sergei

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fveg%2Fhyphy%2Fissues%2F1361%23issuecomment-899768765&data=04%7C01%7Cvjlynch%40buffalo.edu%7C2da6064a8a544508a6da08d960ed882a%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637647395587087881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1fw0mKhQXJn7M%2BSl7Q6QbxFFX5TQy3k1EKanRCmp24E%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANAFRRC5QFCSR57CJBAK7QDT5FSOFANCNFSM5BVZVLWA&data=04%7C01%7Cvjlynch%40buffalo.edu%7C2da6064a8a544508a6da08d960ed882a%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637647395587087881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EUDlF9DDJjOGIF7r1%2Bw7c1GlK%2F5hkuYbbasifN9PzA0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cvjlynch%40buffalo.edu%7C2da6064a8a544508a6da08d960ed882a%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637647395587087881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IzPCy30YJHdp%2B71XGDxS9foQh4qUgpUxGtm9lcE9IdI%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cvjlynch%40buffalo.edu%7C2da6064a8a544508a6da08d960ed882a%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637647395587097837%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XcxJUXRhyTgvDISuTZfmY1TFagW2V5LSDd%2FJxwMFoN8%3D&reserved=0>.
