### ISSUE TITLE
1576310.new-silverback_6115067aefab8f0d369fec30

### ISSUE THREAD

**Issue by Norina28** [veg/hyphy#1367]
Hello,
I have got several errors each time I run my job (GARD).
The same file ran smoothly on my personal mac.  What I can do to get the results in Datamonkey? 

Thanks in advance

Eleonora

**Comment by spond** [comment]
Dear @Norina28,

We are aware of this issue; it appears to not be a trivial one to fix. @stephenshank and @stevenweaver have been working on a more general fix. You could 

1). Rerun the job on datamonkey.
2). Run GARD on usegalaxy.org
3). Run the job locally.

Sorry for the inconvenience.

Best,
Sergei

**Comment by Norina28** [comment]
Thanks so much! I'll one of these three options.

Best

Eleonora

**Comment by Norina28** [comment]
Thanks so much! I'll one of these three options.

Best

Eleonora
