### ISSUE TITLE
aBSREL does not recognize "Unlabeled branches" as an choice when run from command line 

### ISSUE THREAD

**Issue by mbarkdull** [veg/hyphy#1384]
Hello folks, 

When I attempt to run aBSREL with a bash script from the command line, it does not recognize "Unlabeled branches" as a valid choice; I get the error: 
```
Error:
'Unlabeled branches' is not a valid choice passed to 'Choose the set of branches to test for selection' ChoiceList using redirected stdin input or keyword arguments. Valid choices are
	All, Internal, Leaves, Foreground
```

You can see the script I'm using [here](https://github.com/mbarkdull/FormicidaeMolecularEvolution/blob/main/scripts/DataRunningABSREL). The issue is with line 56:
```
      hyphy absrel --alignment $cdsFile --tree $1$treeFile --branches 'Unlabeled branches' --output "./9_2_ABSRELResults/"$2"/background/"$orthogroupNumber"_absrel.json"
```

However, aBSREL does recognize "Unlabeled branches" when I run it interactively.

My script worked just fine on August 3rd, so I wonder if this issue might have to do with your latest release?

Thank you for any help!
Megan

**Comment by spond** [comment]
Dear @mbarkdull,

My guess (based on the error message), is that for this particular dataset there are **no** unlabeled branches (all the branches are labeled as "Foreground"). Can you check if that might be the case?

Best,
Sergei

**Comment by mbarkdull** [comment]
You are 100% correct, it is throwing that error on trees with only foreground branches- thank you for your help! You saved me hours going in circles chasing that error message. 

Cheers!
Megan
