### ISSUE TITLE
1576311,1576634,1576632,1576630,1576628,1576627,1576626,1576625, 1576624, 1576623,1576622,1576621,1576620,1576619,1576618, 1576617,1576616,1576615, 1576613,1576614,1576312,1576308,1576610,1584246,1576608,1576607,1576606,1576605,1576604,1576603, 1576602,1576601,1576600,1576599,1576598, 1576693,

### ISSUE THREAD

**Issue by Khalid123468** [veg/hyphy#1385]
GARD error occurring again and again in each event.

**Comment by stephenshank** [comment]
Dear @Khalid123468,

We're aware of the issue and are looking into a fix.

Best,
Stephen

**Comment by stephenshank** [comment]
Dear @Khalid123468,

I've made a fix and ran a GARD job to completion:
http://datamonkey.org/gard/611be8bf20842c543c33ef1d

Please try again, and let me know if you encountered any issues.

Best,
Stephen

**Comment by Khalid123468** [comment]
Ok thanks..
*Thanks and Best Regards,*

HAFIZ  MUHAMMAD KHALID
*Short term Research Scholar *
*Department of plant pathology & microbiology *
*Texas a & m university USA*
*PhD in Applied Bio-sciences*
*Plant Virology Lab *
Atta-ur Rahman School Of Applied
Biosciences (ASAB)
National University Of Sciences And Technology
Islamabad (NUST)
*gmail: ***@***.*** ***@***.***>, *
*smarteMail: ***@***.***
***@***.***>*
*Cell # 0322-9781094*
