### ISSUE TITLE
aBSREL: option "not kill zero branch lengths" when using command line

### ISSUE THREAD

**Issue by laura-win** [veg/hyphy#1386]
Dear Hyphy-Team, 

for my master thesis, I want to use aBSREL via the command line. I could not find an option yet to "not kill zero branch lengths" in the analysis like in the interactive mode. 

I am very happy for suggestions and help. 

Thank you very much and best regards, 
Laura

**Comment by spond** [comment]
Dear @laura-win,

Use `--kill-zero-lengths option`, where option is one of `Yes`, `No`, `Constrain`.

Best,
Sergei

**Comment by laura-win** [comment]
Dear @spond,

thank you very much for the fast reply!

Best,
Laura
