### ISSUE TITLE
aBSREL:Result processing problem

### ISSUE THREAD

**Issue by 12suiyue** [veg/hyphy#1388]
Hello, your software hyphy is designed very well, but when I processed the results of aBSREL, I found a little inconvenience. When I put the json file on https://biit.cs.ut.ee/clustvis/, I I found that my positive choice node is difficult to find in Fitted tree, because the node is the name given by the software itself, but the name is not displayed in the Fitted tree. I need to click one by one before it is displayed, and my tree is again It is relatively large, because I want to display the selected branch on my own tree in the follow-up, so it is difficult for me to draw, I hope you have a solution, and I look forward to replying!

**Comment by stephenshank** [comment]
Dear @12suiyue,

The annotated Newick string should be available in the JSON output from aBSREL. In Python syntax, if you've loaded it into a dictionary `d`, you can obtain it with:

```
d['input']['trees']['0']
```

See also below results from the interactive viewer on vision.hyphy.org where you can explore this JSON. Let us know if you experience any further issues.

Best,
Stephen

**Comment by 12suiyue** [comment]
Hello, thank you for your reply, but now I am going to draw my positively selected nodes on the evolutionary tree, and I can’t get specific information from vision.hyphy.org. You can’t go to the Fitted on the vision.hyphy.org website. Is the specific node name displayed on the tree? Or include nodes in the tree file exported by Fitted tree.
![IMG_20210821_173951](https://user-images.githubusercontent.com/89245687/130317999-1b3e7a7a-c2df-49df-8568-24d452eb574e.jpg)

**Comment by 12suiyue** [comment]
The most important thing is can you mark the node name in the tree file exported by Fitted tree.thank you!

**Comment by 12suiyue** [comment]
The problem has been solved, thank you
