### ISSUE TITLE
Error with BUSTEDMH.bf

### ISSUE THREAD

**Issue by jacobbowman2015** [veg/hyphy#1390]
Hello,

I have been using Hyphy 2.5.32 and the BustedMH.bf file for multiple hit BUSTED analysis. I have all the files attached as well (I added the txt extension to the files so I could attach them here).

[errors.log](https://github.com/veg/hyphy/files/7048969/errors.log)
[BUSTED-MH.bf.txt](https://github.com/veg/hyphy/files/7048981/BUSTED-MH.bf.txt)
[mammal_amniotes_prestin.aln.txt](https://github.com/veg/hyphy/files/7048988/mammal_amniotes_prestin.aln.txt)
[mammal_amniotes_prestin.aln.treefile.txt](https://github.com/veg/hyphy/files/7048989/mammal_amniotes_prestin.aln.treefile.txt)

I used the command "hyphy BUSTED-MH.bf --alignment mammal_amniotes_prestin.aln --tree mammal_amniotes_prestin.aln.treefile --srv Yes --save-fit mammal_amniotes_prestin.fit --nt 5"

And the resulting error is: 
"Error:Internal error 
Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-7154006.819688101] does not match the last recorded LF maximum [-6154751.259760021]
Internal error 
Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-7154006.819688101] does not match the last recorded LF maximum [-6154751.259760021]"

Is this intrinsic to the size of the gene? Or a system issue? Do I need to change my options? 

Thank you for your help,
Jacob

**Comment by spond** [comment]
Dear @jacobbowman2015,

Did using the revised tree string help? If not, can you please include the console output so I can see at what point the analysis fails. 

Best,
Sergei

**Comment by jacobbowman2015** [comment]
Dear @spond , 

It did not help. I will include the output here. 

Thanks,
Jacob
[BUSTED-MH_Outuput.txt](https://github.com/veg/hyphy/files/7079199/BUSTED-MH_Outuput.txt)

**Comment by spond** [comment]
Dear @jacobbowman2015,

Based on the output, you are still using the same Newick file (where you have names like `Node39/98.4/100`). Please inspect the Newick file and make sure these names have been removed.

Best,
Sergei

**Comment by jacobbowman2015** [comment]
Dear @spond, 

It seems to be running still with no issue (after starting yesterday afternoon).

Thanks, 
Jacob

**Comment by spond** [comment]
Dear @jacobbowman2015,

Excellent! Let me know what you find. These analyses take a little while to run (adding MH imposes a pretty noticeable computational costs, because Q matrices become dense.

Best,
Sergei

**Comment by jacobbowman2015** [comment]
Dear @spond,

Apologies for the late response. The BUSTED-MH worked with your help of the new tree. I appreciate the help a lot. 

I have a theory question about single hit vs multi hit for BUSTED/absREL. Would it be likely that a false negative for single hit appears in a multi-hit analysis? Or asked differently, is multi-hit more stringent and if positive selection isn't detected in single-hit, it wouldn't be detected by multi-hit? 

Thanks,
Jacob
