### ISSUE TITLE
GARD output for selection analyses

### ISSUE THREAD

**Issue by patogonzalez** [veg/hyphy#1392]
Dear HyPhy developers,

I submitted a set of sequences to GARD, and the .nex file was submitted locally for MEME analysis. The errors.log file from MEME was

Error:Unbalanced () in tree string
Unbalanced () in tree string

The .nex output for another set of sequences ran fine in locally in MEME.

I tried using Datamonkey MEME and gave me an error.

I will appreciate if you guide me to correct the .nex file to run MEME and other selection analyses.

Best regards,
Patricio

**Comment by spond** [comment]
Dear @patogonzalez,

Please provide the GARD output file; I am afraid I can't help you unless I am able to replicate the issue.

Best,
Sergei

**Comment by patogonzalez** [comment]
Dear Sergei,

Thanks for your reply.

I realize that the "partitioned data" output gave a truncated (incomplete) phylogeny. After ran again GARD the partitioned data is incomplete again. My sequence dateset contains 164 sequences with 4086 sites. Unfortunately I can not provide you the output since it corresponds to not shareable sequences.

Best,
Patricio

**Comment by spond** [comment]
Dear @patogonzalez,

I have not encountered this behavior previously. When you say "truncated", do you mean that the tree string is not fully written out? Do you see this issue with one dataset, or multiple datasets? Are there are unusual characters in the names of your sequences?

Best,
Sergei

**Comment by patogonzalez** [comment]
Dear @spond ,

When you say "truncated", do you mean that the tree string is not fully written out? 

_Yes I do. I submitted two times the same set of sequences. The first time the .nex file ends with END; , but the second time doesn't_ 

Do you see this issue with one dataset, or multiple datasets? 

_In multiple datasets. My datasets are from ~200 sequences to ~750 sequences. The largest seems to be rejected from GARD because it is not uploaded_

Are there are unusual characters in the names of your sequences?

_The sequences are labeled XXX-123_

Thanks!
Patricio
