### ISSUE TITLE
SLAC result interpretation

### ISSUE THREAD

**Issue by doresannie** [veg/hyphy#1393]
I am doing SLAC analysis at data monkey. it gives me positive and negative sites. how show I know which site is positive and negative in table

**Comment by spond** [comment]
Dear @doresannie,

You can identity sites that are positively or negatively selected at a given significance level by sorting/filtering the result table on the corresponding column. Here's the view of sites positively  selected at p≤0.1, for example, selected by defining an appropriate filter at the top of the table.

Best,
Sergei

<img width="945" alt="image" src="https://user-images.githubusercontent.com/1018513/132345841-2c00d31e-bfe6-4414-90fa-be63a875629b.png">

**Comment by jast10** [comment]
> Dear @doresannie,
> 
> You can identity sites that are positively or negatively selected at a given significance level by sorting/filtering the result table on the corresponding column. Here's the view of sites positively selected at p≤0.1, for example, selected by defining an appropriate filter at the top of the table.
> 
> Best, Sergei
> 
> <img alt="image" width="945" src="https://user-images.githubusercontent.com/1018513/132345841-2c00d31e-bfe6-4414-90fa-be63a875629b.png">

Hi @spond , 
I had a similar question to this when reporting/publishing the SLAC results. 
Here is an attached image of my sequences. SLAC identified 2 positively selected sites at p< 0.05. however, in the P[dn/ds>1] value I have 4 values exceeding 0. I am unsure how to appropriately interpret and report this.

Thanks,
J
![dn_ds_probability](https://user-images.githubusercontent.com/115736176/195677268-4d5774a7-b686-4713-a8df-b79b3dbbec4b.PNG)

**Comment by spond** [comment]
Dear @jast10,

Which two sites did SLAC report as positively selected?  There's definitely something wonky with the table. Site 440 has no non-synonymous substitutions for example. Did you run SLAC through Datamonkey or locally?

Best,
Sergei

**Comment by jast10** [comment]
Hi Sergei,

I attached the fas. file for reference. I ran SLAC via datamonkey normally
the sites would be highlighted but on my browser (Microsoft Edge) my
results were in a blank table as shown.

Thanks,
Justin

**Comment by spond** [comment]
Dear @jast10,

Unfortunately when you respond to GitHub issues by e-mail all the attachments are stripped out. Could you attach the file by going through the web site?

Best,
Sergei

**Comment by jast10** [comment]
Sorry,

On another note, I just observed that SLAC is only using 6 sequences out of 31 available for the analysis.

[](url)
[PVP01_1427900 [Aligned]_10.13.2022.txt](https://github.com/veg/hyphy/files/9780829/PVP01_1427900.Aligned._10.13.2022.txt)

**Comment by spond** [comment]
Dear @jast10,

Datamonkey will strip out identical sequences for efficiency (no signal is lost by doing that). In HyPhy you'd see a message like this

```
$hyphy slac --alignment PVP01_1427900.Aligned._10.13.2022.txt --tree neighbor-joining

...
-------
>[WARNING] This dataset contains 25 duplicate sequences. Identical
sequences do not contribute any information to the analysis and only
slow down computation. Please consider removing duplicate or 'nearly'
duplicate sequences, e.g. using
https://github.com/veg/hyphy-analyses/tree/master/remove-duplicates
prior to running selection analyses
-------

... 
### For partition 1 these sites are significant at p <=0.1

|     Codon      |   Partition    |       S        |       N        |       dS       |       dN       |Selection detected?|
|:--------------:|:--------------:|:--------------:|:--------------:|:--------------:|:--------------:|:-----------------:|
|      128       |       1        |     0.000      |     1.000      |      nan       |     0.500      |  Pos. p = 0.000   |
|      208       |       1        |     0.000      |     1.000      |      nan       |     0.333      |  Pos. p = 0.000   |


```

Looks like SLAC identifies two sites which are the same on Datamonkey:

http://www.datamonkey.org/slac/6349507535d8215fcb302bcf

<img width="798" alt="image" src="https://user-images.githubusercontent.com/1018513/195843725-365e6cd4-fd10-4294-9bfd-69e4f2f28c3a.png">


This is different from you've experienced. Perhaps this is a browser issue? Which browser were you using?

Interestingly, if you run MEME on the same dataset you get a single but DIFFERENT site under selection. MEME is more sensitive that SLAC and much more statistically rigorous. The two sites that SLAC reports have **zero** synonymous sites, which makes the selection detection method it uses quite confused. 

```
hyphy meme --alignment PVP01_1427900.Aligned._10.13.2022.txt --tree neighbor-joining

|   Codon    | Partition  |   alpha    |   beta+    |     p+     |    LRT     |Episodic selection detected?| # branches |Most common codon substitutions at this site|
|:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|:--------------------------:|:----------:|:------------------------------------------:|
|    174     |     1      |    0.096   |  555.608   |    1.000   |    3.621   |      Yes, p =  0.0771      |     8      |           [5]Caa>Gaa|[3]Gaa>Caa            |

```

Neighbor joining gets quite messy for these types of data, so let's see what happens what you look at an ML tree

```
$raxml-ng --msa PVP01_1427900.Aligned._10.13.2022.txt --model GTR+G 
$hyphy meme --alignment PVP01_1427900.Aligned._10.13.2022.txt --tree PVP01_1427900.Aligned._10.13.2022.txt.raxml.bestTree

....

### ** Found _0_ sites under episodic diversifying positive selection at p <= 0.1**

```

Best,
Sergei

**Comment by jast10** [comment]
Thank you, Sergei!

Unfortunately, using the same text file (without any modifications) I sent you I did not get the same output results for site 174. 
Perhaps I should open a separate issue ticket on here?

- I am using Microsoft Edge and Chrome but got returned the same output.
- I did not remove duplicates before running MEME

Lastly, do you have a breakdown of the output table for interpreting MEME? I tired looking at the handbook, but I believe my copy of the HYPHY handbook is from 2007. 

Thanks,
Justin

![MEME output 10 16 2022](https://user-images.githubusercontent.com/115736176/196055259-5e250c38-10f4-49b1-a620-13b604018166.PNG)

**Comment by spond** [comment]
Dear @jast10,

Take a look at http://hyphy.org/resources/tutorial-2017.pdf for a more recent tutorial. 

Datamonkey will always remove the duplicates (you don't have a choice to keep them). If you don't provide a tree in your alignment, it will also use a NJ tree, which is not very stable in these "low divergence" settings.  

My example above was meant to show that for low divergence datasets like yours there's a lot of sensitivity to how the tree is built etc, so results should be treated with caution.

For small-sample, low divergence settings, I would recommend

1). Build an ML tree (outside Datamonkey) and include it in your file before uploading.
2). On Datamonkey, run FEL with the advances option selected
<img width="990" alt="image" src="https://user-images.githubusercontent.com/1018513/196064936-c8d6391d-02b5-400c-838e-2d87a6c90d2b.png">

This will turn on slower but more accurate significance level estimation via parametric bootstrap (see https://pubmed.ncbi.nlm.nih.gov/35632597/ for an example).

Best,
Sergei

**Comment by jast10** [comment]
Dear, @spond 
Thank you so much!

I just wanted to verify what caused the differences in our MEME outputs?

**Comment by spond** [comment]
Dear @jast10,

Because the NJ algorithm, applied to the "unreduced" (my example) and "reduced" (Datamonkey) alignments returns trees that are different, triggering this discordance. It's not very stable in these conditions. 

For these "small" alignment, site methods really struggle.  There's really no signal...

```
$hyphy BUSTED --alignment reduced.aln --srv No --rates 2

### Performing the full (dN/dS > 1 allowed) branch-site model fit
* Log(L) = -1815.34, AIC-c =  3677.09 (23 estimated parameters)
* For *test* branches, the following rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     1.000     |    0.000    |       Not supported by data       |
|      Diversifying selection       |     1.417     |   100.000   |                                   |


### Performing the constrained (dN/dS > 1 not allowed) model fit
* Log(L) = -1815.39, AIC-c =  3675.16 (22 estimated parameters)
* For *test* branches under the null (no dN/dS > 1 model), the following rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.931     |    0.000    |       Not supported by data       |
|         Neutral evolution         |     1.000     |   100.000   |                                   |

----
## Branch-site unrestricted statistical test of episodic diversification [BUSTED]
Likelihood ratio test for episodic diversifying positive selection, **p =   0.4753**.

```

Best,
Sergei

**Comment by jast10** [comment]
Thank you for everything Sergei!

For consistency I will go ahead and use FEL and MEME for my other sequences
on the Datamonkey site (as a single alignment FASTA file), and publish the
p-values based on those output tables.

Without a prompt on the datamonkey site to upload a newick tree, I will use
the tree datamonkey generates and report it as such in my methods.

Thank you so much again, and I will be sure to cite both FEL and MEME in my
manuscript.

Best,
Justin
