### ISSUE TITLE
FEL/FUBAR "error processing your job"

### ISSUE THREAD

**Issue by nonnohasegawa29** [veg/hyphy#1394]
hello, 

I have been trying to submit jobs on FEL and FUBAR. It loads the .fasta file just fine, but when I select the branches and save to proceed, it errors out with the following message (also see attached screenshot)
"We're sorry, there was an error processing your job. Please try again, or visit our GitHub issues and create an issue if the issue persists."

I've had this error for a few hours now (~5h). I keep waiting or opening a new job to see if it improves but it just does not.

Can you let me know if this is from my particular file I'm feeding or if it is perhaps from a maintenance or something else?

<img width="1092" alt="Screen Shot 2021-09-06 at 15 52 48" src="https://user-images.githubusercontent.com/70122446/132178859-23bb249e-3ea1-4eb3-9f75-1737bc9e5c6f.png">

**Comment by spond** [comment]
Dear @nonnohasegawa29,

Can you please provide your job ID (the long alphanumeric sequence in the URL), so I can take a look at the server logs?

Best,
Sergei

**Comment by nonnohasegawa29** [comment]
https://www.datamonkey.org/fel/613ed1d4c8d8423411613897

Sorry for the late response. 

Thanks,
nonno

**Comment by stephenshank** [comment]
Dear @nonnohasegawa29,

From the ID you provided, I can see that this job was submitted earlier today. We had a system outage this morning that has since been resolved, and I suspect this could be the reason for the error.

Can you please resubmit and share the new URL in this thread? I'll be sure to track your job as it moves through the system, to see what is going wrong.

Best,
Stephen

**Comment by nonnohasegawa29** [comment]
Dear Stephen,

Thanks! It seems that now it is working fine. I am guessing since you guys are based in NA when it goes under maintenance or outage happens, it is at my working hours here in Asia. 

https://www.datamonkey.org/fel/61401828c8d84234116169d2
