### ISSUE TITLE
FEL run wrong way

### ISSUE THREAD

**Issue by Phuong2002** [veg/hyphy#1395]
![Screenshot from 2021-09-07 09-59-33](https://user-images.githubusercontent.com/90231299/132277514-0443b673-cf84-42da-9046-c83897e65ee8.png)
FEL not run, just give me a phytogenetic tree.

**Comment by spond** [comment]
Dear @Phuong2002,

As a part of FEL set-up, you need to indicate which branches to analyze. The standard approach is to analyze **all** branches; you could also select internal branches, or any other set you'd like (e.g. a clade). 


1. Select branches.

<img width="916" alt="Screen Shot 2021-09-07 at 7 52 09 AM" src="https://user-images.githubusercontent.com/1018513/132340102-9eaefeec-29e6-47cb-aae8-017ec2a6e6f0.png">

2. Confirm selection and start the analysis.

<img width="935" alt="Screen Shot 2021-09-07 at 7 53 18 AM" src="https://user-images.githubusercontent.com/1018513/132340276-926a21ff-9e14-4eb8-8ac5-ff1d83458c33.png">

Best,
Sergei

**Comment by Phuong2002** [comment]
Thank you Ad, I can finish this work.
Thanks a lot.
