### ISSUE TITLE
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD with errorcode 1.

### ISSUE THREAD

**Issue by aradrac** [veg/hyphy#1396]
I've tried to run several times but it alwas appears tgis error message:
NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

link: http://datamonkey.org/meme/613b97c3c8d842341160e659

**Comment by stephenshank** [comment]
Dear @aradrac,

I'm still looking into this, but wanted to share the following error message that I pulled from the system:

```
Master node received an error:The leaf of the tree lIyKhdJg.tree_0 labeled 'MONACHUS_SCHAUINSLANDI' had no match in the data filter. Please make sure that all leaf names correspond to a sequence name in the data file.
```

I will give updates as I have them.

Best,
Stephen

**Comment by stephenshank** [comment]
Dear @aradrac,

Can you confirm that:
1) the following sequence label is in the MSA, but not the tree: `Neomonachus_schauinslandi`
2) the following sequence label is in the tree, but not the MSA: `Monachus_schauinslandi`

If so, I would try syncing these up and trying again.

Best,
Stephen

**Comment by aradrac** [comment]
Thanks
I'll check it
Best,
