### ISSUE TITLE
Datamonkey is not recognizing my user tree

### ISSUE THREAD

**Issue by vabadu** [veg/hyphy#1397]
Hello,
In the past I have been able to use my own tree in selection analysis.  I am now trying to use aBSREL and it is not giving me the option to analyze with a user tree.  Is this still an option.  I have attached my input file.
Thanks Vanessa

[CD4_25species_DNAseqWithTree.txt](https://github.com/veg/hyphy/files/7181422/CD4_25species_DNAseqWithTree.txt)

**Comment by stevenweaver** [comment]
Hi Vanessa, 

It looks like there's a discrepancy in node labels between fasta headers and the newick tree. Specifically

```
Cebus_capucinus_imitator
```

and 

```
Cebus_imitator
```
Works as expected when the discrepancy is resolved. 

Best,
Steven

<img width="1792" alt="Screen Shot 2021-09-16 at 4 27 36 PM" src="https://user-images.githubusercontent.com/535261/133701245-37bce679-ecfe-46db-a53b-7b4b137b3527.png">

**Comment by vabadu** [comment]
darn it.  I looked for that possible problem but obviously not well enough.

Sorry to bother you with this.

Vanessa


Vanessa Bauer

PRA - Sawyer Lab

Biofrontiers/MCDB

University of Colorado - Boulder

________________________________
