### ISSUE TITLE
The evolutionary tree branch problem of aBSREL results

### ISSUE THREAD

**Issue by 12suiyue** [veg/hyphy#1399]
![屏幕截图 2021-09-20 062739](https://user-images.githubusercontent.com/89245687/133963932-1d14ef86-df82-4e31-acf6-e348c28dae42.png)
In the red area of the evolutionary tree in the figure, it is found that a node has several branches (genes), instead of a node corresponding to only two genes. I want to ask what is going on. If I want to label in my original evolutionary tree With these, can I name the unnamed node in the evolutionary tree of aBSREL results by myself？The attachment below is the complete evolutionary tree of my aBSREL results。
[ABCA.txt](https://github.com/veg/hyphy/files/7193919/ABCA.txt)

**Comment by spond** [comment]
Dear @12suiyue,

That's called a [multifurcation/polytomy](https://observablehq.com/@spond/trends-in-haplotype-frequencies-in-sars-cov-2-data-from). HyPhy will by default remove internal branches with zero length; these branches have no information for evolutionary analyses and only slow down calculations.

Best,
Sergei

**Comment by 12suiyue** [comment]
ok,thank you four your reply!
