### ISSUE TITLE
Assessing significance of aBSREL results at the species level

### ISSUE THREAD

**Issue by mbarkdull** [veg/hyphy#1400]
I'm hoping to get your input on how to most appropriately parse the results of aBSREL to address a research question, which boils down to "do species with a particular trait have more or fewer genes under positive selection than species without that trait?". 

Once I have an estimate of positive selection for each gene from each species (23 species total), I'm trying to decide what is the most appropriate way to parse those results and answer my research question. So far, I've come up with:

- Using permutation tests, either:
     - A global permutation test:
          - Calculate the number of genes under positive selection from all the species of interest.
          - Then perform a permutation test where I shuffle the label "species of interest"/"not of interest".
          - Check if my true value differs from the values I get from permutation. 
    - A per-species approach:
        - For each individual species, calculate the proportion of genes under positive selection. 
        - Perform a permutation test to see if that number is lower/higher than expected by chance, so that I can label each species as "significantly lower/higher than expected" or "not significantly different". 
        - Calculate the number of species of interest with a significantly lower/higher than expected number of genes under positive selection. 
        - Then, perform a second permutation test where I shuffle the label "species of interest"/"not of interest" and see if I have more species of interest with a significantly lower/higher than expected number of genes under positive selection than expected by chance. 
- Using phylogenetic generalized least squares regression and phylogenetic ANOVA:
   - Calculate the proportion of genes under positive selection for each species. 
   - Test the effects of my trait of interest on the proportion of genes under positive selection with something like phytools. 
- Using a generalized linear mixed-effect model 

I've written up some code for the permutation approaches and generated a markdown report, which I've attached in case it makes my above explanation more clear. 

If you have any advice on how to go about connecting my raw aBSREL results to my research question, I would be tremendously grateful!

[communicatingABSRELResults.pdf](https://github.com/veg/hyphy/files/7196165/communicatingABSRELResults.pdf)

**Comment by mbarkdull** [comment]
Actually, I think I have a more fundamental question- what would be the most appropriate way to implement aBSREL (or, I suppose, another HyPhy test) to assess **whether species with a trait of interest have more genes under positive selection than species lacking that trait?** Would it be reasonable to conduct two runs of aBSREL, first setting species with the trait as foreground, and second setting species without the trait as foreground, and then comparing the results between the two runs? So, for example with the phylogeny below, I'd first set blue and yellow species as the foreground, and in a second run set the purple species as foreground. 

I think my question is conceptually somewhat similar to [this issue](https://github.com/veg/hyphy/issues/1100#issuecomment-594887621). 

Then once I've determined the most appropriate way to use aSBREL to get at this question, I'll need to return to my earlier question about assessing significance of results. 

Thank you for your assistance!


![126676776-8261461d-90f9-480e-9f32-52d0d4ffcfb7](https://user-images.githubusercontent.com/51752289/134185240-8a88ced5-1fce-4ee3-8330-d08063db4da6.png)

**Comment by mbarkdull** [comment]
Hi @spond,

Thank you for your response- this is really helpful. I wasn't aware of the BUSTED-PH method. Are there any particular pros or cons to note regarding using BUSTED-PH vs. RELAX? I actually already have a run of RELAX going, so that might save me some time, but I'd like to use the most appropriate method possible. Or, perhaps it would make the most sense to use both methods and see if they corroborate one another?

Again, thank you for your assistance and your speedy reply, 
Megan

**Comment by spond** [comment]
Dear @mbarkdull,

RELAX is really about relative statements: does **group 1** evolve differently from **group 2**. BUSTED-PH also does specific tests for selection; does **group 1** evolve under selection and is it different from **group 2**?

Best,
Sergei

**Comment by mbarkdull** [comment]
Thanks again for your assistance @spond- I've now gotten BUSTED-PH up and running. I appreciate you point me in the direction of this method! 

Returning to my first question, do you have any thoughts on how I might parse the BUSTED-PH results to determine if the species with a trait have a greater number of genes under positive selection? The only place I've seen a group do something like that is in [this paper](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-019-6361-2), which assessed differences in rates of relaxed selection using Fisher's exact test. Does that approach seem reasonable?

Again, thank you so much, 
Megan

**Comment by spond** [comment]
Dear @mbarkdull,

There are a number of post-hoc analyses you can do. One would be a proportion test (like what you describe). Another would be enrichment analysis (e.g. for ontology terms associated with selected genes). Yet another would be a multi-variate regression where you can put species (and possibly other covariates) as explanatory variables.

Best,
Sergei

**Comment by mbarkdull** [comment]
Hi @spond- thank you for the recommendations. I think I'm off in the right direction. I really appreciate the assistance!
