### ISSUE TITLE
ERROR IN MEME 

### ISSUE THREAD

**Issue by psahamondal** [veg/hyphy#1401]
When upload the FASTA file in MEME and try to RUN the process it shows error in analysis.  How can I solve this problem?

**Comment by stephenshank** [comment]
Dear @psahamondal,

I was able to run the following MEME job:
http://datamonkey.org/meme/614b20dfc8d842341162e877

Can you please share a similar URL with an ID to your specific job so that we will be able to further assist?

Best,
Stephen

**Comment by psahamondal** [comment]
Job id is : 1618887.new-silverback
URL: http://www.datamonkey.org/meme/614b47d8c8d842341162efb3
CAN YOU PLEASE SHARE THE PROCESS THAT YOU HAVE USED TO RUN THIS JOB? I MEAN
WHAT TYPE OF FILE YOU HAVE UPLOADED etc.

Thanks & Regards,
Psahamondal

**Comment by stephenshank** [comment]
Dear @psahamondal,

The issue appears to be with HyPhy itself, in particular with the constrained optimization problem that MEME performs for parameter estimation. Tagging @spond who will likely be able to provide better insight.

To run the job I linked to, I simply took this file:
https://data.hyphy.org/web/issues/datasets/CD2.fasta

and uploaded it to MEME through Datamonkey, without specifying anything further.

Best,
Stephen

**Comment by psahamondal** [comment]
Thanks for your response. But how can I solve the problem of HyPhy ?

Thanks & Regards,
 Psahamondal

**Comment by psahamondal** [comment]
> Dear @psahamondal,
> 
> The issue appears to be with HyPhy itself, in particular with the constrained optimization problem that MEME performs for parameter estimation. Tagging @spond who will likely be able to provide better insight.
> 
> To run the job I linked to, I simply took this file:
> https://data.hyphy.org/web/issues/datasets/CD2.fasta
> 
> and uploaded it to MEME through Datamonkey, without specifying anything further.
> 
> Best,
> Stephen

You just simply copy the fasta sequences from NCBI/ other sites  or you delete the stop codons from the sequences? And how you made the file in FASTA format?

**Comment by spond** [comment]
Dear @psahamondal,

You need to provide a coding alignment with no stop codons (you can search this issue board for some suggestions). The alignment in question runs fine in the command line version of HyPhy (2.5.32)

```
mpirun -np 6 HYPHYMPI meme --alignment 614b47d8c8d842341162efb3 --tree 614b47d8c8d842341162efb3.tre

... 

### For partition 1 these sites are significant at p <=0.1

|   Codon    | Partition  |   alpha    |   beta+    |     p+     |    LRT     |Episodic selection detected?| # branches |Most common codon substitutions at this site|
|:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|:--------------------------:|:----------:|:------------------------------------------:|
|     18     |     1      |    0.001   |   13.616   |    0.450   |    3.218   |      Yes, p =  0.0952      |     1      |     [1]AAA>TAT,AAA>TTA,GCT>AAA,GCT>AAC     |
|    257     |     1      |    0.000   |    0.591   |    0.607   |    7.349   |      Yes, p =  0.0113      |     1      |     [1]AGC>GAA,ATT>AGC,ATT>AGT,ATT>CCT     |
|    271     |     1      |    0.000   |    0.217   |    1.000   |    3.850   |      Yes, p =  0.0684      |     2      |[1]AAT>AGT,ACT>GGT,AGT>ATT,ATT>ACT,CCT>AA...|
|    350     |     1      |    0.001   |    3.645   |    0.719   |    4.139   |      Yes, p =  0.0589      |     1      |[1]AAA>CGG,ACA>CCC,ACA>GAA,ACA>TCG,TCG>AA...|
|    381     |     1      |    0.000   |    0.348   |    1.000   |    3.873   |      Yes, p =  0.0676      |     4      |[1]AAT>GTT,AAT>TGT,TCC>TGC,TCT>TCC,TGC>AC...|
|    388     |     1      |    0.000   |    0.466   |    1.000   |    3.814   |      Yes, p =  0.0697      |     4      |[1]CAA>TCC,CAT>TGT,CCA>CAA,GCT>AAT,GCT>CA...|
|    402     |     1      |    0.000   |    4.308   |    0.535   |    3.722   |      Yes, p =  0.0731      |     1      |     [1]AAC>ATT,ATT>TGT,TGT>AAT,TGT>GCA     |
|    432     |     1      |    0.000   |    2.896   |    0.722   |    5.206   |      Yes, p =  0.0339      |     1      |[1]AGA>AGT,AGA>CCA,AGA>TTA,CCA>GCA,TTT>AG...|
|    471     |     1      |    0.000   |    5.907   |    0.166   |    4.951   |      Yes, p =  0.0387      |     0      |                 [1]AAC>GTT                 |

```


Datamonkey runs a version of HyPhy that's a little bit older, and I remember fixing some of the constraint-related bugs in the last few releases. That could explain the problem.

The MEME output file is attached (view it in vision.hyphy.org/MEME)

Best,
Sergei

[614b47d8c8d842341162efb3.MEME.txt](https://github.com/veg/hyphy/files/7228779/614b47d8c8d842341162efb3.MEME.txt)
