### ISSUE TITLE
MEME-incorrect identification of nonsynonymous amino acid changes

### ISSUE THREAD

**Issue by majonavarrete** [veg/hyphy#1402]
Dear HyPhy team, 

I am writing because we may have found some sort of bug in the MEME code involving incorrect identification of nonsynonymous amino acid changes. We ran this analysis with HyPhy version 2.5.30.
Specifically, MEME detected positive selection in two branches that do not have non-synonymous amino acid substitutions, but do have a different nucleotide in the first position of the codon (although this does not result in an amino acid change).

When looking at the alignment, we can see that the change on both branches in question (highlighted in Fig 1) is from Ser (AGC) to Ser (TCC) (see Fig.2 alignment). This change is also reported in the output file of our MEME analysis (see Fig.3 screenshot of the output file) along with other synonymous substitutions (Thr ACC --> Thr ACA).  I am including our alignment and the json file of our analysis in this [folder](https://drive.google.com/drive/folders/1MSCF5NDUTVmn60rIaLLiOUYsM3hNyJGt?usp=sharing)

Is this the expected behavior of MEME or is this something that might need to be fixed?

We appreciate your help -- thank you in advance for your time.
Majo

<img width="830" alt="Fig1_Branchesunderpositiveselection" src="https://user-images.githubusercontent.com/49131575/134397419-405f27b0-27ef-4e08-9eaa-239e8797c149.png">
<img width="454" alt="Fig2_Alignment_RH1" src="https://user-images.githubusercontent.com/49131575/134397430-da54e2f9-1602-4ec2-87f1-79db5e977223.png">
![Fig3_Outputfile_RH1_diurnalintermediate](https://user-images.githubusercontent.com/49131575/134397446-de028b30-e00a-4853-9a31-d13e93c47cf3.png)

**Comment by spond** [comment]
Dear @majonavarrete,

This is not a bug but a feature :) Simply, this is because the underlying evolutionary models do not allow direct substitution between serine islands (e.g., AGC to TCC). In oder to achieve this substitution, evolution has to go through an intermediate state (e.g., AGC->ACC->TCC) which entails non-synonymous changes. 

We have two papers where this is addressed (to a degree)

1. [Toggling selection](https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1000242) 

>Interestingly, some sites at which no non-synonymous substitutions are observed (6, 103; Figure 3) show significant evidence of toggling. Serine is encoded by islands of codons (TCN and AGY). At both site 6 and 103 serine is encoded by TCN and AGY codons, implying the occurrence of non-synonymous substitutions from serine to another amino acid and back to serine, despite the fact that no other amino acids are observed at this site. This is consistent with immune escape and reversion, in which escape occurs from serine to another amino acid followed by reversion to an alternative encoding of serine, at a remove of two substitutions from the original codon. However, it is also possible that mutations between these sets of serine codons could occur as a single event through doublet mutations [61], which are not considered in our model and are a potential source of false positive results with most models of positive selection.

2. [Multihit models](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0248337)

>Nearly three in five empirical alignments considered here provide strong statistical support that at least some of the substitutions are not well modeled by standard codon models. More than one in five prefer to have direct three-hit substitutions accounted for explicitly in the models. Substitutions involving serine codons, which are unique among the amino-acids in that they comprise two islands which are two or three nucleotide changes from each other, are prominent in driving statistical signal for these preferences, especially if they occur along short branches. Many other amino-acid pairs are also involved in such exchanges, indicating that not all of the statistical signal is due to serine codons, although in a typical alignment only a small fraction of sites (about 1%) prefer multiple hit models strongly.

So, under the modeling framework of MEME, this is a valid result, albeit quite counter-intuitive.

Best,
Sergei

**Comment by majonavarrete** [comment]
This is really cool. Thank you so much for the information and your prompt response.
