### ISSUE TITLE
Widespread evidences of positive selection in close related species

### ISSUE THREAD

**Issue by julianajose** [veg/hyphy#1403]
Dear all,

My team have been using hyphy for many datasets of fungi and bacteria genomes, analysing gene families obtained from the OrthoFinder pipeline. We have been finding biologically reasonable evidences in all datasets, with further evidences corroborating the findings. However, we are now analising a dataset of close related species of fiamentous fungi (40 species within the same genus and two outgroups, ~18k genes each) and both FUBAR and MEME (using 3 species as foreground) have returned about 2k gene families each with evidences of positive selection, considering a 5% error aceptance.

It is the first time we get contact with such widespread evidences in both tested models and we would like to ask you if it is more common than we have tought or if it could be an artifact related to the small phylogenetic scale or something else?

Thank you all in advance for helping us with this confusing results.

**Comment by spond** [comment]
Dear @julianajose,

You should **not** use a site-level method (FUBAR or MEME) to screen for gene-level selection. If the goal of your analysis is to "label" a gene with an attribute (selected/not selected), then you should use BUSTED (or BUSTED[S]).

As we wrote in the [BUSTED paper](https://academic.oup.com/mbe/article/32/5/1365/1134918)

>Even when positive selection is undetectable on any one codon site or branch in isolation, using the random effects framework to pool evidence for positive selection across multiple sites and branches can make their cumulative effect apparent. Recently, Lu and Guindon (2014) presented a comprehensive study of covarion models (Guindon et al. 2004) in the context of detecting gene-wide evidence of positive selection, and argued that these models are preferable to random effects branch-site models. Regrettably, they chose to use a method designed to detect selection at the level of individual sites (MEME; Murrell, Wertheim, et al. 2012) to infer selection on the entire gene—an approach that we cannot recommend. Combining a set of results from individual sites to draw conclusions about a whole gene while controlling the false discovery rate leads to an unavoidable drop in power to detect gene-wide selection, especially when the number of taxa (which drive signal at individual sites) is limited.

If you don't use multiple testing correction with MEME/FUBAR in this setting, you will definitely have too many false positives; if you do use multiple testing correction -- you will have no power.

Best,
Sergei

**Comment by julianajose** [comment]
Dear @spond,
Thank you so much for your detailed answer. I sincerelly apologize for missing the BUSTED key informations. We will take a deep dive on BUSTED underlying logic and reorganize our pipelines!
Best!

**Comment by spond** [comment]
Dear @julianajose,

Happy to help. The latest paper in the BUSTED branch of methods is [BUSTED[S]](https://pubmed.ncbi.nlm.nih.gov/32068869/)

Best,
Sergei
