### ISSUE TITLE
How to interpret GARD results ? 

### ISSUE THREAD

**Issue by JorisBI63** [veg/hyphy#1404]
Dear all,

I am using GARD for recombination analysis. I used GARD on the old website version (Datamonkey classic), the current website version (Datamonkey) and in command line (hyphy gard) with HYPHY version 2.5.2 using the same parameters (general discrete and rate classes =3) and the same sequence files. I am wondering why i didn't obtain same results, indeed, number of breakpoints is different between the old website version and the current website of datamonkey and breakpoints locations differ between the 3 output results (classic, current and command line).

Moreover, datamonkey classic have p-value and support to measure significance of each breakpoint while new versions have just AiC score and delta AiC for the best fit model. For my sequences file (10 sequences) and the best delta AiC, I obtained a big number of breakpoint (9) and some of which are very close (728,770,829,896). How to interpret these different results and is there a way to determine breakpoints with sufficient support to obtain the best breakpoints locations for my sequences ? 

Thank you all in advance for helping me.

Joris M

**Comment by spond** [comment]
Dear @JorisBI63,

Some disagreement is expected because the method is stochastic, but dramatic differences are not something you should see.  

Could you share the JSON files and the underlying alignment for me to review?

I would also encourage you to upgrade to 2.5.32 (the most recent version); GARD works a lot faster and has better convergence that before. 

Best,
Sergei

**Comment by JorisBI63** [comment]
Thanks a lot four your answer Sergei.

I share to you the JSON file results and the corresponding alignment of my 10 sequences with the coordinates of 9 breakpoints.
[Slfn4_GARD.zip](https://github.com/veg/hyphy/files/7266878/Slfn4_GARD.zip)
