### ISSUE TITLE
Unable to automate busted in Hyphy.

### ISSUE THREAD

**Issue by RijanDhakal2055** [veg/hyphy#1405]
I am trying to run BUSTED in hyphy on 129 ortho files and corresponding treefiles. So, running it interactively is not applicable here. I am trying to automate the runs over all of the files. I am using Hyphy installed from conda.
I am using this manual web page as a reference to create a bash loop (scroll to the end of the webpage): https://stevenweaver.github.io/hyphy-site/tutorials/current-release-tutorial/.

The bash for loop that I came up with looks like this:
# path to the file of interest

```
cd /path_to_files
for file  in *.pal
do
	file_base="$(basename $file .pal)"
	ext=".treefile"
	treefile="$file_base$ext"
	echo `(echo "1"; echo "5"; echo $file; echo $treefile) | hyphy`
done
```

So, hyphy shows up on my resource usage tabs in linux. 
Look at the top item:
https://imgur.com/a/Cqdmvx2

But the thing is the run has been going on for hours and there is no data. I have an empty error log file and an empty JSON file. This is a test run on one orthofiles and this one has 203 sequences in it. 
Did I set up the automation script wrong? I only want to run the input using default settings. Or is this not the way to automate it?

**Comment by stephenshank** [comment]
Dear @RijanDhakal2055,

I'd recommend installing the latest release of HyPhy and then using the command line interface. It could be the case that the analysis prompts changed, and the options being piped in no longer initiate the analysis... hard to tell. The CLI was implemented precisely for these sorts of batch jobs.

Once installed, `hyphy busted --help` should get you started. Do let us know if you have any further questions.

Best,
Stephen

**Comment by RijanDhakal2055** [comment]
Dear Stephen,

The bash script actually ended up working, turns out the first orthgorup was just that big that it took some time for the program to output data. I am on the latest version of Hyphy?

I ended up generating BUSTED data for my input? Would you be able to help me clear up a few confusions regarding the results and interpretations? I am having some trouble with the manual and the JSON format and a lot of the help links are coming back broken.

Sincerely,
Rijan

**Comment by stephenshank** [comment]
Dear @RijanDhakal2055,

Glad it worked. I'd recommended loading your JSONs into HyPhy Vision:
http://vision.hyphy.org/BUSTED

There's an interactive JSON explorer, as well as a bunch of useful widgets that consume the JSON data for visualization.

Best,
Stephen

**Comment by RijanDhakal2055** [comment]
Dear Stephen,

Thank you for pointing the HyPhy Vision webpage.

I am afraid I might have misread the manuals and used BUSTED in a somewhat wrong manner (experiment design wise). I supplied BUSTED with alignment and tree files hoping to get data points regarding selection rates for individual genes within a orthgroup. For example, rates of selection for any given gene as compared to the others in the Orthogroup file? Did I misread the way BUSTED works ? Or are the following rates the omega values for each gene and the respective model used?

```
AT1G13370_1":{
       "MG94xREV with separate rates for branch sets":0.04687557203864431,
       "Nucleotide GTR":0.04351889116025126,
       "constrained":1.27310041351933,
       "original name":"AT1G13370.1",
       "unconstrained":1.034905230518423
```

I am sorry to bother you with so many questions at once.

Sincerely,
Rijan

**Comment by spond** [comment]
Dear @RijanDhakal2055,

BUSTED estimates a **distribution** of &omega; recorded in the following fields in `JSON`

```"fits":{
....
   "Unconstrained model":{
   ...
     "Rate Distributions":{
...
       "Test":{
         "0":{
           "omega":0,
           "proportion":0.3764894796889474
          },
         "1":{
           "omega":0.9999999999999908,
           "proportion":0.5459362496410268
          },
         "2":{
           "omega":16.76055517083153,
           "proportion":0.07757427067002588
          }
        }
      },
     ...
```

This gives you three inferred rates and their weights. If you want a single &omega; (although I suggest you consider using distributions, as they are a lot more informative, see Figure 1.2 in [this document](http://www.hyphy.org/resources/hyphybook2007.pdf)), then you can find it in BUSTED `JSON` files in the following record 

<img width="487" alt="image" src="https://user-images.githubusercontent.com/1018513/135646578-3fc78be3-062b-4060-9a92-fdcac8d6d55e.png">

(here it is `0.9378087238513145`). This is estimated as a part of the preliminary fitting stages for BUSTED.

Best,
Sergei
