### ISSUE TITLE
Run SBP with Command Line Arguments

### ISSUE THREAD

**Issue by haruosuz** [veg/hyphy#1406]
I wonder how to run SBP (Single Breakpoint Recombination) from a command-line.
`hyphy --help` printed optional flags for GARD but not SBP.

```
$hyphy --help

        gard    [GARD] Screen an alignment using GARD (requires an MPI environment).
```

**Comment by spond** [comment]
Dear @haruosuz,

The current version of HyPhy does not include SBP as a standalone analysis. The first step of GARD (an exhaustive examination of all single breakpoint locations) is equivalent to SBP. 

Hope this helps.

Best,
Sergei

**Comment by haruosuz** [comment]
Dear @spond

Thank you for your reply. I would like to run GARD with protein (amino acid) sequences. I wonder if there is a documentation for GARD showing example code and a list of values other than default value (e.g. `--type Nucleotide --model JTT`).
```
$hyphy gard --help

type
	The type of data to perform screening on
	default value: nucleotide

model
	The substitution model to use
	default value: JTT

```

References:
```
https://github.com/veg/hyphy/issues/980
hyphy GARD command-line parameters · Issue #980 · veg/hyphy

https://github.com/veg/hyphy/issues/202
Detection of recombination breakpoints from aminoacid sequences · Issue #202 · veg/hyphy
```

Thank you,
Haruo Suzuki

**Comment by haruosuz** [comment]
Dear @spond

Thank you for your reply.

I wonder if the model with the lowest AIC-c value being considered the 'best'. For example in the following case, "the baseline (single-partition; no breakpoints) model" is the best?
```
### Fitting the baseline (single-partition; no breakpoints) model
* Log(L) = -1538.46, AIC-c =  3195.18 (41 estimated parameters)

### Performing an exhaustive single breakpoint analysis
Done with single breakpoint analysis.
   Best sinlge break point location: 71
   c-AIC  = 3209.988870542009

### Performing multi breakpoint analysis using a genetic algorithm
Done with 2 breakpoint analysis.
    Best break point locations: 31, 69
    c-AIC = 3257.910266478027
```

Is there any document that explains the output of GARD?
```
*.best-gard
*.best-gard.fit.bf
*.GARD.json
```

Is there any script for GARD post-processing? (e.g. to create files of alignments divided by the "Best break point locations")

**Comment by spond** [comment]
Dear @haruosuz,

>I wonder if the model with the lowest AIC-c value being considered the 'best'. 

Correct. You can view `JSON` result files via http://vision.hyphy.org/GARD which will also provide some result interpretation.

>  Is there any document that explains the output of GARD

Not in one spot; there's a tutorial at http://www.hyphy.org/resources/tutorial-2017.pdf but here's a quick rundown for you.

1. `.best-gard` is a partitioned NEXUS file corresponding to the best inferred partition, with the partition and tree information encoded in NEXUS blocks. 

```
BEGIN ASSUMPTIONS;
	CHARSET span_1 = 1-450;
	CHARSET span_2 = 451-606;
	CHARSET span_3 = 607-818;
	CHARSET span_4 = 819-1491;
	CHARSET span_5 = 1492-1693;
	CHARSET span_6 = 1694-2691;
END;
BEGIN TREES;
	TREE tree_1 = ...
...
END TREES;
```

2. `.best-gard.fit.bf` is the same partitioned NEXUS file, except with the `HYPHY` block added which records the HyPhy Batch Language specification of the best model fit. The idea is that you can use this file to load the full model fit into HyPhy and analyze it further

3. `*.GARD.json` is the machine readable JSON analysis report (e.g. `http://vision.hyphy.org/GARD`)

```
$jq 'keys' /path/to/partitioned.nex.GARD.json 
[
  "analysis",
  "baselineScore",
  "bestModelAICc",
  "breakpointData",
  "improvements",
  "input",
  "potentialBreakpoints",
  "singleTreeAICc",
  "siteBreakPointSupport",
  "timeElapsed",
  "totalModelCount",
  "trees"
]
```


* `analysis` -- analysis description (text)
* `baselineScore` -- single partition model AIC-c score (number)
* `bestModelAICc` -- best GARD model AIC-c score (number)
* `breakpointData` -- information about each partition from the best model (start-end locations, trees)

```
{
  "0": {
    "bps": [
      [
        1,
        449
      ]
    ],
    "tree": "((((AF_231119:0.004475200158416156,(AF082576:0.00222227116761266,(((AF231118:0.03686636734021624,AF234767:0.09710882995787221)Node9:0.01176627005123532,AF231113:0.004464233973702796)Node8:0,(AF231115:0.00224606675881763,AF231114:0.006693938915665526)Node13:0.004447445626403797)Node7:0)Node5:0.002223047620035919)Node3:0.002233082676602591,AF186243:0.006711255557507476)Node2:0,(AF186241:0,(AF231116:0,AF187824:0.0044721178908879)Node19:0.002227627638825075)Node17:0.002226953477122194)Node1:0,AF231117:0.006700170409004888,AF186242:0.002227340762576298)"
  },
  "1": {
    "bps": [
      [
        450,
        605
      ]
    ],
    "tree": "((((((AF_231119:0,AF231117:0)Node5:0.006543532687609313,(AF186242:0,AF186243:0)Node8:0)Node4:0.006572274533633557,AF234767:0.02013671713746686)Node3:0.006639669103016752,((AF231118:0.05462022348560171,AF231115:0)Node13:0,AF231114:0)Node12:0.006595785257879331)Node2:0,AF082576:0)Node1:0,(AF186241:0.01325799017773619,AF231113:0)Node18:0,(AF231116:0,AF187824:0)Node21:0.006577503418616471)"
  },
...
```

* `improvements`  -- stage-by-stage fitting report (one breakpoint, two breakpoints, etc). `deltaAICc` refers to the previous stage. 

```
{
  "0": {
    "breakpoints": [
      [
        1445
      ]
    ],
    "deltaAICc": 172.295379364461
  },
  "1": {
    "breakpoints": [
      [
        1490
      ],
      [
        1692
      ]
    ],
    "deltaAICc": 183.6775061642802
  },
  "2": {
    "breakpoints": [
      [
        605
      ],
      [
        1490
      ],
      [
        1692
      ]
    ],
    "deltaAICc": 32.58586824802842
  }
...
```

* `input` -- description of the input data

```
{
  "file name": "/Users/sergei/Development/hyphy/tests/hbltests/libv3/data/partitioned.nex",
  "number of sequences": 13,
  "number of sites": 2691,
  "partition count": 5
}
```

* `potentialBreakpoints` -- the number of sites in the input alignment where breakpoints can be placed (variable sites) -- a number

* `singleTreeAICc` -- the AIC-c score for the model that uses N partitions but the same tree for all partitions (i.e. a reference model to compare GARD against)

* `siteBreakPointSupport` -- model averaged support for placing a breakpoint at site `X` 

```
{
  "1007": 3.702355535039301e-09,
  "1011": 2.443799878083256e-07,
  "1016": 1.185663478808284e-12,
  "1028": 3.121882806350848e-11,
  "1037": 4.902701248283419e-14,
  "1050": 4.396416401130176e-11,
  "1053": 1.310850369735023e-15,
  "1054": 4.41989923692091e-14,
  "107": 1.853765051912469e-13,
  "1070": 6.308391434175833e-08,
  "1079": 2.949834184441648e-14,
  "1088": 5.472702284233401e-12,
  "1097": 2.82609111293075e-05,
  "1106": 1.350463808566051e-12
```

* `timeElapsed` -- total run in seconds

* `totalModelCount` -- total # of models examined 

* `trees` -- inferred trees under the best model

```
{
  "0": {
    "newickString": "((((AF_231119:0.004475200158416156,(AF082576:0.00222227116761266,(((AF231118:0.03686636734021624,AF234767:0.09710882995787221)Node9:0.01176627005123532,AF231113:0.004464233973702796)Node8:0,(AF231115:0.00224606675881763,AF231114:0.006693938915665526)Node13:0.004447445626403797)Node7:0)Node5:0.002223047620035919)Node3:0.002233082676602591,AF186243:0.006711255557507476)Node2:0,(AF186241:0,(AF231116:0,AF187824:0.0044721178908879)Node19:0.002227627638825075)Node17:0.002226953477122194)Node1:0,AF231117:0.006700170409004888,AF186242:0.002227340762576298)"
  },
  "1": {
    "newickString": "((((((AF_231119:0,AF231117:0)Node5:0.006543532687609313,(AF186242:0,AF186243:0)Node8:0)Node4:0.006572274533633557,AF234767:0.02013671713746686)Node3:0.006639669103016752,((AF231118:0.05462022348560171,AF231115:0)Node13:0,AF231114:0)Node12:0.006595785257879331)Node2:0,AF082576:0)Node1:0,(AF186241:0.01325799017773619,AF231113:0)Node18:0,(AF231116:0,AF187824:0)Node21:0.006577503418616471)"
  },
```

Best,
Sergei

**Comment by haruosuz** [comment]
Dear @spond 

Thank you for the advice. I wonder if there is any script to split an alignment file based on the best inferred partition using the ASSUMPTIONS block in the NEXUS file `.best-gard`.

References:
https://www.biostars.org/p/117854/
Split a concatenated alignment into individual gene alignments

**Comment by spond** [comment]
Dear @haruosuz,

There was no such script readily available, so I made one for you (and maybe others to use). The `biostars` example based on regular expression is fragile (will break for many valid NEXUS files, since it assumes that each `CHARSET` is the first entry on a new line.

https://github.com/veg/hyphy-analyses/tree/master/extract-partitions

Best,
Sergei

**Comment by haruosuz** [comment]
Dear @spond 

Thank you for providing the script.

I produced FASTA output files, using:
```
git clone https://github.com/veg/hyphy-analyses

BATCH_FILE=./hyphy-analyses/extract-partitions/extract-partitions.bf
NEXUS=./hyphy-analyses/extract-partitions/example.nex
DIR_OUTPUT=my_partitions; mkdir "${DIR_OUTPUT}"

conda activate hyphy
hyphy "${BATCH_FILE}" --msa "${NEXUS}" --output "${DIR_OUTPUT}/$(basename ${NEXUS})-parts" --extension fasta ENV="DATA_FILE_PRINT_FORMAT=9"

$find my_partitions | sort
my_partitions
my_partitions/example.nex-parts
my_partitions/example.nex-parts_SPAN_1.fasta
my_partitions/example.nex-parts_SPAN_2.fasta
my_partitions/example.nex-parts_SPAN_3.fasta
my_partitions/example.nex-parts_SPAN_4.fasta
my_partitions/example.nex-parts_SPAN_5.fasta
my_partitions/example.nex-parts_SPAN_6.fasta
my_partitions/example.nex-parts_SPAN_7.fasta
my_partitions/example.nex-parts_SPAN_8.fasta
my_partitions/example.nex-parts_SPAN_9.fasta
```

There is a phylogenetic tree in Newick format at the last part of the FASTA output files.

**Comment by haruosuz** [comment]
Dear @spond 

Thank you for providing the script. When I produced a FASTA output, there was a phylogenetic tree in Newick format at the last part of the FASTA output file. Is this a bug in the script?

I produced FASTA output files, using:
```
git clone https://github.com/veg/hyphy-analyses

BATCH_FILE=./hyphy-analyses/extract-partitions/extract-partitions.bf
NEXUS=./hyphy-analyses/extract-partitions/example.nex
DIR_OUTPUT=my_partitions; mkdir "${DIR_OUTPUT}"

conda activate hyphy
hyphy "${BATCH_FILE}" --msa "${NEXUS}" --output "${DIR_OUTPUT}/$(basename ${NEXUS})-parts" --extension fasta ENV="DATA_FILE_PRINT_FORMAT=9"

$find my_partitions | sort
my_partitions
my_partitions/example.nex-parts
my_partitions/example.nex-parts_SPAN_1.fasta
my_partitions/example.nex-parts_SPAN_2.fasta
my_partitions/example.nex-parts_SPAN_3.fasta
my_partitions/example.nex-parts_SPAN_4.fasta
my_partitions/example.nex-parts_SPAN_5.fasta
my_partitions/example.nex-parts_SPAN_6.fasta
my_partitions/example.nex-parts_SPAN_7.fasta
my_partitions/example.nex-parts_SPAN_8.fasta
my_partitions/example.nex-parts_SPAN_9.fasta
```

**Comment by spond** [comment]
Dear @haruosuz,

Not a bug, it's a feature:) 
Remember, GARD infers segments **and** trees for each segment. Those are the trees you see at the end of each FASTA file.

Best,
Sergei

**Comment by haruosuz** [comment]
Dear @spond

Is it recommended to trim alignments (remove all gaps) before running GARD?

**Comment by spond** [comment]
Dear @haruosuz,

You can trim leading and trailing gaps and possibly remove sites that have (i.e. if only a sequence or two have data at 5' and 3' ends), but other than that, you can keep the gaps in place. 

Best,
Sergei
