### ISSUE TITLE
MEDS?

### ISSUE THREAD

**Issue by ayssel-uct** [veg/hyphy#1408]
Older versions  included a model called "MEDS",did the name change? If it is not available anymore, which other model do you recommend for detecting whether there are different positive selection signals between datasets from two different time-points? (Some background: The data that I want to analyze is deep sequencing data from HIV positive patients sequenced at two different time-points)

**Comment by stevenweaver** [comment]
Dear @ayssel-uct, 

Thank you for your inquiry. Have you considered FADE at all? (Brief description on this page https://hyphy.org/methods/selection-methods/). 

It should be much faster considering it is building upon FUBAR and is supported by the latest version of HYPHY and Datamonkey. 

Best,
Steven

**Comment by ayssel-uct** [comment]
Awesome, thank you
