### ISSUE TITLE
How to interpretMEME results ?

### ISSUE THREAD

**Issue by 12suiyue** [veg/hyphy#1409]
Hello, your hyphy software is very good. I used MEME to try to analyze positively selected sites, but I don’t understand the result file generated. I can only see the site information, but I checked a lot of literature and saw some People can get the positive selection site of the corresponding gene (branch) through this result file. I want to know how this is obtained. Looking forward to your reply, thank you!

**Comment by stephenshank** [comment]
Dear @12suiyue,

I think the easiest way is to visualize your MEME results JSON by loading it into hyphy-vision: http://vision.hyphy.org/MEME.

There's a table where you can sort by p-value to obtain sites that show statistical significance for episodic diversification:
![image](https://user-images.githubusercontent.com/8673708/135276078-2b78dbec-a82f-4f3f-80ee-1839b5bbfad5.png)

There is also a way to explore branch-wise EBF values, though this is typically recommended only for exploratory analysis:
![image](https://user-images.githubusercontent.com/8673708/135276641-722e0ee8-d674-422f-ad6b-8f85107ffde1.png)

And plenty more. I'd recommend starting there. Feel free to ask further questions or post any issues you encounter here.

Best,
Stephen

**Comment by 12suiyue** [comment]
Thank you for your reply!I found If i use p-value sorting for sorting, I cannot get the gene (branching) information, but if I follow your second method and I enter the positive selection site displayed by MEME into the site to display, I find that the following evolutionary tree has some Genes or branches will be displayed in red. I would like to ask if this is a gene (branch) that contains a positive selection site, and whether the EBF threshold cannot be adjusted. I found that if it becomes smaller, the following evolutionary tree will be changed. Many genes are shown in red, and we look forward to hearing from you!
![SharedScreenshot1](https://user-images.githubusercontent.com/89245687/135281550-11de983a-99c8-4352-9bc9-53afd9f7ee05.jpg)
![SharedScreenshot](https://user-images.githubusercontent.com/89245687/135281561-ea2dc845-43ae-4395-9e02-7d4a36750dd3.jpg)

**Comment by stephenshank** [comment]
Dear @12suiyue,

The MEME EBFs are explained in the [associated publication](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1002764).

As far as I know, there is no formal statistical test being performed, which is why users are typically cautioned to only use these in exploratory analyses.

If you are interested in specific branches under selection, you may want to consider the [aBSREL method](https://hyphy.org/methods/selection-methods/).

Best,
Stephen

**Comment by spond** [comment]
Dear @12suiyue,

You can also use https://observablehq.com/@spond/plotting-meme-ebf-on-branches-at-individual-sites to load the JSON file; you can "hack" the notebook if you wish to adjust it.

Best,
Sergei
