### ISSUE TITLE
ABSREL with synonymous rate variation?

### ISSUE THREAD

**Issue by vinjlynch** [veg/hyphy#1410]
Hi All,

We are using ABSREL across ~12k genes to test for selection on a single lineage in a tree with 260 species. While we will compare results from the simple model to the two and three hit multi nucleotide mutation models, I'm also curious about the effects of synonymous rate variation on inferences of selection. Is there a way to include syn rate variation in ABSREL? We are also running BUSTED[S] with and without syn rate variation, but BUSTED doesn't seem to be the best choice for this because we are only testing a single lineage.

Thanks for the info,
Vinny

**Comment by spond** [comment]
Dear @vinjlynch,

There is no support for SRV in `aBSREL` at the moment. You could use BUSTED on a single branch assuming you use `--syn-rates` and `--rates` to select a small number of rates.

Best,
Sergei

**Comment by vinjlynch** [comment]
Thanks! We will give that a try and see what we see…

Sent from my iPhone

On Oct 4, 2021, at 4:42 PM, Sergei Pond ***@***.***> wrote:

﻿

Dear @vinjlynch<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvinjlynch&data=04%7C01%7Cvjlynch%40buffalo.edu%7C8b5827440af14dcb845e08d987778748%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637689769706876432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2F2YHNO77y90gEjAPu6Tlz8cwI55ey3CGc8gnEqgfn3E%3D&reserved=0>,

There is no support for SRV in aBSREL at the moment. You could use BUSTED on a single branch assuming you use --syn-rates and --rates to select a small number of rates.

Best,
Sergei

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fveg%2Fhyphy%2Fissues%2F1410%23issuecomment-933840009&data=04%7C01%7Cvjlynch%40buffalo.edu%7C8b5827440af14dcb845e08d987778748%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637689769706876432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zjRQLAo38CSFY4z%2BG4m0%2FtWd8OOwmpDY2S3o6yEGNJg%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANAFRREU6OUEIXHD3CM2XH3UFIGUPANCNFSM5FJ5GX4Q&data=04%7C01%7Cvjlynch%40buffalo.edu%7C8b5827440af14dcb845e08d987778748%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637689769706886389%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HFubsOyFpetARyIDX7WeqwjDuyV52i%2FlZ52yFnp8ls0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cvjlynch%40buffalo.edu%7C8b5827440af14dcb845e08d987778748%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637689769706886389%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KfgWog%2BXMFmMv494DEFtPOY83Z6UXFul5IRqVXy6iek%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cvjlynch%40buffalo.edu%7C8b5827440af14dcb845e08d987778748%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637689769706896344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MfHIRxFegLvkwCVhQ9OU6KZ8A4vqpT4e21xe4etXQNs%3D&reserved=0>.
