### ISSUE TITLE
Jobs not visible in queue no notification

### ISSUE THREAD

**Issue by markesiddall** [veg/hyphy#1416]
Hi,
I set up a BGM and a MEME run on DataMonkey
They no longer appear in the job queue. I don't want to load the server unnecessarily by creating new instances. 
Please advise

**Comment by stephenshank** [comment]
Dear @markesiddall,

I just checked our queue on the backend, and did not see any MEME or BGM jobs. Moreover, I ran one of each and was able to spot them in the queue:

![image](https://user-images.githubusercontent.com/8673708/138155230-feefad2d-248a-4cb6-b3da-88dbe49a7421.png)

I would recommend keeping track of URLs that correspond to specific jobs, either in a browser tab, spreadsheet, or by using the functionality to email upon completion.

Please let us know if you experience any further issues.

Best,
Stephen
