### ISSUE TITLE
CompareSelectivePressure.bf alternatives

### ISSUE THREAD

**Issue by rzhan186** [veg/hyphy#1422]
Dear Hyphy developers, 

I came across a tool called CompareSelectivePressure.bf from a Hyphy tutorial written back in 2007, the function of this tool seems to fit my purpose perfectly for comparing the selection of a homologous gene in different populations. However, the latest release of Hyphy doesn’t seem to support this function anymore, I am wondering if there are functions in hyphy that can be used for similar purposes? 

Thank you!

Rui

**Comment by spond** [comment]
Dear @rzhan186,

This test has largely been superseded by Contrast-FEL, which is available in HyPhy and Datamonkey.

Best,
Sergei

**Comment by rzhan186** [comment]
Thank you, this is really helpful!
