### ISSUE TITLE
SLAC

### ISSUE THREAD

**Issue by Kaparepen** [veg/hyphy#1425]
I don't know what I do when the mistake is: The alignment must include at least 3 unique sequences for selection methods to work. Could you help me please?

**Comment by spond** [comment]
Dear @Kaparepen,

This error message tells me that HyPhy loaded your alignment, discarded all identical sequences (retaining a single copy for all identical sequences), and ended up with 2 or fewer sequences. You cannot do a proper comparative analysis on ≤3 sequences with SLAC. All you can do, really, is estimate pairwise dN/dS if you have 2 sequences.

What was your input alignment?

Best,
Sergei

**Comment by Kaparepen** [comment]
Thanks for the response. I have 8 sequences for the same protein but each sequence is from different bacterial isolates, and I need to analyses the present SNPs in these sequences. The first sequence is from the reference strain.
 How could I do the dN / dS analysis?

King regards,
Karen

**Comment by spond** [comment]
Dear @Kaparepen,

Sorry, this information is insufficient for me to provide meaningful help. If you could attach your alignment here, that would be best. Barring that, please copy and paste the output from SLAC when you run your data through.

Best,
Sergei

**Comment by Kaparepen** [comment]
Thanks for the response.
Output SLAC : The alignment must include at least 3 unique sequences for  #selection methods to work
Input
[Input peptidase M4.txt](https://github.com/veg/hyphy/files/7499606/Input.peptidase.M4.txt)
>NZ_CP011849.2:c3148091-3146307/1-1782 Piscirickettsia salmonis LF-89 = ATCC VR-1361 chromosome, complete genome Peptidase M4
ATGCGAAAAAAAAATCTTGCTATTATTATTTCTGCGATTACTGCATCTACAGCACTGTTATCATCCCATGCA
TTAAGCACGGTAAATTCATATAATAAGCCTGTTTCCTCTTCTAATATTGAAGGTTTTGCGATTGAAGGTGCA
GGAGGTAGCTCAAATACGATGCTGTCAAGTCGCTCTGCTACAACGACTGATAAAAATACCCTAAGCCAAGTG
AGTAGTACGACAATGAATGGGGATACTTACGTACGTTACCAGCAAAAATATGAGGGTATTCCTGTAATTGGT
AAGCAGGTAGTGGTAAAACAGCCTAAAGCTGTTACTGGCTTTGCAGCAACGAGCCGATCGGCGTCGAGAGCT
ACAGCTACTCGAATATCTTTGGCAAAAGATTTAGATGTTGATTTGGTTGCAACAGTAAGCGCTGGTGATGCC
ATGGCGTTTGCAAAACAGCAGTTTGAGCAGAGCTATAGTGGTACACAAGTTGCTGATGGTTCTAATTCTGTT
AAGGCAACAAAAGAGATTCGTATTGTAGATAATAAAGCTCGGCTTTATTATCGAGTGACGTTTAATGCTAGT
AATACAGCTGGTGGTAAGCCATATAGTATGGTTTATATTATTGCTGCGAACGGTGGGGCTAAGCCTGTAGTG
CTTAAGCATTGGGACAATATTCAAAATTATGAAGATACTGGCCCTGGTGGAAATGAGAAAACGGTAAAGCAT
GGTCCAACAGGTGTTGAATTTTTTTATGGAGAAAATAATTTACCAGCATTGAATGTGAGTGAGAATAACGGC
AGTTGCACAATGGACAATGGAGATGTTCGGCTGGTTGATGTGCAGAATCAAGAGGATCACTCTTGGGATAGT
GATTACAATACAACGGCTTATCAATATAGCTGTGGCCACAATCAGGGTGATCCAATCAATGGTGCGTATTCA
CCCACAGATGATGCTTATTATTTTGGTAGTATGATTATTGATATGTATAAGAATTGGTATGGTGTTGATGCT
TTGCAAGAAAATGGTGAGCCAATGCAGTTAATTATGCGTGTACATTATGGTACTGATTATGACAATGCATTT
TGGGATGGACAGACCATGTCATTTGGCGATGGTAGTAGCTTTTATCCACTTGTATCTTTGGATGTCGCAGGT
CATGAAGTTAGCCATGGATTTACTGAGCAGCATTCGGGTTTAGAATATAGTGATCAATCAGGTTCATTAAAT
GAAGCCTTTTCTGACATGGCAGGCCAGGCAGTGCGAGCTTATTTATTAAGTACAAACTCTGACTTATACAAG
CAACTGTATTTTAATCAAGATGAAGTCACTTGGGGGATTGGTGAGACTATCATGAAAGGTGATAATACAGAT
ACGGCTTTGCGTTATATGGATCAGCCTTCTAAAGATCAAGATGAAAATGGTGTTTCGGCAGATTGTTTAGAT
AAGGATTTAGCAGGATCAGGGTGTATTATATCATATGATGATGTTGTCACCGCAGCAAAAAAACTCCCACTT
CGCTATCAGCAAAGTTATATCGTTCACCATGGAAGTGGTGTATTTAATAAGGCGTTTTACTTGTTATCACAA
CAGGTGGGTATTAAAGAAGCCTTTAAAGTGATGAAGGATGCGAATGCTACACGTTGGACTTCAGGTTCAGAT
TTTGCAGATGCTGCATGTGGTGTGCTTCAGGCAGCTCATGCTGATGGTGTGGGTTCTGACTCAATGATTAAA
GAAGTTTTTAATCAAGTGGGGGTTGCTATAGTAGATGAGGACTGCTCTACTAAG
>NZ_CP038893.1:36700-38432/1-1733 Piscirickettsia salmonis strain Psal-006a chromosome, complete genome Peptidase M4
ATGCGAAAAAAAAATCTTGCTATTATTATTTCTGCCATTACTGCATCTACTGCACTATTATCATCCCATGCA
TTAAGCACGGTAAATTCATACAATAAGCCTGTTTCCTCTTCTAATATCGAAGGTTTTGCGATTGAAGGTGCA
GGAGATAGCTCAAATACAATGCTATCAAGTCGCTCTGCTACAACGACTGATAAAAATACCCTAAGCCAAGTG
AGTAGTACGACAATGGATGGCGATACTTACATCCGTTACCAGCAAAAATATGAGGGTATTCCTGTAATCGGT
ACACAGGTGGTGGTAAAACAGCCTAAAGCTGTTACTGGTTTTGCAGCAACGAGCCGATCGGCATCGACGGCA
ACAGCTACTCGAATATCGTTGGCAAAAGATTTAGATGTTGATTTGGTTGCAACAGTGAGTGCTGATGATGCC
AAAGCATTTGCTAAACAGCAATTTGAAAAGGATTATAGTGGTACGCAAGTTGCTGATGACTCTATAAAGTCA
ACAAAAGAGATTCGTATTGTAGATAATAAAGCTCAGCTTTATTATCGAGTGACGTTTAATGCTAGCAATACA
GCTGGTGGTAAGCCATATCGTATGGTTTATATTATTAATGCCACTGGGACCTCTAAGGCTATGGTGCTGAGT
TTCTGGGACAGTATTCCAAATTATAGTGATACTGGGCCTGGTGGAAATGAGAAAACGGTACAGTATGGTCCA
ACAGGCGTTAAATTTTTTTATGGGGAAAATAATTTACCAGCCTTGAATGTGAGTGAGGACAACAGCACCTGC
ACGATGGACAATGGAGATGTTCGGTTGGTTAATGTAGAGCATCAAGCAGATCATTCTTGGGATAGTGATTAC
AACACAACGGCTTATCAATATAGCTGTGGCCACAATCAGGGTGATCCGATCAATGGTGCGTATTCACCTACA
GATGATGCTTATTATTTTGGTAGTATGATTATTGATATGTATAAGAATTGGTATGGTGTTGATGCTTTGCAA
GAAAATGGCGAGCCAATGCAATTAATTATGCGTGTCCATTATGGTACTGATTATGATAATGCATTTTGGGAT
GGGCATACTATGTCATTTGGCGATGGTAGTAGCTTTTATCCTCTTGTATCTCTGGATGTTGCAGGTCATGAA
GTGAGCCATGGATTTACTGAGCAGCACTCTGGTTTGGATTATAAATATCAATATGGATCATTAAATGAAGCC
TTTTCTGATATGGCAGGTCAAGCGGTGCGGGCTTATTTATTAAGTACAAATCCTGATTTATATAAGCAACTG
TACTTTAACCAAGATGAAGTTACTTGGGGTATTGGTGAAACAATTTCTAAAGGGGATGATGAGAGTGATGCC
CTACGTTATATGAATAACCCTTCTAAAGATGGAGTCTCGGCAGATTGTGATGATAAGGAATTAGCTGGATCG
ACGTGTACTATATCATATGATGAGGTAGTAGCTACCTCAAAAGACTACCCAATTAAAGATCGACAGAGTTAT
ATTGTTCATACTGGTAGTGGTGTATTTAATAAGGCGTTTTACTTGTTATCACAACAGGTGGGTATTAAAGAT
GCCTTTAGGGTAATGAAGGATGCGAATGTTAAATATTGGGGTAAATACTCAGATTTTTCAGATGCTGCATGT
GGTGTGCTAAAAGCTGCTAATGACGACGGTGTGGGTTCTACCTCAATGATTAAAGATGTTTTTAATCAAGTC
GGGGT-------------------------------------------------
>NZ_CP038908.1:35453-37185/1-1733 Piscirickettsia salmonis strain Psal-009 chromosome, complete genome Peptidase M4
ATGCGAAAAAAAAATCTTGCTATTATTATTTCTGCCATTACTGCATCTACTGCACTATTATCATCCCATGCA
TTAAGCACGGTAAATTCATACAATAAGCCTGTTTCCTCTTCTAATATCGAAGGTTTTGCGATTGAAGGTGCA
GGAGATAGCTCAAATACAATGCTATCAAGTCGCTCTGCTACAACGACTGATAAAAATACCCTAAGCCAAGTG
AGTAGTACGACAATGGATGGCGATACTTACATCCGTTACCAGCAAAAATATGAGGGTATTCCTGTAATCGGT
ACACAGGTGGTGGTAAAACAGCCTAAAGCTGTTACTGGTTTTGCAGCAACGAGCCGATCGGCATCGACGGCA
ACAGCTACTCGAATATCGTTGGCAAAAGATTTAGATGTTGATTTGGTTGCAACAGTGAGTGCTGATGATGCC
AAAGCATTTGCTAAACAGCAATTTGAAAAGGATTATAGTGGTACGCAAGTTGCTGATGACTCTATAAAGTCA
ACAAAAGAGATTCGTATTGTAGATAATAAAGCTCAGCTTTATTATCGAGTGACGTTTAATGCTAGCAATACA
GCTGGTGGTAAGCCATATCGTATGGTTTATATTATTAATGCCACTGGGACCTCTAAGGCTATGGTGCTGAGT
TTCTGGGACAGTATTCCAAATTATAGTGATACTGGGCCTGGTGGAAATGAGAAAACGGTACAGTATGGTCCA
ACAGGCGTTAAATTTTTTTATGGGGAAAATAATTTACCAGCCTTGAATGTGAGTGAGGACAACAGCACCTGC
ACGATGGACAATGGAGATGTTCGGTTGGTTAATGTAGAGCATCAAGCAGATCATTCTTGGGATAGTGATTAC
AACACAACGGCTTATCAATATAGCTGTGGCCACAATCAGGGTGATCCGATCAATGGTGCGTATTCACCTACA
GATGATGCTTATTATTTTGGTAGTATGATTATTGATATGTATAAGAATTGGTATGGTGTTGATGCTTTGCAA
GAAAATGGCGAGCCAATGCAATTAATTATGCGTGTCCATTATGGTACTGATTATGATAATGCATTTTGGGAT
GGGCATACTATGTCATTTGGCGATGGTAGTAGCTTTTATCCTCTTGTATCTCTGGATGTTGCAGGTCATGAA
GTGAGCCATGGATTTACTGAGCAGCACTCTGGTTTGGATTATAAATATCAATATGGATCATTAAATGAAGCC
TTTTCTGATATGGCAGGTCAAGCGGTGCGGGCTTATTTATTAAGTACAAATCCTGATTTATATAAGCAACTG
TACTTTAACCAAGATGAAGTTACTTGGGGTATTGGTGAAACAATTTCTAAAGGGGATGATGAGAGTGATGCC
CTACGTTATATGAATAACCCTTCTAAAGATGGAGTCTCGGCAGATTGTGATGATAAGGAATTAGCTGGATCG
ACGTGTACTATATCATATGATGAGGTAGTAGCTACCTCAAAAGACTACCCAATTAAAGATCGACAGAGTTAT
ATTGTTCATACTGGTAGTGGTGTATTTAATAAGGCGTTTTACTTGTTATCACAACAGGTGGGTATTAAAGAT
GCCTTTAGGGTAATGAAGGATGCGAATGTTAAATATTGGGGTAAATACTCAGATTTTTCAGATGCTGCATGT
GGTGTGCTAAAAGCTGCTAATGACGACGGTGTGGGTTCTACCTCAATGATTAAAGATGTTTTTAATCAAGTC
GGGGT-------------------------------------------------
>NZ_CP038923.1:35443-37175/1-1733 Piscirickettsia salmonis strain Psal-011 chromosome, complete genome Peptidasa M4
ATGCGAAAAAAAAATCTTGCTATTATTATTTCTGCCATTACTGCATCTACTGCACTATTATCATCCCATGCA
TTAAGCACGGTAAATTCATACAATAAGCCTGTTTCCTCTTCTAATATCGAAGGTTTTGCGATTGAAGGTGCA
GGAGATAGCTCAAATACAATGCTATCAAGTCGCTCTGCTACAACGACTGATAAAAATACCCTAAGCCAAGTG
AGTAGTACGACAATGGATGGCGATACTTACATCCGTTACCAGCAAAAATATGAGGGTATTCCTGTAATCGGT
ACACAGGTGGTGGTAAAACAGCCTAAAGCTGTTACTGGTTTTGCAGCAACGAGCCGATCGGCATCGACGGCA
ACAGCTACTCGAATATCGTTGGCAAAAGATTTAGATGTTGATTTGGTTGCAACAGTGAGTGCTGATGATGCC
AAAGCATTTGCTAAACAGCAATTTGAAAAGGATTATAGTGGTACGCAAGTTGCTGATGACTCTATAAAGTCA
ACAAAAGAGATTCGTATTGTAGATAATAAAGCTCAGCTTTATTATCGAGTGACGTTTAATGCTAGCAATACA
GCTGGTGGTAAGCCATATCGTATGGTTTATATTATTAATGCCACTGGGACCTCTAAGGCTATGGTGCTGAGT
TTCTGGGACAGTATTCCAAATTATAGTGATACTGGGCCTGGTGGAAATGAGAAAACGGTACAGTATGGTCCA
ACAGGCGTTAAATTTTTTTATGGGGAAAATAATTTACCAGCCTTGAATGTGAGTGAGGACAACAGCACCTGC
ACGATGGACAATGGAGATGTTCGGTTGGTTAATGTAGAGCATCAAGCAGATCATTCTTGGGATAGTGATTAC
AACACAACGGCTTATCAATATAGCTGTGGCCACAATCAGGGTGATCCGATCAATGGTGCGTATTCACCTACA
GATGATGCTTATTATTTTGGTAGTATGATTATTGATATGTATAAGAATTGGTATGGTGTTGATGCTTTGCAA
GAAAATGGCGAGCCAATGCAATTAATTATGCGTGTCCATTATGGTACTGATTATGATAATGCATTTTGGGAT
GGGCATACTATGTCATTTGGCGATGGTAGTAGCTTTTATCCTCTTGTATCTCTGGATGTTGCAGGTCATGAA
GTGAGCCATGGATTTACTGAGCAGCACTCTGGTTTGGATTATAAATATCAATATGGATCATTAAATGAAGCC
TTTTCTGATATGGCAGGTCAAGCGGTGCGGGCTTATTTATTAAGTACAAATCCTGATTTATATAAGCAACTG
TACTTTAACCAAGATGAAGTTACTTGGGGTATTGGTGAAACAATTTCTAAAGGGGATGATGAGAGTGATGCC
CTACGTTATATGAATAACCCTTCTAAAGATGGAGTCTCGGCAGATTGTGATGATAAGGAATTAGCTGGATCG
ACGTGTACTATATCATATGATGAGGTAGTAGCTACCTCAAAAGACTACCCAATTAAAGATCGACAGAGTTAT
ATTGTTCATACTGGTAGTGGTGTATTTAATAAGGCGTTTTACTTGTTATCACAACAGGTGGGTATTAAAGAT
GCCTTTAGGGTAATGAAGGATGCGAATGTTAAATATTGGGGTAAATACTCAGATTTTTCAGATGCTGCATGT
GGTGTGCTAAAAGCTGCTAATGACGACGGTGTGGGTTCTACCTCAATGATTAAAGATGTTTTTAATCAAGTC
GGGGT-------------------------------------------------
>NZ_CP038811.1:35443-37175/1-1733 Piscirickettsia salmonis strain Psal-001 chromosome, complete genome Peptidase M4
ATGCGAAAAAAAAATCTTGCTATTATTATTTCTGCCATTACTGCATCTACTGCACTATTATCATCCCATGCA
TTAAGCACGGTAAATTCATACAATAAGCCTGTTTCCTCTTCTAATATCGAAGGTTTTGCGATTGAAGGTGCA
GGAGATAGCTCAAATACAATGCTATCAAGTCGCTCTGCTACAACGACTGATAAAAATACCCTAAGCCAAGTG
AGTAGTACGACAATGGATGGCGATACTTACATCCGTTACCAGCAAAAATATGAGGGTATTCCTGTAATCGGT
ACACAGGTGGTGGTAAAACAGCCTAAAGCTGTTACTGGTTTTGCAGCAACGAGCCGATCGGCATCGACGGCA
ACAGCTACTCGAATATCGTTGGCAAAAGATTTAGATGTTGATTTGGTTGCAACAGTGAGTGCTGATGATGCC
AAAGCATTTGCTAAACAGCAATTTGAAAAGGATTATAGTGGTACGCAAGTTGCTGATGACTCTATAAAGTCA
ACAAAAGAGATTCGTATTGTAGATAATAAAGCTCAGCTTTATTATCGAGTGACGTTTAATGCTAGCAATACA
GCTGGTGGTAAGCCATATCGTATGGTTTATATTATTAATGCCACTGGGACCTCTAAGGCTATGGTGCTGAGT
TTCTGGGACAGTATTCCAAATTATAGTGATACTGGGCCTGGTGGAAATGAGAAAACGGTACAGTATGGTCCA
ACAGGCGTTAAATTTTTTTATGGGGAAAATAATTTACCAGCCTTGAATGTGAGTGAGGACAACAGCACCTGC
ACGATGGACAATGGAGATGTTCGGTTGGTTAATGTAGAGCATCAAGCAGATCATTCTTGGGATAGTGATTAC
AACACAACGGCTTATCAATATAGCTGTGGCCACAATCAGGGTGATCCGATCAATGGTGCGTATTCACCTACA
GATGATGCTTATTATTTTGGTAGTATGATTATTGATATGTATAAGAATTGGTATGGTGTTGATGCTTTGCAA
GAAAATGGCGAGCCAATGCAATTAATTATGCGTGTCCATTATGGTACTGATTATGATAATGCATTTTGGGAT
GGGCATACTATGTCATTTGGCGATGGTAGTAGCTTTTATCCTCTTGTATCTCTGGATGTTGCAGGTCATGAA
GTGAGCCATGGATTTACTGAGCAGCACTCTGGTTTGGATTATAAATATCAATATGGATCATTAAATGAAGCC
TTTTCTGATATGGCAGGTCAAGCGGTGCGGGCTTATTTATTAAGTACAAATCCTGATTTATATAAGCAACTG
TACTTTAACCAAGATGAAGTTACTTGGGGTATTGGTGAAACAATTTCTAAAGGGGATGATGAGAGTGATGCC
CTACGTTATATGAATAACCCTTCTAAAGATGGAGTCTCGGCAGATTGTGATGATAAGGAATTAGCTGGATCG
ACGTGTACTATATCATATGATGAGGTAGTAGCTACCTCAAAAGACTACCCAATTAAAGATCGACAGAGTTAT
ATTGTTCATACTGGTAGTGGTGTATTTAATAAGGCGTTTTACTTGTTATCACAACAGGTGGGTATTAAAGAT
GCCTTTAGGGTAATGAAGGATGCGAATGTTAAATATTGGGGTAAATACTCAGATTTTTCAGATGCTGCATGT
GGTGTGCTAAAAGCTGCTAATGACGACGGTGTGGGTTCTACCTCAATGATTAAAGATGTTTTTAATCAAGTC
GGGGT-------------------------------------------------
>CP038891.1:35443-37175/1-1733 Piscirickettsia salmonis strain Psal-005 chromosome, complete genome Peptidase M4
ATGCGAAAAAAAAATCTTGCTATTATTATTTCTGCCATTACTGCATCTACTGCACTATTATCATCCCATGCA
TTAAGCACGGTAAATTCATACAATAAGCCTGTTTCCTCTTCTAATATCGAAGGTTTTGCGATTGAAGGTGCA
GGAGATAGCTCAAATACAATGCTATCAAGTCGCTCTGCTACAACGACTGATAAAAATACCCTAAGCCAAGTG
AGTAGTACGACAATGGATGGCGATACTTACATCCGTTACCAGCAAAAATATGAGGGTATTCCTGTAATCGGT
ACACAGGTGGTGGTAAAACAGCCTAAAGCTGTTACTGGTTTTGCAGCAACGAGCCGATCGGCATCGACGGCA
ACAGCTACTCGAATATCGTTGGCAAAAGATTTAGATGTTGATTTGGTTGCAACAGTGAGTGCTGATGATGCC
AAAGCATTTGCTAAACAGCAATTTGAAAAGGATTATAGTGGTACGCAAGTTGCTGATGACTCTATAAAGTCA
ACAAAAGAGATTCGTATTGTAGATAATAAAGCTCAGCTTTATTATCGAGTGACGTTTAATGCTAGCAATACA
GCTGGTGGTAAGCCATATCGTATGGTTTATATTATTAATGCCACTGGGACCTCTAAGGCTATGGTGCTGAGT
TTCTGGGACAGTATTCCAAATTATAGTGATACTGGGCCTGGTGGAAATGAGAAAACGGTACAGTATGGTCCA
ACAGGCGTTAAATTTTTTTATGGGGAAAATAATTTACCAGCCTTGAATGTGAGTGAGGACAACAGCACCTGC
ACGATGGACAATGGAGATGTTCGGTTGGTTAATGTAGAGCATCAAGCAGATCATTCTTGGGATAGTGATTAC
AACACAACGGCTTATCAATATAGCTGTGGCCACAATCAGGGTGATCCGATCAATGGTGCGTATTCACCTACA
GATGATGCTTATTATTTTGGTAGTATGATTATTGATATGTATAAGAATTGGTATGGTGTTGATGCTTTGCAA
GAAAATGGCGAGCCAATGCAATTAATTATGCGTGTCCATTATGGTACTGATTATGATAATGCATTTTGGGAT
GGGCATACTATGTCATTTGGCGATGGTAGTAGCTTTTATCCTCTTGTATCTCTGGATGTTGCAGGTCATGAA
GTGAGCCATGGATTTACTGAGCAGCACTCTGGTTTGGATTATAAATATCAATATGGATCATTAAATGAAGCC
TTTTCTGATATGGCAGGTCAAGCGGTGCGGGCTTATTTATTAAGTACAAATCCTGATTTATATAAGCAACTG
TACTTTAACCAAGATGAAGTTACTTGGGGTATTGGTGAAACAATTTCTAAAGGGGATGATGAGAGTGATGCC
CTACGTTATATGAATAACCCTTCTAAAGATGGAGTCTCGGCAGATTGTGATGATAAGGAATTAGCTGGATCG
ACGTGTACTATATCATATGATGAGGTAGTAGCTACCTCAAAAGACTACCCAATTAAAGATCGACAGAGTTAT
ATTGTTCATACTGGTAGTGGTGTATTTAATAAGGCGTTTTACTTGTTATCACAACAGGTGGGTATTAAAGAT
GCCTTTAGGGTAATGAAGGATGCGAATGTTAAATATTGGGGTAAATACTCAGATTTTTCAGATGCTGCATGT
GGTGTGCTAAAAGCTGCTAATGACGACGGTGTGGGTTCTACCTCAATGATTAAAGATGTTTTTAATCAAGTC
GGGGT-------------------------------------------------
>NZ_CP038972.1:35443-37175/1-1733 Piscirickettsia salmonis strain Psal-069 chromosome, complete genome Peptidase M4
ATGCGAAAAAAAAATCTTGCTATTATTATTTCTGCCATTACTGCATCTACTGCACTATTATCATCCCATGCA
TTAAGCACGGTAAATTCATACAATAAGCCTGTTTCCTCTTCTAATATCGAAGGTTTTGCGATTGAAGGTGCA
GGAGATAGCTCAAATACAATGCTATCAAGTCGCTCTGCTACAACGACTGATAAAAATACCCTAAGCCAAGTG
AGTAGTACGACAATGGATGGCGATACTTACATCCGTTACCAGCAAAAATATGAGGGTATTCCTGTAATCGGT
ACACAGGTGGTGGTAAAACAGCCTAAAGCTGTTACTGGTTTTGCAGCAACGAGCCGATCGGCATCGACGGCA
ACAGCTACTCGAATATCGTTGGCAAAAGATTTAGATGTTGATTTGGTTGCAACAGTGAGTGCTGATGATGCC
AAAGCATTTGCTAAACAGCAATTTGAAAAGGATTATAGTGGTACGCAAGTTGCTGATGACTCTATAAAGTCA
ACAAAAGAGATTCGTATTGTAGATAATAAAGCTCAGCTTTATTATCGAGTGACGTTTAATGCTAGCAATACA
GCTGGTGGTAAGCCATATCGTATGGTTTATATTATTAATGCCACTGGGACCTCTAAGGCTATGGTGCTGAGT
TTCTGGGACAGTATTCCAAATTATAGTGATACTGGGCCTGGTGGAAATGAGAAAACGGTACAGTATGGTCCA
ACAGGCGTTAAATTTTTTTATGGGGAAAATAATTTACCAGCCTTGAATGTGAGTGAGGACAACAGCACCTGC
ACGATGGACAATGGAGATGTTCGGTTGGTTAATGTAGAGCATCAAGCAGATCATTCTTGGGATAGTGATTAC
AACACAACGGCTTATCAATATAGCTGTGGCCACAATCAGGGTGATCCGATCAATGGTGCGTATTCACCTACA
GATGATGCTTATTATTTTGGTAGTATGATTATTGATATGTATAAGAATTGGTATGGTGTTGATGCTTTGCAA
GAAAATGGCGAGCCAATGCAATTAATTATGCGTGTCCATTATGGTACTGATTATGATAATGCATTTTGGGAT
GGGCATACTATGTCATTTGGCGATGGTAGTAGCTTTTATCCTCTTGTATCTCTGGATGTTGCAGGTCATGAA
GTGAGCCATGGATTTACTGAGCAGCACTCTGGTTTGGATTATAAATATCAATATGGATCATTAAATGAAGCC
TTTTCTGATATGGCAGGTCAAGCGGTGCGGGCTTATTTATTAAGTACAAATCCTGATTTATATAAGCAACTG
TACTTTAACCAAGATGAAGTTACTTGGGGTATTGGTGAAACAATTTCTAAAGGGGATGATGAGAGTGATGCC
CTACGTTATATGAATAACCCTTCTAAAGATGGAGTCTCGGCAGATTGTGATGATAAGGAATTAGCTGGATCG
ACGTGTACTATATCATATGATGAGGTAGTAGCTACCTCAAAAGACTACCCAATTAAAGATCGACAGAGTTAT
ATTGTTCATACTGGTAGTGGTGTATTTAATAAGGCGTTTTACTTGTTATCACAACAGGTGGGTATTAAAGAT
GCCTTTAGGGTAATGAAGGATGCGAATGTTAAATATTGGGGTAAATACTCAGATTTTTCAGATGCTGCATGT
GGTGTGCTAAAAGCTGCTAATGACGACGGTGTGGGTTCTACCTCAATGATTAAAGATGTTTTTAATCAAGTC
GGGGT-------------------------------------------------
>NZ_CP039040.1:35453-37185/1-1733 Piscirickettsia salmonis strain Psal-072 chromosome, complete genome Peptidase M4
ATGCGAAAAAAAAATCTTGCTATTATTATTTCTGCCATTACTGCATCTACTGCACTATTATCATCCCATGCA
TTAAGCACGGTAAATTCATACAATAAGCCTGTTTCCTCTTCTAATATCGAAGGTTTTGCGATTGAAGGTGCA
GGAGATAGCTCAAATACAATGCTATCAAGTCGCTCTGCTACAACGACTGATAAAAATACCCTAAGCCAAGTG
AGTAGTACGACAATGGATGGCGATACTTACATCCGTTACCAGCAAAAATATGAGGGTATTCCTGTAATCGGT
ACACAGGTGGTGGTAAAACAGCCTAAAGCTGTTACTGGTTTTGCAGCAACGAGCCGATCGGCATCGACGGCA
ACAGCTACTCGAATATCGTTGGCAAAAGATTTAGATGTTGATTTGGTTGCAACAGTGAGTGCTGATGATGCC
AAAGCATTTGCTAAACAGCAATTTGAAAAGGATTATAGTGGTACGCAAGTTGCTGATGACTCTATAAAGTCA
ACAAAAGAGATTCGTATTGTAGATAATAAAGCTCAGCTTTATTATCGAGTGACGTTTAATGCTAGCAATACA
GCTGGTGGTAAGCCATATCGTATGGTTTATATTATTAATGCCACTGGGACCTCTAAGGCTATGGTGCTGAGT
TTCTGGGACAGTATTCCAAATTATAGTGATACTGGGCCTGGTGGAAATGAGAAAACGGTACAGTATGGTCCA
ACAGGCGTTAAATTTTTTTATGGGGAAAATAATTTACCAGCCTTGAATGTGAGTGAGGACAACAGCACCTGC
ACGATGGACAATGGAGATGTTCGGTTGGTTAATGTAGAGCATCAAGCAGATCATTCTTGGGATAGTGATTAC
AACACAACGGCTTATCAATATAGCTGTGGCCACAATCAGGGTGATCCGATCAATGGTGCGTATTCACCTACA
GATGATGCTTATTATTTTGGTAGTATGATTATTGATATGTATAAGAATTGGTATGGTGTTGATGCTTTGCAA
GAAAATGGCGAGCCAATGCAATTAATTATGCGTGTCCATTATGGTACTGATTATGATAATGCATTTTGGGAT
GGGCATACTATGTCATTTGGCGATGGTAGTAGCTTTTATCCTCTTGTATCTCTGGATGTTGCAGGTCATGAA
GTGAGCCATGGATTTACTGAGCAGCACTCTGGTTTGGATTATAAATATCAATATGGATCATTAAATGAAGCC
TTTTCTGATATGGCAGGTCAAGCGGTGCGGGCTTATTTATTAAGTACAAATCCTGATTTATATAAGCAACTG
TACTTTAACCAAGATGAAGTTACTTGGGGTATTGGTGAAACAATTTCTAAAGGGGATGATGAGAGTGATGCC
CTACGTTATATGAATAACCCTTCTAAAGATGGAGTCTCGGCAGATTGTGATGATAAGGAATTAGCTGGATCG
ACGTGTACTATATCATATGATGAGGTAGTAGCTACCTCAAAAGACTACCCAATTAAAGATCGACAGAGTTAT
ATTGTTCATACTGGTAGTGGTGTATTTAATAAGGCGTTTTACTTGTTATCACAACAGGTGGGTATTAAAGAT
GCCTTTAGGGTAATGAAGGATGCGAATGTTAAATATTGGGGTAAATACTCAGATTTTTCAGATGCTGCATGT
GGTGTGCTAAAAGCTGCTAATGACGACGGTGTGGGTTCTACCTCAATGATTAAAGATGTTTTTAATCAAGTC
GGGGT-------------------------------------------------

**Comment by spond** [comment]
Dear @Kaparepen,

Out of 8 sequences in your alignment, 6 are duplicates (identical copies); Datamonkey.org will automatically prune those out, yielding 2 sequences (and the error). If you run it locally in HyPhy, e.g. 

```
hyphy slac --alignment ~/Downloads/Input.peptidase.M4.txt --tree neighbor-joining
```

You will see the following message 

```
-------
>[WARNING] This dataset contains 6 duplicate sequences. Identical
sequences do not contribute any information to the analysis and only
slow down computation. Please consider removing duplicate or 'nearly'
duplicate sequences, e.g. using
https://github.com/veg/hyphy-analyses/tree/master/remove-duplicates
prior to running selection analyses
-------
```

Best,
Sergei

**Comment by Stradichenko** [comment]
Good evening;
Like @spond, I'm having this issue; which is strange to me because in my case I'm using 200 sequences, many with different lenghts and nucleotides, from a big variety of species, very visible in MEGA. So is unclear to me what _identical_ refers to. In my case I just want to do a dn/ds (ka/ks) but I'm unclear why is not processing any input.

**Comment by stevenweaver** [comment]
Dear @Stradichenko, 

Just as a sanity check, did you align the sequences first before trying SLAC?

Best,
Steven

**Comment by Stradichenko** [comment]
Hi @stevenweaver,
I was double checking... I did an Muscle alignment and the format is .mas (from MEGA). I don't know if this may be involved somehow. 
The data comes from Ensembl Compara orthologs for Olig2:
https://www.ensembl.org/Homo_sapiens/Gene/Compara_Ortholog?db=core;g=ENSG00000205927;r=21:33025935-33029196

Thank you for your attention,
Gary.

**Comment by spond** [comment]
Dear @Stradichenko,

Could you please include your alignment as a text attachment for me to check what's going on?

Best,
Sergei

**Comment by Stradichenko** [comment]
Hi @spond;
I double-double checked and it was an error on my side while clearing the stop codons in sequences. To solve that I tried the code from this [post](https://github.com/veg/hyphy-analyses/tree/master/codon-msa) but I ran with the following error on my file named `example.fas` in my conda env named `env_name`:
```
$ hyphy pre-msa.bf --input example.fas
Error:
Could not read batch file '/home/.../ensembl-data/pre-msa.bf'.
Path stack:
        /home/.../.conda/envs/env_name/lib/hyphy/
        /home/.../ensembl-data/

Check errors.log for execution error details.
```

**Comment by spond** [comment]
Dear @Stradichenko,

`pre-msa.bf` is not a standard analyses, so HyPhy will look for the file in the same directory that you are calling in from (`ensembl-data`), and then the HyPhy installation directory (`/.conda/envs/env_name/lib/hyphy/`). 

You need to download `codon-msa` as a part of [`hyphy-analyses` ](https://github.com/veg/hyphy-analyses), and then either call HyPhy from the `codon-msa` directory or do something like 

```
 $hyphy /path/to/pre-msa.bf ...
```

Best,
Sergei
