### ISSUE TITLE
absrel job error with no clear explanation

### ISSUE THREAD

**Issue by krausedkrause** [veg/hyphy#1426]
Hello,
I submitted job 6181549e29c33675d3c33796 on 11/2, and things seemed to be going well until yesterday when it had an error. It appears to still be running according to the job queue, and when I checked the log file it is still outputting new information, but there is nothing visible in the log file to suggest what the error is/was.
Thanks for your help!
Dave

**Comment by spond** [comment]
Dear @krausedkrause,

This is indeed odd. The job is still running on the cluster. I'll post results when it finishes. @stephenshank or @stevenweaver : any ideas what happened?

Best,
Sergei

**Comment by stephenshank** [comment]
Dear @krausedkrause and @spond,

Odd indeed. It does appear to still be running, so I marked it as such in the database and you can now access the job page once again.

We'll keep an eye on it, do let us know if anything changes.

Best,
Stephen

**Comment by krausedkrause** [comment]
It looks like it sent an error message to me again on Thursday afternoon, but with nothing clear in the logfile about what the error was. I am attaching the logfile, and the job is no longer on the queue this time.
[absrel_log.txt](https://github.com/veg/hyphy/files/7506627/absrel_log.txt)

**Comment by stephenshank** [comment]
As far as I can tell, this job hit the 3 day wall time limit for Datamonkey. There's a progress file that does not seem complete and only an empty results JSON, unfortunately.

There's a lot of sequences in the input (277) for an aBSREL job to be ran on Datamonkey with such limitations. You can check our [usage statistics](http://datamonkey.org/stats) page to see what types of jobs typically complete. It seems like jobs that complete with this many sequences are an outlier.

![image](https://user-images.githubusercontent.com/8673708/140975665-8120a540-03aa-4c48-b832-ca012ce9c6a4.png)
