### ISSUE TITLE
Can HyPhy calculate the migration events stratified by the attributes using the SlatkinMaddison.bf?

### ISSUE THREAD

**Issue by gxcdcjh** [veg/hyphy#1429]
The SlatkinMaddison.bf can calculate the overall migration events. But I want to calculate the migration events stratified by the attributes. I would be greatly appreciated if you could tell me about the detailed methods.

**Comment by spond** [comment]
Dear @gxcdcjh,

Slatkin Maddison can compute migration events between multiple groups, breaking them out by the type of substitution. For example running it on the attached tree (with three groups) as 

```
hyphy sm --tree three-group.txt --regexp-1 '_1' --description-1 'Group 1' --regexp-2 '_2' --description-2 'Group 2' --regexp-3 '_3' --description-3 'Group 3' --groups 3
```

yields the JSON file `three-group.txt.SM.json`. Within this file, you an look at the object indexed by `events` to see which branches had which migration events.

Best,
Sergei

```
 "events":{
   "10_1":{
     "from":"Group 2",
     "to":"Group 1"
    },
   "22_2":{
     "from":"Group 1",
     "to":"Group 2"
    },
   "25_2":{
     "from":"Group 1",
     "to":"Group 2"
    },
   "27_2":{
     "from":"Group 1",
     "to":"Group 2"
    },
   "28_2":{
     "from":"Group 1",
     "to":"Group 2"
    },
   "29_3":{
     "from":"Group 1",
     "to":"Group 3"
    },
   "2_1":{
     "from":"Group 2",
     "to":"Group 1"
    },
   "31_3":{
     "from":"Group 1",
     "to":"Group 3"
    },
   "35_2":{
     "from":"Group 1",
     "to":"Group 2"
    },
   "39_2":{
     "from":"Group 1",
     "to":"Group 2"
    },
   "40_2":{
     "from":"Group 1",
     "to":"Group 2"
    },
   "Node31":{
     "from":"Group 2",
     "to":"Group 1"
    },
   "Node4":{
     "from":"Group 2",
     "to":"Group 1"
    },
   "Node64":{
     "from":"Group 1",
     "to":"Group 3"
    }
  }
```

[three-group.txt](https://github.com/veg/hyphy/files/7548469/three-group.txt)

**Comment by gxcdcjh** [comment]
Dear @spond 
Thank you very much! This code is useful. Additionally, Slatkin Maddison also provides the subsequent permutation test. Is it possible to perform multiple comparisons between groups?
