### ISSUE TITLE
FUBAR stop codons in nucleotide alignment

### ISSUE THREAD

**Issue by HanoverM** [veg/hyphy#1430]
I am attempting to run FUBAR on datamonkey.org on a set of shark variable new antigen receptor (VNAR) sequences. I have generated a FASTA nucleotide alignment of my sequences using ClustalW and a phylogeny tree using FASTTREE. When I try to run FUBAR, I receive a message that stop codons have been identified in my alignment.

All my sequences can be properly translated to the correct protein sequence in reading frame 3 and do not contain stop codons, but translation in reading frames 1 and 2 would result in stop codons appearing but the incorrect protein sequence.

Is there no way to account for the correct reading frame to specify for FUBAR? Does FUBAR automatically translate any submitted nucleotide sequences in the 5' to 3' frame 1? I can't seem to find an answer to this in the documentation for the tool.

Thank you,

Hanover

**Comment by spond** [comment]
Dear @HanoverM,

Your alignment needs to be in frame starting at position 1. Datamonkey methods do not attempt to identify reading frames. That should be done prior to submitting your alignment. 

Best,
Sergei

**Comment by HanoverM** [comment]
Thanks Sergei. I will work on correcting my alignments.

- HM
