### ISSUE TITLE
How to infer selection pressure against of test branches against reference branches?

### ISSUE THREAD

**Issue by thuthuynguyend07** [veg/hyphy#1432]
Hi HYPHY support team and Dr. Pond, 
I'm working with longitudinal viral sequences and want to infer individual sites undergoing selection pressure of some test sequences against other reference sequences of the same individuals. 
I know that RELAX is one approach that allows such relative comparison between test and reference branches but it doesn't identify which sites on the branches are responsible for such relaxed or intensified selection.
I wonder if there's a way to do that with MEME or FUBAR, i.e. identify individual sites subject to selection relative to other branches.
Thank you very much.

**Comment by spond** [comment]
Dear @thuthuynguyend07,

You may want to check out Contrast-FEL (https://academic.oup.com/mbe/article/38/3/1184/5926108). It is available in HyPhy and on Datamonkey.

Best,
Sergei
