### ISSUE TITLE
aBSREL - locating nodes under selection in tree

### ISSUE THREAD

**Issue by SticaC** [veg/hyphy#1434]
Hi,

Under the following three urls, there are nodes under positive selection:

http://datamonkey.org/absrel/60c817121735c43bacd220dc
http://datamonkey.org/absrel/60c95d6c1735c43bacd2542d
http://datamonkey.org/absrel/60c2bb90d0841316fd5cec07

The trees are very large and I am unsure how to locate the specific location of these nodes. If I download the tree file and open in FigTree, so that I can zoom in more, I cant find a way to display the node numbers.

Thanks
Caleb

**Comment by stevenweaver** [comment]
Dear @SticaC, 

Thank you for raising this issue. It is indeed an issue where the newick tree that is exported is excising internal node labels. 

While this is being resolved, you can locate the newick trees with internal node labels by appending `results` to the urls like :

http://datamonkey.org/absrel/60c817121735c43bacd220dc/results

Then searching the document for `trees`. 

Note internal labels here:
https://observablehq.com/d/2ec0a8092bbafd32

There are plans to update the rest of our results pages (as we've done with GARD and FEL), but hopefully this helps in the interim.

Best,
Steven

**Comment by spond** [comment]
Dear @SticaC,

Take a look at https://observablehq.com/@spond/displaying-absrel-results-using-branch-censoring
This should get you most of the way there.

Best,
Sergei

**Comment by SticaC** [comment]
Amazing. Thank you both!

Caleb
