### ISSUE TITLE
unable to run FUBAR

### ISSUE THREAD

**Issue by kdbchau** [veg/hyphy#1440]
Cannot run any jobs for FUBAR on datamonkey server. Constantly getting the error below. I tested this with old files that worked a few months ago and same error persists.

![image](https://user-images.githubusercontent.com/24414352/145681159-eb26657a-7b50-4d8c-b123-2b1374314362.png)

**Comment by spond** [comment]
Dear @kdbchau,

We are in the process of a major cluster upgrade, and it seems like there are some "growing pains" with the Datamonkey service. We will attempt to resolve them as quickly as possible. Stay tuned.

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @kdbchau, 

We performed maintenance on our computing cluster that resulted in a disruption of services. The site should be operating as expected now. 

Best,
Steven
