### ISSUE TITLE
MEME error

### ISSUE THREAD

**Issue by ban2224** [veg/hyphy#1441]
Hi again, the same error from last time is still an issue even though I was told the website should be working. 

openmpi/gnu(3):ERROR:105: Unable to locate a modulefile for 'openmpi/gnu/3.0.2'
/var/spool/torque/mom_priv/jobs/1903253.new-silverback.SC: line 30: mpirun: command not found

**Comment by stevenweaver** [comment]
Sorry, a bit quick. I'm still propagating the fix. One moment.

**Comment by stevenweaver** [comment]
Should be fully resolved at this point. Duplicate of #1437
