### ISSUE TITLE
Incomplete partionned data

### ISSUE THREAD

**Issue by ArfBAD2021** [veg/hyphy#1444]
Hi
I have been run GARD with viral sequences (59 sequences for 9693 sites), but always receive and incomplete partitioned data (.nex file). The number of trees is always incomplete at the bottom of the file, which makes it fail to run in other analyses in Datamonkey.org on HyPhy in Linux. Please, could you help me overcome this PROBLEM? I would be really greatful

**Comment by spond** [comment]
Dear @ArfBAD2021,

Could you please provide a link to the job where this occurs?

Best,
Sergei

**Comment by ArfBAD2021** [comment]
Please, see below

http://datamonkey.org/gard/61befedc652a48728e654f7a
http://datamonkey.org/gard/61beff35652a48728e654fb9
http://datamonkey.org/gard/61beff7a652a48728e654ff8
http://datamonkey.org/gard/61beffb7652a48728e655037
http://datamonkey.org/gard/61bf000b652a48728e655076

Thank you

*Arfang BADJI*
*Post-doctoral fellow, **NaCRRI (National Crop Resources Research
Institute, Namulonge, Uganda) - **Makerere University, Kampala, Uganda.*

*Ph.D. Plant Breeding and Biotechnology/MSc: Plant and Microbial
Biotechnologies *
*Mobile: +256756736561*
* Skype: arf.bad*
https://orcid.org/0000-0003-1105-9668
*Expertise and interests: Plant Breeding, Agri-genomics, Phylogenetics,
Bioinformatics, Biotechnologies...*

**Comment by ArfBAD2021** [comment]
Hi Sergei
Any update about the GARD analysis?
Thank you
*Arfang BADJI*
*Post-doctoral fellow, **NaCRRI (National Crop Resources Research
Institute, Namulonge, Uganda) - **Makerere University, Kampala, Uganda.*

*Ph.D. Plant Breeding and Biotechnology/MSc: Plant and Microbial
Biotechnologies *
*Mobile: +256756736561*
* Skype: arf.bad*
https://orcid.org/0000-0003-1105-9668
*Expertise and interests: Plant Breeding, Agri-genomics, Phylogenetics,
Bioinformatics, Biotechnologies...*
