### ISSUE TITLE
Bacterial genetic code

### ISSUE THREAD

**Issue by Jigyasa3** [veg/hyphy#1445]
Hey!

I am interested in using RELAX and aBSREL on a bacterial gene tree (single-copy protein-coding gene). I have generated the protein-coding nucleotide alignment using the bacterial genetic code (code-11). I wanted to ask if the Bacterial genetic code is supported? I have searched the tutorials and documentation of hyphy but the Universal genetic code is recommended. Would the Universal genetic code work if the initial alignment and tree are generated from the Bacterial genetic code?

**Comment by spond** [comment]
Dear @Jigyasa3,

Yes, please use the Universal code. Codon models do not make explicit use of initiation codons, all they need to account for are stop codons. Those are the same between table 11 (https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi#SG11) and the Universal GC.

Best,
Sergei
