### ISSUE TITLE
Error when running relax on command line

### ISSUE THREAD

**Issue by Jigyasa3** [veg/hyphy#1446]
Hey!

I am interested in testing the RELAX output on a user-defined tree, so I am running RELAX on the command line version.
I have tried giving the node names in the `--test` and `--reference` flags but it doesn't seem to be working. Any help would be great!

Code used-
`/flash/BourguignonU/Tool/hyphy/opt/hyphy/bin/hyphy relax --alignment d__Bacteria_p__Fibrobacterota__p__Bacteroidota__p__UBP14__COG0552_tips_2_.fasta --tree tree8.nwk --test 211 --reference 286`

Files-
[alignment file](https://github.com/Jigyasa3/errors/blob/master/d__Bacteria_p__Fibrobacterota__p__Bacteroidota__p__UBP14__COG0552_tips_2_.fasta)
[treefile](https://github.com/Jigyasa3/errors/blob/master/tree8.nwk)

Error-
`>code –> Universal

-------
>[WARNING] This dataset contains 7 duplicate sequences. Identical
sequences do not contribute any information to the analysis and only
slow down computation. Please consider removing duplicate or 'nearly'
duplicate sequences, e.g. using
https://github.com/veg/hyphy-analyses/tree/master/remove-duplicates
prior to running selection analyses
-------

>Loaded a multiple sequence alignment with **204** sequences, **454** codons, and **1** partitions from `/flash/BourguignonU/Jigs/markergene/paper2_extra/d__Bacteria_p__Fibrobacterota__p__Bacteroidota__p__UBP14__COG0552_tips_2_.fasta`
Error:
RELAX requires at least one designated set of branches in the tree. in call to assert(znxHAiZC.option_count>=2, error_msg);

Function call stack
1 :  assert(znxHAiZC.option_count>=2, error_msg);

        Keyword arguments:
                {
                 "reference":"286",
                 "test":"211"
                }
-------
2 :  ExecuteCommands("assert (`statement`, error_msg)", /flash/BourguignonU/Tool/hyphy/opt/hyphy/share/hyphy/TemplateBatchFiles/libv3/);
-------
3 :  [namespace = znxHAiZC] io.CheckAssertion("`&option_count` >= 2","RELAX requires at least one designated set of branches in the tree.");
-------
4 :  [namespace = relax] selected_branches=Call(settings[utility.getGlobalValue("terms.settings.branch_selector")],partitions_and_trees);
-------
5 :  [namespace = relax] load_file({utility.getGlobalValue("terms.prefix"):"relax",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"relax.select_branches"}});
-------
6 :  namespace
Step 0.LoadFunctionLibrary("modules/shared-load-file.bf", /flash/BourguignonU/Tool/hyphy/opt/hyphy/share/hyphy/TemplateBatchFiles/SelectionAnalyses/);

Step 1.load_file({utility.getGlobalValue("terms.prefix"):"relax",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"relax.select_branches"}});

Step 2.LoadFunctionLibrary("modules/grid_compute.ibf", /flash/BourguignonU/Tool/hyphy/opt/hyphy/share/hyphy/TemplateBatchFiles/SelectionAnalyses/);;
-------

`

**Comment by spond** [comment]
Dear @Jigyasa3,

Your Newick tree needs to be annotated using `{tag}`, like so

```
((A{TEST},B{TEST}){TEST},C,(D{REF},E{REF}){REF})
``` 

See http://hyphy.org/tutorials/phylotree/

You can also use https://github.com/veg/hyphy-analyses/tree/master/LabelTrees

Best,
Sergei

**Comment by Jigyasa3** [comment]
Hey @spond 

Thank you for replying! I was able to create an annotated tree with the tags using `LabelTrees` . I now have {R} and {T} tags after each tip label in the tree.

But I am still getting an error while running the command line version of RELAX.
code-
`/flash/BourguignonU/Tool/hyphy/opt/hyphy/bin/hyphy relax --alignment d__Bacteria_p__Fibrobacterota__p__Bacteroidota__p__UBP14__COG0552_tips_2_.fasta --tree tree8_cluster2.nwk`

files-
[alignment file](https://github.com/Jigyasa3/errors/blob/master/d__Bacteria_p__Fibrobacterota__p__Bacteroidota__p__UBP14__COG0552_tips_2_.fasta)
[tree](https://github.com/Jigyasa3/errors/blob/master/tree8_cluser2.nwk)

error-

`Error:RELAX requires at least one designated set of branches in the tree. in call to assert(xiOUnzFI.option_count>=2, error_msg);
RELAX requires at least one designated set of branches in the tree. in call to assert(xiOUnzFI.option_count>=2, error_msg);
`

**Comment by stephenshank** [comment]
Dear @Jigyasa3,

Which version of HyPhy are you using? My experience is not the same with your dataset. Instead, I am prompted to choose a branch set:

![image](https://user-images.githubusercontent.com/8673708/147939988-0757f696-d5cb-4388-99b1-ad5d0186a635.png)

I also do not see use of the `--reference-group` flag in your command line invocation, which is listed as required when you invoke `hyphy relax --help`.

I'd recommend trying to update to the latest version of HyPhy, and specifying this flag. Do let us know how it goes.

Best,
Stephen

**Comment by Jigyasa3** [comment]
Hey @stephenshank! Thanks for pointing out to use the `--reference-group` flag. It's working!

**Comment by Jigyasa3** [comment]
Hey @stephenshank 

I have a follow-up question to marking Test branches using `label-tree.bf`. This command has options to mark the tips, all branches, some branches, etc. as Test. But I want to examine similar options for the Reference branch(es). Currently, I am manually adding {R} to the tips that I want as Reference. 

But would the results change if the specific nodes are marked as Reference rather than tips? 

Luckily, all my reference tips are present as monophyletic groups, does that mean it doesn't matter if the tips are marked as Reference?

Looking forward to your reply!

**Comment by stephenshank** [comment]
Dear @Jigyasa3,

Any branch being toggled as either reference or test will have the potential to change the result, since it will change whether or not that branch influences the omega distribution that is fit for that particular branch set.

As far as I know, RELAX does not take monophyly into account in any sort of automatic fashion. Instead, if a user thinks this is relevant to an analysis, it is up to them to label an entire monophyletic group/clade in the appropriate branch set.

You can also use http://phylotree.hyphy.org/ to label the branches in your tree for such an analysis, which might be a useful alternative. It has tools for supporting multiple label sets, automatically selecting clades, internal branches, tips, etc.

I hope this answers your question, please let us know if you encounter any further issues.

Best,
Stephen

**Comment by IsaS89** [comment]
Hello,
I'm having a similar issue.
I'm trying to run RELAX on a data set of many different groups of orthologous genes. 
For each group, I have an alignment and a tree. Now the problem is to label all the trees. Using the online tool to manually label every tree is not feasible for the big number of trees, so I'm looking for a way to automate it.  I have tried using _label-tree.bf_, but I can't figure out how to label both the test and reference sets. I only manage to label one set.

**Comment by spond** [comment]
Dear @IsaS89,

I just updated `label-tree.bf` (at https://github.com/veg/hyphy-analyses/tree/master/LabelTrees) so that it will respect already existing labels, and allow you to **add** labels to already existing labels.

#### Input tree 

```
(((REF1,REF2),REF3), ((TEST1, TEST2), TEST3), IGNORED)
```

#### Label reference

```
$hyphy label-tree.bf --tree data/input.nwk --regexp REF --label REFERENCE --output labeled.nwk --internal-nodes Parsimony

$cat labeled.nwk

(((REF1{REFERENCE}:1e-10,REF2{REFERENCE}:1e-10)Node2{REFERENCE}:1e-10,REF3{REFERENCE}:1e-10)Node1{REFERENCE}:1e-10,((TEST1:1e-10,TEST2:1e-10)Node7:1e-10,TEST3:1e-10)Node6:1e-10,IGNORED:1e-10)Node11

```

#### Label test

```
$hyphy label-tree.bf --tree labeled.nwk --regexp TEST --label TEST --output labeled.nwk --internal-nodes Parsimony

$cat labeled.nwk

((((REF1{REFERENCE}:1e-10,REF2{REFERENCE}:1e-10)Node2{REFERENCE}:1e-10,REF3{REFERENCE}:1e-10)Node1{REFERENCE}:1e-10,((TEST1{TEST}:1e-10,TEST2{TEST}:1e-10)Node7{TEST}:1e-10,TEST3{TEST}:1e-10)Node6{TEST}:1e-10,IGNORED:1e-10)Node11% 

```

Best,
Sergei

**Comment by IsaS89** [comment]
Thank you! It's working very well!

**Comment by liamfriar** [comment]
Hi, I was receiving the same prompt to choose my test and reference groups as @stephenshank screenshotted above. I am trying to build an automated pipeline, so this would not work well. I found that adding the --reference-group flag fixed the problem, but I am now confused what the difference is between --reference-group and --reference ? My current call seems to work, but I want to make sure I am not doing something different than I intend?

```
hyphy relax --alignment mod.${alignment_file} --tree $out_tree --reference-group "Background" --test "Foreground" --reference "Background" --models Minimal
rm *tmp
```
