### ISSUE TITLE
directional selection estimation via FADE

### ISSUE THREAD

**Issue by s-s-Naqvi** [veg/hyphy#1447]
Hi,
I am working on foot and mouth disease virus serotype A. I estimated natural selection pressure on 1D gene by using the dN/dS ratio using datamonkey server, mainly MEME and FUBAR. I got following comments from reniewer:
''it is well known that the dN/dS ratio is not reliable for quantifying selection pressure at the population-genetics level. Interpretation of the dN/dS value as an indicator of the direction and strength of natural selection is only valid when almost all genetic variations in the sequences examined are fixed substitutions. See “The Population Genetics of dN/dS” by Sergey Kryazhimskiy and Joshua B. Plotki, for example. Other kinds of analyses are needed to quantify evolutionary pressure in this context''.
What I understood is strength of selection an be measured by RELAX and direction of natural selection could be inferred using FADE in HyPhy. The requirement for FADE is ''Uploaded file must contain both an amino acid multiple sequence alignment and a rooted tree''. The file choice is ''Multiple Sequence Alignment'' on GUI. How to generate file for this analysis? Should a single nexus file containing amino acid sequences and newick tree work? I am getting error doing this. I would really appreciate the help in this regard.

Thanks,
Naqvi

**Comment by spond** [comment]
Dear @s-s-Naqvi,

That's a silly comment. The cited paper assumes free recombination for example, etc. 

The reviewer is correct though in that in viral sequences you can have dN/dS biased upwards by variation at the tips; which may include within-individual polymorphisms that have not been "seen" by selection. A simple and generally reliable solution is to do an analysis on internal tree branches only. You can do this with MEME on Datamonkey, and cite the following papers in support of it

1. https://pubmed.ncbi.nlm.nih.gov/26814962/. Relevant passage 

> We restricted the test to internal branches, which capture at least one and likely multiple rounds of virus replication, to mitigate the biasing effects of neutral or deleterious mutations on the ratio of nonsynonymous-to-synonymous substitution rates (ω) estimates where selection has not yet fully filtered such population level variation25,26

2. https://journals.plos.org/ploscompbiol/article/comments?id=10.1371/journal.pcbi.0020062

> See the section "Individual versus Population-Level Adaption in HIV"

Best,
Sergei

**Comment by s-s-Naqvi** [comment]
Dear @spond 

Thank you very much for providing a solution.

Regards,

Naqvi

**Comment by s-s-Naqvi** [comment]
Dear @spond 

It might be a naïve question but I wanted to ask when should we go for testing direction and strength of natural selection with reference to viruses and what are the criteria? for example if we have a viral population with three serotype co-circulating in a region.

Thanks,
Naqvi

**Comment by s-s-Naqvi** [comment]
When I ran MEME on Datamonkey, I could not find the option to select branches like in aBSREL. Should I upload data file with internal branches only?
