### ISSUE TITLE
Ortholog Group comparison

### ISSUE THREAD

**Issue by francicco** [veg/hyphy#1449]
Hi,

Mine is a question regarding the best procedure to compute the overall Omega (Analyse codon data with a variery of standard models using given tree: `hyphy acd`). I'd like to test if ortholog groups within the same gene family (e.g.: Odorant receptors) have different rates of purifying selection (overall omega values) between two sets of species.
To do that I was thinking to separate genes from the same ortholog groups (OGs) in two groups, one for each species group, and to compute omega (`hyphy acd estimate`), therefore comparing the distribution of omega for all the OGs between the two species.
How should I treat out- and in-paralogs within each OG? Should I try to exclude them or keep them in the alignment?

I hope I express myself clear
Thanks 
F

**Comment by spond** [comment]
Dear @francicco,

I would suggest using a different analysis which directly deals with partitioned data and can compare distributions of selective forces.

1. There's `RELAX`  which was specifically designed for testing for relaxation of selection between groups of branches (https://academic.oup.com/mbe/article/32/3/820/981440)

2. There's `BUSTED-PH`, which compares for selective differences between groups of species (https://github.com/veg/hyphy-analyses/tree/master/BUSTED-PH)

If you run relax, you will also get an estimate of dN/dS (mean) for groups in your tree:

```
$hyphy relax --alignment tests/hbltests/libv3/data/CD2.nex --test GROUP1  --reference GROUP2 --srv No --starting-points 5

....

### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
* Log(L) = -3457.36, AIC-c =  6981.94 (33 estimated parameters)
* non-synonymous/synonymous rate ratio for *Reference* =   1.5188
* non-synonymous/synonymous rate ratio for *Test* =   0.6117
* non-synonymous/synonymous rate ratio for *Unclassified* =   0.6247

```


This is also written into the `JSON` file:

```
 "fits":{
   "MG94xREV with separate rates for branch sets":{
     "AIC-c":6981.943522763865,
     ...
     "Log Likelihood":-3457.360650270821,
     "Rate Distributions":{
       "non-synonymous/synonymous rate ratio for *Reference*":        [
[1.518779774163847, 1] 
        ],
       "non-synonymous/synonymous rate ratio for *Test*":        [
[0.611727374128719, 1] 
        ],
       "non-synonymous/synonymous rate ratio for *Unclassified*":        [
[0.6246757108093913, 1] 
        ]
      },
     "display order":1,
     "estimated parameters":33
    },
 ```

Best,
Sergei

**Comment by spond** [comment]
Dear @francicco,

Yes, that is correct. You can also see from the rate distribution report that the gene is mostly perfectly conserved (dN/dS = 0 for 95% of it), and there are ~5% of sites/branches with dN/dS > 1.

Best,
Sergei

```
|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |   29.462    |                                   |
|        Negative selection         |     0.000     |   65.494    |                                   |
|      Diversifying selection       |     3.005     |    5.044    |                                   |
```
