### ISSUE TITLE
Indel models into BGM

### ISSUE THREAD

**Issue by brmagalis** [veg/hyphy#1450]
Is there a way to specify an indel model in BGM? Or can it be easily incorporated?

**Comment by spond** [comment]
Dear @brmagalis,

No as implemented. Which indel model did you have in mind? The simplest option would be count indels as valid "substitutions" so that branches where indels co-occur could be identified as co-evolving?

Best,
Sergei

**Comment by brmagalis** [comment]
Precisely – just hoping to treat indels as substitutions 😊

 

From: Sergei Pond ***@***.***>
Reply-To: veg/hyphy ***@***.***>
Date: Tuesday, January 11, 2022 at 4:12 PM
To: veg/hyphy ***@***.***>
Cc: Brittany Rife Magalis ***@***.***>, Mention ***@***.***>
Subject: Re: [veg/hyphy] Indel models into BGM (Issue #1450)

 

Dear @brmagalis,

No as implemented. Which indel model did you have in mind? The simplest option would be count indels as valid "substitutions" so that branches where indels co-occur could be identified as co-evolving?

Best,
Sergei

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
