### ISSUE TITLE
Issues Generating the right nexus file for FADE analysis in Datamonkey

### ISSUE THREAD

**Issue by ArfBAD2021** [veg/hyphy#1452]
Hi all
I am trying to run the FADE Program on Datamonkey, however, a failling to righly format the Nexus file combining both the Protein alignment and the tree data. I always get the following standard error message:
/var/spool/torque/mom_priv/jobs/1921107.new-silverback.SC: line 43: [: Variational-Bayes: integer expression expected
/var/spool/torque/mom_priv/jobs/1921107.new-silverback.SC: line 54: [: missing `]'
Check errors.log for execution error details.

Could anyone guide me, maybe by providing a template or giving hints on have to do that?
I know, I need to root the tree, but all have tried has failed even using Phylotree (http://phylotree.hyphy.org) and IcyTree (https://icytree.org/).
I must be doing something wrong, but I can't figure it out.
Thank you

**Comment by spond** [comment]
Dear @ArfBAD2021,

Do you have a job ID/URL for where this is happening?

Best,
Sergei

**Comment by ArfBAD2021** [comment]
Dear Sergei
Please, see the links below:

http://datamonkey.org/fade/61eec9275e56f71949c05015

http://datamonkey.org/fade/61eec4295e56f71949c04edd

http://datamonkey.org/fade/61eec30b5e56f71949c04e96
Thank you and Best regards
*Arfang BADJI*
*Post-doctoral fellow, **NaCRRI (National Crop Resources Research
Institute, Namulonge, Uganda) - **Makerere University, Kampala, Uganda.*

*Ph.D. Plant Breeding and Biotechnology/MSc: Plant and Microbial
Biotechnologies *
*Mobile: +256756736561*
* Skype: arf.bad*
https://orcid.org/0000-0003-1105-9668
*Expertise and interests: Plant Breeding, Agri-genomics, Phylogenetics,
Bioinformatics, Biotechnologies...*
