### ISSUE TITLE
aBSREL - How can I get the optimized branch lengths (B) from the json file

### ISSUE THREAD

**Issue by ariadnamorales** [veg/hyphy#1455]
Hello,

I have a simple question –How can I calculate B, the optimized branch lengths (under the full aBSREL model) in the tree? I can see such values in Hyphy Vision when I load a json file, but I can't find an equivalent value in the actual json file.

Thanks,

Ariadna

**Comment by spond** [comment]
Dear @ariadnamorales,

They are stored as branch attributes...

```
"branch attributes":{
   "0":{
     "Node1024":{
       "Baseline MG94xREV":0.0002612639914042762,
       "Baseline MG94xREV omega ratio":10000000000,
       "Corrected P-value":1,
       "Full adaptive model":0.0002605696824830064,
       "Full adaptive model (non-synonymous subs/site)":0.0002605696824830064,
       "Full adaptive model (synonymous subs/site)":1e-10,
       "LRT":0.8538202862109756,
       "Nucleotide GTR":0.0002625511008246897,
       "Rate Distributions":        [
[10000000000, 1] 
        ],
       "Rate classes":1,
       "Uncorrected P-value":0.2668514227802041
      },
....
"hCoV_19_Wales_PHWC_488075_2020_EPI_ISL_639344_2020_10_30":{
       "Baseline MG94xREV":0.0002716273083282961,
       "Baseline MG94xREV omega ratio":0,
       "Corrected P-value":null,
       "Full adaptive model":0.0002729984315699544,
       "Full adaptive model (non-synonymous subs/site)":1e-10,
       "Full adaptive model (synonymous subs/site)":0.0002729984315699544,
       "LRT":null,
       "Nucleotide GTR":0.0002617820907612385,
       "Rate Distributions":        [
[0, 1] 
        ],
       "Rate classes":1,
       "Uncorrected P-value":null,
       "original name":"hCoV-19/Wales/PHWC-488075/2020|EPI_ISL_639344|2020-10-30"
      },
...
```

As you see, there are several different branch lengths recorded there. You probably want `"Full adaptive model"` (exp subs/site).

Best,
Sergei

**Comment by ariadnamorales** [comment]
Thanks for the quick response. 
But I can't find the exact "B" value reported in the Hyphy Vision table. For example, I see this in the json file:
![image](https://user-images.githubusercontent.com/14182972/153512122-c4f9e9f9-53ee-488c-a6e9-b923c7f2f59c.png)

And this in Hyphy Vision:
![image](https://user-images.githubusercontent.com/14182972/153512185-e5b29909-7969-4980-827a-3bf8c32706e8.png)

Where does the 3.8006 come from? I can see that the LRT, p-value, omega, etc values match, but I am not sure about B.
