### ISSUE TITLE
MEME not working (on datamonkey.org)?

### ISSUE THREAD

**Issue by lccomsa** [veg/hyphy#1457]
Hi! So, it's my first time using datamonkey 2.0. I submitted a series of jobs to MEME via the website on Friday and they appeared to be in the queue, but today when I checked to see if they'd run, they have disappeared from the queue and I didn't receive any emails at all about them either. The job pages for each job also don't say much to indicate that the jobs ran without issue (see image, all the pages look identical), and if I download the log, it is just an empty txt. I was using .nex files for the gene alignments if that helps, and they were vertebrate mitochondrial sequences.
![Screenshot 2022-02-14 150239](https://user-images.githubusercontent.com/74752706/153937753-ae47dc86-742f-42f1-b2eb-ae35629e3f27.jpg)

**Comment by spond** [comment]
Dear @lccomsa,

This is abnormal. Not sure what is going on here. If you look at the queue page (http://www.datamonkey.org/jobqueue), there are some long-running jobs using up cluster resources, but there are also only a few MEME jobs (none from Friday).

Can you include the URL for the page that the screenshot in your post came from?

Best,
Sergei

**Comment by lccomsa** [comment]
Hi @spond,

Here is the URL to the screenshot page; also small mix-up on my part - I submitted the jobs on Thursday not Friday. https://datamonkey.org/meme/620568ed1f6b8629f28f8cd7

In case this is helpful in identifying the issue: I did a test run of MEME using the HIV-1 POL data supplied on the http://www.datamonkey.org/help page, and this ran successfully, though while the job was in the queue I was getting the same progress page as above. (Here is the URL to the completed test run: http://www.datamonkey.org/meme/620ac0534040572c69c40e6e)

Thanks,
Caden

**Comment by spond** [comment]
Dear @lccomsa,

Looks like your original submissions never even made it to the cluster queue. Would you mind trying to resubmit one or two now and see if they go through?

Best,
Sergei

**Comment by lccomsa** [comment]
Hi @spond,

I think I may have found the source of the submissions flopping before even hitting the queue: the .nex files were missing the phylogeny data. I just re-exported one of the alignments and made sure the tree was in there, and the job ran and completed immediately without issue.

Cheers,
Caden

**Comment by spond** [comment]
Dear @lccomsa,

Thanks for letting me know. Could you possibly provide an example for one of the files that broke the submission process? The way it was handled is buggy (no error messages), and I'd like to have an example to see what went wrong.

Best,
Sergei

**Comment by lccomsa** [comment]
Sure thing @spond ! I'll send you an email shortly with one of the failed files as well as the one that just ran successfully.
