### ISSUE TITLE
Fubar Output - help!

### ISSUE THREAD

**Issue by bob100077** [veg/hyphy#1458]
Hi,
I apologize if this isn't the right place to be asking for help, but i'm a little bit at a loss.
The Fubar output from Datamonkey is a nice table (Fubar Site Table), with details about alpha and beta _per site_. I'm having a difficult time finding the same data in the command line implementation through Hyphy. From what I can gather it may be in the .json file as a grid object? Is it possible to extract the same information as the Fubar Site Table? The STDOUT seems to only list the sites predicted to have undergone/undergoing positive selection (for my analysis).

In the end, I am looking for a table or data frame with 1. codon position, 2. alpha, and 3. beta. I don't want the mean or the sum, just the individual values for each site. 

It's entirely possible that my issue is me being able to read the resulting .json file.

Again, sorry if this is a naive question or the improper place to post it!
Thanks for you time,
Chris

My code was (everything was the default):

`hyphy fubar alignmentfile.meg alignmentfile.nwk`

![Screenshot from 2022-02-18 15-06-06](https://user-images.githubusercontent.com/10425952/154754005-70318581-a536-4930-a40d-7d713dd0b988.png)
![Screenshot from 2022-02-18 15-06-42](https://user-images.githubusercontent.com/10425952/154754081-3c05f516-6b84-42f7-a22c-8ea4ee62093e.png)

**Comment by stevenweaver** [comment]
Dear Bob, 

Do experience the same user-friendly interface using hyphy output, you can use http://vision.hyphy.org and load your JSON file. 

Additionally, @sjspielman wrote documentation that details the results schema for FUBAR in addition to other methods, a resource that has proven valuable time and again, even to those within the lab. 

The documentation can be found here -- https://hyphy.org/resources/json-fields.pdf. 

Please let me know if there any other questions and I'd be happy to be of service.

Best,
Steven

**Comment by bob100077** [comment]
Thank you very much for the quick reply! 
I'd love to use the user-friendly interface, but I'm hoping for a way to extract the Fubar site table information individually from >200 fubar runs. I understand the information is contained in the json file (as mentioned in your link), but I can't seem to figure out where it is or how to quickly turn it into a dataframe/table for downstream use. 

TDLR; I'm hoping there is a way to get the Fubar site table for many different Fubar runs/alignments (sort of in a batch style)

Thanks again for making these awesome programs accessible to benchtop scientists like me!

Chris

**Comment by bob100077** [comment]
I've only taken Introduction to Python and I'm not quite at the point of writing scripts like that. 
It works brilliantly. Thank you very much!
