### ISSUE TITLE
missing file ?

### ISSUE THREAD

**Issue by EricDeveaud** [veg/hyphy#1462]
Hello.

while playing with the installation of hyphy-2.5.26 (compiled from release archive: https://github.com/veg/hyphy/archive/refs/tags/2.5.36.tar.gz)

I ran some command line tests and got the following error:

```
rpm_maker:tests/data > hyphy psm --alignment adh.nex --code Universal --output adh.nex.MEME.json 
Error:
Could not read batch file '/opt/gensoft/exe/hyphy/2.5.36/share/hyphy/TemplateBatchFiles/MFPositiveSelection.bf'.
Path stack:
        /opt/gensoft/exe/hyphy/2.5.36/share/hyphy/
        /opt/gensoft/exe/hyphy/2.5.36/share/hyphy/TemplateBatchFiles/

```

NB `MFPositiveSelection.bf` is not provided by the release archive 

regards

Eric

**Comment by spond** [comment]
Dear @EricDeveaud,

You are correct -- the `psm` option is no longer active. I've removed it in the development version and will push the change with the next release.

Best,
Sergei
