### ISSUE TITLE
Job ends abruptly: GARD Ticket Number 1936978.new-silverback

### ISSUE THREAD

**Issue by venuraherath** [veg/hyphy#1463]
Hi Dr. Pond and the Team,

When I try to run GARD analysis (135 sequences & Alignment Length 9345; Faster mode, site to site variation GDM and rate class 3), the job gets terminated abruptly. I was using codon-based alignment. I attached the file just in case you want to recreate the issue.
Your help is greatly appreciated in this regard.
[Nucleotide_Seq_SCMV_135_PAL2NALforGARD.zip](https://github.com/veg/hyphy/files/8233568/Nucleotide_Seq_SCMV_135_PAL2NALforGARD.zip)
Thank you,
Venura

**Comment by venuraherath** [comment]
Thank you Dr. @spond .
I will update you if the job gets terminated again.

> Dear @venuraherath,
> 
> Please use the `Nucleotide (DNA/RNA)` option (the `Codon` option is going to result in much slower run times and may fail). I was able to submit your file to Datamonkey and the analysis is currently running: http://www.datamonkey.org/gard/622b7fdfb75f6753554fcb16
> 
> <img alt="image" width="1236" src="https://user-images.githubusercontent.com/1018513/157912993-def355f9-d1f0-4d25-a0ae-6450eef37351.png">
> 
> Best, Sergei

**Comment by spond** [comment]
Job completed successfully.
