### ISSUE TITLE
SLAC：The results of the Markdown file "......sites are significant at p <= 0.1" are not consistent with the results of the Json file

### ISSUE THREAD

**Issue by NickShanyt** [veg/hyphy#1464]
Hi
I have run Hyphy's SLAC model on my server. In the Markdown file of the run results: "**Performing joint maximum likelihood ancestor state reconstruction**————_For partition 1, these sites are significant at p <= 0.1_" section, I found "**Neg. p = 1.000, Pos. p = 1.000**" in the "**Selection detected?**" column of the table.  However, the corresponding sites are not shown in the Json file results.

I would like to ask, is the p in "**Neg. p = 1.000**" a  p-value threshold?
Why are such sites not shown in the Json file results?

Which file's result should be the final one?

![image](https://user-images.githubusercontent.com/42581222/158561330-08b6a823-476e-4abd-a844-ea2d291993dc.png)

**I uploaded my json file to http://vision.hyphy.org/SLAC and added the same filter, but the result does not show "24" and "27" sites.**
![image](https://user-images.githubusercontent.com/42581222/158562526-372a349d-2f43-4edb-b411-d2b4f0339d2c.png)

**Comment by NickShanyt** [comment]
Many thanks for your prompt reply ！ 

In fact, some **"p ! = 1"** that do not meet the filtering criteria are also shown.
![image](https://user-images.githubusercontent.com/42581222/158719435-acef0020-7a62-48a7-9cc5-762e97109fc1.png)

---
According to your reply, the final result I want should be filtered in the json file. Or I can filter them manually in the Markdown file according to my needs (for example, if I want p<0.1), right?
---
I would be happy to provide you with the input file.
The raw sequence file and the phylogenetic tree file provided this time correspond to the images in this reply. Also, the phylogenetic tree is constructed from the complete sequence of the lineage, while the sequence file is one of the proteins.
---
**[The input files are available here](https://github.com/NickShanyt/Temp):**

**Comment by NickShanyt** [comment]
Many thanks for your prompt reply ！ 

In fact, some **"p ! = 1"** that do not meet the filtering criteria are also shown.
![image](https://user-images.githubusercontent.com/42581222/158719435-acef0020-7a62-48a7-9cc5-762e97109fc1.png)

---
According to your reply, the final result I want should be filtered in the json file. Or I can filter them manually in the Markdown file according to my needs (for example, if I want p<0.1), right?
---
I would be happy to provide you with the input file.
The raw sequence file and the phylogenetic tree file provided this time correspond to the images in this reply. Also, the phylogenetic tree is constructed from the complete sequence of the lineage, while the sequence file is one of the proteins.
---
**[The input files are available here](https://github.com/NickShanyt/Temp):**

> Dear @NickShanyt,
> 
> Thanks for sharing. Clearly, the MarkDown output is incorrect. `p=1.00` means the sites are about as far from significance as they get (e.g. site 24 has no variation at all). Would you mind sharing the input file which generated the output?
> 
> For result interpretation, if you rely on reported p-values and filter based on, say `p<0.1`, you should get the same result.
> 
> Best, Sergei

Many thanks for your prompt reply !

In fact, some **"p ! = 1"** that do not meet the filtering criteria are also shown.
![image](https://user-images.githubusercontent.com/42581222/158719435-acef0020-7a62-48a7-9cc5-762e97109fc1.png)




According to your reply, the final result I want should be filtered in the json file. Or I can filter them manually in the Markdown file according to my needs (for example, if I want p<0.1), right?


I would be happy to provide you with the input file.
The raw sequence file and the phylogenetic tree file provided this time correspond to the images in this reply. Also, the phylogenetic tree is constructed from the complete sequence of the lineage, while the sequence file is one of the proteins.



---
### **[The input files are available here](https://github.com/NickShanyt/Temp)**

> Dear @NickShanyt,
> 
> Thanks for sharing. Clearly, the MarkDown output is incorrect. `p=1.00` means the sites are about as far from significance as they get (e.g. site 24 has no variation at all). Would you mind sharing the input file which generated the output?
> 
> For result interpretation, if you rely on reported p-values and filter based on, say `p<0.1`, you should get the same result.
> 
> Best, Sergei

Many thanks for your prompt reply !

In fact, some **"p ! = 1"** that do not meet the filtering criteria are also shown.
![image](https://user-images.githubusercontent.com/42581222/158719435-acef0020-7a62-48a7-9cc5-762e97109fc1.png)




According to your reply, the final result I want should be filtered in the json file. Or I can filter them manually in the Markdown file according to my needs (for example, if I want p<0.1), right?


I would be happy to provide you with the input file.
The raw sequence file and the phylogenetic tree file provided this time correspond to the images in this reply. Also, the phylogenetic tree is constructed from the complete sequence of the lineage, while the sequence file is one of the proteins.



---
### **[The input files are available here](https://github.com/NickShanyt/Temp)**

**Comment by spond** [comment]
Dear @NickShanyt,

I ran your example with the latest version (2.5.36), and did not observe the same buggy behavior: all sites reported to MD (stdout) are indeed those with p ≤ 0.1. Which version of HyPhy are you running (`hyphy --version`)?

```
|     Codon      |   Partition    |       S        |       N        |       dS       |       dN       |Selection detected?|
|:--------------:|:--------------:|:--------------:|:--------------:|:--------------:|:--------------:|:-----------------:|
|       8        |       1        |     3.000      |     1.000      |     3.987      |     0.445      |  Neg. p = 0.051   |
|       35       |       1        |     9.000      |     3.000      |     9.000      |     1.500      |  Neg. p = 0.004   |
|       53       |       1        |     3.000      |     0.000      |     3.461      |     0.000      |  Neg. p = 0.024   |
|       54       |       1        |     11.000     |     0.000      |     11.000     |     0.000      |  Neg. p = 0.000   |
|       55       |       1        |     0.000      |     6.000      |     0.000      |     3.000      |  Pos. p = 0.088   |
|       63       |       1        |     3.000      |     1.000      |     3.461      |     0.469      |  Neg. p = 0.076   |
|       68       |       1        |     0.000      |     5.000      |     0.000      |     4.708      |  Pos. p = 0.031   |
|       71       |       1        |     2.000      |     0.000      |     2.000      |     0.000      |  Neg. p = 0.111   |
|       75       |       1        |     2.000      |     0.000      |     2.307      |     0.000      |  Neg. p = 0.084   |
|       82       |       1        |     2.000      |     0.000      |     2.307      |     0.000      |  Neg. p = 0.083   |
|       86       |       1        |     2.000      |     0.000      |     2.307      |     0.000      |  Neg. p = 0.091   |
|       90       |       1        |     0.000      |     6.000      |     0.000      |     3.000      |  Pos. p = 0.088   |
|      110       |       1        |     8.000      |     0.000      |     9.232      |     0.000      |  Neg. p = 0.000   |
|      111       |       1        |     3.000      |     0.000      |     3.461      |     0.000      |  Neg. p = 0.028   |
|      115       |       1        |     5.000      |     0.000      |     5.000      |     0.000      |  Neg. p = 0.004   |
|      126       |       1        |     3.000      |     0.000      |     3.461      |     0.000      |  Neg. p = 0.024   |
|      128       |       1        |     7.000      |     6.000      |     8.081      |     2.813      |  Neg. p = 0.052   |
|      142       |       1        |     0.000      |     8.000      |     0.000      |     4.004      |  Pos. p = 0.039   |
|      145       |       1        |     6.000      |     5.000      |     6.925      |     2.344      |  Neg. p = 0.066   |
|      151       |       1        |     0.000      |     8.000      |     0.000      |     4.000      |  Pos. p = 0.039   |
|      153       |       1        |     2.000      |     0.000      |     2.307      |     0.000      |  Neg. p = 0.083   |
|      157       |       1        |     4.000      |     1.000      |     4.261      |     0.485      |  Neg. p = 0.036   |
|      192       |       1        |     3.000      |     0.000      |     3.461      |     0.000      |  Neg. p = 0.024   |
|      204       |       1        |     0.000      |     5.000      |     0.000      |     4.684      |  Pos. p = 0.031   |
|      221       |       1        |     3.000      |     0.000      |     2.432      |     0.000      |  Neg. p = 0.074   |
|      228       |       1        |     8.000      |     0.000      |     9.234      |     0.000      |  Neg. p = 0.000   |
|      229       |       1        |     4.000      |     0.000      |     8.366      |     0.000      |  Neg. p = 0.003   |
|      238       |       1        |     0.000      |     7.000      |     0.000      |     3.499      |  Pos. p = 0.059   |
|      268       |       1        |     7.000      |     0.000      |     8.077      |     0.000      |  Neg. p = 0.000   |
|      274       |       1        |     16.000     |     0.000      |     18.479     |     0.000      |  Neg. p = 0.000   |
|      287       |       1        |     4.000      |     0.000      |     4.000      |     0.000      |  Neg. p = 0.012   |
|      292       |       1        |     4.000      |     0.000      |     4.262      |     0.000      |  Neg. p = 0.010   |
|      296       |       1        |     0.000      |     8.000      |     0.000      |     3.998      |  Pos. p = 0.039   |
|      298       |       1        |     6.000      |     0.000      |     6.924      |     0.000      |  Neg. p = 0.001   |
|      309       |       1        |     6.000      |     0.000      |     6.000      |     0.000      |  Neg. p = 0.001   |
|      310       |       1        |     2.000      |     0.000      |     2.307      |     0.000      |  Neg. p = 0.084   |
|      313       |       1        |     3.000      |     0.000      |     3.000      |     0.000      |  Neg. p = 0.037   |
|      315       |       1        |     5.000      |     0.000      |     5.769      |     0.000      |  Neg. p = 0.002   |
|      325       |       1        |     0.000      |     6.000      |     0.000      |     2.998      |  Pos. p = 0.088   |
|      329       |       1        |     4.000      |     0.000      |     4.000      |     0.000      |  Neg. p = 0.012   |
|      333       |       1        |     5.000      |     0.000      |     5.769      |     0.000      |  Neg. p = 0.003   |
|      337       |       1        |     4.000      |     1.000      |     4.264      |     0.485      |  Neg. p = 0.036   |
|      341       |       1        |     4.000      |     1.000      |     4.615      |     0.469      |  Neg. p = 0.027   |
|      346       |       1        |     7.000      |     0.000      |     8.079      |     0.000      |  Neg. p = 0.000   |
|      360       |       1        |     8.000      |     0.000      |     9.232      |     0.000      |  Neg. p = 0.000   |
|      362       |       1        |     0.000      |     11.000     |     0.000      |     5.484      |  Pos. p = 0.012   |
|      371       |       1        |     2.000      |     0.000      |     2.307      |     0.000      |  Neg. p = 0.084   |
|      379       |       1        |     0.000      |     8.000      |     0.000      |     3.998      |  Pos. p = 0.039   |
|      401       |       1        |     3.000      |     0.000      |     3.986      |     0.000      |  Neg. p = 0.016   |
|      413       |       1        |     0.000      |     9.000      |     0.000      |     4.495      |  Pos. p = 0.026   |
```

Best,
Sergei

**Comment by NickShanyt** [comment]
OMG......……
My version is ：HYPHY 2.5.8(MP) for Linux on x86_64
Maybe that's the problem!
And I checked the version history and I found that I may have wasted a lot of time because Hyphy has done very many optimizations.
Thank you very much for the effort you and your team put in!
Thank you very much for your friendly and prompt reply!

Wish you all the best!

**Comment by NickShanyt** [comment]
> Dear @NickShanyt,
> 
> I ran your example with the latest version (2.5.36), and did not observe the same buggy behavior: all sites reported to MD (stdout) are indeed those with p ≤ 0.1. Which version of HyPhy are you running (`hyphy --version`)?
> 
> ```
> |     Codon      |   Partition    |       S        |       N        |       dS       |       dN       |Selection detected?|
> |:--------------:|:--------------:|:--------------:|:--------------:|:--------------:|:--------------:|:-----------------:|
> |       8        |       1        |     3.000      |     1.000      |     3.987      |     0.445      |  Neg. p = 0.051   |
> |       35       |       1        |     9.000      |     3.000      |     9.000      |     1.500      |  Neg. p = 0.004   |
> |       53       |       1        |     3.000      |     0.000      |     3.461      |     0.000      |  Neg. p = 0.024   |
> |       54       |       1        |     11.000     |     0.000      |     11.000     |     0.000      |  Neg. p = 0.000   |
> |       55       |       1        |     0.000      |     6.000      |     0.000      |     3.000      |  Pos. p = 0.088   |
> |       63       |       1        |     3.000      |     1.000      |     3.461      |     0.469      |  Neg. p = 0.076   |
> |       68       |       1        |     0.000      |     5.000      |     0.000      |     4.708      |  Pos. p = 0.031   |
> |       71       |       1        |     2.000      |     0.000      |     2.000      |     0.000      |  Neg. p = 0.111   |
> |       75       |       1        |     2.000      |     0.000      |     2.307      |     0.000      |  Neg. p = 0.084   |
> |       82       |       1        |     2.000      |     0.000      |     2.307      |     0.000      |  Neg. p = 0.083   |
> |       86       |       1        |     2.000      |     0.000      |     2.307      |     0.000      |  Neg. p = 0.091   |
> |       90       |       1        |     0.000      |     6.000      |     0.000      |     3.000      |  Pos. p = 0.088   |
> |      110       |       1        |     8.000      |     0.000      |     9.232      |     0.000      |  Neg. p = 0.000   |
> |      111       |       1        |     3.000      |     0.000      |     3.461      |     0.000      |  Neg. p = 0.028   |
> |      115       |       1        |     5.000      |     0.000      |     5.000      |     0.000      |  Neg. p = 0.004   |
> |      126       |       1        |     3.000      |     0.000      |     3.461      |     0.000      |  Neg. p = 0.024   |
> |      128       |       1        |     7.000      |     6.000      |     8.081      |     2.813      |  Neg. p = 0.052   |
> |      142       |       1        |     0.000      |     8.000      |     0.000      |     4.004      |  Pos. p = 0.039   |
> |      145       |       1        |     6.000      |     5.000      |     6.925      |     2.344      |  Neg. p = 0.066   |
> |      151       |       1        |     0.000      |     8.000      |     0.000      |     4.000      |  Pos. p = 0.039   |
> |      153       |       1        |     2.000      |     0.000      |     2.307      |     0.000      |  Neg. p = 0.083   |
> |      157       |       1        |     4.000      |     1.000      |     4.261      |     0.485      |  Neg. p = 0.036   |
> |      192       |       1        |     3.000      |     0.000      |     3.461      |     0.000      |  Neg. p = 0.024   |
> |      204       |       1        |     0.000      |     5.000      |     0.000      |     4.684      |  Pos. p = 0.031   |
> |      221       |       1        |     3.000      |     0.000      |     2.432      |     0.000      |  Neg. p = 0.074   |
> |      228       |       1        |     8.000      |     0.000      |     9.234      |     0.000      |  Neg. p = 0.000   |
> |      229       |       1        |     4.000      |     0.000      |     8.366      |     0.000      |  Neg. p = 0.003   |
> |      238       |       1        |     0.000      |     7.000      |     0.000      |     3.499      |  Pos. p = 0.059   |
> |      268       |       1        |     7.000      |     0.000      |     8.077      |     0.000      |  Neg. p = 0.000   |
> |      274       |       1        |     16.000     |     0.000      |     18.479     |     0.000      |  Neg. p = 0.000   |
> |      287       |       1        |     4.000      |     0.000      |     4.000      |     0.000      |  Neg. p = 0.012   |
> |      292       |       1        |     4.000      |     0.000      |     4.262      |     0.000      |  Neg. p = 0.010   |
> |      296       |       1        |     0.000      |     8.000      |     0.000      |     3.998      |  Pos. p = 0.039   |
> |      298       |       1        |     6.000      |     0.000      |     6.924      |     0.000      |  Neg. p = 0.001   |
> |      309       |       1        |     6.000      |     0.000      |     6.000      |     0.000      |  Neg. p = 0.001   |
> |      310       |       1        |     2.000      |     0.000      |     2.307      |     0.000      |  Neg. p = 0.084   |
> |      313       |       1        |     3.000      |     0.000      |     3.000      |     0.000      |  Neg. p = 0.037   |
> |      315       |       1        |     5.000      |     0.000      |     5.769      |     0.000      |  Neg. p = 0.002   |
> |      325       |       1        |     0.000      |     6.000      |     0.000      |     2.998      |  Pos. p = 0.088   |
> |      329       |       1        |     4.000      |     0.000      |     4.000      |     0.000      |  Neg. p = 0.012   |
> |      333       |       1        |     5.000      |     0.000      |     5.769      |     0.000      |  Neg. p = 0.003   |
> |      337       |       1        |     4.000      |     1.000      |     4.264      |     0.485      |  Neg. p = 0.036   |
> |      341       |       1        |     4.000      |     1.000      |     4.615      |     0.469      |  Neg. p = 0.027   |
> |      346       |       1        |     7.000      |     0.000      |     8.079      |     0.000      |  Neg. p = 0.000   |
> |      360       |       1        |     8.000      |     0.000      |     9.232      |     0.000      |  Neg. p = 0.000   |
> |      362       |       1        |     0.000      |     11.000     |     0.000      |     5.484      |  Pos. p = 0.012   |
> |      371       |       1        |     2.000      |     0.000      |     2.307      |     0.000      |  Neg. p = 0.084   |
> |      379       |       1        |     0.000      |     8.000      |     0.000      |     3.998      |  Pos. p = 0.039   |
> |      401       |       1        |     3.000      |     0.000      |     3.986      |     0.000      |  Neg. p = 0.016   |
> |      413       |       1        |     0.000      |     9.000      |     0.000      |     4.495      |  Pos. p = 0.026   |
> ```
> 
> Best, Sergei

OMG......……
My version is ：HYPHY 2.5.8(MP) for Linux on x86_64
Maybe that's the problem!
And I checked the version history and I found that I may have wasted a lot of time because Hyphy has done very many optimizations.
Thank you very much for the effort you and your team put in!
Thank you very much for your friendly and prompt reply!

Wish you all the best!
