### ISSUE TITLE
FEL results not displaying 

### ISSUE THREAD

**Issue by cherylichihara** [veg/hyphy#1465]
https://www.datamonkey.org/fel/62356ebfb75f675355518dd8

Dear all,
What can I do to retrieve my results?

Thank you!

**Comment by stevenweaver** [comment]
Dear @cherylichihara, 

By retrieving results, I'm assuming you mean the raw JSON results file?

You can click on `Export` in the upper right-hand side, then click `Save JSON`.

Best,
Steve
<img width="243" alt="Screen Shot 2022-03-19 at 10 04 27 AM" src="https://user-images.githubusercontent.com/535261/159128722-471213e8-1d31-47ec-a2a6-8cbb884b491b.png">
n
