### ISSUE TITLE
Simple beginner question

### ISSUE THREAD

**Issue by schultzt23** [veg/hyphy#1467]
I've never used DataMonkey before.  I need to use aBSREL.  Am I correct that I upload only one file, a FASTA file, and no tree file?  Can you direct me to a manual or other source that describes in more detail the protocols and methods?  Thanks.

**Comment by schultzt23** [comment]
Thank you very much!

**Comment by schultzt23** [comment]
I watched the video about BUSTED and it was helpful.  It would help for me to understand how long an aBSREL job would take given the number of sites and taxa.  My data set is huge: 475 taxa and 202,215 sites, but I am planning to split it up.  If I ran all 475 taxa with your max of 32,000 sites, I suspect that would take a long time to run . . . right?  What if I split the taxa into two subtrees, one of about 50 taxa and the other of about 200 taxa, but still with ~30,000 sites.  Any idea how long the run would take?  Thanks.

**Comment by stephenshank** [comment]
Dear @schultzt23,

You can get a sense of what is likely to run by taking a look at our [usage statistics](https://datamonkey.org/stats). You might want to split such a dataset with so many sites into individual genes (or perhaps even exons) if you plan to run on Datamonkey.

Best,
Stephen

**Comment by stevenweaver** [comment]
Dear @schultzt23, 

Here is a log-log plot of aBSREL runs, x axis being sequences, and y axis being runtime in minutes. While it doesn't have number of sites, you can use this plot in addition to the usage statistics page to get some degree of expectation.

![untitled](https://user-images.githubusercontent.com/535261/162082218-aced0507-af70-4a49-bfcb-cebbad61a68b.png)

Best,
Steven

**Comment by spond** [comment]
Dear @schultzt23,

Here's some general intuition about aBSREL.

1). The signal for positive selection at a branch is a function of selection strength (fraction of sites under selection and &omega;) and alignment length. The first is what you would call "effect size" and the other is "sample size".

2). aBSREL performs tests over all branches (by default -- you can specify a subset a priori as well). Because of this, it also applies a multiple test correction, which means that for any particular branch `X` with the same effect size and the same alignment length it will be **harder** to find it in a larger tree.

3). Since you have >200K sites, I assume the alignment is a concatenation of multiple genes. Not knowing anything about the system you are studying, I can nevertheless guess that there's going to be some gene-to-gene variation in selective patterns. This could create statistical issues for the model (not necessarily too troublesome), which was originally developed to study single genes. 

4). My guess is that 475 taxa and 200,000 sites would run in about a day on a modern compute node (say something like 32 processors). You are welcome to send me your alignment by e-mail and I'll run the entire thing for you (I am also curious what it would take).

5). My *recommendation* would be two-fold. First, unless you have a good reason to test every branch in the tree, I would select the most interesting branches (this of course depends on your system), and run a smaller tree. 50-100 taxa is a sweet spot generally. Second, I would start by analyzing individual genes instead of a concatenated alignment. 

Best,
Sergei

**Comment by schultzt23** [comment]
Thank you!

_________________________
Ted R. Schultz
Research Entomologist
Department of Entomology
National Museum of Natural History
Smithsonian Institution
NHB CE516 MRC188
1000 Constitution Ave NW
Washington DC 20560-0003
________________________________

**Comment by schultzt23** [comment]
Thank you, Stephen, Steven, and Sergei, for you informative responses.  Based on these, it seems to me that aBSREL handles large data sets pretty quickly.  Sergei, thanks for your kind offer of running my data for me, but perhaps before I send the data to you I should explain things in a bit more detail.  My data consist of 475 taxa and 202,215 sites representing the coding regions in about 400 Ultra-Conserved Element loci.  Because your upper limit is 32,000 sites, I had assumed I would need to divide my data into seven subsets of 475 taxa and ~30,000 sites.  Is that not the case?  I do not want to test every branch for positive selection, so I am not worried about the test correction.  My a priori hypothesis is that there was positive selection on seven internal branches, each of which subtends a clade of ant-associated fungi.  My null hypothesis is NOT that there has been positive selection on one or more of those branches, however.  Instead, it is that there has been positive selection on EACH of them.  Does that mean I would need to run aBSREL seven times (assuming it could handle the 202,215 sites, of course), one for each branch?  That would be fine if the runs complete in reasonable periods of time.  It would also be fine if I had to do 7 x 7 runs because I would need to divide the data into 7 manageable chunks of ~30,000 sites each.  Ultimately I'd like to know in which UCE loci the sites with positive selection arise, if that's possible.  In order to avoid long run times, one of the things I've been planning to do is to create pruned subtrees of my data, because the 475-taxon data contain a lot of very long-branched, distantly related taxa that are not relevant to the selection hypotheses.  This might allow me to run in CodeML, especially if I did so gene-by-gene.  But if it were possible to just run all the data, or seven subsets of the data, in aBSREL, that would be great, even if I had to create pruned subtrees to do so.  (One advantage of parsing the data into two subtress would be that a lot of previously excluded loci could be reintroduced into the data set.)  Let me know, Sergei, if you are still interested in running the data.  Thanks!!!

**Comment by spond** [comment]
Dear @schultzt23,

Apologies for the delay in responding (vacation).

1. Datamonkey **does** limit the number of sites / job, but HyPhy does not. There's some potential for odd behavior of some analyses (errors) if there are more than 100,000 codons in an alignment, but this can be handled with an appropriate command line flag. So it should be possible to analyze the entire dataset in one go. 

2. Based on what you describe, it seems like the stock application of aBSREL, with seven designated branches as the test set (so the tests are done **only** on those branches) will do the trick. The end result will be a test of each of the seven branches for evidence of selection separately. This is done using one run of aBSREL (seven separate tests). 

3. There is no need to subset or prune anything. My guess is that this job will run in a few hours on my M1 laptop; send me the alignment if you are keen (spond at temple dot edu). I will share the results and the command line used to run it. Is your tree labeled?

Best,
Sergei

**Comment by schultzt23** [comment]
Sergei:

Thanks for your reply!  My tree is not currently labeled, but I can label the seven branches.  Is there a standard way to do that?  Is it described on the site?  Does the tree need to be a phylogram or does aBSREL recalculate the branch lengths? If the answers to these questions are on the site, just tell me so.  It's amazing that the run can proceed so quickly.

Ted

_________________________
Ted R. Schultz
Research Entomologist
Department of Entomology
National Museum of Natural History
Smithsonian Institution
NHB CE516 MRC188
1000 Constitution Ave NW
Washington DC 20560-0003
________________________________

**Comment by spond** [comment]
Dear @schultzt23,

Basically you need to tag the branches of interest in the Newick tree with `{label}` where `label` can be anything (e.g. Test). You can do it interactively with `phylotree.js` as described in http://hyphy.org/tutorials/phylotree/ or any other way you can think of.

Best,
Sergei

**Comment by schultzt23** [comment]
Sergei:

I labeled the tree in phylotree as suggested (there are 8 labeled branches rather than 7) and I placed the tree file (.txt) and the data file (in Phylip format) in Dropbox and shared the folder with you.  The data file is obviously rather large (96MB).

Am I correct that you think this will run on HyPhy on a laptop computer in a few hours?  If so, that's amazing.

Will the results be in the form "there is significant selection on at least one branch" or will it return a decision about each branch?  The latter is what I need.

Ted

_________________________
Ted R. Schultz
Research Entomologist
Department of Entomology
National Museum of Natural History
Smithsonian Institution
NHB CE516 MRC188
1000 Constitution Ave NW
Washington DC 20560-0003
________________________________

**Comment by schultzt23** [comment]
Thank you, Sergei!!!  I very much look forward to the results!  And I will be interested to know the input commands for doing it myself.

Question: Am I correct that aBSREL will not return any information identifying the sites under positive selection?

Ted

_________________________
Ted R. Schultz
Research Entomologist
Department of Entomology
National Museum of Natural History
Smithsonian Institution
NHB CE516 MRC188
1000 Constitution Ave NW
Washington DC 20560-0003
________________________________

**Comment by spond** [comment]
Dear @schultzt23,

Still running; take one crashed because of an unanticipated issue; take 2 is running. 

You analysis is quite interesting to me as a developer, because HyPhy is tightly tuned to work on "gene-sized" datasets, and while it runs on (much) longer alignments, this revealed some signifiant computational bottlenecks, mostly having to do with a large memory footprint. 

While thinking about it I implemented a draft  down/upsampling scheme, based on https://arxiv.org/pdf/1112.5016.pdf and https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8560003/ which dramatically speeds up calculations, but doesn't run on the exact dataset you supply, but rather a "simplified" version of it. 

For one such dataset, the results indicate that THREE branches are subject to positive selection with p < 0.001

<img width="537" alt="image" src="https://user-images.githubusercontent.com/1018513/166484123-4ab0d2dc-1fdf-4f56-b3c5-a69af5b2aabe.png">

<img width="417" alt="image" src="https://user-images.githubusercontent.com/1018513/166484161-587e6002-a701-475f-a325-4fee03e9503b.png">

Best,
Sergei

PS I'll post the full dataset results when they finish.

**Comment by schultzt23** [comment]
Sergei:

I am glad to hear that my data set is interesting to you as a computational problem.  Hopefully that means your time investment, which I very much appreciate, is beneficial for both of us.

The image you sent only shows two of the three branches you mention in your message and it's very exciting to see those branches highlighted.  I look forward to the full results and to knowing what the third branch is!  One of interesting things about this data set is that the loci were not chosen because they are candidates for significant dN/dS; in fact, the opposite is true.  They are Ultra-Conserved Elements, chosen because the core regions remain invariant across large swathes of fungal phylogeny.  They are not even chosen because they contain coding regions, although most of them do.  So to find positive dN/dS on a branch in one of these regions is, I think, very sginficant.

Ted

_________________________
Ted R. Schultz
Research Entomologist
Department of Entomology
National Museum of Natural History
Smithsonian Institution
NHB CE516 MRC188
1000 Constitution Ave NW
Washington DC 20560-0003
________________________________

**Comment by spond** [comment]
Dear @schultzt23,

There are two images showing different parts of the tree (one with 2 branches, one with 1 branch)-- let me know if you cam't see them. I am glad there's some interesting biology; all three branches with signal in this preliminary analysis are under very strong purifying selection except at a small fraction of sites; for example


| &omega; | weight | 
| --- | --- |
| 0.016| 96.9% |
| 0.165| 2.9%|,
| >100 | 0.1%|


I always enjoy exploring the types of data I don't normally see -- makes my job more fun, and improves HyPhy. 

Best,
Sergei

**Comment by schultzt23** [comment]
Ah, yes, now I see the two images.  Even more exciting!!!

_________________________
Ted R. Schultz
Research Entomologist
Department of Entomology
National Museum of Natural History
Smithsonian Institution
NHB CE516 MRC188
1000 Constitution Ave NW
Washington DC 20560-0003
________________________________

**Comment by spond** [comment]
Dear @schultzt23,

Sorry I forgot to update this thread. The complete analysis finished and returned essentially the same three branches subsampled dataset...

Full
```
* Node369, p-value =  0.00000
* Node746, p-value =  0.00024
* Node707, p-value =  0.03264
```

Subsampled
```
* Node746, p-value =  0.00000
* Node707, p-value =  0.00000
* Node369, p-value =  0.00027
```

Best,
Sergei

**Comment by schultzt23** [comment]
Sergei:

I have a number of questions.

1] What is the difference between the "complete analysis" and the subsampled analysis?

2] Three branches were significant.  Does that mean the other 5 branches I designated were NOT found to have significant positive selection?

3] How can I find which node numbers correspond to which branches?

4] Where can I read background information for interpreting these results?

Thanks again.

Ted

_________________________
Ted R. Schultz
Research Entomologist
Department of Entomology
National Museum of Natural History
Smithsonian Institution
NHB CE516 MRC188
1000 Constitution Ave NW
Washington DC 20560-0003
________________________________

**Comment by schultzt23** [comment]
Sergei:

Any news on the analysis?  I suspect it’s still running or that it crashed, but I hope I’m wrong about the latter.

Ted

_________________________
Ted R. Schultz
Research Entomologist
Department of Entomology
National Museum of Natural History
Smithsonian Institution
POB 37012 NHB CE516 MRC188
Washington, DC 20013-7012
***@***.***; 00-1-202-633-0999
Shipping address:
Natural History Bldg. CE516
1000 Constitution Ave NW
Washington DC 20560-0003
NMNH Shipping Office: 00-1-202-633-1637

From: Sergei Pond ***@***.***>
Reply-To: veg/hyphy ***@***.***>
Date: Tuesday, May 3, 2022 at 11:47 AM
To: veg/hyphy ***@***.***>
Cc: Ted Schultz ***@***.***>, Mention ***@***.***>
Subject: Re: [veg/hyphy] Simple beginner question (Issue #1467)

External Email - Exercise Caution

Dear @schultzt23<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschultzt23&data=05%7C01%7Cschultzt%40si.edu%7C9fcab8c6ec724f4cc74908da2d1c3547%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637871896427919134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hME%2F4%2Fvcu15JvJxUgbp6DWNx2gWIJ%2FBhdQ2lAefRT%2Fc%3D&reserved=0>,

There are two images showing different parts of the tree (one with 2 branches, one with 1 branch)-- let me know if you cam't see them. I am glad there's some interesting biology; all three branches with signal in this preliminary analysis are under very strong purifying selection except at a small fraction of sites; for example
ω
weight
0.016
96.9%
0.165
2.9%
>100
0.1%

I always enjoy exploring the types of data I don't normally see -- makes my job more fun, and improves HyPhy.

Best,
Sergei

**Comment by spond** [comment]
Dear @schultzt23,

It did finish a while ago. Let me review and see what it found. I am finishing submitting some grants this week, so please give me a few days. 

Thanks for the reminder!

Best,
Sergei

**Comment by schultzt23** [comment]
I don't think I sent a reminder, but it would be GREAT if the run finished.  I am writing up the paper now and those results could be a valuable addition to it.

_________________________
Ted R. Schultz
Research Entomologist
Department of Entomology
National Museum of Natural History
Smithsonian Institution
NHB CE516 MRC188
1000 Constitution Ave NW
Washington DC 20560-0003
________________________________

**Comment by spond** [comment]
Dear @schultzt23,

The results can be found here:

https://observablehq.com/@spond/displaying-absrel-results-using-branch-censoring?url=https://data.hyphy.org/web/swap/nt_coding_spurceup.phy.ABSREL.json

Three branches under selection

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/1018513/196693434-ae1af87e-908b-49a9-8bc1-0ff0ab92aac1.png">


<img width="332" alt="image" src="https://user-images.githubusercontent.com/1018513/196693530-765b2081-b49f-4604-bf9c-140e259cdf99.png">


<img width="355" alt="image" src="https://user-images.githubusercontent.com/1018513/196693597-9db61cd1-8752-4b59-9dac-a86a9e7585af.png">


<img width="423" alt="image" src="https://user-images.githubusercontent.com/1018513/196693666-6eee1413-4241-4ffa-bbf5-eab14a99d628.png">

Best,
Sergei

**Comment by schultzt23** [comment]
Sergei:

Thank you for following up on this.  I am going to attempt to understand the results, but I will probably have some questions.

Ted

_________________________
Ted R. Schultz
Research Entomologist
Department of Entomology
National Museum of Natural History
Smithsonian Institution
NHB CE516 MRC188
1000 Constitution Ave NW
Washington DC 20560-0003
________________________________

**Comment by schultzt23** [comment]
Sergei:

In going back through me e-mail exchanges with you, I think there may be a discrepancy between the results of the full analyses and the "reduced" analyses.  In each case, three branches were identified.  Two of them are the same across analyses, but one of them differs.

Ted

_________________________
Ted R. Schultz
Research Entomologist
Department of Entomology
National Museum of Natural History
Smithsonian Institution
NHB CE516 MRC188
1000 Constitution Ave NW
Washington DC 20560-0003
________________________________

**Comment by spond** [comment]
Dear @schultzt23,

The "reduced" analysis gives the same set of branches, but with slightly different p-values (https://observablehq.com/@spond/displaying-absrel-results-using-branch-censoring?url=https://data.hyphy.org/web/swap/blb.phy.ABSREL.json)

Best,
Sergei

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/1018513/196976261-d8e07fee-bdae-4c80-8df3-d47e2f3cac47.png">

**Comment by schultzt23** [comment]
Here's a possibly older "reduced" analysis in which one of the identified branches differed from the more recent results. It differs by one adjacent node.

_________________________
Ted R. Schultz
Research Entomologist
Department of Entomology
National Museum of Natural History
Smithsonian Institution
NHB CE516 MRC188
1000 Constitution Ave NW
Washington DC 20560-0003

________________________________

**Comment by schultzt23** [comment]
I'm just trying to reconcile the difference in results.  I will assume it's due to some difference in the older "reduced" analyses.

Thanks!!!

Ted

_________________________
Ted R. Schultz
Research Entomologist
Department of Entomology
National Museum of Natural History
Smithsonian Institution
NHB CE516 MRC188
1000 Constitution Ave NW
Washington DC 20560-0003
________________________________
