### ISSUE TITLE
Datamonkey: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by saoirseguita** [veg/hyphy#1470]
I'm receiving the above-mentioned error on both FUBAR and contrast-FEL. Strangely, those functions were actually working well an hour ago. I have an open tab containing some FUBAR results, and exported the original input file. Even submitting this input file (which yielded an output an hour ago) returns the error. Any insights or assistance would be greatly appreciated!

**Comment by stephenshank** [comment]
Dear @saoirseguita,

After digging through logs we saw that our web application process had too many files open. The process auto-restarted, and I've been able to submit several jobs including FUBAR. We put a few additional safeguards in place against this happening again in the future.

Please let us know if you are still experiencing this issue.

Best,
Stephen

**Comment by saoirseguita** [comment]
Everything seems to be working now. Thank you so much for your swift response!

**Comment by saoirseguita** [comment]
@
