### ISSUE TITLE
Issues with viewing json files

### ISSUE THREAD

**Issue by gshreyaa** [veg/hyphy#1471]
I am not able to load the .json files generated from the hyphy command line tool to view them on http://vision.hyphy.org/.  I have tried loading the files multiple times but nothing happens. Please let me know if more information is needed to know if there is anything I need to do differently.

**Comment by stephenshank** [comment]
Dear @gshreyaa,

Are you able to share results JSONs for specific analyses where you encounter bugs? It would help us to recreate the issue you are experiencing and to troubleshoot. I was able to run a simple SLAC job locally with the latest hyphy (2.5.38), obtain the results JSON, and view it at vision.hyphy.org, so it is tough to tell where to start.

Best,
Stephen

**Comment by gshreyaa** [comment]
Thank you for your reply Stephen. Sure. I am looking to view BUSTED and FEL resulting json files. I have shared one FEL and BUSTED resulting json file each. 
[engjson.zip](https://github.com/veg/hyphy/files/8517792/engjson.zip)

**Comment by stevenweaver** [comment]
Dear @gshreyaa, 

The issue here is a well-known problem (#261). 

Please see the issue thread here for a lengthy discussion on the topic. https://github.com/veg/hyphy-vision/issues/712#issuecomment-1022572198

The tl;dr is that `inf` needs to be substituted out with `1e+9999` in order for the application to work appropriately. 

Best,
Steven

**Comment by gshreyaa** [comment]
Hi Steven, 
It worked! Thank you so much for yours and Stephen's help. I appreciate it a lot.

**Comment by gshreyaa** [comment]
Hi Steven, 
Sorry but I have one more question. 
When trying to run MEME, I get the following error: Error:meme.site_tree_bsrel.New_hCoV_19_Hong_Kong_HKU_220326_003_2022_EPI_ISL_11413737_2022_02_17.bsrel_mixture_aux_0 evaluated to a NaN; this can cause all kinds of odd behavior downstream, therefore it is safer to quit now. 

What does this mean and how do I fix this?

Thanks,
Shreya

**Comment by gshreyaa** [comment]
Sorry, another thing. When loading and viewing my FEL json files, I am not able to view the plot with figure1 = RuntimeError: Cannot read properties of undefined (reading '0'). How do I fix this?

**Comment by gshreyaa** [comment]
HYPHY 2.5.36(MP) for Darwin on x86_64
