### ISSUE TITLE
What's the difference between two dN/dS ratios in "Obtaining the global omega" and "Improving branch lengths"?

### ISSUE THREAD

**Issue by xuechunxu** [veg/hyphy#1472]

**Comment by xuechunxu** [comment]
Hi,

When I run hyphy as [as a Command-Line, I got two dN/dS ratios printed on the screen:
```
### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
* Log(L) =  -897.39, AIC-c =  1850.50 (27 estimated parameters)
* 1 partition. Total tree length by partition (subs/site)  0.184
* non-synonymous/synonymous rate ratio for *Reference* =   0.7341
* non-synonymous/synonymous rate ratio for *Test* =   1.0575

### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
* Log(L) =  -896.23, AIC-c =  1848.18 (27 estimated parameters)
* non-synonymous/synonymous rate ratio for *Reference* =   0.6249
* non-synonymous/synonymous rate ratio for *Test* =   3.0998
```

What's the difference between two dN/dS ratios in "Obtaining the global omega" and "Improving branch lengths"?
Why are the two numbers so different? for example dN/dS ratio for *Test* in `Improving branch lengths` is 3.0998, while In   `Obtaining the global omega` is 1.0575.

Best

**Comment by spond** [comment]
Dear @xuechunxu,

These are estimates obtained under two different models. Many HyPhy analyses will run several steps with models of increasing complexity. The results from simpler (and faster to fit models) are used to initialize more complex models, thereby improving performance. 

The two dN/dS estimates you see here are from two such models. The first codon model fixes branch lengths from a nucleotide model and estimates dN/dS ratios. The second codon model, uses the results from the first and re-optimizes branch lengths and the dN/dS ratio.  The second model is more "realistic", hence its estimate should be preferred. However, as you can see from the log likelihood (only changed by 1 point), and the large change in the *Test* estimate (1.1 to 3.1), there's little **precision** in these estimates (small trees/short genes). 

Best,
Sergei
