### ISSUE TITLE
BIG PROBLEM ADMIN!

### ISSUE THREAD

**Issue by noor3468** [veg/hyphy#1473]
Hello admin! 
                 Hope you are well, Im trying to run MEME and IFEL through Classic mode since 3 weeks but unfortunately its not working. And in normal mode when I select SLAC its also not working. Can u elaborate what is the problem and when it will be okay?
                             THANKS

**Comment by spond** [comment]
Dear @noor3468,

We no longer actively maintain classic.datamonkey.org; we simply don't have the resources (@stevenweaver : can you elaborate).

You can run MEME and IFEL on the new Datamonkey; the analysis will run much faster and produce more accurate results. To emulate IFEL, you simply select internal branches for testing in FEL.

<img width="953" alt="image" src="https://user-images.githubusercontent.com/1018513/165624578-25ce6528-aef7-4330-b138-af4c4546332a.png">


Best,
Sergei

**Comment by noor3468** [comment]
Thank you for your response, but how can I reach to new Data monkey?

**Comment by spond** [comment]
Dear @noor3468,

<url>www.datamonkey.org</url>

Which address have you been using?

Best,
Sergei

**Comment by noor3468** [comment]
I'm using that one but you mentioned in your first reply to use new Data
monkey, therefore I asked

**Comment by spond** [comment]
Dear @noor3468,

Sorry, I am not sure what site you are referring to. Have you been using

http://www.datamonkey.org

or 

http://classic.datamonkey.org

Best,
Sergei

**Comment by noor3468** [comment]
I'm using the first one
www.datamonkey.org
But if I open it then click on classic and want to do MEME by it but
unfortunately failed.

**Comment by stephenshank** [comment]
Dear @noor3468,

To run MEME on the latest Datamonkey you can try here: http://www.datamonkey.org/meme, accessed by the Methods and Tools dropdown.

Best,
Stephen

**Comment by noor3468** [comment]
Thanks, I'll check it out.
