### ISSUE TITLE
Issue running BUSTED

### ISSUE THREAD

**Issue by xing-he529** [veg/hyphy#1474]
hi~
i try to run busted with the following command:

hyphy busted --alignment SuperMatrix.fas --tree tree.newick --branches Foreground

But i got an error like this:

>Loaded a multiple sequence alignment with **18** sequences, **10528020** codons, and **1** partitions from `/hyphy/SuperMatrix.fas`
>branches –> Foreground
Error:
Failed to dereference 'busted.filter.default.site_map'

maybe the alignment is too long ? Can someone please kindly tell me what might go wrong and how I can fix this?
Thanks in advance~

**Comment by spond** [comment]
Dear @xing-he529,

Your guess is correct (the length of the alignment is why the error is thrown). Try

```
hyphy busted --alignment SuperMatrix.fas --tree tree.newick --branches Foreground ENV="USE_MEMORY_SAVING_DATA_STRUCTURES=50000000"
```


Best,
Sergei

**Comment by xing-he529** [comment]
That's really helpful, thank you!!!
