### ISSUE TITLE
LHS after aBSREL analysis

### ISSUE THREAD

**Issue by tamelgarejo** [veg/hyphy#1476]
Hi,

I am trying to estimate the variance in branch length estimates produced by the aBSREL model with the Latin hypercube sampling resampling scheme (using this command: HYPHYMP -p). Unfortunately, in the last step of this analysis I got an error message. 
This are the details of the error:

**********Continue with result processing (y/n)?y

	 Available Result Processing Tools
	 ---------------------------------

	(1):View Results
	(2):Save Results
	(3):Variance Estimates
	(4):Save Covariance Matrix
	(5):Parameter Sampler
	(6):Ancestral Sequences

 Please type in the abbreviation for the tool you want to use (or press q to exit):5

####Sampling Method

1. [**Normal + SiR**] Sample parameters using multivariate normal with the estimated variance-covariance matrix
2. [**Latin Hypercube + SiR**] Sample parameters using latin hypercube sampling scheme with intervals derived using profile likelihood (possibly inflated)

>Please choose an option (or press q to cancel selection):2

>Save results to: (`/usr/local/lib/hyphy/TemplateBatchFiles/`) output

####Parameters to Sample

1. [**All**] Sample all independent parameters
2. [**Global**] Sample global model parameters only
3. [**Local**] Sample local model parameter only
4. [**Choose**] Choose which parameters to sample
5. [**RegExp**] Sample model parameters which match a regular expression

>Please choose an option (or press q to cancel selection):1
How many samples should be drawn? (>=1)10 
How many re-samples should be drawn? [1,10]10
Error:
Current script requires at least version 2.220140505 of HyPhy. Had version 2.4.0.20190223alpha. Please download an updated version from http://www.hyphy.org or github.com/veg/hyphy and try again. in call to RequireVersion("2.220140505");

Function call stack
1 :  RequireVersion("2.220140505");
-------
2 :  ExecuteAFile("Samplers/lhc.bf", /usr/local/lib/hyphy/TemplateBatchFiles/);
-------

Check errors.log for execution error details.

Check messages.log for diagnostic messages.
campus-008-033:~ tomasmelgarejo$ 

Could you please let me know If there is a way to fix this?.

Thank you very much for your help.

Best,

Tomas

**Comment by spond** [comment]
Dear @tamelgarejo,

`-p` options are no available in 2.5+ versions of HyPhy; the logic has been moved into the analyses themselves. You also seem to have a rather outdated version of HyPhy (`2.4.0.20190223alpha` > 5 years old), but that is not the issue here. You can edit `RequireVersion("2.220140505")` to say `RequireVersion("2.4")` and see if that happens.

Best,
Sergei

**Comment by tamelgarejo** [comment]
Dear Sergei,

Thank you for your reply and your suggestion. I did edit the "lhc.bf" file and I could do the LHS analysis; however I found another problem on the in successive steps. Please see below:
**********Continue with result processing (y/n)?y


	 Available Result Processing Tools
	 ---------------------------------


	(1):View Results
	(2):Save Results
	(3):Variance Estimates
	(4):Save Covariance Matrix
	(5):Parameter Sampler
	(6):Ancestral Sequences

 Please type in the abbreviation for the tool you want to use (or press q to exit):5


####Sampling Method

1. [**Normal + SiR**] Sample parameters using multivariate normal with the estimated variance-covariance matrix
2. [**Latin Hypercube + SiR**] Sample parameters using latin hypercube sampling scheme with intervals derived using profile likelihood (possibly inflated)

>Please choose an option (or press q to cancel selection):2


>Save results to: (`/usr/local/lib/hyphy/TemplateBatchFiles/`) V1-ouput


####Parameters to Sample

1. [**All**] Sample all independent parameters
2. [**Global**] Sample global model parameters only
3. [**Local**] Sample local model parameter only
4. [**Choose**] Choose which parameters to sample
5. [**RegExp**] Sample model parameters which match a regular expression

>Please choose an option (or press q to cancel selection):1
How many samples should be drawn? (>=1)50
How many re-samples should be drawn? [1,50]25
<<Inflation factor for profile likelihood bounds (permissible range = [0,1000], default value = 2)>>100

Obtaining profile likeihood bounds...
Preparing sampling grid for lDxWsjbN.tree_0.Node145.beta over [0-20.81059362551928]
Preparing sampling grid for lDxWsjbN.tree_0.Node119.beta over [0-12.95776776135462]
Preparing sampling grid for lDxWsjbN.tree_0.Node119.alpha over [0-35.69039649967285]
Preparing sampling grid for lDxWsjbN.tree_0.Node121.beta over [0-18.60432039186516]
Preparing sampling grid for lDxWsjbN.tree_0.Node121.alpha over [0-9.757901095582918]
Preparing sampling grid for lDxWsjbN.tree_0.Node125.alpha over [0-10.25260421311725]
Preparing sampling grid for lDxWsjbN.tree_0.Node125.beta over [0-3.602444512705206]
Preparing sampling grid for lDxWsjbN.tree_0.Node127.beta over [-0.9645894084763476-10.98823190958874]
Preparing sampling grid for lDxWsjbN.tree_0.Node127.alpha over [0-1030.700833380282]
Preparing sampling grid for lDxWsjbN.tree_0.KX867052_CO_2015.alpha over [0-6.790512590233673]
Preparing sampling grid for lDxWsjbN.tree_0.KX867052_CO_2015.beta over [-0.04216419844749138-0.6526196982395263]
Preparing sampling grid for lDxWsjbN.tree_0.Node128.alpha over [0-75.41519057569448]
Preparing sampling grid for lDxWsjbN.tree_0.Node128.beta over [0-8.121139613372323]
Preparing sampling grid for lDxWsjbN.tree_0.Node130.alpha over [0-2.21918211615117]
Preparing sampling grid for lDxWsjbN.tree_0.Node130.beta over [0-27.92590798163252]
Preparing sampling grid for lDxWsjbN.tree_0.Node132.beta over [0-60.28746758392361]
Preparing sampling grid for lDxWsjbN.tree_0.Node132.alpha over [0-9.365697423905297]
Preparing sampling grid for lDxWsjbN.tree_0.Node134.beta over [-0.7842437689545542-2.786189173069118]
Preparing sampling grid for lDxWsjbN.tree_0.Node134.alpha over [0-21.91885674758065]
Preparing sampling grid for lDxWsjbN.tree_0.Node136.beta over [0-28.52813008215113]
Preparing sampling grid for lDxWsjbN.tree_0.Node136.alpha over [0-2.402562606970917]
Preparing sampling grid for lDxWsjbN.tree_0.Node138.alpha over [0-29.32481298777395]
Preparing sampling grid for lDxWsjbN.tree_0.Node138.beta over [0-2.387993606930772]
Preparing sampling grid for lDxWsjbN.tree_0.Node140.alpha over [0-26.78945807288668]
Preparing sampling grid for lDxWsjbN.tree_0.Node140.beta over [0-2.40181686063477]
Preparing sampling grid for lDxWsjbN.tree_0.Node162.beta over [0-30.43293531851854]
Preparing sampling grid for lDxWsjbN.tree_0.Node162.alpha over [0-3.002179536451941]
Preparing sampling grid for lDxWsjbN.tree_0.Hemp_CO_2019.beta over [0-3.213767984162743]
Preparing sampling grid for lDxWsjbN.tree_0.Hemp_CO_2019.alpha over [0-10000]
Preparing sampling grid for lDxWsjbN.tree_0.Node163.beta over [0-20.11153083676654]
Preparing sampling grid for lDxWsjbN.tree_0.Node163.alpha over [0-2.600742731841758]
Preparing sampling grid for lDxWsjbN.tree_0.KT583745_LH71_2013.beta over [0-26.01447408795062]
Preparing sampling grid for lDxWsjbN.tree_0.KT583745_LH71_2013.alpha over [0-2.396779928557367]
Preparing sampling grid for lDxWsjbN.tree_0.U02311_Svr_1986.beta over [0-31.80992794451054]
Preparing sampling grid for lDxWsjbN.tree_0.U02311_Svr_1986.alpha over [0-2.28581132589821]
Preparing sampling grid for lDxWsjbN.tree_0.Node141.beta over [0-7.509948562011352]
Preparing sampling grid for lDxWsjbN.tree_0.Node141.alpha over [0-1.661894994186376]
Preparing sampling grid for lDxWsjbN.tree_0.AY134867_Wor_1995.alpha over [0-10.30355878896525]
Preparing sampling grid for lDxWsjbN.tree_0.AY134867_Wor_1995.beta over [-0.1177435531276936-0.6588133116418415]
Preparing sampling grid for lDxWsjbN.tree_0.Node142.beta over [0-97.03341016914756]
Preparing sampling grid for lDxWsjbN.tree_0.Node142.alpha over [0-9.566806656164358]
Preparing sampling grid for lDxWsjbN.tree_0.Node144.beta over [0-1.952554114631901]
Preparing sampling grid for lDxWsjbN.tree_0.Node144.alpha over [0-14.47675226719338]
Preparing sampling grid for lDxWsjbN.tree_0.Node148.beta over [0-5.323363644708865]
Preparing sampling grid for lDxWsjbN.tree_0.Node148.alpha over [-0.0208463113274852-0.6526741582564339]
Preparing sampling grid for lDxWsjbN.tree_0.Node152.alpha over [0-6.813093153622645]
Preparing sampling grid for lDxWsjbN.tree_0.Node152.beta over [-0.04230978667674393-0.6521185677832531]
Preparing sampling grid for lDxWsjbN.tree_0.Node156.beta over [0-5.323289061293176]
Preparing sampling grid for lDxWsjbN.tree_0.Node156.alpha over [-0.02086561424255291-0.6526738548566562]
Preparing sampling grid for lDxWsjbN.tree_0.Node158.alpha over [0-11.91891309946444]
Preparing sampling grid for lDxWsjbN.tree_0.Node158.beta over [0-1.513600972502732]
Preparing sampling grid for lDxWsjbN.tree_0.MK803280_Wor_2018.beta over [0-11.10079324207479]
Preparing sampling grid for lDxWsjbN.tree_0.MK803280_Wor_2018.alpha over [0-1.328306373805344]
Preparing sampling grid for lDxWsjbN.tree_0.KT583741_CO_2013.alpha over [0-11.86572317766286]
Preparing sampling grid for lDxWsjbN.tree_0.KT583741_CO_2013.beta over [0-1.677393228656263]
Preparing sampling grid for lDxWsjbN.tree_0.KT276913_Svr_2007.beta over [0-10.56709702532191]
Preparing sampling grid for lDxWsjbN.tree_0.KT276913_Svr_2007.alpha over [0-1.517813061544116]
Preparing sampling grid for lDxWsjbN.tree_0.Node153.alpha over [0-10.33927508959341]
Preparing sampling grid for lDxWsjbN.tree_0.Node153.beta over [0-1.321933446684612]
Preparing sampling grid for lDxWsjbN.tree_0.MW188519_Wor_2020.alpha over [0-9.366501102694533]
Preparing sampling grid for lDxWsjbN.tree_0.MW188519_Wor_2020.omega1 over [0-1]
Preparing sampling grid for lDxWsjbN.tree_0.MW188519_Wor_2020.omega2 over [-0.9907886449145972-11.40738749992558]
Preparing sampling grid for lDxWsjbN.tree_0.MW188519_Wor_2020.bsrel_mixture_aux_0 over [1.000000082740371e-08-1]
Preparing sampling grid for lDxWsjbN.tree_0.KX867026_Svr_2006.alpha over [0-11.85322484050703]
Preparing sampling grid for lDxWsjbN.tree_0.KX867026_Svr_2006.beta over [0-2.184685521458979]
Preparing sampling grid for lDxWsjbN.tree_0.Node149.alpha over [0-11.36175727799543]
Preparing sampling grid for lDxWsjbN.tree_0.Node149.beta over [0-1.327183022645828]
Preparing sampling grid for lDxWsjbN.tree_0.S5_W4_2020.alpha over [0-15.64861014434683]
Preparing sampling grid for lDxWsjbN.tree_0.S5_W4_2020.beta over [0-1.084764524277422]
Preparing sampling grid for lDxWsjbN.tree_0.LC621348_Svr_2021.beta over [0-14.24655773335939]
Preparing sampling grid for lDxWsjbN.tree_0.LC621348_Svr_2021.alpha over [0-2.413828440684385]
Preparing sampling grid for lDxWsjbN.tree_0.HQ214016_Mld_2007.beta over [0-10.85385718347112]
Preparing sampling grid for lDxWsjbN.tree_0.HQ214016_Mld_2007.alpha over [0-1.500034699828585]
Preparing sampling grid for lDxWsjbN.tree_0.KX867016_Svr_2006.beta over [0-13.89508917494098]
Preparing sampling grid for lDxWsjbN.tree_0.KX867016_Svr_2006.alpha over [0-1.508743086355067]
Preparing sampling grid for lDxWsjbN.tree_0.KX867055_Wor_2015.bsrel_mixture_aux_0 over [9.999999994736442e-09-1]
Preparing sampling grid for lDxWsjbN.tree_0.KX867055_Wor_2015.omega1 over [0-1]
Preparing sampling grid for lDxWsjbN.tree_0.KX867055_Wor_2015.alpha over [-0.01641159511843569-2.663273693592515]
Preparing sampling grid for lDxWsjbN.tree_0.KX867055_Wor_2015.omega2 over [-0.01641159511843569-0.6530230883820928]
Preparing sampling grid for lDxWsjbN.tree_0.JX487184_PeCT_2009.bsrel_mixture_aux_0 over [9.999999994736442e-09-1]
Preparing sampling grid for lDxWsjbN.tree_0.JX487184_PeCT_2009.alpha over [0-2.190462807243022]
Preparing sampling grid for lDxWsjbN.tree_0.JX487184_PeCT_2009.omega1 over [0-1]
Preparing sampling grid for lDxWsjbN.tree_0.JX487184_PeCT_2009.omega2 over [0-1.083495163628773]
Preparing sampling grid for lDxWsjbN.tree_0.KX867051_CO_2015.beta over [0-12.09779484242591]
Preparing sampling grid for lDxWsjbN.tree_0.KX867051_CO_2015.alpha over [0-2.301696663773338]
Preparing sampling grid for lDxWsjbN.tree_0.KT276896_Kim_2006.beta over [0-10.61478524423234]
Preparing sampling grid for lDxWsjbN.tree_0.KT276896_Kim_2006.alpha over [0-1.315847082379078]
Preparing sampling grid for lDxWsjbN.tree_0.KT583740_LH71_2013.alpha over [0-13.68750600129693]
Preparing sampling grid for lDxWsjbN.tree_0.KT583740_LH71_2013.beta over [-0.1956596407035797-0.6540749270693745]
Preparing sampling grid for lDxWsjbN.tree_0.EU586261_Mld_2007.alpha over [0-11.53690571180855]
Preparing sampling grid for lDxWsjbN.tree_0.EU586261_Mld_2007.beta over [0-2.544336862327314]
Preparing sampling grid for lDxWsjbN.tree_0.KX867024_Wor_2006.alpha over [0-10.43518314663341]
Preparing sampling grid for lDxWsjbN.tree_0.KX867024_Wor_2006.beta over [0-1.084017733019326]
Preparing sampling grid for lDxWsjbN.tree_0.KT276905_Svr_2006.beta over [0-5.375163515828818]
Preparing sampling grid for lDxWsjbN.tree_0.KT276905_Svr_2006.alpha over [0-1.084630580268435]
Preparing sampling grid for lDxWsjbN.tree_0.Node122.beta over [0-13.3456579882794]
Preparing sampling grid for lDxWsjbN.tree_0.Node122.alpha over [0-2.073996896030023]
Preparing sampling grid for lDxWsjbN.tree_0.KX867017_Wor_2006.alpha over [0-93.922663976924]
Preparing sampling grid for lDxWsjbN.tree_0.KX867017_Wor_2006.beta over [0-4.131115130905485]
Preparing sampling grid for lDxWsjbN.tree_0.EU586260_Mld_2007.alpha over [0-1.934131204867211]
Preparing sampling grid for lDxWsjbN.tree_0.EU586260_Mld_2007.beta over [0-10000]
Preparing sampling grid for lDxWsjbN.tree_0.KT276906_Svr_2006.beta over [0-8.38064849995998]
Preparing sampling grid for lDxWsjbN.tree_0.KT276906_Svr_2006.alpha over [-0.07361300266878412-0.9144238622341806]
Preparing sampling grid for lDxWsjbN.tree_0.Node62.beta over [0-10.91535726685555]
Preparing sampling grid for lDxWsjbN.tree_0.Node62.alpha over [0-1.402182208311416]
Preparing sampling grid for lDxWsjbN.tree_0.Node70.beta over [0-8.436951355847295]
Preparing sampling grid for lDxWsjbN.tree_0.Node70.alpha over [0-2.274372096727671]
Preparing sampling grid for lDxWsjbN.tree_0.Node116.alpha over [0-25.65298095239474]
Preparing sampling grid for lDxWsjbN.tree_0.Node116.beta over [0-3.066780206868545]
Preparing sampling grid for lDxWsjbN.tree_0.KX867053_Wor_2015.bsrel_mixture_aux_0 over [9.999999994736442e-09-1]
Preparing sampling grid for lDxWsjbN.tree_0.KX867053_Wor_2015.omega2 over [0-900155624567084.6]
Preparing sampling grid for lDxWsjbN.tree_0.KX867053_Wor_2015.omega1 over [0-1]
Preparing sampling grid for lDxWsjbN.tree_0.KX867053_Wor_2015.alpha over [0-1.085769907448989]
Preparing sampling grid for lDxWsjbN.tree_0.KU892790_CO_2008.beta over [0-11.53848541131034]
Preparing sampling grid for lDxWsjbN.tree_0.KU892790_CO_2008.alpha over [0-1.337703041981877]
Preparing sampling grid for lDxWsjbN.tree_0.Node71.alpha over [0-7.375390453831317]
Preparing sampling grid for lDxWsjbN.tree_0.Node71.beta over [0-1.084939264581854]
Preparing sampling grid for lDxWsjbN.tree_0.Node95.alpha over [0-9.946648363874424]
Preparing sampling grid for lDxWsjbN.tree_0.Node95.beta over [0-1.507753449577418]
Preparing sampling grid for lDxWsjbN.tree_0.Node97.beta over [0-9.171071304176028]
Preparing sampling grid for lDxWsjbN.tree_0.Node97.alpha over [-0.08296024222455657-0.6577264369014497]
Preparing sampling grid for lDxWsjbN.tree_0.Node99.beta over [-0.08296024222455657-3.835914028566996]
Preparing sampling grid for lDxWsjbN.tree_0.Node99.alpha over [0-1.084274327410807]
Preparing sampling grid for lDxWsjbN.tree_0.Node101.alpha over [0-6.064662521515408]
Preparing sampling grid for lDxWsjbN.tree_0.Node101.beta over [0-1.499549983320218]
Preparing sampling grid for lDxWsjbN.tree_0.Node103.alpha over [0-9.977438921532059]
Preparing sampling grid for lDxWsjbN.tree_0.Node103.beta over [0-1.084858684029868]
Preparing sampling grid for lDxWsjbN.tree_0.Node109.alpha over [0-12.73032430923868]
Preparing sampling grid for lDxWsjbN.tree_0.Node109.beta over [0-1.674915473388578]
Preparing sampling grid for lDxWsjbN.tree_0.Node113.alpha over [0-10.00621358968298]
Preparing sampling grid for lDxWsjbN.tree_0.Node113.beta over [0-1.669054085644344]
Preparing sampling grid for lDxWsjbN.tree_0.KT583730_CO_2013.bsrel_mixture_aux_0 over [9.999999994736442e-09-1]
Preparing sampling grid for lDxWsjbN.tree_0.KT583730_CO_2013.omega2 over [0-1.668715062150373]
Preparing sampling grid for lDxWsjbN.tree_0.KT583730_CO_2013.alpha over [0-9.498220359166266]
Preparing sampling grid for lDxWsjbN.tree_0.KT583730_CO_2013.omega1 over [0-1]
Preparing sampling grid for lDxWsjbN.tree_0.KT583744_CO_2013.alpha over [0-9.525048896608364]
Preparing sampling grid for lDxWsjbN.tree_0.KT583744_CO_2013.beta over [0-1.813278835761069]
Preparing sampling grid for lDxWsjbN.tree_0.Node110.beta over [0-10.92144218841311]
Preparing sampling grid for lDxWsjbN.tree_0.Node110.alpha over [0-1.668217564752133]
Preparing sampling grid for lDxWsjbN.tree_0.KX867022_CO_2006.alpha over [0-5.2357442763089]
Preparing sampling grid for lDxWsjbN.tree_0.KX867022_CO_2006.beta over [0-1.312991355530032]
Preparing sampling grid for lDxWsjbN.tree_0.KT583748_LH71_2010.beta over [0-7.286310847714502]
Preparing sampling grid for lDxWsjbN.tree_0.KT583748_LH71_2010.alpha over [0-3.679299349811208]
Preparing sampling grid for lDxWsjbN.tree_0.Node104.alpha over [-0.9635115058191291-21.65078609492919]
Preparing sampling grid for lDxWsjbN.tree_0.Node104.beta over [0-1671.879753790955]
Preparing sampling grid for lDxWsjbN.tree_0.Node106.beta over [-5.658964939205396-7.076792410435957]
Preparing sampling grid for lDxWsjbN.tree_0.Node106.alpha over [-5.658964939205396-0.6624956400476874]
Preparing sampling grid for lDxWsjbN.tree_0.KT583747_CO_2013.beta over [0-9.056880237162586]
Preparing sampling grid for lDxWsjbN.tree_0.KT583747_CO_2013.alpha over [0-1.085900620112606]
Preparing sampling grid for lDxWsjbN.tree_0.KT583739_CO_2013.beta over [0-8.1302566575777]
Preparing sampling grid for lDxWsjbN.tree_0.KT583739_CO_2013.alpha over [-0.06497218255691203-0.6527455836478884]
Preparing sampling grid for lDxWsjbN.tree_0.M24597_Log_1930.beta over [0-4.065380240190569]
Preparing sampling grid for lDxWsjbN.tree_0.M24597_Log_1930.alpha over [0-1.39608801846306]
Preparing sampling grid for lDxWsjbN.tree_0.KX867049_CO_2014.beta over [0-119.0734242707077]
Preparing sampling grid for lDxWsjbN.tree_0.KX867049_CO_2014.alpha over [1e+25--9.000000000000001e+25]
Error:
[0,-1e+26] is not a valid interval in call to FindRoot(z, ZCDF(x/rightSTD)-ZCDF(thisVarValues[ss-1]/rightSTD)-weight, x, thisVarValues[ss-1], rightSpan);

Function call stack
1 :  FindRoot(z, ZCDF(x/rightSTD)-ZCDF(thisVarValues[ss-1]/rightSTD)-weight, x, thisVarValues[ss-1], rightSpan);
-------
2 :  ExecuteCommands(sampleInstructions, /usr/local/lib/hyphy/TemplateBatchFiles/Samplers/);
-------
3 :  ExecuteAFile("Samplers/lhc.bf", /usr/local/lib/hyphy/TemplateBatchFiles/);
-------

Check errors.log for execution error details.

Check messages.log for diagnostic messages.
campus-008-033:~ tomasmelgarejo$ 

Please, any suggestion to solve this issue?.

Thank you,

Tomas

**Comment by spond** [comment]
Dear @tamelgarejo,

Seems like one of the parameter estimates (`lDxWsjbN.tree_0.KX867049_CO_2014.alpha`) is infinite and the sampler is not properly handling it. Sorry -- there is no easy fix for this short of revising `LHC.bf`

Best,
Sergei

**Comment by tamelgarejo** [comment]
Dear Sergei,

Thank you for your time revising this issue. It looks like my dataset (viral gene) that I am trying to test for ancient origin is composed of isolates (strains of a viral species) genetically close related (very short branch-length). Also, it doesn't have "enough" temporal signal.

Again, thank you.

Best regards,

Tomas
