### ISSUE TITLE
Which module of should we use for calculation.

### ISSUE THREAD

**Issue by ld9866** [veg/hyphy#1480]
Hello dear software developers!
I found related tutorials on GitHub and simplified the process, we used Orthofinder's -d mode to identify orthologous genomes from our 11 genome cds files, we used the Single_Copy_Orthologue_Sequences machine for PRANK and GBlock After completing the sequence alignment, we finally wanted to use HYPHY for positive selection analysis, but I found that the process on the official website did not find the method we wanted to analyze.
I uploaded our tree file and one of the example files, we now have about 200 files like this, what we want to do now is to detect genes that are positively selected between pig1 and pig2, hope you can give me some advice Let me complete this crucial step and which module of hyphy should we use for calculation(FEL FUBAR ML SLAC MEME..).
Best wishes!
Dong

treefile:
(opossum,((mouse,(monkey,human)),((horse,dog),(camle,((goat,cattle),(pig1,pig2))))));
cds:
[example.txt](https://github.com/veg/hyphy/files/8750625/example.txt)

**Comment by vappiah** [comment]
@ld9866 I am trying to do a similar analysis. I have already run orthofinder and have my result. But my main challenge is getting the alignment file. I am new to this kind of analysis and I would be grateful if you can give additional details and possibly example commands I can use to obtain the alignment file and parse to HYPHY.

**Comment by spond** [comment]
Dear @vappiah,

I have no first-hand experience with `orthofinder` so I can't really help you here. HyPhy requires a multiple sequence alignment (in frame) in one of the supported formats (`FASTA`, `phylip`, `NEXUS`).

I am sure there is an option to export your "orthogroups" into an alignment file, since the program is building phylogenies anyway for detection.

Best.
Sergei

**Comment by vappiah** [comment]
Hello @spond 

I just read one of the issues and this [tutorial ](https://github.com/veg/hyphy-analyses/tree/master/codon-msa )was given. 

I have 50  _Vibro cholerae_ isolates and I have extracted the CDS of each isolate into a separate fasta files.
I would like to confirm if I can use proceed. In that case I don't need to use orthofinder.


Please advice.
