### ISSUE TITLE
Interpreting RELAX results

### ISSUE THREAD

**Issue by mbarkdull** [veg/hyphy#1483]
Hi all! 

I have a quick question about how to appropriately think about the results of a RELAX analysis. Imagine an alignment for which RELAX finds significant evidence of relaxation of selection in your foreground branches (relative to the background branches). Is it appropriate to also think about this result as evidence for intensification of selection in the background branches, relative to the foreground branches? I.e. if one flipped the branch labels, would one obtain the opposite result for a given alignment?

If it helps, I ask because I'm interested in comparing (genes under positive selection in foreground species(based on BUSTED-PH) + intensified selection in foreground species) with (genes under positive selection in background species + intensified selection in background species), and I'm not sure if I can identify genes under intensified selection in background species without re-running RELAX. I'm hoping I can!

Thanks so much!
Megan

**Comment by spond** [comment]
Dear @mbarkdull,

In most cases, it should work as you describe, i.e. if &omega;<sub>Foreground</sub> ~ &omega;<sub>Background</sub><sup>K</sup>, then &omega;<sub>Background</sub> ~ &omega;<sub>Foreground</sub><sup>1/K</sup>. There are some oddities when K ~ 0 (because 1/K becomes infinite), but otherwise your logic should hold: RELAX is a relative test, so if FG is intensified vs BG, then BG is relaxed vs FG etc.

Here's for example the result of running Fig4H from the RELAX paper. 

As in the paper...

```
### Fitting the alternative model with individual K parameters for 2 branch groups
* Log(L) = -1627.09, AIC-c =  3356.27 (50 estimated parameters)
* Relaxation/intensification parameter (K) =     0.18
* The following rate distribution was inferred for **test** branches

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |    0.222    |                                   |
|        Negative selection         |     0.076     |   99.469    |                                   |
|      Diversifying selection       |     2.468     |    0.309    |                                   |

* The following rate distribution was inferred for **reference** branches

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |    0.222    |                                   |
|        Negative selection         |     0.000     |   99.469    |                                   |
|      Diversifying selection       |    157.952    |    0.309    |     
```

and with branch sets reversed...

```
### Fitting the alternative model with individual K parameters for 2 branch groups
* Log(L) = -1627.07, AIC-c =  3356.23 (50 estimated parameters)
* Relaxation/intensification parameter (K) =     6.11
* The following rate distribution was inferred for **test** branches

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |   99.691    |                                   |
|        Negative selection         |     0.000     |    0.000    |       Not supported by data       |
|      Diversifying selection       |    169.272    |    0.309    |                                   |

* The following rate distribution was inferred for **reference** branches

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.076     |   99.691    |                                   |
|        Negative selection         |     0.084     |    0.000    |       Not supported by data       |
|      Diversifying selection       |     2.317     |    0.309    |                                   |
```

So, approximately (within statistical noise for this small dataset), K = 0.18 is one case and K = 6.11 in the reversed case. 1/0.18 ~ 5.6, so not too far off :)

Best,
Sergei

**Comment by liamfriar** [comment]
Hi,

I am trying to understand the distribution tables. I have taken the outputs from Spielman et al, 2017 (a tutorial). My understanding is: the main result is K=0.73 with p = 0.0014 . How do I read the three tables? I think each one is the _omega_ distribution for a set of branches in a particular analysis, with the first being only the **test** branches with k allowed to vary, the second being the reference branches with k=1, and the third being the combined branch sets with k=1. So what are the three values in each table? Is this like a histogram with 3 bins, each with a max at the given _omega_? But if that is the case, why are there always 2x negative and 1x diversifying and how are the bin boundaries chosen? Or have I misinterpreted? Thank you!

### Fitting the alternative model to test K != 1
* Log(L) = -14337.22, AIC-c = 28849.02 (87 estimated parameters)
* Relaxation/intensification parameter (K) = 0.73
* The following rate distribution was inferred for **test** branches
| Selection mode | dN/dS |Proportion, %| Notes |
|-----------------------------------|---------------|-------------|-----------------------------------|
| Negative selection | 0.031 | 94.752 | |
| Negative selection | 0.086 | 2.951 | |
| Diversifying selection | 1.406 | 2.297 | |
* The following rate distribution was inferred for **reference** branches
| Selection mode | dN/dS |Proportion, %| Notes |
|-----------------------------------|---------------|-------------|-----------------------------------|
| Negative selection | 0.009 | 94.752 | |
| Negative selection | 0.035 | 2.951 | |
| Diversifying selection | 1.591 | 2.297 | |
### Fitting the null (K := 1) model
* Log(L) = -14342.33, AIC-c = 28857.22 (86 estimated parameters)
* The following rate distribution for test/reference branches was inferred
| Selection mode | dN/dS |Proportion, %| Notes |
|-----------------------------------|---------------|-------------|-----------------------------------|
| Negative selection | 0.010 | 94.149 | |
| Negative selection | 0.021 | 3.391 | |
| Diversifying selection | 1.735 | 2.460 | |
----
## Test for relaxation (or intensification) of selection [RELAX]
Likelihood ratio test **p = 0.0014**.
>Evidence for intensification of selection among **test** branches _relative_ to the **reference** branches at P
<=0.05
