### ISSUE TITLE
Cannot run MEME test with my own tree

### ISSUE THREAD

**Issue by zhaoyih8** [veg/hyphy#1486]
Hi
I am trying to run a MEME test on my sequences based on a tree I already made. I have read the samples for preparing file for MEME run. I think my file exactly follow the samples but every time I run it the result is shown as follow:
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:60116] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

[n7:60116] 31 more processes have sent help message help-mpi-api.txt / mpi-abort
[n7:60116] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

**Comment by spond** [comment]
Dear @zhaoyih8,

That looks like an MPI issue to me, and not something that HyPhy is doing, e.g. see https://github.com/open-mpi/ompi/issues/7529
I would suggest you try running an MPI "hello world" program to confirm that you are able to launch MPI processes.

Best,
Sergei
