### ISSUE TITLE
Usage of foreground and background branches

### ISSUE THREAD

**Issue by Suirotras** [veg/hyphy#1487]
I have a set a set of multiple sequence alignments and a species tree. I want to test wether one specific species displays signs of positive selection in these genes, compared to all the other species in the species tree. I want to use aBSREL for this. However, I am a bit confused with how to use the foreground and background branches to do this. 

Do I just label (as foreground branch in the species tree) and select that one specific species in the aBSREL options, or is this wrong? Should I instead label multiple species and will it then only test for positive selection between these foreground branches?

Sorry if this is a simple question. I am just starting to use this program and want to make sure I am using it correctly. many thanks for developing this program!

**Comment by jzehr** [comment]
Dear @Suirotras, 

Good question. In general, for the HyPhy tools, if you only label the branches you want to examine, the remaining branches will be interpreted as `background`. You just need to label the branch (or branches) you want to examine, which can be done with a tool like http://phylotree.hyphy.org/ (in this example I labeled the `THORNYHEAD` branch on the tree, which shows up as being labeled `{Foreground}` in the newick. 

![example](https://user-images.githubusercontent.com/38324371/176187039-371db7c7-1c6d-404e-871e-72331ba3ea49.png)

Once you have a labeled tree, if you are running on the command line, you can just invoke `absrel` with an alignment and tree, accompanied with `--branches Foreground`. Keep in mind you can change the name `Foreground` to any other name, so long as the `--branches` parameter reflects that. 

Let us know if you have any other questions.

Best,

**Comment by Suirotras** [comment]
Dear @jzehr,

That was a clear clear answer. Thanks for your help!

Best,
