### ISSUE TITLE
DataMonkey is not working?

### ISSUE THREAD

**Issue by laurasolartemurillo** [veg/hyphy#1488]
We're sorry, there was an error processing your job. Please try again, or visit
 [our GitHub issues page (http://github.com/veg/hyphy/issues/)
 and create an issue if the issue persists.

**Comment by jzehr** [comment]
Dear @laurasolartemurillo,

Thank you for reporting, we are working to remedy this issue ASAP. 

In the meantime if you have a file that you need analyzed immediately, feel free to send it to my email (jordan dot zehr at temple dot edu) and I would be happy to run it for you. 

Best,

**Comment by laurasolartemurillo** [comment]
Thank you very much to both
