### ISSUE TITLE
arguments for GARD method

### ISSUE THREAD

**Issue by ClarenceCEN** [veg/hyphy#1490]
Hi, I was using the GARD method in hyphy command line version to detect recombination events in a genome. I was wondering is there an argument for users to set the number of recombination breakpoints in the sequence to look for (e.g. only a single breakpoint) since searching for multiple positions could be time-consuming?

**Comment by spond** [comment]
Dear @ClarenceCEN,

Currently there is no such argument, but it can be added in the next release. Are you thinking of something like

```
--max-breakpoints N
```

to request that GARD consider **at most** N breakpoints?

Best,
Sergei

**Comment by spond** [comment]
Dear @ClarenceCEN,

This is available in the 2.5.40 release.

Best,
Sergei
