### ISSUE TITLE
Beginner question on Fst compartmentalization

### ISSUE THREAD

**Issue by Beantha** [veg/hyphy#1491]
Hii,

I'm trying to learn how to analyze my HIV data for compartmentalization between plasma and CSF. I followed the tutorial for Fst of the Vancouver Workshop and I'm using the tutorial data files to practice, however, I cant figure out how to determine the permutation value for the bootstrap and the permutation test? Can someone please explain to me how to calculate this based on the data?

**Comment by spond** [comment]
Dear @Beantha,

You mean the number of replicates for permutations? The typical rule of thumb is that if you want to look at _p-value_ ~ p, then you should generate 1/p + 1 replicates. In other words, if you generate 101 replicates, you can compute p-values down to 0.01, if you generate 1001 replicates -- down to 0.001 etc.

Best,
Sergei

**Comment by Beantha** [comment]
Thank you for responding. In the meantime, I figured out how to get the Fst values, but how do you calculate the p-value of the FST score to determine if the compartmentalization is significant?

**Comment by spond** [comment]
Dear @Beantha,

That's based on the permutation test that the F<sub>ST</sub> analysis performs for you at the very end of the screen output (here the p-values are ~0).

```
Prob {Random F_ST > Observed F_ST}

Hudson, Slatkin and Maddison : 0
Slatkin                      : 0
Hudson, Boos and Kaplan	     : 0
Hudson, S_nn                 : 0
```

Best,
Sergei

**Comment by Beantha** [comment]
Oke, got it. And what value should I add when I get this question "How many permutations would you like to perform?"

**Comment by spond** [comment]
Dear @Beantha,

Depends on how small of a p-value you can identify. 

N = 100 => p = 0.01
N = 1000 => p = 0.001
N = 10000 => p = 0.0001

...

Best,
Sergei

**Comment by Beantha** [comment]
Does the p-value correlate with accuracy or sensitivity? So if I choose 1000 instead of 100, my results would be more accurate?
