### ISSUE TITLE
What can be the most reliable parameters for running GARD method for our sample? 

### ISSUE THREAD

**Issue by Clementine0702** [veg/hyphy#1492]
Hi,
I was using the command-line version of hyphy to run the GARD method to test if there were indications of recombination. My alignment consists of 54 nucleotide sequences and each with 1011 bps (one gene, 54 species of primates). I ran 3 different approaches:
When I tried the default GARD method with no site-to-site rate variation, there is one inferred breakpoint at site 447 with −43.5702 Δ c-AIC compared to the null model, and 99.3979 Δ c-AIC compared to the single tree multiple partitions.
When I tried Beta-Gamma with the rate class of 3, the inferred breakpoints is at site 437 with −58.8679 Δ c-AIC compared to the null model, and 79.8535 Δ c-AIC compared to the single tree multiple partitions.
However, when I used the most recommended parameters with GDD and rate class of 3, there was no shown break point.
Question: Since different parameters generated different GARD results, I’m wondering what you think is the most reliable parameter given my alignment size and the level of divergence in the dataset, and what could we do for the next steps to understand the incongruence.
Is it better to explore the GARD parameter space further? If so, do you have papers recommended for understanding and interpreting the results?
Thanks!

**Comment by spond** [comment]
Dear @Clementine0702,

Interesting example; I'd expect Beta-Gamma and GDD to be somewhat consistent. Would you mind sharing your alignment for me to trouble-shoot? Also, are the Δc-AIC *negative* compared to the single partition (null) model? If so, then the interpretation is that there is no recombination.

One possible explanation for an incongruence is that your alignment possesses spatial heterotachy (i.e one part of the alignment is more divergent than the other) and the GDD distribution is able to capture it better.; but that would be quite unusual.

Best,
Sergei

**Comment by Clementine0702** [comment]
Dear Dr Pond,
Thank you so much for your replies. Your explanation is really helpful.

- Here is a link to our alignment: https://github.com/bitarellolab/BitterReceptors/blob/main/cchen/HyPhy%20Tests/Site_models_results/TAS2R38_final.fa

- Here is a summary of the results: 

![Screen Shot 2022-07-14 at 12 02 53 PM](https://user-images.githubusercontent.com/105946624/179065337-2ccd40db-044c-4bf4-b767-0b09ca171b85.png)

In response to your question:
_"Also, are the Δc-AIC negative compared to the single partition (null) model? If so, then the interpretation is that there is no recombination."_

- Indeed, as shown in the table above, the Δc-AIC vs the null model is negative for "no rate variation" and "beta-gamma", but zero for GDD.

- On the other hand, as shown in the table above, Δc-AIC vs single tree multiple partitions is positive for "no rate" and "beta-gamma" and again zero for GDD.

- Based on your reply, I would think that because Δc-AIC vs null model is never positive in any of my tests, then there is no evidence for recombination. And yet both "no site to site rate variation" and beta-gamma say in the summary output that there is evidence:

**Output from "no site to site rate variation"**
Comparing the AICc score of the best fitting GARD model, which allows for different topologies between segments (12350.1), and that of the model that assumes the same tree for all the partitions inferred by GARD, but allows different branch lengths between partitions (12449.5) suggests that because the multiple tree model can be preferred over the single tree model by an evidence ratio of 100 or greater, at least of one of the breakpoints reflects a true topological incongruence.
**Output from "beta-gamma"**
Comparing the AICc score of the best fitting GARD model, which allows for different topologies between segments (12243.0), and that of the model that assumes the same tree for all the partitions inferred by GARD, but allows different branch lengths between partitions (12322.9) suggests that because the multiple tree model can be preferred over the single tree model by an evidence ratio of 100 or greater, at least of one of the breakpoints reflects a true topological incongruence.

Should we just ignore this and work under the premise that only the  Δc-AIC vs null model (1 partition) is meaningful evidence for recombination, but  Δc-AIC vs null model (multiple partitions) is not?

Thank you very much for your help,
Clementine

**Comment by spond** [comment]
Dear @Clementine0702,

I think you may be running a really old version of GARD (4+ years old). Which HyPhy version do you have?

I confirmed by running your alignment through all currently supported rate variation options (`None`, `GDD`, `Gamma`) that there is *no evidence of recombination*. This is also what the results above suggest. I agree that the phrasing in previous versions of GARD was confusing.

The visualization module (http://vision.hyphy.org/GARD) reports something like this:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/1018513/179090857-a428991d-0fa1-41e8-8829-99bd28994dc2.png">

Best,
Sergei

**Comment by Clementine0702** [comment]
Dear Dr. Pond, 

Thank you so much for helping us to troubleshoot! The version I used is HYPHY 2.5.39(MP). I did update the HyPhy version, but it was before I ran the sample, so it’s possible that the discrepancy was caused by running the old version of HyPhy. 

Thanks again for your help!
Clementine
