### ISSUE TITLE
How to use the k values  in the table of Branch attributes at the bottom of the json output file

### ISSUE THREAD

**Issue by biozhajie** [veg/hyphy#1497]
Dear Professor,

The k values for all branches are listed in the table of Branch attributes at the bottom of the json output file (like shown in figure below), but I have diffculties to use them for further analysis, because I cannot map them to respective branches exactly especially for the branches with the name like 'Node X' (I don't know which node in the phylogeny tree to be corresponded ). 
So I don't how to use these values further, but I don't think they are something of little values since you have desgined to list them separately.

Looking forward to recieving your reply very much!

Thanks,
Jie 

![image](https://user-images.githubusercontent.com/20587062/181398899-7c9fff5a-9e6b-4f75-b3ce-07a5f1c5ae48.png)

**Comment by spond** [comment]
Dear @biozhajie,

Please load the JSON file into https://observablehq.com/@spond/plotting-relax-k-values-on-branches-of-the-tree.

You will be able to color branches by `k` and display internal node names.

<img width="730" alt="Screen Shot 2022-07-29 at 8 20 50 AM" src="https://user-images.githubusercontent.com/1018513/181792010-ea2530d7-4052-4723-b79f-54df6f2fe02b.png">

Best,
Sergei

**Comment by biozhajie** [comment]
Dear Dr. Pond
Thanks for reply very much! But can this tree with k atrribute values be exported as the kind of tree file (e.g nexus file)  which can be manipulated in some popular tree figure programs (e.g. figtree)?

Thanks,
Jie

**Comment by spond** [comment]
Dear @biozhajie,

I added a Newick export box to https://observablehq.com/@spond/plotting-relax-k-values-on-branches-of-the-tree

Best,
Sergei

**Comment by biozhajie** [comment]
Dear @spond 

Thanks your reply very much! That's great! But I am sorry I will put a further request here. If you can add the three options it will be almost perfect for me:
1.  Node ordering option (according to either increasing or decreasing order) for reordering nodes and tips ;
2. Time scale option avilable for setting time of the most recent tip to a real time in years and also setting the scale factor (similar to the option in figtree, see figure 1 below );
3. Scale Axis avilable for rending time scale axis below the tree and alsp the time grids (similar to the option in figtree, see figure 2 below ).

Best,
Jie
 
![image](https://user-images.githubusercontent.com/20587062/182275250-15800320-07e3-4153-a995-d0786ac3ad54.png)
figure1

![image](https://user-images.githubusercontent.com/20587062/182275364-10b3d593-f928-45ca-97b8-d71c38596c22.png)
figure2
