### ISSUE TITLE
How to fix the topology and branch lengthes of my input tree when estimating other parameters using RELAX

### ISSUE THREAD

**Issue by biozhajie** [veg/hyphy#1498]
Dear Pond,

I want to fix the topology and branch lengthes of my input tree  when estimating other parameters using RELAX, how to modify the input file?

Thanks,

Jie

**Comment by spond** [comment]
Dear @biozhajie,

The topology is fixed at whatever you supply (it may be unrooted if the tree is rooted). 

Fixing branch lengths at user supplied values is currently not supported; they are always estimated as a part of the fitting process. Do you have a particular reason for wanting to keep them fixed?

Best,
Sergei

**Comment by biozhajie** [comment]
Dear @spond 

Thanks your reply very much! The reason I want fix the tree branch lengthes is I want to check effect of different branch lengthes on the values of the output parameters (e.g. k values, omega values). The re-estimated tree is quite different from the input tree, and the results (e.g. k distributions among the tree) through a standard analysis are qiute different from my expection which was guessed based on the character pattern of my input tree, so I want to try an anlysis fixing  the tree branch lengthes at the input values to check whether the results will become more similar to my expection. 

Best,
Jie

**Comment by biozhajie** [comment]
Dear @spond 

Can I fix  branch lengths at user supplied values through some modified set-up of analysis?

Best,
Jie

**Comment by spond** [comment]
Dear @biozhajie,

You could in principle. This could lead to poor and biased estimates of other model parameters if branch lengths are too far off. I'll see if I can adapt the analysis without too much code modification.

Best,
Sergei
