### ISSUE TITLE
Re-estimating Branch Lengths in HyPhy and using a BS-REL Model

### ISSUE THREAD

**Issue by amholtz** [veg/hyphy#1502]
Dear Dr. Pond (and others at HyPhy), 

I am currently working with a dataset of 300 whole genome viral sequences. For this dataset, I have reconstructed the phylogenetic tree, and I have previously dated the tree using a uncorrelated relaxed clock model. Since I am looking to find dates of emergence and to date specific nodes in the tree, I think it would be valuable to test for purifying selection and to see if there is an effect on dating. I see this done in the paper on Coronavirsuses (https://journals.asm.org/doi/10.1128/JVI.03273-12) and there have been several other examples. 

I have tried using HyPhy aBSREL for my dataset. It is my understanding that if there are branches that are under positive selection, then these branch lengths would be re-estimated. Once I have re-estimated branch lengths, I would then redate my tree using the same method I used previous (uncorrelated relaxed model). Are branch re-estimations automatic in aBSREL? 

Currently my issue is that when aBSREL finished for my dataset (14 hours), I had one output file, which shows the following for each node in my tree. 

```
"Baseline MG94xREV":0.004224998887986158,
"Baseline MG94xREV omega ratio":0.08030447738388263,
"Corrected P-value":0.03200485355368377,
"Full adaptive model":0.00154316813806515,
"LRT":16.9651662397664,
```

This is the terminal output at the end of the run:

```
### Adaptive branch site random effects likelihood test
Likelihood ratio test for episodic diversifying positive selection at Holm-Bonferroni corrected _p =   0.0500_ found **3** branches under selection among **461** tested.

* Tip48293, p-value =  0.00000
* Tip58402, p-value =  0.00265
* Node128, p-value =  0.03200
```

According to this tutorial, https://github.com/veg/hyphy-tutorials/tree/master/docs/selection, I should have multiple output files given. The run seems to finish successfully, but only one file is given as output. I'm not sure if I'm doing something wrong, or if there is an issue. I am running HyPhy in the command line (HYPHY 2.5.8(MP) for Darwin on x86_64\), which I installed through Conda. 

I would appreciate any guidance you could give on whether I am correct in my approaching using HyPhy aBSREL to reestimate branch lengths taking purification selection into account for dating, and whether my aBSREL output is expected functionality. 

Thank you very much for your time. 

Wishing you the best,
Andrew

**Comment by amholtz** [comment]
I see that I can upload the one output file to http://vision.hyphy.org/aBSREL#hyphy-model-fits, and it shows me the results from my run. This means that the one output file produced was the json file, and I can download the tree with re-estimated branch lengths there.

**Comment by spond** [comment]
Dear @amholtz,

The conda version of HyPhy is several years out of date (2.5.41 is the current version). I strongly encourage you to build the newest version from source (using CMake): speedups alone are worth it.

To address your question:

HyPhy **does** re-estimate the branch lengths under several models, and the current version of `aBSREL` produces more attributes per branch in the JSON file, e.g. 

```
     "COW":{
       "Baseline MG94xREV":0.2533379478418997,
       "Baseline MG94xREV omega ratio":1.961803558433491,
       "Corrected P-value":null,
       "Full adaptive model":0.3953030664704375,
       "Full adaptive model (non-synonymous subs/site)":0.3675416912722853,
       "Full adaptive model (synonymous subs/site)":0.02776137519815224,
       "LRT":null,
       "Nucleotide GTR":0.2481140922832967,
       "Rate Distributions":        [
[0, 0.5376584489599998],
        [10.41733126811686, 0.4623415510400002] 
        ],
       "Rate classes":2,
       "Uncorrected P-value":null,
       "original name":"COW"
      },

```

Branch lengths estimated by **three** different models are reported. You want the `Full adaptive model` or `Full adaptive model (synonymous subs/site)`

- `Nucleotide GTR` :  the branch length estimated under the nucleotide GTR model (initial fit phase)
- `Baseline MG94xREV` :  the branch length estimated under the codon MG94xREV model with one dN/dS per branch (second fit phase)
- `Full adaptive model` :  the branch length estimated under the full adaptive model, i.e. potentially multiple dN/dS classes per branch.  This is further split into synonymous and synonymous components. 

You can use https://observablehq.com/@spond/displaying-absrel-results-using-branch-censoring to load your JSON result files, view trees, and export Newick strings.

Best,
Sergei

**Comment by amholtz** [comment]
Thank you Sergei. This is really useful and very good to know that the conda version is outdated. I have now redone this and uploaded my data using observablehq. I can visualize the trees now very well, but I an unable to download the newick files. I can see that I can copy the newick from the text box above the trees. This, however, does not update when I choose a different model. The tree visualization changes, but the text box with the newick text does not change (see attached images). Is there another way to get the newick file from the json? I also tried using http://vision.hyphy.org/, but the adaptive model tree does not seem to show the branch lengths correctly (see attached image). Thank you again for your time and your help. Best, Andrew

![image](https://user-images.githubusercontent.com/17280223/183446726-34418df7-15c3-411d-8273-8a75a9230d14.png)

![image](https://user-images.githubusercontent.com/17280223/183446826-16b8da8e-c64b-4037-8972-d12ada25ccb7.png)

![image](https://user-images.githubusercontent.com/17280223/183446955-f2dad400-29a7-4b45-b792-86201cfaddff.png)

**Comment by spond** [comment]
Dear @amholtz,

I made an adjustment to the Observable notebook to update branch lengths based on the selected model.

Best,
Sergei

**Comment by amholtz** [comment]
Great, works now. Thank you!
