### ISSUE TITLE
Selecting branches command line

### ISSUE THREAD

**Issue by ayssel-uct** [veg/hyphy#1505]
Hi,

I would like to run FUBAR on a dataset of nucleotide sequences (HIV, Env, from two timepoints). How do I select background and foreground branches if I run hyphy on the command line?

Greets
AY

**Comment by spond** [comment]
Dear @ayssel-uct,

FUBAR does not support partitioning data into branch sets. Most other analyses (FEL, MEME etc), do. See http://hyphy.org/tutorials/phylotree/ for how to prepare the phylogenies with labels.

Best,
Sergei
