### ISSUE TITLE
Can not find P-value in FUBAR results on website (http://www.datamonkey.org/)

### ISSUE THREAD

**Issue by YuantingGuo** [veg/hyphy#1506]
Dear hyphy developers,
I have a question when I used the FUBAR on website (http://www.datamonkey.org/). The results on website indicates that "pervasive positive/diversifying selection at 185 sites ", then I download the FUBAR Site Table, but I can not find the P value in table. So I do not know which are  positively selective sites.
Thank you for your time
Yuanting

**Comment by stephenshank** [comment]
Dear @YuantingGuo,

FUBAR uses a posterior probability threshold. This can be accessed through the results page by sorting on Prob[α<β] in the following manner, which was done by clicking the column headers to sort. I believe you'll want that column in the corresponding table.

Regards,
Stephen
![image](https://user-images.githubusercontent.com/8673708/184208206-9e518425-2798-46ae-821f-a0a225b83a48.png)

**Comment by YuantingGuo** [comment]
Thanks your reply very much! 
Best,
Yuanting
