### ISSUE TITLE
selection density with RELAX

### ISSUE THREAD

**Issue by XiaoliChenSD** [veg/hyphy#1507]
Dear @spond,

I am performing a project about parasites, and now I have free-living organism, hemi-parasites, and holo-parasites, we found large scale gene loss (about 30%-40% gene families are lost), reduced redundancy, and high nucleotide substitution in holo-parasites. We hypothesized that the genes in parasites are ongoing relaxed selection. We first analyzed the selection pressure with CODEML using the branch model, we found few positive selection genes in parasites, small proportion of relaxed selection in holo-parasites (133/2710), and moderate of relaxed selection density in hemi-parasites (799/2710). 

Then we tried to identify the selection density with RELAX, we use all the parasites as test, and free-living organisms as reference, the command was set as below. 
hyphy relax CPU=1 --code Universal --alignment OG0000574_1.Group1.nex --output ./ --test TEST --reference REF --models All

Tree file: (((((((((ATH{REF},GRA{REF}),(SHIM{TEST},PTRI{REF})),(MTR{REF},CSA{REF})),KFE{REF}),VVI{REF}),((BSU{TEST},BSP{TEST}),(SPA{REF},SAL{REF}))),(((((CAU{TEST},INI{REF}),CCA{REF}),(SASI{TEST},MGUT{REF})),HAN{REF}),BVU{REF})),NNU{REF}),ACO{REF})

We tried to get the k (general descriptive) value for each species, about 60%-89% for the k value of different species are less than 1, We are wondering why such large number of genes are evaluated as relaxed selected whatever in free-living or parasites. Is it reasonable to set the command like this, and could you please give me some suggestion on how to interpret the results?

Thanks,
Xiaoli

**Comment by spond** [comment]
Dear @XiaoliChenSD,

General descriptive `k` is somewhat difficult to interpret because the **reference** is not always clearly defined. You can renormalize these `k` (e.g. to have geometric mean on 1), or determine which branch/branches have k~1 to identify your reference. You can almost view these `k` as pairwise branch comparisons: if `k` for branch 1 is greater than `k` for branch 2, then branch 1 is in some sense INTENSIFIED relative to branch 2.

For your purposes, I would label the three groups of branches : free living, hemi- and holo- parasites, define free living as the reference and run a group mode test, where a separate (group level) `K` is estimates for each non-reference group. The command would look something like 

```

hyphy relax --alignment {input.alignment}  --code Universal--mode 'Group mode' --reference-group FREE --srv Yes --starting-points 5

```

For tree labeling, take a look at https://github.com/veg/hyphy-analyses/tree/master/LabelTrees

Best,
Sergei

**Comment by spond** [comment]
Dear @XiaoliChenSD,

`--starting-point N` simply tells HyPhy to do `N` crude optimizations to find a good starting point for the actual model optimization. It helps avoid local maxima and improves method convergence. You can use values of `N` larger than 5, it's just a question of adding more compute time.

Best,
Sergei

**Comment by XiaoliChenSD** [comment]
Dear Sergei,

Thank you so much for your detailed information.  I ran the analysis as you suggested like this:

hyphy relax --alignment {input.alignment}  --code Universal--mode 'Group mode' --reference- FREE --srv Yes --starting-points 5

When I got the results, I noticed that there is only one LRT value and one p-value, did the p-value show whether (HEMI+HOLO) and FREE are significantly different from each other? 

 "test results":{
   "LRT":1.127693764399737,
   "p-value":0.5690159109512838,
   "relaxation or intensification parameter":{
     "FREE":1,
     "HEMI":1.104037912517345,
     "HOLO":0.944261696393257

**Comment by Huangtianyu-caas** [comment]
> Dear Sergei,
> 
> Thank you so much for your reply. So do you mean that general descriptive k could be interpreted as a relative value? I am planning to get a figure like this, with the mean general descriptive k for all orthologs of each species, to show the relax or intense selection density on a phylogenetic tree. Is that OK? ![image](https://user-images.githubusercontent.com/111113428/186129321-8413f953-000a-412e-8409-34ee5617887d.png)
> 
> I am also trying to redo the analysis with the group mode as you suggested, could you please tell me what the parameter of starting points mean? why should I use 5? Thank again for your kind help.

Dear Xiaoli,

May I ask how can I produce a phylogeny with gradient color informing different selection pressure?
Which software should I use?

Thank you for your help!
Best,
Tianyu Huang

**Comment by Huangtianyu-caas** [comment]
Dear @XiaoliChenSD 

May I ask how can I produce a phylogeny tree with gradient color informing different selection pressures, like the one you presented?
Which software can I use to do it?

Thank you very much!
Best,

**Comment by XiaoliChenSD** [comment]
> Dear @XiaoliChenSD
> 
> May I ask how can I produce a phylogeny tree with gradient color informing different selection pressures, like the one you presented? Which software can I use to do it?
> 
> Thank you very much! Best,

Hi, you can use this link to produce a tree with k value.
https://observablehq.com/@spond/plotting-relax-k-values-on-branches-of-the-tree
