### ISSUE TITLE
EBF table in MEME

### ISSUE THREAD

**Issue by khoojj** [veg/hyphy#1512]
Hi,

I have ran MEME on HYPHY version 2.5.41(MP). After loading into Hyphy Vision, the EBF table is empty. I also don't see anything related to EBF in the .json output.

I used the prompts to key in my alignment and tree files, the rest were default values (The only items I could input were alignment and tree files)
Have I missed something in the analyses?

Thanks.

**Comment by spond** [comment]
Dear @khoojj,

2.5.41 has an updated MEME analysis which is not fully backwards compatible with the current HyPhy vision page. Please use https://observablehq.com/@spond/meme to visualize its results.

Best,
Sergei

**Comment by spond** [comment]
Dear @khoojj,

Versions 2.5.39 and earlier, I believe.

Best,
Sergei

**Comment by khoojj** [comment]
Got it thank you.
I have another question on the EBF threshold slider from 0 to 10 in HyPhy
Vision, what does this range of number represent?
The EBF values I received from MEME output are a lot more than 10 (with
some over 100000!)
If I set the slider to 10, does it mean that branches/nodes with EBF > 10
at a particular site will be highlighted?
