### ISSUE TITLE
RELAX exiting with "Internal error in _LikelihoodFunction::ConjugateGradientDescent."

### ISSUE THREAD

**Issue by awalling** [veg/hyphy#1514]
Hello,

I am running the RELAX algorithm using HYPHY HYPHY 2.5.8(MP) for Darwin on x86_64, installed with conda, on a set of 25 alignments/trees. About half of the runs are exiting with the following status:

`### Fitting the general descriptive (separate k per branch) model
Error:
Internal error 
Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-9267.630444432387] does not match the last recorded LF maximum [-9252.871211674597]

Function call stack
1 :  [namespace = __QsXKaV] Optimize(mles, ^lf_id);

-------
2 :  relax.general_descriptive.fit=estimators.FitExistingLF(relax.general_descriptive.fit[terms.likelihood_function],relax.model_object_map);
-------

Check errors.log for execution error details.
`

I attach a representative alignment/tree/error log:
[chlorophyllide_a_reductase_iron_protein_subunit_X.edited.tre.txt](https://github.com/veg/hyphy/files/9455615/chlorophyllide_a_reductase_iron_protein_subunit_X.edited.tre.txt)
[chlorophyllide_a_reductase_iron_protein_subunit_X.fa.txt](https://github.com/veg/hyphy/files/9455626/chlorophyllide_a_reductase_iron_protein_subunit_X.fa.txt)
[errors.log](https://github.com/veg/hyphy/files/9455632/errors.log)

I updated the conda installation of Hyphy today in case that was causing the error, but am still unable to run RELAX without error on about half of my dataset.

**Comment by spond** [comment]
Dear @awalling,

Version 2.5.8 is several years old by now (it seems to be the version on Conda; I'll see if we can update it); many of the changes since that version have been made to address issues like what you have reported here (convergence / optimizer issues).

Would you mind updating to the current version and seeing if this resolves the problem?

Best,
Sergei
