### ISSUE TITLE
Jobs i Queue

### ISSUE THREAD

**Issue by Leki-10** [veg/hyphy#1515]
Hi Sergei,

The job queue seems to have stuck today. Please can the queue be cleared for new runs if possible?

Thanks for your help & time in advance.

Best wishes,
Leki

**Comment by stevenweaver** [comment]
Dear @Leki-10, 

I've cleared the stuck GARD jobs from the past couple of days (they will timeout after 3 days, regardless), and will be monitoring the queue closely throughout the day to ensure it is progressing.

Best,
Steven

**Comment by Leki-10** [comment]
> Dear @Leki-10,
> 
> I've cleared the stuck GARD jobs from the past couple of days (they will timeout after 3 days, regardless), and will be monitoring the queue closely throughout the day to ensure it is progressing.
> 
> Best, Steven

Hi Steven,

Thanks a lot for helping out! Yes, it runs now.

Best regards,
Leki
