### ISSUE TITLE
Errors for all new jobs today

### ISSUE THREAD

**Issue by davidgafl** [veg/hyphy#1516]
Hi,

There is an issue today about launching new analysis with RELAX and BUSTED. (Didn't try the others).
All jobs are aborted with this message : We're sorry, there was an error processing your job. Please try again, or visit
[our GitHub issues page](http://github.com/veg/hyphy/issues/)
and create an issue if the issue persists.
I am using the same files as yesterday when it worked perfectly.
Could please you solve the problem?

Thanks a lot in advance,
David

**Comment by stevenweaver** [comment]
Dear all, 

Yes, the job provisioning processes on our cluster has mysteriously been terminated the past two early mornings (ET). Keeping this issue open until I discover the root of the problem. 

In the meantime, I've restarted the processes and jobs should be running again.

Best,
Steven

**Comment by davidgafl** [comment]
thanks a lot Steven,
Best,
David
