### ISSUE TITLE
Foreground vs background in BUSTED

### ISSUE THREAD

**Issue by katherine-li07** [veg/hyphy#1518]
Hello! 

I have a question about BUSTED that I am hoping you can help with.

My dataset is a population of SARS-CoV-2 viruses that has been aligned to the original Wuhan reference sequence and trimmed to the individual genes.
 
When running BUSTED, would it be correct to set the Wuhan reference sequence as background while leaving the rest of the dataset as foreground branches for testing? I am unsure whether setting the reference sequence as background means it is completely ignored (and testing only involves the foreground), or whether it means that selection is determined for the foreground branches relative to the background.
 
Alternatively, would it be more appropriate to select the entire dataset as foreground and not specify any background branches if my potential background (the Wuhan reference) is only a single sequence?

Thank you!

**Comment by spond** [comment]
Dear @katherine-li07,

My standard recommendation here (viral isolates, where one sequence = one patient) is to run BUSTED on *internal* branches only (from https://pubmed.ncbi.nlm.nih.gov/26814962/) 

<img width="923" alt="image" src="https://user-images.githubusercontent.com/1018513/190249966-c3ad4bac-59df-44d2-a015-adfa768a4baa.png">

Also, one sequence should not affect such an analysis in most cases, and, anyway, excluding all terminal branches will also exclude the Wu-1 reference. 

Hope this helps,
Sergei

**Comment by katherine-li07** [comment]
Great, thank you for your help!

**Comment by spond** [comment]
Dear @katherine-li07,

Happy to help. Let me know how it goes. For SC-2 data, you should also remove all identical sequences (HyPhy will warn you if you have those), because they will make the analysis to run slower and not contribute any signal to the test.

See https://github.com/veg/hyphy-analyses/tree/master/remove-duplicates

Best,
Sergei

**Comment by katherine-li07** [comment]
Thank you Steven and Sergei for your help. 

I am also wondering how BUSTED results relate to FUBAR results. I understand that FUBAR reports positive and negative selection at individual sites, whereas BUSTED reports positive selection across an entire gene, but should these results generally mimic each other for where selection is reported?

For example, I have run the same files through both BUSTED and FUBAR, and in some cases FUBAR reported multiple sites under positive selection, but BUSTED did not detect selection for the gene.

In this case, I am wondering if it is appropriate to compare the results of these two tools, or if I should be sticking to one over the other.

Thank you!
Katherine
