### ISSUE TITLE
How does BUSTED work? 

### ISSUE THREAD

**Issue by gykoh** [veg/hyphy#1522]
Hello!

I ran almost 2 identical runs with my dataset on BUSTED (version is HYPHY 2.5.39 (MP) for Darwin on x86_64). There are no zero-length branches in my dataset. The only setting I changed was the number of omega rate classes to include in the model. The first run was at the default setting 3, while the second run was at 4.

Below is the output I received from the terminal through the settings:

Settings For 1st Run:

Types of standard analyses: (1) selection analyses
Files in Selection Analyses: (5) BUSTED
Choose genetic code: (1) [Universal]
Choose set of branches for selection: [‘ALL’]
Synonymous rate variation: 1. [**Yes**]
The number of omega rate classes to include in the model: 3
Include support for multiple nucleotide substitutions: 3. [**None**]
The number of synonymous rate classes to include in the model: 3
The number of points in the initial distributional guess for likelihood fitting: 250
The number of initial random guesses to ‘seed’ rate values optimization: 1
Reduce zero-length branches: 1. [**No**]

Output From 1st Run:

* Log(L) = -5946.37, AIC-c = 12058.18 (82 estimated parameters)
* For *test* branches, the following rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.387     |   52.227    |                                   |
|         Neutral evolution         |     1.000     |   13.561    |                                   |
|      Diversifying selection       |     2.131     |   34.212    |                                   |

* The following rate distribution for site-to-site **synonymous** rate variation was inferred

|               Rate                | Proportion, % |               Notes               |
|-----------------------------------|---------------|-----------------------------------|
|               0.000               |     2.623     |                                   |
|               0.657               |    71.535     |                                   |
|               2.050               |    25.841     |                                   |

### Performing the constrained (dN/dS > 1 not allowed) model fit
* Log(L) = -5948.82, AIC-c = 12299.97 (197 estimated parameters)
* For *test* branches under the null (no dN/dS > 1 model), the following rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |    6.665    |                                   |
|         Neutral evolution         |     1.000     |   75.120    |                                   |
|         Neutral evolution         |     1.000     |   18.216    |       Collapsed rate class        |

* The following rate distribution for site-to-site **synonymous** rate variation was inferred

|               Rate                | Proportion, % |               Notes               |
|-----------------------------------|---------------|-----------------------------------|
|               0.018               |     3.136     |                                   |
|               0.670               |    71.428     |                                   |
|               2.047               |    25.436     |                                   |

----
## Branch-site unrestricted statistical test of episodic diversification [BUSTED]
Likelihood ratio test for episodic diversifying positive selection, **p =   0.0431**.

Settings For 2nd Run:

Types of standard analyses: (1) selection analyses
Files in Selection Analyses: (5) BUSTED
Choose genetic code: (1) [Universal]
Choose set of branches for selection: [‘ALL’]
Synonymous rate variation: 1. [**Yes**]
The number of omega rate classes to include in the model: 4
Include support for multiple nucleotide substitutions: 3. [**None**]
The number of synonymous rate classes to include in the model: 3
The number of points in the initial distributional guess for likelihood fitting: 250
The number of initial random guesses to ‘seed’ rate values optimization: 1
Reduce zero-length branches: 1. [**No**]

Output From 2nd Run:
* Log(L) = -5990.20, AIC-c = 12149.91 (84 estimated parameters)
* For *test* branches, the following rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |    0.266    |                                   |
|        Negative selection         |     0.520     |   10.859    |                                   |
|        Negative selection         |     0.666     |   78.684    |                                   |
|      Diversifying selection       |     5.538     |   10.191    |                                   |

* The following rate distribution for site-to-site **synonymous** rate variation was inferred

|               Rate                | Proportion, % |               Notes               |
|-----------------------------------|---------------|-----------------------------------|
|               0.557               |    99.713     |                                   |
|              83.679               |     0.242     |                                   |
|              536.604              |     0.045     |                                   |

### Performing the constrained (dN/dS > 1 not allowed) model fit
* Log(L) = -5998.74, AIC-c = 12525.72 (257 estimated parameters)
* For *test* branches under the null (no dN/dS > 1 model), the following rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |    9.899    |                                   |
|         Neutral evolution         |     1.000     |    8.390    |                                   |
|         Neutral evolution         |     1.000     |   69.536    |       Collapsed rate class        |
|         Neutral evolution         |     1.000     |   12.175    |       Collapsed rate class        |

* The following rate distribution for site-to-site **synonymous** rate variation was inferred

|               Rate                | Proportion, % |               Notes               |
|-----------------------------------|---------------|-----------------------------------|
|               0.775               |    99.856     |                                   |
|              125.463              |     0.128     |                                   |
|              417.096              |     0.016     |                                   |

----
## Branch-site unrestricted statistical test of episodic diversification [BUSTED]
Likelihood ratio test for episodic diversifying positive selection, **p =   0.0001**.

Questions:

1) When comparing the two runs, why do I get changes in synonymous rates when the change was in the number of omega rate classes (not related to synonymous rates)?

2) For the 2nd run, why are there rates of about 125 and 417 in the table showing the rate distribution for site-to-site synonymous rate variation? Are these values reliable? What do these values mean? (This is related to the first question).

I have searched for this in the literature but was unable to find this specific topic addressed. Any literature recommendations are welcome! 

3) How does BUSTED deal with collapsed rate classes? How does this affect the comparison between the two models? 

Thank you!

**Comment by spond** [comment]
Dear @gykoh,

1). In principle, every model parameter has the potential to influence any other model parameter. This is especially true of synonymous rates and &omega; ratios. For example [we showed](https://pubmed.ncbi.nlm.nih.gov/32068869/) that there is a big difference in &omega; rates when you have 1 or more than one synonymous rates. 

In your specific case, there seems to be a convergence issue (I would suggest re-running `BUSTED` with `--grid-size 1000 --starting-points 10` command line argument to request that HyPhy do more work up front to try to improve point estimates). How do I know that there is a convergence problem?

Well, when you have **4** &omega; rate classes (run 2), you are **adding** two extra model parameters compared to **3** rate classes (in run 1), yet your log likelihood gets **worse** (-5990.20 vs -5946.37).

2). Point estimates should not be viewed as particularly reliable in any case **without** any quantification of uncertainty. The only result that is confirmed for evidence of statistical significance by BUSTED is the p-value for positive selection. Generally, for rate estimates, the higher the estimate, the wider the error bounds are (variance goes up with the mean). 

3). `Collapsed rate classes` are an indication of model overfitting -- the data don't support more than two classes in this case. HyPhy doesn't do anything special to deal with them, it's just that they don't provide any additional benefit, and incur a computational cost. This is reported as a diagnostic. 

Best,
Sergei

**Comment by gykoh** [comment]
Dear @spond 

Thank you again for your prompt response and for answering my questions!
