### ISSUE TITLE
Dealing with reference genome length not divisible by 3

### ISSUE THREAD

**Issue by ufuomababatunde** [veg/hyphy#1524]
Hello.

I would like to ask what to do with the `pre-msa.bf` step.
I used the SARS-CoV-2 reference genome with 29,903 bp but got an error related to its genome length.

Thank you.

**Comment by spond** [comment]
Dear @ufuomababatunde,

`pre-msa.bf` is meant to work on a gene-by-gene (not a genome level). This implies that the reference sequence must be an in-frame ORF. You could, for example, supply the reference sequence for the `S` gene or the `RdRp` gene etc. 

Similarly, if you wanted to run a codon-based analysis in HyPhy you would **not** run in on the entire genome, consisting of multiple genes, non-coding spacers, and slippage sites. You would select individual genes and apply the analyses to them.

Hope this makes sense.

Best,
Sergei

**Comment by ufuomababatunde** [comment]
Thank you for the clarification. Now it makes sense.

**Comment by singing-scientist** [comment]
Greetings @spond ! I have a related question. Suppose I have a virus alignment that I have determined is not subject to recombination, and I want to use MEME. I would therefore like to build a tree on my full dataset using whole genomes (4500 unique genome sequences, 8000bp each, 9 ORFs). May I ask the recommended strategy for going about this? My guess:

1. build a whole-genome tree using full set of unique genomes (e.g., using raxml-ng)
2. 'slice' each ORF out of the alignment based on its start and end positions. (some slices will now be non-unique, but it's not something to worry about?)
3. run MEME separately for each gene that has been sliced out, using the same (whole-genome based) tree for each run

I'd be grateful to know if this makes sense, or if there is a cleaner/more standard way to use HyPhy for such an application. Finally, related,

4. do you have any general guidelines on how many cores to use? My alignment has ~2/3 invariant sites with approximate π=0.01

Thanks so much for your help!
Chase
