### ISSUE TITLE
Instant error on all jobs

### ISSUE THREAD

**Issue by eibnerg** [veg/hyphy#1526]
Hi DM Team,

Thanks a lot for your helpful services. 
However, I cant start any analysis without getting an immediate error. The corresponding log is always empty.
I was succesful in the past with the exact same input files.

Best,
Georg

**Comment by stephenshank** [comment]
Dear @eibnerg,

It looks like we had a database failure over the weekend. I've restarted it and was able to [submit a FEL job](https://datamonkey.org/fel/63319f9393ca9c31cdc3eb45).

Can you please try again and let me know if you encounter any issues?

Regards,
Stephen

**Comment by eibnerg** [comment]
Hi Stephen,

awesome, that seems to have done the job. At least MEME appears to be running again!
Thanks a lot!

Cheers,
Georg

**Comment by stephenshank** [comment]
Glad to hear! Feel free to reopen if you feel that this issue persists.
