### ISSUE TITLE
Update 2.1 distribution wiki pages etc

### ISSUE THREAD

**Issue by spond** [veg/hyphy#153]
We need to make sure that 
1. The wiki states somewhere that we are currently working on v3 (maybe have a way for the users to provide suggestions)
2. All the documentation we reference in the distributions is available
3. The last 2.1 branches have test datasets and batch files included with instructions (on the download page) on how to use them

**Comment by stevenweaver** [comment]
I'm going to close this issue and focus on v2.3 and the new site.
