### ISSUE TITLE
aBSREL run error

### ISSUE THREAD

**Issue by luisasegovia** [veg/hyphy#1532]
Hi there! I keep getting this error pop up when I run aBSREL with my data set. This is the error message I have been getting every time I run aBSREL.  I only have this issue with this data set so I am not sure what I can do to avoid this message. I am using a partition data set I got from GARD. Thank you.

MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.
NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[n7:41321] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:41321] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:41321] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:41321] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:41321] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:41321] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n7:41321] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

**Comment by stevenweaver** [comment]
Dear @luisasegovia, 

Does this error occur when using hyphy on Datamonkey or on your server?

Best,
Steven

**Comment by luisasegovia** [comment]
Hi. It occurs when I use hyphy on datamonkey.

**Comment by spond** [comment]
Dear @luisasegovia,

Could you share your Datamonkey URL here?

Best,
Sergei

**Comment by luisasegovia** [comment]
Yup. Here's the link: http://datamonkey.org/absrel/63472b6835d8215fcb2fd88c

**Comment by spond** [comment]
Dear @luisasegovia,

Thank you. Let me take a quick look...

Best,
Sergei

**Comment by luisasegovia** [comment]
Thank you for your help!

**Comment by spond** [comment]
Dear @luisasegovia,

Doh, I am not thinking clearly today. Looking at the logs, I see

```
Master node received an error:aBSREL only works on a single partition dataset in call to assert(utility.Array1D(absrel.partitions_and_trees)==1, error_msg);

Function call stack
1 :  assert(utility.Array1D(absrel.partitions_and_trees)==1, error_msg);
-------
2 :  ExecuteCommands("assert (`statement`, error_msg)", /home/datamonkey/datamonkey-js-server/production/app/absrel/../../.hyphy/res/TemplateBatchFiles/libv3/);
-------
3 :  io.CheckAssertion("utility.Array1D (absrel.partitions_and_trees) == 1","aBSREL only works on a single partition dataset");
-------
```

`aBSREL` does not support multiple partition datasets (because the set of branches has to be the same for all sites). Datamonkey does not report this particularly error to you. I would suggest partitioning your data into individual non-recombinant fragments and then running `aBSREL`

Many other analyses (BUSTED, FEL, MEME) **do** support multiple partitions, though.

Best,
Sergei

**Comment by stevenweaver** [comment]
The logging issue has been open issue for quite some time. Linking veg/datamonkey-js#197 to increase awareness.

**Comment by luisasegovia** [comment]
Whoops sorry! I'll close it right away

**Comment by akarimizade** [comment]
Hi! I also have the issue with the same error.
https://www.datamonkey.org/absrel/63ca6712c82f520f6a311bc3
MEME test worked properly, but when I use aBSREL, it gives me an error.
