### ISSUE TITLE
how to calculate the dN/dS for a orthologus gene family ?

### ISSUE THREAD

**Issue by yayahoho1** [veg/hyphy#1536]
Hi,
    I'm pretty new to hyphy and need some help from you. I have 10 bacterial genomes and got 1000 single-copy orthologus gene families by orthofinder. Now I want to calcaulate the dN/dS for a orthologus gene family by hyphy. 
However, I was wondering if
   (1) which method of hyphy I should take ? 
   (2) about tree file,  gene tree of a orthologus gene famliy or species tree(by using the concatenation of all single-copy orthologus gene families ) , which one is better?

 Thanks
 Yilin

**Comment by spond** [comment]
Dear @yayahoho1,

We have written several [tutorials](http://hyphy.org/resources/tutorial-2017.pdf) that you could look at to decide what is the best approach to take. Generally, calculating an average dN/dS per gene is not useful, unless your data are of exceptionally low divergence. As a default analysis to estimate the distribution of dN/dS across sites and branches, I would recommend our `busted` method.

Best,
Sergei
