### ISSUE TITLE
aBSREL output empty

### ISSUE THREAD

**Issue by psorigue** [veg/hyphy#1537]
Hi all,

I run several aBSREL jobs. All of them seem to have run normally, but when I load them in vision.hyphy.org the following messsage appears: "Something went wrong when rendering the results page".

The JSON files are not empty, and no error appeared during their run.

What could I have done wrong? I use the same alignment and tree files for other methods and they show the results as normal.

Thanks a lot

**Comment by stephenshank** [comment]
Dear @psorigue,

Can you please share the JSON file, either through Github or email? This will help us troubleshoot your issue.

Regards,
Stephen

**Comment by psorigue** [comment]
Dear Stephen,

Here I share a couple. Thanks a lot for your help.

Best,
Pol Sorigué
Pol

Missatge de Stephen Shank ***@***.***> del dia dc., 26 d’oct.
2022 a les 14:05:
