### ISSUE TITLE
Cannot install hyphy-develop / hyphy-analyses

### ISSUE THREAD

**Issue by hayleyjaywilson** [veg/hyphy#1538]
Same issue as [Issue with hyphy-analyses install](https://github.com/veg/hyphy/issues/1293#top)
#1293 but the advice is not solving the problem.

Hello, I have been trying to get Hyphy slac to work with my dataset for a while now. I converted to proteins and then back to a codon alignment using goalign codonalign but have the error saying the alignment is not divisible by 3. So I am trying to use the pre-msa.bf script instead. I follow the instructions here:

git clone https://github.com/veg/hyphy.git hyphy-develop
cd hyphy-develop
git checkout develop
cmake ./
make -j MP
./HYPHYMP analysis-file --help

and get the error:

./HYPHYMP analysis-file --help
Error:
Could not read batch file '/rds/user/hjw58/hpc-work/dn_ds/hyphy-develop/analysis-file'.
Path stack:
	/rds/user/hjw58/hpc-work/dn_ds/hyphy-develop/res/
	/rds/user/hjw58/hpc-work/dn_ds/hyphy-develop/

Which was suggested to be solved by adding a target directory to the end of the command

git clone https://github.com/veg/hyphy.git hyphy-develop

However when I try that:

git clone https://github.com/veg/hyphy.git hyphy-develop /home/hjw58/rds/hpc-work/dn_ds

I get this error:
fatal: Too many arguments.

followed by the useage guidelines.

Just doing this:

git clone https://github.com/veg/hyphy.git hyphy-develop
cd hyphy-develop
git checkout develop
cmake ./
make -j MP

Completes but in the process I see that one aspect is failing:
 
git clone https://github.com/veg/hyphy.git hyphy-develop
Cloning into 'hyphy-develop'...
remote: Enumerating objects: 32824, done.
remote: Counting objects: 100% (1432/1432), done.
remote: Compressing objects: 100% (411/411), done.
remote: Total 32824 (delta 1019), reused 1327 (delta 979), pack-reused 31392
Receiving objects: 100% (32824/32824), 57.17 MiB | 20.33 MiB/s, done.
Resolving deltas: 100% (24279/24279), done.
Updating files: 100% (917/917), done.
(hpc_cam) [hjw58@login-q-2 dn_ds]$ cd hyphy-develop
(hpc_cam) [hjw58@login-q-2 hyphy-develop]$ git checkout develop
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
Switched to a new branch 'develop'
(hpc_cam) [hjw58@login-q-2 hyphy-develop]$ cmake ./
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_AVX_EXTENSIONS
-- Performing Test HAVE_AVX_EXTENSIONS - Success
-- Performing Test HAVE_FMA3
-- Performing Test HAVE_FMA3 - Success
-- Performing Test HAVE_NEON_EXTENSIONS
-- Performing Test HAVE_NEON_EXTENSIONS - Failed
Set default compiler flags to -fsigned-char -O3 -std=c++14 -march=native -mtune=native -mavx  -mfma
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found CURL: /usr/lib64/libcurl.so (found version "7.61.1")
/usr/lib64/libcurl.so
-- Found ZLIB: /usr/lib64/libz.so (found suitable version "1.2.11", minimum required is "1.2.9")
-- Found MPI_C: /usr/local/software/spack/spack-views/._rocky8-icelake-20220710/ckngsmwknsbdd57po22aw663ckmnmqf4/intel-oneapi-mpi-2021.6.0/intel-2021.6.0/guxuvcpmykplbrr2e3af2yd7njqhau5e/mpi/2021.6.0/lib/release/libmpi.so (found version "3.1")
-- Found MPI_CXX: /usr/local/software/spack/spack-views/._rocky8-icelake-20220710/ckngsmwknsbdd57po22aw663ckmnmqf4/intel-oneapi-mpi-2021.6.0/intel-2021.6.0/guxuvcpmykplbrr2e3af2yd7njqhau5e/mpi/2021.6.0/lib/libmpicxx.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-fsigned-char -O3 -std=c++14 -march=native -mtune=native -mavx  -mfma   -Xlinker --enable-new-dtags -Xlinker -rpath -Xlinker "/usr/local/software/spack/spack-views/rocky8-icelake-20220710/intel-oneapi-mpi-2021.6.0/intel-2021.6.0/guxuvcpmykplbrr2e3af2yd7njqhau5e/mpi/2021.6.0/lib/release" -Xlinker -rpath -Xlinker "/usr/local/software/spack/spack-views/rocky8-icelake-20220710/intel-oneapi-mpi-2021.6.0/intel-2021.6.0/guxuvcpmykplbrr2e3af2yd7nj
qhau5e/mpi/2021.6.0/lib" -Xlinker --enable-new-dtags -fopenmp
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hjw58/rds/hpc-work/dn_ds/hyphy-develop

I cannot use ./HYPHYMP analysis-file --help and change analysis-file to anything else as there are only the following files in the hyphy-develop directory
<img width="1115" alt="Screenshot 2022-10-31 at 12 12 14" src="https://user-images.githubusercontent.com/82043774/199005263-30717ae2-9375-47ba-a062-656b05519412.png">

Therefore I cannot see any of the files such as pre-msa.bf
Please could someone advise?

**Comment by spond** [comment]
Dear @hayleyjaywilson,

I think the source of confusion here is that you `pre-msa` is a part of a separate HyPhy analysis directory. Once you have installed `HyPhy` as shown above you should do the following to install HyPhy analyses from `hyphy-analysess`

```
$cd /home/hjw58/rds/hpc-work/dn_ds/
$git clone https://github.com/veg/hyphy-analyses.git hyphy-analyse
$cd hyphy-develop 
$./hyphy  /home/hjw58/rds/hpc-work/dn_ds/hyphy-analyses/codon-msa/pre-msa.bf --help
```

In other words, once you have installed an analysis (`.bf` file), you can ask `HyPhy` to run it by providing a file path to the analysis file.

Best,
Sergei
