### ISSUE TITLE
Can not run GARD results

### ISSUE THREAD

**Issue by VeterinaryLi** [veg/hyphy#1539]
Error:

Could not read batch file '/home/lg/miniconda3/lib/hyphy/TemplateBatchFiles/GARDProcessor.bf'.

Path stack:

	/home/lg/miniconda3/lib/hyphy/

	/home/lg/miniconda3/lib/hyphy/TemplateBatchFiles/

I found the software which lack the file of GARDProcessor.bf

**Comment by spond** [comment]
Dear @VeterinaryLi,

`GARDProcessor.bf` has been deprecated for some time. The `gard` analysis generates JSON files which can be viewed directly in vision.hyphy.org/GARD or processed otherwise.

Can you clarify what are you trying to do?

Best,
Sergei

**Comment by VeterinaryLi** [comment]
Dear Sergei;
I want to know the KH value of the reconbination sites.
Could you tell me how to do?
Best
Gen Li



---- Replied Message ----
| From | Sergei ***@***.***> |
| Date | 11/04/2022 03:42 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [veg/hyphy] Can not run GARD results (Issue #1539) |

Dear @VeterinaryLi,

GARDProcessor.bf has been deprecated for some time. The gard analysis generates JSON files which can be viewed directly in vision.hyphy.org/GARD or processed otherwise.

Can you clarify what are you trying to do?

Best,
Sergei

**Comment by spond** [comment]
Dear @VeterinaryLi,

This functionality is currently missing; I will see if I can port the old processor into a standalone analysis. Will keep the issue open for now. In the meantime, you can run KH/SH tests on different partitions using `raxml` or `IQTree`.

Best,
Sergei
