### ISSUE TITLE
aBSREL: when to select 'Leaves' versus 'All'

### ISSUE THREAD

**Issue by Emilyaoc** [veg/hyphy#1541]
Hello! 

Is it possible to get some help with understanding when to opt for testing all branches versus leave only when running aBSREL? 

If the scenario is that you do not have an a priori prediction over which branches have experienced selection (exploratory), but are primarily interested only in the leaves (in my case the leaves are an immune gene sequence for different species), then is it better to select the 'Leaves' option? Does this increase the power at all as selection on fewer branches are being estmiated (if I understand correctly)?  

I am runninng this on the command line, so my code would be:

1) testing only leaves (i.e. the tips):
hyphy absrel --alignment input.fasta --tree my_tree --branches Leaves

OR
2) the default of testing everything (i.e. internal nodes & leaves):
hyphy absrel --alignment input.fasta --tree my_tree 

Thank you for any help you can offer.

**Comment by spond** [comment]
Dear @Emilyaoc,

Option (1) is correct above for testing only Leaves. And you are also correct that this option will improve power of the test, since multiple testing correction will have to be done for **fewer** tests.

Best,
Sergei
