### ISSUE TITLE
Decoding internal branches from RELAX's JSON output

### ISSUE THREAD

**Issue by mchaney1** [veg/hyphy#1543]
Hello, I am working with some JSON files that I have generated using RELAX, and I really would like to map the _k_ values from that output onto a tree for a nice figure (similar to others I've seen in papers that have used RELAX in the past). However, all of the internal nodes/branches are given names like "NodeX" where X is a number. I can't quickly discern which branch attribute from the JSON file refers to any given internal branch. I've checked into the [documentation for HyPhy's JSON output](http://hyphy.org/resources/json-fields.pdf), but I can't find a clear codex for finding this information. 

Any help with this issue would be greatly appreciated! Thank you all for your time.

**Comment by spond** [comment]
Dear @mchaney1,

Give this notebook a go https://observablehq.com/@spond/plotting-relax-k-values-on-branches-of-the-tree

Best,
Sergei
