### ISSUE TITLE
Phylogenetic tree change when submit to BUSTED

### ISSUE THREAD

**Issue by ebrassea** [veg/hyphy#1545]
Hi! I have a problem with my phylogenetic tree, when I submitted my .nex file to BUSTED and click on Run Analysis, the tree changed like the only option to see it is Neighbor-joining tree instead of User-defined tree. I tested another gene and the same occurred. I obtained the tree from GARD, but then change to MEGA and phylotree.js and the tree looks great but when I submitted it again to BUSTED the tree changed and showed another phylogenic

The tree is:

((B_floridae:0.20003859,C_intestinalis:0.26525689):0.02988448,(((((((((((((O_orca:0.04095306,G_melas:0.04277297):0.01630898,T_truncatus:0.02187108):0.05568497,P_sinus:0.07167977):0.03797517,(P_macrocephalus:0.12200976,(B_musculus:0.04565596,B_a_scammoni:0.04453585):0.03881905):0.01892222):0.045893,(C_hircus:0.07641204,(B_mutus:0.03148628,B_taurus:0.02202146):0.07062236):0.04646645):0.03091598,(H_glaber:0.1362911,((T_gelada:0.076347,M_mulatta:0.0915195):0.05730286,(H_s_sapiens:0.04376987,(G_g_gorilla:0.06537436,P_troglodytes:0.04143863):0.01185263):0.06229866):0.04961866):0.03720346):0.01300577,((((C_l_familiaris:0.00000315,C_l_dingo:0.00000315):0.08702266,(V_lagopus:0.05940071,V_vulpe:0.03459823):0.06653372):0.06305042,(L_canadensis:0.13027104,(U_maritimus:0.00558247,U_arctos:0.01311894):0.09609895):0.02434713):0.02117848,((((Z_californianus:0.03503585,E_jubatus:0.03081478):0.03146171,C_ursinus:0.04089903):0.04641381,O_r_divergens:0.11584784):0.03178487,(P_vitulina:0.09810424,(L_weddellii:0.05151911,(M_angustirostris:0.02246986,M_leonina:0.00414203):0.06136867):0.02775935):0.01689789):0.03236855):0.03588242):0.0309446,V_pacos:0.1377713):0.01905035,(((G_gallus:0.11051113,A_forsteri:0.07462224):0.031521,C_livia:0.07869086):0.06867326,(L_chalumnae:0.14690262,(G_evgoodei:0.08545997,(T_s_elegans:0.09352689,C_mydas:0.06694353):0.0349622):0.05993742):0.04558658):0.05147201):0.02044302,(U_parryii:0.13070282,((M_musculus:0.09208119,R_rattus:0.11247811):0.02532647,(O_aureus:0.09757373,(D_rerio:0.12571559,F_heteroclitus:0.1140462):0.03906406):0.0766487):0.02375208):0.03060937):0.0383086,T_m_latirostris:0.10794665):0.05133096,L_africana:0.09502427):0.12696093,(T_sirtalis:0.0436438,T_elegans:0.05391844):1.98473438))

**Comment by spond** [comment]
Dear @ebrassea,

Can you please clarify. Does Datamonkey not accept your tree at all?
One thing to keep in mind is that Datamonkey may reroot trees (this does not change any of the results) for some analyses.

Best,
Sergei

**Comment by ebrassea** [comment]
Dear @spond,

Datamonkey accept my tree but mix phylogeny (primates with marine mammals and so on) before the entire analysis, this complicated the branches selection that I want to test, any clue? I am lost at this point

Best wishes,

Elizabeth

**Comment by spond** [comment]
Dear @ebrassea,

Could you provide the dataset for me to test? 

Best,
Sergei

**Comment by ebrassea** [comment]
Sure, thank you!

[NEXUS.pdf](https://github.com/veg/hyphy/files/10115227/NEXUS.pdf)
