### ISSUE TITLE
hyphy relax Command line

### ISSUE THREAD

**Issue by liangjiameng** [veg/hyphy#1546]
Dear HyPhy team,
I am running some RELAX analyses locally and I am getting confusing results. I installed HYPHY using conda, version 2.5.42.

```
eval "$(/histor/kang/liangjiameng/02.software/99.other/bioconda/minconda3/bin/conda shell.bash hook)"
conda activate hyphy

for i in $(less /histor/kang/liangjiameng/03.project/02.insect/Lepidoptera/04.orthologer/All/Result/single_copy_OG.txt)
do
   hyphy relax --alignment $dir/work/$i/${i}.phy --tree $dir/work/$i/final.tree.nwk -reference-group --reference HAVEERENCE --test NOON --output $dir/work/$i/${i}.RELAX.json CPU=20
done
```
But it shows on the screen

```
........
### Fitting the partitioned descriptive model (completely separate rate distributions for branch sets)
* Log(L) = -27279.84, AIC-c = 54704.21 (72 estimated parameters)
* The following rate distribution was inferred for *test* branches 

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |   73.115    |                                   |
|        Negative selection         |     0.517     |   26.129    |                                   |
|      Diversifying selection       |    483.297    |    0.756    |                                   |

* The following rate distribution was inferred for *reference* branches 

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.008     |   73.484    |                                   |
|        Negative selection         |     0.346     |   25.408    |                                   |
|      Diversifying selection       |     2.766     |    1.108    |                                   |


HYPHY is running in calculator mode. Type 'exit' when you are finished.

```
I have a lot of data and can't type "exit" every time. What should I do?

**Comment by spond** [comment]
Dear @liangjiameng,

Try

```
hyphy  CPU=20 relax --alignment $dir/work/$i/${i}.phy --tree $dir/work/$i/final.tree.nwk  --reference HAVEERENCE --test NOON --output $dir/work/$i/${i}.RELAX.json
```

Best,
Sergei

**Comment by spond** [comment]
Dear @liangjiameng,

This is weird. Could you do me a favor and echo the entire HyPhy command?

```
echo "hyphy  CPU=20 relax --alignment $dir/work/$i/${i}.phy --tree $dir/work/$i/final.tree.nwk  --reference HAVEERENCE --test NOON --output $dir/work/$i/${i}.RELAX.json"
```

There's something on the command line that HyPhy is interpreting as `-c` (calculator) mode, but I don't see what it can be!

Best,
Sergei

**Comment by liangjiameng** [comment]
Run the normal output again

> Dear @liangjiameng,
> 
> This is weird. Could you do me a favor and echo the entire HyPhy command?
> 
> ```
> echo "hyphy  CPU=20 relax --alignment $dir/work/$i/${i}.phy --tree $dir/work/$i/final.tree.nwk  --reference HAVEERENCE --test NOON --output $dir/work/$i/${i}.RELAX.json"
> ```
> 
> There's something on the command line that HyPhy is interpreting as `-c` (calculator) mode, but I don't see what it can be!
> 
> Best, Sergei

Run the normal output again

**Comment by liangjiameng** [comment]
l just ran the front desk again CPU reservation
发自我的小米在 Sergei Pond ***@***.***>，2022年11月30日 下午10:08写道：
Dear @liangjiameng,
Can you remove CPU=20 and see if the issue persists?
Best,
Sergei

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/veg/hyphy/issues/1546#issuecomment-1332204132",
"url": "https://github.com/veg/hyphy/issues/1546#issuecomment-1332204132",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
