### ISSUE TITLE
Question About HyPhy

### ISSUE THREAD

**Issue by gykoh** [veg/hyphy#1548]
Hello! 

What does HyPhy mean by its usage of the term diversifying selection? Is HyPhy working under the assumption that diversifying selection refers mostly to positive selection but also potentially balancing selection?

I looked through different papers, sources, and textbooks to look for a clear definition of diversifying selection, but I could not find one. It seems that diversifying selection is defined in morphological evolution more in terms of selection for extreme phenotypes.

In the textbook _Principles of Population Genetics_ written by Hartl & Clark, it states that diversifying selection, “refers narrowly to selection that favors extreme phenotypes, (Hartl & Clark, 2006). The textbook also talks about how genes that underwent diversifying selection **tend to maintain certain alleles**. One example the textbook uses is the major histocompatibility complex (MHC) in mammals. Certain genes that code for certain selective agents are conserved.

<img width="486" alt="Screen Shot 2022-11-14 at 6 08 14 PM" src="https://user-images.githubusercontent.com/105884770/205109570-6df623a0-3544-4712-a284-8014d48554b2.png">

<img width="425" alt="Screen Shot 2022-11-14 at 6 12 31 PM" src="https://user-images.githubusercontent.com/105884770/205109809-81a1c20c-81fb-4172-bdc9-437b13abbd59.png">

(Hartl & Clark, 2006)

In _Molecular Signatures of Natural Selection_, Nielsen describes diversifying selection a bit differently. “Diversifying selection has in the population genetics literature been synonymous with disruptive selection, a type of selection when two or more extreme phenotypic values are favored simultaneously. This type of selection will often increase variability, and diversifying selection has, therefore, in the molecular evolution literature recently being used more generically to describe any type of selection that **increases variability,**” (Nielsen, 2005). Nielsen advises to avoid using the term “diversifying selection” because there are other forms of selection that can increase genetic variability and that disruptive selection can also decrease genetic variability.

Charlesworth & Charlesworth in _Elements of Evolutionary Genetics_, does not use the term diversifying selection at all throughout the whole book. It does talk about balancing selection, directional selection, positive selection, purifying selection, and stabilizing selection. The picture below of the “Subject Index” does not have diversifying selection at all:

<img width="525" alt="Screen Shot 2022-11-21 at 3 59 09 PM" src="https://user-images.githubusercontent.com/105884770/205109889-fdc1aa63-9c3b-4fc6-9eaf-cb6a0fabbd72.png">

(Charlesworth & Charlesworth, 2010)

In _Evolution of Viral Genomes: Interplay Between Selection, Recombination, and Other Forces_, it states that, “Diversifying, balancing, or (sometimes) directional selection yields dN/dS >1…” (Spielman et al., 2019). It seems that diversifying selection can be synonymous with balancing and sometimes directional selection.

What is HyPhy’s definition of diversifying selection?

Thank you!

Literature Cited

Charlesworth, Brian, and Deborah Charlesworth. Elements of Evolutionary
	Genetics. Roberts and Company Publishers, 2010.

Hartl, Daniel L., and Andrew G. Clark. “Darwinian Selection.” Principles of Population 
        Genetics, 4th ed., Sinauer Associates, Inc., Sunderland, Massachusetts, 2006. 

Nielsen, Rasmus. “Molecular Signatures of Natural Selection.” Annual Review
	of Genetics, vol. 39, no. 1, 15 Dec. 2005, pp. 197–218., 
         https://doi.org/10.1146/annurev.genet.39.073003.112420.

Spielman, S.J., Weaver, S., Shank, S.D., Magalis, B.R., Li, M., Kosakovsky Pond,
	S.L. (2019). Evolution of Viral Genomes: Interplay Between Selection,
	Recombination, and Other Forces. In: Anisimova, M. (eds) Evolutionary
	Genomics. Methods in Molecular Biology, vol 1910. Humana, New York, NY.
	https://doi.org/10.1007/978-1-4939-9074-0_14

**Comment by spond** [comment]
Dear @gykoh,

Diversifying selection simply implies that non-synonymous substitution rates exceed synonymous substitution rates with statistical confidence. This is primarily used to differentiate it from directional selection, where a specific allele (or a specific amino-acid) is selectively advantageous, so once it's fixed, purifying selection is expected. 

There are many selective scenarios which are compatible with dN/dS > 1 (diversifying, disruptive, balancing, compensatory, even some cases of directional selection, see https://academic.oup.com/mbe/article/25/9/1809/1295897).

Best,
Sergei

**Comment by gykoh** [comment]
Thank you Professor Pond!
