### ISSUE TITLE
what is difference between local and global in FitMG94?

### ISSUE THREAD

**Issue by jzhan6** [veg/hyphy#1550]
Maybe a stupid question, but what is difference between local and global option in FitMG94? global means no site heterozygosity and the same rate is assumed for all sites? local means different rates are assumed for all sites?

**Comment by spond** [comment]
Dear @jzhan6,

Great question. 

1. `global` = a single dN/dS ratio shared by all sites and tree branches
2. `local` = each branch has its own dN/dS ratio (or rather a pair of syn. and non-syn. substitution rates).

Both models (in `FitMG94`) assume that there's no site-to-site rate heterogeneity.

Best,
Sergei

**Comment by jzhan6** [comment]
Thanks for the reply even in the Christmas! An amazing Christmas gift! One more question, we find some species with slow evolutionary rate (short branch from root to the tip), we would like to know which proteins slowly evolve in the species/lineages compared with others. Definitely it is possible that all proteins get slower evolved in this lineage. We would like to calculate the evolutionary rate for each protein in all lineages and identify proteins that are significantly slower/faster evolved in the specific lineage.  Could you please tell me if hyphy has some modules to help calculate these values and help identify fast-evolving/slow-evolving proteins? If no, any suggestion for tools or methods? Thanks a lot. Merry Christmas!

**Comment by spond** [comment]
Dear @jzhan6,

HyPhy does not usually calculate temporal rates (you want something like `BEAST` for that), but rather branch lengths (`rate x time`) and relative evolutionary rates (`dN/dS`). 

There are a lot of tests for evolutionary "slowdowns/speed ups" and such going back to [relative rate](https://academic.oup.com/mbe/article-abstract/14/7/769/1119803) and [relative ratio](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Cbek-EAAAAAJ&citation_for_view=Cbek-EAAAAAJ:_FxGoFyzp5QC) tests, however. HyPhy supports both.

Best,
Sergei
