### ISSUE TITLE
Datamonkey segmentation fault (11)

### ISSUE THREAD

**Issue by DeondeJager** [veg/hyphy#1559]
Hi,

Datamonkey is intermittently giving a segmentation fault error. This happens when I run aBSREL, either testing all branches, or just testing one branch, but not consistently. I've attached the error log. Might it be related to this https://github.com/veg/hyphy/issues/1555#issuecomment-1376284333?

Cheers
Deon
[Datamonkey_aBSREL_error_log.txt](https://github.com/veg/hyphy/files/10410669/Datamonkey_aBSREL_error_log.txt)

**Comment by spond** [comment]
Dear @DeondeJager,

Thanks for reporting. The symptoms of the crash look exactly like #1555. @stevenweaver : can you please confirm that the HyPhy version currently deployed to Datamonkey is the one with the fix, i.e. re-released 2.5.46?

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @DeondeJager and @spond 

HyPhy has been updated on Datamonkey. 

Best,
Steven
