### ISSUE TITLE
Interpreting 0 values in aBSREL results

### ISSUE THREAD

**Issue by skaul31** [veg/hyphy#1560]
Hello, 

I have a question about interpreting some of the omega values I am getting from aBSREL. Here are the results from an absrel run for one of my genes of interest: https://www.datamonkey.org/absrel/63d2ba35c82f520f6a324a51#table-tab. 

In the above run I selected all internal and terminal branches of the tree for the exploratory absrel analysis. When I take a look at the results I am seeing that some of the species (CBRIG, CSP28 for example) have been assigned an omega value of 0 for one of the rate classes and this class corresponds to the majority of sites within the gene. I was wondering how to interpret this. When I look at the graph for the omega distribution I can see that the xaxis starts from 0.00001. Does that mean the omega value is actually very very small and not 0? Or is the omega value actually 0? Please let me know. Thank you for your help!

**Comment by spond** [comment]
Dear @skaul31,

The visualization component does apply some floating point number formatting, so you may see very small (near 0 but ≠ 0) rendered as 0.00.

You can always access the actual estimates in the `json` file. For `CSP28` the point estimate is `0` for one of the rate categories, for example.

<img width="915" alt="image" src="https://user-images.githubusercontent.com/1018513/214947210-3a0bf5c0-af60-4e76-b4e1-184e9be5033d.png">

<img width="289" alt="image" src="https://user-images.githubusercontent.com/1018513/214947273-a29a2053-a0a4-451a-94aa-431e8a686748.png">

<img width="538" alt="image" src="https://user-images.githubusercontent.com/1018513/214947326-aefc0e61-45c5-41c1-8a26-e5c87e333e81.png">

<img width="282" alt="image" src="https://user-images.githubusercontent.com/1018513/214947360-5d9e56ca-71a6-4e88-bc24-4f7a2a204cee.png">

Best,
Sergei

**Comment by skaul31** [comment]
Thanks for your quick reply! Yes I do see on the json file that the point estimate is 0 for CSP28. Would this then indicate that dN for these particular sites is 0 and only synonymous substitutions are observed? Or am I thinking about this incorrectly?

**Comment by spond** [comment]
Dear @skaul31,

Mixture distributions like those inferred by `aBSREL` are sometimes difficult to interpret intuitively. What they are really telling you is that each site evolving along a branch has a certain "prior" probability of having a given &omega;. Taking values from the screenshots above, for `CSP28`, these are 93.6% for &omega;=0 and 6.4% for &omega;=46.09. Of course, individual sites will (often strongly) prefer one category over another. One of the common ways to get &omega; = 0, is indeed through a set of sites with exclusively synonymous substitutions. It is rather tricky to get a good sense of why one site branch gets &omega; = 0.01; while another gets &omega; = 0.00.  It is influenced by subtle factors which are difficult to pin down, and also included the effect of other branches.

Best,
Sergei

**Comment by skaul31** [comment]
I see, that makes sense. Thank you for answering my question!
