### ISSUE TITLE
Using FUBAR cache to resume a stalled run?

### ISSUE THREAD

**Issue by hayleyjaywilson** [veg/hyphy#1569]
Hello I am (new to) using FUBAR to determine selection in my alignment. I am working on a slurm system where my job runtime is limited to 12 hours. My FUBAR job runs for the 12 hours and then exits without completing. Am I right in thinking the .cache stores this information so that a run can be resumed from where it stopped rather than restarting? I have tried to resubmit this job but it seems like it just starts from scratch each time. My command is:

`hyphy fubar ENV="USE_MEMORY_SAVING_DATA_STRUCTURES=1e8;"  --alignment FINAL_for_fubar.fasta --tree FINAL_for_dnds_only.final_tree.tree
`

Am I missing something? Apologies if this is obvious.
Thanks

**Comment by spond** [comment]
Dear @hayleyjaywilson,

How big is your alignment? FUBAR will save "milestone" checkpoints, so it doesn't have to redo them, but it does not store partial step information. In other words, if a step (e.g. fitting some model stage) takes > 12 hours, then it won't be cached.

I am always interested in testing interesting use cases, so if you don't mind sharing the input file with me, I'll be happy to run and report on what is going on.

Best,
Sergei

**Comment by hayleyjaywilson** [comment]
Hi Sergei,

My alignment is 1200 isolates with a ~2Mbp genome.
Ah so yes maybe we aren't managing to hit the first milestone.

Happy to email you over the alignment and tree, that would be very helpful. Which address is best to use?

Thanks

Hayley
________________________________

**Comment by spond** [comment]
Dear @hayleyjaywilson,

Yeah, that might do it. I am curious to benchmark this kind of alignment because I don't routinely come across something this long. As this is likely a big file, please use the following dropbox link to send it to me (thanks!). It'll stay open for a few days. 

https://www.dropbox.com/request/8tvfcvj8R6yZLqbLN7Pq

Best,
Sergei

**Comment by spond** [comment]
Dear @hayleyjaywilson,

Got your file, working through it. I don't think I've ever had such a large and LONG alignment to run HyPhy on, so it's exposing some interesting behavior. Thanks for sharing -- I'll post the results here when I have them, and I will probably also spend some time optimizing the code for the next release so such "large and long" alignments are processed more efficiently. 

Stay tuned.

Best,
Sergei

**Comment by spond** [comment]
Dear @hayleyjaywilson,

In 999/1000 cases HyPhy is used for single gene alignments, so we are talking on the order of 1000s bp. Occasionally it has been used on smaller LONG alignments (~10s of sequences and >>1000s bp). I think this is the first case I know of when there are >1000 sequences and >1000000bp. As a software developer, I really appreciate the chance to stress test things and find ways to improve `HyPhy` performance.  

Best,
Sergei

**Comment by hayleyjaywilson** [comment]
Hi,

This has been marked as completed - did you get anywhere with stress testing?

Hayley


________________________________

**Comment by spond** [comment]
Dear @hayleyjaywilson,

GitHub automation sometimes closes issues due to inactivity.
