### ISSUE TITLE
Help with FUBAR Json 

### ISSUE THREAD

**Issue by raufs** [veg/hyphy#1571]
Hi,

This is a follow up to a comment I made in my ticket/issue: https://github.com/veg/hyphy/issues/1568

Specifically, I have been using Hyphy vision to figure out the column headers for the FUBAR resulting json file generated from running the tool via commandline. 

First, as described in my previous ticket, I believe there are more headers for the "MLE" field than there is actual data columns and uploading to Hyphy vision confirms this suggesting the first column corresponds to alpha and the second to beta and so on. 

For the "grid" field there is no header, but I found this PDF ( https://hyphy.org/resources/json-fields.pdf ) in another Github issue/ticket: https://github.com/veg/hyphy/issues/1458 
which states the order of the three columns for the field should be: 

1. nonsyn rate, 2. syn rate, 3. posterior mean over the grid for this dN/dS rate

However, from uploading to Hyphy vision, I believe column 1 and 2 should be flipped.

Can you please confirm that my interpretations based on Hyphy Vision are correct and the header for MLE is out of date along with the PDF shared in the issue 1458? 

I am using Hyphy version 2.5.47 (the most recent I think) installed via Conda.

Thank you!
Rauf

**Comment by spond** [comment]
Dear @raufs,

The PDF is wrong :) All HyPhy analyses that estimate &alpha; and &beta; will report &alpha; first. The headers in the "MLE" field are correctly listed.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/1018513/220981931-51e05281-f691-43f6-81c7-c3f9ab5f1501.png">

There are two extra columns in the "content" part of the `JSON` file, but you can ignore them (they are set to 0). To be honest with you I no longer remember why these columns are there :)

Best,
Sergei

**Comment by raufs** [comment]
Awesome, thank you Sergei for the quick reply and confirmation!

Appreciate it!
Rauf
