### ISSUE TITLE
Compile error #1564 persists in version 2.4.47 (Ubuntu 20.04.5) 

### ISSUE THREAD

**Issue by mjeltsch** [veg/hyphy#1572]
Hi,
2.4.47 does not solve the problem for me. Same issue as previously reported.

/home/mjeltsch/Documents/Informatics/hyphy-2.5.47/src/core/matrix_mult.cpp: In function ‘void _hy_matrix_multiply_4x4x2(double*, double*, double*, int, bool)’:
/home/mjeltsch/Documents/Informatics/hyphy-2.5.47/src/core/matrix_mult.cpp:2624:10: error: ‘_mm256_loadu2_m128d’ was not declared in this scope; did you mean ‘_mm256_loadu_si256’?
 2624 |     B1 = _mm256_loadu2_m128d  (B,B);      // 00,01 x 2
      |          ^~~~~~~~~~~~~~~~~~~
      |          _mm256_loadu_si256
make[3]: *** [CMakeFiles/hyphy.dir/build.make:479: CMakeFiles/hyphy.dir/src/core/matrix_mult.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:141: CMakeFiles/hyphy.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:391: CMakeFiles/MP.dir/rule] Error 2
make: *** [Makefile:318: MP] Error 2

I would need this asap (12 days to deadline for revision...). I guess I just need to find a newer system to install this, correct?
Cheers,
Michael
`

**Comment by spond** [comment]
Dear @mjeltsch,

Bummer. Can you tell me which version of C/C++ `cmake` finds (just paste whatever `cmake` outputs when the second command in the set below).

In the meantime, you should be able to compile by turning off `avx2` extensions. Do the following (from the HyPhy directory)

```
rm -rf CMakeFiles CMakeCache.txt
cmake -DNOAVX=ON ./
make 
```

Best,
Sergei

**Comment by mjeltsch** [comment]
mjeltsch@ubuntu2004:~/Documents/Informatics/hyphy-2.5.47$ cmake -DNOAVX=ON ./
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_SSE4_EXTENSIONS
-- Performing Test HAVE_SSE4_EXTENSIONS - Success
-- Performing Test HAVE_NEON_EXTENSIONS
-- Performing Test HAVE_NEON_EXTENSIONS - Failed
Set default compiler flags to -fsigned-char -O3 -std=c++14 -g -mno-avx -msse4.1 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.68.0")  
/usr/lib/x86_64-linux-gnu/libcurl.so
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found suitable version "1.2.11", minimum required is "1.2.9") 
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-fsigned-char -O3 -std=c++14 -g -mno-avx -msse4.1    -pthread -fopenmp
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mjeltsch/Documents/Informatics/hyphy-2.5.47

**Comment by mjeltsch** [comment]
The build completed successfully!
