### ISSUE TITLE
Question about P[dN/dS<1]<0

### ISSUE THREAD

**Issue by douluojiaofu** [veg/hyphy#1589]
Dear Professor, 
Hello！
I was using SLAC to analyze 1760  NSs（293 condon）genes and got a result with 8 positive sites and 191 negative sites . However ,I found four sites with P [dN/dS<1]<0. It's really strange!
My evolutionary tree is built with mega/NJ/uniform rates/Kimura 2-parameter model/Transitions+Transversions.
I want to know how to explain this strang results(P<0) and what I can do to avoid it next. 
Do I need to rebuild a new tree with different parameters? Or select another methods in datamonkey ? Or just give up the four codon sites?
I would appreciate it if i could get your help.

Sincerely,
Yu Leng
2023 04 10

**Comment by spond** [comment]
Dear @douluojiaofu,

Can you please provide the link to your Datamonkey result page with these results? A negative probability indicates something quite odd, probably an "edge case". In order to diagnose the issue and provide helpful feedback it will be easiest for me to just look at your analysis.

Best,
Sergei

**Comment by douluojiaofu** [comment]
Dear Professor,
Thank you for your help!
This is my result. I analyzed it on the local version of linux，beacuse it's a big data.I packaged its overall result screen and tabular information.

Sincerely,
Yu Leng
2023 04 11
[result.zip](https://github.com/veg/hyphy/files/11195326/result.zip)

**Comment by spond** [comment]
Dear @douluojiaofu,

Thanks for sharing. These **small** negative values (e.g. -4.44E-16) should be treated as ZERO, i.e. very strong evidence of negative selection. 

Best,
Sergei

**Comment by douluojiaofu** [comment]
Dear Professor,
Thank you for your help!
You helped me solve a problem, so that I can continue my research. 
Thank you!

Sincerely,
Yu Leng
2023 04 11
