### ISSUE TITLE
Internal error when running RELAX

### ISSUE THREAD

**Issue by dongzhang0725** [veg/hyphy#1591]
Dear developers,

I encounterred an "Internal error" when running RELAX analysis using the follwing command:
`hyphy CPU=30 RELAX --alignment concatenation.fas ENV="TOLERATE_NUMERICAL_ERRORS=1;" --code Invertebrate-mtDNA --tree tree_marked.tre --test Foreground --output relax.json &> relax.log &`
The full error message is:
```
### Fitting the alternative model to test K != 1
Error:
Internal error 
Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-569804.9328302129] does not match the last recorded LF maximum [-569804.9076651379]

Function call stack
1 :  [namespace = yeiPjMrD] Optimize(mles, likelihoodFunction);
-------
2 :  relax.alternative_model.fit=estimators.FitLF(relax.filter_names,relax.trees,{"0":relax.model_map},relax.general_descriptive.fit,relax.model_object_map,{terms.run_options.retain_lf_object:TRUE,terms.run_options.optimization_log:relax.optimization_log_file("MainALT-log.json")});
-------
3 :  relax.FitMainTestPair();
-------

Check errors.log for execution error details.
```

Could you help me find out what caused the error?

Thank you very much!

Sincerely,
Dong

**Comment by jzehr** [comment]
Dear @dongzhang0725,

What version of HyPhy are you using locally? My suggestion would be to install the latest version of HyPhy and re-run.

Best,

**Comment by spond** [comment]
Dear @dongzhang0725,

In version 2.5.48 or later,  `TOLERATE_NUMERICAL_ERRORS=1` will suppress program termination for this specific condition. In earlier versions, it would not.

Best,
Sergei

**Comment by dongzhang0725** [comment]
Dear @spond ,

Thank you for your reply, I will try hyphy v2.5.50 available in conda, and see what happened.

Sincerely,

Dong

**Comment by dongzhang0725** [comment]
Dear @spond and @jzehr 

I resolved my problem via using new version of HYPHY, thank you very much for your help.

Best wishes,

Dong
