### ISSUE TITLE
 command line interface

### ISSUE THREAD

**Issue by andrewkern** [veg/hyphy#1598]
hey all-- i've been helping a student use `hyphy` with a project and we came to a place where we wanted to use the CLI in a non-interactive way. i was having a bit of a hard time finding how to do this in the documentation, and so with a bit of reverse engineering stumbled upon CLI syntax like this, essentially feeding the desired parameters of the analysis as positional variables. 

`hyphy acd Universal <alignment.fa> MG94CUSTOMCF3X4 Global 012345 <treefile> Estimate`

is this officially supported? is it documented somewhere for me to share with others? I'd be happy to contribute some docs here if that would be helpful.

cheers,
Andy

**Comment by andrewkern** [comment]
thanks @spond! it might be helpful to document the FIFO positional approach too as it's really convenient, if old school 😄

**Comment by spond** [comment]
Dear @andrewkern,

Yes, indeed. Documentation is always the very last thing we do, isn't it?

@stevenweaver : can I ask you to make a note of it somewhere on hyphy.org?

Best,
Sergei

**Comment by andrewkern** [comment]
Happy to help in some way if I can. It would be awesome for GitHub denizens like me if the readme on the repo had such info as well.

**Comment by spond** [comment]
Dear @andrewkern,

That'd be wonderful and I would definitely welcome and encourage it!

Best,
Sergei
