### ISSUE TITLE
Error: not a valid variable identifier in call to FindRoot(models.generic.SetBranchLength.t, 

### ISSUE THREAD

**Issue by eiverso** [veg/hyphy#1599]
Hello,

I'm a online GUI user of the datamonkey RELAX servers, so forgive me if this is something that would be obvious to a person who had installed RELAX themselves. 

I've got a tree in a format and of a size that I've used successfully before, but something is going wrong this time, maybe with a particular taxon name. The tree is attached, along with the error file. Basically, seemingly because of one taxon, I always get this error after about 2 minutes:

**### Fitting the general descriptive (separate k per branch) model
Error:
'cqdenONB.tree_id_0.30_15_27_27_C46_R089_TRA_GEE.t' is not a valid variable identifier in call to FindRoot(models.generic.SetBranchLength.t,** 

Followed by basically the entire tree with a bunch of strange notation. "30_15_27_27_C46_R089_TRA_GEE" is the name of the first taxon in the user-defined tree, read from left to right. Although, in actuality, it is "30_15_27_27_C46_R089_Tra_gee" with lower-case letters. 

Any ideas about what's going wrong?

Note: the alignment, with user-defined tree at the bottom, is renamed .txt, because apparently github doesn't allow you to upload a .fas???

Thanks!

[error_log_1st_2000.txt](https://github.com/veg/hyphy/files/11358242/error_log_1st_2000.txt)
[Cercopithecidae_relax_1_3_23_v2.txt](https://github.com/veg/hyphy/files/11358245/Cercopithecidae_relax_1_3_23_v2.txt)

**Comment by stevenweaver** [comment]
Dear @eiverso, 

Try updating the headers to start with a character instead of a number. HyPhy has difficulty understanding labels that start with a number.

Best,
Steven
