### ISSUE TITLE
Difference between --reference-group and --reference flag (RELAX)

### ISSUE THREAD

**Issue by liamfriar** [veg/hyphy#1616]
Hi, I was receiving the same prompt to choose my test and reference groups as @stephenshank screenshotted in #1446 . I am trying to build an automated pipeline, so this would not work well. I found that adding the --reference-group flag fixed the problem, but I am now confused what the difference is between --reference-group and --reference ? My current call seems to work, but I want to make sure I am not doing something different than I intend? I see that there is a "Group test mode" option when I call `hyphy relax --help` but I can't figure out what that is, so maybe it is related?

```
hyphy relax --alignment mod.${alignment_file} --tree $out_tree --reference-group "Background" --test "Foreground" --reference "Background" --models Minimal
rm *tmp
```

_Originally posted by @liamfriar in https://github.com/veg/hyphy/issues/1446#issuecomment-1570652782_

**Comment by spond** [comment]
Dear @liamfriar,

`--reference-group` only makes sense when you run `RELAX` in group mode (available if you have >2 sets of branches), triggered by `--mode "Group mode"`. Otherwise, use `--reference Name`.

Best,
Sergei
