### ISSUE TITLE
Cannot visualise FUBAR results in hyphy-vision

### ISSUE THREAD

**Issue by jaiganeshjg** [veg/hyphy#1617]
The json output file after FUBAR analyses using command line version of HyPhy is not able to be opened in HyPhy-Vision. It shows Something went wrong when rendering the results page. Please file a [bug](http://github.com/veg/hyphy/issues). 

Attached herewith the json file [fubar.zip](https://github.com/veg/hyphy/files/11748685/fubar.zip)

**Comment by stephenshank** [comment]
Dear @jaiganeshjg,

After inspecting your JSON I was not able to find a `runtime` field to determine which version of HyPhy you are using. These are included in the latest versions, and the resulting output will be more in sync with the latest hyphy-vision.

I'd recommend updating to the latest version of HyPhy and trying again. Ideally this will work, but in the worst case it will allow us to troubleshoot the issue better.

Let us know if you have any questions.

Regards,
Stephen
