### ISSUE TITLE
How to include srv in absrel

### ISSUE THREAD

**Issue by Emilyaoc** [veg/hyphy#1619]
Hello,

I just wanted to check whether it should be possible to run absrel with synonymous rate variation included? I thought that the following should do this:

'hyphy absrel --alignment my_alignment.fas --tree my_tree.nex --branches Leaves --srv Yes'

But I notice that the results look identical to when I run the same analysis without '--srv Yes' (identical log liklihoods & AIC-c scores). I think the default for absrel is no srv, isn't it? So shouldn't the results be a little different when I change from the default setting to instead include srv? I see from a post last year on this help forum Sergei said that "The --srv option is sort of "experimental" for absrel". So I just wanted to check what the current status is?

Thank you for your help with this

Emily

**Comment by spond** [comment]
Dear @Emilyaoc,

Assuming you have a recent version of HyPhy this should do it. Look for the following output block on `stdout` to confirm 

```
* Log(L) = -3700.67, AIC-c =  7568.96 (81 estimated parameters)
* The following rate distribution for site-to-site **synonymous** rate variation was inferred

|               Rate                | Proportion, % |               Notes               |
|-----------------------------------|---------------|-----------------------------------|
|               0.435               |    55.084     |                                   |
|               1.381               |    41.819     |                                   |
|               5.895               |     3.097     |                                   |
```

For example...

```
$hyphy absrel --alignment tests/data/bglobin.nex --srv Yes --branches Leaves

...

### Adaptive branch site random effects likelihood test 
Likelihood ratio test for episodic diversifying positive selection at Holm-Bonferroni corrected _p =   0.0500_ found **0** branches under selection among **17** tested.

```

```
$hyphy absrel --alignment tests/data/bglobin.nex --srv No --branches Leaves

...

### Adaptive branch site random effects likelihood test 
Likelihood ratio test for episodic diversifying positive selection at Holm-Bonferroni corrected _p =   0.0500_ found **2** branches under selection among **17** tested.

* SHEEP, p-value =  0.02583
* MARSUPIAL, p-value =  0.04413

```

Best,
Sergei

**Comment by Emilyaoc** [comment]
Ok, thank you. I have been using HyPhy version 2.5.31. Is this recent enough? Presumably the order of the 'srv' and 'branches' arguments don't matter? Or do they? I note they ae the opposite way around between your and my example?

**Comment by Emilyaoc** [comment]
Actually, I see now that SRV support for aBSREL is litsed as an update in version 2.5.36. So does that mean that as I have been using an earlier version '--srv Yes' is ignored?

**Comment by spond** [comment]
Dear @Emilyaoc, 

The order of the arguments is immaterial. HyPhy does ignore command line arguments which are not consumed by the analysis, and it does so quietly. 

Best,
Sergei

**Comment by Emilyaoc** [comment]
Okay. Thank you.
