### ISSUE TITLE
Contrast-FEL Error

### ISSUE THREAD

**Issue by Cayna26** [veg/hyphy#1620]
Hello! 
When I was trying to run Contrast-FEL, in the Datamonkey Adaptive Evolution Server,  the following error occured:

Standard Error Message
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

I don't understand what the problem is but I send attatched the log file obtained, as it may be of help.

[log.txt](https://github.com/veg/hyphy/files/11847441/log.txt)

Kindly, 
Catarina

**Comment by stephenshank** [comment]
Dear @Cayna26,

It appears as though there are stop codons in one of your sequences, as evidenced by the following lines from the log:

```
*** PROBLEM WITH SEQUENCE ' SPSG2' (681 nt long, stop codons shown in capital letters)

atgatagtaagcttcttcgaccaattcgcaagcccctctttcctaggggtcccacttattgccatcgcaattgcactcccaTGAgtactatttccaactcctccgtcccgaTGAgtaaacaaccgacttattaccgtccaaacaTGAtttattaaccgattcaccaatcaacttatacttcctctgaacgtagggggacataaatgggcactgctactggcctctttaatagtattccttattaccattaacatgttaggccttctcccgtatacctttacacctacaacacaactatccctaaatatagggcttgctgtgccactaTGActtgccacagtaatcattggcatgcgaaatcaaccaacagttgctcttggacaccttctgccagaagggactcctatcccattaattcctgtactaattatcatcgagacaattagcctgttcattcggccactagccctgggagttcgacttacagccaacttgaccgcaggccacctactaattcaactcattgctacagctgtattcgtattaatacctataataccaacagtggcagttctaaccgctgccgttcttttcctattaacgcttctagaagttgcagtagctataattcaagcctacgtatttgtattgcttctaagcctctacctacaagaaaacgtt
Error:

Master node received an error:The input alignment must have the number of sites that is divisible by 3 and must not contain stop codons
```

HyPhy codon models do not allow stop codons, so such sequences need to either be corrected or filtered out prior to analyses like Contrast-FEL.

Regards,
Stephen

**Comment by Cayna26** [comment]
Hello!

I am using the vertebrate mitochondrial genetic code.
However, when i went to check which codons where being marked as stop codons i realized i was TGA, which is coded as stop codon according to the universal genetic code, but as Tryptophan in the mitochondrial. So it seems, that at least in this codon is being applied  the universal genetic code instead of the vertebrate mitochondrial one, when it shoudn't.

Kindly,
Catarina

**Comment by spond** [comment]
Dear @Cayna26,

This could be a bug in how `contrast-fel` is passing its arguments through Datamonkey. You are selecting `vertebrate mitochondrial` on the upload page? @stevenweaver : can you please investigate? 

Best,
Sergei

**Comment by Cayna26** [comment]
Hi, @spond ! 
Yes, i am selecting vertebrate mitochondrial on the upload page. That is why i thought something was wrong and came here to ask for help :)

Kindly,
Catarina
