### ISSUE TITLE
error displaying FEL results

### ISSUE THREAD

**Issue by KVDlab** [veg/hyphy#1621]
FEL seems to run to completion but when the results should be displayed I get the following error

intro = RuntimeError: Failed to fetch
citation = RuntimeError: unable to load module
viewof pv = RuntimeError: unable to load module
summary_table = RuntimeError: Failed to fetch
viewof table_filter = RuntimeError: unable to load module
viewof plot_type = RuntimeError: Failed to fetch
fig1caption = RuntimeError: Failed to fetch
figure1 = RuntimeError: Failed to fetch
table1caption = RuntimeError: unable to load module
viewof table1 = RuntimeError: Failed to fetch
table1legend = RuntimeError: Failed to fetch
viewof tree_id = RuntimeError: Failed to fetch
viewof treeDim = RuntimeError: Failed to fetch
treeLegend = RuntimeError: unable to load module
figure2 = RuntimeError: Failed to fetch

**Comment by spond** [comment]
Dear @KVDlab,

That seems like an issue with JavaScript libraries not loading. I have not seen it before. Is the issue persistent or transient?

Do you see this error with Datamonkey?

Best,
Sergei

**Comment by BasselTwin** [comment]
I'm having the same issue displaying my results, I verified my file and parameters and it persists. ([Photo](https://basseltwin-blog.tumblr.com/private/724925403303641088/tumblr_jaRGKfz6yXXVOQSZD))

**Comment by stevenweaver** [comment]
The Datamonkey page works for me. Looks like it was a timeout issue. Going to close.
