### ISSUE TITLE
What to go further after the analyses of General Descriptive model in RELAX

### ISSUE THREAD

**Issue by biozhajie** [veg/hyphy#1626]
Dear @spond 

I have finished the analyses of General Descriptive model in RELAX, and got the distribution of selection intensity parameters among branches of the entire phylogeny. Then I have two confusions: 
1. Do I need to conduct further analyses focusing all the branches, or just focusing the branches with intensified selections ignoring the branches with relaxed selection? 
2.  For further analyses, if I am insterested in the distribution of omega values among each branch, does this mean I have to conduct many separate analyses branch by branch?

Best,

Jie

**Comment by spond** [comment]
Dear @biozhajie,

I am afraid I don't understand your questions. What are you trying to learn/test with RELAX? The General Descriptive model is just that -- descriptive. It does not directly test any hypotheses.

Best,
Sergei

**Comment by biozhajie** [comment]
> Dear @biozhajie,
> 
> I am afraid I don't understand your questions. What are you trying to learn/test with RELAX? The General Descriptive model is just that -- descriptive. It does not directly test any hypotheses.
> 
> Best, Sergei

Dear @spond 

Thanks your reply very much! I am sorry for my ambiguous expression. 
The key points I am confused are:  If the general descriptive model indicated the selection on the branch was intensified, but we don't know which types the selections belonging to (i.e. postive or negtive selections) a priori, then how to conduct a further test since we don't know which method is appropriate as different methods are designed for different types of selections? 

Again, General Descriptive model always gives the the distribution of selection intensity parameters among branches of the entire phylogeny, then I am not sure which branches are worth for further test, the branches with intensified selections or he branches with relaxed selection? 

Finally, If there are dozens of branches need to be further test, then will we have to conduct dozens of separate tests for those branches (one test for one branch a time), or there is something simpler way to run to get a complete test results at one time?

Best,

Jie

**Comment by spond** [comment]
Dear @biozhajie ,

Generally, you **should not** use test A on your input data to determine how to run test B on the same data (regardless of what the tests are). Doing so will create strong biases toward finding results where they may be none. This is especially the case if you decide what the null hypothesis is for test B depending on the outcome of test A. 

If you use the general descriptive model to examine what the relative selection intensities are on your tree, I would not recommend picking a subset of branches which look like they may be selected and then testing them and only them. For "wholesale" screening of selection on branches you should probably use `aBSREL` because that's what it is designed to do and it includes multiple testing corrections.

Best,
Sergei

**Comment by biozhajie** [comment]
> Dear @biozhajie ,
> 
> Generally, you **should not** use test A on your input data to determine how to run test B on the same data (regardless of what the tests are). Doing so will create strong biases toward finding results where they may be none. This is especially the case if you decide what the null hypothesis is for test B depending on the outcome of test A.
> 
> If you use the general descriptive model to examine what the relative selection intensities are on your tree, I would not recommend picking a subset of branches which look like they may be selected and then testing them and only them. For "wholesale" screening of selection on branches you should probably use `aBSREL` because that's what it is designed to do and it includes multiple testing corrections.
> 
> Best, Sergei

Dear @spond 

Thanks your replies and thank for your interpretion which made me realize the problem of my previous thoughts.  However, as we known,   `aBSREL` can only test for positive selection, but if I want to identify which branches were under intensified  purifying selections were intesfied from the "wholesale" screening of selection on branches, how can I do ?

Best,
Jie
