### ISSUE TITLE
aBSREL - All branches analysed independently of labels

### ISSUE THREAD

**Issue by psorigue** [veg/hyphy#1629]
Hi,

I labelled my tree in phylotree but, when I run the analysis, aBSREL tests for all the branches anyway. I tried the analysis with the oposite branches labelled, and both trees provide the same results.

Is there a way to solve this? I saw a closed issue from some time ago about the same problem, but no solution was suggested.

Thanks in advance!

**Comment by spond** [comment]
Dear @psorigue,

Can you provide more details?

1. Does this issue refer to running `HyPhy` locally or on `Datamonkey`?
2. How are you calling `aBSREL` (the entire command line).
3. Please attached the labeled tree (Newick)

Best,
Sergei

**Comment by psorigue** [comment]
Hi Sergei,

Apologies for not providing enough information.

I am running aBSREL locally on the command line, installed through conda.
So far, the code works but does not read the labels of the tree and instead
it runs the analysis for all the branches. I'm using aThis is my command:

 ``hyphy absrel --alignment aln_final.fa --tree tree_PB_fg.nwk --output
./PBfg.json``

In attachment I share with you the tree.

Thanks a lot for the help.

All the best,
Pol Sorigué

Missatge de Sergei Pond ***@***.***> del dia dj., 27 de jul.
2023 a les 21:21:

**Comment by jzehr** [comment]
Dear @psorigue,

 Try:
 
 `hyphy absrel --alignment aln_final.fa --tree tree_PB_fg.nwk --branches LABELS --output
./PBfg.json` -- change out "LABELS" for the actual name of the label you used to annotate branches in your nwk tree. 

Best,

**Comment by psorigue** [comment]
Now it works, thanks a lot!

Missatge de jzehr ***@***.***> del dia dv., 28 de jul. 2023 a
les 14:22:

**Comment by jzehr** [comment]
Dear @psorigue,

Absolutely! Happy to help. 

Best,
