### ISSUE TITLE
openMP warning message: There was an error initializing an OpenFabrics device

### ISSUE THREAD

**Issue by Suirotras** [veg/hyphy#1634]
Hi,

I am running Hyphy aBSREL (version 2.5.51) compiled with openMPI. However, It seems to be running fine, but it does report the following error:

```
--------------------------------------------------------------------------
By default, for Open MPI 4.0 and later, infiniband ports on a device
are not used by default.  The intent is to use UCX for these devices.
You can override this policy by setting the btl_openib_allow_ib MCA parameter
to true.

  Local host:              r403
  Local adapter:           mlx4_0
  Local port:              2

--------------------------------------------------------------------------
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   r403
  Local device: mlx4_0
--------------------------------------------------------------------------
```

Might this be a problem with the compiled version of openmpi? Which version should I preferably compile HyPhy with? or might it be something else. Should I worry about this error message? Unfortunately, I don't know which openMPI version was used exactly, as HyPhy was not installed and compiled on the HPC cluster by myself.

If I need to provide more information, please ask me. possibly useful information:
platform: x86_64-pc-linux-gnu (64-bit),
which runs CentOS Linux 7

There is one more small problem. I am trying to get aBSREL to write a messages.log file using the following function call:
```
HYPHYMPI -m USEPATH="path" aBSREL --alignment seq.fasta --tree tree.nh --srv Yes --output output.JSON --code Universal
```
However, no messages.log gets generated. Might this be a bug, or am I using the option incorrectly?

Thanks for the help!

Sincerely,
Jari

**Comment by spond** [comment]
Dear @Suirotras,

The `MPI` issue is not related to HyPhy, but rather something to do with system configuration. You can probably safely ignore these messages.

The `-m` should trigger the creation of `messages.log.mpinode0` in the working (`USEPATH` in your case) directory. Are you not seeing it there? Make sure `USEPATH=` ends with a slash, i.e. `USEPATH=/tmp/` and not `USEPATH=/tmp`.

Best,
Sergei

**Comment by Suirotras** [comment]
Hello @spond,

Thanks for the response. I will ignore the error message, as there indeed does not seem to be a problem.

Furthermore, the problem with the -m option has been resolved. It had nothing to do with aBSREL. Right now, the -m option is working as intended for me.

Cheers,
Jari
