### ISSUE TITLE
Interpret the results of the MEME model

### ISSUE THREAD

**Issue by WRran-Hydrogen** [veg/hyphy#1639]
Dear Spond:
The result I got with the MEME model is as follows:
![image](https://github.com/veg/hyphy/assets/117963364/13990745-de62-45e8-b99e-551ad83bd2ff)
_(just found positive selection at 1 sites.)_
But I have one question about this result：This positive selection site represents amino acid NO.161, which translates into codons 481-483 sites. However, there are actually very few codons at this position in the entire alignment sequence, as shown below:
![image](https://github.com/veg/hyphy/assets/117963364/07567c6d-07fc-497c-a559-d407887b056a)
Can I assume that for this positive selection site only non-gap sequences are applicable? And for subsequent analysis (e.g. 3D structure analysis, etc.) is it limited to sequences where codons are present at this site? (As in the figure only the first leaf node has codons at this positive selection site).

Looking forward to your reply!

**Comment by WRran-Hydrogen** [comment]
Dear Spond:
Also, I read two of your articles (_Not So Different After All_. **2005** and _Contrast-FEL_. **2022**) and got a lot out of them!
**The constrast-FEL models establishes a formal statistical framework for testing for differences in evolutionary rates among two or more sets of branches at individual sites.** I have a lage dataset that I want to analyze for selection pressure, they are virus form different habitats, and I would like to use the habitats as a division of the tree subsets so that I can get a certain subset of habitats under positive selection.
I think the constrast-FEL model might be suitable for my research (_there are large differences between viruses, while the habitatt information is complete_). But **HYPHY** does not have an application of the model, can you please advise me on how I should use this model for selection pressure analysis?
BTW, I have performed an exploratory test of the **absrel** model on the dataset (with no foreground branches set) with the intention of exploring whether branches in certain specific habitats are located under selection pressure, but due to the large amount of data, the program ran for a week but with no results.
Looking forward to your reply, thanks!

**Comment by spond** [comment]
Dear @WRran-Hydrogen,

There must be other non-gap sequences at that position; a single sequence will not contribute any signal. I do worry about the potential low homology and gappiness of your alignment -- there seem be a lot of locations that just don't "look right" to the eye.

Like around 412, where you have, among others, codons

```
TTG
CTC
GAA
ATT
```

These would require repeated multi-nucleotide substitutions, which, while not impossible, does not strike me as likely.

Best,
Sergei

PS You can run contrast-fel using `hyphy contrast-fel` assuming your version of HyPhy is <3 years old.

**Comment by WRran-Hydrogen** [comment]
Dear @spond,
Thanks for your help, The differences between my sequences are relatively large because I removed redundancy based on **95% nucleotide identity**, and they may be differences at the _genus_ level or even at the _family_ level, in which case the results obtained using **HYPHY** analysis are not credible? Below is my more complete diagram for discussion：
![image](https://github.com/veg/hyphy/assets/117963364/e979f10c-131e-4e15-8ba4-ee841ce8f10a)
And amino acid alignment graph as follows:
![image](https://github.com/veg/hyphy/assets/117963364/0b76efd1-ffed-4378-b0d3-d74282dfe6ef)
As you listed around 412, amino acid 138 is still conservative.
L TTG
L CTC
F GAA
V ATT
![image](https://github.com/veg/hyphy/assets/117963364/66812e1f-8ed4-41a8-9f8e-957283876ad5)
The way I understand it, sites under positive selection with high β are not conserved in the sequence, and the four codons you gave are still at conserved sites throughout the sequence, so this duplicate substitution may not be an alignment error.

Best wishes!
