### ISSUE TITLE
Error Displaying aBSREL results

### ISSUE THREAD

**Issue by Joye-YF-Zhou** [veg/hyphy#1640]
Hello HyPhy team,

I have just recently finished running aBSREL results on a GARD corrected alignment. However, when I try to visualize the results on HyPhy vision, it fails.  It tells me to file a bug. Would you be able to give any insights on how this might happen? 

Information on how I ran the tests: 
HyPhy version 2.5.48
GARD command: hyphy gard --type nucleotide --alignment file.fasta --rate-class 4 
--mode Faster
aBSREL command: hyphy absrel --alignment file.fasta.best-gard.fit.bf --tree MUSCLE_CARP_prot_8-13-23.fasta.contree

I have attached here the json file of the aBSREL results.

Thank you for looking over this problem!

[file.fasta.best-gard.fit.bf.ABSREL copy.json.zip](https://github.com/veg/hyphy/files/12398353/file.fasta.best-gard.fit.bf.ABSREL.copy.json.zip)

**Comment by spond** [comment]
Dear @Joye-YF-Zhou,

The output of this analysis seems to have some issues with the JSON file (probably a bug); some of the tree branches are missing required records in the JSON file. Would you be able to share the input files for me to take a more in-depth look?

In the meantime, you may be able to view partial results with https://observablehq.com/@spond/displaying-absrel-results-using-branch-censoring

Best,
Sergei

**Comment by Joye-YF-Zhou** [comment]
Dear Dr. Pond,

Thank you for looking over this issue! I would be more than happy for you to look over my input files. I have sent you an email with the files attached!

Best regards,
Joye Zhou
