### ISSUE TITLE
Internal ERROR when running aBSREL

### ISSUE THREAD

**Issue by Joye-YF-Zhou** [veg/hyphy#1641]
Hello HyPhy team, 

I just ran an aBSREL analysis on a given dataset and at the "Improving parameter estimates of the adaptive rate class model
" step, it says:
Internal error 
 
	Internal error 
 
	ERROR: [_LikelihoodFunction::LocateTheBump (index 304) current 
       value   -126826.3114144693 (parameter =   0.9993584395344067), best value   
       -126826.3114144693 (parameter =   0.9993584395344067)); delta = 
      1.455191522836685e-11, tolerance = 9.999999999999 
      Parameter name 
     GZjCEMgC.tree_0.Eupolybothrus_cavernicolus_TRINITY_DN19382_c0_g2_i1_len935_.omega2

     Function call stack
    1 :  [namespace = vPhaUHwH] Optimize(mles, ^lf_id);

    -------
     2 :  
     absrel.full_model.fit=estimators.FitExistingLF(absrel.likelihood_function_id,absrel.model_object_map);
    -------

Is there any reason why this would happen?

information on how aBSREL is ran:

- HyPhy version 2.5.48
- downloaded through conda
- command: absrel --alignment MUSCLE.txt --tree MUSCLE.contree
- This issue is only seen on this given alignment. The other datasets have been able to run aBSREL successfully

I have attached the aBSREL run log here. The alignment could be emailed to upon request. 

Thank you for looking over this error
[absrel_run.log.zip](https://github.com/veg/hyphy/files/12398505/absrel_run.log.zip)

**Comment by spond** [comment]
Dear @Joye-YF-Zhou,

Please rerun the analysis specifying `ENV="TOLERATE_NUMERICAL_ERRORS=1;"` on the command line. Also see https://github.com/veg/hyphy/issues/1630

I made some fixes in subsequent versions (2.5.53 is current), which may reduce the incidence of the warning/error.

Best,
Sergei
