### ISSUE TITLE
Hyphy installation problem 

### ISSUE THREAD

**Issue by joana-morais** [veg/hyphy#1648]
I've tried installing Hyphy using conda but all the commands lead to the same error message:

_PackagesNotFoundError: The following packages are not available from current channels:
 - hyphy

Current channels:

  - https://conda.anaconda.org/bioconda/osx-arm64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch_

I've already checked for the latest conda version. These are the tried commands:

conda install -c bioconda hyphy
conda install -c "bioconda/label/cf201901" python-hyphy-python
conda install -c bioconda python-hyphy-python             
conda install hyphy         

Does anyone know how to solve this issue? Thank you!

**Comment by spond** [comment]
Dear @joana-morais,

Looks like you resolved the issue :)

There have been persistent weird issues with Conda, like installing really outdated versions (2.5.8, while the current release is 2.5.54).
HyPhy is pretty self-contained with minimal external dependencies. You should always be able to build from source, assuming you have `gcc` / `clang` and `CMake`.

Best,
Sergei

**Comment by joana-morais** [comment]
Thank you very much @spond
