### ISSUE TITLE
Problem with SLAC 

### ISSUE THREAD

**Issue by js1604** [veg/hyphy#1652]
For the past 2 days I have been receiving the same error message
'We're sorry, there was an error processing your job. Please try again, or visit
[our GitHub issues page](https://github.com/veg/hyphy/issues/)
and create an issue if the issue persists.
Standard Error Message'

**Comment by stephenshank** [comment]
Thanks for reporting this issue @js1604. Can you please try again?

**Comment by stevenweaver** [comment]
Duplicate of #1651
