### ISSUE TITLE
Problem running SLAC

### ISSUE THREAD

**Issue by rahmedbg** [veg/hyphy#1656]
Every time I want to run SLAC , following message is shown-
We're sorry, there was an error processing your job. Please try again, or visit
[our GitHub issues page](http://github.com/veg/hyphy/issues/)
and create an issue if the issue persists.

My job URL is 

https://www.datamonkey.org/slac/652cb715353125059b65cc4e

**Comment by 3032281342** [comment]
Yes,today I also have this error!!!Do you solve it？

**Comment by stephenshank** [comment]
Dear @rahmedbg and @3032281342,

Thanks for reporting this issue. Can you please try again?

Regards,
Stephen

**Comment by stevenweaver** [comment]
Duplicate of #1651

**Comment by rahmedbg** [comment]
Thanks, now its' working!
