### ISSUE TITLE
dN/dS scores from RELAX

### ISSUE THREAD

**Issue by liamfriar** [veg/hyphy#1659]
Hi,

I am wondering if there is a way to get the dN/dS values calculated along each branch from the RELAX outputs? Or do I have to run a different program to get those raw numbers?

Thank you!

**Comment by liamfriar** [comment]
Hi Steven,

Thank you for your response. Do you think `aBSREL` would be helpful for the following?

I have ~10 ingroup genomes and ~40 outgroup genomes. I the ingroup genomes to be experiencing relaxed selection on many genes. To that end, I have run `RELAX` on about 2000 single copy gene trees across the 50 genomes. That worked great. I am also curious about whether certain metabolic pathways or cellular functions are under more or less relaxed selective pressures. One way to approach this would be to just look at the distribution of "relaxation" vs. "intensification" vs. "not_significant" results from `RELAX` in the different pathways, but I think that could be confusing given confidence p-values for each individual result. I think it would be interesting to instead get the `dN/dS` values for each branch from each gene in each pathway and plot these as distributions for each pathway.

So, for instance: if pathway X has geneA, geneB, geneC, then get all the `dN/dS` values for each of geneA,B,C and plot these all together for in group and outgroup and see if there is a significant (probably T-test) difference between the distributions. I believe there will be very few cases where `dN/dS > 1` , so if those are rare, I will throw them out to make interpretation of the results more straightforward.

It looks like `aBSREL` gives a distribution of `omega` values for each (#1198), so I am not sure how I would parse those results? I could limit the model to 1 `omega` value per branch?

Any and all thoughts/suggestions would be hugely helpful. `hyphy RELAX` was great to run and super useful.

**Comment by liamfriar** [comment]
It looks as though `FitMG94` might be the easiest way to get just an `omega` value for each branch in a gene tree?

**Comment by liamfriar** [comment]
Alternatively, from the `RELAX` results, is this the mean `omega` values for each group of genes?

```
### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
* Log(L) = -8145.95, AIC-c = 16505.96 (106 estimated parameters)
* non-synonymous/synonymous rate ratio for *Reference* =   0.1185
* non-synonymous/synonymous rate ratio for *Test* =   0.1669
* non-synonymous/synonymous rate ratio for *Unclassified* =   0.2065
```

**Comment by stevenweaver** [comment]
Dear @liamfriar, 

They are `omega` values for each branch set defined, but they are not the `mean`, they are computed by maximum likelihood. 

For full details of RELAX values in the JSON output, we have a manual [here](https://hyphy.org/resources/json-fields.pdf) if that helps at all. 

Best,
Steven

**Comment by liamfriar** [comment]
@spond 's last suggestion appears to have worked great. And thank you for the `jq` one-liner! This issue #898 was also helpful for me to run long sequences of concatenated genes.

**Comment by spond** [comment]
Dear @liamfriar,

My pleasure. Glad this was helpful.

Best,
Sergei
