### ISSUE TITLE
how to install OpenMP?

### ISSUE THREAD

**Issue by liamxg** [veg/hyphy#1666]
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND)

**Comment by stevenweaver** [comment]
What OS are you using?

**Comment by spond** [comment]
Dear @liamxg,

`gcc-13` is probably the easiest way to get `OpenMP` support.

1. Install homebrew (https://brew.sh)
2. Use `brew` to install `gcc` (`brew install gcc@13`).
3. Use `gcc-13` to compile HyPhy

```
cd hyphy
rm -rf CMakeCache* CMakeFiles/
CC=gcc-13 CXX=g++-13 cmake ./
make 

```

Best,
Sergei
