### ISSUE TITLE
Bug in FEL method analysis.

### ISSUE THREAD

**Issue by Guomengze** [veg/hyphy#1667]
Something went wrong when rendering the results page.

**Comment by stephenshank** [comment]
Dear @Guomengze,

I was just able to run a FEL job on Datamonkey, so I will need more specifics to help troubleshoot.

If you are trying to run a job on Datamonkey, can you please share the URL?

If you are using HyPhy locally and trying to view results on HyPhy vision, can you please share the version of HyPhy that you have installed, how you invoked it, and the input files if you are able?

Regards,
Stephen
