### ISSUE TITLE
Absrel error

### ISSUE THREAD

**Issue by WRran-Hydrogen** [veg/hyphy#1670]
Dear @spond ,

There is error in absrel model in "All branches to test", when running to the last step. The following are running screenshots details:
![image](https://github.com/veg/hyphy/assets/117963364/52b93755-4ab8-4bb5-bb80-3e95d5bfef62)
The log file was overwritten by running it again. Can you help me solve this problem? Many appreciate you!

**Comment by spond** [comment]
Dear @WRran-Hydrogen,

Try adding `ENV="TOLERATE_NUMERICAL_ERRORS=1;"` as a command line argument. Can you also confirm what HyPhy version you are using (`hyphy --version`)?

Best,
Sergei

**Comment by WRran-Hydrogen** [comment]
Dear @spond,

The version detail is **HYPHY 2.5.2(MP) for Linux on x86_64** and I try to add ENV="TOLERATE_NUMERICAL_ERRORS=1;" as a argument. But since I didn't set the branch label, **absrel** will test all the branches and take a lot of time, so it might be 12h before the results come out.
plus can I ask a navie question?  Does my alignment sequence need to be trimmed based on the quality of the gap? Is there any good way to do this that would significantly reduce the amount of computation and improve the quality of the codon aligned sequence? I am currently using the program **macse reportMaskAA2NT** to trim the aligned codon sequences using the protein aligned trimmed sequences. Thanks for your reply!

Cheers!

**Comment by spond** [comment]
Dear @WRran-Hydrogen,

`2.5.2` is ~5 years old. I strongly encourage you to update to a newer HyPhy version. I am also pretty sure that for something as old as `2.5.2` the solution I proposed won't work; newer versions are also much faster.

Yes, you should definitely try to improve alignment quality. There's no gold standard here; my recent suggestions are here: https://hackmd.io/g387lOT1SmudOueIeKhkuA

Best,
Sergei

**Comment by WRran-Hydrogen** [comment]
Dear @spond,

Thanks for your help. I have updated Hyphy and am going to try again. But I entered the website Hackmd you provided and could not find the relevant process (maybe I need to follow to see it?). In addtion, Is it a better choice to select monophyletic branches for analysis of gene trees that contain great diversity (Excessive phylogenetic diversity seems to lead to a bias in positive selection due to an excessive number of aligned sequences)? Many thanks again!

Cheers.

**Comment by WRran-Hydrogen** [comment]
Dear @spond,
I reran the Absrel model and it still produces the error, see the screenshot below:

command: **hyphy absrel --alignment ARG_domain.msa --tree maxcc.contree --output out.json ENV="TOLERATE_NUMERICAL_ERRORS=1"**

error.log:
![image](https://github.com/veg/hyphy/assets/117963364/50756e73-983d-48d5-a731-9ef2b8264f46)

Process file:
![image](https://github.com/veg/hyphy/assets/117963364/0e6f3209-e906-44f8-ab54-019961e7ee49)

My hyphy version is **HYPHY 2.5.29(MP) for Linux on x86_64**, I don't know what the problem is, could you please help me?

**Comment by spond** [comment]
Dear @WRran-Hydrogen,

1. I would recommend updating to 2.5.59 (2.5.29 is now > 3 years old).
2. Add `ENV="TOLERATE_NUMERICAL_ERRORS=1;"` to the command line arguments to treat the errors you report as warnings.

Best,
Sergei
