### ISSUE TITLE
Same P-value before and after correction

### ISSUE THREAD

**Issue by tongyin121** [veg/hyphy#1672]
Hi,
I used the absrel program to identify the signatures of positive selection across the lineages that interest me, but the results confuse me because p value are the same before and after correction. Is this a normal situation ? If it's not how to solve it.

**Comment by spond** [comment]
Dear @tongyin121,

Can you please provide more details? Ideally, a full reproducible example.

How many branches are in your test set?

Best,
Sergei

**Comment by tongyin121** [comment]
Sure, Here are my tree and command.
Tree: 
((Pili:1,(Peup:1,Ppru:1):0.320178):3.139025,((Plas:1,(Psim:1,(Pdel:1,(Ptri:1,(Pkor:1,((Ppse:1,Pwua:1):0.535223,(Psze:1,Pyun:1):0.283281):0.610446):0.326403):0.248587):0.101212):0.019664):1.005652,(((Palba:1,Palby:1):1.685798,(Ptre:1,(Pdav:1,Prot:1):0.363935):0.578082):0.506785,(Pqio{Foreground}:1,Pade:1):0.61325):2.275384):0.008882):2.444682;
Command:
hyphy aBSREL --alignment $dir --branches "Foreground" --tree aBSREL_Pqio.treefile --output $outdir/$name.aBSREL.json CPU=2 ENV="TOLERATE_NUMERICAL_ERRORS=1;"

**Comment by spond** [comment]
Dear @tongyin121,

Since you only have one branch labeled as `Foreground`, only one test will be run, hence the correction doesn't really apply (correction for 1 test == raw p-value).

Best,
Sergei
