### ISSUE TITLE
Discordant results between FEL and MEME on Datamonkey

### ISSUE THREAD

**Issue by katherinermartin** [veg/hyphy#1678]
I'm finding that when I run FEL and SLAC on HyPhy on Datamonkey, I get conflicting results for the same dataset. For `site 16,` FEL identifies it as evolving under purifying selection, but MEME identifies it as a positively selected site. For both FEL and MEME, I used p-value threshold = 0.05. For FEL, I provided the user defined tree.
Attached are the `.json` for each analysis, happy to provide alignments/trees. One thing to note is that this is a rather short alignment, as the whole alignment had a breakpoint, so this actually represents a partition after that breakpoint.
[part2poly_MEME.json](https://github.com/veg/hyphy/files/13910265/part2poly_MEME.json)
[part2poly_FEL.json](https://github.com/veg/hyphy/files/13910266/part2poly_FEL.json)

**Comment by spond** [comment]
Dear @katherinermartin,

These types of disagreements are **expected** (see https://journals.plos.org/plosgenetics/article/info%3Adoi%2F10.1371%2Fjournal.pgen.1002764)

FEL looks for **pervasive** (i.e. on average) selection, while MEME looks for **episodic** selection. So your site 16 is on average under negative selection, but there are episodes of positive selection as well. See, in the figure below, that site 16 is quite variable, with many synonymous AND non-synonymous subs.

Best,
Sergei


![untitled-3](https://github.com/veg/hyphy/assets/1018513/3215d97b-b57a-42d8-a327-a4643ee330c3)
![untitled-4](https://github.com/veg/hyphy/assets/1018513/c5ce8c35-af92-4c18-a575-83bb25411f99)

**Comment by katherinermartin** [comment]
Ah okay that makes a ton of sense. Thank you so much @spond 😄
