### ISSUE TITLE
Slight difference in GARD breakpoint location: screen output vs screened data

### ISSUE THREAD

**Issue by katherinermartin** [veg/hyphy#1679]
Hi! Apologies if this has been answered previously.

When GARD identifies breakpoints in my alignment, I consistently see a slight discrepancy in the breakpoint identified on the GARD results page (e.g., `Figure 2. Model-averaged support for breakpoint placement`) and the breakpoint identified when I download the partitioned results in the `screened_data.nex` file.

Attached is an example (both `.json` and the screened `.txt`); on-screen, the breakpoint is 183/184 bp, but in `screened_data.nex`, it's 184/185: 

> CHARSET span_1 = 1-184
> CHARSET span_2 = 185-597

If I decide to manually partition, which breakpoint should I use? I feel like I'm missing something fairly obvious since they're so close to one another, so thank you in advance for any help :)

[result_3rate_beta_gamma.json](https://github.com/veg/hyphy/files/13942982/result_3rate_beta_gamma.json)
[screened_data_3rate_beta_gamma.txt](https://github.com/veg/hyphy/files/13942986/screened_data_3rate_beta_gamma.txt)

**Comment by spond** [comment]
Dear @katherinermartin,

It may actually be a bug (adding an extra `1` to the NEXUS `CHARSET`); I'll take a closer look. In any case, for selection analyses HyPhy will move breakpoints to the nearest codon boundary.

Best,
Sergei
