### ISSUE TITLE
missing PRIME online documentation

### ISSUE THREAD

**Issue by kaw97** [veg/hyphy#1681]
Very minor issue, but I noticed the page for the PRIME documentation is dead. Is this a bug or is there no extra documentation?
https://hyphy.org/methods/other/evo/PRIME.md

Additionally, PRIME requires a JSON file with amino acid properties. Does this need to be user-created/how does the JSON need to be formatted, or is one available?

**Comment by spond** [comment]
Dear @kaw97,

It does seem that the old documentation is dead; I need to update it. PRIME is one of these methods that has been "in development" for a decade, but never quite reaches the finish line. @hannahkimincompbio is actively working on it at this time, so perhaps she can help with more specific questions.

The properties file is require **only** if you want to use somethign other than the built-ins (`Atchley`, `LCAP`, `Random`), which is specified via the `--properties` option. If you give `--properties Custom` then you also need to supply `--property-file`. That's basically a `JSON` dictionary of the form 

```
{
   "prop1 name" : {
         "A" : value,
         "C": value,
....
   }
...
}

```

like in https://github.com/veg/hyphy/blob/6674e219ffa22aa08330cce94e2731c99337bbe9/res/TemplateBatchFiles/libv3/models/codon/MG_REV_PROPERTIES.bf#L30

Best,
Sergei
