### ISSUE TITLE
GARD: Internal error in ComputeBranchCache

### ISSUE THREAD

**Issue by matthewglasenapp** [veg/hyphy#1688]
I receive the following error when running gard on a large multiple sequence alignment (9 sequences of 7575 bases each). The error was seemingly produced during the 12 breakpoint analysis. Gard has worked fine for me on smaller sequence alignments. Any tips would be greatly appreciated.

`
hyphy gard --alignment sequence_alignment.phylip
`

Error:
Internal error 
Internal error in ComputeBranchCache (branch gard.tree.part_4.Node9, eval #553580214 ) reversible model cached likeli
hood =   -67.49786829839633, directly computed likelihood =   -79.91359631404707. This is most likely because a non-r
eversible model was incorrectly auto-detected (or specified by the model file in environment variables; for smaller e
rrors, this could be due to numerical instability of calculations for larger alignments).

[errors.log.txt](https://github.com/veg/hyphy/files/14197031/errors.log.txt)
[gard_output.txt](https://github.com/veg/hyphy/files/14197032/gard_output.txt)
[sequence_alignment.phylip.best-gard.fit.bf.txt](https://github.com/veg/hyphy/files/14197070/sequence_alignment.phylip.best-gard.fit.bf.txt)
[sequence_alignment.phylip.best-gard.txt](https://github.com/veg/hyphy/files/14197071/sequence_alignment.phylip.best-gard.txt)
[sequence_alignment.phylip.GARD.json](https://github.com/veg/hyphy/files/14197072/sequence_alignment.phylip.GARD.json)
[sequence_alignment.phylip.txt](https://github.com/veg/hyphy/files/14197089/sequence_alignment.phylip.txt)

**Comment by stevenweaver** [comment]
Dear @matthewglasenapp, 

Would you mind reviewing https://github.com/veg/hyphy/issues/1610 and seeing if this matches the issue you are having?

If you have a recent enough version of `hyphy`, you should be able to use the `ENV="TOLERATE_NUMERICAL_ERRORS=1;" ` command line argument to avoid this error. 
Best,
Steven

**Comment by matthewglasenapp** [comment]
Thanks so much, Steven. That option worked with version 2.5.50. 

`hyphy ENV="TOLERATE_NUMERICAL_ERRORS=1;" gard --alignment sequence_alignment.phylip`
