### ISSUE TITLE
aBSREL Corrected p-value is 0 

### ISSUE THREAD

**Issue by lmnano** [veg/hyphy#1689]
Dear Sergei,

I have a question about aBSREL results as well. Is there a special meaning to the Corrected p-value, if it is 0, or does that just mean it was so small, it got rounded to zero?

I'm asking because of the case of it being 1, where it means there was insufficient evidence to warrant testing. I didn't find any mention of this in the Understanding the content of HyPhy’s JSON output files pdf or anywhere else.

**Comment by spond** [comment]
Dear @lmnano,

You should only see a zero there if the p-value is so small that it *under*flows. Technically, all this means is that the value is smaller than the smallest number that can be represented by a [double-precision floating point number](https://en.wikipedia.org/wiki/IEEE_754-1985) (~2.23×10<sup>−308</sup>(.

```
$hyphy -c 
% LRT = 10, df = 1
1-CChi2 (10,1)
0.001565402257875048
% LRT = 200, df = 1
1-CChi2 (200,1)
0
```

Best,
Sergei

**Comment by lmnano** [comment]
Ok, thank you, that's what I thought.
