### ISSUE TITLE
MEME Output Interpretation

### ISSUE THREAD

**Issue by oscarwallnoefer** [veg/hyphy#1691]
Hi, 

We are trying to understand which sites and branches are under selection in our phylogenetic tree. However, we are failing to interpret the output from MEME. How can we interpret the "0" in #branches? Why can't we set the EBF threshold on DataMonkey when we load our .log output file?

Thank you for your time, 

Oscar

**Comment by spond** [comment]
Dear @oscarwallnoefer,

Not sure I understand your question. Please load the `.json` output files (which you can get from HyPhy or Datamonkey) into https://observablehq.com/@spond/meme for the most recent visualization options.

If you are asking why a particular site has a significant p-value without any individual branch showing up as having high EBF, that's quite common and simply refers to the case of "diffuse" support, i.e. no individual branch is highly influential, but taken together, they are. Alternatively, for sites where nearly all the &omega; weight is allocated to &omega; > 1, EBFs are not meaningful.

Rememeber, that EBF is only an exploratory tool -- the statisitcally "principled" output is the p-value. EBF simply gives you a way to expore where the support for the p-value comes from, but it's not very precise.

Here's an example 

<img width="1184" alt="image" src="https://github.com/veg/hyphy/assets/1018513/6916a575-6961-4152-b1b0-3e70ac8a4d56">

Codon 50 (diffuse support)

<img width="877" alt="image" src="https://github.com/veg/hyphy/assets/1018513/c7bee20d-1ccc-4927-942e-681b3723aa3b">


Codon 96 (single 3x substitution is the source of signal)

<img width="814" alt="image" src="https://github.com/veg/hyphy/assets/1018513/e42f0f7f-5c5a-4511-bf05-19a156cfd45b">


Best,
Sergei

**Comment by oscarwallnoefer** [comment]
Dear @spond, 
Thank you for the quick and excellent response, it was exactly what we were trying to understand!
