### ISSUE TITLE
amino acid sequences

### ISSUE THREAD

**Issue by ElvisFFVII** [veg/hyphy#1694]
How can I send my amino acid sequences for analysis?

Every time I submit to the server this error appears: This doesn't seem to be a nucelotide alignment. It had 20 character states, whereas we expected 4. Perhaps you uploaded an amino-acid alignment by mistake?

My sequences are aligned and in fasta format

**Comment by spond** [comment]
Dear @ElvisFFVII,

Most Datamonkey analyses require **coding sequences** (`FADE` is an exception), so they won't accept amino-acid data. You may need to find CDS/codon sequences underlying your amino-acid alignment.

Best,
Sergei
