### ISSUE TITLE
busted creates tree but then errors

### ISSUE THREAD

**Issue by sobregon1** [veg/hyphy#1696]
I have prepped my nucleotide data by aligning sequences and removing stop codons. Busted will generate a tree but then outputs this error:

/var/spool/torque/mom_priv/jobs/3556890.new-silverback.SC: line 41:  /home/datamonkey/datamonkey-js-server/production/app/busted/../../.hyphy/res//TemplateBatchFiles/SelectionAnalyses/BUSTED.bf --code Universal --alignment /home/datamonkey/datamonkey-js-server/production/app/busted/output/65e387fb52b2134956cca316 --tree /home/datamonkey/datamonkey-js-server/production/app/busted/output/65e387fb52b2134956cca316.tre --branches All --rates 3 --syn-rates 3 --multiple-hits None --srv Yes --grid-size 250 --starting-points 1 --kill-zero-lengths No --output /home/datamonkey/datamonkey-js-server/production/app/busted/output/65e387fb52b2134956cca316.BUSTED.json --save-fit /dev/null: No such file or directory

is this an issue with my dataset (attached) or the server?

Thanks,
sarah
[hyphy1.txt](https://github.com/veg/hyphy/files/14470665/hyphy1.txt)

**Comment by MayvJing** [comment]
Similar error also happened when I use MEME and FEL, while aBSREL is still ok. I run the same data 5 days ago and there were no error that time.

/var/spool/torque/mom_priv/jobs/3560087.new-silverback.SC: line 29:   meme --alignment /home/datamonkey/datamonkey-js-server/production/app/meme/output/65e41cba52b2134956ccbfeb --tree /home/datamonkey/datamonkey-js-server/production/app/meme/output/65e41cba52b2134956ccbfeb.tre --code Universal >> /home/datamonkey/datamonkey-js-server/production/app/meme/output/65e41cba52b2134956ccbfeb.meme.progress: No such file or directory

**Comment by spond** [comment]
Dear @MayvJing and @sobregon1,

Thank you for reporting these issues. It appears to be the result of a recent version upgrade. We'll look into it ASAP and resolve. 

Best,
Sergei

@stevenweaver

**Comment by spond** [comment]
Dear @MayvJing  and @sobregon1,

@stevenweaver has resolved this issue, please try again.

Best,
Sergei

**Comment by MayvJing** [comment]
> Dear @MayvJing and @sobregon1,
> 
> @stevenweaver has resolved this issue, please try again.
> 
> Best, Sergei

It works now, salute your solution!

Best wishes,
Mayv
