### ISSUE TITLE
DATAMONKEY - MULTI-HIT

### ISSUE THREAD

**Issue by TuruuBat** [veg/hyphy#1697]
Hello
Is the MULTI HIT program working on the web?

**Comment by TuruuBat** [comment]
.....
We're sorry, there was an error processing your job. Please try again, or visit
[our GitHub issues page](http://github.com/veg/hyphy/issues/)
and create an issue if the issue persists. 

Standard Error Message 
.....
/var/spool/torque/mom_priv/jobs/3560753.new-silverback.SC: line 30:   /home/datamonkey/datamonkey-js-server/production/app/multihit/../../.hyphy-analyses/FitMultiModel/FitMultiModel.bf --code Universal --alignment /home/datamonkey/datamonkey-js-server/production/app/multihit/output/65e43ab352b2134956ccc1fd --tree /home/datamonkey/datamonkey-js-server/production/app/multihit/output/65e43ab352b2134956ccc1fd.tre --rates 3 --triple-islands No --output /home/datamonkey/datamonkey-js-server/production/app/multihit/output/65e43ab352b2134956ccc1fd.MULTI.json: No such file or directory

**Comment by spond** [comment]
Dear @TuruuBat,

There seems to be an issue with the server at the moment. We'll try to resolve it as quickly as possible.

Best,
Sergei

**Comment by TuruuBat** [comment]
Thank you . 🤗Sent from my iPhoneOn 3 Mar 2024, at 21:52, Sergei Pond ***@***.***> wrote:﻿
Dear @TuruuBat,
There seems to be an issue with the server at the moment. We'll try to resolve it as quickly as possible.
Best,
Sergei

**Comment by spond** [comment]
Dear @TuruuBat,

@stevenweaver has resolved this issue, please try again.

Best,
Sergei
