### ISSUE TITLE
Error when using RELAX

### ISSUE THREAD

**Issue by Oswaldz** [veg/hyphy#1698]
Hi,

I'm using RELAX to analyse over 500 genes of 11 insect species, but have some problems. Apologize that I have no bioinformatics background, but I cannot find what caused the problem. 

Thank you very much. 

Following is what's in my error.log. 
Error:'RPN:"mUyYPLdU.tree_id_0"|"hanni"|{
 "empirical":9,
 "global":{
   "Mixture auxiliary weight for category 1":"relax.ge.bsrel_mixture_aux_0",
   "Mixture auxiliary weight for category 2":"relax.ge.bsrel_mixture_aux_1",
   "Substitution rate from nucleotide A to nucleotide C":"relax.ge.theta_AC",
   "Substitution rate from nucleotide A to nucleotide G":"relax.ge.theta_AG",
   "Substitution rate from nucleotide A to nucleotide T":"relax.ge.theta_AT",
   "Substitution rate from nucleotide C to nucleotide G":"relax.ge.theta_CG",
   "Substitution rate from nucleotide C to nucleotide T":"relax.ge.theta_CT",
   "Substitution rate from nucleotide G to nucleotide T":"relax.ge.theta_GT",
   "non-synonymous/synonymous rate ratio for category 1":"relax.ge.omega1",
   "non-synonymous/synonymous rate ratio for category 2":"relax.ge.omega2",
   "non-synonymous/synonymous rate ratio for category 3":"relax.ge.omega3"
  },
 "local":{
   "relaxation or intensification parameter":"k",
   "synonymous rate":"t"
  }
}|0|relax.set.k' evaluated with errors  Unconsumed values on the stack
[2]------------------
hanni.{
 "empirical":9,
 "global":{
   "Mixture auxiliary weight for category 1":"relax.ge.bsrel_mixture_aux_0",
   "Mixture auxiliary weight for category 2":"relax.ge.bsrel_mixture_aux_1",
   "Substitution rate from nucleotide A to nucleotide C":"relax.ge.theta_AC",
   "Substitution rate from nucleotide A to nucleotide G":"relax.ge.theta_AG",
   "Substitution rate from nucleotide A to nucleotide T":"relax.ge.theta_AT",
   "Substitution rate from nucleotide C to nucleotide G":"relax.ge.theta_CG",
   "Substitution rate from nucleotide C to nucleotide T":"relax.ge.theta_CT",
   "Substitution rate from nucleotide G to nucleotide T":"relax.ge.theta_GT",
   "non-synonymous/synonymous rate ratio for category 1":"relax.ge.omega1",
   "non-synonymous/synonymous rate ratio for category 2":"relax.ge.omega2",
   "non-synonymous/synonymous rate ratio for category 3":"relax.ge.omega3"
  },
 "local":{
   "relaxation or intensification parameter":"k",
   "synonymous rate":"t"
  }
}.0
[1]------------------
hanni.{
 "empirical":9,
 "global":{
   "Mixture auxiliary weight for category 1":"relax.ge.bsrel_mixture_aux_0",
   "Mixture auxiliary weight for category 2":"relax.ge.bsrel_mixture_aux_1",
   "Substitution rate from nucleotide A to nucleotide C":"relax.ge.theta_AC",
   "Substitution rate from nucleotide A to nucleotide G":"relax.ge.theta_AG",
   "Substitution rate from nucleotide A to nucleotide T":"relax.ge.theta_AT",
   "Substitution rate from nucleotide C to nucleotide G":"relax.ge.theta_CG",
   "Substitution rate from nucleotide C to nucleotide T":"relax.ge.theta_CT",
   "Substitution rate from nucleotide G to nucleotide T":"relax.ge.theta_GT",
   "non-synonymous/synonymous rate ratio for category 1":"relax.ge.omega1",
   "non-synonymous/synonymous rate ratio for category 2":"relax.ge.omega2",
   "non-synonymous/synonymous rate ratio for category 3":"relax.ge.omega3"
  },
 "local":{
   "relaxation or intensification parameter":"k",
   "synonymous rate":"t"
  }
}.0
'RPN:"mUyYPLdU.tree_id_0"|"hanni"|{
 "empirical":9,
 "global":{
   "Mixture auxiliary weight for category 1":"relax.ge.bsrel_mixture_aux_0",
   "Mixture auxiliary weight for category 2":"relax.ge.bsrel_mixture_aux_1",
   "Substitution rate from nucleotide A to nucleotide C":"relax.ge.theta_AC",
   "Substitution rate from nucleotide A to nucleotide G":"relax.ge.theta_AG",
   "Substitution rate from nucleotide A to nucleotide T":"relax.ge.theta_AT",
   "Substitution rate from nucleotide C to nucleotide G":"relax.ge.theta_CG",
   "Substitution rate from nucleotide C to nucleotide T":"relax.ge.theta_CT",
   "Substitution rate from nucleotide G to nucleotide T":"relax.ge.theta_GT",
   "non-synonymous/synonymous rate ratio for category 1":"relax.ge.omega1",
   "non-synonymous/synonymous rate ratio for category 2":"relax.ge.omega2",
   "non-synonymous/synonymous rate ratio for category 3":"relax.ge.omega3"
  },
 "local":{
   "relaxation or intensification parameter":"k",
   "synonymous rate":"t"
  }
}|0|relax.set.k' evaluated with errors  Unconsumed values on the stack
[2]------------------
hanni.{
 "empirical":9,
 "global":{
   "Mixture auxiliary weight for category 1":"relax.ge.bsrel_mixture_aux_0",
   "Mixture auxiliary weight for category 2":"relax.ge.bsrel_mixture_aux_1",
   "Substitution rate from nucleotide A to nucleotide C":"relax.ge.theta_AC",
   "Substitution rate from nucleotide A to nucleotide G":"relax.ge.theta_AG",
   "Substitution rate from nucleotide A to nucleotide T":"relax.ge.theta_AT",
   "Substitution rate from nucleotide C to nucleotide G":"relax.ge.theta_CG",
   "Substitution rate from nucleotide C to nucleotide T":"relax.ge.theta_CT",
   "Substitution rate from nucleotide G to nucleotide T":"relax.ge.theta_GT",
   "non-synonymous/synonymous rate ratio for category 1":"relax.ge.omega1",
   "non-synonymous/synonymous rate ratio for category 2":"relax.ge.omega2",
   "non-synonymous/synonymous rate ratio for category 3":"relax.ge.omega3"
  },
 "local":{
   "relaxation or intensification parameter":"k",
   "synonymous rate":"t"
  }
}.0
[1]------------------
hanni.{
 "empirical":9,
 "global":{
   "Mixture auxiliary weight for category 1":"relax.ge.bsrel_mixture_aux_0",
   "Mixture auxiliary weight for category 2":"relax.ge.bsrel_mixture_aux_1",
   "Substitution rate from nucleotide A to nucleotide C":"relax.ge.theta_AC",
   "Substitution rate from nucleotide A to nucleotide G":"relax.ge.theta_AG",
   "Substitution rate from nucleotide A to nucleotide T":"relax.ge.theta_AT",
   "Substitution rate from nucleotide C to nucleotide G":"relax.ge.theta_CG",
   "Substitution rate from nucleotide C to nucleotide T":"relax.ge.theta_CT",
   "Substitution rate from nucleotide G to nucleotide T":"relax.ge.theta_GT",
   "non-synonymous/synonymous rate ratio for category 1":"relax.ge.omega1",
   "non-synonymous/synonymous rate ratio for category 2":"relax.ge.omega2",
   "non-synonymous/synonymous rate ratio for category 3":"relax.ge.omega3"
  },
 "local":{
   "relaxation or intensification parameter":"k",
   "synonymous rate":"t"
  }
}.0

**Comment by spond** [comment]
Dear @Oswaldz,

This is an odd-looking error, I am not sure what caused it. Could you include 

1. The version of HyPhy you are using (`hyphy --version`)
2. The command you are using to run RELAX
3. The output you see printed to the console (screen), **not** the `errors.log` file?

Best,
Sergei

**Comment by Oswaldz** [comment]
Hi Sergei,

I'm using HYPHY 2.5.59(MP) for Darwin on arm64 ARM Neon SIMD zlib (v1.2.12). 

And command is:
hyphy Direction/to/hyphy/RELAX-mod/RELAX.bf --alignment 888aligned-cds.fasta --tree foreground.nwk --code Universal --branches Foreground --multiple-hits None --kill-zero-lengths No > 888_HyPhy-output.log

Following is the print on the console:
Analysis DescriptionAnalysis Description


Analysis Description
----------------------------------------

--------------------

Analysis Description
--------------------
RELAX (a random effects test of selection relaxation) uses a random
effects branch-site model framework to test whether a set of 'Test'
branches evolves under relaxed selection relative to a set of
'Reference' branches (R), as measured by the relaxation parameter (K).
RELAX (a random effects test of selection relaxation) uses a random
Version 2.1 adds a check for stability in K estimates to try to mitigate
effects branch-site model framework to test whether a set of 'Test'
RELAX (a random effects test of selection relaxation) uses a random
convergence problems. Version 3 provides support for >2 branch sets.
branches evolves under relaxed selection relative to a set of
effects branch-site model framework to test whether a set of 'Test'
Version 3.1 adds LHC + Nedler-Mead initial fit phase and keyword support'Reference' branches (R), as measured by the relaxation parameter (K).
branches evolves under relaxed selection relative to a set of
Version 2.1 adds a check for stability in K estimates to try to mitigate

RELAX (a random effects test of selection relaxation) uses a random
'Reference' branches (R), as measured by the relaxation parameter (K).
convergence problems. Version 3 provides support for >2 branch sets.
Version 2.1 adds a check for stability in K estimates to try to mitigate
effects branch-site model framework to test whether a set of 'Test'
Version 3.1 adds LHC + Nedler-Mead initial fit phase and keyword supportconvergence problems. Version 3 provides support for >2 branch sets.
branches evolves under relaxed selection relative to a set of

Version 3.1 adds LHC + Nedler-Mead initial fit phase and keyword support'Reference' branches (R), as measured by the relaxation parameter (K).

- __Requirements__: Version 2.1 adds a check for stability in K estimates to try to mitigate

convergence problems. Version 3 provides support for >2 branch sets.
Version 3.1 adds LHC + Nedler-Mead initial fit phase and keyword support


- __Requirements__: - __Requirements__: 
- __Requirements__: in-frame codon alignment and a phylogenetic tree, with at least two
groups of branches defined using the {} notation (one group can be
defined as all unlabeled branches)
in-frame codon alignment and a phylogenetic tree, with at least two
in-frame codon alignment and a phylogenetic tree, with at least two
groups of branches defined using the {} notation (one group can be
groups of branches defined using the {} notation (one group can be
defined as all unlabeled branches)defined as all unlabeled branches)




- __Citation__: - __Citation__: - __Citation__: in-frame codon alignment and a phylogenetic tree, with at least two
RELAX: Detecting Relaxed Selection in a Phylogenetic Framework (2015).
RELAX: Detecting Relaxed Selection in a Phylogenetic Framework (2015).
groups of branches defined using the {} notation (one group can be
Mol Biol Evol 32 (3): 820-832Mol Biol Evol 32 (3): 820-832defined as all unlabeled branches)




- __Written by__: - __Written by__: 
- __Citation__: RELAX: Detecting Relaxed Selection in a Phylogenetic Framework (2015).
Mol Biol Evol 32 (3): 820-832

Sergei L Kosakovsky Pond, Ben Murrell, Steven Weaver and Temple iGEM /
- __Written by__: UCSD viral evolution group
RELAX: Detecting Relaxed Selection in a Phylogenetic Framework (2015).
Mol Biol Evol 32 (3): 820-832

- __Contact Information__: 
- __Written by__: spond@temple.edu
Sergei L Kosakovsky Pond, Ben Murrell, Steven Weaver and Temple iGEM /
UCSD viral evolution group

- __Analysis Version__: 
- __Contact Information__: 3.1

spond@temple.eduSergei L Kosakovsky Pond, Ben Murrell, Steven Weaver and Temple iGEM /

UCSD viral evolution groupSergei L Kosakovsky Pond, Ben Murrell, Steven Weaver and Temple iGEM /


UCSD viral evolution group- __Analysis Version__: 

- __Contact Information__: 
3.1- __Contact Information__: 

spond@temple.edu
spond@temple.edu

- __Analysis Version__: 
- __Analysis Version__: 3.13.1







>>>>codecodecodecode =>  =>  =>  => UniversalUniversalUniversal

Universal

Error:
Could not find source dataset file "PROMPT_FOR_FILE" (resolved to '/Users/zzha8134/Desktop/Genome/Zhuzhi_single-copy-BUSCOs/shared/alignment/3')
Error:
Error:
Path stack:
Could not find source dataset file "PROMPT_FOR_FILE" (resolved to '/Users/zzha8134/Desktop/Genome/Zhuzhi_single-copy-BUSCOs/shared/alignment/3')
Could not find source dataset file "PROMPT_FOR_FILE" (resolved to '/Users/zzha8134/Desktop/Genome/Zhuzhi_single-copy-BUSCOs/shared/alignment/3')
	/Users/zzha8134/Desktop/Tech/hyphy-master/installation/share/hyphy/
Error:
Path stack:
Path stack:
	/Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/
Could not find source dataset file "PROMPT_FOR_FILE" (resolved to '/Users/zzha8134/Desktop/Genome/Zhuzhi_single-copy-BUSCOs/shared/alignment/3')
	/Users/zzha8134/Desktop/Tech/hyphy-master/installation/share/hyphy/
	/Users/zzha8134/Desktop/Tech/hyphy-master/installation/share/hyphy/

Path stack:
	/Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/
	/Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/
Function call stack
	/Users/zzha8134/Desktop/Tech/hyphy-master/installation/share/hyphy/


1 :  [namespace = PMtSzZTO] DataSet ^dataset_name = ReadDataFile(PROMPT_FOR_FILE);
	/Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/
Function call stack
Function call stack


1 :  [namespace = huDGPZAh] DataSet ^dataset_name = ReadDataFile(PROMPT_FOR_FILE);
1 :  [namespace = xisvZUbY] DataSet ^dataset_name = ReadDataFile(PROMPT_FOR_FILE);

	Keyword arguments:

	Keyword arguments:
		{
	Keyword arguments:
		{
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
Function call stack
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
		}
		{
		}
-------
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
-------
		}
2 :  [namespace = EHXHsOTS] code_info=alignments.LoadGeneticCode(None);
1 :  [namespace = IhwcjYkQ] DataSet ^dataset_name = ReadDataFile(PROMPT_FOR_FILE);
2 :  [namespace = kshSkrkP] code_info=alignments.LoadGeneticCode(None);
-------

2 :  [namespace = avLvqFqI] code_info=alignments.LoadGeneticCode(None);
	Keyword arguments:



		{
	Keyword arguments:
	Keyword arguments:
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
		}
	Keyword arguments:
		{
-------
		{
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
3 :  [namespace = QDjnhiws] return alignments.ReadCodonDataSetFromPath(dataset_name,None);
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
		}

		}
-------
	Keyword arguments:
-------
3 :  [namespace = zNnJeTlt] return alignments.ReadCodonDataSetFromPath(dataset_name,None);
		{
3 :  [namespace = XgNpaQaz] return alignments.ReadCodonDataSetFromPath(dataset_name,None);

		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"

	Keyword arguments:
		}
	Keyword arguments:
		{
-------
		{
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
4 :  r		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
		}
		{
eturn alignments.LoadCodonDataFile(dataset_name,datafilter_name,alignments.ReadCodonDataSet(dataset_name));
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
		}
-------

		}
-------
4 :  return alignments.LoadCodonDataFile(dataset_name,datafilter_name,alignments.ReadCodonDataSet(dataset_name));
	Keyword arguments:
-------
4 :  return alignments.LoadCodonDataFile(dataset_name,datafilter_name,alignments.ReadCodonDataSet(dataset_name));

		{
2 :  [namespace = PxhFWIGD] code_info=alignments.LoadGeneticCode(None);

	Keyword arguments:
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"

	Keyword arguments:
		{
		}
		{
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
	Keyword arguments:
-------
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
		}
		{
5 :  [namespace = relax] codon_data_info=alignments.PromptForGeneticCodeAndAlignment(prefix+".codon_data",prefix+".codon_filter");
		}
-------
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"

-------
5 :  [namespace = relax] codon_data_info=alignments.PromptForGeneticCodeAndAlignment(prefix+".codon_data",prefix+".codon_filter");
		}
	Keyword arguments:
5 :  [namespace = relax] codon_data_info=alignments.PromptForGeneticCodeAndAlignment(prefix+".codon_data",prefix+".codon_filter");

-------
		{
3 :  [namespace = iywFKazF] return alignments.ReadCodonDataSetFromPath(dataset_name,None);
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"

	Keyword arguments:

		}
	Keyword arguments:
		{
	Keyword arguments:
-------
		{
		{
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
6 :  [namespace = relax] load_file({utility.getGlobalValue("terms.prefix"):"relax",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"relax.select_branches"}});
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
		}

		}
		}
-------
	Keyword arguments:
-------
-------
6 :  [namespace = relax] load_file({utility.getGlobalValue("terms.prefix"):"relax",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"relax.select_branches"}});
		{
6 :  [namespace = relax] load_file({utility.getGlobalValue("terms.prefix"):"relax",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"relax.select_branches"}});

		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
4 :  return alignments.LoadCodonDataFile(dataset_name,datafilter_name,alignments.ReadCodonDataSet(dataset_name));

	Keyword arguments:
		}

	Keyword arguments:
		{
-------
	Keyword arguments:
		{
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
7 :  namespace 
		{
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"

		}
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
		}
Step 0.LoadFunctionLibrary("SelectionAnalyses/modules/shared-load-file.bf", /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/);
-------
		}
-------
-------

7 :  namespace 
7 :  namespace 
5 :  [namespace = relax] codon_data_info=alignments.PromptForGeneticCodeAndAlignment(prefix+".codon_data",prefix+".codon_filter");


Step 1.load_file({utility.getGlobalValue("terms.prefix"):"relax",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"relax.select_branches"}});

Step 0.LoadFunctionLibrary("SelectionAnalyses/modules/shared-load-file.bf", /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/);
Step 0.LoadFunctionLibrary("SelectionAnalyses/modules/shared-load-file.bf", /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/);

	Keyword arguments:

		{

Step 2.LoadFunctionLibrary("SelectionAnalyses/modules/grid_compute.ibf", /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/);;
Step 1.load_file({utility.getGlobalValue("terms.prefix"):"relax",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"relax.select_branches"}});
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
Step 1.load_file({utility.getGlobalValue("terms.prefix"):"relax",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"relax.select_branches"}});


		}
	Keyword arguments:

Step 2.LoadFunctionLibrary("SelectionAnalyses/modules/grid_compute.ibf", /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/);;
-------
		{
Step 2.LoadFunctionLibrary("SelectionAnalyses/modules/grid_compute.ibf", /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/);;

6 :  [namespace = relax] load_file({utility.getGlobalValue("terms.prefix"):"relax",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"relax.select_branches"}});
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"

	Keyword arguments:

		}
	Keyword arguments:
		{
	Keyword arguments:
-------
		{
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
		{
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
		}
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
-------
		}
		}
-------
-------
7 :  namespace 

Step 0.LoadFunctionLibrary("SelectionAnalyses/modules/shared-load-file.bf", /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/);

Step 1.load_file({utility.getGlobalValue("terms.prefix"):"relax",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"relax.select_branches"}});

Step 2.LoadFunctionLibrary("SelectionAnalyses/modules/grid_compute.ibf", /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/);;

	Keyword arguments:
		{
		 "tree":"/Users/zzha8134/Desktop/Genome/BUSCO analysis/topology"
		}
-------

Check errors.log for execution error details.

Check errors.log for execution error details.

Check errors.log for execution error details.

Check errors.log for execution error details.
zzha8134@AC07HL1KJQ6P0 alignment % /Users/zzha8134/Desktop/Tech/hyphy-master/hyphy /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/RELAX.bf --alignment 888aligned-cds.msa --tree /Users/zzha8134/Desktop/Genome/BUSCO\ analysis/topology_coakroach_Z.nwk --code Universal --branches Foreground --multiple-hits None --kill-zero-lengths No > 888_HyPhy-output.log"
 
dquote> 
dquote> 
dquote> y
dquote> 
dquote> 
zzha8134@AC07HL1KJQ6P0 alignment % /Users/zzha8134/Desktop/Tech/hyphy-master/hyphy /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/RELAX.bf --alignment 888aligned-cds.msa --tree /Users/zzha8134/Desktop/Genome/BUSCO\ analysis/topology_coakroach_Z.nwk --code Universal --branches Foreground --multiple-hits None --kill-zero-lengths No > 888_HyPhy-output.log 

Check errors.log for execution error details.
zzha8134@AC07HL1KJQ6P0 alignment % /Users/zzha8134/Desktop/Tech/hyphy-master/hyphy /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/RELAX.bf --alignment 888aligned-cds.msa --tree /Users/zzha8134/Desktop/Genome/BUSCO\ analysis/foreground.nwk --code Universal --branches Foreground --multiple-hits None --kill-zero-lengths No > 888_HyPhy-output.log


^C
Check errors.log for execution error details.
zzha8134@AC07HL1KJQ6P0 alignment % /Users/zzha8134/Desktop/Tech/hyphy-master/hyphy /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/RELAX.bf --alignment 888aligned-cds.msa --tree /Users/zzha8134/Desktop/Genome/BUSCO\ analysis/foreground.nwk --code Universal --branches Foreground --multiple-hits None --kill-zero-lengths No > 888_HyPhy-output.log
^C
Check errors.log for execution error details.
zzha8134@AC07HL1KJQ6P0 alignment % /Users/zzha8134/Desktop/Tech/hyphy-master/hyphy /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/RELAX.bf --alignment 888aligned-cds.msa --tree /Users/zzha8134/Desktop/Genome/BUSCO\ analysis/foreground.nwk --code Universal --branches Foreground --multiple-hits None --kill-zero-lengths No > 888_HyPhy-output.log
2

Check errors.log for execution error details.
zzha8134@AC07HL1KJQ6P0 alignment % /Users/zzha8134/Desktop/Tech/hyphy-master/hyphy /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/RELAX.bf --alignment 888aligned-cds.msa --tree /Users/zzha8134/Desktop/Genome/BUSCO\ analysis/foreground.nwk --code Universal --branches Foreground --multiple-hits None --kill-zero-lengths No > 888_HyPhy-output.log
2

Check errors.log for execution error details.
zzha8134@AC07HL1KJQ6P0 alignment % /Users/zzha8134/Desktop/Tech/hyphy-master/hyphy /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/RELAX.bf --alignment 888aligned-cds.fasta --tree /Users/zzha8134/Desktop/Genome/BUSCO\ analysis/foreground.nwk --code Universal --branches Foreground --multiple-hits None --kill-zero-lengths No > 888_HyPhy-output.log
2

Check errors.log for execution error details.
zzha8134@AC07HL1KJQ6P0 alignment % /Users/zzha8134/Desktop/Tech/hyphy-master/hyphy /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/RELAX.bf --alignment 888aligned-cds.fasta --tree /Users/zzha8134/Desktop/Genome/BUSCO\ analysis/foreground.nwk --code Universal --branches Foreground --multiple-hits None --kill-zero-lengths No > 888_HyPhy-output.log
2

Check errors.log for execution error details.
zzha8134@AC07HL1KJQ6P0 alignment % /Users/zzha8134/Desktop/Tech/hyphy-master/hyphy /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/RELAX.bf --alignment 888_10.fasta --tree foreground_10.nwk --code Universal --branches Foreground --multiple-hits None --kill-zero-lengths No > 888_HyPhy-output.log
2

Check errors.log for execution error details.
zzha8134@AC07HL1KJQ6P0 alignment % /Users/zzha8134/Desktop/Tech/hyphy-master/hyphy /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/RELAX.bf --alignment 888_9.fasta --tree foreground_9.nwk --code Universal --branches Foreground --multiple-hits None --kill-zero-lengths No > 888_HyPhy-output.log
2

Check errors.log for execution error details.
zzha8134@AC07HL1KJQ6P0 alignment % /Users/zzha8134/Desktop/Tech/hyphy-master/hyphy /Users/zzha8134/Desktop/Tech/hyphy/RELAX-mod/RELAX.bf --alignment 888aligned-cds.fasta --tree foreground.nwk --code Universal --branches Foreground --multiple-hits None --kill-zero-lengths No > 888_HyPhy-output.log
2

Check errors.log for execution error details.

Thanks for your reply, 

Best wishes,
Zhuzhi

**Comment by spond** [comment]
Dear @Oswaldz,

The error indicates that `HyPhy` is unable to find the alignment file. But it's looking for it in an odd place 

```
Could not find source dataset file "PROMPT_FOR_FILE" (resolved to '/Users/zzha8134/Desktop/Genome/Zhuzhi_single-copy-BUSCOs/shared/alignment/3')
```

My suspicion is that something in the `RELAX-mod/RELAX.bf` may be a bit off (since this is not a standard library analysis). Unfortunately, without looking at `RELAX-mod/RELAX.bf`, I don't think I can be of much further help. Could you share it as a `.txt` attachment here?

Best,
Sergei

**Comment by Oswaldz** [comment]
Hi Sergei,

Thanks. I downloaded the file from the code here, It's in the attachment. 
[RELAX.txt](https://github.com/veg/hyphy/files/14552152/RELAX.txt)

Best wishes,
Zhuzhi
