### ISSUE TITLE
When does RELAX collapse rate classes?

### ISSUE THREAD

**Issue by NatJWalker-Hale** [veg/hyphy#1708]
Hi guys,

As always, thanks so much for developing and supporting such useful methods. I just wanted to ask when and how RELAX chooses to collapse rate classes? From RELAX.bf I can see `if (relax.inferred_ge_distribution[0][1] < 1e-5 || relax.inferred_ge_distribution[1][1] < 1e-5)` - is this checking the inferred dN/dS of a rate class, or the inferred proportion of sites?

Thanks very much for the help!

Nat

**Comment by spond** [comment]
Dear @NatJWalker-Hale,

RELAX checks the **proportion** of sites in &omega; categories 1 or 2 but just for the `general exploratory` model. Are you seeing this happen in your data?

Best,
Sergei

**Comment by NatJWalker-Hale** [comment]
Dear @spond,

Thanks very much for the reply! I think that I'm understanding the output a little bit better now. I also ought to have mentioned that this is v2.5.60. For my example, the stdout contains:

```
### Fitting the general descriptive (separate k per branch) model

### * Log(L) = -6522.20, AIC-c = 13138.83 (47 estimated parameters)
* The following baseline rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |    4.060    |                                   |
|        Negative selection         |     0.000     |   93.895    |                                   |
|      Diversifying selection       |    48.917     |    2.044    |                                   |

```
and then 
```
### Fitting the alternative model to test K != 1
* Log(L) = -6527.00, AIC-c = 13132.30 (39 estimated parameters)
* Relaxation/intensification parameter (K) =     0.64
* The following rate distribution was inferred for **test** branches

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.572     |   79.236    |                                   |
|         Neutral evolution         |     1.000     |   20.764    |                                   |
|      Diversifying selection       |     1.007     |    0.000    |       Not supported by data       |

* The following rate distribution was inferred for **reference** branches

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.418     |   79.236    |                                   |
|         Neutral evolution         |     1.000     |   20.764    |                                   |
|      Diversifying selection       |     1.011     |    0.000    |       Not supported by data       |
```
followed by
```
### Fitting the null (K := 1) model
* Log(L) = -6527.12, AIC-c = 13130.52 (38 estimated parameters)
* The following rate distribution for test/reference branches was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.457     |   77.869    |                                   |
|        Negative selection         |     0.878     |   22.131    |                                   |
|      Diversifying selection       |     1.014     |    0.000    |       Not supported by data       |

```
(so no significant evidence)

But just to be clear, even though the proportion is 0, the alternative and null are still fitting that site class, correct?

The `Not supported by data` message presumably appears when any proportion is estimated as 0. Is this also the case for the output JSON? For this example, none of the model fits have p2 or omega2 in the output.

On the other hand, I have just noticed that some of the sites in the alignment were empty (due to a pruning error), and now that I've removed those sites and re-run, the output JSON _does_ have p2 and omega2 for each model (with p2 still 0). So I'm not sure what is going on there, but sanitising the input seems to have fixed it anyway.

Thanks again!

Nat

**Comment by NatJWalker-Hale** [comment]
Dear @spond,

Okay, that's good to know! Thanks very much for clarifying.

Cheers!

Nat
