### ISSUE TITLE
Error: Internal error  Constrained optimization failed, since a starting point within the domain specified for the variables couldn't be found. Set it by hand, or check your constraints for compatibility.

### ISSUE THREAD

**Issue by glitterseaworms** [veg/hyphy#1709]
To whom it may concern,
I continue receiving the following error when running HyPhy MEME for a specific gene, but not any of my other genes. I'm not sure what to do, as the alignment is correct and has worked with Busted. Please advise on how I should proceed/change parameters. The error details are listed below, but I've also attached the output log from this gene.

-------
[CYTB_500mDeep_MEME_output.txt](https://github.com/veg/hyphy/files/15315526/CYTB_500mDeep_MEME_output.txt)

Error:
Internal error 
Constrained optimization failed, since a starting point within the domain specified for the variables couldn't be found.
Set it by hand, or check your constraints for compatibility.
Failed constraint:meme.site_tree_bsrel.Macellicephalinae_sp.beta_2:=9999.981382244154*3.729975787415313 must be in [0,10000]. Current value = 0.5388088367123185.

Function call stack
1 :  [namespace = mRjFiggH] Optimize(results, ^lf_bsrel);

-------
2 :  [namespace = mpi.VzDhMTUb] Call(result_callback,0,Eval(job+'('+Join(",",utility.Map(arguments,"_value_","utility.convertToArgumentString (_value_)"))+')'),arguments);
-------
3 :  mpi.QueueJob(meme.queue,"meme.handle_a_site",{"0":"meme.site_likelihood","1":"meme.site_likelihood_bsrel","2":alignments.serialize_site_filter((meme.filter_specification[meme.partition_index])[utility.getGlobalValue("terms.data.name")],(_pattern_info_[utility.getGlobalValue("terms.data.sites")])[0]),"3":meme.partition_index,"4":_pattern_info_,"5":meme.site_model_mapping},"meme.store_results");
-------
4 :  Call("utility.ForEachPair.CB",utility.ForEachPair.key,object[utility.ForEachPair.key]);
-------
5 :  utility.ForEachPair(meme.site_patterns,"_pattern_","_pattern_info_",'
            if (_pattern_info_[utility.getGlobalValue("terms.data.is_constant")]) {
                meme.store_results (-1,None,{"0" : "meme.site_likelihood",
                                             "1" : "meme.site_likelihood_bsrel",
                                             "2" : None,
                                             "3" : meme.partition_index,
                                             "4" : _pattern_info_,
                                             "5" : meme.site_model_mapping
                                     });
            } else {
                mpi.QueueJob (meme.queue, "meme.handle_a_site", {"0" : "meme.site_likelihood",
                                                                 "1" : "meme.site_likelihood_bsrel",
                                                                 "2" : alignments.serialize_site_filter
                                                                   ((meme.filter_specification[meme.partition_index])[utility.getGlobalValue("terms.data.name")],
                                                                   (_pattern_info_[utility.getGlobalValue("terms.data.sites")])[0]),
                                                                 "3" : meme.partition_index,
                                                                 "4" : _pattern_info_,
                                                                 "5" : meme.site_model_mapping
                                                                    },
                                                                    "meme.store_results");
            }
        ');
-------

**Comment by spond** [comment]
Dear @glitterseaworms,

These types of errors usually arise due to very long branches in the tree. However, it also seems like you are using a rather old HyPhy build (MEME version of 2.1.2, the current version is 4.0).

May I suggest that you download/install the latest HyPhy version and see if the issue goes away?

Best,
Sergei

**Comment by glitterseaworms** [comment]
Thank you Sergei! I will try this and get back to you.

**Comment by glitterseaworms** [comment]
Just want to update that the new version worked properly -- thank you so much! :-)
