### ISSUE TITLE
What is HyPhy calling the 2 nodes pointed at with arrows in this tree (image and txt file attached)?

### ISSUE THREAD

**Issue by glitterseaworms** [veg/hyphy#1711]
Hello, I could really use help determining what numbers HyPhy aBSREL is labelling 2 nodes that are important to me. I have attached an image of the tree and indicated which nodes I need numbers for with red arrows. I have also attached the input tree file and the aBSREL output file. Thank you!!
[ATP6_aBSREL_500mDeep_output.txt](https://github.com/veg/hyphy/files/15396292/ATP6_aBSREL_500mDeep_output.txt)
[HyPhy-tree-node-question.pdf](https://github.com/veg/hyphy/files/15396311/HyPhy-tree-node-question.pdf)
[4NT_14AA_Tree_56terminals_allloci_500mDeep.txt](https://github.com/veg/hyphy/files/15396330/4NT_14AA_Tree_56terminals_allloci_500mDeep.txt)

**Comment by spond** [comment]
Dear @glitterseaworms,

You can use  https://observablehq.com/@spond/absrel to view the `JSON` that aBSREL outputs. You then have the option to view internal node labels. 

<img width="862" alt="image" src="https://github.com/veg/hyphy/assets/1018513/56151ce8-3d3f-402e-9e56-f6551d8c3db1">

Best,
Sergei

**Comment by glitterseaworms** [comment]
Thank you! This is super helpful!
