### ISSUE TITLE
Persistent error when running Gard

### ISSUE THREAD

**Issue by MiloEliot** [veg/hyphy#1713]
Hello! Thank you for providing such amazing tools!

Recently, I have encountered a persistent problem while running Gard on DataMonkey. My jobs are always aborted after approximately one day without generating any log files to specify the reason. The latest job I submitted is 3954531.new-silverback. While the job is still queued for running, the result page displays an error.

I would greatly appreciate any assistance in resolving this issue.

**Comment by spond** [comment]
Dear @MiloEliot,

Could you please provide the URL for the `datamonkey` job that failed (rather than the ticket)?

Best,
Sergei

**Comment by MiloEliot** [comment]
Hello! Thank you for your reply. Here is the link to the job: http://datamonkey.org/gard/66523af79c7e3231770f9374

**Comment by stevenweaver** [comment]
Dear @MiloEliot, 

The error listed in our system indicates that this job exceeded the job limit of 72 hours. 

> PBS: job killed: walltime 259207 exceeded limit 259200

In situations like this, it's recommended that you run the job locally or reduce the dataset. 

Best,
Steven

**Comment by MiloEliot** [comment]
Hello! Thanks a lot for the troubleshooting and the suggestion. I will try to run it locally.
