### ISSUE TITLE
error

### ISSUE THREAD

**Issue by vitt2022** [veg/hyphy#1716]
I used FUBAR and MEME by uploading the nwk tree. But the error as attached. Could you help?
Error: "An unexpected error occured when parsing the sequence alignment!"
![Capture](https://github.com/veg/hyphy/assets/107045565/7b712ac5-49ae-4502-a05c-9cbcee3fb692)

**Comment by spond** [comment]
Dear @vitt2022,

Our system does not retain failed uploads, so in order for me to provide a meaningful answer, I'd need to see the file you have been trying to upload. If you are comfortable sharing it, please upload it here, or send it to me by e-mail.

Best,
Sergei

**Comment by spond** [comment]
Dear @vitt2022,

GitHub does not forward attachments to e-mails to message boards, so, unfortunately I cannot see your file.  Please use the browser to attach the file to a message.

However, could you please confirm that what you are uploading is an **alignment** with a **tree**, and not just the tree? Datamonkey requires coding sequence alignment data (+ tree) for all of its analyses.

Best,
Sergei

**Comment by vitt2022** [comment]
Thanks Sergei,

Could you please show me where I can put the alignment data and tree? I only see the Browse icon and it just allows for 1 file, either fasta or tree, not both at the same time.

Many thanks,
Vi

On 6 Jun 2024, at 02:59, Sergei Pond ***@***.***> wrote:

﻿

Dear @vitt2022<https://github.com/vitt2022>,

GitHub does not forward attachments to e-mails to message boards, so, unfortunately I cannot see your file. Please use the browser to attach the file to a message.

However, could you please confirm that what you are uploading is an alignment with a tree, and not just the tree? Datamonkey requires coding sequence alignment data (+ tree) for all of its analyses.

Best,
Sergei

**Comment by spond** [comment]
Dear @vitt2022,

`Datamonkey` expects a single file including the alignment and the tree. You can submit them as `FASTA`, `phylip`, `MEGA`, `NEXUS` or any other support format. I attach an example file.

Best,
Sergei

[lysozyme.fas.txt](https://github.com/user-attachments/files/15615269/lysozyme.fas.txt)

**Comment by vitt2022** [comment]
Dear Sergei,

I still got the same problem when I upload the tree. Could you instruct me how to fix it?

Many thanks,
Thuy Vi.
