### ISSUE TITLE
Analysis ends but does not progress to report generation

### ISSUE THREAD

**Issue by hkunerth** [veg/hyphy#1717]
I'm having an issue running SLAC on the datamonkey server. Typically an analysis takes 10-15 minutes for my dataset, then advances to the report screen where I can view results and download the statistics table. 

A recent dataset seems to hang up after 20 minutes and does not advance to this screen. The job will seem to still be running but if I open up the job queue it will have disappeared. I also do not get any results emailed to me. 

The ticket number is 3961521.new-silverback for the latest run, but this has happened 2-3 times

**Comment by spond** [comment]
Dear @hkunerth,

Would you please let us know what the URL for the job is? It's a bit tricky matching ticket numbers with the job logs. 

Best,
Sergei

**Comment by hkunerth** [comment]
For sure,

It's 

https://www.datamonkey.org/slac/6661f0ba9c7e3231771274ab

Like I said, it still says that it's running but is no longer in the job queue and is taking 10x the time of similar sized jobs I recently submitted, so I suspect it's actually frozen up.

**Comment by stevenweaver** [comment]
Dear all, 

This is an actual bug due to excessive JSON size. 

The results can be found [https://data.hyphy.org/web/datamonkey/6661f0ba9c7e3231771274ab.SLAC.json](here) and can be visualized with http://vision.hyphy.org/slac.

Best,
Steven

**Comment by hkunerth** [comment]
Thanks much!!
