### ISSUE TITLE
test for detecting compartmentalization in dataMonkey

### ISSUE THREAD

**Issue by BlasiMar** [veg/hyphy#1719]
Hi, 
Which test should I use in datamonkey to determine if a cluster of sequences is compartmentalized compared to other sequences in the same phylogenetic tree?

**Comment by spond** [comment]
Dear @BlasiMar,

If you have a tree where sequences that can be separated into groups, you could use the `Slatkin-Maddison` test,  see https://github.com/veg/hyphy-analyses/tree/master/SlatkinMaddison

Best,
Sergei
