### ISSUE TITLE
DataMonkey not recognizing forground branches

### ISSUE THREAD

**Issue by ebraun68** [veg/hyphy#1720]
A student is using aBSREL on the Datamonkey server, using a tree with branches labeled as {foreground}. She has had two crashes with the file and I decided to try running her file myself. However, when I loaded the file the branches were not labeled. I tried changing the branch labels to {Foreground} but that did not work either. The student's run when further. I can send the file if that would be helpful

**Comment by spond** [comment]
Dear @ebraun68,

Sorry you are having issues. Yes, please send the file (aligment+tree). Remember that GitHub does not forward e-mail attachments, so please post the file as an attachment via a web form.

Best,
Sergei
