### ISSUE TITLE
MEME interpretation - 0 branches?

### ISSUE THREAD

**Issue by glitterseaworms** [veg/hyphy#1721]
Hello, I was wondering if we should not consider codon sites that have significant p-values but have 0 branches listed? For example:
Based on the likelihood ratio test, episodic diversifying selection has acted on 1 sites in this dataset (p≤0.05).
|   Codon    | Partition  |   alpha    |non-syn rate (beta) distribution, rates : weights|    LRT     |Episodic selection detected?| # branches |         List of most common codon substitutions at this site          |
|:----------:|:----------:|:----------:|:-----------------------------------------------:|:----------:|:--------------------------:|:----------:|:---------------------------------------------------------------------:|
|    168     |     1      |    0.120   |            0.05/2808.48 : 0.00/1.00             |   15.009   |      Yes, p =  0.0002      |     0      |          [1]GTt>AAt,GTt>TAt,GTT>TCC,GTt>TCt,TCT>AAC,tcT>tcC           |

**Comment by spond** [comment]
Dear @glitterseaworms,

This is a bit counterintuitive, but here's an explanation. For the site you provide as an example, `MEME` allocates 100% of the available &omega; weight to the positive selection regime: &beta; = 2808.49. 

When MEME calculates which, if any, branches may be subject to selection, it attempts to estimate a Bayes Factor (empirical Bayes), that &beta; > &alpha; (or &omega; > 1) at that branch. However, the PRIOR probability for &omega; > 1 is estimated to be exactly 1, which makes the prior odds (needed to calculate Bayes Factors) infinite. So `MEME` cannot calculate a Bayes Factor for sites where all the weight is assigned to &beta; > &alpha;, and you end up with the `0` estimate.

Hope this helps,
Sergei

**Comment by glitterseaworms** [comment]
Ah ok thanks for the explanation. In that case, would you say it is reasonable to hypothesize that the site may still be under diversifying selection then?

**Comment by glitterseaworms** [comment]
Thank you kindly for your help. I really appreciate you!
