### ISSUE TITLE
How to choose background branches?

### ISSUE THREAD

**Issue by Buckaroo1** [veg/hyphy#1724]
Dear Developer,

I am currently using aBSREL to detect PSGs in a species that lives in the desert, with the goal of identifying genes that facilitate adaptation to desert environments.

I am uncertain about the selection of background species for this analysis. Specifically, how many and what types of species should be included? I have not been able to find any papers that provide guidance on this matter.

One approach I am considering is to exclude any desert species from the background branches. Could you please advise if this is a beneficial strategy? If so, could you explain why it is effective and what the potential benefits are?

Thank you for your efforts in developing and maintaining Hyphy.

Best regards,
Buckaroo1

**Comment by stevenweaver** [comment]
Dear @Buckaroo1, 

Considering the context of your research question, aBSREL may not be the most suitable as it tests for selection on each branch _individually_. Please see this [thread](https://github.com/veg/hyphy/issues/1542#issuecomment-1312089233) for recommendations. 

Alternative Methods:

	1.	BUSTED-PH : This method is suitable if you have a clear hypothesis about selection differences between foreground (desert species) and background (non-desert species) branches.
	•	Benefit: It explicitly tests for differences in selection pressures between specified groups of branches.
	2.	RELAX: This method tests whether selection is relaxed or intensified along branches of interest compared to background branches.
	•	Benefit: Useful for identifying changes in selective pressure intensity, rather than just positive selection.
	3.	Contrast-FEL (Fixed Effects Likelihood): This method allows for site-by-site comparison of selection pressures between foreground and background branches.
	•	Benefit: Identifies individual sites with different selective regimes between groups.

Practical Recommendations:

	•	Diverse Background: Include various non-desert species to enhance contrast. For example, not only include species from the same genus that live in other environments, but also a broader phylogenetic tree that includes a representative species from the same family. Please see this [detailed comment](https://github.com/veg/hyphy/issues/1635#issuecomment-1663047100) for more recommendations for dataset construction.
	•	Exploratory Testing: Use aBSREL for an exploratory approach where each branch is tested independently.

Best,
Steven

**Comment by Buckaroo1** [comment]
Dear @stevenweaver ,

Thank you for your prompt and detailed response. Your explanation has given me a clearer understanding of how to choose a background branch.

I am intrigued by your suggestion to "include various non-desert species to enhance contrast." Could you elaborate on why using non-desert species, as opposed to desert species, would enhance contrast? If possible, could you provide some references or examples to illustrate this point?

Thank you once again for your assistance.

Best regards,
Buckaroo1
