### ISSUE TITLE
FADE: substitution model selection

### ISSUE THREAD

**Issue by ewysocka** [veg/hyphy#1727]
Hello, 

To begin with, many thanks for developing this great evolutionary selection package suit. 
I have some questions regarding the choice of the model to run FADE with via datamonkey.org.
To select the model for the tree reconstruction, I used modeltest. It indicated JTT as the best one based on AICc score. 
I used this reconstructed tree and alignment on FADE with three different models: LG, JTT and GTR. I compared AICc results. GTR got the best (lowest) score among them.

MODEL  |   AICc
GTR  |    24 041.94
JTT |  24 236.06
LG |  24 542.52

The number of sites differs depending on the model used (LG - 14 sites, JTT - 9 sites and GTR - 6 sites; 5 sites overlap). As mentioned in Kosakovsky Pond et al. 2008, GTR model reduces power together with false positives. I mentioned this because there is a site which overlaps in the results with JTT and LG models, but not with GTR, which was also detected by MEME and BUST.

Which AICc value should I follow when selecting the results, the one from modeltest or the FADE output? There is no big difference since the results overlap but I was wondering about the relations/difference between these AICc scores. 

Many thanks in advance,
Emilia

**Comment by spond** [comment]
Dear @ewysocka,

Sorry for not responding sooner. 

Generally, I would strongly suggest the use of `GTR` here. Otherwise, the danger is that FADE is simply detecting deviations from a "poor-fit" baseline model. 

In your case, `AIC-c` is also strongly suggestive of using the `GTR` model.

Best,
Sergei

**Comment by ewysocka** [comment]
Dear @spond,
Many thanks for your reply!

Cheers,
Emilia
