### ISSUE TITLE
Multi-ORF Analysis Questions

### ISSUE THREAD

**Issue by singing-scientist** [veg/hyphy#1728]
Greetings! I have questions related to the best approach for a multi-ORF analysis, similar to [this issue.](https://github.com/veg/hyphy/issues/1524)

I have a low-diversity (2/3 invariant sites, π ~ 0.01) virus alignment that I have determined is not subject to recombination, and I want to use MEME. I therefore believe it is best to build a tree on the full genome alignment (~4500 unique genome sequences, 8000 bp each, 9 ORFs). May I ask the recommended strategy for going about this? My guess is:

1. build a whole-genome tree using full set of unique genomes (e.g., using raxml-ng)
2. ‘slice’ each ORF out of the alignment based on its start and end positions. As a result, many ORFs will now have non-unique (duplicate) sequences, but I believe this should not change the results (is that correct?)
3. run MEME separately for each ORF that has been sliced out, using the same (whole-genome based) tree for each run

I'd be grateful to know if this makes sense, or if there is a cleaner/more standard way to use HyPhy for such an application. One alternative might be to first extract a set of unique sequences for each ORF and perform the whole pipeline separately for each ORF (tree-building, HyPhy). I believe this is inferior because single ORFs provide less information about tree topology, and could reduce power because e.g. they’d fail to detect homoplasies, say, changes which are clearly recurrent/parallel from looking at the whole genome tree but which are more parsimoniously but erroneously explained by fewer changes in a single-ORF tree.

Thanks so much for your help!
Chase

**Comment by spond** [comment]
Dear @singing-scientist,

Sorry, was away on vacation. Your process seems sensible. Given the expectation that a lot of sequences will likely be identical for each ORF, I'd suggest you run https://github.com/veg/hyphy-analyses/tree/master/remove-duplicates on each ORF alignment + whole-genome tree to trim the duplicates and the tree.

If there's no recombination, using the WG sequences to build a "master" tree would be my suggestion as well (for the reasons you articulated).

Best,
Sergei

**Comment by singing-scientist** [comment]
Dear @spond thank you so much for the wonderfully useful script and the helpful feedback, much obliged!

Yours,
Chase
