### ISSUE TITLE
Barely any parallelism (max 110% CPU) running `hyphy gard` on macOS arm64

### ISSUE THREAD

**Issue by corneliusroemer** [veg/hyphy#1730]
Is it expected that there's hardly any parallelism when running hyphy gard on macOS arm64?

I tried both: self-compiled from source and bioconda builds and I get at most around 110% CPU usage.

Repro:

```
hyphy gard --alignment sample.fasta.txt --mode Faster
```

with this file: [sample.fasta.txt](https://github.com/user-attachments/files/16604162/sample.fasta.txt)

<img width="1265" alt="image" src="https://github.com/user-attachments/assets/6f1ad78d-5df4-4950-847d-75be1ac92e92">

I expected parallelism based on, e.g., this sentence in the [paper](https://academic.oup.com/bioinformatics/article/22/24/3096/208339):
> GARD outperforms other methods and can be run in parallel on a cluster of computers, and so is well suited to screen for recombination in large datasets.

As the algorithm should be pretty easy to parallelize I suspect there's some issue on macos. I'll check whether x86-64 has the same issue (when run through Rosetta2).

**Comment by corneliusroemer** [comment]
When I use the osx-64 binary from bioconda and run through Rosetta2, I _do_ get parallelism:

<img width="836" alt="Hyper 2024-08-13 21 14 14" src="https://github.com/user-attachments/assets/043b6cd3-e4b0-427c-920c-c855dc5f9ccc">

That suggests there's an issue with osx-arm64 specifically. Note that I tried both: the bioconda package (which I made available yesterday) _and_ having compiled from source.

**Comment by spond** [comment]
Dear @corneliusroemer,

GARD benefits from MPI distributed environments, and not that much from multi-threading. If you have `openmpi` installed, run `make MPI` and then `mpirun -np N HYPHYMPI gard ...` where `N` is the number of cores on your system.

Best,
Sergei
