### ISSUE TITLE
Error when install hyphy using `conda install -c bioconda hyphy`?

### ISSUE THREAD

**Issue by liamxg** [veg/hyphy#1735]
Dear @spond,

please see below:

```
conda install -c bioconda hyphy
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/osx-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

'https//repo.anaconda.com/pkgs/main/osx-64'
```

**Comment by spond** [comment]
Dear @liamxg,

That seems to be an issue with accessing conda repos from your site, not something we have any control over. Sorry.

Best,
Sergei

**Comment by spond** [comment]
Dear @liamxg,

Haven't seen this one before. 

Can you check to see if `/usr/local/bin/hyphy` is actually there and is new (i.e. `ls -alt /usr/local/bin/hyphy`)?

It could be that the install process actually completed and the error can be ignored.

Best,
Sergei

**Comment by spond** [comment]
Dear @liamxg,

Looks like it got installed. What do you see when you type `hyphy --version`?

Best,
Sergei

**Comment by spond** [comment]
Dear @liamxg,

Looks good. Now do

```
make MPI
make install
```

and check that 

```
HYPHYMPI --version
```

works as well.

Best,
Sergei

**Comment by spond** [comment]
Dear @liamxg,

Try 

```
rm -rf CMakeFiles CMakeCache.*
cmake ./
make 
make MPI
make install
```

Best,
Sergei
