### ISSUE TITLE
MEME HyPhy killed by signal 15

### ISSUE THREAD

**Issue by moonless00** [veg/hyphy#1736]
Greetings
I'm trying to use MEME 
since i am using more than 500 sequences i've included a tree in my nexus file
however i keep getting this error

MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[n8:53919] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

I've tried switching tree formats to newick, using fasta instead of nexus, erasing all "illegal" characters however, i can't get it work.
any ideas what might be the issue?
also, my sequence file does not have a line 1741

thanks in advance, much appreciated

**Comment by spond** [comment]
Dear @moonless00,

Are you seeing this on Datamonkey? 

Best,
Sergei

**Comment by moonless00** [comment]
Hello @spond,

Yes, I'm using Spidermonkey/BGM from Datamonkey


Cheers,
Chris

**Comment by moonless00** [comment]
Dear @spond,
Thank you for your attention.
Here are some links generated featuring the same error.

https://www.datamonkey.org/meme/66c42d2e77e7f73ceb44f21c
https://www.datamonkey.org/meme/66ce78cdde2c0658debf7a78
https://www.datamonkey.org/meme/66ce791cde2c0658debf7d09
https://www.datamonkey.org/meme/66ce794cde2c0658debf7f8d

Thanks again,
Chris
