### ISSUE TITLE
The dN/dS ratio shows a significant difference between the foreground and background sets. Why is the result still that selection is not associated with the phenotype/trait?

### ISSUE THREAD

**Issue by uyghbo** [veg/hyphy#1737]
Hi team,

When using BUSTED-PH/contrast-fel to detect directional selection pressure, I found the overall dn/ds values are significantly differed in foreground and background genes. However, the results show no evidence of directional selection pressure.

The gene I tested is a drug-resistance-related gene. The foreground strains are exposed to antibiotics.

examples:

### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
* Log(L) =  -451.54, AIC-c =  1127.25 (111 estimated parameters)
* 1 partition. Total tree length by partition (subs/site)  0.006
* non-synonymous/synonymous rate ratio for *background* =  17.0016
* non-synonymous/synonymous rate ratio for *test* =   0.8900

### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
* Log(L) =  -451.49, AIC-c =  1127.16 (111 estimated parameters)
* non-synonymous/synonymous rate ratio for *background* =  23.2139
* non-synonymous/synonymous rate ratio for *test* =   0.8081

## Branch-site unrestricted statistical test of episodic diversification and association with phenotype/trait [BUSTED-PH]
Likelihood ratio test for episodic diversifying positive selection on test branches , **p =   0.5000**.
Likelihood ratio test for episodic diversifying positive selection on background branches , **p =   0.2752**.
Likelihood ratio test for differences in distributions between **test** and **background** , **p =   1.0000**.

## Analysis summary (p = 0.05)
There is **no evidence** of episodic diversifying selection on test branches; selection is not associated with phenotype/trait

**Comment by uyghbo** [comment]
Dear Dr. Sergei L Kosakovsky Pond and Team,

When I use contrast-fel to detect directional selection pressure at the site level, I do find many sites with differences between the foreground and background. However, the BUSTED-PH method detects very few differences at the gene level. Can I use the genes with site-level differences detected by the contrast-fel method to perform functional annotation (such as KEGG/GO) to characterize the pathway differences targeted by the selection pressure in the foreground and background?

**Comment by spond** [comment]
Dear @uyghbo,

Based on what I see, you have a very small, low divergence (<0.01 subs/site) alignment. You probably also have very few branches in the foreground/background test. This means that point estimates of &omega; are very imprecise and are **not** significantly different from each other. 

Can you elaborate what you see with `contrast-fel`? My guess would be that there should be no significantly different sites there either.

Best,
Sergei
