### ISSUE TITLE
Error on MEME

### ISSUE THREAD

**Issue by andrearam28** [veg/hyphy#1741]
Hello,

I am trying to run MEME on HPC on several fasta file but I'm getting this error:

Error:Illegal right hand side in call to Topology id = ...; it must be a string, a Newick tree spec or a topology
Illegal right hand side in call to Topology id = ...; it must be a string, a Newick tree spec or a topology

Is this something to do with my files or the order of the arguments? I did check my fasta files and nothing seems to be out of the ordinary.

This is how I'm trying to run it:

hyphy meme --alignment filename.fasta --output filename.fasta.json 

Thanks,
Andrea

**Comment by spond** [comment]
Dear @andrearam28,

Sounds like there's a tree formatting issue. Can you share `filename.fasta` which is triggering the error?

Best,
Sergei

**Comment by andrearam28** [comment]
Dear Sergei,

Yes, sir, thank you for the help. I am attaching them as .txt files since I got a message about .fasta files not being accepted.

I am not sure which file is giving me the error since I am trying to loop them, however I do have two fasta formats. Please see attached.

[sim_751_4.txt](https://github.com/user-attachments/files/16769740/sim_751_4.txt)
[sim_752_10.txt](https://github.com/user-attachments/files/16769741/sim_752_10.txt)

Thanks,
Andrea

**Comment by spond** [comment]
Dear @andrearam28,

Odd error (what is your HyPhy version?)

I get this [also note the warning re: duplicate sequences]

```
-------
>[WARNING] '/Users/sergei/Downloads/sim_751_4.txt' contains 216
duplicate sequences. Identical sequences do not contribute any
information to the analysis and only slow down computation. Please
consider removing duplicate or 'nearly' duplicate sequences, e.g. using
https://github.com/veg/hyphy-analyses/tree/master/remove-duplicates
prior to running selection analyses
-------


>Please select a tree file for the data: (`/Users/sergei/Development/hyphy/`) 
```

The files you attached have **no tree** in them. `HyPhy` does not automatically build trees, so you should provide one (e.g. inferred using `raxml` or `iqtree` etc). 

You could ask HyPhy to build a very crude neighbor-joining tree, like so, but in most cases I would not recommend it.

```
./hyphy meme --alignment ~/Downloads/sim_751_4.txt --tree neighbor-joining
```

Best,
Sergei

**Comment by andrearam28** [comment]
Hi @spond,

Thank you for the info and advice.

I am using hyphy version 2.5.33. I added the --tree and it looks like it is working great now!

Thanks again,
Andrea
