### ISSUE TITLE
GARD error on Datamonkey

### ISSUE THREAD

**Issue by thersyl** [veg/hyphy#1742]
I am trying to use GARD on an alignment of 86 MHC-II sequences, but I keep getting an error as soon as i submit it.
The URL is here:
https://www.datamonkey.org/gard/66d812dede2c0658dec0644b
I tried using a different FASTA document as well, but the result is the same.

I will try to use it locally in the meantime, but since the GUI versions are no longer available, it will take me much longer as I'm not too familiar with command line.

**Comment by spond** [comment]
Dear @thersyl,

Hidden behind the "download log" button, there's a more informative message

```
...

>Loaded a nucleotide multiple sequence alignment with **85** sequences, **258** sites (99 of which are variable) from `/home/datamonkey/datamonkey-js-server/production/app/gard/output/66d812dede2c0658dec0644b`
>Minimum size of a partition is set to be 167 sites
Error:

Master node received an error:The alignment is too short to permit c-AIC based model comparison. Need at least 341 sites for 85 sequences to fit a two-partiton model. in call to assert(gard.minExpectedSites<=gard.numSites, error_msg);
```

The underlying method requires a number of sites that grows as a function of the number of sequences (`341` in this case), and your alignment is simply too short. Generally, recombination detection on short alignments using GARD is not going to work too well, unless the # of sequences is small.

If you want GARD to work, prune some of the sequences out (e.g. using the approach https://github.com/veg/hyphy/issues/1448). 

I tried your data with (reducing to 34 sequences).

```
tn93-cluster -f -t 0.05 gard.fas > clusters.json
```

There seems to be one breakpoint 

<img width="686" alt="image" src="https://github.com/user-attachments/assets/b065cbf6-6166-4925-a1d8-c743782b2f88">


<img width="735" alt="image" src="https://github.com/user-attachments/assets/cbdbe3c8-ff32-4fb9-a581-07c5eec0d55c">

I don't want to share the reduced file here in case you have concerns about having it the public domain. Datamonkey will run the reduced file.

Best,
Sergei

**Comment by thersyl** [comment]
Thank you for the explanation, I didn't notice the additional info in the log. I am having issues with using HyPhy locally, but I hope I can make it work!

**Comment by spond** [comment]
Dear @thersyl,

Let me know what type of issues you are having. Maybe it's something that I can give you hints about.

Best,
Sergei

**Comment by thersyl** [comment]
Hello Sergei,
I was not able to install HyPhy on my PC, I got several errors while trying to clone it. But I found an alternative software that can detect recombination, so I am giving up on HyPhy for now. Thank you for your offer in any case.
