### ISSUE TITLE
MEME EBFs vs # branches

### ISSUE THREAD

**Issue by dcaffrey** [veg/hyphy#1743]
Dear Spond

I have a MEME json result file that does not report any EBFs. I confirmed this by uploading it to http://vision.hyphy.org/MEME. 

In a prior post you say:
"If you are asking why a particular site has a significant p-value without any individual branch showing up as having high EBF, that's quite common and simply refers to the case of "diffuse" support.

However, the sites table in my json also contains several codons where the # branches is greater than 0. I was under the impression that the # branches referred to the number of branches/nodes for the site where the EBF was greater than  a certain threshold e.g. 100 and would be worthy of reporting as a high EBF.  Is this not the case?  Why are the EBFs not reported when the # branches is > 0?

Thanks!

**Comment by spond** [comment]
Dear @dcaffrey,

Not sure, possibly a version problem. Would you be able to e-mail / upload the `.json` file so that I can check?

Best,
Sergei

**Comment by spond** [comment]
Resolved via e-mail. MEME version is too new for http://vision.hyphy.org/MEME 

Use https://observablehq.com/@spond/meme instead.
