### ISSUE TITLE
Inconsistent results from MEME

### ISSUE THREAD

**Issue by katherinermartin** [veg/hyphy#1744]
Hi there,

I ran MEME on a dataset in December 2023. When I ran it again yesterday, I got slightly different results: no sites were identified as evolving under positive selection in December 2023. Yesterday, MEME identified one site evolving under positive selection. For both analyses, I used a p-value threshold of 0.05.

I'm attaching the input dataset (`monomorphic_input_for_HyPhy.txt`) and the `.json` files for both the December 2023 run and the September 2024 run.

Just curious more than anything. Thank you!

[December2023.json](https://github.com/user-attachments/files/16966931/December2023.json)
[September2024.json](https://github.com/user-attachments/files/16966955/September2024.json)
[monomorphic_for_HyPhy.txt](https://github.com/user-attachments/files/16966935/monomorphic_for_HyPhy.txt)

**Comment by spond** [comment]
Dear @katherinermartin,

There was a version change in HyPhy (2.5.58 vs 2.5.61) between these two. For some reason ther number of tested branches changed between the two analyses  (not sure why, but that could affect the level of support).

<img width="688" alt="image" src="https://github.com/user-attachments/assets/2ce5dd2a-2a94-4c22-a42f-c3cea281f520">

<img width="677" alt="image" src="https://github.com/user-attachments/assets/e49411de-f814-4d70-93e2-19e43f1db408">

In any case, the putatively selected site is only showing one change, but along a very short branch. These types of scenarios could also be a bit numerically unstable.

<img width="793" alt="image" src="https://github.com/user-attachments/assets/ce36c752-e248-4445-9466-7605924666e7">

I just ran the alignment using the current HyPhy version (`2.5.62`) and got one site as well

```
### For partition 1 these sites are significant at p <=0.1

|   Codon    | Partition  |   alpha    |non-syn rate (beta) distribution, rates : weights|    LRT     |Episodic selection detected?| # branches |         List of most common codon substitutions at this site          |
|:----------:|:----------:|:----------:|:-----------------------------------------------:|:----------:|:--------------------------:|:----------:|:---------------------------------------------------------------------:|
|     45     |     1      |    0.000   |             0.00/135.30 : 0.50/0.50             |    4.737   |      Yes, p =  0.0432      |     1      |                              [1]gaC>gaG                               |

### ** Found _1_ sites under episodic diversifying positive selection at p <= 0.1**

```

Best,
Sergei
