### ISSUE TITLE
Constrained optimization failed, since a starting point within the domain specified for the variables couldn't be found. Failed constraint:relax.ge.omega2

### ISSUE THREAD

**Issue by fuesseler** [veg/hyphy#1745]
Dear Hyphy Team,
Thanks for developing and maintaining this great set of tools!
I've been trying to run RELAX on ~14k ortholog alignments, from 6 species.

I installed the newest version from source: 
HYPHY 2.5.62(MP) for Linux on x86_64 x86 SSE4 SIMD zlib (v1.2.11)
(had to turn off AVX support due to our cluster architecture)

Unfortunately, I get the following error for some alignments:

`Error:
Internal error 
Constrained optimization failed, since a starting point within the domain specified for the variables couldn't be found.
Set it by hand, or check your constraints for compatibility.
Failed constraint:relax.ge.omega2:=1/0.4549925633717588 must be in [0,10000]. Current value = 1.
`

The command I run as such:
`$HYPHY ENV="TOLERATE_NUMERICAL_ERRORS=1;" relax --alignment ${INDIR}/"$outname".pal2nal.clipkit.aln.renamed --tree ${TREEDIR}/"$outname".lb.tree --test Foreground --reference Background --srv Yes --output ${OUTDIR}/"${outname}.srv_gt.RELAX.json" > ${OUTDIR}/"${outname}.srv_sptree.RELAX.log" 2>&1
`
The same alignments work fine when I am running ABSREL on them.

Do you have any suggestions on what I might try for these to work? I would be grateful for any insights!

**Comment by spond** [comment]
Dear @fuesseler,

This is an edge case of some sort. Unfortunately they don't follow predictable patterns, and I'd need to see the data to be able to give you meaningful feedback. Would you mind sharing the `--alignment` and `--tree` files?

When you see errors like this it's because one of the parameters managed to run away into an off-limits part of the parameter space: too large, too small, or something totally whacky like `nan`.  That is usually caused by something like mishandled sequence/tree mapping (due to unusual characters or something like that in sequence names), long tree branches, or mishandling of automatically trimmed zero-length internal branches.

Best,
Sergei

**Comment by fuesseler** [comment]
Dear Sergei,
Thanks for the quick response!. Sure I can send you a few files that failed - do you have an email address I can send them to?

Best,,
Flora

**Comment by spond** [comment]
Dear @fuesseler,

Sure, use spond at temple dot edu

Best,
Sergei

**Comment by spond** [comment]
Dear @fuesseler,

Thanks for sharing the files. Unfortunately, I am unable to replicate the issue using the current `hyphy` build on a MacOS X M1 chip. All three example files run to completion, repeatedly. 

Would you be able to provide the `stdout` for one of the failed runs on your system? I want to see where the failure occurs.

```
hyphy relax --test Foreground --reference Background --srv Yes ENV="TOLERATE_NUMERICAL_ERRORS=1;" --alignment ${GENE}.pal2nal.clipkit.aln.renamed --tree ${GENE}.lb.tree
```

----
OG10259

## Test for relaxation (or intensification) of selection [RELAX]
Likelihood ratio test **p =   0.3393**.
>No significant evidence for relaxation (or intensification) of selection among **test** branches _relative_ to the **reference** branches at P<=0.05

----
OG1017

## Test for relaxation (or intensification) of selection [RELAX]
Likelihood ratio test **p =   0.9195**.
>No significant evidence for relaxation (or intensification) of selection among **test** branches _relative_ to the **reference** branches at P<=0.05

----
OG10050

## Test for relaxation (or intensification) of selection [RELAX]
Likelihood ratio test **p =   0.9525**.
>No significant evidence for relaxation (or intensification) of selection among **test** branches _relative_ to the **reference** branches at P<=0.05

Best,
Sergei

**Comment by fuesseler** [comment]
Thanks for looking into it! Here is the stdout for OG10259. As far as I can see, the problem arises at the same point, but only for a subset of alignments.

Best,
Flora

> multiple-files: No
Analysis Description
--------------------
RELAX (a random effects test of selection relaxation) uses a random
effects branch-site model framework to test whether a set of 'Test'
branches evolves under relaxed selection relative to a set of
'Reference' branches (R), as measured by the relaxation parameter (K).
Version 2.1 adds a check for stability in K estimates to try to mitigate
convergence problems. Version 3 provides support for >2 branch sets.
Version 3.1 adds LHC + Nedler-Mead initial fit phase and keyword
support. Version 3.1.1 adds some bug fixes for better convergence.
Version 4.0 adds support for synonymous rate variation. Version 4.1 adds
further support for multiple hit models. Version 4.1.1 adds reporting
for convergence diagnostics. Version 4.5 adds support for multiple
datasets for joint testing.
- __Requirements__: in-frame codon alignment and a phylogenetic tree, with at least two
groups of branches defined using the {} notation (one group can be
defined as all unlabeled branches)
- __Citation__: RELAX: Detecting Relaxed Selection in a Phylogenetic Framework (2015).
Mol Biol Evol 32 (3): 820-832
- __Written by__: Sergei L Kosakovsky Pond, Ben Murrell, Steven Weaver and Temple iGEM /
UCSD viral evolution g
- __Contact Information__: spond@temple.edu
- __Analysis Version__: 4.5
>code => Universal
/work/uesseler/workdir_hyphy/labelled_genetrees/RELAX_AmbCri/OG10259.lb.tree
/work/uesseler/workdir_hyphy/labelled_genetrees/RELAX_AmbCri/OG10259.lb.tree
>Loaded a multiple sequence alignment with **6** sequences, **396** codons, and **1** partitions from `/work/uesseler/old_OMA_workdir/DownstreamProcessing/bestiso_fork/workdir_codon_alignments/codon_alignments_pal2nal/output_transfercleaner/output_clipkit/OG10259.pal2nal.clipkit.aln.renamed`
>mode => Classic mode
>test => Foreground
The number of points in the initial distributional guess for likelihood fitting (permissible range = [1,10000], default value = 250, integer): 
>grid-size => 250
The number of initial random guesses to 'seed' rate values optimization (permissible range = [1,25], default value = 1, integer): 
>starting-points => 1
### Branch sets for RELAX analysis
>multiple-hits => None
* Selected 8 branches as the _Reference_ set: `Node3, Node5, Node7, rAnoCar, rCacDef, rConSub, rCtePal, rCycPin`
* Selected 1 branches as the _Test_ set: `rAmbCri`
The number omega rate classes to include in the model (permissible range = [2,10], default value = 3, integer): 
>rates => 3
>models => All
>srv => Yes
The number omega rate classes to include in the model (permissible range = [1,10], default value = 3, integer): 
>syn-rates => 3
### Obtaining branch lengths and nucleotide substitution biases under the nucleotide GTR model
>kill-zero-lengths => Yes
* Log(L) = -2989.18, AIC-c =  6012.44 (17 estimated parameters)
* 1 partition. Total tree length by partition (subs/site)  0.403
### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
* Log(L) = -2812.41, AIC-c =  5675.37 (25 estimated parameters)
* 1 partition. Total tree length by partition (subs/site)  0.502
* non-synonymous/synonymous rate ratio for *Reference* =   0.1560
* non-synonymous/synonymous rate ratio for *Test* =   0.2097
### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
* Log(L) = -2804.50, AIC-c =  5659.55 (25 estimated parameters)
* 1 partition. Total tree length by partition (subs/site)  0.585
* non-synonymous/synonymous rate ratio for *Reference* =   0.1225
* non-synonymous/synonymous rate ratio for *Test* =   0.3278
### Fitting the general descriptive (separate k per branch) model
Error:
Internal error 
Constrained optimization failed, since a starting point within the domain specified for the variables couldn't be found.
Set it by hand, or check your constraints for compatibility.
Failed constraint:relax.ge.omega1:=1e-08/2.265314117401285 must be in [1e-08,1]. Current value = 4.414398834662173e-09.
Function call stack
1 :  [namespace = sLucyADg] Optimize(mles, ^lf_id);
	Keyword arguments:
		{
		 "reference":"Background"
		}
-------
2 :  relax.general_descriptive.fit=estimators.FitExistingLF(relax.general_descriptive.fit[terms.likelihood_function],relax.model_object_map);
	Keyword arguments:
		{
		 "reference":"Background"
		}
-------
Check errors.log for execution error details.

**Comment by spond** [comment]
Dear @fuesseler,

I'd like to see if I can replicate the issue in an environment similar to yours. Would you mind sharing 

1. The output of `hyphy --version`?
2. Which OS are you using?
3. If you are using a queuing system, what configuration are you giving HyPhy

Assuming (3) is a 'Yes'. what happens if you run the `RELAX` analysis interactively from the shell?

When `HyPhy` aborts an analysis, it may write `/tmp/hyphy.xxx` log file. If one is present, could you e-mail it to me?

Best,
Sergei

**Comment by fuesseler** [comment]
Dear Sergei,

> 1. The output of hyphy --version?

HYPHY 2.5.62(MP) for Linux on x86_64 x86 SSE4 SIMD zlib (v1.2.11)

> 2. Which OS are you using?

Operating System: Debian GNU/Linux 12 (bookworm)  
          Kernel: Linux 6.1.0-23-amd64
    Architecture: x86-64

> 3.   If you are using a queuing system, what configuration are you giving HyPhy

I am using SLURM. In each job array hyphy is run for 50 alignments in parallel with srun, with a total of 50 CPUs and a total of 5G RAM (100M per CPU) shared among them. 

#SBATCH --nodes=1
#SBATCH --ntasks=50
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=100M
#SBATCH --time=0-01:00:00
#SBATCH --array=1-281%10

I tested OG10259 now both with interactive hyphy and by launching this gene separately via my hyphy bash script - it ran without problem in both cases now. I tested it for 3 other alignments and it runs smoothly like this in each case.
Maybe, when I launch the 50 hyphy runs in parallel with srun, there is some issue with memory? I don't get any indications for OOM errors though.  I will try setting the memory resources higher and rerun the whole parallelization script to see if this solves the issue.

**Comment by fuesseler** [comment]
Dear @spond ,
Unfortunately, supplying more memory (1G per cpu, so in total 50G) doesn't change the behaviour. I do notice, that it's not  the same alignments that throw the error when I rerun RELAX, but different alignments.
I also tried constraining the jobs to run only on intel CPUs (as we have a mixture of compute node architecture with AMD Epyc and Intel Xeon) but that also does not change anything. Next I will try looping through the alignments one after the other instead of parallelizing with srun and see if that helps..

If you manage to replicate my issue, I am curious about any insights!

Best,
Flora

**Comment by spond** [comment]
Dear @fuesseler,

For these types of analyses (small alignments), you don't need anywhere near 1GB / CPU. Memory issues would also manifest differently. 

I'll try running this on our AMD boxes, see if I am able to replicate the issue.

Best,
Sergei
