### ISSUE TITLE
KH test on GARD results

### ISSUE THREAD

**Issue by Oliveira-Hugo** [veg/hyphy#1746]
Dear @spond,
I would like to know about the input for the KH test on GARD results from the current HyPhy implementation.

I note that after executing GARD I got the files:
- file.GARD.json
- file.best-gard
- file.best-gard.fit.bf

But none contains the trees for each partitions, which the KH test demands.
I would like to know how to get the necessary inputs for the KH test.

Thank you so much for the attention.

[combined_align.fasta.GARD.json](https://github.com/user-attachments/files/17014946/combined_align.fasta.GARD.json)
[combined_align.fasta.best-gard.fit.txt](https://github.com/user-attachments/files/17014970/combined_align.fasta.best-gard.fit.txt)
[combined_align.fasta.best-gard.txt](https://github.com/user-attachments/files/17014971/combined_align.fasta.best-gard.txt)

**Comment by spond** [comment]
Dear @Oliveira-Hugo,

There is an old file in the HyPhy distribution `hyphy kh`, which will do crude KH tests on two trees. You can also do these types of tests on using `IQTree` (http://www.iqtree.org/doc/Advanced-Tutorial) or `raxml`.

You need to extract GARD partitions from the `combined_align.fasta.best-gard` file, and then test the alternative trees on them. `hyphy` no longer automatically does this. 

In your particular example, all trees have 3 taxa, i.e., the same topology, so you can't run KH/SH tests on them (those tests assume different topologies).

Best,
Sergei
