### ISSUE TITLE
No HYPHYMPI option

### ISSUE THREAD

**Issue by lorsenex** [veg/hyphy#1751]
Greetings,
I recently installed hyphy on a Windows laptop (I run it in Linux with Ubuntu though), and I saw no MPI option for the runs. There is a HYPHYMPI.dir folder in the package, but I don't know how to run the program with an MPI setting. When I type "mpirun -np N build/HYMPHYMPI", I get this error: 

mpirun was unable to launch the specified application as it could not access
or execute an executable:

Executable: build/HYPHYMPI

Thank you in advance!
Lorenzo

**Comment by spond** [comment]
Dear Lorenzo,

Did you run `make MPI` when you were building, and did it complete without errors? The MPI build requires appropriate libraries like `openmpi` which may not be present on your system, for example.

Best,
Sergei

**Comment by lorsenex** [comment]
Dear Sergei,
Thank you, it all works now.
Best,
Lorenzo
