### ISSUE TITLE
Unable to access analysis modules and load previous results on Datamonkey

### ISSUE THREAD

**Issue by weiwei781** [veg/hyphy#1771]
Today, while I was using the Datamonkey website to analyze my data, all the analysis modules suddenly stopped working, and the results I had previously generated could not be loaded. I had been able to run the same file before, but this issue started approximately 6 hours ago. I would like to ask what the issue might be.
![image](https://github.com/user-attachments/assets/79468d06-ded6-416a-a3f3-483f94436c9f)
![image](https://github.com/user-attachments/assets/4b0df001-32e2-4afb-9f7c-acd2fc187ce8)

**Comment by spond** [comment]
Dear @weiwei781,

We'll investigate. Thanks for reporting.

Best,
Sergei

@stevenweaver

**Comment by stevenweaver** [comment]
Dear @weiwei781, 

At 1:39 AM ET on December 4th, 2024, our `mongod` service was disrupted due to consuming too much memory. Services have been restored, and further research is being conducted as to why this happened. 

Thank you for your patience and understanding. 

Best,
@stevenweaver
