### ISSUE TITLE
Standard Error Message - MEME

### ISSUE THREAD

**Issue by Fabineves7** [veg/hyphy#1774]
Since last week, I am struggling with MEME analysis. I always got errors (see logs above), using the partionated data from GARD. 
I used the same partionated data before, without any problems, however now, I am not being able to finish the analysis.  Additionally, the partionated data from GARD is working in other analysis like FEL or SLAC.

[log.txt](https://github.com/user-attachments/files/18060030/log.txt)
[log (1).txt](https://github.com/user-attachments/files/18060112/log.1.txt)

Can you help me with this?

**Comment by spond** [comment]
Dear @Fabineves7,

Can you check what version of HyPhy you have? The current version of MEME is `4.0`, and some of the types of errors that you are seeing were addressed about 1.5 years ago.

Would you be able to try your analysis with the latest version of `HyPhy` / MEME and see if the issue persists?

Best,
Sergei

**Comment by Fabineves7** [comment]
Many thanks for the reply Sergei, 

I am using dataMonkey webserver (https://www.datamonkey.org/meme). I have been trying to run these analyses every day since Monday last week.

**Comment by Fabineves7** [comment]
I cannot upload here the file of partinated data (.nex) because it is not supported. Here is the link of 2 different jobs, one that already ran sucessfully at 21/11, but now it gives an error (https://www.datamonkey.org/meme/67581187b1267005d36b00d5) and another one (https://www.datamonkey.org/meme/67581187b1267005d36b00d5).

**Comment by stevenweaver** [comment]
Dear @Fabineves7, 

The Datamonkey backend has been updated as it was running an outdated version of MEME. Please try again. 

Best,
Steven

**Comment by Fabineves7** [comment]
Dear Steven,

It continues with error message, and now it indicates "HyPhy killed by signal 15" (https://www.datamonkey.org/meme/67586f1ab1267005d36b466b)

**Comment by Fabineves7** [comment]
Many thanks for all your help. It is working :)
