### ISSUE TITLE
Bug in GUI, "New Model"

### ISSUE THREAD

**Issue by sjspielman** [veg/hyphy#212]
There seems to be a bug in the GUI (v2.1) which prevents me from building and/or defining a custom model. A screen shot of the issue is attached.
Basically, I opened HyPhy, selected File-> New-> New Model -> Codon model (doesn't matter if copy from model template or start from scratch). 
The screen then populates with a model template, but the error message "Error: Operation ':/' is not defined. This error message returns even when clicked. I also checked out whether this exists for nucleotide, amino acid, etc. models, and indeed the same error appears.

![screen shot 2014-09-09 at 10 45 44 am](https://cloud.githubusercontent.com/assets/4701111/4204623/dfbac33c-3838-11e4-9c93-20b836fc2b21.png)

**Comment by m-vieira** [comment]
I'm getting the exact same error message.

**Comment by sjspielman** [comment]
Thanks @stevenweaver !

**Comment by taliaku** [comment]
Hi, I'm getting the same error message (on mac OS x)
![screen shot 2017-06-01 at 15 01 55](https://cloud.githubusercontent.com/assets/22200231/26678874/49013c00-46db-11e7-89c5-9e9976f8fb1d.png)
Do you know what's causing it?
