### ISSUE TITLE
GARD: loading a file on the command line

### ISSUE THREAD

**Issue by rvosa** [veg/hyphy#220]
Hi,

I'm having trouble loading an alignment file to do a GARD analysis. Here's my setup:
- OSX 10.9.4, Quad-Core
- I did a git clone just now, then did `cmake .`, then `make HYPHYMPI`
- I use mpirun (Open MPI) 1.6.1
- I start HYPHY as `mpirun -np 4 HYPHYMPI`, everything seems OK

When I then navigate through the text menus, this is what happens:
- I select (11), Recombination
- I select (1), Screen an alignment using GARD
- I get:
  `Please select the file you want to use (or press ENTER to return to the list of analysis types):Initialized GARD on 4 MPI nodes.
  Population size is 6 models` 
- it seems that HYPHY is then waiting for a path, so I drag an alignment onto the terminal
- after dragging I then get what looks like a file prompt:
  `/usr/local/lib/hyphy/TemplateBatchFiles/Nucleotide file to screen::`
- it seems HYPHY is still waiting for a path(?), so I drag again
- at this point the session collapses:

```
/usr/local/lib/hyphy/TemplateBatchFiles/Nucleotide file to screen::Error:

Master node received an error:Could not find source dataset file:PROMPT_FOR_FILE Path stack: {/usr/local/lib/hyphy/,/usr/local/lib/hyphy/TemplateBatchFiles/}

Function call stack
1 : Read Data Set ds from file PROMPT_FOR_FILE
-------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD 
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

--------------------------------------------------------------------------
mpirun has exited due to process rank 0 with PID 51097 on
node lt003445.nnm.local exiting improperly. There are two reasons this could occur:

1. this process did not call "init" before exiting, but others in
the job did. This can cause a job to hang indefinitely while it waits
for all processes to call "init". By rule, if one process calls "init",
then ALL processes must call "init" prior to termination.

2. this process called "init", but exited without calling "finalize".
By rule, all processes that call "init" MUST call "finalize" prior to
exiting or it will be considered an "abnormal termination"

This may have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).
--------------------------------------------------------------------------
[lt003445.nnm.local:51096] 3 more processes have sent help message help-mpi-api.txt / mpi-abort
[lt003445.nnm.local:51096] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

Not sure how to proceed, I tried to check whether it makes a difference if I use a path relative to the current working directory or an absolute path, but that's not making a difference. What am I doing wrong?

**Comment by sadiexiaoyu** [comment]
Hi, all,

I met the similar problem. But I did not drag the file, instead, I gave the path of the sequencing file, and then run the .bf, like this,
/downloads/seq.fas
/usr/local/lib/hyphy/TemplateBatchFiles/Nucleotide file to screen::
GARD.bf
And then I get this error:
/usr/local/lib/hyphy/TemplateBatchFiles/Nucleotide file to screen::Error:

Master node received an error:The format of the sequence file has not been recognized and may be invalid

Function call stack
1 : Read Data Set ds from file PROMPT_FOR_FILE
-------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD 
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[evo-lutra:02330] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[evo-lutra:02330] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

[evo-lutra:02330] 2 more processes have sent help message help-mpi-api.txt / mpi-abort

Could you help me?

Thanks!

Sadiexiaoyu

**Comment by GuangchuangYu** [comment]
After type in the input alignment file, `hyphympi` runs. But if I hit `ENTER` again, it just stop running.

**Comment by stevenweaver** [comment]
Hello @GuangchuangYu,

Can you please provide a sequence of steps to reproduce your issue? Is it also when using GARD?
Are you able to use mpirun with other programs?
What is the output from HYPHYMPI?

Best,
Steven

**Comment by GuangchuangYu** [comment]
I use:

```
mpirun -np 20 hyphympi
```

and select 11 for recombination, and then 1 and input the alignment fasta file name and ENTER.

It show `/usr/local/lib/hyphy/TemplateBatchFiles/Nucleotide file to screen::` in the console.

I can verify that `hyphympi` is running by `ps aux |grep hyphympi` and also in `top`.

But If I hit `ENTER` in console, `hyphy` will exit without any message.

**Comment by stevenweaver** [comment]
Hello @GuangchuangYu ,

It seems as though the prompts for GARD can be a bit confusing at the moment. Currently, you need to submit the file path twice (which is undesired behavior). 

Something like the following command will work for you (with the correct file paths) until the issue is resolved:
`(echo "/home/hyphy/programming/hyphy-2.2.6/tests/hbltests/data/CD2.nex"; echo "/home/hyphy/programming/hyphy-2.2.6/tests/hbltests/data/CD2.nex"; echo "010010"; echo "1"; echo "/home/hyphy/programming/hyphy-2.2.6/tests/hbltests/data/CD2.nex.out") | mpirun -np 40 --hostfile ~/hostfile HYPHYMPI /usr/local/lib/hyphy/TemplateBatchFiles/GARD.bf`

The inputs are:
* Path to File
* Path to File
* Model to use
* Rate variation option
* Output file

Best,
Steven

**Comment by GuangchuangYu** [comment]
I kill the job I run yesterday. It's running and take 100% cpu usage of 20 threads.

I follow your guide to input the file twice, then it throw error:

```

        (1) Screen an alignment using GARD (requires an MPI environment).
        (2) Process GARD results.
        (3) A Likelihood Ratio Test to detect conflicting phylogenetic signal Huelsenbeck and Bull, 1996. [Contributed by Olivier Fedrigo].
        (4) Search an alignment for a single breakpoint.
        (5) Plot genetic distances (similarity) of one sequence against all others in an alignment, using a sliding window. Optionally, determine NJ-based clustering and bootstrap support in every window. This is a HyPhy adaptation of the excellent (but Windows only tool) SimPlot (and/or VarPlot) written by Stuart Ray (http://sray.med.som.jhmi.edu/SCRoftware/simplot/)

1
 Please select the file you want to use (or press ENTER to return to the list of analysis types):Initialized GARD on 20 MPI nodes.
Population size is 38 models

MERS-CoV.85.GARD.fasta
/usr/lib/hyphy/TemplateBatchFiles/Nucleotide file to screen::
MERS-CoV.85.GARD.fasta
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
/usr/lib/hyphy/TemplateBatchFiles/Nucleotide file to screen::Error:

Master node received an error:Could not find source dataset file:PROMPT_FOR_FILE Path stack: {/usr/lib/hyphy/,/usr/lib/hyphy/TemplateBatchFiles/}

Function call stack
1 : Read Data Set ds from file PROMPT_FOR_FILE
-------
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

....
```

**Comment by GuangchuangYu** [comment]
If I input the file only once in console, it seems hyphympi runs quite smoothly:

![screenshot 2016-07-08 13 45 51](https://cloud.githubusercontent.com/assets/626539/16678508/4f8c61a6-4512-11e6-8c76-b38b07160f24.png)

**Comment by GuangchuangYu** [comment]
When I run the command you recommended:
```
#!/bin/bash

(echo "MERS-CoV.85.GARD.fasta";
echo "MERS-CoV.85.GARD.fasta";
echo "010010"; echo "1";
echo "MERS-CoV.85.GARD.fasta.out"
) | mpirun -np 20 hyphympi /usr/lib/hyphy/TemplateBatchFiles/GARD.bf
```

It throw identical error.
