### ISSUE TITLE
REL/BUSTED for non-coding selection

### ISSUE THREAD

**Issue by dagarfield** [veg/hyphy#250]
Gruß,

For a while, we've been making happy use of HyPhy, following Haygood et al. 2007 Nat Gen, to conduct scans for selection on regulatory DNA (using either introns or synonymous sites as neutral proxies). When we have a branch we're interested in, branch-site models seem to function well enough. Often, however, we don't know which, if any branch, may show evidence for positive (or negative) selection, and we're generally clueless about which sites.

My work around so far has been to either drop the branch-specific terms (simply allow rate-variation over sites) or to evaluate each branch with a branch-site model in turn. Both approaches leave something to be desired. 

It seems to me that a variant of BranchSiteREL.bf or BUSTED.bf might be more appropriate. However, I have to admit I'm having a tough time reconfiguring these scripts to shift the contrast from dN/dS [codon models] to regulatory vs. proxy-neutral [nucleotide vs. nucleotide]. Do you have suggestions about some template batch files I might look at for how this might be done? 

Many thanks,

DG

**Comment by spond** [comment]
Hi DG,

Sorry for being slow in responding; give me a few days to think of a way to handle this. BUSTED.bf may be a good way to go, but it is pretty opaque, I agree.

Sergei

**Comment by dagarfield** [comment]
Sergei,

Many thanks for looking into this, but no rush. Anything you come up with would be much appreciated. 

--DG

**Comment by dagarfield** [comment]
Finally back at this problem myself...any clever thoughts, or should I start plugging on the code? :)
