### ISSUE TITLE
PRIME ERROR

### ISSUE THREAD

**Issue by RigersBakiu** [veg/hyphy#251]
Dear prof. Pond,

I had another time the same problem with the prime anayses. Could you help me please?

PRIME ERROR
This error has been reported to the datamonkeys responsible for this. Sorry, we will fix the issue as soon as possible. In the meantime, it may be worthwhile rerunning your analysis to see if the condition is transient.

If the issue is indeed persistent, and you would like more information with regards to what went wrong or be notified when the issue has been resolved, please feel more than free to contact us via the following form.

Email: 
 

Comments: 
 

The following is the error output:

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD 
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
Error:

Master node received an error:Could not read command file in ExecuteAFile.
Original path: 'spool/upload.783036076322409.1.codonFit'.
Expanded path: '/home/datamonkey/Datamonkey/Analyses/PRIME/spool/upload.783036076322409.1.codonFit'

Function call stack
1 : ExecuteAFile from file codonFit using basepath /home/datamonkey/Datamonkey/Analyses/PRIME/.
-------
[n8:91567] *** Process received signal ***
[n8:91567] Signal: Segmentation fault (11)
[n8:91567] Signal code: Address not mapped (1)
[n8:91567] Failing at address: 0x31
--------------------------------------------------------------------------
WARNING: A process refused to die!

Host: n21
PID:  91786

This process may still be running and/or consuming resources.

--------------------------------------------------------------------------
[silverback:89000] 68 more processes have sent help message help-odls-default.txt / odls-default:could-not-kill
[silverback:89000] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[silverback:89000] 69 more processes have sent help message help-odls-default.txt / odls-default:could-not-kill
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

Best regards!

Rigers

**Comment by spond** [comment]
Fixed.
