### ISSUE TITLE
Model Selection Job queue

### ISSUE THREAD

**Issue by UdayanJ** [veg/hyphy#252]
Hello,

I saw the thread earlier about the hardware issues with the GA branch job queue. was wondering if the same problem exists with the model selection/FEL job queue, as there seems to be some analyses that have been in line for 95 hours. Can they be cleared?
Thanks!

![screen shot 2015-01-20 at 10 04 25 am](https://cloud.githubusercontent.com/assets/5125379/5811093/cd5d045a-a08b-11e4-9c44-9d3148dd63a4.png)

**Comment by spond** [comment]
Hi there,

Thanks for bringing this to our attention: there seems to be a bug with Protein Model Selection which was introduced during a recent round of updates. We'll resolve this issue as soon as possible.

Sergei

**Comment by stevenweaver** [comment]
Hi there, 

An update on our server on January 15th shortly before 17:56pm PST caused the Model Selection queue to stall. The queue has been cleared and is now properly dispatching jobs. 

Please try resubmitting your datasets. 

Steven

**Comment by UdayanJ** [comment]
Thanks Sergei and Steven for your help with this. As always, your team are life-savers!!!

Cheers,

Udayan
