### ISSUE TITLE
Adding extra leaf nodes, and assigning a specific model to the extra branch.

### ISSUE THREAD

**Issue by murrellb** [veg/hyphy#254]
We request a function that takes a tree string, and:
1: generates a tree object where the terminal branches are split into two segments to which different models can be assigned. The names of the new nodes need to be straightforwardly related to the taxon labels.
2: assigns a specific model to each of the (newly created) terminal nodes. This model could perhaps be passed in as a parameter.

Thanks!

**Comment by spond** [comment]
Hi Ben,

Please find a code example (also showing how to define the logistic mapper function) at https://github.com/spond/hyphy-support/blob/master/code_examples/issue254.bf

Sergei
