### ISSUE TITLE
Getting MPI and GARD to work

### ISSUE THREAD

**Issue by lanyingjie** [veg/hyphy#260]
Hello everyone,

I've been trying to get HYPHY to work and run GARD on OS X, but each time I select it, it tells me I need an MPI environment.

OpenMP is installed, as can be seen by the terminal output:
136-103:hyphy-2.2.3 lanyingjie$ mpirun -V
mpirun (Open MPI) 1.8.4

Report bugs to http://www.open-mpi.org/community/help/

I'm trying to use the GUI version to get my analysis done, but I'm really at my wits end here. I've also tried downgrading to HYPHY 2.1 (as another thread suggested), but no luck either. Any ideas?

**Comment by spond** [comment]
Hi there,

The GUI version of HyPhy will not work with MPI, unfortunately, so please use the command line version. You also need to wrap HyPhy in a call to mpirun, as in 

```mpirun -np 8 HYPHYMPI /path/to/TemplateBatchFiles/GARD.bf```

Best,
Sergei

**Comment by lanyingjie** [comment]
Right, got it to work! Thanks a lot! (Any chance you could put this information there in the GUI output actually?)

Thanks a lot! :)
