### ISSUE TITLE
HyPhy JSON output is not compliant with ECMA-404

### ISSUE THREAD

**Issue by stevenweaver** [veg/hyphy#261]
Hello,

According to section 8 of the [ECMA-404 standard](http://ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf). 

> Numeric values that cannot be represented as sequences of digits (such as Infinity and NaN) are not permitted.

Please change `inf` to `1e+9999` and `-nan` to `null`, if possible. 

Thank you,
Steven

**Comment by spond** [comment]
Resolved via 810077395e526f829774794f41597f0cf1d67ea4

**Comment by stevenweaver** [comment]
Thanks
