### ISSUE TITLE
Interpreting BranchsiteREL on Hyphy (p values)?

### ISSUE THREAD

**Issue by michael-steffen** [veg/hyphy#262]
I'm trying to learn a bit more about this analysis, however I do not understand what the p values mean and the end interpretation. 

At the end of the analysis it says no branches are under episodic selection. 

However, earlier in the output i see this.

Node: mixtureTree.Node32
	Length parameter = 0
	Class 1: omega =   Infinite, weight = 1.
...Testing for selection at this branch

Node: mixtureTree.Node32
	Length parameter = 0.03787949453905751
	Class 1: omega =     1.0000, weight = 1.
p-value = 0.0149689277132134

I am kinda confused. What does this p-value mean? My thought was this did indicate significance, but at the end, things seem to say differently. 

Can someone please explain this to me?

Thanks,
Mike

**Comment by spond** [comment]
Hi Mike,

The first set of p-values is uncorrected; what you see at the end of the analysis performs has survived the [Holm-Bonferroni](http://en.wikipedia.org/wiki/Holm–Bonferroni_method) multiple testing correction procedure. By definition, the list of branches you get at the end is a subset of those which have significant p-values.

Sergei

**Comment by michael-steffen** [comment]
Thanks Sergei,

I guess the thing that is throwing me off, is that with my analysis there
are many fewer branches under selection than I would have thought.

Using SLAC, FEL, MEME, and FUBAR  as run on datamonkey, I get over 50 sites
under selection in a sequence of 200 amino acids with over 300 sequences.
However, running branchsiteREL i get only 2 terminal branches shown to be
under selection. This seems surprising to me. There seems to many
significant un-corrected p-values also.

Thanks,
Mike

On Thu, Mar 5, 2015 at 2:05 PM, Sergei Pond <notifications@github.com>
wrote:

> Hi Mike,
>
> The first set of p-values is uncorrected; what you see at the end of the
> analysis performs has survived the Holm-Bonferroni
> <http://en.wikipedia.org/wiki/Holm%E2%80%93Bonferroni_method> multiple
> testing correction procedure. By definition, the list of branches you get
> at the end is a subset of those which have significant p-values.
>
> Sergei
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/veg/hyphy/issues/262#issuecomment-77440835>.
>



-- 
Michael A. Steffen
PhD. Candidate
Department of Biological Sciences
800 S. Tucker Drive
University of Tulsa
Tulsa, OK 74104
Phone (708) 738-1491

**Comment by spond** [comment]
Hi Mike,

When you get to 300 sequences (~600 branches), you will lose a big chunk of signal if you test all branches. Site-wise models aggregate data over branches, so it's not surprising that you will see 50 sites under selection, but only 2 branches which clear the threshold. Multiple testing correction is quite strict, so you could  use raw p-values and perform something like an FDR (q-values) if you are happy accepting that some of the **positive** branches are false positives.

Have you looked at the branch-level plots in MEME to get the idea of where the __hotspots__ are for each site?

Sergei

**Comment by michael-steffen** [comment]
Thanks Sergei,

The FDR may be something I'll look into. How often do false positives pop
up in this method?

I haven't looked at the MEME plots, but this is something I will do now.

I was originally going to use the branch methods in PAML, but as I
understand it, the branchsiteREL method seems to be better since I don't
have to specify branches. Plus the standard PAML selection screening seems
to be super slow.

Also, while I think its great that you are responding to my questions, I
also hate to take advantage of you, so if you can refer to additional
examples or publications, I would appreciate it.

Mike



On Thu, Mar 5, 2015 at 2:31 PM, Sergei Pond <notifications@github.com>
wrote:

> Hi Mike,
>
> When you get to 300 sequences (~600 branches), you will lose a big chunk
> of signal if you test all branches. Site-wise models aggregate data over
> branches, so it's not surprising that you will see 50 sites under
> selection, but only 2 branches which clear the threshold. Multiple testing
> correction is quite strict, so you could use raw p-values and perform
> something like an FDR (q-values) if you are happy accepting that some of
> the *positive* branches are false positives.
>
> Have you looked at the branch-level plots in MEME to get the idea of where
> the *hotspots* are for each site?
>
> Sergei
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/veg/hyphy/issues/262#issuecomment-77445442>.
>



-- 
Michael A. Steffen
PhD. Candidate
Department of Biological Sciences
800 S. Tucker Drive
University of Tulsa
Tulsa, OK 74104
Phone (708) 738-1491

**Comment by spond** [comment]
Hi Mike,

The key difference from PAML is that branch site REL does not make any assumptions about the background branches (e.g. in PAML the model that says branch 'A' is under selection, also says that **none** of the other branches are under selection).

Have you seen the (http://mbe.oxfordjournals.org/content/early/2015/02/18/molbev.msv022.abstract)[aBSREL paper]? It provides some useful background on the methods, and the intuition of where selection signals come from.

Sergei

**Comment by michael-steffen** [comment]
I actually had the article downloaded on my desktop for future reading. I'd
like to try the method on my dataset, however, I don't seem to see the
option in the hyphy console, nor does the link for the tutorial in the
manuscript seem to work.

Mike

On Thu, Mar 5, 2015 at 4:18 PM, Sergei Pond <notifications@github.com>
wrote:

> Hi Mike,
>
> The key difference from PAML is that branch site REL does not make any
> assumptions about the background branches (e.g. in PAML the model that says
> branch 'A' is under selection, also says that *none* of the other
> branches are under selection).
>
> Have you seen the (
> http://mbe.oxfordjournals.org/content/early/2015/02/18/molbev.msv022.abstract)[aBSREL
> paper]? It provides some useful background on the methods, and the
> intuition of where selection signals come from.
>
> Sergei
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/veg/hyphy/issues/262#issuecomment-77464540>.
>



-- 
Michael A. Steffen
PhD. Candidate
Department of Biological Sciences
800 S. Tucker Drive
University of Tulsa
Tulsa, OK 74104
Phone (708) 738-1491

**Comment by spond** [comment]
Hi Mike,

The BranchSiteREL standard analysis in HyPhy has the option (default) to run aBSREL (at least if you are using a recent version). The link should work, I just checked [make sure to remove the spaces from the clickable version, they will show up as %20].

Sergei
