### ISSUE TITLE
RELAX Q

### ISSUE THREAD

**Issue by VinnyLynch** [veg/hyphy#264]
Hi All,

I have a quick question about the interpretation of the K-value from the RELAX method. I've tested a gene and found that BS-REL suggests there was a rate acceleration along an internal branch (dN/dS=1.31), but the results were not significant (P=0.44) for dN/dS>1; the branch length is very short so this is not surprising. We then fit a two-rate model and found that the rate along this internal branch (dN/dS=0.85, 95% CI=0.14-2.71) was significantly higher than the other lineages (dN/dS=0.014; LR=7.77, P=0.005). 

We used RELAX to try and infer whether this rate acceleration was more consistent with a signal of relaxed purifying selection or an intensification of positive selection. We found that the test for selection intensification was not significant (LR = 2.43, P=0.12), however, the K-value was positive (K=3.59). But what I would really like to know is whether we can statistically reject an episode of relaxed selection being responsible for the rate acceleration. Is that already implied because K>1 or should we do something more formal like fix K at some value less than 1 (say the K value of the reference lineages) and do a LRT to test K<1?

A little more generally, is this approach of identifying an episode of rapid evolution with BS-REL and a two rate model, and then showing that there is no evidence for relaxed selection with RELAX statistically justifiable?

Thanks
Vinny

**Comment by jwertheim** [comment]
Hi Vinny,

First, I have a question about your BS-REL results. Is the dN/dS of 1.31 for a proportion of sites or all the sites? Did you run BS-REL or possibly aBS-REL, the latter of which can reduce the number of omega classes per branch?

Regarding RELAX, the test your propose, of fixing K at 1, is the test RELAX is performing. You cannot reject relaxed selection being responsible for the increase in dN/dS. Although the test seems to support intensification of selection (albeit the result is not significant). An important part of the RELAX testing framework is choosing the 'test' and 'reference' branch sets. Essentially, you are asking if this one branch has been evolving under more intense evolution than the entire rest of the tree, which could be confounded by intensification on other parts of the tree. 

I am a little wary of using one BS-REL based test to identify a branch and then using a second (RELAX) to perform another test using the same data. Using an exploratory analysis to create a hypothesis and then testing that hypothesis on the same data might not be a valid approach.

Cheers,
Joel Wertheim

**Comment by VinnyLynch** [comment]
HI Joel,

Thanks for the quick reply! We used both BS-REL and aBS-REL, which give more or less the same results. A single rate class for all sites, with aBS-REL the rate is 1.31 with BS-REL the proportion of sites in the rate class of 1000 is 1. I expected these results because the branch lengths are very short (0.01).

The RELAX test I was thinking about was not fixing K=1, but K<1 to test if we can reject a hypothesis of relaxed selection. Fortunately I'm not worried about selection intensification in other parts of the tree since this is a highly conserved gene. We a priori selected the branch we're testing so we don't have the problem of using an exploratory analysis to generate a hypothesis. Of course that doesn't mean the approach of using (a)BS-REL to test for a rate acceleration followed by RELAX to exclude relaxed purifying selection as being responsible for that acceleration is anymore justifiable :)

Vinny

**Comment by jwertheim** [comment]
There won't be a practical difference between testing k<1 and k=1, if the true value of k is actually greater than 1 because k (in the k<1 scenario) will move as close to 1 as possible (resulting in nearly identical LRT comparisons). They're functionally equivalent. Also, it's not clear how to set up an LRT with an inequality constraint (k<1) since the number of parameters doesn't change in the null and alternative.

Cheers,
Joel

**Comment by VinnyLynch** [comment]
OK, I think that makes sense now. Just as an aside, the LRT I was thinking about would have fixed the K for the test lineage at the average for the reference branches, and then compared that to a model with the test lineage having a free K parameter. That would have given a LRT with 1 dgf. 

Thanks again!
Vinny

**Comment by spond** [comment]
Hi Vinny,

To test K &le; 1 (vs K = 1), you would use the same models as implemented in RELAX, but you would compute the significance using the 50:50 mixture of &Chi;<sup>2</sup><sub>0</sub> and &Chi;<sup>2</sup><sub>1</sub>. In your case you will get p = 0.5, because the point estimate K > 1. This all assumes uni-modality of the likelihood surface, but we always make this assumption anyhow (implicitly).

Sergei

**Comment by VinnyLynch** [comment]
Hi Sergei, 

OK, that makes sense.  Given our inference of K=3.6 it is OK to say there is no evidence for relaxed selection even if the P=0.12?

Vinny

**Comment by spond** [comment]
Hi Vinny,

The P value is actually for **intensification** of selection; the P value for relaxation is 0.5. So, yes, there is no evidence for relaxation.

Sergei

**Comment by VinnyLynch** [comment]
Perfect!
