### ISSUE TITLE
BGM failure

### ISSUE THREAD

**Issue by DavidNickle** [veg/hyphy#266]
I am trying to run a co-varition (BGM) analysis on HyPhy Mac OS X GUI but I keep getting an error.

I am using:

Mac Pro (Late 2013)
I am running HyPhy 2.2.3 (Modified Wednesday, December 17, 2014 at 2:37 PM)

My Error is:

Error:
The left hand side expression does not contain an object reference in the following context: 'BGM gen_bgm=<ERROR HERE>(discreteNodes,continuou'

Function call stack
1 : BGM gen_bgm=(discreteNodes,continuousNodes)
-------
2 : ml_bgm_results=runBGM(_bgm_data)
-------
Error:
Problem occurred in line: ml_bgm_results=runBGM(_bgm_data)

Function call stack
1 : ml_bgm_results=runBGM(_bgm_data)
———

**Comment by ArtPoon** [comment]
Hey David,
This is a long running versioning problem. I'll try to patch it tonight.
Sorry for the inconvenience :-/
A

**Comment by DavidNickle** [comment]
Hi Art,

I am still having the same problem:

Error:
The left hand side expression does not contain an object reference in the following context: 'BGM gen_bgm=<ERROR HERE>(discreteNodes,continuou'

Function call stack
1 : BGM gen_bgm=(discreteNodes,continuousNodes)
-------
2 : ml_bgm_results=runBGM(_bgm_data)
-------
Error:
Problem occurred in line: ml_bgm_results=runBGM(_bgm_data)

Function call stack
1 : ml_bgm_results=runBGM(_bgm_data)
———


DAVID

**Comment by ArtPoon** [comment]
Did you pull, compile and re-install?
That call should no longer be in BGM.bf
If you’re on a Mac, then you need to make sure that the copy of BGM.bf at `/usr/local/lib/hyphy/TemplateBatchFiles` has been updated.

**Comment by DavidNickle** [comment]
Hi Art,

First I re-downloaded HyPhy - and of course it did not work because that TemplateBatchFiles file did not get updated.  So I emailed you. Sorry

Then I went to github to see what your actual response was and saw the changes to BGM.bf.  I copied those changes into my local BGM.bf file and it looks like I am off to the races.

Thanks!

I hope all is well with you.

David

**Comment by spond** [comment]
Art, thanks for fixing the issue so quickly.

David: I have released version 2.2.4 to include this and other fixes.
