### ISSUE TITLE
Data monley jobs queued since 5 days

### ISSUE THREAD

**Issue by MPRIYAM** [veg/hyphy#267]
Hello,
Can someone tell me if datamonkey.org is conducting MEME, SBP and GARD analysis since the past five days. At my place all the jobs seem to have been in a queue since past 5 days

**Comment by stevenweaver** [comment]
Hello MPRIYAM, 

datamonkey.org is conducting MEME, SBP, and GARD analysis. There were large jobs that were submitted last week that caused a rather long queue. 

We have halted the MEME job that was creating a bottleneck, and re-evaluating sequence and site limits on datamonkey.org as a result. We are allowing the large SBP job that is causing a bottleneck for other SBP and GARD jobs to continue running at the moment under close moderation. We will make a decision about this analysis later in the day. 

Thank you,
Steven
