### ISSUE TITLE
MEME error perBranchTree is undefined in call to ReplicateConstraint

### ISSUE THREAD

**Issue by ondrej77** [veg/hyphy#269]
I have come across a previous post briefly discussing this MEME error issue but I could not replicate the resolution. I have tried to use the server to run GARD and MEME, but the queue is impractical (over 5 days?). I set up my mac to run GARD with HYPHY (v2.2.4) MPI (successfully, although running the command line interactive menu is super tricky since the input buffer messes things up, and doesn't even show option for saving output file - had to do lots of guessing when I should specify output path). Nonetheless I have GARD output for my data *_finalout, post-processed it with GARDprocessor.bf (output *_finalout_multi.fit), and I fed that nexus file from GARDprocessor.bf *_finalout_multi.fit to MEME. MEME always quits with this error (could not cut and paste, had to retype it, apologies for typos):

---

Error perBranchTree is undefined in call to ReplicateConstraint

Function call stack
1: Replicate the following constraint "this1.?.alpha:=_sFactor*this2.?.synRate_"usingthesevariables:perBranchTree codonTree;

2 :result_String("BPANCHES"] obtainBranchWiseEBEstimate s(sFactor_nsFactor1,nsfactor2 mix ngPJilterString)

3:Branch under condition 'SendJobMEME()'
to
 <END EXECUTION>

else

<END EXECUTION>

Error 
Problem ocurred in line:result_String["BRANCHES"]=obtainBranchWiseEBEstimates(sFactor,nsFactor1,nsFactor2,mixingP,filterString)

Function callstack
1:result_String("BPANCHES"] obtainBranchWiseEBEstimates(sFactor,nsFactor1_nsfactor2 mix ngPJilterString)

2:Branch under condition 'SendJobMEMEO' to

else

<END EXECUTION>
## <END EXECUTION>

Any suggestions why it errors out?

I am not running MEME in MPI environment (did not require it). I tried versions HyPhy 2.2.3, 2.2.4, command line and applications. I tried running just the *_finalout file, but no success.

Any help would be GREATLY appreciated!!! 

PS: Overall, I am trying to figure out if there is any positive selection along the phylogeny branches (with aBSREL) and also what are the specific codons that are adapting (GARD -> MEME) in a set of human genes. If there is any advise on how to "combine" these two processes in a better way, let me know. 

Cheers

**Comment by spond** [comment]
Hi ondrej77,

The MEME file can have a bug in the non-MPI branch. Let me check and see if I can confirm its existence. Would you be able to send me the exact input that produces the error you observe (the file and the analysis options)?

Sergei

**Comment by ondrej77** [comment]
Hello Sergei,
Here is the input file for MEME <2a_GARD_finalout>.

I am using the GUI version of HyPhy 2.2.4 and input options were
-Selection/Recombination
-MEME_mf.bf
-Universal
-New Analysis
-Default
-1
- select input file <2a_GARD_finalout>
-select output file <2a_MEME>
-0.05

I get an error/crash while HyPhy is still doing LF optimization (or just
when it finishes?)

Thanks for your help.

Ondrej

**Comment by wasalp** [comment]
I'm having the same issue, has this been resolved?

Thanks

**Comment by spond** [comment]
Hi @wasalp,

Please use solution discussed in #385 

Best,
Sergei
