### ISSUE TITLE
Branch-site REL method: cannot get output graph using GUI interface on Mac

### ISSUE THREAD

**Issue by tlorin** [veg/hyphy#270]
Hello,

I am using a GUI interface of HyPhy on a iMAc 10.8.5
I downloaded the 2.2.4 version of HyPhy, and I am trying to reproduce the results from the branch-site REL of this workshop (a bit old though): http://www.hyphy.org/w/index.php/Workshop:Fudan2013:SelectionAnalyses

In the workshop it says that I should get a PostScript image as part of the output, but I don't get it, any idea of what is happening? Here are the files that I get:

HIV_gp120.csv
HIV_gp120.csv.annotated.nwk
HIV_gp120.csv.fit
HIV_gp120.csv.json
HIV_gp120.csv.mglocal.fit

(and by the way, what are those .fit files? )

Thanks a lot!

Thibault Lorin
Master Student
University of Basel

**Comment by spond** [comment]
Dear Thibault,

We have overhauled how HyPhy outputs graphics for these analyses. See https://github.com/veg/hyphy-tutorials/tree/master/selection#use-absrel-to-find-lineages-which-have-experienced-episodic-diversification and a link to the web app which visualizes JSON files (http://veg.github.io/hyphy-vision/absrel/). As a plus, the graphics are much nicer now.

Sergei

**Comment by tlorin** [comment]
Thanks so much! It works now! And as you say, it's much nicer :)
