### ISSUE TITLE
aBSREL version not available

### ISSUE THREAD

**Issue by tlorin** [veg/hyphy#271]
Hello again,

In your recent MBE paper, you say that your new optimized version of BSREL will be released soon (that's cool!); however I don't find it in the v2.2.4: maybe it is not implemented yet? Or if it is, where would it be possible to find it? 

Thanks!

Thibault Lorin

**Comment by spond** [comment]
Hi Thibault,

It is already available as an option under BS-REL. Please see https://github.com/veg/hyphy-tutorials/tree/master/selection#use-absrel-to-find-lineages-which-have-experienced-episodic-diversification for a tutorial.

You can also use http://www.datamonkey.org/absrel to run the test online.

Sergei

**Comment by tlorin** [comment]
Perfect! I even have a slight preference for the command line version, and since everything is well explained in this tutorial, it's perfect :)
