### ISSUE TITLE
Automating aBSREL not working

### ISSUE THREAD

**Issue by tlorin** [veg/hyphy#272]
Hello again,
Now that I know where and how to use it, I am trying to automate aBSREL, and here is my 'wrapper' file (I have not tried it yet for many files, even if this what I plan to do).

----------------------
`fileToExe = HYPHY_LIB_DIRECTORY + "TemplateBatchFiles" + DIRECTORY_SEPARATOR + "BranchSiteREL.bf";

inputRedirect = {};

inputRedirect["01"]="Universal";
inputRedirect["02"]="Yes";
inputRedirect["03"]="No";
inputRedirect["04"]="/path/to/example/input/file/HIV_gp120.nex";
inputRedirect["05"]="Y";
inputRedirect["06"]="All";
inputRedirect["07"]="/path/to/my/output/file/HIV_gp120.out";
ExecuteAFile (fileToExe, inputRedirect);`

----------------------

And here is the error that I get:

----------------------
`Error:
Not a valid (or duplicate) option: '2' passed to ChoiceList (with multiple selections) 'Which branches to test?' using redirected stdin input

Function call stack
1 : Choice List for Which branches to test? with choice list:NO_SKIP. Store result in whichBranchesToTest
	Standard input redirect:
		07 : /path/to/my/output/file/HIV_gp120.out
		-------
2 : ExecuteAFile from file fileToExe using basepath /path/to/my/output/file/. reading input from inputRedirect
{"01":"Universal",
"02":"Yes",
"03":"No",
"04":"/path/to/example/input/file/HIV_gp120.nex",
"05":"Y",
"06":"2",
"07":"/path/to/my/output/file/HIV_gp120.out"}

HYPHYMP(11545) malloc: *** error for object 0x7fec7b067400: pointer being realloc'd was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6`

----------------------

Any idea of what is happening?
Thanks a lot!
Cheers,
Thibault

**Comment by spond** [comment]
Hi Thibault,

You need to add an empty line after a multi select, like so

```
inputRedirect["01"]="Universal";
inputRedirect["02"]="Yes";
inputRedirect["03"]="No";
inputRedirect["04"]="/path/to/example/input/file/HIV_gp120.nex";
inputRedirect["05"]="Y";
inputRedirect["06"]="All";
inputRedirect["07"]="";
inputRedirect["08"]="/path/to/my/output/file/HIV_gp120.out";
```

This tells HyPhy that you are done with selecting options for that dialog.

Sergei

**Comment by tlorin** [comment]
Perfect, that works now! Thanks for your fast answer!!
Thibault

**Comment by francicco** [comment]
Hi Guys,

I'm performing the same analysis but I get a different error several times during the same process:

Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-14957.46980740712] does not match the last recorded LF maximum [-14957.46980740713]

What that means?
Cheers
F

**Comment by spond** [comment]
Hi Francicco,

This is an unusual error [an internal error in the optimization algorithm], but in your case this simply seems to be the case of roundoff error. What hardware/software combination are you running the program on? To fix the error, you would need to edit the source and recompile, if you are running a command-line version, or I need to patch the binary if it's on Window/OS X.

Sergei

**Comment by francicco** [comment]
Hi Sergei,

Is not mac or win it's a cluster machine http://www.uibk.ac.at/zid/systeme/hpc-systeme/leo3/

Do you need any other info?

Cheers
F
