### ISSUE TITLE
DEPS analyses in HyPhy software and DataMonkey

### ISSUE THREAD

**Issue by licheng1980** [veg/hyphy#273]
Hello,

The results obtained, for the same dataset, from the DEPS analyses  in the current versions of Hyphy (version 2.1.2) and the Datamonkey differ very much from each other. There were much more sites and residues obtained from the Datamonkey. Just wondering what I am doing wrong or what is going on?

Thank you very much in advance for your input!

Best,

Licheng

**Comment by stevenweaver** [comment]
I'm going to mark this as won't fix as DEPS is being deprecated in the upcoming release of HyPhy and Datamonkey. 

Best,
Steven
