### ISSUE TITLE
Updating of the tree tab of the web app to visualize JSON files not working

### ISSUE THREAD

**Issue by tlorin** [veg/hyphy#274]
Hello,
I am using the web app to visualize the JSON output of HyPhy (http://veg.github.io/hyphy-vision/absrel/). I am new to it and I have a very basic question, sorry if it is very easy to answer.

When I change the input file (Load file --> Choose file) the "Summary" and "Tables" tabs update with the new file, but the "Tree" tab does not. I am using Chrome browser and I tried it on Safari and Firefox, same result. I even shut down my computer and restarted it, doesn't work neither. Am I missing something at some point?

Thanks for your answer!
Cheers,
Thibault

**Comment by spond** [comment]
Dear Thibault,

I've assigned Steven to investigate the issue. Sounds like it could be a bug. Could you please look at the JavaScript console in your browser and tell us if there are any reported problems.

Sergei

**Comment by tlorin** [comment]
Dear Sergei,
Apparently not! When I look at it, nothing is reported.
Thibault

**Comment by tlorin** [comment]
I don't know if this helps but here are the three screenshots of the web app with my input file (that is different from the available tree ;) ).



![screen shot 2015-04-13 at 5 29 31 pm](https://cloud.githubusercontent.com/assets/11868165/7118947/b734a0ee-e202-11e4-8995-da39381943b1.png)
![screen shot 2015-04-13 at 5 29 38 pm](https://cloud.githubusercontent.com/assets/11868165/7118948/b735d018-e202-11e4-93a6-980b5f075a47.png)
![screen shot 2015-04-13 at 5 29 45 pm](https://cloud.githubusercontent.com/assets/11868165/7118949/b735f1a6-e202-11e4-9c55-7b2e039cb25c.png)

Thibault

**Comment by stevenweaver** [comment]
Hi Thibault, 

The issue has been fixed and the site has been updated. 
Please try again. 

Thanks,
Steven

**Comment by tlorin** [comment]
Indeed, that works perfectly now!
Thank you so much to both of you for your fast answers, and fast solution!
All the best,
Thibault
