### ISSUE TITLE
RELAX application

### ISSUE THREAD

**Issue by fzedek** [veg/hyphy#275]
Dear HyPhy Fans,

I have a question about RELAX. We have analyzed one gene from fourteen separate (relatively distantly related) eukaryotic lineages/phylogenies for the presence of positive selection (using MEME and BS-REL). We divided these lineages into two groups, which should differ in the frequency of positive selection and we compared the results to see whether there really was a difference. It was. However, one of the reviewers of our manuscript wants us to analyze the data with RELAX to see whether the two groups differ in relaxation or intensification of selection. First of all, I think such an analysis is not necassary for the question we ask, but more importantly I think that the data set as it cannot be meaningfully analyzed using RELAX.

We have fourteen separate lineages (alignments + trees), eight lineages belongs to the first group and six lineages to the second group. What I think is that we would need to have all these lineages in one big alignment and tree to analyze them in RELAX. However, given the phylogenetic distance between the lineages (there are plants, animals, ciliates and fungi), I think the alignment would be too unreliable or too short (after removal of unreliably aligned residues) for any meaningful analysis. I would like to ask what do you think about this. Am I right about this or am I missing something?

Thanks a lot for any thoughts!

Best regards,

Franta

**Comment by spond** [comment]
Hi Franta,

The utility of RELAX will depend on what types of questions you are seeking to answer. For example, neither BS-REL nor MEME **directly** test for a difference between groups of lineages -- you have to post-process the list of selected sites/branches and there are statistical issues involved. 

Your concern about merging divergent alignments into a single one for RELAX is entirely valid. What I would recommend is that you work with someone on our team (e.g. with me) to modify RELAX to work on multiple alignments jointly: you run the RELAX test without having to partition the tree, but rather using the groups you've already defined in separate alignments.

Sergei

**Comment by fzedek** [comment]
Hi Sergei,

thanks for such a quick reply. I am not sure that I understand what you have suggested with RELAX. Perhaps my description of our dataset was confusing. We have fourteen clades (e. g., plant family Poaceae, animal order of Primates, fungi genus Aspergillus etc.) and we prepared a codon alignment and a phylogenetic tree for each of them (using BAli-Phy). We divided these fourteen clades into two groups (8 and 6) which differ in a factor that should affect the frequency of positive selection. We have analyezed each clade in PAML (M0 model) to get average dN/dS and then using BS-REL and MEME to get the frequency of positively selected branches and codons, respectively. We expected the two groups to differ in these parameters and this expectation was confirmed by a statistical analysis.

What I don´t understand is how can we analyze the data we have (fourteen alignments and fourteen trees) in RELAX to see whether there is some difference between the two groups of clades. I think we would have to prepare a single alignment/tree for all the clades, which I think, as I said, is not a good idea because such an alignment would be highly unreliable.

Franta

**Comment by spond** [comment]
Hi Franta,

Thanks for your clarification; I surmised your data composition correctly. The current version of RELAX would indeed require you to merge the fourteen alignments together, which may be a bad idea. However, what can be done instead is to take the 14 trees, mark 6 them of them as Test, and 8 as Reference, and run the RELAX test on them jointly -- i.e. your clades need not be in the same tree. This would require a fairly trivial modification to the RELAX analyses, which if you are interested, I could implement. 

Sergei

**Comment by fzedek** [comment]
Hi Sergei,

Now I get it. I am interested in analyzing our data using the modified RELAX. What should I do for that?

PS: We have managed to get more sequences from more clades, so our data set is approximately two times larger now.

Franta

**Comment by spond** [comment]
Hi Franta,

I will need to modify the RELAX analysis for you (to accept multiple files). I expect to be able to do it this week and post a link to a working version for you in this thread.

Sergei
