### ISSUE TITLE
Visualizing BUSTED json

### ISSUE THREAD

**Issue by ondrej77** [veg/hyphy#277]
First, thanks for fixing the aBSREL visualization. It works great. I am trying to visualize BUSTED results at

http://veg.github.io/hyphy-vision/busted/

and seem to have an issue where the web app is not loading my file. 

Cheers, Ondrej

**Comment by stevenweaver** [comment]
Hello Ondrej,

The issue has been fixed and the site has been updated.
Please try again.

Thanks,
Steven

**Comment by ondrej77** [comment]
Big THANKS!!!
