### ISSUE TITLE
Toggle analyses error

### ISSUE THREAD

**Issue by balamp** [veg/hyphy#278]
Dear All.

I uploaded an alignment of 44 bacterial isolates for a given gene to datamonkey server (upload.371284594831583.1), inferred evidence for recombination using GARD, and by using the GARD inferred trees and default parameters and HKY85 model, I tried to analyse my sites of interest for evidence of Toggling. 
The analyses resulted in throwing error whether I selected more than 1 site or just even a single site for toggling.

following the error message!

Error: Invalid Matrix Index [2][0] in a 2 by 1 matrix. Function call stack 1 : result=result+"
Partition "+_k+": "+(1+(_treeDesc["RIGHT"])[_k-1]-(_treeDesc["LEFT"])[_k-1])*_factor+" "+_data+"s "+treeLengthArray[_k]*_factor+" subs/site" ------- 2 : Print to File stdout:_makeJobIDHTML(filePrefix) _makeDataDescriptionTM(slacDBID,treeMode,treeLengths) ------- 3 : ExecuteAFile from file "Toggle_Processor.ibf" using basepath /var/lib/datamonkey/share/BFs/. ------- 

Any help would be extremely appreciated.

Thanks and regards,
Bala

**Comment by stevenweaver** [comment]
Hi Bala, 

I'm having trouble recreating this error and, while I have noticed that an error was reported at 19:52 on April 19th, 2015 (PDT), the job for this id completed at 22:48 (PDT). Before delving in further, can you please verify that you are still having an issue?

Thanks,
Steven

**Comment by balamp** [comment]
Dear Steven, 
Thanks for your response. I had the problem when I tried to use GARD inferred trees. I got that above error that I posted. Then I tried to use the NJ tree instead which worked. Perhaps that is why it shows the jobID was completed. I will run with GARD inferred trees again and will update my results. 
Thanks for help.
Bala

**Comment by balamp** [comment]
Dear Steven,

The error persists when I try to use GARD inferred trees. here is the error

Error:

Master node received an error:Invalid Matrix Index [2][0] in a 2 by 1 matrix.

Function call stack
1 : treeLengths[fileID]=(bl_vec*((Transponse(bl_vec))["1"]))[0]
-------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD 
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[n5:81263] *** Process received signal ***
[n5:81263] Signal: Segmentation fault (11)
[n5:81263] Signal code: Address not mapped (1)
[n5:81263] Failing at address: 0x31
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

and at the end, it says,
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 81263 on node n5 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
[silverback:78584] 38 more processes have sent help message help-mpi-api.txt / mpi-abort
[silverback:78584] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[silverback:78584] 13 more processes have sent help message help-odls-default.txt / odls-default:could-not-kill
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

Any help is much appreciated!
Bala

**Comment by spond** [comment]
Dear Bala,

The issue has been resolved; thanks for bringing this to our attention.

Sergei
