### ISSUE TITLE
The same gene, but multiple insertion/deletions...

### ISSUE THREAD

**Issue by AndrzejN** [veg/hyphy#279]
Hi! Here is my VERY basic question. I'm trying to detect regions of gene under positive selection. I have a set of gene coding sequences, however this sequences have MANY deletions/insertions and different STOP codons. 

I'm unable to upload this sequences to DataMonkey.

I edit sequences (start/stop codon), did alignment using Muscle, then reverted it back to nucleotide sequence, whole alignment was saved in nexus format. DataMonkey is rejecting my sequences. I'm getting to the point to see gene names with indication at what position are STOP codons in my sequences, and that they are different.

Why I can't upload this sequences?

ANY help would be greatly appreciated.

BTW. I can run HyPhy analysis using mentioned alignment in MEGA 6...

**Comment by stevenweaver** [comment]
Hello AndrzejN,

Are you sure you are using the correct genetic code?

Your multiple sequence alignment contains both TAA and TGA codons. The only genetic code where both of those codons do not translate to a STOP codon is Flatworm mtDNA.

Documentation for the Genetic Codes are provided by [NCBI](http://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi#SG9) and on [Datamonkey](http://www.datamonkey.org//help/geneticcodes.ph).

Please let me know if this helps. 

Thanks,
Steven

**Comment by spond** [comment]
Hi Andrzej,

This sounds like a data format issue, which could be a simple NEXUS implementation quirks. 

Could you send us the file that's breaking?

Sergei

**Comment by AndrzejN** [comment]
Yes, my sequences have TAA and TGA codons, but why DataMonkey would reject this sequences?

Andrzej

Ps. I would rather not sent you my data :).

**Comment by AndrzejN** [comment]
This is error massage I'm getting: 8 stop codons found (detailed report below). Please double-check your alignment and ensure that only coding data are present and that the correct genetic code is selected.

**Comment by AndrzejN** [comment]
???

**Comment by spond** [comment]
Hi Andrzej,

Standalone HyPhy (including the version included in MEGA) will silently **strip** all sites with stop codons from an alignment. We made a conscious decision to disallow such behavior in Datamonkey, because it would permit the analysis of junk alignments (e.g. when no effort has been made to preserve the frame). In your case, I would suggest that you use the ```CleanStopCodons``` analysis in HyPhy (see http://www.datamonkey.org/help/data.php) to mask all the stop codons with '---' gaps, as this will preserve your alignment coordinates.

Best,
Sergei

**Comment by AndrzejN** [comment]
Thank you! It helped... I also found this information in manual. In general I don't find it very "intuitive" to stop processing seq. with STOP codons, however in case of badly prepared sequences this can be an issue.

Now, everything works great! I really like user interface and output created by DataMonkey.

Again, thank you very much for help and not ignoring "basic questions"!
