### ISSUE TITLE
Sequences from the same species vs. various species - same gene?

### ISSUE THREAD

**Issue by AndrzejN** [veg/hyphy#280]
I can't find simple answer for this question. Can I search for positive selection in the same gene but from various (closely) related species or I can only use gene seq. from the same specie (various individuals). 

If you can guide me where I can search for answer, I will be happy to learn more.

As you noticed I'm "quite new" into this topic.

**Comment by spond** [comment]
Hi Andrzej,

dN/dS measures are **better** suited for inter-species comparisons, because it is assumed that the observed differences are fixed (due to selection, genetic drift etc). The interpretation of dN/dS from a within-population sample is more difficult, because many of the sequence variants you see have not been subject to selective forces, so you may see elevated dN/dS even where there is no selection.

Sergei

**Comment by AndrzejN** [comment]
Thank you for your answer, my understanding was similar but was not sure, since many papers I look at, work with the same species and various haplotypes.

 I already did few tests and all of this tests show two positively selected sites based on my sequences. Some of tests on DataMonkey show more sites, but "manual" is saying some test are not that stringent. 

Now, I'm thinking about negative selection since there is also few sites...

I know that DataMonkey is "asking" about crossing over. Here I have similar question as above. I was thinking that crossing over would be better estimated within specie, but based on your answer situation would be similar here. I really curios how algorithm for crossing over detection works.

I actually have one more question. As I mentioned before my sequences have quite a bit of deletions/insertions and software for dN/dS is rejecting ALL sites which do not have full sequence coverage for all alignment among all seqences. This is quite BAD idea IMO, since e.g. one specie have deletion, but all other 9 (out of 10) don't. That particular site will be missed?! I think this creates quite a bias, especially when trying to work with let say 20 species. I have few "manual" ideas how to avoid it... but this can be quite difficult task to perform.

Again, thank you for answers, highly appreciated!

Andrzej

**Comment by spond** [comment]
Hi Andrzej,

Recombination detection is based on GARD, which is described in [http://mbe.oxfordjournals.org/content/23/10/1891.full](this MBE paper). It is based on seeing if a model with multiple trees (given a set of breakpoints) fits the data better than a model with a single tree, and using a genetic algorithm to place the breakpoints.

HyPhy and Datamonkey do **not** discard sites where at least one of the sequences has characters, even if the rest of the sequences have gaps. They treat gaps as completely missing data, so if you have 10 taxa, but one has a gap at a site, then the analysis at that site will effectively be using only 9 resolved sequences. 

Sergei
