### ISSUE TITLE
Job que backlog >2 days

### ISSUE THREAD

**Issue by Toktora** [veg/hyphy#281]
Hello, it appears someone has posted a huge job to process, which has been running for several days. This has caused a huge backlog in queued tasks. Any chance you could cancel the job holding up the works?

Thanks!

**Comment by stevenweaver** [comment]
Hi Toktora, 
Thank you for bringing this to our attention.
 
The offending job has been canceled. The job with the longest runtime is now 13 hours, and ensuring that the current queue's throughput is within an acceptable boundary will take place tomorrow morning. 

Thank you,
Steven
