### ISSUE TITLE
Interpretation data MEME analysis p-value /q-value versus FEL

### ISSUE THREAD

**Issue by julietdo** [veg/hyphy#284]
Hello,
I'm new in this site/lineage selection analysis and I would like clarify the interpretation of my results got by MEME in comparison with FEL to support the robustness of my data. I have a dataset of N = 210 Sequences and 147 codons. MEME found episodic selection (significant pvalue<0.05 or marginally significant pvalue 0.05- 0.07) at 18 sites. FEL determine 12/18 site positively selected.  

On these 12 sites detected with both FEL/MEME, I also check the q-value gave by MEME. 8 sites have a q-value > 0.1. In the discussion of the article related to the method, its suggested that it could be false positIve. How can I conclude on these results if FEL/MEME are p-value <0.05?

Other question, 2 sites are marginally significant with FEL (pvalues 0.063 and 0.055, respectivelly) but not significant with MEME, how explain it?

Thank you so much for your response
I can send more details on my results by email in case

**Comment by spond** [comment]
Hi Juliet,

Please see #188 for a discussion of p-values, q-values and multiple testing corrections. 

Regarding your question on FEL vs MEME, see this quote from our MEME paper

>This ensures that our inference is conservative. Even in the worst (and biologically unrealistic) case for >MEME, namely when selective pressures are constant throughout the phylogeny, the loss of power ?>compared to FEL is minimal: a site with FEL p-values between  0.0346 and 0.05  will be missed by >MEME, since its p-value will be  for the same ranges of the likelihood ratio test statistic (LRT). In our >simulation scenarios under the assumption of constant 5%, this translates to no more a  loss in power >>(Table S3).

Sergei
