### ISSUE TITLE
Installation path problem

### ISSUE THREAD

**Issue by francicco** [veg/hyphy#291]
All everyone,

I'm trying to install HyPhy on a cluster machine. I follow the instruction executing cmake with the proper environment setting (-DINSTALL_PREFIX=my/local/directory) to install the software locally and everything went smooth without error. I tried to execute a bf file to check is everything is ok and I did:

HYPHYMP BranchSiteREL.bf

it returns me the following error:

Error:
Could not read command file in ExecuteAFile.
Original path: '/usr/local/lib/hyphy/TemplateBatchFiles/TemplateModels/chooseGeneticCode.def'.
Expanded path: '/usr/local/lib/hyphy/TemplateBatchFiles/TemplateModels/chooseGeneticCode.def'

Function call stack
1 : ExecuteAFile from file HYPHY_LIB_DIRECTORY+"TemplateBatchFiles"+DIRECTORY_SEPARATOR+"TemplateModels"+DIRECTORY_SEPARATOR+"chooseGeneticCode.def" using basepath /gpfs/scratch/c7701100/apps/hyphy-2.2.4/res/TemplateBatchFiles/.
-------
Segmentation fault

It look like there is a path problem. HyPhy is searching in a different folder with respect the one I specified during the cmake execution.

How could I fix it?
Thanks
F

**Comment by ArtPoon** [comment]
Hi Francesco,

It looks like you're trying to install HYPHY on a shared clustering environment where you do not have write permissions to /usr/local/.

Based on the stacktrace your installation has been written to a shared user space under /gpfs/scratch, which is usually a part of the filesystem that is allocated for open use.  

You should either do a local install in your own home directory or ask the admin to install HYPHY for you.

Best,
- Art.

**Comment by spond** [comment]
Hi Francesco,

Could you confirm that `my/local/directory` contains HyPhy distribution files? If so, then it sounds like our CMake script may not be setting the compiled-in library path correctly. @stevenweaver will investigate and patch if necessary.

You can also override the default path for library files by using a command line argument 

```
LIBPATH=/path/to/lib/files
```

Sergei

**Comment by stevenweaver** [comment]
Hi Francesco, 

The most probable cause is that you forgot to run `make install` after compilation. `make install` copies the library batch files into the directory specified by the CMake INSTALL_PREFIX environment variable.

Regards,
Steven

**Comment by francicco** [comment]
Hi guys,

my/local/directory is actually the local directory where source code is store and where I'd like to install everything for local usage. And yes I did make install and it seems to work.

I don't know which is the operating system, but the cluster is this (http://www.uibk.ac.at/zid/systeme/hpc-systeme/leo3/).
Cmake version is the latest 3.2.2.

I'll try the Sergei advise, LIBPATH and see...

Thanks guys

**Comment by francicco** [comment]
Using -LIBPATH flag it works!!!
Great!

Now comes the hard stuff...

Thanks guys
