### ISSUE TITLE
Downloading data timeout

### ISSUE THREAD

**Issue by sonnynguyen** [veg/hyphy#293]
I had a rather large dataset analyzed, but server times out when I try to download the FASTA file from ASR module (its hase 391 sequences).  Is there anyway I can retrieve this?

**Comment by stevenweaver** [comment]
Hello sonnynguyen, 

Datamonkey is having an issue handling your analysis request. 

Please allow me to try resolving the issue before trying again. 
I'll have an update for you before 2015-05-22T00:00:00Z

Thanks,
Steven

**Comment by stevenweaver** [comment]
Hello sonnynguyen,

Datamonkey is unable to parse the results of an ASR analysis with this many sequences. 

Can you either rerun the analysis with fewer sequences, or email me directly at sweaver@ucsd.edu with the url that was generated for you?

Thanks,
Steven
