### ISSUE TITLE
Internal error in _LikelihoodFunction

### ISSUE THREAD

**Issue by francicco** [veg/hyphy#294]
Hallo everyone,

I'm executing the aBSREL analysis after compiling the software on a UNIX cluster machine (http://www.uibk.ac.at/zid/systeme/hpc-systeme/leo3/). Unfortunately it gives me the following error:

Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-14957.46980740712] does not match the last recorded LF maximum [-14957.46980740713]

@spond told me that I should edit the source and recompile. But how? Does anybody can help me?

Thanks
F

**Comment by spond** [comment]
Hi francicco,

You could comment out these lines https://github.com/veg/hyphy/blob/331b751eb8624c58196ee8890ffbebc3e693a21a/src/core/likefunc.cpp#L5880-5883 and recompile.

Sergei

**Comment by francicco** [comment]
Thanks a lot! I'll give it a try!
F
