### ISSUE TITLE
How to deal with saturation in aBSREL?

### ISSUE THREAD

**Issue by PakornAiewsakun** [veg/hyphy#295]
Hi there,

I have a got a (baseline) tree from aBSREL (Hyphy 2.2.4). However, some of the internal branches are fully saturated, as indicated by their extremely long lengths (> 1000 substitutions per site). I would like to use this tree for evolutionary timescale inference. So, what are the proper ways of dealing with these branches in this scenario? Any helps will be very much appreciated. 

Best,
Pakorn

**Comment by spond** [comment]
Hi Pakorn,

There really is no *proper* way to deal with this; you should proceed with you analysis assuming that the current models are unable to accurately estimate branch lengths (i.e. they are infinite).

Sergei

**Comment by PakornAiewsakun** [comment]
Thank you very much!
