### ISSUE TITLE
error message using batch file

### ISSUE THREAD

**Issue by eab75** [veg/hyphy#296]
Hi there, I am running Slatkin-Maddison compartmentalization tests on trees with more than 2 groups and using an "all pairwise" batch file to perform all possible 2-way comparisons among these groups.  I encountered the following error that I need help interpreting.  Can you tell by a quick look what the problem might be?

Thanks!

Running 'Macintosh HD:Users:boritze:Desktop:Eli.ControllerMS.05262015:Newick trees:1AllPairwise.bf'

Group1	Group2	p-value
HXB2	Plasma	0.999000999000999
HXB2	N	0.999000999000999
HXB2	CM	0.999000999000999
HXB2	TM	0.999000999000999
HXB2	EM	0.999000999000999
HXB2	LNCMPD1lo57lo	0.999000999000999
HXB2	LNnGC	0.999000999000999
HXB2	LNTfh	0.999000999000999
HXB2	LNEM	0.999000999000999
Plasma	N	0.999000999000999
Plasma	CM	0
Plasma	TM	0.000999000999000999
Plasma	EM	0
Plasma	LNCMPD1lo57lo	0.001998001998001998
Plasma	LNnGC	0
Plasma	LNTfh	0
Plasma	LNEM	0
N	CM	0.999000999000999
N	TM	0.7052947052947053
N	EM	0.06893106893106893
Error:
Ran out of input in buffer during a redirected standard input read.

Function call stack
1 : fprintf(PROMPT_FOR_FILE,CLEAR_FILE,"Tree theTree=",Format(givenTree,1,0),";\n_branchClasses={};\n")
	Standard input redirect:
		Empty Associative List-------
2 : LoadFunctionLibrary from file"SlatkinMaddison" using basepath Macintosh HD:Users:boritze:Desktop:Eli.ControllerMS.05262015:Newick trees:. reading input from {"00":pathtotemp,"01":"2","02":partitionIDs[_p1],"03":"y","04":partitionIDs[_p1],"05":partitionIDs[_p2],"06":pathtosm,"07":"Most certainly","08":"1000"}
-------
Error:
Ran out of input in buffer during a redirected standard input read.

Function call stack
1 : Choice List for Permutation Test with choice list:SKIP_NONE. Store result in resample
	Standard input redirect:
		Empty Associative List-------
2 : LoadFunctionLibrary from file"SlatkinMaddison" using basepath Macintosh HD:Users:boritze:Desktop:Eli.ControllerMS.05262015:Newick trees:. reading input from {"00":pathtotemp,"01":"2","02":partitionIDs[_p1],"03":"y","04":partitionIDs[_p1],"05":partitionIDs[_p2],"06":pathtosm,"07":"Most certainly","08":"1000"}
-------
Error:
Not a valid option: '' passed to Choice List 'Permutation Test' using redirected stdin input

Function call stack
1 : Choice List for Permutation Test with choice list:SKIP_NONE. Store result in resample
	Standard input redirect:
		Empty Associative List-------
2 : LoadFunctionLibrary from file"SlatkinMaddison" using basepath Macintosh HD:Users:boritze:Desktop:Eli.ControllerMS.05262015:Newick trees:. reading input from {"00":pathtotemp,"01":"2","02":partitionIDs[_p1],"03":"y","04":partitionIDs[_p1],"05":partitionIDs[_p2],"06":pathtosm,"07":"Most certainly","08":"1000"}

**Comment by spond** [comment]
Hi eab75,

My guess is the pair of tags that follows *N* *EM* in the testing order (the last one successfully done) has 0 branches in one of the bins. Can you double check that all of the labels match at least one of the leaves?

Sergei

**Comment by eab75** [comment]
Hi Sergei, I double checked and all the bins have multiple branches.  I have a cohort of 20 individuals each of whom has a sequence alignment, and I made each individual's group file by breaking the clone names from the original FASTA down into columns using textwrangler, then pasting the group name column in next to the list of clone names derived from that same FASTA.

I did notice that for this problem happened at the same spot in the order for all three individuals for whom I have the following bins, shown in the order in which they occur in the group files
1)  Plasma
2)  CM
3)  TM
4)  EM
5)  LNCMPD1lo57lo (or in one case just LNCMPD1lo)
6)  LNnGC
7)  LNTfh
8)  LNEM

In all three of the individuals with these 8 bins, Plasma makes it all the way through, but then the error occurs when comparing CM to LNCMPD1lo57lo.  I don't know why that comparison is a problem - the Plasma comparison to each of those two bins was ok.  Do you have any ideas?  Below are the details from the HyPhy console.

Thank you!
Eli

Running 'Macintosh HD:Users:boritze:Desktop:Eli.ControllerMS.05262015:HyPhy files:1AllPairwise.bf'

Group1	Group2	p-value
Plasma	CM	0
Plasma	TM	0.006993006993006993
Plasma	EM	0
Plasma	LNCMPD1lo57lo	0.001998001998001998
Plasma	LNnGC	0
Plasma	LNTfh	0.000999000999000999
Plasma	LNEM	0
CM	TM	0.02397602397602398
CM	EM	0
Error:
Ran out of input in buffer during a redirected standard input read.

Function call stack
1 : fprintf(PROMPT_FOR_FILE,CLEAR_FILE,"Tree theTree=",Format(givenTree,1,0),";\n_branchClasses={};\n")
	Standard input redirect:
		Empty Associative List-------
2 : LoadFunctionLibrary from file"SlatkinMaddison" using basepath Macintosh HD:Users:boritze:Desktop:Eli.ControllerMS.05262015:HyPhy files:. reading input from {"00":pathtotemp,"01":"2","02":partitionIDs[_p1],"03":"y","04":partitionIDs[_p1],"05":partitionIDs[_p2],"06":pathtosm,"07":"Most certainly","08":"1000"}
-------
Error:
Could not create/open output file at path ''. in call to fprintf(

Function call stack
1 : fprintf(PROMPT_FOR_FILE,CLEAR_FILE,"Tree theTree=",Format(givenTree,1,0),";\n_branchClasses={};\n")
	Standard input redirect:
		Empty Associative List-------
2 : LoadFunctionLibrary from file"SlatkinMaddison" using basepath Macintosh HD:Users:boritze:Desktop:Eli.ControllerMS.05262015:HyPhy files:. reading input from {"00":pathtotemp,"01":"2","02":partitionIDs[_p1],"03":"y","04":partitionIDs[_p1],"05":partitionIDs[_p2],"06":pathtosm,"07":"Most certainly","08":"1000"}
-------

Running 'Macintosh HD:Users:boritze:Desktop:Eli.ControllerMS.05262015:HyPhy files:1AllPairwise.bf'

Group1	Group2	p-value
Plasma	CM	0.999000999000999
Plasma	TM	0.4615384615384616
Plasma	EM	0
Plasma	LNCMPD1lo57lo	0.999000999000999
Plasma	LNCD57	0.1728271728271728
Plasma	LNnGC	0.6143856143856143
Plasma	LNTfh	0.999000999000999
Plasma	LNEM	0.2727272727272727
CM	TM	0.7912087912087912
CM	EM	0
Error:
Ran out of input in buffer during a redirected standard input read.

Function call stack
1 : fprintf(PROMPT_FOR_FILE,CLEAR_FILE,"Tree theTree=",Format(givenTree,1,0),";\n_branchClasses={};\n")
	Standard input redirect:
		Empty Associative List-------
2 : LoadFunctionLibrary from file"SlatkinMaddison" using basepath Macintosh HD:Users:boritze:Desktop:Eli.ControllerMS.05262015:HyPhy files:. reading input from {"00":pathtotemp,"01":"2","02":partitionIDs[_p1],"03":"y","04":partitionIDs[_p1],"05":partitionIDs[_p2],"06":pathtosm,"07":"Most certainly","08":"1000"}
-------
Error:
Could not create/open output file at path ''. in call to fprintf(

Function call stack
1 : fprintf(PROMPT_FOR_FILE,CLEAR_FILE,"Tree theTree=",Format(givenTree,1,0),";\n_branchClasses={};\n")
	Standard input redirect:
		Empty Associative List-------
2 : LoadFunctionLibrary from file"SlatkinMaddison" using basepath Macintosh HD:Users:boritze:Desktop:Eli.ControllerMS.05262015:HyPhy files:. reading input from {"00":pathtotemp,"01":"2","02":partitionIDs[_p1],"03":"y","04":partitionIDs[_p1],"05":partitionIDs[_p2],"06":pathtosm,"07":"Most certainly","08":"1000"}
-------

Running 'Macintosh HD:Users:boritze:Desktop:Eli.ControllerMS.05262015:HyPhy files:1AllPairwise.bf'
Plasma	CM	0.02297702297702298
Plasma	TM	0.7162837162837162
Plasma	EM	0
Plasma	LNCMPD1lo	0.8131868131868132
Plasma	LNnGC	0.6333666333666333
Plasma	LNTfh	0.03896103896103896
Plasma	LNEM	0.1118881118881119
CM	TM	0.05294705294705294
CM	EM	0.005994005994005994
Error:
Ran out of input in buffer during a redirected standard input read.

Function call stack
1 : fprintf(PROMPT_FOR_FILE,CLEAR_FILE,"Tree theTree=",Format(givenTree,1,0),";\n_branchClasses={};\n")
	Standard input redirect:
		Empty Associative List-------
2 : LoadFunctionLibrary from file"SlatkinMaddison" using basepath Macintosh HD:Users:boritze:Desktop:Eli.ControllerMS.05262015:HyPhy files:. reading input from {"00":pathtotemp,"01":"2","02":partitionIDs[_p1],"03":"y","04":partitionIDs[_p1],"05":partitionIDs[_p2],"06":pathtosm,"07":"Most certainly","08":"1000"}
-------
Error:
Could not create/open output file at path ''. in call to fprintf(

Function call stack
1 : fprintf(PROMPT_FOR_FILE,CLEAR_FILE,"Tree theTree=",Format(givenTree,1,0),";\n_branchClasses={};\n")
	Standard input redirect:
		Empty Associative List-------
2 : LoadFunctionLibrary from file"SlatkinMaddison" using basepath Macintosh HD:Users:boritze:Desktop:Eli.ControllerMS.05262015:HyPhy files:. reading input from {"00":pathtotemp,"01":"2","02":partitionIDs[_p1],"03":"y","04":partitionIDs[_p1],"05":partitionIDs[_p2],"06":pathtosm,"07":"Most certainly","08":"1000"}

**Comment by eab75** [comment]
I decided to remake the files and remove some of the subsets, because everything starting with "LN" can be analyzed a bit later.  Now I can't even open the newick tree files I created, with the following error.  I don't know if this problem and the previous one are related.  Can you tell?

Running 'Macintosh HD:Users:boritze:Desktop:1AllPairwise.bf'
Error:
Macintosh HD:Users:boritze:Downloads:Compartmentalization tes#3F46E2:S1207.nwk could not be opened for reading by fscanf. Path stack: {Macintosh HD:Users:boritze:Desktop:}

Function call stack
1 : Read the following data from PROMPT_FOR_FILE : Tree into omnibusTree;

**Comment by spond** [comment]
Hi Eli,

Your old error: because each tag is interpreted as a regular expression, when you compare `CM` to `LNCMPD1lo57lo`, the `CM` tag will also match LN**CM**PD1lo57lo, because CM is a substring of LNCMPD1lo57lo.  One option to invert the tags so that `LNCMPD1lo57lo` is before `CM` in the list. Another option is to ensure that the tags are mutually exclusive.

You new error: the tree file name is too long (this a legacy issue which will go away in the next version of HyPhy); trim it to <32 characters.

Sergei

**Comment by eab75** [comment]
All analyses done.  Thanks so much, Sergei!
Eli
