### ISSUE TITLE
Help get install hyphy with the downloaded source code from github in OSX Mavericks

### ISSUE THREAD

**Issue by jacksonlima** [veg/hyphy#297]
Dear all,

Sorry for the very noob question, but I would like to have help installing hyphy in osx mavericks, I do not know what to do with the downloaded file here on github.

Xcode opens the window and do not know what to do.

Best regards,

Jackson Lima

**Comment by spond** [comment]
Hi Jackson,

From the terminal ($ is the prompt symbol; please insert appropriate directories instead of [] placeholders based on where you downloaded the file to)
```
$cd [where the zip file is]
$unzip [zip file name, e.g. 2.2.4.zip]
$cd hyphy-2.2.4/
$cmake ./
$make MP2
$sudo make install [enter password when prompted]
$cd [work direcory]
$/usr/local/bin/HYPHYMP 
```

Sergei
