### ISSUE TITLE
node name recognition

### ISSUE THREAD

**Issue by jlearn** [veg/hyphy#298]
I can't get HyPhy to apparently accept the node names from my newick treefile.

I've changed them several times and I repeatedly get the error message:

Error:
Node names should begin with a letter, a number, or an underscore.

Here are some examples:

Running 'Mac OS X:Applications:HyPhy.app:Contents:Resources:HBL:TemplateBatchFiles:SlatkinMaddison.bf'
Error:
Node names should begin with a letter, a number, or an underscore. Had:((((((((((((08D038.?PRBO13.VAC.AK:0.0016443074999999

Function call stack
1 : Read the following data from PROMPT_FOR_FILE : Tree into givenTree;
-------

Running 'Mac OS X:Applications:HyPhy.app:Contents:Resources:HBL:TemplateBatchFiles:SlatkinMaddison.bf'
Error:
Node names should begin with a letter, a number, or an underscore. Had:((((((((((((x08038.?PRBO13.VAC.AK:0.0016443074999999

Function call stack
1 : Read the following data from PROMPT_FOR_FILE : Tree into givenTree;
-------

Running 'Mac OS X:Applications:HyPhy.app:Contents:Resources:HBL:TemplateBatchFiles:SlatkinMaddison.bf'
Error:
Node names should begin with a letter, a number, or an underscore. Had:(('x08194.?PRBL18.CON.AK':0.002028339800000

Function call stack
1 : Read the following data from PROMPT_FOR_FILE : Tree into givenTree;

**Comment by ArtPoon** [comment]
For starters, HyPhy doesn't like dot ('.') characters in node names, so you will have to replace those with underscores.

**Comment by spond** [comment]
Hi Jerry,

The error message is not informative, I apologize for that. Art is correct - the cause for this particular error is the presence of `.` characters in the names.

Sergei

**Comment by jlearn** [comment]
Thanks, Art. I had forgotten that. It works now.

Jerry

**Comment by ArtPoon** [comment]
Happy to help, Jerry :-)

**Comment by ritasianga** [comment]
hello, I am getting the same error but I do not have . on my node name. PLease help

((S_00006:0.08171000,(((((S_00032:0.08668000,(S_00011:0.08241000,(S_00012:0.07014000,S_00013:0.05874000):0.01813000):0.01432000):0.01866000,((S_00014:0.06922000,S_00015:0.08180000):0.02813000,(((S_00033:0.08125000,(S_00038:0.04313000,((S_00040:0.03683000,(S_00039:0.04096000,S_00035:0.06110000):0.00589000):0.00228000,(S_00036:0.01841000,S_00037:0.02328000):0.03798000):0.01046000):0.02442000):0.00613000,S_00034:0.06828000):0.01489000,(S_00016:0.09412000,(((S_00023:0.05784000,(S_00021:0.05059000,S_00022:0.05445000):0.00891000):0.00636000,((S_00024:0.04738000,S_00025:0.04544000):0.00647000,((S_00026:0.03159000,(S_00029:0.02812000,(S_00028:0.03403000,S_00027:0.03514000):0.00595000):0.03477000):0.01357000,(S_00019:0.02386000,(S_00018:0.03709000,S_00020:0.02159000):0.00574000):0.05187000):0.00436000):0.00814000):0.02070000,(S_00030:0.06533000,S_00031:0.06004000):0.01292000):0.01572000):0.01209000):0.01327000):0.00879000):0.01114000,(S_00008:0.07677000,S_00009:0.07541000):0.03554000):0.00956000,(S_00003:0.08977000,S_00010:0.08383000):0.01327000):0.00845000,(S_00007:0.07245000,(S_00004:0.05586000,S_00005:0.06197000):0.03363000):0.02100000,S_00002:0.09531000):0.00798000):0.00998000,S_00017:0.09588000);
