### ISSUE TITLE
User tree requires registration in Datamonkey but I can't find where to register

### ISSUE THREAD

**Issue by DavidEnard** [veg/hyphy#299]
As the the title says, I can't find where to register as I want to use my own user tree. I need to use DataMonkey to use BGM as I could never make it work with my local install of hyphy-2.2.

Thanks in advance for your help :)

**Comment by ArtPoon** [comment]
Hi David,

Have you tried using BGMs with the latest update to HyPhy?  I had to patch some of the code a little while ago and it should be working now.

What format of file are you trying to upload to Datamonkey?  (Fasta, Nexus?) 

Cheers,
- Art.

**Comment by DavidEnard** [comment]
Hi Art,

Thanks for the very fast answer. As you recommended I updated to Hyphy 2.2.4 and now it works perfectly :). Thanks again for your help.
David.

**Comment by ArtPoon** [comment]
Great, I'm glad it's working for you!  Sorry for the inconvenience, there's been a lot of code refactoring under the hood and the BGM's got left out in the dark for a while.
