### ISSUE TITLE
Need help installing HyPhy

### ISSUE THREAD

**Issue by olgakamneva** [veg/hyphy#300]
Hi Everyone, 
I am trying to install command line version pf HyPhy on MAC OS X 10.7.5.
I get hyphy from hit
$ git clone https://github.com/veg/hyphy.git
Cloning into hyphy...
remote: Counting objects: 21298, done.
remote: Total 21298 (delta 0), reused 0 (delta 0), pack-reused 21298
Receiving objects: 100% (21298/21298), 49.91 MiB | 777 KiB/s, done.
Resolving deltas: 100% (14587/14587), done.

and then follow instructions from Wiki:
$ cd hyphy

$ cmake ./
-- The C compiler identification is GNU 4.2.1
-- The CXX compiler identification is GNU 4.2.1
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /Developer/usr/bin/cc
-- Check for working C compiler: /Developer/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /Developer/usr/bin/c++
-- Check for working CXX compiler: /Developer/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_AVX_EXTENSIONS
-- Performing Test HAVE_AVX_EXTENSIONS - Failed
-- Performing Test HAVE_SSE3_EXTENSIONS
-- Performing Test HAVE_SSE3_EXTENSIONS - Success
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found CURL: /usr/lib/libcurl.dylib (found version "7.21.4") 
-- Found PythonInterp: /Users/okk/Library/Enthought/Canopy_64bit/User/bin/python (found version "2.7.3") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found OpenCL: /System/Library/Frameworks/OpenCL.framework  
-- Found MPI_C: /usr/local/lib/libmpi.dylib  
-- Found MPI_CXX: /usr/local/lib/libmpi_cxx.dylib;/usr/local/lib/libmpi.dylib  
-- Configuring done
WARNING: Target "hyphy_mp" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "HYPHYMP" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "HYPHYOCL" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "HYPHYMPI" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
-- Generating done
-- Build files have been written to: /Users/okk/Downloads/hyphy

Those are just warnings so I ignored those and did:
$ make MP2
Scanning dependencies of target HYPHYMP
[  0%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/_hyExecutionContext.cpp.o
cc1plus: warning: command line option "-Wno-int-to-pointer-cast" is valid for C/ObjC but not for C++
cc1plus: error: unrecognized command line option "-Wno-conversion-null"
cc1plus: error: unrecognized command line option "-Wno-dangling-else"
cc1plus: error: unrecognized command line option "-Wno-logical-op-parentheses"
make[3]: *** [CMakeFiles/HYPHYMP.dir/src/core/_hyExecutionContext.cpp.o] Error 1
make[2]: *** [CMakeFiles/HYPHYMP.dir/all] Error 2
make[1]: *** [CMakeFiles/MP2.dir/rule] Error 2
make: *** [MP2] Error 2

As of now, I do not know out how to fix this error and will appreciate help. This is the version of make I have:
$ make -version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.0

**Comment by stevenweaver** [comment]
Hi olgakamneva,

It looks like you may be using an older, unsupported version of gcc. 
Can you verify that you are using a version >= 4.5 by running the command `gcc --version`?

Additionally, if you have multiple versions of GCC installed on your machine, you can set the correct gcc by using a command like `cmake  -DCMAKE_CXX_COMPILER=/path/to/gcc -DCMAKE_C_COMPILER=/path/to/g++ ./`

Regards,
Steven

**Comment by stevenweaver** [comment]
Hi olgakamneva, 

Since you are using an older version of OSX, perhaps you can try installing a packaged dmg located [here](https://github.com/veg/hyphy/releases).

Best,
Steven

**Comment by spond** [comment]
Hi Steven,

Can you modify the configuration file to set the flags for gcc 4.4? I think this is the lowest version we can use and still support what we need to support?

Sergei
