### ISSUE TITLE
MPI environment missing

### ISSUE THREAD

**Issue by bpfeffer** [veg/hyphy#302]
I'm trying to run HYPHYMPI with GARD and we have openmpi as our MPI, when I try to run this with mpirun I get [ERROR] This analysis requires an MPI enviroment to run"

I've tried using:
```
mpirun -np 8 HYPHYMPI /usr/local/lib/hyphy/TemplateBatchFiles/GARD/bf
```
Along with just trying mpirun with HYPHYMPI and it always comes down to that error. I know MPI works because I use mpiexec with Ray all the time. I figured I'd try this with mpiexec and got the same message. Thanks in advance for any help!

Edit: Details for clarity. CentOS 6.3 64-bit with latest version of hyphy and openmpi 1.5.4

**Comment by ArtPoon** [comment]
Are you using OpenMPI or MPICH?  I think HyPhy is not crazy about OpenMPI.

**Comment by ArtPoon** [comment]
I just reproduced this on my cluster.  If I try to launch `HYPHYMPI` with OpenMPI using your invocation (minus the typo in `GARD.bf`) then I get
```
[ERROR] This analysis requires an MPI environment to run
```
8 times.

If I switch to my other MPI distro (MPICH) then the script runs normally.

**Comment by bpfeffer** [comment]
Thanks for the suggestion, I installed mpich to side directory and it worked calling that version of mpirun instead.

**Comment by stevenweaver** [comment]
Hi, 

As clarification, this is probably because HYPHYMPI was built with MPICH. 

HYPHYMPI needs to be built with the desired `PATH`, `LD_LIBRARY_PATH`, and `MPI*` environment variables set. We use OpenMPI on our cluster with HyPhy. 

Generally, this is done using the command `module load <openmpi module>` on your cluster. 

Thanks,
Steven

**Comment by ArtPoon** [comment]
Is that documented?  I can't find any mention of it in `README.md`.

**Comment by stevenweaver** [comment]
I can make adjustments to the README.md soon. I've only tested HyPhy with openmpi >= 1.6.3, so I may need to check if it works with earlier versions.
