### ISSUE TITLE
Base Composition Question. 

### ISSUE THREAD

**Issue by dagarfield** [veg/hyphy#304]
Tests for selection on non-coding regions....the reviewers....well, they don't hate it!
But they do raise a few issues, and one of them has me perplexed. 

For these tests, I'm using synonymous substitutions within a gene to evaluate substitution patterns in that gene's flanking regulatory regions (e.g. Haygood et al. 2007). This is fine, but the reviewer points out that synonymous sites are often under selection in Drosophila, so it would be nice to see the results tested with 4d sites (four fold degenerate sites).   

I think this is doable. I *think* I can figure out a rate matrix that would work for this problem, and I know I can at least concatenate the 4d sites and treat them as an intronic neutral proxy. But I'm worried about base composition. The 4d sites have a rather different base composition than the rest of the genome. 

The question: Should I be worried about this? If so, can I do anything about it? 

Cheers,

David

**Comment by dagarfield** [comment]
(my first impulse is to say that this is OK -- I'm only using branch length from the neutral proxy, and not the fitted substitution matrix. Still, if someone raised the issue, maybe they see something I don't...)

**Comment by spond** [comment]
Hi David,

Synonymous substitutions are definitely under selection, not just in Drosophila, but more generally. I am, for one, not particularly keen on using 4-fold degenerate sites as a means to *filter* out selective signals. 

1. It's an ugly hack -- if one uses codon model, a synonymous substitution is just that regardless of what position in the codon it hits.

2. A 4-fold degenerate site is only 4-fold degenerate if you **require** the first two positions in the codon to remain constant. As soon as those change, your site is no longer 4-fold degenerate. In other words, they are context sensitive, and generally ill-defined.

3. There is likely selection operating on these sites as well (however ill-defined they may be).

To address the reviewer's concerns, you could fit a **distribution** of synonymous substitution rates to sites, and use its **mean** (or any other statistic) as a reference point. That way your model already accounts for selection at different sites in a natural way, and if you use a CF3x4 codon frequency estimator, then you should also have a handle on position-to-position variation in base frequencies. 

Let me know if you need help with implementing the above.

Sergei

**Comment by dagarfield** [comment]
Hmm...all good points, and a strong argument in favour of the codon model. 
I think I've managed the switch the CF3x4, but I'm not sure I can manage the implementation of the later (or that I totally understand it....something like the section "Site-to-site rate heterogeneity" in the HyPhy book chapter?).

Any help you can provide would be much appreciated, as we'd like to make use of HyPhy for future non-coding analyses. 
I've posted my HyPhy code and example files here:

ftp://ftp-exchange.embl.de/pub/exchange/garfield/HyPhy/exampleFiles.zip

Many thanks!

--DG

**Comment by spond** [comment]
Hi David,

I am unable to download the archive you have linked:

```
Sergeis-MacBook-Pro:UserData sergei$ wget ftp://ftp-exchange.embl.de/pub/exchange/garfield/HyPhy/exampleFiles.zip
--2015-06-17 14:02:56--  ftp://ftp-exchange.embl.de/pub/exchange/garfield/HyPhy/exampleFiles.zip
           => `exampleFiles.zip'
Resolving ftp-exchange.embl.de... 194.94.44.17
Connecting to ftp-exchange.embl.de|194.94.44.17|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... 
Server error, can't determine system type.
==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/exchange/garfield/HyPhy ... done.
==> SIZE exampleFiles.zip ... 21433
==> PASV ... done.    ==> RETR exampleFiles.zip ... 
No such file `exampleFiles.zip'.

```

Sergei

**Comment by dagarfield** [comment]
Gawh! Server permissions issues.
Updated:
ftp://ftp-exchange.embl.de/pub/exchange/garfield/HyPhy/

**Comment by spond** [comment]
Hi David,

OK, the link works now. Give me a few days...

Sergei
