### ISSUE TITLE
Hyphy command line version for WIndows

### ISSUE THREAD

**Issue by darrenpmartin** [veg/hyphy#307]
I've tried and failed to compile a command line version of hyphy for windows.  Would it be possible for you to post one?

**Comment by stevenweaver** [comment]
Hello, 

We currently do not support a command line version of HyPhy for Windows. 
Have you tried installing our exe available on https://github.com/veg/hyphy/releases?

Thanks,
Steven

**Comment by darrenpmartin** [comment]
Thanks for the reply Steven - Segei asked me to post here as a reminder for him to compile a command line version for Windows.

**Comment by darrenpmartin** [comment]
Hi Steven

Thanks for the Reply - Sergei asked me to post on github as a reminder to
send me a windows command line version when he gets around to compiling it.

cheers
darren

**Comment by spond** [comment]
Hi Darren,

I'll compile a version and add it to the binaries list.

Sergei
