### ISSUE TITLE
HyPhy Batch file for YangNielsenBranchSite-2005 model

### ISSUE THREAD

**Issue by aatu18** [veg/hyphy#309]
Hi,

I would like to run the original 2005 branch-site model by Yang and Nielsen in HyPhy. Is there a batch file for this (i.e. not the modified absrel/busted ones)? I tried the "YangNielsenBranchSite2005.bf" from the following link, https://github.com/veg/hyphy/blob/master/res/TemplateBatchFiles/YangNielsenBranchSite2005.bf
However, this one throws errors when the HKY85 model is used to calculate approximate starting values for kappa and branch lengths. I am wondering if there is a modified batch file that fixes this? If not, I could just work around it by providing some dummy starting values. 

Thanks for any suggestion,
Aarti

**Comment by spond** [comment]
Hi Aarti,

You are using the correct batch file. I am not able to readily reproduce the error. Could you please paste in the output from your interaction with HyPhy that cause this error to be generated? 

Sergei

**Comment by aatu18** [comment]
Hi Sergei,

Here is the error I get:

Error:
nucFreqs must be a column vector of the same dimension as the model matrix in the call to Model = ...

Function call stack
1 : Define the model HKY85_Model using transition matrix 'HKY85_Matrix' and equilibrium frequencies 'nucFreqs'
-------

I see that the script correctly runs until step #9 of the batchfile, i.e. defining the codon model GY_Model. This error is thrown in step #10 where it is approximating kappa and branchlenghts using an HKY85 model fit. The line "HarvestFrequencies (nucFreqs,ds,1,1,1);" in the batch file should ideally produce a matrix of nucleotide frequencies to be used with the HKY85 matrix, however, if I print out the contents of nucFreqs, it gives a 20 element matrix (instead of a 4 element base frequency matrix), like the one below, and terminates with the above mentioned error.

nucFreqs = {
{0.08798097708603546}
{0.1552096843925638}
{0}
{0}
{0}
{0.1191093817552961}
{0}
{0}
{0}
{0}
{0}
{0.5002161694768699}
{0}
{0}
{0}
{0}
{0.1374837872892348}
{0}
{0}
{0}
}

I initially thought the N's in my alignment were probably causing harvest frequencies to behave differently?, and therefore tested it on an alignment with no Ns. At that point I didnt get this error. However, on a second alignment with no N's I still get the same error, implying this may not be the cause. 

Thanks very much for any advice on what could be the issue. I also just started using hbl, apologies for the newbee'ishness.

Aarti

**Comment by spond** [comment]
Hi Aarti,

HyPhy parses your alignment as a protein alignment; this can happen with many 'N' characters as you have noticed. You can force HyPhy to treat the data as nucleotides, for example if you use the NEXUS format (which allows you to specify the type of sequences included), or using the BASE4 HyPhy-specific hack: if the first line in your FASTA file is 

```
$BASESET:"ACGT"
```

this will instruct HyPhy to only consider the 4 bases as valid characters. 

Sergei

**Comment by aatu18** [comment]
Great, thank you very much for that, It fixed the issue.
