### ISSUE TITLE
pi_S calculation in HyPhy's  F_ST.bf

### ISSUE THREAD

**Issue by alliblk** [veg/hyphy#310]
Hello HyPhy community,

I am using HyPhy's F_ST program to test for population structure due to geographic subdivision and host species subdivision in a population of rhabdoviruses (work for my Master's thesis). From the output, I have been using the Hudson, Boos, and Kaplan (1992) test, which appears to calculate F_ST as (pi_T-pi_S)/pi_T. 

How exactly does HyPhy calculate Pi_S (the mean subpopulation diversity)? Since HyPhy does not report pi for each subpopulation, but rather just the mean pi of the subpopulations, I used MEGA to determine the intrapopulation nucleotide diversities for the defined subpopulations that I used in HyPhy. If I calculate an unweighted mean of the subpopulation nucleotide diversities from MEGA, I get a different estimate of the mean subpopulation diversity than HyPhy returns for Pi_S. 

I've been trying to figure out what is going on, and it appears that HyPhy is calculating a weighted mean for the mean subpopulation diversity, with the weights related to the proportion of taxa in each subgroup. In my data, one subpopulation is almost 2x as diverse as the other subpopulation, however the more diverse subgroup only represents ~25% of the taxa under study. Thus HyPhy's estimates of the mean subpopulation diversity are lower than my unweighted subpopulation mean (ie. it appears that HyPhy's estimate of Pi_S is much closer to the estimate of pi in the less diverse, larger subpopulation). This then means that the estimates of F_ST calculated by HyPhy are much higher than they are if I use the unweighted mean subpopulation diversity that I calculate by hand. For instance, HyPhy's estimation of F_ST (Hudson, Boos, and Kaplan) for geographic subdivision is 0.379. However if I use my unweighted mean as Pi_S, the F_ST drops to 0.128.

I'm new to this field, and so I'm wondering is this the typical way that pi_S is calculated, and if so, what is the reasoning behind this way of calculating pi_S? Do I need my subgroups to be of identical size? Any help and/or guidance would be much appreciated!

Best,
Allison

**Comment by spond** [comment]
Hi Allison,

The relevant code from HyPhy (F_ST.bf) is 

```
	dd1 = sum1[0]/count1[0]*f_1^2+sum2[0]/count2[0]*f_2^2;
	
	resMatrix[2] = sum3[0]/(count3[0]-bothCladesSize);	/* pi_B */
	resMatrix[1] = dd1/(f_1^2+f_2^2);			        /* pi_S */
	resMatrix[0] = dd1 + 2*f_1*f_2*resMatrix[2];        /* pi_T */
```

Here *f_i* is the fraction of sequences in sample *i* (note that they don't necessarily add up to 1). *sum1[0]/count1[0]* is the raw mean of pairwise distances between sequences in sample 1 (and analogously for sample 2). 

I tend to think of F_st as measure of likely it is that two sequences sampled (randomly) from different populations are more distant from each other than two sequences sampled (randomly) from the same population. Random (unweighted) sampling from populations of different sizes will yield more samples from that population, hence the weighting.

Also, remember **not** to use raw F_ST values, but rather look at the p-value obtained by permutations. This will preserve the biased sample sizes, and give you an estimate of whether or not your observed value is unusually high.

Sergei

**Comment by alliblk** [comment]
Hi Sergei,

Thank you very much for your explanation, this helps me understand what is going on much better!

Best,
Allison
