### ISSUE TITLE
Hyphy with a new codon substitution model

### ISSUE THREAD

**Issue by aatu18** [veg/hyphy#311]
Hi Sergei,

I am running the Yang-Nielsen branch-site model using HYPHYMP. I want to use the branch-site model with my own custom defined codon substitution model. For that, I modified the GY codon substitution model in the batch file YangNielsenBranchSite2005.bf by adding an additional parameter to the rate matrix. When I execute the batch file, I run into the following error:

Error:
Operation 'MAccess' is not implemented/defined for a Number

Function call stack
1 : Branch under condition '_GeneticCode[0][h]==_GeneticCode[0][v]'
	to
		Branch to Branch to GY_Matrix[h-hshift][v-vshift]:=synRate*delta*kappa_inv*kappa_inv
	else
		Branch to Branch to GY_Matrix[h-hshift][v-vshift]:=nonSynRate*delta*kappa_inv*kappa_inv

delta is the additional parameter that I added, which is defined in my batch file as "global delta =1", just as is done for kappa_inv. The matrix bounds look okay, i.e. are within the 61x61 bounds.

Any advice on why I am getting that error? Is hyphy flexible to carry out an analysis like this, using the batch file?

Thanks very much for any help,
Aarti

**Comment by spond** [comment]
Hi Aarti,

Looks like your batch file may not be including `chooseGeneticCode.def'. You need to do that so that the `_GeneticCode` variable is defined. Use 

```
LoadFunctionLibrary("chooseGeneticCode", {"0" : "Universal"});
```

at the top of the file to automatically load the definition for the *Universal* genetic code.

Sergei

**Comment by aatu18** [comment]
Hi Sergei,

_GeneticCode is defined (I included a file with the _GeneticCode specification at the top of the batch file), so that didn't fix it. My modified codon substitution model is assigning non-zero rates (using a new parameter) to codons with >1 substitutions. I am not sure if this has to be defined/implemented elsewhere, i.e other than the batch file? I could email you my batch file if that makes things clearer.

Thanks very much for any help. I would be looking into the REL models soon as well. 

Aarti

**Comment by spond** [comment]
Hi Aarti,

I will need to see your file, most likely. I would suggest you use gist.github.com to post the code so I can comment on it. 

Sergei

**Comment by aatu18** [comment]
I just posted the code on gist. 

Thanks very much for taking a look at this,
Aarti

**Comment by aatu18** [comment]
p.s. should have mentioned, its called "ModifiedYangNielsenBranchSite.bf"

**Comment by spond** [comment]
Hi Aarti,

Look at my branch of your gist: https://gist.github.com/spond/228989e3f19d6faf021a

The error you were seeing was because you typed `_GeneticCode` in place of `_Genetic_Code`. I've made a few other modifications.

Sergei

**Comment by aatu18** [comment]
Hi Sergei,

Ooops, I should have caught that, apologies for that! In reality, I am not sure how to properly debug the batch file in hbl (eg: variable undeclared type errors which warn me). If you have any suggestions for that it would be super helpful. Thanks a million for looking at this!

Aarti

**Comment by spond** [comment]
Hi Aarti,

Yeah, debugging could be tricky (because HyPhy is so permissive and sloppy in places). You can look at messages.log file for lines like 

```
Variable 'END_OF_FILE' was not initialized prior to being used
```

for instances of variables that are (by default) initialized to `0` when first used.

Sergei

**Comment by aatu18** [comment]
Great, thank you very much for all the help!
