### ISSUE TITLE
Python module fails to build on Yosemite

### ISSUE THREAD

**Issue by ArtPoon** [veg/hyphy#312]
Due to this line of `setup.py`:
```
openmp = ['-fopenmp'] if mac_ver()[0] < '10.7.0' else []
```

Yosemite version is `10.10`.  As a text string this is less than `10.7.0`:
```
>>> '10.10.1' < '10.7.0'
True
```

**Comment by stevenweaver** [comment]
Hello Art, 

I've put in place a patch for now. 

If you would like to compile with openmp on osx, you can use [homebrew](http://brew.sh/) to install gcc. 
`brew install gcc`

You can then set gcc-5 as your compiler like so:
`export CC=gcc-5;export CXX=g++-5;python setup.py install`

In the near future, we are going to move the python module to https://github.com/veg/hyphy-python, and remove this directory. 

Thanks,
Steven
