### ISSUE TITLE
how to carry out significant test when I using the slatkin and maddison test

### ISSUE THREAD

**Issue by qianhaoo** [veg/hyphy#314]
Hi, I am troubled in p value when using the slatkin and maddison test.
First, Hyphy Inferred 27 migration events in my tree, and then it showed the following request "How many permutations would you like to perform (total of 3.647695548555865e-032 unique permutations available)?", I input the "1000", finally the result showed "Prob{as many or fewer migration events by chance} = 0", I am not clear in its meaning, does it mean that it is of significance in the compartmentalization?

**Comment by spond** [comment]
Hi qianhaoo,

Yes, a low [p-value](https://en.wikipedia.org/wiki/P-value#Definition_and_interpretation) means a significant result, i.e. there is low probability that **27 or fewer** migration events would be inferred in your tree if the populations were mixed. Therefore the SM test reports evidence of compartmentalization. 

Sergei

**Comment by qianhaoo** [comment]
Dear Sergei,

Thanks for your timely reply.

However, there exists contradictory in my results, please see it in my
attachment.

Best

2015-07-27 11:51 GMT+08:00 Sergei Pond <notifications@github.com>:

**Comment by qianhaoo** [comment]
my problem is that the phylogeny did not show obvious visible compartmentalization, is that reasonable?

**Comment by spond** [comment]
Hi there,

There's no point in doing a formal test if the answer is obvious, is there? For example, if your phylogeny has 500 tips and 250 are from one "populations", and 250 are from the other, then you would expect a lot more than 27 migration events by chance. Remember that SM does not test for complete separation of clades, but rather for less mixing than expected under complete panmixia.

Sergei
