### ISSUE TITLE
Can't open files on HYPHY Mac GUI

### ISSUE THREAD

**Issue by TashyK** [veg/hyphy#315]
Hi

I am trying to run a MEME analysis on the HYPHY Mac GUI. I follow the instructions as in the tutorial and quickselection.bf and then try and open my fasta file. 

I keep getting the error: Could not find source dataset file:PROMPT_FOR_FILE Path stack.

I also tried other analyses and get the same error. I also deleted and reinstalled and it didn't help. My file names are relatively short. 

Could you assist?

Many thanks
Tasha

**Comment by stevenweaver** [comment]
Hello Tasha,

On OSX 10.10.4, I am able to select files, but with one caveat. 

You must select `All Documents` when prompted to select a codon data file.

<img width="688" alt="screen shot 2015-07-27 at 12 14 26" src="https://cloud.githubusercontent.com/assets/535261/8915313/18212ae6-3459-11e5-9ac0-320472c11470.png">

I'm unsure if this will solve your problem, but with your OSX version I may be of more help. 

Thanks,
Steven

**Comment by TashyK** [comment]
Hi Steven 

Thanks so much for getting back to me. 

I'm also on 10.10.4. I've just tried loading the file as you suggested. So... After I've changed the setting on the drop down box to "All Documents", I click on the appropriate fasta file (with the .fas extension). Nothing happens except it kind of goes back to default of "All Readable Documents". I change it back to "All Documents" and try to select the appropriate file again. I then get the "Could not find source dataset file:PROMPT_FOR_FILE Path stack".

This happens regardless of the type of analysis I try to do. I know the file is fine because it's a file I previously used to do  FUBAR analysis on the server - but it doesn't work on the GUI version on my laptop. 

I hope this is clear. Any help would be appreciated.

Thanks
Tasha

**Comment by spond** [comment]
Hi Tasha,

This is most likely because the GUI version uses very old programming interfaces, so if your path names are too long, or have non 0-9 A-Z  characters, you may encounter the error. Can you open the Terminal window, drag the sequence file you have been trying to use into it, and they paste the resulting path name here for us to look at (when you drag a file into a terminal window, OS X will paste the absolute path to the file into the terminal)?

Sergei

**Comment by TashyK** [comment]
Hi Sergei

I just shortened my file names and it seems to have loaded, and is running MEME_mf.bf.

Not sure that my laptop is powerful enough to run the analysis - but at 11% so lets see.

Thank you so much for the help!
Tasha
