### ISSUE TITLE
Running MEME on the sever

### ISSUE THREAD

**Issue by TashyK** [veg/hyphy#316]
Hi 

I have another question. I am trying to run MEME on the university server (for which a FUBAR analysis worked). I have the following script to direct the software what to do:

inputRedirect = {};
inputRedirect["01"]="/scratch/akoch/NEWDATA/ResequencingRun/MEME/test/input/E_FUBARComplementAlign_renameRC_final.fas";
inputRedirect["02"]="010010";
inputRedirect["03"]="General Discrete";
inputRedirect["04"]="3";
inputRedirect["05"]="/scratch/akoch/NEWDATA/ResequencingRun/MEME/test/output/E_FUBARComplementAlign_renameRC_final.fas_meme_out";
ExecuteAFile("/scratch/akoch/NEWDATA/ResequencingRun/MEME/test/bfiles/MEME_mf.bf",inputRedirect);

I've also asked the server administrator to update hyphyMPI to the current version to see if that would help. But I have a feeling there may be a problem with some of my parameters - it was amended for me from a similar GARD script. 

I'm very new to this so any advice would be greatly appreciated. 

Many thanks
Tasha

**Comment by stevenweaver** [comment]
Hello Tasha, 

The MEME analysis takes a separate set of parameters than the GARD script. 

If you are curious about which parameters to use, you can always run HYPHYMP on the batch file for the analysis directly with a command like the following: 
`HYPHYMP /scratch/akoch/NEWDATA/ResequencingRun/MEME/test/bfiles/MEME_mf.bf`

In this case, the parameters would look something like the following:
```
inputRedirect = {}; 
inputRedirect["01"]="Universal"; // Genetic Code
inputRedirect["02"]="New Analysis"; // New Analysis
inputRedirect["03"]="Default"; // Default Model Option
inputRedirect["04"]="2"; // Number of data files
inputRedirect["05"]="/scratch/akoch/NEWDATA/ResequencingRun/MEME/test/input/E_FUBARComplementAlign_renameRC_final.fas";
inputRedirect["06"]="Y"; // Use the tree found
inputRedirect["07"]="/scratch/akoch/NEWDATA/ResequencingRun/MEME/test/output/E_FUBARComplementAlign_renameRC_final.fas_meme_out";
inputRedirect["08"]=".05"; // significance level
ExecuteAFile("/scratch/akoch/NEWDATA/ResequencingRun/MEME/test/bfiles/MEME_mf.bf",inputRedirect);
```

inputRedirect["06"] assumes that you have a newick tree defined at the bottom of your fasta file. If this is not the case, then please supply the full path to the nwk file you would like to use instead of "Y".

Best,
Steven

**Comment by TashyK** [comment]
Hi Steven

Thanks again for this. As you can see I'm trying to get this running on the server and on the GUI. It's the last bit of analysis before a paper, so pushing to get it done soon. You can probably also tell that I'm very new to this :)

Thanks for the MEME parameters. A colleague gave me a modified GARD script while trying to assist.  I'll give it try on those parameters on the server today, and hopefully it'll help. 

Thanks
Tasha

**Comment by TashyK** [comment]
Hi Steven

I've made some progress running MEME on the server. I think a major step was getting an update done to hyphy-2.2.1, and then some modifications to my submission script and the parameters file. 

It seems to start to run but throws up an error of: 
Error:_codonMap= was expected to be a numerical argument

I'm guessing this has something to do with the parameters file. As a long shot I tried changing input 03 to the 012345 (the GTR combined with codon) as suggested on the tutorial page. But it doesn't resolve the problem.

inputRedirect = {};
inputRedirect["01"]="Universal"; // Genetic Code
inputRedirect["02"]="New Analysis"; // New Analysis
inputRedirect["03"]="012345"; // Default Model Option
inputRedirect["04"]="2"; // Number of data files
inputRedirect["05"]="/scratch/akoch/NEWDATA/ResequencingRun/MEME/test/input/E_FUBARComplementAlign_renameRC_final.fas";
inputRedirect["06"]="/scratch/akoch/NEWDATA/ResequencingRun/MEME/test/input/E_FUBARComplementAlign_renameRC_final.nwk"; // Use the tree found
inputRedirect["07"]="/scratch/akoch/NEWDATA/ResequencingRun/MEME/test/output/E_FUBARComplementAlign_renameRC_final.fas_meme_out";
inputRedirect["08"]=".05"; // significance level
ExecuteAFile("/opt/exp_soft/hyphy-mpi-2.2.1/lib/hyphy/TemplateBatchFiles/MEME_mf.bf",inputRedirect);

Let me know what you think and thanks in advance.
Tasha

**Comment by TashyK** [comment]
Hi

Can anyone help with the query above?

Thanks
Tasha

**Comment by stevenweaver** [comment]
Hi, 
Sorry for the delay. 
Please try the following:
```
inputRedirect = {};
inputRedirect["01"]="Universal"; // Genetic Code
inputRedirect["02"]="New Analysis"; // New Analysis
inputRedirect["03"]="Custom"; // Select Custom Model Option
inputRedirect["04"]="012345"; // Default Model Option
inputRedirect["05"]="2"; // Number of data files
inputRedirect["06"]="/scratch/akoch/NEWDATA/ResequencingRun/MEME/test/input/E_FUBARComplementAlign_renameRC_final.fas";
inputRedirect["07"]="/scratch/akoch/NEWDATA/ResequencingRun/MEME/test/input/E_FUBARComplementAlign_renameRC_final.nwk"; // Use the tree found
inputRedirect["08"]="/scratch/akoch/NEWDATA/ResequencingRun/MEME/test/output/E_FUBARComplementAlign_renameRC_final.fas_meme_out";
inputRedirect["09"]=".05"; // significance level
ExecuteAFile("/opt/exp_soft/hyphy-mpi-2.2.1/lib/hyphy/TemplateBatchFiles/MEME_mf.bf",inputRedirect);
```

Best,
Steven

**Comment by TashyK** [comment]
Hi Steven

No probs - thanks so much for getting back to me. 

I've just tried that but still the same error message. So in my errors.log.mpinode file I get the error: Error:_codonMap= was expected to be a numerical argument.

And then a more extensive error in the meme .out file (E_FUBARComplementAlign_renameRC_final.fas.out):

[1438244526.353257] [srvslshpc617:11460:0]         shm.c:65   MXM  WARN  Could not open the KNEM device file at /dev/knem : No such file or directory. Won't use knem.
[1438244526.354221] [srvslshpc617:11461:0]         shm.c:65   MXM  WARN  Could not open the KNEM device file at /dev/knem : No such file or directory. Won't use knem.
[1438244526.358856] [srvslshpc617:11462:0]         shm.c:65   MXM  WARN  Could not open the KNEM device file at /dev/knem : No such file or directory. Won't use knem.
[1438244526.362896] [srvslshpc617:11463:0]         shm.c:65   MXM  WARN  Could not open the KNEM device file at /dev/knem : No such file or directory. Won't use knem.
Error:

Master node received an error:_codonMap= was expected to be a numerical argument

Function call stack
1 : lfunction ComputeCodonCodeToStringMap(genCode){_codonMap {};_nucLetters="ACGT";for(_idx=0;_idx<Columns(genCode);_idx+=1){if(genCode[_idx]!=10){_codonMap+(_nucLetters[_idx$16]+_nucLetters[(_idx%16)$4]+_nucLetters[_idx%4]);}}return  _codonMap;}
        Standard input redirect:
                02 : New Analysis
                03 : Custom
                04 : 012345
                05 : 2
                06 : /scratch/akoch/NEWDATA/ResequencingRun/MEME/test/input/E_FUBARComplementAlign_renameRC_final.fas
                07 : /scratch/akoch/NEWDATA/ResequencingRun/MEME/test/input/E_FUBARComplementAlign_renameRC_final.nwk
                08 : /scratch/akoch/NEWDATA/ResequencingRun/MEME/test/output/E_FUBARComplementAlign_renameRC_final.fas_meme_out
                09 : .05
                -------

Do you think it's an issue with MEME  or the server environment?

I'll wait to hear back from you.

Thanks
Tasha

**Comment by stevenweaver** [comment]
Hello Tasha, 

I'm having quite a time trying to reproduce this error. 

One issue that I noticed from my previous comment is that the number of files should be `"1"` instead of `"2"`, but that would not result in the error you are receiving. 

This seems to be a system-specific issue. We currently test HyPhy compiled with `OpenMPI  1.8.3` on CentOS. In order to help further, I may need to know system information such as which flavor and version of linux you are using, and which mpi implementation you are compiling with. 

Have you tried using the HYPHYMP version? Is it possible to run `HYPHYMP /scratch/akoch/NEWDATA/ResequencingRun/MEME/test/bfiles/MEME_mf.bf` directly to see if the issue disappears?

Apologies for the issue,
Steven

**Comment by spond** [comment]
Hi Tasha,

It may be that your HYPHYMPI binary has been compiled from an old version of the source code. I can't readily tell you what is generating the error that you see because I have not seen it before. Do you see the same error if you try running `MEME.bf`?

Sergei

**Comment by TashyK** [comment]
Hi Steven and Sergei

I've contacted the technical specialist for the server to advise. To be very honest, I don't know which flavour of linux we're running, nor which MPI implementation we're compiling with. And I've been told NEVER to run things directly on the head node, so don't think I should try :).

I will let you know what he says. 

Thanks for all the help.
Tasha

**Comment by TashyK** [comment]
Hi Steven and Sergei

Together with the technical specialist for the server, we managed to get the script running. We're actually running it on a server that hasn't been completely implemented yet. But it's running  Centos 6.6 and Open MPI 1.8.5. The analysis has been running since this morning, but I'm a little concerned about the output. 

The end of the .out file looks like:
nucTree_1.Node334.t=0.002381630869125829;
nucTree_1.Node310.t=0.002258848351286432;
nucTree_1.Node140.t=0.005802121642299418;
DataSet ds_1 = ReadDataFile(USE_NEXUS_FILE_DATA);
DataSetFilter nucData_1 = CreateFilter(ds_1,1,"0-36497","181,166,182,180,167,177,174,189,0,179,168,171,172,37,27,12,28,43,6,8,44,25,13,10,21,5,40,26,38,34,17,32,3,24,14,1,22,16,36,41,33,20,2,30,42,45,39,15,31,23,4,35,9,175,176,178,187,7,184,11,29,18,19,173,170,48,188,47,46,183,131,118,82,114,56,104,109,90,110,51,169,149,158,147,53,84,59,160,102,153,162,107,186,85,78,135,75,81,146,86,96,52,62,134,127,97,124,98,49,61,154,74,71,91,95,80,150,94,143,72,137,139,117,126,144,112,164,65,142,159,119,57,115,148,157,145,136,123,165,132,130,152,163,88,76,155,141,133,50,108,128,79,161,64,185,121,100,101,54,93,103,69,87,70,122,89,68,77,92,111,67,99,138,73,83,129,63,116,120,66,156,105,113,151,60,58,106,140,125,55");
ASSUME_REVERSIBLE_MODELS=0;
LikelihoodFunction nucLF = (nucData_1,nucTree_1);

END;

And hasn't changed since a few hours ago. There are no other output files. There is also messages.log.mpinode0 file that keeps updating but it seems that the following lines keep getting added:

Serializing siteLikelihood with mode 1
Row and/or column partition is empty. All the data will be used by default.

The script that was run looks like:
inputRedirect = {};
inputRedirect["01"]="Universal"; // Genetic Code
inputRedirect["02"]="New Analysis"; // New Analysis
inputRedirect["03"]="Custom"; // Select Custom Model Option
inputRedirect["04"]="012345"; // Default Model Option
inputRedirect["05"]="1"; // Number of data files
inputRedirect["06"]="/home/akoch/MEME/test/input/E_FUBARComplementAlign_renameRC_final.fas";
inputRedirect["07"]="/home/akoch/MEME/test/input/E_FUBARComplementAlign_renameRC_final.nwk"; // Use the tree found
inputRedirect["08"]="/home/akoch/MEME/test/output/E_FUBARComplementAlign_renameRC_final.fas_meme_out";
inputRedirect["09"]=".05"; // significance level
ExecuteAFile("/home/exp_soft/hyphi-mpi/lib/hyphy/TemplateBatchFiles/MEME_mf.bf",inputRedirect);

Let me know what you think.

Thanks so much.
Anastasia

**Comment by TashyK** [comment]
Hi 

Does anyone have any advice on this?

Thanks so much.
Tasha

**Comment by spond** [comment]
Hi Tasha,

Is the analysis still stuck?

Sergei

**Comment by TashyK** [comment]
Hi Sergei

It was stuck for two days, so I killed the job as I didn't want to use up unnecessary resources on the server. 

Is it just a case of waiting for the analysis to run? It seemed a bit weird that the same lines kept getting added to the node log file...

I would so appreciate your advice - this is the last bit of analysis for a paper!

Thanks so much.
Tasha

**Comment by spond** [comment]
Hi Tasha,

Can you send me your alignment / trees? I'll try to debug on our local cluster. Of course I will keep your data confidential and will delete them when the problem has been resolved.

Sergei

**Comment by TashyK** [comment]
Hi Sergei

I would greatly appreciate that. Thank you so much.

I just tried to send the files via attachment but they are too large.

See below for a dropbox link to the codon alignment in fasta format, and
the tree in newick format.

https://www.dropbox.com/s/5amz3nq6bcilsek/E_FUBARComplementAlign_renameRC_final.fas?dl=0
https://www.dropbox.com/s/tf4kmcp11b2iwnr/E_FUBARComplementAlign_renameRC_final.nwk?dl=0

Many thanks
Tasha

**Comment by TashyK** [comment]
Hi Sergei

I was wondering if you had a chance to look at this?

Many thanks
Tasha

**Comment by spond** [comment]
Hi Tasha,

Just back from a workshop; the analysis is running.

Sergei

**Comment by TashyK** [comment]
That is amazing!

Thanks so much Sergei...

When you have a chance, I would love to know what I was doing wrong.

Best,
Tasha

**Comment by spond** [comment]
Hi Tasha,

The CSV of MEME results is available from https://www.dropbox.com/s/8n1fh0zu01qhoyh/E_FUBARC.meme.csv

Sergei

**Comment by TashyK** [comment]
Hi Sergei

That is amazing! Thank you so much.

I need to run another file as those were codons in the complimentary
strand. Any idea of why it wasn't working on this side?

Best,
Tasha
