### ISSUE TITLE
unrooted tree for aBSREL

### ISSUE THREAD

**Issue by antony03** [veg/hyphy#317]
Hi,

I performed an aBSREL analysis with hyphy on some alignments using an unrooted tree. Is this correct to use an unrooted tree? Are the results can vary depending of the root for this analysis? The problem here is that I cannot introduce a correct outgroup to properly root the tree since some genes are exclusively found for the specific taxa that I already used.

Thank you!

**Comment by spond** [comment]
Hi Antony,

The models used by aBSREL are time reversible, so all the rootings of the tree are equivalent. Internally, the analysis un-roots rooted trees, so you are good to go. 

Sergei
