### ISSUE TITLE
upload tree file for RELAX and more

### ISSUE THREAD

**Issue by xzhuo** [veg/hyphy#323]
Hi there,

I am trying to apply RELAX in my paper, but I have 3 questions: 

a) Is it possible to upload a tree file and use it for RELAX, instead of using the tree generated by the datamonkey server?

b) I couldn't use RELAX analysis in HyPhy mac version. I did find RELAX.bf in folder "TempleBatchFiles", however, I could not find the method in the "Standard Analysis" list. 

c) The new application of RELAX using multiple files proposed in issue #275 seems interesting, and when would it be implemented in datamonkey/HyPhy ?

Thank you very much!

-Xiaoyu

**Comment by stevenweaver** [comment]
Hello Xiaoyu, 

a) Yes, it is possible to include a custom tree. If you append your Newick tree to the bottom of your FASTA file, datamonkey will detect the tree automatically. On the branch selection page, you will be presented with an option to use the user supplied tree or the neighbor-joining tree. 
<img width="1273" alt="screen shot 2015-08-26 at 14 53 31" src="https://cloud.githubusercontent.com/assets/535261/9507371/9b533894-4c02-11e5-98cb-11718f490422.png">

b) RELAX.bf has yet to be included in the "Standard Analysis" list. I will keep this ticket open until it is included. In the meantime, you can execute the batch file directly by selecting `File->Open->Open Batch File` and navigating to `RELAX.bf` on your file system. If it is easier, you can save the file directly by navigating to this [page](https://raw.githubusercontent.com/veg/hyphy/master/res/TemplateBatchFiles/RELAX.bf)

c) @spond may be able to help with this inquiry. 

Thanks,
Steven

**Comment by xzhuo** [comment]
Wow, thanks for your quick reply, that is very helpful!

**Comment by spond** [comment]
Hi Xiaoyu,

Regarding (c): I never got around to it. Too much to do, too little time:( Are you interested in using it?

Sergei

**Comment by xzhuo** [comment]
Hmmm, seems I can get around it by merging and manipulating alignment like this:
>t1
---------attagccat
>t2
---------attagccgt
>s1
atcagccat---------
>s2
attagccat---------


Havn't try real data yet, but seems RELAX is working...

Is it possible to use alignment like this? Could there be any problem?

**Comment by spond** [comment]
Hi Xiaoyu,

This approach will work if

1). You have the same tree topology for all the files
2). You don't expect there to be much substitution process heterogeneity from file to file (e.g. it is not likely that branch X is long in file 1, but short in file 2).

Sergei

**Comment by xzhuo** [comment]
I see. Would you mind to exlain a little bit why?

**Comment by spond** [comment]
Hi @xzhuo,

You need (1) so that the definition of "test" versus "reference" branches doesn't change from tree to tree (otherwise you simple can't define them). You need (2) because if one gene is say, very conserved, and another is highly variable, then forcing the same distribution of &omega; values on both genes would result in a poor fit to one or both. When the model doesn't fit the data well, the performance of the test will suffer.

Sergei

**Comment by xzhuo** [comment]
Thanks, it makes sense now.




-Xiaoyu


—

**Comment by gclongo** [comment]
Hi everybody, 

I'm having an issue with an appended tree and this seemed like the appropriate discussion. I have tree with branch lengths included on my nexus file. When I open the file in figtree, the tree looks great. However I load the tree in HyPhy or run it on data monkey it comes as a polytomy, unless I select the unscaled option in HyPhy.  Any idea why this would be? I've attached the nexus file in question.

Cheers,
Gary
[ND3_tree_1.txt](https://github.com/veg/hyphy/files/41959/ND3_tree_1.txt)

**Comment by spond** [comment]
Hi @gclongo,

Datamonkey will fit branch length to the sequences you supply (it will ignore the lengths already there). If your sequences are (nearly) identical, you will get polytomies. Can you provide a link to the Datamonkey job where this behavior is observed?

Sergei

**Comment by gclongo** [comment]
Hi Sergei,

Here's the link:
http://www.datamonkey.org/cgi-bin/datamonkey/jobStatus.pl?file=upload.536683653729469.1

Cheers,
Gary

**Comment by spond** [comment]
Hi @gclongo,

You see this behavior, because HyPhy (and Datamonkey) will nearly always convert rooted trees into unrooted trees. This is because most of the models used by the program are time-reversible, meaning that you can move the root anywhere you'd like (including an existing tree node, i.e. "unrooting") without changing the likelihood of the model and any of the downstream results.

Sergei

**Comment by gclongo** [comment]
Hi Sergei,

Thats what I was most worried about (affecting the analyses). One more question. When I submit a nexus file with a tree with no branch lengths, datamonkey and HyPhy do not convert it into an unrooted tree. I'm not sure which tree is best to use for Branch Site REL, the tree with branch lengths that is converted into an unrooted tree or the tree with no branch lengths that remains rooted. I've attached the file with no branch lengths and included the link to the datamonkey window.
http://www.datamonkey.org/cgi-bin/datamonkey/jobStatus.pl?file=upload.6584595331618.1

Thanks so much for your time and input, I really appreciate it!

Cheers,
Gary

[ND3_tree.txt](https://github.com/veg/hyphy/files/42086/ND3_tree.txt)

**Comment by gclongo** [comment]
Hi @spond ,

Just to follow up, I'm wondering why HyPhy did not convert my user supplied tree without branch lengths while it did indeed convert my tree with branch lengths. From what you say it sounds like it shouldn't matter with time-reversible models.

Cheers,
Gary

**Comment by spond** [comment]
Hi @gclongo,

Shouldn't matter with time reversible models. I think the difference is **what stage** the unrooting occurs (I'll check): during upload or right before the analysis.

Sergei

**Comment by gclongo** [comment]
Hi @spond,

Were you able to check?

Cheers,
Gary
