### ISSUE TITLE
CPUs to use in MAC pro tower 12 core

### ISSUE THREAD

**Issue by mlosada323** [veg/hyphy#324]
Hi,

I'm new to HyPhy. I have a MAC pro tower 12 core with OS X Yosemite 10.10 instal. I downloaded the GUI version of HyPhy for MacOS and runs fine except the programs requiring a MPI environment. In the HyPhy preferences I set up 12 processors to load but that made no difference, still get the error: This analysis requires an MPI environment to run. 

How do I make HyPhy MacOS to run in my computer using multiple processors?

Thanks for your advice and help

Marcos

**Comment by spond** [comment]
Hi Marcos,

The CPU setting you refer to affects MP (Multiprocessing) features of HYPHY, not MPI (distributed computing). If you want to run MPI analyses on Mac OS X, you should do the following

1. Install `open-mpi` (e.g. using [Homebrew](http://brew.sh))
2. Compile a command line version of HyPhy (see the [README](https://github.com/veg/hyphy/blob/master/README.md) file)
3. Start HYPHYMPI in the MPI environment, e.g. using

```
$mpirun -np 12 HYPHYMPI 
```

Sergei

**Comment by ArtPoon** [comment]
Hi Marcos,

I happen to be attempting a compile of HYPHYMPI on my Mac Pro right now, so I'll try working along with you (unless you've already managed to compile).  I happen to be using [MacPorts](https://www.macports.org/) instead of Homebrew, so I already had OpenMPI installed on my system with the following ports:
```
  openmpi-default @1.7.5_3+gcc48 (active)
  openmpi-devel @1.9a1_32808 (active)
```
There may be some versioning issues here that I'll have to keep a lookout for, since we'll be needing both the developer libraries and the executables (such as the `mpirun` script).

On running `cmake .`, I get the following warning messages:
```
-- Could NOT find MPI_C (missing:  MPI_C_LIBRARIES MPI_C_INCLUDE_PATH) 
-- Could NOT find MPI_CXX (missing:  MPI_CXX_LIBRARIES MPI_CXX_INCLUDE_PATH)
```
So evidently the OpenMPI libraries are not in my path, or at least not where the CMake script can find them.

I'll tinker with this and report back.
Cheers,
- Art.

**Comment by spond** [comment]
Hi Art and Marcos,

FWIW, the openmpi install with home-brew and gcc-5 works on my box (gcc-4.x will work too). This could be a CLANG vs GCC issue on OS X as well. Try 

```
CC=/path/to/gcc; CXX=/path/to/g++; cmake ./
```

from the HyPhy source directory. Note that GCC/C++ will need to be installed separately (e.g. using homebrew as well).

Sergei

**Comment by ArtPoon** [comment]
Ok, so it turns out that MacPorts installs `mpicc` and `mpicxx` at `/opt/local/bin` as `mpicc-openmpi-mp` and `mpicxx-openmpi-mp`, respectively.  These are in turn soft links to binary files in `/opt/local/libexec/openmpi-mp/`.  So it didn't matter that `/opt/local/bin` was in my `PATH` because `cmake` was looking for the executables `mpicc` and `mpicxx`.  My solution was simply to make soft links with these file names and point them to the respective links installed by MacPorts.  After doing that I just ran `cmake .` and `make MPI` and I'm off to the races!

**Comment by mlosada323** [comment]
thanks guys!! I'll give it a try

Marcos

**Comment by MiguelArenas** [comment]
Hi there,

I got the same problems than Marcos for running GARD.
First, I got problems for installing the command line version of Hyphy with MPI on my Mac (Intel Pro i7, OS X Yosemite 10.10.5), I tried Homebrew and MacPorts, but finally the configuration with cmake did not work.
So then I tried it on the cluster and there it runs but with problems. After the specification of the "homogeneous rates across sites (fastest)" I got the following error:

			+----------------------+
			|Rate variation options|
			+----------------------+


	(1):[None] Homogeneous rates across sites (fastest)
	(2):[General Discrete] General discrete distribution on N-bins
	(3):[Beta-Gamma] Adaptively discretized gamma N-bins. Try is GDD doesn't converge well, or if you suspect a lot of rate classes and do not want to overparameterize the model

1
 Please choose an option (or press q to cancel selection):
1
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD 
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
/share/apps/hyphy/2.2.4/lib/hyphy/TemplateBatchFiles/Save results to::Error:

Master node received an error:Could not create/open output file at path '/share/apps/hyphy/2.2.4/lib/hyphy/TemplateBatchFiles/1'. in call to fprintf(

Function call stack
1 : fprintf(PROMPT_FOR_FILE,CLEAR_FILE,KEEP_OPEN)
-------
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

[compute-1-32.local:06547] 3 more processes have sent help message help-mpi-api.txt / mpi-abort
[compute-1-32.local:06547] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[miguel@compute-1-32 HYPHY_NEW_prueba]$

Here I do not know if the problem is with Hyphy or with the MPI system of the cluster, or with my specifications..

Apart of that, I think it could be great to be able to run GARD (and any other method) with and without MPI to avoid these problems for non-experts.

Many thanks for helping!
Best,

Miguel

**Comment by spond** [comment]
Hi Miguel,

I'll ask Steven to come up with a how-to for a clean install of OpenMPI on OS X (10.9 and later). Maybe you are right, and I should modify GARD to run without MPI, despite the fact that it will be achingly slow:)

Sergei

**Comment by MiguelArenas** [comment]
Dear Sergei,

I agree, I think providing more details about OpenMPI and cmake can be useful for many users.

In the past I remember to successfully run GARD in another cluster (on a slurm OS) by running a daemon script that we made, but in our new cluster it seems more problematic.

My impression is that the best strategy in hyphy (thinking about users) is to consider both options, with and without MPI. Thus any user can run a small dataset without the need of installing OpenMPI. For a big dataset, non-experts at least will have the chance to run it and wait (better than nothing), and experts can just run it on OpenMPI..

From my side I am going to explore with the computer technician if the problem could be derived from our OS and how we could solve it.. 

All the best,

Miguel

**Comment by stevenweaver** [comment]
Dear Miguel,

I will try updating the README to be a bit more clear on how to install HYPHYMPI from source, but in the meantime can you please try

```
brew tap homebrew/science
brew install hyphy --with-mpi
```

and then submit the command 
`HYPHYMPI`

Regards,
Steven

**Comment by MiguelArenas** [comment]
Dear Sergei,

brew lines succesfully work. 

However then HYPHYMPI does not run,

MacBook-Pro-de-Miguel:hyphy-2.2.4 Miguel$ ls
CMakeLists.txt	CMakeWin32	Examples	README.md	cmake		contrib		help		installers	package.json	res		scripts		src		tests

MacBook-Pro-de-Miguel:hyphy-2.2.4 Miguel$ HYPHYMPI
-bash: HYPHYMPI: command not found

Should I specify a path? or maybe configure HYPHYMPI?

So I tried cmake and I got:

MacBook-Pro-de-Miguel:hyphy-2.2.4 Miguel$ cmake ./
-- The C compiler identification is AppleClang 6.1.0.6020053
-- The CXX compiler identification is AppleClang 6.1.0.6020053
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
-- Found CURL: /usr/lib/libcurl.dylib (found version "7.37.1") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found OpenCL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenCL.framework  
-- Could NOT find MPI_C (missing:  MPI_C_LIBRARIES MPI_C_INCLUDE_PATH) 
-- Could NOT find MPI_CXX (missing:  MPI_CXX_LIBRARIES MPI_CXX_INCLUDE_PATH) 
-- Configuring done
WARNING: Target "hyphy_mp" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "HYPHYMP" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "HYPHYOCL" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
-- Generating done
-- Build files have been written to: /Users/Miguel/Documents/ESCRITORIO_ACTUAL/Programas_Filogenias/HYPHY_all/hyphy-2.2.4

MacBook-Pro-de-Miguel:hyphy-2.2.4 Miguel$ ls
CMakeCache.txt		CMakeWin32		README.md		cmake_uninstall.cmake	installers		scripts
CMakeFiles		Examples		cmake			contrib			package.json		src
CMakeLists.txt		Makefile		cmake_install.cmake	help			res			tests
MacBook-Pro-de-Miguel:hyphy-2.2.4 Miguel$

Best,

Miguel

**Comment by stevenweaver** [comment]
Hello Miguel,

Sincerest apologies. There was an inappropriate dependency declaration in the hyphy homebrew formula which resulted in open-mpi not being installed on your system.

I have made a pull request to the homebrew team, but in the meantime, can you please submit the following commands

```
brew tap homebrew/science
brew install open-mpi
brew install hyphy --with-mpi
```

Once open-mpi is installed with homebrew, you should be able to compile HyPhy the traditional way with cmake as well. 

As far as the issue goes for your cluster, I will attempt writing a section in our README section that details the OpenMPI installation a bit more. 

Regards,
Steven

**Comment by MiguelArenas** [comment]
Hi there,
I followed the commands and everything seems to go right, but at the end GARD did not detect the installed MPI environment. See below..

MacBook-Pro-de-Miguel:hyphy-2.2.4 Miguel$ brew tap homebrew/science
Warning: Already tapped!
MacBook-Pro-de-Miguel:hyphy-2.2.4 Miguel$ brew install open-mpi
==> Installing dependencies for open-mpi: gmp, mpfr, libmpc, isl, gcc, libevent
==> Installing open-mpi dependency: gmp
==> Downloading https://homebrew.bintray.com/bottles/gmp-6.0.0a.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring gmp-6.0.0a.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/gmp/6.0.0a: 15 files, 3,2M
==> Installing open-mpi dependency: mpfr
==> Downloading https://homebrew.bintray.com/bottles/mpfr-3.1.3.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring mpfr-3.1.3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/mpfr/3.1.3: 24 files, 3,6M
==> Installing open-mpi dependency: libmpc
==> Downloading https://homebrew.bintray.com/bottles/libmpc-1.0.3.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring libmpc-1.0.3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libmpc/1.0.3: 10 files, 380K
==> Installing open-mpi dependency: isl
==> Downloading https://homebrew.bintray.com/bottles/isl-0.14.1.yosemite.bottle.3.tar.gz
######################################################################## 100,0%
==> Pouring isl-0.14.1.yosemite.bottle.3.tar.gz
🍺  /usr/local/Cellar/isl/0.14.1: 68 files, 3,2M
==> Installing open-mpi dependency: gcc
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.2.0/gcc-5.2.0.tar.bz2
==> Downloading from http://mirrors.fe.up.pt/pub/gnu/gcc/gcc-5.2.0/gcc-5.2.0.tar.bz2
######################################################################## 100,0%
==> Patching
patching file gcc/jit/Make-lang.in
patching file gcc/jit/jit-playback.c
Hunk #1 succeeded at 2459 with fuzz 2 (offset 43 lines).
==> ../configure --build=x86_64-apple-darwin14.5.0 --prefix=/usr/local/Cellar/gcc/5.2.0 --libdir=/usr/local/Cellar/gcc/5.2.0/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++,fortran --program-s
==> make bootstrap
==> make install
==> Caveats
GCC has been built with multilib support. Notably, OpenMP may not work:
  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
If you need OpenMP support you may want to
  brew reinstall gcc --without-multilib
==> Summary
🍺  /usr/local/Cellar/gcc/5.2.0: 1353 files, 248M, built in 32.0 minutes
==> Installing open-mpi dependency: libevent
==> Downloading https://homebrew.bintray.com/bottles/libevent-2.0.22.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring libevent-2.0.22.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libevent/2.0.22: 48 files, 1,8M
==> Installing open-mpi
==> Downloading https://homebrew.bintray.com/bottles/open-mpi-1.10.0.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring open-mpi-1.10.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/open-mpi/1.10.0: 785 files, 22M
MacBook-Pro-de-Miguel:hyphy-2.2.4 Miguel$ brew install hyphy --with-mpi
==> Installing hyphy from homebrew/homebrew-science
==> Downloading https://github.com/veg/hyphy/archive/2.2.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/hyphy-2.2.4.tar.gz
==> Patching
patching file CMakeLists.txt
Hunk #1 succeeded at 310 (offset 11 lines).
Hunk #2 succeeded at 510 with fuzz 1 (offset -53 lines).
Hunk #3 succeeded at 521 (offset -53 lines).
Hunk #4 succeeded at 531 (offset -53 lines).
==> cmake -DINSTALL_PREFIX=/usr/local/Cellar/hyphy/2.2.4 . -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/hyphy/2.2.4 -DCMAKE_BUILD_TYPE=Release -
==> make SP
==> make MP2
==> make MPI
==> make GTEST
==> make install
==> Caveats
The help has been installed to /usr/local/share/hyphy.
==> Summary
🍺  /usr/local/Cellar/hyphy/2.2.4: 564 files, 124M, built in 59 seconds
MacBook-Pro-de-Miguel:hyphy-2.2.4 Miguel$ HYPHYMPI


      /HYPHY 2.220150907beta(MPI) for Darwin on x86_64\      
***************** TYPES OF STANDARD ANALYSES *****************


	(1) Basic Analyses
	(2) Codon Selection Analyses
	(3) Compartmentalization
	(4) Data File Tools
	(5) Miscellaneous
	(6) Model Comparison
	(7) Kernel Analysis Tools
	(8) Molecular Clock
	(9) Phylogeny Reconstruction
	(10) Positive Selection
	(11) Recombination
	(12) Selection/Recombination
	(13) Relative Rate
	(14) Relative Ratio
	(15) Substitution Rates

 Please select type of analyses you want to list (or press ENTER to process custom batch file):11

 ***************** FILES IN 'Recombination' ***************** 


	(1) Screen an alignment using GARD (requires an MPI environment).
	(2) Process GARD results.
	(3) A Likelihood Ratio Test to detect conflicting phylogenetic signal Huelsenbeck and Bull, 1996. [Contributed by Olivier Fedrigo].
	(4) Search an alignment for a single breakpoint.
	(5) Plot genetic distances (similarity) of one sequence against all others in an alignment, using a sliding window. Optionally, determine NJ-based clustering and bootstrap support in every window. This is a HyPhy adaptation of the excellent (but Windows only tool) SimPlot (and/or VarPlot) written by Stuart Ray (http://sray.med.som.jhmi.edu/SCRoftware/simplot/)

 Please select the file you want to use (or press ENTER to return to the list of analysis types):1
[ERROR] This analysis requires an MPI environment to run

MacBook-Pro-de-Miguel:hyphy-2.2.4 Miguel$

If now I try cmake:

MacBook-Pro-de-Miguel:hyphy-2.2.4 Miguel$ ls
CMakeCache.txt		CMakeWin32		README.md		cmake_uninstall.cmake	installers		res			tests
CMakeFiles		Examples		cmake			contrib			messages.log.mpinode0	scripts
CMakeLists.txt		Makefile		cmake_install.cmake	help			package.json		src
MacBook-Pro-de-Miguel:hyphy-2.2.4 Miguel$ cmake ./
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
-- Found MPI_C: /usr/local/Cellar/open-mpi/1.10.0/lib/libmpi.dylib  
-- Found MPI_CXX: /usr/local/Cellar/open-mpi/1.10.0/lib/libmpi_cxx.dylib;/usr/local/Cellar/open-mpi/1.10.0/lib/libmpi.dylib  
-- Configuring done
WARNING: Target "hyphy_mp" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "HYPHYMP" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "HYPHYOCL" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "HYPHYMPI" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
-- Generating done
-- Build files have been written to: /Users/Miguel/Documents/ESCRITORIO_ACTUAL/Programas_Filogenias/HYPHY_all/hyphy-2.2.4
MacBook-Pro-de-Miguel:hyphy-2.2.4 Miguel$ 

Thanks for trying to solve this!

Best,

Miguel

**Comment by spond** [comment]
Hi Miguel,

You need to use *mpirun* to launch Hyphy, or any other program, in an MPI environment. Something like mpirun -np 8 HYPHYMPI. 

Sergei

**Comment by MiguelArenas** [comment]
Hi Sergei,

You are right, I did not realize..
Now GARD runs correctly on my Mac.
Everyone thank you very much for helping!

Best,
Miguel

**Comment by MiguelArenas** [comment]
Hi Sergei,

Just a point about GARD, probably something that I do not realize right now. 
After running GARD on my computer I did not get output files with the results (i.e., number of detected recombination breakpoints, .nex aln file with the partitions and tree per partition..). How can obtain that? I did not find options to specify the desired outputs during the input..
Many thanks!
Miguel

**Comment by spond** [comment]
Hi Miguel,

You need to run a post-processing step, like described starting on page 7 of http://www.hyphy.org/pubs/Methods2011.pdf

Sergei

**Comment by MiguelArenas** [comment]
Hi Sergei,

I just noted that sometimes an input is asked to the user before printing the corresponding question (see below, pasted from the terminal), so before I introduced an incorrect answer to the output file point. Considering this it works and I get the outputs :-)

Many thanks!

Miguel

MBP-de-Miguel:GARD_prueba Miguel$ mpirun -np 8 HYPHYMPI
     /HYPHY 2.220150907beta(MPI) for Darwin on x86_64\      
***************** TYPES OF STANDARD ANALYSES *****************


	(1) Basic Analyses
	(2) Codon Selection Analyses
	(3) Compartmentalization
	(4) Data File Tools
	(5) Miscellaneous
	(6) Model Comparison
	(7) Kernel Analysis Tools
	(8) Molecular Clock
	(9) Phylogeny Reconstruction
	(10) Positive Selection
	(11) Recombination
	(12) Selection/Recombination
	(13) Relative Rate
	(14) Relative Ratio
	(15) Substitution Rates

11
 Please select type of analyses you want to list (or press ENTER to process custom batch file):

***************** FILES IN 'Recombination' ***************** 


	(1) Screen an alignment using GARD (requires an MPI environment).
	(2) Process GARD results.
	(3) A Likelihood Ratio Test to detect conflicting phylogenetic signal Huelsenbeck and Bull, 1996. [Contributed by Olivier Fedrigo].
	(4) Search an alignment for a single breakpoint.
	(5) Plot genetic distances (similarity) of one sequence against all others in an alignment, using a sliding window. Optionally, determine NJ-based clustering and bootstrap support in every window. This is a HyPhy adaptation of the excellent (but Windows only tool) SimPlot (and/or VarPlot) written by Stuart Ray (http://sray.med.som.jhmi.edu/SCRoftware/simplot/)

1
 Please select the file you want to use (or press ENTER to return to the list of analysis types):Initialized GARD on 8 MPI nodes.
Population size is 14 models

/Users/Miguel/Documents/ESCRITORIO_ACTUAL/Programas_Filogenias/HYPHY_all/hyphy-2.2.4/GARD_prueba/Aln.fas
/usr/local/Cellar/hyphy/2.2.4/lib/hyphy/TemplateBatchFiles/Nucleotide file to screen::
/Users/Miguel/Documents/ESCRITORIO_ACTUAL/Programas_Filogenias/HYPHY_all/hyphy-2.2.4/GARD_prueba/Aln.fas
Please enter a 6 character model designation (e.g:010010 defines HKY85):
010010
Please enter a 6 character model designation (e.g:010010 defines HKY85):

			+----------------------+
			|Rate variation options|
			+----------------------+


	(1):[None] Homogeneous rates across sites (fastest)
	(2):[General Discrete] General discrete distribution on N-bins
	(3):[Beta-Gamma] Adaptively discretized gamma N-bins. Try is GDD doesn't converge well, or if you suspect a lot of rate classes and do not want to overparameterize the model

1
 Please choose an option (or press q to cancel selection):
/Users/Miguel/Documents/ESCRITORIO_ACTUAL/Programas_Filogenias/HYPHY_all/hyphy-2.2.4/GARD_prueba/OutputFile.txt
/usr/local/Cellar/hyphy/2.2.4/lib/hyphy/TemplateBatchFiles/Save results to::There are 5339 potential breakpoints. Bit size of the sample is 13.

Fitting a baseline nucleotide model...
Done with single partition analysis. Log(L) = -14039.6651267081, c-AIC  = 28145.68469979109
Starting the GA...

GENERATION 2 with 1 breakpoints (~0% converged)
Breakpoints    c-AIC  Delta c-AIC [BP      1]
          0 28145.68
          1 27672.79      472.895       2335 
GA has considered        9/        5339 (9 over all runs) unique models
Total run time           0 hrs 0 mins 1 seconds
Throughput                9.00 models/second
Allocated time remaining 999 hrs 59 mins 59 seconds (approx. 32399991 more models.)
.. MANY GENERATIONS ...

MBP-de-Miguel:GARD_prueba Miguel$ ls
Aln.fas				OutputFile.txt			OutputFile.txt_ga_details	messages.log.mpinode0
OutputFile.txt_finalout		OutputFile.txt_splits
