### ISSUE TITLE
How to change species and site-specific codon to missing data

### ISSUE THREAD

**Issue by fayjustin** [veg/hyphy#325]
I need to make a specific codon in a dataset missing data, e.g. NNN. Because the specific codon of interest will change in my batch file, I'd rather manipulate my ReadDataFile object than separately scripting many different input files.

**Comment by spond** [comment]
Hi Justin,

Hyphy does not have convenient features for editing individual level codons in loaded data files (they are assumed to be immutable). An easy but very kludgy hack is to 

1. Read the data file
2. Process individual sequence as strings and do search and replace of individual codes; regular expressions don't work particularly well for matching strings on multiple of three boundaries, so the search and replace is done by brute force.
3. The munged strings are then pushed into a FASTA formatted buffer and read back into a different data object.

The code snippet doing this is [here](https://github.com/spond/hyphy-support/blob/master/code_examples/issue325.bf)

Sergei

**Comment by fayjustin** [comment]
Thanks Sergei,

I've now run into an error when generating a likelihood function:
The dimension of the equilibrium frequencies vector vectorOfFrequencies
(61) doesn't match the number of states in the dataset filter (7997)
codonsMaskedF
Call stack
1 : Construct the following likelihood function:codonsMaskedF ; mtree ;

The error only intermittently occurs, most of the time there is no error.
The output of the FASTA formatted buffer looks correct when there is an
error. However, if I masked all codons to NNN, I get the error every time.
If I set all codons to something arbitrary (GGA), there is no error. If I
use unmasked filter there is no error.

Justin

On Tue, Sep 1, 2015 at 1:17 PM, Sergei Pond <notifications@github.com>
wrote:

> Hi Justin,
>
> Hyphy does not have convenient features for editing individual level
> codons in loaded data files (they are assumed to be immutable). An easy but
> very kludgy hack is to
>
>    1. Read the data file
>    2. Process individual sequence as strings and do search and replace of
>    individual codes; regular expressions don't work particularly well for
>    matching strings on multiple of three boundaries, so the search and replace
>    is done by brute force.
>    3. The munged strings are then pushed into a FASTA formatted buffer
>    and read back into a different data object.
>
> The code snippet doing this is here
> <https://github.com/spond/hyphy-support/blob/master/code_examples/issue325.bf>
>
> Sergei
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/veg/hyphy/issues/325#issuecomment-136816659>.
>



-- 
__________________________________________
Justin Fay
Associate Professor of Genetics
Washington University School of Medicine
Rm 5526, Center for Genome Sciences
4444 Forest Park Pkwy, St. Louis, MO 63108
Ph: 314.747.1808 Fax: 314.362.7855

**Comment by fayjustin** [comment]
Using ??? rather than NNN resolved the issue.

On Tue, Sep 1, 2015 at 1:17 PM, Sergei Pond <notifications@github.com>
wrote:

> Hi Justin,
>
> Hyphy does not have convenient features for editing individual level
> codons in loaded data files (they are assumed to be immutable). An easy but
> very kludgy hack is to
>
>    1. Read the data file
>    2. Process individual sequence as strings and do search and replace of
>    individual codes; regular expressions don't work particularly well for
>    matching strings on multiple of three boundaries, so the search and replace
>    is done by brute force.
>    3. The munged strings are then pushed into a FASTA formatted buffer
>    and read back into a different data object.
>
> The code snippet doing this is here
> <https://github.com/spond/hyphy-support/blob/master/code_examples/issue325.bf>
>
> Sergei
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/veg/hyphy/issues/325#issuecomment-136816659>.
>



-- 
__________________________________________
Justin Fay
Associate Professor of Genetics
Washington University School of Medicine
Rm 5526, Center for Genome Sciences
4444 Forest Park Pkwy, St. Louis, MO 63108
Ph: 314.747.1808 Fax: 314.362.7855

**Comment by spond** [comment]
Hi Jason,

7997 is 20*20*20 - 3, i.e. HyPhy is auto-detecting that the file is composed of amino-acids (too many N's I would guess), and tries to build "protein-codons":). '?' resolve this issue as you noticed.

Sergei
