### ISSUE TITLE
F_ST.bf generating two errors 

### ISSUE THREAD

**Issue by rbjmax** [veg/hyphy#331]
I am using HYPHY 2.22 for MacOS on my OS 10.10.5 powerbook. I have used the F_ST.bf successfully in the past on other macs.

regardless of the method or the file (fasta formatted sequence data), I get two errors after specifying the two populations: Invalid Matrix Index[0][238] in a 1 by 238 matrix {the numbers vary according to the file I am using}
and
Problem occurred in line: overallSample2[Abs(overallSample)]=1

**Comment by spond** [comment]
Hi rjbmax,

Can you please download the latest Mac GUI binary (https://github.com/veg/hyphy/releases/tag/2.2.4), and confirm that the error is still there?

Sergei

**Comment by rbjmax** [comment]
Sergei-
I downloaded and used it, the error is still occurring.

Rachel

**Comment by spond** [comment]
Hi @rbjmax ,

That's unfortunate. Could you please list the sequence of options you have selected for the `F_st.bf` run? Does the error occur on **all** files, reproducibly?

Sergei

**Comment by rbjmax** [comment]
Sergei-
thanks for your attention. 
I selected standard analyses, compartmentalization, F_ST.bf, distance formulae (also tried full likelihood), nucleotide/protein; before uploading each of my four files. all combinations reliably generate the same two errors, the only differences being the number of sequences in each clade/partition.
Rachel

**Comment by rbjmax** [comment]
is it possible that IUPAC ambiguity terms could be a problem? I think one of my sequences has a "Y"

**Comment by spond** [comment]
Ambiguities are not an issue. I'll investigate later today.

**Comment by rbjmax** [comment]
I thought that ambiguities weren't a problem when I did this years ago, glad that hasn't changed. thanks for your effort on my problem.

Rachel

**Comment by spond** [comment]
Can you post the entire console content up to an including the error message, please?

**Comment by rbjmax** [comment]
I uploaded the text to my repository, HYPHY-files (can't add the text file here, and can't make it into a photo)

**Comment by spond** [comment]
Hi @rbjmax,

It's an error that seems to do with the fact that you have 128 sequences total, but only 115 are being selected for the analysis. That should **not** break the code, but it does. Oddly enough I can't easily replicate the issue using a random collection of files I tried (also not including all the sequences). Could you send one of the problematic alignments to me via spond@ucsd.edu please? Of course, I will only use it for debugging purposes.

Sergei
