### ISSUE TITLE
Variable 'MPI_NODE_COUNT' was not initialized prior to being used

### ISSUE THREAD

**Issue by lmdu** [veg/hyphy#333]
Hi all,
When I do recombination analysis, I get an error message:
Variable 'MPI_NODE_COUNT' was not initialized prior to being used

Anybody can help me. Thank you!

**Comment by spond** [comment]
Hi @lmdu,

This is a warning message, which can be safely ignored. HyPhy will set uninitialized variables to 0 by default

Sergei
