### ISSUE TITLE
FUBAR sitewise variance in alpha and beta values?

### ISSUE THREAD

**Issue by karolisr** [veg/hyphy#334]
I have tried looking for answers here and in the older message board with no luck. FUBAR output file reports mean per-site alpha and beta values. Is there a way to obtain a measure of per-site variance for these values? I have examined the sample files, hoping that there would be some sort of per-site set of samples for each codon position. It appears, however, that these files contain "weights of each grid point" as described here: http://www.hyphy.org/w/index.php/FUBAR, which I interpret as weights for each rate category (the 400 alpha and beta pairings). Is there a way to map the data in the output files to get a per-site estimate of variance?

Thank you,
Karolis

**Comment by spond** [comment]
Hi Karolis,

FUBAR outputs the MCMC sample of the alpha, beta distribution to a file whose suffix is `samples.N` (N ranges from 0 to the number of chains you selected - 1). You can use the information contained in these samples files and in the `grid_info` file to compute the quantities you want (see http://www.hyphy.org/w/index.php/FUBAR). 

Working code which takes in FUBAR files and reports means and variances can be found here: https://github.com/spond/hyphy-support/blob/master/code_examples/issue334.bf

Sergei

**Comment by karolisr** [comment]
Thank You!
