### ISSUE TITLE
Automating branch analysis

### ISSUE THREAD

**Issue by lyy005** [veg/hyphy#335]
Hi there
I'm using HyPhy on Linux system. I'm using this wrapper file:

fileToExe = "/hyphy/" + "TemplateBatchFiles"+ DIRECTORY_SEPARATOR+"BranchClassDNDS.bf";

/* a list of file paths */
SetDialogPrompt ( "Provide a list of files to process:" );
fscanf ( PROMPT_FOR_FILE, "Lines", _filesToProcessUsingDEPSrel );

fprintf (stdout, "[READ ", Columns (_filesToProcessUsingDEPSrel), " file path lines]\n");

inputRedirect = {};

inputRedirect["01"]="5";
inputRedirect["03"]="3";
inputRedirect["04"]="4";
inputRedirect["05"]="1";
inputRedirect["06"]="1";
inputRedirect["07"]="tree_nbs.MT.nwk";
inputRedirect["08"]="5";
inputRedirect["09"]="9";
inputRedirect["10"]="23";
inputRedirect["11"]="16";

for ( _fileLine = 0; _fileLine < Columns ( _filesToProcessUsingDEPSrel ); _fileLine += 1 ) {

  inputRedirect [ "02" ]    = _filesToProcessUsingDEPSrel[ _fileLine ];
  ExecuteAFile ( fileToExe, inputRedirect );
}

I tested this wrapper with one file. And there comes this error saying:  

[READ 1 file path lines]
Error:
Not a valid option: '5' passed to Choice List 'Choose Genetic Code' using redirected stdin input

I run hyphy interactively on Linux. The first input would be choose the genetic code, which is 5 (invertebrate mt). Am I supposed to put 5 in inputRedirect [ "01"]?

YY

**Comment by spond** [comment]
Hi @lyy005,

For wrappers, you need to provide the text value of the option (not it's index). For example, you would write

```

inputRedirect = {};

inputRedirect["01"]="Invertebrate mtDNA"; // case sensitive

```

and so on for other menu-based choices.

Best,
Sergei

**Comment by lyy005** [comment]
Hi Sergei
Thank you for your help. It works! Then another error pops up: 

How many rate classes should there be ([3-8] is a good range, must be >=2):Error:
Not a valid (or duplicate) option: 'd' passed to ChoiceList (with multiple selections) 'Choose the branch to test' using redirected stdin input

In my wrapper file, I used: 
inputRedirect["01"]="Invertebrate mtDNA";
inputRedirect["03"]="Complete";
inputRedirect["04"]="4";
inputRedirect["05"]="Default";
inputRedirect["06"]="Default";
inputRedirect["07"]="tree_nbs.MT.nwk";
inputRedirect["08"]="Node3";
inputRedirect["09"]="Node15";
inputRedirect["10"]="Node40";
inputRedirect["11"]="Node25";
inputRedirect["12"]="d";
inputRedirect["13"]="1";
inputRedirect["14"]="d";

inputRedirect["2"] is passed on by a loop in the wrapper. Is inputRedirect["04"]="4"; the right way to input number of Classes?
YY
