### ISSUE TITLE
Breakpoint not moving/same site for every generation in GARD?

### ISSUE THREAD

**Issue by sidneymbell** [veg/hyphy#336]
Hello!

I think I've managed to get both mpich and hyphy/gard up and running properly. However, I'm getting some odd output and it looks like it's not moving the breakpoint at all (it looks at site 1 for every generation). Any ideas what may be causing this? I've placed both the input alignment and the shell output in a dropbox: https://www.dropbox.com/sh/86o453estl9kmgb/AAB_mC3ClP8H5rhdVVVWoOyDa?dl=0

Thanks,

Sidney

**Comment by spond** [comment]
Hi Sidney,

This is not an error: when GARD finds no evidence of recombination (delta AIC = 0), the "breakpoints" reported are meaningless, because the best model is the model with 0 breakpoints. GARD will always **try** to place 1 and 2 breakpoints, but if no cAIC improvement is found, the analysis will terminate and report absence of recombination. See page 7 of http://www.hyphy.org/pubs/Methods2011.pdf for more details on how to interpret the results of GARD using `GARDProcessor.bf`.

Sergei

**Comment by sidneymbell** [comment]
Hi Sergei,

Thank you so much for your help, it's so kind of you to provide so much troubleshooting help to users. I so apologize for the long delay; I've spent a good bit of time since my initial message trying to nail down exactly what the issue is. 

I've since downgraded to hyphy 2.2.0, running with OpenMPI version 1.6.5 on our cluster, and have had some limited success (more so than when I was using the latest version). I've also updated that dropbox with examples that better illustrate the issue I'm having. 

In the 'successful' folder is the input alignment, batchfile, stdout, and results overview file for an alignment that was ran beautifully on this installation of hyphy/GARD. Most notably, it explored "592/11204532598797 (3537 over all runs) unique models".

In the 'unsuccessful' folder is the alignment, batchfile, stdout, and results from an alignment that did not run well on GARD. It's worth mentioning that these are viral sequences from SIVs, and when I make basic ML trees in RAxML from various regions of this same alignment and compare them, you can tangibly see tons of recombination from this alignment. What's the most troubling to me, and is the error I first noticed, is that even on the same installation of hyphy on the same day with the same parameters (I've run this with just about every combination of input parameters I can think of), GARD never explores more than 1 or 2 models total when handed this alignment as input, and invariably returns that there's no recombination. 

I'm sure there's some minor thing that I'm entirely overlooking or some mistake I'm making, but I can't for the life of me figure out what it is. Any thoughts you have would be infinitely helpful.

Let me know if I can provide any other useful information or files. I also have the rest of the gard output files, slurm and mpi output, and nucleotide model selection analysis output files available, but left them out for clarity's sake. 

Thank you again for your time, I so very appreciate it! 

Sidney
