### ISSUE TITLE
compartmentalization tutorial

### ISSUE THREAD

**Issue by mlosada323** [veg/hyphy#337]
Hi Sergei,

I want to use the compartmentalization tests in hyphen. I found a tutorial online from the Vancouver workshop 2011 but it's sort of basic. The website says "Follow the instructions and remember to carry out the significance test", what makes me think that there are more detail instructions somewhere. Hence, how could I access this information to explore all the different tree and distance bases options to check compartmentalization?

Best

Marcos

**Comment by spond** [comment]
Dear Marcos,

If I remember, Selene Zarate had a whole slide deck for the tutorial at that workshop. I'll e-mail her and ask if she still has them.

Sergei

**Comment by mlosada323** [comment]
Thanks

Marcos

**Comment by spond** [comment]
Hi Marcos,

I added a link to the tutorial at http://hyphy.org/w/index.php/User_Guides#Specialized

Sergei

**Comment by mlosada323** [comment]
Thanks. I checked it out and it seems like the implemented Fst and Snn tests to assess compartmentalization only allow for two compartments to be compared. Is that correct? 

Marcos

**Comment by spond** [comment]
Hi Marcos,

Yes, that is correct. You could extend it to multiple compartments without too much difficulty however. Do you have a case study where you need it?

Sergei

**Comment by mlosada323** [comment]
Hi Sergei,

My case study includes 10 body compartments per macaque. Since both SIV and HIV compartmentalization is a relevant issue, expand Fst and Snn analyses in HyPhy to include >2 compartments would make them more applicable and useful.

Best

Marcos

**Comment by mlosada323** [comment]
I ran the phylogenetic tests and found significant evidence of compartmentalization. Now it'd be great to be able to run Fst and Snn tests all at once to see what particular pairwise compartment comparisons are significant.

**Comment by spond** [comment]
Hi Marcos,

Sure, I can mod the F<sub>ST</sub> code to deal with multiple compartments. It's a bit tricky to interpret what this means, e.g. you could have 10 compartments of which only 3 are genetically segregated, but that's enough to drive the signal. 

I also have code somewhere that automatically does all-against-all comparisons, but two compartments at a time.

Sergei

**Comment by mlosada323** [comment]
Agree, an all-regions-included comparison wouldn't be that useful if you try to detect segregation between specific compartments. I was thinking more of a pairwise comparison where the output would be a table of Fst and Snn for each pair with attached significances. Basically the second option in your email. Thanks again for taking care of it.
