### ISSUE TITLE
aBSREL output

### ISSUE THREAD

**Issue by MariaPacheco** [veg/hyphy#339]
Dear Sergei,
I’m trying to run aBSREL several times using different alignments but I’m not getting any result. When  the program finish it only says:

"Adaptive branch site REL summary
Evidence† of episodic diversifying selection was found on out of tested branches ( total branches).
†LRT p ≤ 0.05, corrected for multiple testing".
There is not table or tree.

I have run this test before without any problem but now I'm not getting anything.
Could you please help me?

Thanks,
Maria Pacheco
IGEM, Temple University

**Comment by spond** [comment]
Hi Maria,

To clarify: are you talking about the screen (console) output, or the interactive web application at http://veg.github.io/hyphy-vision/absrel/ ? If it is the latter, please attach the `.json` file that aBSREL has generated so that I can debug it.

Sergei

**Comment by MariaPacheco** [comment]
Hi,
I'm using the interactive web application but I don't see any .json file.
This is my link:
http://test.datamonkey.org/absrel/5609a91ecef9fd7e3f80ef66

Thanks a lot!
Maria

**Comment by spond** [comment]
Hi Maria,

We'll investigate and get back to you when the issue has been resolved.

Thanks,
Sergei

**Comment by MariaPacheco** [comment]
Hi Steve,
I don't understand what it means. Did you solve the problem?
What I need to do?

Thanks a lot!
Maria

**Comment by stevenweaver** [comment]
Hello Maria, 

Sorry, please wait just a few more minutes.
I'll 
I've committed the changes that fix this problem

**Comment by stevenweaver** [comment]
Hello Maria, 

The issue has been resolved, but there are a number of long running jobs running on our cluster that need to complete before restarting our webserver in order for the changes to take effect.

I've scheduled a release of 12:00am EST tonight. After that point, please rerun your aBSREL analyses. If time is urgent, I can retrieve past results in CSV format and email them to you directly.

Apologies for the inconvenience, 
Steven

**Comment by MariaPacheco** [comment]
Thanks Steven!
I can wait, don't worry. Some of the long running jobs are mine too.


Maria

**Comment by stevenweaver** [comment]
Hello Maria,

I've completed the update to aBSREL. 
Please feel free to reopen this issue if you come across further problems.

Regards, 
Steven

**Comment by MariaPacheco** [comment]
Thanks!
It's working.
Maria
