### ISSUE TITLE
Function arguments

### ISSUE THREAD

**Issue by spond** [veg/hyphy#340]
Currently if a function is given too many arguments in a call, HyPhy takes enough from the **end** of the list to make the call, and the rest are left on the stack for other operations to compute so, that broken code computes something

```
function sum (a,b) {
    return a+b;
}

fprintf (stdout, sum (1,2,3) +, "\n");
```

the result is 

```
6
```

**Comment by rdvelazquez** [comment]
In 2.4.0 overloading a function causes an `Unconsumed values on the stack` error.

**Comment by rdvelazquez** [comment]
There is now a TODO comment in `tests/hbltests/UnitTests/HBLCommands/Function.bf` for addressing the unconsumed values on the stack error.
