### ISSUE TITLE
PRIME exchangabilites matrix

### ISSUE THREAD

**Issue by jwconnolly** [veg/hyphy#342]
Hi Dr. Pond, could you explain the inferred exchangeabilities matrix in in PRIME? What exactly is it saying? For example, I have a significant change in codon 985 but I see no red in the matrix. Or conversely, at codon 985 there are many blue boxes (which I assume represents conserved biochemical properties) for example C-R, but there are no C or R residues in my alignment at codon 985 

http://www.datamonkey.org/spool/upload.424035446525431.1_prime.php#

Thanks, Joe

**Comment by spond** [comment]
Hi Joe,

I'm actually working on updating PRIME for a new Datamonkey release, so I may have further comments later on. In the mean time, I would not over interpret the matrices. Firstly, it is not necessary to have any individual rate to be high (red), as the signal may derive from many weak individual contributions. Secondly, every individual pair (e.g. C-R) will be assigned **some** rate by the model, even though the power comes from other residues (presumably with similar property differences). 

Hope this makes sense.

Sergei

**Comment by jwconnolly** [comment]
ok that makes sense, so is there a way to actually identify the different residues at those positions from the information provided by prime? Or would I have to look at the amino acid alignment at that position an infer which residue it is using the properties of that amino acid?

**Comment by spond** [comment]
Hi Joe,

Of course PRIME will base its inference on site composition, but it will also consider gene-wide frequency compositions, branch lengths, tree topology, and all other model component. Because of this, looking at residue composition is a good *sanity check*, but it doesn't tell the whole story. There is no way in the current implementation to identify which specific substitutions (or lack thereof) contributed to the signal.

Sergei

**Comment by jwconnolly** [comment]
Thanks, Dr. Pond. So what conclusions can one draw from PRIME? Just that there are biochemical differences/similarities at these positions throughout the entire gene tree?

Sorry I have so many questions, I just want to pick the proper test/tests and make sure I unsderstand what they are telling me

**Comment by spond** [comment]
Hi Joe,

I would take a look at https://github.com/veg/hyphy-tutorials/raw/master/selection/slides.pdf starting at page 77 for more background on PRIME. 

PRIME tells you which (if any) biochemical properties are conserved or change at a particular site. This inference is made over the entire tree -- there is no power in this framework to assign significance to individual branches.

Sergei

**Comment by jwconnolly** [comment]
thanks! The slides were very helpful, I have one final question. I want to map these sites onto a model by color coding them however the numbers in the analysis and the numbers I uploaded don't add up. PRIME is listing 985 (2,955 nucleotides inc gaps) codons but the Nucleototide output file only list 2520 nucleotides (840 codons) and even worse the AA output file saying there are 760 AA inc gaps (2280 nt). If I see PRIME is showing codon 831 is conserved for example what residue is it talking about?

http://www.datamonkey.org/spool/upload.424035446525431.1_prime.php
http://www.datamonkey.org/cgi-bin/datamonkey/seqPlot.pl?file=upload.424035446525431.1
http://www.datamonkey.org/cgi-bin/datamonkey/seqPlot.pl?file=upload.424035446525431.1.aa

**Comment by spond** [comment]
Hi Joe,

The files are all 985 aa long; the sequence plotters are buggy for some reason (I will check). If you look at http://www.datamonkey.org/cgi-bin/datamonkey/showdata.pl?upload.424035446525431.1 for example, you will see that there are 2955 nucleotides.

Sergei

**Comment by jwconnolly** [comment]
Oh ok, I just used my own alignments to find the sites. Thanks
