### ISSUE TITLE
upload a tree file for BUSTED

### ISSUE THREAD

**Issue by MariaPacheco** [veg/hyphy#343]
Hello,

Is it possible to upload a tree file and use it for Busted?
I know that is possible for aBSREL and Relax, but Busted is not recognizing the tree in my flies.

Thanks,
Maria

**Comment by MariaPacheco** [comment]
to clarify, I'm using the  the interactive web application.

thanks,
Maria Pacheco

**Comment by spond** [comment]
Hi Maria, 

You should be able to see it just the same. @stevenweaver can you please check?

Maria: what is your analysis URL?

Sergei

**Comment by MariaPacheco** [comment]
Hello Sergei,
No, I can not see my tree, only the NJtree. My link is:
http://test.datamonkey.org/busted/560d69361404741c0791324a/select-foreground
Actually, I'm using the same file for RELAX without any problem.
Thanks,
Maria

**Comment by spond** [comment]
Hi Maria,

This means that HyPhy was not able to recognize the tree included in the file. Can you send me the file by e-mail so I can see what the issue is?

Sergei

**Comment by MariaPacheco** [comment]
Yes, HyPhy was not able to recognize the tree included in the file.

Here is the file!

Thanks,
Maria

**Comment by stevenweaver** [comment]
Hello Maria, 

Thank you. I will respond shortly with a solution. 

Steven

**Comment by spond** [comment]
Hi Maria,

GitHub doesn't automatically handle e-mail attachments. Can you please resend it directly to my UCSD address?

Sergei

**Comment by stevenweaver** [comment]
Hello Maria, 

Thank you, I received your FASTA file. 
I have released the fix to test.datamonkey.org this morning. 

Kind Regards,
Steven

**Comment by MariaPacheco** [comment]
Thanks Steven!
Maria

**Comment by MariaPacheco** [comment]
Hello,
Now, Busted is  able to recognize the tree included in my file and I'm
getting the results. However, I cannot save the results in any of the
formats (PNG or SGV).
Here are the links:
http://test.datamonkey.org/busted/5612de75f5febf7f73ec910b or
http://test.datamonkey.org/busted/5613d87df5febf7f73ec91e6

Any suggestions?
Thanks,
Maria Pacheco

**Comment by spond** [comment]
Hi @MariaPacheco,

It seems like a JavaScript bug due to code refactoring. @stevenweaver will fix (Steven, there are also some CSS classes not being applied correctly -- look at the plot axes in the Tree tab in the linked result pages).

Sergei

**Comment by stevenweaver** [comment]
Hello @MariaPacheco,
@spond was correct. Please try again. 

@spond, 
I've hid the legend (indicating foreground and background) on the phylotree view for Busted for now. The plot axes have been resolved.

Regards,
Steven

**Comment by MariaPacheco** [comment]
Thanks!
Maria
