### ISSUE TITLE
Spidermonkey analysis on MT and NUC data

### ISSUE THREAD

**Issue by lyy005** [veg/hyphy#344]
Hi there,
I'm using the Spidermonkey analysis on some MT genes and NUC genes to understand their co-evolution. I wonder is there a way to set the codon tables separately for two types of data?

Thank you
YY

**Comment by ArtPoon** [comment]
The best way would be to run a standalone analysis with HyPhy. You should be able to define separate codon partitions using different genetic codes, and then merge ancestral reconstructions for BGM analysis.

**Comment by lyy005** [comment]
Thank you for your quick reply. I was using the QuickSelectionDetection.bf in HyPhy for analysis. Would you give any advice on how to run two steps separately?

YY
