### ISSUE TITLE
MEME error

### ISSUE THREAD

**Issue by lyy005** [veg/hyphy#345]
Hi 
I ran into this error when I ran the MEME model with HYPHYMPI (HYPHY 2.220150825beta(MP) for Linux on x86_64). 
Error:perBranchTree is undefined in call to ReplicateConstraint.

I found some questions relates to this issue on the forum. I tried the solutions but they didn't work. Thank you for your help!

My inputs are:
inputRedirect = {};
inputRedirect["01"]="Invertebrate mtDNA";
inputRedirect["02"]="New Analysis";
inputRedirect["03"]="Default";
inputRedirect["04"]="1";
inputRedirect["05"]="USER/gene.concatenated.aln.nex";
inputRedirect["06"]="USER/MEME";
inputRedirect["07"]="0.05";
ExecuteAFile ("USER/" + "TemplateBatchFiles"+ DIRECTORY_SEPARATOR+"MEME_mf.bf", inputRedirect);

**Comment by spond** [comment]
Hi @lyy005,

Are you running the analysis in an MPI environment? The version you pasted into the issue box suggests you are using an MP (multi-threaded), but not MPI version.

Still, it's a bug. Let me see if I can fix it.

Sergei

**Comment by lyy005** [comment]
Hi Sergei
Yes, that's MP. I ran the same data on HYPHY 2.24 on windows (win32). It also has this problem. 

YY

**Comment by lyy005** [comment]
Hi Sergei
I uploaded my data to Datamonkey. It only took 3901 codon sites at most. Is there any alternative way to run MEME you would recommend?

YY

**Comment by spond** [comment]
Hi @lyy005,

How large is your file (sequence length and number of sequences)?

Sergei

**Comment by lyy005** [comment]
Hi Sergei
Thank you for your advice. I have 13 mitochondrial genes and 34 nuclear genes for 32 spp. I'll split and run them separately. May I ask a stupid question that why it's not right to combine different genes? And is it ok to put different genes into different data partitions?

YY

**Comment by jergosh** [comment]
I'm getting the same error, both in the MPI and MP versions. I'm using HyPhy v. 2.2.6. I was wondering if there are any temporary workarounds (I would like to run many analyses so Datamonkey is not an option)?

**Comment by spond** [comment]
Hi @jergosh,

I'll take a look and fix it next week.

Sergei

**Comment by jergosh** [comment]
Hi again,
In the meantime, is there a version of Hyphy that's less likely to spit out these errors, or should I just try a few recent ones?

Greg

**Comment by spond** [comment]
Dear @jergosh,

Branch [v.2.2.6 working](https://github.com/veg/hyphy/tree/v2.2.6-working) should be free of this error (in a serial implementation). Could you please confirm? 

Sergei

**Comment by jergosh** [comment]
Hi Sergei,
Thanks for looking into this. I checked out the branch you specified. It ran for a while but then I'm getting the following error:

```bash
[MEME PHASE 0] Retuning branch lengths and nucleotide rates under the codon model...
Improved Log(L) BY 0.07717458302613522 points
[MEME PHASE 1]. Fitting a codon model site-by-site
| Codon |     Beta- |   Weight- |    Beta+  |   Weight+ |     alpha |      LRT  |   p-value |Full Log(L)|   Est. remaining time (secs)
Error:
perBranchTree is undefined in call to ReplicateConstraint.

Function call stack
1 : Replicate the following constraint "this1.?.alpha:=_sFactor*this2.?.synRate__" using these variables:perBranchTree;codonTree;
-------
2 : result_String["BRANCHES"]=obtainBranchWiseEBEstimates(sFactor,nsFactor1,nsFactor2,mixingP,filterString)
-------
3 : Branch under condition 'SendJobMEME()'
	to
		<END EXECUTION>
	else
		<END EXECUTION>
-------

Check errors.log for details on execution errors.

Check messages.log details of this run.
HYPHYMP(10063,0x7fff77516000) malloc: *** error for object 0x7fb22c00b000: pointer being realloc'd was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by spond** [comment]
Dear @jergosh,

Could you please list the analysis options you have selected for MEME? Specifically, did you choose to save individual site analyses to files?

Sergei

**Comment by maja-stanojevic** [comment]
Hello,

When trying to perform MEME analysis I am getting the following message:
Error:
perBranchTree is undefined in call to ReplicateConstraint.

Function call stack
1 : Replicate the following constraint "this1.?.alpha:=_sFactor*this2.?.synRate__" using these variables:perBranchTree;codonTree;
-------
2 : result_String["BRANCHES"]=obtainBranchWiseEBEstimates(sFactor,nsFactor1,nsFactor2,mixingP,filterString)
-------
3 : Branch under condition 'SendJobMEME()'
        to
                <END EXECUTION>
        else
                <END EXECUTION>
-------
Segmentation fault


The analysis is done with an MP version of the HyPhy v. 2.2.6
Can you help?

Sincerely

Maja

**Comment by jergosh** [comment]
Hi again, 
I'm now trying to perform the same analysis again and I've realised I possibly misunderstood what you meant by the serial version of HYPHY. Is this the one built by "make SP"? If so, I'm getting a "No rule to make target `SP'." error (I can build MP2, MPI, HYPHYDEBUG just fine after running cmake).

Best,
Greg

**Comment by spond** [comment]
Hi @jergosh,

MP2 is the one I had in mind.

Sergei

**Comment by jergosh** [comment]
I've just rerun MEME and I'm still getting the same error (it also seems to be the same that @maja-stanojevic is getting). I'm running it as follows: 
```
~/Documents/projects/sw/hyphy-fixed/bin/HYPHYMP ~/Documents/projects/sw/hyphy-fixed/lib/hyphy/TemplateBatchFiles/MEME_mf.bf
```

I then select:
"Universal"
"New Analysis"
"Default"
"1"
<alignment>
<tree>
<output_file>
0.05

I've attached the alignment and tree files (renamed to txt so that github allows the upload). I've also attached the messages.log and errors.log and the contents of stdout.
[7631_1_fa.txt](https://github.com/veg/hyphy/files/105492/7631_1_fa.txt)
[7631_1_tree.txt](https://github.com/veg/hyphy/files/105491/7631_1_tree.txt)

[errors.txt](https://github.com/veg/hyphy/files/105482/errors.txt)
[MEME_stdout.txt](https://github.com/veg/hyphy/files/105481/MEME_stdout.txt)
[messages.txt](https://github.com/veg/hyphy/files/105483/messages.txt)

Many thanks for your help,
Greg

**Comment by lyy005** [comment]
Hi
Just a follow-up question. I'm getting the same error with HYPHY 2.2620160130beta(MP) for Linux on x86_6 running the WestNileVirus_NS3.fas data.  

Has anyone solved this problem?

YY

**Comment by spond** [comment]
Dear @lyy005 ,

Unless you need to include recombinant segments in your analysis, please run a different version of MEME, accessible through QuickSelectionDetection.bf as outlined in this [tutorial](https://github.com/veg/hyphy-tutorials/tree/master/selection#use-meme-to-find-sites-which-have-experienced-episodic-diversification) 

I'm reworking **all** selection analyses for an upcoming v2.3 release, so the issue you encountered will be fixed by then.

Sergei

**Comment by lyy005** [comment]
Thank you @spond 
I tried the QuickSelectionDetection.bf  and it's working. 

YY
