### ISSUE TITLE
HyPhy vision

### ISSUE THREAD

**Issue by francicco** [veg/hyphy#346]
Hi everyone,

I'm trying to visualize my aBSREL result using http://veg.github.io/hyphy-vision/absrel/. The problem is that I can't export the graphics. I guess some exporting buttons are missing.

best,
F

**Comment by spond** [comment]
Hi @francicco,

You are right -- the hyphy-vision version doesn't have the export buttons yet. I've assigned @stevenweaver to work on it, but in the meantime, you can always try printing to PDF (if you are using a Mac OS X machine), or equivalent to get the images you need.

Sergei

**Comment by francicco** [comment]
Thank you @spond,

Would also be possible to re-root the tree?

best,
F

**Comment by spond** [comment]
Hi @francicco ,

The current instance of the aBSREL viewer does not support re-rooting after the analysis, although it is within the capabilities of the tree viewer. aBSREL returns **unrooted* trees, so rerooting a tree will create a "root" branch which has no modeling data associated with it. We'll investigate turning this option back on.

Sergei

**Comment by stevenweaver** [comment]
Hi @francicco ,

I've added an export button to the tree and graph. 

Unfortunately, the export does not include the color scale. I've created a separate issue for myself [here](https://github.com/veg/phylotree.js/issues/10) for that.

If you are using OSX, you can also use `Command-Shift-4` to select a portion of the screen. 

Regards,
Steven
