### ISSUE TITLE
positive selection in non-coding DNA

### ISSUE THREAD

**Issue by malorfisch** [veg/hyphy#347]
Is possible on datamonkey or with HyPhy to assess for positive selection in non-coding regions (comparison of non-coding to coding, as in Haygood et al. 2007. Nat Genet. 39:1140-4)? What would be the methods for such analysis?
Thanking you for your time,
mf

**Comment by spond** [comment]
Hi @malorfisch,

Yes, the paper you cite should have an accompanying HyPhy batch file for testing for selection using their method. Have you tried asking the authors for it?

Sergei

**Comment by spond** [comment]
Hi @malorfisch,

The files your are looking for are at https://github.com/ofedrigo/TestForPositiveSelection

Sergei
