### ISSUE TITLE
HYPHYMPI not finishing faster after giving it more cores

### ISSUE THREAD

**Issue by m-vieira** [veg/hyphy#348]
Hi,

I'm trying to run dNdSRateAnalysis.bf on a fairly large alignment (460 sequences, 321 nucleotides) using HyPhy MPI. I started with 4 processors and was able to fit 4 of the 5 models (Constant, Var. N.Syn., Prop. Var. and Dual Variable), but the job got cancelled without fitting Lineage Dual after running into the maximum permitted wall time in my cluster (36 hours). I tried increasing the number of processors, but it didn't seem to be sufficient and I was spending a lot of service units, so I started doing some tests as I began to suspect HyPhy wasn't making use of any extra processors.

I've run dNdSRateAnalysis.bf selecting only the "Constant Rates" model with either 2 or 8 processors, and the wall time was almost exactly the same (similarly, I got identical wall times for 2 and 8 processors when repeating this test with the "Dual Variable"). 

I'd appreciate some help to identify what I'm doing wrong (or maybe conclude that there is an issue with the HYPHYMPI installation in my cluster).

Below are the input (with file paths simplified) and sbatch files.

Thank you,

Marcos Vieira
University of Chicago

**Input file**
```
/path/to/alignment
1
/path/to/tree
1
4
012345
2
1
d
/path/to/results
```

**sbatch file for 2 processors run**
```
#!/bin/bash
#SBATCH --job-name=HYPHYMPI_TEST_2_NODES
#SBATCH --output=HYPHYMPI_TEST_2_NODES.out
#SBATCH --error=HYPHYMPI_TEST_2_NODES.err
#SBATCH --time=03:00:00
#SBATCH --partition=sandyb
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2

module load hyphy

cd /home/mvieira/hyphy_tutorial
echo $(date) > HYPHYMPI_TEST_TIME_2_NODES

mpirun -np 2 HYPHYMPI /software/hyphy-2.2-el6-x86_64/lib/hyphy/TemplateBatchFiles/dNdSRateAnalysis.bf < HYPHYMPI_TEST_2_NODES_input

echo $(date) >> HYPHYMPI_TEST_TIME_2_NODES
```

**sbatch file for 8 processors run**
```
#!/bin/bash
#SBATCH --job-name=HYPHYMPI_TEST_8_NODES
#SBATCH --output=HYPHYMPI_TEST_8_NODES.out
#SBATCH --error=HYPHYMPI_TEST_8_NODES.err
#SBATCH --time=03:00:00
#SBATCH --partition=sandyb
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8

module load hyphy

cd /home/mvieira/hyphy_tutorial
echo $(date) > HYPHYMPI_TEST_TIME_8_NODES

mpirun -np 8 HYPHYMPI /software/hyphy-2.2-el6-x86_64/lib/hyphy/TemplateBatchFiles/dNdSRateAnalysis.bf < HYPHYMPI_TEST_8_NODES_input

echo $(date) >> HYPHYMPI_TEST_TIME_8_NODES
```

**Comment by spond** [comment]
Hi @m-vieira,

Not all analyses are MPI enabled; you will only get speedups for this particular analysis using multiple cores on the same machine. May I suggest you run [FUBAR](https://github.com/veg/hyphy-tutorials/tree/master/selection#use-fubar-to-find-sites-which-have-experienced-pervasive-diversification) instead, if you are interested in site-level inference? 

Sergei

**Comment by m-vieira** [comment]
Hi Sergei,

Thanks for the clarification. I'll look into FUBAR.

Marcos
