### ISSUE TITLE
Simulating from a codon fit file but specifying the sequence length

### ISSUE THREAD

**Issue by halasadi** [veg/hyphy#349]
Hi,

I've been trying to write a batch file to simulate from a fit file but with a different sequence length than the original data in the fit file.

This code (provided to me by you) below works great for simulating sequences from a fit file

```
SetDialogPrompt ("Load the model fit");
ExecuteAFile (PROMPT_FOR_FILE);

fprintf (stdout, "[SIMULATING DATA FROM `LAST_FILE_PATH`]\n");

DataSet sim = SimulateDataSet (lf);
DataSetFilter simF = CreateFilter (sim,1);

SetDialogPrompt ("Save the simulated alignment to:");
fprintf (PROMPT_FOR_FILE, CLEAR_FILE, simF);
```

**However, I want to simulate a sequence of codons with size, say n.** To do this, I've tried to access the tree and equilibrium frequencies from the likelihood function (```lf```) and input this information into ```Simulate()``` using code similar to this: https://github.com/spond/hyphy-support/blob/master/code_examples/issue204.bf

However, I'm having trouble obtaining the equilibrium frequencies and tree from ```lf``` using the ```GetInformation()``` function. Using ```GetInformation()```, ```lf``` just seems to be {"d","c"}....

Any help will be greatly appreciated!

Hussein

**Comment by halasadi** [comment]
The command I was looking for is LIST_ALL_VARIABLES. This code seemed to work for me:

```
SetDialogPrompt ("Load the model fit");
ExecuteAFile (PROMPT_FOR_FILE);

fprintf (stdout, "[SIMULATING DATA FROM `LAST_FILE_PATH`]\n");

/*fprintf (stdout, LIST_ALL_VARIABLES);*/


characters = { {"A","C","G","T" } 
{"3","TAA,TAG,TGA","",""} };

for (site = 0; site < 33; site +=1){
    if (site == 0){
       DataSet testData = Simulate(givenTree_1, vectorOfFrequencies, characters, 1,0);
    }
    else {
       DataSet sim = Simulate(givenTree_1, vectorOfFrequencies, characters, 1,0);
       DataSet testData = Concatenate(testData, sim);
    }
}

DataSetFilter simF = CreateFilter(testData, 1);


/*DataSet sim = SimulateDataSet (lf);
DataSetFilter simF = CreateFilter (sim,1);*/

SetDialogPrompt ("Save the simulated alignment to:");
fprintf (PROMPT_FOR_FILE, CLEAR_FILE, simF);

```

**Comment by spond** [comment]
Hi @halasadi,

`Simulate` is designed to make parametric bootstrap replicates from a model fit: this requires maintaining the dimension of the data (number of sites). You could simulate individual sites as you did, but a faster way to do it is to to use different simulation instruction, assuming you already have a tree object with fitted model attached to it (e.g. `givenTree_1` in your example, and `T` in the example below`)

```

/* Alphabet spec matrix has the format:

1). First row lists the characters in the same order they are used in the models
2). Second row only has two first meaningful entries:
		(a) Characters per state (1 for nuc and a.a, 3 for codons)
		(b) Comma Separated list of excluded states (such as stop codons)
		
*/

characters = {{"A","C","G","T"}
			  {"1","","",""}};
			  
/*

charactersUniversalCode = {{"A","C","G","T"}
			  				{"3","TAA,TAG,TGA","",""}};
			  				
charactersProtein = {{"A","C","D","E","F","G","H","I","K","L","M","N","P","Q","R","S","T","V","W","Y"}
					 {"1","","","","","","","","","","","","","","","","","","",""};
					 
*/
			  
/* Simulate takes the arguments:

1). A tree
2). A matrix of EF
3). Alphabet spec
4). Number of sites or a string with the root state (that also determines the lenghts)
5). (Optional) Set to 1 to include ancestral states.
6). (Optional) File name to write the data to - only works for simulations without rate categories.
*/

DataSet sim = Simulate (T,eqf,characters,sites,ancChoice,LAST_FILE_PATH);
```

Sergei
