### ISSUE TITLE
a very simple question

### ISSUE THREAD

**Issue by l-yampolsky** [veg/hyphy#350]
How do I launch HyPhy using command line interface?

Tutorials and answers to forum questions here and there give instructions like "Upon launch...". OK.
How do I launch it?
(I guess the fact that it is not obvious to me means that HyPhy did not install correctly, which will be my next question, but let's first find out if there is something very stupid and very obvious I am not doing right).

Thanks very much in advance for your help!

**Comment by stevenweaver** [comment]
Hello, 

May I ask which platform you are using?

The following commands should install and run a command line version of HyPhy, provided you have `cmake` installed.

```
wget https://github.com/veg/hyphy/archive/2.2.6.tar.gz
tar xvzf 2.2.6.tar.gz
cd hyphy-2.2.6
cmake .
make HYPHYMP
/usr/local/bin/HYPHYMP
```

Kind Regards,
Steven

**Comment by l-yampolsky** [comment]
Thanks very much! I should have looked into /usr/local/bin/ after install, not before it. I was trying to launch HYPHYMPI instead of HYPHYMP.
I did "make MP2", not "make HYPHYMP" - that should not make a difference?

(platform: Linux, x86_64)

**Comment by stevenweaver** [comment]
Glad I could help, and no, using MP2 shouldn't make a difference. 

If you have an mpi variant installed on your linux machine (or cluster), you can build an MPI version by using the command `make HYPHYMPI`.

**Comment by filiperomero2** [comment]
Thank you, Steven.
Your answers here were very helpful!
