### ISSUE TITLE
BUSTED output format

### ISSUE THREAD

**Issue by l-yampolsky** [veg/hyphy#351]
Dear Colleagues,
I am planning to run BUSTED for several thousand alignments and I have 2 questions.
1) is there somewhere a formal description of BUSTED output format for the purpose of writing a parser?
and
2) is there a way, in CLI, to ask for a less verbose output (say, all I need is, for each alignment analyzed, just LLs for each model or their p-value and sites where positive selection was detected if any) - maybe I won't need to write a parser?

Thanks very much in advance!

**Comment by spond** [comment]
Dear @l-yampolsky,

BUSTED writes [JSON](http://json.org) files for each file you process (see https://github.com/veg/hyphy-tutorials/tree/master/selection#run-alignment-wide-tests-for-episodic-diversification-busted). All common scripting languages (e.g. Python, Perl) provide modules for parsing JSON files into objects, so writing a parser should be trivial. Here's an example of the JSON BUSTED output, it should be self-explanatory. Look at keys `fits` and `test results`.

```
{
    "fits": {
        "Unconstrained model": {
            "log-likelihood": -13269.34687426236,
            "parameters": 41,
            "AIC-c": 26620.99120922605,
            "runtime": 823,
            "tree length": 2.07931621469404,
            "tree string": "((((((((Homo_sapiens:0.0192700711592093,Pan_troglodytes:0.007148451384124488)Node7:1e-10,Gorilla_gorilla:0.01137065441386363)Node6:0.01096256157050009,Pongo_pygmaeus:0.02751761268537057)Node5:0.03884653418334003,Macaca_mulatta:0.05902988532676096)Node4:0.02630979950299168,Alouatta_seniculus:0.1243202231845073)Node3:0.1295848977407572,Otolemur_crassicaudatus:0.3195468877533464)Node2:0.03366694243299424,Cynocephalus_variegatus:0.193783199589794)Node1:0.6919202921875593,Mus_musculus:0.2039806942993562,Rattus_norvegicus:0.1820575071795646)",
            "rate distributions": {
                "FG": [
                    [
                        0.9865641689119024,
                        0
                    ],
                    [
                        0.933028058290739,
                        0
                    ],
                    [
                        2.317352448627875,
                        1
                    ]
                ],
                "BG": [
                    [
                        0.4876105827025015,
                        0.6858048352668921
                    ],
                    [
                        0.5928672770486135,
                        0.2227675718800387
                    ],
                    [
                        3.015132763212292,
                        0.09142759285306924
                    ]
                ]
            }
        },
        "Constrained model": {
            "log-likelihood": -13270.84851648228,
            "parameters": 40,
            "AIC-c": 26621.98030440424,
            "runtime": 73,
            "tree length": 2.079464628990517,
            "tree string": "((((((((Homo_sapiens:0.01931760628100015,Pan_troglodytes:0.007167247310235911)Node7:1e-10,Gorilla_gorilla:0.01137260399891454)Node6:0.01096403824483036,Pongo_pygmaeus:0.02752234258914422)Node5:0.03885270271870599,Macaca_mulatta:0.05903829951869525)Node4:0.0263118463833133,Alouatta_seniculus:0.1243394115042506)Node3:0.1295958596350156,Otolemur_crassicaudatus:0.31957995783911)Node2:0.03367315472606195,Cynocephalus_variegatus:0.1938162631290867)Node1:0.6918328489888418,Mus_musculus:0.2040044608969027,Rattus_norvegicus:0.1820759851264084)",
            "rate distributions": {
                "FG": [
                    [
                        0.9382667009896091,
                        0
                    ],
                    [
                        0.9376994275382688,
                        0
                    ],
                    [
                        1,
                        1
                    ]
                ],
                "BG": [
                    [
                        0.4898318299687247,
                        0.6897210096204203
                    ],
                    [
                        0.5875139563797906,
                        0.2200864140910051
                    ],
                    [
                        3.03032581203736,
                        0.09019257628857462
                    ]
                ]
            }
        }
    },
    "timers": {
        "overall": 904,
        "unconstrained": 823,
        "constrained": 73
    },
    "profiles": {
        "unconstrained": [
            [An array of site likelihoods under this model]
        ],
        "constrained": [
            [An array of site likelihoods under this model]
        ],
        "optimized null": [
            [An array of site likelihoods under this model]
        ]
    },
    "evidence ratios": {
        "constrained": [
             [Approximate log-likelihood ratios for selection at a site (see the paper)]
        ],
        "optimized null": [
            [Approximate log-likelihood ratios for selection at a site (see the paper)]
         ]
    },
    "test set": "Homo_sapiens,Pan_troglodytes",
    "background": 1,
    "test results": {
        "LR": 3.00328443984472,
        "p": 0.04154795131767564
    }
}

```

**Comment by l-yampolsky** [comment]
Dear Sergei,
Thank you very much, this is very helpful.
Would you agree that the right strategy to look for positive selection in a large number of alignments is to run all of them using BUSTED and then run aBSREL for the subset of alignments for which BUSTED found a significant signal to identify in which branch it happened? 

Best,
Lev Yampolsky

**Comment by l-yampolsky** [comment]
Dear Sergei,

Once again thank you very much for your explanation of the json output format. As I mentioned before, out plan is to run BUSTED and/or aBSREL on a few thousand alignments (transcriptomics data from a species flock). Clearly before thinking about automatizing output we should be thinking about automatizing input.

I did find this: https://evolve.sbcs.qmul.ac.uk/rossiter/2014/10/17/697/, which is very clever, but also complicated and I am not sure I can replicate it with BUSTED.bf. I wonder if there is an easier way to supply HyPhy with input file names so that we could run it on many alignments sequentially by executing one command line.

I would not even be too worrying about parallelization, as we can simply split the workload and run it on different nodes or even different clusters.  All I am trying to achieve is not having to run HyPhy thousands of times.

Many thanks in advance,



--
Lev Yampolsky

Professor
Department of Biological Sciences
East Tennessee State University
Box 70703
Johnson City TN 37614-1710
Cell 423-676-7489
Office/lab 423-439-4359
Fax        423-439-5958

**Comment by spond** [comment]
Hi Lev,

You can write [wrapper files for HyPhy](http://hyphy.org/w/index.php/HyPhy#Automating_HyPhy_analyses), or simply use a command line in POSIX-like systems (OS X and Linux command lines to pipe the input it). For example, here's a working call to BUSTED on my machine (you need to change the paths of course), which can be run in the background 


```
(echo 1; echo "/Volumes/sergei-raid/Dropbox/Swap/CD2-simple.nex"; echo "Y"; echo 1; echo d) | HYPHYMP /usr/local/lib/hyphy/TemplateBatchFiles/BUSTED.bf > /dev/null &
```

Sergei
