### ISSUE TITLE
tree based on a given alignment vs. better supported multi-gene tree

### ISSUE THREAD

**Issue by l-yampolsky** [veg/hyphy#354]
Dear colleagues,

Each time when I supply HyPhy (specifically BUSTED, aBSREL) with a tree topology, should I give it the tree that is the best tree for this particular alignment, or the tree based on many genes in whose topology we believe much stronger than in any single gene-based tree? 

(Of course the two trees are usually quite similar, but some branches are swapped here and there).

Theoretically of course it should be the better supported universal tree, as we believe that it reflects the true order of branching, plus, of course, I want to be able to identify episodes of selection to the edges present on the universal tree, but - what if the incongruence of topology creates a problem for HyPhy?

Thank you very much,

Lev Yampolsky

**Comment by spond** [comment]
Dear Lev,

My personal recommendation would be to run the methods on **both** trees for each gene. This is computationally feasible and will produce several interpretable inferences

1. You will be able to directly assess how much effect changes in the putative gene trees affect dN/dS selection inference. In my experience, methods like BUSTED should be quite robust to such perturbations. aBSREL, because it deals with branch-level inference, may be more sensitive.

2. You may be able to extract something useful from seeing **which** genes produce deviant results between trees. 

Sergei

**Comment by l-yampolsky** [comment]
Thanks! It is feasible, yes, although it is lots of computer time with a few thousand genes. 

I have another question, a rather philosophycal one. I'm not sure I fully understood it from the papers. What is the ground to conclude that the episodes of positive selection are indeed such episodes and not episodes of relaxation of stabilizing selection? Yes, it is difficult to see how selective constraint may be present before and after, but not during a particular edge of the tree. But it is easy to imagine that this edge went through a bottleneck. I noticed that in almost all cases when HyPhy is finding episodes of positive selection, dn/ds is rather modest (yes, much higher than average, mostly 0.75-1.25, not ~0.1, but also not high enough to be individually significant without taking into account types of substitutions), AND there are 2- and 3-nucleotide aa changes. I think it means two things. One is that there are plenty of false negatives - cases when there were no 2- and 3-nucleotide changes would not be picked up. On the other hand - can it possibly be used as an argument against bottleneck explanation? (Hard to see how two consecutive substitutions can occur in a small population.) Do you per chance know of any paper where this is discussed?

Thank you very much for all your help!

Lev Yampolsky

**Comment by spond** [comment]
Dear Lev,

If you were to choose one tree only, I would go with the gene tree. It is probably a better point estimate of a nuisance parameter (tree) for a selection test, so less likely to bias the results at the level of a tree. 

Regarding your philosophical question: remember that the models only produce evidence that dN/dS > 1; you can come up with numerous scenarios that would cause this, including selection, or relaxation. Incidentally we have a test for relaxation, although it is only relative (to other branches in the tree): [RELAX](http://mbe.oxfordjournals.org/content/early/2014/12/22/molbev.msu400)

I would not place too much emphasis on the **value** of dN/dS estimated by BUSTED; because the model does not adjust to the complexity of the data (a 3 rate distribution is fixed), so you might expect a strong degree of smoothing, i.e. small proportions of sites with high dN/dS will get lumped into a single rate with weakly selected sites.

I don't know of a paper that would comprehensively discuss what you are interested in. There has been some debate about whether or not implementing instantaneous multi-nucleotide substitutions is beneficial (see this work by [Goldman et al](http://mbe.oxfordjournals.org/content/24/7/1464). I think you are also talking about events at a single *branch-site* combination; both BUSTED and aBSREL derive their signal from many sites. **If** your branch is very short, then it is likely that selection (when detected) will be driven by a few multi-nucleotide substitutions; I am not sure how to interpret this. The default expectation is that you have strong selection which drives such multiple hits (as you argue).

Sergei

**Comment by l-yampolsky** [comment]
Dear Sergei,

Thank you very much for your previous advice, it has been very helpful. Now I have a question about right strategies of choosing branches as foreground. (I understand how to specify them technically, the question is more methodological). I want to test the hypothesis that there was more positive selection (per branch length unit) in internal branches than in terminal branches of a large tree. Will running BUSTED and/or aBSREL with first internal branches as the foreground, then with the terminal branches as the foreground and comparing the results give me any additional information over simply choosing All branches and then counting how many internal and terminal branches were identified by aBSREL?

Thank you very much in advance and happy Thanksgiving!

Lev Yampolsky



________________________________

**Comment by spond** [comment]
Dear Lev,

For comparing the strength of selection between sets of branches you should use use [RELAX](http://test.datamonkey.org/RELAX), described in this [MBE paper](http://mbe.oxfordjournals.org/content/32/3/820). The standalone analysis is also available in HyPhy (v 2.2.5 or later), in the `TemplateBarchFiles` directory (`RELAX.bf`).

Sergei

**Comment by l-yampolsky** [comment]
Thank you!

**Comment by l-yampolsky** [comment]
Is there a tutorial for RELAX similar to the wonderful tutorials you have for other HYPHY components, like this one -
https://github.com/veg/hyphy-tutorials/tree/master/selectionhttps://github.com/veg/hyphy-tutorials/tree/master/selectionhttps://github.com/veg/hyphy-tutorials/tree/master/selection ?

Do I run RELAX from inside HYPHY by choosing some of the options (isn't obvious which ones) or separately?

Sorry for too many questions...

________________________________

**Comment by spond** [comment]
Dear Lev,

There isn't a tutorial, but I can write one up. You run RELAX from inside HyPhy (choosing the appropriate options) and then visualize the resulting JSON file in the [web app](http://veg.github.io/hyphy-vision/relax/). The tricky part for RELAX is that you need to annotate your Newick tree in a format that HyPhy will understand. 

Take a look at https://github.com/veg/hyphy/issues/323

Sergei

**Comment by l-yampolsky** [comment]
A tutorial would be great, but I feel that I understand the batch language well enough now to figure it out, just using the examples from the paper. Once I figure out how to run it!
>choosing the appropriate options � Which ones? 10 and then 12? (12 = Test for Episodic Directional Selection on a set of labeled branches)
I don�t see RELAX anywhere in HyPhy dialogs, but at least 10-12 asks me about an annotated tree.

#323<https://github.com/veg/hyphy/issues/323> does not help me very much because it describes running it under GUI. I am planning to run it with hundreds of alignments, so I have to do it from a command line on a cluster. We have a wrapper that feeds to HYPHYMPI all necessary answers, including paths to alignments and trees and then captures results, so it�s easy to run it for multiple files. Is it possible to invoke RELAX from a command-line HYPHY?

https://github.com/veg/hyphy/issues/275<https://github.com/veg/hyphy/issues/27> helps but not quite.

Maybe I need to ask you for a good time to call you, at your convenience (as you kindly suggested to a user in #275), describe the dataset and explain what we are trying to do and you tell me how to wrap the data into RELAX?

**Comment by spond** [comment]
Dear Lev,

In the current release of HyPhy you need to specify the RELAX file directly on the command line. Here's a transcript of such a run from my machine (`/usr/local/lib/hyphy` is the default installation target for HyPhy library files on OS X and Linux)

```
Sergeis-Mac-Pro:hyphy2.2 sergei$ HYPHYMP /usr/local/lib/hyphy/TemplateBatchFiles/RELAX.bf 

Analysis Description
====================
RELAX (a random effects test of selection relaxation) uses a random
effects branch-site model framework to test whether a set of 'Test'
branches evolves under relaxed selection relative to a set of
'Reference' branches (R), as measured by the relaxation parameter (K).

Requirements
============
in-frame codon alignment and a phylogenetic tree, with at least two
groups of branches defined using the {} notation (one group can be
defined as all unlabeled branches)

Written by
==========
Sergei L Kosakovsky Pond, Ben Murrell, Steven Weaver and the UCSD viral
evolution group

Contact Information
===================
spond@ucsd.edu

Analysis Version
================
1.00



			+-------------------+
			|Choose Genetic Code|
			+-------------------+


	(1):[Universal] Universal code. (Genebank transl_table=1).
	(2):[Vertebrate mtDNA] Vertebrate mitochondrial DNA code. (Genebank transl_table=2).
	(3):[Yeast mtDNA] Yeast mitochondrial DNA code. (Genebank transl_table=3).
	(4):[Mold/Protozoan mtDNA] Mold, Protozoan and Coelenterate mitochondrial DNA and the Mycloplasma/Spiroplasma code. (Genebank transl_table=4).
	(5):[Invertebrate mtDNA] Invertebrate mitochondrial DNA code. (Genebank transl_table=5).
	(6):[Ciliate Nuclear] Ciliate, Dasycladacean and Hexamita Nuclear code. (Genebank transl_table=6).
	(7):[Echinoderm mtDNA] Echinoderm mitochondrial DNA code. (Genebank transl_table=9).
	(8):[Euplotid Nuclear] Euplotid Nuclear code. (Genebank transl_table=10).
	(9):[Alt. Yeast Nuclear] Alternative Yeast Nuclear code. (Genebank transl_table=12).
	(10):[Ascidian mtDNA] Ascidian mitochondrial DNA code. (Genebank transl_table=13).
	(11):[Flatworm mtDNA] Flatworm mitochondrial DNA code. (Genebank transl_table=14).
	(12):[Blepharisma Nuclear] Blepharisma Nuclear code. (Genebank transl_table=15).
	(13):[Chlorophycean mtDNA] Chlorophycean Mitochondrial Code (transl_table=16).
	(14):[Trematode mtDNA] Trematode Mitochondrial Code (transl_table=21).
	(15):[Scenedesmus obliquus mtDNA] Scenedesmus obliquus mitochondrial Code (transl_table=22).
	(16):[Thraustochytrium mtDNA] Thraustochytrium Mitochondrial Code (transl_table=23).

 Please choose an option (or press q to cancel selection):1

/usr/local/lib/hyphy/TemplateBatchFiles/lib2014/(null):/Volumes/sergei-raid/Coding/hyphy-python/hyphy-src/tests/hbltests/RegressionTesting/RELAX/segfault.nex 
[RELAX] Loaded an MSA with 61 sequences and 227 codons from '/Volumes/sergei-raid/Coding/hyphy-python/hyphy-src/tests/hbltests/RegressionTesting/RELAX/segfault.nex' 

/usr/local/lib/hyphy/TemplateBatchFiles/Please select a tree file for the data::/Volumes/sergei-raid/Coding/hyphy-python/hyphy-src/tests/hbltests/RegressionTesting/RELAX/segfault.nex.tre 


			+----------------------------------------------------------------+
			|Choose the set of branches to test for relaxed selection (T set)|
			+----------------------------------------------------------------+


	(1):[REFERENCE] Set REFERENCE with 111 branches
	(2):[TEST] Set TEST with 8 branches

 Please choose an option (or press q to cancel selection):2
[RELAX] Selected 8 branches as the test set: 1180,181,401,70,811,Node13,Node14,Node16 


			+-------------+
			|Analysis type|
			+-------------+


	(1):[All] [Default] Fit descriptive models AND run the relax test (4 models)
	(2):[Minimal] Run only the RELAX test (2 models)

 Please choose an option (or press q to cancel selection):2
[RELAX] Obtaining branch lengths under the GTR model 
[RELAX] Log(L) = -2734.807485473822 
[RELAX] Obtaining omega and branch length estimates under the partitioned MG94xGTR model 
[RELAX] Log(L) = -2684.886016429424 
[RELAX] Fitting the RELAX null model 
[RELAX] Log(L) = -2562.36842065176 
[RELAX] Fitting the RELAX alternative model 
[RELAX] Log(L) = -2557.29422257227. Relaxation parameter K = 2.028481525586087 
[RELAX] Likelihood ratio test for relaxation on Test branches, p = 0.001444268412365335 

```

An annotated tree looks like this:

```
((((((((((((70{TEST}:0.02525582666799697,((811{TEST}:0.03593392032616975,(181{TEST},1180{TEST}:0.09755831585996391){TEST}:0.07668300714280248){TEST}:0.002346396647307368,401{TEST}){TEST}:0.01021932063804901){REFERENCE}:0.004005210999283765,1220{REFERENCE}){REFERENCE}:0.005212822552452396,1070{REFERENCE}){REFERENCE}:0.0005966346129453164,(720{REFERENCE},750{REFERENCE}:0.001867645454551233){REFERENCE}:0.005015550584592456){REFERENCE}:0.002806121648306893,151{REFERENCE}:0.0001177047793842856){REFERENCE}:0.001480729279300059,(50{REFERENCE}:0.004498315681746378,770{REFERENCE}:0.002983003301270722){REFERENCE}:0.0005182966546421286){REFERENCE}:0.000641295415620563,1150{REFERENCE}:0.001228666049273495){REFERENCE}:0.000344546729454754,((431{REFERENCE}:0.003024283568364022,1250{REFERENCE}){REFERENCE}:0.001519327575050153,1210{REFERENCE}){REFERENCE}:0.0001251624709969322){REFERENCE}:0.001313706490918173,((((680{REFERENCE}:0.001478145056567642,941{REFERENCE}:0.001478839668611895){REFERENCE}:0.00002997720657792448,650{REFERENCE}){REFERENCE}:0.00003943566426328575,970{REFERENCE}:0.001439056698326483){REFERENCE}:0.00145126608429965,700{REFERENCE}:0.00005037611226650076){REFERENCE}:0.001423693341013216){REFERENCE}:0.00004475261782991777,1190{REFERENCE}:0.001476105010794611){REFERENCE}:0.00001402549405249946,171{REFERENCE}){REFERENCE}:0.00000744865804637397,((((((30{REFERENCE}:0.001733338357713298,(((80{REFERENCE}:0.001408436557727452,471{REFERENCE}:0.003072558609763775){REFERENCE}:0.002889299215684197,(((270{REFERENCE},501{REFERENCE}:0.001654527843233203){REFERENCE}:0.001862548977064954,460{REFERENCE}:0.002950457257983702){REFERENCE}:0.0008433044617030439,((((310{REFERENCE},330{REFERENCE}:0.003290418407017004){REFERENCE}:0.00007074862377685366,(520{REFERENCE}:0.00001185245623594032,560{REFERENCE}:0.001585125341651257){REFERENCE}:0.001541896899948917){REFERENCE}:0.00003838140014028027,290{REFERENCE}:0.001559209750176879){REFERENCE}:0.00005494532585346274,540{REFERENCE}:0.001543768294507007){REFERENCE}:0.0007674536402414774){REFERENCE}:0.007009839230503441){REFERENCE}:0.0006670105950469102,((591{REFERENCE}:0.01670199937818521,1260{REFERENCE}:0.00996517167756638){REFERENCE}:0.04270055191469195,(11{REFERENCE},(191{REFERENCE},231{REFERENCE}:0.002135918031343021){REFERENCE}:0.02817814329755263){REFERENCE}:0.0138918463616004){REFERENCE}:0.02715421622983203){REFERENCE}:0.001082219307813282){REFERENCE}:0.002603557263305219,(((20{REFERENCE}:0.009779039878517606,60{REFERENCE}:0.008412914297396813){REFERENCE}:0.00142431059461017,((((511{REFERENCE}:0.001667557437313827,1281{REFERENCE}:0.001315893420393638){REFERENCE}:0.001186014629592635,90{REFERENCE}){REFERENCE}:0.001880929710304656,(((130{REFERENCE}:0.003251264744272528,571{REFERENCE}){REFERENCE}:0.002522499027026638,(301{REFERENCE}:0.001544410718978202,281{REFERENCE}){REFERENCE}:0.001513149543248488){REFERENCE}:0.0002951470035886811,531{REFERENCE}){REFERENCE}:0.003906408355815579){REFERENCE}:0.007764133161807676,490{REFERENCE}:0.01487277528851826){REFERENCE}:0.004377481672980535){REFERENCE}:0.002259556143003712,670{REFERENCE}){REFERENCE}:0.0001454253780884787){REFERENCE}:0.001143911365117651,(161{REFERENCE}:0.00005507613804082642,1110{REFERENCE}:0.001436816065312061){REFERENCE}:0.002797858907526448){REFERENCE}:0.0001373041186922707,(1200{REFERENCE},1270{REFERENCE}:0.003018184361584017){REFERENCE}:0.001451842535978186){REFERENCE}:0.0000343395052017952,141{REFERENCE}:0.001469228687855917){REFERENCE}:0.00002164200771293629,((640{REFERENCE}:0.001513062939813579,961{REFERENCE}){REFERENCE}:0.001484324684981558,740{REFERENCE}:0.001505820979519686){REFERENCE}:0.001495073389195594){REFERENCE}:0.000008861919043435195,241{REFERENCE}:0.001492423294659721)
```

Sergei

**Comment by l-yampolsky** [comment]
Fantastic, thank you, now I understand almost everything.  Last question (last until the next one comes up): are branch lengths in the tree required?

**Comment by spond** [comment]
Dear Lev,

No, branch lengths are not required. For this analysis, they will be ignored even if supplied.

Sergei
