### ISSUE TITLE
Power to detect positive selection using aBSREL

### ISSUE THREAD

**Issue by pbrec** [veg/hyphy#356]
Dear hyphy users and developers,

In general I am interested in the molecular evolution of multi gene-families in insects. At the moment my main focus is to detect patterns of positive selection between orthologous copies of different members of the olfactory receptor gene-family. 
My dataset consist of 5 species with varying degrees of relatedness between <1 and ~ 30 mya. 
Because I had no a priori idea of gene lineages under positive selection, I initially used the branch-models as implemented in codeml to detect orthologous sets (3-5 genes) with branches evolving at different rates. Here I used LRTs comparing M0 (same dN/dS rate for all branches) with M1 (one rate estimated for each branch). For those orthologous sets that had a significantly better fit of M1, I used branch-site models to test for positive selections in lineages with an estimated dN/dS>1 by the M1. That way, I detected several genes that, at an FDR ≤0.5, were estimated to have evolved under positive selection with dN/dS>1.

After doing so, I also used aBSREL on the same dataset, curious to see if the tests would show similar results. I chose to test each branch for each orthologous set as I would do without a priori knowledge of the evolutionary histories of my different genes. However, not a single branch was estimated to evolve under positive selection. Not even when I used the less conservative FDR instead of the Holm correction as is default in aBSREL. 

When I said I had no a priori knowledge about the evolutionary history of the orthologous gene sets I was lying a bit. I know it for at least one of the genes having multiple lines of evidence strongly suggesting that the copy in one of my 5 species evolved under strong positive selection. The original p-value of the aBSREL analysis is significant, but not so after correction for multiple testing.

Now I am wondering about the power aBSREL has in general/ on my dataset. From your paper it seemed to have really great power but my analyses suggest a false negative rate to some degree. Do you think I am using it the wrong way? Or is my dataset somehow not suitable?

I would appreciate any thoughts, help, criticism, discussion.

All the best,

Philipp

**Comment by pbrec** [comment]
Dear Sergei,

Your comments are very helpful. I appreciate that you took your time to write such a detailed response.

Thanks,
Philipp

**Comment by spond** [comment]
Dear Philipp,

No problem. I hope it makes sense. Out of curiosity: what is the omega distribution inferred by aBSREL for the branches that you expected to be under selection?

Sergei

**Comment by pbrec** [comment]
Hi Sergei,

Sorry for the delay. omega on branches I expected to be under selection ranged from 3 to 10.
When I test the branches that I expect to be under selection due to former analyses etc. Two of them actually are estimated to be significant. I am working on extending the dataset by a few species and hope it will increase the power of these analyses.

Philipp

**Comment by spond** [comment]
Hi Philipp,

Please note that aBSREL is **not** expected to gain power from adding more sequences: this is true of any branch level test, because the signal derives from a single branch. Other branches merely provide the background. 

Sergei

**Comment by pbrec** [comment]
Do you have a recommendation on how to analyze this dataset in order to detect genes under less strong positive selection in some lineages as opposed to others?

**Comment by spond** [comment]
Hi Philipp,

Yes, use [RELAX](http://test.datamonkey.org/RELAX), described in this [MBE paper](http://mbe.oxfordjournals.org/content/32/3/820). The standalone analysis is also available in HyPhy (v 2.2.5 or later), in the `TemplateBarchFiles` directory (`RELAX.bf`).

Sergei

**Comment by pbrec** [comment]
Hi Sergei,

Thanks for the suggestion and help. I just started getting into the extensive HyPhy-related literature and didn't come across RELAX, yet. You guys seem to do really great work.

Cheers,
Philipp
