### ISSUE TITLE
the HyPhy webserver at DataMonkey is down

### ISSUE THREAD

**Issue by jbloom** [veg/hyphy#358]
Jobs appear to have been sitting for over a day now.

**Comment by stevenweaver** [comment]
Hello, 

A new version of HyPhy was installed on datamonkey last week, and an introduced bug caused the MEME queue to stop progressing. 

I've reverted the version of HyPhy that the MEME analysis is using to a prior version, and the queue should progress as intended. 

Regards,
Steven
