### ISSUE TITLE
BranchsiteREL error when using Hyphy-CLI

### ISSUE THREAD

**Issue by AICS85** [veg/hyphy#360]
Hello,

I'm interested in using Hyphy via command line as part of a pipeline, but I have encountered an error when analyzing my aligned sequences. The error occurs at the beginning of the [Phase 1] of the analysis and it reads as follows:

Error:
Cannot reuse the filter 'dsf' because it is already being used by likelihood function 'base_LF', and the two likelihood functions impose different leaf-to-sequence mapping. Create a copy the filter and pass it to the second likelihood function to resolve this issue. 

This error does not show when I run the analysis using the Hyphy console on my desktop or in the Datamonkey server. 

I would like to know if there is any way to fix this in the command line? And also, how can I make the changes suggested by the error message and why they do not appear outside the command line? Any help will be appreciated.

Thanks,
A. Castillo
Arizona State University

**Comment by spond** [comment]
Dear @AICS85 ,

Please try checking out and building the current working version of HyPhy to see if the error goes away. What you see is most likely due to the fact that the HyPhy version and the BranchSiteREL analysis version have somehow fallen out of sync (i.e. I introduced the error into one of the releases/commits:)

```
$git clone git@github.com:veg/hyphy.git
$git checkout v2.2.6-working
$cmake ./
$make MP2
$[sudo] make install
```

Sergei

**Comment by AICS85** [comment]
Thanks for your response Dr. Pond,

I am not compiling the program with the source code but I am using the HyPhy-CLI2.2.6.exe version available in GitHub (https://github.com/veg/hyphy/releases), which I believe is the latest available. Should I introduce this correction into the source code provided on the same page or is there a newer command line version were this bug has been fixed?

Again, thank you for your help.

A. Castillo.
Arizona State University
