### ISSUE TITLE
RELAX after gene duplication

### ISSUE THREAD

**Issue by anne-maria** [veg/hyphy#361]
Hello everyone,

I tried out RELAX on my data which contain paralogous sequences. I wanted to know how selection pressure changed after a gene duplication event and tested the branches leading to each paralog against each other. And what confuses me now is that RELAX finds significant selection relaxation in both branches. How can this be when the background is the other "relaxed" branch... 
Is this possible and I just can't make sense of it or is it more likely I made a mistake when performing the analyses?
I would be grateful for any suggestions.

Anne-Maria

**Comment by spond** [comment]
Dear @anne-maria,

Would you be able to provide the JSON file output by RELAX to me for inspection? 

Sergei

**Comment by anne-maria** [comment]
Dear Sergei,

yes of course! Here are the two files where I alternately tested the two branches against each other:

[AW151120relax-e-f.nex.RELAX-json.txt](https://github.com/veg/hyphy/files/48295/AW151120relax-e-f.nex.RELAX-json.txt)
[AW151120relax-f-e.nex.RELAX-json.txt](https://github.com/veg/hyphy/files/48296/AW151120relax-f-e.nex.RELAX-json.txt)

Let me know if you need anything else,
Anne-Maria

**Comment by anne-maria** [comment]
I have an additional question:
From what I understood, performing RELAX with or without calculation of the descriptive models shouldn't affect the outcome of the hypothesis test.
Please correct me if I am wrong.

**Comment by anne-maria** [comment]
So, I tested both: "all" and "minimal" calculations on the same data set and I do get different results. Could someone explain to me where the difference comes from? I couldn't find it in your RELAX paper (or I just didn't understand). I would like to make an informed decision on which calculations to perform.  For some branches I tested it was either a significant result or not, depending on the calculations (all or minimal) I choose. 
Thanks,
Anne-Maria

**Comment by spond** [comment]
Hi @anne-maria, 

The **all** option simply runs more tests, but the key RELAX test itself should not be affected. Can you paste the console output where such differences occur?

Sergei

**Comment by anne-maria** [comment]
Hi Sergei,

here is such an example


**ALL**
================
Analysis Version

1.00

[RELAX] Loaded an MSA with 23 sequences and 387 codons from 'D:\Dokumente_2014\AW151120\RELAX\x-x wdh\AW151120relax-x-x.nex' 


A tree was found in the data file:
(07_DHS1BRA,((NL130802_H,(((21_LOLIUMD,LTEM_DHS3_),(10_FESTUCA,19_LOLIUMD)),HMHSS_PROO)),TRAES_5DL_){1},(((((((20_LOLIUMD,11_FESTUCA),LTEM_DHS2_),LMDHS2_PRO),FRDHS_AW14),NL130802_D),(HL_DHS_AW1,HM_DHS_AW1)),((09_DHS_HOR,13_HORDEUM),(((T_URARTU_D,AEGILOPSDH),TRAES_5BL_),(SCAFFOLD85,TRAES_3B_5)))){2})

Would you like to use it:(Y/N)?y


[RELAX] Selected 1 branches as the test set: Node2 
[RELAX] Obtaining branch lengths under the GTR model 
[RELAX] Log(L) = -6107.977016603408 
[RELAX] Obtaining  omega and branch length estimates under the local MG94xGTR model 
[RELAX] Log(L) = -5722.191194280439 
[RELAX] Obtaining omega and branch length estimates under the partitioned MG94xGTR model 
[RELAX] Log(L) = -5762.118377430323 
[RELAX] Two-stage fit of the general descriptive model (separate relaxation parameter for each branch) 
[RELAX] Log(L) = -5686.725499263605 
[RELAX] Fitting the RELAX null model 
[RELAX] Log(L) = -5687.644173407765 
[RELAX] Fitting the RELAX alternative model 
[RELAX] Log(L) = -5685.978002611482. Relaxation parameter K = 6.400984294624402 
[RELAX] Likelihood ratio test for relaxation on Test branches, p = 0.06793009833257579 
[RELAX] Fitting the RELAX partitioned exploratory model 
[RELAX] Log(L) = -5685.821134103297 

**Minimal**
================
Analysis Version

1.00

[RELAX] Loaded an MSA with 23 sequences and 387 codons from 'D:\Dokumente_2014\AW151120\RELAX\x-x wdh2\AW151120relax-x-x.nex' 


A tree was found in the data file:
(07_DHS1BRA,((NL130802_H,(((21_LOLIUMD,LTEM_DHS3_),(10_FESTUCA,19_LOLIUMD)),HMHSS_PROO)),TRAES_5DL_){1},(((((((20_LOLIUMD,11_FESTUCA),LTEM_DHS2_),LMDHS2_PRO),FRDHS_AW14),NL130802_D),(HL_DHS_AW1,HM_DHS_AW1)),((09_DHS_HOR,13_HORDEUM),(((T_URARTU_D,AEGILOPSDH),TRAES_5BL_),(SCAFFOLD85,TRAES_3B_5)))){2})

Would you like to use it:(Y/N)?y


[RELAX] Selected 1 branches as the test set: Node2 
[RELAX] Obtaining branch lengths under the GTR model 
[RELAX] Log(L) = -6107.977016603408 
[RELAX] Obtaining omega and branch length estimates under the partitioned MG94xGTR model 
[RELAX] Log(L) = -5762.118276137688 
[RELAX] Fitting the RELAX null model 
[RELAX] Log(L) = -5688.423545728567 
[RELAX] Fitting the RELAX alternative model 
[RELAX] Log(L) = -5683.861785971867. Relaxation parameter K = 9.712076193696486 
[RELAX] Likelihood ratio test for relaxation on Test branches, p = 0.002523440156259937 


Thank you for looking into it!
Anne-Maria

**Comment by spond** [comment]
Hi @anne-maria,

This looks like a convergence problem, sadly. When you fit the general exploratory model, subsequent model fits will begin with different initial values. Because the model is fairly complicated, different starting points can determine where the optimization converges. You should see less of an effect if you choose branch sets with more than one branch it them, but in the meantime, you should use the result from the full model fit, because (at least for the alternative model), the likelihood is better. I'll add it to my list of things to do to check for convergence in version 1.1 of the analysis.

Sergei

**Comment by anne-maria** [comment]
Hi Sergei,
thank you so much for your very helpful input!
Anne-Maria

**Comment by anne-maria** [comment]
Hi,
I have another quick question regarding the varying likelihood values. Would it be correct if performed the full and minimal fit and just took the best likelihood for each model and compared those to each other?
Cheers,
Anne-Maria
