### ISSUE TITLE
"Additional Information" column missing on MEME results

### ISSUE THREAD

**Issue by jwconnolly** [veg/hyphy#362]
Hi Dr. Pond, I was wondering why the additional information column is not showing up in my MEME results page (http://www.datamonkey.org/spool/upload.736754144824341.1_meme.php). I ran this test yesterday with one less seq. and it showed up but am not having any luck with my new dataset. This has also happened with another dataset that I have.

**Comment by spond** [comment]
Hi @jwconnolly,

If I recall correctly, the "additional information" column in MEME will appear only after you've run SLAC on the same data, i.e. run SLAC first, then MEME. This is because SLAC generates ancestral sequences and maps substitutions to branches.  

Sergei

**Comment by jwconnolly** [comment]
So essentially the mapped substitutions allow one to say 'at X codon, this taxa underwent this substitution from the ancestral gene'?

**Comment by spond** [comment]
Hi @jwconnolly,

The SLAC analysis is a purely __descriptive__ tool, so you can see where the most likely (in some sense) locations for substitutions at a site are. There is simply no information in the alignment to pinpoint exactly at which branch selection took place, but rather that somewhere on the tree, enough branches experienced episodic selection. MEME generates very rough estimates of where it thinks the substitutions that mattered for selection took place, but they are imprecise and should be taken as such. 

Sergei

**Comment by jwconnolly** [comment]
So would using bsREL in conjunction with MEME show which codons and which lineages were undergoing diversifying selection? Or are the methods to incompatible to combine those results into a concise conclusion?

**Comment by stevenweaver** [comment]
Because the initial issue has been resolved, I am going to go ahead and close this ticket. Please feel free to open an additional ticket if there are unresolved issues you would like to address.

Best,
Steven
