### ISSUE TITLE
BranchSiteREL wrapper error

### ISSUE THREAD

**Issue by ltornabene** [veg/hyphy#363]
I'm trying to run run BranchSiteREL.bh on a series of fasta files with trees embedded.  I am getting an error. Here is my wrapper, which mirrors almost exactly what Sergei wrote up with issue #186 , except I have an extra inputRedirct line, as his wrapper passed the fasta file when the analysis asked if I wanted to allow branch-site variation in synonymous rates.  

Here is my wrapper
------------------
fileToExe = HYPHY_LIB_DIRECTORY + "TemplateBatchFiles" + DIRECTORY_SEPARATOR + "BranchSiteREL.bf";

/* a list of file paths */
SetDialogPrompt ( "Provide a list of files to process:" );
fscanf ( PROMPT_FOR_FILE, "Lines", _filesToProcessUsingBSREL );

fprintf (stdout, "[READ ", Columns (_filesToProcessUsingBSREL), " file path lines]\n");

inputRedirect = {};
inputRedirect["01"]="Universal";
inputRedirect["02"]="Yes"; 
inputRedirect["03"]="No";
inputRedirect["05"]="Y";
inputRedirect["06"]="All";
inputRedirect["07"]="";

for ( _fileLine = 0; _fileLine < Columns ( _filesToProcessUsingBSREL ); _fileLine += 1 ) {

  inputRedirect [ "04" ]    = _filesToProcessUsingBSREL[ _fileLine ];
  inputRedirect [ "08" ]    = inputRedirect [ "04" ]+".bs-rel";
  ExecuteAFile ( fileToExe, inputRedirect );
}

----
Here is the error: 

_____________
Error:
Could not find source dataset file:PROMPT_FOR_FILE Path stack: {Macintosh_HD:Users:luketornabene:Desktop:,Macintosh_HD:Applications:HyPhy.app:Contents:Resources:HBL:TemplateBatchFiles:}

Function call stack
1 : Read Data Set ds from file PROMPT_FOR_FILE
	Standard input redirect:
		06 : All
		07 : 
		08 : /Users/luketornabene/Desktop/hyphyfastas/rag1.fasta.bs-rel
		-------
2 : ExecuteAFile from file fileToExe using basepath Macintosh_HD:Users:luketornabene:Desktop:. reading input from inputRedirect
{"01":"Universal",
"02":"Yes",
"03":"No",
"05":"Y",
"06":"All",
"07":"",
"04":"/Users/luketornabene/Desktop/hyphyfastas/rag1.fasta",
"08":"/Users/luketornabene/Desktop/hyphyfastas/rag1.fasta.bs-rel"}

Any ideas what is causing this?

**Comment by spond** [comment]
Hi @ltornabene,

Hmm, based on the error message, HyPhy is not finding your alignment file (`/Users/luketornabene/Desktop/hyphyfastas/rag1.fasta`) Does the file exist? 

You are running the wrapper through the GUI on OS X, right?

Sergei

**Comment by ltornabene** [comment]
Hi Sergei
Yes, I was initially running on the GUI on OSX.  I switched to the command line version and after a few hours of trouble-shooting yesterday, I figured out that it was a whitespace issue.  A single hidden “ “ of white space either at the end of the fasta file’s directory, or the ‘path list’ file directory was causing HyPhy to not find what it was looking for.  I was able to execute it fine now from the command line. I posted about this on the discussion board, so that can probably be closed now.

Thanks for following up!

Luke

**Comment by ltornabene** [comment]
Sorry to bug you again Sergei.

Now I’m having an issue with BUSTED.  I have tried running the analysis on the command line, on datamonkey, using the attached annotated fasta+newick file, and the universal genetic code, specifying the Foreground branches.  The analysis never gets past the "Fitting the unconstrained branch-site model” stage.  It ran for 24 hours on my laptop and never progressed, and I figured there might be a problem with the likelihood function.   The same analysis is on hour 2 on datamonkey right now.

I switched to the GUI today so I could monitor the progress and likelihood score there, and after about an hour I got the follow error message.


Error:

Incompatible dimensions when trying to add or subtract matrices: first argument was a 257x61 matrix and the second was a 61x61 matrix.


Function call stack

1 : Optimize storing into, busted.MLE_HA, the following likelihood function:busted.LF ;

Do you know the source of this, and might this be why my analysis will not finish on the command-line version?

Luke
