### ISSUE TITLE
BUSTED likelihood function error

### ISSUE THREAD

**Issue by ltornabene** [veg/hyphy#365]
Sorry to bug you again Sergei et al.

Now I’m having an issue with BUSTED.  I have tried running my analysis on the command line and on datamonkey, using an annotated fasta+newick file, and the universal genetic code, specifying the Foreground branches.  Its a modestly sized dataset - 53 sequence, 416 codons. The analysis never gets past the "Fitting the unconstrained branch-site model” stage.  It ran for 24 hours on my Macbook and never progressed past the first model fit, and I figured there might be a problem with the likelihood function.  The same analysis is on hour 2 on datamonkey right now.

I switched to the GUI today so I could monitor the progress and likelihood score there, and after about an hour I got the follow error message.

Error:

Incompatible dimensions when trying to add or subtract matrices: first argument was a 257x61 matrix and the second was a 61x61 matrix.

Function call stack

1 : Optimize storing into, busted.MLE_HA, the following likelihood function:busted.LF ;

Do you know the source of this, and might this be why my analysis will not finish on the command-line version?  Let me know if you want me to email the fasta+tree file.

**Comment by stevenweaver** [comment]
Hi @ltornabene,

May I know which version of HyPhy you are using?

The datamonkey site uses version 2.2.6, and my logs indicate that all BUSTED jobs submitted in the past 24 hours have completed successfully. 

Can you please confirm that the datamonkey job completed?

Thanks,
Steven

**Comment by ltornabene** [comment]
Hi Steven

Yes, I confirm that the Datamonkey job finished. The others running locally on the command line (still running) and GUI (error message) have not.   The command line version is 2.2.6 and the GUI was the most recent one on the download page, vers.  2.2.4.    Also, is there a way to download the .json file from Datamonkey analyses, in addition to just viewing them online, so I can parse information from it using a custom script?

Luke

**Comment by stevenweaver** [comment]
Hi Luke,
Yes, you can retrieve the json by appending `/results` to end of the url.

Example: 
`http://test.datamonkey.org/busted/<id>/results`

As far as the local versions, I will see if I can reproduce the error.

Thanks,
Steven

**Comment by stevenweaver** [comment]
Hello Luke, 

As an update BUSTED looks to require 2.2.6. I've created a new issue, #399, that suggests we should add a new GUI release for 2.2.6. 

Best,
Steven
