### ISSUE TITLE
Running MEDS on the server

### ISSUE THREAD

**Issue by TashyK** [veg/hyphy#368]
Hello

I was wondering if someone could help with a submission script for MEDS to be run on the server. I ran FUBAR a few months ago and the input was something like this:

options = {};
options["00"] = "Universal";
options["01"] = "1";
options["02"] = "/scratch/akoch/NEWDATA/ResequencingRun/FUBAR/Comp/output/E_FUBARComplementAlign_renameRC_final.fas";
options["03"] = "/scratch/akoch/NEWDATA/ResequencingRun/FUBAR/Comp/output/E_FUBARComplementAlign_renameRC_final.nwk";
options["04"] = "20";
options["05"] = "10";
options["06"] = "12500000";
options["07"] = "500000";
options["08"] = "300";
options["09"] = "0.5";
ExecuteAFile("/scratch/akoch/NEWDATA/ResequencingRun/FUBAR/Comp/bfiles/FUBAR.bf", options);

I was wondering if someone could provide me with something similar for MEDS?

Thanks so much.
Tasha

**Comment by stevenweaver** [comment]
Hello, 

Each analysis should follow the same procedure. My recommendation would be to run the analysis manually, take note of each prompt, and then adjust your options in your batch file accordingly. 

Sample fasta and nwk files to be used with MEDS can be found here : http://hyphy.org/w/index.php/MEDS

In MEDS' case, the options would look something like this:

```
options = {};
options["00"] = "/path/to/MEDSdemo.fas";
options["01"] = "/path/to/MEDSdemo.nwk";
options["02"] = "/path/to/MEDSdemo.csv"; // Output file
options["03"] = "Universal";
ExecuteAFile("/scratch/akoch/NEWDATA/ResequencingRun/FUBAR/Comp/bfiles/MEDS.bf", options);
```

Best,
Steven
