### ISSUE TITLE
BUSTED issue opening results file 

### ISSUE THREAD

**Issue by sonnynguyen** [veg/hyphy#371]
Seems like the results are there but unable to be opened? Thanks! 

http://test.datamonkey.org/busted/568445e93b68f74f3bafd8ce

**Comment by stevenweaver** [comment]
Hello @sonnynguyen,

Sorry I missed this. We were in the middle of moving operations during the new year. 
Can you please try your analysis again and reopen this issue if the problem is persistent?

Thanks,
Steven
