### ISSUE TITLE
bsREL questions

### ISSUE THREAD

**Issue by phickner** [veg/hyphy#372]
When I run the bsREL analysis on the datamonkey website some of my analyses show lineages with corrected pvalues <0.05, but when I run the bsREL test using hyphy and the adaptive bsREL, there are no corrected pvalues <1. I am using the same user tree and data set. My objective is to see if any of my proteins of interest show signs of positive selection at lineage (species) of interest. Any suggestions on the analyses I should perform? Right now I am using only bsREL.

**Comment by spond** [comment]
Hi @phickner,

Can you provide an example (e.g. a link to the analysis URL)? The current version of datamonkey implements a different version of BS-REL than the current HyPhy version (aBSREL), but there should be some correlation at least between uncorrected p-values.

Sergei

**Comment by phickner** [comment]
I included links to bsREL and aBSREL analyses on datamonky for two genes
(bsREL analyses are still in the queue). Both illustrate considerably
different results. I'm sure it is something I am doing wrong, probably my
input file because it says no branches were tested when I use the aBSREL
analysis (I used the same input file for both tests). I only included the
datamonkey web server analyses because aBSREL on HyPhy shows similar
results. These are homologous genes in 9 different drosophilids in the D.
melanogaster group.

*bsREL on datamonkey (Gr59d):*

http://www.datamonkey.org/cgi-bin/datamonkey/mpiJobStatus.pl?fileName=upload.649085850230901.1&task=bsr



*aBSREL on datamonkey (Gr59d): *

http://test.datamonkey.org/absrel/568fc71cf5deb3ce7a5533ef



*bsREL on datamonkey (Orco):*

http://www.datamonkey.org/cgi-bin/datamonkey/mpiJobStatus.pl?fileName=upload.809959206332740.1&task=bsr


*aBSREL on datamonkey (Orco): *

http://test.datamonkey.org/absrel/568fcb5af5deb3ce7a5533fb



Thank you,
Paul

On Wed, Jan 6, 2016 at 9:53 PM, Sergei Pond <notifications@github.com>
wrote:

> Hi @phickner <https://github.com/phickner>,
>
> Can you provide an example (e.g. a link to the analysis URL)? The current
> version of datamonkey implements a different version of BS-REL than the
> current HyPhy version (aBSREL), but there should be some correlation at
> least between uncorrected p-values.
>
> Sergei
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/veg/hyphy/issues/372#issuecomment-169533084>.
>



-- 
Paul V. Hickner, Ph.D.
Postdoctoral Research Associate
Department of Biological Sciences
319 Galvin Life Sciences
University of Notre Dame
Notre Dame, IN 46556
(574) 631-7860

**Comment by stevenweaver** [comment]
I believe this issue has been addressed in #391.
