### ISSUE TITLE
aBSREL results

### ISSUE THREAD

**Issue by phickner** [veg/hyphy#373]
How can I correlate the node in the results file with the node on my tree? It seems the annotated tree file from the results just has labels for the leafs. Example below. 

Summary of branches under episodic selection (15 were tested, of which 2 required optimizations) :
	Node11 p = 0.02382141489823297

**Comment by spond** [comment]
Dear @phickner,

HyPhy automatically names internal nodes in the tree (`NodeXX`), unless the tree has explicit names, like in `(a,b)MRCA_ab`. The easiest way to find what `Node11` in your example refers to is to use the web application to **view** the tree. See this [tutorial](https://github.com/veg/hyphy-tutorials/tree/master/selection#use-absrel-to-find-lineages-which-have-experienced-episodic-diversification).

Sergei
