### ISSUE TITLE
Understanding and visualising Data Monkey DEPS Results

### ISSUE THREAD

**Issue by andrewstephenmason** [veg/hyphy#375]
Hi all,
I recently submitted and got results for a DEPS job through DataMonkey based on an alignment of 33 proteins using the WAG model. The analysis ran to completion but now I don't really know how to interpret the results. I couldn't find any clues on the hyphy wiki so could someone give me a step by step, or a link to one?
Apologies if I'm just being a bit dense!
Thanks in advance,
Andrew

**Comment by stevenweaver** [comment]
Hello, 

Is there a specific question you had in mind with the DEPS analysis?
A good place to start would be with the corresponding  [MBE paper](http://mbe.oxfordjournals.org/content/25/9/1809.short). 

Best,
Steven
