### ISSUE TITLE
running hyphy with MPI in linux

### ISSUE THREAD

**Issue by sadiexiaoyu** [veg/hyphy#376]
Dear All,
I am running hyphy in linux with MPI environment, to do GARD data analysis. The MPI is running, however, when I load the file and try to run GARD.bf, I got error message. I could not figure out what is wrong... could anyone help me? Thanks!

Sadiexiaoyu

And the MPI  running seems ok, like this:
mpirun -np 24  /usr/local/bin/HYPHYMPI
/HYPHY 2.220160120beta(MPI) for Linux on x86_64\       
***************** TYPES OF STANDARD ANALYSES *****************

	(1) Basic Analyses
	(2) Codon Selection Analyses
	(3) Compartmentalization
	(4) Data File Tools
	(5) Miscellaneous
	(6) Model Comparison
	(7) Kernel Analysis Tools
	(8) Molecular Clock
	(9) Phylogeny Reconstruction
	(10) Positive Selection
	(11) Recombination
	(12) Selection/Recombination
	(13) Relative Rate
	(14) Relative Ratio
	(15) Substitution Rates
11
 Please select type of analyses you want to list (or press ENTER to process custom batch file):

 ***************** FILES IN 'Recombination' ***************** 

	(1) Screen an alignment using GARD (requires an MPI environment).
	(2) Process GARD results.
	(3) A Likelihood Ratio Test to detect conflicting phylogenetic signal Huelsenbeck and Bull, 1996. [Contributed by Olivier Fedrigo].
	(4) Search an alignment for a single breakpoint.
	(5) Plot genetic distances (similarity) of one sequence against all others in an alignment, using a sliding window. Optionally, determine NJ-based clustering and bootstrap support in every window. This is a HyPhy adaptation of the excellent (but Windows only tool) SimPlot (and/or VarPlot) written by Stuart Ray (http://sray.med.som.jhmi.edu/SCRoftware/simplot/)

1
 Please select the file you want to use (or press ENTER to return to the list of analysis types):Initialized GARD on 4 MPI nodes.
Population size is 6 models
/downloads/seq.fas
/usr/local/lib/hyphy/TemplateBatchFiles/Nucleotide file to screen::
GARD.bf
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD 
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
/usr/local/lib/hyphy/TemplateBatchFiles/Nucleotide file to screen::Error:

Master node received an error:The format of the sequence file has not been recognized and may be invalid

Function call stack
1 : Read Data Set ds from file PROMPT_FOR_FILE
-------
 1 more process has sent help message help-mpi-api.txt / mpi-abort
 Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

2 more processes have sent help message help-mpi-api.txt / mpi-abort

**Comment by crushwx** [comment]
Hello @sadiexiaoyu!
Could you please tell me how to resolve this issue and analyze the gard's output results?
Best wishes!
wang
