### ISSUE TITLE
Can hyphy be used for detecting gene duplication

### ISSUE THREAD

**Issue by sadiexiaoyu** [veg/hyphy#377]
Hello, all,
I would like to ask can hyphy be used for detect hypothesis of gene duplication like PAML? Because when I read the manual of hyphy, it seems that it only consider about orthologous gene, then how about duplicated genes? Or even gene family? Can I test the alignment of the whole sequences from the whole gene family using Hyphy, such as GARD, MEME, or aBSREL?

Sadiexiaoyu

**Comment by stevenweaver** [comment]
Covered in #379
