### ISSUE TITLE
fitting a mutilple tree, multiple partition model, error message for hyphy GARD linux running 

### ISSUE THREAD

**Issue by sadiexiaoyu** [veg/hyphy#378]
Dear All,
I am running GARDprocessor now, but when run to Fitting a multiple tree, multiple partition model, the running is stopped with error : needs 1 arguments; 0 were supplied. Then I checked back my output_final and output_splits files, I found that there is only one tree in the GARD output file. Does that mean my data has no partition to be found, so that there is no recombination? 

Sadiexiaoyu

**Comment by spond** [comment]
Dear @sadiexiaoyu ,

Could you please e-mail me the files you are submitting to `GARDProcessor.bf` so that I can confirm the error and fix it? 

If you have a single tree in the partition file, then, indeed, there is no evidence of recombination. 

Sergei

**Comment by sadiexiaoyu** [comment]
Hi, Sergei,

Thanks! I figure it out! Yes, it is because there is no partition of my data!

And could you help me deal with another question?
I used PAML branch site model to test hypothesis of gene duplication, and I get very good significant results which fit my hypothesis very well. Then I would like to use aBSREL in Hyphy to see how the selection looks like if I do not give a priori hypothesis. However, the aBSREL result shows that 0 branches shows positive selection!

Why the results are so different?!
