### ISSUE TITLE
Applicability of BS-REL

### ISSUE THREAD

**Issue by Asutu** [veg/hyphy#380]
Hello,

I'm trying to apply the Branch-Site REL model (aBS-REL) in order to test the hypothesis of positive/diversifying selection acting in a set of lineages for one gene. I have data for several species but the interest is actually more in two populations of the same species (although I think the aBS-REL is still the best approach here, but I'm open to suggestions since I'm relatively newbie in selection analyses). Since this touches the bounds of population diversity, I tried to correct for eventual slightly deleterious mutations by choosing only the most common haplotype in each population (1 sequence per haplotype). The idea would be that these haplotypes would not carry singletons or doubletons (seen in the population), that could simply be the result of some slightly deleterious mutations segregating within each pop. These two haplotypes have 6 mutations separating them. In the end, the phylogeny has a couple of outgroup sequences plus the two sister haplotypes.
After running aBS-REL through the command line version of HYPHY, there was a quite interesting result. One of the population haplotype branch, say H1, had a "near" significant corrected p-value (~0.54) in a very small fraction of the sequence (1 or 2 codons). omega2 was above 200. I'm not really worried about the "near" here, but I would say it might have something to do with the very small fraction of sites? Well, this observation would fit very nicely with the history for this haplotype.
The problem is that if I remove the other haplotype (H2) from the analyses, there is no signal of diversifying selection on H1, with the result of a single omega1 value of 0.2, which means the test is not being robust to variations in the phylogeny. Why might this be happening? Shouldn't I expect to see at least some omega2 value, even if lower or much more non-significant?
As a note, the convergence failures parameter is always 0 in both runs.

The point is that I'm not sure if these selection methods are applicable to the framework I'm trying to test... Are branch-site selection methods still good to use with this type of data, where intra-specific variation is in some way included in the analyses? I would be grateful to have some insights about this because it seems there aren't any examples in the literature with cases similar to this one.

Thanks.

**Comment by spond** [comment]
Dear @Asutu,

There are several points I'd like to make in response to your questions

1. `Covnergence failures` message implies that you may be using an outdated version of BS-REL. What menu choices do you make during the analysis? 

2. dN/dS estimates are generally difficult to interpret within populations: depending on the structure of the population and intra-population dynamics, it may be possible to obtain dN/dS estimates that are not reflective of selection. Your heurstic is sensible; another one I use from time to time (and so do others) is to restrict your analysis to internal branches only, so "deleterious" mutations not yet filtered out by selection are not going to inflate dN/dS estimates.

3. Where in the tree is the significant branch? By removing H2 from the analysis, you could, for example, remove the `contrast` that is needed to realize that H1 is evolving away from something. In the extreme, if you have only H1-like sequences in the tree, you will never find any signal of selection. An easy way to see this is to run your data (with and without H2) through SLAC on data monkey and see which substitutions get mapped to the branch leading to H1.

Sergei

**Comment by Asutu** [comment]
Hi Sergei,

many thanks for your insights on this. They were really useful and have helped me a lot understanding what might be going on.
> Covnergence failures message implies that you may be using an outdated version of BS-REL. What menu choices do you make during the analysis?
> 
I’m following the HyPhy tutorial for the aBS-REL. The choices are:
(10) Positive Selection
(1) Use the random effects branch-site model (2010) to find lineages subject to episodic selection.
(1):[Universal] Universal code. (Genebank transl_table=1).
(1):[Yes] [Strongly recommended] Automatically decide on appropriate model complexity among branches
(2):[No] [Default] Alpha varies from branch to branch, while omega varies among branch-site combinations
./alignment.fas
./tree.txt
(2):[All] Test all branches
d

The “Convergence failures” message I was referring to is in the output in .json file. The last lines are below:

"Node3":{"LRT":0.764718087415531,
"uncorrected p":0.2810462215929258,
"tested":1,
"p":1}},
"timers":{"Complexity analysis":301,
"Testing":216,
"overall":687},
"version":"Adaptive BS-REL",
"PMID":"YYY",
"convergence failures":0}

I tried to follow your suggestion and piped two analyses (with H2 and without it) through SLAC in Datamonkey. When H2 was included, SLAC mapped 2:2 (Syn:NonSyn) substitutions to the H1 branch, 1:1 to the H2 branch and 14:8 to the interior branch of both haplotypes. Without H2, there were 16:10 substitutions mapped to the H1 branch. This looks like exactly the sum of H1 and interior branches above, so it seems to indicate that all mutations are being mapped, independently of the presence of H2.

I was wondering if it would be worth to run an IFEL with only the population data. Is it possible to run IFEL through the command line version of HYPHY? I loaded one dataset in Datamonkey but is running for more than 22h without any output and is already cluttering a huge queue (sorry… I was trying to kill the run but couldn’t find any way to do it).

Many thanks.

**Comment by spond** [comment]
Dear @Asutu ,

To be honest, I am still a bit confused about the results you are getting. Could you e-mail me the screenshots (or JSON files) of your analysis with and without H2? 

I would run BUSTED restricted only to interior branches (like we did [for HIV](http://www.nature.com/nature/journal/vaop/ncurrent/full/nature16933.html)), if you want to test for SOME population level selection.

Sergei

**Comment by Asutu** [comment]
Hi Sergei,

sure. Maybe I'm doing something wrong?
Please find attached the two .json files for aBS-REL, with H2 (bsrel.A02) and without (bsrel.A03). I had to zip them because github does not support .json extension.
SLAC analyses were ran through datamonkey so I don't have JSON files for these.

Thanks.

[bsrel.results.zip](https://github.com/veg/hyphy/files/108008/bsrel.results.zip)

**Comment by spond** [comment]
Dear @Asutu,

Sorry this fell of my radar. Without H2 to **split off* the differences attributable to H1 from those shared by the ancestral branch, you **average** the signal from H1 **and** the ancestral branch, which swamps out the signal of selection from H1. When you add H2, some non-synonymous changes are now pushed onto the short H1 branch, and the ancestral branch absorbs the rest of "conserved" (&omega; = 0.2) evolution.

This looks like perfectly sensible behavior to me. Now, if our models could allow process heterogeneity along a single branch (which they don't, and almost no other models out there do, with the exception of co-varion models which have their own issues), you might be able to see evidence of selection without H2 in the mix.

Sergei
