### ISSUE TITLE
Unable to upload tree from file

### ISSUE THREAD

**Issue by jamercadodiaz** [veg/hyphy#381]
The issue comes up when trying to upload a tree topology for a partition. When I go to the drop-down menu in "Tree topology", I select the option "Read tree from file" and navigate through the directory to select the tree I want to upload (newick format in this case). When selecting the tree, a new tree window opens showing my tree, however it does not attach the tree to the partition. I also tried opening the tree files first and then doing the partition with my data file, but this doesn't work either. The tree just doesn't show up as an option in "Tree Topology".

My computer is running on Windows 7 Professional, 64 bit OS. The installed HyPhy version is 2.2.4. 

Attached is a sample of the tree file (Dro_Amy_independent_hyp.txt) and the data (alignment file).

Any help is appreciated

Joel

[Dro_Amy_independent_hyp.txt](https://github.com/veg/hyphy/files/106809/Dro_Amy_independent_hyp.txt)

[Dro_Amy_all_alignment.zip](https://github.com/veg/hyphy/files/106810/Dro_Amy_all_alignment.zip)

**Comment by spond** [comment]
Dear @jamercadodiaz,

It seems that your alignment has 17 sequences and the tree only has 16 leaves. In order to assign a topology to an alignment, HyPhy **must** be able to create a 1-1 map between sequences and tree tips.

Sergei

**Comment by jamercadodiaz** [comment]
I dont know how this minor detail escaped my sight! Thank you so much Sergei. I already double checked and it worked! Awesome! Best!, Joel
