### ISSUE TITLE
HYPHYMP and RELAX

### ISSUE THREAD

**Issue by maolun** [veg/hyphy#382]
Dear HyPhy users,

I wonder how to increase the number of threads when running RELAX with HYPHYMP. My system is Mac Yosemite, and I am able to run HYPHYMP /path/to/RELAX.bf successfully. However the number of threads used by HYPHYMP is 1 as indicated by Activity Monitor. And It took about 10 hours to analyze one gene of 32 species. I have 47 genes to go...

Thank you in advance 
Mao-Lun

**Comment by spond** [comment]
Dear @maolun,

The default compiler that ships with recent versions of OS X (clang) does not yet support OpenMP, which is what is required to enable multi-threading in HyPhy. A solution to this is to use `gcc-5` as the compiler. The easiest way to do so is via (homebrew)[http://brew.sh]. 

Try doing this in Terminal

```
$brew install gcc5
[wait a while]

[try]
$gcc-5 
[to confirm that you have the compiler installed]
[cd /path/to/hyphy]
$rm -rf CMakeFiles/ CMakeCache.txt 
[this will clean up older CMake files]
$CC=gcc-5 CXX g++-5 cmake ./
$make MP2
$make install

```

Now you should have a multithreaded version of HyPhy.

Sergeu

**Comment by maolun** [comment]
Dear Sergeu,

Thank you so much. 

An equal sign should be appended to CXX.
$CC=gcc-5 CXX=g++-5 cmake ./

Mao-Lun

**Comment by spond** [comment]
Dear @maolun,

Good catch about the `=`. Did the recipe work for you?

Sergei
