### ISSUE TITLE
MEDS results processor

### ISSUE THREAD

**Issue by TashyK** [veg/hyphy#383]
Hi

I've been running some MEDS analyses and processing them via the MEDS results processor link from the MEDS wiki: http://hyphy.org/w/index.php/MEDS.

It's been unavailable for some time, and I was wondering if the was a new link?

Thanks 
Tasha

**Comment by spond** [comment]
Dear @TashyK,

I am not sure; @murrellb might know.

Sergei

**Comment by murrellb** [comment]
Hi @TaskyK and Sergei

Stellenbosch took my page down. I've updated the wiki page (http://hyphy.org/w/index.php/MEDS) to point to a python script that will process these offline. When I have time I'll build it directly into the MEDS hyphy script.

Cheers,
Ben

**Comment by TashyK** [comment]
Thank you!
