### ISSUE TITLE
MEME through CLI

### ISSUE THREAD

**Issue by l-yampolsky** [veg/hyphy#385]
Dear Sergei and Colleagues,

Sorry for too many questions. I think with your help I am becoming much better with HYPHY, but I am not there yet. You have this wonderful tutorial for BUSTED and aBSREL: github.com/veg/hyphy-tutorials/tree/master/selection. However, it seems to be outdated for MEME, at least for command line interface (I'm using hyphy-2.2.6). Rather then the sequence of input 9,1,1,<alignment> etc. it seems that one needs to select 12,2,1,1,1,1,<alignment> etc. But then it becomes less obvious; I think I am entering something wrong and execution quits on 

Error:perBranchTree is undefined in call to ReplicateConstraint. 

It would be really great if you could update the tutorial for CLI MEME!

Thank you very much in advance,

Lev Y.

**Comment by spond** [comment]
Dear @l-yampolsky,

The tutorial has an error: if you select 12 (Selection/Recombination), the serial version of MEME is broken. You are meant to select 10 (Positive Selection). I've fixed the tutorial. 

Best,
Sergei

**Comment by l-yampolsky** [comment]
Thanks so much! It does not change anything about stand-alone and datamonkey versions, right?

**Comment by spond** [comment]
Hi @l-yampolsky,

No conceptual difference. The data monkey version is parallelized (MPI), while the standalone version is not. 

Sergei
