### ISSUE TITLE
Does PRIME help with saturation?

### ISSUE THREAD

**Issue by lyy005** [veg/hyphy#388]
Hi Sergei,
I got about 50 genes from about 30 insect species that is prone to saturation. I calculated the dS value with KaKs Calculator. On average, it's about 5. Then I use Kr/Kc (radical vs conservative) values rather than dNdS values to test for positive selection. And the values look fine. Do you think PRIME is more tolerant to saturation? 

Also, I was trying to run PRIME locally but didn't find a tutorial about it. I wonder is it possible to run PRIME locally?

Thank you for any advice on this

YY

**Comment by spond** [comment]
Dear @lyy005,

I have never tested PRIME in the context of saturation. I suppose it **could** extract more signal by looking only at __conservative__ substitutions, but I am not prepared to defend this claim.

You can run PRIME locally, yes (it will be slow, however). Give me a day or two to write a little tutorial and make sure everything still works; I am working on v2.3 (and v3) releases, so my working branches of the code may have broken PRIME scripts.

Sergei

**Comment by lyy005** [comment]
Thank you Sergei. I'm looking forward to the PRIME scripts. There is usually a pretty long queue for PRIME on the web server. 

YY
