### ISSUE TITLE
pdf output and plot in DataMonkey webserver in both Chrome or Safari browsers

### ISSUE THREAD

**Issue by JaneZXJ** [veg/hyphy#389]
Why it's failed to download GAB pdf output, and it's worse to run plot of BGM plot, neither pdf nor png going. All of them are stopping at a blank page at both Chrome or Safari browsers.

It's urgent for help! Thanks so much!!

**Comment by stevenweaver** [comment]
Hello, 

Can you please send the links that are causing you a problem to sweaver@temple.edu?

Thanks,
Steven

**Comment by stevenweaver** [comment]
Updated pdf generator utilized by datamonkey to latest version. 

Please try again,
Steven
