### ISSUE TITLE
comment follow issue #391, in case you won't read it...

### ISSUE THREAD

**Issue by JaneZXJ** [veg/hyphy#394]
Hi @spond,
I met the same problem that "not tested" for each branch in the aBSREL results, and I'm not so clear about your resolution. [http://test.datamonkey.org/absrel/56c5806f9dd92ef47c709304]
[http://test.datamonkey.org/absrel/56c5a9569dd92ef47c7093ad]
And more questions about:
1. Did it mean the results of PAML, BSREL and aBSREL should be in concordance? If not, as my BSREL results indeed detected episodic selected branches, but not pass LRT for rBS model in PAML.
2. What's the difference between local HyPhy and web-server? Why did it work locally but not on web-server? 
3. I don't understand correlation of the results between GAB and BSR, as the dN/dS ratio of same lineage or branch is totally different between the two models. And their algorithms are different. 
4. So, after BSREL, because the branch results are in accordance with my expection, where is the site results? Do I need to perform another one, as covarion model of Guindon et al. 2004 cited in your BSREL paper? Or from the results of site-by-site selection? As there are same residues between HyPhy and PAML site models.

So appreciated for your time and any suggestion!
Jane
P.S. my data are hemoglobin genes of birds adapted to different elevations, if it's different from your familiar data.

**Comment by spond** [comment]
Dear @JaneZXJ,

0. @stevenweaver is working on the datamonkey.org resolution. In the meantime, please run aBSREL locally (on your machine), following (these instructions)[https://github.com/veg/hyphy-tutorials/tree/master/selection#use-absrel-to-find-lineages-which-have-experienced-episodic-diversification]

1. aBSREL and BSREL should be in general agreement; there could be a difference on occasional branches. There are **no expectations** of concordance between PAML and aBSREL/BSREL. In our papers we argue that the models in PAML have serious statistical flaws and should not be used in this context. That doesn't mean that they are always (or even frequently) wrong, just that we know of very specific situations when they will behave **very** badly. 

2. The server runs a version of HyPhy; there must have been an error in one of the wrapper scripts.

3. Yes, their algorithms are totally different. BS-REL is the preferred and much more accurate way to estimate branch-level effects.

4. You need to run MEME or FUBAR to detect sites under selection. You **cannot** detect both branches and sites with any degree of confidence. Please see my (recent talk)[http://bit.ly/pond-hutch-2015] where I try to explain why. Like in (2); there may be some agreement between PAML and our models, but like we argue in the FUBAR paper and the MEME paper, PAML models can (again, it does not mean that they will, but they can) give you very wrong results in a number of scenarios.

Sergei
