### ISSUE TITLE
Site-varied branches and branch-specific sites, what's the suitable methods assembly? 

### ISSUE THREAD

**Issue by JaneZXJ** [veg/hyphy#401]
Dear Sergei,
        Thanks for your last reply to #394, and your slide of selection. I've studied the content about Branch or site selection depending on each other, and read almost all of your papers about that. Now I tried the models as you suggested and some issues to be figured out:

1. If the selection inference uncertainty principle is universal in evolution of functional proteins except for pathogen-host system, it's suitable for my data to use your models. As one subunit of my hemoglobin data was detected episodic selection in the main clade by BSR or aBSREL, which did not pass LRT test of any priori rBS or brach model in PAML. 

2. And the analogous subunit in the co-expressed isoform, a lineage under episodic positive selection in BSR but not in aBSREL. If it's because of short branch length, the longest is 0.04, much less than 0.15 that under episodic selection? 

3. For site-level models, I performed both FUBAR and MEME. As I understand, FUBAR is used to detect pervasive selection, and MEME for both pervasive and episodic. So does that mean more site should be under selection in MEME than FUBAR? In my datasets, one of the three subunits in that case, and the others is opposite. I think the two more sites in MEME is caused by more non-synonymous. One of them is an unique substitution in positive branch by aBSREL and rBS of PAML, the other is only detected by MEME. 

4. I also used SLAC, FEL, and EF, PRIME to the same datasets, to compare with  site model of PAML. The minimum number of selected sites in SLAC, followed FEL, maximum in EF except for the heterogeneous  subunit. I can't understand the later result, if EF is expected to detect structure or functional domains specific variation, why distinctive for the subunits of the same heterotetramer (alpha and beta).

5. The last but not lest, do you think it's making sense to predict sites under positive selection on the counts of significant numbers of the above models? Although it's published in  [http://www.ncbi.nlm.nih.gov/pubmed/26142723](url), but I cast doubt on its persuasion. Because these methods are correlated and dependent, I think it's fine to compare the results but not to add them. 

So I'm confused if it's enough to use aBSREL and MEME for my data. If there is suitable sample size of taxa or sequence length? And the minimum of branch length is 0.15?

Thank your so much!
Have a nice day!

Jane

**Comment by JaneZXJ** [comment]
Are you in vacation? @spond 

Enjoy!

**Comment by spond** [comment]
Dear @JaneZXJ,

1. Not sure what your question is here. It is **not** surprising that aBSREL can find selection where PAML doesn't (the opposite also happens).

2. What is the complexity of the model (# of rate classes) inferred by aBSREL on that branch? BSREL uses a slightly less conservative test that aBSREL, so it is also possible that the aBSREL result is on the cusp of significance.

3. There is no hard and fast rule about which method (FUBAR or MEME) will detect more sites. When you have a lot of sequences (hundreds) and a lot of divergence, then yes, MEME should find all the sites that FUBAR does, and then some. MEME can indeed find selection when short branches experience bursts of non-synonymous substitutions.

4. I don't understand the question. EF = Evolutionary Fingerprinting? It is not really designing for site-level inference (you need to feed it different alignments). FEL > SLAC in terms of power, so what you see is as expected.

5.  Again, I can't give you an answer that will be universally applicable. If you know that method A is **always** better than method B (e.g. has more power at the same level of false positive, or better AUC or some other measure of performance), then it makes no sense whatsoever to use method A. Some of the methods you used (aBSREL and MEME) for example, answer different questions, so you **should** use them both. At the end of the day, you can decide if you are willing to tolerate false positives to gain more power (in which case you could `or` the methods), or if you wish to take a consensus poll (`and` the methods) to be more certain, but then lose power. As a reviewer, I always found it tedious when authors present tables upon tables of results of different methods applied to the same data set to answer the same question, and then either cherrypick the results that fit the narrative, or simply leave the reader buried with a data dump and no clear direction as to what that all means.

Sergei
