### ISSUE TITLE
Too slow of Spidermonkey in webserver, where is BGM in HyPhy?

### ISSUE THREAD

**Issue by JaneZXJ** [veg/hyphy#402]
Hi Sergei,
       Another question is about BGM, I expect to find correlation of selected sites. But it seems too slowly   for my less than 30 data sets and sometimes stopped by itself. 
   
       I didn't find it in HyPhy package, is there? 

      Thanks again!

Jane

**Comment by stevenweaver** [comment]
Hello, 

Please refer to issue #322. 

The batch file is located here: https://github.com/veg/hyphy/blob/master/res/TemplateBatchFiles/BGM.bf

Best,
Steven
