### ISSUE TITLE
Cannot build package on Linux Mint

### ISSUE THREAD

**Issue by Brainiarc7** [veg/hyphy#403]
Hello guys,

Here's the error I get when I try to build the MPI version of the package:

lin@mjanja ~/source.build/hyphy/build $ time make MPI -j64
[  6%] Linking CXX executable HYPHYMPI
/usr/local/lib/libopen-pal.so.13: undefined reference to `clGetDeviceIDs@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.13: undefined reference to `clGetPlatformInfo@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.13: undefined reference to `clGetDeviceInfo@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.13: undefined reference to `clGetPlatformIDs@OPENCL_1.0'
collect2: error: ld returned 1 exit status
make[3]: *** [HYPHYMPI] Error 1
make[2]: *** [CMakeFiles/HYPHYMPI.dir/all] Error 2
make[1]: *** [CMakeFiles/MPI.dir/rule] Error 2
make: *** [MPI] Error 2

real	0m0.441s
user	0m0.376s
sys	0m0.028s

The package build fails at that particular stage, after configuring the build step with cmake.

**Comment by stevenweaver** [comment]
Hi, 

This looks to be a problem with either your environment path or openmpi installation. 

The `libopen-pal` is trying to reference OpenCL methods that are presumably from a module that the library is trying to load. You will need to either adjust your `LD_LIBRARY_PATH` environment variable to point to the directory where your OpenCL library exists, or you will need to recompile OpenMPI without the -lOpenCL flag. 

If the former paragraph made no sense to you, then it is undoubtedly a problem with Mint's packaging of openmpi. Mint Linux sometimes mixes their own binary packages with binary packages from Debian and Ubuntu without rebuilding the latter, which makes things a bit of a mess sometimes. 

Before I can try helping further, can you compile hello_world mpi source code?

Best,
Steven

**Comment by Brainiarc7** [comment]
As suspected, my OpenMPI environment is janky.

See this:

mpicc -o hello-world hello-world.c
mpicc: /usr/local/cuda-7.5/lib64/libOpenCL.so.1: no version information available (required by /usr/local/lib/libopen-pal.so.13)
/usr/local/lib/libopen-pal.so.13: undefined reference to `clGetPlatformIDs@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.13: undefined reference to `clGetDeviceIDs@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.13: undefined reference to `clGetPlatformInfo@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.13: undefined reference to `clGetDeviceInfo@OPENCL_1.0'
collect2: error: ld returned 1 exit status

**Comment by stevenweaver** [comment]
Hi, 
This issue is with your devices and operating system. 

This is my conjecture : 
1) You (or the OS) had installed OpenCL 1.0, but your GPU is not compatible with that version
2) You installed OpenMPI, OpenMPI found your broken OpenCL library.
3) Therefore, OpenMPI was compiled with the -lOpenCL flag. 
4) An error occurs whenever you try to compile anything with OpenMPI

The only flags that I could find on the OpenMPI site with regards to disabled opencl was on this page:
https://www.open-mpi.org/projects/hwloc/doc/v1.7.2/a00014.php

You will either have to fix your OpenCL library, or recompile OpenMPI without OpenCL support.

Best,
Steven

**Comment by Brainiarc7** [comment]
Hmmm...That will do.

**Comment by Brainiarc7** [comment]
Well, the documentation pertains to hwloc. Might not be very useful, but I'll check it out.

**Comment by Brainiarc7** [comment]
Hello there,

I have fixed my OpenMPI environment by installing CUDA from the Nvidia repositories and all is well.

I can now build and install hyphy successfully.

Thanks ;-)
