### ISSUE TITLE
Hyphy 2.2.6 link

### ISSUE THREAD

**Issue by sapuizait** [veg/hyphy#405]
Can someone add the hyphy 2.2.6 download link? 

cause as far as I can see the current version is 2.2.4 and I cant find the 2.2.6 version anywhere...

I am running the 2.2.4 on windows and I get the same problem/error that many people have when running MEME

thanks
P

**Comment by stevenweaver** [comment]
Duplicate - #399. 
Will adjust ticket #399 to include a new exe as well. 

Best,
Steven
