### ISSUE TITLE
using given branch lengths for ML calculation

### ISSUE THREAD

**Issue by gusparisi** [veg/hyphy#406]
hi, 
I am testing the ancestor reconstruction method using simulated sequences for a given tree and given evolutionary distances. I would like to estimate the reconstruction using those given distances included in the input file containing the tree. However, printing the distances before ML optimization appeared as "0". 
I include below the script and the treefile 
thank you very much for your help
gustavo

DataSet data = ReadDataFile ("seqfile");
ACCEPT_ROOTED_TREES = 1;
ACCEPT_BRANCH_LENGTHS = 1;
LIKELIHOOD_FUNCTION_OUTPUT=2;

file1 = "treefile";
fscanf (file1,"Tree",tree);
treestring=""+tree;

/*Define model global*/

/*JONES*/

UseModel (USE_NO_MODEL);

     #include "Jones1.mdl";
      Model JTT = (jones,jonesF, 1);

Tree arbol = treestring;

/*crear una clase a partir de los datos*/

        DataSetFilter clase = CreateFilter (data,1);

/*definir la funcion de likelihood, compuesta por los datos, el arbol y el modelo*/

        LikelihoodFunction lk = (clase, arbol);

/*optimizar la funcion de lik en funcion de las distancias*/

        fprintf (mljtt-jtt, "Jones unconstrained Before optimization  Log(L) = ", lk,"\n");

        Optimize (params, lk);

        fprintf (mljtt-jtt, "Jones unconstrained After optimization Log(L) = ", lk,"\n");
        fprintf (mljtt-jtt, "branchlength uno-dos = ", BranchLength(arbol,"uno;dos"),"\n");
        fprintf (outs, "Jones unconstrained  Log(L) = ", lk,"\n");

/*usando la funcion de lik reconstruir los ancestros*/

 /*    DataSet ancestors = ReconstructAncestors (lk,MARGINAL);*/
     DataSet ancestors = ReconstructAncestors (lk);

        DataSetFilter ancestral_filter = CreateFilter (ancestors, 1);
        /*fprintf (outs, "Inferred the `SELECTION_STRINGS` root sequence as \n", ancestral_filter, "\n");*/
        fprintf (outs, "Inferred\n", ancestors, "\n");

        GetDataInfo (node0, ancestral_filter, 0);
        fprintf (outs, "node0 ", node0, "\n");
        GetDataInfo (node2, ancestral_filter, 1);
        fprintf (outs, "node2 ", node2, "\n");
        GetDataInfo (node3, ancestral_filter, 2);
        fprintf (outs, "node3 ", node3, "\n");
        GetDataInfo (node6, ancestral_filter, 3);
        fprintf (outs, "node6 ", node6, "\n");

treefile
(uno:2.700000,((dos:0.900000,tres:0.900000):0.900000,(cuatro:0.900000,cinco:0.900000):0.900000):0.900000);

**Comment by spond** [comment]
Dear @gusparisi,

Instead of 

```
Tree arbol = treestring;
```

use

```
AUTOMATICALLY_CONVERT_BRANCH_LENGTHS = 1; 
Tree arbol = treestring;

fprintf (stdout, "Tree string: ", treestring, "\nTree with branch lengths: ", Format (arbol, 1,1), "\n");

```

to have HyPhy keep the branch length at the values in the file.
Also, because you want to use **fixed** branch lengths, you don't need to call `Optimize` on the likelihood function, because this will re-tune the branch lengths.

If all goes well, the `fprintf` statement should show the same branch lengths.

Sergei

**Comment by gusparisi** [comment]
Dear Sergei
Thank you very much for your answer. 
Unfortunately, we still have problems to use branch lengths from trees. Particularly in this script we tried to use a site-specific substitution matrix and then we assigned to each position a given tree and a given substitution matrix. However, when we print the branch length only the last assigned tree showed the corresponding branch length (in this case tree4). 
Please find below the script and the output. 
Thank you very much for your help
Gustavo

DataSet data = ReadDataFile ("seqfile");
LIKELIHOOD_FUNCTION_OUTPUT=2;
ACCEPT_ROOTED_TREES = 1;
AUTOMATICALLY_CONVERT_BRANCH_LENGTHS = 1;
/*REPLACE_TREE_STRUCTURE = 1;*/
treestring = "(uno:0.003,((dos:0.001,tres:0.001):0.001,(cuatro:0.001,cinco:0.001):0.001):0.001)";

/*SCPE*/
    for(i=0;i<5;i=i+1){
        ExecuteCommands("#include \"scpe-"+i+".dat\";");
        ExecuteCommands("Tree tree"+i+" = treestring;");
        ExecuteCommands("DataSetFilter class"+i+" = CreateFilter (data,1,\""+i+"\",\"\");");
    }
        fprintf (mljtt-scpe, "uno = ", BranchLength(tree1,"uno"));
        fprintf (mljtt-scpe, "uno = ", BranchLength(tree2,"uno"));
        fprintf (mljtt-scpe, "uno = ", BranchLength(tree4,"uno"));

    lfDefCommand = "";
    lfDefCommand * "LikelihoodFunction lk = (class0,tree0,";
    for(i=1;i<4;i=i+1){
        lfDefCommand * ("class"+i+",tree"+i+",");
    }

    lfDefCommand * ("class"+i+",tree"+i+") ");
    lfDefCommand * 0;
    fprintf (stdout, "\nExecuting: ", lfDefCommand, "\n");
    ExecuteCommands (lfDefCommand);
     fprintf (mljtt-scpe, "SCPE Before  Log(L) = ", lk);

And the output
uno = 0.003447515604042076 uno = 0.003033675616539873 uno = 0.002999999999999999SCPE Before  Log(L) = Log Likelihood = -37.4617252562944;
Tree tree0=(uno:0.002500763142347248,((dos:0.0008335877141157492,tres:0.0008335877141157492)Node3:0.0008335877141157492,(cuatro:0.0008335877141157492,cinco:0.0008335877141157492)Node6:0.0008335877141157492)Node2:0.0008335877141157492);
Tree tree1=(uno:0.003447515604042076,((dos:0.001149170871333571,tres:0.001149170871333571)Node3:0.001149170871333571,(cuatro:0.001149170871333571,cinco:0.001149170871333571)Node6:0.001149170871333571)Node2:0.001149170871333571);
Tree tree2=(uno:0.003033675616539873,((dos:0.001011225205513291,tres:0.001011225205513291)Node3:0.001011225205513291,(cuatro:0.001011225205513291,cinco:0.001011225205513291)Node6:0.001011225205513291)Node2:0.001011225205513291);
Tree tree3=(uno:0.002351907772789761,((dos:0.0007839722476379444,tres:0.0007839722476379444)Node3:0.0007839722476379444,(cuatro:0.0007839722476379444,cinco:0.0007839722476379444)Node6:0.0007839722476379444)Node2:0.0007839722476379444);
Tree tree4=(uno:0.002999999999999999,((dos:0.0009999999999999998,tres:0.0009999999999999998)Node3:0.0009999999999999998,(cuatro:0.0009999999999999998,cinco:0.0009999999999999998)Node6:0.0009999999999999998)Node2:0.0009999999999999998);

**Comment by spond** [comment]
Dear @gusparisi,

Could you attach the `messages.log` file that HyPhy generates when executing your script? Also, at what point are you defining substitution models? Are they in the `.dat` files? If so, could you attach one of those for examination?

Best,
Sergei

**Comment by gusparisi** [comment]
hi sergei
thank you very much for your answer, please find attached two examples of
site-specific substitution matrices (.dat) and the logfile.
best
gustavo

On Mon, Mar 14, 2016 at 4:06 PM Sergei Pond <notifications@github.com>
wrote:

> Dear @gusparisi <https://github.com/gusparisi>,
>
> Could you attach the messages.log file that HyPhy generates when
> executing your script? Also, at what point are you defining substitution
> models? Are they in the .dat files? If so, could you attach one of those
> for examination?
>
> Best,
> Sergei
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/veg/hyphy/issues/406#issuecomment-196477180>.
>
-- 

Gustavo Parisi
Departamento de Ciencia y Tecnologia
Universidad Nacional de Quilmes
Roque Saenz Pena 182, Bernal B1876BXD
Argentina

Phone: ++ 54 11 43657100 ext 5659
Fax: ++ 54 11 43657182
Institutional: gustavo.parisi@unq.edu.ar Alternative: gusparisi@gmail.com
Webpage: http://ufq.unq.edu.ar/sbg/

**Comment by spond** [comment]
Dear @gusparisi,

GitHub strips e-mail attachments. Could you please supply them via the GitHub website?

Sergei

**Comment by gusparisi** [comment]
ups! here they go!
[data-for-sergei.zip](https://github.com/veg/hyphy/files/176809/data-for-sergei.zip)
