### ISSUE TITLE
MEME output interpretation

### ISSUE THREAD

**Issue by tan0101** [veg/hyphy#407]
Hi,

I have a question about MEME. I am using 14 sequences, and default setting parameters (significance level=0.1). 
Looking at the results listed in the summary table, I always have β-=0 (p>0.05) so  I am facing the following scenarios:
 
If α=0, β-=0 and β+>0, the codon in consideration is (Pr [β=β+])% of the time under positive selection (ω+= β+/ α= +infinity) while in the remaining (Pr [β=β-]) % of the time it is invariant (ω-= β-/ α= 0). 

If α>0 β-=0 and β+>α>0. It will be that the site is (Pr [β=β+])% of the time under positive selection if ω+>1 while in the remaining (Pr [β=β-]) % of the time it is invariant (ω-= 0). 
Are these conclusions corrects? 
many thanks for your help

**Comment by spond** [comment]
Dear @tan0101,

>If α=0, β-=0 and β+>0, the codon in consideration is (Pr [β=β+])% of the time under positive selection (ω+= β+/ α= +infinity) while in the remaining (Pr [β=β-]) % of the time it is invariant (ω-= β-/ α= 0).

Your interpretation is correct, **except** you should never directly use the point estimates to draw definitive conclusions. All that MEME says is that **some** proportion of branches at a site have **some** &omega; > 1 at p = xx. Point estimates derived from 14 sequences are going to be very imprecise; for example if you estimated a confidence interval around &beta;<sub>-</sub>, it is likely to be quite wide. 

>If α>0 β-=0 and β+>α>0. It will be that the site is (Pr [β=β+])% of the time under positive selection if ω+>1 while in the remaining (Pr [β=β-]) % of the time it is invariant (ω-= 0). 

With the same *proviso* as the previous point (to not over interpret the point estimates, and to only call positive selection if the p-value is low. Also note that (at least to me), `invariant` means no change at all, whereas in your example, you would expect no non-synonymous change.

Best,
Sergei
