### ISSUE TITLE
support for data monkey?

### ISSUE THREAD

**Issue by harturchin** [veg/hyphy#408]
Is there still support for the HyPhy datamonkey now that Dr. Pond's lab has moved to Temple? Some of the job queues on the UCSD servers have many jobs waiting, with small jobs in the first position in the queue that have been running for a long time. Thanks, apologies if this is off topic for the github site.

**Comment by harturchin** [comment]
Hi Steven. Thanks for checking this out. I tried to contact you directly to ask about the long waits on queues 1 and 5 but didn't find your new Temple address. Cheers. Mike Hart

**Comment by stevenweaver** [comment]
Hello Dr. Hart,

Datamonkey has been running on temporary hardware while we have been installing and configuring hardware at Temple. Unfortunately, the temporary hardware has been somewhat inconsistent during this time period.

I have scheduled datamonkey to be migrated to Temple this evening. I will post here again once the migration has been completed. 

Best,
Steven

**Comment by harturchin** [comment]
Thanks, Steven. Wow that must be a big project. Thanks so much for the help, I’m relieved to know the site is continuing at Temple. Good luck with that!

Cheers,
Mike

**Comment by stevenweaver** [comment]
Yes, it's always surprising how big a project relocating can be despite best efforts to be nimble.
In addition, if you would like to contact me directly, my new email address is sweaver@temple.edu.

**Comment by 0ct0puss** [comment]
Following on, I have submitted to the FUBAR queue and it appears stalled? None of the jobs ahead of mine have completed and the first has been on the queue for over 12 hours. I am currently 13th. I downloaded the alignment and tree files produced by the wrapper script and ran them locally and it completed on my MacBook in 7 minutes. Is this part of the migration? Else is the wrapper script that checks formatting etc available somewhere as a download as I could then run analyses locally. I have alignments done in Geneious and exported as .fasta, but doing a tree in Geneious and exporting as either newick or nexus continued to throw an error regarding node naming.

thanks for all the effort that goes in to creating and maintaining this!
Libby Guethlein

**Comment by stevenweaver** [comment]
Hello Libby Guethlein,

Yes, the FUBAR queue was a casualty of part one of the migration.
Can you please check your job once more?

I'm not quite done with the migration yet. Our servers are configured and set up with new instances of datamonkey, but I am waiting to flip the switch until after the weekend is over.

You should be able to use `res/TemplateBatchFiles/ConvertDataFile.bf` inside of the HyPhy repository. 

We should be fixing the Geneious newick tree incompatibility in an upcoming version of HyPhy. Please view #259 for a potential explanation of the bug.

Best,
Steven

**Comment by 0ct0puss** [comment]
Hi Steven

The job has completed. Thank you. I will look into the data conversion or else wait until the migration is complete.

Best
Libby

**Comment by stevenweaver** [comment]
Datamonkey has been migrated to new infrastructure.
