### ISSUE TITLE
new Data monkey problem

### ISSUE THREAD

**Issue by kschafer43** [veg/hyphy#409]
hi Steven and Sergei - We received the following message through the CFAR website. Will you please send me your email addresses? I won't be able to log in all of the time to forward these messages, and would prefer to simply forward messages to your email. Thanks, Kim

From: <jacob.a.russell.drexel@gmail.com> on behalf of Jacob Russell <jar337@drexel.edu>
Date: Tuesday, March 8, 2016 at 9:22 AM
To: Kim Schafer <kschafer@ucsd.edu>
Cc: <cfar@ucsd.edu>
Subject: Re: FW: CFAR Website Feedback

HI Kim. I have a report from a student that their iFEL analysis has been in the queue for 19 hours. Sorry to bug you again, but this seemed like an issue that you'd want on your radar. My students have an assignment due tomorrow that requires a datamonkey analysis, so the procrastinators are potentially running into this log-jam.

Anyways, thanks for listening. Let me know of any updates if you can.

Sincerely,
Jake Russell
Drexel Biology

**Comment by stevenweaver** [comment]
Dr. Russell's issue has been resolved and he has been contacted. 
Thank you.
