### ISSUE TITLE
impossible to upload my data on datamonkey.org

### ISSUE THREAD

**Issue by ct74** [veg/hyphy#410]
Since few days, I have an issue to download some datas on datamonkey.org.
When I upload some datas the following message appears : 413 Request Entity Too Large.
It is very strange, because I already used datamonkey.org to analyse these datas few months ago. And  my data do not exceed the size restriction.
Can you help me with this issue.
Thanks in advance.

**Comment by stevenweaver** [comment]
Hi,

I introduced a new server configuration yesterday. 
I've increased the file upload size to what it was previously. 
Please try again. 

Thank you,
Steven

**Comment by ct74** [comment]
Many thanks it is working again!
Cécile
