### ISSUE TITLE
How can the exact time and effect of substitution along a phylogeny be obtained in HyPhy?

### ISSUE THREAD

**Issue by hyphyInfant** [veg/hyphy#413]
Hello,

I wish to simulate codon sequences along a phylogeny using HyPhy. However, I need more than just the ancestral and extant sequences that may be obtained with the **Simulate** function. Is there a way to identify the exact time along the branches of the phylogeny when substitutions occurred? I will also like
to know the codons associated with each of the substitution events.

A pdf file that contains a more detailed explanation of my problem was attached to this message.

Thanks in advance,
hyphyInfant.

[asked20160328.pdf](https://github.com/veg/hyphy/files/194193/asked20160328.pdf)

**Comment by spond** [comment]
Dear @hyphyInfant,

The simulation code in HyPhy never actually computes intermediate states. If you have a starting codon (`x`) and a specified transition matrix on a branch (`T`), then what you do is simply take the row that corresponds to `x` from `T` (the row defines a valid probability distribution on the characters), and draw a value from that distribution. 

This procedure sums the probabilities of **all** paths that lead from x to the sampled terminal state `y`. You can definitely simulate a more fine substitution map (e.g. via drawing waiting times, changing characters one at a time, etc), but this is much more elaborate that necessary to generate the data under any substitution model that HyPhy supports. 

Take a look at [Jon Bollback's SimMap](http://www.simmap.com) -- it should be able to generate the data you want. 

Sergei
