### ISSUE TITLE
How may one randomly sample from a Gamma distribution in HyPhy?

### ISSUE THREAD

**Issue by hyphyInfant** [veg/hyphy#414]
Hello,

I need to randomly sample an observation from a Gamma distribution using HyPhy but I do not know how to achieve this. I will sincerely appreciate any help on how to solve this problem.

Please note that I am aware of the **GammaDist ** function. I was unable to use the function for the problem at hand, because it provides the probability of observing a value from a Gamma distribution. In my case, I wish to supply the parameters of the Gamma distribution and obtain a randomly sampled value from the distribution. 

Thanks in advance,
hyphyInfant.

**Comment by spond** [comment]
Dear @hyphyInfant,

You can use the canonical [Inverse Transform Sampling](https://en.wikipedia.org/wiki/Inverse_transform_sampling), which is probably the easiest to implement, but is quite inefficient. 

```
function sample_gamma_variate (alpha, beta) {
    FindRoot (sample, Random (0,1) - CGammaDist (_x_,alpha,beta),_x_,1e-9,10000);
    return sample;
}

for (k = 0; k < 100; k += 1) {
    fprintf (stdout, sample_gamma_variate (1,1), "\n");
}
```

Best,
Sergei

**Comment by murrellb** [comment]
Hi folks,

Sergei, is the following no longer supported?:

LoadFunctionLibrary("ProbabilityDistributions");
gammaVariate = sampleFromGamma(p1,p2);

Cheers,
Ben
