### ISSUE TITLE
MEME: relationship between β1and α

### ISSUE THREAD

**Issue by snaketron** [veg/hyphy#415]
Dear developers,

after reading the publication on MEME my understanding was that β1(β-) must always be ≤ α. This was confirmed by the MEME tutorial (https://github.com/veg/hyphy-tutorials/tree/master/selection) which states "β1 is the estimate for the first non-synonymous rate; β1 is always ≤ α".

In practice, I see examples where β1 is greater than α, including the example given in your tutorial. Is β1 == β-? Is my interpretation incorrect or is this a bug?

Regards

**Comment by spond** [comment]
Dear @snaketron ,

Your interpretation **is** correct. I suspect that this is an error in how the output is generated. Embarrassing, that. I will investigate. 

Best,
Sergei

**Comment by szhan** [comment]
Hi Sergei,

I am also starting to use MEME. I am just wondering if this issue will be solved in v2.3. I am trying out v2.2.7 at the moment.

Thanks,
Shing
