### ISSUE TITLE
Discordance between aBSREL and MEME results

### ISSUE THREAD

**Issue by pbrec** [veg/hyphy#417]
Hi,

I am analyzing a big dataset including >140 orthologous groups of a multi-gene family, each with 4 to 20 OTUs. My major goal is to infer patterns of selection, i.e. what lineages are under  selection in the different orthologous groups (here I use aBSREL). Secondly, I am interested in the distribution of sites in the alignments under selection, to see if these are clustered or randomly distributed over genes (here I use MEME).

There are several cases, where aBSREL detects episodic selection for an orthologous group but no actual site is under positive selection in MEME. This happens especially when groups have a low number of OTUs. This is a low-power issue you guys reported in the MEME paper, so this makes sense to me. 

However, there also are several cases where aBSREL does not detect selection but MEME does, actually for a number of sites. I thought that might have to do with the reduced power of aBSREL when there are a lot of branches (due to multiple testing correction). But I am not quite sure how to interpret these results. 

How should I interpret these cases where aBSREL and MEME show this kind of discordance? Also, how reliable are the bayes analyses that suggest branches under selection at a certain site?

Thanks,

Philipp

**Comment by murrellb** [comment]
Hi Philipp,

If there are branches with many sites experiencing selection, aBSREL should
have good power. If there are sites with many branches under selection,
MEME should have good power.

*"Also, how reliable are the bayes analyses that suggest branches under
selection at a certain site?"*

Not. I think of them more as a guide to which branches were driving the
signal for detection at that site, rather than a statistically robust way
of identifying branches with selection occurring.

Cheers,
Ben

**Comment by spond** [comment]
Hi Phillipp,

To add to when @murrellb said, you could also envision (a possibly) pathological case, when the signal for site-level selection (MEME) comes from different branches at different sites, so you don't have enough sites changing along a single branch to give aBSREL power. For example you can have branches 1,3,5 contributing to signal at site X, but branches 2,4,6 at site Y, branches, 7,8,9 at site Z and so on. 

It is also true that the more sequences you add, the harder it is for a single branch in aBSREL to clear the multiple testing correction hurdle: you essentially have the same signal for selection at a given branch, regardless of how many other sequences you have in the analysis, so you don't gain power in aBSREL by adding sequences (but you do by adding sites). MEME, on the other hand, will generally gain power when you add sequences (but not sites).

Best,
Sergei

**Comment by pbrec** [comment]
Hi Ben and Sergei,

Thanks for your responses. Really helpful to wrap my head around it. A combination of MEME and aBSREL seems like a good combination to get an idea of the selective pressures acting.

Just a quick follow up. I discovered that in my version of HYPHY (HYPHY 2.220150924beta(MP) for Darwin on x86_64\) MEME is listed as experimental. Did you change the algorithm since this version?

Best,
Philipp

**Comment by spond** [comment]
Dear @pbrec,

Hmm, it's not experimental. I am pretty certain the algorithm has remained stable since the paper came out. I recently implemented a version that only tests for selection on internal branches, but it won't be in your distribution.

Sergei

**Comment by pbrec** [comment]
Good to know.

Thanks for your help!

Philipp
