### ISSUE TITLE
potential bug in MEME EB branch detection algorithm

### ISSUE THREAD

**Issue by pbrec** [veg/hyphy#419]
Hi,

I've been conducting >150 MEME tests last week and observed unexpected behavior of the algorithm.
As it turns out, for a high proportion of sites detected to evolve under positive selection (>25%) MEME estimates a posterior probability >95% for each branch in the phylogeny to be under positive selection.

I am using HYPHY 2.220150924beta(MP) for Darwin on x86_64. Running some of the datasets through datamonkey did not show this strange behavior.

Best,
Philipp

**Comment by spond** [comment]
Dear @pbrec,

Would you mind sending me an example dataset where this happens?

Sergei

**Comment by pbrec** [comment]
Sure.

The ML tree is included. In this example site 50 is predicted to have pp >95% for all branches.

Cheers,
Philipp

[spond_OR03_example.fa.txt](https://github.com/veg/hyphy/files/228740/spond_OR03_example.fa.txt)

**Comment by spond** [comment]
Dear @pbrec,

Thanks. I'll attempt to replicate and debug.

Best,
Sergei

**Comment by pbrec** [comment]
Dear @spond,

Could you resolve the bug? 

Best,
Philipp
