### ISSUE TITLE
Problem of running the nonCodingSelection.bf

### ISSUE THREAD

**Issue by VinnyLynch** [veg/hyphy#420]
Hi All, 

I've downloaded the nonCodingSelection.bf from https://github.com/ofedrigo/TestForPositiveSelection

When I attempt to run it in HyPhy 2.22 I can successfully load my coding alignment and tree, but get an error message when I try to load my query (non-coding) alignment. Any ideas what is going on here?

Error is:
Macintosh HD:Users:Vinny:Desktop:rs2071473:Selection Test:HLA-DOB.fasta
Error:
Could not find source dataset file:PROMPT_FOR_FILE Path stack: {Macintosh HD:Applications:sequence analysis:HyPhy.app:Contents:Resources:HBL:TemplateBatchFiles:}

Function call stack
1 : Read Data Set ds_query from file PROMPT_FOR_FILE

Best,
Vinny

**Comment by ArtPoon** [comment]
Just a wild guess, have you tried removing the space in "Selection Test" from your path?
- a

**Comment by VinnyLynch** [comment]
I'm running from the GUI, would that matter?

Vinny

**Comment by VinnyLynch** [comment]
Ha! It apparently mattered, thanks much!

**Comment by ArtPoon** [comment]
Yup.  Macs is like that.  :-)
