### ISSUE TITLE
BUSTED incomplete output 

### ISSUE THREAD

**Issue by NY3** [veg/hyphy#424]
Hi there, 
I am running BUSTED on multiple data files and I am finding that for some of them the Constrained model analysis isn't being performed while the majority seem to run properly. 
For example this is what one of the incomplete output files looks like: 
```
{"fits":{"Unconstrained model":{"log-likelihood":-6559.831154848563,
"parameters":33,
"AIC-c":13186.22811907685,
"runtime":1634,
"tree length":12.42501582734556,
"tree string":"((sequence1:0.6822239027384412,sequence2:1.047675289788615)Node2$
"rate distributions":{"FG":[
[0,0.961110079446478]
,[0.3394479409252307,0.03888992055352188]
,[1.041493631809827,1.554353468077078e-16]
]
}}},
"timers":{"overall":1635,
"unconstrained":1634,
"constrained":0},
"profiles":{"unconstrained":[
[-11.922123879478,-8.918217081577362,-8.719060602680564,-8.956659021839329,-18.$
]
},
"evidence ratios":{},
"test set":"sequence1,sequence2,Node2,sequence3,sequence4,Node5,Node1,sequence5$
"background":0,
"test results":{"LR":0,
"p":1}}
```

Any suggestions on what the issue maybe or how to fix it? 

Thank you

**Comment by spond** [comment]
Hi @NY3,

This behavior is expected. The constrained model is not fitted, **unless** the unconstrained model shows evidence of positive selection: &omega;3 > 1 and proportion of sites assigned to that category is non-zero. If there is no such evidence, then the constrained model is the same as the unconstrained model. 

If BUSTED does not run the constrained model, you can interpret this as absence of evidence for positive selection, with p-value of 1

Sergei

**Comment by NY3** [comment]
Of course, makes perfect sense! 
Thanks for your clarification.
