### ISSUE TITLE
Prime

### ISSUE THREAD

**Issue by JuliaSchad** [veg/hyphy#425]
Hi,
I need helpin running Prime on the datamonkey.org It seems that the analyses was done, but i cant see any results and I#m alsonot able to download the .csv file 
In the overview 'information on other analyses' concerning Prime [results] are indicated as proceeded.
JobID .428616073526137.1
Can somebody help to solv the problem?
Thanks a lot
Julia

**Comment by spond** [comment]
Hi @JuliaSchad,

@stevenweaver will fix.

Steven: there are links to `datamonkey-temple` (which fails to resolve, of course) in PRIME result pages:

<img width="1312" alt="screen shot 2016-04-26 at 9 37 46 am" src="https://cloud.githubusercontent.com/assets/1018513/14819987/92b1f40a-0b92-11e6-990c-569be1e9e981.png">


Sergei

**Comment by stevenweaver** [comment]
Hello, 

I have manually edited the results page for JobID 428616073526137.1 and it should be accessible at this point. 

Remedying hostname issues for future results pages now.

Steven

**Comment by stevenweaver** [comment]
Issue has been resolved.
