### ISSUE TITLE
Plot Error - DataMonkey Server (IFEL)

### ISSUE THREAD

**Issue by DonBCilly** [veg/hyphy#433]
Hi,

I get the following error when trying to access the plots following the IFEL analysis:

Error: /var/lib/datamonkey/share//Formats/IFELplot could not be opened for reading by fscanf. Path stack: {/usr/local/bin/,/var/lib/datamonkey/share//BFs/} Function call stack 1 : Read the following data from "../Formats/IFELplot" : Raw into IFELplot; -------

Any ideas why?

Thank you,

Don.

**Comment by stevenweaver** [comment]
Hello Don,

Thank you for bringing this issue to our attention. 
The issue has been resolved, please try again.

Best,
Steven

**Comment by DonBCilly** [comment]
Hi Steven,

Works like a charm, thanks!

Don.
