### ISSUE TITLE
Differential codon usage on different branches

### ISSUE THREAD

**Issue by saurabh-mk** [veg/hyphy#439]
Hello,

Many thanks for this good resource!

I was wondering if there is a way to estimate genome-wide relaxation/intensification of selection in certain branches when base composition and codon frequencies may differ among branches of a tree?

This sort of analysis seems to be briefly reported in Wertheim et al (MBE 2015), but it is not clear to me how to perform it. Are there any simple changes to the RELAX batch file that will make this possible?

Saurabh

**Comment by spond** [comment]
Dear @saurabh-mk,

Apologies for not responding sooner. Yes, you can create models that encode different frequencies across different parts of the tree, but it's not a part of the standard distribution. I can point you to how this can be accomplished by modifying the `RELAX.bf` file, but the tricky part is how to specify which parts of the tree will have different frequencies, and how you want them estimated (e.g. from a subset of sequences).

Sergei

**Comment by saurabh-mk** [comment]
Dear Sergei

Thanks for the response! Nice to know that it can be done :)
1. I was thinking the dirty(?) way would be to a priori specify clades with different GC contents (known from genome, say). Do you think this is a good idea? If it is, it will be good to know how to implement this.
2. Do you know if it has been calculated how much error we expect (with combinations of codon bias and selection/relaxation strengths?). Can you point me to it?

Many thanks!
Saurabh

**Comment by saurabh-mk** [comment]
Hello,

Sorry to reopen this old issue. I am returning to some old work. I hope it is ok to continue here, rather than open a new one.

I would like to perform analysis similar to Wertheim et al (MBE 2015) report for the endosymbionts. Specifically, I want to test for relaxed selection on some branches while simultaneously assigning separate equilibrium nucleotide frequencies to the same branches. Can you guide me on how to accomplish this?

Thanks!
Saurabh Mahajan
