### ISSUE TITLE
two issues: 1)DEPS jobs queue been stuck for 20+ hours in datamonkey and 2)DEPS in GUI kept crashing

### ISSUE THREAD

**Issue by sungml92** [veg/hyphy#442]
Dear all, 

Thank you in advance in viewing and answering my question. 
I currently have two issues; one in datamonkey and the other in hyphy gui version. Both of the issues are dealing with DEPS. 

1) I have observed that my two DEPS job queues in datamonkey have been stuck for more than 20 hours. As far as I understand, data monkey processes the job in a sequential manner. There is a REL queued in front of my queues and has been processing for a little less than a day. Is this a normal phenomenon?

2) Every time I run DEPS in hyphy gui, the job crashes in the middle of the run (farthest went 9 hours then crash). This is the reason I used the datamonkey for DEPS run. I tried DEPS with the sample data provided in the tutorial, however, that run was also crashed after generating several sample files. I am running the hyphy package in OS X El Capitan (8gb memory and 2.9ghz i5). Is anyone experienced and successfully solved this issue? I have run other analyses, e.g. FUBAR, and hyphy did not have any issues in running them. 

Cheers,
Sung

**Comment by stevenweaver** [comment]
Hello Sung,

1) It looks as though the REL job became stuck. I removed that job from the queue and your DEPS job is running now.

2) I've started to try to reproduce your issue, but providing the output from `/Applications/errors.log` may be helpful in diagnosing the problem.

Best,
Steven

**Comment by sungml92** [comment]
Hi Steven,

Below is the excerpt from a crash report

Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00000000bf7fff94
Exception Note:        EXC_CORPSE_NOTIFY

It looks like a problem with mac. I should have looked into the error report before raising the issue. My apology. I will tried to resolve the problem and check back. 

Cheers,
Sung
