### ISSUE TITLE
Basic questions about DEPS

### ISSUE THREAD

**Issue by sungml92** [veg/hyphy#443]
Dear all,

Thank you in advance in viewing and answering my question. 

I have several question regarding DEPS in hyphy gui.

1) How important the tree estimation in Directional Evolution in Protein Sequences? 
I am currently using RaxML -m PROTCATFLU to estimate the tree topology and use FigTree to make the tree rooted. I first generated five trees using the RaxML and fed the hyphy Direction REL.bf with respective trees. Two out of five runs showed me evidences of direction selection, however, others did not. Is this because of the model I selected for tree estimation? or are there any other causes?

2) Unlike web version of DEPS, I was not able to set site-to-site variation and rate class for model in hyphy GUI version. Does the program automatically estimates the variation and rate class?

Cheers,
Sung

**Comment by spond** [comment]
Dear @sungml92,

1. Where you place the root is the most influential, because it determines the **direction** of evolution by informing what the ancestral residues were. If your 5 trees were rooted at different nodes/clades, then you might see significant differences. 

2. The HyPhy GUI uses hard-coded rate variation options (Beta-Gamma with 4 rate categories). It is usually a sensible choice and is meant to reduce user confusion.

Sergei

**Comment by sungml92** [comment]
Dear Sergei,

Thank you for your answer. 
1) For question 1, same root was fixed with FigTree every time after a tree estimation. However, I observed a small variation in initial bifurcation below the ancestral sequence. After fixing the variation problem, I was not able to see any evidence of directional evolution. Looked like initial evidences were false positives. 

Cheers,
Sung

**Comment by spond** [comment]
Dear @sungml92,

A small topological change should lead to concomitantly small changes in selection inference. Could you paste summaries of DEPS results here? I want to make sure there's not something undesirable (e.g., a bug) is going on.

Sergei

**Comment by sungml92** [comment]
Dear Sergei,

I am posting results from repetitive run. One was run with hyphy software (denote with 1-), the other was run with datamonkey (2-). Same root, model, and rate class were used. Both used same protein sequence (30 sequences with 470 aa) but the tree was slightly different. First summary posted below gave me evidences of directional selection, however, second one did not. 

1--------------
[PHASE 0.2] Standard model fit. Log-L = -2071.604680863982. Tree length = 0.1023981103897018 subs/site 
[PHASE 1.1] Model biased for A
[PHASE 1.2] Finished with the model biased for A. Log-L = -2071.605

	Bias term           =    1.000
	proportion          =    0.090
	Exp freq increase   =   -0.000%
	p-value    =    1.000
[PHASE 2.1] Model biased for C
[PHASE 2.2] Finished with the model biased for C. Log-L = -2071.605

	Bias term           =    1.000
	proportion          =    0.095
	Exp freq increase   =    0.000%
	p-value    =    1.000
[PHASE 3.1] Model biased for D
[PHASE 3.2] Finished with the model biased for D. Log-L = -2071.605

	Bias term           =    1.000
	proportion          =    0.087
	Exp freq increase   =    0.000%
	p-value    =    1.000
[PHASE 4.1] Model biased for E
[PHASE 4.2] Finished with the model biased for E. Log-L = -2069.890

	Bias term           =   32.993
	proportion          =    0.044
	Exp freq increase   =    8.673%
	p-value    =    0.330
[PHASE 5.1] Model biased for F
[PHASE 5.2] Finished with the model biased for F. Log-L = -2071.459

	Bias term           =    1.805
	proportion          =    0.500
	Exp freq increase   =    0.246%
	p-value    =    0.962
[PHASE 6.1] Model biased for G
[PHASE 6.2] Finished with the model biased for G. Log-L = -2071.605

	Bias term           =    1.000
	proportion          =    0.065
	Exp freq increase   =    0.000%
	p-value    =    1.000
[PHASE 7.1] Model biased for H
[PHASE 7.2] Finished with the model biased for H. Log-L = -2070.279

	Bias term           =    4.108
	proportion          =    0.500
	Exp freq increase   =    0.874%
	p-value    =    0.449
[PHASE 8.1] Model biased for I
[PHASE 8.2] Finished with the model biased for I. Log-L = -2071.605

	Bias term           =    1.000
	proportion          =    0.089
	Exp freq increase   =    0.000%
	p-value    =    1.000
[PHASE 9.1] Model biased for K
[PHASE 9.2] Finished with the model biased for K. Log-L = -2070.757

	Bias term           =    5.416
	proportion          =    0.178
	Exp freq increase   =    2.899%
	p-value    =    0.638
[PHASE 10.1] Model biased for L
[PHASE 10.2] Finished with the model biased for L. Log-L = -2069.699

	Bias term           =   55.785
	proportion          =    0.021
	Exp freq increase   =   16.773%
	p-value    =    0.283
[PHASE 11.1] Model biased for M
[PHASE 11.2] Finished with the model biased for M. Log-L = -2071.605

	Bias term           =    1.000
	proportion          =    0.094
	Exp freq increase   =    0.000%
	p-value    =    1.000
[PHASE 12.1] Model biased for N
[PHASE 12.2] Finished with the model biased for N. Log-L = -2071.279

	Bias term           =    1.608
	proportion          =    0.500
	Exp freq increase   =    0.841%
	p-value    =    0.884
[PHASE 13.1] Model biased for P
[PHASE 13.2] Finished with the model biased for P. Log-L = -2070.676

	Bias term           =  140.813
	proportion          =    0.026
	Exp freq increase   =   17.948%
	p-value    =    0.603
[PHASE 14.1] Model biased for Q
[PHASE 14.2] Finished with the model biased for Q. Log-L = -2071.605

	Bias term           =    1.000
	proportion          =    0.089
	Exp freq increase   =    0.000%
	p-value    =    1.000
[PHASE 15.1] Model biased for R
[PHASE 15.2] Finished with the model biased for R. Log-L = -2071.605

	Bias term           =    1.000
	proportion          =    0.090
	Exp freq increase   =    0.000%
	p-value    =    1.000
[PHASE 16.1] Model biased for S
[PHASE 16.2] Finished with the model biased for S. Log-L = -2070.330

	Bias term           =    2.390
	proportion          =    0.500
	Exp freq increase   =    1.732%
	p-value    =    0.466
[PHASE 17.1] Model biased for T
[PHASE 17.2] Finished with the model biased for T. Log-L = -2071.575

	Bias term           =    1.168
	proportion          =    0.500
	Exp freq increase   =    0.278%
	p-value    =    0.996
[PHASE 18.1] Model biased for V
[PHASE 18.2] Finished with the model biased for V. Log-L = -2063.334

	Bias term           =  623.107
	proportion          =    0.030
	Exp freq increase   =   42.321%
	p-value    =    0.001
[PHASE 19.1] Model biased for W
[PHASE 19.2] Finished with the model biased for W. Log-L = -2071.605

	Bias term           =    1.002
	proportion          =    0.500
	Exp freq increase   =    0.000%
	p-value    =    1.000
[PHASE 20.1] Model biased for Y
[PHASE 20.2] Finished with the model biased for Y. Log-L = -2071.604

	Bias term           =    1.046
	proportion          =    0.500
	Exp freq increase   =    0.017%
	p-value    =    1.000

Residues (and p-values) for which there is evidence of directional selection
	V : 0.0008780268812730307

The list of sites which show evidence of directional selection (Bayes Factor > 20)
together with the target residues and inferred substitution counts

Site        5 (max BF = 639602706704857.5)
 Preferred residues: V
 Substitution counts:
	F->I:    0/I->F:    1
Site       14 (max BF = 1e+026)
 Preferred residues: V
 Substitution counts:
	I->S:    1/S->I:    0
	I->V:    1/V->I:    0
Site       15 (max BF = 8.607910723857003e+016)
 Preferred residues: V
 Substitution counts:
	L->P:    0/P->L:    1
Site       16 (max BF = 8.12155379512935e+016)
 Preferred residues: V
 Substitution counts:
	A->T:    0/T->A:    1
Site       20 (max BF = 1.295896064723361e+017)
 Preferred residues: V
 Substitution counts:
	K->R:    1/R->K:    0
Site       55 (max BF = 1.225561808188351e+017)
 Preferred residues: V
 Substitution counts:
	N->T:    1/T->N:    0
Site       59 (max BF = 558745695929197.4)
 Preferred residues: V
 Substitution counts:
	I->V:    1/V->I:    0
Site       65 (max BF = 1.222826884585925e+017)
 Preferred residues: V
 Substitution counts:
	K->R:    0/R->K:    1
Site       67 (max BF = 637998928165998.5)
 Preferred residues: V
 Substitution counts:
	I->V:    0/V->I:    1
Site      122 (max BF = 7042782539154911)
 Preferred residues: V
 Substitution counts:
	E->K:    1/K->E:    0
Site      127 (max BF = 1e+026)
 Preferred residues: V
 Substitution counts:
	D->E:    2/E->D:    0
Site      130 (max BF = 715024736420549.2)
 Preferred residues: V
 Substitution counts:
	A->E:    1/E->A:    0
Site      143 (max BF = 1e+026)
 Preferred residues: V
 Substitution counts:
	A->S:    1/S->A:    0
	A->T:    1/T->A:    0
Site      146 (max BF = 714278796805250.9)
 Preferred residues: V
 Substitution counts:
	A->S:    1/S->A:    0
Site      148 (max BF = 1e+026)
 Preferred residues: V
 Substitution counts:
	K->R:    0/R->K:    2
Site      164 (max BF = 1.224393677423951e+017)
 Preferred residues: V
 Substitution counts:
	N->S:    1/S->N:    0
Site      169 (max BF = 712302584987980.8)
 Preferred residues: V
 Substitution counts:
	A->T:    1/T->A:    0
Site      172 (max BF = 1.526913621947671e+017)
 Preferred residues: V
 Substitution counts:
	H->Q:    0/Q->H:    1
Site      183 (max BF = 1.262667184651729e+017)
 Preferred residues: V
 Substitution counts:
	N->S:    1/S->N:    0
Site      186 (max BF = 829307333149652.9)
 Preferred residues: V
 Substitution counts:
	I->L:    0/L->I:    1
Site      195 (max BF = 7.205849922258153e+019)
 Preferred residues: V
 Substitution counts:
	G->V:    1/V->G:    0
Site      202 (max BF = 1e+026)
 Preferred residues: V
 Substitution counts:
	K->N:    1/N->K:    0
	K->T:    1/T->K:    0
Site      223 (max BF = 1e+026)
 Preferred residues: V
 Substitution counts:
	A->V:    1/V->A:    1
Site      228 (max BF = 707848666561243.4)
 Preferred residues: V
 Substitution counts:
	A->T:    1/T->A:    0
Site      229 (max BF = 1.133811271630368e+017)
 Preferred residues: V
 Substitution counts:
	R->S:    1/S->R:    0
Site      230 (max BF = 1.419449562318072e+017)
 Preferred residues: V
 Substitution counts:
	P->T:    0/T->P:    1
Site      231 (max BF = 1.535959704811468e+017)
 Preferred residues: V
 Substitution counts:
	P->Q:    0/Q->P:    1
Site      234 (max BF = 2039958330797352)
 Preferred residues: V
 Substitution counts:
	D->G:    0/G->D:    1
Site      235 (max BF = 1e+026)
 Preferred residues: V
 Substitution counts:
	I->L:    0/L->I:    1
	L->Q:    0/Q->L:    1
Site      285 (max BF = 1e+026)
 Preferred residues: V
 Substitution counts:
	D->N:    1/N->D:    0
	N->S:    1/S->N:    0
Site      291 (max BF = 1.450525411899565e+017)
 Preferred residues: V
 Substitution counts:
	H->Y:    0/Y->H:    1
Site      292 (max BF = 1.234091309136747e+017)
 Preferred residues: V
 Substitution counts:
	H->Y:    1/Y->H:    0
Site      294 (max BF = 2166760903680738)
 Preferred residues: V
 Substitution counts:
	G->R:    1/R->G:    0
Site      298 (max BF = 589169396675229.5)
 Preferred residues: V
 Substitution counts:
	I->T:    1/T->I:    0
Site      308 (max BF = 1.265836604251414e+017)
 Preferred residues: V
 Substitution counts:
	N->S:    0/S->N:    1
Site      321 (max BF = 1.222826884585925e+017)
 Preferred residues: V
 Substitution counts:
	K->R:    0/R->K:    1
Site      358 (max BF = 2.349797375664518e+016)
 Preferred residues: V
 Substitution counts:
	D->N:    1/N->D:    0
Site      374 (max BF = 659578347100276.9)
 Preferred residues: V
 Substitution counts:
	A->V:    1/V->A:    0
Site      410 (max BF = 1.229797020609275e+017)
 Preferred residues: V
 Substitution counts:
	N->T:    0/T->N:    1
Site      428 (max BF = 3.787345556844124e+016)
 Preferred residues: V
 Substitution counts:
	I->T:    0/T->I:    1
Site      430 (max BF = 1e+026)
 Preferred residues: V
 Substitution counts:
	L->V:    0/V->L:    2
Site      455 (max BF = 2.259072578959648e+016)
 Preferred residues: V
 Substitution counts:
	D->G:    1/G->D:    0
Site      484 (max BF = 2.349795358650545e+016)
 Preferred residues: V
 Substitution counts:
	D->N:    1/N->D:    0
Site      485 (max BF = 2.349794648143082e+016)
 Preferred residues: V
 Substitution counts:
	D->N:    1/N->D:    0
Site      506 (max BF = 713906356652857.1)
 Preferred residues: V
 Substitution counts:
	I->M:    0/M->I:    1
Site      536 (max BF = 597690226394443.8)
 Preferred residues: V
 Substitution counts:
	I->M:    1/M->I:    0
Site      541 (max BF = 5.17198567045867e+018)
 Preferred residues: V
 Substitution counts:
	A->V:    1/V->A:    0


2----------
[PHASE 0.2] Standard model fit. Log-L = -2073.967894118765. Tree length = 0.1013999309743295 subs/site 
[PHASE 1.1] Model biased for A
[PHASE 1.2] Finished with the model biased for A. Log-L = -2073.968

	Bias term           =    1.000
	proportion          =    0.094
	Exp freq increase   =   -0.000%
	p-value    =    1.000
[PHASE 2.1] Model biased for C
[PHASE 2.2] Finished with the model biased for C. Log-L = -2073.968

	Bias term           =    1.000
	proportion          =    0.095
	Exp freq increase   =   -0.000%
	p-value    =    1.000
[PHASE 3.1] Model biased for D
[PHASE 3.2] Finished with the model biased for D. Log-L = -2073.968

	Bias term           =    1.000
	proportion          =    0.090
	Exp freq increase   =    0.000%
	p-value    =    1.000
[PHASE 4.1] Model biased for E
[PHASE 4.2] Finished with the model biased for E. Log-L = -2072.248

	Bias term           =   33.349
	proportion          =    0.044
	Exp freq increase   =    8.671%
	p-value    =    0.329
[PHASE 5.1] Model biased for F
[PHASE 5.2] Finished with the model biased for F. Log-L = -2073.823

	Bias term           =    1.802
	proportion          =    0.500
	Exp freq increase   =    0.243%
	p-value    =    0.962
[PHASE 6.1] Model biased for G
[PHASE 6.2] Finished with the model biased for G. Log-L = -2073.968

	Bias term           =    1.000
	proportion          =    0.091
	Exp freq increase   =   -0.000%
	p-value    =    1.000
[PHASE 7.1] Model biased for H
[PHASE 7.2] Finished with the model biased for H. Log-L = -2072.623

	Bias term           =    4.158
	proportion          =    0.500
	Exp freq increase   =    0.878%
	p-value    =    0.442
[PHASE 8.1] Model biased for I
[PHASE 8.2] Finished with the model biased for I. Log-L = -2073.968

	Bias term           =    1.000
	proportion          =    0.100
	Exp freq increase   =    0.000%
	p-value    =    1.000
[PHASE 9.1] Model biased for K
[PHASE 9.2] Finished with the model biased for K. Log-L = -2073.117

	Bias term           =    5.436
	proportion          =    0.177
	Exp freq increase   =    2.887%
	p-value    =    0.637
[PHASE 10.1] Model biased for L
[PHASE 10.2] Finished with the model biased for L. Log-L = -2072.059

	Bias term           =   56.109
	proportion          =    0.021
	Exp freq increase   =   16.655%
	p-value    =    0.282


[PHASE 11.1] Model biased for M
[PHASE 11.2] Finished with the model biased for M. Log-L = -2073.968

	Bias term           =    1.000
	proportion          =    0.091
	Exp freq increase   =   -0.000%
	p-value    =    1.000

[PHASE 12.1] Model biased for N
[PHASE 12.2] Finished with the model biased for N. Log-L = -2073.638

	Bias term           =    1.613
	proportion          =    0.500
	Exp freq increase   =    0.841%
	p-value    =    0.883
[PHASE 13.1] Model biased for P
[PHASE 13.2] Finished with the model biased for P. Log-L = -2073.029

	Bias term           =  143.810
	proportion          =    0.026
	Exp freq increase   =   18.116%
	p-value    =    0.598
[PHASE 14.1] Model biased for Q
[PHASE 14.2] Finished with the model biased for Q. Log-L = -2073.968

	Bias term           =    1.000
	proportion          =    0.076
	Exp freq increase   =   -0.000%
	p-value    =    1.000
[PHASE 15.1] Model biased for R
[PHASE 15.2] Finished with the model biased for R. Log-L = -2073.968

	Bias term           =    1.000
	proportion          =    0.087
	Exp freq increase   =   -0.000%
	p-value    =    1.000
[PHASE 16.1] Model biased for S
[PHASE 16.2] Finished with the model biased for S. Log-L = -2072.690

	Bias term           =    2.394
	proportion          =    0.500
	Exp freq increase   =    1.723%
	p-value    =    0.465
[PHASE 17.1] Model biased for T
[PHASE 17.2] Finished with the model biased for T. Log-L = -2073.840

	Bias term           =    1.356
	proportion          =    0.500
	Exp freq increase   =    0.561%
	p-value    =    0.968
[PHASE 18.1] Model biased for V
[PHASE 18.2] Finished with the model biased for V. Log-L = -2069.703

	Bias term           =  381.707
	proportion          =    0.036
	Exp freq increase   =   37.060%
	p-value    =    0.036
[PHASE 19.1] Model biased for W
[PHASE 19.2] Finished with the model biased for W. Log-L = -2073.968

	Bias term           =    1.002
	proportion          =    0.500
	Exp freq increase   =    0.000%
	p-value    =    1.000

[PHASE 20.1] Model biased for Y
[PHASE 20.2] Finished with the model biased for Y. Log-L = -2073.968

	Bias term           =    1.030
	proportion          =    0.490
	Exp freq increase   =    0.011%
	p-value    =    1.000


Residues (and p-values) for which there is evidence of directional selection

Cheers,
Sung

**Comment by sungml92** [comment]
Dear Sergei,

After above runs, I also run same data in two different running environment; datamonkey, and hyphy gui. For both runs, I have my root fixed (same root is used in both run) and used beta-gamma (4). 
Both datamonkey and hyphy showed "I" has an evidence of directional selection. However, there was a difference in list of sites. Hyphy indicated that site 16, and 334 show evidence of directional selection (there is no "I" in site 334), where datamonkey presented site 345 for having the evidence.
Is this possibly an error?

Furthermore, I am wondering if my previous summaries pose any undesirable outputs. 

Thank you in advance in viewing and answering my questions. 

Cheers,
Sung
