### ISSUE TITLE
Internal error message in Nielsenyang.bf

### ISSUE THREAD

**Issue by aniolv** [veg/hyphy#444]
Dear all,

My name is Aniol Valera.  I am a student of the Msc in Bioinformatics, in Universitat Autonoma de Barcelona. I have been using the Nielsenyang.bf script for detection of positive selection in a set of sequences. While performing a M7-M8 test I found that the program stopped running and said:

"Internal error in _LikelihoodFunction::GradientLocateTheBump".

I had ran the same sequences in M1 and M2 without any trouble. I have never seen this error. I have tested both models in over 3000 alignments, and I only found trouble in 4 of them. I haven't found any explanation, neither looking at the alignment nor searching for internet, and I thought that the best I could do is to ask you here.  I can provide you the Nexus file prepared to run it and the alignments, if you want them.  Thank you, and sorry for the inconvenience.

 Aniol

**Comment by spond** [comment]
Dear @aniolv,

You may be using an old version of HyPhy; the error you see is an internal consistency check failure (but not necessarily an error), and in newer versions of HyPhy this error is now a warning. Please try using the latest release of HyPhy (2.2.6 or even 2.3-alpha).

Sergei

**Comment by aniolv** [comment]
Thanks Sergei! I will try the new version of the package. As I am quite new in all the matters related to evolutionary models and positive selection,  I have another question. I would know if the models M1a and M2a are available in the Nielsenyang.bf script. I am asking this because i am getting a significantly higher number of proteins under positive selection when using M7M8 than M1M2 (these are options 8 and 9, and 2 and 3, in the Nielsenyang.bf model choosing step), and as far as I know, the M1M2 models were improved into M1aM2a. I don't think that is recombination giving false positives because I have used in each alignment GARD.bf , with a previous step of choosing a nucleotide substitution model and the post analysis step that is GARDProcessor.bf. Thanks again for your help, and thanks a lot for the HYPHY package in general! 

Aniol

**Comment by spond** [comment]
Dear @aniolv,

NielsenYang implements relatively outdated models which we no longer recommend as "front-line" tools for selection testing. Please see http://bit.ly/pond-hutch-2015 for an overview of what we do recommend. 

The most direct analog of NY site-level testing would be FUBAR.

Cheers,
Sergei

**Comment by aniolv** [comment]
Thanks a lot Sergei! As far as I have understood, one of the advantages of FUBAR is to not having the issue of selecting models. Only a last question, that I couldn't find in the paper. As models in NY.bf have a log-likelihood value in the output, that could be compared to the chi square distribution (depending on the models and their degrees of freedom), I would know if there is a similar result in FUBAR that could tell if the results are statistically significant or not. Thanks in advance for your help.

Aniol

**Comment by spond** [comment]
Dear @aniolv,

The likelihood ratio test is not necessary for FUBAR.

Sergei

**Comment by aniolv** [comment]
Thanks for your quick answers Sergei! They have been really helpful.

Aniol
