### ISSUE TITLE
Python library installer fails on Linux in v2.2.6

### ISSUE THREAD

**Issue by rhliang** [veg/hyphy#446]
We're using the Python library in some of our work, and when I tried to compile it from the 2.2.6 source, it failed to compile on CentOS 6.  The offending code appears to be line 52 of `src/lib/setup.py`:

```
major, minor, patch = mac_ver()[0].split('.')
```

This line fails because `mac_ver()[0]` returns the empty string.  It looks like this code is still present in master as of now.

**Comment by stevenweaver** [comment]
Hello rhliang, 

We are currently working on removing the python library from the master branch of HyPhy. 
The supported version of the HyPhy python library is now located here:

https://github.com/veg/hyphy-python

Can you please try that repo and see if your problem still persists before moving further?

Best,
Steven

**Comment by rhliang** [comment]
Cool, thanks.  I tried compiling that and it worked fine.  Sorry for the trouble!
