### ISSUE TITLE
Is GARD running?

### ISSUE THREAD

**Issue by antony03** [veg/hyphy#451]
Hi,

I am trying to run GARD on several alignments before running PARRIS.
I launched GARD on a test alignment file as follows:

avincent@Grumpy:~/Desktop/SOFTWARE/hyphy-2.2.4$

 mpirun -np 8 ./HYPHYMPI

       /HYPHY 2.220160718beta(MPI) for Linux on x86_64\       
***************** TYPES OF STANDARD ANALYSES *****************

	(1) Basic Analyses
	(2) Codon Selection Analyses
	(3) Compartmentalization
	(4) Data File Tools
	(5) Miscellaneous
	(6) Model Comparison
	(7) Kernel Analysis Tools
	(8) Molecular Clock
	(9) Phylogeny Reconstruction
	(10) Positive Selection
	(11) Recombination
	(12) Selection/Recombination
	(13) Relative Rate
	(14) Relative Ratio
	(15) Substitution Rates

11
 Please select type of analyses you want to list (or press ENTER to process custom batch file):

 ***************** FILES IN 'Recombination' ***************** 

	(1) Screen an alignment using GARD (requires an MPI environment).
	(2) Process GARD results.
	(3) A Likelihood Ratio Test to detect conflicting phylogenetic signal Huelsenbeck and Bull, 1996. [Contributed by Olivier Fedrigo].
	(4) Search an alignment for a single breakpoint.
	(5) Plot genetic distances (similarity) of one sequence against all others in an alignment, using a sliding window. Optionally, determine NJ-based clustering and bootstrap support in every window. This is a HyPhy adaptation of the excellent (but Windows only tool) SimPlot (and/or VarPlot) written by Stuart Ray (http://sray.med.som.jhmi.edu/SCRoftware/simplot/)

1
 Please select the file you want to use (or press ENTER to return to the list of analysis types):Initialized GARD on 8 MPI nodes.
Population size is 14 models

seq.fas
/home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/installation_final/lib/hyphy/TemplateBatchFiles/Nucleotide file to screen::

It seems to calculate on 8 threads, but nothing happens. My test file is simply a small alignment containing 18 taxa. Do I miss something?
Thank you!

**Comment by stevenweaver** [comment]
Hello @antony03, 

After supplying your nucleotide file to screen, you should receive the following prompt: 
`Please enter a 6 character model designation (e.g:010010 defines HKY85):`

A known issue at the moment is that some users have to enter the path to the nucleotide file twice before the program will continue. Can you please try that?

Best,
Steven

**Comment by antony03** [comment]
Thank you ! It works when I enter twice the input file. However, I have a new problem. I want to launch it without the interactive menu. Consequently, I tried with the following file:

inputRedirect = {};
inputRedirect["01"] = "/home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/seq.fas";
inputRedirect["02"] = "012345"; 
inputRedirect["03"] = "2"; 
inputRedirect["04"] = "3"; 
inputRedirect["05"] = "/home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/test";  

ExecuteAFile("/home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/res/TemplateBatchFiles/GARD.bf", inputRedirect);
 

and obtained the following output:

avincent@Grumpy:~/Desktop/SOFTWARE/hyphy-2.2.4$ mpirun -np 2 ./HYPHYMPI prova.bfInitialized GARD on 2 MPI nodes.
Population size is 2 models

Please enter a 6 character model designation (e.g:010010 defines HKY85):Error:

Master node received an error:Not a valid option: '2' passed to Choice List 'Rate variation options' using redirected stdin input

Function call stack
1 : Choice List for Rate variation options with choice list:SKIP_NONE. Store result in rvChoice
	Standard input redirect:
		04 : 3
		05 : /home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/test
		-------
2 : ExecuteAFile from file "/home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/res/TemplateBatchFiles/GARD.bf" using basepath /home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/. reading input from inputRedirect
{"01":"/home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/seq.fas",
"02":"012345",
"03":"2",
"04":"3",
"05":"/home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/test"}
-------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD 
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

 

Knowing my previous issue, I tried like this:

inputRedirect = {};
inputRedirect["01"] = "/home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/seq.fas";
inputRedirect["02"] = "/home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/seq.fas";
inputRedirect["03"] = "012345"; 
inputRedirect["04"] = "2"; 
inputRedirect["05"] = "3"; 
inputRedirect["06"] = "/home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/test";  

ExecuteAFile("/home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/res/TemplateBatchFiles/GARD.bf", inputRedirect);
 

And again:

avincent@Grumpy:~/Desktop/SOFTWARE/hyphy-2.2.4$ mpirun -np 2 ./HYPHYMPI prova.bfInitialized GARD on 2 MPI nodes.
Population size is 2 models

Please enter a 6 character model designation (e.g:010010 defines HKY85):
Please enter a 6 character model designation (e.g:010010 defines HKY85):Error:

Master node received an error:Not a valid option: '2' passed to Choice List 'Rate variation options' using redirected stdin input

Function call stack
1 : Choice List for Rate variation options with choice list:SKIP_NONE. Store result in rvChoice
	Standard input redirect:
		05 : 3
		06 : /home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/test
		-------
2 : ExecuteAFile from file "/home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/res/TemplateBatchFiles/GARD.bf" using basepath /home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/. reading input from inputRedirect
{"01":"/home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/seq.fas",
"02":"/home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/seq.fas",
"03":"012345",
"04":"2",
"05":"3",
"06":"/home/avincent/Desktop/SOFTWARE/hyphy-2.2.4/test"}
-------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD 
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

 
Have you an idea on how to solve this new issue?

Thank you for your help!

**Comment by antony03** [comment]
Thank you, it works perfectly if I enter the file name twice.

Sincerely,

Antony
