### ISSUE TITLE
IFEL output interpretation

### ISSUE THREAD

**Issue by omiccismith** [veg/hyphy#452]
Hello,

I am new to using HyPhy, and am using IFEL to analyze particular mitochondrial genes for selection. I am working within a single species, and thus am interested in analyzing the internal branches. I ran the genes through HyPhy with the IFEL method analyzing internal branches without branch corrections, and yet I am a bit confused on how to interpret the output. I understand that the program denotes sites of positive and negative selection, but I am unsure of the significance of the other parameters and how they are presented in the FEL results chart and graph at the end. Are the values averaged at all? 

I have searched the message boards, done the tutorial, and have read the Pond et al. 2006 paper on IFEL (http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.0020062). I understand that figure 1 and 2 from this paper are representing the output chart in some way, but I am not sure how this graph was produced, and what parameters it is actually showing. Also, I was wondering if you would be able to clarify where the pA and pB values mentioned in the paper would be located in my output analysis. 

Any help or advice would be greatly appreciated. Thank you.

**Comment by spond** [comment]
Dear @omiccismith,

For each site, IFEL produces three estimates

1. &alpha; : a site-level synonymous rate, which can also be viewed as the baseline rate of the site relative to the alignment-wide rate
2. &beta; : a site-level non-synonymous rate estimate for internal branches only
3. &beta;<sub>other</sub>: a site-level non-synonymous rate estimate for terminal branches only (this is a nuisance parameter)

The test for positive/negative selection compares &beta; to &alpha; and reports a significant result based on whether or not the likelihood ratio test can reject the null hypothesis that &alpha; = &beta; 

p<sub>A/B</sub> values reported in the paper are produced by a different test which is alignment-wide. I am not sure we ever included this test in the distribution. If you are interested, I'll see if I can dig out the old files implementing it.

The 

Sergei

**Comment by omiccismith** [comment]
Thank you for clarifying this. Very helpful information.
