### ISSUE TITLE
"error: narrowing conversion" on compile

### ISSUE THREAD

**Issue by lourencojml** [veg/hyphy#453]
Hi

I have just compiled HyPhy2.2.6 target GTK on my desktop machine with no problems. However, when I try to do the same on my laptop I get several "error: narrowing conversion". Here is an example:

`[ 28%] Building CXX object CMakeFiles/HYPHYGTK.dir/src/gui/HYChartWindow.cpp.o
/home/wolf3239/Downloads/hyphy/src/gui/HYChartWindow.cpp:113:1: error: narrowing conversion of ‘2.3969999999999999e+2’ from ‘double’ to ‘unsigned char’ inside { } [-Wnarrowing]
 };
 ^
/home/wolf3239/Downloads/hyphy/src/gui/HYChartWindow.cpp:113:1: error: narrowing conversion of ‘3.0599999999999998e+1’ from ‘double’ to ‘unsigned char’ inside { } [-Wnarrowing]
/home/wolf3239/Downloads/hyphy/src/gui/HYChartWindow.cpp:113:1: error: narrowing conversion of ‘2.8050000000000001e+1’ from ‘double’ to ‘unsigned char’ inside { } [-Wnarrowing]
/home/wolf3239/Downloads/hyphy/src/gui/HYChartWindow.cpp:113:1: error: narrowing conversion of ‘1.0455e+2’ from ‘double’ to ‘unsigned char’ inside { } [-Wnarrowing]`

The cmake step had no errors and I am unsure why I would get an error on narrowing conversion at this point, when it successfully passes warnings on the same issue before the 28% mark.

Any help is welcome. Thanks.
JL

**Comment by stevenweaver** [comment]
Hi JL, 

May I ask which distribution of Linux you are using on your laptop? Is it the same as your desktop?

Best,
Steven

**Comment by lourencojml** [comment]
Hi Steven, 

Sorry I should have mentioned that. No, I am using Ubuntu 16 on the desktop and Fedora 24 on the laptop. I cant check the desktop one ATM, but Fedora is running gcc 6.1.1. What sort of differences are we looking for?

Thanks

**Comment by stevenweaver** [comment]
JL,

The default gcc version that comes with each distribution was the difference I was looking for. We haven't tested HyPhy with gcc 6 quite yet. I will see if I can recreate the bug with gcc 6. 

Thanks

**Comment by lourencojml** [comment]
I see... I can always try to force a lower version of gcc, tho ill have too look into how to do it. 

Thanks

**Comment by stevenweaver** [comment]
I'm currently installing gcc-6. Generally speaking, newer versions of gcc allow flags that ignore specific exceptions that have been implemented between major versions (a narrowing conversion isn't a major threat here considering the computation is just for rendering graphics) .  If that is the case here, I should be able to make a quick fix between 1-2 days.

**Comment by lourencojml** [comment]
Thanks Steven

**Comment by stevenweaver** [comment]
Hello JL, 

The fix is in the latest commit on the master branch. 
You can use the following link to download https://github.com/veg/hyphy/archive/master.zip

Best,
Steven

**Comment by lourencojml** [comment]
Hey Steven,

I can confirm that it works. Thanks for your time!
