### ISSUE TITLE
Missing Branches in BUSTED

### ISSUE THREAD

**Issue by jwconnolly** [veg/hyphy#455]
Hi guys, I recently ran Busted and selected 4 branches as the foreground but when I get the results I only see 2 Foreground branch sets displayed. Am I missing/misunderstanding something here?
here is the test: http://test.datamonkey.org/busted/5795639217fb77180b073dd7

**Comment by spond** [comment]
Hi @jwconnolly,

I count 4 branches in the foreground set:

```
CPIJ015075_RA
CPIJ011244_RA
HMEL006610_RA
AGAP010691_RA
```

Is that not what you requested when you submitted the analysis?

Sergei

**Comment by jwconnolly** [comment]
That is correct, but I only see 2 Foreground values displayed on the "Model Fits" chart. Should there be 2 other FG values corresponding to the other branches I selected?

**Comment by spond** [comment]
Dear @jwconnolly,

That is also correct (see comment below) -- all branches in the FG/BG groups **share** &omega; values. The two sets of values relate to models (unconstrained / constrained).

Sergei

@stevenweaver : can you please check the row ordering in the model fit table? It doesn't seem right.

**Comment by jwconnolly** [comment]
Ahh that makes much more sense, the ordering threw me off thank you!

**Comment by stevenweaver** [comment]
@spond - I created a new ticket (veg/hyphy-vision#14) in order to address table ordering.
