### ISSUE TITLE
Weird Datamonkey error

### ISSUE THREAD

**Issue by VinnyLynch** [veg/hyphy#456]
Hey Sergei,

I'm having a strange Datamonkey error with ASR (AA sequences). If I try to add site-to-site variation (either General Discrete or Beta-Gamma) I get the following error:

Execution summary
Ancestral state reconstrutction was performed in 00:00:11 wallclock time using User Tree(s) (view as [Newick] or [PDF]), rooted on SLOTH. Log(L) under the JTT (Jones,Taylor,Thornton)+F model is -2879.18.

9 sequences Error: , is out of context:EPHANT,?(WOOLLY_MAMMOTH,ASIAN_ELEPHANT)N Function call stack 1 : Build Tree _TT from string treeS ------- 2 : Print to File lfFile:CLEAR_FILE _returnTreePS(consensusTree,"",1) ------- 3 : ExecuteAFile from file "ASR_Processor.ibf" using basepath /var/lib/datamonkey/share/BFs/. -------

Not quite sure what to make of it.

Vinny

(Dataset is below.)

> SLOTH
> MEEPQSDLSIEPPLSQETFSDLWKLLPQNNVLSPSLS???DYLLLPEDV??????????????ACAP???APAA?TPATPWPLSSSVPSQKEYPG?YNFQLGFLRSGTAKSVTCTY?PALNKLFCQLAKTCPVQLWVTS?PPPG?RVRAMAIY?KSE?MTE?V?RCPHHERC?????????QHLIRVEGNPRAEYWDDSNTFRHSVVVP?EM??V?S?CTTIHYNFMCN?SCMGGMNRRPILTIITLEDSSGNLL?RG??EVRICACPGRDRRTEEENFHKKGEPCHEPPAGTTKRALATTTGSSPPAKKK?LDGEYFTPQIRGHERFK?FRELNEALELKDAQAGKEP?G?R?HS???KSKKGQSTSRHKKLMFKREGPDSD
> 
> CAPE_ELEPHANT_SHREW
> MEESQLDLNMELPLSQESFSYLWE?????????????????????????????????????????????????APVPATSWSLSSSVPSQKTYPGTYGFHLGFLQSGTAKSVTCTYSPDLNKLFCQLAKTCPVQLWVTSPPPPGTRVRTMAIYKKLEHMTEIVRRCPHHERNSDSDGLAPPQHLIRVEGNLRAEYLEDSTTLRHSVVVPYEPPEVGSDCTTIHYNFMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDRRTEEENFHKKEKLCPKPPPRNTKQALLS???VSTQPKKK??SEEYFTLQIRGYKRFRMFQELNEALEMKDA???ADPDGTRAHSSPPKTKKGQSTSCHKTANFKREGPDSD
> 
> AARDVARK
> MEEPQSDLCTDLPLSQETFSYLWELLPENPVLSPSIPPAADNLLFPEVTANWLDEVG????????????????APTPATSWTLPSCVPSQKTYPGTYGFRLGFLQSGTAKSVTCTYSPDLNKLFCQLAKTCPVQLWVTSPPPPGSRVRTMAIYKKSEHMMEVVKRCPHHERCSDSDGLAPPQHLIRVEGNQRADYQEDNVTLRHSVVVPYEPPEVGSDCTTIHYNFMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDRRTEEENFHKKEEPSPKPPPRSTKRALPPSTSSSTQPKKKLLDEEYFTLQIRGRERFKMFLELNEALELKDAQAGKEPEGSRAHSSLPKSKKGQSTSRHKKTSFKREGPDSD
> 
> TENREC
> MEDSQSDMNTDLPLSQETFSYLWELLPEDSVLSASIPSEVDSLPLQDVLSNWL??????????????????PGPPTPAPSWTLSSSVPSQKTYPGTYGFTLGFLHSGTAKSVTCTYSPDLNKLFCQLAKTCPVQLWVTSPPPPGTRVRTMAIYKKSEHMTEVVKRCPHHERCSDIDALAPPQHLIRVEGNQRAEYLEDNVTLRHSVVVPYEPPEVGADCTTIHYNFMCNSSCMGGMNRRPILTIISLEDTSGNLLGRNSFEVRICACPGRDRRTEEENFHKNDEPCPRPPPQSTKRALPTSTGSSTQPKKKPLDEEYYTLQIRGRERFKMFWELNEALELRDAQAGKEPEGSQAHSSPLKAKKRPSTSRHKKTTFKKEGPDSD
> 
> CAPE_GOLDEN_MOLE
> MEDPQSDLGTDLPLSQETFSYLWELLPKDKVLSLSQPPAVDNLLLPEASTNSLGEVV????????????PQQGAPTPATSWTLSSSVPSQKSYPGTYGFSLGFLHSGTAKSVTCTYSPDLNKLFCQLAKTCPVQLWVTSPPPTGTRVRTMAIYKKSEHMTEVVKRCPHHERSSDSDGLAPPQHLIRVEGNLRAEYLEDSTTLRHSVVVPYEPPEVGSECTTIHYNYMCNSSCMGGMNRRPILTIVTLEDSSGNLLGRSSFEVRVCACPGRDRRTEEDNFHKNVEPGPKSPPGSTKRTRPTSTSFFTQTKKKMLDEEYFTLQIRGRERFKMFLELNEALELKDAQAGKEPEESRANSSPMKSKKGQSTSRHKKTLFKSEGPDSD
> 
> ARMADILLO
> MEEPPSDLSIEAPLSQETFSDLWKLLPQNNVLSPSLS??MEDLLLSDDVTSWFGQDE????PEAPAPTTPAPAAPTPATPWPLSSSVPSQKEYPGDYNFRLGFLRSGTAKSVTCTYSPILNKLFCQLAKTCPVQLWVNSPPPPGARVRAMAVYKKSEHMTEVVRRCPHHERCSDGDGLAPPQHLIRVEGNLHAEYLDDINTFRHSVVVPYEMPEVGADCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSNGNLLGRRSFEVRVCACPGRDRRNEEDNFRKKGEPCPEPPVGTTKRTLPTTTSSSPPPKKKPMDGEYFTLQIRGRERFEMFRELNEALELKDAQTGKEPEGSRAHTSYLKSKKGQSTSRHKKLLFKREAPDSD
> 
> WEST_INDIAN_MANATEE
> MEEPQSDLSTELPLSQETFSYLWELLPEKPVLSPSLPPAVDDLLLTEDAATWLGQVGAQEISAGPAPATPTPVALIPATSWTLSSSVPSQKTYPGTYGFRLGFLHSGTAKSVTCTYSPDLNKLFCQLAKTCPVQLWVTSPPPPGTRVRTMAIYKKSEHMTEVVKRCPHHERCSDSDGLAPPQHLIRVEGNLRAEYLEDSVTLRHSVVVPYEPPEVGSDCTTIHFNFMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRICACPGRDRRTEEENFHKKGETSPEPPPRSTKRALPTNTSSCTQPKKKPLDEEYFTLQIRGRERFKMFLELNEALELKDAQAGKEPEGSRAHSSPPKSKKGQSTSRHKKLMFKREGPDSD
> 
> ROCK_HYRAX
> MEETQADLGTELPLSQETFSDFWDLLPPNLHLSSSIPLAVDDLLLSEGPANWPDKPEAEETSANPIPTIPTPVAPIPATSWTLSSSVPSQTTYPGDYGFHLGFLHSGTAKSVTCTYSPDLNKLFCQLAKTCPVQLWVTSSPPPGTCVRTMAIYKKSEHMTEVVKRCPHHERCSDNDGLAPPQHLIRVEGNQRAKYLEDSATLRHSVVVPYEPPEVGSEYTTIHFNFMCNSSCMGGMNRRPILTIITLEDSSGRLLGRNSFEVRICACPGRDRRTEEENFHKKGEPCPEPPTGNTKRALPTNTSSSSQPKKKPMDEECFTLQIRGWERFRMFQELNEALELKDAQAGREPEGSRPHSSTPKSKKGQSTSRHKKLMFKREGPDSD
> 
> ASIAN_ELEPHANT
> MEEPQSDLSTELPLSQETFSYLGKLLPEKLVLSPSLSPAMDDLLLSEDTANWLGQVEAQGMSTTPAPATPTPVAPAPATSWTLSSSVPSQKTYPGTYGFRLGFLHSGTAKSVTCTYSPDLNKLFCQLAKTCPVQLWVASPPPPGTRVRTMAIYKKSEHMTEVVKRCPHHERCSDSDGLAPPQHLIRVEGNLRAEYLEDSITLRHSVVVPYEPPEVGSDCTTIHFNFMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRICACPGRDRRTEEENFHKKGEPCPEPPPRSTKRALPTSTSSSTQPKKKPLDEKYFTLQIRGHECFKMFLELNEALELKDAQAGKQPEGSRAHSSPSKSKKGQSTSRHKKPMFKREG?DSD
> 
> WOOLLY_MAMMOTH
> MEEPQSDLSTELPLSQETFSYLGKLLPEKLVLSPSLSPAMDDLLLSEDTANWLGQVEAQGMSTTPAPATPTPGAPAPATSWTLSSSVPSQKTYPGTYGFRLGFLHSGTAKSVTCTYSPDLNKLFCQLAKTCPVQLWVASPPPPGTRVRTMAIYKKSEHMTEVVK?CPHHERCSDSDGLAPPQHLIRVEGNLRAEYLEDSI?LRHSVVVPYEPPEVGSDCTTIHFNFMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRICACPGRDRRTEEENFHKKGEPCPEPPPRSTKRALPTSTSSSTQPKKKPLDEKYFTLQIRGRERFKMFLELNEALELKDAQAGKEPEGSRAHSSPSKSKKGQSTSRHKKPMFKREGPDSD
> 
> AFRICAN_ELEPHANT
> MEEPQSDLSTELPLSQETFSYLWELLPENPVLSPTLPPAMDDLLLSEDTANWLGQVEAQGMSTTPAPATPTPVAPAPATSWTLSSSVPSQKTYPGTYGFRLGFLHSGTAKSVTCTYSPDLNKLFCQLAKTCPVQLWVASPPPPGTRVRTMAIYKKSEHMTEVVKRCPHHERCSDSDGLAPPQHLIRVEGNLRAEYLEDSITLRHSVVVPYEPPEVGSDCTTIHFNFMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRICACPGRDRRTEEENFHKKGEPCPEPPPRSTKRALPTNTSSSTQPKKKPLDEEYFTLQIRGRERFKMFLELNEALELKDAQAGKEPEGSRAHSSPSKSKKGQSTSRHKKPMFKREGPDSD

(((((AFRICAN_ELEPHANT,(WOOLLY_MAMMOTH,ASIAN_ELEPHANT)),ROCK_HYRAX),WEST_INDIAN_MANATEE),((CAPE_ELEPHANT_SHREW,(CAPE_GOLDEN_MOLE,TENREC)),AARDVARK)),(SLOTH,ARMADILLO))

**Comment by stevenweaver** [comment]
Hello @VinnyLynch ,

This is indeed a bug. The results file is in a slightly different format when using the parameters provided, which causes an error with the newick string being parsed. 

I will discuss with Sergei to schedule a time to fix this. If you need help with results in the meantime, I can provide them if you send me the job number by email : sweaver@temple.edu. 

Best,
Steven
