### ISSUE TITLE
Interpreting DEPS results

### ISSUE THREAD

**Issue by sungml92** [veg/hyphy#457]
To Whom It May Concern,

Before I start, I appreciate everyone reading and leaving a comment on this thread. Furthermore, I apologizes in advance if anyone feels this question is redundant.

I have 79 protein sequences with length of 470 amino acids. After filtering out all redundant sequences, each protein sequences is unique. On average, they are highly similar sequences ranging from 96~99% overlap. Using these sequences, I generate a phylogenetic trees with protein sequence using RaxML PROTGAMMAFLU (protein model was determined using MODEL in datamonkey.org). Using the sequences and the tree, I ran a directional evolution of protein sequences in hyphy gui and datamonkey. For both runs, I had my root fixed and used beta-gamma (4) as parameter. 

After running, I obtained different results from each running environment. 
For datamonkey, the output selected amino acid "I" has evidence of directional evolution and affected site was 345 with EBF over 10^5. 
For hyphy, the output selected the same amino acid, however, listed different sites for selection. It selected 16 and 334 with BF 1066 and 130 respectively. Interestingly, no substitution in site 334 are from or toward Ile. 

At this point, I am confused which result is accurate and why they are giving out different results.
Is there a way to manage this? I am attaching summary file of both result from datamonkey and hyphy.

datamonkey 
[datamonkey_sum.txt](https://github.com/veg/hyphy/files/387773/datamonkey_sum.txt)

hyphy
[hyphy_sum.txt](https://github.com/veg/hyphy/files/387774/hyphy_sum.txt)

Sincerely,
Sung

**Comment by spond** [comment]
Dear @sungml92,

The Datamonkey result makes more sense; there could be a bug in the post-processing code in HyPhy. The Datamonkey implementation is newer and more tested. In any case, we are about to release a method that will be much faster and more robust that DEPS (FADE). 

Sorry for the long delay in responding.

Best,
Sergei

**Comment by sungml92** [comment]
Dear Sergei,

Thank you for your response. I will wait for the new method.

Cheers,
Sung
