### ISSUE TITLE
How to input a Newick user tree in Datamonkey?

### ISSUE THREAD

**Issue by btalbot4** [veg/hyphy#458]
Hi, I am trying to use Datamonkey to detect positive selection, but I do not know how to input a user tree. I have a Newick tree string, and I use an alignment in fasta format. How should I proceed to use both in my analyses?

Thanks,
Ben

**Comment by stevenweaver** [comment]
Hello Ben, 
If you place the Newick tree string at the very end of the FASTA file, Datamonkey will recognize the user tree. 

Example:

[Flu.txt](https://github.com/veg/hyphy/files/400299/Flu.txt)

**Comment by btalbot4** [comment]
Thank you Steven. However, when I input my file, it still doesn't give me the option of using the user tree. Can you point to me on what's wrong in my file? Thanks

[nitrophorin_aligned.txt](https://github.com/veg/hyphy/files/401810/nitrophorin_aligned.txt)

**Comment by btalbot4** [comment]
Great, thanks!

Cheers,
Ben
