### ISSUE TITLE
Skipping alignment step on SCUEAL

### ISSUE THREAD

**Issue by GonzaloYebra** [veg/hyphy#459]
Hi there!

I'm running SCUEAL locally and managed to use it to analyse HIV full-length genomes. However, some of my query sequences contain gappy regions, and in many cases SCUEAL infers recombination with outgroup subtypes (H, J, etc) in these regions. I want to check if this is actually due to a poor alignment because of the presence of these gaps, so I thought that I might align manually these sequences with the reference alignment I created, instead of letting SCUEAL do the alignment. 

The thing is, I can't find any obvious option in the SCUEAL bash files to avoid the alignment step. Could you please give me some advice with this?

Thanks in advance!

Gonzalo

**Comment by spond** [comment]
Dear Gonzalo,

If you have a pre-made alignment of N sequences, of which N-1 are reference sequences, and 1 is a query, you should be able to run `TopLevel/InPlaceScreen.bf` to run the algorithm directly on that alignment. You will need to supply the reference tree, which is tricky if you have recombinant references (i.e. CRFs): the standard SCUEAL approach is to partition recombinants into gap-padded non-recombinant sequences. 

Best,
Sergei

**Comment by GonzaloYebra** [comment]
Hi Sergei,

Great, I'll try that! For now it's just a test to see how the alignment step influences the results in these gappy sequences, so I'm testing them with a reference alignment of only pure subtypes (fortunately I won't have to deal with recombinant references... for now!).

Thanks very much for your useful answer,

Gonzalo
