### ISSUE TITLE
Requires -Wno-narrowing when using gcc 6.1

### ISSUE THREAD

**Issue by tillea** [veg/hyphy#462]
Hi,

as reported in the Debian bug tracking system there is an issue when using gcc 6.1.  This [contribution](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811866#44) lists the posible options to fix the issue. [Here](https://anonscm.debian.org/git/debian-med/hyphy.git/tree/debian/patches/gcc-6.1_narrowing_conversion.patch) you can find the patch I'm using in the just uploaded package.

Kind regards

        Andreas.

**Comment by stevenweaver** [comment]
Hello Andreas,

We have created a new version, 2.2.7, with the patches applied.
https://github.com/veg/hyphy/releases/tag/2.2.7

Many thanks,
Steven
