### ISSUE TITLE
False is not converted to nil in gcc 6.1

### ISSUE THREAD

**Issue by tillea** [veg/hyphy#463]
Hi,

when using gcc 6.1 I needed to apply [this patch](https://anonscm.debian.org/git/debian-med/hyphy.git/tree/debian/patches/gcc-6.1_false_is_not_nil.patch) to successfully build hyphy.

Kind regards

        Andreas.

**Comment by stevenweaver** [comment]
Hello Andreas,

We have created a new version, 2.2.7, with the patches applied. 
https://github.com/veg/hyphy/releases/tag/2.2.7

Many thanks,
Steven
