### ISSUE TITLE
PRIME ERROR 

### ISSUE THREAD

**Issue by dkordis** [veg/hyphy#468]
Hi,

I'm having a strange Datamonkey error with PRIME. I get the following error:

**PRIME analysis results**
Error: Missing analysis settings: 0 Function call stack 1 : Assert 'Abs(_fel_results["SETTINGS"])>=3' ------- 2 : _result=jsonProcessor(primeResults) ------- 3 : ExecuteAFile from file "PRIME_Processor.ibf" using basepath /var/lib/datamonkey/share/BFs/. -------

**PRIME results as a CSV file**
<H1 class = "ErrorCap">HyPhy Run-time Error</H1><pre>
no such table: PRIME_SUMMARY

Function call
 stack
1 : DoSQL(DB_ID(,theCode,"return _matchRecordsByField (0);")
-------
2 : propertyCount=_ExecuteSQL(slacDBID,"SELECT COL_VALUE FROM PRIME_SUMMARY WHERE COL_KEY = 'PropertyCount'")
-------
</pre>

Can you help me,
Dusan

**Comment by stevenweaver** [comment]
Hello Dusan, 

Sorry for the delay in response to this issue. If you are still having this issue, can you please send me the file that you are trying to use with PRIME or the link on datamonkey at sweaver@temple.edu?

Thank you,
Steven

**Comment by dkordis** [comment]
Hi Steven,

 

We already solved the problem by using the TreeSAAP program.

 

Best regards,

Dusan
