### ISSUE TITLE
Python and R support are not in version 2.7

### ISSUE THREAD

**Issue by tillea** [veg/hyphy#469]
I wanted to upgrade the Debian package to version 2.7 and noticed that the Python and R support is missing in this version.  I just want to ask whether this is intentional and not just an oversight.  It would not make sense to remove the existing python-hyphy package and add it later in a new version again.
Thanks for the clarification
     Andreas.

**Comment by tillea** [comment]
Hmmm, is there any chance that somebody explains the role of the Python module and whether it is continued or not?  There are some users of the python-hyphy Debian package and if I upgrade to the latest hyphy version I need to delete the Python package.  Please clarify.
Thanks, Andreas.

**Comment by stevenweaver** [comment]
Hello Andreas, 

Sorry for the delay in response. 
I have split out the Python package to its own repository https://github.com/veg/hyphy-python. 
I've tested that the Python package works with 2.7 and 3.5 with gcc6 and clang, respectively.

The release is found here:
https://github.com/veg/hyphy-python/releases/tag/0.1.4

Will this work with Debian?

Best,
Steven
