### ISSUE TITLE
Can I close the window when my job is queued?

### ISSUE THREAD

**Issue by SerenaMiou** [veg/hyphy#473]
If my job is queued, can I close my computer and just wait?
If the job is done, how can i check the result later?

S

**Comment by stevenweaver** [comment]
Hello S,

If you are talking about datamonkey, yes. Just refresh the page when you return to your browser. 
If you restart your computer while the job is in queue, save the link in your browser and reopen it. 

The link will look something like the following : 
http://datamonkey.org/cgi-bin/datamonkey/mpiJobStatus.pl?fileName=upload.121430756510422.1&task=rel

test.datamonkey.org also has an option to provide an email address to notify you when the job has been completed.

Best,
Steven

**Comment by SerenaMiou** [comment]
Dear Steven,

Thanks for your answer!
And.... How long does the calculation usually take for spidermonkey with 70sites?

I wonder what is the reasonable waiting time until it might go wrong ?

Serena Y.C. Lin

**Comment by stevenweaver** [comment]
Hello Serena, 

I took a look at the datamonkey queue, and it looks like BGM is getting stuck with the alignment you uploaded. 

I will reopen this issue and mark it as a bug. I will have to remove your upload from the queue.
