### ISSUE TITLE
issue automating BUSTED analyses

### ISSUE THREAD

**Issue by uqipopo1** [veg/hyphy#474]
Hello,
I am new to using HyPhy (Linux) to run analyses at the genomic scale (so my apologies if the solution is obvious!). I am trying to automate BUSTED analyses on a set of ~3000 gene alignments for 4 species, where each alignment file corresponds to a unique gene tree. I have created the following custom wrapper (see below) to run on a test set of 10 alignments. I have adjusted the script to prompt for a series of file paths to the alignments and to the corresponding tree files (which I have pasted into two separate text files); however, when I run this wrapper, and supply the text files with my paths, the analysis does not seem to run. Any advice on how to interpret the message log and how to correct my wrapper to get BUSTED running would be greatly appreciated!

---

fileToExe = "/home/path/to/TemplateBatchFiles/BUSTED.bf";

/\* a  list of file paths */
SetDialogPrompt ( "Provide a list of ALN files to process:" );
fscanf ( PROMPT_FOR_FILE, "Lines", _inDirectoryPathsALN );

fprintf (stdout, "[READ ", Columns (_inDirectoryPathsALN), " file path lines]\n");

SetDialogPrompt ( "Provide a list of TRE files to process:" );
fscanf ( PROMPT_FOR_FILE, "Lines", _inDirectoryPathsTRE );

fprintf (stdout, "[READ ", Columns (_inDirectoryPathsTRE), " file path lines]\n");

/\* the options passed to the GUI are encoded here */
inputRedirect = {};
inputRedirect["01"]="Universal";
inputRedirect["04"]="Mg";
inputRedirect["05"]="";

for ( _fileLine = 0; _fileLine < Columns ( _inDirectoryPaths ); _fileLine = _fileLine + 1 ) {

```
inputRedirect [ "02" ]  = _inDirectoryPathsALN[ _fileLine ];
inputRedirect [ "03" ]  = _inDirectoryPathsTRE[ _fileLine ];
ExecuteAFile ( fileToExe, inputRedirect );
```

}

---

> ./HYPHYMP bustedwrapper.bf

/home/path/to/HYPHY/bin/Provide a list of ALN files to process::File_paths_aln.txt
[READ 10 file path lines]

/home/path/to/HYPHY/bin/Provide a list of TRE files to process::File_paths_trees.txt
[READ 10 file path lines]

Check messages.log details of this run.

> cat messages.log 

Variable 'PROMPT_FOR_FILE' was not initialized prior to being used
Variable 'END_OF_FILE' was not initialized prior to being used
Variable '_inDirectoryPaths' was not initialized prior to being used

---

Many Thanks,
Iva

**Comment by stevenweaver** [comment]
This issue seemed to have fallen through the cracks. I apologize. I'm going to close the issue, but if you still need help, please feel free to reopen and I will take a look. 

Regards,
Steven
