### ISSUE TITLE
newbie trying to learn how to use HyPhy with Command line

### ISSUE THREAD

**Issue by jofrank1988** [veg/hyphy#475]
Hello,

I have got kind of a dumb question. I wan to analyze ~1700 alignment files (.fasta) and I am trying to run through the HBL tutorial. A lab mate successfully installed HyPhy 2.2.7 on our linux server. At this point I do not understand what command I need to use to run my tutorial bf file.

I am a complete novice to coding so I am not sure I am using the correct vocabulary. Any help would be greatly appreciated

**Comment by stevenweaver** [comment]
Hi @jofrank1988, 

Thanks for trying HyPhy. 
Which HBL tutorial are you trying to use?

There are multiple targets for HyPhy. For MP2 (which is most commonly built), the binary (and thus the command) would be named `HYPHYMP`.

You would use the command `HYPHYMP <yourbatchfile>`, where `<yourbatchfile>` is the filename of the batch file you are trying to run. 

If your labmate did not use the command `make install`, HYPHYMP may not exist for you. The binary should exist in /usr/local/bin/HYPHYMP. If not, you may have to install HyPhy in your `home` directory. 

For example, this is how I would install and run HyPhy in my home directory. 

```
git clone git@github.com:veg/hyphy.git
cd hyphy
cmake . 
make HYPHYMP
./HYPHYMP
```

Kind Regards,
Steven

**Comment by jofrank1988** [comment]
Thank you for your help and patience, I am trying to follow the HyPhy batch language tutorial presented in the following link.

http://www.hyphy.org/w/index.php/HyPhy

It looks like HYPHYMP has been installed. Thus far I have attempted to run the following command and got no output that I can find:

`[jofrank@erv hyphy-2.2.7]$ /home/software/hyphy-2.2.7/HYPHYMP /data3/jofrank/HERVenv_multiz/p51tutorial_v2.bf `

the contents of p51tutorial_v2.bf is the following:

inputRedirect = {};
inputRedirect["01"]="Universal";
inputRedirect["02"]= "/data3/jofrank/HERVenv_multiz/HyphyBookChapter/p51.nex";
inputRedirect["03"]="MG94CUSTOM";
inputRedirect["04"]="Local";
inputRedirect["05"]="012232";
inputRedirect["06"]="y";

I am sure there is something basic that I am missing. Once again thank you so much for your patience with such a rudimentary question.

Best.

**Comment by stevenweaver** [comment]
Hello @jofrank1988,

You're missing a couple of steps.

In this example, you need to specify the location of the AnalyzeCodonData.bf file.

Try this:
```
fileToExe = "/home/software/hyphy-2.2.7/res/TemplateBatchFiles/AnalyzeCodonData.bf";
inputRedirect = {};
inputRedirect["01"]="Universal";
inputRedirect["02"]= "/data3/jofrank/HERVenv_multiz/HyphyBookChapter/p51.nex";
inputRedirect["03"]="MG94CUSTOM";
inputRedirect["04"]="Local";
inputRedirect["05"]="012232";
inputRedirect["06"]="y";
ExecuteAFile( fileToExe, inputRedirect);
```

**Comment by jofrank1988** [comment]
Thank you @stevenweaver,

That did the trick. I am sure I will run into more issues as I progress through the tutorial.

Thank you for your help and patience.

Best,

John Frank

**Comment by jofrank1988** [comment]
I have continued with Exercise 2 in the aforementioned tutorial and I am running into 2 problems. 

1. I am not sure how to adjust my batch file to run a SLAC analysis. Do I need to specify a different *.bf  file or do I need to adjust the inputRedirect lines? If the latter, I am not clear where in HyPhy I can find the appropriate model for a SLAC analysis.

2. when I attempt to perform an analysis with the following command:

/home/software/hyphy-2.2.7/HYPHYMP batch_wrapper_tutorial_file_v4.txt 

I am prompted with:

/data3/jofrank/HERVenv_multiz/Provide a list of files to process::

I input the following file (which contains my list of .nex files):

BatchAnalysis_tutorial_file.txt

I get the resulting output:

[READ 2 file path lines]

______________READ THE FOLLOWING DATA______________
8 species:{B_FR_83_HXB2,B_US_83_RF,B_US_86_JRFL,B_US_90_WEAU160,D_CD_83_ELI,D_CD_83_NDK,D_CD_84_84ZR085,D_UG_94_94UG114};
Total Sites:1320;
Distinct Sites:118
Please enter a 6 character model designation (e.g:010010 defines HKY85):

A tree was found in the data file:
((((D_CD_83_ELI,D_CD_83_NDK),D_UG_94_94UG114),D_CD_84_84ZR085),B_US_83_RF,((B_FR_83_HXB2,B_US_86_JRFL),B_US_90_WEAU160))

Would you like to use it:(Y/N)?

Current Max: -3177.5323     (90 % done) LF Evals/Sec: 466     CPU Load: 5.806   
______________RESULTS______________
Log Likelihood = -3177.53228655628;
Shared Parameters:
CT=1.16823461285954
AT=0.1243174101128468
AC=0.2379902258253954
CG=AT=0.1243174101128468
GT=AT=0.1243174101128468

Tree givenTree=(B_US_83_RF:0.02913359056751184,((B_FR_83_HXB2:0.01256487774181272,B_US_86_JRFL:0.01892946852467453)Node4:0.002347087399684167,B_US_90_WEAU160:0.02294061788372065)Node3:0.004675726085068701,(((D_CD_83_ELI:0.01971868254581645,D_CD_83_NDK:0.0104436375032162)Node10:0.01282560362310563,D_UG_94_94UG114:0.0582022567533619)Node9:0.004169919497913082,D_CD_84_84ZR085:0.02983485588783593)Node8:0.02827370961144187);
Error:
Could not find source dataset file:PROMPT_FOR_FILE Path stack: {/home/software/hyphy-2.2.7/lib/hyphy/,/data3/jofrank/HERVenv_multiz/,/home/software/hyphy-2.2.7/res/TemplateBatchFiles/}

Function call stack
1 : Read Data Set ds from file PROMPT_FOR_FILE
	Standard input redirect:
		04 : Local
		05 : 012232
		06 : y
		-------
2 : ExecuteAFile from file fileToExe using basepath /data3/jofrank/HERVenv_multiz/. reading input from inputRedirect
{"01":"Universal",
"03":"MG94CUSTOM",
"04":"Local",
"05":"012232",
"06":"y",
"02":"/data3/jofrank/HERVenv_multiz/HyphyBookChapter/Integrase_BDA.nex"}
-------
Segmentation fault (core dumped)

I looks like the first file was read but the second could not. I am not sure what I am doing wrong here.

**Comment by jofrank1988** [comment]
for your reference here is the content of the two text files inputted into HyPhy:

# **batch_wrapper_tutorial_file_v4.txt**

fileToExe = "/home/software/hyphy-2.2.7/res/TemplateBatchFiles/AnalyzeCodonData.bf";

SetDialogPrompt ( "Provide a list of files to process:" );
fscanf ( PROMPT_FOR_FILE, "Lines", _BatchAnalysis_tutorial_file.txt );

fprintf (stdout, "[READ ", Columns (_BatchAnalysis_tutorial_file.txt), " file path lines]\n");

inputRedirect = {};
inputRedirect["01"]="Universal";
inputRedirect["03"]="MG94CUSTOM";
inputRedirect["04"]="Local";
inputRedirect["05"]="012232";
inputRedirect["06"]="y";

for ( _fileLine = 0; _fileLine < Columns ( _BatchAnalysis_tutorial_file.txt ); _fileLine = _fileLine + 1 ) {
 
	inputRedirect [ "02" ]	= _BatchAnalysis_tutorial_file.txt[ _fileLine ];

ExecuteAFile( fileToExe, inputRedirect);
}

**BatchAnalysis_tutorial_file.txt** 

/data3/jofrank/HERVenv_multiz/HyphyBookChapter/p51.nex
/data3/jofrank/HERVenv_multiz/HyphyBookChapter/Integrase_BDA.nex

**Comment by Enhancer01** [comment]
@stevenweaver,

Would you mind if I request this issue be reopened? I kindly need some guide. I want to run BMG, I have some >10k .fa files with trees in separate files. first, how do I indicate foreground/background (testing for selection in a specific branch) in the tree files? Also, I have installed the hyphy/HYPHYMP to my home dir but couldn't find the editable files (.bf files), what do you think I'm doing wrong?

Thank you for your consideration, looking forward to your feedback.

Best regards,
Olatunde
