### ISSUE TITLE
how to measure purifying selection

### ISSUE THREAD

**Issue by jofrank1988** [veg/hyphy#476]
To whom it may concern.

I am currently studying a set of putative Open reading frames (~1700) that I identified in the human genome (>100 AA) and I want to determine if these sequences are undergoing purifying selection. I have managed to generate sequence alignments using the multiz alignments and converted these alignments to fasta format (these contain 5-20 species). Now I need to determine what method I need to use to determine if these sequences are undergoing purifying selection. Secondarily I also want to determine if any individual sites within these ORFs are subject to positive selection.

I figured Hyphy may be the most effective way of dealing with this high number of sequences. However, I am not sure what approach/program to use in order to address both of these questions. From my Reading REL seems to be an appropriate program but I am concerned about the number of assumptions being made. Would BUSTED or MEME provide a good assessment of purifying selection? 

I realize this is a very basic question but any and all information, suggestions or references would be greatly appreciated. 

Best,

John F.

**Comment by spond** [comment]
Dear @jofrank1988,

BUSTED would be a reasonable screen for estimating dN/dS on ORF-wide level. BUSTED explicitly tests for positive selection, i.e. the presence of a component where dN/dS > 1, but you could equally well use it to test for the presence of a component where dN/dS < 1 (this requires minor code modification). 

BUSTED will also output a "quick-and-dirty" enumeration of sites displaying evidence of dN>dS. For a more accurate scan of **sites** subject to selection I would recommend MEME.

As a first pass (before we muck around with the code), just run BUSTED on some of your ORFs, and examine the **distribution** of &omega; values. As a rule of thumb, having a large proportion of sites (e.g. more than 50%) assigned to a category with low  &omega; (e.g. &omega; < .25) is a good indicator of conservation. 

Once you've done this, I can help you with the necessary changes to the scripts.

Best,
Sergei

**Comment by jofrank1988** [comment]
Dear Sergei,

Thank you so much for your prompt and helpful reply. I am running HYPHY using command line and am completely new to writing wrappers to analyze multiple sequence alignments.

I attempted to write the following wrapper (based on the HBL and BUSTED tutorials) to analyze my sequence alignments:

fileToExe = "/home/software/hyphy-2.2.7/res/TemplateBatchFiles/BUSTED.bf";

SetDialogPrompt ( "Provide a list of files to process:" );
fscanf ( PROMPT_FOR_FILE, "Lines", _Busted_pilot_rmb11_path.txt );

fprintf (stdout, "[READ ", Columns (_Busted_pilot_rmb11_path.txt), " file path lines]\n");

inputRedirect = {};
inputRedirect["01"]="Universal";
inputRedirect["03"]="MG94CUSTOMCF3X4";
inputRedirect["04"]="Global";
inputRedirect["05"]="012345";
inputRedirect["06"]="y";

for ( _fileLine = 0; _fileLine < Columns ( _Busted_pilot_rmb11_path.txt ); _fileLine = _fileLine + 1 ) {
 
	inputRedirect [ "02" ]	= _Busted_pilot_rmb11_path.txt[ _fileLine ];

ExecuteAFile( fileToExe, inputRedirect);
}

**Comment by jofrank1988** [comment]
However, after running the initial command, I received the following output:

$ /home/software/hyphy-2.2.7/HYPHYMP batch_wrapper_pilot_rmb11_v2.txt 

/data3/jofrank/HERVenv_multiz/mafExtraction_fasta/rmb11_append_test/Provide a list of files to process::Busted_pilot_rmb11_path.txt                                 
[READ 11 file path lines]

Analysis Description
====================
BUSTED (branch-site unrestricted statistical test of episodic
diversification) uses a random effects branch-site model fitted jointly
to all or a subset of tree branches in order to test for alignment-wide
evidence of episodic diversifying selection. Assuming there is evidence
of positive selection (i.e. there is an omega > 1), BUSTED will also
perform a quick evidence-ratio style analysis to explore which
individual sites may have been subject to selection.

Requirements
============
in-frame codon alignment and a phylogenetic tree (optionally annotated
with {})

Citation
========
In preparation, preprint at xxx

Written by
==========
Sergei L Kosakovsky Pond, Ben Murrell, Sasha Murrell, and the UCSD VEG
group

Contact Information
===================
spond@ucsd.edu

Analysis Version
================
1.00

[BUSTED] Loaded an MSA with 9 sequences and 116 codons from '/data3/jofrank/HERVenv_multiz/mafExtraction_fasta/rmb11_append_test/2_71620494.fasta' 


A tree was found in the data file:
(((((Human,panTro),gorGor),ponAbe),nomLeu),(((rheMac,CrabEating),papHam),Green))

Would you like to use it:(Y/N)?

Error:
Not a valid (or duplicate) option: 'Global' passed to ChoiceList (with multiple selections) 'Which branches to test?' using redirected stdin input

Function call stack
1 : Choice List for Which branches to test? with choice list:NO_SKIP. Store result in whichBranchesToTest
	Standard input redirect:
		05 : 012345
		06 : y
		-------
2 : busted.selected_branches=busted.io.selectBranchesToTest(tree_definition)
	Standard input redirect:
		05 : 012345
		06 : y
		-------
3 : ExecuteAFile from file fileToExe using basepath /data3/jofrank/HERVenv_multiz/mafExtraction_fasta/rmb11_append_test/. reading input from inputRedirect
{"01":"Universal",
"03":"MG94CUSTOMCF3X4",
"04":"Global",
"05":"012345",
"06":"y",
"02":"/data3/jofrank/HERVenv_multiz/mafExtraction_fasta/rmb11_append_test/2_71620494.fasta"}
-------
Segmentation fault (core dumped)

I am guessing the the use of "Global" in inputRedirect04 is probably causing some issues.
Also what does segmentation fault mean? Is it possible my fasta file is not formatted correctly?

Any and all help would be appreciated.

Best,

John Frank

**Comment by spond** [comment]
Dear @jofrank1988,

`Segmentation fault` is a general system error which means that after HyPhy reported the error it failed to gracefully exit (it basically tried to read/write from a memory address that is either not valid, or doesn't belong to the process). It has nothing to do with your data. 

Regarding your other issues: it the wrapper file you used is not appropriate for BUSTED (it is what you would use for a different file, e.g. AnalyzeCodonData.bf).

To make a wrapper file for busted do this. Run through the analysis once manually (follow https://github.com/veg/hyphy-tutorials/tree/master/selection#run-alignment-wide-tests-for-episodic-diversification-busted); please note that some of the branches in HyPhy repo (e.g. 2.3-alpha-working) may have a broken version of BUSTED. Use the master branch for now to avoid other issues. 

As you run through the analysis, record the options you are entering, 

1. "Universal"
2. file name
3. tree to use
...

Then simply convert them to an `inputRedirect` dictionary in the same order, e.g. 

```
inputRedirect = {
"01" : "Universal",
"02" : /path/to/file
...
"04" : "All",
"05" : ""
}
```

One trick you'll need to note is when you select which branches to test (All is a good choice for you), add an empty line to the dictionary (see "05" above), to indicate the end of a multiple choice list.

HTH,
Sergei
