### ISSUE TITLE
Problem compiling HYPHYGTK

### ISSUE THREAD

**Issue by pjdias87** [veg/hyphy#477]
Hi HYPHY community, 

I was trying to compile HYPHYGTK in the branch v2.3-alpha-working and I got this error.

Any clues on how to solve this?

My OS is Ubuntu 16.04 and HYPHYMP and HYPHYMPI installed with no problems. I leave also the output of ./HYPHYGTEST, maybe can give some clue, since one of its test fails.

Regards,

pj

pj@pj:~/Programas_software/hyphy-2.3-alpha-working$ make HYPHYGTK
[  0%] Building CXX object CMakeFiles/HYPHYGTK.dir/src/gui/gtk/HYPlatformComponent.cpp.o
/home/pj/Programas_software/hyphy-2.3-alpha-working/src/gui/gtk/HYPlatformComponent.cpp: In member function ‘virtual bool _HYCanvas::_ProcessOSEvent(Ptr)’:
/home/pj/Programas_software/hyphy-2.3-alpha-working/src/gui/gtk/HYPlatformComponent.cpp:584:48: error: invalid conversion from ‘_String*’ to ‘long int’ [-fpermissive]
             menuChoice  = menuOptions.Find (&s1);
                                                ^
In file included from /home/pj/Programas_software/hyphy-2.3-alpha-working/src/core/include/hy_strings.h:44:0,
                 from /home/pj/Programas_software/hyphy-2.3-alpha-working/src/gui/include/HYBaseGUI.h:14,
                 from /home/pj/Programas_software/hyphy-2.3-alpha-working/src/gui/include/Components/HYComponent.h:10,
                 from /home/pj/Programas_software/hyphy-2.3-alpha-working/src/gui/gtk/HYPlatformComponent.cpp:47:
/home/pj/Programas_software/hyphy-2.3-alpha-working/src/core/include/simplelist.h:285:22: note:   initializing argument 1 of ‘virtual long int _SimpleList::Find(long int, long int) const’
         virtual long Find(long, long startAt = 0) const;
                      ^
CMakeFiles/HYPHYGTK.dir/build.make:62: recipe for target 'CMakeFiles/HYPHYGTK.dir/src/gui/gtk/HYPlatformComponent.cpp.o' failed
make[3]: *** [CMakeFiles/HYPHYGTK.dir/src/gui/gtk/HYPlatformComponent.cpp.o] Error 1
CMakeFiles/Makefile2:419: recipe for target 'CMakeFiles/HYPHYGTK.dir/all' failed
make[2]: *** [CMakeFiles/HYPHYGTK.dir/all] Error 2
CMakeFiles/Makefile2:426: recipe for target 'CMakeFiles/HYPHYGTK.dir/rule' failed
make[1]: *** [CMakeFiles/HYPHYGTK.dir/rule] Error 2
Makefile:305: recipe for target 'HYPHYGTK' failed
make: *** [HYPHYGTK] Error 2

pj@pj:~/Programas_software/hyphy-2.3-alpha-working$ make GTEST
Scanning dependencies of target gtest
[  0%] Building CXX object contrib/gtest-1.7.0/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  6%] Linking CXX static library libgtest.a
[  6%] Built target gtest
Scanning dependencies of target HYPHYGTEST
[  6%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/_hyExecutionContext.cpp.o
[  6%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/alignment.cpp.o
[  6%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/avllist.cpp.o
[ 12%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/avllistx.cpp.o
[ 12%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/avllistxl.cpp.o
[ 12%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/avllistxl_iterator.cpp.o
[ 18%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/baseobj.cpp.o
[ 18%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/batchlan.cpp.o
[ 18%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/batchlan2.cpp.o
[ 18%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/batchlanhelpers.cpp.o
[ 25%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/batchlanruntime.cpp.o
[ 25%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/calcnode.cpp.o
[ 25%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/calcnode2.cpp.o
/home/pj/Programas_software/hyphy-2.3-alpha-working/src/core/calcnode2.cpp: In function ‘void _handle4x4_pruning_case(const double*, const double*, double*, void*)’:
/home/pj/Programas_software/hyphy-2.3-alpha-working/src/core/calcnode2.cpp:148:24: warning: variable ‘t3’ set but not used [-Wunused-but-set-variable]
               t0,t1,t2,t3;
                        ^
[ 25%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/category.cpp.o
[ 31%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/constant.cpp.o
[ 31%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/error.cpp.o
[ 31%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/fisher_exact.cpp.o
[ 37%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/formula.cpp.o
[ 37%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/fstring.cpp.o
[ 37%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/global_object_lists.cpp.o
[ 37%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/hbl_env.cpp.o
[ 43%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/likefunc.cpp.o
[ 43%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/likefunc2.cpp.o
[ 43%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/likefuncocl.cpp.o
[ 43%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/list.cpp.o
[ 50%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/mathobj.cpp.o
[ 50%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/matrix.cpp.o
[ 50%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/nexus.cpp.o
[ 56%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/operation.cpp.o
[ 56%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/parser.cpp.o
[ 56%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/parser2.cpp.o
[ 56%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/polynoml.cpp.o
[ 62%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/regex.cpp.o
[ 62%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/sequence.cpp.o
[ 62%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/simplelist.cpp.o
[ 68%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/site.cpp.o
[ 68%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/stack.cpp.o
[ 68%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/string_file_wrapper.cpp.o
[ 68%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/strings.cpp.o
[ 75%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/trie.cpp.o
[ 75%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/variable.cpp.o
[ 75%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/core/variablecontainer.cpp.o
[ 75%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/new/bayesgraph.cpp.o
[ 81%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/new/bayesgraph2.cpp.o
[ 81%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/new/bgm.cpp.o
[ 81%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/new/bgm2.cpp.o
[ 87%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/new/scfg.cpp.o
[ 87%] Building C object CMakeFiles/HYPHYGTEST.dir/contrib/SQLite-3.8.2/sqlite3.c.o
cc1: warning: command line option ‘-Wno-conversion-null’ is valid for C++/ObjC++ but not for C
cc1: warning: command line option ‘-std=gnu++14’ is valid for C++/ObjC++ but not for C
/home/pj/Programas_software/hyphy-2.3-alpha-working/contrib/SQLite-3.8.2/sqlite3.c: In function ‘balance’:
/home/pj/Programas_software/hyphy-2.3-alpha-working/contrib/SQLite-3.8.2/sqlite3.c:57029:22: warning: array subscript is above array bounds [-Warray-bounds]
         pOld = apCopy[++j];
                      ^
[ 87%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/utils/hyphyunixutils.cpp.o
[ 87%] Building CXX object CMakeFiles/HYPHYGTEST.dir/tests/gtests/ut_avllists.cpp.o
[ 93%] Building CXX object CMakeFiles/HYPHYGTEST.dir/tests/gtests/ut_list.cpp.o
[ 93%] Building CXX object CMakeFiles/HYPHYGTEST.dir/tests/gtests/ut_simplelists.cpp.o
[ 93%] Building CXX object CMakeFiles/HYPHYGTEST.dir/tests/gtests/ut_strings.cpp.o
[100%] Building CXX object CMakeFiles/HYPHYGTEST.dir/src/mains/unix.cpp.o
/home/pj/Programas_software/hyphy-2.3-alpha-working/src/mains/unix.cpp: In function ‘_String getLibraryPath()’:
/home/pj/Programas_software/hyphy-2.3-alpha-working/src/mains/unix.cpp:161:42: warning: ignoring return value of ‘char* getcwd(char*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
     getcwd (curWd,_HYPHY_MAX_PATH_LENGTH);
                                          ^
/home/pj/Programas_software/hyphy-2.3-alpha-working/src/mains/unix.cpp: In function ‘long int DisplayListOfChoices()’:
/home/pj/Programas_software/hyphy-2.3-alpha-working/src/mains/unix.cpp:346:38: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
             fgets (buffer,2048,stdin);
                                      ^
/home/pj/Programas_software/hyphy-2.3-alpha-working/src/mains/unix.cpp:347:38: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
             fgets (buffer,2048,stdin);
                                      ^
/home/pj/Programas_software/hyphy-2.3-alpha-working/src/mains/unix.cpp:390:42: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
                 fgets (buffer,2048,stdin);
                                          ^
[100%] Linking CXX executable HYPHYGTEST
[100%] Built target HYPHYGTEST
Scanning dependencies of target GTEST
[100%] Built target GTEST

pj@pj:~/Programas_software/hyphy-2.3-alpha-working$ ./HYPHYGTEST
[==========] Running 181 tests from 6 test cases.
[----------] Global test environment set-up.
[----------] 18 tests from AVLListTest
[ RUN      ] AVLListTest.FindTest
[       OK ] AVLListTest.FindTest (0 ms)
[ RUN      ] AVLListTest.FindLongTest
[       OK ] AVLListTest.FindLongTest (0 ms)
[ RUN      ] AVLListTest.FindBestTest
[       OK ] AVLListTest.FindBestTest (0 ms)
[ RUN      ] AVLListTest.NextTest
[       OK ] AVLListTest.NextTest (0 ms)
[ RUN      ] AVLListTest.PrevTest
[       OK ] AVLListTest.PrevTest (0 ms)
[ RUN      ] AVLListTest.FirstTest
[       OK ] AVLListTest.FirstTest (0 ms)
[ RUN      ] AVLListTest.LastTest
[       OK ] AVLListTest.LastTest (0 ms)
[ RUN      ] AVLListTest.GetByIndexTest
[       OK ] AVLListTest.GetByIndexTest (0 ms)
[ RUN      ] AVLListTest.ReorderListTest
[       OK ] AVLListTest.ReorderListTest (0 ms)
[ RUN      ] AVLListTest.TraverserTest
[       OK ] AVLListTest.TraverserTest (0 ms)
[ RUN      ] AVLListTest.toStrTest
/home/pj/Programas_software/hyphy-2.3-alpha-working/tests/gtests/ut_avllists.cpp:370: Failure
Value of: return_str->getStr()
  Actual: "(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)"
Expected: "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n"
[  FAILED  ] AVLListTest.toStrTest (0 ms)
[ RUN      ] AVLListTest.RetrieveTest
[       OK ] AVLListTest.RetrieveTest (0 ms)
[ RUN      ] AVLListTest.ClearTest
[       OK ] AVLListTest.ClearTest (0 ms)
[ RUN      ] AVLListTest.InsertTest
[       OK ] AVLListTest.InsertTest (0 ms)
[ RUN      ] AVLListTest.InsertDataTest
[       OK ] AVLListTest.InsertDataTest (0 ms)
[ RUN      ] AVLListTest.HasDataTest
[       OK ] AVLListTest.HasDataTest (0 ms)
[ RUN      ] AVLListTest.DeleteTest
[       OK ] AVLListTest.DeleteTest (0 ms)
[ RUN      ] AVLListTest.countitemsTest
[       OK ] AVLListTest.countitemsTest (0 ms)
[----------] 18 tests from AVLListTest (0 ms total)

[----------] 4 tests from AVLListXLTest
[ RUN      ] AVLListXLTest.ClearTest
[       OK ] AVLListXLTest.ClearTest (0 ms)
[ RUN      ] AVLListXLTest.InsertDataTest
[       OK ] AVLListXLTest.InsertDataTest (0 ms)
[ RUN      ] AVLListXLTest.DeleteXtraTest
[       OK ] AVLListXLTest.DeleteXtraTest (0 ms)
[ RUN      ] AVLListXLTest.SetAndGetXtraTest
[       OK ] AVLListXLTest.SetAndGetXtraTest (0 ms)
[----------] 4 tests from AVLListXLTest (0 ms total)

[----------] 4 tests from AVLListXTest
[ RUN      ] AVLListXTest.InsertDataTest
[       OK ] AVLListXTest.InsertDataTest (0 ms)
[ RUN      ] AVLListXTest.DeleteXtraTest
[       OK ] AVLListXTest.DeleteXtraTest (0 ms)
[ RUN      ] AVLListXTest.PopulateFromListTest
[       OK ] AVLListXTest.PopulateFromListTest (0 ms)
[ RUN      ] AVLListXTest.SetAndGetXtraTest
[       OK ] AVLListXTest.SetAndGetXtraTest (0 ms)
[----------] 4 tests from AVLListXTest (0 ms total)

[----------] 33 tests from ListTest
[ RUN      ] ListTest._NothingListTest
[       OK ] ListTest._NothingListTest (0 ms)
[ RUN      ] ListTest._LengthConstructorListTest
[       OK ] ListTest._LengthConstructorListTest (0 ms)
[ RUN      ] ListTest._StackCopyConstructorListTest
[       OK ] ListTest._StackCopyConstructorListTest (0 ms)
[ RUN      ] ListTest._SubStrConstructorListTest
[       OK ] ListTest._SubStrConstructorListTest (0 ms)
[ RUN      ] ListTest._DataConstructorListTest
[       OK ] ListTest._DataConstructorListTest (0 ms)
[ RUN      ] ListTest.paranthesisTest
[       OK ] ListTest.paranthesisTest (0 ms)
[ RUN      ] ListTest.EqualOpTest
[       OK ] ListTest.EqualOpTest (0 ms)
[ RUN      ] ListTest.EqualTest
[       OK ] ListTest.EqualTest (0 ms)
[ RUN      ] ListTest.AmpersandOpTest
[       OK ] ListTest.AmpersandOpTest (0 ms)
[ RUN      ] ListTest.Ampersand2OpTest
[       OK ] ListTest.Ampersand2OpTest (0 ms)
[ RUN      ] ListTest.DoubleAmpersandOpTest
[       OK ] ListTest.DoubleAmpersandOpTest (0 ms)
[ RUN      ] ListTest.DoubleAmpersand2OpTest
[       OK ] ListTest.DoubleAmpersand2OpTest (0 ms)
[ RUN      ] ListTest.DoubleLessOpTest
[       OK ] ListTest.DoubleLessOpTest (0 ms)
[ RUN      ] ListTest.DoubleLess2OpTest
[       OK ] ListTest.DoubleLess2OpTest (0 ms)
[ RUN      ] ListTest.AppendNewInstanceTest
[       OK ] ListTest.AppendNewInstanceTest (0 ms)
[ RUN      ] ListTest.PlaceTest
[       OK ] ListTest.PlaceTest (0 ms)
[ RUN      ] ListTest.InsertElementTest
[       OK ] ListTest.InsertElementTest (0 ms)
[ RUN      ] ListTest.getStrTest
[       OK ] ListTest.getStrTest (0 ms)
[ RUN      ] ListTest.makeDynamicTest
[       OK ] ListTest.makeDynamicTest (0 ms)
[ RUN      ] ListTest.toFileStrTest
[       OK ] ListTest.toFileStrTest (0 ms)
[ RUN      ] ListTest.bumpNInstTest
[       OK ] ListTest.bumpNInstTest (0 ms)
[ RUN      ] ListTest.FindStringTest
[       OK ] ListTest.FindStringTest (0 ms)
[ RUN      ] ListTest.JoinTest
[       OK ] ListTest.JoinTest (0 ms)
[ RUN      ] ListTest.BinaryFindTest
[       OK ] ListTest.BinaryFindTest (0 ms)
[ RUN      ] ListTest.BinaryInsertTest
[       OK ] ListTest.BinaryInsertTest (0 ms)
[ RUN      ] ListTest.CompareTest
[       OK ] ListTest.CompareTest (0 ms)
[ RUN      ] ListTest.Compare2Test
[       OK ] ListTest.Compare2Test (0 ms)
[ RUN      ] ListTest.FreeUpMemoryTest
[       OK ] ListTest.FreeUpMemoryTest (0 ms)
[ RUN      ] ListTest.ClearTest
[       OK ] ListTest.ClearTest (0 ms)
[ RUN      ] ListTest.DeleteTest
[       OK ] ListTest.DeleteTest (0 ms)
[ RUN      ] ListTest.DeleteListTest
[       OK ] ListTest.DeleteListTest (0 ms)
[ RUN      ] ListTest.ReplaceTest
[       OK ] ListTest.ReplaceTest (0 ms)
[ RUN      ] ListTest.IntersectTest
[       OK ] ListTest.IntersectTest (0 ms)
[----------] 33 tests from ListTest (1 ms total)

[----------] 45 tests from SimpleListTest
[ RUN      ] SimpleListTest._StackCopyConstructorListTest
[       OK ] SimpleListTest._StackCopyConstructorListTest (0 ms)
[ RUN      ] SimpleListTest._LengthConstructorTest
[       OK ] SimpleListTest._LengthConstructorTest (0 ms)
[ RUN      ] SimpleListTest._PopulateTest
[       OK ] SimpleListTest._PopulateTest (0 ms)
[ RUN      ] SimpleListTest._BracketOpTest
[       OK ] SimpleListTest._BracketOpTest (0 ms)
[ RUN      ] SimpleListTest._ParenthOpTest
[       OK ] SimpleListTest._ParenthOpTest (0 ms)
[ RUN      ] SimpleListTest._EqualOpTest
[       OK ] SimpleListTest._EqualOpTest (0 ms)
[ RUN      ] SimpleListTest._DoubleLessOpTest
[       OK ] SimpleListTest._DoubleLessOpTest (0 ms)
[ RUN      ] SimpleListTest._OffsetTest
[       OK ] SimpleListTest._OffsetTest (0 ms)
[ RUN      ] SimpleListTest._ElementTest
[       OK ] SimpleListTest._ElementTest (0 ms)
[ RUN      ] SimpleListTest._PopTest
[       OK ] SimpleListTest._PopTest (0 ms)
[ RUN      ] SimpleListTest._countitemsTest
[       OK ] SimpleListTest._countitemsTest (0 ms)
[ RUN      ] SimpleListTest._EqualTest
[       OK ] SimpleListTest._EqualTest (0 ms)
[ RUN      ] SimpleListTest._MergeTest
[       OK ] SimpleListTest._MergeTest (0 ms)
[ RUN      ] SimpleListTest.DoubleGreaterOpTest
[       OK ] SimpleListTest.DoubleGreaterOpTest (0 ms)
[ RUN      ] SimpleListTest._ListToPartitionStringTest
[       OK ] SimpleListTest._ListToPartitionStringTest (0 ms)
[ RUN      ] SimpleListTest._RequestSpaceTest
[       OK ] SimpleListTest._RequestSpaceTest (0 ms)
[ RUN      ] SimpleListTest._toStrTest
[       OK ] SimpleListTest._toStrTest (1 ms)
[ RUN      ] SimpleListTest._makeDynamicTest
[       OK ] SimpleListTest._makeDynamicTest (0 ms)
[ RUN      ] SimpleListTest._MinTest
[       OK ] SimpleListTest._MinTest (0 ms)
[ RUN      ] SimpleListTest._MaxTest
[       OK ] SimpleListTest._MaxTest (0 ms)
[ RUN      ] SimpleListTest._ClearFormulasInListTest
[       OK ] SimpleListTest._ClearFormulasInListTest (0 ms)
[ RUN      ] SimpleListTest._CountingSortTest
[       OK ] SimpleListTest._CountingSortTest (0 ms)
[ RUN      ] SimpleListTest._BinaryInsertTest
[       OK ] SimpleListTest._BinaryInsertTest (0 ms)
[ RUN      ] SimpleListTest._FindTest
[       OK ] SimpleListTest._FindTest (0 ms)
[ RUN      ] SimpleListTest._FindSteppingTest
[       OK ] SimpleListTest._FindSteppingTest (0 ms)
[ RUN      ] SimpleListTest._FilterRangeTest
[       OK ] SimpleListTest._FilterRangeTest (0 ms)
[ RUN      ] SimpleListTest._BinaryFindTest
[       OK ] SimpleListTest._BinaryFindTest (0 ms)
[ RUN      ] SimpleListTest._SortTest
[       OK ] SimpleListTest._SortTest (0 ms)
[ RUN      ] SimpleListTest._CompareTest
[       OK ] SimpleListTest._CompareTest (0 ms)
[ RUN      ] SimpleListTest._ClearTest
[       OK ] SimpleListTest._ClearTest (0 ms)
[ RUN      ] SimpleListTest._DeleteTest
[       OK ] SimpleListTest._DeleteTest (0 ms)
[ RUN      ] SimpleListTest._TrimMemoryTest
[       OK ] SimpleListTest._TrimMemoryTest (0 ms)
[ RUN      ] SimpleListTest._DeleteDuplicatesTest
[       OK ] SimpleListTest._DeleteDuplicatesTest (0 ms)
[ RUN      ] SimpleListTest._DeleteListTest
[       OK ] SimpleListTest._DeleteListTest (0 ms)
[ RUN      ] SimpleListTest._DisplaceTest
[       OK ] SimpleListTest._DisplaceTest (0 ms)
[ RUN      ] SimpleListTest._PermuteWithReplacementTest
[       OK ] SimpleListTest._PermuteWithReplacementTest (0 ms)
[ RUN      ] SimpleListTest._PermuteTest
[       OK ] SimpleListTest._PermuteTest (0 ms)
[ RUN      ] SimpleListTest._NChooseKTest
[       OK ] SimpleListTest._NChooseKTest (0 ms)
[ RUN      ] SimpleListTest._SwapTest
[       OK ] SimpleListTest._SwapTest (0 ms)
[ RUN      ] SimpleListTest._FlipTest
[       OK ] SimpleListTest._FlipTest (0 ms)
[ RUN      ] SimpleListTest._UnionTest
[       OK ] SimpleListTest._UnionTest (0 ms)
[ RUN      ] SimpleListTest._IntersectTest
[       OK ] SimpleListTest._IntersectTest (0 ms)
[ RUN      ] SimpleListTest._CountCommonElementsTest
[       OK ] SimpleListTest._CountCommonElementsTest (0 ms)
[ RUN      ] SimpleListTest._XORTest
[       OK ] SimpleListTest._XORTest (0 ms)
[ RUN      ] SimpleListTest._SubtractTest
[       OK ] SimpleListTest._SubtractTest (0 ms)
[----------] 45 tests from SimpleListTest (1 ms total)

[----------] 77 tests from StringTest
[ RUN      ] StringTest.InitializeTest
[       OK ] StringTest.InitializeTest (0 ms)
[ RUN      ] StringTest.DuplicateTest
[       OK ] StringTest.DuplicateTest (0 ms)
[ RUN      ] StringTest.DuplicateErasingTest
[       OK ] StringTest.DuplicateErasingTest (0 ms)
[ RUN      ] StringTest.makeDynamicTest
[       OK ] StringTest.makeDynamicTest (0 ms)
[ RUN      ] StringTest.getCharTest
[       OK ] StringTest.getCharTest (0 ms)
[ RUN      ] StringTest.setCharTest
[       OK ] StringTest.setCharTest (0 ms)
[ RUN      ] StringTest.CopyDynamicStringTest
[       OK ] StringTest.CopyDynamicStringTest (0 ms)
[ RUN      ] StringTest.LengthTest
[       OK ] StringTest.LengthTest (0 ms)
[ RUN      ] StringTest.InsertTest
[       OK ] StringTest.InsertTest (0 ms)
[ RUN      ] StringTest.DeleteTest
[       OK ] StringTest.DeleteTest (0 ms)
[ RUN      ] StringTest.AppendNewInstanceTest
[       OK ] StringTest.AppendNewInstanceTest (0 ms)
[ RUN      ] StringTest.EscapeAndAppendTest
[       OK ] StringTest.EscapeAndAppendTest (0 ms)
[ RUN      ] StringTest.EscapeAndAppend2Test
[       OK ] StringTest.EscapeAndAppend2Test (0 ms)
[ RUN      ] StringTest.FinalizeTest
[       OK ] StringTest.FinalizeTest (0 ms)
[ RUN      ] StringTest.getStrTest
[       OK ] StringTest.getStrTest (0 ms)
[ RUN      ] StringTest.ChopTest
[       OK ] StringTest.ChopTest (0 ms)
[ RUN      ] StringTest.CutTest
[       OK ] StringTest.CutTest (0 ms)
[ RUN      ] StringTest.FlipTest
[       OK ] StringTest.FlipTest (0 ms)
[ RUN      ] StringTest.Adler32Test
[       OK ] StringTest.Adler32Test (0 ms)
[ RUN      ] StringTest.TrimTest
[       OK ] StringTest.TrimTest (0 ms)
[ RUN      ] StringTest.FirstNonSpaceIndexTest
[       OK ] StringTest.FirstNonSpaceIndexTest (0 ms)
[ RUN      ] StringTest.KillSpacesTest
[       OK ] StringTest.KillSpacesTest (0 ms)
[ RUN      ] StringTest.CompressSpacesTest
[       OK ] StringTest.CompressSpacesTest (0 ms)
[ RUN      ] StringTest.FirstSpaceIndexTest
[       OK ] StringTest.FirstSpaceIndexTest (0 ms)
[ RUN      ] StringTest.FirstNonSpaceTest
[       OK ] StringTest.FirstNonSpaceTest (0 ms)
[ RUN      ] StringTest.FirstNonSpace2Test
[       OK ] StringTest.FirstNonSpace2Test (0 ms)
[ RUN      ] StringTest.FindTest
[       OK ] StringTest.FindTest (0 ms)
[ RUN      ] StringTest.FindCharTest
[       OK ] StringTest.FindCharTest (0 ms)
[ RUN      ] StringTest.FindKMPTest
[       OK ] StringTest.FindKMPTest (0 ms)
[ RUN      ] StringTest.FindEndOfIdentTest
[       OK ] StringTest.FindEndOfIdentTest (0 ms)
[ RUN      ] StringTest.FindAnyCaseTest
[       OK ] StringTest.FindAnyCaseTest (0 ms)
[ RUN      ] StringTest.ContainsSubstringTest
[       OK ] StringTest.ContainsSubstringTest (0 ms)
[ RUN      ] StringTest.FindBackwardsTest
[       OK ] StringTest.FindBackwardsTest (0 ms)
[ RUN      ] StringTest.FindBinaryTest
[       OK ] StringTest.FindBinaryTest (0 ms)
[ RUN      ] StringTest.EqualsTest
[       OK ] StringTest.EqualsTest (0 ms)
[ RUN      ] StringTest.CompareTest
[       OK ] StringTest.CompareTest (0 ms)
[ RUN      ] StringTest.EqualWithWildCharTest
[       OK ] StringTest.EqualWithWildCharTest (0 ms)
[ RUN      ] StringTest.GreaterTest
[       OK ] StringTest.GreaterTest (0 ms)
[ RUN      ] StringTest.LessTest
[       OK ] StringTest.LessTest (0 ms)
[ RUN      ] StringTest.containsTest
[       OK ] StringTest.containsTest (0 ms)
[ RUN      ] StringTest.beginswithTest
[       OK ] StringTest.beginswithTest (0 ms)
[ RUN      ] StringTest.startswithTest
[       OK ] StringTest.startswithTest (0 ms)
[ RUN      ] StringTest.endswithTest
[       OK ] StringTest.endswithTest (0 ms)
[ RUN      ] StringTest.FormatTimeStringTest
[       OK ] StringTest.FormatTimeStringTest (0 ms)
[ RUN      ] StringTest.ReplaceTest
[       OK ] StringTest.ReplaceTest (0 ms)
[ RUN      ] StringTest.TokenizeTest
[       OK ] StringTest.TokenizeTest (0 ms)
[ RUN      ] StringTest.toNumTest
[       OK ] StringTest.toNumTest (0 ms)
[ RUN      ] StringTest.UpCaseTest
[       OK ] StringTest.UpCaseTest (0 ms)
[ RUN      ] StringTest.LoCaseTest
[       OK ] StringTest.LoCaseTest (0 ms)
[ RUN      ] StringTest.ProcessTreeBranchLengthTest
[       OK ] StringTest.ProcessTreeBranchLengthTest (0 ms)
[ RUN      ] StringTest.ExtractEnclosedExpressionTest
[       OK ] StringTest.ExtractEnclosedExpressionTest (0 ms)
[ RUN      ] StringTest.IsALiteralArgumentTest
[       OK ] StringTest.IsALiteralArgumentTest (0 ms)
[ RUN      ] StringTest.StripQuotesTest
[       OK ] StringTest.StripQuotesTest (0 ms)
[ RUN      ] StringTest.IsValidIdentifierTest
[       OK ] StringTest.IsValidIdentifierTest (0 ms)
[ RUN      ] StringTest.IsValidRefIdentifierTest
[       OK ] StringTest.IsValidRefIdentifierTest (0 ms)
[ RUN      ] StringTest.PathCompositionTest
[       OK ] StringTest.PathCompositionTest (0 ms)
[ RUN      ] StringTest.PathSubtractionTest
[       OK ] StringTest.PathSubtractionTest (0 ms)
[ RUN      ] StringTest.ConvertToAnIdentTest
[       OK ] StringTest.ConvertToAnIdentTest (0 ms)
[ RUN      ] StringTest.ShortenVarIDTest
[       OK ] StringTest.ShortenVarIDTest (0 ms)
[ RUN      ] StringTest.RegExpMatchOnceTest
[       OK ] StringTest.RegExpMatchOnceTest (0 ms)
[ RUN      ] StringTest.RegExpMatchTest
[       OK ] StringTest.RegExpMatchTest (0 ms)
[ RUN      ] StringTest.RegExpMatchAllTest
[       OK ] StringTest.RegExpMatchAllTest (0 ms)
[ RUN      ] StringTest.LempelZivProductionHistoryTest
[       OK ] StringTest.LempelZivProductionHistoryTest (0 ms)
[ RUN      ] StringTest.SortTest
[       OK ] StringTest.SortTest (0 ms)
[ RUN      ] StringTest.FindTerminatorTest
[       OK ] StringTest.FindTerminatorTest (0 ms)
[ RUN      ] StringTest.AppendAnAssignmentToBufferTest
[       OK ] StringTest.AppendAnAssignmentToBufferTest (0 ms)
[ RUN      ] StringTest.BracketTest
[       OK ] StringTest.BracketTest (0 ms)
[ RUN      ] StringTest.ParanthTest
[       OK ] StringTest.ParanthTest (0 ms)
[ RUN      ] StringTest.EqualTest
[       OK ] StringTest.EqualTest (0 ms)
[ RUN      ] StringTest.AmpersandTest
[       OK ] StringTest.AmpersandTest (0 ms)
[ RUN      ] StringTest.DoubleLessTest
[       OK ] StringTest.DoubleLessTest (0 ms)
[ RUN      ] StringTest.DoubleEqualTest
[       OK ] StringTest.DoubleEqualTest (0 ms)
[ RUN      ] StringTest.GreaterOpTest
[       OK ] StringTest.GreaterOpTest (0 ms)
[ RUN      ] StringTest.LesserOpTest
[       OK ] StringTest.LesserOpTest (0 ms)
[ RUN      ] StringTest.LesserEqualOpTest
[       OK ] StringTest.LesserEqualOpTest (0 ms)
[ RUN      ] StringTest.GreaterEqualOpTest
[       OK ] StringTest.GreaterEqualOpTest (0 ms)
[ RUN      ] StringTest.NotEqualOpTest
[       OK ] StringTest.NotEqualOpTest (0 ms)
[----------] 77 tests from StringTest (2 ms total)

[----------] Global test environment tear-down
[==========] 181 tests from 6 test cases ran. (5 ms total)
[  PASSED  ] 180 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] AVLListTest.toStrTest

 1 FAILED TEST
pj@pj:~/Programas_software/hyphy-2.3-alpha-working$

**Comment by stevenweaver** [comment]
Hello pj, 

The HYPHYGTK target configuration in CMake needs to be updated in order work with the latest releases of gcc. I will work on this shortly. 

Thanks,
Steven

**Comment by spond** [comment]
Dear @pjdias87,

Starting with v2.3 all the old GUI branches (including GTK) will no longer be supported. You should be able to compile HyPhy GTK with an older version (e.g. try v 2.2.5).

Release 3 will include an entirely different (JavaScript-based) front end.

Best,
Sergei
