### ISSUE TITLE
Use of more than one genetic code in a single run

### ISSUE THREAD

**Issue by pjdias87** [veg/hyphy#478]
Hi HYPHY community, 

I would like also to ask whether it is possible to assign different genetic codes to different sequences in the codon model file?

My sequences under analysis, although encoded in yeast species that are monophyletic (the Hemiascomycetes), encompass a large period of time and new results are showing that particular branches of this specific group of species have the tendency to “diverge” on the genetic code they use (S. cerevisiae = 1. The Standard Code, C. albicans = 12. The Alternative Yeast Nuclear Code, P. annophilus = 26. Pachysolen tannophilus Nuclear Code, probably this list will increase in the future…).

Of course, this problem can be solve by dividing the global phylogenetic trees into subset ones with single genetic code usage but, in my case, it would be interesting to test for positive selection on the whole phylogenetic tree to question at a large scale whether potential functional diversification of proteins is a recurrent and cronic effect on the homologs of a particular type of transporters or whether there are branches show the tendency for functional diversification to not occur.

If the answer is that HYPHY does not support multiple genetic codes in a single run, as I think it is, I leave the suggestion that maybe it could be an interesting feature to develop and make available in future versions of HYPHY, to increase flexibility and usability of the software.

Regards,

pj

**Comment by spond** [comment]
Dear @pjdias87,

You could develop a model in HyPhy that would technically accommodate multiple genetic codes in a tree. There are several conceptual issues with this however,

1). Along the branch where you have a change in genetic code, the **state space** of the Markov evolutionary model changes. In extreme cases, you could change the number of stop codons, for example. This is not directly handled by the modeling formalism. That said, you **could** encode everything in the space of 64 codons (which is a superset of all possible sense codon sets), and define different rate matrices for different branches.

2). How does one model transitioning from one genetic code to another? For example, what is the process for introducing previously disallowed stop codons into the alphabet of valid states? Just changing which amino acid is coded for by one of the codons is easier to handle.

3). A model like this will be non-reversible (which is not that much of an issue), but for such models the choice of equilibrium frequencies and placing of the root merits careful consideration.

Best,
Sergei
