### ISSUE TITLE
Help running MEME in batch mode on cluster

### ISSUE THREAD

**Issue by jullee** [veg/hyphy#479]
I have several genes to analyze using MEME and am trying to figure out how to run in batch mode, first on my local computer with one of the examples as a test, but ultimately on my university’s cluster. I’m having trouble figuring out the process of running from command line and hoping for some help. I’ve been following the answers on thread #249 but still can’t figure it out. Here’s a rundown of what I’ve tried.

1) Installation (on mac from linux source): I installed HyPhy using MP2 so my call to the program is:

/usr/local/bin/HYPHYMP

This brings up the expected menu and manually entering the inputs with one of the examples from the book chapter works so I’m fairly confident the application is installed correctly and that I can run MEME.

2) My text file, test.txt, for running in batch mode contains (as a test):

/Users/name/Desktop/p51.nex
/Users/name/Desktop/integrase_BDA.nex

3) I then created a separate file, “inputRedirect.bf” which contains (exactly copied from the wiki to just test the process using AnalyzeCodonData.bf):

```

fileToExe = HYPHY_BASE_DIRECTORY + "TemplateBatchFiles" + DIRECTORY_SEPARATOR + "AnalyzeCodonData.bf";

/* a  list of file paths */
SetDialogPrompt ( "Provide a list of files to process:" );
fscanf ( PROMPT_FOR_FILE, "Lines", _inDirectoryPaths );

fprintf (stdout, "[READ ", Columns (_inDirectoryPaths), " file path lines]\n");

/* the options passed to the GUI are encoded here */
inputRedirect = {};
inputRedirect["01"]="Universal";
inputRedirect["03"]="MG94CUSTOM";
inputRedirect["04"]="Local";
inputRedirect["05"]="012232";
inputRedirect["06"]="y";

for ( _fileLine = 0; _fileLine < Columns ( _inDirectoryPaths ); _fileLine = _fileLine + 1 ) {

    inputRedirect [ "02" ]  = _inDirectoryPaths[ _fileLine ];
    ExecuteAFile ( fileToExe, inputRedirect );
}
```

4) Now I’m stuck. In terminal, I call HyPhy and press “enter” to process custom batch file. At the first prompt, I provide the path to “inputRedirect.bf” (it’s on my desktop). At the second prompt, I provide the path to the “test.txt” (also on the desktop). But I receive an error:

```
[READ 2 file path lines]
Error:
Could not read command file in ExecuteAFile.
Original path: '/Users/name/TemplateBatchFiles/AnalyzeCodonData.bf'.
Expanded path: '/Users/name/TemplateBatchFiles/AnalyzeCodonData.bf'

Function call stack
1 : ExecuteAFile from file fileToExe using basepath /Users/Julie/Desktop/. reading input from inputRedirect
{"01":"Universal",
"03":"MG94CUSTOM",
"04":"Local",
"05":"012232",
"06":"y",
"02":"/Users/name/Desktop/p51.nex"}
-------
```

I don’t understand how to tell it where to look for TemplateBatchFiles? I can’t actually see this folder anywhere on my computer. I’ve tried running the program via command line after cd-ing to the desktop and to the location with the Hyphy GUI (with df and text file on the Desktop versus in the same folder with the GUI). What am I missing? 

5) Then, as a secondary question (for once I actually get this working), in that previous post, it was suggested that to save outputs from each of the input files to a separate file, once could “try this”

```
LoadFunctionLibrary  ("GrabBag");
...
pathInfo = splitFilePath (PATH_TO_CURRENT_BF + _inDirectoryPaths[ _fileLine ]); 
// if you have relative path names OR
pathInfo = splitFilePath (_inDirectoryPaths[ _fileLine ]); 
// if you have absolute path names
outputFile = pathInfo["DIRECTORY"] + DIRECTORY_SEPARATOR + pathInfo["FILENAME"] + ".hyphy.out";
...

```

Can you provide a bit of an explanation for newbies? Are these commands we add in Terminal? or to the inputRedirect.bf? For instance, to get the MEME analysis running, I think my inputRedirect file would look something like the following, but there should be an inputRedirect["07”] that specifies an out file and I'm not sure how to do this with a unique file name for all of my genes...

```
fileToExe = HYPHY_BASE_DIRECTORY + "TemplateBatchFiles" + DIRECTORY_SEPARATOR + "QuickSelectionDetection.bf";

/* a  list of file paths */
SetDialogPrompt ( "Provide a list of files to process:" );
fscanf ( PROMPT_FOR_FILE, "Lines", _inDirectoryPaths );

fprintf (stdout, "[READ ", Columns (_inDirectoryPaths), " file path lines]\n");

/* the options passed to the GUI are encoded here */
inputRedirect = {};
inputRedirect["01”]="Universal";
inputRedirect["02”]="New Analysis";
inputRedirect["04”]=“Custom”;
inputRedirect["05”]=“012345;
inputRedirect["06”]=“y”
inputRedirect["08”]=“Estimate dN/dS only";
inputRedirect["09”]=“MEME”;
inputRedirect[“10”]=“0.1”;

for ( _fileLine = 0; _fileLine < Columns ( _inDirectoryPaths ); _fileLine = _fileLine + 1 ) {

    inputRedirect [ "03” ]    = _inDirectoryPaths[ _fileLine ];
    ExecuteAFile ( fileToExe, inputRedirect );
}
```

Thanks in advance for the advice! I've been severely stuck so I appreciate any help!

**Comment by spond** [comment]
Dear @jullee,

The standard install will place library files in `/usr/local/lib/hyphy`. Try

```
$ls /usr/local/lib/hyphy/
``` 
and if you see something like 

```
ChartAddIns		GeneticCodes		SubstitutionModels	TopologyInference	UserAddins
DatapanelAddIns		SubstitutionClasses	TemplateBatchFiles	TreeAddIns		data
```

then everything is as expected.

Sometime in the last several years we (2012, I think), we introduced a new path variable called, **HYPHY_LIB_DIRECTORY** (instead of **HYPHY_BASE_DIRECTORY**, which is now the working directory), so you may have some luck changing **HYPHY_BASE_DIRECTORY** to **HYPHY_LIB_DIRECTORY**, and adding a debug statement 

```
fprintf (stdout, "\n\n", HYPHY_LIB_DIRECTORY, "\n\n");
```

at the top of your inputRedirect.bf file

Your approach to MEME wrappers is correct -- you just add options to the input redirect dictionary, whatever is appropriate for the file at hand.

Then you can run something like

```
$(echo list_of_files) | HYPHYMP redirect.bf 
```

to completely automate the process.

Best,
Sergei

**Comment by jullee** [comment]
Hi Sergei,

Thanks for getting back to me. I made the HYPHY_LIB_DIRECTORY change in my inputRedirect.bf file and that allowed me to run my test batch example in terminal.

However, I'm still very confused about where the output is going. In my test example (ie. the file in point 3 in my question), I didn't make any adjustments to try to redirect the output. And after running, I don't see any output files in the directory with the input files. Where do these go as a default?

But more importantly, can you please elaborate on how to loop through files and send the output to files with the same names? I don't understand the batch language enough to follow the script. Is this what you were getting at in the last few lines of your response? If so, is redirect.bf the same as inputRedirect.bf?

Many thanks!
