### ISSUE TITLE
questions about Hyphy

### ISSUE THREAD

**Issue by nahidshokri** [veg/hyphy#482]
Dear Sergie, 

Thank you so much for your explanation.  I am very newbie in Hyphy and want to make sure that the hypotheses I am testing is the appropriate ones regarding to my data. Here I have got three questions:

1)  To compare tree wide global rate versus local rate, is it necessary to constrain a default substitution model (such as MG94xREV 3x4 ) to a best fit nucleotide model before optimizing of Local parameters?

2)  If I compare a tree wide global rate of selection (dN/dS)versus local rate and get a p value in the favour of global rate , does it mean that I cannot go further and compare the rate of evolution between different branches in tree(by using TestbranchdNdS.bf) or doing interclade variation in substitution rate (through SelectionLRT.bf)? 

3)  if I compare a tree wide global rate of selection (dN/dS)versus local rate and get a p value in the favour of global rate, can I go further and estimate rate of evolution site_by_site?

Many thanks in advance
Nahid

**Comment by spond** [comment]
Dear @nahidshokri,

I would suggest you run aBSREL to understand the distribution of codon-level substitution rates across branches. It's a fully automated analysis, and you will also get a local / global (single dN/dS) rate comparison by looking at the AIC scores of the optimized model, and the single dN/dS model.

Take a look at https://github.com/veg/hyphy-tutorials/tree/master/selection#use-absrel-to-find-lineages-which-have-experienced-episodic-diversification 

Best,
Sergei

**Comment by nahidshokri** [comment]
Dear Sergei, 

Thank you so much for your explanation. I used aBSREL as you suggested. Now I have got 4 questions:

1) What is Mean_dNdS in the csv output file? I asked this question because I got just one value of omega for each branch during phase 2 (in Hyphy console)which is a bit different from reported Mean_dNdS for each branch. However, in one case Mean_dNdS for one of the branch is 10 while it was reported 0 in phase 2.

2)Here is the summary of my result regarding single model and full model:
Model	log L	      # par.	AICc	     Time to fit	Ltree
MG94	-2238.89	24	4526.36	15 sec.	0.13
Full model	-2231.51	26	4515.71	13 sec.	0.30

With regard to the AICc, is that correct saying that there is an obvious site_by_site variation of rate among branches?

3)one of my aims is comparison of substitution rate among branches. I was wondering if I can use Mean_dNdS as an ultimate amount of omega for each branch for comparison?

4) When I want to see json output file, the web app (mentioned in tutorial) doesnt open.

Thank you so much in advance
Nahid

**Comment by nahidshokri** [comment]
Hi Sergei,

I could find the answer for the questions number 1 and 4 from last email. Please help me to find answer for the below questions:

1)Here is the summary of my result regarding single model and full model:
Model log L # par. AICc Time to fit Ltree
MG94 -2238.89 24 4526.36 15 sec. 0.13
Full model -2231.51 26 4515.71 13 sec. 0.30

With regard to the AICc, is that correct saying that there is an obvious site_by_site variation of rate among branches?

2)If site by site  substitution rate varies among branches(according to AIC score), is there any way to show the difference of  rate among branches? I think that we can use rate distribution of full model to show the difference(provided in the json file). Am I right ?

Thanks in advance
Nahid

**Comment by spond** [comment]
Dear @nahidshokri,

1. There is no such thing as **obvious difference** in statistics, of course, but AIC indicates that the model which allows site-to-site rate variation among **some** branches is preferred to the simpler model that does not. **However**, because AIC is used to make a data-driven model construction choices, you have to be a bit cautious in interpreting it: AIC was derived assuming that the models being compared were chosen **before** looking at the data. Here we use the data to choose the models. All that aside, your data do show evidence of site-to-site rate variation.

2. The rate estimates derived from branches can be used **only for exploratory** purposes. Just because dN/dS distributions inferred from two branches have different values, you can't say they are different in a statistically significant way. The only formal test done by aBSREL is whether or not there is evidence of dN/dS > 1 along any given branch. For formal testing of differences between branches, you could consider using RELAX.

Best,
Sergei

**Comment by nahidshokri** [comment]
Thank you so much for the wonderful explanation. 

Kind regards
Nahid

**Comment by nahidshokri** [comment]
Hi Sergei, 

As you may remember, I was to use Relax analysis to compare selection pressure on different parts of tree. I just run Relax.bf and have two questions:

1- When I upload my tree file (which is as follows), 
((E_angophorae{TEST}:0.01531741,E_robusta{TEST}:0.01173479)Node1{TEST}:0.00870492,(I_excavata{REFERENCE}:0.01952825,I_schwarzi{REFERENCE}:0.02563565)Node4{REFERENCE}:0.02442718);
a  **reference branches setting** doesn't appear  in the file dialog to select reference branches. I run the same analysis using your example tree file(HIV-relax.nwk) and didnt come across the same issue. 
Could you please let me know what is the problem with my tree file? I compared my tree file with yours many times and couldn't find anything. 

2-my second question is about the number of test  and reference branches. Can I run Relax analysis just on one test branch and one reference branch? I asked this question as  I am not sure how much  obtained output is reliable in that case

Many thanks in advance
Nahid
