### ISSUE TITLE
HYPHYMPI not running on CentOS 6.8

### ISSUE THREAD

**Issue by ArtPoon** [veg/hyphy#483]
I can build HYPHYMPI on a fresh install of Ubuntu using the following workflow:
1. `git clone https://github.com/veg/hyphy.git`
2. `sudo apt install libopenmpi-dev`
3. `sudo apt install cmake`
4. `cd hyphy; cmake .`
5. `make MPI`
6. `sudo make install`

but I'm having trouble building in CentOS 6.8 (Scyld CW kernel 2.6.32-642.6.1.el6.684g0000.x86_64).  The first issue I ran into is that `yum install cmake` installs an older cmake (2.8.12.2) that is not supported by HyPhy, so I compiled the latest release of cmake (3.6.2).  I loaded the openmpi/gnu/2.0.1 Scyld module and ran through the `cmake; make MPI; sudo make install` process.  

If I run the resulting binary as a serial process, then it seems to function okay; for example, running `./HYPHYMPI Examples/SimpleAnalyses/HKY85.bf` returns the expected output.  However, if I run `mpirun -np 4 ./HYPHYMPI Examples/SimpleAnalyses/HKY85.bf`, then the output from four separate instances of HyPhy are written to the console.  Next, I wrote a little test script:
```
fprintf (stdout, MPI_NODE_COUNT);
```
and confirmed that if I invoke the script with `mpirun -np 4 test.bf` I get the following output:
```
1

1

1

1

```

I'm going to try compiling with MPICH next and will report back.

**Comment by ArtPoon** [comment]
Same result.  
```
$ module unload openmpi/gnu
$ module load mpich/gnu
$ make clean
$ cmake .
$ make MPI
$ ./HYPHYMPI test.bf
1

$ which mpirun
/opt/scyld/mpich/3.2/gnu/bin/mpirun
$ mpirun -np 4 ./HYPHYMPI test.bf
1

1

1

1

```

**Comment by spond** [comment]
Hi @ArtPoon,

I haven't seen this behavior before; @stevenweaver  can you please see what's going on? 

Sergei

**Comment by stevenweaver** [comment]
Using openmpi@1.6.3 on CentOS 6.7, this behavior cannot be replicated. Attempting to reproduce with the mentioned implementations of the MPI protocol now.

**Comment by stevenweaver** [comment]
I can confirm identical behavior using mpich. If @ArtPoon is using Scyld Clusterware, `openmpi/gnu/1.6.3` and `openmpi/gnu/1.6.5` are the only modules I have tested that are functioning as desired. Please verify that these modules are available via the command `module avail`. 

 I currently do not have an explanation for what is happening, but aforementioned should at least be a temporary solution until we find something more conclusive.

**Comment by ArtPoon** [comment]
Ran the following:

```
$ sudo yum install openmpi-1.6-scyld-gnu
$ module unload mpich2/gnu
$ module load openmpi/gnu/1.6.5
$ which mpirun 
/opt/scyld/openmpi/1.6.5/gnu/bin/mpirun
$ make clean
$ cmake .
$ make MPI
$ mpirun -np ./HYPHYMPI test.bf
```

Still same broken output...

**Comment by stevenweaver** [comment]
Hello @ArtPoon, 

I believe this problem could be with CMake. No matter which module is loaded, CMake insists to use openmpi/1.6.3 despite absolute no reference to that directory in my environment variables.

My current conjecture is that this must be happening with you as well, but with a different directory. I'm still trying to resolve this issue, but I wanted to give you an update.

**Comment by ArtPoon** [comment]
Hi Steven, very much appreciated.  I'll keep working at it tonight; I'm probably missing something obvious.  If you'd like I can set up an account for you.
A

**Comment by stevenweaver** [comment]
Sure, please email me at sweaver@temple.edu

**Comment by ArtPoon** [comment]
Ok, it was `cmake` but not the way we thought.  I decided to try cleaning the leftover files from running cmake (in build directory):
```
$ rm cmake_install.cmake 
$ rm CMakeCache.txt
$ rm -rf CmakeFiles
$ module load openmpi/gnu/2.0.1
$ cmake .
$ make MPI
$ mpirun -np 3 ./HYPHYMPI test.bf
3 
```
Going to try to repro the original problem.

**Comment by ArtPoon** [comment]
Got it.  Running `cmake .` without first having a specified a Scyld MPI module (such as openmpi/gnu) raised warnings:
```
-- Unable to determine MPI from MPI driver /usr/bin/mpicc
-- Could NOT find MPI_C (missing:  MPI_C_LIBRARIES MPI_C_INCLUDE_PATH) 
CMake Warning at /usr/local/share/cmake-3.6/Modules/FindMPI.cmake:420 (message):
  Unable to find MPI library mpich++-gnu
```
and the user is unable to build the target with `make MPI`.  If you then load an MPI module and re-run cmake, you are able to build the MPI target but it will not be MPI-enabled (`test.bf` outputs 1's).  If you erase the CMake files and then run through the build process again, the binary is MPI-enabled.
