### ISSUE TITLE
Removing deprecated targets/code

### ISSUE THREAD

**Issue by spond** [veg/hyphy#486]
Starting with `v2.3-dev` branch we should

- [x] Remove all the GUI code and resources, because it is no longer being supported and won't compile with the current core.

- [x]  Remove MAC and GTK targets from CMakeLists.txt

- [ ] Go through the remaining code and clean up #ifdefs (I'll do that one piecemeal)

**Comment by stevenweaver** [comment]
Hi Sergei,

I'm going to close this issue due to the last checkmark item will be done via erosion.

Best,
Steven
