### ISSUE TITLE
BUSTED: Difference between "constrained" and "optimized null" evidence ratio plots 

### ISSUE THREAD

**Issue by nmathers** [veg/hyphy#487]
Hi,

What is the difference between the two lines on the 2Ln Evidence ratio vs. site plot provided with the BUSTED output (on the datamonkey server)? Essentially, I am confused as to how the constrained and optimized null evidence ratios differ, as well as how to interpret each of them separately.

Of course, I will also be using MEME to more confidently identify single sites under selection.

Thank you!!

**Comment by spond** [comment]
Dear @nmathers,

BUSTED fits two models 

1. With positive selection (&omega; &ge; 1 for some proportion of branch sites). Call it M<sub>+</sub>
2. Without positive selection (&omega; &ge; 1 for some proportion of branch sites). Call it M<sub>0</sub>

At each site you can evaluate an **ad hoc** measure of support by comparison the full model M<sub>+</sub> **at that site** with model that disallows positive selection.

- In [constrained], the null model simply moves the &omega; value from M<sub>+</sub> to 1 (leaving all other parameters untouched) and computes 2*log (LR)

- In [optimized null] M<sub>+</sub> is compared with M<sub>0</sub> (again via a site level 2*log(LR)) at the level of a single site. The key difference is that all model parameters can now differ from  M<sub>+</sub>

Best,
Sergei

**Comment by nmathers** [comment]
Okay, thank you!
