### ISSUE TITLE
Running QuickSelectionDetectionMF.bf

### ISSUE THREAD

**Issue by njxyc** [veg/hyphy#489]
The Console returned an error when I got Phase 4. Could anyone explain it for me?

Phase 4: Selection Analysis

Error:
Can't assign within another assignment in the following context: '1,0,1,0)SHORT_MPI_RETURN=<ERROR HERE>1'

Function call stack
1 : pValue=prompt_for_a_value("Significance level for Likelihood Ratio Tests",0.1,0,1,0)SHORT_MPI_RETURN=1

**Comment by njxyc** [comment]
Here is my Phase 1 to 3:
Phase 1:Nucleotide Model (010010) Model Fit


Log Likelihood = -12108.5510919734;
Shared Parameters:
AC=0.2937444622027141
AT=AC=0.2937444622027141
CG=AC=0.2937444622027141
CT=1=1
GT=AC=0.2937444622027141

Tree nucTree_1=((((((AGP75916_5:0.01237614578787779,AGP75918_7:0.02032619001242421)Node6:0.0145876976496896,AGQ42597_3:0.03195608141238799)Node5:0.06338176968689099,AGP75914_3:0.05516377468801349)Node4:0.01665557316491563,AGP75917_6:0.07354455504817997)Node3:0.02024041430663289,(AGP75913_2:0.004300323077882717,AGQ42596_1:0.004532574273968422)Node12:0.09130709862433198)Node2:0.01872951018544706,AGQ42598_2:0.0922722926402858,BRADI2G60434:0.2321091140459106);


Phase 2:MG94x(010010) Model Fit



Phase 3:Estimating dN/dS


Nuc->codon scaling factor:1.60497110835854
Raw scaling factor:1.60497110835854
Tree scaling factor(S): 1

Using dN/dS=0.5086774960291771
Codon model:Log Likelihood = -11867.9439732423;
Shared Parameters:
dNdS=0.5086774960291771
rConstr=1.178665892625431/(0.3190463683649198+dNdS*0.8165057963307383)=1.60497110835854

Tree codonTree_1=((((((AGP75916_5:0.01237614578787779,AGP75918_7:0.0203261900124242)Node6:0.0145876976496896,AGQ42597_3:0.03195608141238798)Node5:0.06338176968689098,AGP75914_3:0.05516377468801348)Node4:0.01665557316491562,AGP75917_6:0.07354455504817993)Node3:0.02024041430663289,(AGP75913_2:0.004300323077882716,AGQ42596_1:0.004532574273968423)Node12:0.09130709862433196)Node2:0.01872951018544706,AGQ42598_2:0.09227229264028573,BRADI2G60434:0.2321091140459105);

**Comment by spond** [comment]
Dear @njxyc,

This looks like an old syntax error (not sure how that slipped through the cracks; what version are you using). You should be able to fix it by editing QuickSelectionDetection.bf and adding a semicolon following before SHORT_MPI_RETURN

```
 pValue=prompt_for_a_value("Significance level for Likelihood Ratio Tests",0.1,0,1,0);
SHORT_MPI_RETURN=1
```

In a default UNIX install, you will find QuickSelectionDetection.bf in /usr/local/lib/hyphy/TemplateBatchFiles

Best,
Sergei

**Comment by njxyc** [comment]
Dear @spond,

Thanks, the version is 2.2.4 (for Mac), but I can't find QuickSelectionDetection.bf in /usr/local/lib/hyphy/TemplateBatchFiles.

Best

**Comment by njxyc** [comment]
Dear @spond ,
I found QuickSelectionDetection.bf in the package, but the semicolon you mentioned seems already exit before SHORT_MPI_RETURN=1, the code is like this:
if (cOptions == 0) {		
	ExecuteAFile("SGEmulator_MF.bf");
}
else { // FEL 
    pValue = prompt_for_a_value ("Significance level for Likelihood Ratio Tests",0.1,0,1,0)
					
	SHORT_MPI_RETURN = 1;
	FEL_RUN_TIMER    = Time(1);
	FEL_MASTER_TIMER = Time(0);
 
Best

**Comment by spond** [comment]
Dear @njxyc,

Insert the semicolon following at the end of line `pValue = prompt_for_a_value ("Significance level for Likelihood Ratio Tests",0.1,0,1,0)`

Best,
Sergei

**Comment by njxyc** [comment]
Dear @spond, 

It fixed!

Thanks very much!

Best
