### ISSUE TITLE
Job queue in DataMonkey

### ISSUE THREAD

**Issue by njxyc** [veg/hyphy#490]
Hi, @stevenweaver 

There are some jobs remaining in the Job queue of DataMonkey for more than 4 days. It seems like that they are all REL or PARRIS analysis. Is there any problem? I wanna perform a PARRIS analysis. Thanks!

**Comment by stevenweaver** [comment]
Hello @njxyc,

The datamonkey queue became stuck. I've cleared the queue, please resubmit any jobs you would like to run. 

Apologies for the inconvenience, 
Steven
