### ISSUE TITLE
Why I need to specify codon data #1 sometimes?

### ISSUE THREAD

**Issue by njxyc** [veg/hyphy#491]
Some of my nexus format file don't need me specify codon data when I perform QuickSelectionDetectionMF.bf, but some need after I upload datafile. There is a window told me 'Please specify codon data #1'. What is codon data?

**Comment by spond** [comment]
Dear @njxyc,

This prompt should only come up in FUBAR (as far as I can recall); you need to supply the file name of the analysis. Some analyses that are recombination-aware, **could** prompt you for multiple files (one per non-recombinant partition).

Best,
Sergei
