### ISSUE TITLE
Busted error "spawn EMFILE"

### ISSUE THREAD

**Issue by vabadu** [veg/hyphy#493]
Hello,

I have tried to start a BUSTED analysis on Datamonkey, but I am getting the error message "spawn EMFILE".  This data file opened fine with HYPHY.  

Thanks for your help, Vanessa

**Comment by stevenweaver** [comment]
Hello Vanessa, 

This was due to a configuration issue on our servers.
Can you please try again? I am actively monitoring the situation. 

Best,
Steven

**Comment by vabadu** [comment]
Thanks Steven,

I was able to start an analysis this time.
