### ISSUE TITLE
Web app for visualization results-File not Found

### ISSUE THREAD

**Issue by avicens** [veg/hyphy#495]
Hi,

I run an aBSREL analysis in Hyphy, but as I tried to go to the web app to visualize the results (http://veg.github.io/hyphy-vision/absrel/) the page is not found. I've noticed this also occurs with other web apps such as RELAX (http://veg.github.io/hyphy-vision/relax/).

Why is occurring this error? Is there a new/another way to access to these apps?

Best

**Comment by spond** [comment]
Dear @avicens,

Apologies for this, try http://veg.github.io/hyphy-vision/pages/absrel/

Best,
Sergei

**Comment by avicens** [comment]
It worked!

Thanks Sergei.
Alberto
