### ISSUE TITLE
GARD job killed

### ISSUE THREAD

**Issue by luisdelaye** [veg/hyphy#500]
Hi,

I'm running GARDMPI on a cluster with a file named hyphy3.msgA.sh:

$ more hyphy3.msgA.sh 

#PBS -N test_msgA3
#PBS -l nodes=1:ppn=8,mem=40gb
#PBS -q default
#PBS -V
module load hyphy/2.220
mpirun -np 8 HYPHYMPI /data/software/hyphy/res/TemplateBatchFiles/GARD.bf < /LUSTRE/usuario/ldelaye/stdin3.txt

and a file named stdin3.txt:

$ more stdin3.txt 
/LUSTRE/usuario/ldelaye/msgA/Msg-A.e2.ed1.tres.o.manual.aln.e1.Pj.fasta
010010
1
/LUSTRE/usuario/ldelaye/msgA/Msg-A.e2.ed1.tres.o.manual.aln.e1.Pj.out

However, when I submit the job:

qsub hyphy3.msgA.sh

I get an error message with the following information:

application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
=>> PBS: job killed: vmem 3372163072 exceeded limit 2147483648

I tried the same analysis doubling the amount of memory to mem=80gb, however, I get the same result:

=>> PBS: job killed: vmem 3587260416 exceeded limit 2147483648

I suspect that perhaps the limit of 2147483648 is something specified inside HYPHYMPI. 

Is there a way to fix this problem?

Thanks!

Luis Delaye

**Comment by stevenweaver** [comment]
Hello Luis,

2147483647 is a very special number, it is the maximum positive number for a signed 32-bit integer.
I think it might be a default limit with your TORQUE installation.

Can you please try the following, change
```
#PBS -l nodes=1:ppn=8,mem=40gb
```

to 
```
#PBS -l nodes=1:ppn=8,mem=40gb,vmem=40gb
```

and try again?

**Comment by luisdelaye** [comment]
It works!
Thanks!
Luis
