### ISSUE TITLE
Cannot print likelihood function after calling ConstructCategoryMatrix

### ISSUE THREAD

**Issue by gtiley** [veg/hyphy#502]
I am optimizing model parameters under some non-standard substitution models; however, I want to print both the parameter estimates with the lnL for the tree as well as the likelihoods for each site. It seems that after I use ConstructCategoryMatrix, I can no longer print the likelihood function object or even the the Optimize receptacle. 

I tried to simply print the likelihood function object before calling ConstructCategoryMatrix to get the vector of site likelihoods, but doing this causes the site likelihoods to not print, as if the likelihood object is no longer available to be passed to ConstructCategoryMatrix.

I've attached an example batch file, data, and output. I appreciate any thoughts you might have on returning both the likelihood function object and site likelihoods from the same optimization results.
[test.zip](https://github.com/veg/hyphy/files/655622/test.zip)

**Comment by ArtPoon** [comment]
Did you try setting `LIKELIHOOD_FUNCTION_OUTPUT=7`?

**Comment by gtiley** [comment]
I just tried it. I get a nexus block as well as the parameter estimates, but still no output of the site likelihoods.

**Comment by spond** [comment]
Dear @gtiley,

Please see the following edited file (I changed the extension to .txt so that I could attach it here directly). Look for `SLKP` comments. The main issue was a missing semicolon following `ConsrtuctCategoryMatrix`.

Best,
Sergei

[test1.txt](https://github.com/veg/hyphy/files/657763/test1.txt)

**Comment by gtiley** [comment]
Great, that resolves everything! I appreciate the additional comments too, it definitely helps to know more about how HYPHY initializes the rate matrix.

Thanks!

George
