### ISSUE TITLE
aBSREL error

### ISSUE THREAD

**Issue by nmathers** [veg/hyphy#505]
Pond & Colleagues,

I have received the following error messaging for a job on the aBSREL server:

unable to read results file. Error: ENOENT, open '/home/datamonkey/datamonkey-js-test/app/absrel/output/585881255ea7fa6b719d3af3.absrel.json'

This has happened a few times with the same data set (NEXUS file with user tree and codon alignment). I've noticed that 1) A convergence problem repeatedly occurs and 2) The job run time is about 48 hours when the error occurs.

Is there a time limit on jobs submitted to the new test.datamonkey.org server? 
Is the convergence problem an issue to worry about? Is this possibly due to any properties of the particular data set? 

I've attached the log file associated with this job. 

Thanks a lot!! (sorry for another question... this site is a great resource and it's very much appreciated)

[aBSREL_log_error_occured.txt](https://github.com/veg/hyphy/files/667797/aBSREL_log_error_occured.txt)

**Comment by stevenweaver** [comment]
Dear @nmathers,

I can immediately confirm that there is a 48 hour time limit on jobs submitted to test.datamonkey.org. 

I will leave this bug open until I find a place on the site to make it clear what the time limit is, and create an error report that is more informative of what actually occurred. 

The number of sites (426) and sequences (78) in this dataset shouldn't be taking more than 48 hours to complete. I would need to debug the aBSREL HyPhy script, which may take some extra time. 

Best,
Steven

**Comment by nmathers** [comment]
Okay, thanks for looking into this!

Nick

**Comment by nmathers** [comment]
To follow up on this post:

Is a repeated convergence problem during aBSREL an issue for obtaining robust results?

What exactly is meant by convergence in aBSREL?

Thanks!
