### ISSUE TITLE
BGM co-evolution error on the command line: HYPHYMPI terminated. ERROR: _SimpleList parents not expected length (1), found

### ISSUE THREAD

**Issue by Batsi-2015** [veg/hyphy#508]
I would like to run spidermonkey on the desktop but I am having an error "HYPHYMPI terminated.
ERROR: _SimpleList parents not expected length (1), found". 

**I am using the following script in HYPHY 2.220160915beta(MPI) for Darwin on x86_64:** 

```
inputRedirect = {};
inputRedirect["01"]="Universal";
inputRedirect["02"]="New Analysis";
inputRedirect["03"]="/Users/batsirai/Documents/Laboratory_Notes/Virology/Selection_Analyses/gp160/SPIDERMONKEY/gp160_6-48wks_NSC.fasta_gardout_finalout";
inputRedirect["04"]="Default";
inputRedirect["05"]="y";
inputRedirect["06"]="/Users/batsirai/Documents/Laboratory_Notes/Virology/Selection_Analyses/gp160/SPIDERMONKEY/file_output.txt";
inputRedirect["07"]="Estimate";
inputRedirect["08"]="BGM co-evolution";
inputRedirect["09"]="Averaged";
inputRedirect["10"]="1";
inputRedirect["11"]="2";
inputRedirect["12"]="10000";
inputRedirect["13"]="100";
inputRedirect["14"]="20";
inputRedirect["15"]="No";
ExecuteAFile ("/usr/local/lib/hyphy/TemplateBatchFiles/QuickSelectionDetection.bf", inputRedirect);
```

**I am getting the error below, I have tried changing the chain length and sampling steps up to 1 sample, I still get the same error:**

```
Total Sites:2640;
Distinct Sites:455

Phase 1:Nucleotide Model (010010) Model Fit


-22672.8164143522

Phase 2:MG94x(010010) Model Fit



Phase 3:Estimating dN/dS


Nuc->codon scaling factor:1.609960048160828
Raw scaling factor:1.648891214527887
Tree scaling factor(S): 1.024181448733173

Using dN/dS=0.5226749801920106
Codon model:-22296.6791567467

Phase 4: Ancestral State Reconstruction and Counting


Counts of inferred non-synonymous substitution by site

    Count    = 880
    Mean     = 1.804545454545454
    Median   = 0
    Variance = 28.480525390423
    Std.Dev  = 5.336714850019908
    COV      = 2.957373468524886
    Sum      = 1588
    Sq. sum  = 27900
    Skewness = 18.20262580309328
    Kurtosis = 11.32657841037727
    Min      = 0
    2.5%     = 0
    97.5%    = 22
    Max      = 32

<<Include only sites with at least this many total substitutions (permissible range = [1,29], default value = 1, integer)>>
Found 223 sites with at least one non-synonymous mutation
<<Run the MCMC chain for this many iterations (permissible range = [1000,1e+26], default value = 100000, integer)>><<How many burn-in steps before the main chain is run (permissible range = [100,1e+26], default value = 1000, integer)>><<Sample from the chain every so many steps (permissible range = [10,10000], default value = 100, integer)>>
Running a BGM on 223 nodes with
                       2 maximum parents per node
                     100 burn-in steps
                   10000 chain length
                     495 samples
**HYPHYMPI terminated.
Error:
ERROR: _SimpleList parents not expected length (1), found** 

HYPHYMPI terminated.
Error:
ERROR: _SimpleList parents not expected length (1), found 

HYPHYMPI terminated.
Error:
ERROR: _SimpleList parents not expected length (1), found 
```

Thanks!

Batsirai

**Comment by ArtPoon** [comment]
Hi Batsi, thanks for porting your e-mail to the github issue tracker.  I've taken the liberty of snipping out the MPI error messages; I had a look through this output and I don't think it pertains to your issue.  I've tried to reproduce the issue using the `p51.nex` example data file and the current master build of HyPhy, but could not get this error.  Can you please run with `p51.nex` on your side so that we can eliminate the input data file as a potential cause?

**Comment by Batsi-2015** [comment]
Hi, thank you for the reply. I think its something to do with the version, I ran the script on the recent release of HyPhy and I didn't get errors using both the p51.nex and my own dataset. I got a csv file with the posterior edges support, but I haven't figured how to get the nice plots I get when I use the datamonkey server. 

After getting the posterior edges support, I haven't really understood what the last part of the analysis does. I have pasted what I did below, my aim was to export all the analysis results. I tried saving it as zip and pdf, but both files can't open. 

**********Continue with result processing (y/n)?y


	 Available Result Processing Tools
	 ---------------------------------


	(1):View Results
	(2):Save Results
	(3):Variance Estimates
	(4):Save Covariance Matrix
	(5):Parameter Sampler
	(6):Syn and non-syn trees
	(7):Ancestral Sequences
	(8):Suzuki-Gojobori Derived Adapative Selection Tool

 Please type in the abbreviation for the tool you want to use (or press q to exit):2


			+----------------------------+
			|Choose a Likelihood Function|
			+----------------------------+


	(1):[nucLF] Likelihood Function "nucLF".
	(2):[lf] Likelihood Function "lf".

 Please choose an option (or press q to cancel selection):2


			+---------------------------+
			|Likelihood Function Display|
			+---------------------------+


	(1):[Value Only] Display Only the ln-likelihood value.
	(2):[List] Display the ln-likelihood value followed by a list of parameter estimates.
	(3):[Standard Tree] Display the ln-likelihood value followed by a tree string with branch lengths representing the expected number of substitutions per site.
	(4):[Parameters only] Display the list of independent parameters and constraints.
	(5):[Parameters+Values] Display the list of parameter names, constraints and MLEs.
	(6):[Parameters+Values+Trees] Display the list of parameter names, constraints and MLEs followed by tree string(s) with branch lengths representing the expected number of substitutions per site.
	(7):[Export Analysis] Save all the components of the analysis in a self-contained HyPhy batch file.

 Please choose an option (or press q to cancel selection):7

/usr/local/lib/hyphy/TemplateBatchFiles/Save results to::/home/batsiraim/Documents/virology/spidermonkey/bgm.zip

**Comment by ArtPoon** [comment]
The exact answer to your question is that option 7 saves a serialized likelihood function, but is probably a completely useless answer as well 😁 
HyPhy has fit a model of evolution to your sequence alignment.  That model contains a number of parameters.  For a given set of data, every setting of these model parameters has a different likelihood of producing your data.  (Likelihood is related to probability with important distinctions that I won't go into here.)  Thus, the likelihood is a *function* of the model parameters and the data.  
HyPhy has used a heuristic algorithm (a recipe for getting an answer that isn't guaranteed to be the correct answer, but should be good enough) to estimate what the best parameter values *seem* to be given your data.  These values are the maximum likelihood estimates of the model parameters.
We want to save this likelihood function with the maximum likelihood parameter estimates.  However, it exists in your computer memory in a machine-readable format that is specific to the program and can't be read directly by any other program.  That means we have to turn it into a generic format; in this case, plain text.  This process is called "serialization".  Another program may still not know how to read the likelihood function in this text (serialized) form, but at least we can open the file in a text editor like Word and have some hope of reading through the contents.  
Our convention for naming files that contain serialized likelihood functions is to append the extension `.lf`.  Your computer won't recognize that files with this extension are associated with HyPhy.  If you double-click on the file, it's not going to open in HyPhy -- in fact I can't even guess what the default application might be.  However, if you quit and re-open HyPhy, you can re-load the likelihood function (your model and data) along with the maximum likelihood parameter estimates into memory (which all got lost when you quit the program) by opening the `.lf` file in HyPhy.
Hope that helps,
- Art.

**Comment by Batsi-2015** [comment]
Thank you so much, it really helped a lot!
