### ISSUE TITLE
Detection of negative selection and neutral evolution with BS-REL

### ISSUE THREAD

**Issue by FraLeon** [veg/hyphy#512]
Hey,
I´m working on molecular evolution in my master thesis and applied the Branch-site-REL method using the datamonkey-server on three datasets of mammalian genes in order to detect lineage specific patterns of evolution.

Now after reading the corresponding paper (Pond et al, 2011) for the method and analysing the results for my datasets there are still two questions I couldn`t answear yet.

1) How is it possible that there are some omega 3 (omega +) values smaller than 1, if the three categories are defined as ω- ≤ ωN ≤ 1 ≤ ω+ to define the three markov substitution models? I already realised that non of these branches (with ω+ < 1) showed a significant evidence for positive selection. But I still don´t get, why there can be values like this in the first place.

2) Since the genes of my datasets are obtained by losses of these genes in other mammals, not only positive selection on specific branches is interesting for me but also branches with high amounts of neutral evolution or negative selection are very interesting. But since a Likelihood ratio test is only performed subsequently to confirm the significance of positive selection I was wondering whether amounts of negative/neutral evolution in other branches are meaningful aswell?
Or would you still need to do another LRT to prove these data as significant? And do you know whether there is any possiblity to perform such additional LRTs?
Apparently there are not many algorithms/models to test neutral evolution or negative selection...

I hope you can help me with these questions.
Thanks a lot in advance!

Best,
Franziska

**Comment by stevenweaver** [comment]
Dear Franziska,

Despite not being an author on this paper, I may be able to help a bit. As a caveat, some of my answers may not be entirely 100% accurate.

1) After looking at the batch file for BranchSiteREL.bf, a constraint for ω+ is never actually set. However, the constraint seems to be applied _post_hoc_. In other words, an initial estimate of ω+ > 1 is set, but the likelihood estimation will allow the parameter to dip below 1. If the parameter does dip below 1, then the hypothesis for that rate class is automatically rejected. This should mean that for every time you see ω+ with a value of less than 1, the p-value should be 1.

2) BS-REL may not be the best solution for detecting negative/neutral evolution. Please take a look at this issue thread #287 

Specifically, Dr. Pond's comment here:

> Hi Takashi,
> You may want to take a look at RELAX (http://test.datamonkey.org/relax, http://mbe.oxfordjournals.org/content/32/3/820) for this purpose. This method can test one possible definition of selection relaxation, which sounds like may be useful to you. Essentially you could take a gene tree, define a group of branches that you think are conserved, and compare whether or not the distribution of dN/dS on those branches is further away from neutrality (dN=dS), than in the rest of the tree. The paper I reference above is a worthwhile read, because it also contains references to other dN/dS tests that people have applied in the past.
> 
> Sergei

Best,
Steven

**Comment by spond** [comment]
Dear @FraLeon,

I agree with @stevenweaver. In the framework of LRT, you can never **prove** neutral evolution, as it is inferred when we **fail to reject** non-neutral evolution (http://blog.minitab.com/blog/understanding-statistics/things-statisticians-say-failure-to-reject-the-null-hypothesis)

It sounds like the RELAX test is perfect for your second question.

Best,
Sergei

**Comment by FraLeon** [comment]
Thanks a lot for these helpful comments!
I just started a RELAX test!

**Comment by stevenweaver** [comment]
You're welcome!
