### ISSUE TITLE
2.3dev intel compilation error

### ISSUE THREAD

**Issue by moskalenko** [veg/hyphy#514]
$ make HYPHYMPI
[  0%] Building CXX object CMakeFiles/HYPHYMPI.dir/src/core/calcnode.cpp.o
/dist/hpc/apps/hyphy/hyphy/src/core/calcnode.cpp(6241): error: a template argument may not reference a local type
        site_has_all_gaps &= (!ArrayAny (iterator->theProbs, cBase, [](_Parameter x, unsigned long) {return x == 0.0; })); //completely unresolved
                               ^

make[3]: *** [CMakeFiles/HYPHYMPI.dir/src/core/calcnode.cpp.o] Error 2
make[2]: *** [CMakeFiles/HYPHYMPI.dir/all] Error 2
make[1]: *** [CMakeFiles/HYPHYMPI.dir/rule] Error 2
make: *** [HYPHYMPI] Error 2

builds with gcc

**Comment by spond** [comment]
Dear @moskalenko,

Can you confirm that the Intel C++ compiler recognizes the C++-14 command line option supplied by the make script? My guess is that our current CMakeLists.txt runs down the gcc branch when `icc` is being used, and sets language standard to gnu++14 and not c++14

Best,
Sergei
