### ISSUE TITLE
aBSREL branch length, LHC, and tMRCA estimates

### ISSUE THREAD

**Issue by dforni** [veg/hyphy#515]
Dear HYPHY developers,
first of all, thank you for this great software! 
I am using aBREL to estimate viral divergence times in a similar way you did in Wertheim et. al,  2014 (DOI:10.1093/molbev/msu185.). 
I have run aBSREL to calculate branch lengths and then I have processed the output of aBSREL ( .fit file ) by running the LHC procedure with the HYPHYMP -p command. 
I have some problem in generating the 500 samples trees from the LHC analyses for the variance estimates. How can I generate them? If I have understood correctly, the .t column from LHC output is not a length measure, but a time parameter.
Can you give me some advice?
thanks for the  support

Best

Diego

**Comment by stevenweaver** [comment]
Dear @dforni,

You are correct in that the .t parameters are time parameters. According to Dr. Pond in this [issue](https://github.com/veg/hyphy/issues/288):
> Also <branch name>.t is not the branch length, but rather a time parameter. The branch length is a function of the time parameter, nucleotide substitution biases, and equilibrium frequencies.

The paper uses the output from LHC to feed the program `r8s`. 

Best,
Steven

**Comment by dforni** [comment]
Dear Steven,
thank you for your reply, I will try it.
Best

Diego
