### ISSUE TITLE
BS-REL including "lost"/"non-functional" genes

### ISSUE THREAD

**Issue by FraLeon** [veg/hyphy#516]
Hey,

I was wondering whether the presence of some sequences in an alignment that are known to belong to non-functional genes in the corresponding species could influence the results of a branch-site REL analysis in datamonkey?
Some of my analyzed datasets include such sequences which I got from NCBI but are only predicted mRNA sequences. No for some of the species (for these I know that the protein is definitely not synthesized) I get a signal for positive selection. Can I work with these results or should I not use the BS-REL method in such cases for some reason?

thanks in advance!
Best, Franziska

**Comment by spond** [comment]
Dear @FraLeon,

As a rule of thumb, you should see **relaxation** of selection on such non-functional branches. This means that sites that used to be conserved (dN/dS < 1) will drift up (closer to dN/dS = 1), while sites that used to be diversified (dN > dS > 1) will drift down (also closer to dN/dS = 1). We have another method (RELAX) designed to test for these scenarios.


 If you get a signal of selection on non-functional branches, several explanations are possible. 

1.  The result is a false positive. This is always a possibility, but aBS-REL tends to be pretty conservative. 
2. The result is a true positive. It could be that the signal you see is simply "left-over" from the selection that had occurred prior to loss of function (although then the obvious follow-up is : why did loss of function follow selection).

Best,
Sergei

**Comment by FraLeon** [comment]
Dear Sergei,

thanks a lot for your answear! I had almost exanctly the same thoughts and positive selction for lost genes gives my analysis a great discussion basis, since exactly this option might actually really make sense.

I already did the RELAX test with several configurations of test- and reference branches.
The only thing I don´t really know how to interpret is the following:
For three datasets I tested for relaxation setting all branches that have been identified to be under positive selection with BS-REL as test-branches. Now for all three genes with RELAX I detect significant relaxation for these testbranches against all others set as reference-branches...

One explanantion I already thought of is that in the reference branches negative selection might be very strong and the relaxation signal in the test-branches might occur due to the relaxation of negative selective pressure and therefore maybe "cover" the strenght of positive selection..?

Can you suggest any other explanation?

Thanks a lot in advance!
Best,
Franziska
