### ISSUE TITLE
Yet another beginner question regarding command line version

### ISSUE THREAD

**Issue by mstagliamonte** [veg/hyphy#518]
Dear HyPhyers,

Thank you for making available this great package. After using Data Monkey with a couple of test files, I am trying to switch to command line, since the size of my dataset requires the analyses to be run on a computer cluster.
I have a nucleotide codon alignment and I would like to screen for 1) recombination (using GARD?); 2) sites under selection (FEL, REL, and SLAC); 3) branch specific selection (GA-Branch).
After reading several tutorials, I am still struggling to get started. I am able to create a tree and select a codon substitution model using other programs... but then? Should I repeat those steps using HyPhy?  I have also noticed that on Data Monkey you can test for codon models starting from a nucleotide model. Should I rather take do something similar to obtain a codon matrix?
I apologize as these topics may have been discussed somewhere else, I am still stuck on which bf files to use to get started.

Sincerely,
Max Tagliamonte

**Comment by stevenweaver** [comment]
Dear @mstagliamonte,

Dr. @spond has written an excellent tutorial [here](https://veg.github.io/hyphy-site/tutorials/selection/README/). This tutorial should be able to get you started on how to use HyPhy, and introduce you to some of our newer methods. Once you are able to use HyPhy on the command line, we can try answering some more questions.

Have you been able to install HyPhy on your cluster?

Best,
Steven

**Comment by mstagliamonte** [comment]
Thank you for responding so quickly, Steven,

The package was already installed on the cluster I am using, it's the 2.3 dev version. 
Thank you for the link, I will go through the tutorial and come back if I still need help.

Regards,
Max

**Comment by stevenweaver** [comment]
Dear @mstagliamonte,
I'm closing this issue for now. Please feel free to reopen if you run into further issues.
