### ISSUE TITLE
missing node of ancestral sequences

### ISSUE THREAD

**Issue by victor0104** [veg/hyphy#519]
Hi,
I'd like to use HyPhy to reconstruct ancestor sequences with gene sequences from virus and a ML tree by using AnalyzeNucProtData.bf. Unfortunately, the output tree topology was different from the input one. Some of nodes in the tree were missed. Is there any setting for me to fixed the topology and branch length of tree when running HyPhy?Thank you.

Regards,
Victor

**Comment by ArtPoon** [comment]
Hi Victor,

Have you tried setting the following environmental variables before you run your analysis:
```
ACCEPT_ROOTED_TREES=1;
ACCEPT_BRANCH_LENGTHS=1;
```
Also, can you post your workflow and a tree or an excerpt from your tree so I can try reproducing your problem?

**Comment by victor0104** [comment]
Hi Dr. Poon,
I'm using the Hyphy 2.2.4 GUI version. Thank you for your suggestion. After trying your recommended setting by modified the AnalyzeNucProtData_fixed.bf, the tree generated by Hyphy displayed all branch length into "nan"(e.g. Tree givenTree=((((((((((JF912181:nan,JF912184:nan)Node9:nan,.....). Is it possible to generate the tree with node number and original branch length? Attached is the zip file with sequences ,tree and  batch files
[hyphy_githup.zip](https://github.com/veg/hyphy/files/753583/hyphy_githup.zip)

Regards,
Victor

**Comment by ArtPoon** [comment]
Okay, I made a couple of modifications and this seems to work for me:
```
SetDialogPrompt ("Please specify a nuleotide data or aminoacid file:");

DataSet ds = ReadDataFile ("sequence.fasta");
DataSetFilter filteredData = CreateFilter (ds,1);

global estPiA;
global estPiC;
global estPiG;
global estPiT;
global sum;

estPiA:<1;
estPiC:<1;
estPiG:<1;
estPiT:=Abs(1-estPiA-estPiC-estPiG);
sum := estPiA+estPiC+estPiG+estPiT;

EMBED_FREQUENCY_DEPENDENCE = 1;

SelectTemplateModel(filteredData); // TN93

estPiA = .25;
estPiC = .25;
estPiG = .25;

vectorOfFrequencies = {{estPiA/sum},{estPiC/sum},{estPiG/sum},{estPiT/sum}};

fprintf (stdout,"\n",ds);

ACCEPT_ROOTED_TREES = 1;
ACCEPT_BRANCH_LENGTHS = 1;
fscanf ("tree.newick", "Raw", treeString);
Tree givenTree = treeString;

LikelihoodFunction lf = (filteredData,givenTree);
Optimize (res,lf);
fprintf (stdout, "\n",lf);

HarvestFrequencies (obsFreq,filteredData,1,1,1);
fprintf (stdout, "\nEstimated Frequencies:", vectorOfFrequencies, "\nObserved Frequencies", obsFreq);

GetString (mbl, TrNModel,-1);
fprintf (stdout,"\n",mbl,"\n");
```

**Comment by spond** [comment]
Dear @victor0104,

@ArtPoon is correct -- you need to set some environment flags to override default tree modification behavior. Here's a slightly tuned version of the script. I would also suggest you use 2.2.7 release.

Best,
Sergei

```
SetDialogPrompt ("Please specify a nuleotide data or aminoacid file:");

DataSet ds = ReadDataFile ("sequence.fasta");
DataSetFilter filteredData = CreateFilter (ds,1);

global estPiA:<1;
global estPiC:<1;
global estPiG:<1;
global estPiT:<1;

global sum := estPiA+estPiC+estPiG+estPiT;

EMBED_FREQUENCY_DEPENDENCE = 1;

SelectTemplateModel(filteredData);

estPiA = .25;
estPiC = .25;
estPiG = .25;
estPiT = .25;

vectorOfFrequencies = {{estPiA/sum},{estPiC/sum},{estPiG/sum},{estPiT/sum}};

ACCEPT_ROOTED_TREES   = 1;
// do not unroot rooted trees

AUTOMATICALLY_CONVERT_BRANCH_LENGTHS = 1; 
// try to incorporate branch lengths supplied in the tree string

fscanf ("tree.newick", "Tree", givenTree);

LikelihoodFunction lf = (filteredData,givenTree);

Optimize (res,lf);

HarvestFrequencies (obsFreq,filteredData,1,1,1);

fprintf (stdout, "\nEstimated Frequencies:", vectorOfFrequencies, "\nObserved Frequencies", obsFreq);

DataSet ancestral = ReconstructAncestors (lf);

fprintf (stdout, "\nFitted tree with internal branch names\n\n", Format (givenTree, 1, 1), "\n\n");

DataSetFilter ancestral_filter = CreateFilter (ancestral,1);

DATA_FILE_PRINT_FORMAT = 9; // FASTA

fprintf (stdout, "\n", ancestral_filter, "\n");
```

**Comment by victor0104** [comment]
Dear @ArtPoon and @spond ,
After using the newest version, the tree displayed well with fixed branch length and ancestor nodes.Thank you all!

Regards,
Victor
