### ISSUE TITLE
Parallelizing MEME

### ISSUE THREAD

**Issue by szhan** [veg/hyphy#521]
Hi HyPhy team,

Thank you for making the nice set of selection analysis tools accessible to everyone! I wish to run MEME on a large number of data sets. I have compiled HYPHYMPI, and tried to run it on a test data set. I do not see that it is using all the available CPUs. I thought that it automatically detects and utilizes all the available CPUs. Or is there an input parameter which I am missing? I do not see such as a parameter in the tutorials.

Also, a side question, I am using v2.2.7, because it seems to be the latest stable release. Is it recommended to use the v2.3 test release instead?

Thank you very much!
Shing

**Comment by ArtPoon** [comment]
Hi Shing, 
Basic question first, did you invoke `HYPHYMPI` in an MPI computing enviornment? e.g.,:
```
mpirun -np 5 HYPHYMPI
```
where `5` is the number of processes to spawn?

cheers,
- Art.

**Comment by szhan** [comment]
Hi Art!

Thanks for the reply! I tried using mpirun with -np 8, and all was well until it crashed with some memory error...

...
3939a06000-3939a07000 r--p 00006000 fd:00 3932289                        /lib64/librt-2.12.so
3939a07000-3939a08000 rw-p 00007000 fd:00 3932289                        /lib64/librt-2.12.so
3939c00000-3939c72000 r-xp 00000000 fd:00 268877                         /usr/lib64/openmpi/lib/libopen-rte.so.7.0.3
3939c72000-3939e71000 ---p 00072000 fd:00 268877                         /usr/lib64/openmpi/lib/libopen-rte.so.7.0.3
3939e71000-3939e76000 rw-p 00071000 fd:00 268877                         /usr/lib64/openmpi/lib/libopen-rte.so.7.0.3
3939e76000-3939e77000 rw-p 00000000 00:00 0
[zoology.ubc.ca:31879] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[zoology.ubc.ca:31879] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 31881 on node crunch09 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
...

Have you encounter this error before?

Thanks!
Shing

**Comment by spond** [comment]
Dear @szhan,

Most of the log consists of  generic MPI messages that would be generated for any abnormal message. Signal 11 is most likely thrown because HyPhy has been trying to read input from a closed stream, e.g., stdin which may not be available for an MPI process. See issue #522 for a recent example. 

Best,
Sergei

**Comment by szhan** [comment]
Hi Art and Sergei,

Thank you for your help! It turns out that I did not specify the output file in the inputRedirect dictionary. Correcting that got rid of the MPI error messages.

This script did the trick:
=====================================================
fileToExe="/data/home/szhan/projects/bin/hyphy_install/lib/hyphy/TemplateBatchFiles/QuickSelectionDetection.bf";

inputRedirect = {};
inputRedirect["01"] = "Universal";
inputRedirect["02"] = "New Analysis";
inputRedirect["04"] = "Custom";
inputRedirect["05"] = "012345";
inputRedirect["06"] = "y";
inputRedirect["08"] = "Estimate dN/dS only";
inputRedirect["09"] = "MEME";
inputRedirect["10"] = "0.10";
inputRedirect["11"] = "n";

fscanf(PROMPT_FOR_FILE, "Lines", _inDirectoryPaths);

inputStem = _inDirectoryPaths[0];
fprintf(stdout, inputStem);
inputRedirect["03"] = inputStem;
inputRedirect["07"] = inputStem + ".model";
inputRedirect["12"] = inputStem + ".results";

ExecuteAFile(fileToExe, inputRedirect);
=====================================================

Thanks very much!
Shing
