### ISSUE TITLE
paralogs and saturation

### ISSUE THREAD

**Issue by sapuizait** [veg/hyphy#523]
I have a group of genes (appx 30) that I would like to check in different bacterial strains for positive selection using the abs-REL method. There are 2 issues that make me wonder whether I could draw some reliable conclusions about them
1) in some of the alignments some of the gene orthologs are pretty diverse... similarities of 50 or even as low as 30%  ...
2) for some of those genes there are also paralogs in their genomes. For those ones I thought of using both the orthologs and the paralog(s)...

any advices are very welcome

thanks
P

**Comment by spond** [comment]
Dear @sapuizait,

1. Assuming your alignment is not too noisy, high divergence is not necessarily a red flag. Generally, more variability is better, but you will at some point run into saturation issues. These will typically manifest as loss of power. 

2. Paralogs are also fine to include, you just need to interpret their roles accordingly.

Best,
Sergei

**Comment by sapuizait** [comment]
Thanks!
