### ISSUE TITLE
BranchSiteREL

### ISSUE THREAD

**Issue by RYoungiii** [veg/hyphy#524]
I'm trying to run the adaptive BranchSite REL in BranchSiteREL.bf using a batchfile with the following input redirect: 

inputRedirect = {};
inputRedirect["01"]="Universal";
inputRedirect["02"]="Yes"; 
inputRedirect["03"]="No"; 
inputRedirect["06"]="All";
inputRedirect["07"]="d";
for ( _fileLine = 0; _fileLine < Columns ( _filesToProcessUsingBSREL ); _fileLine += 1 ) {
  inputRedirect[ "04" ]    = _filesToProcessUsingBSREL[ _fileLine ];
  inputRedirect[ "05" ]    = inputRedirect[ "04" ] +".GARD_splits";
  inputRedirect[ "08" ]    = inputRedirect[ "05" ]+".bs-rel";
  ExecuteAFile ( fileToExe, inputRedirect );
}

However i get an error:
"Not a valid (or duplicate) option: 'd' passed to ChoiceList (with multiple selections) 'Which branches to test?' "

These options work fine without the wrapper. Any suggestions why this error might be occurring?

**Comment by RYoungiii** [comment]
I changed the options to:

inputRedirect = {};
inputRedirect["01"]="Universal";
inputRedirect["02"]="Yes";
inputRedirect["03"]="Yes";
inputRedirect["06"]="All";
inputRedirect["07"]="d";
for ( _fileLine = 0; _fileLine < Columns ( _filesToProcessUsingBSREL ); _fileLine += 1 ) {
inputRedirect[ "04" ] = _filesToProcessUsingBSREL[ _fileLine ];
inputRedirect[ "05" ] = inputRedirect[ "04" ] +".GARD_splits";
inputRedirect[ "08" ] = inputRedirect[ "05" ]+".bs-rel";
ExecuteAFile ( fileToExe, inputRedirect );
}

And the analysis runs.

**Comment by stevenweaver** [comment]
Dear RYoungiii,

Prompt `03` is `Allow branch-site variation in synonymous rates?`. If you select yes, then no branch by branch testing will be performed. 

Are you sure that this issue is not specific to a certain dataset that you are looping through?

Best,
Steven

**Comment by RYoungiii** [comment]
Hi Steven,
Yes, I was seeing if I could get the batch file to run at all. The analysis that I want to run is 3=no. For 3=yes, the model is fit, but, yes, no branch testing is performed (i.e., the script completes). Using 3=no, the script returns the error. If I input the same data (first alignment) entering the options by hand, the analysis completes. My guess is that there might be an issue with the inputredirect in the batchfile? Though, I haven't been able to figure out what it is, yet.
Thanks,
Rob

**Comment by stevenweaver** [comment]
Dear Rob,

This is by no means a desirable solution, but it will work. 

Please change your code to the following:

```
inputRedirect = {};
inputRedirect["01"]="Universal";
inputRedirect["02"]="Yes";
inputRedirect["03"]="No";
inputRedirect["06"]="All";
inputRedirect["07"]="";
for ( _fileLine = 0; _fileLine < Columns ( _filesToProcessUsingBSREL ); _fileLine += 1 ) {
inputRedirect[ "04" ] = _filesToProcessUsingBSREL[ _fileLine ];
inputRedirect[ "05" ] = inputRedirect[ "04" ] +".GARD_splits";
inputRedirect[ "08" ] = inputRedirect[ "05" ]+".bs-rel";
ExecuteAFile ( fileToExe, inputRedirect );
}

```

Specifically, changing `inputRedirect["07"]="d";` to `inputRedirect["07"]="";` will allow the program to run.

Best,
Steven

**Comment by RYoungiii** [comment]
Thanks for looking into this, Steven, and suggesting a solution. I will do this. I do appreciate it.
Best wishes,
Rob
