### ISSUE TITLE
PRIME -- Error: Missing analysis settings

### ISSUE THREAD

**Issue by DDashevsky** [veg/hyphy#525]
Hello,

I am trying to analyze a modestly sized alignment (67 sequences of 83 codons) with PRIME, but got an error that I can't make much sense of. The job number should be 633207300721250.

On the results page the boxes for 'Analysis overview', 'Property importance plot', and 'Site-by-site analysis of property importance' are all empty. Beneath them is this message:

> Error: Missing analysis settings: 0 Function call stack 1 : Assert 'Abs(_fel_results["SETTINGS"])>=3' ------- 2 : _result=jsonProcessor(primeResults) ------- 3 : ExecuteAFile from file "PRIME_Processor.ibf" using basepath /var/lib/datamonkey/share/BFs/. -------

If I use the drop-down menu at the top to request 'PRIME results as a .csv file' I get the following output.

> \<H1 class = "ErrorCap"\>HyPhy Run-time Error\</H1\>\<pre\>
> no such table: PRIME_SUMMARY
> Function call stack
> 1 : DoSQL(DB_ID(,theCode,"return _matchRecordsByField (0);")
> \-\-\-\-\-\-\-
> 2 : propertyCount=_ExecuteSQL(slacDBID,"SELECT COL_VALUE FROM PRIME_SUMMARY WHERE COL_KEY = 'PropertyCount'")
> \-\-\-\-\-\-\-
> \</pre\>

I repeated the analysis twice and go similar results. As far as I can tell I entered something for every single analysis setting I was offered. I found an [earlier thread with the same error](https://github.com/veg/hyphy/issues/468), but it was closed without a solution being posted.

Any help would be appreciated.

Thanks,
Daniel

**Comment by DDashevsky** [comment]
P.S. Am I correct to conclude that there is no implementation of PRIME in the standalone HyPhy package at this time?

**Comment by stevenweaver** [comment]
Hi Daniel, 
Datamonkey is failing to parse the results from HyPhy on the backend despite the results passing the JSON linter. I'm afraid this is going to take time to debug. 

If you would like the JSON results to your job, I can deliver them immediately via sweaver@temple.edu.

Since PRIME is not yet officially published, PRIME is not yet available on the standalone HyPhy package.

**Comment by DDashevsky** [comment]
Hi Steven,

Thanks for getting back to me. I'd love the JSON results. Any tips for how to read the files?

Best,
Daniel

**Comment by spond** [comment]
Dear @DDashevsky,

I'll be releasing a standalone version of PRIME for the v2.3 HyPhy branch in the next couple of weeks. I'll post a link here.

Best,
Sergei

**Comment by DDashevsky** [comment]
Hello Steven,

I've sent several emails following up on this. Not sure if they're getting filtered or if you're simply very busy. I would very much appreciate it if I could get those result files. If you're having trouble finding my emails, a search of my last name "Dashevsky" should bring them up.

Cheers,
Daniel

**Comment by stevenweaver** [comment]
Dear @DDashevsky,

Apologies for the delay. I've sent the results files via email. 

Best,
Steven
