### ISSUE TITLE
Analysing a gene fragment

### ISSUE THREAD

**Issue by Fransansisco** [veg/hyphy#528]
Dear HyPhy Producers,
Is it valid to use Datamonkey to analyse a fragment of a gene? We have sequenced toll-like receptor genes for multiple individuals by dividing them into 5 shorter fragments - my supervisor asked me to  look for positively selected sites in one of the fragments for which we have the most individuals sequenced. This is the fragment with the only two non-synonymous snps of the gene so will analysing it separately not introduce a bias in the ratio of ds/dN? The fragments themselves were assigned in a way arbitrarily (length ca. 500bp) as a way of sequencing the whole gene.
Thank you in advance.

**Comment by spond** [comment]
Dear @Fransansisco,

You can always analyze whatever sequences (or fragments thereof) you wish with Datamonkey, or any other tool. There's nothing invalid about it. Your specific question does merit three follow-up comments

1. If your objective is to estimate dN/dS for the entire gene (e.g. via BUSTED), then you should analyze complete alignments. Not doing so will bias your estimate depending on which (less or more variable than average) segment you choose.

2. If you wish to find specific sites under selection (e.g. FUBAR or MEME),  then the analysis largely operates at the level of a single site, hence it doesn't matter as much that you only include a segment of the gene. Using partial gene sequences will influence branch length and nucleotide substitution rate estimates, but unless your segment is chosen in a particularly biased manner (e.g., by deliberately including a surfeit of variable sites), the effects on dN/dS testing at a site should be slight.

3. For low divergence data (which your seem to be), you may not be powered to detect anything with dN/dS tools. 

Best,
Sergei

**Comment by Fransansisco** [comment]
Thank you so much for the comprehensive answer! It's much appreciated.
Best wishes,
Fran
