### ISSUE TITLE
different output when using absREL in datamonkey or in HYPHY 2.220170208beta(MPI)

### ISSUE THREAD

**Issue by sapuizait** [veg/hyphy#529]
Hi all

I am analyzing an alignment using absREL, however when I run the very same alignment (and the same tree file) using the absREL implemented in datamonkey and the exact same files in hyphy 2.220170208beta(MPI) in my linux machine I get very different outputs
The datamonkey output file shows that there is positive selection in two bacteria sequences (named tai and ent10) however the hyphy on my laptop shows positive selection in only one of them (tai).
Does that have to do with different versions of the software or am I doing sth that I may be unaware of?

In hyphy I run the alignments using a batch file (see below) and in datamonkey I specify in the beginning that in the alignment the code is Mycoplasma/Mold and I also use the "User tree" option

any help is greatly appreciated

Cheers
P

BATCH FILE
-------------------------------------------------------------
inputRedirect = {};
inputRedirect["01"]="Mold/Protozoan mtDNA";
inputRedirect["02"]="Yes";
inputRedirect["03"]="No";
inputRedirect["04"]="ALIGNMENTFILE";
inputRedirect["05"]="TREEFILE";
inputRedirect["06"]="All";
inputRedirect["07"]="";
inputRedirect["08"]="OUTFILE";
ExecuteAFile (HYPHY_LIB_DIRECTORY + "TemplateBatchFiles"+ DIRECTORY_SEPARATOR+"BranchSiteREL.bf", inputRedirect);

**Comment by spond** [comment]
Dear @sapuizait,

Datamonkey an older (BS-REL) version of the analysis. Some differences are not surprising; but they should be fairly minor. Try two things:

1). Run the BS-REL version in HyPhy (fixed number of rates K = 3 per branch), and see if the results are in better agreement.

2). For the `ent10` branch, what is the p-value reported by aBSREL when you run in locally? Is in close to significance (e.g. p = 0.06), but just above the cutoff?

Best,
Sergei

**Comment by sapuizait** [comment]
nah I am afraid I cant make it work... (or be consistent)

datamonkey results:
Branch ?	Corrected p-value ?	ω+ ?	Pr [ω=ω+] ?
TAI	< 0.0001	73.71	0.96
ENTACRO10	< 0.0001	4749.93	0.89
Node9	0.025	1012.66	0.60
Node5	0.024	632.20	0.84
DIMI	0.047	34.39	0.80



local 2.2.7 adaptive bsREL
Branch	Mean_dNdS	RateClasses	OmegaOver1	WtOmegaOver1	LRT	p	p_Holm	BranchLength
EntAcro10	10	1	1E+26	1	0.042119475	0.461226581	1	2.636550442
Node10	10	1	0	0	0	1	1	0
tai	10	1	54.19210711	1	17.58015361	5.12E-05	0.000818878	4.563878189
Node9	10	1	1E+26	1	-0.003194411	0.5	1	12.29786156
Node5	10	1	1E+26	1	10.62360323	0.001703216	0.025548239	9.754351454



local 2.2.7 (fixed number of rates K = 3 per branch)
Branch	Mean_dNdS	RateClasses	OmegaOver1	WtOmegaOver1	LRT	p	p_Holm	BranchLength
L1	0	3	0	0	0	1	1	0.0127552033
w371	0.1081331076	3	0	0	0	1	1	0.0042472115
EntAcro1	0	3	0	0	0	1	1	798.8630339528
EntAcro10	10	3	9999.9999999983	1	-8.3772895297	1	1	19.7111365252
sab	10	3	3333.6855614665	0.9667286972	15.7463406653	0.0001749927	0.0029748758	2705.8434179206
apis2	10	3	230.2855209769	0.948111771	36.5277505363	5.33921029610696E-009	1.01444995626032E-007	90.5250709697
apis	0	3	2.459505702	0	0	1	1	10.3995642174
Node10	10	3	0	0	0	1	1	0
tai	10	3	206.3920274875	0.9489800857	35.8531920603	7.48186790300309E-009	1.34673622254056E-007	21.130713306
dimi	2.2091755762	3	18.1026555696	0.816374824	6.5287426384	0.0177301552	0.2659523274	3.2660558052
Node13	10	3	0	0	0	1	1	0.0100387892
Node9	10	3	9999.9999999983	0.9552978304	6.6904260322	0.0163483774	0.2615740388	45.6654764175
Node7	10	3	0	0	0	1	1	0
Node5	10	3	0	0	0	1	1	0


***I am only attaching the ones that I am interested in + are significant***


therefore the only one that  always seem to be significant is the "tai" but taken into account that I am only interested in the EntAcro10 I dont think I can use this result. In any case as far as I understand I should always trust best the results from the latest hyphy version and always run the adaptive bsREL, so I guess I should just do that?

thanks
