### ISSUE TITLE
v2.3-dev bug, likely namespace related

### ISSUE THREAD

**Issue by sjspielman** [veg/hyphy#533]
Currently, the ProteinGTRFitter.bf script cannot be run with more than 25-26 input files. Upon reaching Phase 2 (initial REV fit), this error appears: 
"Incompatible dimensions between the filter (20) and the frequencies matrix (1)."
Note that the batchfile runs fine to completion where there are fewer than ~25 files. If one were to restart a crashed analysis from the cache file, the analysis will run to completion with no error.

@stevenweaver has suggested that this bug may be due to the finite number of namespaces that HyPhy generates, which makes it difficult at this time to infer reliable exchangeability matrices (more than 25 alignments will be needed).

**Comment by spond** [comment]
Dear @sjspielman,

This is not likely to be a namespace uniqueness bug, as random **unique** names are generated pretty much indefinitely. Run HyPhy with the `-d` command line option: this will drop you into the debug mode when the error triggers and you can enter expressions into the console window to see what the values of various variables are. This particular error indicates that the frequency matrix is not defined in the namespace expected by the model generator. Not sure why they would be, or what is special about the 25-26 file threshold. I would also put print statements in the model definition code right before the spot where the error is thrown. 

Issues like this are a timesuck (sorry!), so I would like to figure out a way to be more pro-active about how to prevent such issues in the future, e.g. with better reporting.

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @spond, 

The idea that namespaces might be finite for datasets was pure conjecture. I wasn't sure if there was a pool of namespaces created explicitly for datasets at start-up after the inclusion of `global_object_lists.cpp`. 

Best,
Steven

**Comment by sjspielman** [comment]
Having gone through about 3-4 days of printing just about every variable, I am confident that there can't be an issue with frequencies not being defined. Printing model definitions suggests that everything is ok as well, and runs fine up until entering the the FitSingleModel_Ext function. I will look into debug mode now as well to try and diagnose further.

**Comment by sjspielman** [comment]
I have further found that the error seems not to depend on the number of files, but the size of the full data provided. I had been using a set of 100 simulations with trees containing b/w [50,150] taxa and alignment lengths b/w [75,300] amino acids. As stated, this results in the error (unless <26 or so files are specified instead of 100). 

The following conditions *do not* give an error:
+ 100 files whose trees have only 5 taxa and alignments are 10 aa long
+ 100 files whose trees have only 5 taxa and alignments are 300 aa long

Alternatively, I *do* get an error if trees have between [50,150] taxa and alignments are 10 aa long.

Is it possible that the issue could relate to the number of taxa? I can't see why/how, but the pattern I am seeing points in that direction.

**Comment by spond** [comment]
Dear @sjspielman,

This is a very puzzling pattern. I have no obvious suggestions as to why this may be occurring. Have you tried `-d` and message logging to get a better sense of where the issue occurs? Since it triggers early in the script, at least you can run a number of trials.

Best,
Sergei

**Comment by sjspielman** [comment]
Heading that direction now. I know already it happens inside FitSingleModel_Ext, called inside the function protein_gtr.fitGTRtoFileList. I will track down more precisely in FitSingleModel_Ext this is happening - although having a minor issue with debug mode in that I can't seem to get out of it (none of the obvious keystrokes, or exit, or esc, kill the process?)..

**Comment by spond** [comment]
Dear @sjspielman,

Type `exit` to finish the debug mode.

Best,
Sergei

**Comment by sjspielman** [comment]
Aha, I had been typing exit().. thanks.

**Comment by spond** [comment]
Ha! `R` hangover.

**Comment by sjspielman** [comment]
May be worthwhile to note that `exit` does not seem to work if one has already tried ctl+c and/or ctl+d...

**Comment by sjspielman** [comment]
Also worthwhile to restate, the most "diagnostic" behavior I have come across is that a run that errors out will run without error if restarted from cache. I'm attaching here the messages.log (as [messages.log.txt](https://github.com/veg/hyphy/files/828311/messages.log.txt)) from such a crashed run (with the usual frequencies error) that, if restarted, will not have the frequencies error and will run just fine. 
Stack from an "errored" run may also be of use. When the error happens in the FitSingleModel_Ext, it occurs with the *first* data filter (index i=0) when entering the loop that calls Build Data Filter:

Function call stack
1 : Build Data Set Filter ^(filters[i]) from DataSet ^(data_filter[i]) with unit size = 1 Partition:
-------
2 : protein_gtr.rev.mle=estimators.FitSingleModel_Ext(utility.Map(filter_info,"_value_","_value_['name']"),trees,protein_gtr.rev_model_branch_lengths,initial_values,{"proportional-branch-length-scaler":proportional_scalers})
-------
3 : protein_gtr.current_gtr_fit=protein_gtr.fitGTRtoFileList(current_results,protein_gtr.current_gtr_fit,result_key,FALSE)
-------

**Comment by spond** [comment]
Fixed via 87bebe2e7ac19a1974c789b2f53c25e62334d5bc
