### ISSUE TITLE
ideal gap percentage threshold in alignment

### ISSUE THREAD

**Issue by sapuizait** [veg/hyphy#535]
Dear all

what would be an appropriate threshold for a position in an alignment to be removed? would you say that if a position has more than 50% gaps its useless and therefore it can be removed? or a position with 50% gaps has still some information? in that case which parts of the alignment would you remove? positions with more than 70% gaps for example?

I know that an option is to check with hmmbuild but I d rather not use it and instead set a universal criterion for positions with gaps, unless that sounds too arbitrary? :)

thanks in advance

**Comment by sjspielman** [comment]
Hi @sapuizait, 

Regarding HyPhy's behavior, you may find this thread from the old HyPhy forum useful: [http://www.hyphy.org/cgi-bin/hyphy_forums/YaBB.pl?num=1201198027](http://www.hyphy.org/cgi-bin/hyphy_forums/YaBB.pl?num=1201198027). In a nutshell, HyPhy will treat gaps as missing data, so if there are at least two non-gapped states in a given column then some information will be there. Note that the linked thread contains some information about flags you can set to customize the default behavior as needed.

The question of "appropriate threshold" for alignment gappiness is one that is still fairly debated and ultimately comes down to personal choice. For example, many people will opt to use a tool like Gblocks, TrimAl, Guidance, etc. to mask and/or filter gappy alignments, but whether or not this step has an effect (either helpful or harmful) will come down to your specific analysis and dataset. It's always a good idea to compare results between a filtered and unfiltered alignment, and if results differ substantially then it could be a good idea to revisit how you performed the multiple sequence alignment.

Best,
Stephanie

**Comment by sapuizait** [comment]
Hey Stephanie

thanks for your quick answer! 
Cool I didnt know that hyphy ignores gap sites, that definitely solves (most of) my problem.

I was mostly worried about false positives when checking for recombination and for saturation. I do usually use trimAl when for example I am building phylogenies but I was not sure if I should try to use a similar approach before entering data to hyphy. 

Thanks for the suggestion (using both filtered and unfiltered) i ll definitely try it


P

**Comment by nselem** [comment]
Hi Stephanie 

I have a query using RELAX and I was wondering if you could help me with it. I am running some analysis to test relaxed purifying selection in a branch level but I obtain different results using a DNA no gap alignment as input from those using an alignment file with gaps. Actually, with a no-gap alignment file, I get not significant results but running the test with an alignment with gaps I got significant relaxed purifying selection results. I think RELAX is taking into account gaps in the analysis, but I am not quite sure how this is happening. 
Could you help me with some information related to this, please? I will appreciate your help. 
Thanks in advance.

Nelly

**Comment by spond** [comment]
Dear @nselem,

How was your alignment generated? When you say "no-gap alignment", do you mean an alignment with all gapped sites removed? What fraction of sites have gaps, and for sites with gaps, how many sequences have data (i.e. does a typical site have 10$% gaps, 50% gaps, etc)?

Best,
Sergei

**Comment by nselem** [comment]
We have an alignment of 205 sequences. The alignment with gaps was generated using [revTrans](http://www.cbs.dtu.dk/services/RevTrans/), and the alignment without gaps (for CODEML) was generated using pal2nal docker version. 50% of sites has gaps, we have two kinds of gap sites, first kind has approximately 10% gaps and the other kind of 50 % gaps (sequences from different genomic lineage). I guess we should remove sites with more gaps than nucleotides, try again both alignments (gaps and no gaps) and compare results?

**Comment by spond** [comment]
Dear @nselem,

If I understand your message correctly, the two alignments (gapped and ungapped) differ by about 2x in the number of sites, i.e., the removal of sites with gaps halves the size of the alignment. In this case it is not at all surprising that you might lose selection signal, because

1. Your alignment (sample) size is smaller, lowering statistical power for mixture models.
2. Removing gapped sites likely results in preferential removal of more variable sites, although this is not necessarily the case.

Unless you have reason to suspect that the alignment is of poor quality, I would suggest that you analyze the complete dataset. It might also be instructive to examine the inferred &omega; distributions to see if their properties change dramatically between datasets.

Best,
Sergei
