### ISSUE TITLE
Fst

### ISSUE THREAD

**Issue by rbjmax** [veg/hyphy#536]
I used to use HyPhy to calculate Fst for paired sets of sequences, is that function still available?

**Comment by stevenweaver** [comment]
Dear @rbjmax,

Yes. Is there a reason why you might think it doesn't exist any longer?
The FST option exists under `Compartmentalization`  in the HyPhy menu. 

Best,
Steven

**Comment by rbjmax** [comment]
I must be looking at the wrong page, that was the term I was looking for. Please, would you provide me the hyphy site? I must be getting sick, I'm really not normally this dumb

**Comment by stevenweaver** [comment]
Hi @rbjmax,

Here is a link to the original thread you had with Dr. Pond. http://www.hyphy.org/cgi-bin/hyphy_forums/YaBB.pl?num=1298581169

Please take care,
Steven

**Comment by rbjmax** [comment]
I meant, is compartmentalization available on http://www.datamonkey.org/? When I had that conversation with Sergei, I was using the downloaded GUI.

**Comment by stevenweaver** [comment]
Dear @rbjmax,

Compartmentalization is not currently available on datamonkey.org. 

However, there are resources available [here](http://hyphy.org/w/index.php/Workshop:Vancouver2011:Compartmentalization) and slides available [here](http://hyphy.org/w/images/c/c6/Compart.pdf) if you need a refresher on how to use the HyPhy package. 

In addition, please feel free to ask any questions if you run into issues. 

Best,
Steven
