### ISSUE TITLE
Test Branch dN/dS Q

### ISSUE THREAD

**Issue by VinnyLynch** [veg/hyphy#538]
Hi All,

Is there a way to fix the w of a specific lineage at 1 with the TestBranchdNdS batch file?

Thanks
Vinny

**Comment by spond** [comment]
Dear @VinnyLynch,

`TestBranchdNdS` is most likely not the most up-do-date analysis to do what you are looking to do. I can tell you how to modify `TestBranchdNdS` to accomplish your requirement, but in exchange, could you tell me what you are trying to accomplish? I may be able to point you to a more modern version of the analysis.

Best,
Sergei

**Comment by VinnyLynch** [comment]
Hi Sergei,

It's for historical reasons.

We're reanalyzing the evidence for an episode of positive selection on the progesterone receptor gene human. aBSREL inferred a class of sites in the human lineage with ω=2.80, however, ω was not significantly greater than 1 (P=0.44) and BUSTED found no evidence of episodic diversifying selection in the human stem-lineage (P=0.57). RELAX, however, found significant evidence relaxed purifying selection (K=0.00, LRT=5.01, P=0.01) in the human stem-lineage (if I'm interpreting that result correctly). 

So we're curious if the old school one rate vs two rate vs fixed w suggests positive selection because the studies that originally suggested positive selection only compared a  one rate to a two rate model, and never tested the two rate free to the two rate fixed model.

Vinny

**Comment by spond** [comment]
Dear @VinnyLynch,

Ah, this makes sense. Do you know which version of site-to-site rate variation you wish to use?

Best,
Sergei

**Comment by VinnyLynch** [comment]
Hi Sergei,

Thanks for the quick response! I think the simple "none" option should be fine.

Best,
Vinny

**Comment by spond** [comment]
Dear @VinnyLynch,

Here you go: the modified batch file will run a "set all dN/dS on selected branches = 1" as a third model and do the LRT for you. 

Best,
Sergei

---

[TestBranchDNDS.txt](https://github.com/veg/hyphy/files/918364/TestBranchDNDS.txt)

**Comment by VinnyLynch** [comment]
Many thanks!
