### ISSUE TITLE
Relax example input files

### ISSUE THREAD

**Issue by dcaffrey** [veg/hyphy#541]
Hi,
Are there example alignment and tree files available for relax? Ideally, some of the files used in the RELAX paper, as I would like to reproduce some these results before proceeding to my own analysis. 
Thanks,
Daniel

**Comment by jwertheim** [comment]
Hi Daniel,

All of the alignments and annotated phylogenies analyzed in our paper are available as Supplementary Material via the MBE website (https://academic.oup.com/mbe/article-lookup/doi/10.1093/molbev/msu400#supplementary-data). Please contact me directly if you have any further questions.

Cheers,
Joel Wertheim

**Comment by dcaffrey** [comment]
Thanks! I may follow up once I have re-analyzed these datasets.
