### ISSUE TITLE
indels RELAX 

### ISSUE THREAD

**Issue by dcaffrey** [veg/hyphy#542]
Hi,
RELAX appears to generate different K values, likelihoods and consequently different P-values (highlighted in bold below) when I provide alignments that only differ in the number of "all-gap" columns.  Any ideas why the calculations are different? I expected the "all-gap" columns to be ignored. Is there an option to tell relax to ignore them?

The input files are attached. nogaps.fasta only contain 15 codons that correspond to binding site residues.  gaps.fasta contains  the same 15 codons but also contains 1238 gap codons "---" in every sequence that correspond to residues that are not part of the binding site. 

Thanks!
Daniel

Summary output for the alignment with all-gap columns:
Analysis Version
================
1.00

[RELAX] Loaded an MSA with 33 sequences and **1238 codons** from '**gaps.fasta**'
[RELAX] Selected 2 branches as the test set: Node38,Node51
[RELAX] Obtaining branch lengths under the GTR model
[RELAX] Log(L) = -674.9428320686895
[RELAX] Obtaining  omega and branch length estimates under the local MG94xGTR model
[RELAX] Log(L) = -522.0696889378667
[RELAX] Obtaining omega and branch length estimates under the partitioned MG94xGTR model
[RELAX] Log(L) = -540.1996757871393
[RELAX] Two-stage fit of the general descriptive model (separate relaxation parameter for each branch)
[RELAX] Log(L) = -555.5155886238617
[RELAX] Fitting the RELAX **null model**
[RELAX] **Log(L) = -560.4148035149228**
[RELAX] Fitting the RELAX **alternative model**
[RELAX] **Log(L) = -558.031767188489.** Relaxation parameter **K = 0.4746434579155744**
[RELAX] Likelihood ratio test for relaxation on Test branches, **p = 0.02902596714731909**
[RELAX] Fitting the RELAX partitioned exploratory model
[RELAX] Log(L) = -557.152678180336

Summary output for the alignment with no all-gap columns:
Analysis Version
================
1.00

[RELAX] Loaded an MSA with 33 sequences and 15 codons from '**nogaps.fasta**'
[RELAX] Selected 2 branches as the test set: Node38,Node51
[RELAX] Obtaining branch lengths under the GTR model
[RELAX] Log(L) = -674.9428807246223
[RELAX] Obtaining  omega and branch length estimates under the local MG94xGTR model
[RELAX] Log(L) = -522.0754857316076
[RELAX] Obtaining omega and branch length estimates under the partitioned MG94xGTR model
[RELAX] Log(L) = -540.1962505873831
[RELAX] Two-stage fit of the general descriptive model (separate relaxation parameter for each branch)
[RELAX] Log(L) = -517.0493669167511
[RELAX] Fitting the RELAX **null model**
[RELAX] **Log(L) = -530.1313927191351**
[RELAX] Fitting the RELAX **alternative model**
[RELAX] **Log(L) = -526.75371453173**7. Relaxation parameter **K = 0**
[RELAX] Likelihood ratio test for relaxation on Test branches, **p = 0.009346667719980162**
[RELAX] Fitting the RELAX partitioned exploratory model
[RELAX] Log(L) = -526.7537071254269

[gaps.fasta.txt](https://github.com/veg/hyphy/files/947797/gaps.fasta.txt)
[nogaps.fasta.txt](https://github.com/veg/hyphy/files/947798/nogaps.fasta.txt)
[sameTreeForBothAnalysis.nh.txt](https://github.com/veg/hyphy/files/947799/sameTreeForBothAnalysis.nh.txt)

**Comment by spond** [comment]
Dear @dcaffrey,

You are correct: there should be no difference between the two, but I think that what is happening is that one of the analyses (`gaps`) fails to converge for the most complex model (_the general descriptive model_); as you can see up to that stage the obtained likelihoods are the same (within tolerance). Not sure why this would happen. I'll take a look and get back to you.

Best,
Sergei

**Comment by dcaffrey** [comment]
I'm currently setting up about 40 gene families with similar properties to the uploaded example for RELAX analysis. As a workaround, I can remove all-gap columns to avoid the same issue. However, I'm wondering if there is a way to evaluate whether each run has converged?
Thanks,
Daniel

**Comment by rdvelazquez** [comment]
I can confirm that this is still an issue with version 2.4 (the develop branch):

gaps:
![screen shot 2019-03-06 at 4 34 53 pm](https://user-images.githubusercontent.com/25244432/53916654-ac9ba480-4030-11e9-952c-6d347f15da0d.png)

no gaps:
![screen shot 2019-03-06 at 4 54 45 pm](https://user-images.githubusercontent.com/25244432/53916659-b32a1c00-4030-11e9-8718-96210a68167e.png)
