### ISSUE TITLE
RELAX optimization failed

### ISSUE THREAD

**Issue by dcaffrey** [veg/hyphy#543]
Hi,
I've encountered an optimization error (below) and I'd appreciate any advice on how to set a "starting point" for whatever parameter RELAX is referring to (maybe omega?).  My debug messages suggest that line 195 of RELAX.bf is causing the issue. The input files are attached.

Thanks,
Daniel

Code snipped from RELAX.bf
194     io.reportProgressMessage("DEBUG","Before line 195 relax.LF:"+relax.LF);
**195     Optimize (relax.MLE.general_descriptive, relax.LF);**
196     fprintf (stdout, "", relax.MLE.general_descriptive, "");
197     io.reportProgressMessage("DEBUG","Completed Optimize (relax.MLE.general_descriptive, relax.LF)");
198     OPTIMIZATION_PRECISION = 0.001;
199     parameters.unconstrain_parameter_set ("relax.LF", {{terms.lf.local.constrained}});
200      io.reportProgressMessage("DEBUG", "Starting Optimize after  parameters.unconstrain_parameter_set");
201     Optimize (relax.MLE.general_descriptive, relax.LF);
202     io.reportProgressMessage ("RELAX", "Log(L) = " + relax.MLE.general_descriptive[1][0]);

Analysis Version
================
1.00

[RELAX] Loaded an MSA with 15 sequences and 133 codons from '/Users/dcaffrey/work/research/researchProjects/paralogs/specificInterfaces/dataset/P53_HUMAN//relaxSurface/sub1PostDupBranch/P53_HUMAN_hits.fasta'
[RELAX] Selected 1 branches as the test set: Node6
[RELAX] Obtaining branch lengths under the GTR model
[RELAX] Log(L) = -4554.82789989226
[RELAX] Obtaining  omega and branch length estimates under the local MG94xGTR model
[RELAX] Log(L) = -3958.006412039235
[RELAX] Obtaining omega and branch length estimates under the partitioned MG94xGTR model
[RELAX] Log(L) = -4174.764003662625
[RELAX] Two-stage fit of the general descriptive model (separate relaxation parameter for each branch)
[DEBUG] Before line 195 relax.LF:0
Error:
Constrained optimization failed, since a starting point within the domain specified for the variables couldn't be found.
Set it by hand, or check your constraints for compatibility.
Failed constraint:RELAX.reference.omega_2:=1/RELAX.reference.omega_0[0:0-1]/RELAX.reference.omega_1[0.0001:0.0001-1] must be in [1,10000]. Current value = inf.

**Function call stack
1 : Optimize storing into, relax.MLE.general_descriptive, the following likelihood function:relax.LF ;
	Standard input redirect:
		Empty Associative List-------
2 : ExecuteAFile from file fileToExe using basepath . reading input from inputRedirect
{"01":"Universal",
"02":"P53_HUMAN_hits.fasta",
"03":"P53_HUMAN_hits_unrootedTrifurcated.nh",
"04":"T",
"06":"All"}**
-------
HYPHYMP(58743,0x7fff7bb23300) malloc: *** error for object 0x7ffebc020c00: pointer being realloc'd was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
[P53_HUMAN_hits.fasta.txt](https://github.com/veg/hyphy/files/962285/P53_HUMAN_hits.fasta.txt)
[P53_HUMAN_hits_unrootedTrifurcated.nh.txt](https://github.com/veg/hyphy/files/962284/P53_HUMAN_hits_unrootedTrifurcated.nh.txt)

**Comment by spond** [comment]
Dear @dcaffrey,

This is a rare message that typically results from incompatible constraints on model parameters. Let me investigate.

Best,
Sergei

**Comment by dcaffrey** [comment]
I've attached a simpler set of input files that produce the same error. They may easier to use for debugging...
[PPARG_HUMAN_hits.fasta.txt](https://github.com/veg/hyphy/files/984773/PPARG_HUMAN_hits.fasta.txt)
[PPARG_HUMAN_hits_unrootedTrifurcated.nh.txt](https://github.com/veg/hyphy/files/984772/PPARG_HUMAN_hits_unrootedTrifurcated.nh.txt)

**Comment by rdvelazquez** [comment]
I was able to run RELAX on this data with the develop branch without issue.
