### ISSUE TITLE
Is there problems with your server?

### ISSUE THREAD

**Issue by vabadu** [veg/hyphy#547]
Hello,
I have noticed over the last few days that jobs are piling up quite substantially in the queue of Datamonkey.  Is there a problem with your server, or is it just super busy?  Also, I have now had multiple runs of Busted abort - sometimes after 24 hours of "running".  I am sure you are aware of these issues, but wanted to bring it up in case you were not.

Thanks for your time, 
Vanessa

**Comment by stevenweaver** [comment]
Dear Vanessa, 

Yes, we experienced an issue with nodes failing on our computing cluster late this week, which caused the datamonkey queue to become backlogged.

I have cleared the queue, please try resubmitting your jobs.

**Comment by vabadu** [comment]
Thank you!!


Vanessa


Vanessa Bauer

PRA - Sawyer Lab

Biofrontiers/MCDB

University of Colorado - Boulder

________________________________

**Comment by vabadu** [comment]
Hello,


Are you by any chance having node problems again?  Yesterday the queue started backing up again.


Thanks for your help, Vanessa


Vanessa Bauer

PRA - Sawyer Lab

Biofrontiers/MCDB

University of Colorado - Boulder

________________________________

**Comment by stevenweaver** [comment]
Dear Vanessa, 

Yes. Unfortunately, we are dealing with a combination of an issue that needs to be thoroughly troubleshooted and a skeleton staff while I am away on a combination of business and holiday. I have put in place a temporary solution, but web services may be inconsistent until next Wednesday. 

Best,
Steven

**Comment by stevenweaver** [comment]
Dear Vanessa,

Yes. Unfortunately, we are dealing with a combination of an issue that needs to be thoroughly investigated and a skeleton staff while I am away from Philadelphia. I have put in place a temporary solution, but web services may be inconsistent until next Wednesday.

Best,
Steven
