### ISSUE TITLE
RELAX bug in v2.3-dev

### ISSUE THREAD

**Issue by sjspielman** [veg/hyphy#549]
A bug has cropped up in SelectionAnalyses/RELAX.bf in v2.3-dev, reproducible when run both locally on Mac and on silverback. The bug does not appear in the current 2.2.7 release (tested with same dataset).

Analysis stdout as follows:
```
[RELAX] Obtaining branch lengths under the GTR model
[RELAX] Log(L) = -808.0806806805953
[RELAX] Obtaining  omega and branch length estimates under the local MG94xGTR model
[RELAX] Log(L) = -768.1974001487026
[RELAX] Obtaining omega and branch length estimates under the partitioned MG94xGTR model
[RELAX] Log(L) = -2e+100
Error:
'ModelMatrixDimension' was expected to be a numerical argument.

Function call stack
1 : ModelMatrixName={ModelMatrixDimension,ModelMatrixDimension}
-------
2 : PopulateModelMatrix((model_parameters["Q"])[k-1],relax.nuc,"t","Min (1000,"+(model_parameters["omegas"])[k-1]+"^local_k)","")
-------
3 : RELAX.reference.model=relax.io.define_a_bsrel_model(RELAX.reference,relax.codon_frequencies,estimators.GetGlobalMLE(relax.mg_results,RELAX.reference),1)
-------

Check errors.log for details on execution errors.

Check messages.log details of this run.
```

Dataset to reproduce error: 
[test-relax.fasta.txt](https://github.com/veg/hyphy/files/1008601/test-relax.fasta.txt)

**Comment by spond** [comment]
Dear @sjspielman,

This issue (and another one yielding -2e+100 estimates) has been fixed with 4efc3b5a9a6c205ff49b82273e1529eabf14507b

RELAX.bf is still diverged from the libv3 branch in that it uses imbedded and out-of-date code to deal with commodity tasks (like defining genetic codes and branch sets), which explains the origin of this issue.

Please confirm that the fix works.

Best,
Sergei

**Comment by sjspielman** [comment]
Works fine now, for both "All" and "Minimal" analysis settings. Thanks!

**Comment by sjspielman** [comment]
I spoke slightly too soon - while the analysis does run now, there are issues with the output JSON being populated. For example, inferred branch lengths are missing due to typos in json keys (function extracts key "branch lengths" but the key in the fitted model is "branch length"). Either way, I'm working now on updating JSONs to be more consistent and sane across analyses so I will resolve this and send pull request in near future.
