### ISSUE TITLE
Unable to select reference branch set in test.datamonkey RELAX

### ISSUE THREAD

**Issue by sjspielman** [veg/hyphy#550]
Test branches are selectable, but cannot select reference branches - this selection is entirely unresponsive.

**Comment by stevenweaver** [comment]
Cannot reproduce as currently stated.

**Comment by sjspielman** [comment]
Issue is reproducible on Macbook Pros (not iMacs) using Chrome Version 58.0.3029.110 (64-bit). Issue is reproducible as well on Safari 10.1, but not 10.0.3, again only on MBP.

**Comment by stephenshank** [comment]
I can also reproduce this using Chrome Version 58.0.3029.110 (64-bit), but only on my MacBook Pro. Using the exact same version on my iMac, it works fine. Very strange...
