### ISSUE TITLE
Inconsistent GY94 inferences.

### ISSUE THREAD

**Issue by hyphyInfant** [veg/hyphy#552]
Hello Sergei.

It was really nice meeting you and Art Poon yesterday at the conference. I attached a zipped folder containing some data sets and HyPhy batch scripts. I inferred the alignment-wide omega values for the data sets using the GY94 model on my computer (using an HYPHYMP that I installed in 2014) and on the silverback cluster. Unfortunately, I got significantly different answers for both platforms. Please, I need help to understand whether the inconsistencies were caused by my code or it is an software update issue.

I look forward to your response. 

Kindest regards,
hyphyInfant.

[question.zip](https://github.com/veg/hyphy/files/1025999/question.zip)

**Comment by spond** [comment]
Dear @hyphyInfant 

Can you please provide the discordant results obtained by two HyPhy versions?

Best,
Sergei

**Comment by hyphyInfant** [comment]
Dear Sergei.

Thank you for your swift response. The requested copies of the discordant outputs were attached to this message. I look forward to your response.

Grateful,
hyphyInfant.

[myComputerMaxLikelihoods.txt](https://github.com/veg/hyphy/files/1036245/myComputerMaxLikelihoods.txt)
[myComputerFullLikelihoods.txt](https://github.com/veg/hyphy/files/1036246/myComputerFullLikelihoods.txt)
[silverbackMaxLikelihoods.txt](https://github.com/veg/hyphy/files/1036248/silverbackMaxLikelihoods.txt)
[silverbackFullLikelihoods.txt](https://github.com/veg/hyphy/files/1036250/silverbackFullLikelihoods.txt)

**Comment by hyphyInfant** [comment]
Hello Sergei.

I still do not understand the reason behind the inconsistencies in the omega estimates from the different HyPhy installations. I trust that you will be able to advice me on how to deal with the problem soon.

Thank you in advance,
hyphyInfant.
