### ISSUE TITLE
full HBL documentation

### ISSUE THREAD

**Issue by elilk** [veg/hyphy#553]
Dear HyPhy team,

We are very interested in developing our own models using HyPhy. For that, we would like to learn HBL. However, in spite of searching thoroughly, we could not find the complete documentation of the language (for example, in the 2005 paper it says the full documentation is part of the distribution and a link is provided. However, this link seems to be broken...).
**Could you please point us to the full HBL documentation for the version of HyPhy that should be used?** (we read on your site that you plan major changes).

Many thanks and kindest regards,
Keren and Eli

**Comment by sjspielman** [comment]
Hi all, 

Are you referring to wiki links that aren't working? If so yes, many of those will not work. Here's my general update on docs - 
There is unfortunately no full documentation for the current version of HBL. We are in the process of writing the next major version of HBL which will have full documentation, although of course it is forthcoming. In the meantime, I recommend looking through previous papers which have written custom HBL code (for example: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0603-7) and/or looking through current code. The hyphy website has a brief minimal example of HBL here also: http://hyphy.org/about/#example-hbl-script . Also feel free to post any questions on this issues page for feedback.
I'm sorry I can't point you to something more definitive. Again, I'm planning to write full documentation for the next iteration of HBL once it is completed. Stay tuned..

-Stephanie

**Comment by spond** [comment]
Dear @elilk,

I have this old reference document which is probably the most complete document I have (attached). You can also look within `tests/hbltests/UnitTests/HBLCommands` for more recent examples.

I will also be more than happy to assist you with specific questions; this will probably be easiest. 

Best,
Sergei

[hbl.html.zip](https://github.com/veg/hyphy/files/1034991/hbl.html.zip)

**Comment by elilk** [comment]
Wonderful!!! We'll a look there. Thanks for the quick reply!

**Comment by ArtPoon** [comment]
Many years ago, I started writing a book on HyPhy and HBL, but I've been looking around my computers and I can't find my TeX files...
