### ISSUE TITLE
Stochastic mapping in HyPhy

### ISSUE THREAD

**Issue by elilk** [veg/hyphy#555]
Dear HyPhy team,

We are interested in implementing stochastic mapping (Nielsen 2002) in HBL.
Specifically, we are interested in a two-state Markov model (1/0) and obtaining a mapping along branches of a given tree.

our questions are:
1. Is there an existing implementation for this in HyPhy? (the "counting renaissance" paper from 2012, Lemey et al. suggests there might be)
2. If not, we would like to follow the algorithmic steps as defined in Nielsen 2002. How shall we go about it, using HBL?

Many thanks,
Keren and Eli

**Comment by spond** [comment]
Dear @elilk,

There is an internal implementation of parts of the Nielsen algorithm -- they only have to do with sampling states of internal **nodes** using posterior probabilities. The rest of the algorithm (i.e. deciding where the substitutions may occur) has to be implemented on top of it. I'll send you some code examples next week, when I return from a foreign trip.


Best,
Sergei

**Comment by elilk** [comment]
Dear Sergei,

Thank you very much for the prompt reply. Great, we look forward to the
code examples :)

Regards and thanks,
Keren and Eli

**Comment by elilk** [comment]
Dear Sergei and Art,

We managed to sample internal states for each node based on the ASR script. Thanks for that lead!
We would now like to sample the transition points on each branch. If you have a code example in that direction, it will be of great help.

Many thanks,
Keren and Eli

**Comment by spond** [comment]
Dear @elilk,

Are you looking to implement the algorithm of Nielsen from his early '00 paper, i.e. to sample from the chain conditioned on the starting and ending states?

Best,
Sergei

**Comment by elilk** [comment]
Dear Sergei,

We thought of Nielsen 2002 (Syst. Biol.) but what you wrote sounds fitting
(given the start and end states of all nodes [leafs + internals], sample
the waiting times along the connecting branch and then the identity of the
character of each event).

Thanks,
Keren and Eli
