### ISSUE TITLE
Branch-site REL followed by MEME and FUBAR

### ISSUE THREAD

**Issue by DonBCilly** [veg/hyphy#556]
Dear HyPhy Users,

Using an alignment of recently duplicated paralogs for around 25 species, I have applied the BS-REL method to ask the question: "Is there evidence of positive selection at a proportion of sites following the duplication of the ancestral Gene?"

BS-REL reports significant values for two nodes on the tree, corresponding to two putative duplication events. I then wanted to ask "specifically, which codons have experienced either episodic (MEME) or pervasive (FUBAR) positive selection?"

However, neither of these methods reports any positively selected sites.
I was wondering what the reason for this discrepancy could be?

Thanks a lot in advance!

Don.

**Comment by sjspielman** [comment]
Hi Don, 

In general, there is no reason that any two methods should have to return the same or overlapping information. It is possible that there is not sufficient signal in your data (indeed 25 taxa is relatively small) to detect selection on a site-specific level, but there is sufficient signal to detect selection across branches when signal across sites is pooled as in BS-REL. In addition, if the strength of positive selection relatively weak, it will (usually) only be detectable for methods like BS-REL which pool the signal.

Either way, this result is not cause for concern and is more or less a "normal" byproduct of using different methods.

Best, 
Stephanie
