### ISSUE TITLE
Reading Newick tree from file

### ISSUE THREAD

**Issue by elilk** [veg/hyphy#557]
Dear Team,

Is it possible in HBL to provide a path to a file that contains a tree in Newick format instead of providing the tree string itself?

Thanks,
Keren and Eli

**Comment by ArtPoon** [comment]
Yes:
```
fscanf("/path/to/file", "Tree", container);
```
You might need to use the `DIRECTORY_SEPARATOR` object instead of `/`.

**Comment by elilk** [comment]
Thanks!!!

**Comment by spond** [comment]
Dear @elilk,


In addition to what Art suggested, you may also take a look at the functions in `TemplateBatchFiles/libv3/tasks/trees.bf` for further ways to handle tree objects. 

```
LoadFunctionLibrary ("libv3/tasks/trees.bf");

... access tree.X functions here

```

For example these functions allow HyPhy to handle tree strings which include taxon names not conforming to HyPhy variable ID requirements (e.g. "taxon-x/11")

You can also use

```
fscanf("/path/to/file", "String", container);
```

If you don't want HyPhy do to more involved parsing (like reading TREE blocks from NEXUS files) which is invoked by passing "Tree" as the format specifier to `fscanf`.

Best,
Sergei

**Comment by elilk** [comment]
Thanks! We'll have a look there.
