### ISSUE TITLE
Single-threaded HYPHY build

### ISSUE THREAD

**Issue by j-kominek** [veg/hyphy#558]
Hi, I want to run multiple HYPHY analyses in parallel, and I noticed that after the hyphyqt merge the HYPHYSP build target was gone. Was there a specific reason for that? Currently I am just running the MPI build with "-np 1", but that's just a workaround. Are there any plans to bring SP back?Thanks!

**Comment by spond** [comment]
Dear @j-kominek,

You can always enforce single-threaded behavior by providing a command line argument to HyPhy, as in 


```
$/path/to/HYPHYMP CPU=1 
```

Best,
Sergei

**Comment by j-kominek** [comment]
Dear Sergei,
Thank you for a prompt reply! I was actually looking for the command line arguments, but didn't find that one and simply running HYPHYMP (by itself, or with "-h"/"--help") just got me right into the analysis choice menu. It's good to know that we can specify a number of processors to be used by HYPHY (by default it uses all available CPUs, correct?). I hope I'm not asking too much, but do you have any information to share about how much do specific analyses benefit from parallelization? I know some of them are built around MPI (e.g. GARD), which are a class of their own, but how about the others, like MEME, RELAX or aBS-REL? I wonder how well they scale, I mean is there a point in going above 2-4 CPUs, e.g. into 16 or 24? Thanks again,

-Jacek

**Comment by spond** [comment]
Dear @j-kominek,

By default, HyPhy will indeed may use **up to** as many threads as there are on the system, obtained via a call to `omp_get_max_threads` (this will return up to 2 per core in many Intel processors for example). 

Most MP benefits will be gained in individual calls to `Optimize` for likelihood functions, where individual computations are parallelized. In most cases, HyPhy will separate sites (unique patterns) in the alignment into N (number of threads) approximately equal parts and send them off to individual threads. 

HyPhy will use a very simple run-time benchmark to automatically detect how many threads are "best" for a given analyses, and if it's not warranted, it won't use the maximum number of threads. For example, on my MacBook Pro:

```
$HYPHYMP tests/hbltests/SimpleOptimizations/SmallCodon.bf 
...
$grep benchmark messages.log 
Auto-benchmarked an optimal number (3) of threads.
```

```
$HYPHYMP tests/hbltests/REL/NY.bf
...
$grep benchmark messages.log 
Auto-benchmarked an optimal number (4) of threads.
Auto-benchmarked an optimal number (3) of threads.
Auto-benchmarked an optimal number (6) of threads.
```

Generally, you will need very large analyses with complex models (e.g. codon models on many sequences / sites) to scale up to 16 or more processors.

Best,
Sergei

**Comment by j-kominek** [comment]
Dear Sergei,
Thank you for the explanation and advice, much appreciated!
