### ISSUE TITLE
Problem installing Hyphy

### ISSUE THREAD

**Issue by leapicard** [veg/hyphy#560]
Dear Hyphy team,

I am trying to install Hyphy after cloning it from the master branch.
However, when I run `cmake .`
I get an error:

> -- Could NOT find CURL (missing:  CURL_LIBRARY CURL_INCLUDE_DIR) 
> -- Could NOT find OpenCL (missing:  OPENCL_LIBRARIES OPENCL_INCLUDE_DIR) 
> -- Could NOT find MPI_C (missing:  MPI_C_LIBRARIES MPI_C_INCLUDE_PATH) 
> -- Could NOT find MPI_CXX (missing:  MPI_CXX_LIBRARIES MPI_CXX_INCLUDE_PATH) 
> -- Configuring done
> WARNING: Target "hyphy_mp" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
> WARNING: Target "HYPHYMP" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
> -- Generating done
> -- Build files have been written to: /home/lea/hyphy

However, both Curl and OpenMPI are installed, so I do not understand why Cmake can't find the paths.

Any help?

Thank you and best regards,
Lea

**Comment by stevenweaver** [comment]
Dear Lea,

In order to better assist you, may I ask which version of Linux you are attempting to install HyPhy on? 

You may need the header files installed for the respective packages. On a RHEL flavored distribution, for example, you might want to verify that you have `libcurl-devel` installed. On a Debian-based flavor of Linux, it would be `libcurl-dev`. 

If you are not using a package manager for curl and MPI, you would want to ensure that your `LD_LIBRARY_PATH` environment variable includes the path to your header files. 

Please let me know if this helps.

Best,
Steven

**Comment by leapicard** [comment]
Dear Steven,

Thank you for your answer,
I am on Ubuntu 16.04.
Installing libcurl-dev has indeed helped but I still can't figure the problem with OpenCL and the MPIs. I am not familiar enough with header files to know where to look for them.

Best,
Lea

**Comment by stevenweaver** [comment]
Dear Lea, 

Are you intending on using the OpenMPI target, `HYPHYMPI`? If you do not intend on running HyPhy within the context of computing cluster, then the `HYPHYMP` target should suffice. OpenCL can safely be ignored as well. 

Please try executing the command: 
`make HYPHYMP`

Best,
Steven

**Comment by leapicard** [comment]
Dear Steven,

I wanted to install HYPHYMPI as it kept returning the error that I needed an MPI environment each time I tried to run GARD with my previous install.
By the way, running 
`make HYPHYMP`
returns:

> [100%] Linking CXX executable HYPHYMP
> /usr/bin/ld : ne peut trouver -lcrypto
> /usr/bin/ld : ne peut trouver -lssl
> collect2: error: ld returned 1 exit status
> CMakeFiles/HYPHYMP.dir/build.make:1264 : la recette pour la cible « HYPHYMP » a échouée
> make[3]: *** [HYPHYMP] Erreur 1
> CMakeFiles/Makefile2:131 : la recette pour la cible « CMakeFiles/HYPHYMP.dir/all » a échouée
> make[2]: *** [CMakeFiles/HYPHYMP.dir/all] Erreur 2
> CMakeFiles/Makefile2:138 : la recette pour la cible « CMakeFiles/HYPHYMP.dir/rule » a échouée
> make[1]: *** [CMakeFiles/HYPHYMP.dir/rule] Erreur 2
> Makefile:188 : la recette pour la cible « HYPHYMP » a échouée
> make: *** [HYPHYMP] Erreur 2

Best,
Lea

**Comment by stevenweaver** [comment]
Dear Lea,

You will also need the openssl library : `apt-get install libssl-dev`

I see, GARD is only supported by the `HYPHYMPI` target. I am not sure which version of MPI you have installed, but you also need to install the library for MPI. 

On Ubuntu, it would be something like the following if you are using openmpi:
`apt-get install openmpi-bin openmpi-doc libopenmpi-dev`

**Comment by leapicard** [comment]
Dear Steven,

thank you for your help, installing those helped and I was able to finish the install.
Just a note in case someone else encounters the same problem, for openCL missing libraries, the command is actually:
`sudo apt-get install ocl-icd-opencl-dev`

I couldn't make the LIB, but as I am not sure it is really necessary for me, I'm not too worried about it.
Just in case, though, it returns:

> [  5%] Building CXX object CMakeFiles/hyphy_mp.dir/src/core/baseobj.cpp.o
> In file included from /home/lea/hyphy/src/core/baseobj.cpp:40:0:
> /home/lea/hyphy/src/core/include/baseobj.h:60:20: fatal error: THyPhy.h: Aucun fichier ou dossier de ce type
> compilation terminated.
> CMakeFiles/hyphy_mp.dir/build.make:62 : la recette pour la cible « CMakeFiles/hyphy_mp.dir/src/core/baseobj.cpp.o » a échouée
> make[3]: *** [CMakeFiles/hyphy_mp.dir/src/core/baseobj.cpp.o] Erreur 1
> CMakeFiles/Makefile2:227 : la recette pour la cible « CMakeFiles/hyphy_mp.dir/all » a échouée
> make[2]: *** [CMakeFiles/hyphy_mp.dir/all] Erreur 2
> CMakeFiles/Makefile2:362 : la recette pour la cible « CMakeFiles/LIB.dir/rule » a échouée
> make[1]: *** [CMakeFiles/LIB.dir/rule] Erreur 2
> Makefile:279 : la recette pour la cible « LIB » a échouée
> make: *** [LIB] Erreur 2

**Comment by stevenweaver** [comment]
You're welcome!
