### ISSUE TITLE
Redirecting output files

### ISSUE THREAD

**Issue by leapicard** [veg/hyphy#561]
Dear Hyphy team,

I am trying to automate analysis of multiple fasta using BUSTED, MEME and GARD.
I was wondering it there is any possibility to chose where output files will go and how to name them.

Best regards,
Lea

**Comment by stevenweaver** [comment]
Dear Lea, 

For BUSTED and MEME, the location of output files is not provided as a supported option. 

In BUSTED's case, for example, the output would be the name of the provided file with the suffix `.BUSTED.json`. The code is located [here](https://github.com/veg/hyphy/blob/master/res/TemplateBatchFiles/BUSTED.bf#L60).

The function call that the HyPhy batch language provides to write to files or `stdout` is `fprintf`. Please see this [line](https://github.com/veg/hyphy/blob/master/res/TemplateBatchFiles/BUSTED.bf#L185).

Best, 
Steven

**Comment by leapicard** [comment]
Dear Steven,

thank you for the quick answer.
I have another problem running MEME, I tried to use the MEME_mf.bf file from the template batch files, but it returns an error when I try to run it.

> Phase 1:Nucleotide Model (012345) Model Fit
> 
> 
> -2002.25459720048
> 
> Phase 2:MG94x(012345) Model Fit
> 
> 
> 
> Phase 3:Estimating dN/dS
> 
> 
> Nuc->codon scaling factor:2.3916898284902
> Raw scaling factor:2.435229434701657
> Tree scaling factor(S): 1.018204537098752
> 
> Using dN/dS=0.2076083917376879
> Codon model:-1913.60902250074
> <<Significance level for Likelihood Ratio Tests (permissible range = [0,1], default value = 0.05)>>
> MEME will use test p-value of 0.05
> 
> [MEME PHASE 0] Retuning branch lengths and nucleotide rates under the codon model...
> Improved Log(L) BY 0.2066292392021296 points
> [MEME PHASE 1]. Fitting a codon model site-by-site
> | Codon |     Beta- |   Weight- |    Beta+  |   Weight+ |     alpha |      LRT  |   p-value |Full Log(L)|   Est. remaining time (secs)
> Error:
> perBranchTree is undefined in call to ReplicateConstraint.
> 
> Function call stack
> 1 : Replicate the following constraint "this1.?.alpha:=_sFactor*this2.?.synRate__" using these variables:perBranchTree;codonTree;
> -------
> 2 : result_String["BRANCHES"]=obtainBranchWiseEBEstimates(sFactor,nsFactor1,nsFactor2,mixingP,filterString)
> -------
> 3 : Branch under condition 'SendJobMEME()'
> 	to
> 		<END EXECUTION>
> 	else
> 		<END EXECUTION>
> -------
> Erreur de segmentation (core dumped)

However when I run it through the CLI from the top, it works perfectly fine with the same input files.
Am I supposed to use another batch file?

Best,
Lea

**Comment by spond** [comment]
Dear @leapicard,

Please see the thread on issue #345 for workaround suggestions on the MEME crash.

Best,
Sergei

**Comment by stevenweaver** [comment]
Closing this issue since last comment references #345
