### ISSUE TITLE
Sampling a value from a Poisson distribution in HBL

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#564]
Hi,

Is there are a way to sample a value from a Poisson distribution with some parameter gamma in HBL?

Thanks!
Keren

**Comment by stevenweaver** [comment]
Dear Keren, 
Yes, you can draw from a Poisson distribution in HyPhy. 

```
LoadFunctionLibrary("Utility/ProbabilityDistributions.bf");
fprintf(stdout, sampleFromPoisson(4));
```

Best,
Steven

**Comment by halabikeren** [comment]
Perfect! Thank you:)
