### ISSUE TITLE
Object of dynamic length in HBL

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#566]
Hi,

Is there an object, like c++ vector, in HBL, that doesn't required dimensions specification ahead, and can be expanded dynamically?

Thanks!
Keren

**Comment by stevenweaver** [comment]
Dear Keren,

Yes, HyPhy has `associative arrays`, which can be allocated dynamically.

Example:

```
foo = {}; 
foo["bar"] = "baz";
fprintf(stdout,foo);
```

Best,
Steven

**Comment by halabikeren** [comment]
Thank you!
