### ISSUE TITLE
Setting a likelihood function with fixed branch lengths

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#573]
Dear Team,

Is it possible to define a likelihood function with a tree that has fixed branch lengths?

Say that I want to use the function SampleAncestors(lf) with a likelihood function lf that regards the tree branch lengths as constants. 

When I try to use the command 'UseModel (USE_NO_MODEL)' before setting the tree instance T, and then set the likelihood function, I receive an error: LF: Not a well-defined tree/model combination: T.

Maybe there is another way?

Thank you!
Keren

**Comment by ArtPoon** [comment]
Have you tried supplying a tree with explicit unit branch lengths and using the following:
'''
USE_BRANCH_LENGTHS=1;
'''

**Comment by ArtPoon** [comment]
Actually it might be `ACCEPT_BRANCH_LENGTHS=1;`
It's been a while :-)

**Comment by halabikeren** [comment]
Thanks!

Maybe I'm not using it right.

Here is an example of a bf script in which I use the suggested constant assignment, but not "useModel":
[lf_useModel.bf.txt](https://github.com/veg/hyphy/files/1134791/lf_useModel.bf.txt)

The output log:
[messages_lf_useModel.log.txt](https://github.com/veg/hyphy/files/1134792/messages_lf_useModel.log.txt)

As can be seen in the log file, although the original branches lengths are processed when reading the tree, once the likelihood function is set, they are modified. This is probably because I didn't restrict the likelihood function not to consider the branch lengths as model's parameters.
However, when I try to add 'UseModel (USE_NO_MODEL)' before setting the tree, I still get the error:
'LF: Not a well-defined tree/model combination: treeid'

So I suppose I'm not using it correctly. Unfortunately, I was unable to find examples of setting a likelihood function that doesn't consider the branch lengths as model's parameters in HBL.

**Comment by ArtPoon** [comment]
Can you send me a minimal data set for reproducing this issue? 
i.e., `data.seq` or some truncated or randomized version of this file that produces the same error.

**Comment by halabikeren** [comment]
Sure,

This is the dataset I used:
[data.seq.txt](https://github.com/veg/hyphy/files/1141193/data.seq.txt)

And the script is:
[lf_useModel.bf.txt](https://github.com/veg/hyphy/files/1141198/lf_useModel.bf.txt)

Thanks!

**Comment by ArtPoon** [comment]
You can't build a likelihood function with the tree because it has no model assigned to its branches.  I would refer to `dNdSRateAnalysis.bf` as a template for how to constrain the branch lengths of your tree.  Here are some excerpts:
```C
UseModel 		  (USE_NO_MODEL);
Tree inTree 	= treeString;
_stringBLs      = BranchLength (inTree,-1);

// if you want to fit a codon model and branch lengths are expected nucleotide substitutions
// _stringBLs = _stringBLs*3;
```

Next you need to manually constrain the branch lengths of your tree and assign a model:
```C
Model model = (RateMatrix, observedCEFV);  // from your script

Tree  givenTree = treeString;  // assigns this model with branch length parameter `resFctor`
bnames = BranchName (givenTree,-1);
lbc    = Columns    (bnames) - 1;
for (lc = 0; lc < lbc; lc = lc+1) {
    ExecuteCommands("givenTree." + bnames[lc] + ".resFctor:=" + _stringBLs[lc] + ";");
}
```

This is just my first pass at adapting the content of the `dNdSRateAnalysis.bf` script to your problem.  I think you'd have to add some adjustment for your global parameter `mu` in the `ExecuteCommands` expression.

**Comment by halabikeren** [comment]
Thank you for the elaborated explanation!


I'm still having a difficultly understanding two things:

1) How the branches lengths of a tree under a given model are calculated?
    I thought that the branch lengths are accepted by summing the diagonal of the rate matrix, set with 
    their parameters values (for example, for branch S1, resFactor's value is 2 and the mu's value is 1 -> 
    the length of branch S1 under the model should be 2*1+2*1=4). This doesn't seem to be the case.

2) It seems that despite fixing the re-scaling factor parameter of each branch to be its own length, once 
    loading the model onto the tree, the branches lengths are divided by (1/0.48).

Please find below a script that demonstrates this issue:

The script: 
[lf_useModel.bf.txt](https://github.com/veg/hyphy/files/1145013/lf_useModel.bf.txt)


The input data for the script:
[data.seq.txt](https://github.com/veg/hyphy/files/1145014/data.seq.txt)


The log output: 
[messages.log.txt](https://github.com/veg/hyphy/files/1145015/messages.log.txt)


As can be seen in the log file:
(1) When loading the tree without the model, the branches lengths are processed successfully.
(2) When setting the re-scaling factor of each branch, the required values are assigned to it.
(3) When loading the model onto the tree, the branches lengths are modified to be their old value*
     (1/0.48) each.

I don't understand the logic that caused (3) to occur.

**Comment by spond** [comment]
Dear @halabikeren,

Try this.

```
// SLKP: the following flag asks HyPhy to attempt 
// to convert user tree branch lengths into appropriate 
// model parameter values

AUTOMATICALLY_CONVERT_BRANCH_LENGTHS = 1;  

// SLKP: if you don't want HyPhy to unroot the tree,
// then set the following environment variable

ACCEPT_ROOTED_TREES   = TRUE; 

// varying traits
traitDataPath = "./data.seq"; 
treeStr = "(S1:2,((S2:1,S3:1):1,S4:1):1,S5:1);";

DataSet traitData  = ReadDataFile(traitDataPath);           
DataSetFilter leavesFilteredData = CreateFilter(traitData,1);

global mu = 1.0;             
// set initial mu
// SLKP: please not that in the matrix below 'mu'
// and 'resFctor' are confounded; only their product 
// can be estimated

RateMatrix = {{* ,mu*resFctor}                              
			  {mu*resFctor,*}};
			  
			  

HarvestFrequencies(observedCEFV,leavesFilteredData,1,1,1); 
Model model = (RateMatrix, observedCEFV);		

Tree treeid = treeStr;
LikelihoodFunction theLikFun = (leavesFilteredData, treeid);     // set the likelihood function
fprintf(stdout, "theLikFun: ", theLikFun, "\n");

```

Best,
Sergei

**Comment by halabikeren** [comment]
Thank you!

It's working now:)

By adding the line 'AUTOMATICALLY_CONVERT_BRANCH_LENGTHS = 1;' to my code, the branch lengths are indeed adjusted to their original length.

I see the branch length expression is consisted of the some factor 0.32 that re-scales the branch lengths back to their original length. This re-scaling factor is not declared in the model.

When I try to remove the local parameter in my model, denoted by 'resFactor', this un-declared factor remains with the same value - 0.32 - and the branch lengths are not re-scaled to their original length.

Therefore, I'm slightly confused. 

I want to define a model over 2 characters, with a single global parameter 'mu', and the initial frequencies of the characters. I don't really need the local parameter 'resFactor', but I was using it for allowing the branch lengths to vary (since, as per my understanding, each branch length is calculated by summing over the diagonal in its assigned rate matrix). As per your comment, I cannot estimate the global parameter 'mu' and the local parameter 'resFactor' separately, as they are confounded. I need the estimation of 'mu' alone - which should be the same for all branches, as it is a global parameter. How can I achieve this?

Thanks again!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

You can't have branch lengths that vary across the tree without local parameters, unless you want all branches to have the same length. If you adjust `mu`, you will also adjust all branch lengths, so you can't estimate it without changing the branch lengths away from whatever the initial values were. 

I don't quite understand what you are trying to achieve, so perhaps you can walk me though it before we go any further.

Best,
Sergei

**Comment by halabikeren** [comment]
Thank you Sergei!

Your answer clarified that the solution you offered provides me what I need.
I am using the local parameter resFactor as a means to allow varying branches lengths along the tree. Therefore, I only need the estimation of the global parameter mu. So in this case, I shouldn't mind that the resFactor and mu are confounded.
However, I'm not sure I understand my the resFactor didn't include the constant that was added to the branch length expression when using 'AUTOMATICALLY_CONVERT_BRANCH_LENGTHS = 1;' to begin with.
