### ISSUE TITLE
Problem reading tree file with BUSTED

### ISSUE THREAD

**Issue by numberjax** [veg/hyphy#574]
Hi,
I am trying to use BUSTED with my own tree file at the end of my multiple sequence alignment but  when I load my file it only shows the nj tree which is not the same as the species tree. 
Is there some issue with my formatting?

I appreciate any advice!

[datamonkey_test.txt](https://github.com/veg/hyphy/files/1133894/datamonkey_test.txt)

**Comment by ArtPoon** [comment]
Spaces are illegal characters for trees in HyPhy and your node names don't match between the tree and data blocks.
Best
A

**Comment by ArtPoon** [comment]
Actually it might be 'ACCEPT_BRANCH_LENGTHS=1;'
It's been a while :-)

**Comment by numberjax** [comment]
Thanks for such a quick response to my query! 

I appreciate you pointing out the errors with the gaps and the names of the nodes! I have corrected this now and everything is working :)

Thanks again for your help!!
