### ISSUE TITLE
mapping node index to father node index

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#576]
Dear Team,

We would like to create a map where the keys are node indices (not the post-order traversal indices but rather, the hyphy internal node indices) and the values are father node indices (also internal).
Based on [Art's code example](http://www.hyphy.org/pubs/Nef/MapMutationsToTree.bf), we managed to obtain such a mapping by combining the branch-to-node map with the node-to-fatherTraversalId map. However, we were wondering if there's a more elegant way to achieve this, for example, by traversing the tree, each time going "up" a branch, extracting the lower (son) node index and the upper (father) node index and inserting the pair into a map.
We could not find a direct code for tree traversal (only the result of traversing the tree -- flat).

Thanks and regards,
Keren and Eli

**Comment by spond** [comment]
Dear @halabikeren,

You could use something like this. 

```
Tree test_tree = ((((Pig:0.147969,Cow:0.213430):0.085099,Horse:0.165787,Cat:0.264806):0.058611,((RhMonkey{PR}:0.002015,Baboon{PR}:0.003108){PR}:0.022733,(Human{PR}:0.004349,Chimp{PR}:0.000799){PR}:0.011873){PR}:0.101856){PR}:0.340802,Rat:0.050958,Mouse:0.097950);

post_order_dict = test_tree ^ 0;

fprintf (stdout, post_order_dict);

/*

{
 "1":{
   "Name":"Pig",
   "Length":0.147969,
   "Depth":4,
   "Parent":3
  },
  "2":{
   "Name":"Cow",
   "Length":0.21343,
   "Depth":4,
   "Parent":3
  },
 "3":{
   "Name":"Node3",
   "Length":0.08509899999999999,
   "Depth":3,
   "Parent":6,
   "Children":{
     "0":1,
     "1":2
    }
  }
  ...
*/

node_parent_map = {};

for (node_index = 1; node_index < Abs (post_order_dict) - 1; node_index += 1) {
    parent_index = (post_order_dict[node_index])["Parent"];
    node_parent_map [ (post_order_dict[node_index])["Name"] ] = (post_order_dict[parent_index])["Name"];
}

fprintf (stdout, node_parent_map);


/*

{
 "Pig":"Node3",
 "Cow":"Node3",
 "Node3":"Node2",
 "Horse":"Node2",
 "Cat":"Node2",
 "Node2":"Node1",
 "RhMonkey":"Node9",
 "Baboon":"Node9",
 "Node9":"Node8",
 "Human":"Node12",
 "Chimp":"Node12",
 "Node12":"Node8",
 "Node8":"Node1",
 "Node1":"Node0",
 "Rat":"Node0",
 "Mouse":"Node0"
}

*/
```

Best,
Sergei

**Comment by halabikeren** [comment]
Thank you!
