### ISSUE TITLE
hyphy fails to raise syntax error

### ISSUE THREAD

**Issue by sjspielman** [veg/hyphy#590]
HyPhy v2.3-dev may fail under certain circumstances to raise a syntax error, and will instead "proceed" with the poor syntax to eventually error out for incurred reasons. Behavior has been seen with constructing mixture models for MEME, in the lfunction model.BranchLengthExpression.

**Comment by spond** [comment]
Dear @sjspielman,

Could you possibly provide a self-contained example of this behavior?

Best,
Sergei

**Comment by sjspielman** [comment]
Yes - here's how to reproduce the bug, in the only context where I ever encountered it. In v2.3-dev, in `models/model_functions.bf`, replace line 419 (in the lfunction model.BranchLengthExpression) with the syntactically wrong line:

```
\\ Current line
keys = utility.Keys (model[^'terms.rate_matrix']);

\\ Replace with this line, which is missing a closing bracket:
keys = utility.Keys (model[utility.getGlobalVariable('terms.rate_matrix'));
```

Then perform a MEME analysis with the attached dataset: [data.txt](https://github.com/veg/hyphy/files/1215902/data.txt) . In my experience, this bug did not cause hyphy to raise a syntax error. Instead, hyphy proceeded to skip over the entire *remainder* of the function and return null. This faulty return value is what ended up triggering a downstream error.

**Comment by spond** [comment]
Dear @sjspielman,

For a single-line file

```
keys = utility.Keys (model[utility.getGlobalVariable('terms.rate_matrix'));
```

I am getting the following error

```
Error:
Missing or unbalanced '[]'  in the following context: 'ble('terms.rate_matrix'))<ERROR HERE>'
```

Seems like this broken line needs to be put into a different context.

Best,
Sergei

**Comment by sjspielman** [comment]
I encountered it while de-hardcoding in my fork so perhaps it was related to that, which is probably good and means I caused some cryptic bug that is now gone(?).
