### ISSUE TITLE
FUBAR fails when tree has internal labels

### ISSUE THREAD

**Issue by sjspielman** [veg/hyphy#591]
For all hyphy versions, FUBAR will fail to run if there are branch/model labels in the provided tree. May cause issue(s) for repeated analyses. See attached example datasets for a failing FUBAR and a successful FUBAR.
[fubar_fails.txt](https://github.com/veg/hyphy/files/1212414/fubar_fails.txt)
[fubar_works.txt](https://github.com/veg/hyphy/files/1212413/fubar_works.txt)

**Comment by spond** [comment]
Dear @sjspielman,

Can you confirm that this has been resolved in 2.3.4?

Best,
Sergei
