### ISSUE TITLE
How to set NEXUS partitions for HYPHY's LHT.bf

### ISSUE THREAD

**Issue by HyPhyUser** [veg/hyphy#593]
Dear HYPHY developers,

I am using a locally installed (OS Windows 7 Professional) version of HYPHY to perform a LHT test for conflicting phylogenetic signal between two partitions of a NEXUS formatted nucleotide data matrix, but HYPHY does not recognize my partitions.

Specifically, I run "Standard Analyses" from the Analyses menu of the console, and select "Recombination" and "LHT.bf".

HYPHY asks "How many replicates?"

After entering the number of replicates a window pops up asking "Please locate a partitioned NEXUS file"

After entering the data file and setting the model I obtain the following message:

"Please add character sets to your NEXUS file..."

Apparently, HYPHY does not recognizes my partitions and I am not able to understand why. I tried alternative NEXUS block specifications including the most obvious to me:

BEGIN ASSUMPTIONS;
      CHARSET Span1 = 1-501 2431-4379 6309-6784;
      CHARSET Span2 = 502-2430 4380-6308 6785-7042;
END;

 without success. I would much appreciate if you please help me on this. Perhaps you have an NEXUS format example for how to create a partition datafile that can be recognized with LHT.bf.

Thank you very much for your help.

Francisco

**Comment by spond** [comment]
Dear @HyPhyUser,

There is no problem with your file. `LHT.bf` appears to have a bug which prevents it from recognizing the partitions. I haven't cheked that LHT works in quite a number of years, but here's the fixed version of it which will detect partitions. You can simply open this file (LHT.txt) via the <kbd>File>Open>Open Batch File</kbd> menu.

Best,
Sergei

[LHT.txt](https://github.com/veg/hyphy/files/1219442/LHT.txt)

**Comment by HyPhyUser** [comment]
Dear Sergei, thank you a lot. Now it works perfectly.

Best,
Francisco
