### ISSUE TITLE
[RELAX] link to descriptive models missing

### ISSUE THREAD

**Issue by schraderL** [veg/hyphy#598]
Hi, 
browsing your tutorial on RELAX, I found this dead link:

> Enter 2 to execute only the Minimal analysis type. Note that entering 1 for All tests will additionally run additional descriptive models described [here](https://veg.github.io/hyphy-site/methods/selection/#relax).

Linking here: https://veg.github.io/hyphy-site/methods/selection/#relax

cheers,
lukas

**Comment by stevenweaver** [comment]
Dear Lukas,

Thanks for bringing this to our attention. The link has been updated.
