### ISSUE TITLE
RELAX fails in 2.3.1

### ISSUE THREAD

**Issue by sjspielman** [veg/hyphy#600]
There appears to be a syntax error:
```
 ~/hyphy/HYPHYMP LIBPATH=/home/sjspielman/hyphy/res/ /home/sjspielman/hyphy/res/TemplateBatchFiles/SelectionAnalyses/RELAX.bf
Error:
Too many closing ')' near '               relax.report_dnds)'.
Check errors.log for details on execution errors.

Check messages.log details of this run.
```

To avoid causing repo conflicts, I will let @spond address along with the other issues being currently addressed.

**Comment by spond** [comment]
Dear @sjspielman,

I can't replicate this with the current code in the `2.3.1-alpha` branch. Please confirm.

Best,
Sergei

**Comment by sjspielman** [comment]
Great, working now for me as well.
