### ISSUE TITLE
2.3.1 writes incorrect taxon names to JSON

### ISSUE THREAD

**Issue by sjspielman** [veg/hyphy#601]
New 2.3.1 edits change all outputted taxa to capital letters even when provided as lowercase. For example, for a tree
`(t1:0.1408208979,((((t4:0.09180754325,t9:0.07128012371):0.1313551269,(t10:0.4165821702,t7:0.04764077778):0.08831922431):0.6377018364,(t3:0.6987412621,t12:0.08350678342):0.04692053027):0.07418762848,(((t5:0.08652378838,t8:0.05359766493):0.103280468,t6:0.08857364883):0.250248048,(t2:0.074322189,t11:0.1835713):0.644012):0.4382723628):0.12478);`, 

we see this in the JSON output:
`(T1:0.140821,(((T4:0.0918075,T9:0.0712801)Node5:0.131355,(T10:0.416582,T7:0.0476408)Node8:0.0883192)Node4:0.637702,(T3:0.698741,T12:0.0835068)Node11:0.0469205)Node3:0.0741876,(((T5:0.0865238,T8:0.0535977)Node16:0.10328,T6:0.0885736)Node15:0.250248,(T2:0.0743222,T11:0.183571)Node20:0.644012)Node14:0.438272)"`.

The mapping similarly (BUSTED as an example):
```
     "T4":{
       "MG94xREV with separate rates for test/background branches":0.03623254412387657,
       "original name":"T4",
       "unconstrained":0.03621823411040697
      },
```
Note that the original name was lowercase "t4".

I think this is addressable without a specific case, but can provide as needed.

**Comment by spond** [comment]
Dear @sjspielman,

The idea is that you can always go back to original names via the `original names` attribute. HyPhy will internally convert taxon names to "valid" IDs (and that could include making them uppercase, since node-sequence mapping is not case sensitive).

Generally it is easier to do this reverse map in the Javascript code on viz.

Best,
Sergei

**Comment by stevenweaver** [comment]
According to the original file format specification:

>  Names that differ only in case (e.g., Beetles and beetles) should also be avoided, as they are considered homonyms.

**Comment by rdvelazquez** [comment]
Branch names now maintain their case when run with the develop branch (I checked BUSTED and SLAC).
