### ISSUE TITLE
simulating with HyPhy

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#610]
Dear team,

We are experimenting with HyPhy simulations. Specifically, we are interested in simulating from the RELAX model. You kindly provided us with the **relaxSim.bf** script (**is this the right file to look at???**) and we are examining it. We have a few questions:

1. We see that the simulation is based on the **SimulateDataSet** function, which relies on an existing file. Is it possible to replace this function with **Simulate**, in which we can control all simulation parameters ourselves?
We tried something like this but that **IS NOT** a valid definition of an alphabet:
`DataSet       sim           = Simulate (fullTree,codon3x4,GeneticCodeExclusions,num_codons,0);`

2. What were the lengths of the MSA datasets examined in the RELAX paper simulation study? We ask because, as a first stage, we'd like to reproduce the RELAX results in order to know we're on the right track. If indeed the simulations there were done with SimulateDataSet, then based on the supp. material, it seems they were done on MSAs of length ~60K. Is that true??? Seems very very long...

Many thanks,
Keren and Eli

**Comment by stevenweaver** [comment]
I believe we answered these questions during your visit. Please reopen if that is not the case.
