### ISSUE TITLE
NeighborJoining.bf of 2.3.2 version produced inconsistent results when sequences contained ambiguity codes

### ISSUE THREAD

**Issue by philiptzou** [veg/hyphy#618]
As the title described. I found that 2.3.x version of hyphy generate inconsistent neighbor joining results than 2.2.x. Here is an example:

`1.fasta`:

```fasta
>A
ATGGGTGCGAGAGCGTCAGTATTAAGCGGGGGAAAATTAGATGCATGGGAAAAAATTCGGTTAAGGCCAGGAGGAAAGAAACAATATAAATTAAAACATATAGTATGGGCAAGCAGGGAATTAGAACGATTTGCAGTAAATCCTGGCCTGTTAGAAACAGC
>B
ATGGGTGCGAGAGCGTCAGTATTAAGCGGGGGAAAATTAGATGCATGGGAAAAAATTCGGTTAAGGCCAGGAGGAAAGAAACAATATAAATTAAAACATATAGTATGGGCAAGCAGGGAAYTAGAACGATTTGCAGTAAATCCTGGCCTGTTAGAAACAGC
>C
ATGGGTGCGAGAGCGTCGGTATTAAGYGGGGGAGAATTAGAYAGATGGGAAAAAATTCGGCTAAGGCCAGGRGGAAACAAAAGATATAAACTAAAACATATAGTATGGGCAAGCAGGGAGCTAGAAAGATTCGCCGTTAATCCTGGCCTGTTAGAAACATC
>D
ATGGGTGCGAGAGCGTCGGTATTAAGTGGGGGAGAATTAGATAGATGGGAAAAAATTCGGCTAAGGCCAGGGGGAAACAAAAGATATAAACTAAAACATATAGTATGGGCAAGCAGGGAGCTAGAAAGATTCGCCGTTAATCCTGGCCTGTTAGAAACATC
```

`2.fasta`:

```fasta
>A
ATGGGTGCGAGAGCGTCAGTATTAAGCGGGGGAAAATTAGATGCATGGGAAAAAATTCGGTTAAGGCCAGGAGGAAAGAAACAATATAAATTAAAACATATAGTATGGGCAAGCAGGGAATTAGAACGATTTGCAGTAAATCCTGGCCTGTTAGAAACAGC
>B
ATGGGTGCGAGAGCGTCAGTATTAAGCGGGGGAAAATTAGATGCATGGGAAAAAATTCGGTTAAGGCCAGGAGGAAAGAAACAATATAAATTAAAACATATAGTATGGGCAAGCAGGGAAYTAGAACGATTTGCAGTAAATCCTGGCCTGTTAGAAACAGC
```

Sequence A and B from `1.fasta` and `2.fasta` are correspondingly identical.

```bash
(echo 1; echo 1; echo 1.fasta; echo 1; echo 7; echo "n") | HYPHYMP LIBPATH=`pwd` TemplateBatchFiles/NeighborJoining.bf

...
((A:0.007158919561063079,B:-0.0008235212980496802):0.1022679832699841,C:-0.001284262282847129,D:0.01389019127958112)
```

However:

```bash
(echo 1; echo 1; echo 2.fasta; echo 1; echo 7; echo "n") | HYPHYMP LIBPATH=`pwd` TemplateBatchFiles/NeighborJoining.bf

...
(A:0,B:0)
```

It is obverse that `0.007158919561063079 + (-0.0008235212980496802) != 0`. The difference is too large that you can't blame the float precision.

I also found the problem is related with the ambiguity codes. If I replaced "Y" to "C" and "R" to "A":

```bash
(echo 1; echo 1; echo 1.fasta; echo 1; echo 7; echo "n") | HYPHYMP LIBPATH=`pwd` TemplateBatchFiles/NeighborJoining.bf

...
((A:0.0072531021884764,B:-0.0009184224474480928):0.1029414569223293,C:0.006004007803641992,D:0.0131965094928867)
...

(echo 1; echo 1; echo 2.fasta; echo 1; echo 7; echo "n") | HYPHYMP LIBPATH=`pwd` TemplateBatchFiles/NeighborJoining.bf

...
(A:0.00316904045098488,B:0.00316904045098488)
```
`0.0072531021884764 + (-0.0009184224474480928) = 0.0063346797410283075` and `0.00316904045098488 + 0.00316904045098488 = 0.00633808090196976`. There is still a tiny difference, however it might be the float precision and normally won't cause any trouble.

After downgrading to 2.2.7, the difference disappeared.

**Comment by spond** [comment]
Dear @philiptzou,

I presume in 2.2.x you got zero distances? 2.3.2, by default, will resolve differences in a data-decedent fashion. When you compare `Y` to `C` in between sequences 1 and 2, this is what happens (by default; you can override this behavior by modifying some source code).

1. HyPhy will compute the frequencies of all nucleotide characters at the site where the ambig is found, in your case, the site is 

```
T
Y
C
C
```

2. It will then rank the characters by frequencies, i.e. T, then C (more frequent).

3. It will resolve Y to the character that that is the most frequent at the site, in this case `C`

4. Therefore sequences A and B will be counted as having a single C,T difference

If you repeat the same steps with only A, and B, the site is now

```
T 
Y
```
which means that T is more frequent than C, so Y will be resolved to a T and the sequences will be considered as having zero differences.

Negative branch lengths come from non-additive distances.

Best,
Sergei

**Comment by philiptzou** [comment]
Sergei,

Thanks for explaining the internal mechanism. It is understandable that the new version of HyPhy chose the different statistical approach to solve the problem of ambiguity codes.

Best,
Philip
