### ISSUE TITLE
Why SLAC mean dN/dS result differs from manual calculation using the output table for all sites

### ISSUE THREAD

**Issue by Assonnati** [veg/hyphy#626]
Hi.

I have a question about what exactly the mean dN/dS reported on the SLAC result page means? How is it generated? 

I calculated by averaging all the sites in the output table but got a quite different dN/dS.

Thanks.

**Comment by spond** [comment]
Dear @Assonnati,

Please do no average dN/dS over sites! It is unlikely to result in an accurate estimate, considering that each dN/dS estimate has a very different variance (and thus relative importance). 

The mean dN/dS is estimated directly, by maximum likelihood, as a part of branch length fitting. It is essentially a gene-wide estimate from the MG94-type codon substitution model. 

Best,
Sergei

**Comment by Assonnati** [comment]
Dear Serigei,
Thank you very much! 
I also read the handbook and it helps a lot.
