### ISSUE TITLE
MEME crashing Hyphy

### ISSUE THREAD

**Issue by katebaumann** [veg/hyphy#641]
Hi,

I am trying to run a MEME to test for positive selection. Using this process (Analysis:Standard Analyses:PositiveSelection:QuickSelectionDetection.bf:MEME. However, after entering all of the details and a short period of time Hyphy crashes giving me the below error message. Any ideas about what is happening?

![screen shot 2017-09-21 at 9 18 53 am](https://user-images.githubusercontent.com/32147992/30672305-0d103bfc-9eaf-11e7-9850-4d5dea90de4e.png)

**Comment by spond** [comment]
Dear @katebaumann,

What is the last prompt you receive prior to the crash?

The GUI version of HyPhy (2.2.6) is no longer being developed, so you may also consider running your data through the most current version following the steps described [here](http://www.hyphy.org/tutorials/current-release-tutorial/#use-meme-to-find-sites-which-have-experienced-pervasive-diversifying-selection).

Best,
Sergei

**Comment by katebaumann** [comment]
Hey Sergei,


The last input before crashing is

N (do not save fit files for individual codons)
Do you have any ideas about what is happening?

I will also give it a go using the current version.


Cheers,

Kate

________________________________

**Comment by katebaumann** [comment]
I am still having trouble with the program crashing. I am not sure what is happening as it has worked for previous data sets. Do you have any idea where I should start looking for the problem?

________________________________

**Comment by spond** [comment]
Dear @katebaumann,

Does MEME crash on **all** datasets that you try, or just that specific one? 

Have you been able to try the 2.3.4 release of HyPhy?

If all else fails, I'll be happy to take a look if you send me the alignment in question directly (spond.at.temple.dot.edu).

Best,
Sergei
