### ISSUE TITLE
two and three taxon trees are not parsed properly

### ISSUE THREAD

**Issue by sjspielman** [veg/hyphy#643]
See attached example batchfile to reproduce, run with either dummy dataset.
[treeparsing.zip](https://github.com/veg/hyphy/files/1321543/treeparsing.zip)

An input tree of `(s1:0.1, s2:0.1);` gets parsed as:
```
{
 "0":{
   "name":"default",
   "filter-string":"",
   "tree":{
     "string":"(s2)",
     "string_with_lengths":"(s2:0.1)",
     "branch length":{
       "s2":0.1
      },
     "annotated_string":"(s2,s1);",
     "model_map":{
       "s2":""
      },
     "partitioned":{
       "s2":"leaf"
      },
     "model_list":{
      {""}
      }
    }
  }
}
```

An input tree of `((s1:0.1, s2:0.1):0.1, s3:0.1);` gets parsed as:

```
{
 "0":{
   "name":"default",
   "filter-string":"",
   "tree":{
     "string":"(s1,s2,s3)",
     "string_with_lengths":"(s1:0.1,s2:0.1,s3:0.1)",
     "branch length":{
       "s1":0.1,
       "s2":0.1,
       "s3":0.1
      },
     "annotated_string":"(s1,s2,s3);",
     "model_map":{
       "s1":"",
       "s2":"",
       "s3":""
      },
     "partitioned":{
       "s1":"leaf",
       "s2":"leaf",
       "s3":"leaf"
      },
     "model_list":{
      {""}
      }
    }
  }
}
```

Note, seems to be parsed correctly once we get to 4-taxon trees.

**Comment by spond** [comment]
Dear @sjspielman,

This is a question on automatic unrooting. The trees recorded in the output were the ones that HyPhy actually used to perform the analyses.

1. A two taxon tree gets converted to a "stump", where one of the sequences is the root

2. A tree-taxon tree that is rooted will be converted to a rake.

3. For N &geq; 4 rooted trees will continue to be unrooted.

One can setenv `ACCEPT_ROOT_TREE = 1` to override this behavior, but for reversible models this will introduce an unidentifiable branch length parameter. 

Best,
Sergei
