### ISSUE TITLE
GARD processor

### ISSUE THREAD

**Issue by leapicard** [veg/hyphy#646]
Hello HYPHY team,

I am trying to process results from GARD analyses using GARDprocessor.bf
However, I seem to have different results on datamonkey and using the batch file, though I am processing the same gene.

# **Batch file results:**

KH Testing partition 4
Drawing resampled likelihoods for segments 3 and 2(9999/0 done)0.06859999999999999

Breakpoint | LHS Raw p | LHS adjusted p | RHS Raw p | RHS adjusted p 
       517 |   0.00940 |        0.05640 |   0.07240 |        0.43440
      1541 |   0.02530 |        0.15180 |   0.11100 |        0.66600
      3789 |   0.06860 |        0.41160 |   0.01440 |        0.08640

At p = 0.009999999999999998 there are 0 significant breakpoints
At p = 0.05 there are 0 significant breakpoints
At p = 0.1 there are 0 significant breakpoints

Mean splits identify: 0.3907407407407408

# **Datamonkey results:**

Breakpoint ? | LHS p-value ? | RHS p-value? | Signficance?
-- | -- | -- | --
502 | 0.00060 | 0.60060 | N.S
2472 | 0.33360 | 0.00120 | N.S
4538 | 0.09900 | 0.00060 | *

At p = 0.01
    there are 0 breakpoints with significant topological incongruence 
At p = 0.05
    there are 0 breakpoints with significant topological incongruence 
At p = 0.1
    there are 1 breakpoints with significant topological incongruence 

I understand that Datamonkey results are not complete due to convergence not being reached, however none of the breakpoints identified are the same.
I used the same parameters, with an HKY85 model and homogeneous rate of variation.

Is it normal that the results are so different?

Best,
Lea Picard

**Comment by spond** [comment]
Dear @leapicard,

This level of discrepancy is abnormal. What were the AIC-c score improvements reported by the two analyses? 

Also, how divergent are the sequences ? E.g. how many variable sites are there between sites 1541 and 2472?

Finally, GARD should also report confidence intervals on the location breakpoints. Could you tell me what they were?

Best,
Sergei

**Comment by leapicard** [comment]
Dear @spond 
I ran the analysis again to make sure I hadn't made any mistakes, and the results are different again? The location of the breakpoint appear to be much more congruent this time though. However, I still get the difference in terms of significant results.

HYPHYMPI GARD:
GENERATION 52 with 5 breakpoints (~100% converged)
Breakpoints    c-AIC  Delta c-AIC [BP      1] [BP      2] [BP      3] [BP      4] [BP      5]
          0 38446.86
          1 38339.33      107.527        516 
          2 38230.83      108.502        516        3788 
          3 38156.68       74.146        516        2972        4601 
          4 38152.31        4.377        516        3020        3571        4601 
          5 38152.31        0.000        516        3020        3571        4601 
GA has considered        56/2659159588722384 (669 over all runs) unique models
Total run time           0 hrs 8 mins 46 seconds
Throughput                1.27 models/second
Allocated time remaining 999 hrs 51 mins 14 seconds (approx. 4578038.224334601 more models.)
Performing the final optimization...

GARD PROCESSOR ON PREVIOUS RESULTS:
KH Testing partition 5
Drawing resampled likelihoods for segments 4 and 3(9999/0 done)0.1498

Breakpoint | LHS Raw p | LHS adjusted p | RHS Raw p | RHS adjusted p 
       517 |   0.00140 |        0.01120 |   0.07430 |        0.59440
      3021 |   0.12860 |        1.00000 |   0.00010 |        0.00080
      3572 |   0.00020 |        0.00160 |   0.18670 |        1.00000
      4602 |   0.14980 |        1.00000 |   0.00010 |        0.00080

At p = 0.01 there are 0 significant breakpoints
At p = 0.05 there are 0 significant breakpoints
At p = 0.1 there are 0 significant breakpoints

Mean splits identify: 0.2294871794871795



GARD DATAMONKEY:
![capture du 2017-10-02 16-19-31](https://user-images.githubusercontent.com/9062007/31081867-8194fda0-a78d-11e7-9824-78326ed0ddbb.png)


I'm not sure about the amount of divergence in my alignment, I am attaching a snapshot of it so you can have a general idea.
![capture du 2017-10-02 16-22-49](https://user-images.githubusercontent.com/9062007/31082026-01da5f64-a78e-11e7-8eff-baccf6af1067.png)
Plus some stats:
Length: 4,818
Sequences: 22
Identical Sites: 2,641 (54.8%)
Pairwise % Identity: 91.3%
 
I'm not sure where I am supposed to find the confidence intervals?

Best,
Lea
