### ISSUE TITLE
Hyphy vision is not loading my file.

### ISSUE THREAD

**Issue by zhiyi1988** [veg/hyphy#649]
Thanks you guys for compiling Hyphy vision.  I am trying to visualize RELAX results but it seems that the web app is not loading my file.

Regards, Zhiyi

**Comment by stevenweaver** [comment]
Dear @zhiyi1988,

I'm sorry you've had issues with using hyphy-vision. May I ask which version of HyPhy you are using? The current app only works with 2.3.3. 

Best,
Steven

**Comment by zhiyi1988** [comment]
I see! Thank you Steven and I'm sorry that I didn't notice that my HyPhy may be outdated. It is the version 2.2.4, I should try the latest version and rerun it.

Regards,
Zhiyi

**Comment by zhiyi1988** [comment]
Dear @stevenweaver, 

Very sorry that I have to bother you again. I've tried to install HyPhy 2.3.3 on my computer which is still running under VISTA. As I'm not familiar with using code to install programs on computer, it is really difficult for me to understand the guidance describing how to configure using CMake and build a HyPhy executable. 

At the moment, it seems that the most convenient way for me to get the figure results of RELAX analyses is processing my data on the web. However, it seems that RELAX on web server is still under maintenance? Because it keeps showing "there was an error processing your job".

So I'm wondering if there is any other way to make the results of RELAX analyses into figures after analyzing the data on version 2.2.4.  

Best regards,
Zhiyi

**Comment by stevenweaver** [comment]
Dear @zhiyi1988. 

Apologies for the delay. We are currently working on a new version of the desktop, but it may not be available until later next year. A version of hyphy-vision that is compatible with 2.2.4 is hosted [here](http://datamonkey.org/hyphy-vision/0.2.3/)

Best,
Steven

**Comment by zhiyi1988** [comment]
Dear Steven,

Thank you very much!

Best regards,
Zhiyi
