### ISSUE TITLE
"something went wrong"

### ISSUE THREAD

**Issue by amoltej** [veg/hyphy#652]
Hi I have tried aBSREL, BUSTED and MEME and every time after uploading file I am getting this message.
Could you please help me what is the problem?
"Your analysis for 59ce1ea37c8dc6509e0d2154 had an error.  The error message can be found at http://test.datamonkey.org/meme/59ce1ea37c8dc6509e0d2154."
same reply coming for other analysis as well
Thanks

**Comment by amoltej** [comment]
Hi may I know if anyone is helping with the current issue?

**Comment by spond** [comment]
Dear @amoltej,

Someone will look into the issue today. 

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @amoltej,

There was an issue with our computing cluster's configurations after performing an update to several core packages. The issue has now been resolved. Please try again.

Best,
Steven
