### ISSUE TITLE
Optimization with fixed branch lengths

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#656]
Hey dear team,

Is it possible to conduct optimization on standard models while fixing the tree branch lengths using the existing wrapper functions?

My issue is that the model is defined within the optimization function (like in FitGTR, for example), and therefore, I'm not sure if or how I could constrain the time parameter of each branch before it is defined, that is, outside the function.

I saw that in the GTR model definition, for example, there is a reference to a function that could answer my needs:

```
models.generic.constrain_branch_length
```
However, I was not able to find it in model_functions.bf.

Thanks!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

The current implementation doesn't allow you to do this out of the box. The reason is that in order to constrain the branch length one has to enforce

`
BL (rate_and_other_parameters, length_parameter) := C
i.e.
length_parameter := inverse (BL) (rate_and_other_parameters, C)
`

and the inversion part can be tricky in general.

Best,
Sergei

**Comment by halabikeren** [comment]
Thank you for the reply! So, if I understand correctly, I could use your suggested solution from [here ](https://github.com/veg/hyphy/issues/611) and write it into my own wrapper functions (from libv3) and get what I need (optimization + fixed branch lengths). Would that be correct?

Thanks!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

Yes, something like that should work. Thankfully all the models in question have branch length expressions that are linear in the "time" parameter (e.g. `t` or `synRate`)

Best,
Sergei

**Comment by halabikeren** [comment]
Thank you!

Does this option apply to models with multiple local parameters? For example, in your MG-REV model, I see that you have two local parameters:

`{
 "non-synonymous rate":"beta",
 "synonymous rate":"alpha"
}
`

In this case, I attempted to apply two constraint:
One on `beta`, which is a combination containing the local parameter `alpha`
One on `alpha`, which is a combination containing the local parameter `beta`

for example:

`TBOSlYjJ.tree_id_0.S1.alpha=1/(0.07653926137190142*ZuJVdzHL.model_MGREV.theta_AC+0.09464712549730789*ZuJVdzHL.model_MGREV.theta_AG+0.1139848110131864*ZuJVdzHL.model_MGREV.theta_AT+0.3195834693584959*beta*ZuJVdzHL.model_MGREV.theta_AC+0.3379149563880396*beta*ZuJVdzHL.model_MGREV.theta_AG+0.4108334347550493*beta*ZuJVdzHL.model_MGREV.theta_AT+0.01780762583916289*ZuJVdzHL.model_MGREV.theta_CG+0.1676640396483337*ZuJVdzHL.model_MGREV.theta_CG*beta+0.1106347947788047*ZuJVdzHL.model_MGREV.theta_CT+0.1416958752584586*ZuJVdzHL.model_MGREV.theta_CT*beta+0.03195906440904225*ZuJVdzHL.model_MGREV.theta_GT+0.2060531241372031*ZuJVdzHL.model_MGREV.theta_GT*beta);
`

`TBOSlYjJ.tree_id_0.S2.beta=1/(0.07653926137190142*alpha*ZuJVdzHL.model_MGREV.theta_AC+0.09464712549730789*alpha*ZuJVdzHL.model_MGREV.theta_AG+0.1139848110131864*alpha*ZuJVdzHL.model_MGREV.theta_AT+0.3195834693584959*ZuJVdzHL.model_MGREV.theta_AC+0.3379149563880396*ZuJVdzHL.model_MGREV.theta_AG+0.4108334347550493*ZuJVdzHL.model_MGREV.theta_AT+0.01780762583916289*ZuJVdzHL.model_MGREV.theta_CG*alpha+0.1676640396483337*ZuJVdzHL.model_MGREV.theta_CG+0.1106347947788047*ZuJVdzHL.model_MGREV.theta_CT*alpha+0.1416958752584586*ZuJVdzHL.model_MGREV.theta_CT+0.03195906440904225*ZuJVdzHL.model_MGREV.theta_GT*alpha+0.2060531241372031*ZuJVdzHL.model_MGREV.theta_GT);
`

In this case, I received a preservation of the relative branch lengths, but not their absolute values:

Original tree: 
`((S1:1,S2:1)Node1:1,S3:1,S4:2);
`

Tree after MG-REV optimization: 
```
((S1:1.51282,S2:1.51282)Node1:1.51282,S3:1.51282,S4:3.02564);
```

This is not problematic in my case, Since I would like to add an additional global parameter to the model which would scale all the branches of the tree. In this case, should leave this setting as is, and use the run_options.proportional_branch_length_scaler, instead?

Thanks!
Keren
