### ISSUE TITLE
setting the same model with several trees

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#658]
Dear team,

We would like to fit the same RELAX model (alternative model) to several trees (based on generated stochastic mappings). That is, when the parameters of the model are optimized with respect to each tree, it is in effect the same parameters (same _**k**_ value across all trees).

If we understand correctly, the function DefineMixtureModel generates a model (we are not sure how since it does not seem to get a tree as an argument). **Could we somehow use this function to define a single model and associate it with several trees**?

If not, any other idea on how we can achieve our required goal? Perhaps even by defining several models but somehow **restricting their parameters to be joined**?

Many thanks,
Keren and Eli

**Comment by spond** [comment]
Dear @halabikeren,

`DefineMixtureModel` defines a **model instance** which can be used with one or more trees. In fact, this is exactly what can be done by modifying the call

```
relax.general_descriptive.fit =  estimators.FitLF (relax.filter_names,
                                    relax.trees,
                                    { "0" : {"DEFAULT" : "relax.ge"}},
                                    relax.final_partitioned_mg_results,
                                    relax.model_object_map,
                                    {
                                        terms.run_options.apply_user_constraints: "relax.init.k"
                                    });
```

In RELAX. All you would need to do is specify N filter names and N corresponding tree names as the first two arguments.

Or you can also go old school and use something like

```

my_model_description =  model.generic.DefineMixtureModel("relax.BS_REL.ModelDescription",
            "my_namespace", {
                "0": parameters.Quote(terms.local),
                "1": relax.codon_data_info[terms.code],
                "2": parameters.Quote (N) // the number of rate classes
            },
            list_of_filrers_to_get_frequencies_from,
            None);

UseModel (^(my_model_description[terms.id]));

Tree T1 = string;
Tree T2 = string;
...
Tree TN = string;

LikelihoodFunction L = (filter1, T1, filter2, T2...);

```

Best,
Sergei

**Comment by halabikeren** [comment]
Great, Thank you!
