### ISSUE TITLE
obtaining aBSREL branch length after LHC

### ISSUE THREAD

**Issue by geofrunz** [veg/hyphy#660]
Dear all, 
I'm trying to perform an analysis similar to Wertheim(2013). 
I've performed aBSREL analysis and LHC parameter sampling. Reading the post
"Interpreting the results from dNdSRateAnalysis.bf #288", I've understood that the .t column doesn't represent the branch length but it still not clear to me how to obtain the branch length (or directly the MRCA using the newly fitted branch lengths). 
Is there any available program or script that can do the job?
Any helps will be very much appreciated.
Many thanks and sorry for the naive question

Best regards,
Geofrunz

**Comment by spond** [comment]
Dear @geofrunz,

In reviewing issue #288, I realized that the script for processing these results was never posted. The attached post-processing script will take the `.fit` and the `.lhc` files and output N (N = number of samples) scaled trees to `stdout` together with the total tree length summary, .e.g

```
Total tree length

	Count    = 100
	Mean     = 13.34091335430907
	Median   = 13.31765168394796
	Variance = 0.6764333572166953
	Std.Dev  = 0.8224556870839275
	COV      = 0.06164912890452717
	Sum      = 1334.091335430907
	Sq. sum  = 17864.96381508265
	Skewness = 0.1861962045736023
	Kurtosis = 899135.8090405557
	Min      = 11.61740740854566
	2.5%     = 12.12801165601616
	97.5%    = 15.25367096297786
	Max      = 15.32711094255674
```

Best,
Sergei

[BranchSiteREL_bl.txt](https://github.com/veg/hyphy/files/1370002/BranchSiteREL_bl.txt)

**Comment by geofrunz** [comment]
Thank you very much!!!

Geofrunz
