### ISSUE TITLE
HYPHY; difficulty in positive selection detection of viral RNA genome

### ISSUE THREAD

**Issue by va89fa** [veg/hyphy#663]
Dear team,

I have decided to investigate positive selection site for a negative sense RNA genome virus. my input is multiple aligned sequences from clustal X software of which I have saved in nxs format. based on turorials I have performed the following steps: new analysis> nxs file> standard analysis> positive selection> quick selection detection> universal> new analysis> nxs file (as a data file)> custom model> tree file in a ph format... but here comes the error in two notes: 
1: build tree given tree from string tree string.
2: execute a file from file "qndhelper1.ibf" using basepath C:\program files (*86)\HyPhy 2.2.3\templatebatchfiles.

-what should I do now to continue?
-what should be a 6 character model designation for this analysis?
-am I doing the right appropriate steps and methods for selection detection of this virus?

Thanks !

**Comment by spond** [comment]
Dear @va89fa,

It looks like you may be having a common issue with sequence names (see https://github.com/veg/hyphy/issues/651)

For the six character model a good default is `012345` 

You may also want to consider running your data through Datamonkey -- our online tool for selection analyses. For example, this route will automatically correct sequence name issues.

Finally, consider using the latest HyPhy version (2.3.4) and  the updated selection analyses described in http://www.hyphy.org/tutorials/current-release-tutorial/

Best,
Sergei

**Comment by va89fa** [comment]
Dear Sergei,

thanks for your advice. I tried to use datamonkey, but my alignment is contained of 383 seqs of 15kb length which is too long for datamonkey.
then I decided to edit tree file as you decribed in #651. but I feel like I may disrupt the actual phylogenetic distances by manually editing the file; [e.g., deleting the first (((((((( ].

if it is possible do you have any other advice to edit my tree files?

Best, 
Vafa

**Comment by spond** [comment]
Dear @va89fa,

Could you paste in your Newick tree string here just to make sure that the problem is with sequence names?

Best,
Sergei

**Comment by va89fa** [comment]
Dear Sergei,

here is the Newick tree:

('JX193078.1':0.07604928001876135,((((((((('HQ008337.1':0.001449840409114668,'KT124545.1':0.0):0.0012423464799757214,'KT124544.1':0.000473):0.0012563035260003005,'HQ412767.1':0.0021154055077672192):0.0033707255695595286,'JF893453.1':0.006661139433024653):0.0033631708458356745,'DQ097393.1':0.010364550200684688):0.000544,'KF361507.1':0.009596039500768485):0.007609022893095925,((((('AB534205.1':0.000073,'AB524406.1':0.000058):0.000115,'JQ713944.1':0.000214):0.000147,'AB524405.1':0.000512):0.00946495134302798,('AY626268.1':0.011378711209305276,'AY626266.1':0.009001603402081776):0.000449):0.0010869713145146287,'AY626267.1':0.011351964716580454):0.004515458572402627):0.016429414484256173,((((((((('KT223819.1':0.000487,'KT223818.1':0.000040):0.003044522961964834,'KJ607171.1':0.0030437006561849214):0.0012506560271436352,'KM885161.1':0.0035923655786525544):0.0018038070636696305,'KM885162.1':0.0058494528689049955):0.00183227475874098,(((((('KM885152.1':0.000180,'KM885150.1':0.000215):0.002623447590826107,'KM885157.1':0.003464201970429566):0.0013136636035739626,'KM885159.1':0.0026603605101926677):0.0011367701890536179,'KM885168.1':0.004487057233461436):0.0012965731528826767,('KM885163.1':0.004345259590211859,'KJ499462.1':0.0031374559946684586):0.003121001236997492):0.000648,'KM885164.1':0.006692008212385305):0.000653):0.0018653037616788298,((('KM885158.1':0.000080,'KM885160.1':0.000183):0.000096,'KM885156.1':0.000167):0.004064631825419679,'KM885155.1':0.005024559336234097):0.004256477700015318):0.0019465813116497548,(('KM885154.1':0.0,'KM885153.1':-0.0):0.000576,'KM885151.1':0.000083):0.008949890366365666):0.004323528969778596,'JN688863.1':0.01415727964137707):0.02033637448063849,(('FJ794269.1':0.012786209779926973,'JN688865.1':0.013822136142923349):0.0016337932928916221,('JN688864.1':0.006875857294836713,'JN688862.1':0.007448676376962244):0.007468648741860789):0.019660890918198698):0.0042307930594733326):0.06613564049630942,'JQ013039.1':0.09879816824247671):0.10703523812791685,((((((((((('JX401405.1':0.004590833972713119,'KJ920203.1':0.003163087667114787):0.000524,'KM885166.1':0.00432431594699145):0.0018353928010078537,'KC894391.1':0.0061375751811329395):0.000878,'HM125898.1':0.005613081980714031):0.004034564698049957,'JN653339.1':0.009988825488864832):0.005948089052754233,((((('JX401403.1':0.007181777860149821,'HM063424.1':0.0069528560670688655):0.0021564625910504894,'KT186351.1':0.0069710142942109084):0.0011243840561193695,'HM063422.1':0.012329224759202732):0.0018656635701898103,'JX401404.1':0.01096134526051746):0.0034059879365573864,('JX193081.1':0.004161939533788531,'JX193077.1':0.0033938731775473704):0.013872236834451851):0.002448321285131753):0.016168826883325556,'AY562991.1':0.019071197160796007):0.009736366543150902,('GQ918280.1':0.038688302784977716,'DQ097394.1':0.024023015283597973):0.009813268831434512):0.0016609690370230183,(((((((('KM056356.1':0.000089,'KC906188.1':0.000043):0.000273,('JX443519.1':0.000340,'JX524203.1':0.000187):0.000057):0.000184,'KP001164.1':0.0010371429617409664):0.000349,('JX110635.1':0.0011240031804682317,'KR338979.1':0.0017931801538963966):0.000114):0.003391641370736674,(((((('AY935495.1':0.000131,'AY935496.1':0.000132):0.0018549697608411513,'AY935494.1':0.0017791343954529908):0.000239,(('AY935497.1':0.0015058262355668122,'AY935498.1':0.00239154192741762):0.000140,'AY935489.1':0.0038342187258101606):0.000126):0.000483,'AY935490.1':0.008083665879390214):0.0012838890551628741,'AY935491.1':0.002368179358233958):0.003902624640421716,('AY935493.1':0.0011393755561722844,'AY935492.1':0.0013682464826598021):0.006439437423926615):0.0032288897782598953):0.0020351742065839937,'JX193079.1':0.010519410212841161):0.011406850603868684,('AY935500.1':0.000606,'AY935499.2':0.0010419112198542966):0.03204398933879847):0.0065133277009721754,'AY225110.1':0.039806214279079453):0.007426846620242521):0.012198433003637703,((((('GQ288390.1':0.003797949851701939,'GQ288389.1':0.0021434241536552176):0.000446,'GQ288392.1':0.00282616839305048):0.000346,('GQ288379.1':0.0022389149713438103,'GQ288377.1':0.0025626761025401754):0.0017375556297260547):0.0043377653342258704,'GQ288380.1':0.005308119795535201):0.018530470339843667,('GQ288391.1':0.009056675497633627,'GQ288378.1':0.00642052516020032):0.01633510653893274):0.035011750613813335):0.012444677249670761,((((('FJ430160.1':0.001591651286035898,'FJ430159.1':0.001842621137079429):0.000091,'JF950509.1':0.0013618441084176979):0.000163,'EF201805.1':0.0011569167064964954):0.042283247509343126,((('KC920893.1':0.002036643353247789,'FJ436302.1':0.000934):0.000110,'FJ436306.1':0.0022035972655192614):0.000276,(((((('KP027404.1':0.000617,'KP027403.1':0.000437):0.000125,'FJ436304.1':0.000930):0.000038,'KC934169.1':0.000423):0.000049,(('HQ317394.1':0.000946,'KF915807.1':0.000174):0.000137,'FJ436305.1':0.000918):0.000067):0.000047,(('KC246549.1':0.000048,'JX677561.1':0.000347):0.000028,'KC934170.1':0.000367):0.000131):0.000055,'FJ436303.1':0.001319323465036304):0.000192):0.045316224124745653):0.014193203990378161,(((((('KM056353.1':0.0038733800774520006,'FJ986192.2':0.006879226864797307):0.007011921523230526,'HQ011508.1':0.022022515891677537):0.010931577204654076,'GU187941.1':0.014652475073383138):0.02273835923050078,('EU293914.1':0.007004786574750017,'AY741404.1':0.010243388581515946):0.012299944102767729):0.009593168073066212,('HQ266602.1':0.02669927522268821,'HQ266603.1':0.01379921572380928):0.06847915503462071):0.009242697702752913,(((('EU140955.1':0.014772265447438215,('HM357251.1':0.019912048934177994,('JX193083.1':0.023031332172822404,(((((((((((((((((('AY845400.2':0.0,'FJ938171.1':0.00991376040865699):0.0065211464394441445,'KJ019841.1':0.0):0.003878124335858393,'AF077761.1':0.0):0.0013851329146283493,'EU546165.2':0.0):0.000654,'Y18898.1':0.000299):0.000199,'KM885165.1':0.000272):0.000363,(('KM056357.1':0.000095,'KM056354.1':0.0011578031506594127):0.000139,'JF950510.1':0.000916):0.000147):0.000365,'JX193082.1':0.0023285581308806445):0.000290,'JF795531.1':0.0010598228719904896):0.000886,('KJ563940.1':0.0,'KJ563936.1':0.000811):0.000362):0.000047,'KJ563935.1':0.0):0.000149,'KJ563938.1':0.0):0.000055,'KJ563937.1':0.0):0.000181,'KJ563939.1':0.000054):0.000829,'JX193080.1':0.004985483643000561):0.0019433508051739786,((((('EU289029.1':0.0,'EU289028.1':0.000360):0.0010805055617289932,('KJ607167.1':0.000660,'KJ607168.1':0.000527):0.000240):0.000072,'AF375823.1':0.0010493229854356334):0.000155,'KM056358.1':0.000504):0.000467,('AF309418.1':0.0,'NC_002617.1':-0.0):0.0027707288087367348):0.003074180071678214):0.010137002268480987,((('KJ636208.1':0.0039437974140314695,'FJ939313.1':0.000747):0.000835,(('HQ902590.1':0.004379523718690517,'KT445901.1':0.000777):0.000190,(((('FJ386395.2':0.0022172377847587306,'FJ386392.2':0.000157):0.0015043237681277022,'FJ386393.2':0.0013378569652969796):0.000947,('FJ386394.2':0.001513662571949513,'DQ060053.1':0.000003):0.000112):0.000090,'FJ386396.5':0.0040147352356812395):0.000406):0.000162):0.003210298134099205,'GU978777.1':0.007051038057365789):0.006591357410957614):0.0019599039761181887,(('KM056355.1':0.0014281060753225249,'KJ670427.1':0.0013441979483972554):0.0015146154619564475,'KC987036.1':0.004585679551533694):0.01767561451460638):0.00888546900757644):0.0028011985483208865):0.007962362986310017):0.015256410842204013,('KM056351.1':0.036579188747817244,('KJ769262.1':0.01465201092476604,'JX316216.1':0.006731974745233354):0.03221915026143791):0.0020486665905252305):0.01564155156181645,'GQ994433.1':0.02948041850137089):0.02891918223963069,((((((((('KJ577136.1':0.003603433506142956,('HM117720.1':0.008621627762148169,'JX974435.1':0.01227903510175432):0.0018486173455190607):0.007553028812787449,('JQ247691.1':0.0068522391185153134,'AY562990.1':0.0068630943834944395):0.000855):0.0032302768061187644,'KJ123642.1':0.023254227483540786):0.004054199296007064,('KF767466.1':0.011917599537447626,'AY562987.1':0.005057360472640143):0.04295597657134691):0.0030789544321732087,('JQ217420.1':0.000090,('JQ217418.1':0.000269,'JQ217419.1':0.000135):0.000385):0.055063142224105174):0.0012734226497947351,((((('GQ288388.2':0.0011478364179353115,'GQ288381.2':0.000435):0.005367575697439401,('GQ288384.2':0.003093812037162494,'GQ288383.2':0.002529578968731486):0.002202550685691311):0.0016609424136614257,('GQ288385.2':0.010425798076109091,'GQ288382.2':0.004054775703738703):0.0038962700495493606):0.0022794538527028483,'GQ288386.2':0.018217609298678224):0.014150963743089547,(('AY562986.1':0.0019518310189994797,'EF065682.1':0.003537359706901912):0.0017930508251741226,'GQ288387.2':0.0029231166239714976):0.017765207206875657):0.02418918729692398):0.02538252682012313,(('FJ751919.1':0.000949,'FJ751918.1':0.000434):0.04058988367812536,'JX012096.2':0.02284853817033563):0.01700248298530809):0.0015504745009925977,'JX119193.1':0.10148685645695854):0.005995049831942281,((((((('AB853928.2':0.012045154440944084,'FJ766529.1':0.010124243140272044):0.0024515647888579163,'HQ839733.1':0.0228753686465171):0.014031825565405984,'KC853020.1':0.04326347543642012):0.002799242568084906,'AB853926.2':0.014522962703478554):0.0025396951535246078,'AY562988.1':0.022157768693296057):0.003143512278581397,((((('KC013040.1':0.018610231367489405,'KC013031.1':0.012615525810146407):0.01596737679594154,((('KJ808820.1':0.00170912798683091,'KJ607163.1':0.0033823082425119937):0.000557,('GQ338311.1':0.000446,'KJ607164.1':0.000344):0.0038584538675425053):0.000731,'FJ766528.1':0.0071838020222953995):0.02480659470311096):0.00649258488962812,(('FJ410145.1':0.0011184703527843014,'FJ410147.1':0.0010577391990246353):0.004777517731910409,'AJ880277.1':0.0023253552208063397):0.016521461080508743):0.0013640470803456782,(((((((((('JX486550.1':0.003790175066685151,'KM374059.1':0.00596920503394266):0.0039059239701134812,'JX486557.1':0.007481076716258597):0.002961668513472791,'HM063423.1':0.004353939365884017):0.006580870180913985,'HM063425.1':0.007767487257446239):0.0020191742654885993,((('JX486553.1':0.0016324852615260004,'JX486554.1':0.001867426475295602):0.010497088499614369,((('JX486555.1':0.000145,'JX486556.1':0.000052):0.005510606816536481,'KT163264.1':0.004524640694789683):0.000815,'FJ766526.1':0.005844081815125864):0.0024267301095538714):0.005887748526504326,(('FJ766530.1':0.0031008563028045067,'FJ766531.1':0.002652242034111425):0.000467,'FJ766527.1':0.0024442422715628036):0.010436033450453368):0.000116):0.000942,'JX486551.1':0.01563403567590605):0.000897,((((((('EF026583.2':0.000112,'EF026579.2':0.000151):0.000028,'JX901110.1':0.0):0.000576,'JX901109.1':0.000676):0.000424,'JX901111.1':0.000778):0.0013823371631884991,'JX901118.1':0.008882447964458594):0.000652,'JN986839.1':0.008991920273178963):0.001284136841214787,'JX901121.1':0.011925038876796207):0.002112640508085281):0.008997852040888281,(((((('JX486552.1':0.002535251742630926,'KJ782376.1':0.0036873339324411617):0.0012564050469396656,(('KJ607166.1':0.005665062133555798,'KJ607165.1':0.004835817821635801):0.000354,'JQ993431.1':0.002687142350396078):0.000723):0.000610,('KJ808819.1':0.003582851276697819,'KM374061.1':0.003704939633243188):0.0022765218105000647):0.0021947594419125813,'KP861633.1':0.006852213299327254):0.002045780662769933,(((((('KT163262.1':0.000315,'KT163261.1':0.000080):0.000207,'KM374060.1':0.000716):0.000268,'KT163263.1':0.000325):0.0018639194020998345,(('KM374056.1':0.004037322586988151,'JQ979176.1':0.0026528739290095802):0.000421,('KM374058.1':0.001716130206556137,'KM374057.1':0.000989):0.003574283272688807):0.000069):0.002649483021675698,('JX901123.1':0.0035726525859193395,'JX901122.1':0.0031358245305119522):0.000887):0.0012280339857200962,'JX901124.1':0.004595764876649023):0.000521):0.01800239038824601,'JX901120.1':0.017701508948725946):0.0025308505618115724):0.0074765270766166125,(('GQ429293.1':0.008122611437199502,'AY562989.1':0.015723517544059082):0.008477639198639954,(('KJ736742.1':0.008127446235377101,'GQ429292.1':0.007574222091135825):0.0024654481692101245,((('KC013035.1':0.002728852757032742,'KC013037.1':0.004026234195600938):0.005454235691094653,'KC013032.1':0.0021442696049379624):0.005164602562150786,(((('KC013034.1':0.001433114399781805,'KC013036.1':0.002664683312342182):0.000765,'KC013033.1':0.0020829365670729325):0.000225,'KC013038.1':0.0035203537899473293):0.0038155268513654517,'KC013039.1':0.00930836449056083):0.004138620844439081):0.006199023331158582):0.002648794254051366):0.0103246791501556):0.0064111936007987015,'JX518532.1':0.03792969203585375):0.005942297721448785):0.009435276892913423,(('JF827027.1':0.013168620230361819,'KJ920204.1':0.01156348735537964):0.010048377264432584,'JF827026.1':0.019677580880385015):0.03245610882463545):0.006517227938362945):0.012822258431301293,(((((((('JN682210.1':0.013748234766386865,'JN682211.1':0.014880314320914852):0.022473789267718702,((((((((('KM056346.1':0.000497,'KM056348.1':0.000821):0.000060,'KM056349.1':0.0011270555886651794):0.0010576656332372215,'KM056345.1':0.000956):0.000928,'KM056347.1':0.00136813438583176):0.000440,'KM056344.1':0.0015824905778417204):0.005516819252737554,'KP089979.1':0.009589023967961264):0.018061054868747168,'KM056352.1':0.02321147030946773):0.000795,'KM056350.1':0.02346566824084024):0.003801088582737187,'KF740478.1':0.00836984435084949):0.0072462940800672865):0.02371975687165644,(('GU585905.1':0.009308133580895404,'AY865652.1':0.012923351530008724):0.006667821939869008,('KJ577585.1':0.004064554524458394,'KF727980.1':0.007562820539052151):0.004386310736765613):0.026339914393640047):0.0016274530652400435,'KR072665.1':0.06043197290215726):0.005102820153480295,'JX393313.1':0.016202342035997703):0.0014107347923518424,((('KC551967.1':0.000849,'KC152049.1':0.000205):0.003259967852670375,'KC152048.1':0.003967816267265272):0.04469751633326913,('KR732614.1':0.009192452780139504,'JN800306.1':0.003323822372988538):0.042682507947478104):0.012787842329722509):0.000681,((('JF966385.1':0.04695625118918784,'KU058680.1':0.011640068188344323):0.008698249753924806,('JF966387.1':0.03724324117873048,'JX390609.1':0.03359633283334126):0.020349039281148246):0.0020222087737419136,('KT948996.1':0.04968000857394926,'JF966386.1':0.04568049899891352):0.009213354871594649):0.004249227086011002):0.005406802272858198,((((('KM670337.1':0.0016174485794605313,'KP776462.1':0.0013531302851619324):0.0019483503837116616,'HQ697254.1':0.000729):0.010076978273266484,(('JX854452.1':0.000690,'JX532092.1':0.00241045427288452):0.027250292421496746,'KT355595.1':0.026420746858418716):0.004458302984902745):0.02961286624089994,'AY562985.1':0.03373523299469715):0.0033728484185134786,((((('HQ697255.1':0.009350168598299378,'KR815908.1':0.015567399824733572):0.006599775562518373,'JX193074.1':0.019087145956289762):0.01975972896491849,'AB605247.1':0.03662343404065894):0.009613684254632826,'JN986837.1':0.022457613582336833):0.0017297597505873778,(((('JF343538.1':0.000328,'GQ338309.1':0.0026412633266392135):0.005424110889933076,'GQ338310.1':0.0045578909956354875):0.01749519037234596,'JN618348.1':0.0044691942409997645):0.0042973149331529195,((('AB853927.2':0.009157059065505006,'JX193075.1':0.01820324194445124):0.002216816778066264,'KJ782375.1':0.0055977243931619215):0.007068290571776188,((('KM408752.1':0.000388,'KJ607169.1':0.000204):0.000929,('KJ528559.1':0.0017443870537307846,'DQ659677.1':0.004278009237753824):0.000359):0.013028714176345864,((((((((((((((('KF935230.1':0.0013996949265680215,'JQ015295.1':0.0010406984542062187):0.0012632887331098354,'KJ567597.1':0.005640315828737805):0.000126,('KF306265.1':0.000296,'JQ015296.1':0.000099):0.000825):0.0016244466632568298,('KC542913.1':0.000833,'KC542912.1':0.0017397295973464162):0.0018915792479595151):0.001320971209220284,'JQ015297.1':0.004800200391425823):0.0025115538335072378,'KC542905.1':0.0024880918507996534):0.00224193565733774,(((('KC542911.1':0.002791878961149834,'KC542910.1':0.0017689223251362188):0.0021064386424051182,'KC542907.1':0.0028034160965756403):0.0010245002520061258,'KF771883.1':0.004473732662239636):0.0010133566718431974,'KC542906.1':0.003408762939498289):0.004512160771516359):0.00474800018585324,('KC542892.1':0.000266,'KC542893.1':0.000722):0.0013074627361185287):0.000401,('KP742770.1':0.00471082590416575,'KJ607170.1':0.007872869546467699):0.0022810961745218686):0.0018743213163919961,((((('KC542914.1':0.0013720067889328687,'KC542894.1':0.000606):0.004881130435909336,(((('KC542908.1':0.0031850835941427337,'JN400897.1':0.002705561628068794):0.0030273534582477757,'KC542899.1':0.000749):0.0022410168296634167,('KC542904.1':0.0011312667445701546,'KC542903.1':0.001706253312417451):0.00324329337621003):0.000301,'KC542896.1':0.0018847991596678616):0.0049057343318481125):0.000479,('KC542909.1':0.00879733704608896,'HM188399.1':0.005545920597968835):0.0033885024791801446):0.000212,'JN631747.1':0.005086169973085242):0.000108,'JN618349.1':0.003627712753742136):0.000359):0.001265437341803855,(('HQ317395.1':0.0028808157651122384,'JN400895.1':0.0020772002944208596):0.004618885035408565,'KJ600786.1':0.01009909413007255):0.003171705711112587):0.004125538546410299,((('JX193076.1':0.0136882656859894,'HQ717357.1':0.004018097445861747):0.009896007704822914,'DQ485231.1':0.005408032634784827):0.004155190096445632,'DQ486859.1':0.008712948713724147):0.000152):0.003966548901343562,'FJ754271.2':0.011343859089309741):0.000988,((('JF343539.1':0.000090,'DQ485230.1':0.004139393315438021):0.009125290450301384,'GU564399.1':0.005462123955477603):0.003356537096419609,'DQ485229.1':0.01263598421720711):0.000593):0.000145,('KM977903.1':0.005985217269948755,(('JN986838.1':0.015484753881003548,'DQ839397.1':0.017328939985770144):0.000780,('KP189357.1':0.020993541611556144,((('JF340367.1':0.000276,'GQ849007.1':0.0016359929975034804):0.0010562743963806864,'KC461214.1':0.00718048976578479):0.00201068861588563,(('EU167540.1':0.014816419482530634,'GQ994434.1':0.0201798835953181):0.0049592451142188,(('AF431744.3':0.006390802762305607,'NC_005036.1':0.006462665544590554):0.000112,((('FJ754272.2':0.0038661666878582576,'FJ754273.2':0.002756179619584675):0.000611,(('KM885167.1':0.000452,'FJ872531.1':0.000998):0.000088,'JN599167.1':0.0012308465009894297):0.0012606484280012402):0.000513,(((((('KC853019.1':0.001519604795987816,'GU143550.1':0.005769831025050876):0.001071548588412987,'JX519467.1':0.010573000309257664):0.000621,'KJ600785.1':0.006360211223819423):0.0072987838286313715,'KC542897.1':0.014926363681998164):0.000184,((('KC542901.1':0.0019000811229670954,'KC542900.1':0.000343):0.0027275906861238164,'JX867334.1':0.002706197035873947):0.005945748728519927,'KC542898.1':0.009735022390257668):0.006252856139660539):0.0012117020067999827,('KC542895.1':0.006266625131590677,('KC542902.1':0.013100342892180279,('JN653340.1':0.006422768085063025,'JN400896.1':0.0019336723958306452):0.000147):0.000040):0.000165):0.000372):0.000850):0.000430):0.000858):0.000333):0.000748):0.000771):0.000178):0.004015936697301113):0.00208533222819224):0.0048599198400192814):0.013668245087610002):0.0030088983312085184):0.008998946024416372):0.012105340294629794):0.009054927739577976):0.011671518154617685):0.013017248118946275):0.0064544912556484604):0.009110658747301525):0.03637727523691524);

**Comment by va89fa** [comment]
Dear Sergei, 

Here is Newick tree:

('JX193078.1':0.07604928001876135,((((((((('HQ008337.1':0.001449840409114668,'KT124545.1':0.0):0.0012423464799757214,'KT124544.1':0.000473):0.0012563035260003005

**Comment by va89fa** [comment]
Dear @spond,

could you give any advice how to edit the newick tree I pasted before manually, not disrupting seq distances?

Regards,
Vafa

**Comment by spond** [comment]
Dear @va89fa,

Here you go. In a suitable text editor, search for regular expression `\'([0-9A-Z]+)\.([0-9A-Z]+)\'` and replaced with `'\1_\2'`.

The result is attached. You also need to replace '.1' with '_1' within sequence names in the alignment file.

Best,
Sergei

[tree-edited.txt](https://github.com/veg/hyphy/files/1384918/tree-edited.txt)

**Comment by va89fa** [comment]
Dear @spond, 

I figured out how to search for regex as you advised, and appreciate tree file edition you made. 
but still HyPhy errors when loading the edited tree file, stating that sequence names should start with a number, letter or underscore, since the tree file contains parentheses at the starts...
what should be written instead?
is there any tool which could convert the newick treeI have, to a HyPhy adaptable format? since I feel I may miss something while manually editing.

Thanks for your precious time considering my problem.

Best, 
Vafa

**Comment by va89fa** [comment]
Dear @spond,

My question may be so simple, but I'd be thankful if you could guide me through analyzing my data in HyPhy.

regards,
Vafa

**Comment by va89fa** [comment]
my problem has been solved.
Thanks.

**Comment by spond** [comment]
Dear @va89fa,

Apologies -- I was away at an NIH study section and am just catching up with HyPhy issues. Were you able to edit the tree?

Best,
Sergei

**Comment by va89fa** [comment]
Dear @spond 

Finally based on template files, I found out that the text file I had pasted virus names and sequences before alignment had issues. so I changed it correctly and aligned the sequences using hyphy.
Thanks again for your precious time,

Regards, 
Vafa
