### ISSUE TITLE
Q computation using the wrapper function estimators.CreateLFObject

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#664]
Dear team,

We are converting a piece of code that defines a binary time reversible Markov model to use the wrapper function estimators.CreateLFObject (or in one of the functions it calls). As expected, we know how the branch t parameters are computed (to adjust for the rate). However, the object seems to return a Q matrix that we do not understand. Could you please help us clarify what this object means and how it is computed?

![image](https://user-images.githubusercontent.com/16238692/31384652-80dd6258-adc8-11e7-8ac4-3fb9a1dfd005.png)

Thank you very much,
Keren and Eli

**Comment by spond** [comment]
Dear @halabikeren,

The `trait_relax.train.model_Q` object should be an expression based matrix; what you see reported there its value computed at current `t` (whatever it may be). As is true for all rate matrices, diagonal entries are auto-populated (so you can ignore the zeros). You can pull out individual rate entries using `GetString`.

```

global rate = 2;
t = 0.1;

Q = {{*, rate*t}
     {rate*t,*}};


fprintf (stdout, Q, "\n");

GetString (rate_ij, Q, 0, 1);

fprintf (stdout, rate_ij, "\n");

```

Output

```
{
{-0.2, 0.2}
{0.2, -0.2}
}
rate*t

```

Best,
Sergei

**Comment by halabikeren** [comment]
Thank you for the clarification!

I'm having a difficulty understanding how Q is expected to look like in the case of having a local parameter t (that is, parameter that has a different value for each branch, therefore resulting in a different Q matrix computation for each branch). 

In the below case, the assigned 't' parameter in the evaluated matrix appears to belong to branch S4:

```
global trait_relax.trait.model.mu_01=1
Tree trait_relax.trait.tree_0=((S1:1,S2:1)Node1:1,S3:1,S4:2);

trait_relax.trait.model_Q: {
{0, 2}
{2, 0}
}

trait_relax.trait.user_model["Q"]: {
{"", "(trait_relax.trait.model.mu_01)*(t)"}
{"(trait_relax.trait.model.mu_01)*(t)", ""}
}
```

Is there a way to extract the global rate matrix (that is, the matrix that is consisted of global parameters only)?

Thanks!
Keren
