### ISSUE TITLE
Subsetting alignment for GARD analyses

### ISSUE THREAD

**Issue by mstagliamonte** [veg/hyphy#667]
Dear Authors,

I am using GARD to perform a recombination analysis on a SNP alignment. I run a few successful tests, and now I am trying to run the program on the full data set (170 sequences, ~ 50,000 sites). The algorithm has been running for over three weeks. I was wondering if there is a way I could subset the alignment to shorten the running times. Would either of the following strategies be correct?

1) Overlapping sliding windows, e.g., if the alignment length were 1,000 sites, I could run 1-500, 250-750, 500-1,000;
2) I could split the sequences, i.e. if I have samples from 3 geographical areas, I could run: a) Area 1 vs Area 2; b) Area 1 vs Area 3; c) Area 2 vs Area 3.

Would any of the above be a correct procedure, or would it have a negative impact on the results?

Thank you for your kind attention,
Max

**Comment by spond** [comment]
Dear @mstagliamonte,

1. Is GARD finding breakpoints? 
2. It is better to subset sequences, not sites. Option 2 is better.
3. You can send me the alignment and I can run it on our big cluster.

Best,
Sergei

**Comment by mstagliamonte** [comment]
Dear @spond ,

Thank you for your kind answer. I am checking with my university policies and PI for the opportunity to send you the data, that is very kind of you.
Right now I am in the process of adding a few new sequences, but when I run it on a small  subset (isolates), GARD did not find any breakpoints.

Regards,
Max

**Comment by stevenweaver** [comment]
Marking issue as resolved, please feel free to reopen if the action is considered premature.
