### ISSUE TITLE
From *.FUBAR.json to *.fubar.csv

### ISSUE THREAD

**Issue by hyphyInfant** [veg/hyphy#673]
Hello.

I am running FUBAR with the HyPhy version 2.3.4. Unlike the outputs from version 2.2.4, where 10 files are saved in the output path, only two files were saved. I am running quite a number of analyses and I wish to know if there is a way to easily extract the MLE estimates from the *.FUBAR.json file. These output used to be outputted in a separate *.fubar.csv file.

I have tried using the following approach but the square brackets contained in the *.FUBAR.json file made it fail.

```
		fscanf("seqs.nex.FUBAR.json", "Raw", fubarOut);
		fubOut = Eval(fubarOut);
                fprintf(stdout, "\n\n", fubOut);
```
Regards,
hyphyinfant.

**Comment by stevenweaver** [comment]
Dear @hyphyinfant, 

I created a new npm package just for you called hyphy-tools. 

Please install like so:
`npm install -g hyphy-tools`

Then use the following command:
`hyphy-mle-export -i <hyphy JSON results file> -o <output_file>`

Best,
Steven

**Comment by hyphyInfant** [comment]
Thanks Steven.

**Comment by stevenweaver** [comment]
You're welcome.
