### ISSUE TITLE
Consecutive calls to estimators.FitMGREV

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#674]
Dear team,

In the RELAX.bf code we saw that there are two consecutive calls to procedures that eventually call the "estimators.FitMGREV" procedure. To the best of our understanding, the first call is based on some initial values and the GTR estimates (relax.gtr_results), while the second call starts from the result of the first call and improves on that.

If this is indeed the case, it seems strange that two calls are required. Wouldn't it be possible to increase the number of iterations of the first call in order to improve its estimates?

```

namespace relax {
    scaler_prefix = "relax.scaler";
 \\ FIRST CALL - "estimators.FitMGREV" will be called inside this:
    doPartitionedMG ("relax", FALSE);
}


io.ReportProgressMessageMD ("RELAX", "codon-refit", "Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model");

\\ SECOND CALL:
relax.final_partitioned_mg_results = estimators.FitMGREV (relax.filter_names, relax.trees, relax.codon_data_info [terms.code], {
    terms.run_options.model_type: terms.local,
    terms.run_options.partitioned_omega: relax.selected_branches,
}, relax.partitioned_mg_results);


```

Many thanks,
Keren and Eli

**Comment by spond** [comment]
Dear @halabikeren,

These calls do slightly different things. The first one fits **only** dN/dS and tree scalers to the data, i.e. all branch lengths are held at constant (relative) values. The second one adjusts all the parameters given the current starting point. This is indeed an optimization on the same data with multiple calls, but these calls are structured to optimize parameters in blocks, which turns out to lead to faster overall performance. 

Hope that makes sense,
Sergei

**Comment by halabikeren** [comment]
Thank you, Sergei!

This indeed makes sense.

I'm having some difficulties understanding how the relative branch lengths are held as constants in the first optimization cycle. When I print out the likelihood function of the MG-REV model after the first optimization cycle, this is what I get:


```
[DEBUG] first MG-REV optimization - branch lengths should remain fixed

MG-REV LF after optimization: 

Log Likelihood = -1319.28505300199;
Shared Parameters:
zuhbRDUk.model_MGREV.omega_0=0.8684230350175446
zuhbRDUk.model_MGREV.omega_1=1
relax.scaler_0=4.192983489261875
zuhbRDUk.model_MGREV.theta_AC=0.3323526510145305=0.3323526510145305
zuhbRDUk.model_MGREV.theta_AG=1=1
zuhbRDUk.model_MGREV.theta_AT=0.0556329412037436=0.0556329412037436
zuhbRDUk.model_MGREV.theta_CG=0.2706764132636734=0.2706764132636734
zuhbRDUk.model_MGREV.theta_CT=0.4077849947492631=0.4077849947492631
zuhbRDUk.model_MGREV.theta_GT=0.206353078927681=0.206353078927681

Tree zuhbRDUk.tree_0=(((S1:0)internal:0,S2:0)Node1:0,S3:0,S4:0.0580221);

```

I see that the relative branch lengths were altered as a result of the optimization.

However, when I print out the tree instance, the branch lengths remain as they were before the optimization:


```
[DEBUG] making sure branch lengths remained fixed in the tree instance:

{
 "0":{
   ...
   "string_with_lengths":"(((S1:0.05)internal:0.05,S2:1)Node1:0.1,S3:0.1,S4:0.2)",
   ...
}
```

Here I see that the branch lengths at the end of the first optimization cycle were not updated in the tree instance used later. Is this what you referred to as holding the relative branch lengths constant? If the answer is yes, is there any way I could force the relative branch lengths to be constant during the optimization? I managed to do so when the model contained a single local parameter, but this model consists of two local parameters (alpha and beta).


Thanks!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

In the example above **relative** branch lengths are constant.

`string_with_lengths` is the **original** tree string, i.e. it will not change during code execution, and is meant to capture user-provided branch lengths.

For MG-REV branch length constraints are handled by the function `models.codon.MG_REV.set_branch_length` in `libv3/models/codons/MG_REV.bf`. If you supply `terms.model.branch_length_constrain` as the name of the constraint parameter (`terms.run_options.proportional_branch_length_scaler`), this should fix branch lengths at their current values. 

Best,
Sergei

**Comment by halabikeren** [comment]
Dear Sergei,

We might be missing something. We are not sure what you refer to when you write "relative". Our interpretation was that relations of lengths in the user-provided tree are held constant but that is not the result we see (as all branches have length 0 except one, which has a branch length of 0.058).

Thanks,
Keren and Eli
