### ISSUE TITLE
FUBAR Simulations.

### ISSUE THREAD

**Issue by hyphyInfant** [veg/hyphy#675]
Hello.

I tried running some simulations using FUBAR on the silverback cluster but sadly, the process failed to complete successfully. It always terminated before completing the second run. I was however able to run the simulations successfully on my computer. A zipped folder that contains example files related to the problem was attached. I will sincerely appreciate any help on how I may troubleshoot the problem.

Kindest regards,
hyphyinfant.

PS: I am aware that I could have set <`nceems = 4`> in line 28 of the attached <`a-fuba.bf`>. This however creates some bias with respect to my analysis.

[report.zip](https://github.com/veg/hyphy/files/1395712/report.zip)

**Comment by stevenweaver** [comment]
Dear @hyphyInfant , 

Is it possible to send the error message you are getting? 

Best,
Steven

**Comment by hyphyInfant** [comment]
Hello Steven.

Thanks for your swift response. I attached copies of the consequent log files.

Kindest regards,
hyphyinfant.
[errors.log](https://github.com/veg/hyphy/files/1395770/errors.log)
[messages.log](https://github.com/veg/hyphy/files/1395771/messages.log)
[a-fuba.out.txt](https://github.com/veg/hyphy/files/1395774/a-fuba.out.txt)

**Comment by stevenweaver** [comment]
Thank you @hyphyInfant, 

I am very aware of what the current issue is, please allow me to find a solution that will work well for you. 

Best,
Steven

**Comment by hyphyInfant** [comment]
Hello Steven.

Thank you. I will await your response.

Grateful,
hyphyinfant.

**Comment by stevenweaver** [comment]
Dear @hyphyInfant,

May I ask which version of HyPhy you are using on your local machine?

Best,
Steven

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am using HyPhy version 2.3.5 on my machine.

Kindest regards.

**Comment by hyphyInfant** [comment]
Dear Steven.

I am really sorry for the spams. I was using my broken phone earlier.

Kindest regards,
Hassan.

**Comment by hyphyInfant** [comment]
Hello Steven.

I hope that you have not ignored my issue.

Please, can you advise me on how I may ensure that a job on the silverback cluster runs with hyphy-2.2.1. Thank you in advance.

Kindest regards,
Hassan.

**Comment by spond** [comment]
Dear @hyphyInfant,

You code fails on replicate 3 on my local installation with version 2.3.6 because it generates the following options array for the third run of FUBAR

```
{
 "01":"Universal",
 "02":"1",
 "93":"/users/sergei/Downloads/report/46-seqs.nex",
 "94":"/users/sergei/Downloads/report/46-tree.II.tre",
 "95":"20",
 "96":"5",
 "97":"2e6",
 "98":"1e6",
 "99":"100",
 "100":"0.5"
}
```

Key "100" precedes key "93" lexicographically, so the analysis doesn't find the input file ("0.5"). Once you fix this, you should be able to run the script on silverback.

You can also change line 77 to 

```
  ExecuteAFile(HYPHY_LIB_DIRECTORY + "/TemplateBatchFiles/SelectionAnalyses/FUBAR.bf", fInput);
```

to avoid explicit path dependancies.

Best,
Sergei
