### ISSUE TITLE
Setting initial EFV parameters manually

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#690]
Hi dear team,

Is there a way to compute a likelihood function (without optimization) based on a model, while setting the frequencies of the initial states manually, rather than estimating them from the data? 

Thanks!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

`
LikelihoodFunction3 my_function = (data, tree, frequencies);
LFCompute (my_function,LF_START_COMPUTE);
LFCompute (my_function,value);
LFCompute (my_function,LF_DONE_COMPUTE);
`

Best,
Sergei
