### ISSUE TITLE
Segmentation fault when attempting to process a tree with an invalid file path with stdin redirecnt

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#692]
Hi dear team,

When attempting to process a tree while providing a file path that does not exist, a segmentation fault is received:

**Code:**

`
tree_path = <PATH THAT DOES NOT EXIST>;
utility.ToggleEnvVariable ("GLOBAL_FPRINTF_REDIRECT", "/dev/null");
ExecuteCommands('tree_' + i + ' = trees.LoadAnnotatedTopologyAndMap(False, name_mapping);', {"0": tree_path}); // need to read the annotated tree with no alignemnt :(
utility.ToggleEnvVariable ("GLOBAL_FPRINTF_REDIRECT", None);
`

**Outcome:**
```
Error:
...
Function call stack
1 : Read the following data from PROMPT_FOR_FILE :  REWIND THE FILERaw into treeString;
        Standard input redirect:
                Empty Associative List-------
2 : result=trees.ExtractTreeInfo(trees.GetTreeString(look_for_newick_tree))
        Standard input redirect:
                Empty Associative List-------
3 : tree_0=trees.LoadAnnotatedTopologyAndMap(False,name_mapping)
        Standard input redirect:
                Empty Associative List-------
4 : ExecuteCommands in string 'tree_'+i+' = trees.LoadAnnotatedTopologyAndMap(False, name_mapping);' using basepath .../. reading input from {"0":tree_path}
Check errors.log for details on execution errors.

Check messages.log details of this run.
Segmentation fault
```
-------

Thanks!
Keren

`

**Comment by spond** [comment]
Dear @halabikeren,

Segmentation faults following error messages are regrettable but at the moment they belong in the `won't fix` category. This has to do with difficulties of clearing out complex objects following an error condition. The revised version of HyPhy (3.0) will deal with them more systematically. 

Best,
Sergei
