### ISSUE TITLE
HyPhy data file tools problem

### ISSUE THREAD

**Issue by va89fa** [veg/hyphy#697]
Hello,

does hyphy perform multiple alignment analysis in order to get data file ready for further analysis?
I have conducted alignment in hyphy for a limited number of sequences as following: 
data file tool> seqalignmentnuc.bf> ...
yet when 15 kb sequences are to be aligned, the final total size reaches to 30 kb and alignment seems to be wrong. 
what could be done with hyphy to get a right multiple alignment?

regards,
Vafa

**Comment by spond** [comment]
Dear @va89fa,

HyPhy does not really perform MSA. The tools you found maps everything to a single reference, which works OK for some datasets (e.g. HIV-1 pol), but won't work for general divergent proteins. 

You should use any of the standard alignment programs such as `muscle`, `MAFFT`, `MSAProbs`, etc, align your data in protein space and then map them back onto nucleotides before performing further analyses.

Best,
Sergei

**Comment by va89fa** [comment]
Dear @spond

Thank you for the guidance and suggestions.

Best, 
Vafa
