### ISSUE TITLE
Selected sites in the aBSREL analysis?

### ISSUE THREAD

**Issue by photocyte** [veg/hyphy#707]
Hi there,

I've run the aBSREL analysis on one of my datasets using the new DataMonkey.org service, and the branch that I suspected was positively selected came up as such:

Name | B | LRT | Test p-value | Uncorrected p-value | ω distribution over sites (% of sites)
-- | -- | -- | -- | -- | --
Node16 | 0.1366 | 18.1248 | 0.0009 | 0 | ω1 =   0.00 (67%)
"" | "" | "" | ""| "" | ω2  =   4.52 (33%)

I am interested in which sites make up those 33% of sites that are reportedly positively selected.  Is there a way to export those sites for further analysis?  I poked around the results page, and the results.json, but nothing came up that looked like it might represent sites.  My apologies if this isn't the correct forum for this type of question (I wasn't able to find an alternative place to post this question).

All the best,
-Tim

**Comment by stevenweaver** [comment]
Dear Tim, 

According to @spond in #394

> You need to run MEME or FUBAR to detect sites under selection. You cannot detect both branches and sites with any degree of confidence. Please see my (recent talk)[http://bit.ly/pond-hutch-2015] where I try to explain why. 

The slideshow presentation is an excellent resource for understanding why and how HyPhy's models work. Take a look at slides titled "Which sites are under selection?" starting on slide 23.
