### ISSUE TITLE
Problems with running RELAX in datamonkey

### ISSUE THREAD

**Issue by WCTavares** [veg/hyphy#708]
Using Datamonkey online, I'm trying to test selection intensification in some branches with a large dataset of 217 sequences and in a smaller, partial dataset with 92 sequences. Both NEXUS input files are very similar, differing just in number of sequences, and in number of tips in the tree.
With the bigger dataset the test runs successfully. However, with the smaller one the analysis aborts within few seconds. 
This occurs independently of the chosen tested branches.

I'm using as testing branches: 
(Fukomys_da,Heteroceph)
 
(((((Callosperm,Marmota_hi),((Cynomys_le,Cynomys_lu),Ictidomys)),Urocitellus),((Tamias_can,((Tamias_cin,Tamias_dor),(Tamias_qua,(Tamias_ruf,Tamias_umb)))),(Tamias_sib,Tamias_str))),Sciurotami)) 

(Clyomys,Euryzygoma)

(((Ctenomys_l,Ctenomys_r),Ctenomys_s),((Octodon_de,Spalacopus),Tympanocto)))

Can anyone help me to identify the error? 

The used files are here: [testing DM.zip](https://github.com/veg/hyphy/files/1514586/testing.DM.zip)

**Comment by stevenweaver** [comment]
Dear @WCTavares, 

This error is the same as the one referenced in #703. When HyPhy 2.3.8 is released (which should be within the next week), the issue should be resolved on datamonkey as well. 

Best,
Steven

**Comment by WCTavares** [comment]
Dear @stevenweaver,
I thank you for your answer.
Best regards,
William Tavares

**Comment by stevenweaver** [comment]
You're welcome. I will close this issue once the change has been reflected in datamonkey. HyPhy 2.3.8 hasn't been officially released quite yet.

**Comment by stevenweaver** [comment]
datamonkey has been updated and is now using HyPhy 2.3.8.

**Comment by WCTavares** [comment]
Dear @stevenweaver ,
Thank you so much.
