### ISSUE TITLE
Problems during hyphy installation

### ISSUE THREAD

**Issue by jnarag** [veg/hyphy#712]
Dear Hyphy Team,

Sorry if this problem has been raised previously, but having tried different gcc compilers I am still running into the same error message. The issue seems to be the openmp cannot be found on my computer (MacPro, OS X El Capitan 10.11.16). After some research, I installed the llvm compiler, but that still doesn't help. I have pasted the error message below, and would be grateful for any help/instructions. 

In the CmakeLlists.txt, I also explicitly called the llvm compiler as follows:

cmake_minimum_required(VERSION 3.0.0)
set(CMAKE_C_COMPILER "/usr/local/opt/llvm/bin/clang")
set(CMAKE_CXX_COMPILER "/usr/local/opt/llvm/bin/clang++")
project(HyPhy)
cmake_policy(VERSION 3.0.0)
cmake_policy(SET CMP0026 OLD)

----ERROR MESSAGE----
hyphy jayna$ cmake ..
CMake Error: The source directory "/Users/jayna" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
ZOO-JAYNA02:hyphy jayna$ cmake .
CMake Deprecation Warning at CMakeLists.txt:6 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

Set compiler flags to -fsigned-char -O3 -msse3 
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Could NOT find Threads (missing: Threads_FOUND) 
-- Could NOT find MPI_C (missing: MPI_C_WORKS) 
-- Could NOT find MPI (missing: MPI_C_FOUND) (found version "3.1")
-- Configuring done
WARNING: Target "HYPHYMP" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "HYPHYOCL" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
-- Generating done
-- Build files have been written to: /Users/jayna/hyphy

----

**Comment by spond** [comment]
Dear @jnarag,

The messages you see are **warnings** not **errors**. `llvm` does not support OpenMP (which means the build you have will be single-threaded).  If you type `make MP`, you should be able to build HyPhy.

You can also specify C and C++ compilers on the command line before you invoke `CMake`, like so

```
$rm -rf CMakeFiles CMakeCache.lst
$ CC=/path/to/C/compiler CXX=/path/to/C++/compiler cmake ./
```

Best,
Sergei
