### ISSUE TITLE
Exchangeability rates in empirical.bf don't match what is in other packages

### ISSUE THREAD

**Issue by stevenweaver** [veg/hyphy#717]
The exchangeability rates in empirical.bf are a bit confusing to me because they seem like they are being scaled, and therefore do not match what is in other packages like RAxML or official documentation.

**Comment by sjspielman** [comment]
We use different AA ordering than in RAxML, so they will look different. Is that the issue you are perhaps noticing? Some of these matrices are scaled and some aren’t, but any implemented scaling won’t affect inference as they are rescaled before use, each time.

**Comment by stevenweaver** [comment]
I noticed the ordering was different. The numbers are clearly different, which makes it difficult to verify when cross-checking against other packages. The only reason this came up is because I'm adding more exchangeability rate matrices and I wanted to make sure that I'm following convention that is being set.

**Comment by sjspielman** [comment]
I see. Recently I have retrieved models from PAML, but some of the “older ones” (WAG, LG, JTT) had been on my computer for I while and I don’t recall how those might be scaled. However, I feel reasonably confident they are correct as we benchmarked against Rate4Site models and got the same results. All that said it would not be too hard to redo them all with the same scaling (if any) applied. Would you recommend that approach? Can’t hurt I figure?

**Comment by stevenweaver** [comment]
Unless there is a good reason not to, I think that would be the right approach. It would save development time in the future since someone new that looks at the exchangeability rates might feel compelled to track down how each one was scaled due to potential doubts about accuracy (whether it's a futile thing to do or not).

**Comment by sjspielman** [comment]
Ok great. I’ll do a full reorganization, code and location, of empirical.bf tomorrow.

**Comment by sjspielman** [comment]
Hey @stevenweaver, 

I just pushed updates, see PR #718. Can you have a look and see if it is less confusing now? Importantly, I ended up removing some models which I could not re-verify.  I have confirmed that all models work with this update, as well.

Also, would it be appropriate to place in the hyphy repo the raw PAML models and python script I used to format these models for HyPhy? Let me know what you think and I can add it in.

**Comment by stevenweaver** [comment]
Thanks Stephanie. I think this will help save a poor soul in the future. Having the python script committed *somewhere* would be a good idea, but committing the python script to the HyPhy package itself would mean indefinite support by the package.

I think we should keep scripts in HyPhy down to its core supported feature set.
