### ISSUE TITLE
ReadFromString(), ReadFromFile() convert species names when reading a nexsus format

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#725]
Hi Dear Team,

I've noticed that when reading data from a string / file in nexus format, the names of the species are converted to be with upper case:

For example, for following code:

```
fas_string = ">a1
A
>a2
C
>a3
A
>a4
A";
DataSet fas_dataset = ReadFromString(fas_string);

nex_string = "#NEXUS
begin data;
	dimensions ntax=4 nchar=1;
	format datatype=dna missing=? gap=-;
matrix
a1       
A
a2    
C
a3      
A
a4  
A
;
end;";
DataSet nex_dataset = ReadFromString(nex_string);


fprintf(stdout, "fas_dataset: ", fas_dataset, "\n"); // debug
fprintf(stdout, "nex_dataset: ", nex_dataset, "\n"); // debug
```

Yields:

```
fas_dataset: 4 species:{a1, a2, a3, a4};
Total Sites:1;
Distinct Sites:1
nex_dataset: 4 species:{A1, A2, A3, A4};
Total Sites:1;
Distinct Sites:1
```

This is also the case when reading the data from a file using `ReadFromFile()`

Is there any particular reason for that?

Thanks!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

Hmm, this seems to be a left-over from the time when I used to treat sequence names as case insensitive in HyPhy. This has now been relaxed (in versions 2.3.x), so I should modify the code to consistently treat sequence names regardless of the format. Filing as a bug to fix for the next release.

Best,
Sergei
