### ISSUE TITLE
Turn message.log off by default

### ISSUE THREAD

**Issue by stevenweaver** [veg/hyphy#727]
It may be advisable to have message.log files turned off by default; whenever you spawn MPI jobs on the cluster that run a while, you end up with megabytes of log files ••per node**.

**Comment by spond** [comment]
Dear @stevenweaver,

Yeah, it's a good idea. It used to be the default that only the master node would write `messages.log` for MPI processes. 

Do you think it is better to write something to system logs for critical diagnostics by default (many fewer lines than now) , and allow users to turn on warning logging via a command line option?

Best,
Sergei

**Comment by sjspielman** [comment]
Hi @spond and @stevenweaver, 

For what its worth, all my MPI jobs only ever produce a messages/errors.log from the master node. I've never encountered more than 1 log file, up to and including the version 2.3.8.

-Stephanie

**Comment by stevenweaver** [comment]
Dear @spond and @sjspielman,

🤔 Multiple messages.log files may have been addressed from the time I placed this issue in my notes. I was transcribing notes to Github from Jira and that particular issue may no longer be expressed. I would still not consider this issue "junk", however.

messages.log and errors.log still do write to the file system by default. Writing to syslog could be an option. Another convention is to write to a hidden directory directly under `$HOME`. For example, `$HOME/.hyphy`. 

The reasons why this is an issue is two-fold : 

1) A single place for logging means that you can set up `logrotate` to point to a single directory for clean up at regular intervals. 

2) One less item that users have to add to their .gitignore in their repos.

Incorporating log levels are definitely a good idea. Please allow me to think about UX from both the advanced and novice researcher's perspective, as well as the sysadmin's perspective, a little bit more before I make a recommendation. 

Best,
Steven
