### ISSUE TITLE
can I work with two species, one branch

### ISSUE THREAD

**Issue by gdczoller** [veg/hyphy#736]
I am rather new to selection detection approaches and wonder if it is possible to do that on two speces, i.e. one one branch alone. Or would I need a third species, some kind of outgroup? What would be the most appropriate method (MEME, FUBAR, aBSREL)?
Thanks for the help

**Comment by spond** [comment]
Dear @gdczoller,

While technically possible, you will have very little power to detect selection in this setting. You will have no power at all to investigate selection at individual sites (sample size of N = 1 branch), and limited power to inquire about individual genes (sample size ~ # sites * fraction of sites under selection, which is usually small). The only method you might be able to run in this context from what we have developed is BUSTED. 

Adding an outgroup does not offer a significant improvement; your sample size is inherently tied to how many sequences you are analyzing. 

You can take a look at the [Nielsen et al 2005](http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.0030170) study to see why these types of comparisons have very limited power. 

Best,
Sergei
