### ISSUE TITLE
what numbers to report in a publication 

### ISSUE THREAD

**Issue by gdczoller** [veg/hyphy#737]
I have now run my 8000+ genes through Hyphy (using BUSTED; thanks for pointing me in the right direction) and have found a number of instances with significant diversifying positive selection. Now I am not quite sure what value I should report in a paper. From the original publication on BUSTED I gather that the p-value and omega3 from the unconstrained model would be useful. Would it be useful to also report the proportion? And if there is no significant selection found, would I also report these numbers (in a supplement)? Many thanks for your help!

**Comment by spond** [comment]
Dear @gdczoller,

It really depends on what your findings and what the purpose of the test was. 

1. p-values will tell you which genes can be categorized as selected / not - selected (binary feature). If the p-value is < cutoff (e.g. 0.05), then the gene is (putatively) selected. You could also run some sort of an FDR procedure to control for multiple testing.  You should **not** interpret the finding that p-value for gene 1 is less than p-value for gene 2 as evidence that gene 1 is under "more" selection than gene 2. 

2.  Both &omega;<sub>3</sub> and p<sub>3</sub> indicate effect size: what is the strength of selection, and what proportion of the branch/site space is subject to it. But both of these values could have large inference errors associated with them, so also can't say that if &omega;<sub>3</sub> for gene 1 is > &omega;<sub>3</sub> for gene 2, then gene 1 is under stronger selection than gene 2. One way to see it is imagine that you have &omega;<sub>3</sub> = 10 for gene 1 and &omega;<sub>3</sub> = 5 for gene 2, but the confidence interval is +/- 5 for both of them, so the values are not significantly different. 

I would probably go with a summary of the &omega;<sub>3</sub> p<sub>3</sub> distribution, perhaps as a heat map, or a hex plot (http://www.meccanismocomplesso.org/en/hexagonal-binning/)

Best,
Sergei

**Comment by gdczoller** [comment]
Many thanks for the comment and suggestions! We are mostly interested to know which genes might have been/are under positive selection. So I will select the ones with p<0.05 (or maybe <0.01). I was also thinking about controlling FDR. 
One co-author is asking for dN/dS values for alle genes (one value per gene), but as far as I understand that is not available from the BUSTED analysis. I have seen people using the SLAC method  to get a mean dN/dS in combination with BUSTED results. Would that be appropriate? Somehow it seems not quite correct to report a mean dN/dS for a gene if only a small fraction (small p3) of the gene has an elevated dN/dS according to the BUSTED analysis. Thanks in advance for shedding some light on this!

**Comment by spond** [comment]
Dear @gdczoller,

BUSTED performs a single dN/dS rate fit (similar to SLAC) as a preliminary phase of the your analysis. It is reported to the screen, and also saved to the JSON file. I would use this value.

One the screen you will see  non-synonymous/synonymous rate ratio reported for each branch set (check the tutorial for [an example](http://hyphy.org/tutorials/current-release-tutorial/#use-busted-to-test-for-alignment-wide-episodic-diversifying-selection)) 


### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
* Log(L) = -5436.33, AIC-c = 10990.97 (59 estimated parameters)
* non-synonymous/synonymous rate ratio for *test* =   0.8430

### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
* Log(L) = -5436.21, AIC-c = 10990.74 (59 estimated parameters)
* non-synonymous/synonymous rate ratio for *test* =   0.8314

In the JSON file, what you need is stored here:

```
{
...
 "fits":{
   ...
   "MG94xREV with separate rates for branch sets":{
     "Log Likelihood":-3466.774243082393,
     "estimated parameters":31,
     "AIC-c":6933.548486164786,
     "Rate Distributions":{
       "non-synonymous/synonymous rate ratio for *test*":[
        [0.9879290798857115, 1]
        ]
      },
    }

```

So you would access it (having loaded the JSON into `busted_results`) as 

```

```
busted_results["Fits"]["MG94xREV with separate rates for branch sets"]["Rate Distributions"]["non-synonymous/synonymous rate ratio for *test*"][0]
```

Best,
Sergei
