### ISSUE TITLE
BUSTED branch selection on datamonkey.org

### ISSUE THREAD

**Issue by lplenderleith** [veg/hyphy#738]
Hello,

When I run BUSTED on the server and select branches using the gui tool, the branches I select do not match what is analysed, according to the log and the labelled tree on the results page. If all branches are selected it works as expected. However if only a subset are selected as foreground branches then this doesn't give a consistent result: often everything *except* the selection is used as foreground, sometimes the selection is used as foreground as expected, and occasionally all branches are used as foreground.
I have only noticed this since the new version of Datamonkey. Is there something obvious I might be doing wrong, or is it a problem with BUSTED?
This seems like a similar issue to #723 but I've opened this as a new issue since it concerns a different tool, and may have a different cause.

Thanks!

**Comment by stevenweaver** [comment]
Dear @lplenderleith, 

Thank you for bringing this to our attention. 

The order for the partition selection prompt became unintentionally dynamic in the latest version of the BUSTED batch file. We have made the appropriate update in the HyPhy batch language to always prompt in the same order. 

The issue should now be resolved.

Thanks again,
Steven
