### ISSUE TITLE
Problem running nonCodingSelection.bf

### ISSUE THREAD

**Issue by jpizzollo** [veg/hyphy#746]
Hello, 

I'm finding an error when I run nonCodingSelection.bf (https://github.com/ofedrigo/TestForPositiveSelection)

When I provide a path for my neutral proxy, an intronic alignment, I see the following message:

Loaded a 3 sequence alignment with 145 nucleotides from
/Users/Jay/Desktop/hytest/intron.afa
Error:
'.return 1;' contained syntax errors, possibly a missing semicolon. ''

Function call stack
1 : ExecuteCommands in string "#include \""+incFileName+"\";" using basepath /Users/Jay/Documents/Tools/TestForPositiveSelection-master/.

Check errors.log for details on execution errors.

Check messages.log details of this run.

The errors.log file reads:
	Error:Failed to make a valid selection in ChoiceList after 10 tries

Any help would be greatly appreciated!
Jay

**Comment by spond** [comment]
Dear @jpizzollo,

Please checkout the beta branch from the git repo. I just pushed a commit that fixes an old syntax error (that used to be ignored by earlier versions of HyPhy) in stale code. 

Best,
Sergei

**Comment by jpizzollo** [comment]
Works! Thanks Sergei!
