### ISSUE TITLE
MEME test results

### ISSUE THREAD

**Issue by zhivkoplias** [veg/hyphy#747]
I've been running HyPhy w/ MEME method, and at the end of the run it provided me with a row without any further details:

_### ** Found _4_ sites under episodic diversifying positive selection at p <= 0.1**

Check messages.log details of this run._

When I searched for "episodic" on the screen above, I've found this:

_### For partition 1 these sites are significant at p <=0.1

|   Codon    | Partition  |   alpha    |   beta+    |     p+     |    LRT     |Episodic selection detected?| # branches |
|:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|:--------------------------:|:----------:|
|    468     |     1      |    0.000   |    6.650   |    0.163   |    8.661   |      Yes, p =  0.0058      |     2      |_

How could I find the three others? Also is there a way to look at the sites under episodic positive selection at the specified threshold?

**Comment by spond** [comment]
Dear @zhivkoplias,

There should be three other sites displayed to the screen (as in http://hyphy.org/tutorials/current-release-tutorial/#use-meme-to-find-sites-which-have-experienced-pervasive-diversifying-selection). If you can't find them, then this could be indicative of a bug. 

However, the more flexible way to explore your data is to load the JSON file produced by MEME into http://vision.hyphy.org/meme

In particular you can adjust the p-value and export the results to machine readable tables (even though the JSON is as well).

Best,
Sergei

**Comment by zhivkoplias** [comment]
Thank you, Sergei.
