### ISSUE TITLE
Executing system calls via HBL script

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#751]
Dear HyPhy team,

I wish to monitor the memory uptake of my HBL script, via the script itself. For this purpose, I would like to execute system calls to linux free command from my script.

Is there any way I could do this?

I tried to use: `utility.ExecuteInGlobalNamespace("free -m | grep Mem | awk '{print $3}'");`, but it didn't work.

Thanks!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

You can't make system calls in HyPhy, sorry. You can always use the Linux `perf` command to capture process state, or run HyPhy through an instrumentation program that can capture memory allocations. 

Best,
Sergei
