### ISSUE TITLE
Output file for batch analysis is not being made

### ISSUE THREAD

**Issue by mshakya** [veg/hyphy#752]
Hi all, 

I am trying to use HyPhy in batch mode, which runs fine, but cant get it to produce the output file, everything seem to print on screen. I have setup the batch file, which looks like this:

```

fileToExecute = HYPHY_BASE_DIRECTORY + DIRECTORY_SEPARATOR + "BranchSiteREL.bf"; 

inputRedirect={};
inputRedirect["01"]="Universal";
inputRedirect["02"]="Yes";
inputRedirect["03"]="No";
inputRedirect["04"]="PSgenes/cds0_470_2689.cdn";
inputRedirect["05"]="t5_cds.fasttree";
inputRedirect["06"]="All";
inputRedirect["07"]="";
inputRedirect["08"]="hyphy/cds0_470_2689_BSrel.out";

ExecuteAFile (fileToExecute,inputRedirect);

```
I run HYPHYMP like:
```
HYPHYMP hyphy/cds0_470_2689_BSrel.bf
```
I am using `HYPHY 2.3.1020180206beta(MP) for Darwin on x86_64`.  I am fairly new to using HyPhy, so this could be some error at my end as well.

Thanks for the help.

**Comment by spond** [comment]
Dear @mshakya,

I am not entirely certain I understand what your issue is. HyPhy will typically print something (updates and analyses summary) to the screen, and something (detailed analysis results) to files. If you wish to capture the standard output to a file, you can always use the standard ` > file` redirect option.

A few other remarks.

1. BranshSiteREL.bf has been deprecated in fact of aBSREL. Please see http://hyphy.org/tutorials/current-release-tutorial/#use-absrel-to-find-lineages-which-have-experienced-episodic-diversifying-selection

2. You can now supply analysis options to to HyPhy on the command line, like so

```
HYPHYMP /path/to/analysis.bf "Universal" "Yes" "No" "PSgenes/cds0_470_2689.cdn" "t5_cds.fasttree" "All" "" "hyphy/cds0_470_2689_BSrel.out"
```

Best,
Sergei

**Comment by mshakya** [comment]
Hi Sergei, Thank you for the quick response. I wanted the detailed results in files, and from what i understood  `inputRedirect["08"]="hyphy/cds0_470_2689_BSrel.out";` would have done it, but there was no such file being created. 

I did not know about the new analysis option, I will try that and I think that should solve my issue. Also, in the command line option, since all the options are specified in the command line what is in the file `/path/to/analysis.bf`. Is it the`aBSREL.bf` files or `BUSTED.bf`, depending on the type of analysis a user want?

Thanks again.

**Comment by spond** [comment]
Dear @mshakya,

`aBSREL` and other recent analyses write out .JSON files in the same directory as the data files. 

>I did not know about the new analysis option, I will try that and I think that should solve my issue. Also, in the command line option, since all the options are specified in the command line what is in the file /path/to/analysis.bf. Is it theaBSREL.bf files or BUSTED.bf, depending on the type of analysis a user want?

`/path/to/analysis.bf` would be the relative or absolute path to the actual analysis you want to run. If you are running from the HyPhy source directory, that would be something like

```
$HYPHYMP res/TemplateBatchFiles/SelectionAnalyses/aBSREL.bf
```

If you ran 

```
make install
```

then the call would look like 

```
$HYPHYMP /usr/local/lib/hyphy/TemplateBatchFiles/SelectionAnalyses/aBSREL.bf 
```

Best,
Sergei

**Comment by mshakya** [comment]
Hi Sergei,

Thank you. I reran the analysis in batchmode as you suggested. I had to remove and rearrange few options, and it worked. Here is what i did from the `hyphy/res/TemplateBatchFiles/SelectionAnalyses` folder:
```
HYPHYMP aBSREL.bf "Universal" "/Projects/results/PSgenes/cds0_470_2689.cdn" "/Projects/results/t5_cds.fasttree" "All" "cds0_470_2689_BSrel.out"
```
However, there was no detailed output file named `cds0_470_2689_BSrel.out`. I also ran the interactive session with `HYPHYMP aBSREL.bf`, but it did not prompt me to enter output file. However, I do see a JSON file `cds0_470_2689.cdn.ABSREL.json`. I think this contains the detailed output. right?

Thanks again for the help.

**Comment by spond** [comment]
Dear @mshakya,

You are correct - the `cds0_470_2689.cdn.ABSREL.json` file contains the detailed output. For example you can view it with `hyphy-vision`. The contents should be fairly self-explanatory. 

Best,
Sergei

**Comment by sjspielman** [comment]
Hi @mshakya,

Note that there is also this documentation explaining JSON contents in detail: http://hyphy.org/resources/json-fields.pdf

Best,
Stephanie

**Comment by mshakya** [comment]
Thank you all.
