### ISSUE TITLE
Internal error in _LikelihoodFunction::ConjugateGradientDescent

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#754]
Dear HyPhy team,

I have a script calling the function Optimize() with a custom likelihood function. When I run the script, the call to Optimize() can have two outcomes:
1) The scripts gets stuck.
2) I receive an error of the form:

`
Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values ... does not match the last recorded LF maximum ...
`

I see this error is refered to in [issue 703](https://github.com/veg/hyphy/issues/703), but I don't know what causes it.

**Information:**
The script and elaboration on how I run it is provided by mail.
The issue occurs both in version 2.3.7 and in version 2.3.11.
When commenting out lines 321-324 in the sent script, the issue no longer occurs.

Thanks!
Keren

**Comment by halabikeren** [comment]
Dear Sergei,

Following your clarification on the cause in [issue 774](https://github.com/veg/hyphy/issues/774), I suspect there is a connection between these two issues.

The reason for this suspicion is that I saw some local `K` parameters in the likelihood function info, as can be seen in the last email I sent concerning this issue:

`tree_id_0.S1.K, tree_id_0.S2.K`

Your second suggestion in your response to  issue 774 corresponds to what I do in TraitRELAX: In my iterative optimization procedure of the alternative model, I repeatedly re-create the model (line 990 in my fork) by:
1) Declaring its parameters (lines 265-294 in my fork).
2) Updating their values according to the result of the previous iteration (line 297 in my fork).
3) Setting the constraints on the parameters (line 300 in my fork).

Since the call `parameters.SetStickBreakingDistribution` is also setting values to some of the model parameters (specifically, the omegas of the reference group and their weights), **additionaly** to the settings done in the iterative optimization procedure of TraitRELAX, could it maybe explain the source of the internal error?

However, I still don't understand where the local `K` parameters are coming from. Please note that in TraitRELAX, I set some constraints after calling `parameters.SetValues` (specifically, constraints that allow fixation of the branch lengths). Could this explain the source of these local parameters?

Many thanks!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

I am looking through your TraitRELAX code. Would you mind e-maling be a **small** test dataset with all the requisite parts?

Best,
Sergei

**Comment by halabikeren** [comment]
Dear Sergei,

An input example is provided by email. Following the arguments in the input.params file should reproduce the internal error. Printing out the variables of the likelihood function, should demonstrate the local `K` parameters that were added:

```
lf_info:
{
 "Categories":{

  },
 "Global Independent":{
  {"trait_relax.reference.omega1", "trait_relax.reference.omega2", "trait_relax.reference.omega3", "trait_relax.reference.bsrel_mixture_aux_0", "trait_relax.reference.bsrel_mixture_aux_1", "trait_relax.test.theta_AG", "trait_relax.test.theta_AC", "trait_relax.test.theta_AT", "trait_relax.test.theta_GT", "trait_relax.test.theta_CT", "trait_relax.test.theta_CG"}
  },
 "Local Independent":{
  {"lESODoJg.tree_id_2.S1.K", "lESODoJg.tree_id_1.S1.K", "lESODoJg.tree_id_2.S2.K", "lESODoJg.tree_id_1.S2.K", "lESODoJg.tree_id_2.Node1.K", "lESODoJg.tree_id_1.Node1.K"}
 ...

```

Many thanks!
Keren

**Comment by halabikeren** [comment]
Dear Sergei,

I believe I found the source of the issue. 

In line 491 in TraitRELAX.bf (my fork), I remove a constraint on the global variable `trait_relax.K`, which no longer exists, as TraitRELAX deletes the likelihood function (unlike RELAX):

```
trait_relax.null_model.fit = custom_functions.FitLF_FixedBLs (trait_relax.filter_names, trait_relax.trees, None, { "0" : parsimonious_model_map}, 
...
parameters.RemoveConstraint(model.generic.GetGlobalParameter (trait_relax.test , terms.trait_relax.k));
```

The first call creates the likelihood function for the fitting of the null model and then deletes the function once finished. The second call removes a constraint from a variable which was deleted along with the function. The removal of the constraint on a non-existing variable appears to create local `K` parameters. Commenting out this line results in the disappearance of these local parameters from the likelihood functions of the iterative alternative model fitting procedure. 

Thanks to your clarification regarding [issue 774](https://github.com/veg/hyphy/issues/774), the source of this issue has been found. So, I am closing the issue.

However, the [memory accumulation issue](https://github.com/veg/hyphy/issues/728) still remains an open issue in TraitRELAX.

Thanks!
Keren
