### ISSUE TITLE
Selecting branches for aBSREL

### ISSUE THREAD

**Issue by tomas-pluskal** [veg/hyphy#756]
Hi,

I am trying to run hyphy in command-line mode for performing aBSREL analysis. I want to supply my own phylogenetic tree, that is why I chose to use comman-line version instead of using datamonkey. Unfortunately, for some reason the HYPHYMP program fails to read the labels from my tree file and only gives me the 4 default options for branch selection:
````
####Choose the set of branches to test for selection

1. [**All**] Include all branches in the analysis
2. [**Internal**] Include all internal branches in the analysis
3. [**Leaves**] Include all leaf branches in the analysis
4. [**Unlabeled branches**] Set of 107 unlabeled branches
````

This is how my tree file looks like:
[newtree.txt](https://github.com/veg/hyphy/files/1732931/newtree.txt)

Any idea why this is happening? 

FYI, I am running this version:
HYPHY 2.3.1120180215beta(MP) for Darwin on x86_64

**Comment by stevenweaver** [comment]
Dear @tomas-pluskal, 

1) Datamonkey does permit the uploading of your own phylogenetic trees. Simply append the tree to the bottom of your FASTA file.

2) It does not look like your attached newick tree is tagged. Please tag your tree like so:

```
(((EELA:0.150276,CONGERA:0.213019):0.230956,(EELB:0.263487,CONGERB:0.202633):0.246917):0.094785,((CAVEFISH:0.451027,(GOLDFISH{Foreground}:0.340495,ZEBRAFISH{Foreground}:0.390163):0.220565):0.067778,((((((NSAM:0.008113,NARG:0.014065):0.052991,SPUN:0.061003,(SMIC:0.027806,SDIA:0.015298,SXAN:0.046873):0.046977):0.009822,(NAUR:0.081298,(SSPI:0.023876,STIE:0.013652):0.058179):0.091775):0.073346,(MVIO:0.012271,MBER:0.039798):0.178835):0.147992,((BFNKILLIFISH:0.317455,(ONIL:0.029217,XCAU:0.084388):0.201166):0.055908,THORNYHEAD:0.252481):0.061905):0.157214,LAMPFISH:0.717196,((SCABBARDA:0.189684,SCABBARDB:0.362015):0.282263,((VIPERFISH:0.318217,BLACKDRAGON:0.109912):0.123642,LOOSEJAW:0.3971):0.287152):0.140663):0.206729):0.222485,(COELACANTH:0.558103,((CLAWEDFROG:0.441842,SALAMANDER:0.299607):0.135307,((CHAMELEON:0.771665,((PIGEON:0.150909,CHICKEN:0.172733):0.082163,ZEBRAFINCH:0.099172):0.272338):0.014055,((BOVINE:0.167569,DOLPHIN:0.15745):0.104783,ELEPHANT:0.166557):0.367205):0.050892):0.114731):0.295021)
```

Notice 
```
GOLDFISH{Foreground}
```

Loading your tree into http://phylotree.hyphy.org/, selecting the branches, and clicking `Export` under the `Newick` link in the upper left hand corner can help facilitate the process. 

Best,
Steven

**Comment by tomas-pluskal** [comment]
Thanks a lot for the quick response!

1. Awesome! Might be worth mentioning in the Help? (https://www.datamonkey.org/help)
2. This is great, but not very obvious. The Help page actually seems to say very little about importing the trees or the tree file formats.

**Comment by stevenweaver** [comment]
Dear @tomas-pluskal, 

Yes, I'll keep this issue open until we place clearer documentation. 

Best,
Steven

@github, this issue blocks veg/datamonkey-js#109

**Comment by harturchin** [comment]
Hi Steven,

I'm having a similar issue but am using the data monkey not the command line. I am uploading a fasta alignment with a Newick string; the file uploads properly and the user tree is correctly displayed. I want to select a subset of branches as foreground for testing; I have tried using the cursor to point and click on individual branches; I have also tried using one of the presets in the dropdown menu (select all terminal nodes; select all internal nodes). But no matter what selection I make at that step in setting up the analysis, aBSREL always puts all branches in the foreground and tests them all.  In the .json output file under the branch attributes section each branch always reads "tested": true.

I saw the comment from Tomas above: do I need to use the phylotree tool to tag my input file with {Foreground} labels in the Newick string for each foreground branch? I can do that but didn't realize that was the way to correctly specify foreground branches (I thought the graphical tool on the data monkey was doing that when I clicked the individual branches, but maybe I misunderstood?).

Thanks!
Mike

**Comment by spond** [comment]
Dear @harturchin,

The behavior you describe indicates a bug in the web interface. You do not need to tag the tree a priori if using the graphical branch selector. @stevenweaver and @stephenshank, could you please work with @harturchin to confirm and resolve the issue.

Best,
Sergei

**Comment by harturchin** [comment]
Hi Steven,

Just a quick followup. I tried tagging my foreground branches using the phylotree tool, but I still get all branches classified as foreground (and all subject to testing) in aBSREL.  So maybe as Sergei suggested this is a bug in the web interface. Thanks so much for looking into that some time.

Mike

**Comment by stevenweaver** [comment]
Dear Mike, 

I began work on detecting and accepting previously tagged newick trees in datamonkey, but it is still in one of my development branches. That feature should be available in a future release to the site.

As far as the bug in the web interface goes, @stephenshank is currently working towards a solution. 

Best,
Steven
