### ISSUE TITLE
Adding a parameter to a mixture model

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#757]
Dear HyPhy team,

I have a model that consists of two model instances (as relax consists of two model instances: `relax.reference.bsrel`_model and `relax.test.bsrel_model`).

I wish to add to my model a parameter that does not belong to any of the model instances (unlike `relax.k `, which is associated with the model instance `relax.test.bsrel_model`). In such case, I have mo model to associate my parameter with, when using the function `model.generic.AddGlobal`.

Is there a better way to add the parameter to my model than simply declaring it without associating it to any model instance? If not, what is the risk of associating it randomly with one of the model instances, but using it via a custom likelihood function formula rather than using it in any constraints (like done with `relax.k`)?

Thank you!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

If you are adding parameters to a **model**, then you should associate it with that model instance, i.e. simply add them to the `(model[terms.parameters])[terms.global]` dictionary, as a `"Description" : "variable ID"` key pair.

If you are adding parameters that do not naturally belong to any particular model (generally you should be able avoid these situations), perhaps some cross-model constraints, then you are on your own when it comes to managing parameter mappings between models and automated bookkeeping. In other words, these parameters will be optimized, but not included in various dictionaries returned by `estimator` functions. 

Can you give me some context as to what the parameter in question is?

Best,
Sergei

**Comment by halabikeren** [comment]
Thank you for the quick response!

I wish to use a mixture model that consists of the test and reference model instances of the RELAX model.

I define parameter `trait_relax.p` as the proportion of codon position that correspond by the RELAX alternative model. Then `(1-trait_relax.p)`  is the proportion of  codon positions that correspond to the RELAX null model, or alternatively, only to the reference model instance.

I therefore define the parameter `trait_relax.p` as follows:

```
	terms.trait_relax.p = "trait dependent site proportion";
	terms.trait_relax.p_range    = {
			terms.lower_bound: "0",
			terms.upper_bound: "1"
		};

parameters.DeclareGlobalWithRanges (trait_dependent_site_proportion, 1, terms.trait_relax.p_range[terms.lower_bound], terms.trait_relax.p_range[terms.upper_bound]); 
```

Unlike the parameter `relax.K`, I don't add `trait_relax.p` to any model instance with a call to the function `model.generic.AddGlobal`. I simply include this parameter via a custom likelihood function formula. For example:

`"Log((1-trait_relax.p)*SITE_LIKELIHOOD[0]+trait_relax.p*SITE_LIKELIHOOD[1])"`

Where the first data set (that corresponds to `SITE_LIKELIHOOD[0]`) consists of a tree whose branches are only labeled as reference branches, and the second data set (that corresponds to `SITE_LIKELIHOOD[1]`) consists of a tree whose branches could be either labeled as reference branches or test branches.

I can extract the value assigned to `trait_relax.p` by simply accessing it's parameter before the deletion of the likelihood function, so I have no problem getting it's value. However, when I try to constrain it after setting it to be equal to 1, using:

`parameters.SetConstraint (trait_relax.p, terms.parameters.one, terms.global);`

It still appears to categorized as a global independent parameter, while it should be categorized as a global constrained parameter, as can be seen in the likelihood function information dictionary:

` "Global Independent":{
  {"trait_relax.p",...`

I therefore suspect that I am doing something wrong.

Thanks again!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

Change 

```
parameters.SetConstraint (trait_relax.p, terms.parameters.one, terms.global);
``` 

to 

```
parameters.SetConstraint ("trait_relax.p", terms.parameters.one, terms.global);
```

Yes, internally, HyPhy will always pick up these variables as estimable model parameters. It's just that they are not recorded in anything that `libv3` knows about and may not be handled correctly by various functions which expect semantically annotated variable declaration. It should not matter for most applications (e.g. if all you want is to estimate log likelihood), but it won't hurt you to add `trait_relax.p` as a global parameter to one (or both) of your models, via `model.generic.AddGlobal`.  

Best,
Sergei

**Comment by halabikeren** [comment]
Thank you, Sergei!

I added the parameter to both model instances, as suggested. I also changed the first argument to `parameters.SetConstraint,` but it seems that now the parameter is categorized as local constrained rather than global constrained:

` "Local Constrained":{
  {"vgwkuMPO.tree_id_0.S4.t", "vgwkuMPO.tree_id_0.S3.t", "vgwkuMPO.tree_id_0.Node1.t", "vgwkuMPO.tree_id_0.S2.t", "vgwkuMPO.tree_id_0.S1.t", 
`**`"trait_relax.p"`**`,... `

These are the settings of the parameter:

` terms.trait_relax.p_range    = {
			terms.lower_bound: "0",
			terms.upper_bound: "1"
		};	
parameters.DeclareGlobalWithRanges (trait_dependent_site_proportion, 1, terms.trait_relax.p_range[terms.lower_bound], terms.trait_relax.p_range[terms.upper_bound]); 
	model.generic.AddGlobal (trait_relax.reference, trait_dependent_site_proportion, terms.trait_relax.p); 
	model.generic.AddGlobal (trait_relax.test, trait_dependent_site_proportion, terms.trait_relax.p); 
	parameters.SetConstraint ("trait_relax.p", terms.parameters.one, terms.global);`

Is there anything wrong with the settings now?
I am using the parameter only via the custom likelihood function formula, as stated above. Please let me know if there is any additional information I should provide.

Thanks!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

Is `trait_dependent_site_proportion` set to `"trait_relax.p"`?

Best,
Sergei

**Comment by halabikeren** [comment]
Yes,

`trait_dependent_site_proportion = "trait_relax.p";`
Sorry, I forgot to include it in the above code.

However, I am unable to reproduce the issue after moving the code applying the constraint to be placed after the assignment of a value to the parameter.

Here is an example of the full information of the likelihood function after the fix:

```
 "Categories":{

  },
 "Global Independent":{
  {"trait_relax.reference.omega1", "trait_relax.reference.omega2", "trait_relax.reference.omega3", "trait_relax.reference.bsrel_mixture_aux_0", "trait_relax.reference.bsrel_mixture_aux_1", "trait_relax.test.theta_AT", "trait_relax.test.theta_AG", "trait_relax.test.theta_CG", "trait_relax.test.theta_AC", "trait_relax.test.theta_CT", "trait_relax.test.theta_GT"}
  },
 "Local Independent":{
  {"dJeKSJUf.tree_id_1.S1.K", "dJeKSJUf.tree_id_1.S2.K", "dJeKSJUf.tree_id_1.Node1.K"}
  },
 "Global Constrained":{
  {"trait_relax.p", "trait_relax.reference.theta_GT", "trait_relax.reference.theta_CT", "trait_relax.reference.theta_CG", "trait_relax.reference.theta_AT", "trait_relax.reference.theta_AG", "trait_relax.reference.theta_AC", "trait_relax.test.omega3", "trait_relax.test.omega2", "trait_relax.test.bsrel_mixture_aux_1", "trait_relax.test.omega1", "trait_relax.test.bsrel_mixture_aux_0"}
  },
 "Local Constrained":{
  {"dJeKSJUf.tree_id_0.S4.t", "dJeKSJUf.tree_id_0.S3.t", "dJeKSJUf.tree_id_0.Node1.t", "dJeKSJUf.tree_id_0.S2.t", "dJeKSJUf.tree_id_0.S1.t", "dJeKSJUf.tree_id_0.Node0.t", "dJeKSJUf.tree_id_1.S1.t", "dJeKSJUf.tree_id_1.S2.t", "dJeKSJUf.tree_id_1.Node1.t", "dJeKSJUf.tree_id_1.I1.t", "dJeKSJUf.tree_id_1.S3.t", "dJeKSJUf.tree_id_1.S4.t", "dJeKSJUf.tree_id_1.Node0.t"}
  },
 "Trees":{
  {"dJeKSJUf.tree_id_0", "dJeKSJUf.tree_id_1"}
  },
 "Models":{
  {"trait_relax.reference", "__MULTIPLE__"}
  },
 "Datafilters":{
  {"data_filter_0", "data_filter_1"}
  },
 "Base frequencies":{
  {"trait_relax.reference_pi", "trait_relax.test_pi"}
  },
 "Compute Template":"Log((1-trait_relax.p)*SITE_LIKELIHOOD[0]+trait_relax.p*SITE_LIKELIHOOD[1])"
}
```
Now `trait_relax.p` is categorized as a global constrained parameter, as it should.
This is the result of the same script in with the issue of having multiple local parameters K, one for each branch labeled as Test in the second input tree of the likelihood function, as discussed in issue [754 ](https://github.com/veg/hyphy/issues/754) (via mail).  That is why the local independent category contains multiple local parameters `K`.
Since this specific issue no longer occurs, I am closing the issue.

Thank you!
Keren
