### ISSUE TITLE
aBSREL find branches underselection outside selected foreground

### ISSUE THREAD

**Issue by J-Calvelo** [veg/hyphy#760]
Hello, sorry for the inconvenience. This is probably just my own ignorance.

I been running some analysis in aBSREL analysis in the web server have very similar results (some branches  under selection) regardless my selection of foreground branches, even when I don't select them. Am I failing to select foreground branches or I'm just confused with foreground/background branch selection in PAML?

Thanks for your time

**Comment by spond** [comment]
Dear @J-Calvelo,

aBSREL will run selection tests on all branches by default. Also, there is no concept of "background" branches for aBSREL, because each branch is allowed to evolve with its own selective regime. When you select a subset of branches to test, this simply limits which branches aBSREL will test.

Best,
Sergei

**Comment by J-Calvelo** [comment]
Thanks. But

**Comment by J-Calvelo** [comment]
Thanks spond, I wasn't sure. But should not it yield negative results if I deliberately exclude those branches?

**Comment by spond** [comment]
Dear @J-Calvelo,

There should be a "not tested" subset of branches if you didn't select them all. Note, that aBSREL will **always** look at every branch during the first phase of the analysis (model complexity), but only look at those you select during the second phase (testing for selection).

Best,
Sergei

**Comment by J-Calvelo** [comment]
I re-run the analysis and I can't find the not tested subset in the JSON or log files.
I'm going to try running HyPhy locally.

**Comment by spond** [comment]
Dear @J-Calvelo,

Could you provide a link to one of the datamonkey result pages where you selected only some branches for testing?

Best,
Sergei

**Comment by J-Calvelo** [comment]
Here
http://www.datamonkey.org/absrel/5a8c5cccb8e13442ca3a1935

**Comment by spond** [comment]
Dear @J-Calvelo,

It appears that Datamonkey currently ignores user selection and tests all branches. I confirmed this with a different dataset. This is a bug.

@stevenweaver and @stephenshank : please investigate and resolve.

Best,
Sergei

**Comment by J-Calvelo** [comment]
Ok. Thanks!
