### ISSUE TITLE
nwk file not recognized help 

### ISSUE THREAD

**Issue by ritasianga** [veg/hyphy#762]
Am unable to get hyphy read my tree files when I want to simulate sequences.
I am using the line of code below;

Tree	      givenTree = "0124.nwk";

and the error is;

Error:Node names should begin with a letter, a number, or an underscore, in the following string context 0124.<ERROR HERE>nwk

my file seems fine. As shown below

((seq_00006:0.08171000,(((((seq_00032:0.08668000,(seq_00011:0.08241000,(seq_00012:0.07014000,seq_00013:0.05874000):0.01813000):0.01432000):0.01866000,((seq_00014:0.06922000,seq_00015:0.08180000):0.02813000,(((seq_00033:0.08125000,(seq_00038:0.04313000,((seq_00040:0.03683000,(seq_00039:0.04096000,seq_00035:0.06110000):0.00589000):0.00228000,(seq_00036:0.01841000,seq_00037:0.02328000):0.03798000):0.01046000):0.02442000):0.00613000,seq_00034:0.06828000):0.01489000,(seq_00016:0.09412000,(((seq_00023:0.05784000,(seq_00021:0.05059000,seq_00022:0.05445000):0.00891000):0.00636000,((seq_00024:0.04738000,seq_00025:0.04544000):0.00647000,((seq_00026:0.03159000,(seq_00029:0.02812000,(seq_00028:0.03403000,seq_00027:0.03514000):0.00595000):0.03477000):0.01357000,(seq_00019:0.02386000,(seq_00018:0.03709000,seq_00020:0.02159000):0.00574000):0.05187000):0.00436000):0.00814000):0.02070000,(seq_00030:0.06533000,seq_00031:0.06004000):0.01292000):0.01572000):0.01209000):0.01327000):0.00879000):0.01114000,(seq_00008:0.07677000,seq_00009:0.07541000):0.03554000):0.00956000,(seq_00003:0.08977000,seq_00010:0.08383000):0.01327000):0.00845000,(seq_00007:0.07245000,(seq_00004:0.05586000,seq_00005:0.06197000):0.03363000):0.02100000,seq_00002:0.09531000):0.00798000):0.00998000,seq_00017:0.09588000);

your help will be appreciated thanks

**Comment by spond** [comment]
Dear @ritasianga,

With

```
Tree	givenTree = "0124.nwk";
```

you are asking HyPhy to treat "0124.nwk" as the Newick string.

Try

```
fscanf ("0124.nwk", "Tree", givenTree);
```

or 

```
fscanf ("0124.nwk", "String", newick_string);

Tree T = newick_string;
```

Best,
Sergei

**Comment by ritasianga** [comment]
fscanf("0124.nwk", "Tree", givenTree);
Tree   T=givenTree;


Tree simulatedTree= givenTree;

and everything worked perfectly fine.  The only difference is that givenTree does not come with the branch lengths  as 0124.nwk did which is still fine.

Thank you very much.
