### ISSUE TITLE
running same batch file for different many virus sequences.

### ISSUE THREAD

**Issue by ritasianga** [veg/hyphy#763]
I want to run 196 viruses each with its own sequence file  and its corresponding tree file  all at once (iteration ) using one batch file. I do not  want the code to ask me to insert the nucleotide sequence and tree as it does now but I want to write a for loop that will make it iterate for all 196 data files.

I added the following code to the batch file;

/*the b1.bf is a text file containing path directories of each  data set I want the code to process*/
/* what am doing: let hypy read the text with file directories, take each line(file directory) when the code requires an aligned sequence to be loaded, it
takes the path line been looked at then loads it up as the sequence file. then executes the remainning commands. Then it moves to the next line(being the next path line)*/

fscanf ("b1.bf", "Lines", _inDirectoryPaths) ;

fprintf(stdout, "[READ",columns (_inDirectoryPaths), "file path lines]\n");
inputRedirect= {};

for (_fileLine=0; _fileLine<columns (_inDirectoryPaths); _fileLine=_fileLine+1) {

     inputRedirect["01"]= _inDirectoryPaths[_fileLine];
     /*DataSet 		ds = ReadDataFile(PROMPT_FOR_FILE);*/
	
     fprintf			(stdout, "Read an alignment with ", ds.species, " sequences and ", ds.sites, " sites\n");
     

}

Am getting the following error:

Expression appears to be incomplete/syntax error. scope:1, parentheses depth:0, matrix scope:0.0

Operations MAccess is not implemented/defined for a number
Call stack.

1: inputRedirect["01"]=_inDirectorypaths[_fileLine].

Please help.

**Comment by spond** [comment]
Dear @ritasianga,

HyPhy batch language is case sensitive. You read in `_inDirectoryPaths` (notice the camel case) and then try to access `_inDirectorypaths`.

You can also pass arguments to HyPhy on command line in a shell script. Assuming you have a directory with files .fas and .nwk (for each input file, e.g. 0001.fas, 0001.nwk, ...) you could do something like this in bash, replacing /path/to with the appropriate paths

```
for FN in /Users/sergei/hyphy/tests/hbltests/data/*.fas; do dirn=(`dirname $FN`); fname=(`basename $FN`); fname="${fname%.*}"; /path/to/HYPHYMP /path/to/my.bf $dirn/${fname}.fas $dirn/${fname}.nwk; done;
```

Best,
Sergei

**Comment by ritasianga** [comment]
Hi Sergei,
Thank you very much. I used the method you stated and I am running into a problem.
what do I put in ReadDataFile(); so that hyphy reads $dirn/${fname}.fas.
I keep trying putting the full directory to where $dirn/${fname}.fas could be and nothing is running.
Thanks

**Comment by spond** [comment]
Dear @ritasianga,

```
DataSet ds = ReadDataFile (PROMPT_FOR_FILE);
```

Best,
Sergei

**Comment by ritasianga** [comment]
Oh wow that was the trick. Thanks alot

**Comment by ritasianga** [comment]
Hello,
Sorry but I have two more specific hyphy questions.
1) How can I save a DataSet variable containing sequences and not the filtered variable. With the filtered sequences, am unable to use them phyml hence I need to access the non filtered sequences. I ask cause when I save the dataset variable, all that is saved is information on the nodes.

2) I want for each file that runs in my batch file, Its content to be saved in its own specific output file. As at now, when I use "fprintf(file.fas, "\n", DataSet variable)" the results of all my files are concatenated in one output file. 

Thank you for your help.

**Comment by spond** [comment]
Dear @ritasianga,

I am sorry, I don't understand your question. In HyPhy, when you keep printing to the same file, the convention is to **append** to the file. You can override this behavior as follows

```

DataSet ds = ReadDataFile (...);
DataSetFilter f = CreateFilter (...);

DataSet ds2 = ReadDataFile (...);
DataSetFilter f2 = CreateFilter (...);

fprintf ("output.txt", f);
fprintf ("output.txt", f2); // append to end of file

fprintf ("output.txt", CLEAR_FILE, f2); // overwrite file contents

```

You need to specify different output files if you wish to write to different files.

Best,
Sergei

**Comment by ritasianga** [comment]
What I want doing is that for each sequence file, the simulated sequences must be saved. To mean if my folder has 200 fas files then I should have 200 output files when the looped batch file is done running. From your response does it mean I must fprintf 200 times? I thought I could use maybe files.fas to mean get the file name and create a new output using its name

**Comment by spond** [comment]
Dear @ritasianga,

If your batch file generates a single simulated file per run (i.e. you call it 200 times via a shell script), then all you need to do is either prompt for the file name to save to, or create it based on some rule. For example,

```
fprintf (PROMPT_FOR_FILE, datafilter); // to prompt

...

// to create output file as a function of input file

fscanf (PROMPT_FOR_FILE, "String", input_file);
output_file = LAST_FILE_PATH + ".simulated.fas";
fprintf (output_file, datafilter);

```

Best,
Sergei

**Comment by ritasianga** [comment]
Hello Sorry for the late reply thanks alot.
