### ISSUE TITLE
Using RELAX when selective regime changes

### ISSUE THREAD

**Issue by nsmat** [veg/hyphy#764]
Hi all,

I'm planning on using RELAX to investigate compare selection in endosymbionts with some free living relatives and had a question about the underlying model. My understanding is that RELAX chooses parameters $\omega_{b,c}^{k_b}$ for each branch and category, and a configuration that describes which branches at each site fall into each of the possible categories.

In the paper, most of the simulations and diagrams in the paper appear to assume that if a site is in a category in the background branches, it will remain in this category in the foreground branches. That is, if a site starts under purifying selection, it will remain under purifying selection, and similarly for positive selection. However, is it possible that RELAX chooses a best-fitting configuration that makes a site switch categories between foreground and background branches – from purifying to positive selection or vice versa – or is there some in built constraint that stops this happening?

My concern is that in the change from free-living to endosymbiosis, the change in selective regime would mean some genes previously under purifying selection would end up under positive selection. Is RELAX unusable in such a situation?

Thanks!

Nik

**Comment by spond** [comment]
Dear @nsmat,

RELAX is a **random effects** model, which means that a branch/site pair is never fixed to a particular category/&omega; value (that would be a **fixed** effects model), but is "a draw" (in the same sense as you draw from a deck of shuffled cards) from the alignment-wide &omega; distribution. The method marginalizes (sums over) all possible combinations draws, assuming that they are made independently of each other. 

Importantly, the &omega; parameters are **not** site/branch specific, but are inferred jointly from the entire dataset. 

There is no assumption that any particular site will be in any particular category. The closest analogy is that if you have 

| &omega; | weight |
| --- | --- | 
| 0.1 | 0.8|
| 0.6 | 0.15 |
|3 | 0.05|

then ~80% of the sites are in the &omega; = 0.1 category, ~15% -- in the &omega; = 0.6 category, and ~5% are in the &omega; = 3 category, but you don't know which ones. 

The traditional way to interpret membership in these models, is that there is each branch/site belongs to each category with some probability, that is informed by the data at the branch/site, and all other branch/site combinations. In some instances, most/all of the probability will be allocated to one category (e.g. invariable locations will gravitate towards low &omega;), while for other sites there may be some significant uncertainty (e.g. 60% &omega; = 0.6, 40% &omega; = 3).

In particular, RELAX can definitely handle the specific case of free-living to endosymbiosis switch.

Best,
Sergei

**Comment by nsmat** [comment]
Hi Sergei,

Thanks hugely for your response, it clarified things completely.

Cheers,
Nik
