### ISSUE TITLE
error processing GARD job on web (same problem as issue #726)

### ISSUE THREAD

**Issue by kmgibson** [veg/hyphy#765]
Dear @stevenweaver and @spond,

I am experiencing the same issue currently that geofrunz's problem was (located at https://github.com/veg/hyphy/issues/726) with the same error message ("We're sorry, there was an error processing your job."). I am submitting a dataset with 59 sequences with 99 sites. The Job Queue says my job is complete, but I do not get any results on the page where I submitted the dataset. It just perpetually stays in the "job is currently running" page.

I have retried running this dataset a few times, as well as redownloading the dataset and trying to run it again. Same problem each time. I am using the default parameters as well.

I was unsure whether I should submit a new issue or comment on the closed issue (#726). If you prefer, I can delete this issue and comment on the old one, so the same issue stays together.

Thanks in advance for any assistance or guidance you can provide.

Best,
Keylie

**Comment by stevenweaver** [comment]
Dear Keylie, 

We will work on being more informative about error output. I was able to look at the logs and identify your dataset. The error reported from HyPhy is the following :
 
```
../.hyphy/res/  /home/datamonkey/datamonkey-js-test/app/gard/../../.hyphy/res//TemplateBatchFiles/GARD.bf
Initialized GARD on 48 MPI nodes.
Population size is 94 models

Nucleotide file to screen: (`/home/datamonkey/datamonkey-js-test/app/gard/../../.hyphy/res//TemplateBatchFiles/`)
Please enter a 6 character model designation (e.g:010010 defines HKY85):

                        +----------------------+
                        |Rate variation options|
                        +----------------------+


        (1):[None] Homogeneous rates across sites (fastest)
        (2):[General Discrete] General discrete distribution on N-bins
        (3):[Beta-Gamma] Adaptively discretized gamma N-bins. Try is GDD doesn't converge well, or if you suspect a lot of rate classes and do not want to overparameterize the model

Please choose an option (or press q to cancel selection):
Save results to: (`/home/datamonkey/datamonkey-js-test/app/gard/../../.hyphy/res//TemplateBatchFiles/`) There are 111 potential breakpoints. Bit size of the sample is 7.
ERROR: Too few sites for c-AIC inference.
```

Forcing a minimum number of sites is necessary because you would not be able to infer a good tree otherwise. For example, imagine trying to build a tree on 500 sequences that only have 10 sites. GARD requires at least `p + 2` sites per partition, where `p` is the number of parameters (number of tree branches + global parameters). 

Best,
Steven

**Comment by kmgibson** [comment]
Dear @stevenweaver,

Thank you!
I appreciate you pulling this for me. I can definitely fix this and lengthen the sequences.

Best,
Keylie
