### ISSUE TITLE
HYPHY Error in Running batch file

### ISSUE THREAD

**Issue by DeepakSingla** [veg/hyphy#766]
I am newbie to HYPHY and trying to run HYPHY with my sequence. The software running fine on command line when when i am running for batch file, it give an error "Operation * with 2 arguments needs 2 arguments; 1 were supplied."  I did not find anywhere the solution of that.

My batch file is
inputRedirect = {};
inputRedirect["01"]="Universal"; // genetic code
inputRedirect["02"]="/media/genomics/DATA1/AnophelesProteome/Transcriptome/OG1_5_3520_aln.fasta"; // codon data
inputRedirect["03"]="/media/genomics/DATA1/AnophelesProteome/Transcriptome/PAML/test.tree"; // tree
inputRedirect["04"]="All"; // Test for selection on a branch
inputRedirect["05"]=""; // complete selection

ExecuteAFile ("/usr/local/lib/hyphy/TemplateBatchFiles/BUSTED-SRV.bf", inputRedirect);

**Comment by spond** [comment]
Dear @DeepakSingla,

`BUSTED-SRV.bf` is an experimental file that doesn't currently work. Use `/usr/local/lib/hyphy/TemplateBatchFiles/SelectionAnalyses/BUSTED.bf`, and update your analysis options as needed.

You can also test the options like so

```
$HYPHYMP /usr/local/lib/hyphy/TemplateBatchFiles/SelectionAnalyses/BUSTED.bf "Universal" "/media/genomics/DATA1/AnophelesProteome/Transcriptome/OG1_5_3520_aln.fasta" "/media/genomics/DATA1/AnophelesProteome/Transcriptome/PAML/test.tree" "All" ""
```

Best,
Sergei
