### ISSUE TITLE
data monkey ticket number

### ISSUE THREAD

**Issue by harturchin** [veg/hyphy#768]
Is the data monkey down? The web portal accepts new job submissions, but submitted jobs wait for a ticket number, and the job queue says it is empty. Thanks!
Mike

**Comment by harturchin** [comment]
After checking again, I see that the job queue now will display jobs; nine jobs started before 3:40 PDT today are running; five others (including two of mine) started at 4:29 PDT or later are queued but not running. So maybe there is a problem with the machine that runs the job queue? Thanks again for help.
Mike

**Comment by harturchin** [comment]
running now, not sure what happened. sorry for the trouble.
mike

**Comment by stevenweaver** [comment]
Dear Mike,

**Comment by harturchin** [comment]
Thanks Steven. Much appreciated!

**Comment by stevenweaver** [comment]
Latency issues should now be resolved on the job queue page. A new job progress page should be released within the next two months.
