### ISSUE TITLE
help with node numbering in aBSREL output

### ISSUE THREAD

**Issue by harturchin** [veg/hyphy#770]
This small aBSREL analysis runs correctly in the data monkey but I'm having troubling putting the output together. The main output from the data monkey (see the JPEG screen grab of the html output) shows four branches with high LRT values and low test p-values. I'm using the .json output to figure out which node number corresponds to which clade of species in the gene tree: Node10 is the lineage leading to (degu, long-tailed chinchilla); and Node31 is the lineage leading to (Chinese hamster, golden hamster), prairie vole).

In the .log output file I'm using the last table called "### Testing selected branches for selection" to summarize the lineages under positive selection. In that table I can find Node10 (and the two terminal branches under selection) but in that table there is no Node31. 

I'm interested in reporting some of the secondary response variables for each branch under selection (the omega2 value; the proportion of sites estimated to be under selection), and I can copy them over from the main html output page, but it would be reassuring to understand why some of those selected branches drop out of the last table in the .log file.

Thanks, and apologies for the flurry of issues.
Mike

[Zp2_Glires_aBSREL_json.txt](https://github.com/veg/hyphy/files/1820574/Zp2_Glires_aBSREL_json.txt)
[Zp2_Glires_aBSREL_log.txt](https://github.com/veg/hyphy/files/1820575/Zp2_Glires_aBSREL_log.txt)
![zp2_glires_absrel_out](https://user-images.githubusercontent.com/17728150/37540973-29ab1db2-2916-11e8-8709-773e7c97eab6.jpg)

**Comment by spond** [comment]
Dear @harturchin,

Perhaps the easiest way to map the names to node locations is to use the tree display. **Thick** branches are the ones that have significant p-values, and if you mouse over them you will see names displayed. 

The log.txt file is truncated (@stevenweaver, we should make sure we flush the buffers before returning .log files), and is missing a few lines at the end (including Node31).

You can also get &omega; values from the .JSON file (see http://hyphy.org/resources/json-fields.pdf) directly.

Best,
Sergei

**Comment by harturchin** [comment]
Thanks Sergei. Right I can get the values I want from the html output or the .json file, I just wanted to be able to keep a complete .log output file, but it seems to be truncated (some lines for some branches are missing from the end of the table. Thanks!

**Comment by harturchin** [comment]
Also I should say when I hover over the thick branches in the .html output file I get branch length values displayed (not node names). Is that maybe a browser-specific problem (I'm using Safari). Thanks again.
Mike

**Comment by spond** [comment]
Dear @harturchin,

Hmm, you should be seeing something like the following (with the node name and branch &omega; distribution). I took this screenshot in Safari just now.

Best,
Sergei

<img width="547" alt="screen shot 2018-03-17 at 3 58 45 pm" src="https://user-images.githubusercontent.com/1018513/37559413-2138cba2-29fc-11e8-8c51-276e66d101f3.png">

**Comment by harturchin** [comment]
Hi Sergei,

Thanks to you or Steven or whoever worked on the aBSREL output formatting. The .log output file is no longer truncated, and now ends with the table summarizing the branches found to be under selection (example pasted below). Previously the .log output files were truncated: the last few lines of the table called 

### Testing selected branches for selection

were cut off, and the table of positive selection results was not included. So thanks so much for the fix!

Cheers,
Mike





### Adaptive branch site random effects likelihood test 
Likelihood ratio test for episodic diversifying positive selection at Holm-Bonferroni corrected _p =   0.0500_ found **14** branches under selection among **35** tested.

* BEAVER, p-value =  0.00000
* Node25, p-value =  0.00000
* GUINEA_PIG, p-value =  0.00000
* DEER_MOUSE, p-value =  0.00000
* Node9, p-value =  0.00000
* CHINESE_HAMSTER, p-value =  0.00003
* Node10, p-value =  0.00124
* Node5, p-value =  0.00120
* HOUSE_MOUSE, p-value =  0.00555
* PIKA, p-value =  0.00607
* Node4, p-value =  0.00612
* PRAIRIE_VOLE, p-value =  0.00593
* Node30, p-value =  0.00627
* RAT, p-value =  0.01053
