### ISSUE TITLE
RELAX - internal error in alternative model fitting when setting initial values manually

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#771]
Dear HyPhy team,

I am experiencing an internal error from the optimization of the alternative model in RELAX, when setting the initial values for the model manually.

The error is inconsistent (that is, not consistently reproducible in the general case of setting the initial values manually, but is consistently reproducible in the attached instance).

This is how I set the initial values manually: **before** creating the model, I set the values for the model (both test and reference instances), using the following syntax:

```
relax.initial_values = {
   "Mixture auxiliary weight for category 1":{
     "ID":"relax.reference.bsrel_mixture_aux_0",
     "MLE":0.5440556665187639
    },
    ....
  };

parameters.SetValues(relax.initial_values);
relax.test.bsrel_model =  model.generic.DefineMixtureModel("models.codon.BS_REL.ModelDescription",
        ...
```
Since I am setting these values before creating the model, the values assignments are not running over the constraints applied on the variables later on in the code.

An error I received, for example:
```
### Fitting the alternative model to test K != 1
Error:
Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-45271.6] does not match the last recorded LF maximum [-45269.3]

Function call stack
1 : Optimize storing into, mles, the following likelihood function:likelihoodFunction ; 
-------
2 : relax.alternative_model.fit=estimators.FitLF(relax.filter_names,relax.trees,{"0":relax.model_map},relax.general_descriptive.fit,relax.model_object_map,{terms.run_options.retain_lf_object:TRUE})
-------
```

**Please find attached:**

An altered RELAX script for example.
The terminal output of execution of the script.
The input used in the execution (sequence alignment, tree, and Test labels are "FG").

[k_0.5_replicate_1_aln_len_300.bf.txt](https://github.com/veg/hyphy/files/1822501/k_0.5_replicate_1_aln_len_300.bf.txt)
[7344902.OU.txt](https://github.com/veg/hyphy/files/1822502/7344902.OU.txt)
[simulated_dataset.k_0.5._replicate_1.nex.txt](https://github.com/veg/hyphy/files/1822503/simulated_dataset.k_0.5._replicate_1.nex.txt)
[labeled_tree.nwk.txt](https://github.com/veg/hyphy/files/1822500/labeled_tree.nwk.txt)

Please let me know if there is anything else I can provide.

Thanks!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

I believe this is the same issue as in issue #774.

Best,
Sergei
