### ISSUE TITLE
RELAX - alternative model fitting sensitivity to starting point 

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#772]
Dear HyPhy team,

I am experiencing a very odd issue with the log likelihood convergence when fitting the RELAX model given different stating points.

Please find attached the result of the following procedure:

1) I simulated 50 datasets with the same omegas (0.01,1,8) and the partitioning to foreground and background branches as the one from the RELAX paper. I simulated 5 different K values (0.2,0.5,1,2,5) - 10 replicates for each k. The alignment length in all cases was 1000 codons.

2) I then ran RELAX on the 50 datasets, given the branch partitioning as the true (simulated) one.

3) I then ran a subsequent execution of the same datasets, but this time set as the initial values the inferred model parameters from the executions in step 2.

Importantly, the inferences from step 3 were quite different than those in step 2. 
This is odd because:
(1) I expected the runs from the initial execution to reach a global maxima, which seems not to be the case.
(2) The differences in logLikelihood were very large (in the order of hundreds) so it seems not to be just trivial issues related to optimization convergence. The inferred k values were also very different between the two runs. 

I am attaching a summary of these results:  [comparsion_relax_different_starting_points.xlsx](https://github.com/veg/hyphy/files/1822665/comparsion_relax_different_starting_points.xlsx)

Please note that 14 out of the 50 executions failed due to internal error, as posted in [Github issue 771](https://github.com/veg/hyphy/issues/771). All these failures occurred only in the second execution and not in the initial one. 

It would be great if you could let me know the source of this behavior.

Please find below:

1) Simulated datasets for 3 examples (with 3 different simulated k):
[simulated_dataset.k_0.2._replicate_0.txt](https://github.com/veg/hyphy/files/1822668/simulated_dataset.k_0.2._replicate_0.txt)
[simulated_dataset.k_1._replicate_3.txt](https://github.com/veg/hyphy/files/1822667/simulated_dataset.k_1._replicate_3.txt)
[simulated_dataset.k_5._replicate_7.txt](https://github.com/veg/hyphy/files/1822666/simulated_dataset.k_5._replicate_7.txt)
2) Used partition:
[labeled_tree.nwk.txt](https://github.com/veg/hyphy/files/1822669/labeled_tree.nwk.txt)
3) Example of RELAX script used in step 3:
[k_5_replicate_7_aln_len_1000.bf.txt](https://github.com/veg/hyphy/files/1822670/k_5_replicate_7_aln_len_1000.bf.txt)

Many thanks!
Keren

**Comment by spond** [comment]
Dear Keren,

This is exactly the same problem as in Issue #774. By using `SetValues` prior to model declaration, you are creating unwanted local variables, and effectively a different model. 

Use

```
relax.alternative_model.fit =  estimators.FitLF (relax.filter_names, relax.trees, { "0" : relax.model_map}, 
                           relax.initial_values, 
                            relax.model_object_map, 
                            {terms.run_options.retain_lf_object: TRUE});
``` 

Best,
Sergei

**Comment by halabikeren** [comment]
Thank you, Sergei!

According to your explanation, I have re-run the procedure with a minor modification in the location of the call to `parameters.SetValues()` (corresponding to your second suggestion in [issue 774](https://github.com/veg/hyphy/issues/774)). This time, I simulated the alignments with more moderate omeges: 0.5,1,2. As before I made two rounds of inference (the second one being initialized with the optimized parameters of the first run).

All executions finished successfully, with no internal error. However, it appears that the likelihood of the alternative model didn't fully converge in the first run since the second run consistently received higher likelihoods  - occasionally by quite large values. Quite oddly, in all runs (except for those in the case of simulated k=0.2) the inferred values of `relax.K`are farther from the ones inferred in step 1. Note that these runs started with a better starting point compared to first run.  

You can find the results here: 
[comparsion_relax_vs_relax_with_initial_values_omegas_0.5_1_2_fixed.xlsx](https://github.com/veg/hyphy/files/1838725/comparsion_relax_vs_relax_with_initial_values_omegas_0.5_1_2_fixed.xlsx)

Thanks!
Keren
