### ISSUE TITLE
MEME - how to calculate Empirical Bayes Factor (EBF)

### ISSUE THREAD

**Issue by gubrins** [veg/hyphy#775]
Hello!

I am new using this method and I am looking for help:
I am looking for episodic positive selection in some related species. I already run my sequences with MEME and I already obtained the results, meaning that I know which sites are positively selected. The problem comes when I want to know which are the sequences that are being selected or if you prefer, the branches of my tree that are being selected. I have been reading several papers (e.g. Murrel et al., 2012; Tomasco et al., 2013) and they say that after MEME you have to calculate the Empirical Bayes Factor. In Murrel et al., (2012) mention that the Empirical Bayes used by Yang et al., (2000) can be adapted for it, but they don't say much more about it. I saw that Yang et al., (2000) used the software Paml, but I don't see how can we connect the results from MEME to Paml.
I am in a dead end right now and I don't know how to continue. 

Thank you very much,
Gabriel

**Comment by spond** [comment]
Dear @gubrins,

Firstly, we don't recommend over-interpreting EBF factors for selection, because it essentially amounts to trying to infer something when sample size is 1 (one site, one branch). 

The current implementation of MEME (http://hyphy.org/tutorials/current-release-tutorial/#use-meme-to-find-sites-which-have-experienced-pervasive-diversifying-selection) reports, for each site, the number of branches with EBF greater than 100 (in the summary output).

It **does not** report individual branches with EBF ≥ 100, but you can modify the code fairly easily to report the entire list of branches. If you are interested, I can post a version of MEME.bf that does that. Remember, **these values are only useful for data exploration**.

Best,
Sergei

**Comment by gubrins** [comment]
Dear Dr. Pond,

Thanks for your quick answer. I have been doing my analyses with the server Datamonkey, because I have a large amount of data and I was not able to analyze it in my computer. I was wondering if it would be possible to know which individual branches have an EBF value higher than 100 directly from the data received from the server. If that is not possible I would be very grateful if you post the version you told me and I would try to do the analyses in a more powerful computer.
Thank you for your time and for your useful advices.

Regards,
Gabriel

**Comment by spond** [comment]
Dear @stephenshank and @stevenweaver,
 
Could you please include the ability to view EBF on trees? I'll provide a modification to the MEME.bf file (will push to the beta branch) that stores this information as branch attributes. I'll post a note here when the file is ready, and provide some further details.

Best,
Sergei

**Comment by gubrins** [comment]
Dear Dr. Pond,

Thank you very much, I appreciate your time and effort.

Regards,
Gabriel

**Comment by gubrins** [comment]
Dear Dr. Pond,

I have checked your publication again (Murrell et al., 2012) and I realized that you included a plot with the EBF values per site on it (I attach the image). It was just to remind you to make things easier for you, because maybe you already had done it before.

Again, thank you very much.

Regards,
Gabriel
![image](https://user-images.githubusercontent.com/32134625/37778447-425431fe-2dea-11e8-9cac-a856671bac2e.png)

**Comment by spond** [comment]
Dear @gubrins,

The plot you attach is available on classic.datamonkey.org (the older version of Datamonkey).
The new version doesn't have that functionality in place yet.

Best,
Sergei

**Comment by spond** [comment]
Dear @stevenweaver and @stephenshank,

In 0d58770, I modified MEME.bf (and a few support files) to produce **branch annotations** in the JSON file for EBF values for all the branches that were in the `test` set, e.g.

```
 "branch attributes":{
   "0":{
...
"Node17":{
       "Nucleotide GTR":0.005138768443223628,
       "Global MG94xREV":0.005303735987214842,
       "EBF site 12 (partition 1)":1,
       "EBF site 15 (partition 1)":1,
       "EBF site 1 (partition 1)":1,
       "EBF site 13 (partition 1)":1,
       "EBF site 6 (partition 1)":1,
       "EBF site 20 (partition 1)":1,
       "EBF site 19 (partition 1)":1,
       "EBF site 31 (partition 1)":1,
       "EBF site 27 (partition 1)":1,
       "EBF site 24 (partition 1)":1,
       "EBF site 34 (partition 1)":1,
       "EBF site 30 (partition 1)":1,
       "EBF site 41 (partition 1)":1,
       "EBF site 36 (partition 1)":1,
       "EBF site 50 (partition 1)":1,
       "EBF site 39 (partition 1)":1,
       "EBF site 78 (partition 1)":1,
       "EBF site 196 (partition 1)":1,
       "EBF site 48 (partition 1)":1,
       "EBF site 54 (partition 1)":1,
       "EBF site 45 (partition 1)":0.8180846836512567,
       ...
       "EBF site 194 (partition 1)":1,
       "EBF site 195 (partition 1)":913.3276497674238
      },
```

The idea is to be able to color the tree based on branch attributes in hyphy vision, e.g. like is shown in the figure attached in a previous message.

Example JSON attached as well.
[partitioned.nex.MEME.json.txt](https://github.com/veg/hyphy/files/1838915/partitioned.nex.MEME.json.txt)



Best,
Sergei

**Comment by gubrins** [comment]
Dear Dr. Pond,

Thank you for modifying the file, it will be really useful for me. 
For the moment I have another doubt. I tried the classic datamonkey server that you sent me before but I obtained different results from the ones I obtained from the new server for the same method. Do you know why is this happening?

Thank you again,
Gabriel

**Comment by spond** [comment]
Dear @gubrins,

Did you use the same settings (model, tree, etc)? How different are the results?

Best,
Sergei

**Comment by gubrins** [comment]
Dear Dr. Pond,

The thing is that in the new server there is not option to change the model. In the classic one the analyses is based on a neighbour joining tree, while it is not said which tree is used in the new server, but don't worry, I will try to figure it out, you aready helped me a lot.

Regards,
Gabriel

**Comment by gubrins** [comment]
Dear @spond, 

I'm new with github and maybe I am doing something wrong. I downloaded the version you updated with the new features and I run an analyses, but in the MEME.json file I don't have the same output as you, I don't see the EBF values that you have. Do I have to do something special?

At the same time, I tried to coloured the output you send me with hyphy vision (partitioned.nex.MEME.json.txt) but I was not able to obtain the same trees as the ones I obtained with classic data monkey. 

Thank you for your attention,
Gabriel

**Comment by gubrins** [comment]
This is my output:

[lysin.fna.MEME.json.txt](https://github.com/veg/hyphy/files/1871556/lysin.fna.MEME.json.txt)

**Comment by spond** [comment]
Dear @gubrins,

In order for HYPHY to "pick up" the new version of analyses, one of two things have to happen

1). The analyses file have to be places in the standard install directory (/usr/local/lib/hyphy/... by default)

2). When you launch HyPhy, use `LIBPATH=/path/to/hyphy/lib` (this directory needs to be the one containing `TemplateBatchFiles`).

What is the command you use to run HyPhy? Where did you place the updated MEME.bf file?

Best,
Sergei

**Comment by gubrins** [comment]
Dear @spond,

Thanks for all your help. I thought once I downloaded the github with the new files I would already have them installed. I did the first thing you told me and now they are perfectly!!

Now my doubt (and I hope is the last one) is how to plot the EBF values in a tree, because in HyPhy vision is not possible, or at least I don't know how to do it. There is another software for that?

Thank you and good afternoon,
Gabriel

**Comment by spond** [comment]
Dear @gubrins,

Hang tight; I can write a simple plug in for vision.hyphy.org while @stephenshank updates the main visualization module.

Best,
Sergei

**Comment by gubrins** [comment]
Dear @spond ,

Thank you very much! I was just checking that there is also a github about HyPhy vision but it would be easier for me if you implement that change into vision.hyphy.org, because as you have seen this programming world is really new for me. 

Once again, thank you very much for all your help and for the program, 
Gabriel

**Comment by gubrins** [comment]
Dear @spond,

After checking the changes in the vision.hyphy.org web I realized that now I do have a plot with the number of branches selected by site but I can't know which branches are those. Will be possible to check this with the update you mentioned before?

Regards,
Gabriel
