### ISSUE TITLE
Non-Reversible Models parameters

### ISSUE THREAD

**Issue by ritasianga** [veg/hyphy#777]
Hello,
Am trying to simulate sequences using the non reversible models. As at now, my models work when I directly input what the global parameters are just before I define the rate matrix. when I set global parameters to 1 or global AC =; , I get a Rate matrix that is JC69.  How come am not getting a rate model that has 12 different or 11 different rates? The code is below. Thanks alot

DataSet   virus= ReadDataFile ("hivfull2.fas");

DataSetFilter    fvirus=CreateFilter(virus,1);

HarvestFrequencies (observFreqs,fvirus,1,1,1);

global AC =;
global AT =;
global CA =;
global CG =;
global CT =;
global GA =;
global GC =;
global GT =;
global TA =;
global TC =;
global TG =;

function PopulateModelMatrix(ModelMatrixName&){

	ModelMatrixName = 
	      {{*,t*AC,t,t*AT}
	       {t*CA,*,t*CG,t*CT}
	       {t*GA,t*GC,*,t*GT}
	       {t*TA,t*TC,t*TG,*}};

	return 0;

}

NREV12RMATRIX=0;
PopulateModelMatrix("NREV12RMATRIX");

Model 	NR12M = (NREV12RMATRIX, observFreqs,1);

ACCEPT_ROOTED_TREES=1;

fscanf ("hivfullrooted.nwk", "Tree", givenTree);

Tree T = givenTree;

LikelihoodFunction  theLnLik = (fvirus, givenTree);

simFreqs ={{0.3064,0.2075, 0.2409,0.2454}}; 

Model simNREV12 = (NREV12RMATRIX, simFreqs);

Tree simulatedTree= givenTree;

for (k= 1; k<=3; k= k+1)

{

	DataSet  sdata=SimulateDataSet(theLnLik);

	DataSetFilter   fsdata=  CreateFilter(sdata,1);

	HarvestFrequencies( simFreqs, fsdata,1,1,1);

	LikelihoodFunction  simLik=(fsdata, simulatedTree);

	DATA_FILE_PRINT_FORMAT= fas;
	fprintf (stdout ,"\n",NREV12RMATRIX);

}

**Comment by spond** [comment]
Dear @ritasianga,

Try the following (this has 11 global model parameters).

Best,
Sergei
[nrev.txt](https://github.com/veg/hyphy/files/1851994/nrev.txt)

**Comment by ritasianga** [comment]
Hello Sergei,

Thank you very much for the response. Adding the following global parameter definitions and also optimizing the likelihood function enabled me to get a rate matrix that looks like a NREV12 parameter matrix.
global AC = 0.25;
global AT = 0.25;
global CA = 0.25;
global CG = 0.25; 
global CT = 1;
global GA = 1;
global GC = 0.25;
global GT = 0.25;
global TA = 0.25;
global TC = 2;
global TG = 0.25;
I have the following  questions:
1) Why did we define the global parameters as above?
2) Mathematical what calculates these rates in hyphy.
3) Generally the rates do not seem like HIV rates  when i use HIV data and am concerned. Could it be the way am defining the model?

I hope my questions are not too much. Thanks alot

**Comment by spond** [comment]
Dear @ritasianga,

You declare the variables as global because that's what these rates are. The values I give here are entirely arbitrary. They are simply initial values which should in reality be optimized on real data. 

I have no idea what your question (3) means, sorry.

Best,
Sergei

**Comment by ritasianga** [comment]
Oh I see. So we just set arbitrary numbers that we expect to be optimized on real data. I thought based on the data hyphy calculates these rates on its own. Thanks alot.
Never mind the last question.

**Comment by ritasianga** [comment]
Is there a standard of measure on how these arbitrary rates are to be chosen? Cause I feel if its just too random, they might affect the ultimate optimized rates

**Comment by spond** [comment]
Dear @ritasianga,

Shouldn't matter too much. You can always start with a small perturbation of the HKY85 model with kappa ~ 4 (which is more or less what I put down in the example).

Best,
Sergei

**Comment by ritasianga** [comment]
Thanks alot for your help I totally get it. Just a quick one though, after I make a simulation, how can I have each simulation to be stored to its own file? for (k= 1; k<=3; k= k+1).

**Comment by spond** [comment]
Dear @ritasianga,

```

N = 100;
for (k=1; k <= N; k+=1) {
        DataSet  sdata=SimulateDataSet(theLnLik);
        DataSetFilter   fsdata=  CreateFilter(sdata,1);
        output_file_path = "/some/path/some-file_" + k + "_sim.dat";
        fprintf (output_file_path, CLEAR_FILE, fsdata);
}

```

Best,
Sergei

**Comment by ritasianga** [comment]
Thanks

**Comment by ritasianga** [comment]
Hello Sergei,

when I try to specify Gamma distribution during my simulation of sequences and also when I try to change the rates to suit certain conditions I get the error below. 


Internal error in ComputeBranchCache (branch givenTree.Node7 ) reversible model cached likelihood = -147477, directly computed likelihood = -147470. This is most likely because a non-reversible model was incorrectly auto-detected (or specified by the model file in environment variables).

I want to believe this means something is wrong with my rate values right?
I need help on what this really means and if when ever i see this error I should just play around with the rate values?
