### ISSUE TITLE
Type of files

### ISSUE THREAD

**Issue by gubrins** [veg/hyphy#778]
Hello,
I have just installed the command line version of hyphy and I was wondering which type of file I have to use for the alignments because I was using .fas but they don't work. 
I also want to carry an analyses with my own time tree and I don't know which is the best format to use it in order to keep all the evolutionary relationships between the different taxa. 

Thank you,
Gabriel

**Comment by spond** [comment]
Dear @gubrins,

FASTA files definitely work. Please review http://hyphy.org/tutorials/current-release-tutorial/#preparing-input-data-for-hyphy and http://classic.datamonkey.org/help/data.php

Newick format is what is expected for trees.

Best,
Sergei

**Comment by gubrins** [comment]
Dear @spond 

Thanks again for your information. For a MEME analyses, I run ``HYPHYMP``, I select Selection Analyses (1) and then MEME (1), the genetic code (2) and when I give the path of the file I want to analyze, I get this message error:

Error emptyString File Encountered By Read Dataset

Function call stack

1 : Read Data Set ^dataset_name from file PROMPT_FOR_FILE

2 : code_info=alignments.LoadGeneticCode(None)

3 : A return statement with:1

4 : A return statement with:1

5 : codon_data_info=alignments.PromptForGeneticCodeAndAlignment(prefix+".codon_data",prefix+".codon_filter")

6 : load_file("meme")

7 : Call a nested list (via namespace):
 

Step 0.LoadFunctionLibrary from file"modules/shared-load-file.bf" using basepath /home/gubrins/hyphy/res/TemplateBatchFiles/SelectionAnalyses/.

Step 1.load_file("meme")


Check errors.log for details on execution errors.

Check messages.log details of this run.

Maybe it's a stupid mistake but I am starting with this, thank you very much!

**Comment by gubrins** [comment]
And then content of the error.log is this:

Error:Could not find source dataset file "PROMPT_FOR_FILE" (resolved to '/home/documents/master_thesis/tutorial_data/lysin.fna')
Path stack:
	/home/gubrins/hyphy/res/
	/home/gubrins/hyphy/res/TemplateBatchFiles/SelectionAnalyses/

**Comment by gubrins** [comment]
And the content of the error.log is this:

Error:Could not find source dataset file "PROMPT_FOR_FILE" (resolved to '/home/documents/master_thesis/tutorial_data/lysin.fna')
Path stack:
	/home/gubrins/hyphy/res/
	/home/gubrins/hyphy/res/TemplateBatchFiles/SelectionAnalyses/

**Comment by stevenweaver** [comment]
Dear @gubrins, 

It looks like you may have entered the file path incorrectly. Take another look at `/home/documents/master_thesis/tutorial_data/lysin.fna`. 

Inferring from the other file paths documented, it seems like it should be `/home/gubrins/documents/master_thesis/tutorial_data/lysin.fna`

**Comment by gubrins** [comment]
Dear @stevenweaver and @spond,

Thank you both of you for your advices. The problem was that I had to add my alignment file inside an specific folder (SelectionAnalyses). Now the data is being analysed! :smile: 

Regards,
Gabriel

**Comment by spond** [comment]
Dear @gubrins,

You don't need to place files inside `SelectionAnalyses`. If you do, you can reference them by easy **relative** file paths (e.g. `filename.fna`), because file paths are calculated relative to the **analysis** file (which is in `SelectionAnalyses`). Otherwise you need to use **absolute** file paths, e.g. `/home/user/data/filename.fna`

Best,
Sergei
