### ISSUE TITLE
performing F_ST amd SMTest for many files at the same time

### ISSUE THREAD

**Issue by samuelkariuki** [veg/hyphy#780]
I have been using HYPHY GUI to perform compartmentalization evaluation where I load one file at a time and follow the prompts. I would however wish to perform this for so many files, say 1000. Is there a way I can give a single command and all the files are looped through and the result for each say F_ST or SMTest given as output. This will save my time a big deal.

**Comment by spond** [comment]
Dear @samuelkariuki,

You can accomplish this quite easily with the command line version of HyPhy and the terminal (if you have a Windows computer, this is a bit trickier). 

For example assume you have a collection of Newick files with the .nwk extension in a directory called `/home/sergei/data/trees`. Further assume that you have installed HyPhy with the default options, so that its library files are in `/usr/local/lib/hyphy/`

The shell command 

```

for tree_file in /home/sergei/data/trees/*.nwk; 
do HYPHYMP /usr/local/lib/hyphy/TemplateBatchFiles/SlatkinMaddison.bf $tree_file 2 csf y CSF BLOOD ${tree_file}.partitions "Most certainly" 1000 > ${tree_file}.output;
done

``` 

Will execute the `SlatkinMaddison.bf` analysis on every .nwk file in the `/home/sergei/data/trees/` directory, with `2` sequence types, `csf` used as the regular expression to split the clades, `CSF` and `BLOOD` as compartment labels, saving the partitioning file to the same file as the tree, but with the `.partitions` extension, and the console output to the `.output` file.

Obviously you will need to adjust parameter settings for your specific analysis.

The same procedure can be used for `F_ST.bf` and any other HyPhy analysis.

Best,
Sergei

**Comment by samuelkariuki** [comment]
Thank you!
Is there a comprehensive manual about HYPHY especially the compartmentalization evaluation part where can always jump for reference?

Regards,
Samuel Kariuki

**Comment by samuelkariuki** [comment]
Dear Sergei,
I am getting the below error ones I run the SMTest batch command.  The command I run is : for tree_file in ./*.nwk; do HYPHYMP /usr/local/lib/hyphy/TemplateBatchFiles/F_ST.bf $tree_file 2 BP y Blood Semen ${tree_file}.partitions "Most certainly" 1000 > ${tree_file}.output; done

`Error:
Not a valid option: './SVB008_combi_shf_aln.nwk' passed to Choice List 'Distance Computation' using redirected stdin input

Function call stack
1 : Choice List for "Distance Computation" with choice list:SKIP_NONE. Store result in distanceChoice
        Standard input redirect:
                000000000002 : 2
                000000000003 : BP
                000000000004 : y
                000000000005 : Blood
                000000000006 : Semen
                000000000007 : ./SVB008_combi_shf_aln.nwk.partitions
                000000000008 : Most certainly
                000000000009 : 1000
                -------
`

**Comment by samuelkariuki** [comment]
Dear Sergei,

I have tried using your suggestion and it seems to work. However, I got different results from what I got when running Slatkin Maddison from the GUI.

I have used HYPHYMP from the command line and GUI on Mac for compartmentalization detection between blood and semen and got different results. The same newick format file was used for both procedures.

HYPHYMP:
Number of migration events = 7
Prob{as many or fewer migration events by chance} = 1


GUI:
Number of migration events = 41
Prob{as many or fewer migration events by chance} = 0

Do you have an idea where the discrepancy could be coming from?

Regards,

Samuel Kariuki

**Comment by spond** [comment]
Dear @samuelkariuki,

Regrading the differences between GUI and CLI, I would first check that you used the same set of options, specifically that the branch partitioning was the same.

Best,
Sergei

**Comment by samuelkariuki** [comment]
Dear Sergei,

I used the same options and tree_file to do Slatkin Maddison test using GUI and CLI. I can send you one of the trees to try on your end and see whether you can advice on the discrepancy. The F_ST from both the GUI and CLI seem to agree though.

Let me know.

Regards,
Samuel Kariuki

**Comment by spond** [comment]
Dear @samuelkariuki,

Yes, please send me the tree and the expression you used to partition the sequences.

Best,
Sergei

**Comment by samuelkariuki** [comment]
Dear Sergei,

I saw Slatkin Maddison test in Hyphy has been upgraded to SM-2019. do we still use the following command for looping through many files:  for tree_file in /home/sergei/data/trees/*.nwk; 
do HYPHYMP /usr/local/lib/hyphy/TemplateBatchFiles/SlatkinMaddison.bf $tree_file 2 csf y CSF BLOOD ${tree_file}.partitions "Most certainly" 1000 > ${tree_file}.output;
done

**Comment by spond** [comment]
Dear @samuelkariuki,

With 2.5 release of HyPhy you should use keyword arguments like in

```
for tree_file in /home/sergei/data/trees/*.nwk;

do HYPHYMP /usr/local/lib/hyphy/TemplateBatchFiles/SM-2019.bf --tree $tree_file --regexp-1 CSF --description-1 CSF --regexp-2 BLOOD --description-2 BLOOD 

done
```

All the options can be seen by calling 

```
hyphy  /usr/local/lib/hyphy/TemplateBatchFiles/SM-2019.bf  --help
```

```
Available analysis command line options
---------------------------------------
Use --option VALUE syntax to invoke
If a [reqired] option is not provided on the command line, the analysis will prompt for its value
[conditionally required] options may or not be required based on the values of other options

tree [required]
	The Newick tree string defining the topology to use for testing

groups
	The number of compartments to test
	defaut value: 2

"description-"+(sm.i+1) [computed at run time] [required]
	"Description for sequences in compartment "+(sm.i+1) [computed at run time]

"regexp-"+(sm.i+1) [computed at run time] [required]
	"Regular expression to select the branches in compartment _"+sm.tag+"_" [computed at run time]

replicates
	The number of bootstrap replicates
	defaut value: 1000

weight
	Probability of branch selection for structured permutation [0-1]; 0 = classical Slatkin-Maddison, 1 = fully structured
	defaut value: 0.2

use-bootstrap
	Use bootstrap weights to respect well supported clades
	defaut value: Yes

output
	Write the JSON file here (default is to save to the same path as the tree file + '_SM.json')
	defaut value: sm.json_file [computed at run time]

```
Best,
Sergei

**Comment by samuelkariuki** [comment]
Thank you @spond 

I was able to run the SM-2019 with the directions you gave. However, I am having a little problem interpreting the results. Would you kindly guide me through.
Regards,

Samuel Kariuki

**Comment by spond** [comment]
Dear @samuelkariuki,

Sorry for not responding sooner. Here's some basic background on the modified SM test. Which specific questions do you have about your results?

Best,
Sergei

[usage.pdf](https://github.com/veg/hyphy/files/3731293/usage.pdf)
