### ISSUE TITLE
RELAX: error processing job

### ISSUE THREAD

**Issue by xiayh17** [veg/hyphy#782]
Hi ,
I had tried many times and it was wrong all the time in the method RELAX.
And i got an email.

Greetings,

Your analysis for 5ad3a08341c64c0eb9387664 had an error.  The error message 
can be found at http://datamonkey.org/relax/5ad3a08341c64c0eb9387664.
If you continue to have issues, please log a bug at 
https://github.com/veg/hyphy.

Regards,
Datamonkey Development Team

**Comment by stevenweaver** [comment]
Dear @xiayh17, 

Sorry for the delay on this. I've had a number of pressing projects over the past week. Was this issue resolved for you?

Best,
Steven
