### ISSUE TITLE
Datamonkey tree display truncated for GARD 

### ISSUE THREAD

**Issue by matsen** [veg/hyphy#783]
Happened on Chrome under both OS X Sierra and Chromebook. Impacts the SVG and PNG downloads too.

http://datamonkey.org/gard/5ad658f24faf7e5040dee2f0

![screenshot 2018-04-17 at 1 40 40 pm](https://user-images.githubusercontent.com/112708/38895573-42c50ad6-4245-11e8-8577-30bc3dc5f676.png)

**Comment by rdvelazquez** [comment]
This has been addressed in https://github.com/veg/phylotree.js/pull/93 but will need the newer version of PhyloTree in datamonkey/vision before the change will take effect there.
