### ISSUE TITLE
Uploading a sequence alignment fails at Datamonkey

### ISSUE THREAD

**Issue by TQ01** [veg/hyphy#784]
Dear all,

 I have a question regarding a nucleotide model testing at Datamonkey (classic).

 Uploading a sequence alignment fails with an error: 

"  HyPhy run-time error
   Empty File Encountered By ReadDataSet.
   Function call stack
   1 : Read Data Set ds from file fileName  "

I have tried all three formats: .fasta. .nex, .phy

The first two sequences of the alignment look like this:

>Allele*10
TGTCCCGGCCCGGCCGCGGGGACGCCTGGTTCCTCACAGTCGGCTACGTGGACGGCACGGAGTTCGTGCGGTTCGACAGCGACGCGGCGAACCCGAGGATGGAGCCGCGGGCGCCGTGG---------------GTGGAGCAGGAGGACCCGCAGTATTGGGACCGGGAGACGCGGATCTCCCAGAGACACGCACAGACTTTCCGACGGAGCCTGGACAACCT
>Allele*167
TGTCCCGGCCCGGCCGCGGGGACGCCTGGTTCCTCACAGTCGGCTACGTGGACGGCACGGAGTTCGTGCGGTTCGACAGCGACGCGGCGAACCCGAGGATGGAGCCGCGGGCGCCGTGG---------------GTGGAGCAGGAGGACCCGCAGTATTGGGACCGGGAGACGCGGATCTCCCAGAGACACGCACAGACTTTCCGATGGAGCCTGGACAACCT
  
Can someone, please, help me to understand what is the problem and how can I fix it?

Thank you.

Tamar

**Comment by spond** [comment]
Dear @TQ01,

The alignment file looks fine to me, so that's likely not the issue. Does the same alignment work with the new datamonkey? Also, are you able to load it into HyPhy locally? (see http://hyphy.org/tutorials/current-release-tutorial/#using-hyphy-to-detect-selection)

It may be fastest if you e-mail me or @stephenshank the alignment in question.

Best,
Sergei

**Comment by TQ01** [comment]
Dear Sergei,

Thank you very much for your quick response.
I will send you an email with the datafile, the answers to your questions and a few details about the data.

Best regards,

Tamar

**Comment by stevenweaver** [comment]
Dear Tamar and Sung, 

It appears this had to do with an issue experienced by the datamonkey-classic server. Please try again. 

Best,
Steven

**Comment by sungml92** [comment]
Dear Steven,

Thank for solving the issue.

Best,
Sung
