### ISSUE TITLE
Error processing aBSREL job

### ISSUE THREAD

**Issue by mht85** [veg/hyphy#785]
Hi,

I ran my alignment and tree on the Datamonkey server (aBSREL method), got an error mid-run and the job was aborted. The log file (attached) doesn't contain any obvious errors so I can't troubleshoot from my end.

[log.txt](https://github.com/veg/hyphy/files/1965539/log.txt)

Any help appreciated.

Cheers,
Mun

**Comment by stevenweaver** [comment]
Dear @mht85, 

Sincerest apologies. This issue slipped past me. It's quite possible that our web services experienced an interruption that day. If you are still having an issue, please reopen the ticket and let us know. 

Best,
Steven
