### ISSUE TITLE
how to explain synonymous changes in coding sequences and negative selection pressure on a coding sequence

### ISSUE THREAD

**Issue by alka26** [veg/hyphy#786]
The sequencing result of a new isolate viral gene, 4 unique synonymous changes  in amino acid found, however selection pressure analysis (SLAC Analysis in datamonkey) support the fact that gene is under negative pressure; dn/ds=0.33.

I do not understand how to interpret the data.

Anybody can explain???

Regards

Alka

**Comment by spond** [comment]
Dear @alka26,

What did you expect the analysis to find? If you have **fewer** non-synonymous changes **relative** to the expected number under neutrality, negative selection may be inferred. Please see pages 30-33 in http://www.hyphy.org/pubs/hyphybook2007.pdf for an example.

Best,
Sergei

**Comment by alka26** [comment]
Thank you so much Sir for reply

Here, wish to clarify that I am bioinformatician but a biologist and new at usage of these tools and encouraged by your reply to dig deeper. Here I want elaborate more on the issue.

The viral protein aforementioned has plays crucial role in assembling and budding of virions and thereby believed to be most conserved viral protein among Genus. We have detected few non synonymous changesin a recent virus isolate upon multiple sequence alignment, which were not present in another 24 reference sequence taken from GenBank. So result was unexpected and seems to be interesting.
The selection pressure analysis was as per previous reports and as expected i.e. negative.

My first query  is as previous.... how to interpret the result these contradictory result (in another terms how many non-synonymous changes are dubbed in positive pressure selection).

The second one is.......is there any possibility of loosing signals of  non-synonymous changes in an alignment.

Thank you in anticipation for your valuable time and patience.
Regards
Alka

**Comment by spond** [comment]
Dear @alka26,

Sorry, I still don't understand your questions. Perhaps you can include a link to your datamonkey analysis and indicate which sites you are talking about. Also please note, that dN/dS = 0.33 is **not** evidence of negative selection (you need to look at p-values). 

1. If you see **only synonymous substitutions** at a particular alignment site, then **by definition** the only two classifications for this site (in the dN/dS framework) are: negatively selected or neutrally evolving.

2. I don't understand what you mean by "losing signals of non-synonymous changes".  Bad alignment can sometimes **create** non-synonymous changes that should not be there.

Best,
Sergei
