### ISSUE TITLE
Process aborted (Killed)

### ISSUE THREAD

**Issue by Abayomi-Olabode** [veg/hyphy#795]
Hi,

I have been attempting to adjust for purifying selection using the aBSREL method but sometime during the runs, the process keeps getting aborted (killed). The errors.log file contains no errors so it makes difficult to know what to do to troubleshoot. I have tried the run on a computing cluster and on my linux (ubuntu) machine.

Please I need your advice on what to do.

Thank you.

Best Wishes,
Abayomi

**Comment by stevenweaver** [comment]
Dear Abayomi, 

Do you have the `messages.log` file available? You can also send the offending multiple sequence alignment file to sweaver@temple.edu as well so that I can try reproducing the issue.

Best,
Steven

**Comment by stevenweaver** [comment]
Dear @Abayomi-Olabode, 

I received your file, thank you. The multiple sequence alignment file you sent me has `3900` sequences of length 450. 

This is a lot for a branch-site method. **You may want to consider reducing your dataset.**

I believe that your process must have been running for quite some time, and that the process eventually violated a system limitation defined by `ulimit`. 

You would be able to confirm this by investigating your `syslog` located at `/var/log/syslog`. 

Best,
Steven

**Comment by Abayomi-Olabode** [comment]
Hi @stevenweaver,

Thank you.

Best,
Abayomi

**Comment by ArtPoon** [comment]
Hi @stevenweaver - we're running a CentOS rig so the log was in `/var/log/messages`, where we find the out-of-memory problem killed the job:
```
May 13 08:19:12 BEVi kernel: HYPHYMP invoked oom-killer: gfp_mask=0x280da, order=0, oom_score_adj=0
May 13 08:19:12 BEVi kernel: HYPHYMP cpuset=/ mems_allowed=0-1
May 13 08:19:12 BEVi kernel: CPU: 7 PID: 179859 Comm: HYPHYMP Tainted: G 
```
We're trying to apply @jwertheim's dating analysis with purifying selection, which uses branch-site derived models, to these data.  Based on your feedback, I think we will try:
1. applying a non-lineage variant model of codon selection like Dual
2. analyzing a random sub-sample of the data

**Comment by ArtPoon** [comment]
Hi @spond - Job was running on head node with 64GB for 16 cores, but there were multiple jobs running on the head node so I suspect it was a legit OOM kill.  If you still want it though I can send you the data.
Any recommendation on how to rescale a tree without a full B-S model analysis?

**Comment by spond** [comment]
Dear @ArtPoon,

Yeah, I would like to see how long it take to run and how much RAM it takes. No immediate recommendation on how to do a quick and dirty analysis, sorry.

Best,
Sergei

**Comment by ArtPoon** [comment]
Ok, sent tarball to your e-mail. We'll probably go the subsampling route, thanks.

**Comment by ArtPoon** [comment]
Memory leak patched in beta branch by @spond
