### ISSUE TITLE
Archived tarball changed when release redone?

### ISSUE THREAD

**Issue by Jehops** [veg/hyphy#796]
Hi,

I think the 2.3.12 release was replaced, i.e., a new tarball was created without a new version. This causes packaging to fail due to hash and/or size mismatches. If there are no downsides, in such situations, could a new release such as 2.3.12.1 be made to prevent these problems?  To be clear, I am not requesting any current changes, just future changes.

Thank you.

```
=> Attempting to fetch https://codeload.github.com/veg/hyphy/tar.gz/2.3.12?dummy=/veg-hyphy-2.3.12_GH0.tar.gz
fetch: https://codeload.github.com/veg/hyphy/tar.gz/2.3.12?dummy=/veg-hyphy-2.3.12_GH0.tar.gz: size mismatch: expected 7901009, actual 7900819
=> Attempting to fetch http://distcache.FreeBSD.org/ports-distfiles/veg-hyphy-2.3.12_GH0.tar.gz
fetch: http://distcache.FreeBSD.org/ports-distfiles/veg-hyphy-2.3.12_GH0.tar.gz: Not Found
```

**Comment by stevenweaver** [comment]
Dear @Jehops, 

Yes. We can adopt `npm`'s policy of not deleting/replacing versions once they are published. I wasn't aware that the tag would be utilized so quickly. 

Thank you, 
Steven
