### ISSUE TITLE
an error processing your job RELAX

### ISSUE THREAD

**Issue by mhdatefzayed** [veg/hyphy#798]
I have tried many times to submit my job on RELAX, every time I got this message
We're sorry, there was an error processing your job. Please try again
http://datamonkey.org/relax/5b0207fe9595ce5f28d74828

**Comment by stevenweaver** [comment]
Dear @mhdatefzayed, 

We should be more descriptive about what is going wrong, but upon inspection, you are selecting all branches as `TEST`.  The RELAX method requires that at least some branches need to be selected as a `REFERENCE`. 

The following is the error reported by HyPhy. 
```
Error:
RELAX requires at least one designated set of branches in the tree. in call to assert(
```

Best,
Steven

**Comment by stevenweaver** [comment]
@veg/datamonkey, 

I'm marking this issue as a bug because we should 1) place further validation on the branch selection page to ensure that at least two partitions are selected and 2) that errors that are recognized by `HyPhy` is reported on the site itself as opposed to simply saying something went wrong. 

Best,
Steven

**Comment by mhdatefzayed** [comment]
this is my first time to run this analysis, I do not know the meaning of reference branches in this context. I would like to ask is there any criteria for selecting reference branches or just select one clade in the phylogenetic tree as a reference ? Thanks for your help.

**Comment by stevenweaver** [comment]
Dear @mhdatefzayed, 

There was an unrelated issue with our database that occurred overnight (Eastern Time). Please try again. 

Best,
Steven

**Comment by mhdatefzayed** [comment]
Thank you @stevenweaver. I believe it works now.
