### ISSUE TITLE
FUBAR run does not output results

### ISSUE THREAD

**Issue by AnnieLamb** [veg/hyphy#799]
Hi there, 

I am trying to run MEME and FUBAR on an alignment of 23 mitogenome sequences (coding regions only). MEME runs fine and outputs results. FUBAR runs and I am sent an email saying the job is complete but when I click on the link in the email I am taken to a page with no results and that says that the job is still running. I have tried running the job using the alignment in both fasta and nexus formats (attached here). I have also tried running the job using a rooted and an unrooted tree. I have further had a go at reverting to Datamonkey classic where the FUBAR job stays queued and does not run. 

Any help would be much appreciated. 

Thanks in advance, 
Annie

[STPmitogenomes_RootedTree_fasta.txt](https://github.com/veg/hyphy/files/2024468/STPmitogenomes_RootedTree_fasta.txt)
[STPmitogenomes_RootedTree_nexus.txt](https://github.com/veg/hyphy/files/2024469/STPmitogenomes_RootedTree_nexus.txt)

**Comment by AnnieLamb** [comment]
Thank you for very much for you quick response and help Steven!

**Comment by spond** [comment]
Dear @stevenweaver,

How large were the JSON files are what are the limits? FADE makes large JSON files, and I want to prevent issues before they happen.

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @spond, 

The document limitation for MongoDB is 16MB. My proposal is to consider removing the posteriors for each MCMC iteration from the FUBAR results.

Best,
Steven

**Comment by LaMartaC** [comment]
Hi there, I am encountering the same issue. I have started the same analysis 7 times and each time something different happened, but I never managed to get the results! Sometimes my submission would disappear from the queue (or showed as completed) but I wouldn't receive any email. Sometimes I received an email but the job was "still running". Sometimes it got stuck after the 5th chain and sometimes after determining positively selected sites. I have solved by running FUBAR on the old website.... however, I got very strange results: are the 2 versions of FUBAR identical? My latest submission was http://datamonkey.org/fubar/5b622feca1e50e1b094766de.
Thanks!

Marta

**Comment by spond** [comment]
Dear @LaMartaC,

It would seem that your job was affected by the same bug as the one discussed in this thread. I have confirmed that the analysis finished with **no sites detected**. This is not too surprising, because your alignment only has 4 sequences, and FUBAR (or any other method)  is not expected to have too much power to find individual sites under selection. Your best bet here I think is BUSTED.

Best,
Sergei

**Comment by LaMartaC** [comment]
Hi Sergei, thank you so much for your quick reply. I already know that overall there is a strong negative pressure but I was interested in getting an estimate of the number of negatively selected sites and FUBAR on the old site resulted in 88% of the sites being negatively selected (SLAC gives me about 3%)! I just wanted to confirm the data. Thanks

**Comment by kemang** [comment]
Hi there,
I am also encountering the same problem just like LaMartaC. I would appreciate if someone can help me solve the problem and send the results to yuko@139.com.
This is my submission: http://www.datamonkey.org/fubar/5b7bbef9667f4d3e4504e253

**Comment by rdvelazquez** [comment]
https://github.com/veg/datamonkey-js/pull/144 was thought to have addressed this but the behavior is still occurring (fubar jobs that create a json file larger than 16MB never go from the progress page to the results page).

**Comment by rdvelazquez** [comment]
It looks like there _are_ some FUBAR jobs that create json files >16MB and finish without issue.
- 32 MB json, job finishes fine: http://datamonkey.org/fubar/5cadf911119e4869148b75bb
- 34.5 MB json, job finishes, creates json but datamonkey stays on progress page: http://datamonkey.org/fubar/5ca370e59a669d272dbbe13f

**Comment by stevenweaver** [comment]
Dear @rdvelazquez, 

To add, there were no restarts on that day for any process. Operations were normal, and the job took 22 minutes to run. What is unusual is that there is no record in the datamonkey server logs for either of those jobs, unfortunately. 

Best,
Steven
