### ISSUE TITLE
Getting the posterior assignment probabilities of internal nodes 

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#800]
Hi dear team,

I wish to extract the values of the posterior probabilities of states assignments in internal nodes.

I believe these are computed as part of the call to either `SampleAncestors` or `ReconstructAncestors`, but since both functions appear to return exact assignments, I am not sure how I can get the probabilities used for generating them.

I saw in the cpp code, /src/core/likefunc2.cpp, a function named `FillInConditionals`, being called by the corresponding cpp function `ReconstructAncestors`, but I am not sure how I can access the probabilities. 

Could you please guide me?

Many thanks!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

You are probably looking for marginal reconstruction options, namely

Pr (state at node X = S | Data),

where the assignments over other nodes are integrated out. 

What you want is this:

```
DataSet	 		_marginalAncestors 			= ReconstructAncestors (_lf_ID,MARGINAL);
DataSetFilter	_marginalAncestorsFilter	= CreateFilter 		   (_marginalAncestors, 1);
GetDataInfo 	(_marginalFilterSiteToPatternMap, _marginalAncestorsFilter);

```

`_marginalAncestors` will contain inferred sequences (maximum conditional prob at a site), but there will also be a `_marginalAncestors.marginal_support_matrix` created that reports the entire distribution. 

This is going to be a matrix where each **row** is an ancestral node (get the name of the i-th sequence as ` GetString (name, _marginalAncestors, i)`), and each column is the concatenation of posterior distributions for each **site pattern** (i.e. unique site). You can get the `site -> pattern` map by calling 

```
GetDataInfo 	(_marginalFilterSiteToPatternMap, _marginalAncestorsFilter);
```

If your likelihood function was defined on **C** characters (e.g. 61), then the posterior probability for the **p-th** pattern in sequence **I*** will be in 

```
_marginalAncestors.marginal_support_matrix[I][(p-1)*C] to _marginalAncestors.marginal_support_matrix[I][p*C-1]
```

for example here's a short snippet for a nucleotide filter (you can see the high values for "robust" states), `CAAT...`

```
{{
/*start pattern 0*/ 4.787149368186583e-09, 0.9999990254648929, 4.734286852746961e-07, 4.96319272458301e-07 /*end pattern 0*/, /*start pattern 1*/0.999107448066743, 0.000864180150449857, 1.385103802160939e-05, 1.452074478547338e-05,  /*end pattern 1*/, /*start pattern 2*/ 0.999999961881688, 1.06433067079455e-08, 1.341323333979692e-08, 1.406177196905389e-08, /*end pattern 2*/, /*start pattern 3*/ 7.557379202237834e-09, 6.730453857556859e-07, 4.180897484843698e-09, 0.9999993152163376
```

Best,
Sergei

**Comment by halabikeren** [comment]
Thank you, Sergei!

This is exactly what I needed.
