### ISSUE TITLE
Datamonkey - ASR option not shown

### ISSUE THREAD

**Issue by juliannenp** [veg/hyphy#801]
Hi, 

I don't think this is the appropriate place to ask this question, but I've been unsure where/who else to ask, and I've been banging my head against the wall for the last few hours. 

I have an amino acid alignment of 12 sites, 37 sequences, 1 partition, a rooted tree that I am providing, and I'm trying to run an ASR in Datamonkey (classic). But after I upload my data, the option for ASR isn't available in the drop down menu, and when I go to "Information: Other Analyses" and choose "Set up ASR" it brings me back to the previous page with no option for ASR. 

Any idea what the problem is? Thanks so much!!

[insectphylogeny.txt](https://github.com/veg/hyphy/files/2028156/insectphylogeny.txt)

**Comment by juliannenp** [comment]
Hi Steven, 

Thanks for getting back to me so quickly! That's unfortunate to hear, but at least makes me feel a little bit better that it wasn't some silly mistake on my part. Well, in any case, I'll figure out some other method -- thanks again!

Best, 
Julianne

**Comment by stevenweaver** [comment]
Dear @juliannenp, 

I'm going to close this issue, but your story will not go forgotten. 

Best,
Steven

**Comment by ArtPoon** [comment]
Hi Julianne, I can help you analyze these data with ASR.

**Comment by ArtPoon** [comment]
@juliannenp, do you know what protein substitution model you'd prefer to use?  I'm assuming you want amino acid ASR based on your alignment.

**Comment by ArtPoon** [comment]
Also, the tree provided with your alignment has no branch lengths and there are not enough sites in the alignment to accurately estimate branch lengths.  Can you please either provide a tree with branch lengths or a longer alignment (with coordinates for the sites you want the ASR at)?

**Comment by juliannenp** [comment]
Hi Art,

Thanks so much for your help! I really appreciate it!
This tree has been cobbled together from many different phylogenies across
different insect groups, so I think I could get a longer alignment for some
species but not all. Let me see if I can do this right now.

Thanks again!

Best,
Julianne

**Comment by ArtPoon** [comment]
Ok, here's a minimal script that will perform ASR on your data:
```C
// load the protein alignment including a tree
DataSet ds = ReadDataFile("insectphylogeny.txt");
DataSetFilter filteredData = CreateFilter(ds, 1);

// pick one of the AA substitution models
SelectTemplateModel(filteredData);

IS_TREE_PRESENT_IN_DATA = 1;
ACCEPT_BRANCH_LENGTHS = 1;
ACCEPT_ROOTED_TREES = 1;  // is your tree unrooted? 
//treeString = RerootTree(DATAFILE_TREE, 0);
Tree givenTree = DATAFILE_TREE;

LikelihoodFunction lf = (filteredData, givenTree);
Optimize (res, lf);

// ancestral reconstruction by joint maximum likelihood
DataSet anc = ReconstructAncestors(lf);
DataSetFilter adf = CreateFilter(anc, 1);

DATA_FILE_PRINT_FORMAT = 9; // FASTA sequential
fprintf("anc.fa", CLEAR_FILE, adf);
```

**Comment by ArtPoon** [comment]
I forgot to mention, to run the script you will need to have command-line HyPhy installed on your computer and the run this script with `HYPHYMP <name of script>`. 

It sounds like your tree has unit branch lengths - if you can get full nucleotide gene sequences associated with these taxa then I can show you how to estimate branch lengths in evolutionary time and then feed the result into a modified version of the script.

**Comment by juliannenp** [comment]
Hi Art,
Yes, I just downloaded HyPhy, and will do as you suggested. I'll see if I
can get full nucleotide gene sequences. It should be easy but it may take a
little bit more time. If it isn't too much trouble, please let me know what
aspects would be modified to this script if I were to get this data.
Thanks so so much!
Best,
Julianne

**Comment by juliannenp** [comment]
Hi Art, 

This worked wonderfully!! Thanks so much for your help!

**Comment by ArtPoon** [comment]
Glad it worked out @juliannenp - i recommend doing some sanity checks, e.g., manually evaluate an arbitrary selection of sites to see if ASR outputs make sense.
