### ISSUE TITLE
Spidermonkey on Datamonkey (classic) -- stalled?

### ISSUE THREAD

**Issue by juliannenp** [veg/hyphy#803]
Hi, 

Thanks in advance for any help you can provide! 
I have a Spidermonkey/BGM analysis running on Datamonkey. I've tried running it a few times now and it runs for 8-10 hours without finishing. I just tried to rerun it again (it's now just at 40 minutes), but I'm wondering if there's something I did wrong. 
I have only 37 sequences and 3 sites. 
Thanks!

-Julianne

**Comment by ArtPoon** [comment]
There's definitely something wrong there.  Is it possible for you to send me your data set so that I can attempt a standalone analysis?  My contact info is [here](https://www.schulich.uwo.ca/pathol/people/bios/faculty/poon_art.html)

**Comment by TQ01** [comment]
Hello,

I would appreciate any help with my question.

I am experiencing similar issue as juliannenp; running a nucleotide model selection test on Datamonkey Classic, and though before it has been taking no more than 2-3 minutes for the same data, it is running for already 25 minutes for now. Also, I see that the queue of analysis running is unusually long, and the longest time a model selection test is being running is about 85 hours, just for 5 sequences.

I wonder if a server has a problem, and if we would need to cancel all jobs till the web-server works again.

Best regards,

Tamar

**Comment by stevenweaver** [comment]
@TQ01, 

We've made substantial upgrades to our high performance computing cluster this weekend. Unfortunately, due to the upgrades, a communication protocol mismatch has arisen between our cluster and classic datamonkey. Today is a holiday in the United States. We will investigate soon, however.

Best,
Steven

**Comment by TQ01** [comment]
Dear Steven,

thank you for your quick response. 
I look forward to getting back to the server for further analysis after the issue is solved.

Best regards,

Tamar

**Comment by juliannenp** [comment]
Unfortunately, I think it stalled again. Any help here?

**Comment by stevenweaver** [comment]
@juliannenp - Would you mind trying to give running BGM another go? There was an issue with how BGM was attempting to call `openmpi`.

**Comment by juliannenp** [comment]
Hi Steven,
I ended up running the analysis on the hyphy gui, but now when I just ran
it on the webserver, I get this error:
[image: image.png]

In any case, I shouldn't need access to the webserver version.

Best,
Julianne
