### ISSUE TITLE
Basic questions related to Datamonkey Selection Tools

### ISSUE THREAD

**Issue by mhdatefzayed** [veg/hyphy#804]
Dear All,
I do have two basic questions about MEME and RELAX. 

My questions as follow:

1-	MEME identifies episodic selection that affects only a subset of lineages, however as far as I can see from my MEME output results, MEME refers only to sites under diversifying selection without designating at which subset of lineages. In this good source of information http://www.hyphy.org/resources/slides-selection-2016.pdf especially for the basic level like me one slide (page # 80)  shows q-value and branch-site information in the output results of MEME, but in my case I do not get such information from the online analysis output results, I do not know if something wrong I am doing, or something extra I should do.
  
2- As Relax tests natural selection strength on set of test branches versus reference branches. My question is about the idea of selecting branches according to the posed question. If the phylogenetic tree is based on the same gene from different species, and the question is to see if this gene has been selected in some species rather than other set of species (Giving that what I would like to test is in two distinguished clades), as far as I understand I can select the branches of the test species and compare them with the branches of the reference species, Is that correct ? Saying that maybe correct, what will make difference in the posed question among selecting only branch leaves in these two sets or selecting branch leaves with internal branches in these two sets (i.e. Test set against Reference set) ?     

Many thanks in forward.

**Comment by mhdatefzayed** [comment]
Dear Dr. Sergie,
Thank you so much for your time, reply and explanation. Please Sir, give me the chance to ask some more questions and hopefully that will not bother you, my questions are : 

1-	Can aBSREL complement MEME job by assigning branches under episodic diversifying selection ?
2-	Using MEME and FEL analyses on the same dataset, MEME detect one site under episodic positive selection while FEL detects it under pervasive positive selection. If the data was as follow:
MEME Result
α	        β-	       p-	         β+	         p+	       LRT	            p-value
0.02	0	     0.56	       3.25  	0.44	8.91           	0.01	
FEL Result for the same Site
Alpha		Beta	    	 Alpha=Beta		LRT		p-value
0.07		1.145		        0.75		7.731		0.005
From my view, I would trust MEME result because of the higher LRT value, Am I correct ? Or I should consider other facets of comparison.	        
3-	I was trying to use RELAX today, but I could not select reference branches like I used to do before “the button is not activated for selection”, I can see that it automatically assigns the rest of the tree as a reference once I select test branches, Is that OK ?

Many Thanks for your time and consideration.

**Comment by spond** [comment]
Dear @mhdatefzayed,.

1. Yes, to a degree. The two methods are somewhat complementary.

2. FEL and MEME **do not** disagree here, so you don't have to choose one or the other. You **never** use the raw value of LRT (or p-values) derived under **different** tests to compare the strength of evidence. The correct way to interpret the results here is that both FEL and MEME are significant, and you don't privilege one over another. MEME is a more complex model, so it is not a surprise that the method finds more nuance in describing the evolution of a site. 

3. @stephenshank can you please check that RELAX analysis set-up is working correctly? If don't need to specify "unclassified" branches in the tree, then defaulting the unselected branches to "reference" should work for you.

Best,
Sergei

**Comment by mhdatefzayed** [comment]
Thank you Sir for your detailed answer.

**Comment by stephenshank** [comment]
Dear @mhdatefzayed and @spond,

RELAX seems to be working as expected to me. Using the CD2 dataset, [I submitted a job to Datamonkey](http://datamonkey.org/relax/5b0ee078a0861d724890f5b1). I was able to select both test and reference branches as follows::

![image](https://user-images.githubusercontent.com/8673708/40740032-b4ca89b6-6415-11e8-8b53-9f669e1810d0.png)

After the analysis completed, I checked correctness of test:
![image](https://user-images.githubusercontent.com/8673708/40740070-d4a54fdc-6415-11e8-94dc-f58fe90cc202.png)

reference:
![image](https://user-images.githubusercontent.com/8673708/40740086-df0929c6-6415-11e8-8567-48e7fa44f641.png)

and unclassified branches:
![image](https://user-images.githubusercontent.com/8673708/40740111-f06fdc3c-6415-11e8-92bf-8c78c84fe114.png)

which seems to check out. I did a similar analysis with only test branches, which did indeed default the unselected branches to reference as mentioned by @spond.

@mhdatefzayed Hope this helps; if not, can you please clarify what you meant when you wrote that you could not select reference branches (so that I can try to reproduce the error)?

Best, 
Stephen

**Comment by nmathers** [comment]
Just a possibly relevant thought here - I recently was unable to select reference branches in aBSREL and BUSTED on datamonkey with a dataset containing 133 sequences. After reducing the dataset to 80 sequences, I was then able to successfully select reference/foreground branches. Perhaps the number of branches in the tree is a problem?

**Comment by mhdatefzayed** [comment]
Dear @stephenshank,
I remember one week ago, RELAX was working perfectly like what you described. While now I am trying to use it on Safari and Chrome and I was not able to press "Reference" button to select the reference branches, it just not active as in this photo 
![20180530_145148](https://user-images.githubusercontent.com/39471256/40741778-4e16abf0-641a-11e8-9668-37980a25de8f.jpg)


Besides this my job still running since yesterday, I believe also before this it was not taking that much time.

Thank you so much for your time and consideration.

**Comment by stephenshank** [comment]
Dear @nmathers,
Thanks for the feedback. I subsetted a [large hemagglutinin alignment](https://github.com/veg/evogenomics_hyphy/blob/master/datasets/h3_full.fna) to 133 sequences and was able to [submit a BUSTED job](http://datamonkey.org/busted/5b0ef0d1a0861d724890f783) (though it has not finished running as of writing) with the following branch selection:

![image](https://user-images.githubusercontent.com/8673708/40742417-7ff42f74-641c-11e8-83ad-acef36e2f167.png)

Any additional information you can provide with respect to reproducing the error (operating system with version, browser with version, etc.) would be appreciated.

Best,
Stephen

**Comment by stephenshank** [comment]
Dear @mhdatefzayed,

Unfortunately I am unable to reproduce the error in Safari:

![safari](https://user-images.githubusercontent.com/8673708/40742476-a8504674-641c-11e8-9109-0685ba2f0cd2.gif)

I am currently running Mac OS X (10.13.3) and Safari (11.0.3). Any details you can provide about your system would be useful. Also, another option is to [annotate the tree with phylotree](http://hyphy.org/tutorials/phylotree/) and [run HyPhy on the command line](http://hyphy.org/installation/).

Best,
Stephen

**Comment by mhdatefzayed** [comment]
Thank you Sir @stephenshank  for your followup, I use macOS High Sierra 10.3.4 and Safari 11.1.
My job that still running is http://datamonkey.org/relax/5b0e2097a0861d724890d92d
In this job the reference branches had been assigned automatically not by me.

**Comment by nmathers** [comment]
@stephenshank The error occurred while using both Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit) and Safari (Version 11.1) on Mac OS Sierra 10.13.4. I was able to successfully select branches on Datamonkey in aBSREL with a dataset of 80 sequences in both of those browsers.

I am able to select the branches with the tree viewer. However, once the job beings to run, aBSREL does not recognize any subset of branches as selected but rather selects all branches.

Perhaps it's an issue with my data file(nexus)?
[nmathers_133sequence_datamonkeyinput.txt](https://github.com/veg/hyphy/files/2059576/nmathers_133sequence_datamonkeyinput.txt)

Thanks!

**Comment by mhdatefzayed** [comment]
Dear @stephenshank ,
Just to update you, that I was trying RELAX on one clade of my tree and it works fine, while when I was trying it on the whole tree, the reference button was inactive as I told before. So I believe it may not a matter of the mac or the browser version. Many thanks for your time and consideration.

**Comment by stephenshank** [comment]
Dear @nmathers,

This certainly was a bug, which should be resolved now. Please let me know if you still experience any issues.

**Comment by stephenshank** [comment]
Dear @mhdatefzayed,

Thanks for reporting this; we were finally able to replicate the issue, which seems to appear when the screen width is reduced. @rdvelazquez is working on a new branch selection component at the moment... when it is done, we will be sure to test this bug and let you know when a working version is live.

Best,
Stephen
