### ISSUE TITLE
meds data set simulations (from Plos Comp Biol 2012)

### ISSUE THREAD

**Issue by juanangel87** [veg/hyphy#806]
Hello!
I am trying to compare the performance of some selection tests, and I need simulated data with and without positive selection in foreground branches. In the paper reporting MEDS (PloS Comp Biol et al ,2012) I saw that you did such simulations, and the first author passed me the script that was used. This old script still works at the new hyphy, but I have some questions.
1-In the paper, 5 different values of omegaT for the foregrounds are used (table 5), but in the script I do not see how can I set it. 
2-In Table 6 there are different substitutions to target AA. Is it something that has to be specified in the script?
In the simulated sets that available from http://www.hyphy.org/w/index.php/MEDS I only see different sets of different sizes and foreground branches, but it seems they were not run specifying different values for OmegaT, so I do not know whether it can actually be set...
It is a paper from 2012 and I am not sure you still have the simulator script. I have not posted it because it is not mine, but if it helps to solve the question I could post it/send it by email if you (the coauthors of the paper) are Ok with it.

thank you so much for your help.

Juan

**Comment by spond** [comment]
Dear @juanangel87,

Please post the script to make sure we are talking about the same thing. I'll take a look and tell you what I can find. Are you interested specifically in MEDS-based simulated data?

Best,
Sergei

**Comment by juanangel87** [comment]
Hello @spond 
I have attached the script, kindly provided by Ben Murrell. He saw the post, and answered my doubts by email. 
I am interested in simulating data where there is directional selection in specific (foreground) branches, but not necessarily on using  MEDS. I have not found any other data simulator with scenarios like this one (directional selection in foreground branches of interest), so I am really interested in the simulator that you generated to assess the power and false positives of MEDS. I think it can be very useful.
[MEDSsimulator.txt](https://github.com/veg/hyphy/files/2099267/MEDSsimulator.txt)
Thank you so much for your help,
Best wishes,
Juan
