### ISSUE TITLE
GARD analysis - non-coding nucleotide data

### ISSUE THREAD

**Issue by jayoung** [veg/hyphy#807]
Hi there,

I thought I'd try running GARD on some non-coding sequences using the online version.  I've read the paper and if I understand right, the method does not require protein-coding sequences (I would select data type=nucleotide) - is that correct?  

I think DataMonkey-Classic website is running GARD on my sequences now, but if I try the new website, I get an error message: "The number of nucleotide columns in the data set must be divisible by 3 - had 1465 sites. Please check that the reading frame is aligned with the beginning of the data set, and that no trailing sites are extraneous".   That is true for my alignment, but I don't think it should matter for this analysis, if I'm running in nucleotide (not codon) mode - have I understood right?  Seems like the input parser may be applying a standard which is appropriate for most HyPhy analyses, but is stricter than it needs to be for GARD.

thanks for all your hard work on HyPhy!

Janet Young

------------------------------------------------------------------- 

Dr. Janet Young 

Malik lab
http://research.fhcrc.org/malik/en.html

Division of Basic Sciences
Fred Hutchinson Cancer Research Center
1100 Fairview Avenue N., A2-025, 
P.O. Box 19024, Seattle, WA 98109-1024, USA.

tel: (206) 667 4512
email: jayoung  ...at...  fredhutch.org

-------------------------------------------------------------------

**Comment by spond** [comment]
Dear @jayoung,

Thank you for reporting this issue. You are correct in your assessment: the same data handler that is used by coding sequence analyses is used by GARD, imposing restrictions that are too stringent. We will modify the upload data validator to allow non-coding data for GARD.

Best,
Sergei

**Comment by jayoung** [comment]
Thanks, Sergei.  Hopefully that's an easy modification.

Janet

**Comment by NatJWalker-Hale** [comment]
Hi guys, 

Have there been any developments on this? I am also trying to use GARD through the webserver for non-coding DNA alignments but the same error is still popping up. 

Thanks for all your hard work and great platform, 

Nathanael

**Comment by spond** [comment]
Dear @NatJWalker-Hale,

@rdvelazquez and/or @stevenweaver : could you provide an update?

Best,
Sergei

**Comment by rdvelazquez** [comment]
Dear @NatJWalker-Hale and @spond,

I'm looking into this now. I'm planning to rework the `datareader.bf` batch file to be able to handle non-coding DNA/RNA and hope to have a fix into the staging site for use by early next week.

Best,
Ryan

**Comment by NatJWalker-Hale** [comment]
Thanks @rdvelazquez for the prompt response!

**Comment by rdvelazquez** [comment]
@NatJWalker-Hale This fix is now live at staging.datamonkey.org

Could you confirm that it works for you and that you're able to run your GARD job?

**Comment by NatJWalker-Hale** [comment]
Hi @rdvelazquez, the analysis ran to completion on staging.datamonkey.org, thank you very much for the quick fix!

However, I get different results when running GARD locally (with a smaller number of nodes), which infers 2 breakpoints, and running GARD on the webserver, which infers none. Is there any explanation for these differences in behaviour? The version I am running locally is the latest version of HYPHY.

**Comment by rdvelazquez** [comment]
I don't have an explanation for the differences but could you share the link to the datamonkey analysis? and also the exact version of HyPhy that you are running locally (you can just type `HYPHYMPI --version`)? It may be helpful for locating the problem or explaining the difference.

**Comment by rdvelazquez** [comment]
Glad to help! Let us know if you have any other issues.

**Comment by jayoung** [comment]
thanks for the fix!
