### ISSUE TITLE
error in "Positive Selection"->"Quickly test for positive selection" 

### ISSUE THREAD

**Issue by gdczoller** [veg/hyphy#809]
When selecting "Positive Selection"->"Quickly test for positive selection" I run into below error: 

Please select the analysis you would like to perform (or press ENTER to return to the list of analysis types):9
Error:
'.return 1;' contained syntax errors, possibly a missing semicolon. ''
Function call stack
1 : ExecuteAFile from file "qndhelper1.ibf" using basepath /cluster/project/gdc/shared/tools/hyphy/lib/hyphy/TemplateBatchFiles/.

This is on a centos7 using the latest Hyphy version 2.3.920180621beta(MP). 
Any ideas what's missing?

**Comment by spond** [comment]
Dear @gdczoller,

I recently changed the HBL parser to be less permissive to syntax errors (like missing semicolons); what you see is an old analysis file that used to work **despite** having syntactic errors, but no longer does. I'll fix that issue before the next release. 

However, this analysis has been **deprecated** in favor of much improved (and extended) versions. Please see http://hyphy.org/tutorials/current-release-tutorial/#using-hyphy-to-detect-selection to get started.

Best,
Sergei
