### ISSUE TITLE
BUSTED branch selection on data monkey

### ISSUE THREAD

**Issue by harturchin** [veg/hyphy#811]
This problem seems to be similar to #738. I want to use the BUSTED method to test specific nodes or terminal branches. However, for any alignment I seem to get the same BUSTED model fit no matter which branches are selected. I uploaded two examples (internal nodes only, terminal leaves only). The log files for all runs have the same set of branches to be tested (all branches), and have nearly the same values for model parameters. Thanks for any help or suggestions.
Mike
[BUSTED_internal_nodes_only.log](https://github.com/veg/hyphy/files/2139345/BUSTED_internal_nodes_only.log)
[BUSTED_terminal_leaves_only.log](https://github.com/veg/hyphy/files/2139346/BUSTED_terminal_leaves_only.log)

**Comment by stevenweaver** [comment]
Dear @harturchin, 

Thank you for bringing this to our attention. This issue is related to #813 in that the TREES are not being stripped from the original NEXUS file, therefore HyPhy is using the unannotated tree instead of the annotated one. I will need to investigate how to squash this bug for good.

Best,
Steven

**Comment by harturchin** [comment]
Thanks Steven!

Sent from my iPhone

On Jun 28, 2018, at 10:50 AM, Steven Weaver <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear @harturchin<https://github.com/harturchin>,

Thank you for bringing this to our attention. This issue is related to #813<https://github.com/veg/hyphy/issues/813> in that the TREES are not being stripped from the original NEXUS file, therefore HyPhy is using the unannotated tree instead of the annotated one. I will need to investigate how to squash this bug for good.

Best,
Steven

**Comment by stevenweaver** [comment]
Dear @harturchin, 

Thank you for catching this issue so quickly! It was introduced in 1.1.10 due to overlooked poor merge. 

Best,
Steven
