### ISSUE TITLE
Datamonkey webpage classic bug

### ISSUE THREAD

**Issue by ChariteVirology** [veg/hyphy#812]
I would like to use the Datamonkey classic server but an analysis is blocking this site since more than 140 hours now an it is impossible to use the platform. I dont think the analysis does take that much time but I rather think it is a bug. 

Could you somehow help me? Or tell me which person to contact who is in charge of this?

Thank you in advance and best regards

**Comment by stevenweaver** [comment]
Dear @ChariteVirology, 

I believe I've resolved the issue with Datamonkey Classic, please try again. 

Best,
Steven
