### ISSUE TITLE
Missing data and GARD analysis

### ISSUE THREAD

**Issue by mstagliamonte** [veg/hyphy#821]
Dear  Authors,

I am running GARD.bf command line on a computer cluster using SNP data. The run successfully completes and only find one partition. When opening the final output file though I notice the following:
```

BEGIN CHARACTERS;
        DIMENSIONS NCHAR = 13597;
        FORMAT
                DATATYPE = DNA
                GAP=-
                MISSING=?
                NOLABELS
        ;
```

The fasta file is correctly recognized as DNA, but the missing character is "?", while on my file missing data are coded as "N". Is there an option I can use to change this when calling GARD.bf? Or should I rather edit the fasta file? Should I repeat the analysis after re-coding for missing data, or should I not worry about the reliability of the results?

Thank you for your kind attention,
Max

**Comment by spond** [comment]
Dear @mstagliamonte,

`N` and `?` are synonymous in this context. Both will be recognized as 4-way missing data.

Best,
Sergei

**Comment by mstagliamonte** [comment]
Thank you for the prompt answer!

Regards,
Max
