### ISSUE TITLE
BUSTED batch directory errors

### ISSUE THREAD

**Issue by dmvelasco** [veg/hyphy#822]
Hello, I am attempting to run BUSTED for a batch of all genes in the genome on a cluster and have received the following error 

```Could not read command file in ExecuteAFile.
Original path: 'libv3/all-terms.bf'.
Expanded path: '/share/apps/hyphy-2.3.13/lib/TemplateBatchFiles/SelectionAnalyses/libv3/all-terms.bf'
```
With only read/execute access to this directory, I found that the `libv3` directory is actually at  `/share/apps/hyphy-2.3.13/lib/TemplateBatchFiles/libv3` not at `/share/apps/hyphy-2.3.13/lib/TemplateBatchFiles/SelectionAnalyses/libv3`. Thus I attempted to work around this issue by making local directory copies of `/share/apps/hyphy-2.3.13/lib/TemplateBatchFiles/libv3`, `/share/apps/hyphy-2.3.13/lib/TemplateBatchFiles/SelectionAnalyses/modules`, and `BUSTED.bf`. However using the path to the local `BUSTED.bf` brought the following error in which it appears something is duplicating the `libv3` in the path to `UtilityFunctions.bf`, and possibly `IOFunctions.bf`, as seen below.

```Could not read command file in ExecuteAFile.
Original path: 'libv3/UtilityFunctions.bf'.
Expanded path: '/local-path/libv3/libv3/UtilityFunctions.bf'
```

Also see messages 1 and 2 below
```Function call stack
1 : LoadFunctionLibrary from file"libv3/UtilityFunctions.bf" using basepath /local-path/libv3/.
        Standard input redirect:
                000000000001 : Universal
                000000000002 : /fasta-path/gene.fa
                000000000003 : /tree-path/tree.tree
                000000000004 : All
                000000000005 :
                -------
2 : LoadFunctionLibrary from file"IOFunctions.bf" using basepath /local-path/libv3/.
        Standard input redirect:
                000000000001 : Universal
                000000000002 : /fasta-path/gene_msa.fa
                000000000003 : /tree-path/tree.tree
                000000000004 : All
                000000000005 :
                -------
3 : LoadFunctionLibrary from file"libv3/UtilityFunctions.bf" using basepath /local-path/.
        Standard input redirect:
                000000000001 : Universal
                000000000002 : /fasta-path/gene_msa.fa
                000000000003 : /tree-path/tree.tree
                000000000004 : All
                000000000005 :
                -------
```
Any suggestions or workarounds for this situation? Thank you!

**Comment by dmvelasco** [comment]
Another directory issue with `convenience/regexp.bf` (below), which I found located at `libv3/convenience/regexp.bf`

```Could not read command file in ExecuteAFile.
Original path: 'convenience/regexp.bf'.
Expanded path: '/local-path/convenience/regexp.bf'

Function call stack
1 : LoadFunctionLibrary from file"convenience/regexp.bf" using basepath /local-path/.
        Standard input redirect:
                000000000001 : Universal
                000000000002 : /fasta-path/gene_msa.fa
                000000000003 : /tree-path/tree.tree
                000000000004 : All
                000000000005 :
                -------
```

Thanks in advance for any assistance.

**Comment by spond** [comment]
Dear @dmvelasco,

When you execute HyPhy, you can pass it the `LIBPATH` argument, which should point to the directory **enclosing** `TemplateBatchFiles`, so sounds like you could call

```
$HYPHYMP LIBPATH=/share/apps/hyphy-2.3.13/lib/ 
```

Best,
Sergei

**Comment by dmvelasco** [comment]
Thanks so much for your help! That appears to have alleviated my issues.
