### ISSUE TITLE
MEME analysis breaks around 3 hours

### ISSUE THREAD

**Issue by cksajil** [veg/hyphy#823]
I tried to do MEME analysis on [this file](https://raw.githubusercontent.com/cksajil/Bioinfo/master/Input.fsa) via [Datamonkey web server](http://datamonkey.org/). Genetic code selected was 'Universal code'. The program runs for around 3 hours and breaks. The error log can be found [here](https://raw.githubusercontent.com/cksajil/Bioinfo/master/MEMElog.txt). I tried several times and the error persists. I could successfully complete other analysis like Fubar, Slac, and Fel on the same input file. Kindly help.

**Comment by spond** [comment]
Dear @cksajil,

Let me investigate. 

Best,
Sergei

**Comment by cksajil** [comment]
Dear @spond,
Thank you for following this up. I could access the results you sent. I also tried to run the same via staging.datamonkey.org as you suggested, but the problem still persists and returned error within ten minutes.

Best,
Sajil
