### ISSUE TITLE
PRIME analysis

### ISSUE THREAD

**Issue by GmmPalomar** [veg/hyphy#824]
I have read some article where they run PRIME on the Datamonkey server but I have not found how to do it. Could anyone recommend me some guide or explain how to do it? Thanks in advance

**Comment by spond** [comment]
Dear @GmmPalomar,

You should be able to perform the analysis on classic.datamonkey.org 
A version for the new data monkey is being developed.

Best,
Sergei

**Comment by GmmPalomar** [comment]
Thank you. However, after trying several times, I always get this message:

This job appears to have expired. This could be caused by an interrupted connection to the cluster, power outage or site maintenance. Please resubmit this job and sorry for any inconvenience!

Is there any site maintenance or may be related with my University connection? 

Best,
Gmm

**Comment by rdvelazquez** [comment]
@GmmPalomar the issue is likely related to a recent power outage affecting our server. We will let you know as soon as we have classic.datamonkey.org running correctly again (Hopefully before mid-afternoon EST). Sorry about that.

Best,
Ryan

**Comment by GmmPalomar** [comment]
Dear Prof. Pond,
I have tried from different locations and with different input files (those that work for other analyses). PRIME error is still there. Could you check if there is any issue with this analysis on the classic.datamonkey server please? Thanks in advance

Best,
Gmm

**Comment by rdvelazquez** [comment]
@GmmPalomar datamonkey classic is now back up and running and able to process PRIME jobs. Thanks for your patience. 

Best,
Ryan

**Comment by GmmPalomar** [comment]
Thanks a lot! Now it is working 

Best,
Gmm

**Comment by tigerxu** [comment]
Report an issue when running prime analysis on the DataMonkey server online. I tried several times and got the message below

This error has been reported to the datamonkeys responsible for this. Sorry, we will fix the issue as soon as possible. In the meantime, it may be worthwhile rerunning your analysis to see if the condition is transient.

I have performed the other analysis FEL, MEME, SLAC. All these run well.

Many thanks for helping look at it!

**Comment by rdvelazquez** [comment]
Reopening this issue now as we seem to be having issues with PRIME on classic again. Also see @tigerxu 's comments in issue #856

**Comment by rdvelazquez** [comment]
Dear @tigerxu,

Getting PRIME back up and running on Datamonkey Classic is still on our list but may not get done in the next few weeks. Just wanted to give you a heads up.

We will be porting PRIME over to the newer version of HyPhy and the current Datamonkey site (datamonkey.org) in the future to coincide with the method being published (not sure when that will be). 

Sorry for any inconvenience this may cause.

Best,
Ryan

**Comment by tigerxu** [comment]
Dear Ryan,

Still get error information on Datamonkey Classic. Detailed information
below

http://classic.datamonkey.org/spool/upload.557813217722089.1_prime.php
http://classic.datamonkey.org/cgi-bin/datamonkey/jobStatus.pl?file=upload.557813217722089.1

I'm wondering if I'm missing something. Many thanks for your help!

Best wishes,
Zhuofei

**Comment by rdvelazquez** [comment]
Tracking progress toward porting PRIME to the new version of HyPhy in #710.

**Comment by rduraescarvalho** [comment]
Hey all, 

Now I am also getting the same message:

"This job appears to have expired. This could be caused by an interrupted connection to the cluster, power outage or site maintenance. Please resubmit this job and sorry for any inconvenience!"

Would be the classic Datamonkey out of service?

Thanks,

Ricardo.
