### ISSUE TITLE
Datamonkey server problem?

### ISSUE THREAD

**Issue by karenbobier** [veg/hyphy#827]
I have been trying to get on datamonkey.org to analyze some files and I keep getting a 502 Bad Gateway message.

**Comment by stevenweaver** [comment]
Dear @karenbobier, 

We're aware of the issue. Our datacenter has been experiencing intermittent power issues. It should be back up by the end of the day today. 

Best,
Steven

**Comment by stevenweaver** [comment]
Dear @karenbobier, 

datamonkey.org should once again be up. Sincerest apologies for the disruption. We are currently investigating ways to make datamonkey more robust against power failures.

Best,
Steven
