### ISSUE TITLE
14hrs and No results

### ISSUE THREAD

**Issue by Rosseroni** [veg/hyphy#832]

**Comment by Rosseroni** [comment]
I should mention that for my project I am trying to run BUSTED on 11 nucleotide alignments in Pearson/FASTA format, with all stop codons removed, but again it just keeps saying job running.

And this is what I can see in what I am calling the standard output, but I cannot get past this to anything else, its just running:


Analysis Description
--------------------
BUSTED (branch-site unrestricted statistical test of episodic
diversification) uses a random effects branch-site model fitted jointly
to all or a subset of tree branches in order to test for alignment-wide
evidence of episodic diversifying selection. Assuming there is evidence
of positive selection (i.e. there is an omega > 1), BUSTED will also
perform a quick evidence-ratio style analysis to explore which
individual sites may have been subject to selection.

- __Requirements__: in-frame codon alignment and a phylogenetic tree (optionally annotated
with {})

- __Citation__: *Gene-wide identification of episodic selection*, Mol Biol Evol.
32(5):1365-71

- __Written by__: Sergei L Kosakovsky Pond

- __Contact Information__: spond@temple.edu

- __Analysis Version__: 1.2



####Choose Genetic Code

1. [**Universal**] Universal code. (Genebank transl_table=1).
2. [**Vertebrate mtDNA**] Vertebrate mitochondrial DNA code. (Genebank transl_table=2).
3. [**Yeast mtDNA**] Yeast mitochondrial DNA code. (Genebank transl_table=3).
4. [**Mold/Protozoan mtDNA**] Mold, Protozoan and Coelenterate mitochondrial DNA and the Mycloplasma/Spiroplasma code. (Genebank transl_table=4).
5. [**Invertebrate mtDNA**] Invertebrate mitochondrial DNA code. (Genebank transl_table=5).
6. [**Ciliate Nuclear**] Ciliate, Dasycladacean and Hexamita Nuclear code. (Genebank transl_table=6).
7. [**Echinoderm mtDNA**] Echinoderm mitochondrial DNA code. (Genebank transl_table=9).
8. [**Euplotid Nuclear**] Euplotid Nuclear code. (Genebank transl_table=10).
9. [**Alt. Yeast Nuclear**] Alternative Yeast Nuclear code. (Genebank transl_table=12).
10. [**Ascidian mtDNA**] Ascidian mitochondrial DNA code. (Genebank transl_table=13).
11. [**Flatworm mtDNA**] Flatworm mitochondrial DNA code. (Genebank transl_table=14).
12. [**Blepharisma Nuclear**] Blepharisma Nuclear code. (Genebank transl_table=15).
13. [**Chlorophycean mtDNA**] Chlorophycean Mitochondrial Code (transl_table=16).
14. [**Trematode mtDNA**] Trematode Mitochondrial Code (transl_table=21).
15. [**Scenedesmus obliquus mtDNA**] Scenedesmus obliquus mitochondrial Code (transl_table=22).
16. [**Thraustochytrium mtDNA**] Thraustochytrium Mitochondrial Code (transl_table=23).
17. [**Pterobranchia mtDNA**] Pterobranchia Mitochondrial Code (transl_table=24).
18. [**SR1 and Gracilibacteria**] Candidate Division SR1 and Gracilibacteria Code (transl_table=25).
19. [**Pachysolen Nuclear**] Pachysolen tannophilus Nuclear Code (transl_table=26).

>Please choose an option (or press q to cancel selection):

>Select a coding sequence alignment file (`/home/datamonkey/datamonkey-js-test/app/busted/../../.hyphy/res//TemplateBatchFiles/SelectionAnalyses/`) 

>Please select a tree file for the data: (`/home/datamonkey/datamonkey-js-test/app/busted/../../.hyphy/res//TemplateBatchFiles/SelectionAnalyses/`) 
>Loaded a multiple sequence alignment with **4** sequences, **726** codons, and **1** partitions from `/home/datamonkey/datamonkey-js-test/app/busted/output/5b6a38758a48e40e1bcb5ecf`


####Choose the set of branches to test for selection

1. [**All**] Include all branches in the analysis
2. [**Internal**] Include all internal branches in the analysis
3. [**Leaves**] Include all leaf branches in the analysis
4. [**FG**] Set FG with 5 branches

>Please choose an option (or press q to cancel selection):
1. [**All**] Include all branches in the analysis
2. [**Internal**] Include all internal branches in the analysis
3. [**Leaves**] Include all leaf branches in the analysis
4. [**FG**] Set FG with 5 branches

>Please choose an option (or press q to cancel selection):

### Branches to test for selection in the BUSTED analysis
* Selected 5 branches to test in the BUSTED analysis: `E_COLI, CRYPTOMERIA_JAPONICA, Node1, AMBORELLA, ASPARAGUS`


### Obtaining branch lengths and nucleotide substitution biases under the nucleotide GTR model
* Log(L) = -4801.91, AIC-c =  9629.86 (13 estimated parameters)

### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
* Log(L) = -4705.00, AIC-c =  9450.29 (20 estimated parameters)
* non-synonymous/synonymous rate ratio for *test* =   1.6280

### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
* Log(L) = -4704.42, AIC-c =  9449.14 (20 estimated parameters)
* non-synonymous/synonymous rate ratio for *test* =   1.6749

### Performing the full (dN/dS > 1 allowed) branch-site model fit
* Log(L) = -4691.72, AIC-c =  9431.85 (24 estimated parameters)
* For *test* branches, the following rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     1.000     |   29.367    |                                   |
|         Neutral evolution         |     1.000     |   54.661    |       Collapsed rate class        |
|      Diversifying selection       |    28.915     |   15.972    |                                   |


### Performing the constrained (dN/dS > 1 not allowed) model fit
* Log(L) = -4713.59, AIC-c =  9473.55 (23 estimated parameters)
* For *test* branches under the null (no dN/dS > 1 model), the following rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|         Neutral evolution         |     1.000     |   15.943    |                                   |
|         Neutral evolution         |     1.000     |   29.396    |       Collapsed rate class        |
|         Neutral evolution         |     1.000     |   54.661    |       Collapsed rate class        |

----
## Branch-site unrestricted statistical test of episodic diversification [BUSTED]
Likelihood ratio test for episodic diversifying positive selection, **p =   0.0000**.

**Comment by spond** [comment]
Dear @Rosseroni,

We have had a major equipment malfunction in the datacenter that is hosting datamonkey.org infrastructure, which resulted in repeated power outages and servers going down. We (and others) are working on mitigating the issue, but in the meantime I have two suggestions

1). Try running your job again 
2). Post the URL for the job doesn't complete, so I can check its status on the server.

Best,
Sergei

**Comment by Rosseroni** [comment]
Okay, sorry, I just have no clue what I am doing. I am sorry to hear you are having trouble with your servers. I hope for both of our sakes that is resolved soon! I will resubmit the job now, and here is the URL: http://datamonkey.org/busted/5b6a34558a48e40e1bcb5cdc

Just because I have never done this program before, is there an average time it should take when all goes smoothly?

**Comment by spond** [comment]
Dear @Rosseroni,

The BUSTED job you reference has completed, but the results have not been communicated back to the web server. Please save and view the attached file in http://vision.hyphy.org/BUSTED (use the `Load` button in the top right) 

Looking at the evidence ratio plot 

![screen shot 2018-08-08 at 10 36 43 am](https://user-images.githubusercontent.com/1018513/43844134-034e4ac4-9af7-11e8-9af0-ba9513485304.png)

it seems to me that your file may not have been correctly aligned. You can also see from the tree plot that branch lengths are **very** large (over 1 substitution per site). 

Best,
Sergei


[issue832.BUSTED.txt](https://github.com/veg/hyphy/files/2270644/issue832.BUSTED.txt)

**Comment by Rosseroni** [comment]
Thank you for sending this! The alignment was pretty gappy. Should I pick more similar taxa sequences for a more meaningful comparison?

**Comment by Rosseroni** [comment]
The tree plot in the link you sent shows humans and monkeys, my sequences are all plants. I also have 11 sequences not 9 like the results you sent me show. I am just confused? Also I am seeing a different plot than you, and when I hit the load button it asks me to pick a file and when I do pick the sequence file nothing happens.

**Comment by spond** [comment]
Dear @Rosseroni,

You don't pick the sequence file, you pick the `issue832.BUSTED.txt` file I linked above. You need to first download it to your computer.

I think the alignment is just wrong -- how did you make it?

Best,
Sergei

**Comment by Rosseroni** [comment]
Oh man that makes sense! sorry about that! Let me do that really quick. So we had to take a nucleotide sequence and translate the protein blast it for similar sequences and that produced a list of 20 species with homologous proteins, so i pulled the nucleotide sequences of the protein from NCBI and did a ClustalO alignment, which is what I uploaded. this has been a project over multiple weeks and submissions that have built on the last so I assumed keeping the species with homology from the previous exercises made sense, but it looks like I need to pick some new taxa and do it direct off the nucleotide blast and align those? is ClustalO a good alignment? should I truncate the sequences just to the well aligned regions to cut out the gaps?

**Comment by Rosseroni** [comment]
Can you try this URL: http://datamonkey.org/busted/5b6a34558a48e40e1bcb5cdc

I tried a shorter run of only four sequences to see that would effect run time, and I think I sent you that link instead of the full 11. Really sorry for this. I feel like an idiot needing this much help.

**Comment by spond** [comment]
Dear @Rosseroni,

You should align the protein sequences and then back-translate them to codons. You current alignment clear problems, most notably indels that are not multiples of 3 

```
GCAAAACGCAAGAACCGT---GAGGCCATCA----T---CAG---TA-----C
```

Best,
Sergei

**Comment by stephenshank** [comment]
Dear @Rosseroni,

We've resolved an issue that was causing jobs to hang. Please let me know if you are able to submit a BUSTED job.

Regarding back translation, [pal2nal](https://omictools.com/pal2nal-tool) is one option.

Best,
Stephen

**Comment by Rosseroni** [comment]
thank you! its working!
