### ISSUE TITLE
I can't find FADE in interactive mode

### ISSUE THREAD

**Issue by juliaqr** [veg/hyphy#833]
I would like to run the FADE test in my console interactive mode (Ubuntu) and I cannot find it in the 'selection analyses' section as this tutorial suggested: https://veg.github.io/hyphy-site/tutorials/current-release-tutorial/
Could it be a matter of the version I am using? I'm working with **hyphy-2.3.13**.
I have checked in other sections and I cannot find it either.
Thank you very much!

**Comment by spond** [comment]
Dear @juliaqr,

It is a part of the **2.3.14** release.

Best,
Sergei

**Comment by juliaqr** [comment]
Dear @spond, 
Thank you very much for your answer. I will upgrade my version then.

Best, 
Júlia
