### ISSUE TITLE
Choice of selection analysis

### ISSUE THREAD

**Issue by MarcNiebel** [veg/hyphy#838]
My dataset compromises three transmitting couples of HCV which have been sampled longitudinally infected with genotype 1a. My first transmitting couple constitutes 20 sequences (12 source and 8 recipient ones), second couple constitutes 9 sequences (4 source and 5 recipient ones) and third couple constitutes 11 sequences (8 source and 3 recipient ones). They are all full length genomes.

My question which I am trying to answer is:
Which individual sites are under positive selection?
Looking at your helpful guidelines http://www.hyphy.org/getting-started/#characterizing-selective-pressures and reading the extensive material available the choices to answer that specific question seem to be FEL and or MEME. 
However do I carry out the analysis as individual patients or as transmitting couples or all together as they are all infected with a similar genotype?

Any further guidance would be much appreciated.

**Comment by spond** [comment]
Dear @MarcNiebel,

Considering that your samples have relatively few sequences, I would venture a guess that there will be relatively little power to detect site-level selection. I would do the following 

0). Do a gene-by-gene analysis; genome wide analysis does not contribute any power to individual site inference, and you expect genes to be "units" of evolution anyhow.

1). Run MEME on combined source-recipient pairs. This will indicate which sites are under episodic selection, but you won't know in which subject (or during transmission) 

2). Run RELAX to compare selective pressures between source and recipient (and the transmission branch). This will tell you if selection regimes differ recipients and sources. 

3). Run aBSREL focusing on the transmission branch only to see if there is anything interesting going on during selection.

4). Run Contrast-FEL to look for individual sites that evolve differently between sources and recipients (http://hyphy.org/methods/other/fel-contrast/#fel-contrast)

Best,
Sergei

**Comment by MarcNiebel** [comment]
Hi Sergei,

Thanks for that in depth answer. This is really helpful.

 Do you think an epitope by epitope might even be better at detecting selection than gene by gene?

Kind Regards,

Marc

**Comment by spond** [comment]
Dear @MarcNiebel,

I don't recommend going down to the level of an epitope, because they are too short to enable any degree of robust inference (e.g. branch lengths, substitution biases, etc). 

If **could** combine epitopes into groups, e.g. group A : only source, group B : only recipient, group C: both, group D: neither, and treat those as genomic units. Another option (but you can't run that with stock analyses), is to have substitution rates, i.e. &omega; depend on the epitope class (as defined by the groups above, for example), and run a joint analysis. 

Do you have a specific evolutionary hypothesis you wish to test?

Best,
Sergei

**Comment by MarcNiebel** [comment]
Dear Sergei,

I am looking at whether on transmission there is a significant change in selection pressures and whether these can be attributed to the changing landscape of the immune response therefore why I thought of using epitopes.

Kind regards,

Marc

**Comment by spond** [comment]
Dear @MarcNiebel,

I think your should run two analyses then : both at the level of transmission pairs

1). RELAX, with source and recipient branches in the tree designated as Reference and Test, respectively. Do the sequences form separate clades in the tree?

2). FEL-Contrast to identify which, if any, sites are differentially selected between subjects.

If you have HLA-dervied epitopes, there's another analysis (partitioned by epitopes) that you can do, but I'll have to look at your data and modify some of the scripts. E-mail me if you are interested.

Best,
Sergei

**Comment by MarcNiebel** [comment]
Dear Sergei,

The source and recipient's do not form separate clades per se so I am wondering which branch to choose for RELAX analysis. Attached is one of my gene trees.

Kind Regards,

Marc
[E2 tree.pptx](https://github.com/veg/hyphy/files/2339400/E2.tree.pptx)
