### ISSUE TITLE
GARD stopped

### ISSUE THREAD

**Issue by AdenoV** [veg/hyphy#842]
Hey,
I am trying to detect recombination in some codon alignment. However, after a few hours, datamonkey send me an email in which  says the following:

Your analysis for 5b9a4a2da913185b60116395 had an error.  The error message 
can be found at http://datamonkey.org/gard/5b9a4a2da913185b60116395.

When I visit the GARD analysis webpage, I see the following message:

We're sorry, there was an error processing your job. Please try again, or visit our GitHub issues and create an issue if the issue persists.

I do not understand what is going bad.

Can someone help me?
Thanks,
JR

**Comment by spond** [comment]
Dear @AdenoV,

Sorry about this. Upon examination of log files it seems like your job terminated prematurely (not entirely certain why). Would you please try running it again and letting me know if the problem persists.

Best,
Sergei

**Comment by AdenoV** [comment]
Dear Sergei,

The problem persits with this and other inputs.

JR


Jennifer Risso Ballester
PhD Student Evolución y Salud
Instituto Cavanilles de Biodiversidad y Biologia Evolutiva

________________________________
De: Sergei Pond <notifications@github.com>
Enviado: lunes, 17 de septiembre de 2018 16:09:26
Para: veg/hyphy
Cc: Jennifer Risso Ballester; Mention
Asunto: Re: [veg/hyphy] GARD stopped (#842)


Dear @AdenoV<https://github.com/AdenoV>,

Sorry about this. Upon examination of log files it seems like your job terminated prematurely (not entirely certain why). Would you please try running it again and letting me know if the problem persists.

Best,
Sergei

**Comment by rdvelazquez** [comment]
Hi @AdenoV ,

Sorry for the delayed response.

There were stochastic errors with GARD in hyphy version 2.3.14. datamonkey.org has been modified to use an earlier version of HyPhy (version 2.3.11) for GARD analyses. If you try to run your analyses again they should work without issue.

GARD is being revised to address the stochastic errors for the next (2.4) release.

Best,
Ryan
