### ISSUE TITLE
Choose reference sequence

### ISSUE THREAD

**Issue by Ben7124** [veg/hyphy#846]
Hi,

I am using Datamonkey to test for selection in sites using FEL. Is there anyway to choose a reference sequence in the input upon which to base the numbering of the sites on? For example, Selecton color codes the amino acid sites on a user specified reference sequence. 

Thanks for your assistance.

Ben

**Comment by spond** [comment]
Dear @Ben7124,

Not sure what you mean. The numbering is always based on the alignment you provided (e.g. site 1 gets index 1 and so on). 

@stephenshank : do you have any suggestion based on the MSA viewer you have been developing?

Best,
Sergei

**Comment by stephenshank** [comment]
Dear @Ben7124 and @spond,

A straightforward way to have a correspondence between the sites in your alignment and a reference is to have the reference sequence be part of the alignment. If it is desirable to have certain statistics plotted directly on the alignment, we have begun such visualizations in the [aforementioned alignment viewer](http://alignment.hyphy.org/) (see below), and it should not be too difficult to expand upon them and incorporate the results into Datamonkey.

@Ben7124: can you specify exactly what type of plot you're after? Perhaps the site plot that already exists on the FEL pages, with the ability to view the alignment underneath as in the image below?

Best,
Stephen

![image](https://user-images.githubusercontent.com/8673708/46436190-51365500-c726-11e8-9fc9-1a4550029314.png)
