### ISSUE TITLE
FUBAR Query

### ISSUE THREAD

**Issue by BruceMD** [veg/hyphy#847]
Good afternoon,

I have been trying my best to run a FUBAR analysis on my MSA from the terminal line but I am greatly missing the plot at the moment.
The first thing I do not understand is the necessity and the layout of the tree that needs to be added, and if there is any way of bypassing that as my end goal is to run a few hundred MSA's for Selection Analysis.
As my understanding goes, uploading the Fasta file was sufficient for Data Monkey.

[Orf21Seq.txt](https://github.com/veg/hyphy/files/2450851/Orf21Seq.txt)
[Orf21Tree.txt](https://github.com/veg/hyphy/files/2450852/Orf21Tree.txt)

**Comment by spond** [comment]
Dear @BruceMD,

If you run FUBAR from the command line, you can visualize the resulting JSON files using http://vision.hyphy.org/FUBAR

Please see http://hyphy.org/tutorials/current-release-tutorial/

Best,
Sergei

**Comment by stephenshank** [comment]
Dear @BruceMD,

> ...is it possible to create a Bash script to pass every single file and its corresponding phylogenetic tree to HyPhy then automatically select FUBAR along with its defaults?

Suppose you have files `msa1.fasta`, `tree1.new`, ..., `msa1000.fasta`, `tree1000.fasta`. To achieve what you describe in bash, you can try something like

```
for i in {1..1000};
do (echo 1; echo msa$i.fasta; echo tree$i.new; echo 20; echo 3; echo .5;) | $HYPHY_PATH/HYPHYMP LIBPATH=$HYPHY_PATH/res $HYPHY_PATH/res/TemplateBatchFiles/SelectionAnalyses/FUBAR.bf
done;
```

where `$HYPHY_PATH` is specific to your system (containing the executable `HYPHYMP`, the `res` directory, etc). The series of echos piped into the HyPhy invocation is a programmatic equivalent of manually typing them in.

Please let me know if you run into any issues.

Best,
Stephen
