### ISSUE TITLE
Different results when running GARD via "Classic" interface

### ISSUE THREAD

**Issue by lkelly3** [veg/hyphy#848]
Hello

I have used GARD quite a lot in the past for recombination detection (via what is now called your Classic interface). Recently I ran some tests with your current server (www.datamonkey.org) and for all datasets analysed I got the result "GARD found no evidence of recombination". However, the results did show trees for multiple partitions, and multiple partitions were defined if I exported the "Partitioned data" results file, so I wanted to make sure I wasn't missing some evidence of recombination/misunderstanding the results. 

I ran a test using exactly the same dataset and parameter settings in GARD via datamonkey.org and classic.datamonkey.org. The only difference is that with the classic version I also ran the model selection first, and then specified the best fit model - presumably this happens automatically with the current version? With the current version, no evidence of recombination is found, but with the classic version a single recombination breakpoint is detected with high significance from the KH test (see attached screenshots). Is is expected to get different results from different versions of the server even when using the same parameter settings? Is the GARD algorithm different in the current version? I notice that a different number of potential breakpoints is detected in the classic vs current versions, so I guess there must be some differences in the way GARD is working?

Any insights in to this would be gratefully received!

Many thanks
Laura

![gard_results_current_server](https://user-images.githubusercontent.com/28711507/46729445-4119fa80-cc7d-11e8-921d-b6f78ac96b77.jpg)
![gard_results_classic_server](https://user-images.githubusercontent.com/28711507/46729448-44ad8180-cc7d-11e8-9387-7995187d3f3b.jpg)

**Comment by lkelly3** [comment]
Hi Stephen

Thanks for replying so quickly, I look forward to hearing what you discover!

Laura

**Comment by stephenshank** [comment]
Dear @lkelly3,

Thank you for opening this issue; I believe I've tracked down the source of the discrepancy. Your dataset does indeed show a statistically significant signal for recombination, but a subtle bug was preventing the results page from stating as such.

At this point I can:

1. send you a corrected output JSON via your preferred email address, which can be viewed at http://vision.hyphy.org
2. post the corrected JSON here
3. alert you when this fix is pushed to http://datamonkey.org (should be no later than this time next week) so that the job can be resubmitted

Please let me know how you'd like to proceed.

Best,
Stephen

**Comment by lkelly3** [comment]
Hi Stephen

The 3rd option would be best for me because I think I may be getting the same issue with some other datasets as well.

Thanks for your help
Laura

**Comment by lkelly3** [comment]
Hi Stephen

I've run a test with one of the datasets that previously had no recombination reported when using the beta-gamma rate variation option and GARD is now reporting evidence for recombination (plus I can also see the Recombination report and Topological incongruence report), so I think it is working fine now.

Many thanks
Laura
