### ISSUE TITLE
aBSREL failed with offending likelihood error

### ISSUE THREAD

**Issue by lhui2010** [veg/hyphy#850]
Hello, 

I was running aBSREL to test for positive selection for 29985 orthogroups, 26845 finished successfully. But the rest exited with errors, mostly were offending likelihood like "Error:Internal error, dumping the offending likelihood function to /tmp/hyphy.dumpInternal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-12344.4] does not match the last recorded LF maximum [-12344.1]"

I tried rerun using dataset OG0000004 with the same command but the error remains.

Content of bs file should be fine since there were 26845 tasks succeeded.

**bs file**:
```

fileToExe = "/lustre/home/user/bin/hyphy/lib/hyphy/TemplateBatchFiles/SelectionAnalyses/aBSREL.bf";


inputRedirect = {};
inputRedirect["01"]="Universal";
inputRedirect["02"]="/lustre/home/user/project/buzzo/OrthoFinder/running/maize_v1.1/Alignments/OG0000044/OG0000044.fna";
inputRedirect["03"]="/lustre/home/user/project/buzzo/OrthoFinder/running/maize_v1.1/Alignments/OG0000044/OG0000044.nwk";
inputRedirect["04"]="All";

ExecuteAFile( fileToExe, inputRedirect);

```

---

**Software and environment**:
* Software: HYPHY 2.3.14.20180809beta(MP) for Linux on x86_64 (built with Conda)
* System: CentOS 7.4
* File system: lustre

The command I use was  `HYPHYMP OG0000044.bs >OG0000044.hyphy_log` .

**The error logs together with data files were also uploaded here**:
* [errors.log](https://github.com/veg/hyphy/files/2482058/errors.log)
* [messages.log](https://github.com/veg/hyphy/files/2482060/messages.log)
* [OG0000044.bs.txt](https://github.com/veg/hyphy/files/2482061/OG0000044.bs.txt)
* [OG0000044.fna.txt](https://github.com/veg/hyphy/files/2482062/OG0000044.fna.txt)
* [OG0000044.hyphy_log.txt](https://github.com/veg/hyphy/files/2482064/OG0000044.hyphy_log.txt)
* [OG0000044.nwk.txt](https://github.com/veg/hyphy/files/2482065/OG0000044.nwk.txt)

Any help would be appreciated!

Many thanks!
Hui

**Comment by spond** [comment]
Dear @Hui,

Many thanks for providing such a detailed bug report. I made some recent fixes in the develop/beta branch that may have repaired the issue. Let me check that it's indeed the case, and I if so, you should be able to run the remaining analyses with the `beta` branch.

Best,
Sergei

**Comment by spond** [comment]
Dear @lhui2010,

I have confirmed that the `beta` branch of HyPhy is able to complete the analyses. Please note that the example you provided has effectively _infinite_ branch lengths for some of the branches, which indicates a potential alignment / homology detection problem, and this is also why you were seeing issues with the current version of HyPhy.

Best,
Sergei

**Comment by lhui2010** [comment]
Dear @spond, 

Many thanks for your quick and detailed reply. I'm glad to know that beta version works and thanks for your work. Also, thanks for notifying of the infinite branches. I'll have a check on the alignments. 

Best, 
Hui

**Comment by lhui2010** [comment]
Dear @spond,

The cmake command documented in README.md to install HYPHY to separate directory seemed to be deprecated. 

I used `cmake -DINSTALL_PREFIX=/location/of/choice`  to install HYPHY into a separate directory yesterday, but it always gave me a warning that this command was not used. HYPHYMP could be compiled though. But every time of executing it gave me a warning: `Batch file to run: (`/usr/local/lib/hyphy/`)"`, the error persisted even if I typed the correct path of bs file. 

I tried executing it in the installation dir, adding to PATH, and stucked here for quite a while and at last I came to Bioconda installation recipe for HYPHY and found that the correct form of installing HYPHY to a non-default directory is `cmake -DCMAKE_INSTALL_PREFIX`. This solves the above problems.

Maybe you can make an fix on the README.md file in your next release. So people like me won't stuck here.

Best regards, 
Hui
