### ISSUE TITLE
Were The p-values of the positive sites adjusted for multiple testing?

### ISSUE THREAD

**Issue by Tiredbird** [veg/hyphy#851]
Dear sir or madame,
I ran SLAC FEL and MEME analysis and I got several positive sites.
I wanted to know the p-values were adjusted for multiple testing.
Could I use them in the paper directly ?  

I hope you can help me. Thank you very much 
Regards,
Mingyue

**Comment by spond** [comment]
Dear @Tiredbird,

No, they are not adjusted for multiple testing, because the traditional setting of multiple testing (multiple tests on the same data) does not directly apply here. 

See #188 for a more in-depth discussion.

Best,
Sergei
