### ISSUE TITLE
Can no longer open my completed runs to view my results?

### ISSUE THREAD

**Issue by balasink** [veg/hyphy#857]
How long does the datamonkey server keep out results for different methods? I've ran over 50 methods for different genes using BUSTED, MEME, FUBAR, and aBSREL which I was able to open and view many times but after the website was updated, I can no longer open anything. Even runs that finished just a couple days before the new datamonkey server got updated will not open at all anymore. I've saved all the previous runs .json files and any excel tables but I need to go back to them to visualize some data.

**Comment by rdvelazquez** [comment]
Dear @balasink,

Thanks for reaching out. You are correct that the previous runs are currently not available from datamonkey. We are in the process of porting over the old results files. We will let you know when the results become available again; hopefully within a week or so. If you have an urgent request for specific results files feel free to reach out and we can see if we can get those to you sooner.

Best,
Ryan

**Comment by balasink** [comment]
Thank you for the quick response! I do need a few of them for tomorrow for a meeting - can I send you a list of job titles?

**Comment by rdvelazquez** [comment]
Sure. Please reach out to me at ryan.velazquez0001@temple.edu.

**Comment by rdvelazquez** [comment]
To document for others what was discussed via email with @balasink:

Previous results files that are no longer available at datamonkey.org can now be accessed via previousresults.datamonkey.org. So if, for example, you had a previous result that you could view at datamonkey.org/absrel/abc123 but the result is no longer there, the result can now be viewed at previousresults.datamonkey.org/absrel/abc123.

We will work on a more permanent solution in the future but this is a workable stop-gap in the interim.
