### ISSUE TITLE
Hyphy datamonkey: lost genes

### ISSUE THREAD

**Issue by MarliesMonnens** [veg/hyphy#862]
Hi,
I am working with the BUSTED package implemented on the datamonkey webserver, as I would like to test for positive selection in a particular gene. I made a phylogenetic tree, based on multiple different markers in advance to use as a 'backbone' for this test.
However, in one specific clade in the tree, this one gene I want to test is no longer present. Is this a (theoretical) problem? Could you give me any advice on how to proceed with this analysis, if at all possible?
Many kind regards,
Marlies

**Comment by stevenweaver** [comment]
Dear Marlies, 

In positive selection analyses, I think it is best to focus on the specific clades/lineage that you are interested in. In this scenario, it would be best to omit the clade without the particular gene. 

I believe you may be able to use the tree that you have already built by pruning the clade without the gene of interest. You can use our tool, [phylotree.js](http://phylotree.hyphy.org/). Let us know if you need more help in knowing how to do that.

Best,
Steven
