### ISSUE TITLE
HBL unit tests for 2.4 alpha

### ISSUE THREAD

**Issue by spond** [veg/hyphy#863]
Dear @stephenshank, @stevenweaver, @rdvelazquez,

I have pushed HyPhy v2.4.0 alpha to the `develop` branch; it passes a fair number of existing tests, but I need some help fleshing out unit tests, especially since I am going to undertake a push to v2.5 (full base class refactor) before v3.0. 

There are two major tasks that I need help with.

1. Creating unit tests for HBL commands (fairly straightforward)
2. Testing viability of legacy standard analyses: do they run with 2.4 and do they serve a useful purpose.

Let's focus on [1] for the time being. A good prototype for a unit test can be found at https://github.com/veg/hyphy/blob/develop/tests/hbltests/UnitTests/HBLCommands/GetString.bf

A unit test will pick a single HBL command (e.g. `GetString`), which in this case is a polymorphic command which retrieves various "string" like attributes and such from various objects, and runs it through both valid and invalid inputs to ensure correct output and error handling. You should be able to follow the same fairly simple code structure to design tests for other commands. 

As you can see `tests/hbltests/UnitTests/HBLCommands` contains a small subset of test, which I would like to expand to cover the complete set of HBL commands. There is some limited documentation for what the command are meant to be doing at our wiki page http://hyphy.org/w/index.php/Category:HBL_Command and also http://hyphy.org/w/index.php/Category:HBL_Built-in_function for built-in functions.

Correctness can be checked in a variety of ways.

1. We wish to compare that 2.4 produces output / behavior as 2.3.x does. Some of the error messages changed in 2.4, but the same conditions should trigger errors, and for valid input, the results should be the same. This means that for **new** unit tests, they should be run in 2.3.xx **and** 2.4.

2. For some functions (e.g. built-ins), you know what the correct answer is from external sources (e.g. mathematical functions)

Below I am providing a table of commands / built-ins that we need to write tests for. My vision was that all four of us strive to write and commit a unit test **per working day** (so four unit tests per day, or ~20 per week). Clearly some will be more time consuming that others, and if bugs are revealed, I will be the primary person to fix them (although help is always welcome). Please make pull requests directly to the `veg` branch for individual tests. 

#### Built-ins (functions)

The trick for these is to test them on all data types that HyPhy supports : __None (null), Numbers, Strings, Matrices, Dictionaries, Topologies, Trees__. Obviously some operations do not make sense for some types, and some are defined (e.g. Tree[index]), but don't have a common meaning (i.e. they are specific to HyPhy).

The checked items have existing tests.

- [x]  ! @rdvelazquez (The array functionality isn't documented and doesn't seem to work as expected; see [this line](https://github.com/veg/hyphy/pull/871/files#diff-e79180c9424fcbbe4dfd6187a76f2038R30))
- [x]  != @rdvelazquez
- [x]  $ @rdvelazquez
- [x]  % @rdvelazquez
- [x]  & @rdvelazquez
- [x]  && @rdvelazquez (String modifiers 2 {escape special characters} and 3 {escape new line} don't seem to work; see [this line](https://github.com/veg/hyphy/pull/871/files#diff-1616d03622e0742952ffe0daba4bdc75R40))
- [x]  * @rdvelazquez
- [x]  + @rdvelazquez
- [x]  - @rdvelazquez
- [x]  / @rdvelazquez
- [x]  < @rdvelazquez
- [x]  <= @rdvelazquez
- [x]  == @rdvelazquez (not in docs)
- [x]  > @rdvelazquez
- [x]  >=  @rdvelazquez
- [x]  Abs - [3900af1e62e3a854c6a6314adadf6d4833131f8a]
- [x]  Arctan - [3900af1e62e3a854c6a6314adadf6d4833131f8a]
- [x]  Beta (Beta function) @rdvelazquez
- [x]  BranchCount @rdvelazquez
- [x]  BranchLength
- [x]  BranchName @rdvelazquez
- [x]  CChi2 (Cumulative chi^2) @rdvelazquez
- [x]  CGammaDist (Cumulative Gamma) @rdvelazquez
- [x]  Call @rdvelazquez
- [x]  Columns @rdvelazquez
- [x]  Cos - @stephenshank
- [x]  Differentiate
- [x]  Eigensystem @rdvelazquez
- [x]  Erf @rdvelazquez
- [x]  Eval @rdvelazquez
- [x]  Exp - [3900af1e62e3a854c6a6314adadf6d4833131f8a]
- [x]  Format @rdvelazquez
- [x]  Gamma - @stephenshank
- [x]  GammaDist @rdvelazquez 
- [x]  IBeta (Incomplete Beta function) @stephenshank
- [x]  IGamma (Incomplete Gamma function) @stephenshank
InvChi2 (Inverse Chi^2) @stephenshank (not used; should be deprecated)
- [x]  Inverse
- [x]  Join
- [x]  LUDecompose (Matrix LU decomposition) @rdvelazquez 
- [x]  LUSolve (Solve a linear system using the LU decomposition) @rdvelazquez 
- [x]  LnGamma @stephenshank
- [x]  Log - [ba88bef6b271925f8e4a86ee5cdcb05dc0b86abf] 
- [x]  MAccess (this is the bracket, i.e. element access operation for matrices, trees, strings) @rdvelazquez 
- [x]  Max - [1c2e731a7ed1698d8f50d6c538572bba77fc9446]
- [x]  Min - @rdvelazquez (Topology still fails; [@spond : need to review the ported COT code])
PSTreeString (slated for deprecation)
- [x]  Random @rdvelazquez 
- [x]  RerootTree
- [x]  Rows @rdvelazquez 
- [x]  Simplex (Simplex integer programming)
- [x]  Simplify (simplify expression) @rdvelazquez (not in docs)
- [x]  Sin - @stephenshank
- [x]  Sqrt - @stephenshank
TEXTreeString (slated for deprecation)
- [x]  Tan - @stephenshank
- [x]  Time @rdvelazquez 
- [x]  TipCount
- [x]  TipName
- [x]  Transpose @stephenshank
- [x]  Type
- [x]  ZCDF (standard normal cumulative DF) - @stephenshank
- [x]  ^ - @stephenshank
- [x]  || - @stephenshank

#### HBL commands / operations

- [x] #include [adcb0da1133758e16e7850357564e4337dacd5cc]
#profile (a helper function for profiling code... no batch test needed)
- [ ] AlignSequences @spond is going to look at it (@rdvelazquez attempted in #892 but wasn't able to get it working)
- [x] assert @rdvelazquez
- [x] BayesianGraphicalModel (This may be of note: https://github.com/veg/hyphy/tree/master/tests/hbltests/BayesianGraphicalModels)
- [x] break @rdvelazquez 
- [x] category @rdvelazquez 
ChoiceList (This is for the GUI and I'm assuming should slated for deprecation)
- [x] ClearConstraints - @stevenweaver 
- [x] continue @rdvelazquez
- [x] DataSet @rdvelazquez
- [x] DataSetFilter @rdvelazquez
- [x] DeleteObject
- [x] Differentiate
- [x] do{ @rdvelazquez
- [x] DoSQL
- [x] else @stephenshank (tested as part of `if`)
- [x] ExecuteAFile @rdvelazquez
- [x] ExecuteCommands @rdvelazquez
- [x] Export
- [x] ffunction @rdvelazquez
- [x] FindRoot [8a60f0faa7f72ff6c9857e60b35c4bc7012af137]
- [x] for @rdvelazquez
- [x] fprintf @rdvelazquez
- [x] fscanf @rdvelazquez
- [x] function @rdvelazquez
- [x] GetDataInfo
- [x] GetInformation @rdvelazquez 
GetNeutralNull // slated for deprecation 
- [x] GetString
- [x] GetURL
- [x] HarvestFrequencies - @stevenweaver 
- [x] if - @stephenshank
Import (not in docs) (isn't used in the selection analysis BFs or in the GARD bf; I assume this should be deprecated)
- [x] Integrate [274015d61b855937410c9da12fb9f0cdb139be51]
LFCompute (Some likelihood testing is done via testiphy) (Doesn't appear to be used much at all, https://github.com/veg/hyphy/search?q=LikelihoodFunction3&unscoped_q=LikelihoodFunction3, should this be deprecated?)
- [x] lfunction @rdvelazquez
- [ ] LikelihoodFunction - @stevenweaver (Some likelihood testing is done via testiphy)
- [ ] LikelihoodFunction3 (Not in docs; Some likelihood testing is done via testiphy)
- [x] LoadFunctionLibrary @rdvelazquez
- [x] Model @rdvelazquez 
- [ ] MolecularClock - @stevenweaver
- [ ] MPIReceive - @stevenweaver
- [ ] MPISend - @stevenweaver
- [x] namespace @spond 
- [x] ReplicateConstraint - @stevenweaver
- [x] RequireVersion @rdvelazquez 
- [x] return @rdvelazquez
SCFG (Not in docs; Likely slated for deprecation {not used in TemplateBatchFiles/}; This may be of note: https://github.com/veg/hyphy/tree/master/tests/hbltests/UnitTests/HBLCommands/res/SCFG)
SetDialogPrompt (Not sure of an easy way to automate a test for SetDialogPrompt)
- [x] SimulateDataSet @rdvelazquez 
- [x] sscanf (not in docs) @rdvelazquez 
StateCounter // slated for deprecation 
- [x] Topology @rdvelazquez 
- [x] Tree @rdvelazquez 
- [x] while

Best,
Sergei

**Comment by stevenweaver** [comment]
Hi @rdvelazquez, 

Can we please comment out the failing tests and mark them as `TODO`? 
https://travis-ci.org/veg/hyphy/jobs/485481054#L1028

Thanks,
Steven

**Comment by rdvelazquez** [comment]
Closing this for now as I think we have achieved the level of testing that we were after.
