### ISSUE TITLE
absrel results tree problem

### ISSUE THREAD

**Issue by anabut123** [veg/hyphy#869]
Hi,

I have a problem when I use absrel on datamonkey server. My output tree doesn't look like a tree at all. There are no branches but if you hover over the nodes you get the node number. It is very difficult to read this data, is that normal or am I doing something wrong? My analysis runs normally and I can select all the branches for analysis in my tree (newick format) without a problem.

Best,
Ana

**Comment by rdvelazquez** [comment]
Hi Ana,

Could you send us a link to your job so that we can take a look at it? I was able to run an aBSREL job and didn't seem to have issues with the tree: http://datamonkey.org/absrel/5c066f2589721376a5c3c940 so seeing your data set will help us to troubleshoot.

Thanks,
Ryan

**Comment by rdvelazquez** [comment]
Hi @anabut123,

I'm closing this issue now but if you are still having problems please provide and example dataset or link so that I can try to reproduce and troubleshoot.

Best,
Ryan
