### ISSUE TITLE
dS values on each branch in SLAC

### ISSUE THREAD

**Issue by yaotli** [veg/hyphy#873]
Hi,

Is it possible to extract the dS values on each branch in SLAC analyses? 
Or is there any .batch file which can calculate the dS values for a given tree?

The purpose here is to get the raw dS values not only between sequences but also between nodes.
I have tried to use CodeML with both (model =0+NSsites = 0 and model = 1+Nsites = 0) models. But I guess these analyses aims to test the selection ( or omega value ) across branch so the dS values are modified to test the hypotheses. 

Very appreciate if anyone has idea.

**Comment by spond** [comment]
Dear @yaotli,

You can use something I wrote a long time ago (for http://hyphy.org/resources/hyphybook2007.pdf).

Download the following batch file : http://www.hyphy.org/phylohandbook/dSdN.bf and run it in the current version of HyPhy.

The output will look something like this, including an entry for the dS tree.

```
Total nucleotide sites :1698
Synonymous  sites      :373.961442083241
Nonsynonymous  sites   :1252.136185463959

Total tree lengths:
	E[syn]        : 0.05569992455178992
	E[non-syn]    : 0.02957197610185132
	dS            : 0.2529096886621986
	dN            : 0.04010204002078083


E[Syn subs/nucleotide site] tree: 
	(CHICKEN_HONGKONG_1997:0.001296611902769635,DUCK_HONGKONG_1997:0.007908310104257932,(DUCK_SHANDONG_2004:0.007233224339257135,(DUCK_GUANGZHOU_2005:0.01353160961906095,CHICKEN_GUANGDONG_2005:0.01034413449311087)Node5:0.008140386369694172)Node3:0.007245647723639221)

E[Non-syn subs/nucleotide site] tree: 
	(CHICKEN_HONGKONG_1997:0.002052986487653492,DUCK_HONGKONG_1997:0,(DUCK_SHANDONG_2004:0.003934707072730336,(DUCK_GUANGZHOU_2005:0.004016893184259723,CHICKEN_GUANGDONG_2005:0.009360918561857978)Node5:0.003038862417928891)Node3:0.007167608377420902)

dS tree: 
	(CHICKEN_HONGKONG_1997:0.005887363677490502,DUCK_HONGKONG_1997:0.03590827568271311,(DUCK_SHANDONG_2004:0.03284299808996012,(DUCK_GUANGZHOU_2005:0.06144128925476509,CHICKEN_GUANGDONG_2005:0.04696831917070363)Node5:0.03696203538723104)Node3:0.03289940739933509)

dN tree: 
	(CHICKEN_HONGKONG_1997:0.002784019099922392,DUCK_HONGKONG_1997:0,(DUCK_SHANDONG_2004:0.005335787502236047,(DUCK_GUANGZHOU_2005:0.005447238651876924,CHICKEN_GUANGDONG_2005:0.01269417807947565)Node5:0.004120948220765063)Node3:0.00971986846650476)

Estimating pairwise dN/dS: total of 10 analyses
```

Best,
Sergei

**Comment by yaotli** [comment]
Dear @spond 
Thanks so much for your prompt reply! I will definately try this out. 

Best,
Yao
