### ISSUE TITLE
MEME do not finish

### ISSUE THREAD

**Issue by AdenoV** [veg/hyphy#877]
Hi everyone,
I am running some MEME jobs on Datamonkey, but becasuse of input is a little bit large, I am running it on staging version of datamonkey webpage. However, jobs appear to do not finish never. Examples of jobs are the following ticket numbers:
-http://staging.datamonkey.org/meme/5c190ca9296e1853ca495701 
-http://staging.datamonkey.org/meme/5c191014296e1853ca4958de

Best regards,
JR

**Comment by AdenoV** [comment]
Thank you so much, Rayan.
So, can I run it throughout hyphy on windows?

**Comment by rdvelazquez** [comment]
@AdenoV sorry for the delayed response. HyPhy is currently available on Mac and Linux but not on Windows. We are planning to update datamonkey to use the newer (soon to be released) version of HyPhy in the next month or so.
