### ISSUE TITLE
Datamonkey job results do not load

### ISSUE THREAD

**Issue by jtpverhoeven** [veg/hyphy#878]
Hi there, 

Just reporting an issue I am currently encountering on DataMonkey across different analysis.

Results of completed jobs are not displayed, leading to an empty screen on open.
Inspecting the  XHR calls on page load shows that the results are being returned, however nothing is drawn on the screen. Could maybe be related to JS errors observed  in the console?

(Tested on Chrome Version 71.0.3578.98 and Firefox Quantum)

![monkey1](https://user-images.githubusercontent.com/13039623/50450025-ae950900-0905-11e9-8b89-94b816097446.png)

![monkey2](https://user-images.githubusercontent.com/13039623/50450029-b785da80-0905-11e9-94ae-e9bd3668adc9.png)

![monkey3](https://user-images.githubusercontent.com/13039623/50450072-05024780-0906-11e9-9083-5cf08e85bb0c.png)

**Comment by spond** [comment]
Dear @jtpverhoeven,

Thank you for this bug report. Looks like the analyses are finishing ('results' is populated), but some `Bootstrap.js` related libraries are not loading. Could you supply the job ID (or full Datamonkey URL) for the analyses where this behavior occurs?

Best,
Sergei

PS Due the current US holidays, it may take us longer than usual to repair issues.

**Comment by jtpverhoeven** [comment]
Hi Sergei,

Here is an example where, on my end at least, the specified behavior occurs: 
https://www.datamonkey.org/fel/5c23a269bdd1573ada2103c7

Thanks for looking into it, if you need any more details let me know.

Cheers,
Joost

**Comment by stevenweaver** [comment]
Dear Joost, 

Thank you for pointing this issue out. It has now been resolved by rebuilding the JavaScript files with webpack.

Best,
Steven

**Comment by kagningemma** [comment]
Dear @spond , 
I am having a similar issue with BUSTED; completed job results can't be displayed in the browser. 

http://datamonkey.org/busted/5f3f4a54503f2f234816652f
http://datamonkey.org/busted/5f3f4a3b503f2f23481664fd

Best Regards,
Emmanuel
