### ISSUE TITLE
Model definition in GARD

### ISSUE THREAD

**Issue by NatJWalker-Hale** [veg/hyphy#882]
Hi guys, 

I am running some GARD analyses through the command line and I just wanted to clarify model specification - in HYPHY, which settings correspond to the classic GTR+G with 4 bins? Is it 012345 with General Discrete on 4 bins, or with Beta-gamma on 4 bins? 

Cheers, 

Nat

**Comment by srwis** [comment]
Hi Nat, 

012345 will give you the GTR model. If you want the +G as in gamma distributed site variation, choose the Beta-Gamma option. Then when prompted choose 4 bins. 

If you want to know more about the General Discrete Distribution and the Beta-Gamma and how they compare I'd check out this [paper.](https://academic.oup.com/mbe/article/22/2/223/963847)

Best,
Sadie
