### ISSUE TITLE
RELAX tree

### ISSUE THREAD

**Issue by babslangille** [veg/hyphy#886]
Hi there,
I'm trying to use RELAX through Datamonkey. If I run a .nex file without a tree in it, it works fine. But everytime I try it with the tree data added, it will load into the main interface and I can assign my reference and test branches, but when I click submit, it sits on the waiting page, never actually starting. I'm not sure the problem. I've tried different tree configurations and no luck. I've attached my file if that helps.
Any help would be greatly appreciated.
Thank you,
Barbara
[HelpFIle.txt](https://github.com/veg/hyphy/files/2765723/HelpFIle.txt)

**Comment by stevenweaver** [comment]
Dear @babslangille, 

The issue appears to be in this line in your NEXUS file:
`Begin trees;`

If you change `Begin` to all upper case, `BEGIN`, the analysis should work. I'll leave this issue open as the line [here](https://github.com/veg/datamonkey-js/blob/master/app/models/msa.js#L133) should not be case-sensitive.

Best,
Steven

**Comment by babslangille** [comment]
Thank you very much. It's working now.
Cheers,
Barbara
