### ISSUE TITLE
FUBAR convergence warning (PSRF & NEFF)

### ISSUE THREAD

**Issue by snaketron** [veg/hyphy#887]
Dear Developers,

perhaps it would be wise to warn/advise FUBAR users when the convergence in their simulation is inadequate (e.g. high PSRF/low NEFF). 

Best

**Comment by spond** [comment]
Dear @snaketron,

Sorry, this fell through the cracks. The new version of FUBAR (in the dev branch) uses a variational Bayes approach by default, which doesn't have the issues with N<sub>eff</sub>.

Best,
Sergei
