### ISSUE TITLE
HYPHYMP spamming /var/log/syslog

### ISSUE THREAD

**Issue by ArtPoon** [veg/hyphy#894]
My student just ran into an unusual problem running HYPHYMP on Ubuntu 16.04 - something was rapidly eating up disk space (nearly 500GB).  We identified the problem as bloated `syslog` files in `/var/log`.  They were filled with the following messages, repeated indefinitely:
```
Jan 30 08:19:24 Langley org.freedesktop.FileManager1[8576]:  Please select type of analyses you want to list (or press ENTER to process custom batch file):#033[2J#033[H     /HYPHY 2.3.14.20190128beta(MP) for Linux on x86_64\
Jan 30 08:19:24 Langley org.freedesktop.FileManager1[8576]: ***************** TYPES OF STANDARD ANALYSES *****************
Jan 30 08:19:24 Langley org.freedesktop.FileManager1[8576]: #011(1) Selection Analyses
Jan 30 08:19:24 Langley org.freedesktop.FileManager1[8576]: #011(2) Evolutionary Hypothesis Testing
Jan 30 08:19:24 Langley org.freedesktop.FileManager1[8576]: #011(3) Relative evolutionary rate inference
```
et cetera.  In other words, the typical HyPhy menu on launching an interactive session.  She had only recently downloaded and installed HYPHYMP and ran a handful of times.  

Some informative outputs:
```
user@Langley:~/git/HyPhy/hyphy$ HYPHYMP --version

HYPHY 2.3.14.20190128beta(MP) for Linux on x86_64
user@Langley:~/git/HyPhy/hyphy$ uname -a
Linux Langley 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by spond** [comment]
Dear @ArtPoon,

Hmm. Clearly this behavior is undesirable. However, HyPhy does not ever write anything directly to `/var/log`. Somehow `stdin` and `stdout` are being redirected in a way to generate this infinite loop. Can you ask your student what sequence of commands created the log issue, i.e. how was HyPhy invoked?

I have never seen this pattern of log spamming before, and I can't immediately figure out how it might happen.

Best,
Sergei

**Comment by ArtPoon** [comment]
Student has no recollection of using redirection operators on the command line, just invoked `HYPHYMP` and mucked about with the standard menu.

**Comment by ArtPoon** [comment]
We'll try to reproduce on our end.  Probably an operating system level issue.  Thanks @spond

**Comment by rdvelazquez** [comment]
Hi @ArtPoon,

Any update on this? Just trying to tie up loose ends before the 2.4 release.

Thanks!
Ryan
