### ISSUE TITLE
Model codes

### ISSUE THREAD

**Issue by babslangille** [veg/hyphy#897]
I'm using HyPhy on my PC and I'm running pairwise relative rates. I'm attempting to use a model not in the list but I'm having difficulty tracking down the 6 number designation. I'm trying to use the MG94 model. What is the code/ where would I find this?
Thanks so much!

**Comment by spond** [comment]
Dear @babslangille,

The standard MG94 is an option in the model dropdown. I would use `MG94customCF3x4` with `012345` model designation. This would represent the Muse Gaut 94 model with corrected frequency estimates, and the GTR nucleotide component.

Best,
Sergei

**Comment by babslangille** [comment]
Dear Sergei,
Thank you for your help. I was foolishly using the nucleotide option, not the codon one.
Cheers,
Barbara
