### ISSUE TITLE
Issue running RELAX

### ISSUE THREAD

**Issue by chasesmith15** [veg/hyphy#898]
Hello,

I am new to HyPhy and attempting to run RELAX but continue to get the error: 
Error:Failed to dereference 'relax.filter.default.site_map'

What would be the cause of this error?

Thanks in advance,
Chase

**Comment by spond** [comment]
Dear @chasesmith15,

Sorry for not responding sooner. How many sites are in your alignment? This error can occur if the alignment is very long (e.g. over 1,000,000 sites). To fix it, you need to add the following line to the `RELAX.bf` file, which can be found in `TemplateBatchFiles/SelectionAnalyses/RELAX.bf`.

```
utility.SetEnvVariable ("USE_MEMORY_SAVING_DATA_STRUCTURES", 1e8);
```

Best,
Sergei

**Comment by chasesmith15** [comment]
Hey Sergei, 

Thanks for responding that worked! I have a concatenated alignment of protein coding loci that is ~120k sites. 

Best,
Chase

**Comment by xuechunxu** [comment]
Hi,

I used `hyphy FitMG94.bf`, and got the same error.  Which file I need to revised?
My commond line:
`hyphy FitMG94.bf --alignment XX.fasta --tree XX.nwk --lrt Yes --type local`

The error:
`Error:Failed to dereference 'fitter.filter.default.site_map'
Failed to dereference 'fitter.filter.default.site_map'`

Thanks
Chun-xu

**Comment by spond** [comment]
Dear @xuechunxu,

This error occurs when your alignment is very long (>100,000 sites). Add `ENV="USE_MEMORY_SAVING_DATA_STRUCTURES=1e10;"` to the command line and the error should go away.

Best,
Sergei

**Comment by xuechunxu** [comment]
Thank you very much, it's worked.
