### ISSUE TITLE
SeqAlignShared.ibf Segfault HyPhy 2.4

### ISSUE THREAD

**Issue by srwis** [veg/hyphy#901]
Segmentation fault occurs when running the first two analysis in the Data File Tools menu SeqAlignment.bf, SeqAlignmentCodon.bf.

I believe these two are all related because they all stop running after they attempt to load SeqAlignShared.ibf 

there is no errors.log.

SeqAlignment.bf messages.log:
[messages.log](https://github.com/veg/hyphy/files/2852306/messages.log)

SeqAlignmentCodon.bf messages.log:
[messages.log](https://github.com/veg/hyphy/files/2852314/messages.log)

**Comment by spond** [comment]
Dear @srwis,

Thanks for reporting. This revealed several issues, which should be fixed in 454ff8dd

Best,
Sergei

**Comment by srwis** [comment]
No longer getting a seg fault for these. They are all reporting actual errors now.
