### ISSUE TITLE
MergeSites.bf and MergeSequences.bf SegFault HyPhy 2.4

### ISSUE THREAD

**Issue by srwis** [veg/hyphy#905]
Both MergeSites.bf and MergeSequences.bf immediately result in a SegFault when chosen from the Data File Tools list. Empty errors and messages log returned for both

**Comment by spond** [comment]
Dear @srwis,

Please check if this is also fixed by 454ff8ddd2cfedc8f6d97ceb2701d72478c63bb1 and close as appropriate.

Best,
Sergei

**Comment by srwis** [comment]
both working now.
