### ISSUE TITLE
Phylogeny Reconstruction SegFaults Hyphy 2.4

### ISSUE THREAD

**Issue by srwis** [veg/hyphy#907]
5 out of 8 of the Phylogeny Reconstruction tests give seg faults so I'm just going to list them all here:

ClusterAnalysis.bf files:
[input.txt](https://github.com/veg/hyphy/files/2852873/input.txt)
[messages.log](https://github.com/veg/hyphy/files/2852874/messages.log)

DistanceMatrix.bf files:
[input.txt](https://github.com/veg/hyphy/files/2852876/input.txt)
[messages.log](https://github.com/veg/hyphy/files/2852877/messages.log)

NeighborJoining.bf files:
[input.txt](https://github.com/veg/hyphy/files/2852881/input.txt)
[messages.log](https://github.com/veg/hyphy/files/2852882/messages.log)

BranchSwap.bf files:
[input_2.txt](https://github.com/veg/hyphy/files/2852885/input_2.txt)

I dug around in BranchSwap.bf a bit and figured out that the seg fault occurs somewhere around a  GetInformation step which might relate these errors to #906 

SequentialAddition.bf files:
[errors.log](https://github.com/veg/hyphy/files/2852897/errors.log)
[input.txt](https://github.com/veg/hyphy/files/2852898/input.txt)

**Comment by spond** [comment]
Seems to have been resolved with #904 issue fix
