### ISSUE TITLE
utility:ForEachPair-error

### ISSUE THREAD

**Issue by Gmogeras** [veg/hyphy#913]
Hello!
I'm starting using Hyphy for a selection analysis with MEME. I have a sequence fasta file with the species name in number, the same for the species-tree. When i start the analysis i have the next lines:
###Obtaining branch lenghts and nucleotide substitution biases under the nucleotide GTR model
###Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases.
###Improving branch lengths, nucleotide substitution biases, and global dN/dS ratio under a full codon model.
**ERROR:
utility.ForEachPair is non re-entrant in call to assert....**

The rest of the file i will upload it with my input, the error.log and a copy of the error message in screen. When this happend, the analysis stops with another lines reporting error, each one of this lines mentions the "utility.ForEachPair" module. 
What could i ve do to repair this? Is it because of my input files? I hope you could help me.
[error.txt](https://github.com/veg/hyphy/files/2902823/error.txt)
[errors.log](https://github.com/veg/hyphy/files/2902824/errors.log)
[CodonSeqFile-SpTree.txt](https://github.com/veg/hyphy/files/2902853/CodonSeqFile-SpTree.txt)

**Comment by spond** [comment]
Dear @Gmogeras,

Could you please try running the code in the `develop` branch? This is the one we are actively developing, so the issue you are seeing may not be present there.

```
$git checkout https://github.com/veg/hyphy.git hyphy-2.4
$cd hyphy-2.4
$git checkout develop
$cmake ./
$make 
$./HYPHYMP 

or

$mpirun ./HYPHYMPI ... or whatever your MPI environment expects

```

Best,
Sergei
