### ISSUE TITLE
Error when try to compile Hyphy 2.4.0 alpha

### ISSUE THREAD

**Issue by kmeusemann** [veg/hyphy#921]
Hi,

I am new to Hyphy - and later need to run (either busted or relaxed) on several thousand files (thus non-interactively, command line etc which seems also to be a bit tricky and complex).
Maybe stupid, but I fail already to generate a executable (I have version cmake 3.5.1, installed additionally 
- sudo apt-get install libcurl4-gnutls-dev
- sudo apt install ocl-icd-opencl-dev

I get same errors no matter if I tray make MP, make MPI or make HYPHYMPI, make GTEST
### I get warnings already doing cmake (path here replaced by KM):

cmake .

(I searched here and other platforms but cannot figure out the problem):

Set compiler flags to -fsigned-char -O3 -std=gnu++14 -march=corei7-avx -mtune=corei7-avx -g 
-- Configuring done
WARNING: Target "HYPHYMP" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "HYPHYOCL" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "HYPHYMPI" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
-- Generating done
-- Build files have been written to: /home/KM/hyphy-2.4.0-alpha.1

What does it mean - do i have to change something somwhere? (CMakeLists / other files - I am not familiar with C++ though)

when i then still try to go on it also gives me errors I don't understand and don't know how to fix them.
(probably caused by message above)..

HELP much appreciated! 
Many thanks Karen

###

/home/KM/hyphy-2.4.0-alpha.1$ make MP
Scanning dependencies of target HYPHYMP
[  5%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/batchlanhelpers.cpp.o
[  5%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/variable.cpp.o
[  5%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/constant.cpp.o
[ 10%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/batchlan.cpp.o
[ 10%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/matrix.cpp.o
[ 10%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/avllistxl_iterator.cpp.o
[ 10%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/string_file_wrapper.cpp.o
[ 15%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/polynoml.cpp.o
[ 15%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/global_object_lists.cpp.o
[ 15%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/alignment.cpp.o
[ 20%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/batchlan2.cpp.o
[ 20%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/avllistx_iterator.cpp.o
[ 20%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/category.cpp.o
[ 25%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/parser2.cpp.o
[ 25%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/tree_iterator.cpp.o
[ 25%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/string_buffer.cpp.o
[ 30%] Building CXX object CMakeFiles/HYPHYMP.dir/src/core/dataset_filter.cpp.o
/home/KM/hyphy-2.4.0-alpha.1/src/core/dataset_filter.cpp: In member function ‘long unsigned int _DataSetFilter::FindUniqueSequences(_SimpleList&, _SimpleList&, _SimpleList&, short int) const’:
/home/KM/hyphy-2.4.0-alpha.1/src/core/dataset_filter.cpp:170:43: error: call of overloaded ‘_String(long unsigned int&, bool)’ is ambiguous
         _String         state1 (unit,false),
                                           ^
In file included from /home/KM/hyphy-2.4.0-alpha.1/src/core/include/parser.h:46:0,
                 from /home/KM/hyphy-2.4.0-alpha.1/src/core/include/translation_table.h:45,
                 from /home/KM/hyphy-2.4.0-alpha.1/src/core/include/dataset.h:45,
                 from /home/KM/hyphy-2.4.0-alpha.1/src/core/include/dataset_filter.h:44,
                 from /home/KM/hyphy-2.4.0-alpha.1/src/core/dataset_filter.cpp:42:
/home/KM/hyphy-2.4.0-alpha.1/src/core/include/hy_strings.h:243:3: note: candidate: _String::_String(const _String&, long unsigned int)
   _String(const _String &str, unsigned long copies);
   ^
/home/KM/hyphy-2.4.0-alpha.1/src/core/include/hy_strings.h:151:5: note: candidate: _String::_String(hyFloat, unsigned char)
     _String(const hyFloat number, unsigned char digits_of_precision);
     ^
/home/KM/hyphy-2.4.0-alpha.1/src/core/include/hy_strings.h:140:3: note: candidate: _String::_String(hyFloat, const char*)
   _String(const hyFloat number, const char *format = nil);
   ^
/home/KM/hyphy-2.4.0-alpha.1/src/core/dataset_filter.cpp:171:27: error: call of overloaded ‘_String(long unsigned int&, bool)’ is ambiguous
         state2 (unit,false);
                           ^
In file included from /home/KM/hyphy-2.4.0-alpha.1/src/core/include/parser.h:46:0,
                 from /home/KM/hyphy-2.4.0-alpha.1/src/core/include/translation_table.h:45,
                 from /home/KM/hyphy-2.4.0-alpha.1/src/core/include/dataset.h:45,
                 from /home/KM/hyphy-2.4.0-alpha.1/src/core/include/dataset_filter.h:44,
                 from /home/KM/hyphy-2.4.0-alpha.1/src/core/dataset_filter.cpp:42:
/home/KM/hyphy-2.4.0-alpha.1/src/core/include/hy_strings.h:243:3: note: candidate: _String::_String(const _String&, long unsigned int)
   _String(const _String &str, unsigned long copies);
   ^
/home/KM/hyphy-2.4.0-alpha.1/src/core/include/hy_strings.h:151:5: note: candidate: _String::_String(hyFloat, unsigned char)
     _String(const hyFloat number, unsigned char digits_of_precision);
     ^
/home/KM/hyphy-2.4.0-alpha.1/src/core/include/hy_strings.h:140:3: note: candidate: _String::_String(hyFloat, const char*)
   _String(const hyFloat number, const char *format = nil);
   ^
CMakeFiles/HYPHYMP.dir/build.make:446: recipe for target 'CMakeFiles/HYPHYMP.dir/src/core/dataset_filter.cpp.o' failed
make[3]: *** [CMakeFiles/HYPHYMP.dir/src/core/dataset_filter.cpp.o] Error 1
CMakeFiles/Makefile2:227: recipe for target 'CMakeFiles/HYPHYMP.dir/all' failed
make[2]: *** [CMakeFiles/HYPHYMP.dir/all] Error 2
CMakeFiles/Makefile2:170: recipe for target 'CMakeFiles/MP.dir/rule' failed
make[1]: *** [CMakeFiles/MP.dir/rule] Error 2
Makefile:201: recipe for target 'MP' failed
make: *** [MP] Error 2

**Comment by ArtPoon** [comment]
Can you please provide some details about your system?  *e.g.*, run `cat /proc/version` if you're running Linux.  I also suggest trying a slightly older release of HyPhy - you're using 2.4 alpha, which is pretty bleeding edge.

**Comment by spond** [comment]
Dear @kmeusemann,

That's a picky compiler you have there, but it found a real issue, which I just fixed in the develop branch. Try

```
git clone https://github.com/veg/hyphy.git hyphy-dev
cd hyphy-dev 
git checkout develop
cmake ./
make install
```

As far as running multiple files, should be pretty straightforward via a shell script. How are your data formatted? Do you have a directory of alignments + trees?

Best,
Sergei

**Comment by kmeusemann** [comment]
1) ArtPoon: Linux version 4.4.0-142-generic (buildd@lgw01-amd64-033) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) ) #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019
-> what version shall I use then?

2) @Sergej: 
ok i will try - and let you know how it goes!  thanks :))
yes shell script but i have to figfure out exactly how etc - yes i have alignments & respective trees (and knowledge what i wanna take as forground - we aim to try relax (and maybe busted and/or aBSREL - not sure yet, but first i must get it to run and run e.g. 2 example files at all... 

Best Karen

**Comment by kmeusemann** [comment]
Dear Sergej:

that worked thanks and looked good but I still get warnings about the HYPHYMP, HYPHYMPI etc. (see below). When i than after make install try again 
make MP or make MPI etc same errors as yesterday. 

Does the command above automatically install MP or only HyPhy that can run on 1 thred (CPU) only?
 (aim would be to use MP / and or MPI so multiple threads)

sudo make install then also seemed to work... but see above.
I am also wondering - can i call it somehow, is it then located in /usr/local/lib/hyphy
I see no HYPHY executable in the folder i did cmake etc - so i again fail a bit.

when running the test script (I changed here HYPHYMP tp HYPHY is also gives me:
./run_unit_tests.sh 
./tests/hbltests/UnitTests/HBLCommands/Abs.bf
./run_unit_tests.sh: line 16: /home/meusemann/Programs/HYPHY_dev/hyphy-dev/HYPHY: No such file or directory
altough at the end it tells me : 
###-----------------------ALL TEST PASSED------------------------------------...

also i find a lot here:
/usr/local/lib/hyphy/
ChartAddIns      GeneticCodes         TemplateBatchFiles  UserAddins
data             SubstitutionClasses  TopologyInference
DatapanelAddIns  SubstitutionModels   TreeAddIns
b

but where is the executable then?
(I also tried providing a prefix but that does not work either. sorry for bothering...

a step fw compared to yesterday, still i think not there yet...

best Karen

/home/meusemann/Programs/HYPHY_dev/hyphy-dev/run_tests.sh

-- Install configuration: ""
-- Up-to-date: /usr/local/lib/hyphy
-- Up-to-date: /usr/local/lib/hyphy


thanks & best
Karen

###

cmake ./
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_AVX_EXTENSIONS
-- Performing Test HAVE_AVX_EXTENSIONS - Success
Set compiler flags to -fsigned-char -O3 -std=gnu++14 -march=corei7-avx -mtune=corei7-avx -g 
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.47.0") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so  
-- Found MPI_C: /usr/lib/openmpi/lib/libmpi.so  
-- Found MPI_CXX: /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so  
-- Configuring done
WARNING: Target "HYPHYMP" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "HYPHYOCL" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "HYPHYMPI" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
-- Generating done
-- Build files have been written to: /home/meusemann/Programs/HYPHY_dev/hyphy-dev

**Comment by spond** [comment]
Dear @kmeusemann,

By default the binary goes to `/usr/local/bin`. You can try

```
$which HYPHYMP
```

to see if the binary is in your path.

Best,
Sergei

PS @rdvelazquez can you please follow up to make sure our installer/test scripts work out of the box as expected? They definitely should

**Comment by kmeusemann** [comment]
did it and its not in my PATH (also again checking with echo $PATH what its in my PATH, so 
it must have gone somewhere else - but not sure how to find out where. 

when i specify a special place for the installation as described in the readme: 

`mkdir -p /opt/hyphy`
`cmake -DINSTALL_PREFIX=/opt/hyphy .

that dow not work: -> no executable is there.
all additional files are however in /usr/local/lib/hyphy ...

maybe you can again write to install it locally specified, i can try again (make install does also not work either , works only with sudo, but then again - not in usr/local/bin neither user/bin etc pp...)

**Comment by kmeusemann** [comment]
quick note: i now try an older version, but here have again (but different) problems will try to solve it - 
hoping still for an solution for the current version. Aim is to run RELAX and BUSTED - I read now all tutorials wiki etc - but are there for example some EXAMPLE files how exactly the tree is labeled then (in Newick etc) 
(so input files - alignment / tree / batchfile examples for BUSTED/RELAXED) ?

Many thanks again Karen

**Comment by kmeusemann** [comment]
Hi,
I finally made it to install properly HYPHY(MP), after solvinmg some other issues with libraries (connected with ld - so I have now executables:  :) ! HYPHYMP (yeah...) but only for the previous version : hyphy-2.3.14/
appreciate if issues with the most current version are solved .

still looking for some example files for Busted/Relax - (trees and input batch files) - are they in tests or examples? Also - what is the difference between  /RELAX-Groups.bf, RELAX.bf and RELAX-SRV.bf ?

Thanks again for all help! Karen

**Comment by rdvelazquez** [comment]
Hi @kmeusemann,

Thank you for letting us know about the issues. I hope my comments below are somewhat helpful:

__Building HYPHYMP:__
Version 2.4.0-alpha is still under active development. It builds fine on the systems I'm able to test on but I will be working on improving the build system soon and the details of the issues you came across are helpful. Thanks again for sharing these! I'll reach out to you when I come across answers to your specific build questions.

__Example Files:__
- Busted does not require labeled branches and can be run on any dataset (see for example `./tests/hbltests/data/CD2.nex`)
- Example fasta for relax (same for both trees): [relax-fasta.txt](https://github.com/veg/hyphy/files/2970814/relax-fasta.txt)
- Example newick for relax: [relax_testOnly-newick.txt](https://github.com/veg/hyphy/files/2970815/relax_testOnly-newick.txt)
- Another example newick for relax: [relax_testAndRef-newick.txt](https://github.com/veg/hyphy/files/2970816/relax_testAndRef-newick.txt)

__Difference between RELAX batch files:__
- Relax has undergone some changes in version 2.4:
     - In version 2.3.14 (and previous versions) relax needed a set of "test" branches and a set of reference branches. HyPhy recognizes branch labels as anything in curly brackets (`{anything_here}`) in the newick tree. You are prompted to select which set of branches you want to use as the test set so the `anything_here` doesn't need to be a specific label. HyPhy also recognizes unlabeled branches (i.e. no curly brackets) as a set of branches so if you only have one set of labeled branches you can just use the "unlabeled branches" as the reference set
     - In version 2.4 you will be able to run relax on more than just two sets of branches. This functionality was previously provided via a separate batch file (`RELAX-Groups.bf`) but will be incorporated into the standard `RELAX.bf` batch file in version 2.4 onward.

Additionally, I will note that we are working on providing standard command line invocation with keyword arguments for hyphy in version 2.4 which will make your batch analysis of thousands of files more straight forward than working around the interactive prompts. RELAX has yet to be ported over to use command line arguments but is next on my list. Busted should be good to go.

**Comment by spond** [comment]
Dear @kmeusemann,

Take a look at http://hyphy.org/tutorials/current-release-tutorial/#use-relax-to-compare-selective-pressures-on-different-parts-of-the-tree for a tutorial.

Best,
Sergei

**Comment by kmeusemann** [comment]
Dear Ryan,
Hi,

thansk so much for the feedback :))
some notes: 
1) in the tutrorials http://hyphy.org/tutorials/phylotree/
there is that you for Busted need labeled branches: in case i wanna do with BUSTED on at least  I aim to  specify a set of foreground branches on which to test for positive selection (remaining branches are designated "background") - so here i need the branch labeled correct? - thanks for the links above :)

2) versions: for now I must stick to version 2.3.14 since 2.4.  I am not able to get latter working. Anyway the option > 2 sets of branches in future versions will be great and I will push back to later since its i think useful and interesting :) (for first analyses i only have 2 sets of branches though).

3) working directly with command line will be invcredibly useful becaus alsthough it might be not too difficult to have this workaroubnd with creating batchfiles (that capture the interactive mode commands) for me is quite not that convenient - so I will hilghy appreciate this :+1: 
 :-)

@spond : thasnks a lot again for the link!
I missed that the alignment file includes the labeled tree at the bottom...

##

trying around with the batch file now  (aim to analyse a lot genes for different species against all others species so quite a lot to analyse...

Many thanks again
Karen

**Comment by rdvelazquez** [comment]
Hi @kmeusemann,

I'm currently checking to make sure our install/test scripts work as expected. Could you try a few things to help me pinpoint your exact issue?

1. Make sure you have the following dependencies installed:
   - cmake >= 3.12
   - gcc >= 4.9
   - libcurl
   - libpthread
   - openm
2. Clone hyphy into a new directory `git clone http://github.com/veg/hyphy hyphy-test-build`
3. `cd hyphy-test-build`
4. `git checkout develop`
5. `cmake .` (note the "dot" after cmake)
6. `make install`

After running through these steps could you:
1. Let me know what you get with `which hyphy`
2. If there is a `hyphy` on your PATH (i.e. `which hyphy` does not return "no hyphy in..."), continue on, if not, run `make hyphy` and see if that creates an executable (`hyphy`) in the `hyphy-test-build` directory
3. Send me (post here as an attachment or email me at ryan.velazquez0001@temple.edu) the contents of the Makefile that is in the `hyphy-test-build` directory.
4. If you now have a `hyphy` executable, try running `hyphy slac --alignment <path_to_an_alignment_file> --tree <path_to_a_corresponding_tree_file>` and see if that runs.
5. Let me know if there's anything else that you think might be helpful for locating your issue.

Best,
Ryan

relates to #930

**Comment by kmeusemann** [comment]
Dear Ryan,

since I am currently running a lot jobs, i probably will move testing to a later point when i have more time 
to do testing: 
short info: I have cmake 3.5.1 (in the readme it was as requirenment > 3.0 ... maybe that solved then already the issue, anyway i would liket to stick to the currently running version...
gcc >= 4.9: gcc >= 4.9
libcurl: yes done
libpthread: yes done
openm: yes done

when i follow above still its installed in by path - and overwriting the now running version correct?  so either i install it locally or i will come back when i have finished my other analyses - would that be ok? (or i try an additional computer).

many thanks
Karen

**Comment by rdvelazquez** [comment]
Sounds good. No rush.

**Comment by kmeusemann** [comment]
short question: do yopu mean with openm
openmpi ?

Best, Karen
(I uninstalled now cmake from the rpositories, installing 3.14.1 - but its gives me a could of weired messages,,... hope my system will still work... fingers crossed :))

**Comment by kmeusemann** [comment]
Dear Ryan,

now trying what you wrote above:
along with the step make install I got the next error:


meusemann@oekoxx:~/Programs/hyphy-test-build$ make install
Scanning dependencies of target hyphy
[  0%] Building CXX object CMakeFiles/hyphy.dir/src/core/_hyExecutionContext.cpp.o
[  5%] Building CXX object CMakeFiles/hyphy.dir/src/core/alignment.cpp.o
[  5%] Building CXX object CMakeFiles/hyphy.dir/src/core/associative_list.cpp.o
[  5%] Building CXX object CMakeFiles/hyphy.dir/src/core/avllist.cpp.o
[ 10%] Building CXX object CMakeFiles/hyphy.dir/src/core/avllistx.cpp.o
[ 10%] Building CXX object CMakeFiles/hyphy.dir/src/core/avllistx_iterator.cpp.o
[ 10%] Building CXX object CMakeFiles/hyphy.dir/src/core/avllistxl.cpp.o
[ 15%] Building CXX object CMakeFiles/hyphy.dir/src/core/avllistxl_iterator.cpp.o
[ 15%] Building CXX object CMakeFiles/hyphy.dir/src/core/baseobj.cpp.o
[ 15%] Building CXX object CMakeFiles/hyphy.dir/src/core/batchlan.cpp.o
[ 15%] Building CXX object CMakeFiles/hyphy.dir/src/core/batchlan2.cpp.o
[ 20%] Building CXX object CMakeFiles/hyphy.dir/src/core/batchlanhelpers.cpp.o
[ 20%] Building CXX object CMakeFiles/hyphy.dir/src/core/batchlanruntime.cpp.o
[ 20%] Building CXX object CMakeFiles/hyphy.dir/src/core/calcnode.cpp.o
[ 25%] Building CXX object CMakeFiles/hyphy.dir/src/core/category.cpp.o
[ 25%] Building CXX object CMakeFiles/hyphy.dir/src/core/constant.cpp.o
[ 25%] Building CXX object CMakeFiles/hyphy.dir/src/core/dataset.cpp.o
[ 30%] Building CXX object CMakeFiles/hyphy.dir/src/core/dataset_filter.cpp.o
[ 30%] Building CXX object CMakeFiles/hyphy.dir/src/core/dataset_filter_numeric.cpp.o
[ 30%] Building CXX object CMakeFiles/hyphy.dir/src/core/fisher_exact.cpp.o
[ 30%] Building CXX object CMakeFiles/hyphy.dir/src/core/formula.cpp.o
[ 35%] Building CXX object CMakeFiles/hyphy.dir/src/core/formula_parsing_context.cpp.o
[ 35%] Building CXX object CMakeFiles/hyphy.dir/src/core/fstring.cpp.o
[ 35%] Building CXX object CMakeFiles/hyphy.dir/src/core/global_object_lists.cpp.o
[ 40%] Building CXX object CMakeFiles/hyphy.dir/src/core/global_things.cpp.o
[ 40%] Building CXX object CMakeFiles/hyphy.dir/src/core/hbl_env.cpp.o
[ 40%] Building CXX object CMakeFiles/hyphy.dir/src/core/likefunc.cpp.o
[ 40%] Building CXX object CMakeFiles/hyphy.dir/src/core/likefunc2.cpp.o
/home/meusemann/Programs/hyphy-test-build/src/core/likefunc2.cpp: In member function ‘_List* _LikelihoodFunction::RecoverAncestralSequencesMarginal(long int, _Matrix&, const _List&, bool)’:
/home/meusemann/Programs/hyphy-test-build/src/core/likefunc2.cpp:896:50: error: call of overloaded ‘_String(long int&, bool)’ is ambiguous
     _String      codeBuffer    (unitLength, false);
                                                  ^
In file included from /home/meusemann/Programs/hyphy-test-build/src/core/include/parser.h:46:0,
                 from /home/meusemann/Programs/hyphy-test-build/src/core/include/category.h:43,
                 from /home/meusemann/Programs/hyphy-test-build/src/core/include/likefunc.h:44,
                 from /home/meusemann/Programs/hyphy-test-build/src/core/likefunc2.cpp:44:
/home/meusemann/Programs/hyphy-test-build/src/core/include/hy_strings.h:243:3: note: candidate: _String::_String(const _String&, long unsigned int)
   _String(const _String &str, unsigned long copies);
   ^
/home/meusemann/Programs/hyphy-test-build/src/core/include/hy_strings.h:151:5: note: candidate: _String::_String(hyFloat, unsigned char)
     _String(const hyFloat number, unsigned char digits_of_precision);
     ^
/home/meusemann/Programs/hyphy-test-build/src/core/include/hy_strings.h:140:3: note: candidate: _String::_String(hyFloat, const char*)
   _String(const hyFloat number, const char *format = nil);
   ^
/home/meusemann/Programs/hyphy-test-build/src/core/likefunc2.cpp:900:59: error: call of overloaded ‘_String(long int, bool)’ is ambiguous
         (*result) < new _String(siteCount*unitLength,false);
                                                           ^
In file included from /home/meusemann/Programs/hyphy-test-build/src/core/include/parser.h:46:0,
                 from /home/meusemann/Programs/hyphy-test-build/src/core/include/category.h:43,
                 from /home/meusemann/Programs/hyphy-test-build/src/core/include/likefunc.h:44,
                 from /home/meusemann/Programs/hyphy-test-build/src/core/likefunc2.cpp:44:
/home/meusemann/Programs/hyphy-test-build/src/core/include/hy_strings.h:243:3: note: candidate: _String::_String(const _String&, long unsigned int)
   _String(const _String &str, unsigned long copies);
   ^
/home/meusemann/Programs/hyphy-test-build/src/core/include/hy_strings.h:151:5: note: candidate: _String::_String(hyFloat, unsigned char)
     _String(const hyFloat number, unsigned char digits_of_precision);
     ^
/home/meusemann/Programs/hyphy-test-build/src/core/include/hy_strings.h:140:3: note: candidate: _String::_String(hyFloat, const char*)
   _String(const hyFloat number, const char *format = nil);
   ^
CMakeFiles/hyphy.dir/build.make:413: recipe for target 'CMakeFiles/hyphy.dir/src/core/likefunc2.cpp.o' failed
make[2]: *** [CMakeFiles/hyphy.dir/src/core/likefunc2.cpp.o] Error 1
CMakeFiles/Makefile2:232: recipe for target 'CMakeFiles/hyphy.dir/all' failed
make[1]: *** [CMakeFiles/hyphy.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

##

running it with sudo it again failed. also i have no executable

 note: candidate: _String::_String(hyFloat, const char*)
   _String(const hyFloat number, const char *format = nil);
   ^
CMakeFiles/hyphy.dir/build.make:413: recipe for target 'CMakeFiles/hyphy.dir/src/core/likefunc2.cpp.o' failed
make[2]: *** [CMakeFiles/hyphy.dir/src/core/likefunc2.cpp.o] Error 1
CMakeFiles/Makefile2:232: recipe for target 'CMakeFiles/hyphy.dir/all' failed
make[1]: *** [CMakeFiles/hyphy.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

###

then I checked: there is no hyphy executable in the hyphy-test-build directory

## i then tried locally "make hyphy" 
again giving me the same error and no executable:
make hyphy
[  0%] Building CXX object CMakeFiles/hyphy.dir/src/core/likefunc2.cpp.o
/home/meusemann/Programs/hyphy-test-build/src/core/likefunc2.cpp: In member function ‘_List* _LikelihoodFunction::RecoverAncestralSequencesMarginal(long int, _Matrix&, const _List&, bool)’:
/home/meusemann/Programs/hyphy-test-build/src/core/likefunc2.cpp:896:50: error: call of overloaded ‘_String(long int&, bool)’ is ambiguous
     _String      codeBuffer    (unitLength, false);
                                                  ^
In file included from /home/meusemann/Programs/hyphy-test-build/src/core/include/parser.h:46:0,
                 from /home/meusemann/Programs/hyphy-test-build/src/core/include/category.h:43,
                 from /home/meusemann/Programs/hyphy-test-build/src/core/include/likefunc.h:44,
                 from /home/meusemann/Programs/hyphy-test-build/src/core/likefunc2.cpp:44:
/home/meusemann/Programs/hyphy-test-build/src/core/include/hy_strings.h:243:3: note: candidate: _String::_String(const _String&, long unsigned int)
   _String(const _String &str, unsigned long copies);
   ^
/home/meusemann/Programs/hyphy-test-build/src/core/include/hy_strings.h:151:5: note: candidate: _String::_String(hyFloat, unsigned char)
     _String(const hyFloat number, unsigned char digits_of_precision);
     ^
/home/meusemann/Programs/hyphy-test-build/src/core/include/hy_strings.h:140:3: note: candidate: _String::_String(hyFloat, const char*)
   _String(const hyFloat number, const char *format = nil);
   ^
/home/meusemann/Programs/hyphy-test-build/src/core/likefunc2.cpp:900:59: error: call of overloaded ‘_String(long int, bool)’ is ambiguous
         (*result) < new _String(siteCount*unitLength,false);
                                                           ^
In file included from /home/meusemann/Programs/hyphy-test-build/src/core/include/parser.h:46:0,
                 from /home/meusemann/Programs/hyphy-test-build/src/core/include/category.h:43,
                 from /home/meusemann/Programs/hyphy-test-build/src/core/include/likefunc.h:44,
                 from /home/meusemann/Programs/hyphy-test-build/src/core/likefunc2.cpp:44:
/home/meusemann/Programs/hyphy-test-build/src/core/include/hy_strings.h:243:3: note: candidate: _String::_String(const _String&, long unsigned int)
   _String(const _String &str, unsigned long copies);
   ^
/home/meusemann/Programs/hyphy-test-build/src/core/include/hy_strings.h:151:5: note: candidate: _String::_String(hyFloat, unsigned char)
     _String(const hyFloat number, unsigned char digits_of_precision);
     ^
/home/meusemann/Programs/hyphy-test-build/src/core/include/hy_strings.h:140:3: note: candidate: _String::_String(hyFloat, const char*)
   _String(const hyFloat number, const char *format = nil);
   ^
CMakeFiles/hyphy.dir/build.make:413: recipe for target 'CMakeFiles/hyphy.dir/src/core/likefunc2.cpp.o' failed
make[3]: *** [CMakeFiles/hyphy.dir/src/core/likefunc2.cpp.o] Error 1
CMakeFiles/Makefile2:232: recipe for target 'CMakeFiles/hyphy.dir/all' failed
make[2]: *** [CMakeFiles/hyphy.dir/all] Error 2
CMakeFiles/Makefile2:244: recipe for target 'CMakeFiles/hyphy.dir/rule' failed
make[1]: *** [CMakeFiles/hyphy.dir/rule] Error 2
Makefile:229: recipe for target 'hyphy' failed
make: *** [hyphy] Error 2

###

the makefile attached here (compressed as zip).

I hope that unless all done this hyphy 2.3.14 still works, it does not give me anything now typing which hyphy - which it did beofore doing all this.. anyway i can obviously still call it globally -> HYPHYMP gives me then the interactive mode of the previously successfully installed hyphy version:
$ HYPHYMP
    /HYPHY 2.3.14.20190314beta(MP) for Linux on x86_64\
[Makefile.zip](https://github.com/veg/hyphy/files/3043266/Makefile.zip)

**Comment by rdvelazquez** [comment]
Thanks for trying that out @kmeusemann! A few things:  

1. > do you mean with "openm" actually openmpi ?  

That should have been "openmp". Sorry about that. I don't think this is causing your issue though.  

2. HYPHYMP 2.3.14 should still work fine

3. I don't immediately know why hyphy 2.4.0 isn't building for you but now that you have gone through those steps and provided the info I should have everything I need to look into it further so thank you! 

I'll get back to you once I locate the issue.

**Comment by stevenweaver** [comment]
Dear @rdvelazquez, 

I would like to add that I also have the exact same error as @kmeusemann when trying to build develop using gcc 5. 

Best,
Steven

**Comment by rdvelazquez** [comment]
Thank you @stevenweaver. I don't have the issue when using aocc 1.2.1 on linux and AppleClang 10.0.0 on mac. I'll try to reproduce with gcc and troubleshoot.

**Comment by rdvelazquez** [comment]
@kmeusemann I can confirm that this issue occurs with gcc 5 but not with gcc 6... If you would like to use the develop branch and can get gcc 6 that may be the fastest way and the path with the least resistance.

@spond The issue that gcc 5 is having may have been introduced with:
- https://github.com/veg/hyphy/commit/91ce09c8a39466236f87173b2559f36593bdbd63#diff-c53dda11276f6252eac4048840459f38R142
and/or 
- https://github.com/veg/hyphy/commit/91ce09c8a39466236f87173b2559f36593bdbd63#diff-afbc595c25d435ba8efa51f611b7f20fR156

See:
- https://travis-ci.org/rdvelazquez/hyphy/jobs/515912403#L418 
and 
- https://travis-ci.org/rdvelazquez/hyphy/jobs/515912403#L428

**Comment by spond** [comment]
Dear @rdvelazquez,

That's actually a real bug left over from refactoring -- I am fixing it in the next push. 

Best,
Sergei

**Comment by kmeusemann** [comment]
ok sounds good - (and glad that I am not the only one with that problem.
Sergei/Ryan: ok then plan is to install gcc v6 and try again from ryan above?
also if there are options to run it on command line directly (instead of generating files that catch interactively mode) are highly appreciated!

Best Karen

**Comment by rdvelazquez** [comment]
@kmeusemann just to provide an update:
- Feel free to install gcc v6 and trying to compile the develop branch if you want
- @spond is working on a fix to allow the develop branch to compile with gcc v5 (he's already addressed one issue, but there's another issue as well)
- There are options to run RELAX on the command line directly (just recently implemented in the develop branch). You can run `HYPHYMP relax --help` to see the arguments that you should provide. This is still in active development so you may see strange behavior and please reach out to us if you do.

We'll let you know once the gcc v5 issue is resolved.

**Comment by spond** [comment]
Dear all,

The gcc5 issues should have been resolved with the current develop branch

Best,
Sergei

**Comment by kmeusemann** [comment]
Dear Sergei & Ryan: 

1) I successfully could compile now the 2.4.0alpha version form the developer bracnch using currently gcc gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)  and  cmake version 3.14.1
2) I reran the one analyses with RELAX that failed in version 2.3.14: it works now and the "main" result but several values are different , I post this to #930 

Many thanks 
Karen
