### ISSUE TITLE
Error Running BGM with 2.4 (develop branch)

### ISSUE THREAD

**Issue by rdvelazquez** [veg/hyphy#923]
When running BGM with the default parameters (using various datasets including the CD2.nex dataset `./tests/hbltests/libv3/data/CD2.nex`) I get the following error:

`Error:
BGM_MCMC_SAMPLES must be positive and less than BGM_MCMC_MAXSTEPS - BGM_MCMC_BURNIN`

I'm running on mac using the interactive command line prompt. I've confirmed that the same file and parameters work with version 2.3.14. I've attached the error.log, messages.log and full command line printout for reference.

@ArtPoon - Let me know if you have any thoughts. I'll look into finding and fixing the issue as well.

[errors.log](https://github.com/veg/hyphy/files/2970653/errors.log)
[messages.log](https://github.com/veg/hyphy/files/2970654/messages.log)
[commandLineOutput.txt](https://github.com/veg/hyphy/files/2970655/commandLineOutput.txt)

**Comment by srwis** [comment]
I'm getting the same error and when I run HyPhy in debug mode and test if BGM_MCMC_SAMPLES < (BGM_MCMC_MAXSTEPS - BGM_MCMC_BURNIN) it is and it is positive as well so I'm not sure what going on here. You can see this check at the bottom of input.txt

[errors.log](https://github.com/veg/hyphy/files/3008879/errors.log)
[input.txt](https://github.com/veg/hyphy/files/3008880/input.txt)
[messages.log](https://github.com/veg/hyphy/files/3008881/messages.log)

**Comment by rdvelazquez** [comment]
Addressed by https://github.com/veg/hyphy/commit/2d72cd0794c57fcdebdf17928d08b882cb32e3fc
