### ISSUE TITLE
Tree leaf not matching sequence names

### ISSUE THREAD

**Issue by srwis** [veg/hyphy#929]
These bfs return an error:
`"Error:
The leaf of the tree codonTree_2 labeled 'D_CD_83_ELI' had no match in the data filter. Please make sure that all leaf names correspond to a sequence name in the data file."`

but when I look at the files the sequence names match up with the trees leaf names. 

-  CompareSelectivePressure.bf
[errors.log](https://github.com/veg/hyphy/files/3009777/errors.log)
[input.txt](https://github.com/veg/hyphy/files/3009778/input.txt)
[messages.log](https://github.com/veg/hyphy/files/3009779/messages.log)

- CompareSelectivePressureIVL.bf
[errors.log](https://github.com/veg/hyphy/files/3009786/errors.log)
[input.txt](https://github.com/veg/hyphy/files/3009787/input.txt)
[messages.log](https://github.com/veg/hyphy/files/3009788/messages.log)

**Comment by spond** [comment]
These are going to be deprecated. We have contrast-fel in place now.

**Comment by srwis** [comment]
got it. I'll remove them from the list.

**Comment by aftermthplanner** [comment]
ah wait sorry what?  you'll have to forgive me I have incredibly low intelligence, but I'm getting about the same issue, with this decision order:
3 Relative Evolutionary Rate interference
1 (the only option) Infer relative evolutionary rates on a nucleotide or protein alignment, in a spirit similar to Rate4Site
sequence input
tree input
1 - analysis type: protein
1 - protein model: [LG] blah blah blah generalist empirical model of protein evolution from Le and Gascuel(2008)
1 - optimize branch lengths with rate variation?: [Gamma] use a four-category etc etc
and this result:
### Obtaining alignment-wide branch-length estimates
Error:
The leaf of the tree iesi_wYW.tree_0 labeled 'XP_032746792_1_2_404_structural_maintenance_of_chromosomes_protein_1B_Rattus_rattus' had no match in the data filter. Please make sure that all leaf names correspond to a sequence name in the data file.

this is also the first leaf in the tree file, so we assumed it was likely this was a problem throughout, but that could be false.
how exactly does an amateur go about solving this?

**Comment by aftermthplanner** [comment]
Sequence Name:
XP_032746792.1/2-404 structural maintenance of chromosomes protein 1B [Rattus rattus]
Leaf name
XP_032746792.1/2-404_structural_maintenance_of_chromosomes_protein_1B_Rattus_rattus:
I tried chnging the spaces but that did _not_ work

**Comment by spond** [comment]
Dear @aftermthplanner,

Can you please share your input data so I can see exactly what's going on?

Best,
Sergei

**Comment by aftermthplanner** [comment]
fixed it using different software.  turns out it was "-" marks that worked I think.

**Comment by evanho550** [comment]
I'm having the exact same issue as @aftermthplanner . Could you possibly elaborate how this issue was resolved? Sorry, I know this was several years ago. But I also got the same error, and the sequence looks identical in both the tree and the MSA.
