### ISSUE TITLE
error when running RELAX using 2.3.14

### ISSUE THREAD

**Issue by kmeusemann** [veg/hyphy#930]
Dear all,

after finally successful running hundreds of analyses with RELAX and BUSTED, we ran into a problem only for one alignment and tree (note: analysis of the same gene with other forground branches ran fine). The log file (shortened) below (I removed the path).
1.) Any idea/help how to solve that problem?
2) I send alignment and tree to Sergej seperately - just in case

Many thanks :+1: 
Karen

I think something similar was posted here: https://github.com/veg/hyphy/issues/854
but cannot really figure out if this has been solved (if not, I probably would delete analysing this gene maybe). 
######

## Branch sets for RELAX analysis
* Selected 1 branches as the _test_ set: MNAT
* Selected 12 branches as the _reference_ set: [...]
### Obtaining branch lengths and nucleotide substitution biases under the nucleotide GTR model
[...]
### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
[...]
### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
[...]
### Fitting the alternative model to test K != 1
Error:
Internal error, dumping the offending likelihood function to /tmp/hyphy.dump
        ERROR: [_LikelihoodFunction::LocateTheBump (index 4) current value   -7285.328500426617 (parameter =                    0), best value    -7285.29669014139 (parameter = 1.269613219925255e-17)); delta =  0.03181028522703855 ]

Parameter name relax.reference.omega1

Function call stack
1 : Optimize storing into, mles, the following likelihood function:likelihoodFunction ;
        Standard input redirect:
                06 :
                -------
2 : relax.alternative_model.fit=estimators.FitLF(relax.filter_names,relax.trees,{"0":relax.model_map},relax.general_descriptive.fit,relax.model_object_map,{terms.run_options.retain_lf_object:TRUE})
        Standard input redirect:
                06 :
                -------
3 : ExecuteAFile from file "/apps/hyphy/2.3.14/lib/hyphy/TemplateBatchFiles/SelectionAnalyses/RELAX.bf" using basepath [PATH]//IG_PEARCEY_RELAX/. reading input from inputRedirect
{
 "01":"Universal",
 "02":"[PATH]/IG_PEARCEY_RELAX/ORTHOMCL0005878/Mnat/ORTHOMCL0005878.linsi.nt.fas.trimmed.fas",
 "03":"[PATH]//IG_PEARCEY_RELAX/ORTHOMCL0005878/Mnat/ORTHOMCL0005878_excluded_taxa_TREE.tre",
 "04":"test",
 "05":"Minimal",
 "06":""
}
-------
        
error when running RELAX using 2.3.14

**Comment by spond** [comment]
Dear Karen,

I have made a number of changes to RELAX in v2.4 alpha release. Could you please try to see if using that release will address the issue?

Best,
Sergei

**Comment by kmeusemann** [comment]
Dear Sergej,
thanks a lot - but I struggled last time to install 2.4 (even with the dev. branch tc) to install it and generate a executable - has this been also maybe fixed? otherwise notr sure how to try it out. I send you tree and alignment separately, so maybe you can try it (instead that i again try to install 2.4.alpha?).
Many thanks Karen

**Comment by rdvelazquez** [comment]
@kmeusemann The gcc 5 issue has been resolved (see https://github.com/veg/hyphy/issues/921) and you should now be able to build the develop branch.

Let us know if your RELAX issue is fixed in the develop branch or if you run into any issues.

Best,
Ryan

**Comment by kmeusemann** [comment]
Dear Spond & Ryan,

its fixed, see also #921, and the RELAX issue seems to be solved. Several values are quite different comparing the version Sergei ran for me and what I get now te last HYPHY version. I send you this in a separate emails since data are confidential. Basically I'd need to know if this matters in the end or not: I ran many many analyses already with 2.3.14
and I'd need to run more (Reference genes) now with the new version but if values are not compüarable I am actually unsure if I then need to calculate everything from scratch ? :-/
many thanks so far, more via email!

Best Karen

**Comment by spond** [comment]
Dear @kmeusemann,

Some differences between 2.3.14 and 2.4 are to be expected. I have revised RELAX.bf extensively for 2.4 (it is now at version 3), to improve convergence and enable additional features. Generally, v2.4 results are to be preferred. However, if you already have 2.4 and 2.3.14 results for some file, you could check log-likelihood scores for the same model on the same alignment, and see which version yields better fits.

Best,
Sergei

**Comment by kmeusemann** [comment]
Dear Sergei,
maybe you can look quickly into what I sent you vial email as well!
Thanks Karen

**Comment by kmeusemann** [comment]
Hi Sergei,

okay got it. many thanks for commenting! I will use 2-4-0-alpha from (current method), developer branch then! (Or shall I use another version?)
Many thanks, hope that alstogether some comments helpes you as well :)

Thanks Karen
