### ISSUE TITLE
Key Word Arguments Conflict with Interactive Command Line Prompt

### ISSUE THREAD

**Issue by rdvelazquez** [veg/hyphy#933]
For methods that have key word arguments, options can no longer be selected from the interactive command line prompt (the default is automatically chosen). For example, when running BUSED from the interactive command line prompt, I choose an alignment file and then the Universal genetic code is automatically selected for me. This happens with other methods and other arguments besides genetic code.

**Comment by spond** [comment]
Does this occur with the ‘-i’ option?

**Comment by rdvelazquez** [comment]
Nope. Works as expected with the `-i` option. Good call!
