### ISSUE TITLE
problem with datamonkey webserver 

### ISSUE THREAD

**Issue by gubrins** [veg/hyphy#934]
Hi to all of you,

Once more I want to congratulate you for the webserver, it helped me a lot during my master's thesis. Currently we want to publish the results of my thesis but we have to make more analyses. I've been trying to analyze the data since yesterday but it seems that the computational power of the webserver has decreased. There are not a lot of items in the cue and still I receive an error message telling me I can't analyze the data: "We're sorry, there was an error processing your job. Please try again, or visit our GitHub issues and create an issue if the issue persists."
I've been checking and there are two items running for more than 200 hours each one, could be that the reason? 

Thank you for yout time,
Gabriel

**Comment by stevenweaver** [comment]
Hi @gubrins, 

It appears that one of our job spawning processes failed last night, which resulted in some jobs not being able to start. Try again and we're glad datamonkey has been able to help you for your master's thesis. 

Best,
Steven

**Comment by gubrins** [comment]
Now it's working much better, thank you!
