### ISSUE TITLE
Legacy Command Line Files that do not work with 2.4 alpha

### ISSUE THREAD

**Issue by srwis** [veg/hyphy#936]
I've decided to consolidate all of the files that are currently not working into one list so it's easier to see. Will update as I retest and as they get fixed/deleted. 

Seg Faults:
- [x] TestClade.bf (_as of 5-21_) [this and the next 3 issues resolved with c7fa119fa35059fe52f3249c12c79679340f8212]
- [x] AnalyzeNucDataFreq.bf (_as of 5-21_)
- [x] SequentialAdditon.bf (_as of 5-22_)
- [x] TopologySearchConstrained.bf
- [x] LocalClock.bf
- [x] MolClockAllRoots.bf
- [x] NielsenYang.bf [works with 519df343]
- [x] PairwiseRelativeRatio.bf
- [x] BranchAPrior.bf (_in the phylohandbook folder now_) [works with 3bbbb3fd]
- [x] YangNielsenBranchSite2005.bf (resulted from this commit: a6b7ef8)

Not working:
- [x] LEISR.bf (_new error as of 5-21-19_) [should be resolved with c7fa119fa35059fe52f3249c12c79679340f8212 as well as the next 2]
- [ ] FitnessAAModels.bf (_new error as of 5-21-19_)
- [x] SlidingWindowAnalysis.bf (_5-21-19_)
- [x] Phylohandbook Examples (_these have been moved to their own folder_)
  - [x] http://www.hyphy.org/phylohandbook/dSdN.bf
  - [x] http://www.hyphy.org/phylohandbook/LRT.bf
  - [x] http://www.hyphy.org/phylohandbook/ErrorEstimates.bf
- [x] BivariateCodonRateAnalysis.bf
- [x] CodonBivariateRateProcessor.bf
- [x] F_ST.bf
- [x] NucModelCompare.bf
- [x] AAModelComparison.bf
- [x] MolecularClock.bf
- [x] NeighborJoining.bf
- [x] CleanStopCodons.bf
- [x] CleanGaps.bf

To Be Removed:
- [x] Kernel Analysis
- [x] CompareSelectivePressure.bf
- [x] CompareSelectivePressureIVL.bf
- [x] GADatedClock.bf (_this is just dead_)
- [x] DirectionalREL.bf (_this has been superseded by BS-REL_)
- [x] SiteRates.bf (_this has been superseded by LEISR.bf_)
- [x] BUSTED-SRV.bf (_this is all in the BUSTED.bf now_)
- [x] MFPositiveSelection.bf
- [x] MEDS.bf (_to be moved to hyphy analyses_)
- [x] BranchClassDNDS.bf
- [x] SubtreeSelectionComparison.bf
- [x] StripStopCodons.bf (duplicate of CleanStopCodons.bf)
- [x] DatedTipsMolecularClock.bf
- [x] StarDecomposition.bf
- [x] BranchSwap.bf
- [x] SeqAlignmentNuc.bf
- [x] SeqAlignment.bf
- [x] SeqAlignmentProt.bf

**Comment by spond** [comment]
Dear @srwis,

My cursory inspection of the code would imply that the `+1UL` is in error. I'll remove it in the next code commit.

Best,
Sergei

**Comment by srwis** [comment]
**NielsanYang.bf** is behaving strangely. For me it hangs after the Beta model if I choose run all no matter how long I leave it running. if I choose run custom and just run Beta and the next model Beta+W it is fine and runs in under a minute. If I choose run custom and then choose 8 other models that aren't Beta it also runs fine. 

However, I asked @rdvelazquez to check and see if it hung on Beta for him and he actually gets a seg fault so I'm not sure what is happening and have been unable to pinpoint exactly where the error is.

**Comment by srwis** [comment]
**PairwiseRelativeRatio.bf** 

Tried fixing an error: `Error:
Attempted to delete a data set filter which is still being referenced by a likelihood function` by adding a  `DeleteObject(lf);` statement as suggested for a similar error in #858 but that basically allows it to run one file and then returns a seg fault:

`***** RUNNING SINGLE FILE ANALYSES *****


File /home/swisotsky/Dropbox/hyphy_tests/data/sim_BUSTED/CV1_100_replicate.1 : ln-likelihood = -1269.677204654311Segmentation fault (core dumped)`

the commit in which the seg fault is occurring can be found in #938

**Comment by srwis** [comment]
**MEDS.bf**

Would this be a candidate for the https://github.com/veg/hyphy-analyses ? It basically already has a write up at http://www.hyphy.org/w/index.php/MEDS with some associated processing scripts.

**Comment by spond** [comment]
Dear @srwis,

Yes, I think it would be.

Best,
Sergei

**Comment by spond** [comment]
Dear @srwis,

> **PairwiseRelativeRatio.bf**
> 
> Tried fixing an error: `Error: Attempted to delete a data set filter which is still being referenced by a likelihood function` by adding a `DeleteObject(lf);` statement as suggested for a similar error in #858 but that basically allows it to run one file and then returns a seg fault:
> 
> `***** RUNNING SINGLE FILE ANALYSES *****
> 
> File /home/swisotsky/Dropbox/hyphy_tests/data/sim_BUSTED/CV1_100_replicate.1 : ln-likelihood = -1269.677204654311Segmentation fault (core dumped)`
> 
> the commit in which the seg fault is occurring can be found in #938

This is a fairly obscure error that has to do with my fixing an old "fragility" in HyPhy which was not backward compatible. I'll look into it. The `DeleteObject` fix **should** work, but maybe it triggers other issues.

Best,
Sergei

**Comment by srwis** [comment]
**SubtreeSelectionComparison.bf**
The error is:

> Error:
> Invalid Matrix Index [0][0] in a 0 by 7 matrix.
> 
> Function call stack
> 1 : doneSites[siteMap][0]=nFactor_Tree

where `doneSites    = {filteredData.unique_sites,7};`
I think this is happening because of something to do with how the unique_sites are being counted for the filteredData. I tried 3 different files and they all gave me filteredData.unique_sites = 0. From what I can tell from looking at p51.nex there should be some unique sites when it's filtered by codons. When it is unfiltered there are unique sites see: 
[input_p51.txt](https://github.com/veg/hyphy/files/3048188/input_p51.txt)

So it's either that the three files I tried all have no unique sites when filtered by codons or what's calculating the unique sites on filtered data is wonky. from what I can tell that was [site.cpp](https://github.com/veg/hyphy/blob/e1420457b4d0c9de8f206a78614c44525dc7be68/src/core/site.cpp) but it looks like that file has changed in the dev branch and I'm not sure what's responsible for it now. Let me know what you think. Thanks!

**Comment by srwis** [comment]
**MFPositiveSelection.bf**

So this requires a file that lists subset lengths as well as a file with trees. I haven't been able to figure out what the subset list should look like. (Is it CSV, just a bunch of numbers on new lines, do I need to list start and finish of the subsets....?) So I think this file need clearer instructions about file requirements prior to use or should be removed if it is not commonly used.

**Comment by srwis** [comment]
@spond I noticed while trying to resolve the issue with **StarDecomposition.bf** that there is an entirely separate folder for [Topology inference](https://github.com/veg/hyphy/tree/master/res/TopologyInference) that overlaps with a lot of the phylogeny reconstruction options. 

I'd suggest either deleting that folder or moving all of the relevant bfs to it so there is less duplication. Let me know what you'd prefer.

**Comment by spond** [comment]
Dear @srwis,

Yes the topology inference folder had to do something with the no-longer existing GUI and should be deleted.

Best,
Sergei

**Comment by srwis** [comment]
> **SubtreeSelectionComparison.bf**
> The error is:
> 
> > Error:
> > Invalid Matrix Index [0][0] in a 0 by 7 matrix.
> > Function call stack
> > 1 : doneSites[siteMap][0]=nFactor_Tree
> 
> where `doneSites = {filteredData.unique_sites,7};`
> I think this is happening because of something to do with how the unique_sites are being counted for the filteredData. I tried 3 different files and they all gave me filteredData.unique_sites = 0. From what I can tell from looking at p51.nex there should be some unique sites when it's filtered by codons. When it is unfiltered there are unique sites see:
> [input_p51.txt](https://github.com/veg/hyphy/files/3048188/input_p51.txt)
> 
> So it's either that the three files I tried all have no unique sites when filtered by codons or what's calculating the unique sites on filtered data is wonky. from what I can tell that was [site.cpp](https://github.com/veg/hyphy/blob/e1420457b4d0c9de8f206a78614c44525dc7be68/src/core/site.cpp) but it looks like that file has changed in the dev branch and I'm not sure what's responsible for it now. Let me know what you think. Thanks!

Hey Sergei,

I think df.unique_site issue is actually impacting more bfs. I was trying to use the [StripStopCodons.bf](https://github.com/veg/hyphy/blob/develop/res/TemplateBatchFiles/StripStopCodons.bf) or the [CleanStopCodons.bf](https://github.com/veg/hyphy/blob/develop/res/TemplateBatchFiles/CleanStopCodons.bf) as a basis to strip Serines for the Triple Hit model but I am running into the same issue where datafilter.unique_sites is 0. This makes me suspect that the stop codon files (or which there should probably be just one) are not actually working either. because if there are no unique sites it just says that there are no stop codons.

Here's the serine file: 
[StripSerines.bf.txt](https://github.com/veg/hyphy/files/3163917/StripSerines.bf.txt)

Best,
Sadie

**Comment by spond** [comment]
Dear @srwis,

We should deprecate `SubtreeSelectionComparison` (this is effectively an obsolete version of Contrast-FEL).

In 2.4, `unique_sites` is only defined for `DataSet` objects. The way to count the number of patterns in a `DataSetFilter` is to look at the dimension of the pattern counts in `filter.site_freqs` (it will have as many _rows_ as there are unique site patterns).

Best,
Sergei

**Comment by srwis** [comment]
> Dear @srwis,
> 
> My cursory inspection of the code would imply that the `+1UL` is in error. I'll remove it in the next code commit.
> 
> Best,
> Sergei

Hey Sergei, 

Checking these I see that the +1UL was deleted but then reverted back. See the history here around April 1st/2nd [https://github.com/veg/hyphy/blob/63958f0c3aba5a992e3f3f6274af7ebb97a1bab4/src/core/batchlanruntime.cpp#L940](batchlanruntime.cpp) . Curious which way is correct. 

I checked and reverting to not having the +1UL solves the issue mentioned for the SeqAlign bfs not having the expected matrix dimensions but the bfs return a different error anyway. So it is not like this is the sole issue in their implementation.

Best,
Sadie

**Comment by srwis** [comment]
I went ahead and removed all the currently none working legacy files both from the prompt and TemplateBatchFiles in #964 . These include:

-  DatedTipsMolecularClock.bf
-  StarDecomposition.bf
- BranchSwap.bf
-  SeqAlignmentNuc.bf
-  SeqAlignment.bf
-  SeqAlignmentProt.bf

I did **not** remove **TopologySearchConstrained.bf** from the TemplateBatchFiles folder as that still results in a seg fault and figured we should try and address that before the next release. I did remove it from files.lst.

I'll go through the files I did remove and leave a comment for each detailing the errors I've seen so far and how far I got along in troubleshooting as well just so we have a record of those.

**Comment by srwis** [comment]
**DatedTipsMolecularClock.bf**

This one seems very error prone or perhaps I was using bad data sets. Either way, I discover the following 3 errors when using [hiv1_transmission.txt](https://github.com/veg/hyphy/files/3203482/hiv1_transmission.txt):

1. You can't use a tree that is partitioned like branchname_date {label}. if you do you get this error: 
`Error: Model is not associated with the node:0557_24`
`Function call stack 1: LikelihoodFunction lf = (filteredData, givenTree) ;`
My suggestion here is to have this error be more informative or state at the input step that partitioned trees will not work. 
2. Using a none labeled tree, I chose the option to have both nonsyn and syn rates locally constrained and got the following error:
`Parsing error (parameter list is out of context in the following context: `
`clockTree.0564_7.synRate,<ERROR HERE>nonSynRate:=clockTree_sc’) while compiling the statement: clockTr
ee.0564_7.synRate,nonSynRate:=clockTree_scaler_0*(0.6999999999999998-clockTree.Node26_1.T)`
`Function call stack
1 :  clockTree.0564_7.synRate,nonSynRate:=clockTree_scaler_0*(0.6999999999999998-clockTree.Node26_1.T);
2 :  ExecuteCommands(generateDatedTipConstraints(“clockTree”,parameter2ConstrainString,tipDateAVL,0,_initialGuesses), /home/swisotsky/hyphy/res/TemplateBatchFiles/);`
 where:
`parameter2ConstrainString
synRate,nonSynRate`
So looks like it tries to constrain `synRate,nonSynRate` at once and the comma throws an error. My suggestion here is to either write it so it loops over `parameter2ConstrainString` or throw some if statements in and have it constrain each rate individually. 

3. However, even if when I choose to constrain just the synonymous rate I got the following error:
`Error: Failed to compute a valid transition matrix; this is usually caused by ill-conditioned rate matrices (e.g. very large rate values)`
`Function call stack
1 :  Optimize(res1, lfConstrained);`
This is a new to me error and I do not currently know how to handle it. 

additionally, I used this data set 
[integrase_BDA.nex.txt](https://github.com/veg/hyphy/files/3203481/integrase_BDA.nex.txt)

 as well to test and got a fourth error:
`Error:
Internal error, dumping the offending likelihood function to /tmp/hyphy.dumpConstrained optimization failed, since a starting point within the domain specified for the variables couldn’t be found.
Set it by hand, or check your constraints for compatibility.
Failed constraint:clockTree.A1_KE_99_KNH1088.t:=clockTree_scaler_0[3.64174:0-10000]*(0.0248996-clockTree.Node2.T[10.2351:0-0.0205024]) must be in [0,10000]. Current value = -37.183.`

`Function call stack
1 : Optimize storing into, res1, the following likelihood function:lfConstrained ; `

**Comment by srwis** [comment]
**LEISR.bf**

upon retesting on 5-21 this is giving me the same error as 3) from the **DatedTipsMolecularClock.bf**  see for full error:
[LEISR error.txt](https://github.com/veg/hyphy/files/3203574/LEISR.error.txt)

**Comment by srwis** [comment]
**FitnessAAModels.bf**
New error as of 5-21:
`Error: Internal error Likelihood function evaluation encountered a NaN (probably due to a parameterization error or a bug). Function call stack 1 : Optimize(res, lf); `
[fitnessAA.txt](https://github.com/veg/hyphy/files/3204188/fitnessAA.txt)

**Comment by srwis** [comment]
**SequentialAdditon.bf**
New seg fault. See file for more info:
[sequentialaddition.txt](https://github.com/veg/hyphy/files/3207859/sequentialaddition.txt)

**Comment by spond** [comment]
Dear @srwis,

Please confirm that c7fa119fa35059fe52f3249c12c79679340f8212 fixes the issues. Great work finding them!

Best,
Sergei

**Comment by srwis** [comment]
Hey @spond , 

So I tried just pulling the latest develop branch and with a fresh clone of the latest dev branch and I'm still getting the same error for LEISR. This is what I did for the fresh install:
`1166 git clone https://github.com/veg/hyphy.git
 1165  git remote add veg https://github.com/veg/hyphy.git
 1166  cd hyphy/
 1167  git remote add veg https://github.com/veg/hyphy.git
 1168  git fetch veg develop
 1169  git branch
 1170  git checkout --track veg/develop
 1171  git pull
 1172  git branch
 1173  cmake .
 1174  make install
 1175  make -j MP`

I also checked with git log and it looks like the commit is there so I'm not sure what's up:
`git log | grep c7fa119
Merge: 2b918c54 c7fa119f
commit c7fa119fa35059fe52f3249c12c79679340f8212`

Best,
Sadie

**Comment by spond** [comment]
Dear @srwis,

I can't replicate LEISR errors with the standard test. Can you please provide the entire (input + settings) configuration that triggers the errors?

Best,
Sergei

**Comment by srwis** [comment]
Hey @spond 

here's the input: 
[LEISR error.txt](https://github.com/veg/hyphy/files/3213085/LEISR.error.txt) 
with this data set:
[ksr2.fna.txt](https://github.com/veg/hyphy/files/3213087/ksr2.fna.txt)

this was also on the cluster so I'm testing locally on my mac to see if I get the same error.

Best,
Sadie

**Comment by spond** [comment]
Dear @srwis,

Resolved the LEISR issue; there was a problem with allowing the rate parameter to become < 0 in the file (fixed). Also I found an unrelated issue that JC69 has one random entry as 10.7 (instead of 1). Should be fixed with fcbabe162ef7d434d3c518efeeed71f77fa601e9

Best,
Sergei

**Comment by srwis** [comment]
Checked and LEISR is fixed! Also checked the rest of the recent issues I posted and all but **FitnessAAModels.bf** seem to run fine now. I get this error with the p51.nex data set:
`Error:
Internal error 
Likelihood function evaluation encountered a NaN (probably due to a parameterization error or a bug).
Function call stack
1 :  Optimize(res, lf);`

Here's the input for that:
[FitnessAA_input.txt](https://github.com/veg/hyphy/files/3217214/FitnessAA_input.txt)

**Comment by sdwfrost** [comment]
Can I add a postprocessing failure? When fitting a model using `hyphy -p`, and selecting (9) for Ancestral Sequences, I get the following:

```
Error:
Likelihood Function/SCFGlikelihoodFunctionName__ has not been initialized in call to DataSet ancestralSequences = ReconstuctAncestors(likelihoodFunctionName__);

Function call stack
1 :  DataSet ancestralSequences = ReconstuctAncestors(likelihoodFunctionName__);
```
