### ISSUE TITLE
no results received and job is disappear from Job Queue list

### ISSUE THREAD

**Issue by Farheena1** [veg/hyphy#937]
Hi,
I initiated two job on MEME and FUBAR , server started running them. FUBAR job disappeared from Job Queue same day but MEME keep running two days and then disappeared. I didn't received any mail.  
Please guide me how to track my jobs.

**Comment by rdvelazquez** [comment]
Hi @Farheena1,

I was able to run a FUBAR job and was emailed when the job completed. It seems like datamonkey is working as expected but I could be wrong. Some things you could try:
- Checking your spam/trash folder in your email
- Submitting the job again
- Submitting the job again with a different email address  

If you still are not able to get notified by datamonkey when you job completes, please email me (ryan.velazquez0001@temple.edu) with your files and I will run them through datamonkey and send you the links to the results. I will then also look into why our server was unable to email you.

Best,
Ryan

**Comment by Farheena1** [comment]
Thanks Ryan for guidance,
I just submitted both jobs again with different email address, by the way i checked my spam/trash folders but they don't have any notification from Datamonkey. currently my both new jobs are in running and their tickets no. are 722967 (Fubar) 722968 (MEME).
Hope everything goes well. I will let you know about the results. Thanks again.

**Comment by rdvelazquez** [comment]
Just to document what @Farheena1 and I discussed via email: 
- The MEME job finished without issue and sent an email with the results
- The FUBAR job never sent an email (for either of us) and the datamonkey page (http://datamonkey.org/fubar/5ca370e59a669d272dbbe13f) appears stuck at the `Running MCMC chain 5` stage; however, the job _did_ complete and the results json file _is_ available on our server... datamonkey just doesn't think that the job finished for some reason (therefore it doesn't send the email nor does it show the results).

This may relate to https://github.com/veg/hyphy/issues/799.

I'm looking into the issue now.

**Comment by Farheena1** [comment]
Thanks Ryan for helping me out of this issue.

**Comment by Farheena1** [comment]
The problem persistent with my latest Job for  FUBAR having ticket no 1029920. Job disappeared from Queue after showing complete status and I didn't get any result notification mail. Please send me the result jason file if available on the server. MEME job is also running and its ticket no is 1029921.

**Comment by stephenshank** [comment]
Dear @Farheena1,

I was able to successfully complete a FUBAR job:
http://datamonkey.org/fubar/5d3667364df9420244c087ff

I did look for yours by the identifier that you gave, but unfortunately the job seems to have failed before the results were stored. 

I also tried running it again with your dataset after Datamonkey's post-processing, and received an error. Could you try running it again, and if it does not work, could you email me the dataset at sshank@temple.edu?

Best,
Stephen

**Comment by stevenweaver** [comment]
Dear @Farheena1, 

I was able to replicate your issue. It appears that with this specific dataset, datamonkey isn't detecting that the job is completing (as stated earlier). 

Thank you for reporting it and I will look into it shortly.

Best,
Steven

**Comment by Vincentl9** [comment]
I encountered a similar problem. I am running FUBAR on my datasets and it does complete the job and I can see the result online. However no email is sent (I tried with different emails). Therefore I do not have a link to my job and once I close my browser I have to run my analysis again. Also just now the datasets that I have previously run without problems (although without getting any email) would not run anymore. I get a "Cannot read property 'on' of undefined" error. Could somebody please help? Thanks you!

**Comment by stevenweaver** [comment]
Dear @Vincentl9, 

I've asked our institution to escalate priority for this issue. Unfortunately, we are beholden to them for this issue to be resolved at the moment. 

Best,
Steven

**Comment by Vincentl9** [comment]
Dear Steven,

Thank you for such a quick response. I have managed to run my job again. It looks like there may only be 5 jobs queued at a time? But I still do not receive emails with a job link. It would also be useful if the job had a name of the file that I am running to identify it. At the moment I have to write down which file I have already run.

Thank you!

Best,

Damian 

Damian Dudka
Postdoctoral Researcher
Michael Lampson lab
University of Pennsylvania
Philadelphia, PA, USA
(215)-898-3693
dudka@sas.upenn.edu

**Comment by Vincentl9** [comment]
Dear Steven,

I just also noticed just now that one of my jobs that usually would take max 15-20 min has been running for 50min and it has disappeared from the queue. It is probably stuck.

Best,

Damian


Damian Dudka
Postdoctoral Researcher
Michael Lampson lab
University of Pennsylvania
Philadelphia, PA, USA
(215)-898-3693
dudka@sas.upenn.edu

**Comment by Vincentl9** [comment]
I forgot to give you a job name sorry - its 549008.localhost


Damian Dudka
Postdoctoral Researcher
Michael Lampson lab
University of Pennsylvania
Philadelphia, PA, USA
(215)-898-3693
dudka@sas.upenn.edu
