### ISSUE TITLE
running HYPHY 2.4.0 alpha on command line

### ISSUE THREAD

**Issue by kmeusemann** [veg/hyphy#944]
Hi,
thanks for solving issues with the new alpha version HYPHY 2.4.0. 
I looked at "./HYPHYMP relax --help to figure out the correct command linbe: 
...but struggled a bit:

Can you extend the help more detailed pls? KM: I do not really get what the correct command line should be: should i call the options e.g. with -- - or do I simply lists arguments?

(same question for busted)

./HYPHYMP relax [OPTIONS]
for example:
A) ./HYPHYMP relax --code Universal --alignment ALIGNMENT.fas --tree TREEFILE.tre --mode codon --test
(do i need to specify the rest as "reference"? or not nedded? I labeled all branches to test in the tree with {test}...
-- models Minimal

or  B) ./HYPHYMP relax Universal ALIGNMENTNAME TREEFILE codon test Minimal
?

##
sorry for the maybe stupid questions, but need to analyse several tenthousand files.

best and many thanks
Karen

####
Analysis options description
----------------------------
code
    Which genetic code should be used
    defaut value: Universal
alignment [required]
    An in-frame codon alignment in one of the formats supported by HyPhy
tree
    A phylogenetic tree (optionally annotated with {})
    defaut value: null [computed at run time]
mode
    Run mode
    defaut value: Classic mode
reference-group
    The set of branches to use as reference
    defaut value: null [computed at run time]
test
    Branches to use as the test set
    defaut value: null [computed at run time]
reference
    Branches to use as the reference test
    defaut value: null [computed at run time]
rates
    The number omega rate classes to include in the model [2-10, default 3]
    defaut value: relax.rate_classes [computed at run time]
models
    Which version of the test to run (All or Minimal)
    defaut value: All

**Comment by spond** [comment]
Dear @kmeusemann,

Use something like what I pasted below (adjusted settings as needed). It's a good idea to provide `Example use` strings, which I will add to the next code push.

```
hyphy relax --alignment tests/hbltests/data/CD2.nex --test PR --models Minimal
```

Best,
Sergei

**Comment by kmeusemann** [comment]
2 quick questions related to this to above explanation and looking into D2.nex with request to confirm shortly:
1) thus basically every option is involked with "--" and option? I would add this to the help file
-> see above, e.g. 
--code Universal|XX|YY
(for me as user this is more intuitive to understand)
2) --test PR -> this means in your example its labeled with {PR] ? if yes
so I would change frnm above to:
-- test LABEL (add explanation)

;)
Many thanks
Karen

**Comment by kmeusemann** [comment]
see differnces version 2.4.0 alpha last week and today also issue #930 
best Karen

**Comment by spond** [comment]
Dear Karen,

Thanks for these suggestions! I will work on improving the help message. 

Best,
Sergei
