### ISSUE TITLE
RELAX results: collapsed rate class 

### ISSUE THREAD

**Issue by NatJWalker-Hale** [veg/hyphy#946]
Hi guys, 

I am running a RELAX analysis and see in the output during the fit of the alternative model "collapsed rate class" for the purifying, neutral, and diversifying sites. This corresponds to a significant p-value for k !=0, but k is inferred to be exactly 1. Is this a legitimate result? It seems to suggest all sites along the branch are neutral. 

Best, 

Nat

**Comment by spond** [comment]
Dear @NatJWalker-Hale,

That doesn't sound right. Can you paste in the screen output of RELAX here?

Best,
Sergei
