### ISSUE TITLE
PRIME error

### ISSUE THREAD

**Issue by guangshuailiu** [veg/hyphy#947]
Hi,
I'm having a strange Datamonkey error with PRIME. I get the following error:
This error has been reported to the datamonkeys responsible for this. Sorry, we will fix the issue as soon as possible. In the meantime, it may be worthwhile rerunning your analysis to see if the condition is transient.

If the issue is indeed persistent, and you would like more information with regards to what went wrong or be notified when the issue has been resolved, please feel more than free to contact us via the following form.

The following is the error output:

Error:

Master node received an error:Current batch file requires at least version :2.3.0 of HyPhy. Please download an updated version from http://www.hyphy.org and try again. in call to RequireVersion(

Function call stack
1 : RequireVersion(("2.3.0")
-------
2 : LoadFunctionLibrary from file"chooseGeneticCode.def" using basepath /home/datamonkey/Datamonkey/Analyses/PRIME/.
-------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD 
with errorcode 1.

Can you help me, 
Many thanks

Liu guangshuai

**Comment by rdvelazquez** [comment]
Hi Liu,

Prime is being ported to Libv3 to work with the newer versions of HyPhy (you can track progress in #710). There are known issues with the implementation currently on classic.datamonkey.org. Once PRIME is ported to the newer versions of HyPhy it will be released for use at datamonkey.org.

Best,
Ryan

**Comment by guangshuailiu** [comment]
Dear Ryan,
Thank you for your quick reply. It's very helpful.
Best,
Liu
