### ISSUE TITLE
running the new version 2.4.0-alpha.2

### ISSUE THREAD

**Issue by kmeusemann** [veg/hyphy#955]
Hi all,
we finally installed 2.4.0-alpha.2 and it seems to work differently than before. Also I do not really everything in the hel message:

1) I wanna run busted (with a lot files)
a) first in batch mode (with scripts).

earlier my file looked like this: example.bf

inputRedirect = {};
inputRedirect["01"]="Universal"; // genetic code
inputRedirect["02"]="alignment.fas"; // codon data
inputRedirect["03"]="TREE.tre"; // tree
inputRedirect["04"]="test"; // Test for selection on a branch gen_relax.sh  test
inputRedirect["05"]=""; // complete selection

ExecuteAFile("PATH/hyphy/2.4.0a2-git/lib/hyphy/TemplateBatchFiles/SelectionAnalyses/BUSTED.bf", inputRedirect);

then i startet job scripts with:
HYPHYMP example.bf > example.bf.log

-> this only gives me errors, so what is wrong above?
I at least found out thats calling it changed to hyphy.
(calling it interactively, I also could not choose "test" anymore.

2) running it on command line: 
I tried: 
hyphy busted --alignment  aligment.fas --tree TREE.tre --branches test

but isn't there an option to specify the number of cores? I also tried to add
--save-fit
but then again it gives me errors that I must specify a value...

anyway: can somebody provide me pls the correct command line?

###

same problem for relax.

Many thanks again, Karen

**Comment by kmeusemann** [comment]
PS: what does further more the error mean:
"Error:DataSet(Filter)/Associative Array busted.codon_data has not been properly initialized
DataSet(Filter)/Associative Array busted.codon_data has not been properly initialized...?
Many thanks
Karen

**Comment by spond** [comment]
Dear Karen,

With 2.4 you should be able to run many analyses via command line using keyword arguments, like in 

```
hyphy busted --alignment aligment.fas --tree TREE.tre --branches test
```

The example you give in item 1 (via `inputRedirect`) should still work, but you need to make sure they supply all the required arguments in **the order they are solicited**.

You can specify the number of cores (e.g. 4) via the CPU command line argument. By default, HyPhy will try to use as many cores as it can.

```
hyphy CPU=4 busted --alignment aligment.fas --tree TREE.tre --branches test
```

`--save-fit` requires a file path following the keyword.

```
"Error:DataSet(Filter)/Associative Array busted.codon_data has not been properly initialized
DataSet(Filter)/Associative Array busted.codon_data has not been properly initialized...?
... and: Error:HyPhy killed by signal 2
```

How do you get the above error?

Best,
Sergei

**Comment by kmeusemann** [comment]
Hi Sergei
1) ok many thanks. also for the CPU command. What do you mean by --save-fit requires a file path following the keyword? I tried --save-fit FILE, but how exactly it must be then (sorry to ask this stupid question)?
2) the previous Error: I think I found the problem (there was a typo in one command - sorry) -t trying it again now
3) for RELAX: 

options are:

mode
	Run mode
	defaut value: Classic mode
	applies to: Group test mode

reference-group [conditionally required]
	The set of branches to use as reference
	applies to: Select the set of branches to use as reference

test [conditionally required]
	Branches to use as the test set
	applies to: Choose the set of branches to use as the _test_ set

I have in each tree only one species labeled (with {test}), thus is the correct command (e.g.)
hyphy relax --alignment align.fas --tree TREE.tre --test test --models Minimal 

??

(I was just confused because in busted the option is --branches - correct? 
branches
	Branches to test
	defaut value: All

while in relax the same option is specified differently - with --test (when labeles as test it would be --test test) - correct?

test [conditionally required]
	Branches to use as the test set
	applies to: Choose the set of branches to use as the _test_ set

Best and I'll let you know how it goes!
Karen

**Comment by kmeusemann** [comment]
Hi all,

a small update: 
1) after several trials it works now, however I did not use option "--save-fit" since did not really get wuat is meant by: "it requires a file path following the keyword"
2) I realized that BUSTED need for identical analyses (identical cluster, identical RAM, identical # of CPUS ca. 4-5 times as long as in the first 2.4.0.alspha version and the previous versions. out of curiositry: why is this? Because now its more "thorough"? This is however not the case for RELAX, here computation time is similar to previous versions.

Thanks Karen

**Comment by spond** [comment]
Dear @kmeusemann,

1. `save-fit` allows you to save the HyPhy likelihood function for the alternative model (e.g. if you want to simulate from it later). It does **not** control where the JSON goes. You could activate this option like so

```
hyphy busted --save-fit /home/sergei/sandbox/busted.fit [other options here]
```

2. The 2.4.0 alpha BUSTED analyses turns on synonymous rate variation by defaultt, whereas the older versions did not. This is expected impact on run time is exactly what you see : 4-5x slower. You can turn this option **off** like so

```
hyphy busted  --srv No [other options here]
```

Best,
Sergei

**Comment by kmeusemann** [comment]
Hi Sergei, 
thanks for the reply! Just in short: can you say in short what consequences it has to turn on/off "synonymous rate variation" ?
many thanks  & have a nice weekend
Karen

**Comment by spond** [comment]
@srwis : do you want to comment, since you are working on the paper about it?

**Comment by srwis** [comment]
Hi Karen,

In short, unless you know that a data set has no synonymous rate variation (SRV) I would recommend turning SRV on. Basically, we see that when there is site-to-site SRV present in a data set, BUSTED without SRV runs the risk of returning false positives. So yeah, if you don't know and the run time is not prohibitive for you, I'd use the default with SRV on. 

Hope that clears it up and if you've got any other questions RE: srv, lemme know.

Best,
Sadie

**Comment by kmeusemann** [comment]
yes that hels - thanks :) if the paper is out, link appreciated :) ! 
best Karen
