### ISSUE TITLE
Several methods not working in Classic Datamonkey 

### ISSUE THREAD

**Issue by tohmak** [veg/hyphy#957]
Hello!
I have been working on the selection analysis using SLAC/FEL/MEME in classic datamonkey webserver. 
I recently noticed that those methods does not show up in the analysis option. Only the iFEL was available. I went to 'Information:Other analyses' page and then selected 'SLAC', 'FEL', and 'MEME' to set up those analyses, however again, no choice other than iFEL was available. Same things happens to the other methods, e.g. FUBAR, Spidermonkey, Model selection. Does anyone knows what happened to the datamonkey? Is there some bugs or those methods are no more supported in the classic version of Datamonkey?

Thank you,
Tohma

**Comment by rdvelazquez** [comment]
Hi Tohma,

We've recently removed some of the methods from Classic Datamonkey that are now available on datamonkey.org. We did this to encourage use of the newer site as the newer site is using a more current version of HyPhy and is easier to maintain. 

If there are any features for the removed methods on the Classic Datamonkey site that aren't available in the newer site please let us know and we will either try to replicate those features on the new site or evaluate brining those methods back to Classic Datamonkey.

Best,
Ryan

**Comment by tohmak** [comment]
Hi Ryan,

Thank you for your quick response! Ok, I understand. It is time for me to move to the new version of Datamonkey;)

I believe there is no difference between classic and new version, except that MEME in new version shows only the # branches with EBF>100 although the classic version reported EBF for all the individual branches at each site. This is the reason I want those methods, especially MEME, back to the classic version. I know that we need careful interpretation of EBF in MEME and those values should be used for data exploration only, not for direct evidence of episodic diversifying selection on the branches. But still, EBF of individual branches provides me good ideas; EBF values in classic MEME guided me finding of very important epitopes of viruses, which are now confirmed by in vitro assay. 

Thank you!
Tohma

**Comment by stephenshank** [comment]
Dear @tohmak,

Thanks for helping us to improve MEME on the new Datamonkey! I believe this is related to #775. We'll take a look and get back to you soon.

Best,
Stephen

**Comment by rdvelazquez** [comment]
Hi @tohmak,

Thanks for the input. I've re-enabled MEME on Classic Datamonkey until we get the EBF values for the branches on datamonkey.org.

Please don't hesitate to let us know if you have other suggestions for how we can make things better.

Best,
Ryan
