### ISSUE TITLE
RELAX result (version 2.4.0.alpha2)

### ISSUE THREAD

**Issue by kmeusemann** [veg/hyphy#959]

**Comment by kmeusemann** [comment]
running RELAX with the new version (command lline mode) for quite 1/3 ther is the message:
* Detected convergence issues (negative LRT). Refitting the alterative/null model pair from a new starting point
-> what does it exactly mean - is this restrting then and how much longer will the run take?
Thanks Karen

**Comment by spond** [comment]
Dear @kmeusemann,

Not much you can do; it is simply an indication that the analysis is not numerically stable. Common causes

1. One branch set has too few branches
2. Low information dataset: short, or low divergence sequences

Best,
Sergei
