### ISSUE TITLE
unrooted tree for MEME

### ISSUE THREAD

**Issue by zhoulinlin2019** [veg/hyphy#961]
Hello,

I performed an MEM analysis with hyphy on some alignments using an unrooted tree. Is this correct to use an unrooted tree? Are the results can vary depending of the root for this analysis? The problem here is that I cannot introduce a correct outgroup to properly root the tree.

Thank you!

**Comment by spond** [comment]
Dear @zhoulinlin2019,

All selection analyses are performed on unrooted trees. Because our substitution models are time-reversible, it makes no difference where you place the root, if you do.

Best,
Sergei

**Comment by zhoulinlin2019** [comment]
Thanks very much for your reply!

Best,
Zhou
