### ISSUE TITLE
Different result of MEME between classic.datamonkey.org and the desktop version of HyPhy 

### ISSUE THREAD

**Issue by zhoulinlin2019** [veg/hyphy#962]
Hello!
I used the same alignment, substitution model and tree to run MEME using classic.datamonkey.org and the desktop version of HyPhy. I set the Significance Level as default (0.1). When I got the result I search for sites with evidence of episodic diversifying selection at 0.05 significance level. But I got more sites (<0.05) from the desktop version of HyPhy than from classic.datamonkey.org.
Which one is more reliable? Or is this an error?

Thanks!

**Comment by spond** [comment]
Dear @zhoulinlin2019,

Later versions will generally be more reliable. Which version of HyPhy did you use, and how different were the results?

Best,
Sergei

**Comment by zhoulinlin2019** [comment]
Thanks a lot!
I used HyPhy 2.2.4 Windows installer and using MEME to detect sites with evidence of episodic diversifying selection for HA gene of influenza A virus H1N1pdm09. The results from classic.datamonkey.org were 127, 156, 169, 180, 470, 542, 543. The results from the desktop version of HyPhy were 13, 55, 65, 127, 156, 169, 180, 202, 242, 470, 542. So can I use the results from the desktop version of HyPhy?

Best,
Zhou

**Comment by spond** [comment]
Dear @zhoulinlin2019,

I would use the develop branch of HyPhy (v2.4) or the current version of data monkey. See http://hyphy.org/tutorials/current-release-tutorial/ 

When you compare the results between the two implementations of the method, look not just at the list of sites but also at the p-values. For example, if one version reports p = 0.04 and the other : p = 0.06, it is quite different from p = 0.01 and p = 0.5.

Best,
Sergei

**Comment by zhoulinlin2019** [comment]
Thanks very much for your suggestion.

Best,
Zhou
