### ISSUE TITLE
Spidermonkey not available?

### ISSUE THREAD

**Issue by suskcampbell** [veg/hyphy#963]
I cant find a way to run Spidermonkey on the new site or the classic site. there is no drop-down option for this analysis. There is also no mention of it on the new website. Is this not available anymore?

**Comment by stevenweaver** [comment]
Dear @suskcampbell, 

Spidermonkey is located under `BGM` on the new site. http://datamonkey.org/bgm. 
We should name refer to it as `Spidermonkey/BGM` on the site, however. So I'll keep this ticket open.

Best,
Steven

**Comment by suskcampbell** [comment]
oh great! I found it now. I should have made that connection. Thank you

**Comment by rdvelazquez** [comment]
Closed by https://github.com/veg/datamonkey-js/commit/fa92c04524cd74024bdc220d8b31663a2a7632cb
