### ISSUE TITLE
Specifying Protein tree using FEL on Datamonkey

### ISSUE THREAD

**Issue by SammyRoC** [veg/hyphy#966]
I was wondering if it is possible to perform FEL while specifying a protein tree and having the nucleotide codon sequence be used to infer positive and negative selected sites rather than specifying the nucleotide tree? In clarity, my goal is to identify positive/negative selected sites, but we believe that the protein tree demonstrates the phylogeny more appropriately than the nucleotide tree. Therefore, we want to use the protein tree topology.

Thanks in advanced.

**Comment by spond** [comment]
Dear @SammyRoC,

You can use any tree you want, as long as it has the correct number of leaves that match your sequence data. Datamonkey will recognize trees included with the alignment files. For example, in a FASTA file that I attach here, there's a user tree specified at the end. 

When you upload the alignment to Datamonkey, it will use the included tree by default.

<img width="985" alt="Screen Shot 2019-05-24 at 4 14 08 PM" src="https://user-images.githubusercontent.com/1018513/58354302-ff6e4680-7e3e-11e9-83c1-45d24edfa6f1.png">

[CD2.txt](https://github.com/veg/hyphy/files/3218446/CD2.txt)

Best,
Sergei

**Comment by SammyRoC** [comment]
Thank you so much! That is extremely helpful!
