### ISSUE TITLE
how to interpret "branches = 0" in MEME result

### ISSUE THREAD

**Issue by dongzhang0725** [veg/hyphy#972]
Hi developer,

I am trying to run MEME analysis using interactive command line. However, I don't know why the results show 0 branches show evidence for positive selection at some sites. I have read #666 issue, and still don't know how to settle this problem. I am using the version 2.3.14. Could you please tell me how to interpret this result?
![image](https://user-images.githubusercontent.com/15956921/58958065-9b4f6900-87d4-11e9-91cd-aac04c004ca4.png)
![image](https://user-images.githubusercontent.com/15956921/58957773-ed43bf00-87d3-11e9-8c4e-bc4d74e911f8.png)

Best,
Dong

**Comment by spond** [comment]
Dear @dongzhang0725,

This occurs when **many** branches show **weak individual** evidence for selection. Taken together, there is enough signal to call positive selection, but no individual branch rises to the level of significance. Think of this as "team" vs "individual" effort that wins the game:)

Best,
Sergei

**Comment by dongzhang0725** [comment]
> Dear @dongzhang0725,
> 
> This occurs when **many** branches show **weak individual** evidence for selection. Taken together, there is enough signal to call positive selection, but no individual branch rises to the level of significance. Think of this as "team" vs "individual" effort that wins the game:)
> 
> Best,
> Sergei

Dear Sergei,

 I get it.

Thank you very much for your help.

Best,
Dong
