### ISSUE TITLE
Running SCUEAL using hyphy

### ISSUE THREAD

**Issue by CampbellSam** [veg/hyphy#978]
Dear all,

I have been struggling to run SCUEAL using HyPhy (version=hyphy_v2.5.0). I am currently trying to use a batch command based on the following, from the SCUEAL documentation:

 $mpirun -np [number of processors] pathto/HYPHYMPI BASEPATH=pathto/HYPHY_Source/ USEPATH=/dev/ null pathto/SCUEAL/TopLevel/MPIScreenFASTA.bf

I have not been able to run SCUEAL successfully using this and I would prefer to run it from the command line but there doesn't appear to be an option for this.
The documentation is not up to date for current versions of HyPhy, has anyone ran SCUEAL recently and is there a better/easier way to do so? 

Thanks!

**Comment by spond** [comment]
Dear @campbellsam,

SCUEAL has not been ported over to v2.5. Let me check to see if the current SCUEAL code reveals any incompatibility with v2.5 and get back to you. 

Best,
Sergei
