### ISSUE TITLE
hyphy GARD command-line parameters

### ISSUE THREAD

**Issue by jayoung** [veg/hyphy#980]
hi there,

I've just installed hyphy locally and am looking forward to trying the new command line version.  I have  /HYPHY 2.5.0(MP) for Linux on x86_64\.

I'd like to run GARD with similar parameters as I normally choose on the website: rate variation = general discrete and 3 classes, but I can't see the correct way to specify that in the documentation.  "hyphy --help" and "hyphy GARD --help" begins to help me - it does tell me what the command line options are, but it doesn't tell me the possible values for each option.  Can you help?  

This is what I tried:
"hyphy GARD --type Nucleotide --alignment myAln_NT.fa -rv GDD --rate-classes 3"
but as it is running it includes this message in the output:
"type: Nucleotide
rv: None"
which I assume means I didn't specify -rv correctly.   What's the correct way to specify the discrete model?

I'm also wondering what the correct way to specify substitution models is, e.g. for hky85, would I add "--model hky85" or use the numerical scheme to specify that, as in the older command line version of hyphy?

I'd love to hear the answer here, but also it'd be great if this information could be added to the output of "hyphy GARD --help".

thanks very much,

Janet Young

------------------------------------------------------------------- 

Dr. Janet Young 

Malik lab
http://research.fhcrc.org/malik/en.html

Division of Basic Sciences
Fred Hutchinson Cancer Research Center
1100 Fairview Avenue N., A2-025, 
P.O. Box 19024, Seattle, WA 98109-1024, USA.

tel: (206) 667 4512
email: jayoung  ...at...  fredhutch.org

-------------------------------------------------------------------

**Comment by rdvelazquez** [comment]
Hi @jayoung,

Thanks for sharing your issue. It looks like you forgot the double dash for "rv" you want `--rv` instead of `-rv`. The options for rate-variation are `None`, `Gamma` or `GDD`. I agree that these should be in the help documentation and we will look to add them soon.

The choices for protein model are: LG, WAG, JTT, JC69, mtMet, mtVer, mtInv, gcpREV, HIVBm, HIVWm, GTR.

We will look to add the choices to the documentation but in the meantime, what I do to see the choices is provide a choice that I know is wrong `--model abcdefg` for example and the script will then error telling you that you provided an invalid choice and show the list of valid choices in the error message.

Best,
Ryan

**Comment by jayoung** [comment]
hi Ryan, 

Thanks for the quick response, and sorry about my dumb error!   

Somehow I managed to use the double-dash on all the other args but not that one.  Would it be easy/worthwhile to add an argument checker to hyphy to warn users about unrecognized/unused args? (to save us from ourselves).

Does '--model' apply to nucleotide (not codon) alignments, too, or does it always use GTR or other standard model choice?  I definitely don't have an opinion on what model I want to use - I just saw elsewhere some discussion of people getting different results with old/new versions of GARD/datamonkey perhaps due to use of hky85 versus other models, and it'd be nice to understand what's going on behind the scenes.

thanks again,

Janet

**Comment by rdvelazquez** [comment]
Hi Janet,

An argument checker for HyPhy would be nice but I don't think we have plans to add one at this point.

The `--model` only applies to protein alignments. Nucleotide alignments use the GTR model (see this batch file: https://github.com/veg/hyphy/blob/master/res/TemplateBatchFiles/libv3/models/DNA/GTR.bf). Codon alignments use the MG_REV model (see this batch file: https://github.com/veg/hyphy/blob/master/res/TemplateBatchFiles/libv3/models/codon/MG_REV.bf)

Best,
Ryan

**Comment by jayoung** [comment]
Thanks again, Ryan - that's helpful.  Would be great to add that info to the documentation too.

Janet

**Comment by spond** [comment]
Dear @liamxg,

GDD = general discrete distribution (on K > 1 rate classes, specified by `--rate-classes` which defaults to `4`).

Here it means `K` rates and `K-1` weights will be estimated by maximum likelihood, subject to the additional constraint that the mean of the distribution is 1. 

See https://academic.oup.com/mbe/article/22/2/223/963847 for some general discussion.

<img width="608" alt="image" src="https://github.com/user-attachments/assets/58dd69e7-08ce-4a48-a689-07666b466ad0">


Best,
Sergei

**Comment by spond** [comment]
Dear @liamxg,

FRD is the same thing as GDD. If you want to read a comprehensive paper on the subject, check out Joe Felsenstein's paper all the way back from 2001: https://pubmed.ncbi.nlm.nih.gov/11675604/

Best,
Sergei
