### ISSUE TITLE
GARD - Codon model and Discrete rate classes?

### ISSUE THREAD

**Issue by jayoung** [veg/hyphy#981]
hi again,

I'm thinking about the best setup to use to screen my alignment for recombination. Naively, it seems I want this combination:
1) 'Codon' (it's a protein-coding in-frame alignment)
2) 'Discrete' because I want to allow rate variation (to allow for heterotachy), maybe 3 categories

So I tried this on the command line:
`hyphy GARD --alignment myAln.fa --type Codon --rv GDD --rate-classes 3
`
but got an error:
`Error:
User-defined function 'models.codon.MG_REV.ModelDescription' needs 2 parameters, but 1 were supplied.
`

Does that error make any sense to you?  Perhaps GARD is just not designed to run the codon model with rate variation, but if it should be possible to do that, what would be the second parameter I should supply?  

These two simpler variants of the command both seem to work (although both analyses are still running, so I won't know for a while if they complete, but it's a pretty good sign that they're running):
```
hyphy GARD --alignment myAln.fa --type Nucleotide --rv GDD --rate-classes 3
hyphy GARD --alignment myAln.fa --type Codon
```
thanks again,

Janet

**Comment by rdvelazquez** [comment]
Hi Janet,

Thanks for posting this. This is a bug and I'm working on addressing it now.

@spond do you have an example of another batch file that allows for specification of rate variation for codon data? I didn't see this in any of the other standard analyses.

Best,
Ryan

**Comment by jayoung** [comment]
Thanks, Ryan - I'll keep an eye out for a fix.

**Comment by youxinchen** [comment]
The error also reproted when I use HYPHY (version:2.5.2(MP) for Linux on x86_64) on the command line"hyphy GARD --alignment XX.fas --type codon --rv GDD --rate-classes X" or "hyphy GARD --alignment XX.fas --type codon --rv Gamma --rate-classes X",but it is work well when I run GARD in websever.

**Comment by alephreish** [comment]
Sorry for intervening, but it seems that the issue is still persistent a year after. I personally get nonsensical results when no rate variation is allowed, as compared to `--type nucleotide`. I've checked the datamonkey server and it doesn't seem to provide 'codon' as data type anymore.

**Comment by spond** [comment]
Dear @alephreish,

I would try `hyphy GARD --alignment myAln.fa --type nucleotide --rv GDD --rate-classes 3`. The `codon` option does not support rate variation because allowing it while using **codon** models would not ever finish. I should probably remove the `codon` option altogether because it is "experimental"; one issue with codon data is that the neighbor-joining tree reconstruction doesn't work well with codon-based distances. 

Are you getting sensible results with the `--type nucleotide` option?

Best,
Sergei

**Comment by alephreish** [comment]
Hi Sergei,

thanks for the response. Yes, with `--type nucleotide` I get a very systematic result (recombination between homologous domains within fusion proteins, smth you can immediately recognize from a tree topology) with the topology for the longer arm corresponding roughly to a codon tree I get with iqtree for the whole alignment. I'll continue playing with `--type nucleotide` then.

Best,
Andrey
