### ISSUE TITLE
BGM jobs not completing on datamonkey

### ISSUE THREAD

**Issue by harturchin** [veg/hyphy#983]
Hi Hyphy,

I'm trying to run BGM on this input file using the default run parameter values. The alignment comes from this database. 

http://orthomam1.mbb.univ-montp2.fr:8080/OrthoMaM_v10b7/
[RTL1.txt](https://github.com/veg/hyphy/files/3291555/RTL1.txt)

I chose nucleotides (not codons) because the gene encodes both an mRNA (on one strand) and a series of microRNAs (on the other strand) that regulate expression of the protein-coding gene.  So I am interested in coevolving nucleotide sites not coevolving codons. 

The job is long and slow but seems to start to converge on estimates of coevolving sites. In the current run I get this interim output file (log file) with seven pairs of sites under selection. 

[BGM_output_48hr_log.txt](https://github.com/veg/hyphy/files/3291558/BGM_output_48hr_log.txt)

I meant to upload a screen grab of the html output window here but I can't seem to upload a tiff image to this page.

The current run has now disappeared from the job queue, but the html output window says the job is still running; reloading the datamonkey browser window with the current job does not generate a complete output. In previous runs the analysis got to about this same point and then crashed with a generic data monkey error message that the job failed. 

I can't tell whether this is a problem on the datamonkey side, or a problem with the size of the job. Art Poon suggested that because the method is new on datamonkey possibly not all the bugs have been found and fixed. Thanks very much for any help you can suggest.

Mike Hart

**Comment by ArtPoon** [comment]
Hi Mike, I think one of the problems is that you are running this analysis with the threshold number of substitutions at the default setting (1+).  As a result the BGM has an excessive number of variables.  For example, I ran your data with a threshold of 3+ (under "Advanced options") and obtained results after about 24h on 1,781 nodes (polymorphic nucleotide sites).  I would set this threshold substantially higher (at least 5).

**Comment by harturchin** [comment]
Ok I see thanks for the advice. I should have thought of that. Will try with a couple of different higher limits. Thanks! Mike

Sent from my iPhone

On Jun 14, 2019, at 10:23 AM, Art Poon <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Mike, I think one of the problems is that you are running this analysis with the threshold number of substitutions at the default setting (1+). As a result the BGM has an excessive number of variables. For example, I ran your data with a threshold of 3+ (under "Advanced options") and obtained results after about 24h on 1,781 nodes (polymorphic nucleotide sites). I would set this threshold substantially higher (at least 5).
