### ISSUE TITLE
ds>1 in most sites may produce positive selection underestimation?

### ISSUE THREAD

**Issue by d-caraballo** [veg/hyphy#986]
Hi. I have been carrying out phylogenetic and selection analyses in duplicated genes in Nematodes. I applied codon-based methods (SLAC, FEL, IFEL, REL, MEME and FUBAR). In my dataset I found that synonymous sites are saturated (with dS > 1 along most sites according to SLAC). The question is if this would make the dN/dS ratio challenging to infer accurately if at all, under the presumption that dS adequately captures the input of neutral mutations. While PAML and related methods supposedly are robust to long branch lengths for synonymous sites in large trees, I don’t know if I count with sufficient number of species falling into this zone. Could I be underestimating positive selection in this group?

**Comment by spond** [comment]
Dear @d-caraballo,

Remember that `dS` measure in SLAC is across the entire tree, not a single branch. Total tree lengths that exceed `dS>1` are **far from saturation**; you would need this measure to apply to individual branches. I would also recommend you run FUBAR for these types of analyses, as it is much more statistically principled that SLAC is. 

In addition, if `dN/dS` cannot be inferred reliably, you would see this as wide confidence intervals, or lack of statistical power for site-level tests. In other words, I don't think you should be too concerned here.

Best,
Sergei

**Comment by d-caraballo** [comment]
Dear Sergei,

Thanks for the prompt response. Do you suggest to test the alignment for saturation or should I only inspect confidence intervals in Datamonkey output? What method/program would you suggest to test for saturation at individual branches?

Cheers,

Diego

**Comment by spond** [comment]
Dear @d-caraballo,

Tests will typically fail "gracefully" when you have saturation -- they will simply lose power. A tell-tale sign of saturation in this case is the presence of "infinite" branch lengths.

Best,
Sergei

**Comment by d-caraballo** [comment]
Dear @spond,

Thanks for your response. I attach you the trees under analysis (nwk). These are duplicated genes for which I obtained independent alignments (_Vertebrates_ and _Caenorhabditis_), and performed separate analyses for two domains of the protein (recognition and catalytic domains).
The trees were inferred using PhyML (models selected under AIC and trees searched under aLRT). I am not sure if the total tree length should be calculated as the sum of all branch lengths divided by the number of branches of the trees, but as an approximate measure I can say that the scale of the trees reach 1.4-2.5 substitutions per site.

Cheers,

Diego



[Caenorhabditis_catalytic_domain.txt](https://github.com/veg/hyphy/files/3339292/Caenorhabditis_catalytic_domain.txt)
[Caenorhabditis_recognition.txt](https://github.com/veg/hyphy/files/3339293/Caenorhabditis_recognition.txt)
[Vertebrates_catalytic.txt](https://github.com/veg/hyphy/files/3339294/Vertebrates_catalytic.txt)
[Vertebrates_recognition.txt](https://github.com/veg/hyphy/files/3339295/Vertebrates_recognition.txt)
