### ISSUE TITLE
p-value precision in HyPhy RELAX

### ISSUE THREAD

**Issue by lokdeep1993** [veg/hyphy#988]
I ran HyPhy RELAX on a list of genes for different species and noticed that p-value turned out to be 0 for a lot of them. Even if I do multiple testing correction on those candidates, it will still be significant as the p-value was 0. **I want to make calculation of p-value more precise in HyPhy RELAX**.
Please suggest me some modification in the script/command such that the calculation of p-value will be more precise.
Thank You
Lokdeep

**Comment by spond** [comment]
Dear @lokdeep1993,

You should have full precision results in JSON files (screen output is formatted to 4-5 digits of precision). If they are reported as 0, you can assume that the p-values are, say <1e-26 (which is what you'll find in R).  

Best,
Sergei
