### ISSUE TITLE
Retrieving sites under selection from the aBSREL results

### ISSUE THREAD

**Issue by GilEshel** [veg/hyphy#989]
Hello,

I have been using the Branch-Site model in CodeML for my analyses, and recently started to use aBSREL.

I was wondering if there is an equivalent procedure to the CodeML Bayes Empirical Bayes test, to infer which sites are under positive selection in the foreground branches? The current output only indicates the portion of sites and the corresponding omega value.

We are interested in these sites for our functional validations.

Many thanks!
Gil

**Comment by spond** [comment]
Dear @GilEshel,

There's no power to reliably detect selection at a single site along specific branches (you effectively have a sample size of one). We have the following passage in the [MEME paper](http://www.plosgenetics.org/article/info%3Adoi%2F10.1371%2Fjournal.pgen.1002764)

>However, we caution that despite obvious interest in identifying specific branch-site combinations subject to diversifying selection, such inference is based on very limited data (the evolution of one codon along one branch), and cannot be recommended for purposes other than data exploration and result visualization. This observation could be codified as the “selection inference uncertainty principle” – one cannot simultaneously infer both the site and the branch subject to diversifying selection. In this manuscript, we describe how to infer the location of sites, pooling information over branches; previously [20] we have outlined a complementary approach to find selected branches by pooling information over sites.

I recommend the following:

1. Use MEME to find sites subject to episodic selection. This doesn't tell you which branches, but has good statistical properties. 

2. Use BUSTED restricted to a specific subset of branches (ideally > 1), and review Evidence Ratios as an *exploratory* tool to find which sites contribute to the signal.

Hope this helps,
Sergei

**Comment by GilEshel** [comment]
Dear Sergei,

Thanks for your reply, I will try that.

Best regards,
Gil

**Comment by GilEshel** [comment]
Dear Sergei,

I have run both MEME and BUSTED as you recommended.

I have a followup question regarding the 'Evidence Ratios'.

I couldn't figure out how these values are calculated. I read the "Evidence of Selection at Individual Sites" paragraph of the BUSTED paper, and I tried playing with the 'Site Log Likelihood' values of the unconstrained and constrained, as I understood from the paper, but I couldn't get the same values as reported in the 'Evidence Ratios' (in the json file).

1. How these values are calculated?
2. What they mean (which cutoff will indicate that a site is contributing to the signal)?

Thanks a lot for your help!!!
Gil

**Comment by spond** [comment]
Dear @GilEshel,

1. These are calculated as "log likelihood ratio ratios", ER = `2 log (L[site | selection allowed) - 2 log (L[site | selection not allowed])` 

2. They have a loose interpretation; site ER that is above 0 for the _optimized null_ setting contributes **something** to the signal. Typically you want to look at ER of ~2 or higher as suggestive. However, there is no rigorous statistical interpretation here, i.e. ER = 2 means that there is some probability that site is under selection. Higher ERs mean more signal of selection. 

Best,
Sergei

**Comment by GilEshel** [comment]
Dear Sergei,

Thank you very much for these details!

I think I understood now how to analyze my data, but I wanted to check if I got it right.

My interest is to identify genes that are under positive selection, at either one or more branches that lead to the taxa with the trait of interest (multiple independent origins). 

So, I'm using aBSREL, since I can test each of these branches, as well as to get the dN/dS estimates of all other branches (so I can then filter out genes that also have dN/dS in non-relevant branches).

I'm also interested to know which sites are under selection in these genes that I found "related" to my trait. Are these genetic changes affect the structure/function of the protein (we can test that if we know which sites). 

So, here I understood, that in order to connect between which branches and which sites, I need to run both BUSTED and MEME. From BUSTED, I can look for the genes that I found with aBSREL, get the ER values, and compare them with the sites identified by MEME. Sites with high ER that were found significant by MEME are my top candidates.

Does that sound reasonable?

Thank you, and best regards,
Gil

**Comment by spond** [comment]
Dear @GilEshel,

If you have the set of taxa with the trait of interest known **beforehand** (which I presume you do), then you should be able to run a single BUSTED analysis. For this analysis, specify the set of branches leading to the taxa of interest as your **test** set, and then use ER scan to pick out which sites are driving the signal, assuming the test result is positive. This is the "proper" hypothesis test, i.e. you formulate your hypothesis before examining the data. 

If, on the other hand, you use the results of aBSREL to **define** which branches to test with other techniques, then you expose yourself to biases, whereupon the same data are used to formulate the hypothesis and to test it. It is at best an exploratory analysis. I suppose in this situation, one could craft a simple extension to aBSREL which would report evidence ratios similar to what is reported by BUSTED, but I would expect that this approach will not provide a particularly clear picture because it is based on inference from a single branch.

Best,
Sergei

**Comment by GilEshel** [comment]
Dear Sergei,

Thank you! Indeed, I know beforehand which branches should be tested for positive selection. I executed both aBSREL and BUSTED with these branches labeled as foreground.

From the aBSREL results, I noticed that many of the genes that were identified under positive selection in at least one of the tested branches, also have branches in the background with an estimated dN/dS > 1 (I attached an aBSREL json file as an example for such case). Since I'm interested to find genes that are specific to the evolution of the trait, I filtered out these non-specific positively selected genes.

When I'm comparing aBSREL with the BUSTED results, I see that a lot of the aBSREL non-specific positively selected genes were also found to be under positive selection using BUSTED (I attached the BUSTED json file corresponding to the same ortholog group as in my aBSREL example). 

I attached Venn diagrams showing the number of overlapping genes between the different methods, from 4 different phylogenomic analyses (completely different taxa) that I'm currently running (I also added the MEME results). I split up the aBSREL specific (aBSREL_uniq) and non-specific (aBSREL_not_uniq) gene lists, to see how they overlapped with BUSTED and MEME.

It seems that if I would only run BUSTED, I would capture genes that are also under positive selection in some of the background branches. Would combining the aBSREL and the BUSTED results, and perhaps MEME as well, to find genes that are specifically under selection in the foreground branches, make sense?

Thanks!
Gil

[partition35934_aligned_with_labeled_tree.cds.BUSTED.txt](https://github.com/veg/hyphy/files/3377910/partition35934_aligned_with_labeled_tree.cds.BUSTED.txt)
[partition35934_aligned_with_labeled_tree.cds.ABSREL.txt](https://github.com/veg/hyphy/files/3377911/partition35934_aligned_with_labeled_tree.cds.ABSREL.txt)
[HyPhy_methods_overlap1.pdf](https://github.com/veg/hyphy/files/3377918/HyPhy_methods_overlap1.pdf)

**Comment by spond** [comment]
Dear @GilEshel,

Filtering "non-specific" genes makes sense to me, although you might want to impose some stringency conditions on it, e.g. the extent of selection on "background" branches. That said. filtering based on the condition of "at least one background branch has corrected p < 0.05" is perfectly fine. Make sure you use corrected p-values here.

Looking at your BUSTED and aBSREL examples, I'd like to caution that if you run BUSTED on a subset of branches (which you did), the test does **not** formally examine background branches at all. Therefore, even though the point estimate of &omega; on the background branches is greater than one, BUSTED makes no statistical statements regarding selection on the background branches. For example, it could very well be *in*significant.

BUSTED and aBSREL will largely agree (if you have the same set of test branches), but not always. If BUSTED returns a positive result, but aBSREL returns a negative result, you can interpret this disagreement that as evidence of selection that is too weak along any **individual** branch to be significant (aBSREL), but is sufficiently strong among the group of test branches to be detectable (BUSTED). If you see a positive result with aBSREL but not BUSTED< this could mean that the evolutionary process is sufficiently heterogenous between branches that the assumption of common selective regimes on all test branches (made by BUSTED) is not a good fit to the data. aBSREL, which makes no such assumption can therefore be more sensitive.

Best,
Sergei

Best,
Sergei

**Comment by GilEshel** [comment]
Dear Sergei,

Many thanks for your help and input!

Best,
Gil

**Comment by hongzhonglu** [comment]
> 1. Use MEME to find sites subject to episodic selection. This doesn't tell you which branches, but has good statistical properties.

Dear Sergei @spond ,
I am also interested to find positive selected sites from interested branches. Does it mean that MEME can not be used to estimate the positive selected sites from interested branches?

**Comment by spond** [comment]
Dear @hongzhonglu,

You can use MEME, especially if you defined the branches a priori (i.e. didn't analyze the data first, then determine which branches are **interesting**). For smaller numbers of branches (~5-10) it may be better to use FEL.

Best,
Sergei

**Comment by hongzhonglu** [comment]
Dear Sergei @spond,
Thanks for your help!

Best,
Hongzhong

**Comment by emiliomastriani** [comment]
Hi guys, I am new using MEME and I have some troubles to understand the results. For example, I obtained the site 9628 results under selection. Now I wish to "see" who this site  is .... Is it enough to get the nucleotide at position 9628 into my MSA? For further analysis on this site, should I consider only that nucleotide (9628) or the codon starting at this position? Furthermore, the mentioned site looks to be under selective pressure both into other datasets with different geo-localization: should I repeat the analysis using a different method (SLAC) to confirm that the results is significant?

![Screen Shot 2020-05-20 at 5 03 39 PM](https://user-images.githubusercontent.com/65239532/82646641-89fea700-9c47-11ea-9771-2f865783d7b1.png)
Thank you very much

**Comment by felixheno** [comment]
> Filtering "non-specific" genes makes sense to me, although you might want to impose some stringency conditions on it, e.g. the extent of selection on "background" branches. That said. filtering based on the condition of "at least one background branch has corrected p < 0.05" is perfectly fine. Make sure you use corrected p-values here.

Dear Sergei @spond,

I am also interested in identifying genes that have been under selection (and the sites driving the signal) in an set of branches defined _a priori_, and would like to filter "non-specific" genes, but I was wondering how you would suggest that I obtain corrected p-values for background branches. Since aBSREL with _a priori_ foreground branches will not test background branches, do you suggest that I run aBSREL in exploratory mode and see if any of the significant branches (after correcting for multiple testing) is part of the background set in the BUSTED analysis, as a way to filter "non-specific" genes?

In brief, based on what I have read about the HyPhy tests and in this issue, my planned analysis is as follows:
1. Run BUSTED with target and background branch sets to test if there is evidence of positive selection
2. If positive, ER scan will be used to find sites driving the signal (threshold ER > 2)
3. Run exploratory aBSREL to see if the is evidence of positive selection in branches in the BUSTED background set

Would it be reasonable to use the exploratory aBSREL results to also indicate which branches in the BUSTED target set that is under selection?

Best,
Felix
