### ISSUE TITLE
Problem with standard command-line prompt

### ISSUE THREAD

**Issue by noory3** [veg/hyphy#990]
Hi hyphy team, 

I have been using the previous command-line version of hyphy (version 1.2) with no issues. I recently updated to hypyh 2.2 and am having trouble with the command-line prompts. 

For example, if I want to fit my Alignment.txt to BUSTED I can do so using the interactive command line prompt `hyphy -i` and then specifying the analysis, alignment file, tree, etc with no problems. 

However, when I try to run the same model + alignment + tree using the Standard command line tool `hyphy --alignment Alignment.txt  --tree Tree.trees` I get the following error file:

> Error:Could not find source dataset file "PROMPT_FOR_FILE" (resolved to '/home/BUSTED/TRY/All')
> Path stack:
>         /usr/local/lib/hyphy/
>         /usr/local/lib/hyphy/TemplateBatchFiles/SelectionAnalyses/
> Could not find source dataset file "PROMPT_FOR_FILE" (resolved to '/home/BUSTED/TRY/All')
> Path stack:
>         /usr/local/lib/hyphy/
>         /usr/local/lib/hyphy/TemplateBatchFiles/SelectionAnalyses/

any ideas as to what is causing this and how to fix it? 

Thank you! 

Note: I have the same problem with all models not just BUSTED.

**Comment by stevenweaver** [comment]
Dear @noory3, 

Command line arguments like `--alignment` and `--tree` were not fully supported in batch files until `hyphy 2.5`. Would you try upgrading to `2.5` and trying again?

Best,
Steven

**Comment by stephenshank** [comment]
Dear @noory3,

From a cursory inspection of your command line invocation, I think you are missing an analysis specification. Trying adding `busted`, as such:

```
hyphy busted --alignment CD2-slim.fasta --tree CD2.new
```

I was able to start a BUSTED analysis using the above command with HyPhy 2.5.0, and can share the files if it would help.

Please let me know how it goes.

Best,
Stephen

**Comment by noory3** [comment]
Hi @stephenshank , 

Sorry, that was a typo in my initial question. `hyphy busted --alignment Alignment.txt --tree Tree.trees` was the command I ran without much luck. 

Noor

**Comment by stephenshank** [comment]
Dear @noory,

Can you confirm that when you type `hyphy`, you see something like

```
           /HYPHY 2.5.0.(MP) for Darwin on x86_64\           
```

(crucial part being being the 2.5.0) printed to the screen? I ask because you stated that you are running version 2.2.

Best,
Stephen

**Comment by noory3** [comment]
Hi @stephenshank,

`/HYPHY 2.5.0(MP) for FreeBSD on amd64\   
`
is printed when I run interactive hyphy.

**Comment by stephenshank** [comment]
Dear @noory3,

Hmm. This is definitely a tricky issue, so thanks for reporting!

How did you install HyPhy 2.5.0? I.e., did you use `conda`, or did you clone the repository and follow the instructions on the README?

Best,
Stephen

**Comment by Jehops** [comment]
Hi all,

@noory3 is using HyPhy installed from [the FreeBSD package](https://www.freshports.org/biology/hyphy/).  The package version is still listed as 2.3.14.16 on that page, but @noory3 is running version 2.5.0.  I haven't push the changes to the FreeBSD repository yet.

Joseph

**Comment by Jehops** [comment]
Here are the blueprints for the FreeBSD package in case they are helpful.  This latest update to 2.5.0 has still not been pushed to the main repository yet.  I'll wait to confirm there is not a problem.
https://github.com/Jehops/freebsd-ports/tree/hyphy/biology/hyphy

It's essentially vanilla hyphy with a few minor patches that were accepted in to your repository after the 2.5.0 release. If there is anything that I/we can test, please let us know.

Regards,

Joseph

**Comment by stevenweaver** [comment]
Dear @Jehops, 

Within our immediate lab, we do not use FreeBSD. Additionally, FreeBSD is not part of our CI, so it's difficult to ensure compatibility as commits happen fairly regularly. If there was a way to update [travis](https://github.com/veg/hyphy/blob/master/.travis.yml) with settings to ensure that a build will work for FreeBSD, we would be very open to including it. 

Best,
Steven

**Comment by Jehops** [comment]
Hi Steven,

Sorry for the long delay.  I'm not familiar with Travis, but the differences between FreeBSD and Linux for these sorts of things are often minor.  We have a FreeBSD "CI guy".  I might try asking him first, since it might be simple for him to get this going.

Cheers,

J.

**Comment by spond** [comment]
Dear @Jehops,

I am not sure this is a FreeBSD specific issue. When you encountered this error

1. What is the current working directory (the result of `pwd`)?
2. Does this directory contain the file `Alignment.txt`, case-sensitive?

The error message indicates to me that HyPhy is not able to locate the alignment file in the `/home/BUSTED/TRY/` directory.

Also: consider using the latest HyPhy release (v2.5.4).

Best,
Sergei

**Comment by Jehops** [comment]
Hi all,

@noory3, I updated to hyphy to version 2.5.4 on the cluster (awarnach) if you have the time and motivation to test.

Joseph
