### ISSUE TITLE
GARD: Error processing protein data on Datamonkey 

### ISSUE THREAD

**Issue by kwade4** [veg/hyphy#991]
Hello, 

Running GARD on Datamonkey using: 
- Data Type: `Protein`
- Genetic Code: `Universal`
- Site-to-site variation: `General Discrete`
- Rate classes: `3`

Gives this error: 
 
`We're sorry, there was an error processing your job. Please try again, or visit our GitHub issues and create an issue if the issue persists.` 

I can reproduce this error using different protein data sets. 
* `test.fasta` ([test.zip](https://github.com/veg/hyphy/files/3382567/test.zip)) 
* `test-2.fasta` ([test-2.zip](https://github.com/veg/hyphy/files/3382624/test-2.zip))

Thank you for your help!

**Comment by srwis** [comment]
Hi,

I can confirm on datamonkey.org, neither of the test data sets provided work and they generate an empty log file. However, it appears they run with the chosen parameters on [staging.datamonkey.org](http://staging.datamonkey.org/gard/). 

They also run using the command line version of GARD in HyPhy 2.5.0. So I'm not sure what is wrong with GARD on main datamonkey site, (maybe @stevenweave or @stephenshank knows more) but if you want to use the staging version it should work fine. The only caveat with it that I've been informed of is that branch selection is currently broken for all methods on the staging site. 

Hope that helps!
Sadie

**Comment by kwade4** [comment]
Hi Sadie, 

Thank you very much for your reply! 

I am having a bit of trouble running GARD on staging.datamonkey.com and the command line version. 

#### DataMonkey
On staging.datamonkey.org, when I select "Run Analysis", it seems as though it gets stuck verifying the input file. I can reproduce this error using Firefox and Chrome. This is the screen that I see: 
![GARD](https://user-images.githubusercontent.com/48563808/63027896-c19c1f80-be7b-11e9-9311-3173a32a0490.png)

#### Command line
Using the command line version of GARD in HyPhy 2.5.0 with my data set ([data.zip](https://github.com/veg/hyphy/files/3502396/data.zip)), I encounter the following error: 

```console
Error:
Internal error in  _LikelihoodFunction::GradientLocateTheBump: in the Brent loop iteration 1. -1046952.877855302 / -1046883.563137246.
```

I have tried the command line version from Anaconda and building from source on the `master` and `develop` branches. 

[GARD_protein_error.txt](https://github.com/veg/hyphy/files/3502412/GARD_protein_error.txt)
[messages.log](https://github.com/veg/hyphy/files/3502383/messages.log)
[errors.log](https://github.com/veg/hyphy/files/3502384/errors.log)


Thank you again for all of your help!

**Comment by kwade4** [comment]
Hello, 

Thank you for your response! Yes, the error I have is similar to #853, #703, and possibly #995. 

Thank you again for all of your help!
