### ISSUE TITLE
Issues with GARD on current release

### ISSUE THREAD

**Issue by bpiat** [veg/hyphy#995]
Hi,

I have been trying unsuccessfully to use GARD on v2.5.0 and have been getting errors.

When I run '--type Nucleotide' the analysis finishes. The JSON file gets printed out but the 'best-gard' results file is empty so I can't see the results.

When I run '--type Codon' I get the following error during the multi breakpoint analysis:
User-defined function 'gard.GA.initializeModels' needs 4 parameters, but 3 were supplied.

This happens when using either MPI or the new multi-threaded version.

Any insight on how to fix this problem?

**Comment by stevenweaver** [comment]
This issue should be resolved in the latest version of HyPhy, 2.5.5
