### ISSUE TITLE
FEL analysis stopped in Datamonkey server 

### ISSUE THREAD

**Issue by lrjoshi** [veg/hyphy#996]
I have 106 sequences (2100 aa). I am running MEME, FEL, FUBAR and SLAC. All other tests were run successfully but FEL was stopped. I don't know what other information could be useful here. It just says the run was stopped, open a Github issue.

**Comment by srwis** [comment]
Hi, 
Do you have the link to the job log still? Like this one: http://datamonkey.org/gard/5b9a4a2da913185b60116395

That might provide us more information about what went wrong. Additionally, if you can post the file you used I can see if I can replicate the error.

Best,
Sadie

**Comment by lrjoshi** [comment]
Hi Sadie,
Here is the link; https://www.datamonkey.org/fel/5d3afd5e4f280c7d8f201258 

But the run was completed successfully after few attempts. 

Thanks.

**Comment by stevenweaver** [comment]
Thanks @lrjoshi, 

It looks like HyPhy is seg-faulting on your dataset. 

The error message was 

```
Check messages.log details of this run.
/var/spool/torque/mom_priv/jobs/1031517.silverback.SC: line 37: 52528 Done                    ( echo $GENETIC_CODE; echo $FN; echo $TREE_FN; echo "4"; echo $RATE_VARIATION; echo "0.1" )
     52532 Segmentation fault      (core dumped) | $HYPHY LIBPATH=$HYPHY_PATH $FEL > $PROGRESS_FILE
```

Was there anything different about the run that completed successfully? For example, which branches were selected?

Best,
Steven
