### ISSUE TITLE
MEME error  

### ISSUE THREAD

**Issue by Fund-SciEnt** [veg/hyphy#997]
I´m using a dataset (input file) to performed different analyses. GARD or aBSREL ran without errors, however, MEME analysis did not run. An error is mentioned. The following report is showed in the analysis:  

Analysis Description
--------------------
MEME (Mixed Effects Model of Evolution) estimates a site-wise synonymous
(&alpha;) and a two-category mixture of non-synonymous (&beta;-, with
proportion p-, and &beta;+ with proportion [1-p-]) rates, and uses a
likelihood ratio test to determine if &beta;+ > &alpha; at a site. The
estimates aggregate information over a proportion of branches at a site,
so the signal is derived from episodic diversification, which is a
combination of strength of selection [effect size] and the proportion of
the tree affected. A subset of branches can be selected for testing as
well, in which case an additional (nuisance) parameter will be inferred
-- the non-synonymous rate on branches NOT selected for testing.
Multiple partitions within a NEXUS file are also supported for
recombination - aware analysis. 

- __Requirements__: in-frame codon alignment and a phylogenetic tree

- __Citation__: Detecting Individual Sites Subject to Episodic Diversifying Selection.
_PLoS Genet_ 8(7): e1002764.

- __Written by__: Sergei L. Kosakovsky Pond, Steven Weaver

- __Contact Information__: spond@temple.edu

- __Analysis Version__: 2.0.1

####Choose Genetic Code

1. [**Universal**] Universal code. (Genebank transl_table=1).
2. [**Vertebrate mtDNA**] Vertebrate mitochondrial DNA code. (Genebank transl_table=2).
3. [**Yeast mtDNA**] Yeast mitochondrial DNA code. (Genebank transl_table=3).
4. [**Mold/Protozoan mtDNA**] Mold, Protozoan and Coelenterate mitochondrial DNA and the Mycloplasma/Spiroplasma code. (Genebank transl_table=4).
5. [**Invertebrate mtDNA**] Invertebrate mitochondrial DNA code. (Genebank transl_table=5).
6. [**Ciliate Nuclear**] Ciliate, Dasycladacean and Hexamita Nuclear code. (Genebank transl_table=6).
7. [**Echinoderm mtDNA**] Echinoderm mitochondrial DNA code. (Genebank transl_table=9).
8. [**Euplotid Nuclear**] Euplotid Nuclear code. (Genebank transl_table=10).
9. [**Alt. Yeast Nuclear**] Alternative Yeast Nuclear code. (Genebank transl_table=12).
10. [**Ascidian mtDNA**] Ascidian mitochondrial DNA code. (Genebank transl_table=13).
11. [**Flatworm mtDNA**] Flatworm mitochondrial DNA code. (Genebank transl_table=14).
12. [**Blepharisma Nuclear**] Blepharisma Nuclear code. (Genebank transl_table=15).
13. [**Chlorophycean mtDNA**] Chlorophycean Mitochondrial Code (transl_table=16).
14. [**Trematode mtDNA**] Trematode Mitochondrial Code (transl_table=21).
15. [**Scenedesmus obliquus mtDNA**] Scenedesmus obliquus mitochondrial Code (transl_table=22).
16. [**Thraustochytrium mtDNA**] Thraustochytrium Mitochondrial Code (transl_table=23).
17. [**Pterobranchia mtDNA**] Pterobranchia Mitochondrial Code (transl_table=24).
18. [**SR1 and Gracilibacteria**] Candidate Division SR1 and Gracilibacteria Code (transl_table=25).
19. [**Pachysolen Nuclear**] Pachysolen tannophilus Nuclear Code (transl_table=26).

>Please choose an option (or press q to cancel selection):

>Select a coding sequence alignment file (`/home/datamonkey/datamonkey-js-server/production/app/meme/../../.hyphy/res//TemplateBatchFiles/SelectionAnalyses/`) >Loaded a multiple sequence alignment with **13** sequences, **457** codons, and **3** partitions from `/home/datamonkey/datamonkey-js-server/production/app/meme/output/5d3bb0cb90c9e1174891b373`

####Choose the set of branches to test for selection

1. [**All**] Include all branches in the analysis
2. [**Internal**] Include all internal branches in the analysis
3. [**Leaves**] Include all leaf branches in the analysis

>Please choose an option (or press q to cancel selection):
1. [**All**] Include all branches in the analysis
2. [**Internal**] Include all internal branches in the analysis
3. [**Leaves**] Include all leaf branches in the analysis

>Please choose an option (or press q to cancel selection):
>Select the p-value threshold to use when testing for selection (permissible range = [0,1], default value = 0.1): 

### Branches to include in the MEME analysis
Selected 23 branches to include in the MEME analysis: `IGHA_SAIMIRI_CDS, IGHA_CALLITHRIX_CDS, IGHA_SAGUINUS_CDS, Node5, Node3, IGHA_CEBUS_CDS, IGHA_CEBUSALBIFRONS_, Node8, Node2, IGHA_AOTUS_CDS, Node1, IGHA_PITHECIA_CDS, IGHA_PLECTUROCEBUS_C, Node12, IGHA_ALOUATTA_CDS, IGHA_ATELES_CDS, Node16, IGHA_MACACA_CDS, IGHA1_HUMAN_CDS, IGHA2_HUMAN_CDS, Node21, Node19, Node15`
Selected 23 branches to include in the MEME analysis: `IGHA_SAIMIRI_CDS, IGHA_CALLITHRIX_CDS, IGHA_SAGUINUS_CDS, Node5, Node3, IGHA_CEBUS_CDS, IGHA_CEBUSALBIFRONS_, Node8, Node2, IGHA_AOTUS_CDS, Node1, IGHA_PITHECIA_CDS, IGHA_PLECTUROCEBUS_C, Node12, IGHA_ALOUATTA_CDS, IGHA_ATELES_CDS, Node16, IGHA_MACACA_CDS, IGHA1_HUMAN_CDS, IGHA2_HUMAN_CDS, Node21, Node19, Node15`
Selected 23 branches to include in the MEME analysis: `IGHA_SAIMIRI_CDS, IGHA_CALLITHRIX_CDS, IGHA_SAGUINUS_CDS, Node5, Node3, IGHA_CEBUS_CDS, IGHA_CEBUSALBIFRONS_, Node8, Node2, IGHA_AOTUS_CDS, Node1, IGHA_PITHECIA_CDS, IGHA_PLECTUROCEBUS_C, Node12, IGHA_ALOUATTA_CDS, IGHA_ATELES_CDS, Node16, IGHA_MACACA_CDS, IGHA1_HUMAN_CDS, IGHA2_HUMAN_CDS, Node21, Node19, Node15`

### Obtaining branch lengths and nucleotide substitution biases under the nucleotide GTR model
* Log(L) = -5578.37, AIC-c = 11311.41 (77 estimated parameters)

### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
* Log(L) = -5512.51, AIC-c = 11195.46 (84 estimated parameters)
* non-synonymous/synonymous rate ratio for *test* =   0.6108

### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model

[IgA GARD1.txt](https://github.com/veg/hyphy/files/3437789/IgA.GARD1.txt)

What could be the cause of this error?

**Comment by spond** [comment]
Dear @Fund-SciEnt,

I have confirmed the issue which appears to only influence analyses with multiple partitions. Please check here shortly for a resolution. 

Best,
Sergei

**Comment by spond** [comment]
Dear @Fund-SciEnt,

I was able to identify the issue and will work on resolving it. In the meantime, the workaround is to edit the `CHARACTERS` block in the NEXUS file, like I did in the attachment. The edited file will be processed by MEME.

Best,
Sergei

[IgA.GARD1.txt](https://github.com/veg/hyphy/files/3476428/IgA.GARD1.txt)

**Comment by spond** [comment]
Dear @Fund-SciEnt,

I have resolved the underlying issue in the current `dev` branch. You can test it out using

```
git clone https://github.com/veg/hyphy.git hyphy-develop
cd hyphy-develop
git checkout develop
cmake ./
make -j MP
hyphy meme --alignment myfile
```

Best,
Sergei
